-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BIBASE_W_SP_CREATE_PARAM_FILE_DLY("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
  GW_CLOCK_FWD_ENV_IND STRING;
  COMPOSITE_DLY_LOAD_IND STRING;
  PMWorkflowName STRING;
  PMSessionName STRING;
BEGIN
  SELECT 
    TRY_PARSE_JSON(:param_json):GW_CLOCK_FWD_ENV_IND::STRING,
    TRY_PARSE_JSON(:param_json):COMPOSITE_DLY_LOAD_IND::STRING,
    TRY_PARSE_JSON(:param_json):PMWorkflowName::STRING,
    ''s_m_bibase_wr_fnol_dtl_ins''
  INTO
    GW_CLOCK_FWD_ENV_IND,
    COMPOSITE_DLY_LOAD_IND,
    PMWorkflowName,
    PMSessionName;

-- Component SQ_ETL_PRCS_CTRL, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ETL_PRCS_CTRL AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as JOB_START_DT,
$2 as JOB_END_DT,
$3 as COMPOSITE_DAILY_LOAD_DT,
$4 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 



TO_CHAR(JOB_START_DT - INTERVAL ''2 HOURS'' , ''YYYY-MM-DD"BH"HH24:MI:SS.FF6'') AS JOB_START_DTTM,



TO_CHAR(JOB_END_DT, ''YYYY-MM-DD"BH"HH24:MI:SS.FF6'') AS JOB_END_DTTM,



CASE 

WHEN :GW_CLOCK_FWD_ENV_IND = ''Y'' THEN CASE

WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60>24 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)>2) THEN (CAST(JOB_END_dT AS DATE)-2)

 WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60>24 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)=2) THEN (CAST(JOB_END_dT AS DATE)-1)

 WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60>30 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)=1) THEN (CAST(JOB_END_dT AS DATE)-1)

 WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60>24 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)=1 and  EXTRACT(HOUR FROM JOB_END_dT) <=6) THEN (CAST(JOB_END_dT AS DATE)-1)

 WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60<24 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)>1 ) THEN (CAST(JOB_END_dT AS DATE)-1)

 WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60<24 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)<=1 ) and   EXTRACT(HOUR FROM JOB_END_dT) <=6 THEN (CAST(JOB_END_dT AS DATE)) -1

 WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60=24 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)<=1 ) and   EXTRACT(HOUR FROM JOB_END_dT) <=6 THEN (CAST(JOB_END_dT AS DATE))  else (CAST(JOB_END_dT AS DATE)) 

  

END



WHEN :GW_CLOCK_FWD_ENV_IND = ''N'' THEN CASE

WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60>24 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)>2) THEN (CAST(JOB_END_dT AS DATE)-2)

 WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60>24 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)=2) THEN (CAST(JOB_END_dT AS DATE)-1)

 WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60>30 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)=1) THEN (CAST(JOB_END_dT AS DATE)-1)

 WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60>24 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)=1 and  EXTRACT(HOUR FROM JOB_END_dT) <=6) THEN (CAST(JOB_END_dT AS DATE)-1)

 WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60<24 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)>1 ) THEN (CAST(JOB_END_dT AS DATE)-1)

 WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60<24 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)<=1 ) and   EXTRACT(HOUR FROM JOB_END_dT) <=6 THEN (CAST(JOB_END_dT AS DATE)) -1

 WHEN (( (CAST((CAST(job_end_dt AS DATE)- CAST(JOB_START_DT AS DATE)) AS DECIMAL(18,6)) * 60*24)

  + ((EXTRACT(  HOUR FROM job_end_dt) - EXTRACT(  HOUR FROM JOB_START_DT))* 60)

  + ((EXTRACT(MINUTE FROM job_end_dt) - EXTRACT(MINUTE FROM JOB_START_DT))  )

  + ((EXTRACT(SECOND FROM job_end_dt) - EXTRACT(SECOND FROM JOB_START_DT))/60))/60=24 AND CAST(JOB_END_dT AS DATE)-CAST(JOB_START_DT AS DATE)<=1 ) and   EXTRACT(HOUR FROM JOB_END_dT) <=6 THEN (CAST(JOB_END_dT AS DATE))  else (CAST(JOB_END_dT AS DATE)) 

  

END  end  COMPOSITE_DAILY_LOAD_DT 

 

FROM  DB_T_PROD_CORE.ETL_PRCS_CTRL A WHERE PRCS_STAG = ''EDW_DLY'' AND PRCS_STS=''SUCCEEDED''



QUALIFY 

(ROW_NUMBER() OVER(ORDER BY JOB_END_DT DESC)=1 AND :COMPOSITE_DLY_LOAD_IND = ''DLY'') 

OR (:COMPOSITE_DLY_LOAD_IND = ''HISTORY'')



ORDER BY JOB_END_DT DESC
) SRC
)
);


-- Component Exp_pass_src_to_tgt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_pass_src_to_tgt AS
(
SELECT
TO_CHAR ( SQ_ETL_PRCS_CTRL.JOB_START_DT , ''YYYY-MM-DD HH24:MI:SS.US'' ) as O_JOB_START_DT,
TO_CHAR ( SQ_ETL_PRCS_CTRL.JOB_END_DT , ''YYYY-MM-DD HH24:MI:SS.US'' ) as O_JOB_END_DT,
TO_CHAR ( SQ_ETL_PRCS_CTRL.COMPOSITE_DAILY_LOAD_DT , ''YYYY-MM-DD'' ) as O_COMPOSITE_DAILY_LOAD_DT,
SQ_ETL_PRCS_CTRL.source_record_id
FROM
SQ_ETL_PRCS_CTRL
);


-- Component COMPOSITE_PARAM_FIL_DLY, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE COMPOSITE_PARAM_FIL_DLY AS
(
SELECT
Exp_pass_src_to_tgt.O_JOB_START_DT as JOB_START_DTTM,
Exp_pass_src_to_tgt.O_JOB_END_DT as JOB_END_DTTM,
Exp_pass_src_to_tgt.O_COMPOSITE_DAILY_LOAD_DT as COMPOSITE_DAILY_LOAD_DT
FROM
Exp_pass_src_to_tgt
);


-- Component COMPOSITE_PARAM_FIL_DLY, Type EXPORT_DATA Exporting data
;


END; ';