-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BIBASE_WR_MBRSHP_DTL_INS("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
  PMWorkflowName STRING;
  PMSessionName STRING;
BEGIN
  SELECT 
    TRY_PARSE_JSON(:param_json):PMWorkflowName::STRING,
    ''s_m_bibase_wr_mbrshp_Dtl_ins''
  INTO
    PMWorkflowName,
    PMSessionName;

-- Component SQ_WR_MBRSHP_DTL, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_WR_MBRSHP_DTL AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SRC_IDNTFTN_SYS,
$2 as MBRSHP_NUM,
$3 as PLCY_NUM,
$4 as NAME1,
$5 as NAME2,
$6 as ADDR1,
$7 as ADDR2,
$8 as CITY,
$9 as ST_CD,
$10 as ZIP,
$11 as AGNT_NUM,
$12 as EXPN_DT,
$13 as HOME_NUM,
$14 as WORK_NUM,
$15 as CELL_NUM,
$16 as FAX,
$17 as EML,
$18 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 

A.SRC_IDNTFTN_SYS,

A.MBRSHP_NUM,

A.PLCY_NUM,

A.NAME1,

A.NAME2,

A.ADDR1,

A.ADDR2,

CITY,

A.ST_CD,

A.ZIP,

A.AGNT_NUM,

A.EXPN_DT,

/* A.AUTO_IND, */
COALESCE(A.HOME_NUM,CAST(C.HOME_PHONE AS VARCHAR(15))) AS HOME_NUM,

COALESCE(A.WORK_NUM,CAST(C.WORK_PHONE AS VARCHAR(15))) AS WORK_NUM,

COALESCE(A.CELL_NUM,CAST(C.CELL_PHONE AS VARCHAR(15)))  AS CELL_NUM,

COALESCE(A.FAX,C.FAX) AS FAX,

COALESCE(A.EML,CAST(C.EMAIL AS VARCHAR(100))) AS EML

FROM

(SELECT 

SRC_IDNTFTN_SYS,

MBRSHP_NUM,

TRIM(PLCY_NUM) AS PLCY_NUM,

TRIM(NAME1) AS NAME1,

TRIM(NAME2) AS NAME2,

TRIM(ADDR1) AS ADDR1,

TRIM(ADDR2) AS ADDR2,

TRIM(CITY) AS CITY,

TRIM(ST_CD) AS ST_CD,

TRIM(ZIP) AS ZIP,

TRIM(AGNT_NUM) AS AGNT_NUM,

COALESCE(EXPIRATION_DATE, CAST(''1980-01-01'' AS DATE)) AS EXPN_DT,

HOME_NUM,

WORK_NUM,

CELL_NUM,

FAX,

 EML 

/* ,CASE WHEN SUM(AUTO_IND) OVER(PARTITION BY MBRSHP_NUM) >1 THEN ''Y'' ELSE ''N'' END AUTO_IND */
FROM 

(SELECT 

CAST(''DB2'' AS VARCHAR(10)) AS SRC_IDNTFTN_SYS,    

CAST(PL_POL_NUM AS VARCHAR(25)) AS PLCY_NUM,     

CAST(PL_MEMBER_NUM AS VARCHAR(8)) AS MBRSHP_NUM,     

CAST(PL_NAME_1 AS VARCHAR(75)) AS NAME1,     

CAST(PL_NAME_2 AS VARCHAR(75)) AS NAME2,     

CAST(PL_ADDRESS_1 AS VARCHAR(50)) AS ADDR1,     

CAST(PL_ADDRESS_2 AS VARCHAR(50)) AS ADDR2,     

CAST(PL_CITY AS VARCHAR(30)) AS CITY,     

CAST(PL_STATE AS VARCHAR(2)) AS ST_CD,     

CAST(PL_ZIP AS VARCHAR(13)) AS ZIP,     

CAST(PL_AGT_NUM AS VARCHAR(8)) AS AGNT_NUM, 

CAST(PL_TYPE AS VARCHAR(50)) AS PLCY_TYPE,    

CAST(PL_EXP_DATE AS DATE) AS EXPIRATION_DATE,

CAST(NULL AS VARCHAR(15)) AS HOME_NUM,

CAST(NULL AS VARCHAR(15)) AS WORK_NUM,

CAST(NULL AS VARCHAR(15))  AS CELL_NUM,

CAST(NULL AS VARCHAR(15))  AS FAX,

CAST(NULL AS VARCHAR(100)) AS EML

/* ,0 AS AUTO_IND     */
FROM DB_T_STAG_MEMBXREF_PROD.POLICYLIST 

WHERE PL_TYPE  <> ''1'' /* Eliminating all legacy auto policies */ 

UNION ALL 

/* Getting legacy auto DB_T_CORE_DM_PROD.policy and exceed auto DB_T_CORE_DM_PROD.policy */

SELECT    

CAST(''DB2'' AS VARCHAR(10)) AS SRC_IDNTFTN_SYS,

CAST(EX_POL_NUM AS VARCHAR(25)) AS PLCY_NUM,     

CAST(EX_MEMBER_NUM AS VARCHAR(8)) AS MBRSHP_NUM,     

CAST(EX_LONG_NAME AS VARCHAR(75)) AS NAME1,     

CAST(NULL AS VARCHAR(75)) AS NAME2,     

CAST(EX_ADDRESS_1 AS VARCHAR(50)) AS ADDR1,     

CAST(EX_ADDRESS_2 AS VARCHAR(50)) AS ADDR2,     

CAST(EX_CITY AS VARCHAR(30)) AS CITY,     

CAST(EX_STATE AS VARCHAR(2)) AS ST,     

CAST(EX_ZIP AS VARCHAR(13)) AS ZIP,     

CAST(CAST(EX_AGT_NUM AS INTEGER) AS VARCHAR(8)) AS AGNT_NUM,

CAST(''APV'' AS VARCHAR(50)) AS PLCY_TYPE,

CAST(EX_EXPIRATION_DT AS DATE) AS EXPIRATION_DATE,

CAST(NULL AS VARCHAR(15)) AS HOME_NUM,

CAST(NULL AS VARCHAR(15)) AS WORK_NUM,

CAST(NULL AS VARCHAR(15))  AS CELL_NUM,

CAST(NULL AS VARCHAR(15))  AS FAX,

CAST(NULL AS VARCHAR(100)) AS EML 

/* ,CASE WHEN B.POL_NBR IS NOT NULL THEN 1 ELSE  0 END AS AUTO_IND    */
FROM DB_T_CORE_MEMBXREF_PROD.EXCEED_POL_LIST A 

LEFT OUTER JOIN   (SELECT POL_NBR FROM DB_T_STAG_MEMBXREF_PROD.POL_VEH_LIST GROUP BY 1) B

ON A.EX_POL_NUM=B.POL_NBR

UNION  ALL

/* Getting legacy ING policy*/   

SELECT    

CAST(''DB2'' AS VARCHAR(10)) AS SRC_IDNTFTN_SYS,

CAST(POL_ID AS VARCHAR(25)) AS PLCY_NUM,     

CAST(INSURED_MEMBER_NUM AS VARCHAR(8)) AS MBRSHP_NUM,     

CAST(TRIM(INSURED_FIRST_NM) || '' '' || TRIM(INSURED_MID_NM) || '' '' || TRIM(INSURED_LAST_NM) AS VARCHAR(75)) AS NAME1,     

CAST(NULL AS VARCHAR(75)) AS NAME2,     

CAST(INSURED_ADDR_LN_1 AS VARCHAR(50)) AS ADDR1,     

CAST(INSURED_ADDR_LN_2 AS VARCHAR(50)) AS ADDR2,     

CAST(INSURED_CITY_NM AS VARCHAR(30)) AS CITY,     

CAST(INSURED_STATE_CD AS VARCHAR(2)) AS ST,     

CAST(INSURED_ZIP_CD AS VARCHAR(13)) AS ZIP,  

CASE 
  WHEN TRY_TO_NUMBER(AGT_ID) > 0 AND TRY_TO_NUMBER(AGT_ID) < 99999999 
  THEN REGEXP_REPLACE(AGT_ID, ''^0+'', '''') 
  ELSE ''0'' 
END AS AGT_NUM,

CAST(''ING'' AS VARCHAR(50)) AS PLCY_TYPE,

NULL AS EXPIRATION_DATE,

CAST(NULL AS VARCHAR(15)) AS HOME_NUM,

CAST(NULL AS VARCHAR(15)) AS WORK_NUM,

CAST(NULL AS VARCHAR(15))  AS CELL_NUM,

CAST(NULL AS VARCHAR(15))  AS FAX,

CAST(NULL AS VARCHAR(100)) AS EML 

/* ,0 AS AUTO_IND     */
FROM DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST

UNION ALL 

SELECT

CAST(''GW'' AS VARCHAR(10)) AS SRC_IDNTFTN_SYS, 

A.PLCY_NUM,

A.MBRSHP_NUM,

CASE 

WHEN INM.INDIV_PRTY_ID IS NOT NULL THEN COALESCE(TRIM(INM.GVN_NAME)||'' '','''')||COALESCE(TRIM(INM.FMLY_NAME),'''')

WHEN ONM.PRTY_ID IS NOT NULL THEN COALESCE(TRIM(DB_T_PROD_CORE.ORG_NAME)||'' '','''') ELSE '''' END AS NAME1,

CAST(NULL AS VARCHAR(75)) AS NAME2,   

P.ADDR1 AS ADDR1,

P.ADDR2 AS ADDR2,

CITY AS CITY,

P.ST_CD AS ST_CD,

P.ZIP AS ZIP,

REGEXP_REPLACE(IO.INTRNL_ORG_NUM, ''^0+'', '''') AS AGNT_NUM,

A.PLCY_TYPE,

A.EXPIRATION_DATE,

P.HOME_NUM AS HOME_NUM,

P.WORK_NUM AS WORK_NUM,

P.CELL_NUM  AS CELL_NUM,

P.FAX  AS FAX,

P.EML AS EML 

 FROM 

(SELECT 

A.AGMT_ID,

A.HOST_AGMT_NUM AS PLCY_NUM,

CASE 
  WHEN MBRSHP_TYPE_CD = ''CUST'' THEN 
    ''C'' || LPAD(REGEXP_REPLACE(MBRSHP_NUM, ''^0+'', ''''), 7, ''0'')
    
  WHEN MBRSHP_TYPE_CD = ''MBRSHP'' THEN 
    LPAD(REGEXP_REPLACE(MBRSHP_NUM, ''^0+'', ''''), 8, ''0'')
END AS MBRSHP_NUM,

CASE WHEN P.PROD_NAME IN (''COMMERCIAL'', ''PPV'')  THEN ''APV'' ELSE P.PROD_NAME END AS PLCY_TYPE,

CAST(A.AGMT_PLND_EXPN_DTTM AS DATE)  AS EXPIRATION_DATE 

/* CAST(A.MODL_ACTL_END_DTTM AS DATE)  AS EXPIRATION_DATE  */
FROM DB_T_PROD_CORE.AGMT AS A 

JOIN (SELECT MAX(JOB_END_DT) AS FEED_DTTM FROM DB_T_PROD_CORE.ETL_PRCS_CTRL WHERE PRCS_STS = ''SUCCEEDED'' AND PRCS_STAG = ''EDW_DLY'' AND SRC_NM = ''GW'') ECTL ON 1=1  

JOIN DB_T_PROD_CORE.AGMT_PROD  AS AP ON A.AGMT_ID=AP.AGMT_ID AND  ECTL.FEED_DTTM BETWEEN AP.AGMT_PROD_STRT_DTTM AND AP.AGMT_PROD_END_DTTM

JOIN DB_T_PROD_CORE.PROD  P ON AP.PROD_ID=P.PROD_ID AND ECTL.FEED_DTTM BETWEEN P.PROD_STRT_DTTM AND P.PROD_END_DTTM 

LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_MBRSHP  AS AM ON  A.AGMT_ID=AM.AGMT_ID AND ECTL.FEED_DTTM BETWEEN AM.AGMT_MBRSHP_STRT_DTTM AND AM.AGMT_MBRSHP_END_DTTM

LEFT OUTER JOIN DB_T_PROD_CORE.MBRSHP   AS M ON M.MBRSHP_ID=AM.MBRSHP_ID AND CAST(M.EDW_END_DTTM AS DATE) =CAST( ''9999-12-31'' AS DATE)

WHERE MODL_EFF_DTTM <= ECTL.FEED_DTTM  AND A.AGMT_TYPE_CD = ''PPV'' 

AND AP.AGMT_PROD_ROLE_CD=''PLCYTYPE''

QUALIFY ROW_NUMBER() OVER(PARTITION BY HOST_AGMT_NUM ORDER BY MODL_EFF_DTTM DESC, MODL_CRTN_DTTM DESC) = 1 

) AS A

LEFT OUTER JOIN 

(SELECT AGMT_ID, MAX(NIN_PRTY_ID) AS NIN_PRTY_ID, MAX(AGT_PRTY_ID) AS AGT_PRTY_ID FROM (

SELECT AGMT_ID,CASE WHEN PRTY_AGMT_ROLE_CD = ''PLCYPRININS'' THEN PRTY_ID END NIN_PRTY_ID,

CASE WHEN PRTY_AGMT_ROLE_CD = ''PRDA'' THEN PRTY_ID END AGT_PRTY_ID

FROM DB_T_PROD_CORE.PRTY_AGMT A 

JOIN (SELECT MAX(JOB_END_DT) AS FEED_DTTM FROM DB_T_PROD_CORE.ETL_PRCS_CTRL WHERE PRCS_STS = ''SUCCEEDED'' AND PRCS_STAG = ''EDW_DLY'' AND SRC_NM = ''GW'') ECTL ON 1=1  

WHERE PRTY_AGMT_ROLE_CD IN  (''PLCYPRININS'',''PRDA'') AND ECTL.FEED_DTTM BETWEEN PRTY_AGMT_STRT_DTTM AND PRTY_AGMT_END_DTTM

QUALIFY ROW_NUMBER() OVER(PARTITION BY AGMT_ID,PRTY_ID ORDER BY PRTY_AGMT_STRT_DTTM DESC, TRANS_STRT_DTTM DESC) = 1 ) AS T GROUP BY AGMT_ID ) PA

ON A.AGMT_ID = PA.AGMT_ID 

LEFT OUTER JOIN 

(SELECT PRTY_ID,

MAX(ADDR1) AS ADDR1,

MAX(ADDR2) AS ADDR2,

MAX(CITY) AS CITY,

MAX(ST_CD) AS ST_CD,

MAX(ZIP) AS ZIP,

MAX(
  CASE 
    WHEN LENGTH(HOME_NUM) = 10 AND HOME_NUM = LOWER(HOME_NUM) AND HOME_NUM = UPPER(HOME_NUM)
      THEN SUBSTR(HOME_NUM, 1, 3) || ''-'' || SUBSTR(HOME_NUM, 4, 3) || ''-'' || SUBSTR(HOME_NUM, 7, 4)
    ELSE HOME_NUM 
  END
) AS HOME_NUM,

MAX(
  CASE 
    WHEN LENGTH(CELL_NUM) = 10 AND CELL_NUM = LOWER(CELL_NUM) AND CELL_NUM = UPPER(CELL_NUM)
      THEN SUBSTR(CELL_NUM, 1, 3) || ''-'' || SUBSTR(CELL_NUM, 4, 3) || ''-'' || SUBSTR(CELL_NUM, 7, 4)
    ELSE CELL_NUM 
  END
) AS CELL_NUM,

MAX(
  CASE 
    WHEN LENGTH(WORK_NUM) = 10 AND WORK_NUM = LOWER(WORK_NUM) AND WORK_NUM = UPPER(WORK_NUM)
      THEN SUBSTR(WORK_NUM, 1, 3) || ''-'' || SUBSTR(WORK_NUM, 4, 3) || ''-'' || SUBSTR(WORK_NUM, 7, 4)
    ELSE WORK_NUM 
  END
) AS WORK_NUM,

MAX(
  CASE 
    WHEN LENGTH(FAX) = 10 AND FAX = LOWER(FAX) AND FAX = UPPER(FAX)
      THEN SUBSTR(FAX, 1, 3) || ''-'' || SUBSTR(FAX, 4, 3) || ''-'' || SUBSTR(FAX, 7, 4)
    ELSE FAX 
  END
) AS FAX,

MAX(EML) AS EML 

FROM (

SELECT 

PA.PRTY_ID,

CASE WHEN L.ADDR_SBTYPE_CD = ''STADR'' THEN SA.ADDR_LN_1_TXT END AS ADDR1,

CASE WHEN L.ADDR_SBTYPE_CD = ''STADR'' THEN SA.ADDR_LN_2_TXT END AS ADDR2,

CASE WHEN L.ADDR_SBTYPE_CD = ''STADR'' THEN C.GEOGRCL_AREA_NAME END AS CITY,

CASE WHEN L.ADDR_SBTYPE_CD = ''STADR'' THEN T.GEOGRCL_AREA_SHRT_NAME END AS ST_CD,

CASE WHEN L.ADDR_SBTYPE_CD = ''STADR'' THEN PC.POSTL_CD_NUM END AS ZIP,

COALESCE(CASE WHEN PA.PRTY_ADDR_USGE_TYPE_CD = ''PREMAIL'' THEN TRIM(EA.ELCTRNC_ADDR_TXT) END,CASE WHEN PA.PRTY_ADDR_USGE_TYPE_CD = ''SCEMAIL'' THEN TRIM(EA.ELCTRNC_ADDR_TXT) END) AS EML,

CASE WHEN PA.PRTY_ADDR_USGE_TYPE_CD = ''HOMEPHN'' THEN CAST(DB_T_PROD_CORE.TLPHN_NUM AS VARCHAR(15)) END AS HOME_NUM,

CASE WHEN PA.PRTY_ADDR_USGE_TYPE_CD = ''CELLPHN'' THEN CAST(DB_T_PROD_CORE.TLPHN_NUM AS VARCHAR(15)) END AS CELL_NUM,

CASE WHEN PA.PRTY_ADDR_USGE_TYPE_CD = ''WORKPHN'' THEN CAST(DB_T_PROD_CORE.TLPHN_NUM AS VARCHAR(15)) END AS WORK_NUM,

CASE WHEN PA.PRTY_ADDR_USGE_TYPE_CD = ''FAXNBR'' THEN CAST(DB_T_PROD_CORE.TLPHN_NUM AS VARCHAR(15)) END AS FAX 

FROM DB_T_PROD_CORE.PRTY_ADDR AS PA 

JOIN (SELECT MAX(JOB_END_DT) AS FEED_DTTM FROM DB_T_PROD_CORE.ETL_PRCS_CTRL WHERE PRCS_STS = ''SUCCEEDED'' AND PRCS_STAG = ''EDW_DLY'' AND SRC_NM = ''GW'') ECTL ON 1=1 

JOIN  DB_T_PROD_CORE.LOCTR AS L ON PA.LOC_ID = L.LOCTR_ID AND L.ADDR_SBTYPE_CD IN (''STADR'',''EMLADR'',''TELNBR'') 

LEFT OUTER JOIN DB_T_PROD_CORE.STREET_ADDR AS SA ON  PA.LOC_ID = SA.STREET_ADDR_ID AND L.ADDR_SBTYPE_CD = ''STADR'' AND CAST(SA.EDW_END_DTTM AS DATE) = CAST(''9999-12-31'' AS DATE) 

LEFT OUTER JOIN CITY AS C ON  SA.CITY_ID = C.CITY_ID AND CAST(C.EDW_END_DTTM AS DATE) = CAST(''9999-12-31'' AS DATE) 

LEFT OUTER JOIN DB_T_PROD_CORE.TERR AS T ON  SA.TERR_ID = T.TERR_ID AND CAST(T.EDW_END_DTTM AS DATE) = CAST(''9999-12-31'' AS DATE) 

LEFT OUTER JOIN DB_T_PROD_CORE.POSTL_CD AS PC ON  SA.POSTL_CD_ID = PC.POSTL_CD_ID AND CAST(PC.EDW_END_DTTM AS DATE) = CAST(''9999-12-31'' AS DATE) 

LEFT OUTER JOIN DB_T_PROD_CORE.ELCTRNC_ADDR AS EA ON PA.LOC_ID = EA.ELCTRNC_ADDR_ID AND L.ADDR_SBTYPE_CD = ''EMLADR'' 

LEFT OUTER JOIN DB_T_PROD_CORE.TLPHN_NUM AS TN ON PA.LOC_ID = TN.TLPHN_NUM_ID AND L.ADDR_SBTYPE_CD = ''TELNBR'' AND CAST(TN.EDW_END_DTTM AS DATE) = CAST(''9999-12-31'' AS DATE)

WHERE PA.PRTY_ID <> 9999 AND PA.PRTY_ADDR_STRT_DTTM<=ECTL.FEED_DTTM 

QUALIFY ROW_NUMBER() OVER(PARTITION BY PA.PRTY_ID,PRTY_ADDR_USGE_TYPE_CD  ORDER BY PA.PRTY_ADDR_STRT_DTTM DESC, PA.TRANS_STRT_DTTM DESC) = 1 /* EIM- 15713 Removed LOC_ID from Partition by clause and added ''DESC'' to TRANS_STRT_DTTM order by column */
) AS T GROUP BY PRTY_ID ) AS P

ON PA.NIN_PRTY_ID = P.PRTY_ID

LEFT OUTER JOIN DB_T_PROD_CORE.INDIV_NAME AS INM ON PA.NIN_PRTY_ID = INM.INDIV_PRTY_ID AND CAST(INM.EDW_END_DTTM AS DATE) = CAST(''9999-12-31'' AS DATE)

LEFT OUTER JOIN DB_T_PROD_CORE.ORG_NAME AS ONM ON PA.NIN_PRTY_ID = ONM.PRTY_ID AND CAST(ONM.EDW_END_DTTM AS DATE) = CAST(''9999-12-31'' AS DATE)

LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG AS IO ON PA.AGT_PRTY_ID = IO.INTRNL_ORG_PRTY_ID AND CAST(IO.EDW_END_DTTM AS DATE) =CAST( ''9999-12-31'' AS DATE) ) PM

QUALIFY ROW_NUMBER() OVER(PARTITION BY MBRSHP_NUM ORDER BY CASE PLCY_TYPE WHEN ''APV'' THEN 1 WHEN ''ING'' THEN 3 ELSE 2 END ASC, EXPN_DT DESC, PLCY_NUM DESC, SRC_IDNTFTN_SYS DESC ) = 1

) AS A

LEFT OUTER JOIN 

DB_T_STAG_MEMBXREF_PROD.CLIENT_INFO AS C

ON A.MBRSHP_NUM = C.MEMBER_NBR
) SRC
)
);


-- Component exp_pass_to_target, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_to_target AS
(
SELECT
SQ_WR_MBRSHP_DTL.SRC_IDNTFTN_SYS as SRC_IDNTFTN_SYS,
SQ_WR_MBRSHP_DTL.MBRSHP_NUM as MBRSHP_NUM,
SQ_WR_MBRSHP_DTL.PLCY_NUM as PLCY_NUM,
SQ_WR_MBRSHP_DTL.NAME1 as NAME1,
SQ_WR_MBRSHP_DTL.NAME2 as NAME2,
SQ_WR_MBRSHP_DTL.ADDR1 as ADDR1,
SQ_WR_MBRSHP_DTL.ADDR2 as ADDR2,
SQ_WR_MBRSHP_DTL.CITY as CITY,
SQ_WR_MBRSHP_DTL.ST_CD as ST_CD,
SQ_WR_MBRSHP_DTL.ZIP as ZIP,
SQ_WR_MBRSHP_DTL.AGNT_NUM as AGNT_NUM,
SQ_WR_MBRSHP_DTL.EXPN_DT as EXPN_DT,
SQ_WR_MBRSHP_DTL.HOME_NUM as HOME_NUM,
SQ_WR_MBRSHP_DTL.WORK_NUM as WORK_NUM,
SQ_WR_MBRSHP_DTL.CELL_NUM as CELL_NUM,
SQ_WR_MBRSHP_DTL.FAX as FAX,
SQ_WR_MBRSHP_DTL.EML as EML,
SQ_WR_MBRSHP_DTL.source_record_id
FROM
SQ_WR_MBRSHP_DTL
);


-- Component Tgt_WR_MBRSHP_DTL, Type TARGET 
INSERT INTO DB_V_PROD_PRES.WR_MBRSHP_DTL
(
SRC_IDNTFTN_SYS,
MBRSHP_NUM,
PLCY_NUM,
NAME1,
NAME2,
ADDR1,
ADDR2,
CITY,
ST_CD,
ZIP,
AGNT_NUM,
EXPN_DT,
HOME_NUM,
WORK_NUM,
CELL_NUM,
FAX,
EML
)
SELECT
exp_pass_to_target.SRC_IDNTFTN_SYS as SRC_IDNTFTN_SYS,
exp_pass_to_target.MBRSHP_NUM as MBRSHP_NUM,
exp_pass_to_target.PLCY_NUM as PLCY_NUM,
exp_pass_to_target.NAME1 as NAME1,
exp_pass_to_target.NAME2 as NAME2,
exp_pass_to_target.ADDR1 as ADDR1,
exp_pass_to_target.ADDR2 as ADDR2,
exp_pass_to_target.CITY as CITY,
exp_pass_to_target.ST_CD as ST_CD,
exp_pass_to_target.ZIP as ZIP,
exp_pass_to_target.AGNT_NUM as AGNT_NUM,
exp_pass_to_target.EXPN_DT as EXPN_DT,
exp_pass_to_target.HOME_NUM as HOME_NUM,
exp_pass_to_target.WORK_NUM as WORK_NUM,
exp_pass_to_target.CELL_NUM as CELL_NUM,
exp_pass_to_target.FAX as FAX,
exp_pass_to_target.EML as EML
FROM
exp_pass_to_target;


END; ';