-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BIBASE_WR_PLCY_CLM_LIST_INS("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
  PMWorkflowName STRING;
  PMSessionName STRING;
BEGIN
  SELECT 
    TRY_PARSE_JSON(:param_json):PMWorkflowName::STRING,
    ''s_m_bibase_wr_plcy_clm_list_ins''
  INTO
    PMWorkflowName,
    PMSessionName;

-- Component SQ_WR_PLCY_CLM_LIST, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_WR_PLCY_CLM_LIST AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SRC_IDNTFTN_SYS,
$2 as MBRSHP_NUM,
$3 as PLCY_NUM,
$4 as CAUS_CD,
$5 as CAUS_DESC,
$6 as LOB_CD,
$7 as CLM_NUM,
$8 as CSR_CLM_NUM,
$9 as CLM_LOSS_DT,
$10 as VEH_VIN_CD,
$11 as TOT_LOSS_AMT,
$12 as VEH_MAKE_CD,
$13 as VEH_MODL_DESC,
$14 as VEH_MODL_YR,
$15 as RTD_DRVR_FRST_NAME,
$16 as RTD_DRVR_LAST_NAME,
$17 as RTD_DRVR_BIRTH_DT,
$18 as RTD_DRVR_AGE,
$19 as RTD_DRVR_CLNT_ID,
$20 as UNIT_REF_NBR,
$21 as CLM_STS_DESC,
$22 as PLCY_INFR_IND,
$23 as PLCY_STS_CD,
$24 as PLCY_STS_DESC,
$25 as CMPRN_DEDCTB,
$26 as LAST_YR_CLM_CNT,
$27 as LAST_YR_CLM_AMT,
$28 as LAST_3YR_CLM_CNT,
$29 as LAST_3YR_CLM_AMT,
$30 as LAST_5YR_CLM_CNT,
$31 as LAST_5YR_CLM_AMT,
$32 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT * FROM (

SELECT CAST( ''GW'' AS VARCHAR(10)) AS SRC_IDNTFTN_SYS,E. * FROM (     

SELECT 

CAST(A.MBRSHP_NUM AS VARCHAR(8)) MBRSHP_NUM

,CAST(A.POL_NBR AS VARCHAR(25))AS PLCY_NUM

,CAST(C.PERIL_TYPE_CD AS VARCHAR(3)) CAUS_CD

,CAST(initcap(C.PERIL_TYPE_DESC) AS VARCHAR(100)) CAUS_DESC

,CAST(A.INSRNC_LOB_TYPE_CD AS VARCHAR(30)) AS LOB_CD

,C.CLM_NUM CLM_NUM

,C.CLM_NUM CSR_CLM_NUM

,TO_CHAR(DATE(C.CLM_LOSS_DT), ''YYYY-MM-DD'') CLM_LOSS_DT

,CAST(DRV_NAME.VEH_VIN AS VARCHAR(50)) VEH_VIN_CD

,CAST(DB_T_PROD_CORE.CLM_AMT AS DECIMAL(15,2)) TOT_LOSS_AMT

,CAST(DRV_NAME.VEH_MAKE AS VARCHAR(10)) VEH_MAKE_CD

,CAST(DRV_NAME.VEH_MODEL AS VARCHAR(100))VEH_MODL_DESC 

,CAST(DRV_NAME.VEH_YR AS INTEGER)  VEH_MODL_YR

,CAST(DRV_NAME.GVN_NAME AS VARCHAr(30)) RTD_DRVR_FRST_NAME

,CAST(DRV_NAME.FMLY_NAME AS VARCHAR(30)) RTD_DRVR_LAST_NAME

,DRV_NAME.BIRTH_DT RTD_DRVR_BIRTH_DT

,CAST(EXTRACT(YEAR FROM CLM_LOSS_DT)-EXTRACT(YEAR FROM  DRV_NAME.BIRTH_DT) AS INTEGER) RTD_DRVR_AGE

,CAST(DRV_NAME.INDIV_FULL_NAME AS VARCHAR(50)) RTD_DRVR_CLNT_ID 

,CAST(DRV_NAME.VEH_VIN AS VARCHAR(50)) UNIT_REF_NBR 

,CAST(C.CLM_STS_TYPE_CD AS VARCHAR(10)) CLM_STS_DESC

,CASE WHEN A.AGMT_STS_CD IN (''ACTIVE'',''CNFRMD'',''INFORCE'',''SCHEDULED'') THEN ''I'' ELSE ''O'' END  PLCY_INFR_IND

,CASE WHEN A.AGMT_STS_CD IN (''ACTIVE'',''CNFRMD'',''INFORCE'',''SCHEDULED'') THEN ''1'' ELSE ''5'' END  PLCY_STS_CD

,COALESCE(CAST(CASE WHEN (A.AGMT_STS_CD IN (''INFORCE'')) then ''INFORCE'' ELSE A.AGMT_STS_DESC end AS VARCHAR(30)),''EXPIRED'') AS  PLCY_STS_DESC

,COALESCE(CAST(CMPRN_CVGE_DED AS INTEGER),0)CMPRN_DEDCTB 

,COALESCE(LAST_YR_CLM_CNT,0) LAST_YR_CLM_CNT

,COALESCE(LAST_YR_CLM_AMT,0.00) LAST_YR_CLM_AMT

,COALESCE(LAST_3YR_CLM_CNT,0)LAST_3YR_CLM_CNT

,COALESCE(LAST_3YR_CLM_AMT,0.00)LAST_3YR_CLM_AMT

,COALESCE(LAST_5YR_CLM_CNT,0) LAST_5YR_CLM_CNT

,COALESCE(LAST_5YR_CLM_AMT,0.00)LAST_5YR_CLM_AMT

FROM (SELECT C.CLM_ID, C.CLM_NUM,AC.AGMT_ID,CLM_DT.CLM_DTTM CLM_LOSS_DT, DB_T_PROD_CORE.CLM_AMT,CLM_STS_TYPE_CD,

CP.PERIL_TYPE_CD ,PERIL_TYPE_DESC, HOST_AGMT_NUM

FROM DB_T_PROD_CORE.CLM C 

JOIN (SELECT MAX(JOB_END_DT) AS FEED_DTTM FROM DB_T_PROD_CORE.ETL_PRCS_CTRL WHERE PRCS_STS = ''SUCCEEDED'' AND PRCS_STAG = ''EDW_DLY'' AND SRC_NM = ''GW'') ECTL ON 1=1

JOIN DB_T_PROD_CORE.AGMT_CLM AC 

ON C.CLM_ID=AC.CLM_ID /* AND ECTL.FEED_DTTM BETWEEN AC.AGMT_CLM_RLTNSHP_STRT_DTTM AND AC.AGMT_CLM_RLTNSHP_END_DTTM */
JOIN DB_T_PROD_CORE.AGMT AG ON AC.AGMT_ID=AG.AGMT_ID AND AGMT_TYPE_CD=''PPV''

JOIN  DB_T_PROD_CORE.CLM_DT CLM_DT ON CLM_DT.CLM_ID=C.CLM_ID AND CLM_DT.CLM_DT_TYPE_CD=''LOSS'' 

AND CAST(CLM_DT.EDW_END_DTTM AS DATE) =CAST(''9999-12-31'' AS DATE)

LEFT OUTER JOIN (

SELECT	CLM_ID, SUM(TOTAL_INCURRED) CLM_AMT 

FROM	(  

SELECT	 A.CLM_ID  ,  SUM (  

CASE	    

	WHEN	(CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD = ''PYMNT''                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''PDL'')                    

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')                                                                                   

	AND	      CLMLINEITM.LNITM_CTGY_TYPE_CD IN (  ''LOSS'',''DED'',''DEDRFND'',

		''FRMRDED'') ) THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)      

ELSE	     0  

END	      )  AS LOSS_PMT_AMT   ,SUM (  

CASE	    

	WHEN	(CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD = ''PYMNT''                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''PDL'')                    

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')                                                                   

	AND	     CLMTRANS.DOES_NOT_ERODE_RSERV_IND=''F''                                     ) THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)      

ELSE	     0  

END	      )  AS LOSS_PMT_ERODING_AMT     ,(SUM (  

CASE	    

	WHEN	( CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD=''RESRV'' )                  

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD=''PDL''                   

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD =''LOSS''                                     THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)   

ELSE	     0   

END	      ) )-LOSS_PMT_ERODING_AMT AS RSERV_AMT        ,(SUM(  

CASE	    

	WHEN	(CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD = ''PYMNT''                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''EXPNS'')                   

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''EXPNS'')                   

	AND	      CLMLINEITM.LNITM_CTGY_TYPE_CD IN (   ''SALVEXP'',''SUBROEXP'',

		''IAENG'',''LEGCOV'',''LEGDEF'',''RPRTS'' )                   )                  THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)   

ELSE	     0   

END	      ) )EXPENSE_PAID    ,SUM(   

CASE	    

	WHEN	( CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''                    

	AND	      CLMTRANS.RCVRY_CTGY_TYPE_CD IN (''SUBRO'' , ''SALVAGE'')                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''EXPNS'')                   

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''EXPNS'')                   

	AND	      CLMLINEITM.LNITM_CTGY_TYPE_CD IN ( ''RCVRY'',''SALVEXP'',

		''SUBROEXP'' ,''IAENG'',''LEGCOV'',''LEGDEF'',''RPRTS'' )                  )THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)   

ELSE	     0   

END	      )+   SUM(   

CASE	    

	WHEN	( CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''                    

	AND	      CLMTRANS.RCVRY_CTGY_TYPE_CD IN (''SUBRO'' , ''SALVAGE'')                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''PDL'')                   

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')                   

	AND	      CLMLINEITM.LNITM_CTGY_TYPE_CD IN ( ''RCVRY'',''SALVEXP'',

		''SUBROEXP'' )                  )THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)   

ELSE	     0   

END	      )+SUM(   

CASE	    

	WHEN	( CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''                    

	AND	      CLMTRANS.RCVRY_CTGY_TYPE_CD IN (''CREXP'')                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''EXPNS'')                   

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''EXPNS'')                   

	AND	      CLMLINEITM.LNITM_CTGY_TYPE_CD IN ( ''RCVRY'',''SALVEXP'',

		''SUBROEXP'' ,''IAENG'',''LEGCOV'',''LEGDEF'',''RPRTS'' )                  )THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)   

ELSE	     0   

END	      )+SUM(   

CASE	    

	WHEN	( CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''                    

	AND	      CLMTRANS.RCVRY_CTGY_TYPE_CD IN (''CRLOSS'')                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''PDL'')                   

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')                                     )THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)   

ELSE	     0   

END	      )RECOVERY,(LOSS_PMT_AMT+RSERV_AMT+EXPENSE_PAID-RECOVERY) TOTAL_INCURRED       

FROM	DB_T_PROD_CORE.CLM_EXPSR A JOIN DB_T_PROD_CORE.CLM B 

	ON	A.CLM_ID=B.CLM_ID JOIN DB_T_PROD_CORE.CLM_EXPSR_TRANS CLMTRANS   

	ON	A.CLM_EXPSR_ID=CLMTRANS.CLM_EXPSR_ID JOIN DB_T_PROD_CORE.CLM_EXPSR_TRANS_LNITM CLMLINEITM 

	ON	CLMTRANS.CLM_EXPSR_TRANS_ID=CLMLINEITM.CLM_EXPSR_TRANS_ID  

WHERE	CAST(A.EDW_END_DTTM AS DATE)=''9999-12-31'' 

	AND	 CAST(B.EDW_END_DTTM AS DATE)=''9999-12-31''  

	AND	 CAST(CLMTRANS.EDW_END_DTTM AS DATE)=''9999-12-31'' 

	AND	 CAST(CLMLINEITM.EDW_END_DTTM AS DATE)=''9999-12-31''  

	

GROUP	BY 1)a group by 1) CA

ON CA.CLM_ID=C.CLM_ID 

 LEFT OUTER JOIN DB_T_PROD_CORE.CLM_STS CST ON CST.CLM_ID=C.CLM_ID AND CAST(CST.EDW_END_DTTM AS DATE)=CAST(''9999-12-31'' AS DATE)

LEFT OUTER JOIN DB_T_PROD_CORE.CLM_PERIL CP ON C.CLM_ID=CP.CLM_ID AND CAST(CP.EDW_END_DTTM AS DATE) =CAST(''9999-12-31'' AS DATE)

LEFT OUTER JOIN DB_T_PROD_CORE.PERIL_TYPE PT ON CP.PERIL_TYPE_CD=PT.PERIL_TYPE_CD AND  cast(PT.EDW_END_DTTM AS DATE) =CAST(''9999-12-31'' AS DATE)

WHERE   C.CLM_STRT_DTTM <=ECTL.FEED_DTTM 

QUALIFY ROW_NUMBER() OVER(PARTITION BY c.clm_num,CLM_LOSS_DT ORDER BY C.CLM_END_DTTM DESC, C.EDW_END_DTTM DESC) = 1)C

JOIN (SELECT 

A.AGMT_ID, 

CASE
  WHEN MBRSHP_TYPE_CD = ''CUST'' THEN 
    ''C'' || SUBSTR(CAST(CAST(MBRSHP_NUM AS INTEGER) AS VARCHAR), 2)
  WHEN MBRSHP_TYPE_CD = ''MBRSHP'' THEN
    CAST(CAST(MBRSHP_NUM AS INTEGER) AS VARCHAR)
END AS MBRSHP_NUM,

A.HOST_AGMT_NUM AS POL_NBR,

A.MODL_EFF_DTTM AS EFF_DT,

A.MODL_ACTL_END_DTTM AS EXPN_DT,

D.INSRNC_LOB_TYPE_CD AS INSRNC_LOB_TYPE_CD,

AS1.AGMT_STS_CD AGMT_STS_CD,AS2.AGMT_STS_DESC AGMT_STS_DESC,

CASE WHEN a.MODL_EFF_DTTM > a.MODL_CRTN_DTTM THEN a.MODL_EFF_DTTM 

ELSE a.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM

FROM  DB_T_PROD_CORE.AGMT AS A 

JOIN (SELECT MAX(JOB_END_DT) AS FEED_DTTM FROM DB_T_PROD_CORE.ETL_PRCS_CTRL WHERE PRCS_STS = ''SUCCEEDED'' AND PRCS_STAG = ''EDW_DLY'' AND SRC_NM = ''GW'') ECTL ON 1=1 

JOIN  DB_T_PROD_CORE.AGMT TRM 

ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM 

AND A.AGMT_TYPE_CD=''PPV''

and    TRM.AGMT_TYPE_CD=''POLTRM''   /*  commented as part of ticket EIM-18917 - AND CAST(CAST(FEED_DTTM AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' BETWEEN trm.AGMT_EFF_DTTM AND trm.AGMT_PLND_EXPN_DTTM  */
JOIN DB_T_PROD_CORE.AGMT_STS  AS AS1  ON  TRM.AGMT_ID=AS1.AGMT_ID AND AS1.AGMT_STS_STRT_DTTM <= CAST(CAST(FEED_DTTM AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

JOIN DB_T_PROD_CORE.AGMT_PROD AP ON A.AGMT_ID=AP.AGMT_ID 

JOIN DB_T_PROD_CORE.PROD P ON AP.PROD_ID=P.PROD_ID 

LEFT OUTER JOIN DB_T_PROD_CORE.INSRNC_LOB_TYPE D ON D.INSRNC_LOB_TYPE_CD=P.INSRNC_LOB_TYPE_CD

LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_STS_TYPE  AS AS2  ON  AS1.AGMT_STS_CD=AS2.AGMT_STS_CD 

LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_MBRSHP  AS AM ON  A.AGMT_ID=AM.AGMT_ID AND AM.AGMT_MBRSHP_STRT_DTTM <=ECTL.FEED_DTTM  AND AM.AGMT_MBRSHP_END_DTTM>=ECTL.FEED_DTTM 

LEFT OUTER JOIN DB_T_PROD_CORE.MBRSHP   AS M ON M.MBRSHP_ID=AM.MBRSHP_ID

WHERE  p.INSRNC_LOB_TYPE_CD=''PA'' 

AND AP.AGMT_PROD_ROLE_CD=''PLCYTYPE''

and NEW_AGMT_EFF_DTTM <= CAST(CAST(FEED_DTTM AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond''

AND AS1.AGMT_STS_CD <> ''CNFRMDDT'' 

QUALIFY ROW_NUMBER() OVER(PARTITION BY POL_NBR ORDER BY A.MODL_CRTN_DTTM DESC,A.MODL_EFF_DTTM DESC,AS1.AGMT_STS_STRT_DTTM DESC)=1)A

ON A.POL_NBR=C.HOST_AGMT_NUM



LEFT OUTER JOIN (

/*eim-17800*/

select distinct host_agmt_num, clm.clm_num, indivname.indiv_full_name, mv.motr_veh_ser_num VEH_VIN,GVN_NAME,FMLY_NAME,BIRTH_DT,

CASE WHEN  MV.MFG_YR_NUM = ''UNK'' THEN NULL ELSE CAST( MV.MFG_YR_NUM AS INTEGER) END AS VEH_YR,MV.PRTY_ASSET_ID

,mv.veh_mfgr_name VEH_MAKE, mv.modl_name VEH_MODEL,CLM.CLM_ID/* -,pii.* */
from DB_T_PROD_CORE.CLM CLM

join DB_T_PROD_CORE.CLM_EXPSR ce on ce.clm_id = clm.clm_id and ce.edw_end_dttm = ''9999-12-31 23:59:59.999999''

join DB_T_PROD_CORE.prty_clm pc on pc.clm_id = clm.clm_id and pc.edw_end_dttm = ''9999-12-31 23:59:59.999999''

join DB_T_PROD_CORE.CLM_INSRBL_INT cii on cii.clm_id = clm.clm_id and ce.insrbl_int_id = cii.insrbl_int_id and cii.edw_end_dttm = ''9999-12-31 23:59:59.999999''

join DB_T_PROD_CORE.INSRBL_INT ii on ii.insrbl_int_id = cii.insrbl_int_id /* and ii.edw_end_dttm = ''9999-12-31 23:59:59.999999'' */
left join DB_T_PROD_CORE.prty_insrbl_int pii on pii.insrbl_int_id = ii.insrbl_int_id and pc.prty_id = pii.prty_id 

    and pii.prty_clm_role_cd like ''%DRV%'' and pii.edw_end_dttm = ''9999-12-31 23:59:59.999999''

left join DB_T_PROD_CORE.indiv indiv on indiv.indiv_prty_id = pii.prty_id and indiv.edw_end_dttm = ''9999-12-31 23:59:59.999999''

left join DB_T_PROD_CORE.indiv_name indivname on indivname.indiv_prty_id = indiv.indiv_prty_id and indivname.edw_end_dttm = ''9999-12-31 23:59:59.999999''

join DB_T_PROD_CORE.AGMT_CLM ac on ac.clm_id = clm.clm_id and ac.edw_end_dttm = ''9999-12-31 23:59:59.999999''

join DB_T_PROD_CORE.AGMT AGMT on agmt.agmt_id = ac.agmt_id and agmt.edw_end_dttm = ''9999-12-31 23:59:59.999999''

join DB_T_PROD_CORE.MOTR_VEH mv on mv.prty_asset_id = ii.prty_asset_id and mv.edw_end_dttm = ''9999-12-31 23:59:59.999999''

left join DB_T_PROD_CORE.prty_to_prty_asset ptpa on ptpa.prty_asset_id = ii.prty_asset_id and ptpa.edw_end_dttm = ''9999-12-31 23:59:59.999999''

where clm.edw_end_dttm = ''9999-12-31 23:59:59.999999''

and ce.LOSS_PRTY_TYPE_CD <> ''THRDPRTY''

QUALIFY ROW_NUMBER() OVER (PARTITION BY clm.CLM_ID ORDER BY ptpa.TRANS_STRT_DTTM DESC, ii.EDW_END_DTTM DESC,  indiv.TRANS_STRT_DTTM DESC, indiv.EDW_END_DTTM DESC,pii.PRTY_ID )=1





/*eim-17800*/

)DRV_NAME

ON DRV_NAME.CLM_ID=C.CLM_ID

LEFT OUTER JOIN (

/*SEL   CII.CLM_ID CLM_ID, II.PRTY_ASSET_ID PRTY_ASSET_ID,

MV.VEH_MFGR_NAME VEH_MAKE, MV.MODL_NAME VEH_MODEL,

MV.MOTR_VEH_SER_NUM VEH_VIN ,  

CASE WHEN  MV.MFG_YR_NUM = ''UNK'' THEN NULL ELSE CAST( MV.MFG_YR_NUM AS INTEGER) END AS VEH_YR

FROM DB_T_PROD_CORE.CLM_INSRBL_INT CII 

JOIN (SELECT MAX(JOB_END_DT) AS FEED_DTTM FROM DB_T_PROD_CORE.ETL_PRCS_CTRL WHERE PRCS_STS = ''SUCCEEDED'' AND PRCS_STAG = ''EDW_DLY'' AND SRC_NM = ''GW'') ECTL ON 1=1 

LEFT OUTER JOIN DB_T_PROD_CORE.INSRBL_INT  II

ON CII.INSRBL_INT_ID=II.INSRBL_INT_ID

AND CII.CLM_INSRBL_INT_STRT_DTTM<=ECTL.FEED_DTTM

AND CII.CLM_INSRBL_INT_END_DTTM>=ECTL.FEED_DTTM

LEFT OUTER JOIN DB_T_PROD_CORE.MOTR_VEH MV

ON MV.PRTY_ASSET_ID= II.PRTY_ASSET_ID 

WHERE II.INSRBL_INT_CTGY_CD=''ASSET'' 

AND ECTL.FEED_DTTM BETWEEN CLM_INSRBL_INT_STRT_DTTM AND CLM_INSRBL_INT_END_DTTM

QUALIFY ROW_NUMBER() OVER (PARTITION BY CII.CLM_ID ORDER BY CII.CLM_INSRBL_INT_END_DTTM DESC, MV.EDW_END_DTTM DESC, MV.EDW_STRT_DTTM DESC )=1

) VEH ON C.CLM_ID=VEH.CLM_ID

LEFT OUTER JOIN (*/

SELECT A.AGMT_ID,PRTY_ASSET_ID,F.FEAT_ID, FEAT_DTL_VAL CMPRN_CVGE_DED  FROM DB_T_PROD_CORE.AGMT_INSRD_ASSET_FEAT  A 

JOIN (SELECT MAX(JOB_END_DT) AS FEED_DTTM FROM DB_T_PROD_CORE.ETL_PRCS_CTRL WHERE PRCS_STS = ''SUCCEEDED'' AND PRCS_STAG = ''EDW_DLY'' AND SRC_NM = ''GW'') ECTL ON 1=1 

JOIN DB_T_PROD_CORE.FEAT AS F ON A.FEAT_ID = F.FEAT_ID  AND CAST(F.EDW_END_DTTM AS DATE)= CAST(''9999-12-31'' AS DATE) 

WHERE AGMT_ASSET_FEAT_STRT_DTTM <= ECTL.FEED_DTTM

AND F.INSRNC_CVGE_TYPE_CD =''COMP'' AND F.FEAT_SBTYPE_CD = ''OPT''

QUALIFY ROW_NUMBER() OVER(PARTITION BY A.AGMT_ID,A.PRTY_ASSET_ID,A.FEAT_ID ORDER BY A.AGMT_ASSET_FEAT_STRT_DTTM DESC, A.TRANS_STRT_DTTM DESC ) = 1)COV ON

COV.AGMT_ID=C.AGMT_ID AND COV.PRTY_ASSET_ID=DRV_NAME.PRTY_ASSET_ID

LEFT OUTER JOIN (

SELECT    POL_NUM,

COUNT(DISTINCT CASE WHEN (EXTRACT(YEAR FROM CLM_DTTM) BETWEEN EXTRACT(YEAR FROM ECTL.FEED_DT)-1 AND EXTRACT(YEAR FROM ECTL.FEED_DT)-1) THEN CLM_NUM ELSE NULL END) LAST_YR_CLM_CNT,

SUM(CASE WHEN (EXTRACT(YEAR FROM CLM_DTTM) BETWEEN EXTRACT(YEAR FROM ECTL.FEED_DT)-1 AND EXTRACT(YEAR FROM ECTL.FEED_DT)-1) THEN DB_T_PROD_CORE.CLM_AMT ELSE 0 END) LAST_YR_CLM_AMT,

COUNT( DISTINCT CASE WHEN (EXTRACT(YEAR FROM CLM_DTTM) BETWEEN EXTRACT(YEAR FROM ECTL.FEED_DT)-3 AND EXTRACT(YEAR FROM ECTL.FEED_DT)-1) THEN CLM_NUM ELSE NULL END) LAST_3YR_CLM_CNT,

SUM(CASE WHEN (EXTRACT(YEAR FROM CLM_DTTM)  BETWEEN EXTRACT(YEAR FROM ECTL.FEED_DT)-3 AND EXTRACT(YEAR FROM ECTL.FEED_DT)-1) THEN DB_T_PROD_CORE.CLM_AMT ELSE 0 END) LAST_3YR_CLM_AMT,

COUNT( DISTINCT CASE WHEN (EXTRACT(YEAR FROM CLM_DTTM) BETWEEN EXTRACT(YEAR FROM ECTL.FEED_DT)-5 AND EXTRACT(YEAR FROM ECTL.FEED_DT)-1) THEN CLM_NUM ELSE NULL END) LAST_5YR_CLM_CNT,

SUM(CASE WHEN (EXTRACT(YEAR FROM CLM_DTTM)  BETWEEN EXTRACT(YEAR FROM ECTL.FEED_DT)-5 AND EXTRACT(YEAR FROM ECTL.FEED_DT)-1) THEN DB_T_PROD_CORE.CLM_AMT ELSE 0 END) LAST_5YR_CLM_AMT

FROM (SELECT DISTINCT C.CLM_ID,C.CLM_NUM,A.AGMT_ID,CDT.CLM_dTTM,DB_T_PROD_CORE.CLM_AMT, HOST_AGMT_NUM POL_NUM

FROM DB_T_PROD_CORE.CLM C 

JOIN DB_T_PROD_CORE.CLM_DT CDT  ON C.CLM_ID=CDT.CLM_ID AND CDT.CLM_DT_TYPE_CD =''LOSS'' 

JOIN (

SELECT	CLM_ID, SUM(TOTAL_INCURRED) CLM_AMT 

FROM	(  

SELECT A.CLM_ID  ,  SUM (  

CASE	    

	WHEN	(CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD = ''PYMNT''                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''PDL'')                    

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')                                                                                   

	AND	      CLMLINEITM.LNITM_CTGY_TYPE_CD IN (  ''LOSS'',''DED'',''DEDRFND'',

		''FRMRDED'') ) THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)      

ELSE	     0  

END	      )  AS LOSS_PMT_AMT   ,SUM (  

CASE	    

	WHEN	(CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD = ''PYMNT''                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''PDL'')                    

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')                                                                   

	AND	     CLMTRANS.DOES_NOT_ERODE_RSERV_IND=''F''                                     ) THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)      

ELSE	     0  

END	      )  AS LOSS_PMT_ERODING_AMT     ,(SUM (  

CASE	    

	WHEN	( CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD=''RESRV'' )                  

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD=''PDL''                   

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD =''LOSS''                                     THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)   

ELSE	     0   

END	      ) )-LOSS_PMT_ERODING_AMT AS RSERV_AMT        ,(SUM(  

CASE	    

	WHEN	(CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD = ''PYMNT''                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''EXPNS'')                   

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''EXPNS'')                   

	AND	      CLMLINEITM.LNITM_CTGY_TYPE_CD IN (   ''SALVEXP'',''SUBROEXP'',

		''IAENG'',''LEGCOV'',''LEGDEF'',''RPRTS'' )                   )                  THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)   

ELSE	     0   

END	      ) )EXPENSE_PAID    ,SUM(   

CASE	    

	WHEN	( CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''                    

	AND	      CLMTRANS.RCVRY_CTGY_TYPE_CD IN (''SUBRO'' , ''SALVAGE'')                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''EXPNS'')                   

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''EXPNS'')                   

	AND	      CLMLINEITM.LNITM_CTGY_TYPE_CD IN ( ''RCVRY'',''SALVEXP'',

		''SUBROEXP'' ,''IAENG'',''LEGCOV'',''LEGDEF'',''RPRTS'' )                  )THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)   

ELSE	     0   

END	      )+   SUM(   

CASE	    

	WHEN	( CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''                    

	AND	      CLMTRANS.RCVRY_CTGY_TYPE_CD IN (''SUBRO'' , ''SALVAGE'')                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''PDL'')                   

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')                   

	AND	      CLMLINEITM.LNITM_CTGY_TYPE_CD IN ( ''RCVRY'',''SALVEXP'',

		''SUBROEXP'' )                  )THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)   

ELSE	     0   

END	      )+SUM(   

CASE	    

	WHEN	( CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''                    

	AND	      CLMTRANS.RCVRY_CTGY_TYPE_CD IN (''CREXP'')                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''EXPNS'')                   

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''EXPNS'')                   

	AND	      CLMLINEITM.LNITM_CTGY_TYPE_CD IN ( ''RCVRY'',''SALVEXP'',

		''SUBROEXP'' ,''IAENG'',''LEGCOV'',''LEGDEF'',''RPRTS'' )                  )THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)   

ELSE	     0   

END	      )+SUM(   

CASE	    

	WHEN	( CLMTRANS.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''                    

	AND	      CLMTRANS.RCVRY_CTGY_TYPE_CD IN (''CRLOSS'')                   

	AND	      CLMTRANS.EXPSR_COST_TYPE_CD IN (''PDL'')                   

	AND	      CLMTRANS.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')                                     )THEN (CLMLINEITM.CLM_EXPSR_LNITM_AMT)   

ELSE	     0   

END	      )RECOVERY,(LOSS_PMT_AMT+RSERV_AMT+EXPENSE_PAID-RECOVERY) TOTAL_INCURRED       

FROM	DB_T_PROD_CORE.CLM_EXPSR A JOIN DB_T_PROD_CORE.CLM B 

	ON	A.CLM_ID=B.CLM_ID JOIN DB_T_PROD_CORE.CLM_EXPSR_TRANS CLMTRANS   

	ON	A.CLM_EXPSR_ID=CLMTRANS.CLM_EXPSR_ID JOIN DB_T_PROD_CORE.CLM_EXPSR_TRANS_LNITM CLMLINEITM 

	ON	CLMTRANS.CLM_EXPSR_TRANS_ID=CLMLINEITM.CLM_EXPSR_TRANS_ID  

WHERE	CAST(A.EDW_END_DTTM AS DATE)=''9999-12-31'' 

	AND	 CAST(B.EDW_END_DTTM AS DATE)=''9999-12-31''  

	AND	 CAST(CLMTRANS.EDW_END_DTTM AS DATE)=''9999-12-31'' 

	AND	 CAST(CLMLINEITM.EDW_END_DTTM AS DATE)=''9999-12-31''  

	

GROUP	BY 1)a group by 1) CA ON CA.CLM_ID=C.CLM_ID

JOIN DB_T_PROD_CORE.AGMT_CLM AC ON AC.CLM_ID=C.CLM_ID JOIN DB_T_PROD_CORE.AGMT A ON A.AGMT_ID=AC.AGMT_ID) LAST_YR

JOIN (SELECT CAST(MAX(JOB_END_DT) AS DATE) AS FEED_DT FROM DB_T_PROD_CORE.ETL_PRCS_CTRL WHERE PRCS_STS = ''SUCCEEDED'' AND PRCS_STAG = ''EDW_DLY'' AND SRC_NM = ''GW'') ECTL ON 1=1 

GROUP BY 1) CLM_LAST_YR ON CLM_LAST_YR.POL_NUM=A.POL_NBR    )   AS E  



UNION ALL 

SELECT  CAST(''DB2'' AS VARCHAR(10)) SRC_IDNTFTN_SYS,

MBRSHP_NUM,L.PLCY_NUM,CAUS_CD,CAUS_DESC,LOB_CD,CLM_NUM,CSR_CLM_NUM,CLM_LOSS_DT,VEH_VIN_CD,

TOT_LOSS_AMT,VEH_MAKE_CD,VEH_MODL_DESC,VEH_MODL_YR,RTD_DRVR_FRST_NAME,RTD_DRVR_LAST_NAME,RTD_DRVR_BIRTH_DT,

RTD_DRVR_AGE,RTD_DRVR_CLNT_ID,UNIT_REF_NBR,CLM_STS_DESC,PLCY_INFR_IND,

CASE WHEN (E.PLCY_NUM IS NOT NULL) THEN E.PLCY_STS_CD ELSE L.PLCY_STS_CD END PLCY_STS_CD,

CASE WHEN (E.PLCY_NUM IS NOT NULL) THEN E.PLCY_STS_DESC ELSE L.PLCY_STS_DESC END PLCY_STS_DESC,

CMPRN_DEDCTB,LAST_YR_CLM_CNT,LAST_YR_CLM_AMT,LAST_3YR_CLM_CNT,LAST_3YR_CLM_AMT,LAST_5YR_CLM_CNT,LAST_5YR_CLM_AMT

FROM (  

SELECT                    

TRIM(CLIENT_REF_NBR) AS MBRSHP_NUM,

TRIM(POL_NBR) AS PLCY_NUM,

TRIM(CLAIM_CAUSE_CD) AS CAUS_CD,

TRIM(CS01_CODE_DES) AS CAUS_DESC, 

CAST(TRIM(CLAIM_LOB_CD) AS VARCHAR(10)) AS LOB_CD,

TRIM(CLAIM_NBR) AS CLM_NUM,

TRIM(CSR_CLAIM_NBR) AS CSR_CLM_NUM,

TRIM(CLAIM_LOSS_DT) AS CLM_LOSS_DT,

TRIM(CLAIM_LOSS_VIN) AS VEH_VIN_CD,

CLAIM_LOSS_AMT AS TOT_LOSS_AMT,

TRIM(CLAIM_VEH_MAKE) AS VEH_MAKE_CD,

TRIM(CLAIM_VEH_DESC) AS VEH_MODL_DESC,

CLAIM_VEH_YEAR AS VEH_MODL_YR,

TRIM(CLAIM_RATED_DRV_FST_NM) AS RTD_DRVR_FRST_NAME,

TRIM(CLAIM_RATED_DRV_LST_NM) AS RTD_DRVR_LAST_NAME,

CLAIM_RATED_DRV_DOB AS RTD_DRVR_BIRTH_DT,

CLAIM_RATED_DRV_AGE AS RTD_DRVR_AGE,

TRIM(CLAIM_RATED_DRV_CLT_ID) AS RTD_DRVR_CLNT_ID,

TRIM(CLAIM_UNIT_RFR) AS UNIT_REF_NBR,

TRIM(CLAIM_STATUS_CD) AS CLM_STS_DESC, /*  column name change from CLM_STS_CD */
TRIM(POL_INFORCE_IND) AS PLCY_INFR_IND,

CAST(CASE WHEN POL_INFORCE_IND=''I'' THEN ''1'' WHEN POL_INFORCE_IND=''O'' THEN ''5'' ELSE POL_INFORCE_IND END AS VARCHAR(2)) AS PLCY_STS_CD, 

CASE WHEN UPPER(TRIM(PS_STS.DESC1)) = ''INFORCE'' THEN ''IN FORCE''

WHEN UPPER(TRIM(PS_STS.DESC1)) = ''CANCELLED'' THEN ''CANCELED''

ELSE UPPER(TRIM(PS_STS.DESC1)) END AS PLCY_STS_DESC,

CAST(CASE WHEN CLM_CMP_DED = ''NO COV'' THEN NULL ELSE CLM_CMP_DED END AS INTEGER) AS CMPRN_DEDCTB, 

LAST_YRS_CLM_SUM AS LAST_YR_CLM_CNT,

LAST_YRS_CLM_AMT AS LAST_YR_CLM_AMT,

LAST_3YRS_CLM_SUM AS LAST_3YR_CLM_CNT,

LAST_3YRS_CLM_AMT AS LAST_3YR_CLM_AMT,

LAST_5YRS_CLM_SUM AS LAST_5YR_CLM_CNT,

LAST_5YRS_CLM_AMT AS LAST_5YR_CLM_AMT

FROM DB_T_STAG_MEMBXREF_PROD.POL_CLAIMS_LIST AS T 

LEFT OUTER JOIN DB_T_STAG_MEMBXREF_PROD.PS_LOOKUP AS  PS_STS 

ON PLCY_STS_CD = PS_STS.FIELD_VALUE 

AND PS_STS.FIELD_NAME=''PC_STATUS''

LEFT OUTER JOIN DB_T_SHRD_PROD.CLAIM_SUPPORT_01 AS AUTO_CAUS 

ON CAUS_CD = AUTO_CAUS.CS01_CODE

AND AUTO_CAUS.CS01_TABLE_ID  =''C008''  ) AS L 



LEFT OUTER JOIN 

(SELECT PPV.HOST_AGMT_NUM AS PLCY_NUM,

CASE WHEN COALESCE(A_S.AGMT_STS_CD,''~'') IN  (''ACTIVE'',''CNFRMD'',''INFORCE'',''SCHEDULED'') THEN ''1'' ELSE ''5'' END AS PLCY_STS_CD,

STS_TYPE.AGMT_STS_DESC PLCY_STS_DESC FROM 

(SELECT T1.HOST_AGMT_NUM,T1.TERM_NUM,T1.AGMT_ID,T1.MODL_CRTN_DTTM,T1.MODL_EFF_DTTM,T1.AGMT_EFF_DTTM,

CASE WHEN T1.MODL_EFF_DTTM > T1.MODL_CRTN_DTTM THEN T1.MODL_EFF_DTTM ELSE T1.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM

FROM DB_T_PROD_CORE.AGMT T1,

(SELECT CAST(CAST(MAX(JOB_END_DT) AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECONDS'' AS FEED_DTTM FROM DB_T_PROD_CORE.ETL_PRCS_CTRL WHERE PRCS_STS = ''SUCCEEDED'' AND PRCS_STAG = ''EDW_DLY'' AND SRC_NM = ''GW'') E

WHERE T1.AGMT_TYPE_CD = ''PPV'' AND T1.SRC_SYS_CD = ''GWPC'' AND E.FEED_DTTM BETWEEN AGMT_EFF_DTTM AND AGMT_PLND_EXPN_DTTM

AND T1.TRANS_STRT_DTTM = (SELECT MIN(T2.TRANS_STRT_DTTM) FROM DB_T_PROD_CORE.AGMT T2 WHERE T1.AGMT_ID = T2.AGMT_ID) 

AND NEW_AGMT_EFF_DTTM <=  E.FEED_DTTM QUALIFY ROW_NUMBER() OVER(PARTITION BY T1.HOST_AGMT_NUM ORDER BY T1.MODL_CRTN_DTTM DESC ) = 1) PPV 

INNER JOIN 

(SELECT HOST_AGMT_NUM, TERM_NUM,AGMT_ID,FEED_DTTM FROM DB_T_PROD_CORE.AGMT A,

(SELECT CAST(CAST(MAX(JOB_END_DT) AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECONDS'' AS FEED_DTTM FROM DB_T_PROD_CORE.ETL_PRCS_CTRL WHERE PRCS_STS = ''SUCCEEDED'' AND PRCS_STAG = ''EDW_DLY'' AND SRC_NM = ''GW'') E 

WHERE AGMT_TYPE_CD = ''POLTRM'' AND E.FEED_DTTM BETWEEN AGMT_EFF_DTTM AND AGMT_PLND_EXPN_DTTM GROUP BY 1,2,3) TRM 

ON PPV.HOST_AGMT_NUM = TRM.HOST_AGMT_NUM AND PPV.TERM_NUM = TRM.TERM_NUM  

INNER JOIN DB_T_PROD_CORE.AGMT_STS A_S ON TRM.AGMT_ID = A_S.AGMT_ID  AND A_S.AGMT_STS_STRT_DTTM <= TRM.FEED_DTTM AND A_S.AGMT_STS_CD <> ''CNFRMDDT'' 

INNER JOIN DB_T_PROD_CORE.AGMT_STS_TYPE STS_TYPE ON A_S.AGMT_STS_CD=STS_TYPE.AGMT_STS_CD AND STS_TYPE.EDW_END_DTTM=''9999-12-31 23:59:59.999999''

QUALIFY ROW_NUMBER() OVER(PARTITION BY PPV.AGMT_ID ORDER BY A_S.AGMT_STS_STRT_DTTM DESC) = 1 

 ) E  ON L.PLCY_NUM=E.PLCY_NUM) CMP
) SRC
)
);


-- Component EXP_WR_PLCY_CLM_LIST, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXP_WR_PLCY_CLM_LIST AS
(
SELECT
SQ_WR_PLCY_CLM_LIST.SRC_IDNTFTN_SYS as SRC_IDNTFTN_SYS,
SQ_WR_PLCY_CLM_LIST.MBRSHP_NUM as MBRSHP_NUM,
SQ_WR_PLCY_CLM_LIST.PLCY_NUM as PLCY_NUM,
SQ_WR_PLCY_CLM_LIST.CAUS_CD as CAUS_CD,
SQ_WR_PLCY_CLM_LIST.CAUS_DESC as CAUS_DESC,
SQ_WR_PLCY_CLM_LIST.LOB_CD as LOB_CD,
SQ_WR_PLCY_CLM_LIST.CLM_NUM as CLM_NUM,
SQ_WR_PLCY_CLM_LIST.CSR_CLM_NUM as CSR_CLM_NUM,
SQ_WR_PLCY_CLM_LIST.CLM_LOSS_DT as CLM_LOSS_DT,
SQ_WR_PLCY_CLM_LIST.VEH_VIN_CD as VEH_VIN_CD,
SQ_WR_PLCY_CLM_LIST.TOT_LOSS_AMT as TOT_LOSS_AMT,
SQ_WR_PLCY_CLM_LIST.VEH_MAKE_CD as VEH_MAKE_CD,
SQ_WR_PLCY_CLM_LIST.VEH_MODL_DESC as VEH_MODL_DESC,
SQ_WR_PLCY_CLM_LIST.VEH_MODL_YR as VEH_MODL_YR,
SQ_WR_PLCY_CLM_LIST.RTD_DRVR_FRST_NAME as RTD_DRVR_FRST_NAME,
SQ_WR_PLCY_CLM_LIST.RTD_DRVR_LAST_NAME as RTD_DRVR_LAST_NAME,
SQ_WR_PLCY_CLM_LIST.RTD_DRVR_BIRTH_DT as RTD_DRVR_BIRTH_DT,
SQ_WR_PLCY_CLM_LIST.RTD_DRVR_AGE as RTD_DRVR_AGE,
SQ_WR_PLCY_CLM_LIST.RTD_DRVR_CLNT_ID as RTD_DRVR_CLNT_ID,
SQ_WR_PLCY_CLM_LIST.UNIT_REF_NBR as UNIT_REF_NBR,
SQ_WR_PLCY_CLM_LIST.CLM_STS_DESC as CLM_STS_DESC,
SQ_WR_PLCY_CLM_LIST.PLCY_INFR_IND as PLCY_INFR_IND,
SQ_WR_PLCY_CLM_LIST.PLCY_STS_CD as PLCY_STS_CD,
SQ_WR_PLCY_CLM_LIST.PLCY_STS_DESC as PLCY_STS_DESC,
SQ_WR_PLCY_CLM_LIST.CMPRN_DEDCTB as CMPRN_DEDCTB,
SQ_WR_PLCY_CLM_LIST.LAST_YR_CLM_CNT as LAST_YR_CLM_CNT,
SQ_WR_PLCY_CLM_LIST.LAST_YR_CLM_AMT as LAST_YR_CLM_AMT,
SQ_WR_PLCY_CLM_LIST.LAST_3YR_CLM_CNT as LAST_3YR_CLM_CNT,
SQ_WR_PLCY_CLM_LIST.LAST_3YR_CLM_AMT as LAST_3YR_CLM_AMT,
SQ_WR_PLCY_CLM_LIST.LAST_5YR_CLM_CNT as LAST_5YR_CLM_CNT,
SQ_WR_PLCY_CLM_LIST.LAST_5YR_CLM_AMT as LAST_5YR_CLM_AMT,
SQ_WR_PLCY_CLM_LIST.source_record_id
FROM
SQ_WR_PLCY_CLM_LIST
);


-- Component WR_PLCY_CLM_LIST, Type TARGET 
INSERT INTO DB_V_PROD_PRES.WR_PLCY_CLM_LIST
(
SRC_IDNTFTN_SYS,
MBRSHP_NUM,
PLCY_NUM,
CAUS_CD,
CAUS_DESC,
LOB_CD,
CLM_NUM,
CSR_CLM_NUM,
CLM_LOSS_DT,
VEH_VIN_CD,
TOT_LOSS_AMT,
VEH_MAKE_CD,
VEH_MODL_DESC,
VEH_MODL_YR,
RTD_DRVR_FRST_NAME,
RTD_DRVR_LAST_NAME,
RTD_DRVR_BIRTH_DT,
RTD_DRVR_AGE,
RTD_DRVR_CLNT_ID,
UNIT_REF_NBR,
CLM_STS_DESC,
PLCY_INFR_IND,
PLCY_STS_CD,
PLCY_STS_DESC,
CMPRN_DEDCTB,
LAST_YR_CLM_CNT,
LAST_YR_CLM_AMT,
LAST_3YR_CLM_CNT,
LAST_3YR_CLM_AMT,
LAST_5YR_CLM_CNT,
LAST_5YR_CLM_AMT
)
SELECT
EXP_WR_PLCY_CLM_LIST.SRC_IDNTFTN_SYS as SRC_IDNTFTN_SYS,
EXP_WR_PLCY_CLM_LIST.MBRSHP_NUM as MBRSHP_NUM,
EXP_WR_PLCY_CLM_LIST.PLCY_NUM as PLCY_NUM,
EXP_WR_PLCY_CLM_LIST.CAUS_CD as CAUS_CD,
EXP_WR_PLCY_CLM_LIST.CAUS_DESC as CAUS_DESC,
EXP_WR_PLCY_CLM_LIST.LOB_CD as LOB_CD,
EXP_WR_PLCY_CLM_LIST.CLM_NUM as CLM_NUM,
EXP_WR_PLCY_CLM_LIST.CSR_CLM_NUM as CSR_CLM_NUM,
EXP_WR_PLCY_CLM_LIST.CLM_LOSS_DT as CLM_LOSS_DT,
EXP_WR_PLCY_CLM_LIST.VEH_VIN_CD as VEH_VIN_CD,
EXP_WR_PLCY_CLM_LIST.TOT_LOSS_AMT as TOT_LOSS_AMT,
EXP_WR_PLCY_CLM_LIST.VEH_MAKE_CD as VEH_MAKE_CD,
EXP_WR_PLCY_CLM_LIST.VEH_MODL_DESC as VEH_MODL_DESC,
EXP_WR_PLCY_CLM_LIST.VEH_MODL_YR as VEH_MODL_YR,
EXP_WR_PLCY_CLM_LIST.RTD_DRVR_FRST_NAME as RTD_DRVR_FRST_NAME,
EXP_WR_PLCY_CLM_LIST.RTD_DRVR_LAST_NAME as RTD_DRVR_LAST_NAME,
EXP_WR_PLCY_CLM_LIST.RTD_DRVR_BIRTH_DT as RTD_DRVR_BIRTH_DT,
EXP_WR_PLCY_CLM_LIST.RTD_DRVR_AGE as RTD_DRVR_AGE,
EXP_WR_PLCY_CLM_LIST.RTD_DRVR_CLNT_ID as RTD_DRVR_CLNT_ID,
EXP_WR_PLCY_CLM_LIST.UNIT_REF_NBR as UNIT_REF_NBR,
EXP_WR_PLCY_CLM_LIST.CLM_STS_DESC as CLM_STS_DESC,
EXP_WR_PLCY_CLM_LIST.PLCY_INFR_IND as PLCY_INFR_IND,
EXP_WR_PLCY_CLM_LIST.PLCY_STS_CD as PLCY_STS_CD,
EXP_WR_PLCY_CLM_LIST.PLCY_STS_DESC as PLCY_STS_DESC,
EXP_WR_PLCY_CLM_LIST.CMPRN_DEDCTB as CMPRN_DEDCTB,
EXP_WR_PLCY_CLM_LIST.LAST_YR_CLM_CNT as LAST_YR_CLM_CNT,
EXP_WR_PLCY_CLM_LIST.LAST_YR_CLM_AMT as LAST_YR_CLM_AMT,
EXP_WR_PLCY_CLM_LIST.LAST_3YR_CLM_CNT as LAST_3YR_CLM_CNT,
EXP_WR_PLCY_CLM_LIST.LAST_3YR_CLM_AMT as LAST_3YR_CLM_AMT,
EXP_WR_PLCY_CLM_LIST.LAST_5YR_CLM_CNT as LAST_5YR_CLM_CNT,
EXP_WR_PLCY_CLM_LIST.LAST_5YR_CLM_AMT as LAST_5YR_CLM_AMT
FROM
EXP_WR_PLCY_CLM_LIST;


END; ';