-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_GW_GL_MISSING_CLM_EXPSR_TRANS_MTHLY("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN

-- Component SQ_ADD_BAL_ACC, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ADD_BAL_ACC AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CLM_NUM,
$2 as CLM_EXPSR_TRANS_ID,
$3 as SOURCE_EXPOSURE_ID,
$4 as CLM_EXPSR_TRANS_SBTYPE_CD,
$5 as EXPSR_COST_TYPE_CD,
$6 as EXPSR_COST_CTGY_TYPE_CD,
$7 as CLM_EXPSR_TRANS_DTTM,
$8 as LNITM_CTGY_TYPE_CD,
$9 as CLM_EXPSR_LNITM_AMT,
$10 as CLM_EXPSR_TRANS_LNITM_STRT_DTTM,
$11 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT DISTINCT  CLM_NUM,         

CET.CLM_EXPSR_TRANS_ID,

CE.NK_SRC_KEY AS "SOURCE EXPOSURE ID" ,

CLM_EXPSR_TRANS_SBTYPE_CD,                          

EXPSR_COST_TYPE_CD,       

EXPSR_COST_CTGY_TYPE_CD,                                                            

CLM_EXPSR_TRANS_DTTM,

LNITM_CTGY_TYPE_CD,        

CLM_EXPSR_LNITM_AMT,     

CLM_EXPSR_TRANS_LNITM_STRT_DTTM

FROM DB_T_PROD_CORE.CLM_EXPSR_TRANS CET

JOIN DB_T_PROD_CORE.CLM_EXPSR CE ON  CE.CLM_EXPSR_ID = CET.CLM_EXPSR_ID

JOIN DB_T_PROD_CORE.CLM ON CLM.CLM_ID = CE.CLM_ID

JOIN DB_T_PROD_CORE.CLM_EXPSR_TRANS_LNITM CETL ON CETL.CLM_EXPSR_TRANS_ID = CET.CLM_EXPSR_TRANS_ID

WHERE    CET.EXPSR_COST_TYPE_CD <> ''expns'' 

AND CET.EXPSR_COST_CTGY_TYPE_CD <> ''expns'' 

AND (CET.GL_MTH_NUM IS NULL OR CET.GL_YR_NUM IS NULL)

AND CET.EDW_END_DTTM = ''9999-12-31 23:59:59.999999'' 

AND CE.EDW_END_DTTM =  ''9999-12-31 23:59:59.999999'' 

AND CLM.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''  

AND CETL.LNITM_CTGY_TYPE_CD IS NOT NULL
) SRC
)
);


-- Component exp_ADD_BAL_ACC, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ADD_BAL_ACC AS
(
SELECT
SQ_ADD_BAL_ACC.CLM_NUM as CLM_NUM,
SQ_ADD_BAL_ACC.CLM_EXPSR_TRANS_ID as CLM_EXPSR_TRANS_ID,
SQ_ADD_BAL_ACC.SOURCE_EXPOSURE_ID as SOURCE_EXPOSURE_ID,
SQ_ADD_BAL_ACC.CLM_EXPSR_TRANS_SBTYPE_CD as CLM_EXPSR_TRANS_SBTYPE_CD,
SQ_ADD_BAL_ACC.EXPSR_COST_TYPE_CD as EXPSR_COST_TYPE_CD,
SQ_ADD_BAL_ACC.EXPSR_COST_CTGY_TYPE_CD as EXPSR_COST_CTGY_TYPE_CD,
SQ_ADD_BAL_ACC.CLM_EXPSR_TRANS_DTTM as CLM_EXPSR_TRANS_DTTM,
SQ_ADD_BAL_ACC.LNITM_CTGY_TYPE_CD as LNITM_CTGY_TYPE_CD,
SQ_ADD_BAL_ACC.CLM_EXPSR_LNITM_AMT as CLM_EXPSR_LNITM_AMT,
SQ_ADD_BAL_ACC.CLM_EXPSR_TRANS_LNITM_STRT_DTTM as CLM_EXPSR_TRANS_LNITM_STRT_DTTM,
SQ_ADD_BAL_ACC.source_record_id
FROM
SQ_ADD_BAL_ACC
);


-- Component ADD_BAL_ACCOUNTING, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE ADD_BAL_ACCOUNTING AS
(
SELECT
exp_ADD_BAL_ACC.CLM_NUM as CLM_NUM,
exp_ADD_BAL_ACC.CLM_EXPSR_TRANS_ID as CLM_EXPSR_TRANS_ID,
exp_ADD_BAL_ACC.SOURCE_EXPOSURE_ID as SOURCE_EXPOSURE_ID,
exp_ADD_BAL_ACC.CLM_EXPSR_TRANS_SBTYPE_CD as CLM_EXPSR_TRANS_SBTYPE_CD,
exp_ADD_BAL_ACC.EXPSR_COST_TYPE_CD as EXPSR_COST_TYPE_CD,
exp_ADD_BAL_ACC.EXPSR_COST_CTGY_TYPE_CD as EXPSR_COST_CTGY_TYPE_CD,
exp_ADD_BAL_ACC.CLM_EXPSR_TRANS_DTTM as CLM_EXPSR_TRANS_DTTM,
exp_ADD_BAL_ACC.LNITM_CTGY_TYPE_CD as LNITM_CTGY_TYPE_CD,
exp_ADD_BAL_ACC.CLM_EXPSR_LNITM_AMT as CLM_EXPSR_LNITM_AMT,
exp_ADD_BAL_ACC.CLM_EXPSR_TRANS_LNITM_STRT_DTTM as CLM_EXPSR_TRANS_LNITM_STRT_DTTM
FROM
exp_ADD_BAL_ACC
);


-- Component ADD_BAL_ACCOUNTING, Type EXPORT_DATA Exporting data
;


END; ';