-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_TREXIS_AGT_ACCTBLY_PREM_MTHLY("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
  PRCS_ID STRING;
BEGIN
  SELECT 
    TRY_PARSE_JSON(:param_json):PRCS_ID::STRING
  INTO
    PRCS_ID;

-- Component SQ_TREXIS_AGT_ACCTBLY_PREM, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_TREXIS_AGT_ACCTBLY_PREM AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as AGENT_NBR,
$2 as STATE_NBR,
$3 as DATE_WRITTEN,
$4 as NB_PREM_AMT,
$5 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT AGENT_NBR, 

	STATE_NBR, 

	DATE_WRITTEN, 

	NB_PREM_AMT 

FROM DB_T_PROD_COMN.TREXIS_AGT_ACCTBLY_PREM
) SRC
)
);


-- Component exp_pass_thru, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_thru AS
(
SELECT
SQ_TREXIS_AGT_ACCTBLY_PREM.AGENT_NBR as AGENT_NBR,
SQ_TREXIS_AGT_ACCTBLY_PREM.STATE_NBR as STATE_NBR,
SQ_TREXIS_AGT_ACCTBLY_PREM.DATE_WRITTEN as DATE_WRITTEN,
SQ_TREXIS_AGT_ACCTBLY_PREM.NB_PREM_AMT as NB_PREM_AMT,
:PRCS_ID as PRCS_ID,
SQ_TREXIS_AGT_ACCTBLY_PREM.source_record_id
FROM
SQ_TREXIS_AGT_ACCTBLY_PREM
);


-- Component TREXIS_AGT_ACCTBLY_PREM1, Type TARGET 
INSERT INTO DB_T_PROD_COMN.TREXIS_AGT_ACCTBLY_PREM
(
AGENT_NBR,
STATE_NBR,
DATE_WRITTEN,
PREMIUM_AMT,
PRCS_ID
)
SELECT
exp_pass_thru.AGENT_NBR as AGENT_NBR,
exp_pass_thru.STATE_NBR as STATE_NBR,
exp_pass_thru.DATE_WRITTEN as DATE_WRITTEN,
exp_pass_thru.NB_PREM_AMT as PREMIUM_AMT,
exp_pass_thru.PRCS_ID as PRCS_ID
FROM
exp_pass_thru;


END; ';