-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_UMBRELLA_BORDEREAUX_FILES("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
  CAL_START_DT STRING;
  CAL_END_DT STRING;
BEGIN
  SELECT 
    TRY_PARSE_JSON(:param_json):CAL_START_DT::STRING,
    TRY_PARSE_JSON(:param_json):CAL_END_DT::STRING
  INTO
    CAL_START_DT,
    CAL_END_DT;

-- Component SQ_UMB_BORDEREAU, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_UMB_BORDEREAU AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as TRANS_ID,
$2 as UW_CMPNY,
$3 as STATE,
$4 as TRANS_TYPE,
$5 as POL_TYPE_DESC,
$6 as POL_NBR,
$7 as POL_EFF_DT,
$8 as POL_EXP_DT,
$9 as TERM,
$10 as POL_INS_NM,
$11 as PER_MIL_VAL,
$12 as PREM_PER_MIL_COV,
$13 as TRANS_EFF_DT,
$14 as TRANS_ENTRY_DT,
$15 as UW_YEAR,
$16 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 

A.TRANS_ID, A.UW_CMPNY, A.STATE, A.TRANS_TYPE, 

A.POL_TYPE_DESC, A.POL_NBR, A.POL_EFF_DT, 

A.POL_EXP_DT, A.TERM, A.POL_INS_NM, A.PER_MIL_VAL, 

A.PREM_PER_MIL_COV,A.TRANS_EFF_DT,A.TRANS_ENTRY_DT,A.UW_YEAR 

FROM

DB_T_PROD_WRK.UMB_BORDEREAU A

WHERE

  CASE 

    WHEN cast(A.TRANS_ENTRY_DT AS DATE )  > CAST(A.TRANS_EFF_DT AS DATE) 

         THEN cast(A.TRANS_ENTRY_DT AS DATE)

     ELSE cast(A.TRANS_EFF_DT AS DATE)

     END     >=  ''$CAL_START_DT''

              

   AND

       CASE 

       WHEN cast(A.TRANS_ENTRY_DT AS DATE)  > CAST(A.TRANS_EFF_DT AS DATE) 

          THEN cast(A.TRANS_ENTRY_DT AS DATE)

      ELSE cast(A.TRANS_EFF_DT AS DATE)

       END     <=  ''$CAL_END_DT''
) SRC
)
);


-- Component exp_src_tgt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_src_tgt AS
(
SELECT
SQ_UMB_BORDEREAU.TRANS_ID as TRANS_ID,
SQ_UMB_BORDEREAU.UW_CMPNY as UW_CMPNY,
SQ_UMB_BORDEREAU.STATE as STATE,
SQ_UMB_BORDEREAU.TRANS_TYPE as TRANS_TYPE,
SQ_UMB_BORDEREAU.POL_TYPE_DESC as POL_TYPE_DESC,
SQ_UMB_BORDEREAU.POL_NBR as POL_NBR,
TO_CHAR ( SQ_UMB_BORDEREAU.POL_EFF_DT , ''YYYYMMDD'' ) as o_POL_EFF_DT,
TO_CHAR ( SQ_UMB_BORDEREAU.POL_EXP_DT , ''YYYYMMDD'' ) as o_POL_EXP_DT,
SQ_UMB_BORDEREAU.TERM as TERM,
SQ_UMB_BORDEREAU.POL_INS_NM as POL_INS_NM,
SQ_UMB_BORDEREAU.PER_MIL_VAL as PER_MIL_VAL,
SQ_UMB_BORDEREAU.PREM_PER_MIL_COV as PREM_PER_MIL_COV,
TO_CHAR ( SQ_UMB_BORDEREAU.TRANS_EFF_DT , ''YYYYMMDD'' ) as o_TRANS_EFF_DT,
TO_CHAR ( SQ_UMB_BORDEREAU.TRANS_ENTRY_DT , ''YYYYMMDD'' ) as o_TRANS_ENTRY_DT,
SQ_UMB_BORDEREAU.UW_YEAR as UW_YEAR,
SQ_UMB_BORDEREAU.source_record_id
FROM
SQ_UMB_BORDEREAU
);


-- Component Umbrella_Bordereaux_Detail, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE Umbrella_Bordereaux_Detail AS
(
SELECT
exp_src_tgt.TRANS_ID as TRANS_ID,
exp_src_tgt.UW_CMPNY as UW_COMPANY,
exp_src_tgt.STATE as STATE,
exp_src_tgt.TRANS_TYPE as TRANS_TYPE,
exp_src_tgt.POL_TYPE_DESC as POLICY_TYPE,
exp_src_tgt.POL_NBR as POL_NUMBER,
exp_src_tgt.o_POL_EFF_DT as EFF_DATE,
exp_src_tgt.o_POL_EXP_DT as EXP_DATE,
exp_src_tgt.TERM as TERM,
exp_src_tgt.POL_INS_NM as NAME,
exp_src_tgt.PER_MIL_VAL as MILLION_TYPE,
exp_src_tgt.PREM_PER_MIL_COV as PREMIUM,
exp_src_tgt.o_TRANS_EFF_DT as TRANS_EFF_DATE,
exp_src_tgt.o_TRANS_ENTRY_DT as TRANS_ENTRY_DATE,
exp_src_tgt.UW_YEAR as UW_YEAR
FROM
exp_src_tgt
);


-- Component Umbrella_Bordereaux_Detail, Type EXPORT_DATA Exporting data
;


END; ';