-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_WRK_EDW_EBLM_PLCY_VEH_EXTRACT("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
  CAL_END_DT STRING;
BEGIN
  SELECT 
    TRY_PARSE_JSON(:param_json):CAL_END_DT::STRING
  INTO
    CAL_END_DT;

-- Component sq_edw_eblm_plcy_veh, Type Pre SQL 
DELETE FROM DB_WRK.EDW_EBLM_PLCY_VEH    WHERE MO_ID=EXTRACT(YEAR FROM CAST('':CAL_END_DT'' AS DATE))*100+EXTRACT(MONTH FROM CAST('':CAL_END_DT'' AS DATE));


-- Component sq_edw_eblm_plcy_veh, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_edw_eblm_plcy_veh AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as PLCY_NBR,
$2 as PLCY_VEH_KEY,
$3 as PLCY_CHG_EFF_DT,
$4 as PLCY_CHG_EXP_DT,
$5 as PLCY_PLN_EXP_DT,
$6 as PLCY_EFF_TYPE_CD,
$7 as VEH_CHG_EFF_DT,
$8 as VEH_CHG_EXP_DT,
$9 as DRV_SKEY,
$10 as RSK_ST_CD,
$11 as RSK_TERR_CD,
$12 as RSK_POSTAL_CD,
$13 as PA_SYM_CD,
$14 as ANN_MILE_DESC,
$15 as PLCY_OGN_EFF_DT,
$16 as PLCY_OGN_IPT_DT,
$17 as YEARS_WITH_ALFA,
$18 as MASTER_COMPANY_NBR,
$19 as VEH_MAKE_DESC,
$20 as VEH_MODEL_YR,
$21 as VEH_TYPE_CD,
$22 as VEH_CST_NEW_AMT,
$23 as GENDER_CD,
$24 as OCP_DESC,
$25 as CLIENT_DOB,
$26 as CLIENT_AGE,
$27 as MARITAL_STATUS_CD,
$28 as VEH_USE_CD,
$29 as CLIENT_EFF_DT,
$30 as NBR_MILES_WORK,
$31 as INS_SCR1,
$32 as INS_SCR2,
$33 as PA_POINTS_NBR,
$34 as NBR_SPEED_VIOLNS,
$35 as DW_PLCY_SKEY,
$36 as PLCY_SVC_NBR,
$37 as SALES_AGENCY_NBR,
$38 as PTY_INS_CARRIER_CD,
$39 as PTY_INS_CARRIER_NM,
$40 as NM_INSUR_GENDER_CD,
$41 as NM_INSUR_DOB,
$42 as NM_INSUR_AGE,
$43 as NM_INSUR_MARITAL_STATUS_CD,
$44 as NM_INSUR_MEMB_TYPE,
$45 as NM_INSUR_MEMB_NBR,
$46 as NM_INSUR_SKEY,
$47 as DRVEXC,
$48 as DRVEXC25,
$49 as PA_SYM_CD_2,
$50 as MO_ID,
$51 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH  ADDRESS_HIERARCHY AS       

(       

SELECT  LOCTR.LOCTR_ID, 
    STREET_ADDR.ADDR_LN_1_TXT AS PLCY_MAIL_ADDRESS_1, 
    STREET_ADDR.ADDR_LN_2_TXT AS PLCY_MAIL_ADDRESS_2,     
    CITY.GEOGRCL_AREA_NAME AS CITY, 
    TERR.GEOGRCL_AREA_NAME AS STATE,
    POSTL_CD.POSTL_CD_NUM AS ZIP, 
    CNTY.GEOGRCL_AREA_NAME AS COUNTY     

FROM  DB_T_PROD_CORE.LOCTR  

    JOIN DB_T_PROD_CORE.STREET_ADDR AS STREET_ADDR ON  LOCTR.LOCTR_ID=STREET_ADDR.STREET_ADDR_ID AND STREET_ADDR.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))  

    LEFT JOIN CITY ON  STREET_ADDR.CITY_ID=CITY.CITY_ID AND CITY.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))  

    LEFT JOIN DB_T_PROD_CORE.TERR ON STREET_ADDR.TERR_ID=TERR.TERR_ID AND  TERR.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))  

    LEFT JOIN DB_T_PROD_CORE.POSTL_CD ON   STREET_ADDR.POSTL_CD_ID=POSTL_CD.POSTL_CD_ID AND POSTL_CD.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6)) 

    LEFT JOIN  DB_T_PROD_CORE.CNTY ON  STREET_ADDR.CNTY_ID=CNTY.CNTY_ID AND CNTY.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6)) 

    LEFT JOIN DB_T_PROD_CORE.CTRY ON STREET_ADDR.CTRY_ID=CTRY.CTRY_ID AND CTRY.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6)) 

  WHERE LOCTR.LOCTR_SBTYPE_CD=''AD''  AND LOCTR.ADDR_SBTYPE_CD=''STADR'' )

, LOCATION_ADDRESS AS       

(SELECT  x.PRTY_ASSET_ID, max(TERR.GEOGRCL_AREA_SHRT_NAME)  AS STATE,max(POSTL_CD.POSTL_CD_NUM)   ZIP

FROM (SELECT * from DB_T_PROD_CORE.PRTY_ASSET_LOCTR  WHERE  PRTY_ASSET_LOCTR.PRTY_ASSET_LOCTR_ROLE_CD IN (''RSKST'' ,''RSKPC'')

AND   CAST(PRTY_ASSET_LOCTR.TRANS_STRT_DTTM AS DATE)<=CAST('':CAL_END_DT'' AS DATE) AND CAST(PRTY_ASSET_LOCTR.TRANS_END_DTTM AS DATE)>CAST('':CAL_END_DT'' AS DATE) )X

    left JOIN DB_T_PROD_CORE.MOTR_VEH ON MOTR_VEH.PRTY_ASSET_ID=X.PRTY_ASSET_ID

    LEFT JOIN DB_T_PROD_CORE.TERR ON X.LOC_ID=TERR.TERR_ID 

    LEFT JOIN DB_T_PROD_CORE.POSTL_CD  ON X.LOC_ID=POSTL_CD.POSTL_CD_ID

where TERR.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))   

 group by 1)

,  ASSET_DETAIL AS       

( SELECT ASSET_DTL_CD_XREF.ASSET_DTL_CD , ASSET_DTL_TYPE.ASSET_DTL_DESC  , ASSET_DTL_TYPE.ASSET_DTL_SCHM_TYPE_CD , ASSET_DTL_CD_XREF.PRTY_ASSET_ID      

FROM DB_T_PROD_CORE.ASSET_DTL_CD_XREF, DB_T_PROD_CORE.ASSET_DTL_TYPE      

WHERE  ASSET_DTL_TYPE.ASSET_DTL_CD=ASSET_DTL_CD_XREF.ASSET_DTL_CD        

AND ASSET_DTL_CD_XREF.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))       

AND ASSET_DTL_CD_XREF.ASSET_DTL_CD<>''UNK'')       

,PRTY_ASSET_COVERAGES AS       

( SELECT  AGMT.AGMT_ID, AGMT.HOST_AGMT_NUM, PRTY_ASSET.PRTY_ASSET_ID, RATE_SYMB_CD  , f.INSRNC_CVGE_TYPE_CD,       

    CASE WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f2.FEAT_NAME       

    WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f.FEAT_NAME       

    WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f4.FEAT_NAME  END TERM_NAME,       

    CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.FEAT_NAME       

    WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.FEAT_NAME       

    WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.FEAT_NAME  END COV_NAME,       

    CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.NK_SRC_KEY       

    WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.NK_SRC_KEY       

    WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.NK_SRC_KEY  END COV_PATTERNCODE,       

    CASE WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f2.NK_SRC_KEY       

    WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f.NK_SRC_KEY       

    WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f4.NK_SRC_KEY  END TERM_PATTERNCODE,       

    CASE WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN CAST(f.FEAT_DTL_VAL AS DECIMAL(18,4))       

    WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN CAST(f.FEAT_DTL_VAL AS DECIMAL(18,4))       

    WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN  f.FEAT_DTL_CD_NAME END VAL         

FROM DB_T_PROD_CORE.FEAT f       

JOIN DB_T_PROD_CORE.AGMT_INSRD_ASSET_FEAT ON f.FEAT_ID=AGMT_INSRD_ASSET_FEAT.FEAT_ID  /* AND EOM_DAY BETWEEN AGMT_INSRD_ASSET_FEAT.TRANS_STRT_DTTM  AND AGMT_INSRD_ASSET_FEAT.TRANS_END_DTTM       */
    JOIN DB_T_PROD_CORE.AGMT ON AGMT_INSRD_ASSET_FEAT.AGMT_ID=AGMT.AGMT_ID AND AGMT.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))      

    JOIN  DB_T_PROD_CORE.PRTY_ASSET ON AGMT_INSRD_ASSET_FEAT.PRTY_ASSET_ID=PRTY_ASSET.PRTY_ASSET_ID AND PRTY_ASSET.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))      

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr1 ON f.FEAT_ID=fr1.RLTD_FEAT_ID AND   fr1.FEAT_RLTNSHP_TYPE_CD =''COVT''  /* AND EOM_DAY BETWEEN fr1.TRANS_STRT_DTTM AND fr1.TRANS_END_DTTM         */
    LEFT JOIN DB_T_PROD_CORE.FEAT f1 ON fr1.FEAT_ID=f1.FEAT_ID           

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr2 ON f.FEAT_ID=fr2.RLTD_FEAT_ID AND   fr2.FEAT_RLTNSHP_TYPE_CD =''TERMOPT'' /*  AND EOM_DAY BETWEEN fr2.TRANS_STRT_DTTM AND fr2.TRANS_END_DTTM         */
    LEFT JOIN DB_T_PROD_CORE.FEAT f2 ON fr2.FEAT_ID=f2.FEAT_ID       

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr3 ON f.FEAT_ID=fr3.RLTD_FEAT_ID AND   fr3.FEAT_RLTNSHP_TYPE_CD =''COVOPTT'' /* AND EOM_DAY BETWEEN fr3.TRANS_STRT_DTTM AND fr3.TRANS_END_DTTM         */
    LEFT JOIN DB_T_PROD_CORE.FEAT f3 ON fr3.FEAT_ID=f3.FEAT_ID       

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr4 ON f.FEAT_ID=fr4.RLTD_FEAT_ID AND   fr4.FEAT_RLTNSHP_TYPE_CD =''TERMPKG'' /* AND EOM_DAY BETWEEN fr4.TRANS_STRT_DTTM AND fr4.TRANS_END_DTTM        */
    LEFT JOIN DB_T_PROD_CORE.FEAT f4 ON fr4.FEAT_ID=f4.FEAT_ID       

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr5 ON f.FEAT_ID=fr5.RLTD_FEAT_ID AND   fr5.FEAT_RLTNSHP_TYPE_CD =''COVPKG''  /* AND EOM_DAY BETWEEN fr5.TRANS_STRT_DTTM AND fr5.TRANS_END_DTTM        */
    LEFT JOIN DB_T_PROD_CORE.FEAT f5 ON fr5.FEAT_ID=f5.FEAT_ID       

WHERE f.FEAT_SBTYPE_CD IN (''TERM'', ''OPT'', ''PKG'')       

AND AGMT.modl_crtn_dttm = (SELECT MAX(aa.modl_crtn_dttm)  FROM DB_T_PROD_CORE.AGMT aa WHERE aa.host_agmt_num=AGMT.host_agmt_num)   

AND AGMT.AGMT_CUR_STS_CD=''BOUND''       

AND CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.NK_SRC_KEY       

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.NK_SRC_KEY       

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.NK_SRC_KEY       

END  NOT IN (''HOLI_SCHEDULEDPROPERTYDEDUCTIBLESITEM_ALFA'', ''HOSI_SCHEDULEDPROPERTYITEM_ALFA''))       

, INDIV_NAME_STG  AS       

( SELECT INDIV_PRTY_ID, MAX(GVN_NAME) GVN_NAME, MAX(MDL_NAME) MDL_NAME, MAX(FMLY_NAME) FMLY_NAME       

FROM  DB_T_PROD_CORE.INDIV_NAME       

WHERE EDW_END_DTTM= CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))       

GROUP BY INDIV_PRTY_ID)        

, PRTY_SCORE_HIERARCHY AS       

(SELECT A.PRTY_ID, A.MODL_NAME, max(LTRIM(B.PRTY_SCR_VAL))  AS PRTY_SCR_VAL      

FROM  ( SELECT PRTY_SCR.PRTY_ID, MAX(MODL_RUN.MODL_RUN_DTTM) MODL_RUN_DTTM,ANLTCL_MODL.MODL_NAME     

      FROM DB_T_PROD_CORE.PRTY_SCR, DB_T_PROD_CORE.MODL_RUN, DB_T_PROD_CORE.ANLTCL_MODL  

     WHERE PRTY_SCR.MODL_RUN_ID=MODL_RUN.MODL_RUN_ID  

     AND PRTY_SCR.MODL_ID=ANLTCL_MODL.MODL_ID  

     AND cast(MODL_RUN.MODL_RUN_DTTM as date) <CAST('':CAL_END_DT'' AS DATE)  

/*      AND EOM_DAY  BETWEEN MODL_RUN.MODL_RUN_STRT_DTTM AND MODL_RUN.MODL_RUN_END_DTTM  */
/*      AND EOM_DAY  BETWEEN ANLTCL_MODL.MODL_FROM_DTTM AND ANLTCL_MODL.MODL_TO_DTTM  */
     AND PRTY_SCR.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6)) 

     GROUP BY PRTY_SCR.PRTY_ID, ANLTCL_MODL.MODL_NAME ) A,  

     (SELECT PRTY_SCR.PRTY_ID, MODL_RUN.MODL_RUN_DTTM, ANLTCL_MODL.MODL_NAME,      

    CASE WHEN TO_NUMBER(PRTY_SCR_VAL) IS NULL THEN PRTY_SCR_VAL   

  ELSE CAST( PRTY_SCR_VAL AS INTEGER) END  PRTY_SCR_VAL     

      FROM DB_T_PROD_CORE.PRTY_SCR, DB_T_PROD_CORE.MODL_RUN, DB_T_PROD_CORE.ANLTCL_MODL  

     WHERE PRTY_SCR.MODL_RUN_ID=MODL_RUN.MODL_RUN_ID  

     AND PRTY_SCR.MODL_ID=ANLTCL_MODL.MODL_ID  

/*      AND EOM_DAY  BETWEEN MODL_RUN.MODL_RUN_STRT_DTTM AND MODL_RUN.MODL_RUN_END_DTTM  */
/*      AND EOM_DAY  BETWEEN ANLTCL_MODL.MODL_FROM_DTTM AND ANLTCL_MODL.MODL_TO_DTTM  */
     AND PRTY_SCR.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6)) ) B  

     WHERE A.PRTY_ID =B.PRTY_ID    AND A.MODL_NAME=B.MODL_NAME  AND A.MODL_RUN_DTTM=B.MODL_RUN_DTTM

     and a.MODL_NAME=''LEXIS NEXIS''

     group by A.PRTY_ID,  A.MODL_NAME)       

, AGMT_SCORE_HIERARCHY AS  ( SELECT A.AGMT_ID, A.MODL_RUN_DTTM, A.MODL_NAME, LTRIM(B.AGMT_SCR_VAL)  AS AGMT_SCR_VAL      

FROM ( SELECT AGMT_SCR.AGMT_ID, MAX(MODL_RUN.MODL_RUN_DTTM) MODL_RUN_DTTM,ANLTCL_MODL.MODL_NAME     

      FROM DB_T_PROD_CORE.AGMT_SCR, DB_T_PROD_CORE.MODL_RUN, DB_T_PROD_CORE.ANLTCL_MODL  

     WHERE AGMT_SCR.MODL_RUN_ID=MODL_RUN.MODL_RUN_ID  

     AND AGMT_SCR.MODL_ID=ANLTCL_MODL.MODL_ID  

AND cast(MODL_RUN.MODL_RUN_DTTM AS date) <CAST('':CAL_END_DT'' AS DATE) /* Hardcoded month end timestamp before which the scoring model was run   */
/*      AND EOM_DAY  BETWEEN MODL_RUN.MODL_RUN_STRT_DTTM AND MODL_RUN.MODL_RUN_END_DTTM  */
/*      AND EOM_DAY  BETWEEN ANLTCL_MODL.EDW_STRT_DTTM AND ANLTCL_MODL.EDW_END_DTTM  */
/*      AND EOM_DAY  BETWEEN AGMT_SCR.TRANS_STRT_DTTM AND AGMT_SCR.TRANS_END_DTTM  */
     GROUP BY AGMT_SCR.AGMT_ID, ANLTCL_MODL.MODL_NAME ) A,  

     (  SELECT AGMT_SCR.AGMT_ID, MODL_RUN.MODL_RUN_DTTM, ANLTCL_MODL.MODL_NAME,      

    CASE WHEN TO_NUMBER(AGMT_SCR.AGMT_SCR_VAL) IS NULL THEN AGMT_SCR.AGMT_SCR_VAL   

  ELSE CAST( AGMT_SCR.AGMT_SCR_VAL AS INTEGER) END  AGMT_SCR_VAL     

      FROM DB_T_PROD_CORE.AGMT_SCR, DB_T_PROD_CORE.MODL_RUN, DB_T_PROD_CORE.ANLTCL_MODL  

     WHERE AGMT_SCR.MODL_RUN_ID=MODL_RUN.MODL_RUN_ID  

     AND AGMT_SCR.MODL_ID=ANLTCL_MODL.MODL_ID  

/*     AND EOM_DAY  BETWEEN MODL_RUN.MODL_RUN_STRT_DTTM AND MODL_RUN.MODL_RUN_END_DTTM  */
/*     AND EOM_DAY  BETWEEN ANLTCL_MODL.EDW_STRT_DTTM AND ANLTCL_MODL.EDW_END_DTTM  */
/*     AND EOM_DAY  BETWEEN AGMT_SCR.TRANS_STRT_DTTM AND AGMT_SCR.TRANS_END_DTTM  */
      ) B WHERE A.AGMT_ID =B.AGMT_ID  AND A.MODL_NAME=B.MODL_NAME  AND A.MODL_RUN_DTTM=B.MODL_RUN_DTTM )      

, DRIVING_HISTORY AS       

( SELECT A.INDIV_PRTY_ID, A.DRVG_HIST_DTTM,  B.PNLTY_PNTS_CNT  , MAJ_CNVICTN_CNT, MINOR_CNVICTN_CNT, DUI_IND      

FROM ( SELECT INDIV_PRTY_ID, MAX(DRVG_HIST_DTTM) DRVG_HIST_DTTM  FROM DB_T_PROD_CORE.PRTY_DRVG_HIST  

        WHERE  

/* Hardcoded month end timestamp before which the scoring model was run  */
     PRTY_DRVG_HIST.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))  

     GROUP BY INDIV_PRTY_ID ) A,  

(SELECT INDIV_PRTY_ID, DRVG_HIST_DTTM, PNLTY_PNTS_CNT  , MAJ_CNVICTN_CNT, MINOR_CNVICTN_CNT, DUI_IND      

FROM DB_T_PROD_CORE.PRTY_DRVG_HIST  WHERE PRTY_DRVG_HIST.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6)) 

) B  WHERE A.INDIV_PRTY_ID =B.INDIV_PRTY_ID AND A.DRVG_HIST_DTTM=B.DRVG_HIST_DTTM )      

, SVC_CENTER AS  (       

SELECT DB_T_PROD_CORE.ORG_NAME , pa.agmt_ID      

FROM DB_T_PROD_CORE.ORG_NAME o, DB_T_PROD_CORE.PRTY_AGMT  pA      

WHERE o.PRTY_ID=PA.PRTY_ID      

 AND PA.PRTY_AGMT_ROLE_CD=  ''SVC''     

 AND CAST('':CAL_END_DT'' AS DATE)  BETWEEN CAST(pA.TRANS_STRT_DTTM AS DATE)  AND CAST(pA.TRANS_END_DTTM AS DATE)

/* AND o.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))      */
 )    

,  AGENT AS  (      

SELECT io.INTRNL_ORG_NUM , pa.AGMT_ID      

FROM DB_T_PROD_CORE.PRTY_AGMT pa, DB_T_PROD_CORE.INTRNL_ORG io      

WHERE pa.PRTY_ID=io.INTRNL_ORG_PRTY_ID      

 AND pa.PRTY_AGMT_ROLE_CD=''PRDA''     

 AND io.INTRNL_ORG_SBTYPE_CD=''PRDA'' 

 AND CAST('':CAL_END_DT'' AS DATE)  BETWEEN CAST(pA.TRANS_STRT_DTTM AS DATE)  AND CAST(pA.TRANS_END_DTTM AS DATE)     

/* AND io.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))      */
 )      

, PREV_CARRIER AS  (       

 SELECT MAX(DB_T_PROD_CORE.ORG_NAME) AS ORG_NAME , PRTY_RLTD.PRTY_ID      

FROM  DB_T_PROD_CORE.PRTY_RLTD, DB_T_PROD_CORE.ORG_NAME      

WHERE  PRTY_RLTD.RLTD_PRTY_ID=ORG_NAME.PRTY_ID      

 AND PRTY_RLTD.PRTY_RLTD_ROLE_CD=''PRIINSCAR''     

 AND CAST('':CAL_END_DT'' AS DATE) BETWEEN CAST(PRTY_RLTD.TRANS_STRT_DTTM AS DATE) AND CAST(PRTY_RLTD.TRANS_END_DTTM AS DATE)      

 AND ORG_NAME.EDW_END_DTTM =CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))        

 GROUP BY PRTY_RLTD.PRTY_ID  )       

,  MEMBERSHIP AS       

(SELECT m.MBRSHP_NUM, am.AGMT_ID  , m.MBRSHP_TYPE_CD       

FROM  DB_T_PROD_CORE.AGMT_MBRSHP am, DB_T_PROD_CORE.MBRSHP m      

WHERE am.MBRSHP_ID=m.MBRSHP_ID      

AND m.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6)))       

,  RATED_DRIVER AS       

( SELECT AGMT_ID, PRTY_ASSET_ID, MAX(PRTY_ID) PRTY_ID  FROM       

 DB_T_PROD_CORE.PRTY_AGMT_ASSET       

 WHERE PRTY_AGMT_ROLE_CD=''RTDDRVR''        

GROUP BY AGMT_ID, PRTY_ASSET_ID   )       

,  OCCUPATION AS       

( SELECT  INDIV_OCPTN.INDIV_PRTY_ID,  INDIV_OCPTN.OCPTN_TYPE_CD, OCPTN_TYPE.OCPTN_TYPE_DESC      

    FROM  DB_T_PROD_CORE.INDIV_OCPTN, DB_T_PROD_CORE.OCPTN_TYPE   

    WHERE   INDIV_OCPTN.OCPTN_TYPE_CD  =OCPTN_TYPE.OCPTN_TYPE_CD   

    AND INDIV_OCPTN.EDW_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6)))

/* Added below code for the defect # 16909 */
, DRIVER_EXCLUSIONS AS 

(SELECT   PRTY_ASSET_ID,AGMT_ID,FE_ID,

CASE WHEN F_ICTC=''DRVEXC'' THEN ''Y'' ELSE ''N'' END AS DRVEXC,

CASE WHEN F_ICTC=''DRVEXC25'' THEN ''Y'' ELSE ''N'' END AS DRVEXC25

FROM (SELECT DISTINCT NULL AS PRTY_ASSET_ID,AGMT_FEAT.AGMT_ID,AGMT_FEAT.FE_ID,FA.* 

    FROM (SELECT DISTINCT NULL AS PRTY_ASSET_ID,AGMT_FEAT.AGMT_ID,AGMT_FEAT.FEAT_ID AS FE_ID 

        FROM DB_T_PROD_CORE.AGMT_FEAT 

        minus 

        SELECT DISTINCT NULL AS PRTY_ASSET_ID  ,AGMT_INSRD_ASSET_FEAT.AGMT_ID  ,AGMT_INSRD_ASSET_FEAT.FEAT_ID AS FE_ID

        FROM AGMT_INSRD_ASSET_FEAT) AS AGMT_FEAT

        INNER JOIN (SELECT DISTINCT F.FEAT_ID AS F_ID,F.FEAT_SBTYPE_CD AS F_SB_CD,F.INSRNC_CVGE_TYPE_CD AS F_ICTC,F.COMN_FEAT_NAME FROM DB_T_PROD_CORE.FEAT F

            where F.FEAT_INSRNC_SBTYPE_CD = ''EXCLSN''  AND F.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

            /*   AND F.FEAT_SBTYPE_CD =''CL''*/

) FA ON AGMT_FEAT.FE_ID = FA.F_ID

        UNION ALL

        SELECT DISTINCT AGAS.PRTY_ASSET_ID,AIAF.AGMT_ID,AIAF.FEAT_ID AS FE_ID,FA.*

        FROM DB_T_PROD_CORE.AGMT_ASSET AGAS

        INNER JOIN DB_T_PROD_CORE.AGMT_INSRD_ASSET_FEAT AIAF ON AGAS.AGMT_ID = AIAF.AGMT_ID

        AND AGAS.PRTY_ASSET_ID = AIAF.PRTY_ASSET_ID 

        INNER JOIN (SELECT DISTINCT F.FEAT_ID AS F_ID,F.FEAT_SBTYPE_CD AS F_SB_CD,F.INSRNC_CVGE_TYPE_CD AS F_ICTC,F.COMN_FEAT_NAME FROM DB_T_PROD_CORE.FEAT F

            where F.FEAT_INSRNC_SBTYPE_CD = ''EXCLSN''  AND F.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

) FA ON AIAF.FEAT_ID = FA.F_ID

) Z qualify row_number() OVER (PARTITION BY Z.AGMT_ID,F_ICTC,Z.PRTY_ASSET_ID ORDER BY Z.F_ID DESC) = 1)  



SELECT DISTINCT           

AGMT.HOST_AGMT_NUM  AS PLCY_NBR           

,TRIM(AGMT.HOST_AGMT_NUM)||TRIM(MOTR_VEH.MOTR_VEH_SER_NUM) AS PLCY_VEH_KEY           

,AGMT.MODL_EFF_DTTM  AS PLCY_CHG_EFF_DT           

,AGMT.MODL_ACTL_END_DTTM AS PLCY_CHG_EXP_DT           

,AGMT.AGMT_PLND_EXPN_DTTM AS PLCY_PLN_EXP_DT           

,EVV.EV_ACTVY_TYPE_CD  AS PLCY_EFF_TYPE_CD           

,AGMT_ASSET.AGMT_ASSET_STRT_DTTM   AS VEH_CHG_EFF_DT           

,AGMT_ASSET.AGMT_ASSET_END_DTTM   AS VEH_CHG_EXP_DT           

,RATED_DRIVER.PRTY_ID AS DRV_SKEY           

,STATE  AS RSK_ST_CD           

,XREF.ASSET_DTL_TXT AS RSK_TERR_CD           

,VEH_RISK_LOCATION.ZIP  AS RSK_POSTAL_CD           

,COALESCE(           

(SELECT  MAX(RATE_SYMB_CD  )  FROM  PRTY_ASSET_COVERAGES WHERE PRTY_ASSET_ID=MOTR_VEH.PRTY_ASSET_ID AND AGMT_ID=AGMT.AGMT_ID AND INSRNC_CVGE_TYPE_CD=''COMP'' )  ,      

(SELECT  MAX(RATE_SYMB_CD  ) FROM  PRTY_ASSET_COVERAGES WHERE PRTY_ASSET_ID=MOTR_VEH.PRTY_ASSET_ID AND AGMT_ID=AGMT.AGMT_ID AND INSRNC_CVGE_TYPE_CD=''COLL'' ))  AS PA_SYM_CD      

,( SELECT  MAX(MOTR_VEH_DTL.ANNUAL_DSTC_MEAS)FROM DB_T_PROD_CORE.MOTR_VEH_DTL            

WHERE MOTR_VEH_DTL.PRTY_ASSET_ID=MOTR_VEH.PRTY_ASSET_ID          

 AND  MOTR_VEH_DTL.EDW_END_DTTM=  CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP_NTZ(6))   ) ANN_MILE_DESC         

, AGMT. AGMT_EFF_DTTM  AS PLCY_OGN_EFF_DT           

,AGMT.AGMT_OPN_DTTM  AS PLCY_OGN_IPT_DT          

, EXTRACT(YEAR FROM CAST('':CAL_END_DT'' AS DATE)) - EXTRACT(YEAR FROM AGMT.CNTNUS_SRVC_DTTM) AS YEARS_WITH_ALFA          

,( SELECT MAX(INTRNL_ORG_NUM) FROM   DB_T_PROD_CORE.PRTY_AGMT

    JOIN DB_T_PROD_CORE.INTRNL_ORG ON PRTY_AGMT.PRTY_ID=INTRNL_ORG.INTRNL_ORG_PRTY_ID AND INTRNL_ORG.EDW_END_DTTM=''9999-12-31 23:59:59.999999''           

    WHERE           

/* PRTY_AGMT.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' AND            */
 CAST('':CAL_END_DT'' AS DATE)  BETWEEN CAST(PRTY_AGMT.TRANS_STRT_DTTM AS DATE)  AND CAST(PRTY_AGMT.TRANS_END_DTTM AS DATE)  AND

PRTY_AGMT_ROLE_CD=''CMP'' AND INTRNL_ORG_SBTYPE_CD=''CO'' AND PRTY_AGMT.AGMT_ID=AGMT.AGMT_ID ) AS MASTER_COMP_NUM           

,(SELECT  MAX(VEH_MFGR_NAME ) FROM   DB_T_PROD_CORE.MOTR_VEH WHERE MOTR_VEH.PRTY_ASSET_ID=AGMT_ASSET. PRTY_ASSET_ID) VEH_TYPE_DESC          

,MOTR_VEH.MFG_YR_NUM "YEAR"           

/* ,MOTR_VEH.VEH_MFGR_CD MAKE            */
/* ,MOTR_VEH.MODL_NAME MODEL  */
,(SELECT  MAX(MOTR_VEH_TYPE_CD ) FROM   DB_T_PROD_CORE.MOTR_VEH WHERE MOTR_VEH.PRTY_ASSET_ID=AGMT_ASSET. PRTY_ASSET_ID) VEH_TYPE_CD          

,SUM(ASSET_VAL.ASSET_VAL_AMT) AS VEH_CST_NEW_AMT           

,DRIVER_DETAILS.GNDR_TYPE_CD AS GENDER_CD              

/* ,OCCUPATION.OCPTN_TYPE_CD  DRV_OCCUPATION            */
,OCCUPATION.OCPTN_TYPE_DESC  DRV_OCCUPATION_DESC           

,DRIVER_DETAILS.BIRTH_DT   AS CLIENT_DOB           

, EXTRACT(YEAR FROM CAST('':CAL_END_DT'' AS DATE)) - EXTRACT(YEAR FROM DRIVER_DETAILS.BIRTH_DT) AS CLIENT_AGE          

,( SELECT MAX( INDIV_MRTL_STS.MRTL_STS_CD  )  FROM  DB_T_PROD_CORE.INDIV_MRTL_STS WHERE INDIV_MRTL_STS.INDIV_PRTY_ID=RATED_DRIVER.PRTY_ID )  AS MARITAL_STATUS_CD           

,(SELECT MAX(ASSET_DTL_TYPE.ASSET_DTL_DESC) FROM ASSET_DETAIL                  

JOIN DB_T_PROD_CORE.ASSET_DTL_TYPE ON ASSET_DETAIL.ASSET_DTL_CD=ASSET_DTL_TYPE.ASSET_DTL_CD                   

WHERE ASSET_DETAIL.ASSET_DTL_SCHM_TYPE_CD=''VEHUSE'' AND    PRTY_ASSET_ID=MOTR_VEH.PRTY_ASSET_ID)  AS VEH_USE_CD         

,AGMT.CNTNUS_SRVC_DTTM  AS CLIENT_EFF_DT            

, 0 AS NBR_MILES_WORK           

/* removed  code for defect 19119 ID 000030 START           

,( SELECT MAX(AGMT_SCR_VAL  )         FROM AGMT_SCORE_HIERARCHY          WHERE MODL_NAME=''LVP''           AND AGMT_ID=AGMT.AGMT_ID) AS INS_SCR1         

,( SELECT MAX(AGMT_SCR_VAL  )         FROM AGMT_SCORE_HIERARCHY          WHERE MODL_NAME=''ARS''           AND AGMT_ID=AGMT.AGMT_ID) AS INS_SCR2

removed  code for defect 19119 ID 000030 END*/

/* added  code for defect 19119 ID 000030 START */
,( SELECT MAX(PRTY_SCR_VAL) FROM PRTY_SCORE_HIERARCHY  WHERE MODL_NAME=''LEXIS NEXIS'' AND PRIINSURED_PRTY.PRTY_AGMT_ROLE_CD =''PLCYPRININS''AND PRTY_ID=PRIINSURED_PRTY.PRTY_ID) AS INS_SCR1         

,( SELECT MAX(AGMT_SCR_VAL  )   FROM AGMT_SCORE_HIERARCHY  WHERE MODL_NAME=''ARS''  AND AGMT_ID=AGMT.AGMT_ID) AS INS_SCR2

/* added  code for defect 19119 ID 000030 END           */
,DRIVING_HISTORY.PNLTY_PNTS_CNT  AS PA_POINTS_NBR           

,0 AS NBR_SPEED_VIOLNS            

,AGMT.AGMT_ID AS DW_PLCY_SKEY           

,DB_T_PROD_CORE.ORG_NAME AS PLCY_SVC_NBR           

,AGENT.INTRNL_ORG_NUM AS SALES_AGENCY_NBR           

,DB_T_PROD_CORE.ORG_NAME  AS  PTY_INS_CARRIER_CD           

,DB_T_PROD_CORE.ORG_NAME  AS  PTY_INS_CARRIER_NM           

,PRIINSURED_DETAILS.GNDR_TYPE_CD AS NM_INSUR_GENDER_CD           

,PRIINSURED_DETAILS.BIRTH_DT AS NM_INSUR_DOB           

, EXTRACT(YEAR FROM CAST('':CAL_END_DT'' AS DATE)) - EXTRACT(YEAR FROM PRIINSURED_DETAILS.BIRTH_DT) AS NM_INSUR_AGE          

 ,( SELECT MAX(INDIV_MRTL_STS.MRTL_STS_CD  ) FROM  DB_T_PROD_CORE.INDIV_MRTL_STS WHERE INDIV_MRTL_STS.INDIV_PRTY_ID=PRIINSURED_PRTY.PRTY_ID) AS   NM_INSUR_MARITAL_STATUS_CD            

,( SELECT  MAX(MBRSHP_TYPE_CD)   FROM  MEMBERSHIP  WHERE  AGMT_ID=AGMT.AGMT_ID) MEMBER_TYPE                     

,(  SELECT  MAX(MBRSHP_NUM )  FROM MEMBERSHIP WHERE  AGMT_ID=AGMT.AGMT_ID) MEMBER_NUMBER          

,PRIINSURED_PRTY.PRTY_ID AS NM_INSUR_SKEY           

/* Added below code for the defect # 16909 */
,COALESCE(DRVEXC,''N'') AS DRVEXC                                     

,COALESCE(DRVEXC25,''N'') AS DRVEXC25  

,( SELECT  MAX(MOTR_VEH_TYPE_CD ) FROM DB_T_PROD_CORE.MOTR_VEH WHERE MOTR_VEH.PRTY_ASSET_ID=AGMT_ASSET.PRTY_ASSET_ID) PA_SYM_CD_2 

,CAST((EXTRACT(YEAR FROM CAST('':CAL_END_DT'' AS DATE)) * 100 + EXTRACT(MONTH FROM CAST('':CAL_END_DT'' AS DATE))) AS INTEGER) AS MO_ID

FROM (SELECT * FROM 

(SELECT  PPV.HOST_AGMT_NUM,PPV.AGMT_ID,PPV.AGMT_SRC_CD,MODL_CRTN_DTTM,  A_S.AGMT_STS_CD,A_S.AGMT_STS_RSN_CD,

CASE WHEN A_S.AGMT_STS_CD = ''CNCLD''  AND A_S.AGMT_STS_RSN_CD = ''CHGUWCMPY'' THEN ''Y'' END AS C2C_CANC_IND ,PPV.AGMT_EFF_DTTM,

PPV.AGMT_SIGND_DTTM,PPV.MODL_ACTL_END_DTTM,PPV.MODL_EFF_DTTM,PPV.CNTNUS_SRVC_DTTM,PPV.AGMT_PLND_EXPN_DTTM,AGMT_OPN_DTTM

FROM (SELECT  T1.HOST_AGMT_NUM,T1.TERM_NUM,T1.AGMT_ID,T1.MODL_CRTN_DTTM,T1.AGMT_SRC_CD,

  T1.MODL_EFF_DTTM,T1.AGMT_EFF_DTTM,T1.AGMT_SIGND_DTTM,T1.MODL_ACTL_END_DTTM,T1.CNTNUS_SRVC_DTTM,

  T1.AGMT_PLND_EXPN_DTTM,T1.AGMT_OPN_DTTM,

CASE WHEN T1.MODL_EFF_DTTM > T1.MODL_CRTN_DTTM THEN T1.MODL_EFF_DTTM ELSE T1.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM

FROM  DB_T_PROD_CORE.AGMT T1 WHERE   T1.AGMT_TYPE_CD = ''PPV''  AND T1.SRC_SYS_CD = ''GWPC'' 

 AND CAST('':CAL_END_DT'' AS DATE)  BETWEEN CAST(AGMT_EFF_DTTM AS DATE) AND CAST(AGMT_PLND_EXPN_DTTM AS DATE)

AND T1.TRANS_STRT_DTTM = (SELECT  MIN(T2.TRANS_STRT_DTTM) FROM  DB_T_PROD_CORE.AGMT T2 WHERE   T1.AGMT_ID = T2.AGMT_ID) 

 AND CAST(NEW_AGMT_EFF_DTTM AS DATE) <=  CAST('':CAL_END_DT'' AS DATE)  ) PPV 

INNER JOIN 

(SELECT  HOST_AGMT_NUM, TERM_NUM,AGMT_ID FROM  DB_T_PROD_CORE.AGMT WHERE   AGMT_TYPE_CD = ''POLTRM'' 

 AND CAST('':CAL_END_DT'' AS DATE)  BETWEEN CAST(AGMT_EFF_DTTM AS DATE) AND CAST(AGMT_PLND_EXPN_DTTM AS DATE) GROUP   BY 1,2,3) TRM 

 ON  PPV.HOST_AGMT_NUM = TRM.HOST_AGMT_NUM  AND PPV.TERM_NUM = TRM.TERM_NUM  

INNER JOIN  DB_T_PROD_CORE.AGMT_STS A_S 

 ON  TRM.AGMT_ID = A_S.AGMT_ID   AND CAST(A_S.AGMT_STS_STRT_DTTM AS DATE) <= CAST('':CAL_END_DT'' AS DATE)   AND A_S.AGMT_STS_CD <> ''CNFRMDDT'' 

QUALIFY ROW_NUMBER() OVER(PARTITION BY PPV.AGMT_ID ORDER   BY A_S.AGMT_STS_STRT_DTTM DESC) = 1 

)  A  QUALIFY ROW_NUMBER() OVER(PARTITION BY HOST_AGMT_NUM ORDER   BY  CASE WHEN (AGMT_STS_CD=''INFORCE'') THEN 1 ELSE 2 END ,MODL_CRTN_DTTM DESC ) = 1) AGMT          

JOIN DB_T_PROD_CORE.AGMT_PROD  ON AGMT.AGMT_ID=AGMT_PROD.AGMT_ID AND AGMT_PROD.EDW_END_DTTM=''9999-12-31 23:59:59.999999''         

and AGMT_STS_CD=''INFORCE''

JOIN DB_T_PROD_CORE.PROD  ON AGMT_PROD.PROD_ID=PROD.PROD_ID AND PROD.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

 and PROD.PROD_NAME IN (''PPV'', ''AUTO'',''PPV2'', ''COMMERCIAL'', ''PERSONAL AUTO'') 

 JOIN DB_T_PROD_CORE.AGMT_ASSET ON AGMT.AGMT_ID=AGMT_ASSET.AGMT_ID 

 AND CAST(AGMT_ASSET.TRANS_STRT_DTTM AS DATE)<=CAST('':CAL_END_DT'' AS DATE) AND CAST(AGMT_ASSET.TRANS_END_DTTM AS DATE)>CAST('':CAL_END_DT'' AS DATE)

/* AND AGMT_ASSET.EDW_END_DTTM=''9999-12-31 23:59:59.999999''        */
LEFT JOIN DB_T_PROD_CORE.MOTR_VEH  ON AGMT_ASSET.PRTY_ASSET_ID=MOTR_VEH.PRTY_ASSET_ID AND MOTR_VEH.EDW_END_DTTM=''9999-12-31 23:59:59.999999''        

/*    ON AGMT.AGMT_ID=PRTY_AGMT.AGMT_ID AND PRTY_AGMT.PRTY_AGMT_ROLE_CD=''PLCYDRVR'' AND PRTY_AGMT.EDW_END_DTTM =''9999-12-31 23:59:59.999999''           */
/* Added below code for the defect # 16909 */
LEFT OUTER JOIN DRIVER_EXCLUSIONS ON  DRIVER_EXCLUSIONS.AGMT_ID=AGMT.AGMT_ID AND DRIVER_EXCLUSIONS.PRTY_ASSET_ID=AGMT_ASSET.PRTY_ASSET_ID

LEFT JOIN LOCATION_ADDRESS  VEH_RISK_LOCATION  ON  VEH_RISK_LOCATION.PRTY_ASSET_ID= MOTR_VEH.PRTY_ASSET_ID         

LEFT OUTER JOIN DB_T_PROD_CORE.ASSET_DTL_CD_XREF XREF ON AGMT_ASSET.PRTY_ASSET_ID=XREF.PRTY_ASSET_ID AND XREF.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' AND XREF.ASSET_DTL_CD in (''HOTC'',''TC'')            

LEFT OUTER  JOIN DB_T_PROD_CORE.ASSET_DTL_TYPE TL ON XREF.ASSET_DTL_CD=TL.ASSET_DTL_CD AND TL.ASSET_DTL_SCHM_TYPE_CD = ''TERR''           

LEFT OUTER  JOIN DB_T_PROD_CORE.ASSET_VAL on ASSET_VAL.PRTY_ASSET_ID=MOTR_VEH.PRTY_ASSET_ID and ASSET_VAL.ASSET_VALUT_AMT_CD=''NCA''           

LEFT JOIN DB_T_PROD_CORE.PRTY_AGMT AS PRIINSURED_PRTY ON AGMT.AGMT_ID=PRIINSURED_PRTY.AGMT_ID AND PRIINSURED_PRTY.PRTY_AGMT_ROLE_CD=''PLCYPRININS'' AND PRIINSURED_PRTY.EDW_END_DTTM=''9999-12-31 23:59:59.999999''           

LEFT JOIN  DB_T_PROD_CORE.INDIV  AS PRIINSURED_DETAILS  ON PRIINSURED_PRTY.PRTY_ID=PRIINSURED_DETAILS.INDIV_PRTY_ID  AND PRIINSURED_DETAILS.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT JOIN(SELECT EV_ACTVY_TYPE_CD,HOST_AGMT_NUM FROM  DB_T_PROD_CORE.AGMT POL

JOIN DB_T_PROD_CORE.EV EVV ON EVV.AGMT_ID=POL.AGMT_ID    AND EVV.EV_SBTYPE_CD=''PLCYTRNS'' 

 AND POL.AGMT_TYPE_CD=''POL'' AND POL.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

   AND EVV.EV_DTTM<=CAST('':CAL_END_DT'' AS DATE)

   QUALIFY ROW_NUMBER() OVER(PARTITION BY HOST_AGMT_NUM ORDER BY EVV.EDW_STRT_DTTM DESC)=1

)EVV ON EVV.HOST_AGMT_NUM=AGMT.HOST_AGMT_NUM

LEFT JOIN ( SELECT INDIV_OCPTN.INDIV_PRTY_ID, MAX(INDIV_OCPTN.OCPTN_TYPE_CD) OCPTN_TYPE_CD, MAX(OCPTN_TYPE.OCPTN_TYPE_DESC) OCPTN_TYPE_DESC       

            FROM  DB_T_PROD_CORE.INDIV_OCPTN, DB_T_PROD_CORE.OCPTN_TYPE   

            WHERE  INDIV_OCPTN.OCPTN_TYPE_CD  =OCPTN_TYPE.OCPTN_TYPE_CD   

            AND  INDIV_OCPTN.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

           GROUP BY INDIV_OCPTN.INDIV_PRTY_ID) PRIINSURED_OCCUP    

 ON PRIINSURED_OCCUP.INDIV_PRTY_ID=PRIINSURED_PRTY.PRTY_ID         

LEFT JOIN RATED_DRIVER  ON  RATED_DRIVER.AGMT_ID=AGMT.AGMT_ID  AND MOTR_VEH.PRTY_ASSET_ID =RATED_DRIVER.PRTY_ASSET_ID           

LEFT JOIN  DRIVING_HISTORY  ON DRIVING_HISTORY.INDIV_PRTY_ID=PRIINSURED_PRTY.PRTY_ID         

LEFT JOIN SVC_CENTER ON SVC_CENTER.AGMT_ID = AGMT.AGMT_ID           

LEFT JOIN AGENT ON AGENT.AGMT_ID = AGMT.AGMT_ID           

LEFT JOIN PREV_CARRIER ON PREV_CARRIER.PRTY_ID =PRIINSURED_PRTY.PRTY_ID           

LEFT JOIN  DB_T_PROD_CORE.INDIV  AS DRIVER_DETAILS ON DRIVER_DETAILS.INDIV_PRTY_ID=RATED_DRIVER.PRTY_ID and DRIVER_DETAILS.edw_end_dttm =''9999-12-31 23:59:59.999999''  

LEFT JOIN OCCUPATION ON OCCUPATION.INDIV_PRTY_ID=RATED_DRIVER.PRTY_ID

/* added  code for defect 19119 ID 000030 START */
left join DB_T_PROD_CORE.PRTY_AGMT  on PRTY_AGMT.AGMT_ID = AGMT.AGMT_ID

/* where plcy_nbr =''19000107143'' */
and PRTY_AGMT.PRTY_AGMT_ROLE_CD =''PLCYPRININS''

GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
) SRC
)
);


-- Component exp_passthrough, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_passthrough AS
(
SELECT
sq_edw_eblm_plcy_veh.PLCY_NBR as PLCY_NBR,
sq_edw_eblm_plcy_veh.PLCY_VEH_KEY as PLCY_VEH_KEY,
sq_edw_eblm_plcy_veh.PLCY_CHG_EFF_DT as PLCY_CHG_EFF_DT,
sq_edw_eblm_plcy_veh.PLCY_CHG_EXP_DT as PLCY_CHG_EXP_DT,
sq_edw_eblm_plcy_veh.PLCY_PLN_EXP_DT as PLCY_PLN_EXP_DT,
sq_edw_eblm_plcy_veh.PLCY_EFF_TYPE_CD as PLCY_EFF_TYPE_CD,
sq_edw_eblm_plcy_veh.VEH_CHG_EFF_DT as VEH_CHG_EFF_DT,
sq_edw_eblm_plcy_veh.VEH_CHG_EXP_DT as VEH_CHG_EXP_DT,
sq_edw_eblm_plcy_veh.DRV_SKEY as DRV_SKEY,
sq_edw_eblm_plcy_veh.RSK_ST_CD as RSK_ST_CD,
sq_edw_eblm_plcy_veh.RSK_TERR_CD as RSK_TERR_CD,
sq_edw_eblm_plcy_veh.RSK_POSTAL_CD as RSK_POSTAL_CD,
sq_edw_eblm_plcy_veh.PA_SYM_CD as PA_SYM_CD,
sq_edw_eblm_plcy_veh.ANN_MILE_DESC as ANN_MILE_DESC,
sq_edw_eblm_plcy_veh.PLCY_OGN_EFF_DT as PLCY_OGN_EFF_DT,
sq_edw_eblm_plcy_veh.PLCY_OGN_IPT_DT as PLCY_OGN_IPT_DT,
sq_edw_eblm_plcy_veh.YEARS_WITH_ALFA as YEARS_WITH_ALFA,
sq_edw_eblm_plcy_veh.MASTER_COMPANY_NBR as MASTER_COMPANY_NBR,
sq_edw_eblm_plcy_veh.VEH_MAKE_DESC as VEH_MAKE_DESC,
sq_edw_eblm_plcy_veh.VEH_MODEL_YR as VEH_MODEL_YR,
sq_edw_eblm_plcy_veh.VEH_TYPE_CD as VEH_TYPE_CD,
sq_edw_eblm_plcy_veh.VEH_CST_NEW_AMT as VEH_CST_NEW_AMT,
sq_edw_eblm_plcy_veh.GENDER_CD as GENDER_CD,
sq_edw_eblm_plcy_veh.OCP_DESC as OCP_DESC,
sq_edw_eblm_plcy_veh.CLIENT_DOB as CLIENT_DOB,
sq_edw_eblm_plcy_veh.CLIENT_AGE as CLIENT_AGE,
sq_edw_eblm_plcy_veh.MARITAL_STATUS_CD as MARITAL_STATUS_CD,
sq_edw_eblm_plcy_veh.VEH_USE_CD as VEH_USE_CD,
sq_edw_eblm_plcy_veh.CLIENT_EFF_DT as CLIENT_EFF_DT,
sq_edw_eblm_plcy_veh.NBR_MILES_WORK as NBR_MILES_WORK,
sq_edw_eblm_plcy_veh.INS_SCR1 as INS_SCR1,
sq_edw_eblm_plcy_veh.INS_SCR2 as INS_SCR2,
sq_edw_eblm_plcy_veh.PA_POINTS_NBR as PA_POINTS_NBR,
sq_edw_eblm_plcy_veh.NBR_SPEED_VIOLNS as NBR_SPEED_VIOLNS,
sq_edw_eblm_plcy_veh.DW_PLCY_SKEY as DW_PLCY_SKEY,
sq_edw_eblm_plcy_veh.PLCY_SVC_NBR as PLCY_SVC_NBR,
sq_edw_eblm_plcy_veh.SALES_AGENCY_NBR as SALES_AGENCY_NBR,
sq_edw_eblm_plcy_veh.PTY_INS_CARRIER_CD as PTY_INS_CARRIER_CD,
sq_edw_eblm_plcy_veh.PTY_INS_CARRIER_NM as PTY_INS_CARRIER_NM,
sq_edw_eblm_plcy_veh.NM_INSUR_GENDER_CD as NM_INSUR_GENDER_CD,
sq_edw_eblm_plcy_veh.NM_INSUR_DOB as NM_INSUR_DOB,
sq_edw_eblm_plcy_veh.NM_INSUR_AGE as NM_INSUR_AGE,
sq_edw_eblm_plcy_veh.NM_INSUR_MARITAL_STATUS_CD as NM_INSUR_MARITAL_STATUS_CD,
sq_edw_eblm_plcy_veh.NM_INSUR_MEMB_TYPE as NM_INSUR_MEMB_TYPE,
sq_edw_eblm_plcy_veh.NM_INSUR_MEMB_NBR as NM_INSUR_MEMB_NBR,
sq_edw_eblm_plcy_veh.NM_INSUR_SKEY as NM_INSUR_SKEY,
sq_edw_eblm_plcy_veh.DRVEXC as DRVEXC,
sq_edw_eblm_plcy_veh.DRVEXC25 as DRVEXC25,
sq_edw_eblm_plcy_veh.PA_SYM_CD_2 as PA_SYM_CD_2,
sq_edw_eblm_plcy_veh.MO_ID as MO_ID,
:PRCS_ID as prcs_id,
CURRENT_TIMESTAMP as load_dt,
sq_edw_eblm_plcy_veh.source_record_id
FROM
sq_edw_eblm_plcy_veh
);


-- Component tgt_edw_eblm_plcy_veh, Type TARGET 
INSERT INTO DB_T_PROD_WRK.EDW_EBLM_PLCY_VEH
(
PLCY_NBR,
PLCY_VEH_KEY,
PLCY_CHG_EFF_DT,
PLCY_CHG_EXP_DT,
PLCY_PLN_EXP_DT,
PLCY_EFF_TYPE_CD,
VEH_CHG_EFF_DT,
VEH_CHG_EXP_DT,
DRV_SKEY,
RSK_ST_CD,
RSK_TERR_CD,
RSK_POSTAL_CD,
PA_SYM_CD,
ANN_MILE_DESC,
PLCY_OGN_EFF_DT,
PLCY_OGN_IPT_DT,
YEARS_WITH_ALFA,
MASTER_COMPANY_NBR,
VEH_MAKE_DESC,
VEH_MODEL_YR,
VEH_TYPE_CD,
VEH_CST_NEW_AMT,
GENDER_CD,
OCP_DESC,
CLIENT_DOB,
CLIENT_AGE,
MARITAL_STATUS_CD,
VEH_USE_CD,
CLIENT_EFF_DT,
NBR_MILES_WORK,
INS_SCR1,
INS_SCR2,
PA_POINTS_NBR,
NBR_SPEED_VIOLNS,
DW_PLCY_SKEY,
PLCY_SVC_NBR,
SALES_AGENCY_NBR,
PTY_INS_CARRIER_CD,
PTY_INS_CARRIER_NM,
NM_INSUR_GENDER_CD,
NM_INSUR_DOB,
NM_INSUR_AGE,
NM_INSUR_MARITAL_STATUS_CD,
NM_INSUR_MEMB_TYPE,
NM_INSUR_MEMB_NBR,
NM_INSUR_SKEY,
DRVEXC,
DRVEXC25,
PRCS_ID,
LOAD_DT,
PA_SYM_CD_2,
MO_ID
)
SELECT
exp_passthrough.PLCY_NBR as PLCY_NBR,
exp_passthrough.PLCY_VEH_KEY as PLCY_VEH_KEY,
exp_passthrough.PLCY_CHG_EFF_DT as PLCY_CHG_EFF_DT,
exp_passthrough.PLCY_CHG_EXP_DT as PLCY_CHG_EXP_DT,
exp_passthrough.PLCY_PLN_EXP_DT as PLCY_PLN_EXP_DT,
exp_passthrough.PLCY_EFF_TYPE_CD as PLCY_EFF_TYPE_CD,
exp_passthrough.VEH_CHG_EFF_DT as VEH_CHG_EFF_DT,
exp_passthrough.VEH_CHG_EXP_DT as VEH_CHG_EXP_DT,
exp_passthrough.DRV_SKEY as DRV_SKEY,
exp_passthrough.RSK_ST_CD as RSK_ST_CD,
exp_passthrough.RSK_TERR_CD as RSK_TERR_CD,
exp_passthrough.RSK_POSTAL_CD as RSK_POSTAL_CD,
exp_passthrough.PA_SYM_CD as PA_SYM_CD,
exp_passthrough.ANN_MILE_DESC as ANN_MILE_DESC,
exp_passthrough.PLCY_OGN_EFF_DT as PLCY_OGN_EFF_DT,
exp_passthrough.PLCY_OGN_IPT_DT as PLCY_OGN_IPT_DT,
exp_passthrough.YEARS_WITH_ALFA as YEARS_WITH_ALFA,
exp_passthrough.MASTER_COMPANY_NBR as MASTER_COMPANY_NBR,
exp_passthrough.VEH_MAKE_DESC as VEH_MAKE_DESC,
exp_passthrough.VEH_MODEL_YR as VEH_MODEL_YR,
exp_passthrough.VEH_TYPE_CD as VEH_TYPE_CD,
exp_passthrough.VEH_CST_NEW_AMT as VEH_CST_NEW_AMT,
exp_passthrough.GENDER_CD as GENDER_CD,
exp_passthrough.OCP_DESC as OCP_DESC,
exp_passthrough.CLIENT_DOB as CLIENT_DOB,
exp_passthrough.CLIENT_AGE as CLIENT_AGE,
exp_passthrough.MARITAL_STATUS_CD as MARITAL_STATUS_CD,
exp_passthrough.VEH_USE_CD as VEH_USE_CD,
exp_passthrough.CLIENT_EFF_DT as CLIENT_EFF_DT,
exp_passthrough.NBR_MILES_WORK as NBR_MILES_WORK,
exp_passthrough.INS_SCR1 as INS_SCR1,
exp_passthrough.INS_SCR2 as INS_SCR2,
exp_passthrough.PA_POINTS_NBR as PA_POINTS_NBR,
exp_passthrough.NBR_SPEED_VIOLNS as NBR_SPEED_VIOLNS,
exp_passthrough.DW_PLCY_SKEY as DW_PLCY_SKEY,
exp_passthrough.PLCY_SVC_NBR as PLCY_SVC_NBR,
exp_passthrough.SALES_AGENCY_NBR as SALES_AGENCY_NBR,
exp_passthrough.PTY_INS_CARRIER_CD as PTY_INS_CARRIER_CD,
exp_passthrough.PTY_INS_CARRIER_NM as PTY_INS_CARRIER_NM,
exp_passthrough.NM_INSUR_GENDER_CD as NM_INSUR_GENDER_CD,
exp_passthrough.NM_INSUR_DOB as NM_INSUR_DOB,
exp_passthrough.NM_INSUR_AGE as NM_INSUR_AGE,
exp_passthrough.NM_INSUR_MARITAL_STATUS_CD as NM_INSUR_MARITAL_STATUS_CD,
exp_passthrough.NM_INSUR_MEMB_TYPE as NM_INSUR_MEMB_TYPE,
exp_passthrough.NM_INSUR_MEMB_NBR as NM_INSUR_MEMB_NBR,
exp_passthrough.NM_INSUR_SKEY as NM_INSUR_SKEY,
exp_passthrough.DRVEXC as DRVEXC,
exp_passthrough.DRVEXC25 as DRVEXC25,
exp_passthrough.prcs_id as PRCS_ID,
exp_passthrough.load_dt as LOAD_DT,
exp_passthrough.PA_SYM_CD_2 as PA_SYM_CD_2,
exp_passthrough.MO_ID as MO_ID
FROM
exp_passthrough;


END; ';