-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_WRK_EDW_EBLM_PREM_TRANS_SUMMARY_EXTRACT("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
  PRCS_ID STRING;
BEGIN
  SELECT 
    TRY_PARSE_JSON(:param_json):PRCS_ID::STRING
  INTO
    PRCS_ID;

-- Component SQ_AGMT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGMT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as HOST_AGMT_NUM,
$2 as AGMT_ID,
$3 as AGMT_OPN_DTTM,
$4 as MODL_ACTL_END_DTTM,
$5 as AGMT_PLND_EXPN_DTTM,
$6 as PRTY_ASSET_ID,
$7 as MOTR_VEH_SER_NUM,
$8 as INSRNC_CVGE_TYPE_CD,
$9 as MBRSHP_NUM,
$10 as MBRSHP_TYPE_CD,
$11 as PLCY_AMT,
$12 as PLCY_AMT1,
$13 as AGMT_CURY_PLCY_AMT,
$14 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH  PLCY_ASSET_COVERAGES AS

(

SELECT  AGMT.AGMT_ID, AGMT.HOST_AGMT_NUM, PRTY_ASSET.PRTY_ASSET_ID, RATE_SYMB_CD  , f.INSRNC_CVGE_TYPE_CD, AGMT.AGMT_EFF_DTTM,

AGMT.MODL_ACTL_END_DTTM,

AGMT.AGMT_PLND_EXPN_DTTM,

CASE 

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f2.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f4.FEAT_NAME

END TERM_NAME, 

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.FEAT_ID

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.FEAT_ID

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.FEAT_ID

END COV_FEAT_ID,

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.FEAT_NAME

END COV_NAME, 

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.NK_SRC_KEY

END COV_PATTERNCODE, 

CASE WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f2.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f4.NK_SRC_KEY

END TERM_PATTERNCODE, 

CASE 

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN CAST(f.FEAT_DTL_VAL AS DECIMAL(18,4)) 

WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN CAST(f.FEAT_DTL_VAL AS DECIMAL(18,4)) 

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN  f.FEAT_DTL_CD_NAME

END VAL

 ,CASE WHEN NB.AGMT_ID IS NOT NULL THEN ''Y'' ELSE ''N'' END AS NB_IND  

FROM DB_T_PROD_CORE.FEAT f

JOIN DB_T_PROD_CORE.AGMT_INSRD_ASSET_FEAT ON f.FEAT_ID=AGMT_INSRD_ASSET_FEAT.FEAT_ID  AND	TO_DATE(AGMT_INSRD_ASSET_FEAT.TRANS_END_DTTM)=''12/31/9999''  

JOIN DB_T_PROD_CORE.AGMT ON AGMT_INSRD_ASSET_FEAT.AGMT_ID=AGMT.AGMT_ID AND	AGMT.EDW_END_DTTM=TO_TIMESTAMP_NTZ(''12/31/9999 23:59:59.999999'', ''MM/DD/YYYY HH24:MI:SS.FF'')  

JOIN  DB_T_PROD_CORE.PRTY_ASSET ON AGMT_INSRD_ASSET_FEAT.PRTY_ASSET_ID=PRTY_ASSET.PRTY_ASSET_ID AND	PRTY_ASSET.EDW_END_DTTM=TO_TIMESTAMP_NTZ(''12/31/9999 23:59:59.999999'', ''MM/DD/YYYY HH24:MI:SS.FF'') 

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr1 ON f.FEAT_ID=fr1.RLTD_FEAT_ID AND   fr1.FEAT_RLTNSHP_TYPE_CD =''COVT''     AND TO_DATE(fr1.TRANS_END_DTTM)=''12/31/9999''       

LEFT JOIN DB_T_PROD_CORE.FEAT f1 ON fr1.FEAT_ID=f1.FEAT_ID   AND	TO_DATE(f1.EDW_END_DTTM)=''12/31/9999''              

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr2 ON f.FEAT_ID=fr2.RLTD_FEAT_ID AND   fr2.FEAT_RLTNSHP_TYPE_CD =''TERMOPT''     AND TO_DATE(fr2.TRANS_END_DTTM)=''12/31/9999''  

LEFT JOIN DB_T_PROD_CORE.FEAT f2 ON fr2.FEAT_ID=f2.FEAT_ID  AND	TO_DATE(f2.EDW_END_DTTM)=''12/31/9999''  

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr3 ON f.FEAT_ID=fr3.RLTD_FEAT_ID AND   fr3.FEAT_RLTNSHP_TYPE_CD =''COVOPTT''    AND TO_DATE(fr3.TRANS_END_DTTM)=''12/31/9999''

LEFT JOIN DB_T_PROD_CORE.FEAT f3 ON fr3.FEAT_ID=f3.FEAT_ID  AND	TO_DATE(f3.EDW_END_DTTM)=''12/31/9999''  

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr4 ON f.FEAT_ID=fr4.RLTD_FEAT_ID AND   fr4.FEAT_RLTNSHP_TYPE_CD =''TERMPKG'' AND TO_DATE(fr4.TRANS_END_DTTM)=''12/31/9999''

LEFT JOIN DB_T_PROD_CORE.FEAT f4 ON fr4.FEAT_ID=f4.FEAT_ID  AND	TO_DATE(f4.EDW_END_DTTM)=''12/31/9999''  

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr5 ON f.FEAT_ID=fr5.RLTD_FEAT_ID AND   fr5.FEAT_RLTNSHP_TYPE_CD =''COVPKG''  AND TO_DATE(fr5.TRANS_END_DTTM)=''12/31/9999''

LEFT JOIN 

(SELECT EV_STS.AGMT_ID  FROM DB_T_PROD_CORE.EV

INNER JOIN DB_T_PROD_CORE.EV_STS ON EV.EV_ID=EV_STS.EV_ID AND EV_STS.EV_STS_TYPE_CD=''BOUND'' AND

EV_STS.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''    

WHERE  EV_ACTVY_TYPE_CD=''SBMSSN''  AND EV_SBTYPE_CD=''PLCYTRNS''  AND EV.EDW_END_DTTM= ''9999-12-31 23:59:59.999999'' ) NB

ON NB.AGMT_ID=AGMT.AGMT_ID

LEFT JOIN DB_T_PROD_CORE.FEAT f5 ON fr5.FEAT_ID=f5.FEAT_ID  AND	TO_DATE(f5.EDW_END_DTTM)=''12/31/9999''  

WHERE f.FEAT_SBTYPE_CD IN (''TERM'', ''OPT'', ''PKG'')

AND	AGMT.modl_crtn_dttm = (SELECT	MAX(aa.modl_crtn_dttm)  FROM	DB_T_PROD_CORE.AGMT aa WHERE	aa.host_agmt_num=AGMT.host_agmt_num)

AND AGMT.AGMT_CUR_STS_CD=''BOUND''

AND CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.NK_SRC_KEY

END  NOT IN (''HOLI_SCHEDULEDPROPERTYDEDUCTIBLESITEM_ALFA'', ''HOSI_SCHEDULEDPROPERTYITEM_ALFA'') 



)





select 

PAC.HOST_AGMT_NUM,

PAC.AGMT_ID,

PAC.AGMT_EFF_DTTM,

PAC.MODL_ACTL_END_DTTM,

PAC.AGMT_PLND_EXPN_DTTM,

PAC.PRTY_ASSET_ID,

MOTR_VEH_SER_NUM,

PAC.INSRNC_CVGE_TYPE_CD,

MBRSHP_NUM,

MBRSHP_TYPE_CD,

SUM(ERND.PLCY_ASSET_CVGE_AMT) as ERND_PREM,

SUM(PREM.PLCY_ASSET_CVGE_AMT) as WRT_PREM,

SUM(CASE WHEN PAC.NB_IND=''Y'' THEN PREM.PLCY_ASSET_CVGE_AMT 

ELSE 0  END) AS NB_WRT_PREM



from PLCY_ASSET_COVERAGES  PAC

inner join DB_T_PROD_CORE.AGMT_PROD on AGMT_PROD.AGMT_ID=PAC.AGMT_ID AND AGMT_PROD.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''    

inner join DB_T_PROD_CORE.PROD on PROD.PROD_ID=AGMT_PROD.PROD_ID AND PROD.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''    

inner join DB_T_PROD_CORE.AGMT_ASSET on PAC.AGMT_ID= AGMT_ASSET.AGMT_ID AND AGMT_ASSET.PRTY_ASSET_ID=PAC.PRTY_ASSET_ID AND AGMT_ASSET.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

inner join DB_T_PROD_CORE.MOTR_VEH on AGMT_ASSET.PRTY_ASSET_ID=MOTR_VEH.PRTY_ASSET_ID AND MOTR_VEH.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''        

inner join DB_T_PROD_CORE.AGMT_MBRSHP on AGMT_MBRSHP.AGMT_ID=PAC.AGMT_ID AND AGMT_MBRSHP.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''    

inner join DB_T_PROD_CORE.MBRSHP on MBRSHP.MBRSHP_ID=AGMT_MBRSHP.MBRSHP_ID AND MBRSHP.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''    

inner join DB_T_PROD_CORE.PLCY_ASSET_CVGE_MTRC AS PREM  ON PAC.AGMT_ID= PREM.AGMT_ID AND PAC.COV_FEAT_ID= PREM.FEAT_ID 

 AND PAC.PRTY_ASSET_ID= PREM.PRTY_ASSET_ID 

AND PREM.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''  AND   PREM.INSRNC_MTRC_TYPE_CD=''TRANPREM''

inner join DB_T_PROD_CORE.PLCY_ASSET_CVGE_MTRC  AS ERND ON PAC.AGMT_ID= ERND.AGMT_ID AND PAC.COV_FEAT_ID= ERND.FEAT_ID 

AND PAC.PRTY_ASSET_ID= ERND.PRTY_ASSET_ID 

AND ERND.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''  AND   ERND.INSRNC_MTRC_TYPE_CD=''ERNDPREM''

Where 

AGMT_PROD_ROLE_CD=''PLCYTYPE'' and   

PROD.PROD_NAME IN (''PPV'', ''AUTO'', ''COMMERCIAL'', ''PERSONAL AUTO'')  		  

GROUP BY 

HOST_AGMT_NUM,

PAC.AGMT_ID,

AGMT_EFF_DTTM,

MODL_ACTL_END_DTTM,

AGMT_PLND_EXPN_DTTM,

PAC.PRTY_ASSET_ID,

MOTR_VEH_SER_NUM,

INSRNC_CVGE_TYPE_CD,

MBRSHP_NUM,

MBRSHP_TYPE_CD

ORDER BY HOST_AGMT_NUM
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_AGMT.HOST_AGMT_NUM as HOST_AGMT_NUM,
SQ_AGMT.AGMT_ID as AGMT_ID,
SQ_AGMT.AGMT_OPN_DTTM as AGMT_OPN_DTTM,
SQ_AGMT.MODL_ACTL_END_DTTM as MODL_ACTL_END_DTTM,
SQ_AGMT.AGMT_PLND_EXPN_DTTM as AGMT_PLND_EXPN_DT,
SQ_AGMT.PRTY_ASSET_ID as PRTY_ASSET_ID,
SQ_AGMT.MOTR_VEH_SER_NUM as MOTR_VEH_SER_NUM,
SQ_AGMT.INSRNC_CVGE_TYPE_CD as INSRNC_CVGE_TYPE_CD,
SQ_AGMT.MBRSHP_NUM as MBRSHP_NUM,
SQ_AGMT.MBRSHP_TYPE_CD as MBRSHP_TYPE_CD,
SQ_AGMT.PLCY_AMT as ERNDPREM,
SQ_AGMT.PLCY_AMT1 as PREM,
SQ_AGMT.AGMT_CURY_PLCY_AMT as AGMT_CURY_PLCY_AMT,
:PRCS_ID as prcs_id,
CURRENT_TIMESTAMP as load_dt,
SQ_AGMT.source_record_id
FROM
SQ_AGMT
);


-- Component EDW_EBLM_PREM_TRANS_SUMMARY, Type TARGET 
INSERT INTO DB_T_PROD_WRK.EDW_EBLM_PREM_TRANS_SUMMARY
(
PLCY_NBR,
DW_PLCY_SKEY,
PLCY_OGN_EFF_DT,
PLCY_ACTUAL_EXP_DT,
PLCY_PLN_EXP_DT,
DW_VEH_SKEY,
UNIT_REF_NBR,
COV_TYPE_CD,
ALFA_CUST_MEMB_NBR,
ALFA_CUST_MEMB_TYPE,
EARNED_PREMIUM_AMT,
WRITTEN_PREMIUM_AMT,
WRITTEN_PREMIUM_AMT_NB,
PRCS_ID,
LOAD_DT
)
SELECT
exp_pass_through.HOST_AGMT_NUM as PLCY_NBR,
exp_pass_through.AGMT_ID as DW_PLCY_SKEY,
exp_pass_through.AGMT_OPN_DTTM as PLCY_OGN_EFF_DT,
exp_pass_through.MODL_ACTL_END_DTTM as PLCY_ACTUAL_EXP_DT,
exp_pass_through.AGMT_PLND_EXPN_DT as PLCY_PLN_EXP_DT,
exp_pass_through.PRTY_ASSET_ID as DW_VEH_SKEY,
exp_pass_through.MOTR_VEH_SER_NUM as UNIT_REF_NBR,
exp_pass_through.INSRNC_CVGE_TYPE_CD as COV_TYPE_CD,
exp_pass_through.MBRSHP_NUM as ALFA_CUST_MEMB_NBR,
exp_pass_through.MBRSHP_TYPE_CD as ALFA_CUST_MEMB_TYPE,
exp_pass_through.ERNDPREM as EARNED_PREMIUM_AMT,
exp_pass_through.PREM as WRITTEN_PREMIUM_AMT,
exp_pass_through.AGMT_CURY_PLCY_AMT as WRITTEN_PREMIUM_AMT_NB,
exp_pass_through.prcs_id as PRCS_ID,
exp_pass_through.load_dt as LOAD_DT
FROM
exp_pass_through;


END; ';