-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_HR_SVC_BENEFITS("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_SRC_HR_SVC_BENEFITS_SRC, Type TABLE_DDL Creating an empty table
CREATE OR REPLACE TEMPORARY TABLE SQ_SRC_HR_SVC_BENEFITS
(
DED_CLS varchar(50),
DED_AMT nvarchar(20),
PRD integer,
DED_CD varchar(50),
JOB_CD integer,
SVC integer,
YR integer,
source_record_id number autoincrement start 1 increment 1
);


-- Component SQ_SRC_HR_SVC_BENEFITS_SRC, Type IMPORT_DATA Importing Data
;


-- Component EXP_HR_SVC_BENEFITS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXP_HR_SVC_BENEFITS AS
(
SELECT
TO_NUMBER(TO_CHAR ( CURRENT_TIMESTAMP , ''YYYYMM'' )) as MO_ID,
SQ_SRC_HR_SVC_BENEFITS.DED_CLS as DED_CLS,
IFNULL(TRY_TO_DECIMAL(REPLACE(SQ_SRC_HR_SVC_BENEFITS.DED_AMT,'','',NULL)), 0) as o_DED_AMT,
SQ_SRC_HR_SVC_BENEFITS.PRD as PRD,
SQ_SRC_HR_SVC_BENEFITS.DED_CD as DED_CD,
SQ_SRC_HR_SVC_BENEFITS.JOB_CD as JOB_CD,
SQ_SRC_HR_SVC_BENEFITS.SVC as SVC,
SQ_SRC_HR_SVC_BENEFITS.YR as YR,
$PRCS_ID as PRCS_ID,
CURRENT_TIMESTAMP as LOAD_DTTM,
SQ_SRC_HR_SVC_BENEFITS.source_record_id
FROM
SQ_SRC_HR_SVC_BENEFITS
);


-- Component HR_SVC_BENEFITS, Type TARGET 
INSERT INTO DB_T_PROD_COMN.HR_SVC_BENEFITS
(
MO_ID,
DED_CLS,
DED_AMT,
PRD,
DED_CD,
JOB_CD,
SVC,
YR,
PRCS_ID,
LOAD_DTTM
)
SELECT
EXP_HR_SVC_BENEFITS.MO_ID as MO_ID,
EXP_HR_SVC_BENEFITS.DED_CLS as DED_CLS,
EXP_HR_SVC_BENEFITS.o_DED_AMT as DED_AMT,
EXP_HR_SVC_BENEFITS.PRD as PRD,
EXP_HR_SVC_BENEFITS.DED_CD as DED_CD,
EXP_HR_SVC_BENEFITS.JOB_CD as JOB_CD,
EXP_HR_SVC_BENEFITS.SVC as SVC,
EXP_HR_SVC_BENEFITS.YR as YR,
EXP_HR_SVC_BENEFITS.PRCS_ID as PRCS_ID,
EXP_HR_SVC_BENEFITS.LOAD_DTTM as LOAD_DTTM
FROM
EXP_HR_SVC_BENEFITS;


END; ';