-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_HR_SVC_DEDUCTIONS("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_SRC_HR_SVC_DEDUCTIONS_SRC, Type TABLE_DDL Creating an empty table
CREATE OR REPLACE TEMPORARY TABLE SQ_SRC_HR_SVC_DEDUCTIONS
(
YR integer,
DED_CD varchar(50),
DED_CLS varchar(50),
DED_AMT nvarchar(20),
JOB_CD integer,
HR_STS varchar(50),
SVC integer,
source_record_id number autoincrement start 1 increment 1
);


-- Component SQ_SRC_HR_SVC_DEDUCTIONS_SRC, Type IMPORT_DATA Importing Data
;


-- Component EXP_HR_SVC_DEDUCTIONS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXP_HR_SVC_DEDUCTIONS AS
(
SELECT
TO_NUMBER(TO_CHAR ( CURRENT_TIMESTAMP , ''YYYYMM'' )) as MO_ID,
SQ_SRC_HR_SVC_DEDUCTIONS.YR as YR,
SQ_SRC_HR_SVC_DEDUCTIONS.DED_CD as DED_CD,
SQ_SRC_HR_SVC_DEDUCTIONS.DED_CLS as DED_CLS,
IFNULL(TRY_TO_DECIMAL(REPLACE(SQ_SRC_HR_SVC_DEDUCTIONS.DED_AMT,'','',NULL)), 0) as o_DED_AMT,
SQ_SRC_HR_SVC_DEDUCTIONS.JOB_CD as JOB_CD,
SQ_SRC_HR_SVC_DEDUCTIONS.HR_STS as HR_STS,
SQ_SRC_HR_SVC_DEDUCTIONS.SVC as SVC,
$PRCS_ID as PRCS_ID,
CURRENT_TIMESTAMP as LOAD_DTTM,
SQ_SRC_HR_SVC_DEDUCTIONS.source_record_id
FROM
SQ_SRC_HR_SVC_DEDUCTIONS
);


-- Component HR_SVC_DEDUCTIONS, Type TARGET 
INSERT INTO DB_T_PROD_COMN.HR_SVC_DEDUCTIONS
(
MO_ID,
YR,
DED_CD,
DED_CLS,
DED_AMT,
JOB_CD,
HR_STS,
SVC,
PRCS_ID,
LOAD_DTTM
)
SELECT
EXP_HR_SVC_DEDUCTIONS.MO_ID as MO_ID,
EXP_HR_SVC_DEDUCTIONS.YR as YR,
EXP_HR_SVC_DEDUCTIONS.DED_CD as DED_CD,
EXP_HR_SVC_DEDUCTIONS.DED_CLS as DED_CLS,
EXP_HR_SVC_DEDUCTIONS.o_DED_AMT as DED_AMT,
EXP_HR_SVC_DEDUCTIONS.JOB_CD as JOB_CD,
EXP_HR_SVC_DEDUCTIONS.HR_STS as HR_STS,
EXP_HR_SVC_DEDUCTIONS.SVC as SVC,
EXP_HR_SVC_DEDUCTIONS.PRCS_ID as PRCS_ID,
EXP_HR_SVC_DEDUCTIONS.LOAD_DTTM as LOAD_DTTM
FROM
EXP_HR_SVC_DEDUCTIONS;


END; ';