-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_ACCTBLY_PTS("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
  prcs_id STRING;
BEGIN
  SELECT 
    TRY_PARSE_JSON(:param_json):prcs_id::STRING
  INTO
    prcs_id;

-- Component SQ_ACCTBLY_PTS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ACCTBLY_PTS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as AGENT_NBR,
$2 as DATE_WRITTEN,
$3 as DATE_USED,
$4 as STATE_NBR,
$5 as DISTRICT,
$6 as REGION,
$7 as SERVICE_CENTER,
$8 as POINT_1_AMT,
$9 as POINT_1_IND,
$10 as POINT_2_AMT,
$11 as POINT_2_IND,
$12 as POINT_3_AMT,
$13 as POINT_3_IND,
$14 as POINT_4_AMT,
$15 as POINT_4_IND,
$16 as POINT_5_AMT,
$17 as POINT_5_IND,
$18 as POINT_6_AMT,
$19 as POINT_6_IND,
$20 as POINT_7_AMT,
$21 as POINT_7_IND,
$22 as TOTAL_POINTS,
$23 as UPDATE_DATE,
$24 as UPDATE_TIME,
$25 as UPDATE_SOURCE,
$26 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
ACCTBLY_PTS.AGENT_NBR,
ACCTBLY_PTS.DATE_WRITTEN,
ACCTBLY_PTS.DATE_USED,
ACCTBLY_PTS.STATE_NBR,
ACCTBLY_PTS.DISTRICT,
ACCTBLY_PTS.REGION,
ACCTBLY_PTS.SERVICE_CENTER,
ACCTBLY_PTS.POINT_1_AMT,
ACCTBLY_PTS.POINT_1_IND,
ACCTBLY_PTS.POINT_2_AMT,
ACCTBLY_PTS.POINT_2_IND,
ACCTBLY_PTS.POINT_3_AMT,
ACCTBLY_PTS.POINT_3_IND,
ACCTBLY_PTS.POINT_4_AMT,
ACCTBLY_PTS.POINT_4_IND,
ACCTBLY_PTS.POINT_5_AMT,
ACCTBLY_PTS.POINT_5_IND,
ACCTBLY_PTS.POINT_6_AMT,
ACCTBLY_PTS.POINT_6_IND,
ACCTBLY_PTS.POINT_7_AMT,
ACCTBLY_PTS.POINT_7_IND,
ACCTBLY_PTS.TOTAL_POINTS,
ACCTBLY_PTS.UPDATE_DATE,
ACCTBLY_PTS.UPDATE_TIME,
ACCTBLY_PTS.UPDATE_SOURCE
FROM DB_T_PROD_STAG.ACCTBLY_PTS
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_ACCTBLY_PTS.AGENT_NBR as AGENT_NBR,
SQ_ACCTBLY_PTS.DATE_WRITTEN as DATE_WRITTEN,
SQ_ACCTBLY_PTS.DATE_USED as DATE_USED,
SQ_ACCTBLY_PTS.STATE_NBR as STATE_NBR,
SQ_ACCTBLY_PTS.DISTRICT as DISTRICT,
SQ_ACCTBLY_PTS.REGION as REGION,
SQ_ACCTBLY_PTS.SERVICE_CENTER as SERVICE_CENTER,
SQ_ACCTBLY_PTS.POINT_1_AMT as POINT_1_AMT,
SQ_ACCTBLY_PTS.POINT_1_IND as POINT_1_IND,
SQ_ACCTBLY_PTS.POINT_2_AMT as POINT_2_AMT,
SQ_ACCTBLY_PTS.POINT_2_IND as POINT_2_IND,
SQ_ACCTBLY_PTS.POINT_3_AMT as POINT_3_AMT,
SQ_ACCTBLY_PTS.POINT_3_IND as POINT_3_IND,
SQ_ACCTBLY_PTS.POINT_4_AMT as POINT_4_AMT,
SQ_ACCTBLY_PTS.POINT_4_IND as POINT_4_IND,
SQ_ACCTBLY_PTS.POINT_5_AMT as POINT_5_AMT,
SQ_ACCTBLY_PTS.POINT_5_IND as POINT_5_IND,
SQ_ACCTBLY_PTS.POINT_6_AMT as POINT_6_AMT,
SQ_ACCTBLY_PTS.POINT_6_IND as POINT_6_IND,
SQ_ACCTBLY_PTS.POINT_7_AMT as POINT_7_AMT,
SQ_ACCTBLY_PTS.POINT_7_IND as POINT_7_IND,
SQ_ACCTBLY_PTS.TOTAL_POINTS as TOTAL_POINTS,
SQ_ACCTBLY_PTS.UPDATE_DATE as UPDATE_DATE,
SQ_ACCTBLY_PTS.UPDATE_TIME as UPDATE_TIME,
SQ_ACCTBLY_PTS.UPDATE_SOURCE as UPDATE_SOURCE,
:prcs_id as prcs_id,
SQ_ACCTBLY_PTS.source_record_id
FROM
SQ_ACCTBLY_PTS
);


-- Component ACCTBLY_PTS_1, Type TARGET 
INSERT INTO DB_T_PROD_STAG.ACCTBLY_PTS
(
AGENT_NBR,
DATE_WRITTEN,
DATE_USED,
STATE_NBR,
DISTRICT,
REGION,
SERVICE_CENTER,
POINT_1_AMT,
POINT_1_IND,
POINT_2_AMT,
POINT_2_IND,
POINT_3_AMT,
POINT_3_IND,
POINT_4_AMT,
POINT_4_IND,
POINT_5_AMT,
POINT_5_IND,
POINT_6_AMT,
POINT_6_IND,
POINT_7_AMT,
POINT_7_IND,
TOTAL_POINTS,
UPDATE_DATE,
UPDATE_TIME,
UPDATE_SOURCE,
PRCS_ID
)
SELECT
EXPTRANS.AGENT_NBR as AGENT_NBR,
EXPTRANS.DATE_WRITTEN as DATE_WRITTEN,
EXPTRANS.DATE_USED as DATE_USED,
EXPTRANS.STATE_NBR as STATE_NBR,
EXPTRANS.DISTRICT as DISTRICT,
EXPTRANS.REGION as REGION,
EXPTRANS.SERVICE_CENTER as SERVICE_CENTER,
EXPTRANS.POINT_1_AMT as POINT_1_AMT,
EXPTRANS.POINT_1_IND as POINT_1_IND,
EXPTRANS.POINT_2_AMT as POINT_2_AMT,
EXPTRANS.POINT_2_IND as POINT_2_IND,
EXPTRANS.POINT_3_AMT as POINT_3_AMT,
EXPTRANS.POINT_3_IND as POINT_3_IND,
EXPTRANS.POINT_4_AMT as POINT_4_AMT,
EXPTRANS.POINT_4_IND as POINT_4_IND,
EXPTRANS.POINT_5_AMT as POINT_5_AMT,
EXPTRANS.POINT_5_IND as POINT_5_IND,
EXPTRANS.POINT_6_AMT as POINT_6_AMT,
EXPTRANS.POINT_6_IND as POINT_6_IND,
EXPTRANS.POINT_7_AMT as POINT_7_AMT,
EXPTRANS.POINT_7_IND as POINT_7_IND,
EXPTRANS.TOTAL_POINTS as TOTAL_POINTS,
EXPTRANS.UPDATE_DATE as UPDATE_DATE,
EXPTRANS.UPDATE_TIME as UPDATE_TIME,
EXPTRANS.UPDATE_SOURCE as UPDATE_SOURCE,
EXPTRANS.prcs_id as PRCS_ID
FROM
EXPTRANS;


END; ';