-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_BC_TRANSACTION_MNTHLY("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
  PRCS_ID STRING;
BEGIN
  SELECT 
    TRY_PARSE_JSON(:param_json):PRCS_ID::STRING
  INTO
    PRCS_ID;

-- Component SQ_bc_transaction_mnthly_x, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_bc_transaction_mnthly_x AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as LoadCommandID,
$2 as Reversed,
$3 as CommissionAmount,
$4 as PublicID,
$5 as Reason,
$6 as CommissionAmount_cur,
$7 as CreateTime,
$8 as TransactionDate,
$9 as CommissionAmountChanged,
$10 as Currency,
$11 as CommissionAmountChanged_cur,
$12 as ReversalReason,
$13 as WriteoffChannel,
$14 as UpdateTime,
$15 as Amount,
$16 as Amount_cur,
$17 as ID,
$18 as CreateUserID,
$19 as TransactionNumberDenorm,
$20 as TransactionNumber,
$21 as BeanVersion,
$22 as Retired,
$23 as UpdateUserID,
$24 as Subtype,
$25 as Basis,
$26 as Basis_cur,
$27 as PolicyNumber,
$28 as AccountNumber,
$29 as TermNumber,
$30 as TYPECODE,
$31 as nk_public_id,
$32 as GLMonth,
$33 as GLYear,
$34 as AccountingDate,
$35 as Invoicenumber,
$36 as InvoiceitemID,
$37 as Typecode_Chargecategory,
$38 as amt_ctgy_typecode,
$39 as CTL_ID,
$40 as LOAD_DTTM,
$41 as load_user,
$42 as LNITM_AMT,
$43 as LDGRSIDE_TYPECODE,
$44 as TACCOUNT_TYPECODE,
$45 as ownerid,
$46 as EV_MED_TYPE_CD,
$47 as FUNDS_TFR_TYPE_CD,
$48 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
bc_transaction_mnthly_x.LoadCommandID,
bc_transaction_mnthly_x.Reversed,
bc_transaction_mnthly_x.CommissionAmount,
bc_transaction_mnthly_x.PublicID,
bc_transaction_mnthly_x.Reason,
bc_transaction_mnthly_x.CommissionAmount_cur,
bc_transaction_mnthly_x.CreateTime,
bc_transaction_mnthly_x.TransactionDate,
bc_transaction_mnthly_x.CommissionAmountChanged,
bc_transaction_mnthly_x.Currency,
bc_transaction_mnthly_x.CommissionAmountChanged_cur,
bc_transaction_mnthly_x.ReversalReason,
bc_transaction_mnthly_x.WriteoffChannel,
bc_transaction_mnthly_x.UpdateTime,
bc_transaction_mnthly_x.Amount,
bc_transaction_mnthly_x.Amount_cur,
bc_transaction_mnthly_x.ID,
bc_transaction_mnthly_x.CreateUserID,
bc_transaction_mnthly_x.TransactionNumberDenorm,
bc_transaction_mnthly_x.TransactionNumber,
bc_transaction_mnthly_x.BeanVersion,
bc_transaction_mnthly_x.Retired,
bc_transaction_mnthly_x.UpdateUserID,
bc_transaction_mnthly_x.Subtype,
bc_transaction_mnthly_x.Basis,
bc_transaction_mnthly_x.Basis_cur,
bc_transaction_mnthly_x.PolicyNumber,
bc_transaction_mnthly_x.AccountNumber,
bc_transaction_mnthly_x.TermNumber,
bc_transaction_mnthly_x.TYPECODE,
bc_transaction_mnthly_x.nk_public_id,
bc_transaction_mnthly_x.GLMonth,
bc_transaction_mnthly_x.GLYear,
bc_transaction_mnthly_x.AccountingDate,
bc_transaction_mnthly_x.Invoicenumber,
bc_transaction_mnthly_x.InvoiceitemID,
bc_transaction_mnthly_x.Typecode_Chargecategory,
bc_transaction_mnthly_x.amt_ctgy_typecode,
bc_transaction_mnthly_x.CTL_ID,
bc_transaction_mnthly_x.LOAD_DTTM,
bc_transaction_mnthly_x.load_user,
bc_transaction_mnthly_x.LNITM_AMT,
bc_transaction_mnthly_x.LDGRSIDE_TYPECODE,
bc_transaction_mnthly_x.TACCOUNT_TYPECODE,
bc_transaction_mnthly_x.ownerid,
bc_transaction_mnthly_x.EV_MED_TYPE_CD,
bc_transaction_mnthly_x.FUNDS_TFR_TYPE_CD
FROM bc_transaction_mnthly_x
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_bc_transaction_mnthly_x.LoadCommandID as LoadCommandID,
SQ_bc_transaction_mnthly_x.Reversed as Reversed,
SQ_bc_transaction_mnthly_x.CommissionAmount as CommissionAmount,
SQ_bc_transaction_mnthly_x.PublicID as PublicID,
SQ_bc_transaction_mnthly_x.Reason as Reason,
SQ_bc_transaction_mnthly_x.CommissionAmount_cur as CommissionAmount_cur,
SQ_bc_transaction_mnthly_x.CreateTime as CreateTime,
SQ_bc_transaction_mnthly_x.TransactionDate as TransactionDate,
SQ_bc_transaction_mnthly_x.CommissionAmountChanged as CommissionAmountChanged,
SQ_bc_transaction_mnthly_x.Currency as Currency,
SQ_bc_transaction_mnthly_x.CommissionAmountChanged_cur as CommissionAmountChanged_cur,
SQ_bc_transaction_mnthly_x.ReversalReason as ReversalReason,
SQ_bc_transaction_mnthly_x.WriteoffChannel as WriteoffChannel,
SQ_bc_transaction_mnthly_x.UpdateTime as UpdateTime,
SQ_bc_transaction_mnthly_x.Amount as Amount,
SQ_bc_transaction_mnthly_x.Amount_cur as Amount_cur,
SQ_bc_transaction_mnthly_x.ID as ID,
SQ_bc_transaction_mnthly_x.CreateUserID as CreateUserID,
SQ_bc_transaction_mnthly_x.TransactionNumberDenorm as TransactionNumberDenorm,
SQ_bc_transaction_mnthly_x.TransactionNumber as TransactionNumber,
SQ_bc_transaction_mnthly_x.BeanVersion as BeanVersion,
SQ_bc_transaction_mnthly_x.Retired as Retired,
SQ_bc_transaction_mnthly_x.UpdateUserID as UpdateUserID,
SQ_bc_transaction_mnthly_x.Subtype as Subtype,
SQ_bc_transaction_mnthly_x.Basis as Basis,
SQ_bc_transaction_mnthly_x.Basis_cur as Basis_cur,
SQ_bc_transaction_mnthly_x.PolicyNumber as PolicyNumber,
SQ_bc_transaction_mnthly_x.AccountNumber as AccountNumber,
SQ_bc_transaction_mnthly_x.TermNumber as TermNumber,
SQ_bc_transaction_mnthly_x.TYPECODE as TYPECODE,
SQ_bc_transaction_mnthly_x.nk_public_id as nk_public_id,
SQ_bc_transaction_mnthly_x.GLMonth as GLMonth,
SQ_bc_transaction_mnthly_x.GLYear as GLYear,
SQ_bc_transaction_mnthly_x.AccountingDate as AccountingDate,
SQ_bc_transaction_mnthly_x.Invoicenumber as Invoicenumber,
SQ_bc_transaction_mnthly_x.InvoiceitemID as InvoiceitemID,
SQ_bc_transaction_mnthly_x.Typecode_Chargecategory as Typecode_Chargecategory,
SQ_bc_transaction_mnthly_x.amt_ctgy_typecode as amt_ctgy_typecode,
SQ_bc_transaction_mnthly_x.CTL_ID as CTL_ID,
:PRCS_ID as PROCESS_ID,
SQ_bc_transaction_mnthly_x.LOAD_DTTM as LOAD_DTTM,
SQ_bc_transaction_mnthly_x.load_user as load_user,
SQ_bc_transaction_mnthly_x.LNITM_AMT as LNITM_AMT,
SQ_bc_transaction_mnthly_x.LDGRSIDE_TYPECODE as LDGRSIDE_TYPECODE,
SQ_bc_transaction_mnthly_x.TACCOUNT_TYPECODE as TACCOUNT_TYPECODE,
SQ_bc_transaction_mnthly_x.ownerid as ownerid,
SQ_bc_transaction_mnthly_x.EV_MED_TYPE_CD as EV_MED_TYPE_CD,
SQ_bc_transaction_mnthly_x.FUNDS_TFR_TYPE_CD as FUNDS_TFR_TYPE_CD,
SQ_bc_transaction_mnthly_x.source_record_id
FROM
SQ_bc_transaction_mnthly_x
);


-- Component bc_transaction_mnthly_x1, Type TARGET 
INSERT INTO bc_transaction_mnthly_x
(
LoadCommandID,
Reversed,
CommissionAmount,
PublicID,
Reason,
CommissionAmount_cur,
CreateTime,
TransactionDate,
CommissionAmountChanged,
Currency,
CommissionAmountChanged_cur,
ReversalReason,
WriteoffChannel,
UpdateTime,
Amount,
Amount_cur,
ID,
CreateUserID,
TransactionNumberDenorm,
TransactionNumber,
BeanVersion,
Retired,
UpdateUserID,
Subtype,
Basis,
Basis_cur,
PolicyNumber,
AccountNumber,
TermNumber,
TYPECODE,
nk_public_id,
GLMonth,
GLYear,
AccountingDate,
Invoicenumber,
InvoiceitemID,
Typecode_Chargecategory,
amt_ctgy_typecode,
CTL_ID,
PROCESS_ID,
LOAD_USER,
LOAD_DTTM,
LNITM_AMT,
LDGRSIDE_TYPECODE,
TACCOUNT_TYPECODE,
ownerid,
EV_MED_TYPE_CD,
FUNDS_TFR_TYPE_CD
)
SELECT
exp_pass_through.LoadCommandID as LoadCommandID,
exp_pass_through.Reversed as Reversed,
exp_pass_through.CommissionAmount as CommissionAmount,
exp_pass_through.PublicID as PublicID,
exp_pass_through.Reason as Reason,
exp_pass_through.CommissionAmount_cur as CommissionAmount_cur,
exp_pass_through.CreateTime as CreateTime,
exp_pass_through.TransactionDate as TransactionDate,
exp_pass_through.CommissionAmountChanged as CommissionAmountChanged,
exp_pass_through.Currency as Currency,
exp_pass_through.CommissionAmountChanged_cur as CommissionAmountChanged_cur,
exp_pass_through.ReversalReason as ReversalReason,
exp_pass_through.WriteoffChannel as WriteoffChannel,
exp_pass_through.UpdateTime as UpdateTime,
exp_pass_through.Amount as Amount,
exp_pass_through.Amount_cur as Amount_cur,
exp_pass_through.ID as ID,
exp_pass_through.CreateUserID as CreateUserID,
exp_pass_through.TransactionNumberDenorm as TransactionNumberDenorm,
exp_pass_through.TransactionNumber as TransactionNumber,
exp_pass_through.BeanVersion as BeanVersion,
exp_pass_through.Retired as Retired,
exp_pass_through.UpdateUserID as UpdateUserID,
exp_pass_through.Subtype as Subtype,
exp_pass_through.Basis as Basis,
exp_pass_through.Basis_cur as Basis_cur,
exp_pass_through.PolicyNumber as PolicyNumber,
exp_pass_through.AccountNumber as AccountNumber,
exp_pass_through.TermNumber as TermNumber,
exp_pass_through.TYPECODE as TYPECODE,
exp_pass_through.nk_public_id as nk_public_id,
exp_pass_through.GLMonth as GLMonth,
exp_pass_through.GLYear as GLYear,
exp_pass_through.AccountingDate as AccountingDate,
exp_pass_through.Invoicenumber as Invoicenumber,
exp_pass_through.InvoiceitemID as InvoiceitemID,
exp_pass_through.Typecode_Chargecategory as Typecode_Chargecategory,
exp_pass_through.amt_ctgy_typecode as amt_ctgy_typecode,
exp_pass_through.CTL_ID as CTL_ID,
exp_pass_through.PROCESS_ID as PROCESS_ID,
exp_pass_through.load_user as LOAD_USER,
exp_pass_through.LOAD_DTTM as LOAD_DTTM,
exp_pass_through.LNITM_AMT as LNITM_AMT,
exp_pass_through.LDGRSIDE_TYPECODE as LDGRSIDE_TYPECODE,
exp_pass_through.TACCOUNT_TYPECODE as TACCOUNT_TYPECODE,
exp_pass_through.ownerid as ownerid,
exp_pass_through.EV_MED_TYPE_CD as EV_MED_TYPE_CD,
exp_pass_through.FUNDS_TFR_TYPE_CD as FUNDS_TFR_TYPE_CD
FROM
exp_pass_through;


END; ';