-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_GW_CLOSEOUT_CTL("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
  PRCS_ID STRING;
  p_LOAD_USER STRING;
BEGIN
  SELECT 
    TRY_PARSE_JSON(:param_json):PRCS_ID::STRING,
    TRY_PARSE_JSON(:param_json):p_LOAD_USER::STRING
  INTO
    PRCS_ID,
    p_LOAD_USER;

-- Component SQ_GW_CLOSEOUT_CTL, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_GW_CLOSEOUT_CTL AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ACCOUNTING_YR,
$2 as ACCOUNTING_MO,
$3 as CLOSEOUT_TYPE,
$4 as CLOSEOUT_SEQ_NBR,
$5 as BEGINNING_TS,
$6 as ENDING_TS,
$7 as EOM_DT,
$8 as CTL_ID,
$9 as LOAD_DTTM,
$10 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
GW_CLOSEOUT_CTL.ACCOUNTING_YR,
GW_CLOSEOUT_CTL.ACCOUNTING_MO,
GW_CLOSEOUT_CTL.CLOSEOUT_TYPE,
GW_CLOSEOUT_CTL.CLOSEOUT_SEQ_NBR,
GW_CLOSEOUT_CTL.BEGINNING_TS,
GW_CLOSEOUT_CTL.ENDING_TS,
GW_CLOSEOUT_CTL.EOM_DT,
GW_CLOSEOUT_CTL.CTL_ID,
GW_CLOSEOUT_CTL.LOAD_DTTM
FROM DB_T_PROD_STAG.GW_CLOSEOUT_CTL
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_GW_CLOSEOUT_CTL.ACCOUNTING_YR as ACCOUNTING_YR,
SQ_GW_CLOSEOUT_CTL.ACCOUNTING_MO as ACCOUNTING_MO,
SQ_GW_CLOSEOUT_CTL.CLOSEOUT_TYPE as CLOSEOUT_TYPE,
SQ_GW_CLOSEOUT_CTL.CLOSEOUT_SEQ_NBR as CLOSEOUT_SEQ_NBR,
SQ_GW_CLOSEOUT_CTL.BEGINNING_TS as BEGINNING_TS,
SQ_GW_CLOSEOUT_CTL.ENDING_TS as ENDING_TS,
SQ_GW_CLOSEOUT_CTL.EOM_DT as EOM_DT,
SQ_GW_CLOSEOUT_CTL.CTL_ID as CTL_ID,
:PRCS_ID as PROCESS_ID,
:p_LOAD_USER as LOAD_USER,
SQ_GW_CLOSEOUT_CTL.LOAD_DTTM as LOAD_DTTM,
SQ_GW_CLOSEOUT_CTL.source_record_id
FROM
SQ_GW_CLOSEOUT_CTL
);


-- Component GW_CLOSEOUT_CTL1, Type TARGET 
INSERT INTO DB_T_PROD_STAG.GW_CLOSEOUT_CTL
(
ACCOUNTING_YR,
ACCOUNTING_MO,
CLOSEOUT_TYPE,
CLOSEOUT_SEQ_NBR,
BEGINNING_TS,
ENDING_TS,
EOM_DT,
PRCS_ID,
CTL_ID,
LOAD_USER,
LOAD_DTTM
)
SELECT
exp_pass_through.ACCOUNTING_YR as ACCOUNTING_YR,
exp_pass_through.ACCOUNTING_MO as ACCOUNTING_MO,
exp_pass_through.CLOSEOUT_TYPE as CLOSEOUT_TYPE,
exp_pass_through.CLOSEOUT_SEQ_NBR as CLOSEOUT_SEQ_NBR,
exp_pass_through.BEGINNING_TS as BEGINNING_TS,
exp_pass_through.ENDING_TS as ENDING_TS,
exp_pass_through.EOM_DT as EOM_DT,
exp_pass_through.PROCESS_ID as PRCS_ID,
exp_pass_through.CTL_ID as CTL_ID,
exp_pass_through.LOAD_USER as LOAD_USER,
exp_pass_through.LOAD_DTTM as LOAD_DTTM
FROM
exp_pass_through;


END; ';