-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_XLAT_AUTO_2_COMPARE_WITH_SOURCE("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_XLAT_AUTOMATION_1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_XLAT_AUTOMATION_1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SRC_TBL_NM,
$2 as L_en_US,
$3 as PRIORITY,
$4 as TYPECODE,
$5 as S_en_US,
$6 as RETIRED,
$7 as NAME,
$8 as ID,
$9 as DESCRIPTION,
$10 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
XLAT_AUTMTN_ALL_SRC_REF.SRC_TBL_NM,
XLAT_AUTMTN_ALL_SRC_REF.L_en_US,
XLAT_AUTMTN_ALL_SRC_REF.PRIORITY,
XLAT_AUTMTN_ALL_SRC_REF.TYPECODE,
XLAT_AUTMTN_ALL_SRC_REF.S_en_US,
XLAT_AUTMTN_ALL_SRC_REF.RETIRED,
XLAT_AUTMTN_ALL_SRC_REF.NAME,
XLAT_AUTMTN_ALL_SRC_REF.ID,
XLAT_AUTMTN_ALL_SRC_REF.DESCRIPTION
FROM DB_T_PROD_STAG.XLAT_AUTMTN_ALL_SRC_REF
WHERE RETIRED=0
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_XLAT_AUTOMATION_1.SRC_TBL_NM as SRC_TBL_NM,
SQ_XLAT_AUTOMATION_1.SRC_TBL_NM || ''.typecode'' as SRC_TBL_NM_out,
SQ_XLAT_AUTOMATION_1.L_en_US as L_en_US,
SQ_XLAT_AUTOMATION_1.PRIORITY as PRIORITY,
RTRIM ( LTRIM ( SQ_XLAT_AUTOMATION_1.TYPECODE ) ) as TYPECODE_out,
SQ_XLAT_AUTOMATION_1.S_en_US as S_en_US,
SQ_XLAT_AUTOMATION_1.RETIRED as RETIRED,
SQ_XLAT_AUTOMATION_1.NAME as NAME,
SQ_XLAT_AUTOMATION_1.ID as ID,
SQ_XLAT_AUTOMATION_1.DESCRIPTION as DESCRIPTION,
SQ_XLAT_AUTOMATION_1.source_record_id
FROM
SQ_XLAT_AUTOMATION_1
);


-- Component LKP_XLAT_BASE, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_XLAT_BASE AS
(
SELECT
LKP.TGT_IDNTFTN_NM,
EXPTRANS.TYPECODE_out as TYPECODE_out,
EXPTRANS.source_record_id,
ROW_NUMBER() OVER(PARTITION BY EXPTRANS.source_record_id ORDER BY LKP.SRC_IDNTFTN_NM asc,LKP.SRC_IDNTFTN_VAL asc,LKP.TGT_IDNTFTN_NM asc) RNK
FROM
EXPTRANS
LEFT JOIN (
SELECT trim(SRC_IDNTFTN_NM) as SRC_IDNTFTN_NM  ,trim(SRC_IDNTFTN_VAL) as SRC_IDNTFTN_VAL ,  trim(TGT_IDNTFTN_NM) as TGT_IDNTFTN_NM
FROM DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT WHERE EXPN_DT=''9999-12-31''
) LKP ON LKP.SRC_IDNTFTN_NM = EXPTRANS.SRC_TBL_NM_out AND LKP.SRC_IDNTFTN_VAL = EXPTRANS.TYPECODE_out
QUALIFY RNK = 1
);


-- Component EXPTRANS1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS1 AS
(
SELECT
EXPTRANS.SRC_TBL_NM as SRC_TBL_NM,
EXPTRANS.SRC_TBL_NM || ''.typecode'' as SRC_TBL_NM_out,
EXPTRANS.L_en_US as L_en_US,
EXPTRANS.PRIORITY as PRIORITY,
EXPTRANS.TYPECODE_out as TYPECODE_out,
EXPTRANS.S_en_US as S_en_US,
EXPTRANS.RETIRED as RETIRED,
EXPTRANS.NAME as NAME,
EXPTRANS.ID as ID,
EXPTRANS.DESCRIPTION as DESCRIPTION,
LKP_XLAT_BASE.TGT_IDNTFTN_NM as TGT_IDNTFTN_NM,
CASE WHEN LKP_XLAT_BASE.TGT_IDNTFTN_NM IS NULL THEN ''N'' ELSE ''E'' END as ROW_IND,
EXPTRANS.source_record_id
FROM
EXPTRANS
INNER JOIN LKP_XLAT_BASE ON EXPTRANS.source_record_id = LKP_XLAT_BASE.source_record_id
);


-- Component FILTRANS, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE FILTRANS AS
(
SELECT
EXPTRANS1.SRC_TBL_NM as SRC_TBL_NM,
EXPTRANS1.SRC_TBL_NM_out as SRC_TBL_NM_out,
EXPTRANS1.L_en_US as L_en_US,
EXPTRANS1.PRIORITY as PRIORITY,
EXPTRANS1.TYPECODE_out as TYPECODE_out,
EXPTRANS1.S_en_US as S_en_US,
EXPTRANS1.RETIRED as RETIRED,
EXPTRANS1.NAME as NAME,
EXPTRANS1.ID as ID,
EXPTRANS1.DESCRIPTION as DESCRIPTION,
EXPTRANS1.TGT_IDNTFTN_NM as TGT_IDNTFTN_NM,
EXPTRANS1.ROW_IND as ROW_IND,
EXPTRANS1.source_record_id
FROM
EXPTRANS1
WHERE --EXPTRANS1.ROW_IND = ''N'' 
TRUE
);


-- Component SRTTRANS, Type SORTER 
CREATE OR REPLACE TEMPORARY TABLE SRTTRANS AS
(
SELECT
FILTRANS.SRC_TBL_NM as SRC_TBL_NM,
FILTRANS.SRC_TBL_NM_out as SRC_TBL_NM_out,
FILTRANS.L_en_US as L_en_US,
FILTRANS.PRIORITY as PRIORITY,
FILTRANS.TYPECODE_out as TYPECODE_out,
FILTRANS.S_en_US as S_en_US,
FILTRANS.RETIRED as RETIRED,
FILTRANS.NAME as NAME,
FILTRANS.ID as ID,
FILTRANS.DESCRIPTION as DESCRIPTION,
FILTRANS.TGT_IDNTFTN_NM as TGT_IDNTFTN_NM,
FILTRANS.ROW_IND as ROW_IND,
FILTRANS.source_record_id
FROM
FILTRANS
ORDER BY SRC_TBL_NM_out 
);


-- Component LKPTRANS, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKPTRANS AS
(
SELECT
LKP.TGT_IDNTFTN_NM,
SRTTRANS.SRC_TBL_NM_out as in_SRC_IDNTFTN_NM,
SRTTRANS.L_en_US as L_en_US,
SRTTRANS.PRIORITY as PRIORITY,
SRTTRANS.TYPECODE_out as TYPECODE_out,
SRTTRANS.S_en_US as S_en_US,
SRTTRANS.RETIRED as RETIRED,
SRTTRANS.NAME as NAME,
SRTTRANS.ID as ID,
SRTTRANS.DESCRIPTION as DESCRIPTION,
SRTTRANS.ROW_IND as ROW_IND,
SRTTRANS.source_record_id
FROM
SRTTRANS
LEFT JOIN (
SELECT TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM as TGT_IDNTFTN_NM, TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_NM as SRC_IDNTFTN_NM ,
TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL
FROM DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT
where EXPN_DT=''9999-12-31''
and SRC_IDNTFTN_SYS=''GW''
group by 1,2,3
) LKP ON LKP.SRC_IDNTFTN_NM = SRTTRANS.SRC_TBL_NM_out AND LKP.SRC_IDNTFTN_VAL = SRTTRANS.TYPECODE_out
);


-- Component XLAT_AUTMTN_CMPRSN, Type TARGET 
INSERT INTO DB_T_PROD_STAG.XLAT_AUTMTN_CMPRSN
(
SRC_TBL_NM,
L_en_US,
PRIORITY,
TYPECODE,
S_en_US,
RETIRED,
NAME,
ID,
DESCRIPTION,
TGT_IDNTFTN_NM,
ROW_IND
)
SELECT
LKPTRANS.in_SRC_IDNTFTN_NM as SRC_TBL_NM,
LKPTRANS.L_en_US as L_en_US,
LKPTRANS.PRIORITY as PRIORITY,
LKPTRANS.TYPECODE_out as TYPECODE,
LKPTRANS.S_en_US as S_en_US,
LKPTRANS.RETIRED as RETIRED,
LKPTRANS.NAME as NAME,
LKPTRANS.ID as ID,
LKPTRANS.DESCRIPTION as DESCRIPTION,
LKPTRANS.TGT_IDNTFTN_NM as TGT_IDNTFTN_NM,
LKPTRANS.ROW_IND as ROW_IND
FROM
LKPTRANS;


END; ';