-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_RENEWALS_AUTO_EXTRACT("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_WR_MULTILINE_METRICS_DTL, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_WR_MULTILINE_METRICS_DTL AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CAL_MTH,
$2 as AL_PERSONAL_TOTAL,
$3 as AL_COMMERCIAL_TOTAL,
$4 as GA_PERSONAL_TOTAL,
$5 as GA_COMMERCIAL_TOTAL,
$6 as MS_PERSONAL_TOTAL,
$7 as MS_COMMERCIAL_TOTAL,
$8 as GRAND_TOTAL,
$9 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
/* For Auto renewal extract: */




SELECT TO_CHAR(SRC.CALENDAR_DATE, ''YYYYMM'') AS CAL_MTH



,SUM(case when SRC.SALES_ST_CD = ''AL'' AND SRC.PLCY_TYPE_CD in (''PPV'',''PPV2'') then SRC.UNIT_CNT_END_IFO else 0 END ) as AL_PERSONAL_TOTAL

,SUM(case when SRC.SALES_ST_CD = ''AL'' AND SRC.PLCY_TYPE_CD not in (''PPV'',''PPV2'') then SRC.UNIT_CNT_END_IFO else 0 END ) as AL_COMMERCIAL_TOTAL



,SUM(case when SRC.SALES_ST_CD = ''GA'' AND SRC.PLCY_TYPE_CD in (''PPV'',''PPV2'') then SRC.UNIT_CNT_END_IFO else 0 END ) as GA_PERSONAL_TOTAL

,SUM(case when SRC.SALES_ST_CD = ''GA'' AND SRC.PLCY_TYPE_CD not in (''PPV'',''PPV2'') then SRC.UNIT_CNT_END_IFO else 0 END ) as GA_COMMERCIAL_TOTAL



,SUM(case when SRC.SALES_ST_CD = ''MS'' AND SRC.PLCY_TYPE_CD in (''PPV'',''PPV2'') then SRC.UNIT_CNT_END_IFO else 0 END ) as MS_PERSONAL_TOTAL

,SUM(case when SRC.SALES_ST_CD = ''MS'' AND SRC.PLCY_TYPE_CD not in (''PPV'',''PPV2'') then SRC.UNIT_CNT_END_IFO else 0 END ) as MS_COMMERCIAL_TOTAL



,SUM( SRC.UNIT_CNT_END_IFO ) as GRAND_TOTAL

FROM

(

select  distinct  

B.PLCY_INCPTN_DT , B.PLCY_PRD_TERM_EFF_DT, A.HOST_AGMT_NUM,

A.CALENDAR_DATE , A.UNIT_CNT_END_IFO , A.SALES_ST_CD , A.PLCY_TYPE_CD

FROM DB_V_PROD_ACT.WR_MULTILINE_METRICS_DTL A

JOIN DB_V_PROD_AUDT.D_PLCY_PRD B ON A.HOST_AGMT_NUM = B.PLCY_PRD_PLCY_NUM



WHERE calendar_date >= $Report_Start_Date

and calendar_date <= $Report_End_Date

AND A.LOB_CD = ''PA''

AND ( A.CALENDAR_DATE - B.PLCY_INCPTN_DT ) > 184    /*Inception Date must be greater than 184 days prior to DB_SP_PROD.Calendar Date*/





/*Policy Term Effective Date must be the same month and year of DB_SP_PROD.Calendar Date*/

AND EXTRACT(YEAR ,B.PLCY_PRD_TERM_EFF_DT) = Extract(YEAR , A.CALENDAR_DATE)

AND EXTRACT(MONTH ,B.PLCY_PRD_TERM_EFF_DT) = Extract(MONTH , A.CALENDAR_DATE)

) src

GROUP BY CAL_MTH

ORDER BY CAL_MTH
) SRC
)
);


-- Component exp_pass_through_auto, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through_auto AS
(
SELECT
SQ_WR_MULTILINE_METRICS_DTL.CAL_MTH as CAL_MTH,
SQ_WR_MULTILINE_METRICS_DTL.AL_PERSONAL_TOTAL as AL_PERSONAL_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL.AL_COMMERCIAL_TOTAL as AL_COMMERCIAL_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL.GA_PERSONAL_TOTAL as GA_PERSONAL_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL.GA_COMMERCIAL_TOTAL as GA_COMMERCIAL_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL.MS_PERSONAL_TOTAL as MS_PERSONAL_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL.MS_COMMERCIAL_TOTAL as MS_COMMERCIAL_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL.GRAND_TOTAL as GRAND_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL.source_record_id
FROM
SQ_WR_MULTILINE_METRICS_DTL
);


-- Component auto_renewals_extract, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE auto_renewals_extract AS
(
SELECT
exp_pass_through_auto.CAL_MTH as CAL_MTH,
exp_pass_through_auto.AL_PERSONAL_TOTAL as AL_PERSONAL_TOTAL,
exp_pass_through_auto.AL_COMMERCIAL_TOTAL as AL_COMMERCIAL_TOTAL,
exp_pass_through_auto.GA_PERSONAL_TOTAL as GA_PERSONAL_TOTAL,
exp_pass_through_auto.GA_COMMERCIAL_TOTAL as GA_COMMERCIAL_TOTAL,
exp_pass_through_auto.MS_PERSONAL_TOTAL as MS_PERSONAL_TOTAL,
exp_pass_through_auto.MS_COMMERCIAL_TOTAL as MS_COMMERCIAL_TOTAL,
exp_pass_through_auto.GRAND_TOTAL as GRAND_TOTAL
FROM
exp_pass_through_auto
);


-- Component auto_renewals_extract, Type EXPORT_DATA Exporting data
;


END; ';