-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_RENEWALS_NEW_POLICY_UNIT_COUNT_EXTRACT("PARAM_JSON" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_WR_MULTILINE_METRICS_DTL2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_WR_MULTILINE_METRICS_DTL2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CAL_YR,
$2 as CAL_MTH,
$3 as AL_PERSONAL_POLICY_COUNT_TOTAL,
$4 as AL_COMMERCIAL_POLICY_COUNT_TOTAL,
$5 as GA_PERSONAL_POLICY_COUNT_TOTAL,
$6 as GA_COMMERCIAL_POLICY_COUNT_TOTAL,
$7 as MS_PERSONAL_POLICY_COUNT_TOTAL,
$8 as MS_COMMERCIAL_POLICY_COUNT_TOTAL,
$9 as GRAND_TOTAL_POLICY_COUNT,
$10 as AL_PERSONAL_UNIT_COUNT_TOTAL,
$11 as AL_COMMERCIAL_UNIT_COUNT_TOTAL,
$12 as GA_PERSONAL_UNIT_COUNT_TOTAL,
$13 as GA_COMMERCIAL_UNIT_COUNT_TOTAL,
$14 as MS_PERSONAL_UNIT_COUNT_TOTAL,
$15 as MS_COMMERCIAL_UNIT_COUNT_TOTAL,
$16 as GRAND_TOTAL_UNIT_COUNT,
$17 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
/* New DB_T_CORE_DM_PROD.Policy COUNT */




select EXTRACT(year, calendar_date) AS CAL_YR,  EXTRACT(year, calendar_date) AS CAL_MTH

,SUM(case when A.SALES_ST_CD = ''AL'' AND A.PLCY_TYPE_CD in (''PPV'',''PPV2'') then A.PLCY_CNT_NEW_BUSI else 0 END ) as AL_PERSONAL_POLICY_COUNT_TOTAL

,SUM(case when A.SALES_ST_CD = ''AL'' AND A.PLCY_TYPE_CD NOT in (''PPV'',''PPV2'') then A.PLCY_CNT_NEW_BUSI else 0 END ) as AL_COMMERCIAL_POLICY_COUNT_TOTAL



,SUM(case when A.SALES_ST_CD = ''GA'' AND A.PLCY_TYPE_CD in (''PPV'',''PPV2'') then A.PLCY_CNT_NEW_BUSI else 0 END ) as GA_PERSONAL_POLICY_COUNT_TOTAL

,SUM(case when A.SALES_ST_CD = ''GA'' AND A.PLCY_TYPE_CD NOT in (''PPV'',''PPV2'') then A.PLCY_CNT_NEW_BUSI else 0 END ) as GA_COMMERCIAL_POLICY_COUNT_TOTAL



,SUM(case when A.SALES_ST_CD = ''MS'' AND A.PLCY_TYPE_CD in (''PPV'',''PPV2'') then A.PLCY_CNT_NEW_BUSI else 0 END ) as MS_PERSONAL_POLICY_COUNT_TOTAL

,SUM(case when A.SALES_ST_CD = ''MS'' AND A.PLCY_TYPE_CD NOT in (''PPV'',''PPV2'') then A.PLCY_CNT_NEW_BUSI else 0 END ) as MS_COMMERCIAL_POLICY_COUNT_TOTAL



,SUM(A.PLCY_CNT_NEW_BUSI) AS GRAND_TOTAL_POLICY_COUNT 



,SUM(case when A.SALES_ST_CD = ''AL'' AND A.PLCY_TYPE_CD in (''PPV'',''PPV2'') then A.UNIT_CNT_NEW_BUSI else 0 END ) as AL_PERSONAL_UNIT_COUNT_TOTAL

,SUM(case when A.SALES_ST_CD = ''AL'' AND A.PLCY_TYPE_CD NOT in (''PPV'',''PPV2'') then A.UNIT_CNT_NEW_BUSI else 0 END ) as AL_COMMERCIAL_UNIT_COUNT_TOTAL



,SUM(case when A.SALES_ST_CD = ''GA'' AND A.PLCY_TYPE_CD in (''PPV'',''PPV2'') then A.UNIT_CNT_NEW_BUSI else 0 END ) as GA_PERSONAL_UNIT_COUNT_TOTAL

,SUM(case when A.SALES_ST_CD = ''GA'' AND A.PLCY_TYPE_CD NOT in (''PPV'',''PPV2'') then A.UNIT_CNT_NEW_BUSI else 0 END ) as GA_COMMERCIAL_UNIT_COUNT_TOTAL



,SUM(case when A.SALES_ST_CD = ''MS'' AND A.PLCY_TYPE_CD in (''PPV'',''PPV2'') then A.UNIT_CNT_NEW_BUSI else 0 END ) as MS_PERSONAL_UNIT_COUNT_TOTAL

,SUM(case when A.SALES_ST_CD = ''MS'' AND A.PLCY_TYPE_CD NOT in (''PPV'',''PPV2'') then A.UNIT_CNT_NEW_BUSI else 0 END ) as MS_COMMERCIAL_UNIT_COUNT_TOTAL

,SUM(A.UNIT_CNT_NEW_BUSI) AS GRAND_TOTAL_UNIT_COUNT

from DB_V_PROD_ACT.WR_MULTILINE_METRICS_DTL A

where calendar_date >= $Report_Start_Date

and calendar_date <= $Report_End_Date

and lob_cd = ''PA''

AND A.PLCY_CNT_NEW_BUSI <> 0

group by CAL_YR, CAL_MTH



UNION



SELECT EXTRACT(year, calendar_date) AS CAL_YR, extract(month, calendar_date) AS CAL_MTH /* TO_CHAR(CALENDAR_DATE, ''YYYY'') AS CAL_YEAR, SALES_ST_CD AS SALES_STATE,  */


,SUM(case when A.SALES_ST_CD = ''AL'' AND A.PLCY_TYPE_CD in (''PPV'',''PPV2'') then A.PLCY_CNT_NEW_BUSI else 0 END ) as AL_PERSONAL_POLICY_COUNT_TOTAL

,SUM(case when A.SALES_ST_CD = ''AL'' AND A.PLCY_TYPE_CD NOT in (''PPV'',''PPV2'') then A.PLCY_CNT_NEW_BUSI else 0 END ) as AL_COMMERCIAL_POLICY_COUNT_TOTAL



,SUM(case when A.SALES_ST_CD = ''GA'' AND A.PLCY_TYPE_CD in (''PPV'',''PPV2'') then A.PLCY_CNT_NEW_BUSI else 0 END ) as GA_PERSONAL_POLICY_COUNT_TOTAL

,SUM(case when A.SALES_ST_CD = ''GA'' AND A.PLCY_TYPE_CD NOT in (''PPV'',''PPV2'') then A.PLCY_CNT_NEW_BUSI else 0 END ) as GA_COMMERCIAL_POLICY_COUNT_TOTAL



,SUM(case when A.SALES_ST_CD = ''MS'' AND A.PLCY_TYPE_CD in (''PPV'',''PPV2'') then A.PLCY_CNT_NEW_BUSI else 0 END ) as MS_PERSONAL_POLICY_COUNT_TOTAL

,SUM(case when A.SALES_ST_CD = ''MS'' AND A.PLCY_TYPE_CD NOT in (''PPV'',''PPV2'') then A.PLCY_CNT_NEW_BUSI else 0 END ) as MS_COMMERCIAL_POLICY_COUNT_TOTAL



,SUM(A.PLCY_CNT_NEW_BUSI) AS GRAND_TOTAL_POLICY_COUNT 



,SUM(case when A.SALES_ST_CD = ''AL'' AND A.PLCY_TYPE_CD in (''PPV'',''PPV2'') then A.UNIT_CNT_NEW_BUSI else 0 END ) as AL_PERSONAL_UNIT_COUNT_TOTAL

,SUM(case when A.SALES_ST_CD = ''AL'' AND A.PLCY_TYPE_CD NOT in (''PPV'',''PPV2'') then A.UNIT_CNT_NEW_BUSI else 0 END ) as AL_COMMERCIAL_UNIT_COUNT_TOTAL



,SUM(case when A.SALES_ST_CD = ''GA'' AND A.PLCY_TYPE_CD in (''PPV'',''PPV2'') then A.UNIT_CNT_NEW_BUSI else 0 END ) as GA_PERSONAL_UNIT_COUNT_TOTAL

,SUM(case when A.SALES_ST_CD = ''GA'' AND A.PLCY_TYPE_CD NOT in (''PPV'',''PPV2'') then A.UNIT_CNT_NEW_BUSI else 0 END ) as GA_COMMERCIAL_UNIT_COUNT_TOTAL



,SUM(case when A.SALES_ST_CD = ''MS'' AND A.PLCY_TYPE_CD in (''PPV'',''PPV2'') then A.UNIT_CNT_NEW_BUSI else 0 END ) as MS_PERSONAL_UNIT_COUNT_TOTAL

,SUM(case when A.SALES_ST_CD = ''MS'' AND A.PLCY_TYPE_CD NOT in (''PPV'',''PPV2'') then A.UNIT_CNT_NEW_BUSI else 0 END ) as MS_COMMERCIAL_UNIT_COUNT_TOTAL

,SUM(A.UNIT_CNT_NEW_BUSI) AS GRAND_TOTAL_UNIT_COUNT





FROM DB_V_PROD_ACT.WR_MULTILINE_METRICS_DTL A



WHERE calendar_date >= $Report_Start_Date

and calendar_date <= $Report_End_Date

and LOB_CD = ''PA''

AND A.PLCY_CNT_NEW_BUSI <> 0

GROUP BY CAL_MTH, CAL_YR



ORDER BY 1,2
) SRC
)
);


-- Component exp_pass_through_new_policy, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through_new_policy AS
(
SELECT
SQ_WR_MULTILINE_METRICS_DTL2.CAL_YR as CAL_YR,
SQ_WR_MULTILINE_METRICS_DTL2.CAL_MTH as CAL_MTH,
SQ_WR_MULTILINE_METRICS_DTL2.AL_PERSONAL_POLICY_COUNT_TOTAL as AL_PERSONAL_POLICY_COUNT_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL2.AL_COMMERCIAL_POLICY_COUNT_TOTAL as AL_COMMERCIAL_POLICY_COUNT_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL2.GA_PERSONAL_POLICY_COUNT_TOTAL as GA_PERSONAL_POLICY_COUNT_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL2.GA_COMMERCIAL_POLICY_COUNT_TOTAL as GA_COMMERCIAL_POLICY_COUNT_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL2.MS_PERSONAL_POLICY_COUNT_TOTAL as MS_PERSONAL_POLICY_COUNT_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL2.MS_COMMERCIAL_POLICY_COUNT_TOTAL as MS_COMMERCIAL_POLICY_COUNT_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL2.GRAND_TOTAL_POLICY_COUNT as GRAND_TOTAL_POLICY_COUNT,
SQ_WR_MULTILINE_METRICS_DTL2.AL_PERSONAL_UNIT_COUNT_TOTAL as AL_PERSONAL_UNIT_COUNT_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL2.AL_COMMERCIAL_UNIT_COUNT_TOTAL as AL_COMMERCIAL_UNIT_COUNT_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL2.GA_PERSONAL_UNIT_COUNT_TOTAL as GA_PERSONAL_UNIT_COUNT_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL2.GA_COMMERCIAL_UNIT_COUNT_TOTAL as GA_COMMERCIAL_UNIT_COUNT_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL2.MS_PERSONAL_UNIT_COUNT_TOTAL as MS_PERSONAL_UNIT_COUNT_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL2.MS_COMMERCIAL_UNIT_COUNT_TOTAL as MS_COMMERCIAL_UNIT_COUNT_TOTAL,
SQ_WR_MULTILINE_METRICS_DTL2.GRAND_TOTAL_UNIT_COUNT as GRAND_TOTAL_UNIT_COUNT,
SQ_WR_MULTILINE_METRICS_DTL2.source_record_id
FROM
SQ_WR_MULTILINE_METRICS_DTL2
);


-- Component new_policy_count_extract, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE new_policy_count_extract AS
(
SELECT
exp_pass_through_new_policy.CAL_YR as CAL_YR,
exp_pass_through_new_policy.CAL_MTH as CAL_MTH,
exp_pass_through_new_policy.AL_PERSONAL_POLICY_COUNT_TOTAL as AL_PERSONAL_POLICY_COUNT_TOTAL,
exp_pass_through_new_policy.AL_COMMERCIAL_POLICY_COUNT_TOTAL as AL_COMMERCIAL_POLICY_COUNT_TOTAL,
exp_pass_through_new_policy.GA_PERSONAL_POLICY_COUNT_TOTAL as GA_PERSONAL_POLICY_COUNT_TOTAL,
exp_pass_through_new_policy.GA_COMMERCIAL_POLICY_COUNT_TOTAL as GA_COMMERCIAL_POLICY_COUNT_TOTAL,
exp_pass_through_new_policy.MS_PERSONAL_POLICY_COUNT_TOTAL as MS_PERSONAL_POLICY_COUNT_TOTAL,
exp_pass_through_new_policy.MS_COMMERCIAL_POLICY_COUNT_TOTAL as MS_COMMERCIAL_POLICY_COUNT_TOTAL,
exp_pass_through_new_policy.GRAND_TOTAL_POLICY_COUNT as GRAND_TOTAL_POLICY_COUNT,
exp_pass_through_new_policy.AL_PERSONAL_UNIT_COUNT_TOTAL as AL_PERSONAL_UNIT_COUNT_TOTAL,
exp_pass_through_new_policy.AL_COMMERCIAL_UNIT_COUNT_TOTAL as AL_COMMERCIAL_UNIT_COUNT_TOTAL,
exp_pass_through_new_policy.GA_PERSONAL_UNIT_COUNT_TOTAL as GA_PERSONAL_UNIT_COUNT_TOTAL,
exp_pass_through_new_policy.GA_COMMERCIAL_UNIT_COUNT_TOTAL as GA_COMMERCIAL_UNIT_COUNT_TOTAL,
exp_pass_through_new_policy.MS_PERSONAL_UNIT_COUNT_TOTAL as MS_PERSONAL_UNIT_COUNT_TOTAL,
exp_pass_through_new_policy.MS_COMMERCIAL_UNIT_COUNT_TOTAL as MS_COMMERCIAL_UNIT_COUNT_TOTAL,
exp_pass_through_new_policy.GRAND_TOTAL_UNIT_COUNT as GRAND_TOTAL_UNIT_COUNT
FROM
exp_pass_through_new_policy
);


-- Component new_policy_count_extract, Type EXPORT_DATA Exporting data
;


END; ';