-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_WRK_EDW_AUTO_EBLM_CLAIM_EXTRACT("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
       run_id STRING;
       PRCS_ID STRING;
	   v_start_time TIMESTAMP;
BEGIN
       run_id := (SELECT run_id FROM control_worklet WHERE worklet_name = :worklet_name ORDER BY insert_ts DESC LIMIT 1);
       PRCS_ID := (SELECT param_value FROM control_params WHERE run_id = :run_id AND param_name = ''PRCS_ID'' LIMIT 1);
	   v_start_time := CURRENT_TIMESTAMP();

-- Component sq_edw_eblm_clm_dtl1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_edw_eblm_clm_dtl1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as PLCY_VEH_KEY,
$2 as CLM_NBR,
$3 as CLM_LOSS_DT,
$4 as ACC_ST_CD,
$5 as BI_NET_PAID_LOSS_DCC,
$6 as BI_NET_INCURRED_LOSS,
$7 as BI_NET_INCURRED_LOSS_DCC,
$8 as BI_GROSS_INCURRED_LOSS_DCC,
$9 as CMP_NET_PAID_LOSS_DCC,
$10 as CMP_NET_INCURRED_LOSS,
$11 as CMP_NET_INCURRED_LOSS_DCC,
$12 as CMP_GROSS_INCURRED_LOSS_DCC,
$13 as COL_NET_PAID_LOSS_DCC,
$14 as COL_NET_INCURRED_LOSS,
$15 as COL_NET_INCURRED_LOSS_DCC,
$16 as COL_GROSS_INCURRED_LOSS_DCC,
$17 as CS_NET_PAID_LOSS_DCC,
$18 as CS_NET_INCURRED_LOSS,
$19 as CS_NET_INCURRED_LOSS_DCC,
$20 as CS_GROSS_INCURRED_LOSS_DCC,
$21 as CUS_NET_PAID_LOSS_DCC,
$22 as CUS_NET_INCURRED_LOSS,
$23 as CUS_NET_INCURRED_LOSS_DCC,
$24 as CUS_GROSS_INCURRED_LOSS_DCC,
$25 as ERS_NET_PAID_LOSS_DCC,
$26 as ERS_NET_INCURRED_LOSS,
$27 as ERS_NET_INCURRED_LOSS_DCC,
$28 as ERS_GROSS_INCURRED_LOSS_DCC,
$29 as EXN_NET_PAID_LOSS_DCC,
$30 as EXN_NET_INCURRED_LOSS,
$31 as EXN_NET_INCURRED_LOSS_DCC,
$32 as EXN_GROSS_INCURRED_LOSS_DCC,
$33 as GAP_NET_PAID_LOSS_DCC,
$34 as GAP_NET_INCURRED_LOSS,
$35 as GAP_NET_INCURRED_LOSS_DCC,
$36 as GAP_GROSS_INCURRED_LOSS_DCC,
$37 as LOI_NET_PAID_LOSS_DCC,
$38 as LOI_NET_INCURRED_LOSS,
$39 as LOI_NET_INCURRED_LOSS_DCC,
$40 as LOI_GROSS_INCURRED_LOSS_DCC,
$41 as LOU_NET_PAID_LOSS_DCC,
$42 as LOU_NET_INCURRED_LOSS,
$43 as LOU_NET_INCURRED_LOSS_DCC,
$44 as LOU_GROSS_INCURRED_LOSS_DCC,
$45 as MED_NET_PAID_LOSS_DCC,
$46 as MED_NET_INCURRED_LOSS,
$47 as MED_NET_INCURRED_LOSS_DCC,
$48 as MED_GROSS_INCURRED_LOSS_DCC,
$49 as PD_NET_PAID_LOSS_DCC,
$50 as PD_NET_INCURRED_LOSS,
$51 as PD_NET_INCURRED_LOSS_DCC,
$52 as PD_GROSS_INCURRED_LOSS_DCC,
$53 as SG_NET_PAID_LOSS_DCC,
$54 as SG_NET_INCURRED_LOSS,
$55 as SG_NET_INCURRED_LOSS_DCC,
$56 as SG_GROSS_INCURRED_LOSS_DCC,
$57 as SL_NET_PAID_LOSS_DCC,
$58 as SL_NET_INCURRED_LOSS,
$59 as SL_NET_INCURRED_LOSS_DCC,
$60 as SL_GROSS_INCURRED_LOSS_DCC,
$61 as UNB_NET_PAID_LOSS_DCC,
$62 as UNB_NET_INCURRED_LOSS,
$63 as UNB_NET_INCURRED_LOSS_DCC,
$64 as UNB_GROSS_INCURRED_LOSS_DCC,
$65 as UND_NET_PAID_LOSS_DCC,
$66 as UND_NET_INCURRED_LOSS,
$67 as UND_NET_INCURRED_LOSS_DCC,
$68 as UND_GROSS_INCURRED_LOSS_DCC,
$69 as UNP_NET_PAID_LOSS_DCC,
$70 as UNP_NET_INCURRED_LOSS,
$71 as UNP_NET_INCURRED_LOSS_DCC,
$72 as UNP_GROSS_INCURRED_LOSS_DCC,
$73 as UNSL_NET_PAID_LOSS_DCC,
$74 as UNSL_NET_INCURRED_LOSS,
$75 as UNSL_NET_INCURRED_LOSS_DCC,
$76 as UNSL_GROSS_INCURRED_LOSS_DCC,
$77 as BI_NET_PAID_LOSS,
$78 as BI_GROSS_PAID_LOSS,
$79 as BI_GROSS_PAID_LOSS_DCC,
$80 as BI_GROSS_INCURRED_LOSS,
$81 as CMP_NET_PAID_LOSS,
$82 as CMP_GROSS_PAID_LOSS,
$83 as CMP_GROSS_PAID_LOSS_DCC,
$84 as CMP_GROSS_INCURRED_LOSS,
$85 as COL_NET_PAID_LOSS,
$86 as COL_GROSS_PAID_LOSS,
$87 as COL_GROSS_PAID_LOSS_DCC,
$88 as COL_GROSS_INCURRED_LOSS,
$89 as CS_NET_PAID_LOSS,
$90 as CS_GROSS_PAID_LOSS,
$91 as CS_GROSS_PAID_LOSS_DCC,
$92 as CS_GROSS_INCURRED_LOSS,
$93 as CUS_NET_PAID_LOSS,
$94 as CUS_GROSS_PAID_LOSS,
$95 as CUS_GROSS_PAID_LOSS_DCC,
$96 as CUS_GROSS_INCURRED_LOSS,
$97 as ERS_NET_PAID_LOSS,
$98 as ERS_GROSS_PAID_LOSS,
$99 as ERS_GROSS_PAID_LOSS_DCC,
$100 as ERS_GROSS_INCURRED_LOSS,
$101 as EXN_NET_PAID_LOSS,
$102 as EXN_GROSS_PAID_LOSS,
$103 as EXN_GROSS_PAID_LOSS_DCC,
$104 as EXN_GROSS_INCURRED_LOSS,
$105 as GAP_NET_PAID_LOSS,
$106 as GAP_GROSS_PAID_LOSS,
$107 as GAP_GROSS_PAID_LOSS_DCC,
$108 as GAP_GROSS_INCURRED_LOSS,
$109 as LOI_NET_PAID_LOSS,
$110 as LOI_GROSS_PAID_LOSS,
$111 as LOI_GROSS_PAID_LOSS_DCC,
$112 as LOI_GROSS_INCURRED_LOSS,
$113 as LOU_NET_PAID_LOSS,
$114 as LOU_GROSS_PAID_LOSS,
$115 as LOU_GROSS_PAID_LOSS_DCC,
$116 as LOU_GROSS_INCURRED_LOSS,
$117 as MED_NET_PAID_LOSS,
$118 as MED_GROSS_PAID_LOSS,
$119 as MED_GROSS_PAID_LOSS_DCC,
$120 as MED_GROSS_INCURRED_LOSS,
$121 as PD_NET_PAID_LOSS,
$122 as PD_GROSS_PAID_LOSS,
$123 as PD_GROSS_PAID_LOSS_DCC,
$124 as PD_GROSS_INCURRED_LOSS,
$125 as SG_NET_PAID_LOSS,
$126 as SG_GROSS_PAID_LOSS,
$127 as SG_GROSS_PAID_LOSS_DCC,
$128 as SG_GROSS_INCURRED_LOSS,
$129 as SL_NET_PAID_LOSS,
$130 as SL_GROSS_PAID_LOSS,
$131 as SL_GROSS_PAID_LOSS_DCC,
$132 as SL_GROSS_INCURRED_LOSS,
$133 as UNB_NET_PAID_LOSS,
$134 as UNB_GROSS_PAID_LOSS,
$135 as UNB_GROSS_PAID_LOSS_DCC,
$136 as UNB_GROSS_INCURRED_LOSS,
$137 as UND_NET_PAID_LOSS,
$138 as UND_GROSS_PAID_LOSS,
$139 as UND_GROSS_PAID_LOSS_DCC,
$140 as UND_GROSS_INCURRED_LOSS,
$141 as UNP_NET_PAID_LOSS,
$142 as UNP_GROSS_PAID_LOSS,
$143 as UNP_GROSS_PAID_LOSS_DCC,
$144 as UNP_GROSS_INCURRED_LOSS,
$145 as UNSL_NET_PAID_LOSS,
$146 as UNSL_GROSS_PAID_LOSS,
$147 as UNSL_GROSS_PAID_LOSS_DCC,
$148 as UNSL_GROSS_INCURRED_LOSS,
$149 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT    

A.PLCY_VEH_KEY                     

,A.CLM_NBR                          

,A.CLM_LOSS_DT                      

,A.ACC_ST_CD           

,(BI_DIRECT_LOSS_AMT + BI_DCC_EXPENSE_AMT) - (BI_SALVAGE_RECOVERY_AMT - BI_SALVAGE_EXPENSE_AMT) - (BI_SUBR_RECOVERY_AMT - BI_SUBR_EXPENSE_AMT ) - BI_DIR_LOSS_RECOVERY_AMT - BI_DCC_RECOVERY_AMT  AS BI_NET_PAID_LOSS_DCC

,(BI_DIRECT_LOSS_AMT + BI_LOSS_RES_AMT) - (BI_SALVAGE_RECOVERY_AMT - BI_SALVAGE_EXPENSE_AMT) - (BI_SUBR_RECOVERY_AMT - BI_SUBR_EXPENSE_AMT ) - BI_DIR_LOSS_RECOVERY_AMT  AS BI_NET_INCURRED_LOSS

,(BI_DIRECT_LOSS_AMT + BI_LOSS_RES_AMT) + (BI_DCC_EXPENSE_AMT+0) - (BI_SALVAGE_RECOVERY_AMT - BI_SALVAGE_EXPENSE_AMT) - (BI_SUBR_RECOVERY_AMT - BI_SUBR_EXPENSE_AMT ) - BI_DIR_LOSS_RECOVERY_AMT - BI_DCC_RECOVERY_AMT  AS BI_NET_INCURRED_LOSS_DCC

,(BI_DIRECT_LOSS_AMT + BI_LOSS_RES_AMT) + (BI_DCC_EXPENSE_AMT+0)  AS BI_GROSS_INCURRED_LOSS_DCC

,(0 + CMP_DCC_EXPENSE_AMT) - (CMP_SALVAGE_RECOVERY_AMT - CMP_SALVAGE_EXPENSE_AMT) - (CMP_SUBR_RECOVERY_AMT - CMP_SUBR_EXPENSE_AMT ) - CMP_DIR_LOSS_RECOVERY_AMT - CMP_DCC_RECOVERY_AMT  AS CMP_NET_PAID_LOSS_DCC

,(0 + CMP_LOSS_RES_AMT) - (CMP_SALVAGE_RECOVERY_AMT - CMP_SALVAGE_EXPENSE_AMT) - (CMP_SUBR_RECOVERY_AMT - CMP_SUBR_EXPENSE_AMT ) - CMP_DIR_LOSS_RECOVERY_AMT  AS CMP_NET_INCURRED_LOSS

,(0 + CMP_LOSS_RES_AMT) + (CMP_DCC_EXPENSE_AMT+0) - (CMP_SALVAGE_RECOVERY_AMT - CMP_SALVAGE_EXPENSE_AMT) - (CMP_SUBR_RECOVERY_AMT - CMP_SUBR_EXPENSE_AMT ) - CMP_DIR_LOSS_RECOVERY_AMT - CMP_DCC_RECOVERY_AMT  AS CMP_NET_INCURRED_LOSS_DCC

,(0 + CMP_LOSS_RES_AMT) + (CMP_DCC_EXPENSE_AMT+0)  AS CMP_GROSS_INCURRED_LOSS_DCC

,(COL_DIRECT_LOSS_AMT + COL_DCC_EXPENSE_AMT) - (COL_SALVAGE_RECOVERY_AMT - COL_SALVAGE_EXPENSE_AMT) - (COL_SUBR_RECOVERY_AMT - COL_SUBR_EXPENSE_AMT ) - COL_DIR_LOSS_RECOVERY_AMT - COL_DCC_RECOVERY_AMT  AS COL_NET_PAID_LOSS_DCC

,(COL_DIRECT_LOSS_AMT + COL_LOSS_RES_AMT) - (COL_SALVAGE_RECOVERY_AMT - COL_SALVAGE_EXPENSE_AMT) - (COL_SUBR_RECOVERY_AMT - COL_SUBR_EXPENSE_AMT ) - COL_DIR_LOSS_RECOVERY_AMT  AS COL_NET_INCURRED_LOSS

,(COL_DIRECT_LOSS_AMT + COL_LOSS_RES_AMT) + (COL_DCC_EXPENSE_AMT+0) - (COL_SALVAGE_RECOVERY_AMT - COL_SALVAGE_EXPENSE_AMT) - (COL_SUBR_RECOVERY_AMT - COL_SUBR_EXPENSE_AMT ) - COL_DIR_LOSS_RECOVERY_AMT - COL_DCC_RECOVERY_AMT  AS COL_NET_INCURRED_LOSS_DCC

,(COL_DIRECT_LOSS_AMT + COL_LOSS_RES_AMT) + (COL_DCC_EXPENSE_AMT+0)  AS COL_GROSS_INCURRED_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS CS_NET_PAID_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS CS_NET_INCURRED_LOSS

,CAST(0 AS DECIMAL(15,2))  AS CS_NET_INCURRED_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS CS_GROSS_INCURRED_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS CUS_NET_PAID_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS CUS_NET_INCURRED_LOSS

,CAST(0 AS DECIMAL(15,2))  AS CUS_NET_INCURRED_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS CUS_GROSS_INCURRED_LOSS_DCC

,(ERS_DIRECT_LOSS_AMT + ERS_DCC_EXPENSE_AMT) - (ERS_SALVAGE_RECOVERY_AMT - ERS_SALVAGE_EXPENSE_AMT) - (ERS_SUBR_RECOVERY_AMT - ERS_SUBR_EXPENSE_AMT ) - ERS_DIR_LOSS_RECOVERY_AMT - ERS_DCC_RECOVERY_AMT  AS ERS_NET_PAID_LOSS_DCC

,(ERS_DIRECT_LOSS_AMT + ERS_LOSS_RES_AMT) - (ERS_SALVAGE_RECOVERY_AMT - ERS_SALVAGE_EXPENSE_AMT) - (ERS_SUBR_RECOVERY_AMT - ERS_SUBR_EXPENSE_AMT ) - ERS_DIR_LOSS_RECOVERY_AMT  AS ERS_NET_INCURRED_LOSS

,(ERS_DIRECT_LOSS_AMT + ERS_LOSS_RES_AMT) + (ERS_DCC_EXPENSE_AMT+0) - (ERS_SALVAGE_RECOVERY_AMT - ERS_SALVAGE_EXPENSE_AMT) - (ERS_SUBR_RECOVERY_AMT - ERS_SUBR_EXPENSE_AMT ) - ERS_DIR_LOSS_RECOVERY_AMT - ERS_DCC_RECOVERY_AMT  AS ERS_NET_INCURRED_LOSS_DCC

,(ERS_DIRECT_LOSS_AMT + ERS_LOSS_RES_AMT) + (ERS_DCC_EXPENSE_AMT+0)  AS ERS_GROSS_INCURRED_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS EXN_NET_PAID_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS EXN_NET_INCURRED_LOSS

,CAST(0 AS DECIMAL(15,2))  AS EXN_NET_INCURRED_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS EXN_GROSS_INCURRED_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS GAP_NET_PAID_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS GAP_NET_INCURRED_LOSS

,CAST(0 AS DECIMAL(15,2))  AS GAP_NET_INCURRED_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS GAP_GROSS_INCURRED_LOSS_DCC

,(LOI_DIRECT_LOSS_AMT + LOI_DCC_EXPENSE_AMT) - (LOI_SALVAGE_RECOVERY_AMT - LOI_SALVAGE_EXPENSE_AMT) - (LOI_SUBR_RECOVERY_AMT - LOI_SUBR_EXPENSE_AMT ) - LOI_DIR_LOSS_RECOVERY_AMT - LOI_DCC_RECOVERY_AMT  AS LOI_NET_PAID_LOSS_DCC

,(LOI_DIRECT_LOSS_AMT + LOI_LOSS_RES_AMT) - (LOI_SALVAGE_RECOVERY_AMT - LOI_SALVAGE_EXPENSE_AMT) - (LOI_SUBR_RECOVERY_AMT - LOI_SUBR_EXPENSE_AMT ) - LOI_DIR_LOSS_RECOVERY_AMT  AS LOI_NET_INCURRED_LOSS

,(LOI_DIRECT_LOSS_AMT + LOI_LOSS_RES_AMT) + (LOI_DCC_EXPENSE_AMT+0) - (LOI_SALVAGE_RECOVERY_AMT - LOI_SALVAGE_EXPENSE_AMT) - (LOI_SUBR_RECOVERY_AMT - LOI_SUBR_EXPENSE_AMT ) - LOI_DIR_LOSS_RECOVERY_AMT - LOI_DCC_RECOVERY_AMT  AS LOI_NET_INCURRED_LOSS_DCC

,(LOI_DIRECT_LOSS_AMT + LOI_LOSS_RES_AMT) + (LOI_DCC_EXPENSE_AMT+0)  AS LOI_GROSS_INCURRED_LOSS_DCC

,(LOU_DIRECT_LOSS_AMT + LOU_DCC_EXPENSE_AMT) - (LOU_SALVAGE_RECOVERY_AMT - LOU_SALVAGE_EXPENSE_AMT) - (LOU_SUBR_RECOVERY_AMT - LOU_SUBR_EXPENSE_AMT ) - LOU_DIR_LOSS_RECOVERY_AMT - LOU_DCC_RECOVERY_AMT  AS LOU_NET_PAID_LOSS_DCC

,(LOU_DIRECT_LOSS_AMT + LOU_LOSS_RES_AMT) - (LOU_SALVAGE_RECOVERY_AMT - LOU_SALVAGE_EXPENSE_AMT) - (LOU_SUBR_RECOVERY_AMT - LOU_SUBR_EXPENSE_AMT ) - LOU_DIR_LOSS_RECOVERY_AMT  AS LOU_NET_INCURRED_LOSS

,(LOU_DIRECT_LOSS_AMT + LOU_LOSS_RES_AMT) + (LOU_DCC_EXPENSE_AMT+0) - (LOU_SALVAGE_RECOVERY_AMT - LOU_SALVAGE_EXPENSE_AMT) - (LOU_SUBR_RECOVERY_AMT - LOU_SUBR_EXPENSE_AMT ) - LOU_DIR_LOSS_RECOVERY_AMT - LOU_DCC_RECOVERY_AMT  AS LOU_NET_INCURRED_LOSS_DCC

,(LOU_DIRECT_LOSS_AMT + LOU_LOSS_RES_AMT) + (LOU_DCC_EXPENSE_AMT+0)  AS LOU_GROSS_INCURRED_LOSS_DCC

,(MED_DIRECT_LOSS_AMT + MED_DCC_EXPENSE_AMT) - (MED_SALVAGE_RECOVERY_AMT - MED_SALVAGE_EXPENSE_AMT) - (MED_SUBR_RECOVERY_AMT - MED_SUBR_EXPENSE_AMT ) - MED_DIR_LOSS_RECOVERY_AMT - MED_DCC_RECOVERY_AMT  AS MED_NET_PAID_LOSS_DCC

,(MED_DIRECT_LOSS_AMT + MED_LOSS_RES_AMT) - (MED_SALVAGE_RECOVERY_AMT - MED_SALVAGE_EXPENSE_AMT) - (MED_SUBR_RECOVERY_AMT - MED_SUBR_EXPENSE_AMT ) - MED_DIR_LOSS_RECOVERY_AMT  AS MED_NET_INCURRED_LOSS

,(MED_DIRECT_LOSS_AMT + MED_LOSS_RES_AMT) + (MED_DCC_EXPENSE_AMT+0) - (MED_SALVAGE_RECOVERY_AMT - MED_SALVAGE_EXPENSE_AMT) - (MED_SUBR_RECOVERY_AMT - MED_SUBR_EXPENSE_AMT ) - MED_DIR_LOSS_RECOVERY_AMT - MED_DCC_RECOVERY_AMT  AS MED_NET_INCURRED_LOSS_DCC

,(MED_DIRECT_LOSS_AMT + MED_LOSS_RES_AMT) + (MED_DCC_EXPENSE_AMT+0)  AS MED_GROSS_INCURRED_LOSS_DCC

,(PD_DIRECT_LOSS_AMT + PD_DCC_EXPENSE_AMT) - (PD_SALVAGE_RECOVERY_AMT - PD_SALVAGE_EXPENSE_AMT) - (PD_SUBR_RECOVERY_AMT - PD_SUBR_EXPENSE_AMT ) - PD_DIR_LOSS_RECOVERY_AMT - PD_DCC_RECOVERY_AMT  AS PD_NET_PAID_LOSS_DCC

,(PD_DIRECT_LOSS_AMT + PD_LOSS_RES_AMT) - (PD_SALVAGE_RECOVERY_AMT - PD_SALVAGE_EXPENSE_AMT) - (PD_SUBR_RECOVERY_AMT - PD_SUBR_EXPENSE_AMT ) - PD_DIR_LOSS_RECOVERY_AMT  AS PD_NET_INCURRED_LOSS

,(PD_DIRECT_LOSS_AMT + PD_LOSS_RES_AMT) + (PD_DCC_EXPENSE_AMT+0) - (PD_SALVAGE_RECOVERY_AMT - PD_SALVAGE_EXPENSE_AMT) - (PD_SUBR_RECOVERY_AMT - PD_SUBR_EXPENSE_AMT ) - PD_DIR_LOSS_RECOVERY_AMT - PD_DCC_RECOVERY_AMT  AS PD_NET_INCURRED_LOSS_DCC

,(PD_DIRECT_LOSS_AMT + PD_LOSS_RES_AMT) + (PD_DCC_EXPENSE_AMT+0)  AS PD_GROSS_INCURRED_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS SG_NET_PAID_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS SG_NET_INCURRED_LOSS

,CAST(0 AS DECIMAL(15,2))  AS SG_NET_INCURRED_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS SG_GROSS_INCURRED_LOSS_DCC

,(SL_DIRECT_LOSS_AMT + SL_DCC_EXPENSE_AMT) - (SL_SALVAGE_RECOVERY_AMT - SL_SALVAGE_EXPENSE_AMT) - (SL_SUBR_RECOVERY_AMT - SL_SUBR_EXPENSE_AMT ) - SL_DIR_LOSS_RECOVERY_AMT - SL_DCC_RECOVERY_AMT  AS SL_NET_PAID_LOSS_DCC

,(SL_DIRECT_LOSS_AMT + SL_LOSS_RES_AMT) - (SL_SALVAGE_RECOVERY_AMT - SL_SALVAGE_EXPENSE_AMT) - (SL_SUBR_RECOVERY_AMT - SL_SUBR_EXPENSE_AMT ) - SL_DIR_LOSS_RECOVERY_AMT  AS SL_NET_INCURRED_LOSS

,(SL_DIRECT_LOSS_AMT + SL_LOSS_RES_AMT) + (SL_DCC_EXPENSE_AMT+0) - (SL_SALVAGE_RECOVERY_AMT - SL_SALVAGE_EXPENSE_AMT) - (SL_SUBR_RECOVERY_AMT - SL_SUBR_EXPENSE_AMT ) - SL_DIR_LOSS_RECOVERY_AMT - SL_DCC_RECOVERY_AMT  AS SL_NET_INCURRED_LOSS_DCC

,(SL_DIRECT_LOSS_AMT + SL_LOSS_RES_AMT) + (SL_DCC_EXPENSE_AMT+0)  AS SL_GROSS_INCURRED_LOSS_DCC

,(UNB_DIRECT_LOSS_AMT + UNB_DCC_EXPENSE_AMT) - (UNB_SALVAGE_RECOVERY_AMT - UNB_SALVAGE_EXPENSE_AMT) - (UNB_SUBR_RECOVERY_AMT - UNB_SUBR_EXPENSE_AMT ) - UNB_DIR_LOSS_RECOVERY_AMT - UNB_DCC_RECOVERY_AMT  AS UNB_NET_PAID_LOSS_DCC

,(UNB_DIRECT_LOSS_AMT + UNB_LOSS_RES_AMT) - (UNB_SALVAGE_RECOVERY_AMT - UNB_SALVAGE_EXPENSE_AMT) - (UNB_SUBR_RECOVERY_AMT - UNB_SUBR_EXPENSE_AMT ) - UNB_DIR_LOSS_RECOVERY_AMT  AS UNB_NET_INCURRED_LOSS

,(UNB_DIRECT_LOSS_AMT + UNB_LOSS_RES_AMT) + (UNB_DCC_EXPENSE_AMT+0) - (UNB_SALVAGE_RECOVERY_AMT - UNB_SALVAGE_EXPENSE_AMT) - (UNB_SUBR_RECOVERY_AMT - UNB_SUBR_EXPENSE_AMT ) - UNB_DIR_LOSS_RECOVERY_AMT - UNB_DCC_RECOVERY_AMT  AS UNB_NET_INCURRED_LOSS_DCC

,(UNB_DIRECT_LOSS_AMT + UNB_LOSS_RES_AMT) + (UNB_DCC_EXPENSE_AMT+0)  AS UNB_GROSS_INCURRED_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS UND_NET_PAID_LOSS_DCC

,(0 + UND_LOSS_RES_AMT) - (0 - 0) - (0 - 0 ) - 0  AS UND_NET_INCURRED_LOSS

,(0 + UND_LOSS_RES_AMT) + (0+0) - (0 - 0) - (0 - 0 ) - 0 - 0  AS UND_NET_INCURRED_LOSS_DCC

,(0 + UND_LOSS_RES_AMT) + (0+0)  AS UND_GROSS_INCURRED_LOSS_DCC

,(UNP_DIRECT_LOSS_AMT + UNP_DCC_EXPENSE_AMT) - (UNP_SALVAGE_RECOVERY_AMT - UNP_SALVAGE_EXPENSE_AMT) - (UNP_SUBR_RECOVERY_AMT - UNP_SUBR_EXPENSE_AMT ) - UNP_DIR_LOSS_RECOVERY_AMT - UNP_DCC_RECOVERY_AMT  AS UNP_NET_PAID_LOSS_DCC

,(UNP_DIRECT_LOSS_AMT + UNP_LOSS_RES_AMT) - (UNP_SALVAGE_RECOVERY_AMT - UNP_SALVAGE_EXPENSE_AMT) - (UNP_SUBR_RECOVERY_AMT - UNP_SUBR_EXPENSE_AMT ) - UNP_DIR_LOSS_RECOVERY_AMT  AS UNP_NET_INCURRED_LOSS

,(UNP_DIRECT_LOSS_AMT + UNP_LOSS_RES_AMT) + (UNP_DCC_EXPENSE_AMT+0) - (UNP_SALVAGE_RECOVERY_AMT - UNP_SALVAGE_EXPENSE_AMT) - (UNP_SUBR_RECOVERY_AMT - UNP_SUBR_EXPENSE_AMT ) - UNP_DIR_LOSS_RECOVERY_AMT - UNP_DCC_RECOVERY_AMT  AS UNP_NET_INCURRED_LOSS_DCC

,(UNP_DIRECT_LOSS_AMT + UNP_LOSS_RES_AMT) + (UNP_DCC_EXPENSE_AMT+0)  AS UNP_GROSS_INCURRED_LOSS_DCC

,(UNSL_DIRECT_LOSS_AMT + UNSL_DCC_EXPENSE_AMT) - (UNSL_SALVAGE_RECOVERY_AMT - UNSL_SALVAGE_EXPENSE_AMT) - (UNSL_SUBR_RECOVERY_AMT - UNSL_SUBR_EXPENSE_AMT ) - UNSL_DIR_LOSS_RECOVERY_AMT - UNSL_DCC_RECOVERY_AMT  AS UNSL_NET_PAID_LOSS_DCC

,(UNSL_DIRECT_LOSS_AMT + UNSL_LOSS_RES_AMT) - (UNSL_SALVAGE_RECOVERY_AMT - UNSL_SALVAGE_EXPENSE_AMT) - (UNSL_SUBR_RECOVERY_AMT - UNSL_SUBR_EXPENSE_AMT ) - UNSL_DIR_LOSS_RECOVERY_AMT  AS UNSL_NET_INCURRED_LOSS

,(UNSL_DIRECT_LOSS_AMT + UNSL_LOSS_RES_AMT) + (UNSL_DCC_EXPENSE_AMT+0) - (UNSL_SALVAGE_RECOVERY_AMT - UNSL_SALVAGE_EXPENSE_AMT) - (UNSL_SUBR_RECOVERY_AMT - UNSL_SUBR_EXPENSE_AMT ) - UNSL_DIR_LOSS_RECOVERY_AMT - UNSL_DCC_RECOVERY_AMT  AS UNSL_NET_INCURRED_LOSS_DCC

,(UNSL_DIRECT_LOSS_AMT + UNSL_LOSS_RES_AMT) + (UNSL_DCC_EXPENSE_AMT+0)  AS UNSL_GROSS_INCURRED_LOSS_DCC

,BI_DIRECT_LOSS_AMT - (BI_SALVAGE_RECOVERY_AMT - BI_SALVAGE_EXPENSE_AMT) - (BI_SUBR_RECOVERY_AMT - BI_SUBR_EXPENSE_AMT ) - BI_DIR_LOSS_RECOVERY_AMT   AS BI_NET_PAID_LOSS

,BI_DIRECT_LOSS_AMT  AS BI_GROSS_PAID_LOSS

,BI_DIRECT_LOSS_AMT + BI_DCC_EXPENSE_AMT   AS BI_GROSS_PAID_LOSS_DCC

,BI_DIRECT_LOSS_AMT + BI_LOSS_RES_AMT  AS BI_GROSS_INCURRED_LOSS

,0 - (CMP_SALVAGE_RECOVERY_AMT - CMP_SALVAGE_EXPENSE_AMT) - (CMP_SUBR_RECOVERY_AMT - CMP_SUBR_EXPENSE_AMT ) - CMP_DIR_LOSS_RECOVERY_AMT   AS CMP_NET_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS CMP_GROSS_PAID_LOSS

,0 + CMP_DCC_EXPENSE_AMT   AS CMP_GROSS_PAID_LOSS_DCC

,0 + CMP_LOSS_RES_AMT  AS CMP_GROSS_INCURRED_LOSS

,COL_DIRECT_LOSS_AMT - (COL_SALVAGE_RECOVERY_AMT - COL_SALVAGE_EXPENSE_AMT) - (COL_SUBR_RECOVERY_AMT - COL_SUBR_EXPENSE_AMT ) - COL_DIR_LOSS_RECOVERY_AMT   AS COL_NET_PAID_LOSS

,COL_DIRECT_LOSS_AMT  AS COL_GROSS_PAID_LOSS

,COL_DIRECT_LOSS_AMT + COL_DCC_EXPENSE_AMT   AS COL_GROSS_PAID_LOSS_DCC

,COL_DIRECT_LOSS_AMT + COL_LOSS_RES_AMT  AS COL_GROSS_INCURRED_LOSS

,CAST(0 AS DECIMAL(15,2))  AS CS_NET_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS CS_GROSS_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS CS_GROSS_PAID_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS CS_GROSS_INCURRED_LOSS

,CAST(0 AS DECIMAL(15,2))  AS CUS_NET_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS CUS_GROSS_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS CUS_GROSS_PAID_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS CUS_GROSS_INCURRED_LOSS

,ERS_DIRECT_LOSS_AMT - (ERS_SALVAGE_RECOVERY_AMT - ERS_SALVAGE_EXPENSE_AMT) - (ERS_SUBR_RECOVERY_AMT - ERS_SUBR_EXPENSE_AMT ) - ERS_DIR_LOSS_RECOVERY_AMT   AS ERS_NET_PAID_LOSS

,ERS_DIRECT_LOSS_AMT  AS ERS_GROSS_PAID_LOSS

,ERS_DIRECT_LOSS_AMT + ERS_DCC_EXPENSE_AMT   AS ERS_GROSS_PAID_LOSS_DCC

,ERS_DIRECT_LOSS_AMT + ERS_LOSS_RES_AMT  AS ERS_GROSS_INCURRED_LOSS

,CAST(0 AS DECIMAL(15,2))  AS EXN_NET_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS EXN_GROSS_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS EXN_GROSS_PAID_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS EXN_GROSS_INCURRED_LOSS

,CAST(0 AS DECIMAL(15,2))  AS GAP_NET_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS GAP_GROSS_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS GAP_GROSS_PAID_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS GAP_GROSS_INCURRED_LOSS

,LOI_DIRECT_LOSS_AMT - (LOI_SALVAGE_RECOVERY_AMT - LOI_SALVAGE_EXPENSE_AMT) - (LOI_SUBR_RECOVERY_AMT - LOI_SUBR_EXPENSE_AMT ) - LOI_DIR_LOSS_RECOVERY_AMT   AS LOI_NET_PAID_LOSS

,LOI_DIRECT_LOSS_AMT  AS LOI_GROSS_PAID_LOSS

,LOI_DIRECT_LOSS_AMT + LOI_DCC_EXPENSE_AMT   AS LOI_GROSS_PAID_LOSS_DCC

,LOI_DIRECT_LOSS_AMT + LOI_LOSS_RES_AMT  AS LOI_GROSS_INCURRED_LOSS

,LOU_DIRECT_LOSS_AMT - (LOU_SALVAGE_RECOVERY_AMT - LOU_SALVAGE_EXPENSE_AMT) - (LOU_SUBR_RECOVERY_AMT - LOU_SUBR_EXPENSE_AMT ) - LOU_DIR_LOSS_RECOVERY_AMT   AS LOU_NET_PAID_LOSS

,LOU_DIRECT_LOSS_AMT  AS LOU_GROSS_PAID_LOSS

,LOU_DIRECT_LOSS_AMT + LOU_DCC_EXPENSE_AMT   AS LOU_GROSS_PAID_LOSS_DCC

,LOU_DIRECT_LOSS_AMT + LOU_LOSS_RES_AMT  AS LOU_GROSS_INCURRED_LOSS

,MED_DIRECT_LOSS_AMT - (MED_SALVAGE_RECOVERY_AMT - MED_SALVAGE_EXPENSE_AMT) - (MED_SUBR_RECOVERY_AMT - MED_SUBR_EXPENSE_AMT ) - MED_DIR_LOSS_RECOVERY_AMT   AS MED_NET_PAID_LOSS

,MED_DIRECT_LOSS_AMT  AS MED_GROSS_PAID_LOSS

,MED_DIRECT_LOSS_AMT + MED_DCC_EXPENSE_AMT   AS MED_GROSS_PAID_LOSS_DCC

,MED_DIRECT_LOSS_AMT + MED_LOSS_RES_AMT  AS MED_GROSS_INCURRED_LOSS

,PD_DIRECT_LOSS_AMT - (PD_SALVAGE_RECOVERY_AMT - PD_SALVAGE_EXPENSE_AMT) - (PD_SUBR_RECOVERY_AMT - PD_SUBR_EXPENSE_AMT ) - PD_DIR_LOSS_RECOVERY_AMT   AS PD_NET_PAID_LOSS

,PD_DIRECT_LOSS_AMT  AS PD_GROSS_PAID_LOSS

,PD_DIRECT_LOSS_AMT + PD_DCC_EXPENSE_AMT   AS PD_GROSS_PAID_LOSS_DCC

,PD_DIRECT_LOSS_AMT + PD_LOSS_RES_AMT  AS PD_GROSS_INCURRED_LOSS

,CAST(0 AS DECIMAL(15,2))  AS SG_NET_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS SG_GROSS_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS SG_GROSS_PAID_LOSS_DCC

,CAST(0 AS DECIMAL(15,2))  AS SG_GROSS_INCURRED_LOSS

,SL_DIRECT_LOSS_AMT - (SL_SALVAGE_RECOVERY_AMT - SL_SALVAGE_EXPENSE_AMT) - (SL_SUBR_RECOVERY_AMT - SL_SUBR_EXPENSE_AMT ) - SL_DIR_LOSS_RECOVERY_AMT   AS SL_NET_PAID_LOSS

,SL_DIRECT_LOSS_AMT  AS SL_GROSS_PAID_LOSS

,SL_DIRECT_LOSS_AMT + SL_DCC_EXPENSE_AMT   AS SL_GROSS_PAID_LOSS_DCC

,SL_DIRECT_LOSS_AMT + SL_LOSS_RES_AMT  AS SL_GROSS_INCURRED_LOSS

,UNB_DIRECT_LOSS_AMT - (UNB_SALVAGE_RECOVERY_AMT - UNB_SALVAGE_EXPENSE_AMT) - (UNB_SUBR_RECOVERY_AMT - UNB_SUBR_EXPENSE_AMT ) - UNB_DIR_LOSS_RECOVERY_AMT   AS UNB_NET_PAID_LOSS

,UNB_DIRECT_LOSS_AMT  AS UNB_GROSS_PAID_LOSS

,UNB_DIRECT_LOSS_AMT + UNB_DCC_EXPENSE_AMT   AS UNB_GROSS_PAID_LOSS_DCC

,UNB_DIRECT_LOSS_AMT + UNB_LOSS_RES_AMT  AS UNB_GROSS_INCURRED_LOSS

,CAST(0 AS DECIMAL(15,2))  AS UND_NET_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS UND_GROSS_PAID_LOSS

,CAST(0 AS DECIMAL(15,2))  AS UND_GROSS_PAID_LOSS_DCC

,0 + UND_LOSS_RES_AMT  AS UND_GROSS_INCURRED_LOSS

,UNP_DIRECT_LOSS_AMT - (UNP_SALVAGE_RECOVERY_AMT - UNP_SALVAGE_EXPENSE_AMT) - (UNP_SUBR_RECOVERY_AMT - UNP_SUBR_EXPENSE_AMT ) - UNP_DIR_LOSS_RECOVERY_AMT   AS UNP_NET_PAID_LOSS

,UNP_DIRECT_LOSS_AMT  AS UNP_GROSS_PAID_LOSS

,UNP_DIRECT_LOSS_AMT + UNP_DCC_EXPENSE_AMT   AS UNP_GROSS_PAID_LOSS_DCC

,UNP_DIRECT_LOSS_AMT + UNP_LOSS_RES_AMT  AS UNP_GROSS_INCURRED_LOSS

,UNSL_DIRECT_LOSS_AMT - (UNSL_SALVAGE_RECOVERY_AMT - UNSL_SALVAGE_EXPENSE_AMT) - (UNSL_SUBR_RECOVERY_AMT - UNSL_SUBR_EXPENSE_AMT ) - UNSL_DIR_LOSS_RECOVERY_AMT   AS UNSL_NET_PAID_LOSS

,UNSL_DIRECT_LOSS_AMT  AS UNSL_GROSS_PAID_LOSS

,UNSL_DIRECT_LOSS_AMT + UNSL_DCC_EXPENSE_AMT   AS UNSL_GROSS_PAID_LOSS_DCC

,UNSL_DIRECT_LOSS_AMT + UNSL_LOSS_RES_AMT  AS UNSL_GROSS_INCURRED_LOSS

FROM  DB_T_PROD_WRK.EDW_EBLM_CLM_DTL1 A  

LEFT OUTER JOIN  

DB_T_PROD_WRK.EDW_EBLM_CLM_DTL2 B   ON 

A.PLCY_VEH_KEY = B.PLCY_VEH_KEY AND 

A.CLM_NBR = B.CLM_NBR AND

A.CLM_LOSS_DT= B.CLM_LOSS_DT AND

A.ACC_ST_CD = B.ACC_ST_CD
) SRC
)
);


-- Component exp_pass_to_target, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_to_target AS
(
SELECT
sq_edw_eblm_clm_dtl1.PLCY_VEH_KEY as PLCY_VEH_KEY,
sq_edw_eblm_clm_dtl1.CLM_NBR as CLM_NBR,
sq_edw_eblm_clm_dtl1.CLM_LOSS_DT as CLM_LOSS_DT,
sq_edw_eblm_clm_dtl1.ACC_ST_CD as ACC_ST_CD,
sq_edw_eblm_clm_dtl1.BI_NET_PAID_LOSS_DCC as BI_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.BI_NET_INCURRED_LOSS as BI_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.BI_NET_INCURRED_LOSS_DCC as BI_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.BI_GROSS_INCURRED_LOSS_DCC as BI_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.CMP_NET_PAID_LOSS_DCC as CMP_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.CMP_NET_INCURRED_LOSS as CMP_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.CMP_NET_INCURRED_LOSS_DCC as CMP_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.CMP_GROSS_INCURRED_LOSS_DCC as CMP_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.COL_NET_PAID_LOSS_DCC as COL_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.COL_NET_INCURRED_LOSS as COL_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.COL_NET_INCURRED_LOSS_DCC as COL_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.COL_GROSS_INCURRED_LOSS_DCC as COL_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.CS_NET_PAID_LOSS_DCC as CS_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.CS_NET_INCURRED_LOSS as CS_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.CS_NET_INCURRED_LOSS_DCC as CS_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.CS_GROSS_INCURRED_LOSS_DCC as CS_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.CUS_NET_PAID_LOSS_DCC as CUS_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.CUS_NET_INCURRED_LOSS as CUS_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.CUS_NET_INCURRED_LOSS_DCC as CUS_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.CUS_GROSS_INCURRED_LOSS_DCC as CUS_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.ERS_NET_PAID_LOSS_DCC as ERS_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.ERS_NET_INCURRED_LOSS as ERS_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.ERS_NET_INCURRED_LOSS_DCC as ERS_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.ERS_GROSS_INCURRED_LOSS_DCC as ERS_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.EXN_NET_PAID_LOSS_DCC as EXN_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.EXN_NET_INCURRED_LOSS as EXN_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.EXN_NET_INCURRED_LOSS_DCC as EXN_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.EXN_GROSS_INCURRED_LOSS_DCC as EXN_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.GAP_NET_PAID_LOSS_DCC as GAP_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.GAP_NET_INCURRED_LOSS as GAP_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.GAP_NET_INCURRED_LOSS_DCC as GAP_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.GAP_GROSS_INCURRED_LOSS_DCC as GAP_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.LOI_NET_PAID_LOSS_DCC as LOI_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.LOI_NET_INCURRED_LOSS as LOI_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.LOI_NET_INCURRED_LOSS_DCC as LOI_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.LOI_GROSS_INCURRED_LOSS_DCC as LOI_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.LOU_NET_PAID_LOSS_DCC as LOU_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.LOU_NET_INCURRED_LOSS as LOU_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.LOU_NET_INCURRED_LOSS_DCC as LOU_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.LOU_GROSS_INCURRED_LOSS_DCC as LOU_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.MED_NET_PAID_LOSS_DCC as MED_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.MED_NET_INCURRED_LOSS as MED_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.MED_NET_INCURRED_LOSS_DCC as MED_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.MED_GROSS_INCURRED_LOSS_DCC as MED_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.PD_NET_PAID_LOSS_DCC as PD_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.PD_NET_INCURRED_LOSS as PD_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.PD_NET_INCURRED_LOSS_DCC as PD_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.PD_GROSS_INCURRED_LOSS_DCC as PD_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.SG_NET_PAID_LOSS_DCC as SG_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.SG_NET_INCURRED_LOSS as SG_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.SG_NET_INCURRED_LOSS_DCC as SG_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.SG_GROSS_INCURRED_LOSS_DCC as SG_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.SL_NET_PAID_LOSS_DCC as SL_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.SL_NET_INCURRED_LOSS as SL_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.SL_NET_INCURRED_LOSS_DCC as SL_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.SL_GROSS_INCURRED_LOSS_DCC as SL_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UNB_NET_PAID_LOSS_DCC as UNB_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UNB_NET_INCURRED_LOSS as UNB_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.UNB_NET_INCURRED_LOSS_DCC as UNB_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UNB_GROSS_INCURRED_LOSS_DCC as UNB_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UND_NET_PAID_LOSS_DCC as UND_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UND_NET_INCURRED_LOSS as UND_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.UND_NET_INCURRED_LOSS_DCC as UND_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UND_GROSS_INCURRED_LOSS_DCC as UND_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UNP_NET_PAID_LOSS_DCC as UNP_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UNP_NET_INCURRED_LOSS as UNP_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.UNP_NET_INCURRED_LOSS_DCC as UNP_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UNP_GROSS_INCURRED_LOSS_DCC as UNP_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UNSL_NET_PAID_LOSS_DCC as UNSL_NET_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UNSL_NET_INCURRED_LOSS as UNSL_NET_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.UNSL_NET_INCURRED_LOSS_DCC as UNSL_NET_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UNSL_GROSS_INCURRED_LOSS_DCC as UNSL_GROSS_INCURRED_LOSS_DCC,
sq_edw_eblm_clm_dtl1.BI_NET_PAID_LOSS as BI_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.BI_GROSS_PAID_LOSS as BI_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.BI_GROSS_PAID_LOSS_DCC as BI_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.BI_GROSS_INCURRED_LOSS as BI_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.CMP_NET_PAID_LOSS as CMP_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.CMP_GROSS_PAID_LOSS as CMP_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.CMP_GROSS_PAID_LOSS_DCC as CMP_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.CMP_GROSS_INCURRED_LOSS as CMP_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.COL_NET_PAID_LOSS as COL_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.COL_GROSS_PAID_LOSS as COL_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.COL_GROSS_PAID_LOSS_DCC as COL_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.COL_GROSS_INCURRED_LOSS as COL_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.CS_NET_PAID_LOSS as CS_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.CS_GROSS_PAID_LOSS as CS_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.CS_GROSS_PAID_LOSS_DCC as CS_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.CS_GROSS_INCURRED_LOSS as CS_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.CUS_NET_PAID_LOSS as CUS_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.CUS_GROSS_PAID_LOSS as CUS_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.CUS_GROSS_PAID_LOSS_DCC as CUS_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.CUS_GROSS_INCURRED_LOSS as CUS_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.ERS_NET_PAID_LOSS as ERS_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.ERS_GROSS_PAID_LOSS as ERS_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.ERS_GROSS_PAID_LOSS_DCC as ERS_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.ERS_GROSS_INCURRED_LOSS as ERS_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.EXN_NET_PAID_LOSS as EXN_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.EXN_GROSS_PAID_LOSS as EXN_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.EXN_GROSS_PAID_LOSS_DCC as EXN_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.EXN_GROSS_INCURRED_LOSS as EXN_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.GAP_NET_PAID_LOSS as GAP_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.GAP_GROSS_PAID_LOSS as GAP_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.GAP_GROSS_PAID_LOSS_DCC as GAP_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.GAP_GROSS_INCURRED_LOSS as GAP_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.LOI_NET_PAID_LOSS as LOI_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.LOI_GROSS_PAID_LOSS as LOI_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.LOI_GROSS_PAID_LOSS_DCC as LOI_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.LOI_GROSS_INCURRED_LOSS as LOI_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.LOU_NET_PAID_LOSS as LOU_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.LOU_GROSS_PAID_LOSS as LOU_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.LOU_GROSS_PAID_LOSS_DCC as LOU_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.LOU_GROSS_INCURRED_LOSS as LOU_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.MED_NET_PAID_LOSS as MED_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.MED_GROSS_PAID_LOSS as MED_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.MED_GROSS_PAID_LOSS_DCC as MED_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.MED_GROSS_INCURRED_LOSS as MED_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.PD_NET_PAID_LOSS as PD_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.PD_GROSS_PAID_LOSS as PD_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.PD_GROSS_PAID_LOSS_DCC as PD_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.PD_GROSS_INCURRED_LOSS as PD_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.SG_NET_PAID_LOSS as SG_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.SG_GROSS_PAID_LOSS as SG_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.SG_GROSS_PAID_LOSS_DCC as SG_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.SG_GROSS_INCURRED_LOSS as SG_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.SL_NET_PAID_LOSS as SL_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.SL_GROSS_PAID_LOSS as SL_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.SL_GROSS_PAID_LOSS_DCC as SL_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.SL_GROSS_INCURRED_LOSS as SL_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.UNB_NET_PAID_LOSS as UNB_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.UNB_GROSS_PAID_LOSS as UNB_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.UNB_GROSS_PAID_LOSS_DCC as UNB_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UNB_GROSS_INCURRED_LOSS as UNB_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.UND_NET_PAID_LOSS as UND_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.UND_GROSS_PAID_LOSS as UND_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.UND_GROSS_PAID_LOSS_DCC as UND_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UND_GROSS_INCURRED_LOSS as UND_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.UNP_NET_PAID_LOSS as UNP_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.UNP_GROSS_PAID_LOSS as UNP_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.UNP_GROSS_PAID_LOSS_DCC as UNP_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UNP_GROSS_INCURRED_LOSS as UNP_GROSS_INCURRED_LOSS,
sq_edw_eblm_clm_dtl1.UNSL_NET_PAID_LOSS as UNSL_NET_PAID_LOSS,
sq_edw_eblm_clm_dtl1.UNSL_GROSS_PAID_LOSS as UNSL_GROSS_PAID_LOSS,
sq_edw_eblm_clm_dtl1.UNSL_GROSS_PAID_LOSS_DCC as UNSL_GROSS_PAID_LOSS_DCC,
sq_edw_eblm_clm_dtl1.UNSL_GROSS_INCURRED_LOSS as UNSL_GROSS_INCURRED_LOSS,
cast(LTRIM ( RTRIM ( :PRCS_ID ) ) as BIGINT) as out_PRCS_ID,
CURRENT_TIMESTAMP as out_LOAD_DT,
sq_edw_eblm_clm_dtl1.source_record_id
FROM
sq_edw_eblm_clm_dtl1
);


-- Component tgt_edw_eblm_claim_feed, Type TARGET 
INSERT INTO DB_T_PROD_WRK.EDW_EBLM_CLAIM_FEED
(
PLCY_VEH_KEY,
CLM_NBR,
CLM_LOSS_DT,
ACC_ST_CD,
BI_NET_PAID_LOSS_DCC,
BI_NET_INCURRED_LOSS,
BI_NET_INCURRED_LOSS_DCC,
BI_GROSS_INCURRED_LOSS_DCC,
CMP_NET_PAID_LOSS_DCC,
CMP_NET_INCURRED_LOSS,
CMP_NET_INCURRED_LOSS_DCC,
CMP_GROSS_INCURRED_LOSS_DCC,
COL_NET_PAID_LOSS_DCC,
COL_NET_INCURRED_LOSS,
COL_NET_INCURRED_LOSS_DCC,
COL_GROSS_INCURRED_LOSS_DCC,
CS_NET_PAID_LOSS_DCC,
CS_NET_INCURRED_LOSS,
CS_NET_INCURRED_LOSS_DCC,
CS_GROSS_INCURRED_LOSS_DCC,
CUS_NET_PAID_LOSS_DCC,
CUS_NET_INCURRED_LOSS,
CUS_NET_INCURRED_LOSS_DCC,
CUS_GROSS_INCURRED_LOSS_DCC,
ERS_NET_PAID_LOSS_DCC,
ERS_NET_INCURRED_LOSS,
ERS_NET_INCURRED_LOSS_DCC,
ERS_GROSS_INCURRED_LOSS_DCC,
EXN_NET_PAID_LOSS_DCC,
EXN_NET_INCURRED_LOSS,
EXN_NET_INCURRED_LOSS_DCC,
EXN_GROSS_INCURRED_LOSS_DCC,
GAP_NET_PAID_LOSS_DCC,
GAP_NET_INCURRED_LOSS,
GAP_NET_INCURRED_LOSS_DCC,
GAP_GROSS_INCURRED_LOSS_DCC,
LOI_NET_PAID_LOSS_DCC,
LOI_NET_INCURRED_LOSS,
LOI_NET_INCURRED_LOSS_DCC,
LOI_GROSS_INCURRED_LOSS_DCC,
LOU_NET_PAID_LOSS_DCC,
LOU_NET_INCURRED_LOSS,
LOU_NET_INCURRED_LOSS_DCC,
LOU_GROSS_INCURRED_LOSS_DCC,
MED_NET_PAID_LOSS_DCC,
MED_NET_INCURRED_LOSS,
MED_NET_INCURRED_LOSS_DCC,
MED_GROSS_INCURRED_LOSS_DCC,
PD_NET_PAID_LOSS_DCC,
PD_NET_INCURRED_LOSS,
PD_NET_INCURRED_LOSS_DCC,
PD_GROSS_INCURRED_LOSS_DCC,
SG_NET_PAID_LOSS_DCC,
SG_NET_INCURRED_LOSS,
SG_NET_INCURRED_LOSS_DCC,
SG_GROSS_INCURRED_LOSS_DCC,
SL_NET_PAID_LOSS_DCC,
SL_NET_INCURRED_LOSS,
SL_NET_INCURRED_LOSS_DCC,
SL_GROSS_INCURRED_LOSS_DCC,
UNB_NET_PAID_LOSS_DCC,
UNB_NET_INCURRED_LOSS,
UNB_NET_INCURRED_LOSS_DCC,
UNB_GROSS_INCURRED_LOSS_DCC,
UND_NET_PAID_LOSS_DCC,
UND_NET_INCURRED_LOSS,
UND_NET_INCURRED_LOSS_DCC,
UND_GROSS_INCURRED_LOSS_DCC,
UNP_NET_PAID_LOSS_DCC,
UNP_NET_INCURRED_LOSS,
UNP_NET_INCURRED_LOSS_DCC,
UNP_GROSS_INCURRED_LOSS_DCC,
UNSL_NET_PAID_LOSS_DCC,
UNSL_NET_INCURRED_LOSS,
UNSL_NET_INCURRED_LOSS_DCC,
UNSL_GROSS_INCURRED_LOSS_DCC,
BI_NET_PAID_LOSS,
BI_GROSS_PAID_LOSS,
BI_GROSS_PAID_LOSS_DCC,
BI_GROSS_INCURRED_LOSS,
CMP_NET_PAID_LOSS,
CMP_GROSS_PAID_LOSS,
CMP_GROSS_PAID_LOSS_DCC,
CMP_GROSS_INCURRED_LOSS,
COL_NET_PAID_LOSS,
COL_GROSS_PAID_LOSS,
COL_GROSS_PAID_LOSS_DCC,
COL_GROSS_INCURRED_LOSS,
CS_NET_PAID_LOSS,
CS_GROSS_PAID_LOSS,
CS_GROSS_PAID_LOSS_DCC,
CS_GROSS_INCURRED_LOSS,
CUS_NET_PAID_LOSS,
CUS_GROSS_PAID_LOSS,
CUS_GROSS_PAID_LOSS_DCC,
CUS_GROSS_INCURRED_LOSS,
ERS_NET_PAID_LOSS,
ERS_GROSS_PAID_LOSS,
ERS_GROSS_PAID_LOSS_DCC,
ERS_GROSS_INCURRED_LOSS,
EXN_NET_PAID_LOSS,
EXN_GROSS_PAID_LOSS,
EXN_GROSS_PAID_LOSS_DCC,
EXN_GROSS_INCURRED_LOSS,
GAP_NET_PAID_LOSS,
GAP_GROSS_PAID_LOSS,
GAP_GROSS_PAID_LOSS_DCC,
GAP_GROSS_INCURRED_LOSS,
LOI_NET_PAID_LOSS,
LOI_GROSS_PAID_LOSS,
LOI_GROSS_PAID_LOSS_DCC,
LOI_GROSS_INCURRED_LOSS,
LOU_NET_PAID_LOSS,
LOU_GROSS_PAID_LOSS,
LOU_GROSS_PAID_LOSS_DCC,
LOU_GROSS_INCURRED_LOSS,
MED_NET_PAID_LOSS,
MED_GROSS_PAID_LOSS,
MED_GROSS_PAID_LOSS_DCC,
MED_GROSS_INCURRED_LOSS,
PD_NET_PAID_LOSS,
PD_GROSS_PAID_LOSS,
PD_GROSS_PAID_LOSS_DCC,
PD_GROSS_INCURRED_LOSS,
SG_NET_PAID_LOSS,
SG_GROSS_PAID_LOSS,
SG_GROSS_PAID_LOSS_DCC,
SG_GROSS_INCURRED_LOSS,
SL_NET_PAID_LOSS,
SL_GROSS_PAID_LOSS,
SL_GROSS_PAID_LOSS_DCC,
SL_GROSS_INCURRED_LOSS,
UNB_NET_PAID_LOSS,
UNB_GROSS_PAID_LOSS,
UNB_GROSS_PAID_LOSS_DCC,
UNB_GROSS_INCURRED_LOSS,
UND_NET_PAID_LOSS,
UND_GROSS_PAID_LOSS,
UND_GROSS_PAID_LOSS_DCC,
UND_GROSS_INCURRED_LOSS,
UNP_NET_PAID_LOSS,
UNP_GROSS_PAID_LOSS,
UNP_GROSS_PAID_LOSS_DCC,
UNP_GROSS_INCURRED_LOSS,
UNSL_NET_PAID_LOSS,
UNSL_GROSS_PAID_LOSS,
UNSL_GROSS_PAID_LOSS_DCC,
UNSL_GROSS_INCURRED_LOSS,
PRCS_ID,
LOAD_DT
)
SELECT
exp_pass_to_target.PLCY_VEH_KEY as PLCY_VEH_KEY,
exp_pass_to_target.CLM_NBR as CLM_NBR,
exp_pass_to_target.CLM_LOSS_DT as CLM_LOSS_DT,
exp_pass_to_target.ACC_ST_CD as ACC_ST_CD,
exp_pass_to_target.BI_NET_PAID_LOSS_DCC as BI_NET_PAID_LOSS_DCC,
exp_pass_to_target.BI_NET_INCURRED_LOSS as BI_NET_INCURRED_LOSS,
exp_pass_to_target.BI_NET_INCURRED_LOSS_DCC as BI_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.BI_GROSS_INCURRED_LOSS_DCC as BI_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.CMP_NET_PAID_LOSS_DCC as CMP_NET_PAID_LOSS_DCC,
exp_pass_to_target.CMP_NET_INCURRED_LOSS as CMP_NET_INCURRED_LOSS,
exp_pass_to_target.CMP_NET_INCURRED_LOSS_DCC as CMP_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.CMP_GROSS_INCURRED_LOSS_DCC as CMP_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.COL_NET_PAID_LOSS_DCC as COL_NET_PAID_LOSS_DCC,
exp_pass_to_target.COL_NET_INCURRED_LOSS as COL_NET_INCURRED_LOSS,
exp_pass_to_target.COL_NET_INCURRED_LOSS_DCC as COL_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.COL_GROSS_INCURRED_LOSS_DCC as COL_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.CS_NET_PAID_LOSS_DCC as CS_NET_PAID_LOSS_DCC,
exp_pass_to_target.CS_NET_INCURRED_LOSS as CS_NET_INCURRED_LOSS,
exp_pass_to_target.CS_NET_INCURRED_LOSS_DCC as CS_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.CS_GROSS_INCURRED_LOSS_DCC as CS_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.CUS_NET_PAID_LOSS_DCC as CUS_NET_PAID_LOSS_DCC,
exp_pass_to_target.CUS_NET_INCURRED_LOSS as CUS_NET_INCURRED_LOSS,
exp_pass_to_target.CUS_NET_INCURRED_LOSS_DCC as CUS_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.CUS_GROSS_INCURRED_LOSS_DCC as CUS_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.ERS_NET_PAID_LOSS_DCC as ERS_NET_PAID_LOSS_DCC,
exp_pass_to_target.ERS_NET_INCURRED_LOSS as ERS_NET_INCURRED_LOSS,
exp_pass_to_target.ERS_NET_INCURRED_LOSS_DCC as ERS_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.ERS_GROSS_INCURRED_LOSS_DCC as ERS_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.EXN_NET_PAID_LOSS_DCC as EXN_NET_PAID_LOSS_DCC,
exp_pass_to_target.EXN_NET_INCURRED_LOSS as EXN_NET_INCURRED_LOSS,
exp_pass_to_target.EXN_NET_INCURRED_LOSS_DCC as EXN_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.EXN_GROSS_INCURRED_LOSS_DCC as EXN_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.GAP_NET_PAID_LOSS_DCC as GAP_NET_PAID_LOSS_DCC,
exp_pass_to_target.GAP_NET_INCURRED_LOSS as GAP_NET_INCURRED_LOSS,
exp_pass_to_target.GAP_NET_INCURRED_LOSS_DCC as GAP_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.GAP_GROSS_INCURRED_LOSS_DCC as GAP_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.LOI_NET_PAID_LOSS_DCC as LOI_NET_PAID_LOSS_DCC,
exp_pass_to_target.LOI_NET_INCURRED_LOSS as LOI_NET_INCURRED_LOSS,
exp_pass_to_target.LOI_NET_INCURRED_LOSS_DCC as LOI_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.LOI_GROSS_INCURRED_LOSS_DCC as LOI_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.LOU_NET_PAID_LOSS_DCC as LOU_NET_PAID_LOSS_DCC,
exp_pass_to_target.LOU_NET_INCURRED_LOSS as LOU_NET_INCURRED_LOSS,
exp_pass_to_target.LOU_NET_INCURRED_LOSS_DCC as LOU_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.LOU_GROSS_INCURRED_LOSS_DCC as LOU_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.MED_NET_PAID_LOSS_DCC as MED_NET_PAID_LOSS_DCC,
exp_pass_to_target.MED_NET_INCURRED_LOSS as MED_NET_INCURRED_LOSS,
exp_pass_to_target.MED_NET_INCURRED_LOSS_DCC as MED_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.MED_GROSS_INCURRED_LOSS_DCC as MED_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.PD_NET_PAID_LOSS_DCC as PD_NET_PAID_LOSS_DCC,
exp_pass_to_target.PD_NET_INCURRED_LOSS as PD_NET_INCURRED_LOSS,
exp_pass_to_target.PD_NET_INCURRED_LOSS_DCC as PD_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.PD_GROSS_INCURRED_LOSS_DCC as PD_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.SG_NET_PAID_LOSS_DCC as SG_NET_PAID_LOSS_DCC,
exp_pass_to_target.SG_NET_INCURRED_LOSS as SG_NET_INCURRED_LOSS,
exp_pass_to_target.SG_NET_INCURRED_LOSS_DCC as SG_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.SG_GROSS_INCURRED_LOSS_DCC as SG_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.SL_NET_PAID_LOSS_DCC as SL_NET_PAID_LOSS_DCC,
exp_pass_to_target.SL_NET_INCURRED_LOSS as SL_NET_INCURRED_LOSS,
exp_pass_to_target.SL_NET_INCURRED_LOSS_DCC as SL_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.SL_GROSS_INCURRED_LOSS_DCC as SL_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.UNB_NET_PAID_LOSS_DCC as UNB_NET_PAID_LOSS_DCC,
exp_pass_to_target.UNB_NET_INCURRED_LOSS as UNB_NET_INCURRED_LOSS,
exp_pass_to_target.UNB_NET_INCURRED_LOSS_DCC as UNB_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.UNB_GROSS_INCURRED_LOSS_DCC as UNB_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.UND_NET_PAID_LOSS_DCC as UND_NET_PAID_LOSS_DCC,
exp_pass_to_target.UND_NET_INCURRED_LOSS as UND_NET_INCURRED_LOSS,
exp_pass_to_target.UND_NET_INCURRED_LOSS_DCC as UND_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.UND_GROSS_INCURRED_LOSS_DCC as UND_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.UNP_NET_PAID_LOSS_DCC as UNP_NET_PAID_LOSS_DCC,
exp_pass_to_target.UNP_NET_INCURRED_LOSS as UNP_NET_INCURRED_LOSS,
exp_pass_to_target.UNP_NET_INCURRED_LOSS_DCC as UNP_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.UNP_GROSS_INCURRED_LOSS_DCC as UNP_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.UNSL_NET_PAID_LOSS_DCC as UNSL_NET_PAID_LOSS_DCC,
exp_pass_to_target.UNSL_NET_INCURRED_LOSS as UNSL_NET_INCURRED_LOSS,
exp_pass_to_target.UNSL_NET_INCURRED_LOSS_DCC as UNSL_NET_INCURRED_LOSS_DCC,
exp_pass_to_target.UNSL_GROSS_INCURRED_LOSS_DCC as UNSL_GROSS_INCURRED_LOSS_DCC,
exp_pass_to_target.BI_NET_PAID_LOSS as BI_NET_PAID_LOSS,
exp_pass_to_target.BI_GROSS_PAID_LOSS as BI_GROSS_PAID_LOSS,
exp_pass_to_target.BI_GROSS_PAID_LOSS_DCC as BI_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.BI_GROSS_INCURRED_LOSS as BI_GROSS_INCURRED_LOSS,
exp_pass_to_target.CMP_NET_PAID_LOSS as CMP_NET_PAID_LOSS,
exp_pass_to_target.CMP_GROSS_PAID_LOSS as CMP_GROSS_PAID_LOSS,
exp_pass_to_target.CMP_GROSS_PAID_LOSS_DCC as CMP_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.CMP_GROSS_INCURRED_LOSS as CMP_GROSS_INCURRED_LOSS,
exp_pass_to_target.COL_NET_PAID_LOSS as COL_NET_PAID_LOSS,
exp_pass_to_target.COL_GROSS_PAID_LOSS as COL_GROSS_PAID_LOSS,
exp_pass_to_target.COL_GROSS_PAID_LOSS_DCC as COL_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.COL_GROSS_INCURRED_LOSS as COL_GROSS_INCURRED_LOSS,
exp_pass_to_target.CS_NET_PAID_LOSS as CS_NET_PAID_LOSS,
exp_pass_to_target.CS_GROSS_PAID_LOSS as CS_GROSS_PAID_LOSS,
exp_pass_to_target.CS_GROSS_PAID_LOSS_DCC as CS_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.CS_GROSS_INCURRED_LOSS as CS_GROSS_INCURRED_LOSS,
exp_pass_to_target.CUS_NET_PAID_LOSS as CUS_NET_PAID_LOSS,
exp_pass_to_target.CUS_GROSS_PAID_LOSS as CUS_GROSS_PAID_LOSS,
exp_pass_to_target.CUS_GROSS_PAID_LOSS_DCC as CUS_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.CUS_GROSS_INCURRED_LOSS as CUS_GROSS_INCURRED_LOSS,
exp_pass_to_target.ERS_NET_PAID_LOSS as ERS_NET_PAID_LOSS,
exp_pass_to_target.ERS_GROSS_PAID_LOSS as ERS_GROSS_PAID_LOSS,
exp_pass_to_target.ERS_GROSS_PAID_LOSS_DCC as ERS_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.ERS_GROSS_INCURRED_LOSS as ERS_GROSS_INCURRED_LOSS,
exp_pass_to_target.EXN_NET_PAID_LOSS as EXN_NET_PAID_LOSS,
exp_pass_to_target.EXN_GROSS_PAID_LOSS as EXN_GROSS_PAID_LOSS,
exp_pass_to_target.EXN_GROSS_PAID_LOSS_DCC as EXN_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.EXN_GROSS_INCURRED_LOSS as EXN_GROSS_INCURRED_LOSS,
exp_pass_to_target.GAP_NET_PAID_LOSS as GAP_NET_PAID_LOSS,
exp_pass_to_target.GAP_GROSS_PAID_LOSS as GAP_GROSS_PAID_LOSS,
exp_pass_to_target.GAP_GROSS_PAID_LOSS_DCC as GAP_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.GAP_GROSS_INCURRED_LOSS as GAP_GROSS_INCURRED_LOSS,
exp_pass_to_target.LOI_NET_PAID_LOSS as LOI_NET_PAID_LOSS,
exp_pass_to_target.LOI_GROSS_PAID_LOSS as LOI_GROSS_PAID_LOSS,
exp_pass_to_target.LOI_GROSS_PAID_LOSS_DCC as LOI_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.LOI_GROSS_INCURRED_LOSS as LOI_GROSS_INCURRED_LOSS,
exp_pass_to_target.LOU_NET_PAID_LOSS as LOU_NET_PAID_LOSS,
exp_pass_to_target.LOU_GROSS_PAID_LOSS as LOU_GROSS_PAID_LOSS,
exp_pass_to_target.LOU_GROSS_PAID_LOSS_DCC as LOU_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.LOU_GROSS_INCURRED_LOSS as LOU_GROSS_INCURRED_LOSS,
exp_pass_to_target.MED_NET_PAID_LOSS as MED_NET_PAID_LOSS,
exp_pass_to_target.MED_GROSS_PAID_LOSS as MED_GROSS_PAID_LOSS,
exp_pass_to_target.MED_GROSS_PAID_LOSS_DCC as MED_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.MED_GROSS_INCURRED_LOSS as MED_GROSS_INCURRED_LOSS,
exp_pass_to_target.PD_NET_PAID_LOSS as PD_NET_PAID_LOSS,
exp_pass_to_target.PD_GROSS_PAID_LOSS as PD_GROSS_PAID_LOSS,
exp_pass_to_target.PD_GROSS_PAID_LOSS_DCC as PD_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.PD_GROSS_INCURRED_LOSS as PD_GROSS_INCURRED_LOSS,
exp_pass_to_target.SG_NET_PAID_LOSS as SG_NET_PAID_LOSS,
exp_pass_to_target.SG_GROSS_PAID_LOSS as SG_GROSS_PAID_LOSS,
exp_pass_to_target.SG_GROSS_PAID_LOSS_DCC as SG_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.SG_GROSS_INCURRED_LOSS as SG_GROSS_INCURRED_LOSS,
exp_pass_to_target.SL_NET_PAID_LOSS as SL_NET_PAID_LOSS,
exp_pass_to_target.SL_GROSS_PAID_LOSS as SL_GROSS_PAID_LOSS,
exp_pass_to_target.SL_GROSS_PAID_LOSS_DCC as SL_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.SL_GROSS_INCURRED_LOSS as SL_GROSS_INCURRED_LOSS,
exp_pass_to_target.UNB_NET_PAID_LOSS as UNB_NET_PAID_LOSS,
exp_pass_to_target.UNB_GROSS_PAID_LOSS as UNB_GROSS_PAID_LOSS,
exp_pass_to_target.UNB_GROSS_PAID_LOSS_DCC as UNB_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.UNB_GROSS_INCURRED_LOSS as UNB_GROSS_INCURRED_LOSS,
exp_pass_to_target.UND_NET_PAID_LOSS as UND_NET_PAID_LOSS,
exp_pass_to_target.UND_GROSS_PAID_LOSS as UND_GROSS_PAID_LOSS,
exp_pass_to_target.UND_GROSS_PAID_LOSS_DCC as UND_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.UND_GROSS_INCURRED_LOSS as UND_GROSS_INCURRED_LOSS,
exp_pass_to_target.UNP_NET_PAID_LOSS as UNP_NET_PAID_LOSS,
exp_pass_to_target.UNP_GROSS_PAID_LOSS as UNP_GROSS_PAID_LOSS,
exp_pass_to_target.UNP_GROSS_PAID_LOSS_DCC as UNP_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.UNP_GROSS_INCURRED_LOSS as UNP_GROSS_INCURRED_LOSS,
exp_pass_to_target.UNSL_NET_PAID_LOSS as UNSL_NET_PAID_LOSS,
exp_pass_to_target.UNSL_GROSS_PAID_LOSS as UNSL_GROSS_PAID_LOSS,
exp_pass_to_target.UNSL_GROSS_PAID_LOSS_DCC as UNSL_GROSS_PAID_LOSS_DCC,
exp_pass_to_target.UNSL_GROSS_INCURRED_LOSS as UNSL_GROSS_INCURRED_LOSS,
exp_pass_to_target.out_PRCS_ID as PRCS_ID,
exp_pass_to_target.out_LOAD_DT as LOAD_DT
FROM
exp_pass_to_target;


END; ';