-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BIBASE_W_AGT_ACCTBLY_BI_BONUS("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
       run_id STRING;
       LOAD_PARAM STRING;
       CAL_DATE STRING;
       v_start_time TIMESTAMP;
BEGIN
       run_id := (SELECT run_id FROM control_worklet WHERE worklet_name = :worklet_name ORDER BY insert_ts DESC LIMIT 1);
       LOAD_PARAM := (SELECT param_value FROM control_params WHERE run_id = :run_id AND param_name = ''LOAD_PARAM'' LIMIT 1);
       CAL_DATE := (SELECT param_value FROM control_params WHERE run_id = :run_id AND param_name = ''CAL_DATE'' LIMIT 1);
       v_start_time := CURRENT_TIMESTAMP();

-- Component AGT_ACCTBLY_BI_BONUS, Type Pre SQL 
delete FROM   DB2_prefix.AGT_ACCTBLY_BI_BONUS 



where update_date =case(:LOAD_PARAM) when (''SCHEDULED'') 

THEN (case( MONTH(CURRENT_DATE)) when  9  THEN date(year(CURRENT_DATE)||''-11-30'')

when  10  THEN date(year(CURRENT_DATE)||''-11-30'')

when  11 THEN date(year(CURRENT_DATE)||''-11-30'')

when  12 THEN date(year(CURRENT_DATE)||''-11-30'')

ELSE  date(year(CURRENT_DATE)||''-12-31'')END)

ELSE date(:CAL_DATE)end;


-- Component SQ_AGMT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGMT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as AGNT_NBR,
$2 as ST_CD,
$3 as RGN_CD,
$4 as DSTRCT_CD,
$5 as SRVC_CTR_CD,
$6 as BONUS_YR,
$7 as COMPANY,
$8 as PLCY_SYMBOL,
$9 as AGNT_TOT_PREM,
$10 as UPDATE_DATE,
$11 as SRC_IDNTFTN_SYS,
$12 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT

CAST(T.AGNT_NBR AS INTEGER) AGNT_NBR_NEW,

CAST(case when T.ST_CD =''AL''  then ''01'' when T.ST_CD=''GA'' THEN ''10'' when T.ST_CD=''MS'' THEN ''28'' END AS INTEGER) ST_CD_NEW,

COALESCE(case 

        when T.RGN_CD = ''ALABAMA NORTH MARKETING'' then ''1''

        when t.rgn_cd = ''ALABAMA SOUTH MARKETING'' then ''2''

        when t.rgn_cd = ''MISSISSIPPI MARKETING'' then ''6''

        when t.rgn_Cd = ''GEORGIA MARKETING'' then ''5'' else ''''

end,'''')  REG_CD_NEW,

substr(COALESCE(T.DSTRCT_CD,''''),1,1) DSTRCT_CD,/*  ST_CD,RGN_CD, DSTRCT_CD,  SRVC_CTR_CD */
CAST(COALESCE(T.SVC_NBR,'''') AS INTEGER) SVC_NBR_NEW,

EXTRACT(YEAR FROM  CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) ELSE CAST(:CAL_DATE AS DATE)END ) as "BONUS_YEAR",

case when T.CMPY_CD=''AMI'' THEN ''A'' 

when T.CMPY_CD=''AIC'' THEN ''P''

when T.CMPY_CD=''AGI'' THEN ''S''

when T.CMPY_CD=''AMF'' THEN ''F''

when T.CMPY_CD=''AMG'' THEN ''G'' END AS COMPANY,

CAST(coalesce(t.COMM_POL_SYM_stg ,'''')AS VARCHAR(3)) as POL_SYMBOL,

SUM(BOOK_SIZE_AUTO + BOOK_SIZE_OTHERS) AS AGENT_TOT_PREM,

T.CALENDAR_DATE as "UPDATE_DATE",

/* ''1347'' AS PRCS_ID    ---BIGINT NOT NULL */
 T.SRC_IDNTFTN_SYS



FROM 

(

SELECT 

V.HOST_AGMT_NUM, V.AGMT_ID, CAST(''GW'' AS VARCHAR(10)) AS SRC_IDNTFTN_SYS, 

  CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) ELSE CAST(:CAL_DATE AS DATE)END  AS CALENDAR_DATE, TE.GEOGRCL_AREA_SHRT_NAME AS ST_CD,  /*P.prod_name,*/ p.COMM_POL_SYM_stg, max(intrnl_org_num_svc) intrnl_org_num_svc,

MAX(UPPER(IO_RGN.INTRNL_ORG_NUM) ) AS RGN_CD,



max(case when prty_agmt_role_cd = ''cmp'' then io.INTRNL_ORG_NUM end) as "CMPY_CD",



MAX(IO_DIST.INTRNL_ORG_NUM ) AS DSTRCT_CD,

MAX(CASE WHEN PRTY_AGMT_ROLE_CD = ''SVC'' 
         THEN REGEXP_REPLACE(IO.INTRNL_ORG_NUM, ''^0+'', '''') 
    END) AS SVC_NBR,

MAX(CASE WHEN PRTY_AGMT_ROLE_CD = ''PRDA'' 
         THEN REGEXP_REPLACE(IO.INTRNL_ORG_NUM, ''^0+'', '''') 
    END) AS AGNT_NBR,

MAX(CASE WHEN P.INSRNC_TYPE_CD =''AUTO'' THEN COALESCE(V.PLCY_AMT*2,0) ELSE 0 END) AS BOOK_SIZE_AUTO,

MAX(CASE WHEN P.INSRNC_TYPE_CD <>''AUTO'' THEN COALESCE(V.PLCY_AMT,0)*365/DAYS_IN_TERM ELSE 0 END) AS BOOK_SIZE_OTHERS

FROM 

    (SELECT A.HOST_AGMT_NUM, A.AGMT_ID, A.DAYS_IN_TERM, MAX(PM.PLCY_AMT) AS PLCY_AMT 

    FROM  (SELECT PPV.HOST_AGMT_NUM,PPV.AGMT_ID, A_S.AGMT_STS_CD,PPV.DAYS_IN_TERM 

                            FROM  (SELECT T1.HOST_AGMT_NUM,T1.AGMT_ID,T1.TERM_NUM,CAST(T1.AGMT_PLND_EXPN_DTTM AS DATE) - CAST(T1.AGMT_EFF_DTTM AS DATE)  AS DAYS_IN_TERM   

FROM DB_T_PROD_CORE.AGMT T1 WHERE T1.AGMT_TYPE_CD = ''PPV'' AND T1.SRC_SYS_CD = ''GWPC'' 

AND CAST( CAST( CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) 

ELSE CAST(:CAL_DATE AS DATE)END    AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' BETWEEN AGMT_EFF_DTTM AND AGMT_PLND_EXPN_DTTM

AND T1.TRANS_STRT_DTTM = (SELECT MIN(T2.TRANS_STRT_DTTM) FROM DB_T_PROD_CORE.AGMT T2 WHERE T1.AGMT_ID = T2.AGMT_ID) 

AND CASE WHEN T1.MODL_EFF_DTTM > T1.MODL_CRTN_DTTM THEN T1.MODL_EFF_DTTM ELSE T1.MODL_CRTN_DTTM END <=  

CAST( CAST(( CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) 

ELSE CAST(:CAL_DATE AS DATE)END  )  AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND''  

QUALIFY ROW_NUMBER() OVER(PARTITION BY T1.HOST_AGMT_NUM ORDER BY T1.MODL_CRTN_DTTM DESC ) = 1) PPV 

INNER JOIN 

(SELECT HOST_AGMT_NUM, TERM_NUM,AGMT_ID FROM DB_T_PROD_CORE.AGMT WHERE AGMT_TYPE_CD = ''POLTRM'' AND 

CAST( CAST(( CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) ELSE CAST(:CAL_DATE AS DATE)END )  AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' BETWEEN AGMT_EFF_DTTM AND AGMT_PLND_EXPN_DTTM GROUP BY 1,2,3) TRM 

ON PPV.HOST_AGMT_NUM = TRM.HOST_AGMT_NUM AND PPV.TERM_NUM = TRM.TERM_NUM   

/* --------------------------------------------------------------------------------------- */
/* and ppv.host_agmt_num = ''12000121642'' */
/* --------------------------------------------------------------------------------------- */
INNER JOIN  DB_T_PROD_CORE.AGMT_STS A_S ON TRM.AGMT_ID = A_S.AGMT_ID  AND A_S.AGMT_STS_STRT_DTTM <= CAST( CAST(( CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) ELSE CAST(:CAL_DATE AS DATE)END  )  AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' 

            AND A_S.AGMT_STS_CD <> ''CNFRMDDT'' 

            QUALIFY ROW_NUMBER() OVER(PARTITION BY PPV.AGMT_ID ORDER BY A_S.AGMT_STS_STRT_DTTM DESC) = 1 AND A_S.AGMT_STS_CD = ''INFORCE'') A

            INNER JOIN DB_T_PROD_CORE.PLCY_MTRC AS PM 

            ON A.AGMT_ID = PM.AGMT_ID AND PM.INSRNC_MTRC_TYPE_CD = ''TOTTRMPREM'' AND PM.EDW_END_DTTM=''9999-12-31 23:59:59.999999''

GROUP BY 1,2,3

) V

 

/* -------get prty_id for getting service center, district, region, and company-------- */
LEFT OUTER JOIN  DB_T_PROD_CORE.PRTY_AGMT PA ON 

                V.AGMT_ID = PA.AGMT_ID AND 

                PA.PRTY_AGMT_ROLE_CD IN (''SVC'',''PRDA'',''cmp'')

/* AND CAST( CAST(cast('':CAL_DATE'' as date ''yyyy-mm-DD'')   AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' BETWEEN PA.TRANS_STRT_DTTM AND PA.TRANS_END_DTTM */
                

LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG IO ON PA.PRTY_ID = IO.INTRNL_ORG_PRTY_ID 

                AND PA.PRTY_AGMT_ROLE_CD IN (''SVC'',''PRDA'',''cmp'')

                AND IO.INTRNL_ORG_SBTYPE_CD IN (''SRVCCTR'',''PRDA'',''co'')

/* AND CAST( CAST(cast('':CAL_DATE'' as date ''yyyy-mm-DD'')   AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' BETWEEN IO.TRANS_STRT_DTTM AND IO.TRANS_END_DTTM */
                

                      /* to get svc for a agent*/

                 left join (

                select distinct  a.prty_id prty_id_agnt , c.intrnl_org_prty_id prty_id_svc,  b.intrnl_org_num intrnl_org_num_agnt  , c.intrnl_org_num intrnl_org_num_svc from DB_T_PROD_CORE.PRTY_RLTD a join DB_T_PROD_CORE.INTRNL_ORG b on a.prty_id=b.intrnl_org_prty_id

join DB_T_PROD_CORE.INTRNL_ORG c on a.rltd_prty_id=c.intrnl_org_prty_id

 and a.prty_rltd_role_cd=''PRDASVC'' ) active_svc on case when pa.prty_agmt_role_cd=''prda'' then pa.prty_id else 999999 end =prty_id_agnt

                

LEFT OUTER JOIN DB_T_PROD_CORE.PRTY_RLTD DIST 

                ON DIST.PRTY_RLTD_ROLE_CD = ''DISTTOSVC'' 

                AND DIST.PRTY_STRC_TYPE_CD = ''SLSHRCHY'' 

                AND PA.PRTY_AGMT_ROLE_CD = ''SVC'' 

                AND DIST.RLTD_PRTY_ID = PA.PRTY_ID

                AND CAST( CAST( CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) ELSE CAST(:CAL_DATE AS DATE)END    AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' BETWEEN DIST.TRANS_STRT_DTTM AND DIST.TRANS_END_DTTM



LEFT OUTER JOIN DB_T_PROD_CORE.PRTY_RLTD RGN

                ON RGN.PRTY_RLTD_ROLE_CD = ''RGNTODIST''

                AND RGN.PRTY_STRC_TYPE_CD = ''SLSHRCHY''

                AND PA.PRTY_AGMT_ROLE_CD = ''SVC'' 

                AND RGN.RLTD_PRTY_ID = DIST.PRTY_ID

                AND CAST( CAST( CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) ELSE CAST(:CAL_DATE AS DATE)END    AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' BETWEEN RGN.TRANS_STRT_DTTM AND RGN.TRANS_END_DTTM



LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG IO_DIST

                ON DIST.PRTY_ID = IO_DIST.INTRNL_ORG_PRTY_ID 

                AND IO_DIST.INTRNL_ORG_SBTYPE_CD = ''SLSDSTRCT''

                AND CAST( CAST( CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) ELSE CAST(:CAL_DATE AS DATE)END    AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' BETWEEN IO_DIST.TRANS_STRT_DTTM AND IO_DIST.TRANS_END_DTTM



LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG IO_RGN

                ON RGN.PRTY_ID = IO_RGN.INTRNL_ORG_PRTY_ID 

                AND IO_RGN.INTRNL_ORG_SBTYPE_CD = ''RPG''

                AND CAST( CAST( CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) ELSE CAST(:CAL_DATE AS DATE)END   AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' BETWEEN IO_RGN.TRANS_STRT_DTTM AND IO_RGN.TRANS_END_DTTM



LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_LOCTR AS AL 

                ON V.AGMT_ID = AL.AGMT_ID AND AL.AGMT_LOCTR_ROLE_TYPE_CD = ''AGTWINST'' AND 

                CAST( CAST( CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) ELSE CAST(:CAL_DATE AS DATE)END   AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' BETWEEN AL.TRANS_STRT_DTTM AND AL.TRANS_END_DTTM 



LEFT OUTER JOIN DB_T_PROD_CORE.TERR TE 

                ON AL.LOC_ID = TE.TERR_ID AND CAST(TE.EDW_END_DTTM AS DATE)=  ''9999-12-31'' 

          

/* ---------------------------------------------------------------------------------------------- */
/* ------this gets the product type example 7352323/ppv/auto */
/* ---------------------------------------------------------------------------------------------- */
LEFT OUTER JOIN 

(SELECT AGMT_ID,/*PROD_NAME,*/INSRNC_TYPE_CD  , ptc.COMM_POL_SYM_stg

    FROM DB_T_PROD_CORE.AGMT_PROD AP  

		INNER JOIN DB_T_PROD_CORE.PROD P ON AP.PROD_ID = P.PROD_ID 

		join DB_T_PROD_STAG.GW_POLTYPE_CONV ptc on ptc.GW_POL_TYP_CD_stg = p.prod_name

                AND P.PROD_SBTYPE_CD =''PLCYTYPE''

                AND AP.AGMT_PROD_ROLE_CD= ''PLCYTYPE''

                AND CAST(AP.EDW_END_DTTM AS DATE)=  ''9999-12-31''

                AND CAST(P.EDW_END_DTTM AS DATE)=  ''9999-12-31''  

/* and ap.agmt_id = ''7352323'' */
    GROUP BY 1,2,3

) P ON V.AGMT_ID = P.AGMT_ID 





GROUP BY 1,2,3,4,5,6) T 



/* where T.AGNT_NBR = ''1563'' */
GROUP BY 1,2,3,4,5,6,7,8,10,11

HAVING SUM(BOOK_SIZE_AUTO+book_size_others) <> 0  



UNION

                                                                                                                                                             

SELECT CAST(AGENT_NBR AS INTEGER),

CAST(case when ST_CD =''AL''  then ''01'' when ST_CD=''GA'' THEN ''10'' when ST_CD=''MS'' THEN ''28'' END AS INTEGER) ST_CD_NEW,

COALESCE(case 

        when RGN_CD = ''ALABAMA NORTH MARKETING'' then ''1''

        when rgn_cd = ''ALABAMA SOUTH MARKETING'' then ''2''

        when rgn_cd = ''MISSISSIPPI MARKETING'' then ''6''

        when rgn_Cd = ''GEORGIA MARKETING'' then ''5'' else ''''

end,'''')  REG_CD_NEW,

substr(COALESCE(DSTRCT_CD,''''),1,1) DSTRCT_CD,/*  ST_CD,RGN_CD, DSTRCT_CD,  SRVC_CTR_CD */
CAST(COALESCE(SRVC_CTR_CD,'''') AS INTEGER) SVC_NBR_NEW,

EXTRACT(YEAR FROM  CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) 

ELSE CAST(:CAL_DATE AS DATE)END ) AS BONUS_YEAR,

case when UWCO=''AMI'' THEN ''A'' 

when UWCO=''AIC'' THEN ''P''

when UWCO=''AGI'' THEN ''S''

when UWCO=''AMF'' THEN ''F''

when UWCO=''AMG'' THEN ''G'' END AS COMPANY,

CAST(coalesce(COMS_PLCY_SYMB,'''') AS VARCHAR(3)),



SUM(BOOK_SIZE_AUTO+BOOK_SIZE_OTHERS) BOOK_SIZE,

CALENDAR_DATE,

CAST(''DB2'' AS VARCHAR(10)) AS SRC_IDNTFTN_SYS



FROM EPRESDB_EDW.V_LGCY_BOOK_SIZE 

WHERE CALENDAR_DATE =CAST( CASE WHEN (:LOAD_PARAM =''SCHEDULED'') THEN (CASE WHEN (EXTRACT( MONTH FROM CURRENT_DATE)  IN (9,10,11,12))  THEN CAST(EXTRACT(YEAR FROM CURRENT_DATE)||''-11-30'' AS DATE) 

ELSE  CAST(EXTRACT(YEAR FROM CURRENT_DATE)-1||''-12-31'' AS DATE) END) ELSE CAST(:CAL_DATE AS DATE)END  AS DATE)

GROUP BY 1,2,3,4,5,6,7,8,10,11
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_AGMT.AGNT_NBR as AGNT_NBR,
SQ_AGMT.ST_CD as ST_CD,
SQ_AGMT.RGN_CD as RGN_CD,
SQ_AGMT.DSTRCT_CD as DSTRCT_CD,
SQ_AGMT.SRVC_CTR_CD as SRVC_CTR_CD,
SQ_AGMT.BONUS_YR as BONUS_YR,
SQ_AGMT.COMPANY as COMPANY,
SQ_AGMT.PLCY_SYMBOL as PLCY_SYMBOL,
SQ_AGMT.AGNT_TOT_PREM as AGNT_TOT_PREM,
SQ_AGMT.UPDATE_DATE as UPDATE_DATE,
SQ_AGMT.SRC_IDNTFTN_SYS as SRC_IDNTFTN_SYS,
SQ_AGMT.source_record_id
FROM
SQ_AGMT
);


-- Component AGT_ACCTBLY_BI_BONUS, Type TARGET 
INSERT INTO AGT_ACCTBLY_BI_BONUS
(
AGENT_NBR,
STATE_NBR,
REGION,
DISTRICT,
SERVICE_CENTER,
BONUS_YEAR,
COMPANY_CODE,
POLICY_SYMBOL,
AGENT_TOT_PREM,
UPDATE_DATE,
UPDATE_SOURCE
)
SELECT
EXPTRANS.AGNT_NBR as AGENT_NBR,
EXPTRANS.ST_CD as STATE_NBR,
EXPTRANS.RGN_CD as REGION,
EXPTRANS.DSTRCT_CD as DISTRICT,
EXPTRANS.SRVC_CTR_CD as SERVICE_CENTER,
EXPTRANS.BONUS_YR as BONUS_YEAR,
EXPTRANS.COMPANY as COMPANY_CODE,
EXPTRANS.PLCY_SYMBOL as POLICY_SYMBOL,
EXPTRANS.AGNT_TOT_PREM as AGENT_TOT_PREM,
EXPTRANS.UPDATE_DATE as UPDATE_DATE,
EXPTRANS.SRC_IDNTFTN_SYS as UPDATE_SOURCE
FROM
EXPTRANS;


END; ';