-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_AR_INVOICE_LINE_ADJSTMT_INS("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
       run_id STRING;
       start_dttm TIMESTAMP;
       end_dttm TIMESTAMP;
       PRCS_ID STRING;
	   v_start_time TIMESTAMP;
BEGIN
      run_id := (SELECT run_id FROM control_worklet WHERE worklet_name = :worklet_name ORDER BY insert_ts DESC LIMIT 1);
       start_dttm := (SELECT param_value FROM control_params WHERE run_id = :run_id AND param_name = ''start_dttm'' LIMIT 1);
       end_dttm := (SELECT param_value FROM control_params WHERE run_id = :run_id AND param_name = ''end_dttm'' LIMIT 1);
       PRCS_ID := (SELECT param_value FROM control_params WHERE run_id = :run_id AND param_name = ''PRCS_ID'' LIMIT 1);

	   v_start_time := CURRENT_TIMESTAMP();

-- Component SQ_bc_itemevent, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_bc_itemevent AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as Src_AR_INVC_ID,
$2 as Src_AR_INVC_LN_NUM,
$3 as Src_EV_ID,
$4 as Src_ADJSTMT_TYPE_CD,
$5 as Src_AR_INVC_LN_ADJSTMT_CRTN_DTTM,
$6 as Src_FROM_INVC_ITM_ID,
$7 as Src_TO_INVC_ITM_ID,
$8 as Src_NK_SRC_KEY,
$9 as Src_TRANS_STRT_DTTM,
$10 as Ins_upd_flag,
$11 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT SRC_TEMP.AR_INVC_ID AS SRC_AR_INVC_ID,

SRC_TEMP.AR_INVC_LN_NUM AS SRC_AR_INVC_LN_NUM,

SRC_TEMP.EV_ID AS SRC_EV_ID,

SRC_TEMP.LKP_XLAT_EVENT_TYPE AS SRC_ADJSTMT_TYPE_CD,

SRC_TEMP.EventDate_stg AS SRC_AR_INVC_LN_ADJSTMT_CRTN_DTTM,

SRC_TEMP.FromInvoiceID_stg AS SRC_FROM_INVC_ITM_ID,

SRC_TEMP.ToInvoiceID_stg AS SRC_TO_INVC_ITM_ID,

SRC_TEMP.ID_stg AS SRC_NK_SRC_KEY,

SRC_TEMP.UpdateTime_stg AS SRC_TRANS_STRT_DTTM,

case when LKP_TGT.AR_INVC_LN_ADJSTMT_ID is NULL THEN ''I'' ELSE ''R'' END AS INS_UPD_FLAG

FROM (

SELECT SRC.TransactionID_stg,

SRC.InvoiceItemID_stg,

SRC.EventType_stg,

SRC.FromInvoiceID_stg,

SRC.ToInvoiceID_stg,

SRC.EventDate_stg,

SRC.UpdateTime_stg,

SRC.ID_stg,

Case when LKP_XLAT_EVENT_TYPE.TGT_IDNTFTN_VAL IS NULL then ''UNK'' else LKP_XLAT_EVENT_TYPE.TGT_IDNTFTN_VAL End as LKP_XLAT_EVENT_TYPE, 

Case when LKP_XLAT_EV_ACT_TYPE_CD.TGT_IDNTFTN_VAL IS NULL then ''UNK'' else LKP_XLAT_EV_ACT_TYPE_CD.TGT_IDNTFTN_VAL End as LKP_XLAT_EV_ACT_TYPE_CD,

Case when LKP_EV_SBTYPE.TGT_IDNTFTN_VAL IS NULL then ''UNK'' else LKP_EV_SBTYPE.TGT_IDNTFTN_VAL End as LKP_EV_SBTYPE

,LKP_AR_INVC_LN.AR_INVC_ID

,LKP_EV.EV_ID

,LKP_AR_INVC_LN.AR_INVC_LN_NUM

FROM(-- --------------------------------SOURCE QUERY STARTS*/-------------------------------------------------------------- */
select  distinct cast(a.TransactionID_stg as varchar(100)) as TransactionID_stg,

cast(a.InvoiceItemID_stg as varchar(50)) as InvoiceItemID_stg,

b.typecode_stg as EventType_stg,a.FromInvoiceID_stg,a.ToInvoiceID_stg,

a.EventDate_stg,a.UpdateTime_stg,a.ID_stg,

bctl.typecode_stg as ev_act_type_cd,

''EV_SBTYPE2'' as EV_SBTYPE

from DB_T_PROD_STAG.bc_itemevent a

left outer join DB_T_PROD_STAG.bctl_itemeventtype b on a.EventType_stg=b.id_stg 

left outer join   DB_T_PROD_STAG.bc_transaction  bc  on a.TransactionID_stg = bc.ID_stg

left outer join DB_T_PROD_STAG.bctl_transaction bctl ON bctl.ID_stg =bc.Subtype_stg

where  ((a.UpdateTime_stg > (:start_dttm) and    a.UpdateTime_stg <= (:end_dttm))

or (bc.UpdateTime_stg > (:start_dttm) and   bc.UpdateTime_stg <= (:end_dttm)))

qualify row_number() over(partition by a.ID_stg order by a.updatetime_stg desc)=1

)SRC



/* --LKP_XLAT_EVENT_TYPE */


LEFT OUTER JOIN

(SELECT 

    TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL AS TGT_IDNTFTN_VAL

    ,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL AS SRC_IDNTFTN_VAL 

FROM 

    DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT TERADATA_ETL_REF_XLAT

WHERE 

    TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM= ''ADJSTMT_TYPE'' 

	AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_NM=''bctl_itemeventtype.typecode''

    AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''

	)LKP_XLAT_EVENT_TYPE

ON LKP_XLAT_EVENT_TYPE.SRC_IDNTFTN_VAL=SRC.EVENTTYPE_STG 



/* --LKP_XLAT_EV_ACT_TYPE_CD */


LEFT OUTER JOIN

(SELECT 

    TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL

    ,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 

FROM 

    DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT

WHERE 

TGT_IDNTFTN_NM= ''EV_ACTVY_TYPE'' AND SRC_IDNTFTN_SYS in (''GW'',''DS'' ) 

AND EXPN_DT=''9999-12-31''

)LKP_XLAT_EV_ACT_TYPE_CD

ON LKP_XLAT_EV_ACT_TYPE_CD.SRC_IDNTFTN_VAL=SRC.EV_ACT_TYPE_CD 

/* --LKP_XLAT_EV_SBTYPE */
LEFT OUTER JOIN

(SELECT 

    TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL

    ,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 

FROM 

    DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT

WHERE 

TGT_IDNTFTN_NM= ''EV_SBTYPE'' AND SRC_IDNTFTN_SYS in (''GW'',''DS'' ) 

AND EXPN_DT=''9999-12-31''

)LKP_EV_SBTYPE

ON LKP_EV_SBTYPE.SRC_IDNTFTN_VAL=EV_SBTYPE



/* --LKP_AR_INVC_LN */


LEFT OUTER JOIN

(SELECT	 AR_INVC_LN.AR_INVC_ID AS AR_INVC_ID,  AR_INVC_LN.AR_INVC_LN_NUM AS AR_INVC_LN_NUM,

		 AR_INVC_LN.HOST_INVC_LN_NUM AS HOST_INVC_LN_NUM 

FROM	DB_T_PROD_CORE.AR_INVC_LN 

QUALIFY	ROW_NUMBER() OVER(PARTITION BY AR_INVC_LN.HOST_INVC_LN_NUM ORDER BY AR_INVC_LN.EDW_END_DTTM desc) = 1 

)LKP_AR_INVC_LN

ON LKP_AR_INVC_LN.HOST_INVC_LN_NUM=SRC.INVOICEITEMID_STG



/* --LKP_EV */


LEFT OUTER JOIN

(SELECT EV.EV_ID AS EV_ID, EV.EV_DESC AS EV_DESC, EV.EV_STRT_DTTM AS EV_STRT_DTTM,

        EV.EV_END_DTTM AS EV_END_DTTM, EV.EV_RSN_CD AS EV_RSN_CD, EV.AGMT_ID AS AGMT_ID,

        EV.PRCSD_SRC_SYS_CD AS PRCSD_SRC_SYS_CD, EV.FUNC_CD AS FUNC_CD,

        EV.EV_DTTM AS EV_DTTM, EV.EDW_STRT_DTTM AS EDW_STRT_DTTM, EV.SRC_TRANS_ID AS SRC_TRANS_ID,

        EV.EV_SBTYPE_CD AS EV_SBTYPE_CD, EV.EV_ACTVY_TYPE_CD AS EV_ACTVY_TYPE_CD 

FROM    DB_T_PROD_CORE.EV  EV

WHERE EV_ACTVY_TYPE_CD IN (''CHRGBILLED'',''CHRGDUE'',''CHRGPAID'',''CHRGWRTOFF'')

QUALIFY ROW_NUMBER() OVER(PARTITION BY  EV.EV_SBTYPE_CD,EV.EV_ACTVY_TYPE_CD,EV.SRC_TRANS_ID ORDER BY EV.EDW_END_DTTM DESC) = 1

)LKP_EV

ON LKP_EV.SRC_TRANS_ID=SRC.TRANSACTIONID_STG AND LKP_EV.EV_SBTYPE_CD=LKP_EV_SBTYPE.TGT_IDNTFTN_VAL 

AND LKP_EV.EV_ACTVY_TYPE_CD=LKP_XLAT_EV_ACT_TYPE_CD.TGT_IDNTFTN_VAL



-- -------------------------------------SOURCE QUERY ENDS*/------------------------------------------------------------------- */


)SRC_TEMP



/* --LKP_TGT */


LEFT OUTER JOIN

(SELECT AR_INVC_LN_ADJSTMT.AR_INVC_LN_ADJSTMT_ID as AR_INVC_LN_ADJSTMT_ID,

        AR_INVC_LN_ADJSTMT.AR_INVC_ID as AR_INVC_ID, AR_INVC_LN_ADJSTMT.AR_INVC_LN_NUM as AR_INVC_LN_NUM,

        AR_INVC_LN_ADJSTMT.EV_ID as EV_ID, AR_INVC_LN_ADJSTMT.ADJSTMT_TYPE_CD as ADJSTMT_TYPE_CD,

        AR_INVC_LN_ADJSTMT.AR_INVC_LN_ADJSTMT_CRTN_DTTM as AR_INVC_LN_ADJSTMT_CRTN_DTTM 

FROM    DB_T_PROD_CORE.AR_INVC_LN_ADJSTMT AR_INVC_LN_ADJSTMT

WHERE   CAST(AR_INVC_LN_ADJSTMT.EDW_END_DTTM AS DATE)=''9999-12-31''

)LKP_TGT

ON LKP_TGT.ADJSTMT_TYPE_CD=SRC_TEMP.LKP_XLAT_EVENT_TYPE

AND COALESCE(LKP_TGT.EV_ID,''0'')=COALESCE(SRC_TEMP.EV_ID,''0'')

AND LKP_TGT.AR_INVC_ID=SRC_TEMP.AR_INVC_ID

AND LKP_TGT.AR_INVC_LN_NUM=SRC_TEMP.AR_INVC_LN_NUM

AND LKP_TGT.AR_INVC_LN_ADJSTMT_CRTN_DTTM=SRC_TEMP.EventDate_stg

WHERE INS_UPD_FLAG=''I'' AND SRC_TEMP.AR_INVC_ID IS NOT NULL
) SRC
)
);


-- Component exp_INS_FLG_SET, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_INS_FLG_SET AS
(
SELECT
SQ_bc_itemevent.Src_AR_INVC_ID as Src_AR_INVC_ID,
SQ_bc_itemevent.Src_AR_INVC_LN_NUM as Src_AR_INVC_LN_NUM,
seq_AR_INVC_LN_ADJSTMT_ID.NEXTVAL as Src_AR_INVC_LN_ADJSTMT_ID,
SQ_bc_itemevent.Src_EV_ID as Src_EV_ID,
SQ_bc_itemevent.Src_ADJSTMT_TYPE_CD as Src_ADJSTMT_TYPE_CD,
SQ_bc_itemevent.Src_AR_INVC_LN_ADJSTMT_CRTN_DTTM as Src_AR_INVC_LN_ADJSTMT_CRTN_DTTM,
SQ_bc_itemevent.Src_FROM_INVC_ITM_ID as Src_FROM_INVC_ITM_ID,
SQ_bc_itemevent.Src_TO_INVC_ITM_ID as Src_TO_INVC_ITM_ID,
SQ_bc_itemevent.Src_NK_SRC_KEY as Src_NK_SRC_KEY,
SQ_bc_itemevent.Src_TRANS_STRT_DTTM as Src_TRANS_STRT_DTTM,
:PRCS_ID as PRCS_ID,
CURRENT_TIMESTAMP as EDW_STRT_DTTM,
TO_DATE ( ''12/31/9999 23:59:59.999999'' , ''MM/DD/YYYY HH24:MI:SS.FF6'' ) as EDW_END_DTTM,
TO_DATE ( ''12/31/9999 23:59:59.999999'' , ''MM/DD/YYYY HH24:MI:SS.FF6'' ) as TRANS_END_DTTM,
SQ_bc_itemevent.source_record_id
FROM
SQ_bc_itemevent
);


-- Component AR_INVC_LN_ADJSTMT, Type TARGET 
INSERT INTO DB_T_PROD_CORE.AR_INVC_LN_ADJSTMT
(
AR_INVC_ID,
AR_INVC_LN_NUM,
AR_INVC_LN_ADJSTMT_ID,
EV_ID,
ADJSTMT_TYPE_CD,
AR_INVC_LN_ADJSTMT_CRTN_DTTM,
FROM_INVC_ITM_ID,
TO_INVC_ITM_ID,
NK_SRC_KEY,
PRCS_ID,
EDW_STRT_DTTM,
EDW_END_DTTM,
TRANS_STRT_DTTM,
TRANS_END_DTTM
)
SELECT
exp_INS_FLG_SET.Src_AR_INVC_ID as AR_INVC_ID,
exp_INS_FLG_SET.Src_AR_INVC_LN_NUM as AR_INVC_LN_NUM,
exp_INS_FLG_SET.Src_AR_INVC_LN_ADJSTMT_ID as AR_INVC_LN_ADJSTMT_ID,
exp_INS_FLG_SET.Src_EV_ID as EV_ID,
exp_INS_FLG_SET.Src_ADJSTMT_TYPE_CD as ADJSTMT_TYPE_CD,
exp_INS_FLG_SET.Src_AR_INVC_LN_ADJSTMT_CRTN_DTTM as AR_INVC_LN_ADJSTMT_CRTN_DTTM,
exp_INS_FLG_SET.Src_FROM_INVC_ITM_ID as FROM_INVC_ITM_ID,
exp_INS_FLG_SET.Src_TO_INVC_ITM_ID as TO_INVC_ITM_ID,
exp_INS_FLG_SET.Src_NK_SRC_KEY as NK_SRC_KEY,
exp_INS_FLG_SET.PRCS_ID as PRCS_ID,
exp_INS_FLG_SET.EDW_STRT_DTTM as EDW_STRT_DTTM,
exp_INS_FLG_SET.EDW_END_DTTM as EDW_END_DTTM,
exp_INS_FLG_SET.Src_TRANS_STRT_DTTM as TRANS_STRT_DTTM,
exp_INS_FLG_SET.TRANS_END_DTTM as TRANS_END_DTTM
FROM
exp_INS_FLG_SET;


END; ';