-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_SWAP_CURR_PREV("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_Shortcut_to_STG_FED_MSTR_TRG, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_STG_FED_MSTR_TRG AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as FEED_IND,
$2 as FEED_DT,
$3 as REC_COUNT,
$4 as DOLLAR_AMT,
$5 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
STG_FED_MSTR_TRG.FEED_IND,
STG_FED_MSTR_TRG.FEED_DT,
STG_FED_MSTR_TRG.REC_COUNT,
STG_FED_MSTR_TRG.DOLLAR_AMT
FROM DB_T_STAG_PROD.STG_FED_MSTR_TRG
WHERE 1 = 0
) SRC
)
);


-- Component Shortcut_to_STG_FED_MSTR_TRG1, Type TARGET 
INSERT INTO DB_T_STAG_PROD.STG_FED_MSTR_TRG
(
FEED_IND,
FEED_DT,
REC_COUNT,
DOLLAR_AMT
)
SELECT
SQ_Shortcut_to_STG_FED_MSTR_TRG.FEED_IND as FEED_IND,
SQ_Shortcut_to_STG_FED_MSTR_TRG.FEED_DT as FEED_DT,
SQ_Shortcut_to_STG_FED_MSTR_TRG.REC_COUNT as REC_COUNT,
SQ_Shortcut_to_STG_FED_MSTR_TRG.DOLLAR_AMT as DOLLAR_AMT
FROM
SQ_Shortcut_to_STG_FED_MSTR_TRG;


END; ';