-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_PS_ALF_DEPT("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- PIPELINE START FOR 1

-- Component SQ_PS_DEPT_TBL, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_PS_DEPT_TBL AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SETID,
$2 as EFFDT,
$3 as DESCR,
$4 as EFF_STATUS,
$5 as DESCRSHORT,
$6 as ACCOUNTING_OWNER,
$7 as DEPTID,
$8 as COMPANY,
$9 as SETID_LOCATION,
$10 as LOCATION,
$11 as TAX_LOCATION_CD,
$12 as MANAGER_ID,
$13 as MANAGER_POSN,
$14 as BUDGET_YR_END_DT,
$15 as BUDGET_LVL,
$16 as GL_EXPENSE,
$17 as EEO4_FUNCTION,
$18 as CAN_IND_SECTOR,
$19 as ACCIDENT_INS,
$20 as SI_ACCIDENT_NUM,
$21 as HAZARD,
$22 as ESTABID,
$23 as RISKCD,
$24 as GVT_DESCR40,
$25 as GVT_SUB_AGENCY,
$26 as GVT_PAR_LINE2,
$27 as GVT_PAR_LINE3,
$28 as GVT_PAR_LINE4,
$29 as GVT_PAR_LINE5,
$30 as GVT_PAR_DESCR2,
$31 as GVT_PAR_DESCR3,
$32 as GVT_PAR_DESCR4,
$33 as GVT_PAR_DESCR5,
$34 as FTE_EDIT_INDC,
$35 as DEPT_TENURE_FLG,
$36 as TL_DISTRIB_INFO,
$37 as USE_BUDGETS,
$38 as USE_ENCUMBRANCES,
$39 as USE_DISTRIBUTION,
$40 as BUDGET_DEPTID,
$41 as DIST_PRORATE_OPTN,
$42 as HP_STATS_DEPT_CD,
$43 as HP_STATS_FACULTY,
$44 as MANAGER_NAME,
$45 as COUNTRY_GRP,
$46 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT SETID, 

EFFDT, DESCR, 

EFF_STATUS, 

DESCRSHORT, 

ACCOUNTING_OWNER, 

DEPTID, 

COMPANY, 

SETID_LOCATION, 

LOCATION, 

TAX_LOCATION_CD, 

MANAGER_ID, 

MANAGER_POSN, 

BUDGET_YR_END_DT, 

BUDGET_LVL, 

GL_EXPENSE, 

EEO4_FUNCTION, 

CAN_IND_SECTOR, 

ACCIDENT_INS, 

SI_ACCIDENT_NUM, 

HAZARD, 

ESTABID, 

RISKCD, 

GVT_DESCR40, 

GVT_SUB_AGENCY, 

GVT_PAR_LINE2, 

GVT_PAR_LINE3, 

GVT_PAR_LINE4, 

GVT_PAR_LINE5, 

GVT_PAR_DESCR2, 

GVT_PAR_DESCR3, 

GVT_PAR_DESCR4, 

GVT_PAR_DESCR5, 

FTE_EDIT_INDC, 

DEPT_TENURE_FLG, 

TL_DISTRIB_INFO, 

USE_BUDGETS, 

USE_ENCUMBRANCES, 

USE_DISTRIBUTION, 

BUDGET_DEPTID, 

DIST_PRORATE_OPTN, 

HP_STATS_DEPT_CD, 

HP_STATS_FACULTY, 

MANAGER_NAME, 

COUNTRY_GRP

 FROM PS_DB2_OWNER.PS_DEPT_TBL
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_PS_DEPT_TBL.SETID as SETID,
SQ_PS_DEPT_TBL.DEPTID as DEPTID,
SQ_PS_DEPT_TBL.EFFDT as EFFDT,
SQ_PS_DEPT_TBL.EFF_STATUS as EFF_STATUS,
SQ_PS_DEPT_TBL.DESCR as DESCR,
SQ_PS_DEPT_TBL.DESCRSHORT as DESCRSHORT,
SQ_PS_DEPT_TBL.COMPANY as COMPANY,
SQ_PS_DEPT_TBL.SETID_LOCATION as SETID_LOCATION,
SQ_PS_DEPT_TBL.LOCATION as LOCATION,
SQ_PS_DEPT_TBL.TAX_LOCATION_CD as TAX_LOCATION_CD,
SQ_PS_DEPT_TBL.MANAGER_ID as MANAGER_ID,
SQ_PS_DEPT_TBL.MANAGER_POSN as MANAGER_POSN,
SQ_PS_DEPT_TBL.BUDGET_YR_END_DT as BUDGET_YR_END_DT,
SQ_PS_DEPT_TBL.BUDGET_LVL as BUDGET_LVL,
SQ_PS_DEPT_TBL.GL_EXPENSE as GL_EXPENSE,
SQ_PS_DEPT_TBL.EEO4_FUNCTION as EEO4_FUNCTION,
SQ_PS_DEPT_TBL.CAN_IND_SECTOR as CAN_IND_SECTOR,
SQ_PS_DEPT_TBL.ACCIDENT_INS as ACCIDENT_INS,
SQ_PS_DEPT_TBL.SI_ACCIDENT_NUM as SI_ACCIDENT_NUM,
SQ_PS_DEPT_TBL.HAZARD as HAZARD,
SQ_PS_DEPT_TBL.ESTABID as ESTABID,
SQ_PS_DEPT_TBL.RISKCD as RISKCD,
SQ_PS_DEPT_TBL.GVT_DESCR40 as GVT_DESCR40,
SQ_PS_DEPT_TBL.GVT_SUB_AGENCY as GVT_SUB_AGENCY,
SQ_PS_DEPT_TBL.GVT_PAR_LINE2 as GVT_PAR_LINE2,
SQ_PS_DEPT_TBL.GVT_PAR_LINE3 as GVT_PAR_LINE3,
SQ_PS_DEPT_TBL.GVT_PAR_LINE4 as GVT_PAR_LINE4,
SQ_PS_DEPT_TBL.GVT_PAR_LINE5 as GVT_PAR_LINE5,
SQ_PS_DEPT_TBL.GVT_PAR_DESCR2 as GVT_PAR_DESCR2,
SQ_PS_DEPT_TBL.GVT_PAR_DESCR3 as GVT_PAR_DESCR3,
SQ_PS_DEPT_TBL.GVT_PAR_DESCR4 as GVT_PAR_DESCR4,
SQ_PS_DEPT_TBL.GVT_PAR_DESCR5 as GVT_PAR_DESCR5,
NULL as CLASS_UNIT_NZL,
NULL as ORG_UNIT_AUS,
NULL as WORK_SECTOR_AUS,
NULL as APS_AGENT_CD_AUS,
NULL as IND_COMMITTEE_BEL,
NULL as NACE_CD_BEL,
SQ_PS_DEPT_TBL.FTE_EDIT_INDC as FTE_EDIT_INDC,
SQ_PS_DEPT_TBL.DEPT_TENURE_FLG as DEPT_TENURE_FLG,
SQ_PS_DEPT_TBL.TL_DISTRIB_INFO as TL_DISTRIB_INFO,
SQ_PS_DEPT_TBL.USE_BUDGETS as USE_BUDGETS,
SQ_PS_DEPT_TBL.USE_ENCUMBRANCES as USE_ENCUMBRANCES,
SQ_PS_DEPT_TBL.USE_DISTRIBUTION as USE_DISTRIBUTION,
SQ_PS_DEPT_TBL.BUDGET_DEPTID as BUDGET_DEPTID,
SQ_PS_DEPT_TBL.source_record_id
FROM
SQ_PS_DEPT_TBL
);


-- PIPELINE START FOR 2

-- Component SQ_PS_DEPT_TBL1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_PS_DEPT_TBL1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
select count(*) as record_count

from

PS_DB2_OWNER.ps_dept_tbl
) SRC
)
);


-- Component PS_ALF_DEPT, Type TARGET 
INSERT INTO DB_T_STAG_FIN_PROD.PS_ALF_DEPT
(
SETID,
DEPTID,
EFFDT,
EFF_STATUS,
DESCR,
DESCRSHORT,
COMPANY,
SETID_LOCATION,
LOCATION,
TAX_LOCATION_CD,
MANAGER_ID,
MANAGER_POSN,
BUDGET_YR_END_DT,
BUDGET_LVL,
GL_EXPENSE,
EEO4_FUNCTION,
CAN_IND_SECTOR,
ACCIDENT_INS,
SI_ACCIDENT_NUM,
HAZARD,
ESTABID,
RISKCD,
GVT_DESCR40,
GVT_SUB_AGENCY,
GVT_PAR_LINE2,
GVT_PAR_LINE3,
GVT_PAR_LINE4,
GVT_PAR_LINE5,
GVT_PAR_DESCR2,
GVT_PAR_DESCR3,
GVT_PAR_DESCR4,
GVT_PAR_DESCR5,
FTE_EDIT_INDC,
DEPT_TENURE_FLG,
TL_DISTRIB_INFO,
USE_BUDGETS,
USE_ENCUMBRANCES,
USE_DISTRIBUTION,
BUDGET_DEPTID,
DIST_PRORATE_OPTN,
HP_STATS_DEPT_CD,
HP_STATS_FACULTY,
MANAGER_NAME,
ACCOUNTING_OWNER,
COUNTRY_GRP
)
SELECT
exp_pass_through.SETID as SETID,
exp_pass_through.DEPTID as DEPTID,
exp_pass_through.EFFDT as EFFDT,
exp_pass_through.EFF_STATUS as EFF_STATUS,
exp_pass_through.DESCR as DESCR,
exp_pass_through.DESCRSHORT as DESCRSHORT,
exp_pass_through.COMPANY as COMPANY,
exp_pass_through.SETID_LOCATION as SETID_LOCATION,
exp_pass_through.LOCATION as LOCATION,
exp_pass_through.TAX_LOCATION_CD as TAX_LOCATION_CD,
exp_pass_through.MANAGER_ID as MANAGER_ID,
exp_pass_through.MANAGER_POSN as MANAGER_POSN,
exp_pass_through.BUDGET_YR_END_DT as BUDGET_YR_END_DT,
exp_pass_through.BUDGET_LVL as BUDGET_LVL,
exp_pass_through.GL_EXPENSE as GL_EXPENSE,
exp_pass_through.EEO4_FUNCTION as EEO4_FUNCTION,
exp_pass_through.CAN_IND_SECTOR as CAN_IND_SECTOR,
exp_pass_through.ACCIDENT_INS as ACCIDENT_INS,
exp_pass_through.SI_ACCIDENT_NUM as SI_ACCIDENT_NUM,
exp_pass_through.HAZARD as HAZARD,
exp_pass_through.ESTABID as ESTABID,
exp_pass_through.RISKCD as RISKCD,
exp_pass_through.GVT_DESCR40 as GVT_DESCR40,
exp_pass_through.GVT_SUB_AGENCY as GVT_SUB_AGENCY,
exp_pass_through.GVT_PAR_LINE2 as GVT_PAR_LINE2,
exp_pass_through.GVT_PAR_LINE3 as GVT_PAR_LINE3,
exp_pass_through.GVT_PAR_LINE4 as GVT_PAR_LINE4,
exp_pass_through.GVT_PAR_LINE5 as GVT_PAR_LINE5,
exp_pass_through.GVT_PAR_DESCR2 as GVT_PAR_DESCR2,
exp_pass_through.GVT_PAR_DESCR3 as GVT_PAR_DESCR3,
exp_pass_through.GVT_PAR_DESCR4 as GVT_PAR_DESCR4,
exp_pass_through.GVT_PAR_DESCR5 as GVT_PAR_DESCR5,
exp_pass_through.CLASS_UNIT_NZL as FTE_EDIT_INDC,
exp_pass_through.ORG_UNIT_AUS as DEPT_TENURE_FLG,
exp_pass_through.WORK_SECTOR_AUS as TL_DISTRIB_INFO,
exp_pass_through.APS_AGENT_CD_AUS as USE_BUDGETS,
exp_pass_through.IND_COMMITTEE_BEL as USE_ENCUMBRANCES,
exp_pass_through.NACE_CD_BEL as USE_DISTRIBUTION,
exp_pass_through.FTE_EDIT_INDC as BUDGET_DEPTID,
exp_pass_through.DEPT_TENURE_FLG as DIST_PRORATE_OPTN,
exp_pass_through.TL_DISTRIB_INFO as HP_STATS_DEPT_CD,
exp_pass_through.USE_BUDGETS as HP_STATS_FACULTY,
exp_pass_through.USE_ENCUMBRANCES as MANAGER_NAME,
exp_pass_through.USE_DISTRIBUTION as ACCOUNTING_OWNER,
exp_pass_through.BUDGET_DEPTID as COUNTRY_GRP
FROM
exp_pass_through;


-- PIPELINE END FOR 1

-- Component exp_ps_dept_tbl, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ps_dept_tbl AS
(
SELECT
SQ_PS_DEPT_TBL1.record_count as record_count,
:FEED_IND as feed_ind,
to_Char ( CURRENT_TIMESTAMP , ''YYYY-MM-DD'' ) as feed_dt,
filler,
SQ_PS_DEPT_TBL1.source_record_id
FROM
SQ_PS_DEPT_TBL1
);


-- Component TRG_STAG_PS_LOOKUP, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_STAG_PS_LOOKUP AS
(
SELECT
exp_ps_dept_tbl.feed_ind as feed_ind,
exp_ps_dept_tbl.feed_dt as feed_dt,
exp_ps_dept_tbl.record_count as record_cnt,
exp_ps_dept_tbl.filler as FIELD1,
exp_ps_dept_tbl.filler as FIELD2,
exp_ps_dept_tbl.filler as FIELD3,
exp_ps_dept_tbl.filler as FIELD4,
exp_ps_dept_tbl.filler as FIELD5,
exp_ps_dept_tbl.filler as FIELD6,
exp_ps_dept_tbl.filler as FIELD7,
exp_ps_dept_tbl.filler as FIELD8,
exp_ps_dept_tbl.filler as FIELD9,
exp_ps_dept_tbl.filler as FIELD10,
exp_ps_dept_tbl.filler as FIELD11,
exp_ps_dept_tbl.filler as FIELD12,
exp_ps_dept_tbl.filler as FIELD13,
exp_ps_dept_tbl.filler as FIELD14,
exp_ps_dept_tbl.filler as FIELD15,
exp_ps_dept_tbl.filler as FIELD16,
exp_ps_dept_tbl.filler as FIELD17,
exp_ps_dept_tbl.filler as FIELD18,
exp_ps_dept_tbl.filler as FIELD19,
exp_ps_dept_tbl.filler as FIELD20,
exp_ps_dept_tbl.filler as FIELD21,
exp_ps_dept_tbl.filler as FIELD22,
exp_ps_dept_tbl.filler as FIELD23,
exp_ps_dept_tbl.filler as FIELD24,
exp_ps_dept_tbl.filler as FIELD25,
exp_ps_dept_tbl.filler as FIELD26,
exp_ps_dept_tbl.filler as FIELD27
FROM
exp_ps_dept_tbl
);


-- Component TRG_STAG_PS_LOOKUP, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 2

END; ';