-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_PRTY_GRP_INSUPD("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
       run_id STRING;
       start_dttm STRING;
       end_dttm STRING;
       PRCS_ID STRING;
	   v_start_time TIMESTAMP;
BEGIN
       run_id := (SELECT run_id FROM control_run_id WHERE worklet_name = :worklet_name ORDER BY insert_ts DESC LIMIT 1);
       start_dttm := (SELECT param_value FROM control_params WHERE run_id = :run_id AND param_name = ''start_dttm'' LIMIT 1);
       end_dttm := (SELECT param_value FROM control_params WHERE run_id = :run_id AND param_name = ''end_dttm'' LIMIT 1);
       PRCS_ID := (SELECT param_value FROM control_params WHERE run_id = :run_id AND param_name = ''PRCS_ID'' LIMIT 1);
	   v_start_time := CURRENT_TIMESTAMP();

-- Component LKP_TERADATA_ETL_REF_XLAT_SRC_CD, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_TERADATA_ETL_REF_XLAT_SRC_CD AS
(
SELECT 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL

	,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 

FROM 

	DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT

WHERE 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM= ''SRC_SYS'' 

             AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_NM= ''derived'' 

		AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_SYS=''DS'' 

		AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''
);


-- Component SQ_cc_group, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_cc_group AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CreateTime,
$2 as Name,
$3 as cctl_grouptype_TYPECODE,
$4 as SYS_SRC_CD,
$5 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT case when cc_group.CreateTime_stg is null then TO_DATE(''19000101'',''YYYYMMDD'')  else cc_group.CreateTime_stg end as CreateTime_stg

, cc_group.Name_stg

, cctl_grouptype.TYPECODE_stg ,

''SRC_SYS6'' as SYS_SRC_CD

FROM

 (SELECT  

 cc_group.CreateTime_stg, 

 cc_group.Name_stg, 

 cc_group.UpdateTime_stg,

 cc_group.GroupType_stg

FROM

 DB_T_PROD_STAG.cc_group

where 

cc_group.UpdateTime_stg > (:start_dttm)

and cc_group.UpdateTime_stg <= (:end_dttm))cc_group 

inner join

DB_T_PROD_STAG.cctl_grouptype on cc_group.grouptype_stg = cctl_grouptype.id_stg
) SRC
)
);


-- Component exp_PRTY_GRP_pass_thru, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_PRTY_GRP_pass_thru AS
(
SELECT
SQ_cc_group.CreateTime as o_CreateTime,
SQ_cc_group.Name as Name,
SQ_cc_group.cctl_grouptype_TYPECODE as cctl_grouptype_TYPECODE,
SQ_cc_group.SYS_SRC_CD as SYS_SRC_CD,
SQ_cc_group.source_record_id
FROM
SQ_cc_group
);


-- Component LKP_GROUPTYPE, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_GROUPTYPE AS
(
SELECT
LKP.TGT_IDNTFTN_VAL,
exp_PRTY_GRP_pass_thru.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_PRTY_GRP_pass_thru.source_record_id ORDER BY LKP.TGT_IDNTFTN_VAL desc,LKP.SRC_IDNTFTN_VAL desc) RNK
FROM
exp_PRTY_GRP_pass_thru
LEFT JOIN (
SELECT 
	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL
	,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 
FROM 
	DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT
WHERE 
	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM= ''PRTY_GRP_TYPE'' 
             AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_NM= ''cctl_grouptype.typecode'' 
		AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_SYS=''GW'' 
		AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''
) LKP ON LKP.SRC_IDNTFTN_VAL = exp_PRTY_GRP_pass_thru.cctl_grouptype_TYPECODE
QUALIFY RNK = 1
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
exp_PRTY_GRP_pass_thru.o_CreateTime as CreateTime,
exp_PRTY_GRP_pass_thru.Name as Name,
CASE WHEN LKP_GROUPTYPE.TGT_IDNTFTN_VAL IS NULL THEN ''UNK'' ELSE LKP_GROUPTYPE.TGT_IDNTFTN_VAL END as out_cctl_grouptype_typecode,
exp_PRTY_GRP_pass_thru.SYS_SRC_CD as SYS_SRC_CD,
LKP_1.TGT_IDNTFTN_VAL /* replaced lookup LKP_TERADATA_ETL_REF_XLAT_SRC_CD */ as SRC_SYS_CD,
exp_PRTY_GRP_pass_thru.source_record_id,
row_number() over (partition by exp_PRTY_GRP_pass_thru.source_record_id order by exp_PRTY_GRP_pass_thru.source_record_id) as RNK
FROM
exp_PRTY_GRP_pass_thru
INNER JOIN LKP_GROUPTYPE ON exp_PRTY_GRP_pass_thru.source_record_id = LKP_GROUPTYPE.source_record_id
LEFT JOIN LKP_TERADATA_ETL_REF_XLAT_SRC_CD LKP_1 ON LKP_1.SRC_IDNTFTN_VAL = exp_PRTY_GRP_pass_thru.SYS_SRC_CD
QUALIFY row_number() over (partition by exp_PRTY_GRP_pass_thru.source_record_id order by exp_PRTY_GRP_pass_thru.source_record_id) 
= 1
);


-- Component LKP_PRTY_GRP, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_PRTY_GRP AS
(
SELECT
LKP.PRTY_GRP_ID,
LKP.PRTY_GRP_DESC,
LKP.PRTY_GRP_STRT_DTTM,
LKP.PRTY_GRP_RSN_TYPE_CD,
LKP.EDW_STRT_DTTM,
LKP.SRC_SYS_CD,
EXPTRANS.source_record_id,
ROW_NUMBER() OVER(PARTITION BY EXPTRANS.source_record_id ORDER BY LKP.PRTY_GRP_ID asc,LKP.PRTY_GRP_DESC asc,LKP.PRTY_GRP_NAME asc,LKP.PRTY_GRP_STRT_DTTM asc,LKP.PRTY_GRP_RSN_TYPE_CD asc,LKP.PRTY_GRP_TYPE_CD asc,LKP.EDW_STRT_DTTM asc,LKP.EDW_END_DTTM asc,LKP.SRC_SYS_CD asc) RNK
FROM
EXPTRANS
LEFT JOIN (
SELECT	PRTY_GRP.PRTY_GRP_ID as PRTY_GRP_ID, PRTY_GRP.PRTY_GRP_DESC as PRTY_GRP_DESC,PRTY_GRP.PRTY_GRP_NAME as PRTY_GRP_NAME,PRTY_GRP.PRTY_GRP_STRT_DTTM as PRTY_GRP_STRT_DTTM, PRTY_GRP.PRTY_GRP_RSN_TYPE_CD as PRTY_GRP_RSN_TYPE_CD,PRTY_GRP.PRTY_GRP_TYPE_CD as PRTY_GRP_TYPE_CD,PRTY_GRP.EDW_STRT_DTTM as EDW_STRT_DTTM,PRTY_GRP.EDW_END_DTTM as EDW_END_DTTM,PRTY_GRP.SRC_SYS_CD as SRC_SYS_CD FROM DB_T_PROD_CORE.PRTY_GRP 
QUALIFY	ROW_NUMBER() OVER(PARTITION BY PRTY_GRP_NAME,PRTY_GRP_TYPE_CD,SRC_SYS_CD ORDER BY EDW_END_DTTM desc) = 1
) LKP ON LKP.PRTY_GRP_NAME = EXPTRANS.Name AND LKP.PRTY_GRP_TYPE_CD = EXPTRANS.out_cctl_grouptype_typecode AND LKP.SRC_SYS_CD = EXPTRANS.SRC_SYS_CD
QUALIFY ROW_NUMBER() OVER(PARTITION BY EXPTRANS.source_record_id ORDER BY LKP.PRTY_GRP_ID asc,LKP.PRTY_GRP_DESC asc,LKP.PRTY_GRP_NAME asc,LKP.PRTY_GRP_STRT_DTTM asc,LKP.PRTY_GRP_RSN_TYPE_CD asc,LKP.PRTY_GRP_TYPE_CD asc,LKP.EDW_STRT_DTTM asc,LKP.EDW_END_DTTM asc,LKP.SRC_SYS_CD asc)  
= 1
);


-- Component exp_data_transformation, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_data_transformation AS
(
SELECT
LKP_PRTY_GRP.PRTY_GRP_ID as PRTY_GRP_ID,
''UNK'' as PRTY_GRP_DESC,
''UNK'' as PRTY_GRP_DESC1,
EXPTRANS.Name as PRTY_GRP_NAME,
EXPTRANS.CreateTime as PRTY_GRP_STRT_DT,
NULL as PRTY_GRP_DATA_SRC_CD,
NULL as PARNT_PRTY_GRP_ID,
NULL as PRTY_GRP_RSN_TYPE_CD,
EXPTRANS.out_cctl_grouptype_typecode as PRTY_GRP_TYPE_CD,
:PRCS_ID as PRCS_ID,
md5 ( ltrim ( rtrim ( LKP_PRTY_GRP.PRTY_GRP_DESC ) ) || ltrim ( rtrim ( LKP_PRTY_GRP.PRTY_GRP_STRT_DTTM ) ) ) as chksum_lkp,
md5 ( ltrim ( rtrim ( PRTY_GRP_DESC1 ) ) || ltrim ( rtrim ( EXPTRANS.CreateTime ) ) ) as chksum_iinp,
CASE WHEN chksum_lkp IS NULL THEN ''I'' ELSE CASE WHEN chksum_lkp != chksum_iinp THEN ''U'' ELSE ''R'' END END as out_INS_UPD_FLG,
LKP_PRTY_GRP.EDW_STRT_DTTM as lkp_EDW_STRT_DTTM,
CURRENT_TIMESTAMP as EDW_STRT_DTTM,
TO_DATE ( ''12/31/9999 23:59:59.999999'' , ''MM/DD/YYYY HH24:MI:SS.FF6'' ) as EDW_END_DTTM,
dateadd ( second, -1, CURRENT_TIMESTAMP ) as EDW_END_DTTM3_exp,
EXPTRANS.SRC_SYS_CD as SRC_SYS_CD,
EXPTRANS.source_record_id
FROM
EXPTRANS
INNER JOIN LKP_PRTY_GRP ON EXPTRANS.source_record_id = LKP_PRTY_GRP.source_record_id
);


-- Component rtr_PRTY_GRP_INSERT, Type ROUTER Output Group INSERT
CREATE OR REPLACE TEMPORARY TABLE rtr_PRTY_GRP_INSERT AS (
SELECT
exp_data_transformation.PRTY_GRP_ID as PRTY_GRP_ID,
exp_data_transformation.PRTY_GRP_DESC as PRTY_GRP_DESC,
exp_data_transformation.PRTY_GRP_NAME as PRTY_GRP_NAME,
exp_data_transformation.PRTY_GRP_STRT_DT as PRTY_GRP_STRT_DT,
exp_data_transformation.PRTY_GRP_DATA_SRC_CD as PRTY_GRP_DATA_SRC_CD,
exp_data_transformation.PARNT_PRTY_GRP_ID as PARNT_PRTY_GRP_ID,
exp_data_transformation.PRTY_GRP_RSN_TYPE_CD as PRTY_GRP_RSN_TYPE_CD,
exp_data_transformation.PRTY_GRP_TYPE_CD as PRTY_GRP_TYPE_CD,
exp_data_transformation.PRCS_ID as PRCS_ID,
exp_data_transformation.SRC_SYS_CD as SRC_SYS_CD,
exp_data_transformation.out_INS_UPD_FLG as out_INS_UPD_FLG,
exp_data_transformation.lkp_EDW_STRT_DTTM as lkp_EDW_STRT_DTTM,
exp_data_transformation.EDW_STRT_DTTM as EDW_STRT_DTTM,
exp_data_transformation.EDW_END_DTTM as EDW_END_DTTM,
exp_data_transformation.EDW_END_DTTM3_exp as EDW_END_DTTM3_exp,
exp_data_transformation.source_record_id
FROM
exp_data_transformation
WHERE exp_data_transformation.out_INS_UPD_FLG = ''I''
);


-- Component rtr_PRTY_GRP_UPDATE, Type ROUTER Output Group UPDATE
CREATE OR REPLACE TEMPORARY TABLE rtr_PRTY_GRP_UPDATE AS (
SELECT
exp_data_transformation.PRTY_GRP_ID as PRTY_GRP_ID,
exp_data_transformation.PRTY_GRP_DESC as PRTY_GRP_DESC,
exp_data_transformation.PRTY_GRP_NAME as PRTY_GRP_NAME,
exp_data_transformation.PRTY_GRP_STRT_DT as PRTY_GRP_STRT_DT,
exp_data_transformation.PRTY_GRP_DATA_SRC_CD as PRTY_GRP_DATA_SRC_CD,
exp_data_transformation.PARNT_PRTY_GRP_ID as PARNT_PRTY_GRP_ID,
exp_data_transformation.PRTY_GRP_RSN_TYPE_CD as PRTY_GRP_RSN_TYPE_CD,
exp_data_transformation.PRTY_GRP_TYPE_CD as PRTY_GRP_TYPE_CD,
exp_data_transformation.PRCS_ID as PRCS_ID,
exp_data_transformation.SRC_SYS_CD as SRC_SYS_CD,
exp_data_transformation.out_INS_UPD_FLG as out_INS_UPD_FLG,
exp_data_transformation.lkp_EDW_STRT_DTTM as lkp_EDW_STRT_DTTM,
exp_data_transformation.EDW_STRT_DTTM as EDW_STRT_DTTM,
exp_data_transformation.EDW_END_DTTM as EDW_END_DTTM,
exp_data_transformation.EDW_END_DTTM3_exp as EDW_END_DTTM3_exp,
exp_data_transformation.source_record_id
FROM
exp_data_transformation
WHERE exp_data_transformation.out_INS_UPD_FLG = ''U''
);


-- Component upd_PRTY_GRP_insupd, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_PRTY_GRP_insupd AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
rtr_PRTY_GRP_UPDATE.PRTY_GRP_ID as PRTY_GRP_ID1,
rtr_PRTY_GRP_UPDATE.PRTY_GRP_DESC as PRTY_GRP_DESC1,
rtr_PRTY_GRP_UPDATE.PRTY_GRP_NAME as PRTY_GRP_NAME1,
rtr_PRTY_GRP_UPDATE.PRTY_GRP_STRT_DT as PRTY_GRP_STRT_DT1,
rtr_PRTY_GRP_UPDATE.PRTY_GRP_DATA_SRC_CD as PRTY_GRP_DATA_SRC_CD1,
rtr_PRTY_GRP_UPDATE.PARNT_PRTY_GRP_ID as PARNT_PRTY_GRP_ID1,
rtr_PRTY_GRP_UPDATE.PRTY_GRP_RSN_TYPE_CD as PRTY_GRP_RSN_TYPE_CD1,
rtr_PRTY_GRP_UPDATE.PRTY_GRP_TYPE_CD as PRTY_GRP_TYPE_CD1,
rtr_PRTY_GRP_UPDATE.PRCS_ID as PRCS_ID1,
rtr_PRTY_GRP_UPDATE.EDW_STRT_DTTM as EDW_STRT_DTTM3,
rtr_PRTY_GRP_UPDATE.EDW_END_DTTM as EDW_END_DTTM3,
rtr_PRTY_GRP_UPDATE.SRC_SYS_CD as SRC_SYS_CD,
rtr_PRTY_GRP_UPDATE.source_record_id,
0 as UPDATE_STRATEGY_ACTION
FROM
rtr_PRTY_GRP_UPDATE
);


-- Component upd_PRTY_GRP_ins, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_PRTY_GRP_ins AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
sq_PRTY_GRP.NEXTVAL as PRTY_GRP_ID1,
rtr_PRTY_GRP_INSERT.PRTY_GRP_DESC as PRTY_GRP_DESC1,
rtr_PRTY_GRP_INSERT.PRTY_GRP_NAME as PRTY_GRP_NAME1,
rtr_PRTY_GRP_INSERT.PRTY_GRP_STRT_DT as PRTY_GRP_STRT_DT1,
rtr_PRTY_GRP_INSERT.PRTY_GRP_DATA_SRC_CD as PRTY_GRP_DATA_SRC_CD1,
rtr_PRTY_GRP_INSERT.PARNT_PRTY_GRP_ID as PARNT_PRTY_GRP_ID1,
rtr_PRTY_GRP_INSERT.PRTY_GRP_RSN_TYPE_CD as PRTY_GRP_RSN_TYPE_CD1,
rtr_PRTY_GRP_INSERT.PRTY_GRP_TYPE_CD as PRTY_GRP_TYPE_CD1,
rtr_PRTY_GRP_INSERT.PRCS_ID as PRCS_ID1,
rtr_PRTY_GRP_INSERT.EDW_STRT_DTTM as EDW_STRT_DTTM1,
rtr_PRTY_GRP_INSERT.EDW_END_DTTM as EDW_END_DTTM1,
rtr_PRTY_GRP_INSERT.SRC_SYS_CD as o_SYS_CD1,
rtr_PRTY_GRP_INSERT.source_record_id,
0 as UPDATE_STRATEGY_ACTION
FROM
rtr_PRTY_GRP_INSERT
);


-- Component exp_PASS_TO_TARGET_INSUPD, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_PASS_TO_TARGET_INSUPD AS
(
SELECT
upd_PRTY_GRP_insupd.PRTY_GRP_ID1 as PRTY_GRP_ID1,
upd_PRTY_GRP_insupd.PRTY_GRP_DESC1 as PRTY_GRP_DESC1,
upd_PRTY_GRP_insupd.PRTY_GRP_NAME1 as PRTY_GRP_NAME1,
upd_PRTY_GRP_insupd.PRTY_GRP_STRT_DT1 as PRTY_GRP_STRT_DT1,
upd_PRTY_GRP_insupd.PRTY_GRP_DATA_SRC_CD1 as PRTY_GRP_DATA_SRC_CD1,
upd_PRTY_GRP_insupd.PARNT_PRTY_GRP_ID1 as PARNT_PRTY_GRP_ID1,
upd_PRTY_GRP_insupd.PRTY_GRP_RSN_TYPE_CD1 as PRTY_GRP_RSN_TYPE_CD1,
upd_PRTY_GRP_insupd.PRTY_GRP_TYPE_CD1 as PRTY_GRP_TYPE_CD1,
upd_PRTY_GRP_insupd.PRCS_ID1 as PRCS_ID1,
upd_PRTY_GRP_insupd.EDW_STRT_DTTM3 as EDW_STRT_DTTM3,
upd_PRTY_GRP_insupd.EDW_END_DTTM3 as EDW_END_DTTM3,
upd_PRTY_GRP_insupd.SRC_SYS_CD as SRC_SYS_CD,
upd_PRTY_GRP_insupd.source_record_id
FROM
upd_PRTY_GRP_insupd
);


-- Component exp_PASS_TO_TARGET_INS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_PASS_TO_TARGET_INS AS
(
SELECT
upd_PRTY_GRP_ins.PRTY_GRP_ID1 as PRTY_GRP_ID1,
upd_PRTY_GRP_ins.PRTY_GRP_DESC1 as PRTY_GRP_DESC1,
upd_PRTY_GRP_ins.PRTY_GRP_NAME1 as PRTY_GRP_NAME1,
upd_PRTY_GRP_ins.PRTY_GRP_STRT_DT1 as PRTY_GRP_STRT_DT1,
upd_PRTY_GRP_ins.PRTY_GRP_DATA_SRC_CD1 as PRTY_GRP_DATA_SRC_CD1,
upd_PRTY_GRP_ins.PARNT_PRTY_GRP_ID1 as PARNT_PRTY_GRP_ID1,
upd_PRTY_GRP_ins.PRTY_GRP_RSN_TYPE_CD1 as PRTY_GRP_RSN_TYPE_CD1,
upd_PRTY_GRP_ins.PRTY_GRP_TYPE_CD1 as PRTY_GRP_TYPE_CD1,
upd_PRTY_GRP_ins.PRCS_ID1 as PRCS_ID1,
upd_PRTY_GRP_ins.EDW_STRT_DTTM1 as EDW_STRT_DTTM1,
upd_PRTY_GRP_ins.EDW_END_DTTM1 as EDW_END_DTTM1,
upd_PRTY_GRP_ins.o_SYS_CD1 as o_SYS_CD1,
upd_PRTY_GRP_ins.source_record_id
FROM
upd_PRTY_GRP_ins
);


-- Component PRTY_GRP_ins, Type TARGET 
INSERT INTO DB_T_PROD_CORE.PRTY_GRP
(
PRTY_GRP_ID,
PRTY_GRP_DESC,
PRTY_GRP_NAME,
PRTY_GRP_STRT_DTTM,
PRTY_GRP_DATA_SRC_CD,
PARNT_PRTY_GRP_ID,
PRTY_GRP_RSN_TYPE_CD,
PRTY_GRP_TYPE_CD,
PRCS_ID,
EDW_STRT_DTTM,
EDW_END_DTTM,
SRC_SYS_CD
)
SELECT
exp_PASS_TO_TARGET_INS.PRTY_GRP_ID1 as PRTY_GRP_ID,
exp_PASS_TO_TARGET_INS.PRTY_GRP_DESC1 as PRTY_GRP_DESC,
exp_PASS_TO_TARGET_INS.PRTY_GRP_NAME1 as PRTY_GRP_NAME,
exp_PASS_TO_TARGET_INS.PRTY_GRP_STRT_DT1 as PRTY_GRP_STRT_DTTM,
exp_PASS_TO_TARGET_INS.PRTY_GRP_DATA_SRC_CD1 as PRTY_GRP_DATA_SRC_CD,
exp_PASS_TO_TARGET_INS.PARNT_PRTY_GRP_ID1 as PARNT_PRTY_GRP_ID,
exp_PASS_TO_TARGET_INS.PRTY_GRP_RSN_TYPE_CD1 as PRTY_GRP_RSN_TYPE_CD,
exp_PASS_TO_TARGET_INS.PRTY_GRP_TYPE_CD1 as PRTY_GRP_TYPE_CD,
exp_PASS_TO_TARGET_INS.PRCS_ID1 as PRCS_ID,
exp_PASS_TO_TARGET_INS.EDW_STRT_DTTM1 as EDW_STRT_DTTM,
exp_PASS_TO_TARGET_INS.EDW_END_DTTM1 as EDW_END_DTTM,
exp_PASS_TO_TARGET_INS.o_SYS_CD1 as SRC_SYS_CD
FROM
exp_PASS_TO_TARGET_INS;


-- Component upd_PRTY_GRP_upd, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_PRTY_GRP_upd AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
rtr_PRTY_GRP_UPDATE.PRTY_GRP_ID as PRTY_GRP_ID3,
rtr_PRTY_GRP_UPDATE.PRTY_GRP_DESC as PRTY_GRP_DESC3,
rtr_PRTY_GRP_UPDATE.PRTY_GRP_NAME as PRTY_GRP_NAME3,
rtr_PRTY_GRP_UPDATE.PRTY_GRP_STRT_DT as PRTY_GRP_STRT_DT3,
rtr_PRTY_GRP_UPDATE.PRTY_GRP_DATA_SRC_CD as PRTY_GRP_DATA_SRC_CD3,
rtr_PRTY_GRP_UPDATE.PARNT_PRTY_GRP_ID as PARNT_PRTY_GRP_ID3,
rtr_PRTY_GRP_UPDATE.PRTY_GRP_RSN_TYPE_CD as PRTY_GRP_RSN_TYPE_CD3,
rtr_PRTY_GRP_UPDATE.PRTY_GRP_TYPE_CD as PRTY_GRP_TYPE_CD3,
rtr_PRTY_GRP_UPDATE.PRCS_ID as PRCS_ID3,
rtr_PRTY_GRP_UPDATE.lkp_EDW_STRT_DTTM as lkp_EDW_STRT_DTTM3,
rtr_PRTY_GRP_UPDATE.EDW_END_DTTM3_exp as EDW_END_DTTM3_exp3,
rtr_PRTY_GRP_UPDATE.source_record_id,
1 as UPDATE_STRATEGY_ACTION
FROM
rtr_PRTY_GRP_UPDATE
);


-- Component PRTY_GRP_insupd, Type TARGET 
INSERT INTO DB_T_PROD_CORE.PRTY_GRP
(
PRTY_GRP_ID,
PRTY_GRP_DESC,
PRTY_GRP_NAME,
PRTY_GRP_STRT_DTTM,
PRTY_GRP_DATA_SRC_CD,
PARNT_PRTY_GRP_ID,
PRTY_GRP_RSN_TYPE_CD,
PRTY_GRP_TYPE_CD,
PRCS_ID,
EDW_STRT_DTTM,
EDW_END_DTTM,
SRC_SYS_CD
)
SELECT
exp_PASS_TO_TARGET_INSUPD.PRTY_GRP_ID1 as PRTY_GRP_ID,
exp_PASS_TO_TARGET_INSUPD.PRTY_GRP_DESC1 as PRTY_GRP_DESC,
exp_PASS_TO_TARGET_INSUPD.PRTY_GRP_NAME1 as PRTY_GRP_NAME,
exp_PASS_TO_TARGET_INSUPD.PRTY_GRP_STRT_DT1 as PRTY_GRP_STRT_DTTM,
exp_PASS_TO_TARGET_INSUPD.PRTY_GRP_DATA_SRC_CD1 as PRTY_GRP_DATA_SRC_CD,
exp_PASS_TO_TARGET_INSUPD.PARNT_PRTY_GRP_ID1 as PARNT_PRTY_GRP_ID,
exp_PASS_TO_TARGET_INSUPD.PRTY_GRP_RSN_TYPE_CD1 as PRTY_GRP_RSN_TYPE_CD,
exp_PASS_TO_TARGET_INSUPD.PRTY_GRP_TYPE_CD1 as PRTY_GRP_TYPE_CD,
exp_PASS_TO_TARGET_INSUPD.PRCS_ID1 as PRCS_ID,
exp_PASS_TO_TARGET_INSUPD.EDW_STRT_DTTM3 as EDW_STRT_DTTM,
exp_PASS_TO_TARGET_INSUPD.EDW_END_DTTM3 as EDW_END_DTTM,
exp_PASS_TO_TARGET_INSUPD.SRC_SYS_CD as SRC_SYS_CD
FROM
exp_PASS_TO_TARGET_INSUPD;


-- Component exp_PASS_TO_TARGET_UPD, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_PASS_TO_TARGET_UPD AS
(
SELECT
upd_PRTY_GRP_upd.PRTY_GRP_ID3 as PRTY_GRP_ID3,
upd_PRTY_GRP_upd.lkp_EDW_STRT_DTTM3 as lkp_EDW_STRT_DTTM3,
upd_PRTY_GRP_upd.EDW_END_DTTM3_exp3 as EDW_END_DTTM3_exp3,
upd_PRTY_GRP_upd.source_record_id
FROM
upd_PRTY_GRP_upd
);


-- Component PRTY_GRP_upd, Type TARGET 
MERGE INTO DB_T_PROD_CORE.PRTY_GRP
USING exp_PASS_TO_TARGET_UPD ON (PRTY_GRP.PRTY_GRP_ID = exp_PASS_TO_TARGET_UPD.PRTY_GRP_ID3 AND PRTY_GRP.EDW_STRT_DTTM = exp_PASS_TO_TARGET_UPD.lkp_EDW_STRT_DTTM3)
WHEN MATCHED THEN UPDATE
SET
PRTY_GRP_ID = exp_PASS_TO_TARGET_UPD.PRTY_GRP_ID3,
EDW_STRT_DTTM = exp_PASS_TO_TARGET_UPD.lkp_EDW_STRT_DTTM3,
EDW_END_DTTM = exp_PASS_TO_TARGET_UPD.EDW_END_DTTM3_exp3;


END; ';