-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_ETL_LOAD_CTRL_UPD("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_Shortcut_to_MEMBER1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_MEMBER1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as START_DTTM,
$2 as END_DTTM,
$3 as ID,
$4 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT MAX(END_DTTM) as START_DTTM,  MAX(LAST_UPDATE_TS ) as END_DTTM , maX(Id)
FROM
 DB_T_STAG_MEMBXREF_PROD.MEMBER a join  DB_T_STAG_MEMBXREF_PROD.ETL_LOAD_CTRL B on 1=1 and  B.PRCS_NM =''FEDERATION'' AND B.STATUS =''IN PROGRESS''
) SRC
)
);


-- Component exp_calc1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_calc1 AS
(
SELECT
''SUCCEEDED'' as out_STATUS,
SQ_Shortcut_to_MEMBER1.ID as ID,
SQ_Shortcut_to_MEMBER1.source_record_id
FROM
SQ_Shortcut_to_MEMBER1
);


-- Component UPD_STATUS, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE UPD_STATUS AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
exp_calc1.ID as ID,
exp_calc1.out_STATUS as out_STATUS,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_calc1
);


-- Component Shortcut_to_ETL_LOAD_CTRL1, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_STAG_MEMBXREF_PROD.ETL_LOAD_CTRL
USING UPD_STATUS ON (UPDATE_STRATEGY_ACTION = 1 AND ETL_LOAD_CTRL.ID = UPD_STATUS.ID)
WHEN MATCHED THEN UPDATE
SET
STATUS = UPD_STATUS.out_STATUS
;


END; ';