-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_ECTL_BATCH_INFO_UPD2025("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_Shortcut_to_ECTL_BATCH_INFO, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_ECTL_BATCH_INFO AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_BATCH_ID,
$2 as ECTL_PROJ_ID,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT ECTL_BATCH_ID, ECTL_PROJ_ID 
FROM
 DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO
WHERE ECTL_BATCH_INFO.ECTL_ACTIVE_IND = ''Y''
AND ECTL_BATCH_INFO.ECTL_PROJ_ID = 4
) SRC
)
);


-- Component exp_UPD_BATCH_TS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_UPD_BATCH_TS AS
(
SELECT
SQ_Shortcut_to_ECTL_BATCH_INFO.ECTL_BATCH_ID as ECTL_BATCH_ID,
SQ_Shortcut_to_ECTL_BATCH_INFO.ECTL_PROJ_ID as ECTL_PROJ_ID,
''N'' as out_BATCH_IND,
CURRENT_TIMESTAMP as out_BATCH_END_TS,
SQ_Shortcut_to_ECTL_BATCH_INFO.source_record_id
FROM
SQ_Shortcut_to_ECTL_BATCH_INFO
);


-- Component upd_ECTL_BATCH_INFO, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_ECTL_BATCH_INFO AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
exp_UPD_BATCH_TS.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_UPD_BATCH_TS.ECTL_PROJ_ID as ECTL_PROJ_ID,
exp_UPD_BATCH_TS.out_BATCH_IND as out_BATCH_IND,
exp_UPD_BATCH_TS.out_BATCH_END_TS as out_BATCH_END_TS,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_UPD_BATCH_TS
);


-- Component ECTL_BATCH_INFO_UPD, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO
USING upd_ECTL_BATCH_INFO ON (UPDATE_STRATEGY_ACTION = 1 AND ECTL_BATCH_INFO.ECTL_BATCH_ID = upd_ECTL_BATCH_INFO.ECTL_BATCH_ID)
WHEN MATCHED THEN UPDATE
SET
ECTL_PROJ_ID = upd_ECTL_BATCH_INFO.ECTL_PROJ_ID,
ECTL_BATCH_END_TS = upd_ECTL_BATCH_INFO.out_BATCH_END_TS,
ECTL_ACTIVE_IND = upd_ECTL_BATCH_INFO.out_BATCH_IND
;


END; ';