-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_AGMT_FEAT_PERIL_MTRC_INSUPD("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
declare
start_dttm timestamp;
end_dttm timestamp;
prcs_id integer;
in_FEAT_SBTYPE_CD VARCHAR;

BEGIN 

    start_dttm := current_timestamp();
    end_dttm := current_timestamp();
    prcs_id := 1;
	in_FEAT_SBTYPE_CD := ''1'';

-- Component LKP_TERADATA_ETL_REF_XLAT_ASSET_CMTRCT_ROLE_SBTYPE, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_TERADATA_ETL_REF_XLAT_ASSET_CMTRCT_ROLE_SBTYPE AS
(
SELECT 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL

	,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 

FROM 

	db_t_prod_core.TERADATA_ETL_REF_XLAT

WHERE 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM=''ASSET_CNTRCT_ROLE_SBTYPE''

         		AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''
);


-- Component LKP_TERADATA_ETL_REF_XLAT_ASSET_SBTYPE, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_TERADATA_ETL_REF_XLAT_ASSET_SBTYPE AS
(
SELECT 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL

	,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 

FROM 

	db_t_prod_core.TERADATA_ETL_REF_XLAT

WHERE 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM= ''PRTY_ASSET_SBTYPE'' 

             AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_NM= ''derived'' 

		AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_SYS=''DS'' 

		AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''
);


-- Component LKP_TERADATA_ETL_REF_XLAT_INSRNC_MTRC, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_TERADATA_ETL_REF_XLAT_INSRNC_MTRC AS
(
SELECT 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL

	,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 

FROM 

	db_t_prod_core.TERADATA_ETL_REF_XLAT

WHERE 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM= ''INSRNC_MTRC_TYPE''

             AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_NM=''derived''

			AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''
);


-- Component LKP_TERADATA_ETL_REF_XLAT_PLCY_SECTION_TYPE, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_TERADATA_ETL_REF_XLAT_PLCY_SECTION_TYPE AS
(
SELECT 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL

	,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 

FROM 

	db_t_prod_core.TERADATA_ETL_REF_XLAT

WHERE 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM= ''PLCY_SECTN_TYPE'' 

		AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''
);


-- Component LKP_TERADATA_ETL_REF_XLAT_RTG_PERIL, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_TERADATA_ETL_REF_XLAT_RTG_PERIL AS
(
SELECT 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL

	,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 

FROM 

	db_t_prod_core.TERADATA_ETL_REF_XLAT

WHERE 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM=''RTG_PERIL_TYPE''

         		AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''
);


-- Component SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as PublicID,
$2 as Feat_NKsrckey,
$3 as Inscrn_Mtrc_Type_CD,
$4 as Peril_type,
$5 as Amount,
$6 as Section_type,
$7 as Earnings_as_of_dt,
$8 as TRANS_STRT_DTTM,
$9 as TRANS_END_DTTM,
$10 as cury_cd,
$11 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT pc_policyperiod.PublicID_stg,pc_etlclausepattern.PatternID_stg,''INSRNC_MTRC_TYPE16'' AS Inscrn_Mtrc_Type_CD

,pctl_periltype_alfa.TypeCode_stg AS Peril_type

,sum(pcx_hotransaction_hoe.amount_stg)

,''PLCY_SECTN_TYPE_CD'' AS section_type

,pc_policyperiod.EditEffectiveDate_stg

,pc_policyperiod.UpdateTime_stg AS TRANS_STRT_DTTM

,pc_policyperiod.UpdateTime_stg AS TRANS_END_DTTM

,''ISO_CURY_TYPE1'' AS cury_cd

FROM DB_T_PROD_STAG.pc_policyperiod 

/* Added as part of EIM-41199 */
INNER JOIN DB_T_PROD_STAG.pc_policy ON pc_policy.ID_stg=pc_policyperiod.PolicyID_stg

JOIN DB_T_PROD_STAG.pcx_hotransaction_hoe ON pcx_hotransaction_hoe.BranchID_stg = pc_policyperiod.id_stg

AND (pcx_hotransaction_hoe.ExpirationDate_stg IS NULL

OR pcx_hotransaction_hoe.ExpirationDate_stg > pc_policyperiod.EditEffectiveDate_stg)

JOIN DB_T_PROD_STAG.pcx_homeownerscost_hoe ON pcx_homeownerscost_hoe.ID_stg = pcx_hotransaction_hoe.HomeownersCost_stg

AND (pcx_hotransaction_hoe.ExpirationDate_stg IS NULL OR pcx_hotransaction_hoe.ExpirationDate_stg > pc_policyperiod.EditEffectiveDate_stg)

JOIN  DB_T_PROD_STAG.pctl_PerilType_alfa ON  pctl_PerilType_alfa.ID_stg = pcx_homeownerscost_hoe.PerilType_alfa_stg

 JOIN DB_T_PROD_STAG.pcx_homeownerslinecov_hoe ON pcx_homeownerslinecov_hoe.id_stg =  pcx_homeownerscost_hoe.HomeownersLineCov_stg

AND (pcx_homeownerslinecov_hoe.ExpirationDate_stg IS NULL OR pcx_homeownerslinecov_hoe.ExpirationDate_stg > pc_policyperiod.EditEffectiveDate_stg)

 JOIN DB_T_PROD_STAG.pc_policyline ON pc_policyline.ID_stg = pcx_homeownerslinecov_hoe.HOLine_stg

 JOIN DB_T_PROD_STAG.pc_etlclausepattern ON pc_etlclausepattern.PatternID_stg = pcx_homeownerslinecov_hoe.PatternCode_stg

INNER JOIN DB_T_PROD_STAG.pctl_policyperiodstatus ON pc_policyperiod.Status_stg=pctl_policyperiodstatus.id_stg

WHERE  pctl_policyperiodstatus.typecode_stg=''Bound''

AND pcx_homeownerscost_hoe.HomeownersLineCov_stg IS NOT NULL

AND  pc_policyperiod.UpdateTime_stg > (:start_dttm)

AND pc_policyperiod.UpdateTime_stg <= (:end_dttm)

group by pc_policyperiod.PublicID_stg,pc_etlclausepattern.PatternID_stg,Inscrn_Mtrc_Type_CD,Peril_type

,section_type,pc_policyperiod.EditEffectiveDate_stg,TRANS_STRT_DTTM,TRANS_END_DTTM,cury_cd
) SRC
)
);


-- Component exp_pass_frm_src, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_frm_src AS
(
SELECT
SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.PublicID as PublicID,
SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.Feat_NKsrckey as Feat_NKsrckey,
''UNK'' as o_Asset_Classification_code,
CASE WHEN LKP_1.TGT_IDNTFTN_VAL /* replaced lookup LKP_TERADATA_ETL_REF_XLAT_ASSET_CMTRCT_ROLE_SBTYPE */ IS NULL THEN ''UNK'' ELSE LKP_2.TGT_IDNTFTN_VAL /* replaced lookup LKP_TERADATA_ETL_REF_XLAT_ASSET_CMTRCT_ROLE_SBTYPE */ END as ASSET_CNTRCT_ROLE_SBTYPE_CD,
SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.Earnings_as_of_dt as Earnings_as_of_dt1,
CASE WHEN LKP_3.TGT_IDNTFTN_VAL /* replaced lookup LKP_TERADATA_ETL_REF_XLAT_PLCY_SECTION_TYPE */ IS NULL THEN ''UNK'' ELSE LKP_4.TGT_IDNTFTN_VAL /* replaced lookup LKP_TERADATA_ETL_REF_XLAT_PLCY_SECTION_TYPE */ END as Section_type1,
LKP_5.TGT_IDNTFTN_VAL /* replaced lookup LKP_TERADATA_ETL_REF_XLAT_INSRNC_MTRC */ as o_Inscrn_Mtrc_Type_CD,
SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.Amount as Amount,
CASE WHEN SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.TRANS_STRT_DTTM IS NULL THEN to_date ( ''1900-01-01'' , ''yyyy-mm-dd'' ) ELSE SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.TRANS_STRT_DTTM END as TRANS_STRT_DTTM1,
CASE WHEN SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.TRANS_END_DTTM IS NULL THEN TO_DATE ( ''12/31/9999 23:59:59.999999'' , ''MM/DD/YYYY HH24:MI:SS.FF6'' ) ELSE SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.TRANS_END_DTTM END as TRANS_END_DTTM1,
''PPV'' as IN_AGMT_TYPE_CD,
CASE WHEN LKP_6.TGT_IDNTFTN_VAL /* replaced lookup LKP_TERADATA_ETL_REF_XLAT_RTG_PERIL */ IS NULL THEN ''UNK'' ELSE LKP_7.TGT_IDNTFTN_VAL /* replaced lookup LKP_TERADATA_ETL_REF_XLAT_RTG_PERIL */ END as in_RTG_PERIL_TYPE_CD,
SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.Earnings_as_of_dt as Earnings_as_of_dt,
SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.cury_cd as cury_cd,
SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.source_record_id,
row_number() over (partition by SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.source_record_id order by SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.source_record_id) as RNK
FROM
SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x
LEFT JOIN LKP_TERADATA_ETL_REF_XLAT_ASSET_CMTRCT_ROLE_SBTYPE LKP_1 ON LKP_1.SRC_IDNTFTN_VAL = ''UNK''
LEFT JOIN LKP_TERADATA_ETL_REF_XLAT_ASSET_CMTRCT_ROLE_SBTYPE LKP_2 ON LKP_2.SRC_IDNTFTN_VAL = ''UNK''
LEFT JOIN LKP_TERADATA_ETL_REF_XLAT_PLCY_SECTION_TYPE LKP_3 ON LKP_3.SRC_IDNTFTN_VAL = SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.Section_type
LEFT JOIN LKP_TERADATA_ETL_REF_XLAT_PLCY_SECTION_TYPE LKP_4 ON LKP_4.SRC_IDNTFTN_VAL = SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.Section_type
LEFT JOIN LKP_TERADATA_ETL_REF_XLAT_INSRNC_MTRC LKP_5 ON LKP_5.SRC_IDNTFTN_VAL = SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.Inscrn_Mtrc_Type_CD
LEFT JOIN LKP_TERADATA_ETL_REF_XLAT_RTG_PERIL LKP_6 ON LKP_6.SRC_IDNTFTN_VAL = SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.Peril_type
LEFT JOIN LKP_TERADATA_ETL_REF_XLAT_RTG_PERIL LKP_7 ON LKP_7.SRC_IDNTFTN_VAL = SQ_pc_AgmtQuotn_ast_ft_prl_mtr_x.Peril_type
QUALIFY RNK = 1
);


-- Component LKP_AGMT_PPV, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_AGMT_PPV AS
(
SELECT
LKP.AGMT_ID,
LKP.AGMT_TYPE_CD,
exp_pass_frm_src.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pass_frm_src.source_record_id ORDER BY LKP.AGMT_ID asc,LKP.HOST_AGMT_NUM asc,LKP.AGMT_NAME asc,LKP.AGMT_OPN_DTTM asc,LKP.AGMT_CLS_DTTM asc,LKP.AGMT_PLND_EXPN_DTTM asc,LKP.AGMT_SIGND_DTTM asc,LKP.AGMT_TYPE_CD asc,LKP.AGMT_LEGLY_BINDG_IND asc,LKP.AGMT_SRC_CD asc,LKP.AGMT_CUR_STS_CD asc,LKP.AGMT_CUR_STS_RSN_CD asc,LKP.AGMT_OBTND_CD asc,LKP.AGMT_SBTYPE_CD asc,LKP.AGMT_PRCSG_DTTM asc,LKP.ALT_AGMT_NAME asc,LKP.ASSET_LIABTY_CD asc,LKP.BAL_SHET_CD asc,LKP.STMT_CYCL_CD asc,LKP.STMT_ML_TYPE_CD asc,LKP.PRPOSL_ID asc,LKP.AGMT_OBJTV_TYPE_CD asc,LKP.FINCL_AGMT_SBTYPE_CD asc,LKP.MKT_RISK_TYPE_CD asc,LKP.ORIGNL_MATURTY_DT asc,LKP.RISK_EXPSR_MTGNT_SBTYPE_CD asc,LKP.BNK_TRD_BK_CD asc,LKP.PRCG_METH_SBTYPE_CD asc,LKP.FINCL_AGMT_TYPE_CD asc,LKP.DY_CNT_BSS_CD asc,LKP.FRST_PREM_DUE_DT asc,LKP.INSRNC_AGMT_SBTYPE_CD asc,LKP.INSRNC_AGMT_TYPE_CD asc,LKP.NTWK_SRVC_AGMT_TYPE_CD asc,LKP.FRMLTY_TYPE_CD asc,LKP.CNTRCT_TERM_NUM asc,LKP.RATE_RPRCG_CYCL_MTH_NUM asc,LKP.CMPND_INT_CYCL_MTH_NUM asc,LKP.MDTERM_INT_PMT_CYCL_MTH_NUM asc,LKP.PREV_MDTERM_INT_PMT_DT asc,LKP.NXT_MDTERM_INT_PMT_DT asc,LKP.PREV_INT_RATE_RVSD_DT asc,LKP.NXT_INT_RATE_RVSD_DT asc,LKP.PREV_REF_DT_INT_RATE asc,LKP.NXT_REF_DT_FOR_INT_RATE asc,LKP.MDTERM_CNCLTN_DT asc,LKP.STK_FLOW_CLAS_IN_MTH_IND asc,LKP.STK_FLOW_CLAS_IN_TERM_IND asc,LKP.LGCY_DSCNT_IND asc,LKP.AGMT_IDNTFTN_CD asc,LKP.TRMTN_TYPE_CD asc,LKP.INT_PMT_METH_CD asc,LKP.LBR_AGMT_DESC asc,LKP.GUARTD_IMPRSNS_CNT asc,LKP.COST_PER_IMPRSN_AMT asc,LKP.GUARTD_CLKTHRU_CNT asc,LKP.COST_PER_CLKTHRU_AMT asc,LKP.BUSN_PRTY_ID asc,LKP.PMT_PLN_TYPE_CD asc,LKP.INVC_STREM_TYPE_CD asc,LKP.MODL_CRTN_DTTM asc,LKP.CNTNUS_SRVC_DTTM asc,LKP.BILG_METH_TYPE_CD asc,LKP.SRC_SYS_CD asc,LKP.AGMT_EFF_DTTM asc,LKP.MODL_EFF_DTTM asc,LKP.PRCS_ID asc,LKP.MODL_ACTL_END_DTTM asc,LKP.TIER_TYPE_CD asc,LKP.EDW_STRT_DTTM asc,LKP.EDW_END_DTTM asc,LKP.VFYD_PLCY_IND asc,LKP.SRC_OF_BUSN_CD asc,LKP.NK_SRC_KEY asc,LKP.OVRD_COMS_TYPE_CD asc,LKP.LGCY_PLCY_IND asc,LKP.TRANS_STRT_DTTM asc) RNK
FROM
exp_pass_frm_src
LEFT JOIN (
SELECT	AGMT.AGMT_ID AS AGMT_ID, AGMT.HOST_AGMT_NUM AS HOST_AGMT_NUM,
		AGMT.AGMT_NAME AS AGMT_NAME, AGMT.AGMT_OPN_DTTM AS AGMT_OPN_DTTM,
		AGMT.AGMT_CLS_DTTM AS AGMT_CLS_DTTM, AGMT.AGMT_PLND_EXPN_DTTM AS AGMT_PLND_EXPN_DTTM,
		AGMT.AGMT_SIGND_DTTM AS AGMT_SIGND_DTTM, AGMT.AGMT_LEGLY_BINDG_IND AS AGMT_LEGLY_BINDG_IND,
		AGMT.AGMT_SRC_CD AS AGMT_SRC_CD, AGMT.AGMT_CUR_STS_CD AS AGMT_CUR_STS_CD,
		AGMT.AGMT_CUR_STS_RSN_CD AS AGMT_CUR_STS_RSN_CD, AGMT.AGMT_OBTND_CD AS AGMT_OBTND_CD,
		AGMT.AGMT_SBTYPE_CD AS AGMT_SBTYPE_CD, AGMT.AGMT_PRCSG_DTTM AS AGMT_PRCSG_DTTM,
		AGMT.ALT_AGMT_NAME AS ALT_AGMT_NAME, AGMT.ASSET_LIABTY_CD AS ASSET_LIABTY_CD,
		AGMT.BAL_SHET_CD AS BAL_SHET_CD, AGMT.STMT_CYCL_CD AS STMT_CYCL_CD,
		AGMT.STMT_ML_TYPE_CD AS STMT_ML_TYPE_CD, AGMT.PRPOSL_ID AS PRPOSL_ID,
		AGMT.AGMT_OBJTV_TYPE_CD AS AGMT_OBJTV_TYPE_CD, AGMT.FINCL_AGMT_SBTYPE_CD AS FINCL_AGMT_SBTYPE_CD,
		AGMT.MKT_RISK_TYPE_CD AS MKT_RISK_TYPE_CD, AGMT.ORIGNL_MATURTY_DT AS ORIGNL_MATURTY_DT,
		AGMT.RISK_EXPSR_MTGNT_SBTYPE_CD AS RISK_EXPSR_MTGNT_SBTYPE_CD,
		AGMT.BNK_TRD_BK_CD AS BNK_TRD_BK_CD, AGMT.PRCG_METH_SBTYPE_CD AS PRCG_METH_SBTYPE_CD,
		AGMT.FINCL_AGMT_TYPE_CD AS FINCL_AGMT_TYPE_CD, AGMT.DY_CNT_BSS_CD AS DY_CNT_BSS_CD,
		AGMT.FRST_PREM_DUE_DT AS FRST_PREM_DUE_DT, AGMT.INSRNC_AGMT_SBTYPE_CD AS INSRNC_AGMT_SBTYPE_CD,
		AGMT.INSRNC_AGMT_TYPE_CD AS INSRNC_AGMT_TYPE_CD, AGMT.NTWK_SRVC_AGMT_TYPE_CD AS NTWK_SRVC_AGMT_TYPE_CD,
		AGMT.FRMLTY_TYPE_CD AS FRMLTY_TYPE_CD, AGMT.CNTRCT_TERM_NUM AS CNTRCT_TERM_NUM,
		AGMT.RATE_RPRCG_CYCL_MTH_NUM AS RATE_RPRCG_CYCL_MTH_NUM, AGMT.CMPND_INT_CYCL_MTH_NUM AS CMPND_INT_CYCL_MTH_NUM,
		AGMT.MDTERM_INT_PMT_CYCL_MTH_NUM AS MDTERM_INT_PMT_CYCL_MTH_NUM,
		AGMT.PREV_MDTERM_INT_PMT_DT AS PREV_MDTERM_INT_PMT_DT, AGMT.NXT_MDTERM_INT_PMT_DT AS NXT_MDTERM_INT_PMT_DT,
		AGMT.PREV_INT_RATE_RVSD_DT AS PREV_INT_RATE_RVSD_DT, AGMT.NXT_INT_RATE_RVSD_DT AS NXT_INT_RATE_RVSD_DT,
		AGMT.PREV_REF_DT_INT_RATE AS PREV_REF_DT_INT_RATE, AGMT.NXT_REF_DT_FOR_INT_RATE AS NXT_REF_DT_FOR_INT_RATE,
		AGMT.MDTERM_CNCLTN_DT AS MDTERM_CNCLTN_DT, AGMT.STK_FLOW_CLAS_IN_MTH_IND AS STK_FLOW_CLAS_IN_MTH_IND,
		AGMT.STK_FLOW_CLAS_IN_TERM_IND AS STK_FLOW_CLAS_IN_TERM_IND,
		AGMT.LGCY_DSCNT_IND AS LGCY_DSCNT_IND, AGMT.AGMT_IDNTFTN_CD AS AGMT_IDNTFTN_CD,
		AGMT.TRMTN_TYPE_CD AS TRMTN_TYPE_CD, AGMT.INT_PMT_METH_CD AS INT_PMT_METH_CD,
		AGMT.LBR_AGMT_DESC AS LBR_AGMT_DESC, AGMT.GUARTD_IMPRSNS_CNT AS GUARTD_IMPRSNS_CNT,
		AGMT.COST_PER_IMPRSN_AMT AS COST_PER_IMPRSN_AMT, AGMT.GUARTD_CLKTHRU_CNT AS GUARTD_CLKTHRU_CNT,
		AGMT.COST_PER_CLKTHRU_AMT AS COST_PER_CLKTHRU_AMT, AGMT.BUSN_PRTY_ID AS BUSN_PRTY_ID,
		AGMT.PMT_PLN_TYPE_CD AS PMT_PLN_TYPE_CD, AGMT.INVC_STREM_TYPE_CD AS INVC_STREM_TYPE_CD,
		AGMT.MODL_CRTN_DTTM AS MODL_CRTN_DTTM, AGMT.CNTNUS_SRVC_DTTM AS CNTNUS_SRVC_DTTM,
		AGMT.BILG_METH_TYPE_CD AS BILG_METH_TYPE_CD, AGMT.SRC_SYS_CD AS SRC_SYS_CD,
		AGMT.AGMT_EFF_DTTM AS AGMT_EFF_DTTM, AGMT.MODL_EFF_DTTM AS MODL_EFF_DTTM,
		AGMT.PRCS_ID AS PRCS_ID, AGMT.MODL_ACTL_END_DTTM AS MODL_ACTL_END_DTTM,
		AGMT.TIER_TYPE_CD AS TIER_TYPE_CD, AGMT.EDW_STRT_DTTM AS EDW_STRT_DTTM,
		AGMT.EDW_END_DTTM AS EDW_END_DTTM, AGMT.VFYD_PLCY_IND AS VFYD_PLCY_IND,
		AGMT.SRC_OF_BUSN_CD AS SRC_OF_BUSN_CD, AGMT.OVRD_COMS_TYPE_CD AS OVRD_COMS_TYPE_CD,
		AGMT.LGCY_PLCY_IND AS LGCY_PLCY_IND, AGMT.TRANS_STRT_DTTM AS TRANS_STRT_DTTM,
		AGMT.NK_SRC_KEY AS NK_SRC_KEY, AGMT.AGMT_TYPE_CD AS AGMT_TYPE_CD 
FROM	db_t_prod_core.AGMT 
WHERE AGMT_TYPE_CD =''PPV''
QUALIFY	Row_Number() Over(
PARTITION BY AGMT.NK_SRC_KEY,AGMT.HOST_AGMT_NUM  
ORDER BY AGMT.EDW_END_DTTM DESC) = 1
) LKP ON LKP.NK_SRC_KEY = exp_pass_frm_src.PublicID AND LKP.AGMT_TYPE_CD = exp_pass_frm_src.IN_AGMT_TYPE_CD
QUALIFY RNK = 1
);


-- Component LKP_FEAT, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_FEAT AS
(
SELECT
LKP.FEAT_ID,
exp_pass_frm_src.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pass_frm_src.source_record_id ORDER BY LKP.FEAT_ID desc,LKP.FEAT_SBTYPE_CD desc,LKP.NK_SRC_KEY desc,LKP.FEAT_INSRNC_SBTYPE_CD desc,LKP.FEAT_CLASFCN_CD desc,LKP.FEAT_DESC desc,LKP.FEAT_NAME desc,LKP.COMN_FEAT_NAME desc,LKP.FEAT_LVL_SBTYPE_CNT desc,LKP.INSRNC_CVGE_TYPE_CD desc,LKP.INSRNC_LOB_TYPE_CD desc,LKP.PRCS_ID desc) RNK
FROM
exp_pass_frm_src
LEFT JOIN (
SELECT FEAT.FEAT_ID as FEAT_ID, FEAT.FEAT_INSRNC_SBTYPE_CD as FEAT_INSRNC_SBTYPE_CD, FEAT.FEAT_CLASFCN_CD as FEAT_CLASFCN_CD, FEAT.FEAT_DESC as FEAT_DESC, FEAT.FEAT_NAME as FEAT_NAME, FEAT.COMN_FEAT_NAME as COMN_FEAT_NAME, FEAT.FEAT_LVL_SBTYPE_CNT as FEAT_LVL_SBTYPE_CNT, FEAT.INSRNC_CVGE_TYPE_CD as INSRNC_CVGE_TYPE_CD, FEAT.INSRNC_LOB_TYPE_CD as INSRNC_LOB_TYPE_CD, FEAT.PRCS_ID as PRCS_ID, FEAT.FEAT_SBTYPE_CD as FEAT_SBTYPE_CD, FEAT.NK_SRC_KEY as NK_SRC_KEY FROM db_t_prod_core.FEAT
QUALIFY ROW_NUMBER () OVER (PARTITION BY NK_SRC_KEY,FEAT_SBTYPE_CD  ORDER BY edw_end_dttm DESC)=1
) LKP ON LKP.FEAT_SBTYPE_CD = :in_FEAT_SBTYPE_CD AND LKP.NK_SRC_KEY = exp_pass_frm_src.Feat_NKsrckey
QUALIFY RNK = 1
);


-- Component LKP_AGMT_FEAT_PERIL_MTRC, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_AGMT_FEAT_PERIL_MTRC AS
(
SELECT
LKP.AGMT_ID,
LKP.FEAT_ID,
LKP.AGMT_FEAT_STRT_DTTM,
LKP.RTG_PERIL_TYPE_CD,
LKP.PLCY_SECTN_TYPE_CD,
LKP.INSRNC_MTRC_TYPE_CD,
LKP.AGMT_FEAT_PERIL_MTRC_AMT,
LKP.EDW_STRT_DTTM,
exp_pass_frm_src.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pass_frm_src.source_record_id ORDER BY LKP.AGMT_ID asc,LKP.FEAT_ID asc,LKP.AGMT_FEAT_STRT_DTTM asc,LKP.RTG_PERIL_TYPE_CD asc,LKP.PLCY_SECTN_TYPE_CD asc,LKP.INSRNC_MTRC_TYPE_CD asc,LKP.AGMT_FEAT_PERIL_MTRC_AMT asc,LKP.EDW_STRT_DTTM asc) RNK
FROM
exp_pass_frm_src
INNER JOIN LKP_AGMT_PPV ON exp_pass_frm_src.source_record_id = LKP_AGMT_PPV.source_record_id
INNER JOIN LKP_FEAT ON LKP_AGMT_PPV.source_record_id = LKP_FEAT.source_record_id
LEFT JOIN (
SELECT AGMT_FEAT_PERIL_MTRC.AGMT_FEAT_STRT_DTTM as AGMT_FEAT_STRT_DTTM, AGMT_FEAT_PERIL_MTRC.PLCY_SECTN_TYPE_CD as PLCY_SECTN_TYPE_CD, AGMT_FEAT_PERIL_MTRC.AGMT_FEAT_PERIL_MTRC_AMT as AGMT_FEAT_PERIL_MTRC_AMT, AGMT_FEAT_PERIL_MTRC.EDW_STRT_DTTM as EDW_STRT_DTTM, AGMT_FEAT_PERIL_MTRC.FEAT_ID as FEAT_ID, AGMT_FEAT_PERIL_MTRC.AGMT_ID as AGMT_ID, AGMT_FEAT_PERIL_MTRC.RTG_PERIL_TYPE_CD as RTG_PERIL_TYPE_CD, AGMT_FEAT_PERIL_MTRC.INSRNC_MTRC_TYPE_CD as INSRNC_MTRC_TYPE_CD FROM db_t_prod_core.AGMT_FEAT_PERIL_MTRC QUALIFY	ROW_NUMBER() OVER(
PARTITION BY   INSRNC_MTRC_TYPE_CD,
		RTG_PERIL_TYPE_CD,FEAT_ID,AGMT_ID 
ORDER BY AGMT_FEAT_PERIL_MTRC.EDW_END_DTTM DESC) = 1
) LKP ON LKP.FEAT_ID = LKP_FEAT.FEAT_ID AND LKP.AGMT_ID = LKP_AGMT_PPV.AGMT_ID AND LKP.RTG_PERIL_TYPE_CD = exp_pass_frm_src.in_RTG_PERIL_TYPE_CD AND LKP.INSRNC_MTRC_TYPE_CD = exp_pass_frm_src.o_Inscrn_Mtrc_Type_CD
QUALIFY ROW_NUMBER() OVER(PARTITION BY exp_pass_frm_src.source_record_id ORDER BY LKP.AGMT_ID asc,LKP.FEAT_ID asc,LKP.AGMT_FEAT_STRT_DTTM asc,LKP.RTG_PERIL_TYPE_CD asc,LKP.PLCY_SECTN_TYPE_CD asc,LKP.INSRNC_MTRC_TYPE_CD asc,LKP.AGMT_FEAT_PERIL_MTRC_AMT asc,LKP.EDW_STRT_DTTM asc) 
= 1
);


-- Component LKP_TERADATA_ETL_REF_XLAT_CURY_CD, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_TERADATA_ETL_REF_XLAT_CURY_CD AS
(
SELECT
LKP.TGT_IDNTFTN_VAL,
exp_pass_frm_src.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pass_frm_src.source_record_id ORDER BY LKP.TGT_IDNTFTN_VAL desc,LKP.SRC_IDNTFTN_VAL desc) RNK
FROM
exp_pass_frm_src
LEFT JOIN (
SELECT 
	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL
	,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 
FROM 
	DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT
WHERE 
	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM= ''ISO_CURY_TYPE''
             AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_NM=''derived''
			AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''
) LKP ON LKP.SRC_IDNTFTN_VAL = exp_pass_frm_src.cury_cd
QUALIFY ROW_NUMBER() OVER(PARTITION BY exp_pass_frm_src.source_record_id ORDER BY LKP.TGT_IDNTFTN_VAL desc,LKP.SRC_IDNTFTN_VAL desc) 
= 1
);


-- Component exp_ins_upd, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ins_upd AS
(
SELECT
LKP_AGMT_FEAT_PERIL_MTRC.AGMT_ID as lkp_AGMT_ID,
LKP_AGMT_FEAT_PERIL_MTRC.EDW_STRT_DTTM as lkp_EDW_STRT_DTTM,
LKP_AGMT_FEAT_PERIL_MTRC.FEAT_ID as lkp_FEAT_ID,
LKP_AGMT_FEAT_PERIL_MTRC.RTG_PERIL_TYPE_CD as lkp_RTG_PERIL_TYPE_CD,
LKP_AGMT_FEAT_PERIL_MTRC.INSRNC_MTRC_TYPE_CD as lkp_INSRNC_MTRC_TYPE_CD,
LKP_AGMT_FEAT_PERIL_MTRC.AGMT_FEAT_STRT_DTTM as lkp_AGMT_FEAT_STRT_DTTM,
MD5 ( LKP_AGMT_FEAT_PERIL_MTRC.AGMT_FEAT_PERIL_MTRC_AMT || TO_CHAR ( LKP_AGMT_FEAT_PERIL_MTRC.AGMT_FEAT_STRT_DTTM ) ) as lkp_checksum,
LKP_FEAT.FEAT_ID as in_FEAT_ID,
LKP_AGMT_PPV.AGMT_ID as in_AGMT_ID,
exp_pass_frm_src.o_Inscrn_Mtrc_Type_CD as in_Inscrn_Mtrc_Type_CD,
exp_pass_frm_src.in_RTG_PERIL_TYPE_CD as in_RTG_PERIL_TYPE_CD,
exp_pass_frm_src.ASSET_CNTRCT_ROLE_SBTYPE_CD as in_ASSET_CNTRCT_ROLE_SBTYPE_CD,
exp_pass_frm_src.Earnings_as_of_dt1 as Earnings_as_of_dt1,
exp_pass_frm_src.Section_type1 as Section_type,
exp_pass_frm_src.Earnings_as_of_dt as Earnings_as_of_dt,
exp_pass_frm_src.Amount as Amount,
MD5 ( exp_pass_frm_src.Amount || TO_CHAR ( exp_pass_frm_src.Earnings_as_of_dt ) ) as in_checksum,
exp_pass_frm_src.TRANS_STRT_DTTM1 as TRANS_STRT_DTTM,
exp_pass_frm_src.TRANS_END_DTTM1 as TRANS_END_DTTM,
CASE WHEN lkp_checksum IS NULL THEN ''I'' ELSE ( CASE WHEN lkp_checksum <> in_checksum THEN ''U'' ELSE ''R'' END ) END as ins_upd_flag,
CURRENT_TIMESTAMP as EDW_STRT_DTTM,
TO_DATE ( ''12/31/9999 23:59:59.999999'' , ''MM/DD/YYYY HH24:MI:SS.FF6'' ) as EDW_END_DTTM,
to_date ( ''1900-01-01'' , ''yyyy-mm-dd'' ) as AGMT_ASSET_STRT_DTTM,
:PRCS_ID as PRCS_ID,
exp_pass_frm_src.o_Asset_Classification_code as o_Asset_Classification_code,
LKP_TERADATA_ETL_REF_XLAT_CURY_CD.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL,
LKP_AGMT_PPV.AGMT_TYPE_CD as AGMT_TYPE_CD,
''UNK'' as STS_CD,
exp_pass_frm_src.source_record_id
FROM
exp_pass_frm_src
INNER JOIN LKP_AGMT_PPV ON exp_pass_frm_src.source_record_id = LKP_AGMT_PPV.source_record_id
INNER JOIN LKP_FEAT ON LKP_AGMT_PPV.source_record_id = LKP_FEAT.source_record_id
INNER JOIN LKP_AGMT_FEAT_PERIL_MTRC ON LKP_FEAT.source_record_id = LKP_AGMT_FEAT_PERIL_MTRC.source_record_id
INNER JOIN LKP_TERADATA_ETL_REF_XLAT_CURY_CD ON LKP_AGMT_FEAT_PERIL_MTRC.source_record_id = LKP_TERADATA_ETL_REF_XLAT_CURY_CD.source_record_id
);


-- Component RTRTRANS_INSERT, Type ROUTER Output Group INSERT
create or replace temporary table RTRTRANS_INSERT as
SELECT
exp_ins_upd.lkp_AGMT_ID as lkp_AGMT_ID,
exp_ins_upd.lkp_FEAT_ID as lkp_FEAT_ID,
exp_ins_upd.lkp_RTG_PERIL_TYPE_CD as lkp_RTG_PERIL_TYPE_CD,
exp_ins_upd.lkp_INSRNC_MTRC_TYPE_CD as lkp_INSRNC_MTRC_TYPE_CD,
exp_ins_upd.lkp_EDW_STRT_DTTM as lkp_EDW_STRT_DTTM,
exp_ins_upd.in_FEAT_ID as in_FEAT_ID,
exp_ins_upd.in_AGMT_ID as in_AGMT_ID,
exp_ins_upd.in_Inscrn_Mtrc_Type_CD as in_Inscrn_Mtrc_Type_CD,
exp_ins_upd.in_RTG_PERIL_TYPE_CD as in_RTG_PERIL_TYPE_CD,
exp_ins_upd.in_ASSET_CNTRCT_ROLE_SBTYPE_CD as in_ASSET_CNTRCT_ROLE_SBTYPE_CD,
exp_ins_upd.Earnings_as_of_dt1 as Earnings_as_of_dt4,
exp_ins_upd.Section_type as Section_type,
exp_ins_upd.Earnings_as_of_dt as Earnings_as_of_dt,
exp_ins_upd.Amount as Amount,
exp_ins_upd.TRANS_STRT_DTTM as TRANS_STRT_DTTM,
exp_ins_upd.TRANS_END_DTTM as TRANS_END_DTTM,
exp_ins_upd.ins_upd_flag as ins_upd_flag,
exp_ins_upd.EDW_STRT_DTTM as EDW_STRT_DTTM,
exp_ins_upd.EDW_END_DTTM as EDW_END_DTTM,
exp_ins_upd.PRCS_ID as PRCS_ID,
exp_ins_upd.lkp_AGMT_FEAT_STRT_DTTM as lkp_AGMT_FEAT_STRT_DTTM,
exp_ins_upd.AGMT_ASSET_STRT_DTTM as AGMT_ASSET_STRT_DTTM,
exp_ins_upd.o_Asset_Classification_code as o_Asset_Classification_code,
exp_ins_upd.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL,
exp_ins_upd.AGMT_TYPE_CD as AGMT_TYPE_CD,
exp_ins_upd.STS_CD as STS_CD,
exp_ins_upd.source_record_id
FROM
exp_ins_upd
WHERE exp_ins_upd.ins_upd_flag = ''I'';


-- Component RTRTRANS_UPDATE, Type ROUTER Output Group UPDATE
create or replace temporary table RTRTRANS_UPDATE as
SELECT
exp_ins_upd.lkp_AGMT_ID as lkp_AGMT_ID,
exp_ins_upd.lkp_FEAT_ID as lkp_FEAT_ID,
exp_ins_upd.lkp_RTG_PERIL_TYPE_CD as lkp_RTG_PERIL_TYPE_CD,
exp_ins_upd.lkp_INSRNC_MTRC_TYPE_CD as lkp_INSRNC_MTRC_TYPE_CD,
exp_ins_upd.lkp_EDW_STRT_DTTM as lkp_EDW_STRT_DTTM,
exp_ins_upd.in_FEAT_ID as in_FEAT_ID,
exp_ins_upd.in_AGMT_ID as in_AGMT_ID,
exp_ins_upd.in_Inscrn_Mtrc_Type_CD as in_Inscrn_Mtrc_Type_CD,
exp_ins_upd.in_RTG_PERIL_TYPE_CD as in_RTG_PERIL_TYPE_CD,
exp_ins_upd.in_ASSET_CNTRCT_ROLE_SBTYPE_CD as in_ASSET_CNTRCT_ROLE_SBTYPE_CD,
exp_ins_upd.Earnings_as_of_dt1 as Earnings_as_of_dt4,
exp_ins_upd.Section_type as Section_type,
exp_ins_upd.Earnings_as_of_dt as Earnings_as_of_dt,
exp_ins_upd.Amount as Amount,
exp_ins_upd.TRANS_STRT_DTTM as TRANS_STRT_DTTM,
exp_ins_upd.TRANS_END_DTTM as TRANS_END_DTTM,
exp_ins_upd.ins_upd_flag as ins_upd_flag,
exp_ins_upd.EDW_STRT_DTTM as EDW_STRT_DTTM,
exp_ins_upd.EDW_END_DTTM as EDW_END_DTTM,
exp_ins_upd.PRCS_ID as PRCS_ID,
exp_ins_upd.lkp_AGMT_FEAT_STRT_DTTM as lkp_AGMT_FEAT_STRT_DTTM,
exp_ins_upd.AGMT_ASSET_STRT_DTTM as AGMT_ASSET_STRT_DTTM,
exp_ins_upd.o_Asset_Classification_code as o_Asset_Classification_code,
exp_ins_upd.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL,
exp_ins_upd.AGMT_TYPE_CD as AGMT_TYPE_CD,
exp_ins_upd.STS_CD as STS_CD,
exp_ins_upd.source_record_id
FROM
exp_ins_upd
WHERE exp_ins_upd.ins_upd_flag = ''U'';


-- Component exp_upd, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_upd AS
(
SELECT
RTRTRANS_UPDATE.lkp_AGMT_ID as lkp_AGMT_ID3,
RTRTRANS_UPDATE.lkp_FEAT_ID as lkp_FEAT_ID3,
RTRTRANS_UPDATE.lkp_RTG_PERIL_TYPE_CD as lkp_RTG_PERIL_TYPE_CD3,
RTRTRANS_UPDATE.lkp_INSRNC_MTRC_TYPE_CD as lkp_INSRNC_MTRC_TYPE_CD3,
RTRTRANS_UPDATE.lkp_EDW_STRT_DTTM as lkp_EDW_STRT_DTTM3,
dateadd ( second,-1, RTRTRANS_UPDATE.EDW_STRT_DTTM ) as EDW_END_DTTM,
dateadd ( second,-1, RTRTRANS_UPDATE.TRANS_STRT_DTTM ) as TRANS_END_DTTM,
NULL as lkp_AAF_PERIL_MTRC_DTTM,
RTRTRANS_UPDATE.lkp_AGMT_FEAT_STRT_DTTM as lkp_AGMT_FEAT_STRT_DTTM,
RTRTRANS_UPDATE.source_record_id
FROM
RTRTRANS_UPDATE
);


-- Component AGMT_FEAT_PERIL_MTRC_ins_new, Type TARGET 
INSERT INTO DB_T_PROD_CORE.AGMT_FEAT_PERIL_MTRC
(
AGMT_ID,
FEAT_ID,
AGMT_FEAT_ROLE_CD,
AGMT_FEAT_STRT_DTTM,
RTG_PERIL_TYPE_CD,
AGMT_FEAT_PERIL_STRT_DTTM,
PLCY_SECTN_TYPE_CD,
INSRNC_MTRC_TYPE_CD,
AGMT_FEAT_PERIL_MTRC_STRT_DTTM,
AGMT_FEAT_PERIL_MTRC_END_DTTM,
AGMT_FEAT_PERIL_MTRC_AMT,
CURY_CD,
PRCS_ID,
EDW_STRT_DTTM,
EDW_END_DTTM,
TRANS_STRT_DTTM
)
SELECT
RTRTRANS_INSERT.in_AGMT_ID as AGMT_ID,
RTRTRANS_INSERT.in_FEAT_ID as FEAT_ID,
RTRTRANS_INSERT.AGMT_TYPE_CD as AGMT_FEAT_ROLE_CD,
RTRTRANS_INSERT.Earnings_as_of_dt4 as AGMT_FEAT_STRT_DTTM,
RTRTRANS_INSERT.in_RTG_PERIL_TYPE_CD as RTG_PERIL_TYPE_CD,
RTRTRANS_INSERT.AGMT_ASSET_STRT_DTTM as AGMT_FEAT_PERIL_STRT_DTTM,
RTRTRANS_INSERT.STS_CD as PLCY_SECTN_TYPE_CD,
RTRTRANS_INSERT.in_Inscrn_Mtrc_Type_CD as INSRNC_MTRC_TYPE_CD,
RTRTRANS_INSERT.AGMT_ASSET_STRT_DTTM as AGMT_FEAT_PERIL_MTRC_STRT_DTTM,
RTRTRANS_INSERT.EDW_END_DTTM as AGMT_FEAT_PERIL_MTRC_END_DTTM,
RTRTRANS_INSERT.Amount as AGMT_FEAT_PERIL_MTRC_AMT,
RTRTRANS_INSERT.TGT_IDNTFTN_VAL as CURY_CD,
RTRTRANS_INSERT.PRCS_ID as PRCS_ID,
RTRTRANS_INSERT.EDW_STRT_DTTM as EDW_STRT_DTTM,
RTRTRANS_INSERT.EDW_END_DTTM as EDW_END_DTTM,
RTRTRANS_INSERT.TRANS_STRT_DTTM as TRANS_STRT_DTTM
FROM
RTRTRANS_INSERT;


-- Component exp_ins, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ins AS
(
SELECT
RTRTRANS_UPDATE.in_AGMT_ID as AGMT_ID,
RTRTRANS_UPDATE.in_FEAT_ID as FEAT_ID,
RTRTRANS_UPDATE.in_ASSET_CNTRCT_ROLE_SBTYPE_CD as ASSET_CNTRCT_ROLE_SBTYPE_CD,
RTRTRANS_UPDATE.Earnings_as_of_dt4 as Earnings_as_of_dt,
RTRTRANS_UPDATE.in_RTG_PERIL_TYPE_CD as RTG_PERIL_TYPE_CD,
RTRTRANS_UPDATE.Earnings_as_of_dt4 as Earnings_as_of_dt1,
RTRTRANS_UPDATE.Earnings_as_of_dt4 as Earnings_as_of_dt2,
RTRTRANS_UPDATE.Section_type as AGMT_SECTN_CD,
RTRTRANS_UPDATE.in_Inscrn_Mtrc_Type_CD as INSRNC_MTRC_TYPE_CD,
RTRTRANS_UPDATE.Earnings_as_of_dt as Earnings_as_of_dt3,
RTRTRANS_UPDATE.Amount as AGMT_ASSET_FEAT_PERIL_AMT,
RTRTRANS_UPDATE.PRCS_ID as PRCS_ID,
RTRTRANS_UPDATE.EDW_STRT_DTTM as EDW_STRT_DTTM,
RTRTRANS_UPDATE.EDW_END_DTTM as EDW_END_DTTM,
RTRTRANS_UPDATE.TRANS_STRT_DTTM as TRANS_STRT_DTTM,
RTRTRANS_UPDATE.TRANS_END_DTTM as TRANS_END_DTTM,
RTRTRANS_UPDATE.AGMT_ASSET_STRT_DTTM as AGMT_ASSET_STRT_DTTM3,
RTRTRANS_UPDATE.AGMT_TYPE_CD as o_Asset_Classification_code3,
RTRTRANS_UPDATE.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL3,
''UNK'' as PLCY_SECTN_TYPE_CD,
RTRTRANS_UPDATE.source_record_id
FROM
RTRTRANS_UPDATE
);


-- Component upd_ins, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_ins AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
exp_ins.AGMT_ID as AGMT_ID,
exp_ins.FEAT_ID as FEAT_ID,
exp_ins.ASSET_CNTRCT_ROLE_SBTYPE_CD as ASSET_CNTRCT_ROLE_SBTYPE_CD,
exp_ins.Earnings_as_of_dt as Earnings_as_of_dt,
exp_ins.RTG_PERIL_TYPE_CD as RTG_PERIL_TYPE_CD,
exp_ins.Earnings_as_of_dt1 as Earnings_as_of_dt1,
exp_ins.Earnings_as_of_dt2 as Earnings_as_of_dt2,
exp_ins.AGMT_SECTN_CD as AGMT_SECTN_CD,
exp_ins.INSRNC_MTRC_TYPE_CD as INSRNC_MTRC_TYPE_CD,
exp_ins.Earnings_as_of_dt3 as Earnings_as_of_dt3,
exp_ins.AGMT_ASSET_FEAT_PERIL_AMT as AGMT_ASSET_FEAT_PERIL_AMT,
exp_ins.PRCS_ID as PRCS_ID,
exp_ins.EDW_STRT_DTTM as EDW_STRT_DTTM,
exp_ins.EDW_END_DTTM as EDW_END_DTTM,
exp_ins.TRANS_STRT_DTTM as TRANS_STRT_DTTM,
exp_ins.TRANS_END_DTTM as TRANS_END_DTTM,
exp_ins.AGMT_ASSET_STRT_DTTM3 as AGMT_ASSET_STRT_DTTM3,
exp_ins.o_Asset_Classification_code3 as o_Asset_Classification_code3,
exp_ins.TGT_IDNTFTN_VAL3 as TGT_IDNTFTN_VAL3,
exp_ins.PLCY_SECTN_TYPE_CD as PLCY_SECTN_TYPE_CD,
0 as UPDATE_STRATEGY_ACTION,
exp_ins.source_record_id as source_record_id
FROM
exp_ins
);


-- Component AGMT_FEAT_PERIL_MTRC_upd_ins, Type TARGET 
INSERT INTO DB_T_PROD_CORE.AGMT_FEAT_PERIL_MTRC
(
AGMT_ID,
FEAT_ID,
AGMT_FEAT_ROLE_CD,
AGMT_FEAT_STRT_DTTM,
RTG_PERIL_TYPE_CD,
AGMT_FEAT_PERIL_STRT_DTTM,
PLCY_SECTN_TYPE_CD,
INSRNC_MTRC_TYPE_CD,
AGMT_FEAT_PERIL_MTRC_STRT_DTTM,
AGMT_FEAT_PERIL_MTRC_END_DTTM,
AGMT_FEAT_PERIL_MTRC_AMT,
CURY_CD,
PRCS_ID,
EDW_STRT_DTTM,
EDW_END_DTTM,
TRANS_STRT_DTTM
)
SELECT
upd_ins.AGMT_ID as AGMT_ID,
upd_ins.FEAT_ID as FEAT_ID,
upd_ins.o_Asset_Classification_code3 as AGMT_FEAT_ROLE_CD,
upd_ins.Earnings_as_of_dt1 as AGMT_FEAT_STRT_DTTM,
upd_ins.RTG_PERIL_TYPE_CD as RTG_PERIL_TYPE_CD,
upd_ins.AGMT_ASSET_STRT_DTTM3 as AGMT_FEAT_PERIL_STRT_DTTM,
upd_ins.PLCY_SECTN_TYPE_CD as PLCY_SECTN_TYPE_CD,
upd_ins.INSRNC_MTRC_TYPE_CD as INSRNC_MTRC_TYPE_CD,
upd_ins.AGMT_ASSET_STRT_DTTM3 as AGMT_FEAT_PERIL_MTRC_STRT_DTTM,
upd_ins.EDW_END_DTTM as AGMT_FEAT_PERIL_MTRC_END_DTTM,
upd_ins.AGMT_ASSET_FEAT_PERIL_AMT as AGMT_FEAT_PERIL_MTRC_AMT,
upd_ins.TGT_IDNTFTN_VAL3 as CURY_CD,
upd_ins.PRCS_ID as PRCS_ID,
upd_ins.EDW_STRT_DTTM as EDW_STRT_DTTM,
upd_ins.EDW_END_DTTM as EDW_END_DTTM,
upd_ins.TRANS_STRT_DTTM as TRANS_STRT_DTTM
FROM
upd_ins;


-- Component update_upd, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE update_upd AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
exp_upd.lkp_AGMT_ID3 as lkp_AGMT_ID3,
exp_upd.lkp_FEAT_ID3 as lkp_FEAT_ID3,
exp_upd.lkp_RTG_PERIL_TYPE_CD3 as lkp_RTG_PERIL_TYPE_CD3,
exp_upd.lkp_INSRNC_MTRC_TYPE_CD3 as lkp_INSRNC_MTRC_TYPE_CD3,
exp_upd.lkp_EDW_STRT_DTTM3 as lkp_EDW_STRT_DTTM3,
exp_upd.EDW_END_DTTM as EDW_END_DTTM,
exp_upd.TRANS_END_DTTM as TRANS_END_DTTM,
exp_upd.lkp_AAF_PERIL_MTRC_DTTM as lkp_AAF_PERIL_MTRC_DTTM,
exp_upd.lkp_AGMT_FEAT_STRT_DTTM as lkp_AGMT_FEAT_STRT_DTTM,
1 as UPDATE_STRATEGY_ACTION,
exp_upd.source_record_id as source_record_id
FROM
exp_upd
);


-- Component AGMT_FEAT_PERIL_MTRC_upd, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_PROD_CORE.AGMT_FEAT_PERIL_MTRC
USING update_upd ON (UPDATE_STRATEGY_ACTION = 1 AND AGMT_FEAT_PERIL_MTRC.AGMT_ID = update_upd.lkp_AGMT_ID3 AND AGMT_FEAT_PERIL_MTRC.FEAT_ID = update_upd.lkp_FEAT_ID3 AND AGMT_FEAT_PERIL_MTRC.RTG_PERIL_TYPE_CD = update_upd.lkp_RTG_PERIL_TYPE_CD3 AND AGMT_FEAT_PERIL_MTRC.INSRNC_MTRC_TYPE_CD = update_upd.lkp_INSRNC_MTRC_TYPE_CD3 AND AGMT_FEAT_PERIL_MTRC.EDW_STRT_DTTM = update_upd.lkp_EDW_STRT_DTTM3)
WHEN MATCHED THEN UPDATE
SET
EDW_END_DTTM = update_upd.EDW_END_DTTM,
TRANS_END_DTTM = update_upd.TRANS_END_DTTM
;


END; ';