-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_EOM_PARAMETER_FILES("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_ECTL_MISPREM_HEADER, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ECTL_MISPREM_HEADER AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as DAILY_FEED_IND,
$2 as TO_DATE,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT DAILY_FEED_IND, MAX(TO_DATE) FROM DB_T_CTRL_PROD.ECTL_MISPREM_HEADER   

GROUP BY DAILY_FEED_IND
) SRC
)
);


-- Component exp_MOVE_DATA, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_MOVE_DATA AS
(
SELECT
SQ_ECTL_MISPREM_HEADER.DAILY_FEED_IND as DAILY_FEED_IND,
SQ_ECTL_MISPREM_HEADER.TO_DATE as TO_DATE,
SQ_ECTL_MISPREM_HEADER.source_record_id
FROM
SQ_ECTL_MISPREM_HEADER
);


-- Component LEGACY_EOM_PARAMETER_FILES, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE LEGACY_EOM_PARAMETER_FILES AS
(
SELECT
exp_MOVE_DATA.DAILY_FEED_IND as out_FEED_IND,
exp_MOVE_DATA.TO_DATE as out_DATE
FROM
exp_MOVE_DATA
);


-- Component LEGACY_EOM_PARAMETER_FILES, Type EXPORT_DATA Exporting data

;


END; ';