-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_MEMBER_MASTER2025("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE PMMAPPINGNAME varchar;
BEGIN 

PMMAPPINGNAME:='' '';  

-- PIPELINE START FOR 1

-- Component SQ_Shortcut_to_STG_FED_MSTR_DELTA, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_STG_FED_MSTR_DELTA AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMBER_NBR,
$2 as PAID_TO_DATE,
$3 as TX_CD,
$4 as FEED_DT,
$5 as FEED_IND,
$6 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT STG_FED_MSTR_DELTA.MEMBER_NBR, 
STG_FED_MSTR_DELTA.PAID_TO_DATE,
STG_FED_MSTR_DELTA.TX_CD, 
STG_FED_MSTR_TRG.FEED_DT,
STG_FED_MSTR_TRG.FEED_IND
FROM
DB_T_STAG_PROD.STG_FED_MSTR_DELTA, DB_T_STAG_PROD.STG_FED_MSTR_TRG
WHERE (TX_CD = ''NEW'' or TX_CD = ''DEL'') /* and member_nbr in (1772280) */
) SRC
)
);


-- Component LKP_GETMEMNUM, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_GETMEMNUM AS
(
SELECT
LKP.MEMBER_SEQ,
LKP.DATE_REQUESTED,
LKP.TIME_REQUESTED,
LKP.AGENT_NBR,
LKP.USER_ID,
LKP.SC_NUMBER,
SQ_Shortcut_to_STG_FED_MSTR_DELTA.source_record_id,
ROW_NUMBER() OVER(PARTITION BY SQ_Shortcut_to_STG_FED_MSTR_DELTA.source_record_id ORDER BY LKP.MEMBERNUM asc,LKP.MEMBER_SEQ asc,LKP.DATE_REQUESTED asc,LKP.TIME_REQUESTED asc,LKP.AGENT_NBR asc,LKP.USER_ID asc,LKP.SC_NUMBER asc) RNK
FROM
SQ_Shortcut_to_STG_FED_MSTR_DELTA
LEFT JOIN (
SELECT MAX(MEMBER_SEQ) AS MEMBER_SEQ, 
                   DATE_REQUESTED AS DATE_REQUESTED, 
                   TIME_REQUESTED AS TIME_REQUESTED, 
                   AGENT_NBR AS AGENT_NBR, 
                   USER_ID AS USER_ID, 
                   SC_NUMBER AS SC_NUMBER, 
                   MEMBERNUM AS MEMBERNUM 
                   FROM POLDATA.GETMEMBERNUM
                   WHERE 
                      STATUS = ''ACTIVE''         
/* AND SC_NUMBER > 0  */
                      group by MEMBERNUM,
                      DATE_REQUESTED, 
                      TIME_REQUESTED, 
                      AGENT_NBR, 
                      USER_ID, 
                      SC_NUMBER
) LKP ON LKP.MEMBERNUM = SQ_Shortcut_to_STG_FED_MSTR_DELTA.MEMBER_NBR
QUALIFY RNK = 1
);


-- Component exp_Batch_Prgm, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Batch_Prgm AS
(
SELECT
SQ_Shortcut_to_STG_FED_MSTR_DELTA.MEMBER_NBR as MEMBER_NBR,
4 as out_PROJ_ID,
''Y'' as out_BATCH_IND,
PMMappingName as out_PRGM_NM,
''MEMBER_MASTER'' as out_TABLE_NM,
SQ_Shortcut_to_STG_FED_MSTR_DELTA.source_record_id
FROM
SQ_Shortcut_to_STG_FED_MSTR_DELTA
);


-- Component exp_EFF_DT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_EFF_DT AS
(
SELECT
substr ( SQ_Shortcut_to_STG_FED_MSTR_DELTA.PAID_TO_DATE , 1 , 4 ) as YYYY_PDTODT,
substr ( SQ_Shortcut_to_STG_FED_MSTR_DELTA.PAID_TO_DATE , 5 , 2 ) as MM_PDTODT,
substr ( SQ_Shortcut_to_STG_FED_MSTR_DELTA.PAID_TO_DATE , 7 , 2 ) as DD_PDTODT,
lpad ( to_char ( DATE_PART(''YYYY'', TO_TIMESTAMP(SQ_Shortcut_to_STG_FED_MSTR_DELTA.FEED_DT)) ) , 4 , ''0'' ) as YYYY_TRG,
lpad ( to_char ( DATE_PART(''MM'', TO_TIMESTAMP(SQ_Shortcut_to_STG_FED_MSTR_DELTA.FEED_DT)) ) , 2 , ''0'' ) as MM_TRG,
lpad ( to_char ( DATE_PART(''DD'', TO_TIMESTAMP(SQ_Shortcut_to_STG_FED_MSTR_DELTA.FEED_DT)) ) , 2 , ''0'' ) as DD_TRG,
YYYY_TRG as out_EFF_DT_YYYY,
CASE WHEN SQ_Shortcut_to_STG_FED_MSTR_DELTA.FEED_IND = ''X'' and SQ_Shortcut_to_STG_FED_MSTR_DELTA.TX_CD = ''NEW'' and MM_PDTODT IS NOT NULL and MM_PDTODT != ''00'' THEN MM_PDTODT ELSE MM_TRG END as out_EFF_DT_MM,
CASE WHEN SQ_Shortcut_to_STG_FED_MSTR_DELTA.TX_CD = ''NEW'' and ( SQ_Shortcut_to_STG_FED_MSTR_DELTA.FEED_IND = ''X'' or SQ_Shortcut_to_STG_FED_MSTR_DELTA.FEED_IND = ''M'' ) and DD_PDTODT IS NOT NULL and DD_PDTODT != ''00'' THEN DD_PDTODT ELSE DD_TRG END as out_EFF_DT_DD,
SQ_Shortcut_to_STG_FED_MSTR_DELTA.source_record_id
FROM
SQ_Shortcut_to_STG_FED_MSTR_DELTA
);


-- Component m_lkp_Control_Tables, Type MAPPLET 
--MAPPLET NOT REGISTERED: m_lkp_Control_Tables, mapplet instance m_lkp_Control_Tables;


-- Component LKP_MEMBER_MSTR, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_MEMBER_MSTR AS
(
SELECT
LKP.MEMB_SKEY,
SQ_Shortcut_to_STG_FED_MSTR_DELTA.source_record_id,
ROW_NUMBER() OVER(PARTITION BY SQ_Shortcut_to_STG_FED_MSTR_DELTA.source_record_id ORDER BY LKP.MEMB_SKEY asc,LKP.MEMB_NUM asc,LKP.MEMB_EFF_DT asc,LKP.MEMB_EXP_DT asc,LKP.MEMB_EMAIL asc,LKP.MEMB_PHONE asc,LKP.MEMB_ORIG_SALES_AGENT_NBR asc,LKP.MEMB_ORIG_SALES_AGENT_SC_NBR asc,LKP.MEMB_ORIG_SALES_USER_ID asc,LKP.MEMB_SEQ asc,LKP.MEMB_DATE_REQUESTED asc,LKP.MEMB_TIME_REQUESTED asc,LKP.ECTL_INS_BATCH_ID asc,LKP.ECTL_UPD_BATCH_ID asc,LKP.ECTL_INS_PRGM_ID asc,LKP.ECTL_UPD_PRGM_ID asc) RNK
FROM
SQ_Shortcut_to_STG_FED_MSTR_DELTA
LEFT JOIN (
SELECT MEMBER_MSTR.MEMB_SKEY as MEMB_SKEY, 
MEMBER_MSTR.MEMB_NUM as MEMB_NUM, 
MEMBER_MSTR.MEMB_EFF_DT as MEMB_EFF_DT, 
MEMBER_MSTR.MEMB_EXP_DT as MEMB_EXP_DT, 
MEMBER_MSTR.MEMB_EMAIL as MEMB_EMAIL, 
MEMBER_MSTR.MEMB_PHONE as MEMB_PHONE, 
MEMBER_MSTR.ECTL_INS_BATCH_ID as ECTL_INS_BATCH_ID, MEMBER_MSTR.ECTL_UPD_BATCH_ID as ECTL_UPD_BATCH_ID, MEMBER_MSTR.ECTL_INS_PRGM_ID as ECTL_INS_PRGM_ID,
MEMBER_MSTR.ECTL_UPD_PRGM_ID as ECTL_UPD_PRGM_ID
FROM MEMBER_MSTR
WHERE MEMB_EXP_DT = ''9999-12-31''
) LKP ON LKP.MEMB_NUM = SQ_Shortcut_to_STG_FED_MSTR_DELTA.MEMBER_NBR
QUALIFY RNK = 1
);


-- Component m_validate_date, Type MAPPLET 
--MAPPLET NOT REGISTERED: m_validate_date, mapplet instance m_validate_date;


-- Component rtr_New_Upd_Del_DEL_EXPIRE_MEMBER, Type ROUTER Output Group DEL_EXPIRE_MEMBER
SELECT
LKP_MEMBER_MSTR.MEMB_SKEY as MEMB_SKEY,
SQ_Shortcut_to_STG_FED_MSTR_DELTA.MEMBER_NBR as MEMBER_NBR,
SQ_Shortcut_to_STG_FED_MSTR_DELTA.TX_CD as TX_CD,
m_validate_date.out_DATE_DT as EFF_DT,
m_lkp_Control_Tables.mplt_BATCH_ID as mplt_BATCH_ID,
m_lkp_Control_Tables.mplt_PRGM_ID as mplt_PRGM_ID,
m_lkp_Control_Tables.mplt_TABLE_ID as mplt_TABLE_ID,
LKP_GETMEMNUM.MEMBER_SEQ as MEMBER_SEQ1,
LKP_GETMEMNUM.AGENT_NBR as AGENT_NBR1,
LKP_GETMEMNUM.USER_ID as USER_ID1,
LKP_GETMEMNUM.SC_NUMBER as SC_NUMBER1,
LKP_GETMEMNUM.DATE_REQUESTED as DATE_REQUESTED,
LKP_GETMEMNUM.TIME_REQUESTED as TIME_REQUESTED,
SQ_Shortcut_to_STG_FED_MSTR_DELTA.source_record_id
FROM
SQ_Shortcut_to_STG_FED_MSTR_DELTA
LEFT JOIN LKP_GETMEMNUM ON SQ_Shortcut_to_STG_FED_MSTR_DELTA.source_record_id = LKP_GETMEMNUM.source_record_id
LEFT JOIN m_lkp_Control_Tables ON LKP_GETMEMNUM.source_record_id = m_lkp_Control_Tables.source_record_id
LEFT JOIN LKP_MEMBER_MSTR ON m_lkp_Control_Tables.source_record_id = LKP_MEMBER_MSTR.source_record_id
LEFT JOIN m_validate_date ON LKP_MEMBER_MSTR.source_record_id = m_validate_date.source_record_id
WHERE CASE WHEN LKP_MEMBER_MSTR.MEMB_SKEY IS NOT NULL and SQ_Shortcut_to_STG_FED_MSTR_DELTA.TX_CD = ''DEL'' THEN TRUE ELSE FALSE END;


-- Component rtr_New_Upd_Del_NEW_MEMBER, Type ROUTER Output Group NEW_MEMBER
SELECT
LKP_MEMBER_MSTR.MEMB_SKEY as MEMB_SKEY,
SQ_Shortcut_to_STG_FED_MSTR_DELTA.MEMBER_NBR as MEMBER_NBR,
SQ_Shortcut_to_STG_FED_MSTR_DELTA.TX_CD as TX_CD,
m_validate_date.out_DATE_DT as EFF_DT,
m_lkp_Control_Tables.mplt_BATCH_ID as mplt_BATCH_ID,
m_lkp_Control_Tables.mplt_PRGM_ID as mplt_PRGM_ID,
m_lkp_Control_Tables.mplt_TABLE_ID as mplt_TABLE_ID,
LKP_GETMEMNUM.MEMBER_SEQ as MEMBER_SEQ1,
LKP_GETMEMNUM.AGENT_NBR as AGENT_NBR1,
LKP_GETMEMNUM.USER_ID as USER_ID1,
LKP_GETMEMNUM.SC_NUMBER as SC_NUMBER1,
LKP_GETMEMNUM.DATE_REQUESTED as DATE_REQUESTED,
LKP_GETMEMNUM.TIME_REQUESTED as TIME_REQUESTED,
SQ_Shortcut_to_STG_FED_MSTR_DELTA.source_record_id
FROM
SQ_Shortcut_to_STG_FED_MSTR_DELTA
LEFT JOIN LKP_GETMEMNUM ON SQ_Shortcut_to_STG_FED_MSTR_DELTA.source_record_id = LKP_GETMEMNUM.source_record_id
LEFT JOIN m_lkp_Control_Tables ON LKP_GETMEMNUM.source_record_id = m_lkp_Control_Tables.source_record_id
LEFT JOIN LKP_MEMBER_MSTR ON m_lkp_Control_Tables.source_record_id = LKP_MEMBER_MSTR.source_record_id
LEFT JOIN m_validate_date ON LKP_MEMBER_MSTR.source_record_id = m_validate_date.source_record_id
WHERE CASE WHEN LKP_MEMBER_MSTR.MEMB_SKEY IS NULL and SQ_Shortcut_to_STG_FED_MSTR_DELTA.TX_CD = ''NEW'' THEN TRUE ELSE FALSE END;


-- Component exp_New_Member, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_New_Member AS
(
SELECT
rtr_New_Upd_Del_NEW_MEMBER.MEMBER_NBR as MEMBER_NBR,
rtr_New_Upd_Del_NEW_MEMBER.EFF_DT as EFF_DT,
to_date ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as EXP_DT,
rtr_New_Upd_Del_NEW_MEMBER.mplt_BATCH_ID as INS_BATCH_ID,
rtr_New_Upd_Del_NEW_MEMBER.mplt_PRGM_ID as INS_PRGM_ID,
rtr_New_Upd_Del_NEW_MEMBER.MEMBER_SEQ1 as MEMBER_SEQ1,
rtr_New_Upd_Del_NEW_MEMBER.DATE_REQUESTED as DATE_REQUESTED,
rtr_New_Upd_Del_NEW_MEMBER.TIME_REQUESTED as TIME_REQUESTED,
rtr_New_Upd_Del_NEW_MEMBER.AGENT_NBR1 as AGENT_NBR1,
rtr_New_Upd_Del_NEW_MEMBER.USER_ID1 as USER_ID1,
rtr_New_Upd_Del_NEW_MEMBER.SC_NUMBER1 as SC_NUMBER1,
rtr_New_Upd_Del_NEW_MEMBER.source_record_id
FROM
rtr_New_Upd_Del_NEW_MEMBER
);


-- Component upd_Expire_Member, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_Expire_Member AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
rtr_New_Upd_Del_DEL_EXPIRE_MEMBER.MEMB_SKEY as MEMB_SKEY,
rtr_New_Upd_Del_DEL_EXPIRE_MEMBER.EFF_DT as EXP_DT,
rtr_New_Upd_Del_DEL_EXPIRE_MEMBER.mplt_BATCH_ID as upd_BATCH_ID,
rtr_New_Upd_Del_DEL_EXPIRE_MEMBER.mplt_PRGM_ID as upd_PRGM_ID,
rtr_New_Upd_Del_DEL_EXPIRE_MEMBER.MEMBER_SEQ1 as MEMBER_SEQ3,
rtr_New_Upd_Del_DEL_EXPIRE_MEMBER.DATE_REQUESTED as DATE_REQUESTED,
rtr_New_Upd_Del_DEL_EXPIRE_MEMBER.TIME_REQUESTED as TIME_REQUESTED,
rtr_New_Upd_Del_DEL_EXPIRE_MEMBER.AGENT_NBR1 as AGENT_NBR3,
rtr_New_Upd_Del_DEL_EXPIRE_MEMBER.USER_ID1 as USER_ID3,
rtr_New_Upd_Del_DEL_EXPIRE_MEMBER.SC_NUMBER1 as SC_NUMBER3,
rtr_New_Upd_Del_DEL_EXPIRE_MEMBER.TX_CD as TX_CD3,
1 as UPDATE_STRATEGY_ACTION
FROM
rtr_New_Upd_Del_DEL_EXPIRE_MEMBER
);


-- Component MEMBER_MSTR_INS, Type TARGET 
INSERT INTO DB_T_CORE_PROD.MEMBER_MSTR
(
MEMB_SKEY,
MEMB_NUM,
MEMB_EFF_DT,
MEMB_EXP_DT,
MEMB_ORIG_SALES_AGENT_NBR,
MEMB_ORIG_SALES_AGENT_SC_NBR,
MEMB_ORIG_SALES_USER_ID,
MEMB_SEQ,
MEMB_DATE_REQUESTED,
MEMB_TIME_REQUESTED,
ECTL_INS_BATCH_ID,
ECTL_INS_PRGM_ID
)
SELECT
row_number() over (order by 1) as MEMB_SKEY,
exp_New_Member.MEMBER_NBR as MEMB_NUM,
exp_New_Member.EFF_DT as MEMB_EFF_DT,
exp_New_Member.EXP_DT as MEMB_EXP_DT,
exp_New_Member.AGENT_NBR1 as MEMB_ORIG_SALES_AGENT_NBR,
exp_New_Member.SC_NUMBER1 as MEMB_ORIG_SALES_AGENT_SC_NBR,
exp_New_Member.USER_ID1 as MEMB_ORIG_SALES_USER_ID,
exp_New_Member.MEMBER_SEQ1 as MEMB_SEQ,
exp_New_Member.DATE_REQUESTED as MEMB_DATE_REQUESTED,
exp_New_Member.TIME_REQUESTED as MEMB_TIME_REQUESTED,
exp_New_Member.INS_BATCH_ID as ECTL_INS_BATCH_ID,
exp_New_Member.INS_PRGM_ID as ECTL_INS_PRGM_ID
FROM
exp_New_Member;


-- Component exp_Empire_Member, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Empire_Member AS
(
SELECT
upd_Expire_Member.MEMB_SKEY as MEMB_SKEY,
upd_Expire_Member.EXP_DT as EXP_DT,
upd_Expire_Member.upd_BATCH_ID as upd_BATCH_ID,
upd_Expire_Member.upd_PRGM_ID as upd_PRGM_ID,
upd_Expire_Member.MEMBER_SEQ3 as MEMBER_SEQ3,
upd_Expire_Member.DATE_REQUESTED as DATE_REQUESTED,
upd_Expire_Member.TIME_REQUESTED as TIME_REQUESTED,
upd_Expire_Member.AGENT_NBR3 as AGENT_NBR3,
upd_Expire_Member.USER_ID3 as USER_ID3,
upd_Expire_Member.SC_NUMBER3 as SC_NUMBER3,
upd_Expire_Member.source_record_id
FROM
upd_Expire_Member
);


-- Component MEMBER_MSTR_EXPIRE, Type TARGET 
MERGE INTO DB_T_CORE_PROD.MEMBER_MSTR
USING exp_Empire_Member ON (MEMBER_MSTR.MEMB_SKEY = exp_Empire_Member.MEMB_SKEY)
WHEN MATCHED THEN UPDATE
SET
MEMB_SKEY = exp_Empire_Member.MEMB_SKEY,
MEMB_EXP_DT = exp_Empire_Member.EXP_DT,
MEMB_ORIG_SALES_AGENT_NBR = exp_Empire_Member.AGENT_NBR3,
MEMB_ORIG_SALES_AGENT_SC_NBR = exp_Empire_Member.SC_NUMBER3,
MEMB_ORIG_SALES_USER_ID = exp_Empire_Member.USER_ID3,
MEMB_SEQ = exp_Empire_Member.MEMBER_SEQ3,
MEMB_DATE_REQUESTED = exp_Empire_Member.DATE_REQUESTED,
MEMB_TIME_REQUESTED = exp_Empire_Member.TIME_REQUESTED,
ECTL_UPD_BATCH_ID = exp_Empire_Member.upd_BATCH_ID,
ECTL_UPD_PRGM_ID = exp_Empire_Member.upd_PRGM_ID;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_MEMBER_MSTR, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_MEMBER_MSTR AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMB_SKEY,
$2 as MEMB_NUM,
$3 as MEMB_ORIG_SALES_AGENT_NBR,
$4 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT distinct MEMBER_MSTR.MEMB_SKEY, MEMBER_MSTR.MEMB_NUM,MEMB_ORIG_SALES_AGENT_NBR 
FROM DB_T_CORE_PROD.MEMBER_MSTR   where MEMB_EXP_DT=''9999-12-31''
) SRC
)
);


-- Component LKP_GETMEMBERSHIP_TABLE, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_GETMEMBERSHIP_TABLE AS
(
SELECT
LKP.MEMBERNUM,
LKP.AGENT_NBR,
LKP.USER_ID,
LKP.STATUS,
SQ_MEMBER_MSTR.MEMB_NUM as MEMB_NUM,
SQ_MEMBER_MSTR.source_record_id,
ROW_NUMBER() OVER(PARTITION BY SQ_MEMBER_MSTR.source_record_id ORDER BY LKP.MEMBERNUM asc,LKP.AGENT_NBR asc,LKP.USER_ID asc,LKP.STATUS asc) RNK
FROM
SQ_MEMBER_MSTR
LEFT JOIN (
SELECT GETMEMBERNUM.AGENT_NBR as AGENT_NBR, GETMEMBERNUM.USER_ID as USER_ID, GETMEMBERNUM.STATUS as STATUS, GETMEMBERNUM.MEMBERNUM as MEMBERNUM FROM  GETMEMBERNUM
WHERE STATUS =''ACTIVE''
and upper(ltrim(rtrim(USER_ID))) like ''%-RECOD%'' 
 qualify row_number() over (partition by GETMEMBERNUM.MEMBERNUM order by GETMEMBERNUM.DATE_REQUESTED desc) = 1
) LKP ON LKP.MEMBERNUM = SQ_MEMBER_MSTR.MEMB_NUM
QUALIFY RNK = 1
);


-- Component exp_set_paramter_val, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_set_paramter_val AS
(
SELECT
LKP_GETMEMBERSHIP_TABLE.MEMBERNUM as MEMBERNUM,
LKP_GETMEMBERSHIP_TABLE.AGENT_NBR as AGENT_NBR,
LKP_GETMEMBERSHIP_TABLE.USER_ID as USER_ID,
LKP_GETMEMBERSHIP_TABLE.STATUS as STATUS,
SQ_MEMBER_MSTR.MEMB_SKEY as MEMB_SKEY,
SQ_MEMBER_MSTR.MEMB_NUM as MEMB_NUM,
CASE WHEN LKP_GETMEMBERSHIP_TABLE.MEMBERNUM IS NULL THEN ''REJ'' ELSE ''UPD'' END as O_Flag,
SQ_MEMBER_MSTR.source_record_id
FROM
SQ_MEMBER_MSTR
INNER JOIN LKP_GETMEMBERSHIP_TABLE ON SQ_MEMBER_MSTR.source_record_id = LKP_GETMEMBERSHIP_TABLE.source_record_id
);


-- Component rtr_upd_rej_Update_agnet_nbr, Type ROUTER Output Group Update_agnet_nbr
SELECT
exp_set_paramter_val.MEMBERNUM as MEMBERNUM,
exp_set_paramter_val.AGENT_NBR as AGENT_NBR,
exp_set_paramter_val.USER_ID as USER_ID,
exp_set_paramter_val.STATUS as STATUS,
exp_set_paramter_val.MEMB_SKEY as MEMB_SKEY,
exp_set_paramter_val.MEMB_NUM as MEMB_NUM,
exp_set_paramter_val.O_Flag as O_Flag,
exp_set_paramter_val.source_record_id
FROM
exp_set_paramter_val
WHERE exp_set_paramter_val.O_Flag = ''UPD'';


-- Component UPDTRANS_AGNT_NBR, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE UPDTRANS_AGNT_NBR AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
rtr_upd_rej_Update_agnet_nbr.MEMBERNUM as MEMBERNUM1,
rtr_upd_rej_Update_agnet_nbr.AGENT_NBR as AGENT_NBR1,
rtr_upd_rej_Update_agnet_nbr.USER_ID as USER_ID1,
rtr_upd_rej_Update_agnet_nbr.STATUS as STATUS1,
rtr_upd_rej_Update_agnet_nbr.MEMB_SKEY as MEMB_SKEY1,
rtr_upd_rej_Update_agnet_nbr.MEMB_NUM as MEMB_NUM1,
1 as UPDATE_STRATEGY_ACTION
FROM
rtr_upd_rej_Update_agnet_nbr
);


-- Component Shortcut_to_MEMBER_MSTR, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_CORE_PROD.MEMBER_MSTR
USING UPDTRANS_AGNT_NBR ON (UPDATE_STRATEGY_ACTION = 1 AND MEMBER_MSTR.MEMB_SKEY = UPDTRANS_AGNT_NBR.MEMB_SKEY1)
WHEN MATCHED THEN UPDATE
SET
MEMB_ORIG_SALES_AGENT_NBR = UPDTRANS_AGNT_NBR.AGENT_NBR1
;


-- PIPELINE END FOR 2

END; ';