-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STG_FIN_SML("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component sq_PS_ALF_REPOS_SML_S, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_PS_ALF_REPOS_SML_S AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as BUSINESS_UNIT,
$2 as TRANSACTION_ID,
$3 as DTTM_STAMP,
$4 as ALF_REC_COUNTER,
$5 as LEDGER_GROUP,
$6 as LEDGER,
$7 as JOURNAL_ID,
$8 as JOURNAL_LINE,
$9 as FISCAL_YEAR,
$10 as ACCOUNTING_PERIOD,
$11 as JOURNAL_DATE,
$12 as ACCOUNT_CD,
$13 as DEPTID,
$14 as PRODUCT,
$15 as PROJECT_ID,
$16 as CHARTFIELD1,
$17 as CHARTFIELD2,
$18 as CHARTFIELD3,
$19 as AFFILIATE,
$20 as ALF_TRANS_CODE,
$21 as ALF_POL_PREFIX,
$22 as ALF_POL_NUMBER,
$23 as ALF_AGENT_NO,
$24 as ALF_SERV_CTR_NBR,
$25 as ALF_STATE_CD,
$26 as ALF_COMPANY_CD,
$27 as ALF_BUDGET_SYM,
$28 as ALF_ACCT_NBR,
$29 as ALF_LEGACY_LINE_NO,
$30 as ALF_ACCT_DT,
$31 as APPL_JRNL_ID,
$32 as BUSINESS_UNIT_GL,
$33 as ACCOUNTING_DT,
$34 as GL_DISTRIB_STATUS,
$35 as JRNL_LN_REF,
$36 as JRNL_DESCR,
$37 as CURRENCY_CD,
$38 as STATISTICS_CODE,
$39 as MONETARY_AMOUNT,
$40 as STATISTIC_AMOUNT,
$41 as FOREIGN_AMOUNT,
$42 as FOREIGN_CURRENCY,
$43 as PROCESS_INSTANCE,
$44 as ALF_POL_EFF_DATE,
$45 as ALF_POL_EXP_DATE,
$46 as ALF_REFERENCE,
$47 as ALF_PROGRAM_CD,
$48 as ALF_CLASS,
$49 as ALF_POL_TYPE,
$50 as ALF_PF_PART,
$51 as ALF_CONST_CD,
$52 as ALF_BO_CH_IND,
$53 as ALF_PROT_CLASS,
$54 as ALF_TERM,
$55 as ALF_BOAT_CLASS,
$56 as ALF_FCL_DATA_F,
$57 as ALF_TOT_PREM,
$58 as ALF_MUN_TAX,
$59 as ALF_ROW_INDICATOR,
$60 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 

TRIM(PS_ALF_REPOS_SML_S.BUSINESS_UNIT), 

TRIM(PS_ALF_REPOS_SML_S.TRANSACTION_ID), 

PS_ALF_REPOS_SML_S.DTTM_STAMP, 

PS_ALF_REPOS_SML_S.ALF_REC_COUNTER, 

TRIM(PS_ALF_REPOS_SML_S.LEDGER_GROUP), 

TRIM(PS_ALF_REPOS_SML_S.LEDGER), 

TRIM(PS_ALF_REPOS_SML_S.JOURNAL_ID), 

PS_ALF_REPOS_SML_S.JOURNAL_LINE, 

PS_ALF_REPOS_SML_S.FISCAL_YEAR, 

PS_ALF_REPOS_SML_S.ACCOUNTING_PERIOD, 

PS_ALF_REPOS_SML_S.JOURNAL_DATE, 

TRIM(PS_ALF_REPOS_SML_S.ACCOUNT_CD), 

TRIM(PS_ALF_REPOS_SML_S.DEPTID), 

TRIM(PS_ALF_REPOS_SML_S.PRODUCT), 

TRIM(PS_ALF_REPOS_SML_S.PROJECT_ID), 

TRIM(PS_ALF_REPOS_SML_S.CHARTFIELD1), 

TRIM(PS_ALF_REPOS_SML_S.CHARTFIELD2), 

TRIM(PS_ALF_REPOS_SML_S.CHARTFIELD3), 

TRIM(PS_ALF_REPOS_SML_S.AFFILIATE), 

TRIM(PS_ALF_REPOS_SML_S.ALF_TRANS_CODE), 

TRIM(PS_ALF_REPOS_SML_S.ALF_POL_PREFIX), 

PS_ALF_REPOS_SML_S.ALF_POL_NUMBER, 

TRIM(PS_ALF_REPOS_SML_S.ALF_AGENT_NO), 

TRIM(PS_ALF_REPOS_SML_S.ALF_SERV_CTR_NBR), 

TRIM(PS_ALF_REPOS_SML_S.ALF_STATE_CD), 

TRIM(PS_ALF_REPOS_SML_S.ALF_COMPANY_CD), 

TRIM(PS_ALF_REPOS_SML_S.ALF_BUDGET_SYM), 

TRIM(PS_ALF_REPOS_SML_S.ALF_ACCT_NBR), 

TRIM(PS_ALF_REPOS_SML_S.ALF_LEGACY_LINE_NO), 

PS_ALF_REPOS_SML_S.ALF_ACCT_DT, 

TRIM(PS_ALF_REPOS_SML_S.APPL_JRNL_ID), 

TRIM(PS_ALF_REPOS_SML_S.BUSINESS_UNIT_GL), 

PS_ALF_REPOS_SML_S.ACCOUNTING_DT, 

TRIM(PS_ALF_REPOS_SML_S.GL_DISTRIB_STATUS), 

TRIM(PS_ALF_REPOS_SML_S.JRNL_LN_REF), 

TRIM(PS_ALF_REPOS_SML_S.JRNL_DESCR), 

TRIM(PS_ALF_REPOS_SML_S.CURRENCY_CD), 

TRIM(PS_ALF_REPOS_SML_S.STATISTICS_CODE), 

PS_ALF_REPOS_SML_S.MONETARY_AMOUNT, 

PS_ALF_REPOS_SML_S.STATISTIC_AMOUNT, 

PS_ALF_REPOS_SML_S.FOREIGN_AMOUNT, 

TRIM(PS_ALF_REPOS_SML_S.FOREIGN_CURRENCY), 

PS_ALF_REPOS_SML_S.PROCESS_INSTANCE, 

PS_ALF_REPOS_SML_S.ALF_POL_EFF_DATE, 

PS_ALF_REPOS_SML_S.ALF_POL_EXP_DATE, 

TRIM(PS_ALF_REPOS_SML_S.ALF_REFERENCE), 

TRIM(PS_ALF_REPOS_SML_S.ALF_PROGRAM_CD), 

TRIM(PS_ALF_REPOS_SML_S.ALF_CLASS), 

TRIM(PS_ALF_REPOS_SML_S.ALF_POL_TYPE), 

TRIM(PS_ALF_REPOS_SML_S.ALF_PF_PART), 

TRIM(PS_ALF_REPOS_SML_S.ALF_CONST_CD), 

TRIM(PS_ALF_REPOS_SML_S.ALF_BO_CH_IND), 

TRIM(PS_ALF_REPOS_SML_S.ALF_PROT_CLASS), 

TRIM(PS_ALF_REPOS_SML_S.ALF_TERM), 

TRIM(PS_ALF_REPOS_SML_S.ALF_BOAT_CLASS), 

TRIM(PS_ALF_REPOS_SML_S.ALF_FCL_DATA_F), 

PS_ALF_REPOS_SML_S.ALF_TOT_PREM, 

TRIM(PS_ALF_REPOS_SML_S.ALF_MUN_TAX), 

TRIM(PS_ALF_REPOS_SML_S.ALF_ROW_INDICATOR) 

FROM

 DB_T_STAG_FIN_PROD.PS_ALF_REPOS_SML_S

WHERE TRIM(PS_ALF_REPOS_SML_S.FISCAL_YEAR) = (SELECT ECTL_PARAM_VALUE FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM WHERE ECTL_PARAM_DESC=''ACCOUNTING_YEAR'') AND TRIM( PS_ALF_REPOS_SML_S.ACCOUNTING_PERIOD) = (SELECT ECTL_PARAM_VALUE FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM WHERE ECTL_PARAM_DESC=''ACCOUNTING_MONTH'')
) SRC
)
);


-- Component STG_FIN_SML_INS, Type TARGET 
INSERT INTO DB_T_STAG_FIN_PROD.STG_FIN_SML
(
BUSINESS_UNIT,
TRANSACTION_ID,
DTTM_STAMP,
ALF_REC_COUNTER,
LEDGER_GROUP,
LEDGER,
JOURNAL_ID,
JOURNAL_LINE,
FISCAL_YEAR,
ACCOUNTING_PERIOD,
JOURNAL_DATE,
ACCOUNT_NBR,
DEPTID,
PRODUCT,
PROJECT_ID,
CHARTFIELD1,
CHARTFIELD2,
CHARTFIELD3,
AFFILIATE,
ALF_TRANS_CODE,
ALF_POL_PREFIX,
ALF_POL_NUMBER,
ALF_AGENT_NO,
ALF_SERV_CTR_NBR,
ALF_STATE_CD,
ALF_COMPANY_CD,
ALF_BUDGET_SYM,
ALF_ACCT_NBR,
ALF_LEGACY_LINE_NO,
ALF_ACCT_DT,
APPL_JRNL_ID,
BUSINESS_UNIT_GL,
ACCOUNTING_DT,
GL_DISTRIB_STATUS,
JRNL_LN_REF,
JRNL_DESCR,
CURRENCY_CD,
STATISTICS_CODE,
MONETARY_AMOUNT,
STATISTIC_AMOUNT,
FOREIGN_AMOUNT,
FOREIGN_CURRENCY,
PROCESS_INSTANCE,
ALF_POL_EFF_DATE,
ALF_POL_EXP_DATE,
ALF_REFERENCE,
ALF_PROGRAM_CD,
ALF_CLASS,
ALF_POL_TYPE,
ALF_PF_PART,
ALF_CONST_CD,
ALF_BO_CH_IND,
ALF_PROT_CLASS,
ALF_TERM,
ALF_BOAT_CLASS,
ALF_FCL_DATA_F,
ALF_TOT_PREM,
ALF_MUN_TAX,
ALF_ROW_INDICATOR
)
SELECT
sq_PS_ALF_REPOS_SML_S.BUSINESS_UNIT as BUSINESS_UNIT,
sq_PS_ALF_REPOS_SML_S.TRANSACTION_ID as TRANSACTION_ID,
sq_PS_ALF_REPOS_SML_S.DTTM_STAMP as DTTM_STAMP,
sq_PS_ALF_REPOS_SML_S.ALF_REC_COUNTER as ALF_REC_COUNTER,
sq_PS_ALF_REPOS_SML_S.LEDGER_GROUP as LEDGER_GROUP,
sq_PS_ALF_REPOS_SML_S.LEDGER as LEDGER,
sq_PS_ALF_REPOS_SML_S.JOURNAL_ID as JOURNAL_ID,
sq_PS_ALF_REPOS_SML_S.JOURNAL_LINE as JOURNAL_LINE,
sq_PS_ALF_REPOS_SML_S.FISCAL_YEAR as FISCAL_YEAR,
sq_PS_ALF_REPOS_SML_S.ACCOUNTING_PERIOD as ACCOUNTING_PERIOD,
sq_PS_ALF_REPOS_SML_S.JOURNAL_DATE as JOURNAL_DATE,
sq_PS_ALF_REPOS_SML_S.ACCOUNT_CD as ACCOUNT_NBR,
sq_PS_ALF_REPOS_SML_S.DEPTID as DEPTID,
sq_PS_ALF_REPOS_SML_S.PRODUCT as PRODUCT,
sq_PS_ALF_REPOS_SML_S.PROJECT_ID as PROJECT_ID,
sq_PS_ALF_REPOS_SML_S.CHARTFIELD1 as CHARTFIELD1,
sq_PS_ALF_REPOS_SML_S.CHARTFIELD2 as CHARTFIELD2,
sq_PS_ALF_REPOS_SML_S.CHARTFIELD3 as CHARTFIELD3,
sq_PS_ALF_REPOS_SML_S.AFFILIATE as AFFILIATE,
sq_PS_ALF_REPOS_SML_S.ALF_TRANS_CODE as ALF_TRANS_CODE,
sq_PS_ALF_REPOS_SML_S.ALF_POL_PREFIX as ALF_POL_PREFIX,
sq_PS_ALF_REPOS_SML_S.ALF_POL_NUMBER as ALF_POL_NUMBER,
sq_PS_ALF_REPOS_SML_S.ALF_AGENT_NO as ALF_AGENT_NO,
sq_PS_ALF_REPOS_SML_S.ALF_SERV_CTR_NBR as ALF_SERV_CTR_NBR,
sq_PS_ALF_REPOS_SML_S.ALF_STATE_CD as ALF_STATE_CD,
sq_PS_ALF_REPOS_SML_S.ALF_COMPANY_CD as ALF_COMPANY_CD,
sq_PS_ALF_REPOS_SML_S.ALF_BUDGET_SYM as ALF_BUDGET_SYM,
sq_PS_ALF_REPOS_SML_S.ALF_ACCT_NBR as ALF_ACCT_NBR,
sq_PS_ALF_REPOS_SML_S.ALF_LEGACY_LINE_NO as ALF_LEGACY_LINE_NO,
sq_PS_ALF_REPOS_SML_S.ALF_ACCT_DT as ALF_ACCT_DT,
sq_PS_ALF_REPOS_SML_S.APPL_JRNL_ID as APPL_JRNL_ID,
sq_PS_ALF_REPOS_SML_S.BUSINESS_UNIT_GL as BUSINESS_UNIT_GL,
sq_PS_ALF_REPOS_SML_S.ACCOUNTING_DT as ACCOUNTING_DT,
sq_PS_ALF_REPOS_SML_S.GL_DISTRIB_STATUS as GL_DISTRIB_STATUS,
sq_PS_ALF_REPOS_SML_S.JRNL_LN_REF as JRNL_LN_REF,
sq_PS_ALF_REPOS_SML_S.JRNL_DESCR as JRNL_DESCR,
sq_PS_ALF_REPOS_SML_S.CURRENCY_CD as CURRENCY_CD,
sq_PS_ALF_REPOS_SML_S.STATISTICS_CODE as STATISTICS_CODE,
sq_PS_ALF_REPOS_SML_S.MONETARY_AMOUNT as MONETARY_AMOUNT,
sq_PS_ALF_REPOS_SML_S.STATISTIC_AMOUNT as STATISTIC_AMOUNT,
sq_PS_ALF_REPOS_SML_S.FOREIGN_AMOUNT as FOREIGN_AMOUNT,
sq_PS_ALF_REPOS_SML_S.FOREIGN_CURRENCY as FOREIGN_CURRENCY,
sq_PS_ALF_REPOS_SML_S.PROCESS_INSTANCE as PROCESS_INSTANCE,
sq_PS_ALF_REPOS_SML_S.ALF_POL_EFF_DATE as ALF_POL_EFF_DATE,
sq_PS_ALF_REPOS_SML_S.ALF_POL_EXP_DATE as ALF_POL_EXP_DATE,
sq_PS_ALF_REPOS_SML_S.ALF_REFERENCE as ALF_REFERENCE,
sq_PS_ALF_REPOS_SML_S.ALF_PROGRAM_CD as ALF_PROGRAM_CD,
sq_PS_ALF_REPOS_SML_S.ALF_CLASS as ALF_CLASS,
sq_PS_ALF_REPOS_SML_S.ALF_POL_TYPE as ALF_POL_TYPE,
sq_PS_ALF_REPOS_SML_S.ALF_PF_PART as ALF_PF_PART,
sq_PS_ALF_REPOS_SML_S.ALF_CONST_CD as ALF_CONST_CD,
sq_PS_ALF_REPOS_SML_S.ALF_BO_CH_IND as ALF_BO_CH_IND,
sq_PS_ALF_REPOS_SML_S.ALF_PROT_CLASS as ALF_PROT_CLASS,
sq_PS_ALF_REPOS_SML_S.ALF_TERM as ALF_TERM,
sq_PS_ALF_REPOS_SML_S.ALF_BOAT_CLASS as ALF_BOAT_CLASS,
sq_PS_ALF_REPOS_SML_S.ALF_FCL_DATA_F as ALF_FCL_DATA_F,
sq_PS_ALF_REPOS_SML_S.ALF_TOT_PREM as ALF_TOT_PREM,
sq_PS_ALF_REPOS_SML_S.ALF_MUN_TAX as ALF_MUN_TAX,
sq_PS_ALF_REPOS_SML_S.ALF_ROW_INDICATOR as ALF_ROW_INDICATOR
FROM
sq_PS_ALF_REPOS_SML_S;


END; ';