-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STG_FIN_S3B("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_PS_ALF_REPOS_S3B_S, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_PS_ALF_REPOS_S3B_S AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as BUSINESS_UNIT,
$2 as TRANSACTION_ID,
$3 as DTTM_STAMP,
$4 as ALF_REC_COUNTER,
$5 as LEDGER_GROUP,
$6 as LEDGER,
$7 as JOURNAL_ID,
$8 as JOURNAL_LINE,
$9 as FISCAL_YEAR,
$10 as ACCOUNTING_PERIOD,
$11 as JOURNAL_DATE,
$12 as ACCOUNT_NBR,
$13 as DEPTID,
$14 as PRODUCT,
$15 as PROJECT_ID,
$16 as CHARTFIELD1,
$17 as CHARTFIELD2,
$18 as CHARTFIELD3,
$19 as AFFILIATE,
$20 as ALF_POL_PREFIX,
$21 as ALF_POLICY_NBR,
$22 as ALF_COV_TYPE,
$23 as ALF_AGT_NBR,
$24 as ALF_SERV_CTR_NBR,
$25 as ALF_COMPANY_CODE,
$26 as ALF_BILL_BANK_CD,
$27 as ALF_POLICY_ID,
$28 as ALF_LOB_CD,
$29 as ALF_CLAIMENT_ID,
$30 as ALF_TRANS_OBJ_CD,
$31 as ALF_TRANS_ACT_CD,
$32 as ALF_ACCOUNT_ID,
$33 as ALF_ACCOUNT_DT,
$34 as MONETARY_AMOUNT,
$35 as CURRENCY_CD,
$36 as STATISTIC_AMOUNT,
$37 as STATISTICS_CODE,
$38 as FOREIGN_AMOUNT,
$39 as FOREIGN_CURRENCY,
$40 as APPL_JRNL_ID,
$41 as BUSINESS_UNIT_GL,
$42 as ACCOUNTING_DT,
$43 as GL_DISTRIB_STATUS,
$44 as JRNL_LN_REF,
$45 as JRNL_DESCR,
$46 as PROCESS_INSTANCE,
$47 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT

	TRIM(PS_ALF_REPOS_S3B_S.BUSINESS_UNIT),

	TRIM(PS_ALF_REPOS_S3B_S.TRANSACTION_ID),

	PS_ALF_REPOS_S3B_S.DTTM_STAMP,

	PS_ALF_REPOS_S3B_S.ALF_REC_COUNTER,

	TRIM(PS_ALF_REPOS_S3B_S.LEDGER_GROUP),

	TRIM(PS_ALF_REPOS_S3B_S.LEDGER),

	TRIM(PS_ALF_REPOS_S3B_S.JOURNAL_ID),

	PS_ALF_REPOS_S3B_S.JOURNAL_LINE,

	PS_ALF_REPOS_S3B_S.FISCAL_YEAR,

	PS_ALF_REPOS_S3B_S.ACCOUNTING_PERIOD,

	PS_ALF_REPOS_S3B_S.JOURNAL_DATE,

	TRIM(PS_ALF_REPOS_S3B_S.ACCOUNT_NBR),

	TRIM(PS_ALF_REPOS_S3B_S.DEPTID),

	TRIM(PS_ALF_REPOS_S3B_S.PRODUCT),

	TRIM(PS_ALF_REPOS_S3B_S.PROJECT_ID),

	TRIM(PS_ALF_REPOS_S3B_S.CHARTFIELD1),

	TRIM(PS_ALF_REPOS_S3B_S.CHARTFIELD2),

	TRIM(PS_ALF_REPOS_S3B_S.CHARTFIELD3),

	TRIM(PS_ALF_REPOS_S3B_S.AFFILIATE),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_POL_PREFIX),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_POLICY_NBR),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_COV_TYPE),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_AGT_NBR),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_SERV_CTR_NBR),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_COMPANY_CODE),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_BILL_BANK_CD),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_POLICY_ID),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_LOB_CD),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_CLAIMENT_ID),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_TRANS_OBJ_CD),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_TRANS_ACT_CD),

	TRIM(PS_ALF_REPOS_S3B_S.ALF_ACCOUNT_ID),

	PS_ALF_REPOS_S3B_S.ALF_ACCOUNT_DT,

	PS_ALF_REPOS_S3B_S.MONETARY_AMOUNT,

	TRIM(PS_ALF_REPOS_S3B_S.CURRENCY_CD),

	PS_ALF_REPOS_S3B_S.STATISTIC_AMOUNT,

	TRIM(PS_ALF_REPOS_S3B_S.STATISTICS_CODE),

	PS_ALF_REPOS_S3B_S.FOREIGN_AMOUNT,

	TRIM(PS_ALF_REPOS_S3B_S.FOREIGN_CURRENCY),

	TRIM(PS_ALF_REPOS_S3B_S.APPL_JRNL_ID),

	TRIM(PS_ALF_REPOS_S3B_S.BUSINESS_UNIT_GL),

	PS_ALF_REPOS_S3B_S.ACCOUNTING_DT,

	TRIM(PS_ALF_REPOS_S3B_S.GL_DISTRIB_STATUS),

	TRIM(PS_ALF_REPOS_S3B_S.JRNL_LN_REF),

	TRIM(PS_ALF_REPOS_S3B_S.JRNL_DESCR),

	PS_ALF_REPOS_S3B_S.PROCESS_INSTANCE

FROM

	DB_T_STAG_FIN_PROD.PS_ALF_REPOS_S3B_S

WHERE

	PS_ALF_REPOS_S3B_S.FISCAL_YEAR = (SELECT ECTL_PARAM_VALUE FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM WHERE ECTL_PARAM_DESC=''ACCOUNTING_YEAR'') AND

	PS_ALF_REPOS_S3B_S.ACCOUNTING_PERIOD = (SELECT ECTL_PARAM_VALUE FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM WHERE ECTL_PARAM_DESC=''ACCOUNTING_MONTH'')
) SRC
)
);


-- Component exp_Pass_Through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Pass_Through AS
(
SELECT
SQ_PS_ALF_REPOS_S3B_S.BUSINESS_UNIT as BUSINESS_UNIT,
SQ_PS_ALF_REPOS_S3B_S.TRANSACTION_ID as TRANSACTION_ID,
SQ_PS_ALF_REPOS_S3B_S.DTTM_STAMP as DTTM_STAMP,
SQ_PS_ALF_REPOS_S3B_S.ALF_REC_COUNTER as ALF_REC_COUNTER,
SQ_PS_ALF_REPOS_S3B_S.LEDGER_GROUP as LEDGER_GROUP,
SQ_PS_ALF_REPOS_S3B_S.LEDGER as LEDGER,
SQ_PS_ALF_REPOS_S3B_S.JOURNAL_ID as JOURNAL_ID,
SQ_PS_ALF_REPOS_S3B_S.JOURNAL_LINE as JOURNAL_LINE,
SQ_PS_ALF_REPOS_S3B_S.FISCAL_YEAR as FISCAL_YEAR,
SQ_PS_ALF_REPOS_S3B_S.ACCOUNTING_PERIOD as ACCOUNTING_PERIOD,
SQ_PS_ALF_REPOS_S3B_S.JOURNAL_DATE as JOURNAL_DATE,
SQ_PS_ALF_REPOS_S3B_S.ACCOUNT_NBR as ACCOUNT_NBR,
SQ_PS_ALF_REPOS_S3B_S.DEPTID as DEPTID,
SQ_PS_ALF_REPOS_S3B_S.PRODUCT as PRODUCT,
SQ_PS_ALF_REPOS_S3B_S.PROJECT_ID as PROJECT_ID,
SQ_PS_ALF_REPOS_S3B_S.CHARTFIELD1 as CHARTFIELD1,
SQ_PS_ALF_REPOS_S3B_S.CHARTFIELD2 as CHARTFIELD2,
SQ_PS_ALF_REPOS_S3B_S.CHARTFIELD3 as CHARTFIELD3,
SQ_PS_ALF_REPOS_S3B_S.AFFILIATE as AFFILIATE,
SQ_PS_ALF_REPOS_S3B_S.ALF_POL_PREFIX as ALF_POL_PREFIX,
SQ_PS_ALF_REPOS_S3B_S.ALF_POLICY_NBR as ALF_POLICY_NBR,
SQ_PS_ALF_REPOS_S3B_S.ALF_COV_TYPE as ALF_COV_TYPE,
SQ_PS_ALF_REPOS_S3B_S.ALF_AGT_NBR as ALF_AGT_NBR,
SQ_PS_ALF_REPOS_S3B_S.ALF_SERV_CTR_NBR as ALF_SERV_CTR_NBR,
SQ_PS_ALF_REPOS_S3B_S.ALF_COMPANY_CODE as ALF_COMPANY_CODE,
SQ_PS_ALF_REPOS_S3B_S.ALF_BILL_BANK_CD as ALF_BILL_BANK_CD,
SQ_PS_ALF_REPOS_S3B_S.ALF_POLICY_ID as ALF_POLICY_ID,
SQ_PS_ALF_REPOS_S3B_S.ALF_LOB_CD as ALF_LOB_CD,
SQ_PS_ALF_REPOS_S3B_S.ALF_CLAIMENT_ID as ALF_CLAIMENT_ID,
SQ_PS_ALF_REPOS_S3B_S.ALF_TRANS_OBJ_CD as ALF_TRANS_OBJ_CD,
SQ_PS_ALF_REPOS_S3B_S.ALF_TRANS_ACT_CD as ALF_TRANS_ACT_CD,
SQ_PS_ALF_REPOS_S3B_S.ALF_ACCOUNT_ID as ALF_ACCOUNT_ID,
SQ_PS_ALF_REPOS_S3B_S.ALF_ACCOUNT_DT as ALF_ACCOUNT_DT,
SQ_PS_ALF_REPOS_S3B_S.MONETARY_AMOUNT as MONETARY_AMOUNT,
SQ_PS_ALF_REPOS_S3B_S.CURRENCY_CD as CURRENCY_CD,
SQ_PS_ALF_REPOS_S3B_S.STATISTIC_AMOUNT as STATISTIC_AMOUNT,
SQ_PS_ALF_REPOS_S3B_S.STATISTICS_CODE as STATISTICS_CODE,
SQ_PS_ALF_REPOS_S3B_S.FOREIGN_AMOUNT as FOREIGN_AMOUNT,
SQ_PS_ALF_REPOS_S3B_S.FOREIGN_CURRENCY as FOREIGN_CURRENCY,
SQ_PS_ALF_REPOS_S3B_S.APPL_JRNL_ID as APPL_JRNL_ID,
SQ_PS_ALF_REPOS_S3B_S.BUSINESS_UNIT_GL as BUSINESS_UNIT_GL,
SQ_PS_ALF_REPOS_S3B_S.ACCOUNTING_DT as ACCOUNTING_DT,
SQ_PS_ALF_REPOS_S3B_S.GL_DISTRIB_STATUS as GL_DISTRIB_STATUS,
SQ_PS_ALF_REPOS_S3B_S.JRNL_LN_REF as JRNL_LN_REF,
SQ_PS_ALF_REPOS_S3B_S.JRNL_DESCR as JRNL_DESCR,
SQ_PS_ALF_REPOS_S3B_S.PROCESS_INSTANCE as PROCESS_INSTANCE,
SQ_PS_ALF_REPOS_S3B_S.source_record_id
FROM
SQ_PS_ALF_REPOS_S3B_S
);


-- Component STG_FIN_S3B, Type TARGET 
INSERT INTO DB_T_STAG_FIN_PROD.STG_FIN_S3B
(
BUSINESS_UNIT,
TRANSACTION_ID,
DTTM_STAMP,
ALF_REC_COUNTER,
LEDGER_GROUP,
LEDGER,
JOURNAL_ID,
JOURNAL_LINE,
FISCAL_YEAR,
ACCOUNTING_PERIOD,
JOURNAL_DATE,
ACCOUNT_NBR,
DEPTID,
PRODUCT,
PROJECT_ID,
CHARTFIELD1,
CHARTFIELD2,
CHARTFIELD3,
AFFILIATE,
ALF_POL_PREFIX,
ALF_POLICY_NBR,
ALF_COV_TYPE,
ALF_AGT_NBR,
ALF_SERV_CTR_NBR,
ALF_COMPANY_CD,
ALF_BILL_BANK_CD,
ALF_POLICY_ID,
ALF_LOB_CD,
ALF_CLAIMENT_ID,
ALF_TRANS_OBJ_CD,
ALF_TRANS_ACT_CD,
ALF_ACCOUNT_ID,
ALF_ACCT_DT,
MONETARY_AMOUNT,
CURRENCY_CD,
STATISTIC_AMOUNT,
STATISTICS_CODE,
FOREIGN_AMOUNT,
FOREIGN_CURRENCY,
APPL_JRNL_ID,
BUSINESS_UNIT_GL,
ACCOUNTING_DT,
GL_DISTRIB_STATUS,
JRNL_LN_REF,
JRNL_DESCR,
PROCESS_INSTANCE
)
SELECT
exp_Pass_Through.BUSINESS_UNIT as BUSINESS_UNIT,
exp_Pass_Through.TRANSACTION_ID as TRANSACTION_ID,
exp_Pass_Through.DTTM_STAMP as DTTM_STAMP,
exp_Pass_Through.ALF_REC_COUNTER as ALF_REC_COUNTER,
exp_Pass_Through.LEDGER_GROUP as LEDGER_GROUP,
exp_Pass_Through.LEDGER as LEDGER,
exp_Pass_Through.JOURNAL_ID as JOURNAL_ID,
exp_Pass_Through.JOURNAL_LINE as JOURNAL_LINE,
exp_Pass_Through.FISCAL_YEAR as FISCAL_YEAR,
exp_Pass_Through.ACCOUNTING_PERIOD as ACCOUNTING_PERIOD,
exp_Pass_Through.JOURNAL_DATE as JOURNAL_DATE,
exp_Pass_Through.ACCOUNT_NBR as ACCOUNT_NBR,
exp_Pass_Through.DEPTID as DEPTID,
exp_Pass_Through.PRODUCT as PRODUCT,
exp_Pass_Through.PROJECT_ID as PROJECT_ID,
exp_Pass_Through.CHARTFIELD1 as CHARTFIELD1,
exp_Pass_Through.CHARTFIELD2 as CHARTFIELD2,
exp_Pass_Through.CHARTFIELD3 as CHARTFIELD3,
exp_Pass_Through.AFFILIATE as AFFILIATE,
exp_Pass_Through.ALF_POL_PREFIX as ALF_POL_PREFIX,
exp_Pass_Through.ALF_POLICY_NBR as ALF_POLICY_NBR,
exp_Pass_Through.ALF_COV_TYPE as ALF_COV_TYPE,
exp_Pass_Through.ALF_AGT_NBR as ALF_AGT_NBR,
exp_Pass_Through.ALF_SERV_CTR_NBR as ALF_SERV_CTR_NBR,
exp_Pass_Through.ALF_COMPANY_CODE as ALF_COMPANY_CD,
exp_Pass_Through.ALF_BILL_BANK_CD as ALF_BILL_BANK_CD,
exp_Pass_Through.ALF_POLICY_ID as ALF_POLICY_ID,
exp_Pass_Through.ALF_LOB_CD as ALF_LOB_CD,
exp_Pass_Through.ALF_CLAIMENT_ID as ALF_CLAIMENT_ID,
exp_Pass_Through.ALF_TRANS_OBJ_CD as ALF_TRANS_OBJ_CD,
exp_Pass_Through.ALF_TRANS_ACT_CD as ALF_TRANS_ACT_CD,
exp_Pass_Through.ALF_ACCOUNT_ID as ALF_ACCOUNT_ID,
exp_Pass_Through.ALF_ACCOUNT_DT as ALF_ACCT_DT,
exp_Pass_Through.MONETARY_AMOUNT as MONETARY_AMOUNT,
exp_Pass_Through.CURRENCY_CD as CURRENCY_CD,
exp_Pass_Through.STATISTIC_AMOUNT as STATISTIC_AMOUNT,
exp_Pass_Through.STATISTICS_CODE as STATISTICS_CODE,
exp_Pass_Through.FOREIGN_AMOUNT as FOREIGN_AMOUNT,
exp_Pass_Through.FOREIGN_CURRENCY as FOREIGN_CURRENCY,
exp_Pass_Through.APPL_JRNL_ID as APPL_JRNL_ID,
exp_Pass_Through.BUSINESS_UNIT_GL as BUSINESS_UNIT_GL,
exp_Pass_Through.ACCOUNTING_DT as ACCOUNTING_DT,
exp_Pass_Through.GL_DISTRIB_STATUS as GL_DISTRIB_STATUS,
exp_Pass_Through.JRNL_LN_REF as JRNL_LN_REF,
exp_Pass_Through.JRNL_DESCR as JRNL_DESCR,
exp_Pass_Through.PROCESS_INSTANCE as PROCESS_INSTANCE
FROM
exp_Pass_Through;


END; ';