-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STG_FIN_LUE("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component sq_PS_ALF_REPOS_LUE_S, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_PS_ALF_REPOS_LUE_S AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as BUSINESS_UNIT,
$2 as TRANSACTION_ID,
$3 as DTTM_STAMP,
$4 as ALF_REC_COUNTER,
$5 as LEDGER_GROUP,
$6 as LEDGER,
$7 as JOURNAL_ID,
$8 as JOURNAL_LINE,
$9 as FISCAL_YEAR,
$10 as ACCOUNTING_PERIOD,
$11 as JOURNAL_DATE,
$12 as ACCOUNT_CD,
$13 as DEPTID,
$14 as PRODUCT,
$15 as PROJECT_ID,
$16 as CHARTFIELD1,
$17 as CHARTFIELD2,
$18 as CHARTFIELD3,
$19 as AFFILIATE,
$20 as ALF_COV_TYPE15,
$21 as ALF_SERV_CTR_NBR,
$22 as ALF_AGENT_NBR,
$23 as ALF_POL_EFF_DATE,
$24 as ALF_POL_EXP_DATE,
$25 as ALF_POL_PREFIX,
$26 as ALF_POL_NUMBER,
$27 as ALF_COMPANY_CD,
$28 as ALF_ORIG_PREM,
$29 as ALF_LOB_CD,
$30 as ALF_TRANS_SRC_CD,
$31 as MONETARY_AMOUNT,
$32 as CURRENCY_CD,
$33 as STATISTIC_AMOUNT,
$34 as STATISTICS_CODE,
$35 as FOREIGN_AMOUNT,
$36 as FOREIGN_CURRENCY,
$37 as APPL_JRNL_ID,
$38 as BUSINESS_UNIT_GL,
$39 as ACCOUNTING_DT,
$40 as GL_DISTRIB_STATUS,
$41 as JRNL_LN_REF,
$42 as JRNL_DESCR,
$43 as PROCESS_INSTANCE,
$44 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 

TRIM(PS_ALF_REPOS_LUE_S.BUSINESS_UNIT), 

TRIM(PS_ALF_REPOS_LUE_S.TRANSACTION_ID), 

PS_ALF_REPOS_LUE_S.DTTM_STAMP, 

PS_ALF_REPOS_LUE_S.ALF_REC_COUNTER, 

TRIM(PS_ALF_REPOS_LUE_S.LEDGER_GROUP), 

TRIM(PS_ALF_REPOS_LUE_S.LEDGER), 

TRIM(PS_ALF_REPOS_LUE_S.JOURNAL_ID), 

PS_ALF_REPOS_LUE_S.JOURNAL_LINE, 

PS_ALF_REPOS_LUE_S.FISCAL_YEAR, 

PS_ALF_REPOS_LUE_S.ACCOUNTING_PERIOD, 

PS_ALF_REPOS_LUE_S.JOURNAL_DATE, 

TRIM(PS_ALF_REPOS_LUE_S.ACCOUNT_CD), 

TRIM(PS_ALF_REPOS_LUE_S.DEPTID), 

TRIM(PS_ALF_REPOS_LUE_S.PRODUCT), 

TRIM(PS_ALF_REPOS_LUE_S.PROJECT_ID), 

TRIM(PS_ALF_REPOS_LUE_S.CHARTFIELD1), 

TRIM(PS_ALF_REPOS_LUE_S.CHARTFIELD2), 

TRIM(PS_ALF_REPOS_LUE_S.CHARTFIELD3), 

TRIM(PS_ALF_REPOS_LUE_S.AFFILIATE), 

TRIM(PS_ALF_REPOS_LUE_S.ALF_COV_TYPE15), 

TRIM(PS_ALF_REPOS_LUE_S.ALF_SERV_CTR_NBR), 

TRIM(PS_ALF_REPOS_LUE_S.ALF_AGENT_NBR), 

PS_ALF_REPOS_LUE_S.ALF_POL_EFF_DATE, 

PS_ALF_REPOS_LUE_S.ALF_POL_EXP_DATE, 

TRIM(PS_ALF_REPOS_LUE_S.ALF_POL_PREFIX), 

PS_ALF_REPOS_LUE_S.ALF_POL_NUMBER, 

TRIM(PS_ALF_REPOS_LUE_S.ALF_COMPANY_CD), 

PS_ALF_REPOS_LUE_S.ALF_ORIG_PREM, 

TRIM(PS_ALF_REPOS_LUE_S.ALF_LOB_CD), 

TRIM(PS_ALF_REPOS_LUE_S.ALF_TRANS_SRC_CD), 

PS_ALF_REPOS_LUE_S.MONETARY_AMOUNT, 

TRIM(PS_ALF_REPOS_LUE_S.CURRENCY_CD), 

PS_ALF_REPOS_LUE_S.STATISTIC_AMOUNT, 

TRIM(PS_ALF_REPOS_LUE_S.STATISTICS_CODE), 

PS_ALF_REPOS_LUE_S.FOREIGN_AMOUNT, 

TRIM(PS_ALF_REPOS_LUE_S.FOREIGN_CURRENCY), 

TRIM(PS_ALF_REPOS_LUE_S.APPL_JRNL_ID), 

TRIM(PS_ALF_REPOS_LUE_S.BUSINESS_UNIT_GL), 

PS_ALF_REPOS_LUE_S.ACCOUNTING_DT, 

TRIM(PS_ALF_REPOS_LUE_S.GL_DISTRIB_STATUS), 

TRIM(PS_ALF_REPOS_LUE_S.JRNL_LN_REF), 

TRIM(PS_ALF_REPOS_LUE_S.JRNL_DESCR), 

PS_ALF_REPOS_LUE_S.PROCESS_INSTANCE 

FROM

DB_T_STAG_FIN_PROD.PS_ALF_REPOS_LUE_S

WHERE TRIM(PS_ALF_REPOS_LUE_S.FISCAL_YEAR) = (SELECT ECTL_PARAM_VALUE FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM WHERE ECTL_PARAM_DESC=''ACCOUNTING_YEAR'') AND TRIM( PS_ALF_REPOS_LUE_S.ACCOUNTING_PERIOD) = (SELECT ECTL_PARAM_VALUE FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM WHERE ECTL_PARAM_DESC=''ACCOUNTING_MONTH'')
) SRC
)
);


-- Component STG_FIN_LUE_INS, Type TARGET 
INSERT INTO DB_T_STAG_FIN_PROD.STG_FIN_LUE
(
BUSINESS_UNIT,
TRANSACTION_ID,
DTTM_STAMP,
ALF_REC_COUNTER,
LEDGER_GROUP,
LEDGER,
JOURNAL_ID,
JOURNAL_LINE,
FISCAL_YEAR,
ACCOUNTING_PERIOD,
JOURNAL_DATE,
ACCOUNT_NBR,
DEPTID,
PRODUCT,
PROJECT_ID,
CHARTFIELD1,
CHARTFIELD2,
CHARTFIELD3,
AFFILIATE,
ALF_COV_TYPE15,
ALF_SERV_CTR_NBR,
ALF_AGENT_NBR,
ALF_POL_EFF_DATE,
ALF_POL_EXP_DATE,
ALF_POL_PREFIX,
ALF_POL_NUMBER,
ALF_COMPANY_CD,
ALF_ORIG_PREM,
ALF_LOB_CD,
ALF_TRANS_SRC_CD,
MONETARY_AMOUNT,
CURRENCY_CD,
STATISTIC_AMOUNT,
STATISTICS_CODE,
FOREIGN_AMOUNT,
FOREIGN_CURRENCY,
APPL_JRNL_ID,
BUSINESS_UNIT_GL,
ACCOUNTING_DT,
GL_DISTRIB_STATUS,
JRNL_LN_REF,
JRNL_DESCR,
PROCESS_INSTANCE
)
SELECT
sq_PS_ALF_REPOS_LUE_S.BUSINESS_UNIT as BUSINESS_UNIT,
sq_PS_ALF_REPOS_LUE_S.TRANSACTION_ID as TRANSACTION_ID,
sq_PS_ALF_REPOS_LUE_S.DTTM_STAMP as DTTM_STAMP,
sq_PS_ALF_REPOS_LUE_S.ALF_REC_COUNTER as ALF_REC_COUNTER,
sq_PS_ALF_REPOS_LUE_S.LEDGER_GROUP as LEDGER_GROUP,
sq_PS_ALF_REPOS_LUE_S.LEDGER as LEDGER,
sq_PS_ALF_REPOS_LUE_S.JOURNAL_ID as JOURNAL_ID,
sq_PS_ALF_REPOS_LUE_S.JOURNAL_LINE as JOURNAL_LINE,
sq_PS_ALF_REPOS_LUE_S.FISCAL_YEAR as FISCAL_YEAR,
sq_PS_ALF_REPOS_LUE_S.ACCOUNTING_PERIOD as ACCOUNTING_PERIOD,
sq_PS_ALF_REPOS_LUE_S.JOURNAL_DATE as JOURNAL_DATE,
sq_PS_ALF_REPOS_LUE_S.ACCOUNT_CD as ACCOUNT_NBR,
sq_PS_ALF_REPOS_LUE_S.DEPTID as DEPTID,
sq_PS_ALF_REPOS_LUE_S.PRODUCT as PRODUCT,
sq_PS_ALF_REPOS_LUE_S.PROJECT_ID as PROJECT_ID,
sq_PS_ALF_REPOS_LUE_S.CHARTFIELD1 as CHARTFIELD1,
sq_PS_ALF_REPOS_LUE_S.CHARTFIELD2 as CHARTFIELD2,
sq_PS_ALF_REPOS_LUE_S.CHARTFIELD3 as CHARTFIELD3,
sq_PS_ALF_REPOS_LUE_S.AFFILIATE as AFFILIATE,
sq_PS_ALF_REPOS_LUE_S.ALF_COV_TYPE15 as ALF_COV_TYPE15,
sq_PS_ALF_REPOS_LUE_S.ALF_SERV_CTR_NBR as ALF_SERV_CTR_NBR,
sq_PS_ALF_REPOS_LUE_S.ALF_AGENT_NBR as ALF_AGENT_NBR,
sq_PS_ALF_REPOS_LUE_S.ALF_POL_EFF_DATE as ALF_POL_EFF_DATE,
sq_PS_ALF_REPOS_LUE_S.ALF_POL_EXP_DATE as ALF_POL_EXP_DATE,
sq_PS_ALF_REPOS_LUE_S.ALF_POL_PREFIX as ALF_POL_PREFIX,
sq_PS_ALF_REPOS_LUE_S.ALF_POL_NUMBER as ALF_POL_NUMBER,
sq_PS_ALF_REPOS_LUE_S.ALF_COMPANY_CD as ALF_COMPANY_CD,
sq_PS_ALF_REPOS_LUE_S.ALF_ORIG_PREM as ALF_ORIG_PREM,
sq_PS_ALF_REPOS_LUE_S.ALF_LOB_CD as ALF_LOB_CD,
sq_PS_ALF_REPOS_LUE_S.ALF_TRANS_SRC_CD as ALF_TRANS_SRC_CD,
sq_PS_ALF_REPOS_LUE_S.MONETARY_AMOUNT as MONETARY_AMOUNT,
sq_PS_ALF_REPOS_LUE_S.CURRENCY_CD as CURRENCY_CD,
sq_PS_ALF_REPOS_LUE_S.STATISTIC_AMOUNT as STATISTIC_AMOUNT,
sq_PS_ALF_REPOS_LUE_S.STATISTICS_CODE as STATISTICS_CODE,
sq_PS_ALF_REPOS_LUE_S.FOREIGN_AMOUNT as FOREIGN_AMOUNT,
sq_PS_ALF_REPOS_LUE_S.FOREIGN_CURRENCY as FOREIGN_CURRENCY,
sq_PS_ALF_REPOS_LUE_S.APPL_JRNL_ID as APPL_JRNL_ID,
sq_PS_ALF_REPOS_LUE_S.BUSINESS_UNIT_GL as BUSINESS_UNIT_GL,
sq_PS_ALF_REPOS_LUE_S.ACCOUNTING_DT as ACCOUNTING_DT,
sq_PS_ALF_REPOS_LUE_S.GL_DISTRIB_STATUS as GL_DISTRIB_STATUS,
sq_PS_ALF_REPOS_LUE_S.JRNL_LN_REF as JRNL_LN_REF,
sq_PS_ALF_REPOS_LUE_S.JRNL_DESCR as JRNL_DESCR,
sq_PS_ALF_REPOS_LUE_S.PROCESS_INSTANCE as PROCESS_INSTANCE
FROM
sq_PS_ALF_REPOS_LUE_S;


END; ';