-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_PS_ALF_PROJECT("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- PIPELINE START FOR 1

-- Component SQ_PS_PROJECT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_PS_PROJECT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as DESCR,
$2 as EFF_STATUS,
$3 as CURRENCY_CD,
$4 as BUSINESS_UNIT,
$5 as PROJECT_ID,
$6 as LAST_ACTIVITY_ID,
$7 as IN_USE_SW,
$8 as INTEGRATION_TMPL,
$9 as PROJECT_TYPE,
$10 as BUSINESS_UNIT_AM,
$11 as ASSET_ID,
$12 as PROFILE_ID,
$13 as SYSTEM_SOURCE,
$14 as TEMPLATE_ID,
$15 as TEMPLATE_SW,
$16 as AFUDC_PROJ_SW,
$17 as TARGET_PROJ_SW,
$18 as SALES_TAX_PROJ_SW,
$19 as DOCKET_NUMBER,
$20 as PROJECT_FUNCTION,
$21 as LAST_CRITERIA_ID,
$22 as RT_TYPE,
$23 as CUR_EFFDT_TYPE,
$24 as PERCENT_COMPLETE,
$25 as PC_ACT_OPTION,
$26 as PROJECT_USER1,
$27 as PROJECT_USER2,
$28 as PROJECT_USER3,
$29 as PROJECT_USER4,
$30 as PROJECT_USER5,
$31 as PROJECT_USER_DT1,
$32 as PROJECT_USER_DT2,
$33 as PC_USER_CURRENCY,
$34 as PROJECT_USERAMT1,
$35 as PROJECT_USERAMT2,
$36 as PROJECT_USERAMT3,
$37 as AN_GRP_ACTV_BUD,
$38 as AN_GRP_TOT_COSTS,
$39 as SET_OVERRIDE,
$40 as DTTM_STAMP,
$41 as PC_MSP_USR1,
$42 as PC_MSP_USR2,
$43 as PC_MSP_PROJ_ID,
$44 as PC_REV_ACTIVITY,
$45 as ENFORCE,
$46 as ENFORCE_TYPE,
$47 as TOLERANCE,
$48 as PC_SCH_PRODUCT,
$49 as PC_SCH_FIELD1,
$50 as PC_SCH_FIELD2,
$51 as PC_SCH_FIELD3,
$52 as PC_SCH_FIELD4,
$53 as PC_SCH_FIELD5,
$54 as PC_SCH_FIELD6,
$55 as PC_SCH_FIELD7,
$56 as PC_SCH_FIELD8,
$57 as PC_INDENT_LEVEL,
$58 as PROJ_GRANT_STATUS,
$59 as GRANT_FLG,
$60 as GM_PRIMARY_FLAG,
$61 as PC_TEMPLATE_ID,
$62 as PC_FND_DIST_SW,
$63 as START_DT,
$64 as END_DT,
$65 as BASELINE_START_DT,
$66 as BASELINE_FINISH_DT,
$67 as EARLY_START_DT,
$68 as EARLY_FINISH_DT,
$69 as ACTUAL_START_DT,
$70 as ACTUAL_FINISH_DT,
$71 as LATE_START_DT,
$72 as LATE_FINISH_DT,
$73 as PC_DURATION,
$74 as SUMMARY_PRJ,
$75 as PC_CHC_SW,
$76 as PC_CHC_TEMPLATE,
$77 as PC_CALCULATE_SW,
$78 as PC_PRJ_DEF_CALC_MT,
$79 as PC_ACT_DEF_CALC_MT,
$80 as PC_HOURS_PER_DAY,
$81 as PC_CALC_METHOD,
$82 as PC_SUM_METHOD,
$83 as PM_AUTO_REVIEW,
$84 as PM_AUTO_POP,
$85 as FORECAST_AUT_APP,
$86 as FORECAST_LEVEL,
$87 as FORECAST_RATE,
$88 as FORECAST_SRC,
$89 as PROJ_REQUEST_ID,
$90 as PPK_PROJ_VERSION,
$91 as PGM_SCHED_METHOD,
$92 as PC_PERCENT_DTTM,
$93 as HOLIDAY_LIST_ID,
$94 as FMS_DTTM_STAMP,
$95 as FMS_OPRID,
$96 as FMS_LASTUPDDTTM,
$97 as FMS_LASTUPDOPRID,
$98 as CONSTRAINT_DT_FLG,
$99 as CHARGING_LEVEL,
$100 as CHARGING_LEVEL_TR,
$101 as RATE_PLAN,
$102 as BUDGET_APPROVER,
$103 as SCEN_ADJUST_PCT_TM,
$104 as SCEN_ADJUST_PCT_EX,
$105 as TEMPLATE_TYPES,
$106 as PROJ_TMPL_FILTER,
$107 as LAST_CBUD_TYPE,
$108 as LAST_RBUD_TYPE,
$109 as FNA_REQUESTED,
$110 as MANAGED_BY_WO,
$111 as RELEASE,
$112 as CATEGORY_IND,
$113 as APPLICATION_AREA,
$114 as APPLICATION,
$115 as RATE_SELECT,
$116 as PC_REV_BUD_AN_GRP,
$117 as AN_GRP_TOT_REV,
$118 as AN_GRP_EAC,
$119 as RETAIN_HISTORY,
$120 as AN_GRP_FREV,
$121 as ANLTC_ACT_COST,
$122 as ANLTC_ACT_REV,
$123 as ANLTC_FC_COST,
$124 as ANLTC_FC_REV,
$125 as ONE_TARGET_SW,
$126 as P6_INCL_INTGRTN,
$127 as P6_TEMPLATE_ID,
$128 as P6_WBS_LVL,
$129 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT DESCR, EFF_STATUS, CURRENCY_CD, BUSINESS_UNIT, PROJECT_ID, LAST_ACTIVITY_ID, IN_USE_SW, INTEGRATION_TMPL, PROJECT_TYPE, BUSINESS_UNIT_AM, ASSET_ID, PROFILE_ID, SYSTEM_SOURCE, TEMPLATE_ID, TEMPLATE_SW, AFUDC_PROJ_SW, TARGET_PROJ_SW, SALES_TAX_PROJ_SW, DOCKET_NUMBER, PROJECT_FUNCTION, LAST_CRITERIA_ID, RT_TYPE, CUR_EFFDT_TYPE, PERCENT_COMPLETE, PC_ACT_OPTION, PROJECT_USER1, PROJECT_USER2, PROJECT_USER3, PROJECT_USER4, PROJECT_USER5, PROJECT_USER_DT1, PROJECT_USER_DT2, PC_USER_CURRENCY, PROJECT_USERAMT1, PROJECT_USERAMT2, PROJECT_USERAMT3, AN_GRP_ACTV_BUD, AN_GRP_TOT_COSTS, SET_OVERRIDE, DTTM_STAMP, PC_MSP_USR1, PC_MSP_USR2, PC_MSP_PROJ_ID, PC_REV_ACTIVITY, ENFORCE, ENFORCE_TYPE, TOLERANCE, PC_SCH_PRODUCT, PC_SCH_FIELD1, PC_SCH_FIELD2, PC_SCH_FIELD3, PC_SCH_FIELD4, PC_SCH_FIELD5, PC_SCH_FIELD6, PC_SCH_FIELD7, PC_SCH_FIELD8, PC_INDENT_LEVEL, PROJ_GRANT_STATUS, GRANT_FLG, GM_PRIMARY_FLAG, PC_TEMPLATE_ID, PC_FND_DIST_SW 

FROM PS_DB2_OWNER.PS_PROJECT
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_PS_PROJECT.BUSINESS_UNIT as BUSINESS_UNIT,
SQ_PS_PROJECT.PROJECT_ID as PROJECT_ID,
SQ_PS_PROJECT.LAST_ACTIVITY_ID as LAST_ACTIVITY_ID,
SQ_PS_PROJECT.EFF_STATUS as EFF_STATUS,
SQ_PS_PROJECT.IN_USE_SW as IN_USE_SW,
SQ_PS_PROJECT.INTEGRATION_TMPL as INTEGRATION_TMPL,
SQ_PS_PROJECT.DESCR as DESCR,
SQ_PS_PROJECT.PROJECT_TYPE as PROJECT_TYPE,
SQ_PS_PROJECT.BUSINESS_UNIT_AM as BUSINESS_UNIT_AM,
SQ_PS_PROJECT.ASSET_ID as ASSET_ID,
SQ_PS_PROJECT.PROFILE_ID as PROFILE_ID,
SQ_PS_PROJECT.SYSTEM_SOURCE as SYSTEM_SOURCE,
SQ_PS_PROJECT.TEMPLATE_ID as TEMPLATE_ID,
SQ_PS_PROJECT.TEMPLATE_SW as TEMPLATE_SW,
SQ_PS_PROJECT.AFUDC_PROJ_SW as AFUDC_PROJ_SW,
SQ_PS_PROJECT.TARGET_PROJ_SW as TARGET_PROJ_SW,
SQ_PS_PROJECT.SALES_TAX_PROJ_SW as SALES_TAX_PROJ_SW,
SQ_PS_PROJECT.DOCKET_NUMBER as DOCKET_NUMBER,
SQ_PS_PROJECT.PROJECT_FUNCTION as PROJECT_FUNCTION,
SQ_PS_PROJECT.LAST_CRITERIA_ID as LAST_CRITERIA_ID,
SQ_PS_PROJECT.CURRENCY_CD as CURRENCY_CD,
SQ_PS_PROJECT.RT_TYPE as RT_TYPE,
SQ_PS_PROJECT.CUR_EFFDT_TYPE as CUR_EFFDT_TYPE,
SQ_PS_PROJECT.PERCENT_COMPLETE as PERCENT_COMPLETE,
SQ_PS_PROJECT.PC_ACT_OPTION as PC_ACT_OPTION,
SQ_PS_PROJECT.PROJECT_USER1 as PROJECT_USER1,
SQ_PS_PROJECT.PROJECT_USER2 as PROJECT_USER2,
SQ_PS_PROJECT.PROJECT_USER3 as PROJECT_USER3,
SQ_PS_PROJECT.PROJECT_USER4 as PROJECT_USER4,
SQ_PS_PROJECT.PROJECT_USER5 as PROJECT_USER5,
SQ_PS_PROJECT.PROJECT_USER_DT1 as PROJECT_USER_DT1,
SQ_PS_PROJECT.PROJECT_USER_DT2 as PROJECT_USER_DT2,
SQ_PS_PROJECT.PC_USER_CURRENCY as PC_USER_CURRENCY,
SQ_PS_PROJECT.PROJECT_USERAMT1 as PROJECT_USERAMT1,
SQ_PS_PROJECT.PROJECT_USERAMT2 as PROJECT_USERAMT2,
SQ_PS_PROJECT.PROJECT_USERAMT3 as PROJECT_USERAMT3,
SQ_PS_PROJECT.AN_GRP_ACTV_BUD as AN_GRP_ACTV_BUD,
SQ_PS_PROJECT.AN_GRP_TOT_COSTS as AN_GRP_TOT_COSTS,
SQ_PS_PROJECT.SET_OVERRIDE as SET_OVERRIDE,
SQ_PS_PROJECT.DTTM_STAMP as DTTM_STAMP,
SQ_PS_PROJECT.PC_MSP_USR1 as PC_MSP_USR1,
SQ_PS_PROJECT.PC_MSP_USR2 as PC_MSP_USR2,
SQ_PS_PROJECT.PC_MSP_PROJ_ID as PC_MSP_PROJ_ID,
SQ_PS_PROJECT.PC_REV_ACTIVITY as PC_REV_ACTIVITY,
SQ_PS_PROJECT.ENFORCE as ENFORCE,
SQ_PS_PROJECT.ENFORCE_TYPE as ENFORCE_TYPE,
SQ_PS_PROJECT.TOLERANCE as TOLERANCE,
SQ_PS_PROJECT.PC_SCH_PRODUCT as PC_SCH_PRODUCT,
SQ_PS_PROJECT.PC_SCH_FIELD1 as PC_SCH_FIELD1,
SQ_PS_PROJECT.PC_SCH_FIELD2 as PC_SCH_FIELD2,
SQ_PS_PROJECT.PC_SCH_FIELD3 as PC_SCH_FIELD3,
SQ_PS_PROJECT.PC_SCH_FIELD4 as PC_SCH_FIELD4,
SQ_PS_PROJECT.PC_SCH_FIELD5 as PC_SCH_FIELD5,
SQ_PS_PROJECT.PC_SCH_FIELD6 as PC_SCH_FIELD6,
SQ_PS_PROJECT.PC_SCH_FIELD7 as PC_SCH_FIELD7,
SQ_PS_PROJECT.PC_SCH_FIELD8 as PC_SCH_FIELD8,
SQ_PS_PROJECT.PC_INDENT_LEVEL as PC_INDENT_LEVEL,
SQ_PS_PROJECT.PROJ_GRANT_STATUS as PROJ_GRANT_STATUS,
SQ_PS_PROJECT.GRANT_FLG as GRANT_FLG,
SQ_PS_PROJECT.GM_PRIMARY_FLAG as GM_PRIMARY_FLAG,
SQ_PS_PROJECT.PC_TEMPLATE_ID as PC_TEMPLATE_ID,
SQ_PS_PROJECT.PC_FND_DIST_SW as PC_FND_DIST_SW,
SQ_PS_PROJECT.source_record_id
FROM
SQ_PS_PROJECT
);


-- Component PS_ALF_PROJECT, Type TARGET 
INSERT INTO DB_T_STAG_FIN_PROD.PS_ALF_PROJECT
(
BUSINESS_UNIT,
PROJECT_ID,
LAST_ACTIVITY_ID,
EFF_STATUS,
IN_USE_SW,
INTEGRATION_TMPL,
DESCR,
PROJECT_TYPE,
BUSINESS_UNIT_AM,
ASSET_ID,
PROFILE_ID,
SYSTEM_SOURCE,
TEMPLATE_ID,
TEMPLATE_SW,
AFUDC_PROJ_SW,
TARGET_PROJ_SW,
SALES_TAX_PROJ_SW,
DOCKET_NUMBER,
PROJECT_FUNCTION,
LAST_CRITERIA_ID,
CURRENCY_CD,
RT_TYPE,
CUR_EFFDT_TYPE,
PERCENT_COMPLETE,
PC_ACT_OPTION,
PROJECT_USER1,
PROJECT_USER2,
PROJECT_USER3,
PROJECT_USER4,
PROJECT_USER5,
PROJECT_USER_DT1,
PROJECT_USER_DT2,
PC_USER_CURRENCY,
PROJECT_USERAMT1,
PROJECT_USERAMT2,
PROJECT_USERAMT3,
AN_GRP_ACTV_BUD,
AN_GRP_TOT_COSTS,
SET_OVERRIDE,
DTTM_STAMP,
PC_MSP_USR1,
PC_MSP_USR2,
PC_MSP_PROJ_ID,
PC_REV_ACTIVITY,
ENFORCE,
ENFORCE_TYPE,
TOLERANCE,
PC_SCH_PRODUCT,
PC_SCH_FIELD1,
PC_SCH_FIELD2,
PC_SCH_FIELD3,
PC_SCH_FIELD4,
PC_SCH_FIELD5,
PC_SCH_FIELD6,
PC_SCH_FIELD7,
PC_SCH_FIELD8,
PC_INDENT_LEVEL,
PROJ_GRANT_STATUS,
GRANT_FLG,
GM_PRIMARY_FLAG,
PC_TEMPLATE_ID,
PC_FND_DIST_SW
)
SELECT
exp_pass_through.BUSINESS_UNIT as BUSINESS_UNIT,
exp_pass_through.PROJECT_ID as PROJECT_ID,
exp_pass_through.LAST_ACTIVITY_ID as LAST_ACTIVITY_ID,
exp_pass_through.EFF_STATUS as EFF_STATUS,
exp_pass_through.IN_USE_SW as IN_USE_SW,
exp_pass_through.INTEGRATION_TMPL as INTEGRATION_TMPL,
exp_pass_through.DESCR as DESCR,
exp_pass_through.PROJECT_TYPE as PROJECT_TYPE,
exp_pass_through.BUSINESS_UNIT_AM as BUSINESS_UNIT_AM,
exp_pass_through.ASSET_ID as ASSET_ID,
exp_pass_through.PROFILE_ID as PROFILE_ID,
exp_pass_through.SYSTEM_SOURCE as SYSTEM_SOURCE,
exp_pass_through.TEMPLATE_ID as TEMPLATE_ID,
exp_pass_through.TEMPLATE_SW as TEMPLATE_SW,
exp_pass_through.AFUDC_PROJ_SW as AFUDC_PROJ_SW,
exp_pass_through.TARGET_PROJ_SW as TARGET_PROJ_SW,
exp_pass_through.SALES_TAX_PROJ_SW as SALES_TAX_PROJ_SW,
exp_pass_through.DOCKET_NUMBER as DOCKET_NUMBER,
exp_pass_through.PROJECT_FUNCTION as PROJECT_FUNCTION,
exp_pass_through.LAST_CRITERIA_ID as LAST_CRITERIA_ID,
exp_pass_through.CURRENCY_CD as CURRENCY_CD,
exp_pass_through.RT_TYPE as RT_TYPE,
exp_pass_through.CUR_EFFDT_TYPE as CUR_EFFDT_TYPE,
exp_pass_through.PERCENT_COMPLETE as PERCENT_COMPLETE,
exp_pass_through.PC_ACT_OPTION as PC_ACT_OPTION,
exp_pass_through.PROJECT_USER1 as PROJECT_USER1,
exp_pass_through.PROJECT_USER2 as PROJECT_USER2,
exp_pass_through.PROJECT_USER3 as PROJECT_USER3,
exp_pass_through.PROJECT_USER4 as PROJECT_USER4,
exp_pass_through.PROJECT_USER5 as PROJECT_USER5,
exp_pass_through.PROJECT_USER_DT1 as PROJECT_USER_DT1,
exp_pass_through.PROJECT_USER_DT2 as PROJECT_USER_DT2,
exp_pass_through.PC_USER_CURRENCY as PC_USER_CURRENCY,
exp_pass_through.PROJECT_USERAMT1 as PROJECT_USERAMT1,
exp_pass_through.PROJECT_USERAMT2 as PROJECT_USERAMT2,
exp_pass_through.PROJECT_USERAMT3 as PROJECT_USERAMT3,
exp_pass_through.AN_GRP_ACTV_BUD as AN_GRP_ACTV_BUD,
exp_pass_through.AN_GRP_TOT_COSTS as AN_GRP_TOT_COSTS,
exp_pass_through.SET_OVERRIDE as SET_OVERRIDE,
exp_pass_through.DTTM_STAMP as DTTM_STAMP,
exp_pass_through.PC_MSP_USR1 as PC_MSP_USR1,
exp_pass_through.PC_MSP_USR2 as PC_MSP_USR2,
exp_pass_through.PC_MSP_PROJ_ID as PC_MSP_PROJ_ID,
exp_pass_through.PC_REV_ACTIVITY as PC_REV_ACTIVITY,
exp_pass_through.ENFORCE as ENFORCE,
exp_pass_through.ENFORCE_TYPE as ENFORCE_TYPE,
exp_pass_through.TOLERANCE as TOLERANCE,
exp_pass_through.PC_SCH_PRODUCT as PC_SCH_PRODUCT,
exp_pass_through.PC_SCH_FIELD1 as PC_SCH_FIELD1,
exp_pass_through.PC_SCH_FIELD2 as PC_SCH_FIELD2,
exp_pass_through.PC_SCH_FIELD3 as PC_SCH_FIELD3,
exp_pass_through.PC_SCH_FIELD4 as PC_SCH_FIELD4,
exp_pass_through.PC_SCH_FIELD5 as PC_SCH_FIELD5,
exp_pass_through.PC_SCH_FIELD6 as PC_SCH_FIELD6,
exp_pass_through.PC_SCH_FIELD7 as PC_SCH_FIELD7,
exp_pass_through.PC_SCH_FIELD8 as PC_SCH_FIELD8,
exp_pass_through.PC_INDENT_LEVEL as PC_INDENT_LEVEL,
exp_pass_through.PROJ_GRANT_STATUS as PROJ_GRANT_STATUS,
exp_pass_through.GRANT_FLG as GRANT_FLG,
exp_pass_through.GM_PRIMARY_FLAG as GM_PRIMARY_FLAG,
exp_pass_through.PC_TEMPLATE_ID as PC_TEMPLATE_ID,
exp_pass_through.PC_FND_DIST_SW as PC_FND_DIST_SW
FROM
exp_pass_through;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_PS_PROJECT1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_PS_PROJECT1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_Count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
select count(*) as record_count

from

PS_DB2_OWNER.ps_project
) SRC
)
);


-- Component exp_ps_project, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ps_project AS
(
SELECT
SQ_PS_PROJECT1.record_Count as record_count,
:feed_ind as feed_ind,
to_char ( CURRENT_TIMESTAMP , ''YYYY-MM_DD'' ) as feed_Dt,
filler,
SQ_PS_PROJECT1.source_record_id
FROM
SQ_PS_PROJECT1
);


-- Component TRG_STAG_PS_LOOKUP, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_STAG_PS_LOOKUP AS
(
SELECT
exp_ps_project.feed_ind as feed_ind,
exp_ps_project.feed_Dt as feed_dt,
exp_ps_project.record_count as record_cnt,
exp_ps_project.filler as FIELD1,
exp_ps_project.filler as FIELD2,
exp_ps_project.filler as FIELD3,
exp_ps_project.filler as FIELD4,
exp_ps_project.filler as FIELD5,
exp_ps_project.filler as FIELD6,
exp_ps_project.filler as FIELD7,
exp_ps_project.filler as FIELD8,
exp_ps_project.filler as FIELD9,
exp_ps_project.filler as FIELD10,
exp_ps_project.filler as FIELD11,
exp_ps_project.filler as FIELD12,
exp_ps_project.filler as FIELD13,
exp_ps_project.filler as FIELD14,
exp_ps_project.filler as FIELD15,
exp_ps_project.filler as FIELD16,
exp_ps_project.filler as FIELD17,
exp_ps_project.filler as FIELD18,
exp_ps_project.filler as FIELD19,
exp_ps_project.filler as FIELD20,
exp_ps_project.filler as FIELD21,
exp_ps_project.filler as FIELD22,
exp_ps_project.filler as FIELD23,
exp_ps_project.filler as FIELD24,
exp_ps_project.filler as FIELD25,
exp_ps_project.filler as FIELD26,
exp_ps_project.filler as FIELD27
FROM
exp_ps_project
);


-- Component TRG_STAG_PS_LOOKUP, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 2

END; ';