-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_PS_ALF_REPOS_S3B("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- PIPELINE START FOR 1

-- Component SQ_PS_ALF_REPOS_S3B_S, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_PS_ALF_REPOS_S3B_S AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as BUSINESS_UNIT,
$2 as TRANSACTION_ID,
$3 as DTTM_STAMP,
$4 as ALF_REC_COUNTER,
$5 as LEDGER_GROUP,
$6 as LEDGER,
$7 as JOURNAL_ID,
$8 as JOURNAL_LINE,
$9 as FISCAL_YEAR,
$10 as ACCOUNTING_PERIOD,
$11 as JOURNAL_DATE,
$12 as ACCOUNT,
$13 as DEPTID,
$14 as PRODUCT,
$15 as PROJECT_ID,
$16 as CHARTFIELD1,
$17 as CHARTFIELD2,
$18 as CHARTFIELD3,
$19 as AFFILIATE,
$20 as ALF_POL_PREFIX,
$21 as ALF_POLICY_NBR,
$22 as ALF_COV_TYPE,
$23 as ALF_AGT_NBR,
$24 as ALF_SERV_CTR_NBR,
$25 as ALF_COMPANY_CD,
$26 as ALF_BILL_BANK_CD,
$27 as ALF_POLICY_ID,
$28 as ALF_LOB_CD,
$29 as ALF_CLAIMENT_ID,
$30 as ALF_TRANS_OBJ_CD,
$31 as ALF_TRANS_ACT_CD,
$32 as ALF_ACCOUNT_ID,
$33 as ALF_ACCT_DT,
$34 as MONETARY_AMOUNT,
$35 as CURRENCY_CD,
$36 as STATISTIC_AMOUNT,
$37 as STATISTICS_CODE,
$38 as FOREIGN_AMOUNT,
$39 as FOREIGN_CURRENCY,
$40 as APPL_JRNL_ID,
$41 as BUSINESS_UNIT_GL,
$42 as ACCOUNTING_DT,
$43 as GL_DISTRIB_STATUS,
$44 as JRNL_LN_REF,
$45 as JRNL_DESCR,
$46 as PROCESS_INSTANCE,
$47 as ALF_BATCH_TYPE,
$48 as ALF_BATCH_DATE,
$49 as ALF_BATCH_SEQ_NBR,
$50 as ALF_TRANS_SEQ_NBR,
$51 as ALF_GW_POLICY_TYPE,
$52 as ALF_GW_LINE_OF_BUS,
$53 as ALF_SRC_BIL_REFNBR,
$54 as ALF_INVOICE_NBR,
$55 as ALF_CHK_NBR,
$56 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT BUSINESS_UNIT,

TRANSACTION_ID,

DTTM_STAMP,

ALF_REC_COUNTER,

LEDGER_GROUP,

LEDGER,

JOURNAL_ID,

JOURNAL_LINE,

FISCAL_YEAR,

ACCOUNTING_PERIOD,

JOURNAL_DATE,

ACCOUNT,

DEPTID,

PRODUCT,

PROJECT_ID,

CHARTFIELD1,

CHARTFIELD2,

CHARTFIELD3,

AFFILIATE,

ALF_POL_PREFIX,

ALF_POLICY_NBR,

ALF_COV_TYPE,

ALF_AGT_NBR,

ALF_SERV_CTR_NBR,

ALF_COMPANY_CD,

ALF_BILL_BANK_CD,

ALF_POLICY_ID,

ALF_LOB_CD,

ALF_CLAIMENT_ID,

ALF_TRANS_OBJ_CD,

ALF_TRANS_ACT_CD,

ALF_ACCOUNT_ID,

ALF_ACCT_DT,

MONETARY_AMOUNT,

CURRENCY_CD,

STATISTIC_AMOUNT,

STATISTICS_CODE,

FOREIGN_AMOUNT,

FOREIGN_CURRENCY,

APPL_JRNL_ID,

BUSINESS_UNIT_GL,

ACCOUNTING_DT,

GL_DISTRIB_STATUS,

JRNL_LN_REF,

JRNL_DESCR,

PROCESS_INSTANCE,

ALF_BATCH_TYPE,

ALF_BATCH_DATE,

ALF_BATCH_SEQ_NBR,

ALF_TRANS_SEQ_NBR,

ALF_GW_POLICY_TYPE,

ALF_GW_LINE_OF_BUS,

ALF_SRC_BIL_REFNBR,

ALF_INVOICE_NBR,

ALF_CHK_NBR   FROM DB_T_STAG_FIN_PROD.PS_ALF_REPOS_S3B_S WHERE FISCAL_YEAR = :PSYR_ID AND ACCOUNTING_PERIOD = :PSMO_ID UNION ALL

  SELECT BUSINESS_UNIT,

TRANSACTION_ID,

DTTM_STAMP,

ALF_REC_COUNTER,

LEDGER_GROUP,

LEDGER,

JOURNAL_ID,

JOURNAL_LINE,

FISCAL_YEAR,

ACCOUNTING_PERIOD,

JOURNAL_DATE,

ACCOUNT,

DEPTID,

PRODUCT,

PROJECT_ID,

CHARTFIELD1,

CHARTFIELD2,

CHARTFIELD3,

AFFILIATE,

ALF_POL_PREFIX,

ALF_POLICY_NBR,

ALF_COV_TYPE,

ALF_AGT_NBR,

ALF_SERV_CTR_NBR,

ALF_COMPANY_CD,

ALF_BILL_BANK_CD,

ALF_POLICY_ID,

ALF_LOB_CD,

ALF_CLAIMENT_ID,

ALF_TRANS_OBJ_CD,

ALF_TRANS_ACT_CD,

ALF_ACCOUNT_ID,

ALF_ACCT_DT,

MONETARY_AMOUNT,

CURRENCY_CD,

STATISTIC_AMOUNT,

STATISTICS_CODE,

FOREIGN_AMOUNT,

FOREIGN_CURRENCY,

APPL_JRNL_ID,

BUSINESS_UNIT_GL,

ACCOUNTING_DT,

GL_DISTRIB_STATUS,

JRNL_LN_REF,

JRNL_DESCR,

PROCESS_INSTANCE,

ALF_BATCH_TYPE,

ALF_BATCH_DATE,

ALF_BATCH_SEQ_NBR,

ALF_TRANS_SEQ_NBR,

ALF_GW_POLICY_TYPE,

ALF_GW_LINE_OF_BUS,

ALF_SRC_BIL_REFNBR,

ALF_INVOICE_NBR,

ALF_CHK_NBR

    FROM PS_DB2_OWNER.PS_ALF_REPOS_S3B_A WHERE FISCAL_YEAR = :PSYR_ID AND ACCOUNTING_PERIOD = :PSMO_ID
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_PS_ALF_REPOS_S3B_S.BUSINESS_UNIT as BUSINESS_UNIT,
SQ_PS_ALF_REPOS_S3B_S.TRANSACTION_ID as TRANSACTION_ID,
SQ_PS_ALF_REPOS_S3B_S.DTTM_STAMP as DTTM_STAMP,
SQ_PS_ALF_REPOS_S3B_S.ALF_REC_COUNTER as ALF_REC_COUNTER,
SQ_PS_ALF_REPOS_S3B_S.LEDGER_GROUP as LEDGER_GROUP,
SQ_PS_ALF_REPOS_S3B_S.LEDGER as LEDGER,
SQ_PS_ALF_REPOS_S3B_S.JOURNAL_ID as JOURNAL_ID,
SQ_PS_ALF_REPOS_S3B_S.JOURNAL_LINE as JOURNAL_LINE,
SQ_PS_ALF_REPOS_S3B_S.FISCAL_YEAR as FISCAL_YEAR,
SQ_PS_ALF_REPOS_S3B_S.ACCOUNTING_PERIOD as ACCOUNTING_PERIOD,
SQ_PS_ALF_REPOS_S3B_S.JOURNAL_DATE as JOURNAL_DATE,
SQ_PS_ALF_REPOS_S3B_S.ACCOUNT as ACCOUNT,
SQ_PS_ALF_REPOS_S3B_S.DEPTID as DEPTID,
SQ_PS_ALF_REPOS_S3B_S.PRODUCT as PRODUCT,
SQ_PS_ALF_REPOS_S3B_S.PROJECT_ID as PROJECT_ID,
SQ_PS_ALF_REPOS_S3B_S.CHARTFIELD1 as CHARTFIELD1,
SQ_PS_ALF_REPOS_S3B_S.CHARTFIELD2 as CHARTFIELD2,
SQ_PS_ALF_REPOS_S3B_S.CHARTFIELD3 as CHARTFIELD3,
SQ_PS_ALF_REPOS_S3B_S.AFFILIATE as AFFILIATE,
SQ_PS_ALF_REPOS_S3B_S.ALF_POL_PREFIX as ALF_POL_PREFIX,
SQ_PS_ALF_REPOS_S3B_S.ALF_POLICY_NBR as ALF_POLICY_NBR,
SQ_PS_ALF_REPOS_S3B_S.ALF_COV_TYPE as ALF_COV_TYPE,
SQ_PS_ALF_REPOS_S3B_S.ALF_AGT_NBR as ALF_AGT_NBR,
SQ_PS_ALF_REPOS_S3B_S.ALF_SERV_CTR_NBR as ALF_SERV_CTR_NBR,
SQ_PS_ALF_REPOS_S3B_S.ALF_COMPANY_CD as ALF_COMPANY_CD,
SQ_PS_ALF_REPOS_S3B_S.ALF_BILL_BANK_CD as ALF_BILL_BANK_CD,
SQ_PS_ALF_REPOS_S3B_S.ALF_POLICY_ID as ALF_POLICY_ID,
SQ_PS_ALF_REPOS_S3B_S.ALF_LOB_CD as ALF_LOB_CD,
SQ_PS_ALF_REPOS_S3B_S.ALF_CLAIMENT_ID as ALF_CLAIMENT_ID,
SQ_PS_ALF_REPOS_S3B_S.ALF_TRANS_OBJ_CD as ALF_TRANS_OBJ_CD,
SQ_PS_ALF_REPOS_S3B_S.ALF_TRANS_ACT_CD as ALF_TRANS_ACT_CD,
SQ_PS_ALF_REPOS_S3B_S.ALF_ACCOUNT_ID as ALF_ACCOUNT_ID,
SQ_PS_ALF_REPOS_S3B_S.ALF_ACCT_DT as ALF_ACCT_DT,
SQ_PS_ALF_REPOS_S3B_S.MONETARY_AMOUNT as MONETARY_AMOUNT,
SQ_PS_ALF_REPOS_S3B_S.CURRENCY_CD as CURRENCY_CD,
SQ_PS_ALF_REPOS_S3B_S.STATISTIC_AMOUNT as STATISTIC_AMOUNT,
SQ_PS_ALF_REPOS_S3B_S.STATISTICS_CODE as STATISTICS_CODE,
SQ_PS_ALF_REPOS_S3B_S.FOREIGN_AMOUNT as FOREIGN_AMOUNT,
SQ_PS_ALF_REPOS_S3B_S.FOREIGN_CURRENCY as FOREIGN_CURRENCY,
SQ_PS_ALF_REPOS_S3B_S.APPL_JRNL_ID as APPL_JRNL_ID,
SQ_PS_ALF_REPOS_S3B_S.BUSINESS_UNIT_GL as BUSINESS_UNIT_GL,
SQ_PS_ALF_REPOS_S3B_S.ACCOUNTING_DT as ACCOUNTING_DT,
SQ_PS_ALF_REPOS_S3B_S.GL_DISTRIB_STATUS as GL_DISTRIB_STATUS,
SQ_PS_ALF_REPOS_S3B_S.JRNL_LN_REF as JRNL_LN_REF,
SQ_PS_ALF_REPOS_S3B_S.JRNL_DESCR as JRNL_DESCR,
SQ_PS_ALF_REPOS_S3B_S.PROCESS_INSTANCE as PROCESS_INSTANCE,
SQ_PS_ALF_REPOS_S3B_S.source_record_id
FROM
SQ_PS_ALF_REPOS_S3B_S
);


-- Component PS_ALF_REPOS_S3B_S2, Type TARGET 
INSERT INTO DB_T_STAG_FIN_PROD.PS_ALF_REPOS_S3B_S
(
BUSINESS_UNIT,
TRANSACTION_ID,
DTTM_STAMP,
ALF_REC_COUNTER,
LEDGER_GROUP,
LEDGER,
JOURNAL_ID,
JOURNAL_LINE,
FISCAL_YEAR,
ACCOUNTING_PERIOD,
JOURNAL_DATE,
ACCOUNT_NBR,
DEPTID,
PRODUCT,
PROJECT_ID,
CHARTFIELD1,
CHARTFIELD2,
CHARTFIELD3,
AFFILIATE,
ALF_POL_PREFIX,
ALF_POLICY_NBR,
ALF_COV_TYPE,
ALF_AGT_NBR,
ALF_SERV_CTR_NBR,
ALF_COMPANY_CODE,
ALF_BILL_BANK_CD,
ALF_POLICY_ID,
ALF_LOB_CD,
ALF_CLAIMENT_ID,
ALF_TRANS_OBJ_CD,
ALF_TRANS_ACT_CD,
ALF_ACCOUNT_ID,
ALF_ACCOUNT_DT,
MONETARY_AMOUNT,
CURRENCY_CD,
STATISTIC_AMOUNT,
STATISTICS_CODE,
FOREIGN_AMOUNT,
FOREIGN_CURRENCY,
APPL_JRNL_ID,
BUSINESS_UNIT_GL,
ACCOUNTING_DT,
GL_DISTRIB_STATUS,
JRNL_LN_REF,
JRNL_DESCR,
PROCESS_INSTANCE
)
SELECT
exp_pass_through.BUSINESS_UNIT as BUSINESS_UNIT,
exp_pass_through.TRANSACTION_ID as TRANSACTION_ID,
exp_pass_through.DTTM_STAMP as DTTM_STAMP,
exp_pass_through.ALF_REC_COUNTER as ALF_REC_COUNTER,
exp_pass_through.LEDGER_GROUP as LEDGER_GROUP,
exp_pass_through.LEDGER as LEDGER,
exp_pass_through.JOURNAL_ID as JOURNAL_ID,
exp_pass_through.JOURNAL_LINE as JOURNAL_LINE,
exp_pass_through.FISCAL_YEAR as FISCAL_YEAR,
exp_pass_through.ACCOUNTING_PERIOD as ACCOUNTING_PERIOD,
exp_pass_through.JOURNAL_DATE as JOURNAL_DATE,
exp_pass_through.ACCOUNT as ACCOUNT_NBR,
exp_pass_through.DEPTID as DEPTID,
exp_pass_through.PRODUCT as PRODUCT,
exp_pass_through.PROJECT_ID as PROJECT_ID,
exp_pass_through.CHARTFIELD1 as CHARTFIELD1,
exp_pass_through.CHARTFIELD2 as CHARTFIELD2,
exp_pass_through.CHARTFIELD3 as CHARTFIELD3,
exp_pass_through.AFFILIATE as AFFILIATE,
exp_pass_through.ALF_POL_PREFIX as ALF_POL_PREFIX,
exp_pass_through.ALF_POLICY_NBR as ALF_POLICY_NBR,
exp_pass_through.ALF_COV_TYPE as ALF_COV_TYPE,
exp_pass_through.ALF_AGT_NBR as ALF_AGT_NBR,
exp_pass_through.ALF_SERV_CTR_NBR as ALF_SERV_CTR_NBR,
exp_pass_through.ALF_COMPANY_CD as ALF_COMPANY_CODE,
exp_pass_through.ALF_BILL_BANK_CD as ALF_BILL_BANK_CD,
exp_pass_through.ALF_POLICY_ID as ALF_POLICY_ID,
exp_pass_through.ALF_LOB_CD as ALF_LOB_CD,
exp_pass_through.ALF_CLAIMENT_ID as ALF_CLAIMENT_ID,
exp_pass_through.ALF_TRANS_OBJ_CD as ALF_TRANS_OBJ_CD,
exp_pass_through.ALF_TRANS_ACT_CD as ALF_TRANS_ACT_CD,
exp_pass_through.ALF_ACCOUNT_ID as ALF_ACCOUNT_ID,
exp_pass_through.ALF_ACCT_DT as ALF_ACCOUNT_DT,
exp_pass_through.MONETARY_AMOUNT as MONETARY_AMOUNT,
exp_pass_through.CURRENCY_CD as CURRENCY_CD,
exp_pass_through.STATISTIC_AMOUNT as STATISTIC_AMOUNT,
exp_pass_through.STATISTICS_CODE as STATISTICS_CODE,
exp_pass_through.FOREIGN_AMOUNT as FOREIGN_AMOUNT,
exp_pass_through.FOREIGN_CURRENCY as FOREIGN_CURRENCY,
exp_pass_through.APPL_JRNL_ID as APPL_JRNL_ID,
exp_pass_through.BUSINESS_UNIT_GL as BUSINESS_UNIT_GL,
exp_pass_through.ACCOUNTING_DT as ACCOUNTING_DT,
exp_pass_through.GL_DISTRIB_STATUS as GL_DISTRIB_STATUS,
exp_pass_through.JRNL_LN_REF as JRNL_LN_REF,
exp_pass_through.JRNL_DESCR as JRNL_DESCR,
exp_pass_through.PROCESS_INSTANCE as PROCESS_INSTANCE
FROM
exp_pass_through;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_PS_ALF_REPOS_S3B_S1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_PS_ALF_REPOS_S3B_S1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CNT,
$2 as MONETARY_AMOUNT,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
with c AS (select count(1) CNT FROM PS_ALF_REPOS_S3B_S) 

 ,s AS (SELECT  COALESCE(SUM(CAST(MONETARY_AMOUNT AS FLOAT)), 0) AS MONETARY_AMOUNT

FROM DB_T_STAG_FIN_PROD.PS_ALF_REPOS_S3B_S

WHERE FISCAL_YEAR =  :PSYR_ID

AND ACCOUNTING_PERIOD = :PSMO_ID

and  ACCOUNT_NBR IN (SELECT ACCT_NBR FROM DB_T_SHRD_FIN_PROD.REPOS_FIN_ACCT_NBR_LKUP           

WHERE REPOS_CD = ''S3B'')

AND GL_DISTRIB_STATUS = ''D'')

select  C.CNT,S.MONETARY_AMOUNT

from

C join S

on 1=1
) SRC
)
);


-- Component exp_ps_alf_repos_s3b, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ps_alf_repos_s3b AS
(
SELECT
SQ_PS_ALF_REPOS_S3B_S1.CNT as record_count,
:feed_ind as feed_ind,
DATE_PART(''MM'', TO_TIMESTAMP(CURRENT_TIMESTAMP)) as feed_mm,
CASE WHEN feed_mm = 1 THEN 12 ELSE ( feed_mm - 1 ) END as o_feed_mm,
DATE_PART(''YY'', TO_TIMESTAMP(CURRENT_TIMESTAMP)) as feed_yy,
CASE WHEN feed_mm = 1 THEN feed_yy - 1 ELSE feed_yy END as o_feed_yy,
o_feed_yy || ''-'' || LPad ( o_feed_mm , 2 , ''0'' ) || ''-'' || ''01'' as feed_dt,
to_char ( SQ_PS_ALF_REPOS_S3B_S1.MONETARY_AMOUNT ) as o_MONETARY_AMOUNT,
FIELD1,
FIELD2,
FIELD3,
FIELD4,
FIELD5,
FIELD6,
FIELD7,
FIELD8,
FIELD9,
FIELD10,
FIELD11,
FIELD12,
FIELD13,
FIELD14,
FIELD15,
FIELD16,
FIELD17,
FIELD18,
FIELD19,
FIELD20,
FIELD21,
FIELD22,
FIELD23,
FIELD24,
FIELD25,
FIELD26,
SQ_PS_ALF_REPOS_S3B_S1.source_record_id
FROM
SQ_PS_ALF_REPOS_S3B_S1
);


-- Component TRG_STAG_PS_REPOS, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_STAG_PS_REPOS AS
(
SELECT
exp_ps_alf_repos_s3b.feed_ind as feed_ind,
exp_ps_alf_repos_s3b.feed_dt as feed_dt,
exp_ps_alf_repos_s3b.record_count as record_cnt,
exp_ps_alf_repos_s3b.o_MONETARY_AMOUNT as monetary_amount,
exp_ps_alf_repos_s3b.FIELD1 as FIELD1,
exp_ps_alf_repos_s3b.FIELD2 as FIELD2,
exp_ps_alf_repos_s3b.FIELD3 as FIELD3,
exp_ps_alf_repos_s3b.FIELD4 as FIELD4,
exp_ps_alf_repos_s3b.FIELD5 as FIELD5,
exp_ps_alf_repos_s3b.FIELD6 as FIELD6,
exp_ps_alf_repos_s3b.FIELD7 as FIELD7,
exp_ps_alf_repos_s3b.FIELD8 as FIELD8,
exp_ps_alf_repos_s3b.FIELD9 as FIELD9,
exp_ps_alf_repos_s3b.FIELD10 as FIELD10,
exp_ps_alf_repos_s3b.FIELD11 as FIELD11,
exp_ps_alf_repos_s3b.FIELD12 as FIELD12,
exp_ps_alf_repos_s3b.FIELD13 as FIELD13,
exp_ps_alf_repos_s3b.FIELD14 as FIELD14,
exp_ps_alf_repos_s3b.FIELD15 as FIELD15,
exp_ps_alf_repos_s3b.FIELD16 as FIELD16,
exp_ps_alf_repos_s3b.FIELD17 as FIELD17,
exp_ps_alf_repos_s3b.FIELD18 as FIELD18,
exp_ps_alf_repos_s3b.FIELD19 as FIELD19,
exp_ps_alf_repos_s3b.FIELD20 as FIELD20,
exp_ps_alf_repos_s3b.FIELD21 as FIELD21,
exp_ps_alf_repos_s3b.FIELD22 as FIELD22,
exp_ps_alf_repos_s3b.FIELD23 as FIELD23,
exp_ps_alf_repos_s3b.FIELD24 as FIELD24,
exp_ps_alf_repos_s3b.FIELD25 as FIELD25,
exp_ps_alf_repos_s3b.FIELD26 as FIELD26
FROM
exp_ps_alf_repos_s3b
);


-- Component TRG_STAG_PS_REPOS, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 2

END; ';