-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_PS_ALF_REPOS_SML("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- PIPELINE START FOR 1

-- Component SQ_PS_ALF_REPOS_SML_S, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_PS_ALF_REPOS_SML_S AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as BUSINESS_UNIT,
$2 as TRANSACTION_ID,
$3 as DTTM_STAMP,
$4 as ALF_REC_COUNTER,
$5 as LEDGER_GROUP,
$6 as LEDGER,
$7 as JOURNAL_ID,
$8 as JOURNAL_LINE,
$9 as FISCAL_YEAR,
$10 as ACCOUNTING_PERIOD,
$11 as JOURNAL_DATE,
$12 as ACCOUNT,
$13 as DEPTID,
$14 as PRODUCT,
$15 as PROJECT_ID,
$16 as CHARTFIELD1,
$17 as CHARTFIELD2,
$18 as CHARTFIELD3,
$19 as AFFILIATE,
$20 as ALF_TRANS_CODE,
$21 as ALF_POL_PREFIX,
$22 as ALF_POL_NUMBER,
$23 as ALF_AGENT_NO,
$24 as ALF_SERV_CTR_NBR,
$25 as ALF_STATE_CD,
$26 as ALF_COMPANY_CD,
$27 as ALF_BUDGET_SYM,
$28 as ALF_ACCT_NBR,
$29 as ALF_LEGACY_LINE_NO,
$30 as ALF_ACCT_DT,
$31 as APPL_JRNL_ID,
$32 as BUSINESS_UNIT_GL,
$33 as ACCOUNTING_DT,
$34 as GL_DISTRIB_STATUS,
$35 as JRNL_LN_REF,
$36 as JRNL_DESCR,
$37 as CURRENCY_CD,
$38 as STATISTICS_CODE,
$39 as MONETARY_AMOUNT,
$40 as STATISTIC_AMOUNT,
$41 as FOREIGN_AMOUNT,
$42 as FOREIGN_CURRENCY,
$43 as PROCESS_INSTANCE,
$44 as ALF_POL_EFF_DATE,
$45 as ALF_POL_EXP_DATE,
$46 as ALF_REFERENCE,
$47 as ALF_PROGRAM_CD,
$48 as ALF_CLASS,
$49 as ALF_POL_TYPE,
$50 as ALF_PF_PART,
$51 as ALF_CONST_CD,
$52 as ALF_BO_CH_IND,
$53 as ALF_PROT_CLASS,
$54 as ALF_TERM,
$55 as ALF_BOAT_CLASS,
$56 as ALF_FCL_DATA_F,
$57 as ALF_TOT_PREM,
$58 as ALF_MUN_TAX,
$59 as ALF_ROW_INDICATOR,
$60 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT *

FROM

 DB_T_STAG_FIN_PROD.PS_ALF_REPOS_SML_S

WHERE FISCAL_YEAR = :PSYR_ID AND ACCOUNTING_PERIOD = :PSMO_ID 

UNION ALL

SELECT *

FROM

 PS_DB2_OWNER.PS_ALF_REPOS_SML_A

WHERE FISCAL_YEAR = :PSYR_ID AND ACCOUNTING_PERIOD = :PSMO_ID
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_PS_ALF_REPOS_SML_S.BUSINESS_UNIT as BUSINESS_UNIT,
SQ_PS_ALF_REPOS_SML_S.TRANSACTION_ID as TRANSACTION_ID,
SQ_PS_ALF_REPOS_SML_S.DTTM_STAMP as DTTM_STAMP,
SQ_PS_ALF_REPOS_SML_S.ALF_REC_COUNTER as ALF_REC_COUNTER,
SQ_PS_ALF_REPOS_SML_S.LEDGER_GROUP as LEDGER_GROUP,
SQ_PS_ALF_REPOS_SML_S.LEDGER as LEDGER,
SQ_PS_ALF_REPOS_SML_S.JOURNAL_ID as JOURNAL_ID,
SQ_PS_ALF_REPOS_SML_S.JOURNAL_LINE as JOURNAL_LINE,
SQ_PS_ALF_REPOS_SML_S.FISCAL_YEAR as FISCAL_YEAR,
SQ_PS_ALF_REPOS_SML_S.ACCOUNTING_PERIOD as ACCOUNTING_PERIOD,
SQ_PS_ALF_REPOS_SML_S.JOURNAL_DATE as JOURNAL_DATE,
SQ_PS_ALF_REPOS_SML_S.ACCOUNT as ACCOUNT,
SQ_PS_ALF_REPOS_SML_S.DEPTID as DEPTID,
SQ_PS_ALF_REPOS_SML_S.PRODUCT as PRODUCT,
SQ_PS_ALF_REPOS_SML_S.PROJECT_ID as PROJECT_ID,
SQ_PS_ALF_REPOS_SML_S.CHARTFIELD1 as CHARTFIELD1,
SQ_PS_ALF_REPOS_SML_S.CHARTFIELD2 as CHARTFIELD2,
SQ_PS_ALF_REPOS_SML_S.CHARTFIELD3 as CHARTFIELD3,
SQ_PS_ALF_REPOS_SML_S.AFFILIATE as AFFILIATE,
SQ_PS_ALF_REPOS_SML_S.ALF_TRANS_CODE as ALF_TRANS_CODE,
SQ_PS_ALF_REPOS_SML_S.ALF_POL_PREFIX as ALF_POL_PREFIX,
SQ_PS_ALF_REPOS_SML_S.ALF_POL_NUMBER as ALF_POL_NUMBER,
SQ_PS_ALF_REPOS_SML_S.ALF_AGENT_NO as ALF_AGENT_NO,
SQ_PS_ALF_REPOS_SML_S.ALF_SERV_CTR_NBR as ALF_SERV_CTR_NBR,
SQ_PS_ALF_REPOS_SML_S.ALF_STATE_CD as ALF_STATE_CD,
SQ_PS_ALF_REPOS_SML_S.ALF_COMPANY_CD as ALF_COMPANY_CD,
SQ_PS_ALF_REPOS_SML_S.ALF_BUDGET_SYM as ALF_BUDGET_SYM,
SQ_PS_ALF_REPOS_SML_S.ALF_ACCT_NBR as ALF_ACCT_NBR,
SQ_PS_ALF_REPOS_SML_S.ALF_LEGACY_LINE_NO as ALF_LEGACY_LINE_NO,
SQ_PS_ALF_REPOS_SML_S.ALF_ACCT_DT as ALF_ACCT_DT,
SQ_PS_ALF_REPOS_SML_S.APPL_JRNL_ID as APPL_JRNL_ID,
SQ_PS_ALF_REPOS_SML_S.BUSINESS_UNIT_GL as BUSINESS_UNIT_GL,
SQ_PS_ALF_REPOS_SML_S.ACCOUNTING_DT as ACCOUNTING_DT,
SQ_PS_ALF_REPOS_SML_S.GL_DISTRIB_STATUS as GL_DISTRIB_STATUS,
SQ_PS_ALF_REPOS_SML_S.JRNL_LN_REF as JRNL_LN_REF,
SQ_PS_ALF_REPOS_SML_S.JRNL_DESCR as JRNL_DESCR,
SQ_PS_ALF_REPOS_SML_S.CURRENCY_CD as CURRENCY_CD,
SQ_PS_ALF_REPOS_SML_S.STATISTICS_CODE as STATISTICS_CODE,
SQ_PS_ALF_REPOS_SML_S.MONETARY_AMOUNT as MONETARY_AMOUNT,
SQ_PS_ALF_REPOS_SML_S.STATISTIC_AMOUNT as STATISTIC_AMOUNT,
SQ_PS_ALF_REPOS_SML_S.FOREIGN_AMOUNT as FOREIGN_AMOUNT,
SQ_PS_ALF_REPOS_SML_S.FOREIGN_CURRENCY as FOREIGN_CURRENCY,
SQ_PS_ALF_REPOS_SML_S.PROCESS_INSTANCE as PROCESS_INSTANCE,
SQ_PS_ALF_REPOS_SML_S.ALF_POL_EFF_DATE as ALF_POL_EFF_DATE,
SQ_PS_ALF_REPOS_SML_S.ALF_POL_EXP_DATE as ALF_POL_EXP_DATE,
SQ_PS_ALF_REPOS_SML_S.ALF_REFERENCE as ALF_REFERENCE,
SQ_PS_ALF_REPOS_SML_S.ALF_PROGRAM_CD as ALF_PROGRAM_CD,
SQ_PS_ALF_REPOS_SML_S.ALF_CLASS as ALF_CLASS,
SQ_PS_ALF_REPOS_SML_S.ALF_POL_TYPE as ALF_POL_TYPE,
SQ_PS_ALF_REPOS_SML_S.ALF_PF_PART as ALF_PF_PART,
SQ_PS_ALF_REPOS_SML_S.ALF_CONST_CD as ALF_CONST_CD,
SQ_PS_ALF_REPOS_SML_S.ALF_BO_CH_IND as ALF_BO_CH_IND,
SQ_PS_ALF_REPOS_SML_S.ALF_PROT_CLASS as ALF_PROT_CLASS,
SQ_PS_ALF_REPOS_SML_S.ALF_TERM as ALF_TERM,
SQ_PS_ALF_REPOS_SML_S.ALF_BOAT_CLASS as ALF_BOAT_CLASS,
SQ_PS_ALF_REPOS_SML_S.ALF_FCL_DATA_F as ALF_FCL_DATA_F,
SQ_PS_ALF_REPOS_SML_S.ALF_TOT_PREM as ALF_TOT_PREM,
SQ_PS_ALF_REPOS_SML_S.ALF_MUN_TAX as ALF_MUN_TAX,
SQ_PS_ALF_REPOS_SML_S.ALF_ROW_INDICATOR as ALF_ROW_INDICATOR,
SQ_PS_ALF_REPOS_SML_S.source_record_id
FROM
SQ_PS_ALF_REPOS_SML_S
);


-- Component PS_ALF_REPOS_SML_S2, Type TARGET 
INSERT INTO DB_T_STAG_FIN_PROD.PS_ALF_REPOS_SML_S
(
BUSINESS_UNIT,
TRANSACTION_ID,
DTTM_STAMP,
ALF_REC_COUNTER,
LEDGER_GROUP,
LEDGER,
JOURNAL_ID,
JOURNAL_LINE,
FISCAL_YEAR,
ACCOUNTING_PERIOD,
JOURNAL_DATE,
ACCOUNT_CD,
DEPTID,
PRODUCT,
PROJECT_ID,
CHARTFIELD1,
CHARTFIELD2,
CHARTFIELD3,
AFFILIATE,
ALF_TRANS_CODE,
ALF_POL_PREFIX,
ALF_POL_NUMBER,
ALF_AGENT_NO,
ALF_SERV_CTR_NBR,
ALF_STATE_CD,
ALF_COMPANY_CD,
ALF_BUDGET_SYM,
ALF_ACCT_NBR,
ALF_LEGACY_LINE_NO,
ALF_ACCT_DT,
APPL_JRNL_ID,
BUSINESS_UNIT_GL,
ACCOUNTING_DT,
GL_DISTRIB_STATUS,
JRNL_LN_REF,
JRNL_DESCR,
CURRENCY_CD,
STATISTICS_CODE,
MONETARY_AMOUNT,
STATISTIC_AMOUNT,
FOREIGN_AMOUNT,
FOREIGN_CURRENCY,
PROCESS_INSTANCE,
ALF_POL_EFF_DATE,
ALF_POL_EXP_DATE,
ALF_REFERENCE,
ALF_PROGRAM_CD,
ALF_CLASS,
ALF_POL_TYPE,
ALF_PF_PART,
ALF_CONST_CD,
ALF_BO_CH_IND,
ALF_PROT_CLASS,
ALF_TERM,
ALF_BOAT_CLASS,
ALF_FCL_DATA_F,
ALF_TOT_PREM,
ALF_MUN_TAX,
ALF_ROW_INDICATOR
)
SELECT
exp_pass_through.BUSINESS_UNIT as BUSINESS_UNIT,
exp_pass_through.TRANSACTION_ID as TRANSACTION_ID,
exp_pass_through.DTTM_STAMP as DTTM_STAMP,
exp_pass_through.ALF_REC_COUNTER as ALF_REC_COUNTER,
exp_pass_through.LEDGER_GROUP as LEDGER_GROUP,
exp_pass_through.LEDGER as LEDGER,
exp_pass_through.JOURNAL_ID as JOURNAL_ID,
exp_pass_through.JOURNAL_LINE as JOURNAL_LINE,
exp_pass_through.FISCAL_YEAR as FISCAL_YEAR,
exp_pass_through.ACCOUNTING_PERIOD as ACCOUNTING_PERIOD,
exp_pass_through.JOURNAL_DATE as JOURNAL_DATE,
exp_pass_through.ACCOUNT as ACCOUNT_CD,
exp_pass_through.DEPTID as DEPTID,
exp_pass_through.PRODUCT as PRODUCT,
exp_pass_through.PROJECT_ID as PROJECT_ID,
exp_pass_through.CHARTFIELD1 as CHARTFIELD1,
exp_pass_through.CHARTFIELD2 as CHARTFIELD2,
exp_pass_through.CHARTFIELD3 as CHARTFIELD3,
exp_pass_through.AFFILIATE as AFFILIATE,
exp_pass_through.ALF_TRANS_CODE as ALF_TRANS_CODE,
exp_pass_through.ALF_POL_PREFIX as ALF_POL_PREFIX,
exp_pass_through.ALF_POL_NUMBER as ALF_POL_NUMBER,
exp_pass_through.ALF_AGENT_NO as ALF_AGENT_NO,
exp_pass_through.ALF_SERV_CTR_NBR as ALF_SERV_CTR_NBR,
exp_pass_through.ALF_STATE_CD as ALF_STATE_CD,
exp_pass_through.ALF_COMPANY_CD as ALF_COMPANY_CD,
exp_pass_through.ALF_BUDGET_SYM as ALF_BUDGET_SYM,
exp_pass_through.ALF_ACCT_NBR as ALF_ACCT_NBR,
exp_pass_through.ALF_LEGACY_LINE_NO as ALF_LEGACY_LINE_NO,
exp_pass_through.ALF_ACCT_DT as ALF_ACCT_DT,
exp_pass_through.APPL_JRNL_ID as APPL_JRNL_ID,
exp_pass_through.BUSINESS_UNIT_GL as BUSINESS_UNIT_GL,
exp_pass_through.ACCOUNTING_DT as ACCOUNTING_DT,
exp_pass_through.GL_DISTRIB_STATUS as GL_DISTRIB_STATUS,
exp_pass_through.JRNL_LN_REF as JRNL_LN_REF,
exp_pass_through.JRNL_DESCR as JRNL_DESCR,
exp_pass_through.CURRENCY_CD as CURRENCY_CD,
exp_pass_through.STATISTICS_CODE as STATISTICS_CODE,
exp_pass_through.MONETARY_AMOUNT as MONETARY_AMOUNT,
exp_pass_through.STATISTIC_AMOUNT as STATISTIC_AMOUNT,
exp_pass_through.FOREIGN_AMOUNT as FOREIGN_AMOUNT,
exp_pass_through.FOREIGN_CURRENCY as FOREIGN_CURRENCY,
exp_pass_through.PROCESS_INSTANCE as PROCESS_INSTANCE,
exp_pass_through.ALF_POL_EFF_DATE as ALF_POL_EFF_DATE,
exp_pass_through.ALF_POL_EXP_DATE as ALF_POL_EXP_DATE,
exp_pass_through.ALF_REFERENCE as ALF_REFERENCE,
exp_pass_through.ALF_PROGRAM_CD as ALF_PROGRAM_CD,
exp_pass_through.ALF_CLASS as ALF_CLASS,
exp_pass_through.ALF_POL_TYPE as ALF_POL_TYPE,
exp_pass_through.ALF_PF_PART as ALF_PF_PART,
exp_pass_through.ALF_CONST_CD as ALF_CONST_CD,
exp_pass_through.ALF_BO_CH_IND as ALF_BO_CH_IND,
exp_pass_through.ALF_PROT_CLASS as ALF_PROT_CLASS,
exp_pass_through.ALF_TERM as ALF_TERM,
exp_pass_through.ALF_BOAT_CLASS as ALF_BOAT_CLASS,
exp_pass_through.ALF_FCL_DATA_F as ALF_FCL_DATA_F,
exp_pass_through.ALF_TOT_PREM as ALF_TOT_PREM,
exp_pass_through.ALF_MUN_TAX as ALF_MUN_TAX,
exp_pass_through.ALF_ROW_INDICATOR as ALF_ROW_INDICATOR
FROM
exp_pass_through;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_PS_ALF_REPOS_SML_S1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_PS_ALF_REPOS_SML_S1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CNT,
$2 as MONETARY_AMOUNT,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
with c AS (select count(1) CNT FROM PS_ALF_REPOS_SML_S) 

 ,s AS (SELECT  COALESCE(SUM(CAST(MONETARY_AMOUNT AS FLOAT)), 0) AS MONETARY_AMOUNT

FROM DB_T_STAG_FIN_PROD.PS_ALF_REPOS_SML_S

WHERE FISCAL_YEAR =  :PSYR_ID

AND ACCOUNTING_PERIOD = :PSMO_ID

and  ACCOUNT_CD IN (SELECT ACCT_NBR FROM DB_T_SHRD_FIN_PROD.REPOS_FIN_ACCT_NBR_LKUP           

WHERE REPOS_CD = ''SML'')

AND GL_DISTRIB_STATUS = ''D'')

select  C.CNT,S.MONETARY_AMOUNT

from

C join S

on 1=1
) SRC
)
);


-- Component exp_ps_alf_repos_sml, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ps_alf_repos_sml AS
(
SELECT
SQ_PS_ALF_REPOS_SML_S1.CNT as record_count,
:feed_ind as feed_ind,
DATE_PART(''MM'', TO_TIMESTAMP(CURRENT_TIMESTAMP)) as feed_mm,
CASE WHEN feed_mm = 1 THEN 12 ELSE ( feed_mm - 1 ) END as o_feed_mm,
DATE_PART(''YY'', TO_TIMESTAMP(CURRENT_TIMESTAMP)) as feed_yy,
CASE WHEN feed_mm = 1 THEN feed_yy - 1 ELSE feed_yy END as o_feed_yy,
o_feed_yy || ''-'' || LPad ( o_feed_mm , 2 , ''0'' ) || ''-'' || ''01'' as feed_dt,
to_char ( SQ_PS_ALF_REPOS_SML_S1.MONETARY_AMOUNT ) as o_MONETARY_AMOUNT,
FIELD1,
FIELD2,
FIELD3,
FIELD4,
FIELD5,
FIELD6,
FIELD7,
FIELD8,
FIELD9,
FIELD10,
FIELD11,
FIELD12,
FIELD13,
FIELD14,
FIELD15,
FIELD16,
FIELD17,
FIELD18,
FIELD19,
FIELD20,
FIELD21,
FIELD22,
FIELD23,
FIELD24,
FIELD25,
FIELD26,
SQ_PS_ALF_REPOS_SML_S1.source_record_id
FROM
SQ_PS_ALF_REPOS_SML_S1
);


-- Component TRG_STAG_PS_REPOS, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_STAG_PS_REPOS AS
(
SELECT
exp_ps_alf_repos_sml.feed_ind as feed_ind,
exp_ps_alf_repos_sml.feed_dt as feed_dt,
exp_ps_alf_repos_sml.record_count as record_cnt,
exp_ps_alf_repos_sml.o_MONETARY_AMOUNT as monetary_amount,
exp_ps_alf_repos_sml.FIELD1 as FIELD1,
exp_ps_alf_repos_sml.FIELD2 as FIELD2,
exp_ps_alf_repos_sml.FIELD3 as FIELD3,
exp_ps_alf_repos_sml.FIELD4 as FIELD4,
exp_ps_alf_repos_sml.FIELD5 as FIELD5,
exp_ps_alf_repos_sml.FIELD6 as FIELD6,
exp_ps_alf_repos_sml.FIELD7 as FIELD7,
exp_ps_alf_repos_sml.FIELD8 as FIELD8,
exp_ps_alf_repos_sml.FIELD9 as FIELD9,
exp_ps_alf_repos_sml.FIELD10 as FIELD10,
exp_ps_alf_repos_sml.FIELD11 as FIELD11,
exp_ps_alf_repos_sml.FIELD12 as FIELD12,
exp_ps_alf_repos_sml.FIELD13 as FIELD13,
exp_ps_alf_repos_sml.FIELD14 as FIELD14,
exp_ps_alf_repos_sml.FIELD15 as FIELD15,
exp_ps_alf_repos_sml.FIELD16 as FIELD16,
exp_ps_alf_repos_sml.FIELD17 as FIELD17,
exp_ps_alf_repos_sml.FIELD18 as FIELD18,
exp_ps_alf_repos_sml.FIELD19 as FIELD19,
exp_ps_alf_repos_sml.FIELD20 as FIELD20,
exp_ps_alf_repos_sml.FIELD21 as FIELD21,
exp_ps_alf_repos_sml.FIELD22 as FIELD22,
exp_ps_alf_repos_sml.FIELD23 as FIELD23,
exp_ps_alf_repos_sml.FIELD24 as FIELD24,
exp_ps_alf_repos_sml.FIELD25 as FIELD25,
exp_ps_alf_repos_sml.FIELD26 as FIELD26
FROM
exp_ps_alf_repos_sml
);


-- Component TRG_STAG_PS_REPOS, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 2

END; ';