-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BAL_SRC_TO_STG("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE TGT_NM varchar;
MAPPING_NM varchar;
ACT_PROJ_ID varchar;
ECTL_ACTIVE_IND varchar;
BEGIN 

TGT_NM:='' ''; 
MAPPING_NM:='' ''; 
ACT_PROJ_ID:='' ''; 
ECTL_ACTIVE_IND:='' ''; 

-- PIPELINE START FOR 1

-- Component sq_TRG_FILE_SRC, Type TABLE_DDL Creating an empty table
CREATE OR REPLACE TEMPORARY TABLE sq_TRG_FILE
(
IND varchar(1),
EFF_DT varchar(10),
RECORD_CNT decimal,
source_record_id number autoincrement start 1 increment 1
);


-- Component sq_TRG_FILE_SRC, Type IMPORT_DATA Importing Data
;


-- PIPELINE START FOR 1

-- Component sq_TGT_TABLE, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_TGT_TABLE AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as JOURNAL_LINE,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT COUNT(*) AS JOURNAL_LINE 
FROM
 TGT_NM
) SRC
)
);


-- Component exp_DUMMY_PORT_TRG, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_DUMMY_PORT_TRG AS
(
SELECT
sq_TRG_FILE.RECORD_CNT as RECORD_CNT,
1 as DUMMY,
sq_TRG_FILE.source_record_id
FROM
sq_TRG_FILE
);


-- Component exp_DUMMY_PORT_TGT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_DUMMY_PORT_TGT AS
(
SELECT
sq_TGT_TABLE.JOURNAL_LINE as TGT_CNT,
1 as DUMMY,
sq_TGT_TABLE.source_record_id
FROM
sq_TGT_TABLE
);


-- Component jnr_TRG_TGT, Type JOINER 
CREATE OR REPLACE TEMPORARY TABLE jnr_TRG_TGT AS
(
SELECT
exp_DUMMY_PORT_TRG.RECORD_CNT as RECORD_CNT,
exp_DUMMY_PORT_TRG.DUMMY as DUMMY,
exp_DUMMY_PORT_TGT.TGT_CNT as TGT_CNT,
exp_DUMMY_PORT_TGT.DUMMY as DUMMY1,
row_number() over (order by 1) AS source_record_id
FROM
exp_DUMMY_PORT_TRG
INNER JOIN exp_DUMMY_PORT_TGT ON exp_DUMMY_PORT_TGT.DUMMY = exp_DUMMY_PORT_TRG.DUMMY
);


-- Component exp_RJCT_CNT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_RJCT_CNT AS
(
SELECT
jnr_TRG_TGT.TGT_CNT as TGT_CNT,
jnr_TRG_TGT.RECORD_CNT as SRC_CNT,
jnr_TRG_TGT.RECORD_CNT - jnr_TRG_TGT.TGT_CNT as out_ECTL_RJCT_CNT,
0 as out_ECTL_DEL_CNT,
0 as out_ECTL_UPD_CNT,
TGT_NM as out_ECTL_TABLE_NM,
ltrim ( rtrim ( MAPPING_NM ) ) as out_ECTL_PRGM_NM,
ACT_PROJ_ID as out_ECTL_PROJ_ID,
ECTL_ACTIVE_IND as out_ECTL_ACTIVE_IND,
CURRENT_TIMESTAMP as out_ECTL_INS_TS,
CASE WHEN ( jnr_TRG_TGT.RECORD_CNT - jnr_TRG_TGT.TGT_CNT ) <> 0 THEN TGT_NM || '' - AUDIT FAILED'' ELSE TGT_NM || '' - AUDIT PASSED'' END as out_ECTL_MSG_TEXT,
jnr_TRG_TGT.source_record_id
FROM
jnr_TRG_TGT
);


-- Component mplt_LKP_CTRL_TBLS_VALIDATION, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_CTRL_TBLS_VALIDATION, mapplet instance mplt_LKP_CTRL_TBLS_VALIDATION;


-- Component ECTL_AUDIT_LOG_INS, Type TARGET 
INSERT INTO DB_T_CTRL_FIN_PROD.ECTL_AUDIT_LOG
(
ECTL_BATCH_ID,
ECTL_PRGM_ID,
ECTL_TABLE_ID,
ECTL_SRC_ROW_CNT,
ECTL_TRGT_INS_CNT,
ECTL_TRGT_UPD_CNT,
ECTL_TRGT_DEL_CNT,
ECTL_TRGT_REJ_CNT,
ECTL_MESSAGE_TXT,
ECTL_ORIG_INS_TS
)
SELECT
mplt_LKP_CTRL_TBLS_VALIDATION.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
mplt_LKP_CTRL_TBLS_VALIDATION.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
mplt_LKP_CTRL_TBLS_VALIDATION.out_ECTL_TABLE_ID as ECTL_TABLE_ID,
exp_RJCT_CNT.SRC_CNT as ECTL_SRC_ROW_CNT,
exp_RJCT_CNT.TGT_CNT as ECTL_TRGT_INS_CNT,
exp_RJCT_CNT.out_ECTL_UPD_CNT as ECTL_TRGT_UPD_CNT,
exp_RJCT_CNT.out_ECTL_DEL_CNT as ECTL_TRGT_DEL_CNT,
exp_RJCT_CNT.out_ECTL_RJCT_CNT as ECTL_TRGT_REJ_CNT,
exp_RJCT_CNT.out_ECTL_MSG_TEXT as ECTL_MESSAGE_TXT,
exp_RJCT_CNT.out_ECTL_INS_TS as ECTL_ORIG_INS_TS
FROM
exp_RJCT_CNT
INNER JOIN mplt_LKP_CTRL_TBLS_VALIDATION ON exp_RJCT_CNT.source_record_id = mplt_LKP_CTRL_TBLS_VALIDATION.source_record_id;


-- PIPELINE START FOR 2

-- Component sq_ECTL_AUDIT_LOG, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_ECTL_AUDIT_LOG AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_TRGT_REJ_CNT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT ECTL_AUDIT_LOG.ECTL_TRGT_REJ_CNT 
FROM
 DB_T_CTRL_FIN_PROD.ECTL_AUDIT_LOG
WHERE ECTL_BATCH_ID IN (SELECT ECTL_BATCH_ID FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_ACTIVE_IND=''$ECTL_ACTIVE_IND''  AND ECTL_PROJ_ID=''$ACT_PROJ_ID'')
AND ECTL_PRGM_ID IN (SELECT ECTL_PRGM_ID FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_INFO WHERE ECTL_PRGM_NM =''MAPPING_NM'')
AND ECTL_TABLE_ID IN (SELECT ECTL_TABLE_ID FROM DB_T_CTRL_FIN_PROD.ECTL_TABLE_XREF WHERE ECTL_TABLE_NM = ''TGT_NM'')
) SRC
)
);


-- Component exp_BALANCE, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_BALANCE AS
(
SELECT
CASE WHEN sq_ECTL_AUDIT_LOG.ECTL_TRGT_REJ_CNT <> 0 THEN RAISE_ERROR(''BALANCING FAILED FOR '' || TGT_NM) ELSE ''SUCCESS'' END as var_ERROR_FILE_MSG,
''SUCCESS'' as out_SUCCESS,
sq_ECTL_AUDIT_LOG.source_record_id
FROM
sq_ECTL_AUDIT_LOG
);


-- Component fil_NO_RECORD_PASS, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE fil_NO_RECORD_PASS AS
(
SELECT
exp_BALANCE.out_SUCCESS as SUCCESS,
exp_BALANCE.source_record_id
FROM
exp_BALANCE
WHERE exp_BALANCE.out_SUCCESS <> ''SUCCESS''
);


-- Component ECTL_AUDIT_LOG_INS_1, Type TARGET 
INSERT INTO DB_T_CTRL_FIN_PROD.ECTL_AUDIT_LOG
(
ECTL_MESSAGE_TXT
)
SELECT
fil_NO_RECORD_PASS.SUCCESS as ECTL_MESSAGE_TXT
FROM
fil_NO_RECORD_PASS;


-- PIPELINE END FOR 2

END; ';