-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_MEMBER_TRANSACTION2025("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE PMMAPPINGNAME varchar;
BEGIN 

PMMAPPINGNAME:='' ''; 

-- Component SQ_Shortcut_to_MEMBER, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_MEMBER AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMBER_NBR,
$2 as MEMBER_TYPE,
$3 as COUNTY_CODE,
$4 as STATUS,
$5 as DUES_AMT,
$6 as PAY_SOURCE,
$7 as PAID_TO_DATE,
$8 as GW_BILL_REF,
$9 as GW_DUE_DATE,
$10 as COMB_BILL_IND,
$11 as ALLOW_COMBINED_BILLING,
$12 as FOUR_DAY_LTR_IND,
$13 as OUT_OF_STATE,
$14 as COUNTY_CHG_IND,
$15 as DATE_BILLED,
$16 as DATE_PAID,
$17 as DATE_CANCELLED,
$18 as COUNTY_PAID_DT,
$19 as LAST_UPDATE_TS,
$20 as STD_COUNTY_CD,
$21 as STD_COUNTY_NAME,
$22 as COUNTY_NAME,
$23 as FONTEVA_STATUS,
$24 as MEMB_SKEY,
$25 as MEMB_EFF_DT,
$26 as TGT_MEMB_SKEY1,
$27 as TGT_MEMB_EFF_DT1,
$28 as TGT_STATUS_CD,
$29 as TGT_DATE_BILLED,
$30 as TGT_DATE_PAID1,
$31 as TGT_DATE_CANCELLED1,
$32 as REC_TYPE,
$33 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT  MBR_MEMBER_NBR  	,
 MBR_MEMBER_TYPE 	,
 MBR_COUNTY_CODE 	,
 MBR_STATUS	,
 MBR_DUES_AMT 	,
 MBR_PAY_SOURCE 	,
 MBR_PAID_TO_DATE 	,
 MBR_GW_BILL_REF 	,
 MBR_GW_DUE_DATE 	,
 MBR_COMB_BILL_IND 	,
 MBR_ALLOW_COMBINED_BILLING 	,
 MBR_FOUR_DAY_LTR_IND 	,
 MBR_OUT_OF_STATE 	,
 MBR_COUNTY_CHG_IND 	,
 MBR_DATE_BILLED 	,
 MBR_DATE_PAID	,
 MBR_DATE_CANCELLED 	,
 MBR_COUNTY_PAID_DT 	,
 MBR_LasT_UPDATE_TS 	,
 MBR_STD_COUNTY_CD 	,
 MBR_STD_COUNTY_NAME 	,
 MBR_COUNTY_NAME  	,
 MBR_FONTEVA_STATUS	,
 MSTR_MEMB_SKEY	,
 MSTR_MEMB_EFF_DT	,
 TGT_MEMB_SKEY,
 TGT_MEMB_EFF_DT,
TGT_STATUS_CD,
TGT_DATE_BILLED,
TGT_DATE_PAID,
TGT_DATE_CANCELLED,
OUT_FLAG
FROM
(
SELECT MBR.MEMBER_NBR  	AS MBR_MEMBER_NBR  	,
DB_T_SHRD_PROD.MEMBER_TYPE 	AS MBR_MEMBER_TYPE 	,
MBR.COUNTY_CODE 	AS MBR_COUNTY_CODE 	,
MBR.STATUS	AS MBR_STATUS	,
MBR.DUES_AMT 	AS MBR_DUES_AMT 	,
MBR.PAY_SOURCE 	AS MBR_PAY_SOURCE 	,
MBR.PAID_TO_DATE 	AS MBR_PAID_TO_DATE 	,
MBR.GW_BILL_REF 	AS MBR_GW_BILL_REF 	,
MBR.GW_DUE_DATE 	AS MBR_GW_DUE_DATE 	,
MBR.COMB_BILL_IND 	AS MBR_COMB_BILL_IND 	,
MBR.ALLOW_COMBINED_BILLING 	AS MBR_ALLOW_COMBINED_BILLING 	,
MBR.FOUR_DAY_LTR_IND 	AS MBR_FOUR_DAY_LTR_IND 	,
MBR.OUT_OF_STATE 	AS MBR_OUT_OF_STATE 	,
MBR.COUNTY_CHG_IND 	AS MBR_COUNTY_CHG_IND 	,
MBR.DATE_BILLED 	AS MBR_DATE_BILLED 	,
MBR.DATE_PAID	AS MBR_DATE_PAID	,
MBR.DATE_CANCELLED 	AS MBR_DATE_CANCELLED 	,
MBR.COUNTY_PAID_DT 	AS MBR_COUNTY_PAID_DT 	,
MBR.LAST_UPDATE_TS 	AS MBR_LAST_UPDATE_TS 	,
MBR.STD_COUNTY_CD 	AS MBR_STD_COUNTY_CD 	,
MBR.STD_COUNTY_NAME 	AS MBR_STD_COUNTY_NAME 	,
MBR.COUNTY_NAME  	AS MBR_COUNTY_NAME  	,
MBR.FONTEVA_STATUS	AS MBR_FONTEVA_STATUS	,
MSTR.MEMB_SKEY	AS MSTR_MEMB_SKEY	,
MSTR.MEMB_EFF_DT	AS MSTR_MEMB_EFF_DT	,
TGT.MEMB_SKEY AS TGT_MEMB_SKEY,
TGT.CHG_EFF_DT AS TGT_MEMB_EFF_DT,
TGT.STATUS_CD AS TGT_STATUS_CD,
TGT.DATE_BILLED AS TGT_DATE_BILLED,
TGT.DATE_PAID AS TGT_DATE_PAID,
TGT.DATE_CANCELLED AS TGT_DATE_CANCELLED
,Coalesce(Trim(DB_T_SHRD_PROD.MEMBER_TYPE),''~'') AS LG_MEMBER_TYPE
,Coalesce(Trim(MBR.COUNTY_CODE),''~'')  AS LG_COUNTY_CODE
,Coalesce(Trim(MBR.STATUS),''~'')   AS LG_STATUS
,Coalesce(Cast(MBR.DUES_AMT AS INTEGER),''0'')  AS LG_DUE_aMT
,Coalesce(To_Date(MBR.PAID_TO_Date,''YYYY-MM-DD''),To_Date(''1900-01-01'',''YYYY-MM-DD''))  AS LG_PAID_TO_Date
,Coalesce(MBR.COUNTY_PAID_DT,To_Date(''1900-01-01'',''YYYY-MM-DD''))  AS LG_COUNTY_PAID_DT
,Coalesce(Trim(MBR.PAY_SOURCE),''~'')   AS LG_PAY_SOURCE
,Coalesce(Trim(MBR.OUT_OF_STATE),''~'')   AS LG_OUT_OF_STATE
,Coalesce(Trim(MBR.COUNTY_CHG_IND),''~'')  AS LG_COUNTY_CHG_IND
,Coalesce(Trim(MBR.GW_BILL_REF),''~'')  AS LG_GW_BILL_REF
,Coalesce(MBR.GW_DUE_DATE,To_Date(''1900-01-01'',''YYYY-MM-DD''))  AS LG_GW_DUE_DATE
,Coalesce(Trim(MBR.COMB_BILL_IND),''~'')   AS LG_COMB_BILL_IND
,Coalesce(Trim(MBR.ALLOW_COMBINED_BILLING),''~'')  AS LG_ALLOW_COMBINED_BILLING
,Coalesce(Trim(MBR.FOUR_DAY_LTR_IND),''~'')  AS LG_FOUR_DAY_LTR_IND
,Coalesce(Trim(MBR.STD_COUNTY_CD),''~'')   AS LG_STD_COUNTY_CD
,Coalesce(Trim(MBR.STD_COUNTY_NAME),''~'')  AS LG_STD_COUNTY_NAME
,Coalesce(Trim(Upper(MBR.COUNTY_NAME)),''~'')  AS LG_COUNTY_NAME
,Coalesce(Trim(MBR.FONTEVA_STATUS),''~'')  AS LG_FONTEVA_STATUS
,
Cast(Coalesce(Trim(DB_T_SHRD_PROD.MEMBER_TYPE),''~'')||
Coalesce(Trim(MBR.COUNTY_CODE),''~'')|| 
Coalesce(Trim(MBR.STATUS),''~'') ||
Coalesce(Cast(Round(MBR.DUES_AMT ) AS INTEGER),''0'')||
Coalesce(To_Date(MBR.PAID_TO_Date,''YYYY-MM-DD''),To_Date(''1900-01-01'',''YYYY-MM-DD''))||
Coalesce(MBR.COUNTY_PAID_DT,To_Date(''1900-01-01'',''YYYY-MM-DD''))||
Coalesce(Trim(MBR.PAY_SOURCE),''~'') ||
Coalesce(Trim(MBR.OUT_OF_STATE),''~'') ||
Coalesce(Trim(MBR.COUNTY_CHG_IND),''~'')|| 
Coalesce(Trim(MBR.GW_BILL_REF),''~'')||
Coalesce(MBR.GW_DUE_DATE,To_Date(''1900-01-01'',''YYYY-MM-DD''))||
Coalesce(Trim(MBR.COMB_BILL_IND),''~'') ||
Coalesce(Trim(MBR.ALLOW_COMBINED_BILLING),''~'')||
Coalesce(Trim(MBR.FOUR_DAY_LTR_IND),''~'')||
Coalesce(Trim(MBR.STD_COUNTY_CD),''~'') ||
Coalesce(Trim(MBR.STD_COUNTY_NAME),''~'')||
Coalesce(Trim(Upper(MBR.COUNTY_NAME)),''~'') ||
Coalesce(Trim(MBR.FONTEVA_STATUS),''~'') AS VARCHAR(500)
) AS SRC_MD5

 ,Cast(Coalesce(Trim(TGT.MEMB_TYPE),''~'')||		        
Coalesce(Trim(TGT.COUNTY_CD),''~'')||
Coalesce(Trim(TGT.STATUS_CD),''~'')||	
Coalesce(TGT.AMT_PAID,''0'')|| 	
Coalesce(TGT.PAID_TO_DT ,To_Date(''1900-01-01'',''YYYY-MM-DD''))||	
Coalesce(TGT.COUNTY_PAID_DT,To_Date(''1900-01-01'',''YYYY-MM-DD''))||	
Coalesce(Trim(TGT.FED_SRC)	,''~'')||	
CASE WHEN Trim(TGT.OUT_OF_STATE) ='''' THEN ''~'' ELSE Coalesce(Trim(TGT.OUT_OF_STATE),''~'')END||	
Coalesce(Trim(TGT.COUNTY_CHG_IND),''~'')||
Coalesce(Trim(TGT.GW_BILL_REF),''~'')|| 	
Coalesce(TGT.GW_DUE_DATE ,To_Date(''1900-01-01'',''YYYY-MM-DD''))|| 	
Coalesce(Trim(TGT.COMB_BILL_IND),''~'')|| 	
Coalesce(Trim(TGT.ALLOW_COMBINED_BILLING),''~'')||
Coalesce(Trim(TGT.FOUR_DAY_LTR_IND)	,''~'')|| 	
Coalesce(Trim(TGT.STD_COUNTY_CD),''~'')|| 	
Coalesce(Trim(TGT.STD_COUNTY_NAME),''~'')||	
Coalesce(Trim(Upper(TGT.COUNTY_NAME)),''~'')||
Coalesce(Trim(TGT.FONTEVA_STATUS),''~'')AS VARCHAR(500)) AS TGT_MD5

,Lag(LG_MEMBER_TYPE,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC ) AS PR_LG_MEMBER_TYPE
,Lag(LG_COUNTY_CODE,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS  ASC) AS PR_LG_COUNTY_CODE
,Lag(LG_STATUS,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC) AS PR_LG_STATUS
,Lag(LG_DUE_aMT,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC) AS PR_LG_DUE_aMT
,Lag(LG_PAID_TO_Date,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS  ASC) AS PR_LG_PAID_TO_Date
,Lag(LG_COUNTY_PAID_DT,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS  ASC) AS PR_LG_COUNTY_PAID_DT
,Lag(LG_PAY_SOURCE,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC) AS PR_LG_PAY_SOURCE
,Lag(LG_OUT_OF_STATE,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC ) AS PR_LG_OUT_OF_STATE
,Lag(LG_COUNTY_CHG_IND,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC) AS PR_LG_COUNTY_CHG_IND
,Lag(LG_GW_BILL_REF,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC) AS PR_LG_GW_BILL_REF
,Lag(LG_GW_DUE_DATE,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC) AS PR_LG_GW_DUE_DATE
,Lag(LG_COMB_BILL_IND,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC ) AS PR_LG_COMB_BILL_IND
,Lag(LG_ALLOW_COMBINED_BILLING,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC) AS PR_LG_ALLOW_COMBINED_BILLING
,Lag(LG_FOUR_DAY_LTR_IND,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC ) AS PR_LG_FOUR_DAY_LTR_IND
,Lag(LG_STD_COUNTY_CD,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC ) AS PR_LG_STD_COUNTY_CD
,Lag(LG_STD_COUNTY_NAME,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC ) AS PR_LG_STD_COUNTY_NAME
,Lag(LG_COUNTY_NAME,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC ) AS PR_LG_COUNTY_NAME
,Lag(LG_FONTEVA_STATUS,1) Over (PARTITION BY MBR.MEMBER_NBR  ORDER BY MBR.LAST_UPDATE_TS ASC ) AS PR_LG_FONTEVA_STATUS
,Cast(PR_LG_MEMBER_TYPE||PR_LG_COUNTY_CODE||PR_LG_STATUS||PR_LG_DUE_aMT||PR_LG_PAID_TO_Date||PR_LG_COUNTY_PAID_DT||PR_LG_PAY_SOURCE||PR_LG_OUT_OF_STATE||PR_LG_COUNTY_CHG_IND||PR_LG_GW_BILL_REF||PR_LG_GW_DUE_DATE||PR_LG_COMB_BILL_IND||PR_LG_ALLOW_COMBINED_BILLING||PR_LG_FOUR_DAY_LTR_IND||PR_LG_STD_COUNTY_CD||PR_LG_STD_COUNTY_NAME||PR_LG_COUNTY_NAME||PR_LG_FONTEVA_STATUS AS VARCHAR(500)) AS PR_MD5

,Rank () Over (PARTITION BY MBR_MEMBER_NBR ORDER BY MBR_LAST_UPDATE_TS ASC) frt_rank,

CASE WHEN tgt.MEMB_SKEY IS NULL AND frt_rank=1 THEN ''I''
WHEN PR_MD5 <> SRC_MD5   AND frt_rank<>1 AND MBR.LAST_UPDATE_TS> Coalesce(TGT.CHG_EFF_DT  ,Cast(''1900-01-01 00:00:00.000000'' AS TIMESTAMP)) THEN ''I''
WHEN Trim(TGT_MD5) <> Trim(SRC_MD5)  AND  frt_rank =1 AND MBR.LAST_UPDATE_TS> Coalesce(TGT.CHG_EFF_DT ,Cast(''1900-01-01 00:00:00.000000'' AS TIMESTAMP))  THEN ''I''
ELSE ''R'' END AS OUT_FLAG
FROM DB_T_STAG_MEMBXREF_PROD.MEMBER MBR
JOIN DB_T_CORE_PROD.MEMBER_MSTR MSTR
ON MBR.MEMBER_NBR =MSTR.MEMB_NUM
LEFT OUTER JOIN (SELECT * FROM DB_T_CORE_PROD.MEMBER_TRANS TGT WHERE  Cast(TGT.CHG_EXP_DT AS DATE) = ''9999-12-31'')TGT
ON MSTR.MEMB_SKEY = TGT.MEMB_SKEY
WHERE 1=1
--AND MBR.LAST_UPDATE_TS > $federation_start_dttm AND MBR.LAST_UPDATE_TS <= $federation_end_dttm
AND Cast(MSTR.MEMB_EXP_DT AS DATE) = ''9999-12-31''
)A
) SRC
)
);


-- Component exp_Source, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Source AS
(
SELECT
SQ_Shortcut_to_MEMBER.TGT_MEMB_SKEY1 as TGT_MEMB_SKEY,
SQ_Shortcut_to_MEMBER.MEMBER_TYPE as FED_TYPE,
SQ_Shortcut_to_MEMBER.COUNTY_CODE as COUNTY,
SQ_Shortcut_to_MEMBER.STATUS as STATUS,
SQ_Shortcut_to_MEMBER.DUES_AMT as AMOUNT_PAID,
CASE WHEN is_date ( SQ_Shortcut_to_MEMBER.PAID_TO_DATE , ''YYYY-MM-DD'' ) THEN to_date ( SQ_Shortcut_to_MEMBER.PAID_TO_DATE , ''YYYY-MM-DD'' ) ELSE NULL END as out_PAID_TO_DATE,
SQ_Shortcut_to_MEMBER.COUNTY_PAID_DT as out_COPAY_DATE,
SQ_Shortcut_to_MEMBER.PAY_SOURCE as FED_SOURCE,
SQ_Shortcut_to_MEMBER.OUT_OF_STATE as OUT_OF_STATE,
SQ_Shortcut_to_MEMBER.COUNTY_CHG_IND as COUNTY_CHG_IND,
NULL as TX_CD,
NULL as FEED_IND,
SQ_Shortcut_to_MEMBER.LAST_UPDATE_TS as out_CHG_EFF_DT,
4 as out_PROJ_ID,
''Y'' as out_BATCH_IND,
PMMappingName as out_PRGM_NM,
''MEMBER_TRANS'' as out_TABLE_NM,
To_Char ( SQ_Shortcut_to_MEMBER.DATE_BILLED , ''YYYYMMDD'' ) as v_DATE_BILLED,
substr ( v_DATE_BILLED , 1 , 4 ) as out_DB_YYYY,
substr ( v_DATE_BILLED , 5 , 2 ) as out_DB_MM,
substr ( v_DATE_BILLED , 7 , 2 ) as out_DB_DD,
To_Char ( SQ_Shortcut_to_MEMBER.DATE_PAID , ''YYYYMMDD'' ) as v_DATE_PAID,
substr ( v_DATE_PAID , 1 , 4 ) as out_DP_YYYY,
substr ( v_DATE_PAID , 5 , 2 ) as out_DP_MM,
substr ( v_DATE_PAID , 7 , 2 ) as out_DP_DD,
To_Char ( SQ_Shortcut_to_MEMBER.DATE_CANCELLED , ''YYYYMMDD'' ) as v_DATE_CANCELLED,
substr ( v_DATE_CANCELLED , 1 , 4 ) as out_DC_YYYY,
substr ( v_DATE_CANCELLED , 5 , 2 ) as out_DC_MM,
substr ( v_DATE_CANCELLED , 7 , 2 ) as out_DC_DD,
SQ_Shortcut_to_MEMBER.GW_BILL_REF as GW_BILL_REF,
SQ_Shortcut_to_MEMBER.GW_DUE_DATE as out_GW_DUE_DATE,
To_Char ( SQ_Shortcut_to_MEMBER.GW_DUE_DATE , ''YYYYMMDD'' ) as v_GW_DUE_DATE_test1,
SQ_Shortcut_to_MEMBER.COMB_BILL_IND as COMB_BILL_IND,
SQ_Shortcut_to_MEMBER.ALLOW_COMBINED_BILLING as ALLOW_COMBINED_BILLING,
SQ_Shortcut_to_MEMBER.FOUR_DAY_LTR_IND as FOUR_DAY_LTR_IND,
SQ_Shortcut_to_MEMBER.STD_COUNTY_CD as STD_COUNTY_CD,
SQ_Shortcut_to_MEMBER.STD_COUNTY_NAME as STD_COUNTY_NAME,
SQ_Shortcut_to_MEMBER.COUNTY_NAME as COUNTY_NAME,
SQ_Shortcut_to_MEMBER.FONTEVA_STATUS as FONTEVA_STATUS,
SQ_Shortcut_to_MEMBER.TGT_STATUS_CD as TGT_STATUS_CD,
SQ_Shortcut_to_MEMBER.TGT_DATE_BILLED as TGT_DATE_BILLED,
SQ_Shortcut_to_MEMBER.TGT_DATE_PAID1 as TGT_DATE_PAID1,
SQ_Shortcut_to_MEMBER.TGT_DATE_CANCELLED1 as TGT_DATE_CANCELLED1,
SQ_Shortcut_to_MEMBER.REC_TYPE as REC_TYPE,
SQ_Shortcut_to_MEMBER.MEMB_SKEY as MEMB_SKEY,
SQ_Shortcut_to_MEMBER.MEMB_EFF_DT as MEMB_EFF_DT,
SQ_Shortcut_to_MEMBER.source_record_id
FROM
SQ_Shortcut_to_MEMBER
);


-- Component m_validate_date_DC, Type MAPPLET 
--MAPPLET NOT REGISTERED: m_validate_date, mapplet instance m_validate_date_DC;


-- Component m_lkp_Control_Tables, Type MAPPLET 
--MAPPLET NOT REGISTERED: m_lkp_Control_Tables, mapplet instance m_lkp_Control_Tables;


-- Component m_validate_date_DP, Type MAPPLET 
--MAPPLET NOT REGISTERED: m_validate_date, mapplet instance m_validate_date_DP;


-- Component m_validate_date_DB, Type MAPPLET 
--MAPPLET NOT REGISTERED: m_validate_date, mapplet instance m_validate_date_DB;


-- Component rtr_Member_Trans_NEW, Type ROUTER Output Group NEW
SELECT
exp_Source.TGT_MEMB_SKEY as MEMB_SKEY_SRC,
exp_Source.FED_TYPE as FED_TYPE_SRC,
exp_Source.COUNTY as COUNTY_SRC,
exp_Source.STATUS as STATUS_SRC,
exp_Source.AMOUNT_PAID as AMOUNT_PAID_SRC,
exp_Source.out_PAID_TO_DATE as PAID_TO_DATE_SRC,
exp_Source.out_COPAY_DATE as COPAY_DATE_SRC,
exp_Source.FED_SOURCE as FED_SOURCE_SRC,
exp_Source.OUT_OF_STATE as OUT_OF_STATE_SRC,
exp_Source.COUNTY_CHG_IND as COUNTY_CHG_IND_SRC,
exp_Source.TX_CD as TX_CD,
exp_Source.out_CHG_EFF_DT as CHG_EFF_DT,
exp_Source.FEED_IND as FEED_IND,
m_validate_date_DB.out_DATE_DT as DATE_BILLED_DELTA,
m_validate_date_DP.out_DATE_DT as DATE_PAID_DELTA,
m_validate_date_DC.out_DATE_DT as DATE_CANCELLED_DELTA,
m_lkp_Control_Tables.mplt_BATCH_ID as mplt_BATCH_ID,
m_lkp_Control_Tables.mplt_PRGM_ID as mplt_PRGM_ID,
m_lkp_Control_Tables.mplt_TABLE_ID as mplt_TABLE_ID,
m_lkp_Control_Tables.mplt_PROJ_ID as mplt_PROJ_ID,
exp_Source.GW_BILL_REF as GW_BILL_REF_SRC,
exp_Source.out_GW_DUE_DATE as GW_DUE_DATE_SRC,
exp_Source.COMB_BILL_IND as COMB_BILL_IND_SRC,
exp_Source.ALLOW_COMBINED_BILLING as ALLOW_COMBINED_BILLING_SRC,
exp_Source.FOUR_DAY_LTR_IND as FOUR_DAY_LTR_IND_SRC,
exp_Source.STD_COUNTY_CD as STD_COUNTY_CD,
exp_Source.STD_COUNTY_NAME as STD_COUNTY_NAME,
exp_Source.COUNTY_NAME as COUNTY_NAME,
exp_Source.FONTEVA_STATUS as FONTEVA_STATUS,
exp_Source.REC_TYPE as REC_TYPE,
exp_Source.TGT_STATUS_CD as TGT_STATUS_CD,
exp_Source.TGT_DATE_BILLED as TGT_DATE_BILLED,
exp_Source.TGT_DATE_PAID1 as TGT_DATE_PAID1,
exp_Source.TGT_DATE_CANCELLED1 as TGT_DATE_CANCELLED1,
exp_Source.REC_TYPE as REC_TYPE4,
exp_Source.MEMB_SKEY as MEMB_SKEY,
exp_Source.MEMB_EFF_DT as MEMB_EFF_DT,
exp_Source.source_record_id
FROM
exp_Source
LEFT JOIN m_validate_date_DC ON exp_Source.source_record_id = m_validate_date_DC.source_record_id
LEFT JOIN m_lkp_Control_Tables ON m_validate_date_DC.source_record_id = m_lkp_Control_Tables.source_record_id
LEFT JOIN m_validate_date_DP ON m_lkp_Control_Tables.source_record_id = m_validate_date_DP.source_record_id
LEFT JOIN m_validate_date_DB ON m_validate_date_DP.source_record_id = m_validate_date_DB.source_record_id
WHERE exp_Source.REC_TYPE = ''I'';


-- Component exp_INS_Member_Trans, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_INS_Member_Trans AS
(
SELECT
rtr_Member_Trans_NEW.MEMB_SKEY as MEMB_SKEY,
rtr_Member_Trans_NEW.CHG_EFF_DT as CHG_EFF_DT,
to_date ( ''12/31/9999 23:59:59.999999'' , ''MM/DD/YYYY HH24:MI:SS.FF6'' ) as out_CHG_EXP_DT,
rtr_Member_Trans_NEW.FED_TYPE_SRC as FED_TYPE,
rtr_Member_Trans_NEW.COUNTY_SRC as COUNTY,
rtr_Member_Trans_NEW.STATUS_SRC as STATUS,
CASE WHEN STATUS_CD_MTLKP1 != rtr_Member_Trans_NEW.STATUS_SRC THEN STATUS_CD_MTLKP1 ELSE rtr_Member_Trans_NEW.TGT_STATUS_CD END as out_PREV_STATUS,
rtr_Member_Trans_NEW.AMOUNT_PAID_SRC as AMOUNT_PAID,
rtr_Member_Trans_NEW.PAID_TO_DATE_SRC as PAID_TO_DATE,
rtr_Member_Trans_NEW.COPAY_DATE_SRC as COPAY_DATE,
CASE WHEN ltrim ( rtrim ( rtr_Member_Trans_NEW.FED_SOURCE_SRC ) ) IS NULL THEN null ELSE ltrim ( rtrim ( rtr_Member_Trans_NEW.FED_SOURCE_SRC ) ) END as out_FED_SOURCE,
CASE WHEN ltrim ( rtrim ( rtr_Member_Trans_NEW.OUT_OF_STATE_SRC ) ) IS NULL THEN null ELSE ltrim ( rtrim ( rtr_Member_Trans_NEW.OUT_OF_STATE_SRC ) ) END as out_OUT_OF_STATE,
CASE WHEN ltrim ( rtrim ( rtr_Member_Trans_NEW.COUNTY_CHG_IND_SRC ) ) IS NULL THEN null ELSE ltrim ( rtrim ( rtr_Member_Trans_NEW.COUNTY_CHG_IND_SRC ) ) END as out_COUNTY_CHG_IND,
rtr_Member_Trans_NEW.mplt_BATCH_ID as INS_BATCH_ID,
rtr_Member_Trans_NEW.mplt_PRGM_ID as INS_PRGM_ID,
CASE WHEN ( DATE_BILLED_MTLKP1 IS NULL or rtr_Member_Trans_NEW.DATE_BILLED_DELTA > DATE_BILLED_MTLKP1 ) THEN rtr_Member_Trans_NEW.DATE_BILLED_DELTA ELSE DATE_BILLED_MTLKP1 END as out_DATE_BILLED,
CASE WHEN ( DATE_CANCELLED_LKP1 IS NULL or rtr_Member_Trans_NEW.DATE_CANCELLED_DELTA > DATE_CANCELLED_LKP1 ) THEN rtr_Member_Trans_NEW.DATE_CANCELLED_DELTA ELSE DATE_CANCELLED_LKP1 END as out_DATE_CANCELLED,
CASE WHEN ( DATE_PAID_MT_LKP1 IS NULL or rtr_Member_Trans_NEW.DATE_PAID_DELTA > DATE_PAID_MT_LKP1 ) THEN rtr_Member_Trans_NEW.DATE_PAID_DELTA ELSE DATE_PAID_MT_LKP1 END as out_DATE_PAID,
rtr_Member_Trans_NEW.GW_BILL_REF_SRC as GW_BILL_REF_SRC1,
rtr_Member_Trans_NEW.GW_DUE_DATE_SRC as GW_DUE_DATE_SRC1,
rtr_Member_Trans_NEW.COMB_BILL_IND_SRC as COMB_BILL_IND_SRC1,
rtr_Member_Trans_NEW.ALLOW_COMBINED_BILLING_SRC as ALLOW_COMBINED_BILLING_SRC1,
rtr_Member_Trans_NEW.FOUR_DAY_LTR_IND_SRC as FOUR_DAY_LTR_IND_SRC1,
rtr_Member_Trans_NEW.STD_COUNTY_CD as STD_COUNTY_CD1,
rtr_Member_Trans_NEW.STD_COUNTY_NAME as STD_COUNTY_NAME1,
rtr_Member_Trans_NEW.COUNTY_NAME as COUNTY_NAME1,
rtr_Member_Trans_NEW.FONTEVA_STATUS as FONTEVA_STATUS1,
rtr_Member_Trans_NEW.source_record_id
FROM
rtr_Member_Trans_NEW
);


-- Component MEMBER_TRANS_INS, Type TARGET 
INSERT INTO DB_T_CORE_PROD.MEMBER_TRANS
(
MEMB_SKEY,
CHG_EFF_DT,
CHG_EXP_DT,
MEMB_TYPE,
COUNTY_CD,
STATUS_CD,
AMT_PAID,
PAID_TO_DT,
COUNTY_PAID_DT,
FED_SRC,
OUT_OF_STATE,
COUNTY_CHG_IND,
PREV_STATUS_CD,
DATE_BILLED,
DATE_PAID,
DATE_CANCELLED,
ECTL_INS_BATCH_ID,
ECTL_INS_PRGM_ID,
GW_BILL_REF,
GW_DUE_DATE,
COMB_BILL_IND,
ALLOW_COMBINED_BILLING,
FOUR_DAY_LTR_IND,
STD_COUNTY_CD,
STD_COUNTY_NAME,
COUNTY_NAME,
FONTEVA_STATUS
)
SELECT
exp_INS_Member_Trans.MEMB_SKEY as MEMB_SKEY,
exp_INS_Member_Trans.CHG_EFF_DT as CHG_EFF_DT,
exp_INS_Member_Trans.out_CHG_EXP_DT as CHG_EXP_DT,
exp_INS_Member_Trans.FED_TYPE as MEMB_TYPE,
exp_INS_Member_Trans.COUNTY as COUNTY_CD,
exp_INS_Member_Trans.STATUS as STATUS_CD,
exp_INS_Member_Trans.AMOUNT_PAID as AMT_PAID,
exp_INS_Member_Trans.PAID_TO_DATE as PAID_TO_DT,
exp_INS_Member_Trans.COPAY_DATE as COUNTY_PAID_DT,
exp_INS_Member_Trans.out_FED_SOURCE as FED_SRC,
exp_INS_Member_Trans.out_OUT_OF_STATE as OUT_OF_STATE,
exp_INS_Member_Trans.out_COUNTY_CHG_IND as COUNTY_CHG_IND,
exp_INS_Member_Trans.out_PREV_STATUS as PREV_STATUS_CD,
exp_INS_Member_Trans.out_DATE_BILLED as DATE_BILLED,
exp_INS_Member_Trans.out_DATE_PAID as DATE_PAID,
exp_INS_Member_Trans.out_DATE_CANCELLED as DATE_CANCELLED,
exp_INS_Member_Trans.INS_BATCH_ID as ECTL_INS_BATCH_ID,
exp_INS_Member_Trans.INS_PRGM_ID as ECTL_INS_PRGM_ID,
exp_INS_Member_Trans.GW_BILL_REF_SRC1 as GW_BILL_REF,
exp_INS_Member_Trans.GW_DUE_DATE_SRC1 as GW_DUE_DATE,
exp_INS_Member_Trans.COMB_BILL_IND_SRC1 as COMB_BILL_IND,
exp_INS_Member_Trans.ALLOW_COMBINED_BILLING_SRC1 as ALLOW_COMBINED_BILLING,
exp_INS_Member_Trans.FOUR_DAY_LTR_IND_SRC1 as FOUR_DAY_LTR_IND,
exp_INS_Member_Trans.STD_COUNTY_CD1 as STD_COUNTY_CD,
exp_INS_Member_Trans.STD_COUNTY_NAME1 as STD_COUNTY_NAME,
exp_INS_Member_Trans.COUNTY_NAME1 as COUNTY_NAME,
exp_INS_Member_Trans.FONTEVA_STATUS1 as FONTEVA_STATUS
FROM
exp_INS_Member_Trans;


-- Component MEMBER_TRANS_INS, Type Post SQL 
UPDATE MEMBER_TRANS 
FROM (
SELECT DISTINCT MEMB_SKEY,CHG_EFF_DT
,Max(CHG_EFF_DT) Over (PARTITION BY MEMB_SKEY ORDER BY CHG_EFF_DT ASC  ROWS BETWEEN 1 Following AND 1 Following ) - 1 -- - INTERVAL ''1'' SECOND AS LEAD1
FROM member_trans
) A
SET CHG_EXP_DT = A.LEAD1
WHERE MEMBER_TRANS.CHG_EFF_DT = A.CHG_EFF_DT
AND MEMBER_TRANS.MEMB_SKEY= A.MEMB_SKEY
AND Cast(MEMBER_TRANS.CHG_EXP_DT AS DATE) = ''9999-12-31''
AND LEAD1 IS NOT NULL;


END; ';