-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_AUT_FIN_PREMIUM_TXN("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
	run_id STRING;
	workflow_name STRING;
	session_name STRING;
	PMMappingName STRING;
	ACT_PROJ_ID STRING;
	ECTL_ACTIVE_IND STRING;
	TableName STRING;
	REPOS_CD STRING;
	v_start_time TIMESTAMP;
BEGIN
	run_id := (SELECT run_id FROM control_run_id WHERE worklet_name = :worklet_name ORDER BY insert_ts DESC LIMIT 1);
	workflow_name := (SELECT workflow_name FROM control_run_id WHERE worklet_name = :worklet_name ORDER BY insert_ts DESC LIMIT 1);
	session_name := ''s_m_AUT_FIN_PREMIUM_TXN'';
	PMMappingName := sp_get_scoped_param(:run_id, ''PMMappingName'', :workflow_name, :worklet_name, :session_name);
	ACT_PROJ_ID := sp_get_scoped_param(:run_id, ''ACT_PROJ_ID'', :workflow_name, :worklet_name, :session_name);
	ECTL_ACTIVE_IND := sp_get_scoped_param(:run_id, ''ECTL_ACTIVE_IND'', :workflow_name, :worklet_name, :session_name);
	TableName := sp_get_scoped_param(:run_id, ''TableName'', :workflow_name, :worklet_name, :session_name);
	REPOS_CD := sp_get_scoped_param(:run_id, ''REPOS_CD'', :workflow_name, :worklet_name, :session_name);
	v_start_time := CURRENT_TIMESTAMP();

-- Component sq_STG_FIN_AUT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_FIN_AUT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as BUSINESS_UNIT,
$2 as LEDGER,
$3 as FISCAL_YEAR,
$4 as ACCOUNTING_PERIOD,
$5 as ACCOUNT_NBR,
$6 as DEPTID,
$7 as PRODUCT,
$8 as PROJECT_ID,
$9 as CHARTFIELD1,
$10 as CHARTFIELD2,
$11 as CHARTFIELD3,
$12 as ALF_POL_PREFIX,
$13 as ALF_POL_NUMBER,
$14 as ALF_AGENT_NO,
$15 as ALF_SERV_CTR_NBR,
$16 as ALF_COMPANY_CD,
$17 as GL_DISTRIB_STATUS,
$18 as MONETARY_AMOUNT,
$19 as ALF_POL_EFF_DATE,
$20 as ALF_POL_EXP_DATE,
$21 as ALF_TOT_PREM,
$22 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT TRIM(STG_FIN_AUT.BUSINESS_UNIT), TRIM(STG_FIN_AUT.LEDGER), STG_FIN_AUT.FISCAL_YEAR, STG_FIN_AUT.ACCOUNTING_PERIOD, TRIM(STG_FIN_AUT.ACCOUNT_NBR), TRIM(STG_FIN_AUT.DEPTID), TRIM(STG_FIN_AUT.PRODUCT), TRIM(STG_FIN_AUT.PROJECT_ID), TRIM(STG_FIN_AUT.CHARTFIELD1), TRIM(STG_FIN_AUT.CHARTFIELD2), TRIM(STG_FIN_AUT.CHARTFIELD3), TRIM(STG_FIN_AUT.ALF_POL_PREFIX), TRIM(STG_FIN_AUT.ALF_POL_NUMBER), TRIM(STG_FIN_AUT.ALF_AGENT_NO), TRIM(STG_FIN_AUT.ALF_SERV_CTR_NBR), TRIM(STG_FIN_AUT.ALF_COMPANY_CD), TRIM(STG_FIN_AUT.GL_DISTRIB_STATUS), STG_FIN_AUT.MONETARY_AMOUNT, STG_FIN_AUT.ALF_POL_EFF_DATE, STG_FIN_AUT.ALF_POL_EXP_DATE, STG_FIN_AUT.ALF_TOT_PREM

FROM

DB_T_STAG_FIN_PROD.STG_FIN_AUT

WHERE

GL_DISTRIB_STATUS=''D''
) SRC
)
);


-- Component exp_GET_DATA, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_GET_DATA AS
(
SELECT
substr ( sq_STG_FIN_AUT.BUSINESS_UNIT , 1 , 3 ) as CMPY_CD,
sq_STG_FIN_AUT.CHARTFIELD1 as ST_CD,
CASE 
  WHEN TRY_TO_NUMBER(sq_STG_FIN_AUT.ALF_SERV_CTR_NBR) IS NOT NULL 
    THEN TO_CHAR(TO_NUMBER(sq_STG_FIN_AUT.ALF_SERV_CTR_NBR)) 
  ELSE sq_STG_FIN_AUT.ALF_SERV_CTR_NBR 
END AS out_SVC_NBR,
CASE 
  WHEN TRY_TO_NUMBER(sq_STG_FIN_AUT.ALF_AGENT_NO) IS NOT NULL 
    THEN TO_CHAR(TO_NUMBER(sq_STG_FIN_AUT.ALF_AGENT_NO)) 
  ELSE sq_STG_FIN_AUT.ALF_AGENT_NO 
END AS out_AGNT_NBR,
sq_STG_FIN_AUT.ALF_COMPANY_CD as CMPY_TYPE_CD,
CASE 
    WHEN LENGTH(LTRIM(RTRIM(sq_STG_FIN_AUT.ALF_POL_PREFIX))) = 1 
        THEN LTRIM(RTRIM(sq_STG_FIN_AUT.ALF_POL_PREFIX)) || ''00000'' 
    ELSE LTRIM(RTRIM(sq_STG_FIN_AUT.ALF_POL_PREFIX)) || ''0000'' 
END AS var_PRODUCT_CD,
CASE 
    WHEN LTRIM(RTRIM(sq_STG_FIN_AUT.PRODUCT)) IS NULL 
         OR LTRIM(RTRIM(sq_STG_FIN_AUT.PRODUCT)) = '''' 
        THEN ''A00000'' 
    WHEN LTRIM(RTRIM(sq_STG_FIN_AUT.PRODUCT)) = ''NO_PRD'' 
        THEN CASE 
            WHEN LTRIM(RTRIM(sq_STG_FIN_AUT.ALF_POL_PREFIX)) IN (''G'', ''N'') 
                THEN ''A00000'' 
            WHEN LTRIM(RTRIM(sq_STG_FIN_AUT.ALF_POL_PREFIX)) = ''B'' 
                THEN ''C00001'' 
            ELSE 
                CASE 
                    WHEN LENGTH(LTRIM(RTRIM(sq_STG_FIN_AUT.ALF_POL_PREFIX))) = 1 
                        THEN LTRIM(RTRIM(sq_STG_FIN_AUT.ALF_POL_PREFIX)) || ''00000'' 
                    ELSE LTRIM(RTRIM(sq_STG_FIN_AUT.ALF_POL_PREFIX)) || ''0000'' 
                END
        END 
    ELSE sq_STG_FIN_AUT.PRODUCT 
END AS out_PRODUCT_CD,
CONCAT ( sq_STG_FIN_AUT.ALF_POL_PREFIX , TO_CHAR ( sq_STG_FIN_AUT.ALF_POL_NUMBER ) ) as PLCY_NBR,
sq_STG_FIN_AUT.ALF_POL_EFF_DATE as PLCY_EFF_DT,
sq_STG_FIN_AUT.ALF_POL_EXP_DATE as PLCY_EXP_DT,
NULL as PLCY_TERM,
sq_STG_FIN_AUT.ACCOUNTING_PERIOD as ACCTNG_MO,
sq_STG_FIN_AUT.FISCAL_YEAR as ACCTNG_YR,
sq_STG_FIN_AUT.FISCAL_YEAR * 100 + sq_STG_FIN_AUT.ACCOUNTING_PERIOD as MO_ID,
sq_STG_FIN_AUT.CHARTFIELD2 as POOL_CD,
sq_STG_FIN_AUT.CHARTFIELD3 as REINSUR_CD,
sq_STG_FIN_AUT.ALF_TOT_PREM as TOT_PREM_AMT,
sq_STG_FIN_AUT.MONETARY_AMOUNT as MONETARY_AMT,
sq_STG_FIN_AUT.LEDGER as LEDGER,
sq_STG_FIN_AUT.ACCOUNT_NBR as ACCT_NBR,
sq_STG_FIN_AUT.GL_DISTRIB_STATUS as GL_DSTR_STATUS,
sq_STG_FIN_AUT.DEPTID as DEPT_ID,
sq_STG_FIN_AUT.PROJECT_ID as PROJ_ID,
NULL as ALF_ACCT_ID,
:PMMappingName as in_PRGM_NM,
:ACT_PROJ_ID as in_ACT_PROJ_ID,
:ECTL_ACTIVE_IND as in_BATCH_ACTIVE_IND,
:TableName as in_TABLE_NM,
:REPOS_CD as out_REPOS_CD,
sq_STG_FIN_AUT.source_record_id
FROM
sq_STG_FIN_AUT
);


-- Component LKP_FIN_PREMIUM_TXN, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_FIN_PREMIUM_TXN AS
(
SELECT
LKP.PRODUCT_CD,
exp_GET_DATA.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_GET_DATA.source_record_id ORDER BY LKP.PRODUCT_CD asc) RNK
FROM
exp_GET_DATA
LEFT JOIN (
SELECT FIN_PREMIUM_TXN.CMPY_CD as CMPY_CD, FIN_PREMIUM_TXN.ST_CD as ST_CD, FIN_PREMIUM_TXN.SVC_NBR as SVC_NBR, FIN_PREMIUM_TXN.AGNT_NBR as AGNT_NBR, FIN_PREMIUM_TXN.CMPY_TYPE_CD as CMPY_TYPE_CD, FIN_PREMIUM_TXN.PRODUCT_CD as PRODUCT_CD, FIN_PREMIUM_TXN.PLCY_NBR as PLCY_NBR, FIN_PREMIUM_TXN.PLCY_EFF_DT as PLCY_EFF_DT, FIN_PREMIUM_TXN.PLCY_EXP_DT as PLCY_EXP_DT, FIN_PREMIUM_TXN.ACCTNG_MO as ACCTNG_MO, FIN_PREMIUM_TXN.ACCTNG_YR as ACCTNG_YR, FIN_PREMIUM_TXN.POOL_CD as POOL_CD, FIN_PREMIUM_TXN.REINSUR_CD as REINSUR_CD, FIN_PREMIUM_TXN.LEDGER as LEDGER, FIN_PREMIUM_TXN.ACCT_NBR as ACCT_NBR, FIN_PREMIUM_TXN.GL_DSTR_STATUS as GL_DSTR_STATUS, FIN_PREMIUM_TXN.DEPT_ID as DEPT_ID FROM DB_T_CORE_FIN_PROD.FIN_PREMIUM_TXN
WHERE EXISTS 
	(
	SELECT 1 FROM
	DB_T_CTRL_FIN_PROD.ECTL_PRGM_INFO B
	,DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM C
	,DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM D
	WHERE
	B.ECTL_PRGM_NM = :PMMappingName
	AND FIN_PREMIUM_TXN.ECTL_PRGM_ID = B.ECTL_PRGM_ID
	AND c.ECTL_PARAM_DESC = ''ACCOUNTING_MONTH''
	AND C.ECTL_PARAM_VALUE = FIN_PREMIUM_TXN.ACCTNG_MO
	AND D.ECTL_PARAM_DESC = ''ACCOUNTING_YEAR''
	AND D.ECTL_PARAM_VALUE = FIN_PREMIUM_TXN.ACCTNG_YR
	)
) LKP ON LKP.CMPY_CD = exp_GET_DATA.CMPY_CD AND LKP.ST_CD = exp_GET_DATA.ST_CD AND LKP.SVC_NBR = exp_GET_DATA.out_SVC_NBR AND LKP.AGNT_NBR = exp_GET_DATA.out_AGNT_NBR AND LKP.CMPY_TYPE_CD = exp_GET_DATA.CMPY_TYPE_CD AND LKP.PRODUCT_CD = exp_GET_DATA.out_PRODUCT_CD AND LKP.PLCY_NBR = exp_GET_DATA.PLCY_NBR AND LKP.PLCY_EFF_DT = exp_GET_DATA.PLCY_EFF_DT AND LKP.PLCY_EXP_DT = exp_GET_DATA.PLCY_EXP_DT AND LKP.ACCTNG_MO = exp_GET_DATA.ACCTNG_MO AND LKP.ACCTNG_YR = exp_GET_DATA.ACCTNG_YR AND LKP.POOL_CD = exp_GET_DATA.POOL_CD AND LKP.REINSUR_CD = exp_GET_DATA.REINSUR_CD AND LKP.LEDGER = exp_GET_DATA.LEDGER AND LKP.ACCT_NBR = exp_GET_DATA.ACCT_NBR AND LKP.GL_DSTR_STATUS = exp_GET_DATA.GL_DSTR_STATUS AND LKP.DEPT_ID = exp_GET_DATA.DEPT_ID
QUALIFY RNK = 1
);


-- Component LKP_FIN_PRODUCT_HIER, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_FIN_PRODUCT_HIER AS
(
SELECT
LKP.LOB_ROLLUP,
exp_GET_DATA.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_GET_DATA.source_record_id ORDER BY LKP.LOB_ROLLUP asc) RNK
FROM
exp_GET_DATA
LEFT JOIN (
SELECT
LOB_ROLLUP,
PRODUCT_CD
FROM DB_T_CORE_FIN_PROD.FIN_PRODUCT_HIER
) LKP ON LKP.PRODUCT_CD = exp_GET_DATA.out_PRODUCT_CD
QUALIFY RNK = 1
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET, output = ''out_out_MPLT_LKP_BATCH_PRGM''
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;
CALL mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''exp_GET_DATA'');



-- Component LKP_REPOS_FIN_ACCT_NBR_LKUP, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_REPOS_FIN_ACCT_NBR_LKUP AS
(
SELECT
LKP.ACCT_NBR,
LKP.MULTIPLY_FACTOR,
exp_GET_DATA.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_GET_DATA.source_record_id ORDER BY LKP.ACCT_NBR asc,LKP.MULTIPLY_FACTOR asc) RNK
FROM
exp_GET_DATA
LEFT JOIN (
SELECT
ACCT_NBR,
MULTIPLY_FACTOR,
REPOS_CD
FROM DB_T_SHRD_FIN_PROD.REPOS_FIN_ACCT_NBR_LKUP
) LKP ON LKP.REPOS_CD = exp_GET_DATA.out_REPOS_CD AND LKP.ACCT_NBR = exp_GET_DATA.ACCT_NBR
QUALIFY RNK = 1
);


-- Component exp_EXISTS_IN_TGT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_EXISTS_IN_TGT AS
(
SELECT
exp_GET_DATA.MO_ID as MO_ID,
exp_GET_DATA.CMPY_CD as CMPY_CD,
exp_GET_DATA.ST_CD as ST_CD,
exp_GET_DATA.out_SVC_NBR as SVC_NBR,
exp_GET_DATA.out_AGNT_NBR as AGNT_NBR,
exp_GET_DATA.CMPY_TYPE_CD as CMPY_TYPE_CD,
LKP_FIN_PRODUCT_HIER.LOB_ROLLUP as LOB_CD,
exp_GET_DATA.out_PRODUCT_CD as PRODUCT_CD,
NULL as COV_TYPE_CD,
exp_GET_DATA.PLCY_NBR as PLCY_NBR,
exp_GET_DATA.PLCY_EFF_DT as PLCY_EFF_DT,
exp_GET_DATA.PLCY_EXP_DT as PLCY_EXP_DT,
exp_GET_DATA.PLCY_TERM as PLCY_TERM,
exp_GET_DATA.ACCTNG_MO as ACCTNG_MO,
exp_GET_DATA.ACCTNG_YR as ACCTNG_YR,
exp_GET_DATA.POOL_CD as POOL_CD,
exp_GET_DATA.REINSUR_CD as REINSUR_CD,
exp_GET_DATA.TOT_PREM_AMT as TOT_PREM_AMT,
exp_GET_DATA.MONETARY_AMT * LKP_REPOS_FIN_ACCT_NBR_LKUP.MULTIPLY_FACTOR as out_MONETARY_AMT,
exp_GET_DATA.LEDGER as LEDGER,
exp_GET_DATA.ACCT_NBR as ACCT_NBR,
exp_GET_DATA.GL_DSTR_STATUS as GL_DSTR_STATUS,
exp_GET_DATA.DEPT_ID as DEPT_ID,
exp_GET_DATA.PROJ_ID as PROJ_ID,
exp_GET_DATA.ALF_ACCT_ID as ALF_ACCT_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as ECTL_ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as ECTL_MODIFY_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
''NEW'' as ECTL_TXN_CD,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as ECTL_START_DATE,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as ECTL_END_DATE,
CASE WHEN LKP_REPOS_FIN_ACCT_NBR_LKUP.ACCT_NBR IS NULL THEN ''REJ'' ELSE CASE WHEN LKP_FIN_PREMIUM_TXN.PRODUCT_CD IS NULL THEN ''INS'' ELSE ''REJ'' END END as chk_INS_REJ,
exp_GET_DATA.source_record_id
FROM
exp_GET_DATA
INNER JOIN LKP_FIN_PREMIUM_TXN ON exp_GET_DATA.source_record_id = LKP_FIN_PREMIUM_TXN.source_record_id
INNER JOIN LKP_FIN_PRODUCT_HIER ON LKP_FIN_PREMIUM_TXN.source_record_id = LKP_FIN_PRODUCT_HIER.source_record_id
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON LKP_FIN_PRODUCT_HIER.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
INNER JOIN LKP_REPOS_FIN_ACCT_NBR_LKUP ON mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id = LKP_REPOS_FIN_ACCT_NBR_LKUP.source_record_id
);


-- Component rtr_FIN_PREMIUM_TXN_INSERT, Type ROUTER Output Group INSERT
CREATE OR REPLACE TEMPORARY TABLE rtr_FIN_PREMIUM_TXN_INSERT AS (
SELECT
exp_EXISTS_IN_TGT.MO_ID as MO_ID,
exp_EXISTS_IN_TGT.CMPY_CD as CMPY_CD,
exp_EXISTS_IN_TGT.ST_CD as ST_CD,
exp_EXISTS_IN_TGT.SVC_NBR as SVC_NBR,
exp_EXISTS_IN_TGT.AGNT_NBR as AGNT_NBR,
exp_EXISTS_IN_TGT.CMPY_TYPE_CD as CMPY_TYPE_CD,
exp_EXISTS_IN_TGT.LOB_CD as LOB_CD,
exp_EXISTS_IN_TGT.PRODUCT_CD as PRODUCT_CD,
exp_EXISTS_IN_TGT.COV_TYPE_CD as COV_TYPE_CD,
exp_EXISTS_IN_TGT.PLCY_NBR as PLCY_NBR,
exp_EXISTS_IN_TGT.PLCY_EFF_DT as PLCY_EFF_DT,
exp_EXISTS_IN_TGT.PLCY_EXP_DT as PLCY_EXP_DT,
exp_EXISTS_IN_TGT.PLCY_TERM as PLCY_TERM,
exp_EXISTS_IN_TGT.ACCTNG_MO as ACCTNG_MO,
exp_EXISTS_IN_TGT.ACCTNG_YR as ACCTNG_YR,
exp_EXISTS_IN_TGT.POOL_CD as POOL_CD,
exp_EXISTS_IN_TGT.REINSUR_CD as REINSUR_CD,
exp_EXISTS_IN_TGT.TOT_PREM_AMT as TOT_PREM_AMT,
exp_EXISTS_IN_TGT.out_MONETARY_AMT as MONETARY_AMT,
exp_EXISTS_IN_TGT.LEDGER as LEDGER,
exp_EXISTS_IN_TGT.ACCT_NBR as ACCT_NBR,
exp_EXISTS_IN_TGT.GL_DSTR_STATUS as GL_DSTR_STATUS,
exp_EXISTS_IN_TGT.DEPT_ID as DEPT_ID,
exp_EXISTS_IN_TGT.PROJ_ID as PROJ_ID,
exp_EXISTS_IN_TGT.ALF_ACCT_ID as ALF_ACCT_ID,
exp_EXISTS_IN_TGT.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_EXISTS_IN_TGT.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
exp_EXISTS_IN_TGT.ECTL_MODIFY_TS as ECTL_MODIFY_TS,
exp_EXISTS_IN_TGT.ECTL_SRC_ID as ECTL_SRC_ID,
exp_EXISTS_IN_TGT.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_EXISTS_IN_TGT.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_EXISTS_IN_TGT.ECTL_TXN_CD as ECTL_TXN_CD,
exp_EXISTS_IN_TGT.ECTL_START_DATE as ECTL_START_DATE,
exp_EXISTS_IN_TGT.ECTL_END_DATE as ECTL_END_DATE,
exp_EXISTS_IN_TGT.chk_INS_REJ as chk_INS_REJ,
exp_EXISTS_IN_TGT.source_record_id
FROM
exp_EXISTS_IN_TGT
WHERE exp_EXISTS_IN_TGT.chk_INS_REJ = ''INS''
);


-- Component srt_FIN_PREMIUM_TXN, Type SORTER 
CREATE OR REPLACE TEMPORARY TABLE srt_FIN_PREMIUM_TXN AS
(
SELECT
rtr_FIN_PREMIUM_TXN_INSERT.MO_ID as MO_ID,
rtr_FIN_PREMIUM_TXN_INSERT.CMPY_CD as CMPY_CD,
rtr_FIN_PREMIUM_TXN_INSERT.ST_CD as ST_CD,
rtr_FIN_PREMIUM_TXN_INSERT.SVC_NBR as SVC_NBR,
rtr_FIN_PREMIUM_TXN_INSERT.AGNT_NBR as AGNT_NBR,
rtr_FIN_PREMIUM_TXN_INSERT.CMPY_TYPE_CD as CMPY_TYPE_CD,
rtr_FIN_PREMIUM_TXN_INSERT.LOB_CD as LOB_CD,
rtr_FIN_PREMIUM_TXN_INSERT.PRODUCT_CD as PRODUCT_CD,
rtr_FIN_PREMIUM_TXN_INSERT.COV_TYPE_CD as COV_TYPE_CD,
rtr_FIN_PREMIUM_TXN_INSERT.PLCY_NBR as PLCY_NBR,
rtr_FIN_PREMIUM_TXN_INSERT.PLCY_EFF_DT as PLCY_EFF_DT,
rtr_FIN_PREMIUM_TXN_INSERT.PLCY_EXP_DT as PLCY_EXP_DT,
rtr_FIN_PREMIUM_TXN_INSERT.PLCY_TERM as PLCY_TERM,
rtr_FIN_PREMIUM_TXN_INSERT.ACCTNG_MO as ACCTNG_MO,
rtr_FIN_PREMIUM_TXN_INSERT.ACCTNG_YR as ACCTNG_YR,
rtr_FIN_PREMIUM_TXN_INSERT.POOL_CD as POOL_CD,
rtr_FIN_PREMIUM_TXN_INSERT.REINSUR_CD as REINSUR_CD,
rtr_FIN_PREMIUM_TXN_INSERT.TOT_PREM_AMT as TOT_PREM_AMT,
rtr_FIN_PREMIUM_TXN_INSERT.MONETARY_AMT as MONETARY_AMT,
rtr_FIN_PREMIUM_TXN_INSERT.LEDGER as LEDGER,
rtr_FIN_PREMIUM_TXN_INSERT.ACCT_NBR as ACCT_NBR,
rtr_FIN_PREMIUM_TXN_INSERT.GL_DSTR_STATUS as GL_DSTR_STATUS,
rtr_FIN_PREMIUM_TXN_INSERT.DEPT_ID as DEPT_ID,
rtr_FIN_PREMIUM_TXN_INSERT.PROJ_ID as PROJ_ID,
rtr_FIN_PREMIUM_TXN_INSERT.ALF_ACCT_ID as ALF_ACCT_ID,
rtr_FIN_PREMIUM_TXN_INSERT.ECTL_BATCH_ID as ECTL_BATCH_ID,
rtr_FIN_PREMIUM_TXN_INSERT.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
rtr_FIN_PREMIUM_TXN_INSERT.ECTL_MODIFY_TS as ECTL_MODIFY_TS,
rtr_FIN_PREMIUM_TXN_INSERT.ECTL_SRC_ID as ECTL_SRC_ID,
rtr_FIN_PREMIUM_TXN_INSERT.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
rtr_FIN_PREMIUM_TXN_INSERT.ECTL_PRGM_ID as ECTL_PRGM_ID,
rtr_FIN_PREMIUM_TXN_INSERT.ECTL_TXN_CD as ECTL_TXN_CD,
rtr_FIN_PREMIUM_TXN_INSERT.ECTL_START_DATE as ECTL_START_DATE,
rtr_FIN_PREMIUM_TXN_INSERT.ECTL_END_DATE as ECTL_END_DATE,
rtr_FIN_PREMIUM_TXN_INSERT.source_record_id
FROM
rtr_FIN_PREMIUM_TXN_INSERT
ORDER BY MO_ID , CMPY_CD , ST_CD , SVC_NBR , AGNT_NBR , CMPY_TYPE_CD , LOB_CD , PRODUCT_CD , COV_TYPE_CD , PLCY_NBR , PLCY_EFF_DT , PLCY_EXP_DT , PLCY_TERM , ACCTNG_MO , ACCTNG_YR , POOL_CD , REINSUR_CD , LEDGER , ACCT_NBR , GL_DSTR_STATUS , DEPT_ID , PROJ_ID , ALF_ACCT_ID , ECTL_BATCH_ID , ECTL_ORIG_INS_TS , ECTL_MODIFY_TS , ECTL_SRC_ID , ECTL_SRC_INST_ID , ECTL_PRGM_ID , ECTL_TXN_CD , ECTL_START_DATE , ECTL_END_DATE 
);


-- Component agg_FIN_PREMIUM_TXN, Type AGGREGATOR 
CREATE OR REPLACE TEMPORARY TABLE agg_FIN_PREMIUM_TXN AS
(
SELECT *, sum(in_TOT_PREM_AMT) OVER () as TOT_PREM_AMT, sum(in_MONETARY_AMT) OVER () as MONETARY_AMT FROM (
SELECT
srt_FIN_PREMIUM_TXN.MO_ID as MO_ID,
srt_FIN_PREMIUM_TXN.CMPY_CD as CMPY_CD,
srt_FIN_PREMIUM_TXN.ST_CD as ST_CD,
srt_FIN_PREMIUM_TXN.SVC_NBR as SVC_NBR,
srt_FIN_PREMIUM_TXN.AGNT_NBR as AGNT_NBR,
srt_FIN_PREMIUM_TXN.CMPY_TYPE_CD as CMPY_TYPE_CD,
srt_FIN_PREMIUM_TXN.LOB_CD as LOB_CD,
srt_FIN_PREMIUM_TXN.PRODUCT_CD as PRODUCT_CD,
srt_FIN_PREMIUM_TXN.COV_TYPE_CD as COV_TYPE_CD,
srt_FIN_PREMIUM_TXN.PLCY_NBR as PLCY_NBR,
srt_FIN_PREMIUM_TXN.PLCY_EFF_DT as PLCY_EFF_DT,
srt_FIN_PREMIUM_TXN.PLCY_EXP_DT as PLCY_EXP_DT,
srt_FIN_PREMIUM_TXN.PLCY_TERM as PLCY_TERM,
srt_FIN_PREMIUM_TXN.ACCTNG_MO as ACCTNG_MO,
srt_FIN_PREMIUM_TXN.ACCTNG_YR as ACCTNG_YR,
srt_FIN_PREMIUM_TXN.POOL_CD as POOL_CD,
srt_FIN_PREMIUM_TXN.REINSUR_CD as REINSUR_CD,
MIN(srt_FIN_PREMIUM_TXN.TOT_PREM_AMT) as in_TOT_PREM_AMT,
--sum(in_TOT_PREM_AMT) as TOT_PREM_AMT,
MIN(srt_FIN_PREMIUM_TXN.MONETARY_AMT) as in_MONETARY_AMT,
--sum(in_MONETARY_AMT) as MONETARY_AMT,
srt_FIN_PREMIUM_TXN.LEDGER as LEDGER,
srt_FIN_PREMIUM_TXN.ACCT_NBR as ACCT_NBR,
srt_FIN_PREMIUM_TXN.GL_DSTR_STATUS as GL_DSTR_STATUS,
srt_FIN_PREMIUM_TXN.DEPT_ID as DEPT_ID,
srt_FIN_PREMIUM_TXN.PROJ_ID as PROJ_ID,
srt_FIN_PREMIUM_TXN.ALF_ACCT_ID as ALF_ACCT_ID,
srt_FIN_PREMIUM_TXN.ECTL_BATCH_ID as ECTL_BATCH_ID,
srt_FIN_PREMIUM_TXN.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
srt_FIN_PREMIUM_TXN.ECTL_MODIFY_TS as ECTL_MODIFY_TS,
srt_FIN_PREMIUM_TXN.ECTL_SRC_ID as ECTL_SRC_ID,
srt_FIN_PREMIUM_TXN.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
srt_FIN_PREMIUM_TXN.ECTL_PRGM_ID as ECTL_PRGM_ID,
srt_FIN_PREMIUM_TXN.ECTL_TXN_CD as ECTL_TXN_CD,
srt_FIN_PREMIUM_TXN.ECTL_START_DATE as ECTL_START_DATE,
srt_FIN_PREMIUM_TXN.ECTL_END_DATE as ECTL_END_DATE,
MIN(srt_FIN_PREMIUM_TXN.source_record_id) as source_record_id
FROM
srt_FIN_PREMIUM_TXN
GROUP BY
srt_FIN_PREMIUM_TXN.MO_ID,
srt_FIN_PREMIUM_TXN.CMPY_CD,
srt_FIN_PREMIUM_TXN.ST_CD,
srt_FIN_PREMIUM_TXN.SVC_NBR,
srt_FIN_PREMIUM_TXN.AGNT_NBR,
srt_FIN_PREMIUM_TXN.CMPY_TYPE_CD,
srt_FIN_PREMIUM_TXN.LOB_CD,
srt_FIN_PREMIUM_TXN.PRODUCT_CD,
srt_FIN_PREMIUM_TXN.COV_TYPE_CD,
srt_FIN_PREMIUM_TXN.PLCY_NBR,
srt_FIN_PREMIUM_TXN.PLCY_EFF_DT,
srt_FIN_PREMIUM_TXN.PLCY_EXP_DT,
srt_FIN_PREMIUM_TXN.PLCY_TERM,
srt_FIN_PREMIUM_TXN.ACCTNG_MO,
srt_FIN_PREMIUM_TXN.ACCTNG_YR,
srt_FIN_PREMIUM_TXN.POOL_CD,
srt_FIN_PREMIUM_TXN.REINSUR_CD,
srt_FIN_PREMIUM_TXN.LEDGER,
srt_FIN_PREMIUM_TXN.ACCT_NBR,
srt_FIN_PREMIUM_TXN.GL_DSTR_STATUS,
srt_FIN_PREMIUM_TXN.DEPT_ID,
srt_FIN_PREMIUM_TXN.PROJ_ID,
srt_FIN_PREMIUM_TXN.ALF_ACCT_ID,
srt_FIN_PREMIUM_TXN.ECTL_BATCH_ID,
srt_FIN_PREMIUM_TXN.ECTL_ORIG_INS_TS,
srt_FIN_PREMIUM_TXN.ECTL_MODIFY_TS,
srt_FIN_PREMIUM_TXN.ECTL_SRC_ID,
srt_FIN_PREMIUM_TXN.ECTL_SRC_INST_ID,
srt_FIN_PREMIUM_TXN.ECTL_PRGM_ID,
srt_FIN_PREMIUM_TXN.ECTL_TXN_CD,
srt_FIN_PREMIUM_TXN.ECTL_START_DATE,
srt_FIN_PREMIUM_TXN.ECTL_END_DATE
));


-- Component FIN_PREMIUM_TXN_AUT_INS, Type TARGET 
INSERT INTO DB_T_CORE_FIN_PROD.FIN_PREMIUM_TXN
(
MO_ID,
CMPY_CD,
ST_CD,
SVC_NBR,
AGNT_NBR,
CMPY_TYPE_CD,
LOB_CD,
PRODUCT_CD,
COV_TYPE_CD,
PLCY_NBR,
PLCY_EFF_DT,
PLCY_EXP_DT,
PLCY_TERM,
ACCTNG_MO,
ACCTNG_YR,
POOL_CD,
REINSUR_CD,
TOT_PREM_AMT,
MONETARY_AMT,
LEDGER,
ACCT_NBR,
GL_DSTR_STATUS,
DEPT_ID,
PROJ_ID,
ALF_ACCT_ID,
ECTL_BATCH_ID,
ECTL_ORIG_INS_TS,
ECTL_MODIFY_TS,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_PRGM_ID,
ECTL_TXN_CD,
ECTL_START_DATE,
ECTL_END_DATE
)
SELECT
agg_FIN_PREMIUM_TXN.MO_ID as MO_ID,
agg_FIN_PREMIUM_TXN.CMPY_CD as CMPY_CD,
agg_FIN_PREMIUM_TXN.ST_CD as ST_CD,
agg_FIN_PREMIUM_TXN.SVC_NBR as SVC_NBR,
agg_FIN_PREMIUM_TXN.AGNT_NBR as AGNT_NBR,
agg_FIN_PREMIUM_TXN.CMPY_TYPE_CD as CMPY_TYPE_CD,
agg_FIN_PREMIUM_TXN.LOB_CD as LOB_CD,
agg_FIN_PREMIUM_TXN.PRODUCT_CD as PRODUCT_CD,
agg_FIN_PREMIUM_TXN.COV_TYPE_CD as COV_TYPE_CD,
agg_FIN_PREMIUM_TXN.PLCY_NBR as PLCY_NBR,
agg_FIN_PREMIUM_TXN.PLCY_EFF_DT as PLCY_EFF_DT,
agg_FIN_PREMIUM_TXN.PLCY_EXP_DT as PLCY_EXP_DT,
agg_FIN_PREMIUM_TXN.PLCY_TERM as PLCY_TERM,
agg_FIN_PREMIUM_TXN.ACCTNG_MO as ACCTNG_MO,
agg_FIN_PREMIUM_TXN.ACCTNG_YR as ACCTNG_YR,
agg_FIN_PREMIUM_TXN.POOL_CD as POOL_CD,
agg_FIN_PREMIUM_TXN.REINSUR_CD as REINSUR_CD,
agg_FIN_PREMIUM_TXN.TOT_PREM_AMT as TOT_PREM_AMT,
agg_FIN_PREMIUM_TXN.MONETARY_AMT as MONETARY_AMT,
agg_FIN_PREMIUM_TXN.LEDGER as LEDGER,
agg_FIN_PREMIUM_TXN.ACCT_NBR as ACCT_NBR,
agg_FIN_PREMIUM_TXN.GL_DSTR_STATUS as GL_DSTR_STATUS,
agg_FIN_PREMIUM_TXN.DEPT_ID as DEPT_ID,
agg_FIN_PREMIUM_TXN.PROJ_ID as PROJ_ID,
agg_FIN_PREMIUM_TXN.ALF_ACCT_ID as ALF_ACCT_ID,
agg_FIN_PREMIUM_TXN.ECTL_BATCH_ID as ECTL_BATCH_ID,
agg_FIN_PREMIUM_TXN.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
agg_FIN_PREMIUM_TXN.ECTL_MODIFY_TS as ECTL_MODIFY_TS,
agg_FIN_PREMIUM_TXN.ECTL_SRC_ID as ECTL_SRC_ID,
agg_FIN_PREMIUM_TXN.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
agg_FIN_PREMIUM_TXN.ECTL_PRGM_ID as ECTL_PRGM_ID,
agg_FIN_PREMIUM_TXN.ECTL_TXN_CD as ECTL_TXN_CD,
agg_FIN_PREMIUM_TXN.ECTL_START_DATE as ECTL_START_DATE,
agg_FIN_PREMIUM_TXN.ECTL_END_DATE as ECTL_END_DATE
FROM
agg_FIN_PREMIUM_TXN;


END; ';