-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_PRTY_AGMT_ASSET_INSUPD("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE 

start_dttm TIMESTAMP;
end_dttm TIMESTAMP;
PRCS_ID INTEGER;
P_DEFAULT_STR_CD char;
BEGIN 
start_dttm := CURRENT_TIMESTAMP();
end_dttm := CURRENT_TIMESTAMP();
PRCS_ID := 1;   

-- Component LKP_TERADATA_ETL_REF_XLAT, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_TERADATA_ETL_REF_XLAT AS
(
SELECT 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL

	,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 

FROM 

	DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT

WHERE 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM= ''PRTY_AGMT_ROLE''

	AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_NM IN (''pctl_accountcontactrole.typecode'',''pctl_userrole.typecode'',''cctl_contactrole.typecode'',''pctl_policycontactrole.TYPECODE'',''pctl_additionalinteresttype.typecode'',''bctl_accountrole.typecode'',''derived'') 

	AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_SYS in (''GW'',''DS'') 

	AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''
);


-- Component LKP_TERADATA_ETL_REF_XLAT_ASSET_CLASFCN, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_TERADATA_ETL_REF_XLAT_ASSET_CLASFCN AS
(
SELECT 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL

	,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 

FROM 

	DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT

WHERE 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM= ''PRTY_ASSET_CLASFCN'' 

             --AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_NM in ( ''derived'' ,''pcx_holineschcovitemcov_alfa.ChoiceTerm1'', ''cctl_contentlineitemschedule'')

		AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_SYS in (''DS'', ''GW'') 

		AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''
);


-- Component LKP_TERADATA_ETL_REF_XLAT_ASSET_CONTRACT_ROLE_SBTYPE, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_TERADATA_ETL_REF_XLAT_ASSET_CONTRACT_ROLE_SBTYPE AS
(
SELECT 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL

	,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 

FROM 

	DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT

WHERE 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM= ''ASSET_CNTRCT_ROLE_SBTYPE''

             AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_NM in ( ''derived'')

		AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_SYS in (''DS'', ''GW'') 

		AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''
);


-- Component LKP_TERADATA_ETL_REF_XLAT_ASSET_SBTYPE, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_TERADATA_ETL_REF_XLAT_ASSET_SBTYPE AS
(
SELECT 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_VAL as TGT_IDNTFTN_VAL

	,TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_VAL as SRC_IDNTFTN_VAL 

FROM 

	DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT

WHERE 

	TERADATA_ETL_REF_XLAT.TGT_IDNTFTN_NM= ''PRTY_ASSET_SBTYPE'' 

             AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_NM= ''derived'' 

		AND TERADATA_ETL_REF_XLAT.SRC_IDNTFTN_SYS=''DS'' 

		AND TERADATA_ETL_REF_XLAT.EXPN_DT=''9999-12-31''
);


-- Component SQ_pc_prty_asset_quotn_asset_x, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_pc_prty_asset_quotn_asset_x AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as AddressBookUID,
$2 as Policyperiod_publicid,
$3 as FixedID,
$4 as SubType,
$5 as classification_code,
$6 as Role_cd,
$7 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
select distinct pc_contact.AddressBookUID_stg as AddressBookUID

,pc_policyperiod.PublicID_stg as Policyperiod_publicid

,pc_personalvehicle.FixedID_stg as FixedID

,''PRTY_ASSET_SBTYPE4'' as SubType

,''PRTY_ASSET_CLASFCN3'' as classification_code

,''PRTY_AGMT_ROLE7'' AS Role_cd

from  DB_T_PROD_STAG.pc_policyperiod pc_policyperiod

join DB_T_PROD_STAG.pc_vehicledriver pc_vehicledriver on pc_vehicledriver.BranchID_stg = pc_policyperiod.id_stg 

join DB_T_PROD_STAG.pc_personalvehicle  pc_personalvehicle on pc_personalvehicle.FixedID_stg = pc_vehicledriver.vehicle_stg and pc_personalvehicle.BranchID_stg = pc_policyperiod.id_stg

join DB_T_PROD_STAG.pc_policycontactrole pc_policycontactrole on pc_vehicledriver.PolicyDriver_stg = pc_policycontactrole.id_stg

join DB_T_PROD_STAG.pc_contact pc_contact on pc_policycontactrole.ContactDenorm_stg = pc_contact.ID_stg

join DB_T_PROD_STAG.pctl_contact  pctl_contact on pctl_contact.ID_stg=pc_contact.subtype_stg

join DB_T_PROD_STAG.pc_job pc_job on pc_job.id_stg=pc_policyperiod.JobID_stg

join DB_T_PROD_STAG.pctl_job pctl_job on pctl_job.id_stg=pc_job.Subtype_stg

join DB_T_PROD_STAG.pctl_policyperiodstatus pctl_policyperiodstatus on pctl_policyperiodstatus.id_stg=pc_policyperiod.Status_stg

where pc_vehicledriver.Rated_alfa_stg = 1 and pctl_policyperiodstatus.TYPECODE_stg not in (''Temporary'') and pc_contact.AddressBookUID_stg is not null and pc_job.JobNumber_stg is not null and pc_personalvehicle.FixedId_stg is not null

and pc_personalvehicle.ExpirationDate_stg is null and pc_vehicledriver.ExpirationDate_stg is null 

and  pc_policyperiod.UpdateTime_stg > (:start_dttm)	

and pc_policyperiod.UpdateTime_stg <= (:end_dttm) 

and	Policyperiod_publicid  is not null 

	and pc_personalvehicle.FixedID_stg is not NULL 

	and AddressBookUID_STG is not NULL 

	and pctl_policyperiodstatus.Typecode_stg =''Bound''
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_pc_prty_asset_quotn_asset_x.AddressBookUID as AddressBookUID,
SQ_pc_prty_asset_quotn_asset_x.Policyperiod_publicid as Policyperiod_publicid,
SQ_pc_prty_asset_quotn_asset_x.FixedID as FixedID,
''PPV'' as IN_AGMT_TYPE_CD,
LKP_1.TGT_IDNTFTN_VAL /* replaced lookup LKP_TERADATA_ETL_REF_XLAT_ASSET_SBTYPE */ as in_prty_asset_sbtype_cd,
LKP_2.TGT_IDNTFTN_VAL /* replaced lookup LKP_TERADATA_ETL_REF_XLAT_ASSET_CLASFCN */ as in_class_cd,
LKP_3.TGT_IDNTFTN_VAL /* replaced lookup LKP_TERADATA_ETL_REF_XLAT */ as PRTY_AGMT_ROLE_CD,
SQ_pc_prty_asset_quotn_asset_x.source_record_id,
row_number() over (partition by SQ_pc_prty_asset_quotn_asset_x.source_record_id order by SQ_pc_prty_asset_quotn_asset_x.source_record_id) as RNK
FROM
SQ_pc_prty_asset_quotn_asset_x
LEFT JOIN LKP_TERADATA_ETL_REF_XLAT_ASSET_SBTYPE LKP_1 ON LKP_1.SRC_IDNTFTN_VAL = SQ_pc_prty_asset_quotn_asset_x.SubType
LEFT JOIN LKP_TERADATA_ETL_REF_XLAT_ASSET_CLASFCN LKP_2 ON LKP_2.SRC_IDNTFTN_VAL = SQ_pc_prty_asset_quotn_asset_x.classification_code
LEFT JOIN LKP_TERADATA_ETL_REF_XLAT LKP_3 ON LKP_3.SRC_IDNTFTN_VAL = SQ_pc_prty_asset_quotn_asset_x.Role_cd
QUALIFY RNK = 1
);


-- Component LKP_PRTY_ASSET_ID, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_PRTY_ASSET_ID AS
(
SELECT
LKP.PRTY_ASSET_ID,
EXPTRANS.source_record_id,
ROW_NUMBER() OVER(PARTITION BY EXPTRANS.source_record_id ORDER BY LKP.PRTY_ASSET_ID asc,LKP.ASSET_HOST_ID_VAL asc,LKP.PRTY_ASSET_SBTYPE_CD asc,LKP.PRTY_ASSET_CLASFCN_CD asc,LKP.ASSET_INSRNC_HIST_TYPE_CD asc,LKP.ASSET_DESC asc,LKP.PRTY_ASSET_NAME asc,LKP.PRTY_ASSET_STRT_DTTM asc,LKP.PRTY_ASSET_END_DTTM asc,LKP.EDW_STRT_DTTM asc,LKP.EDW_END_DTTM asc,LKP.SRC_SYS_CD asc) RNK
FROM
EXPTRANS
LEFT JOIN (
SELECT PRTY_ASSET.PRTY_ASSET_ID as PRTY_ASSET_ID, PRTY_ASSET.ASSET_INSRNC_HIST_TYPE_CD as ASSET_INSRNC_HIST_TYPE_CD, PRTY_ASSET.ASSET_DESC as ASSET_DESC, PRTY_ASSET.PRTY_ASSET_NAME as PRTY_ASSET_NAME, PRTY_ASSET.PRTY_ASSET_STRT_DTTM as PRTY_ASSET_STRT_DTTM, PRTY_ASSET.PRTY_ASSET_END_DTTM as PRTY_ASSET_END_DTTM, PRTY_ASSET.EDW_STRT_DTTM as EDW_STRT_DTTM, PRTY_ASSET.EDW_END_DTTM as EDW_END_DTTM, PRTY_ASSET.SRC_SYS_CD as SRC_SYS_CD, PRTY_ASSET.ASSET_HOST_ID_VAL as ASSET_HOST_ID_VAL, PRTY_ASSET.PRTY_ASSET_SBTYPE_CD as PRTY_ASSET_SBTYPE_CD, PRTY_ASSET.PRTY_ASSET_CLASFCN_CD as PRTY_ASSET_CLASFCN_CD 
FROM DB_T_PROD_CORE.PRTY_ASSET 
QUALIFY ROW_NUMBER() OVER(PARTITION BY  ASSET_HOST_ID_VAL,PRTY_ASSET_SBTYPE_CD,PRTY_ASSET_CLASFCN_CD ORDER BY EDW_END_DTTM DESC) = 1
) LKP ON LKP.ASSET_HOST_ID_VAL = EXPTRANS.FixedID AND LKP.PRTY_ASSET_SBTYPE_CD = EXPTRANS.in_prty_asset_sbtype_cd AND LKP.PRTY_ASSET_CLASFCN_CD = EXPTRANS.in_class_cd
QUALIFY RNK = 1
);


-- Component LKP_INDIV_CNT_MGR, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_INDIV_CNT_MGR AS
(
SELECT
LKP.INDIV_PRTY_ID,
EXPTRANS.source_record_id,
ROW_NUMBER() OVER(PARTITION BY EXPTRANS.source_record_id ORDER BY LKP.INDIV_PRTY_ID desc,LKP.NK_LINK_ID desc) RNK
FROM
EXPTRANS
LEFT JOIN (
SELECT 
	INDIV.INDIV_PRTY_ID as INDIV_PRTY_ID, 
	INDIV.NK_LINK_ID as NK_LINK_ID 
FROM 
	DB_T_PROD_CORE.INDIV
WHERE
	INDIV.NK_PUBLC_ID IS NULL
) LKP ON LKP.NK_LINK_ID = EXPTRANS.AddressBookUID
QUALIFY RNK = 1
);


-- Component LKP_AGMT_PPV, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_AGMT_PPV AS
(
SELECT
LKP.AGMT_ID,
EXPTRANS.source_record_id,
ROW_NUMBER() OVER(PARTITION BY EXPTRANS.source_record_id ORDER BY LKP.AGMT_ID asc,LKP.HOST_AGMT_NUM asc,LKP.AGMT_NAME asc,LKP.AGMT_OPN_DTTM asc,LKP.AGMT_CLS_DTTM asc,LKP.AGMT_PLND_EXPN_DTTM asc,LKP.AGMT_SIGND_DTTM asc,LKP.AGMT_TYPE_CD asc,LKP.AGMT_LEGLY_BINDG_IND asc,LKP.AGMT_SRC_CD asc,LKP.AGMT_CUR_STS_CD asc,LKP.AGMT_CUR_STS_RSN_CD asc,LKP.AGMT_OBTND_CD asc,LKP.AGMT_SBTYPE_CD asc,LKP.AGMT_PRCSG_DTTM asc,LKP.ALT_AGMT_NAME asc,LKP.ASSET_LIABTY_CD asc,LKP.BAL_SHET_CD asc,LKP.STMT_CYCL_CD asc,LKP.STMT_ML_TYPE_CD asc,LKP.PRPOSL_ID asc,LKP.AGMT_OBJTV_TYPE_CD asc,LKP.FINCL_AGMT_SBTYPE_CD asc,LKP.MKT_RISK_TYPE_CD asc,LKP.ORIGNL_MATURTY_DT asc,LKP.RISK_EXPSR_MTGNT_SBTYPE_CD asc,LKP.BNK_TRD_BK_CD asc,LKP.PRCG_METH_SBTYPE_CD asc,LKP.FINCL_AGMT_TYPE_CD asc,LKP.DY_CNT_BSS_CD asc,LKP.FRST_PREM_DUE_DT asc,LKP.INSRNC_AGMT_SBTYPE_CD asc,LKP.INSRNC_AGMT_TYPE_CD asc,LKP.NTWK_SRVC_AGMT_TYPE_CD asc,LKP.FRMLTY_TYPE_CD asc,LKP.CNTRCT_TERM_NUM asc,LKP.RATE_RPRCG_CYCL_MTH_NUM asc,LKP.CMPND_INT_CYCL_MTH_NUM asc,LKP.MDTERM_INT_PMT_CYCL_MTH_NUM asc,LKP.PREV_MDTERM_INT_PMT_DT asc,LKP.NXT_MDTERM_INT_PMT_DT asc,LKP.PREV_INT_RATE_RVSD_DT asc,LKP.NXT_INT_RATE_RVSD_DT asc,LKP.PREV_REF_DT_INT_RATE asc,LKP.NXT_REF_DT_FOR_INT_RATE asc,LKP.MDTERM_CNCLTN_DT asc,LKP.STK_FLOW_CLAS_IN_MTH_IND asc,LKP.STK_FLOW_CLAS_IN_TERM_IND asc,LKP.LGCY_DSCNT_IND asc,LKP.AGMT_IDNTFTN_CD asc,LKP.TRMTN_TYPE_CD asc,LKP.INT_PMT_METH_CD asc,LKP.LBR_AGMT_DESC asc,LKP.GUARTD_IMPRSNS_CNT asc,LKP.COST_PER_IMPRSN_AMT asc,LKP.GUARTD_CLKTHRU_CNT asc,LKP.COST_PER_CLKTHRU_AMT asc,LKP.BUSN_PRTY_ID asc,LKP.PMT_PLN_TYPE_CD asc,LKP.INVC_STREM_TYPE_CD asc,LKP.MODL_CRTN_DTTM asc,LKP.CNTNUS_SRVC_DTTM asc,LKP.BILG_METH_TYPE_CD asc,LKP.SRC_SYS_CD asc,LKP.AGMT_EFF_DTTM asc,LKP.MODL_EFF_DTTM asc,LKP.PRCS_ID asc,LKP.MODL_ACTL_END_DTTM asc,LKP.TIER_TYPE_CD asc,LKP.EDW_STRT_DTTM asc,LKP.EDW_END_DTTM asc,LKP.VFYD_PLCY_IND asc,LKP.SRC_OF_BUSN_CD asc,LKP.NK_SRC_KEY asc,LKP.OVRD_COMS_TYPE_CD asc,LKP.LGCY_PLCY_IND asc,LKP.TRANS_STRT_DTTM asc) RNK
FROM
EXPTRANS
LEFT JOIN (
SELECT AGMT.AGMT_ID as AGMT_ID, AGMT.HOST_AGMT_NUM as HOST_AGMT_NUM, AGMT.AGMT_NAME as AGMT_NAME, AGMT.AGMT_OPN_DTTM as AGMT_OPN_DTTM, AGMT.AGMT_CLS_DTTM as AGMT_CLS_DTTM, AGMT.AGMT_PLND_EXPN_DTTM as AGMT_PLND_EXPN_DTTM, AGMT.AGMT_SIGND_DTTM as AGMT_SIGND_DTTM, AGMT.AGMT_LEGLY_BINDG_IND as AGMT_LEGLY_BINDG_IND, AGMT.AGMT_SRC_CD as AGMT_SRC_CD, AGMT.AGMT_CUR_STS_CD as AGMT_CUR_STS_CD, AGMT.AGMT_CUR_STS_RSN_CD as AGMT_CUR_STS_RSN_CD, AGMT.AGMT_OBTND_CD as AGMT_OBTND_CD, AGMT.AGMT_SBTYPE_CD as AGMT_SBTYPE_CD, AGMT.AGMT_PRCSG_DTTM as AGMT_PRCSG_DTTM, AGMT.ALT_AGMT_NAME as ALT_AGMT_NAME, AGMT.ASSET_LIABTY_CD as ASSET_LIABTY_CD, AGMT.BAL_SHET_CD as BAL_SHET_CD, AGMT.STMT_CYCL_CD as STMT_CYCL_CD, AGMT.STMT_ML_TYPE_CD as STMT_ML_TYPE_CD, AGMT.PRPOSL_ID as PRPOSL_ID, AGMT.AGMT_OBJTV_TYPE_CD as AGMT_OBJTV_TYPE_CD, AGMT.FINCL_AGMT_SBTYPE_CD as FINCL_AGMT_SBTYPE_CD, AGMT.MKT_RISK_TYPE_CD as MKT_RISK_TYPE_CD, AGMT.ORIGNL_MATURTY_DT as ORIGNL_MATURTY_DT, AGMT.RISK_EXPSR_MTGNT_SBTYPE_CD as RISK_EXPSR_MTGNT_SBTYPE_CD, AGMT.BNK_TRD_BK_CD as BNK_TRD_BK_CD, AGMT.PRCG_METH_SBTYPE_CD as PRCG_METH_SBTYPE_CD, AGMT.FINCL_AGMT_TYPE_CD as FINCL_AGMT_TYPE_CD, AGMT.DY_CNT_BSS_CD as DY_CNT_BSS_CD, AGMT.FRST_PREM_DUE_DT as FRST_PREM_DUE_DT, AGMT.INSRNC_AGMT_SBTYPE_CD as INSRNC_AGMT_SBTYPE_CD, AGMT.INSRNC_AGMT_TYPE_CD as INSRNC_AGMT_TYPE_CD, AGMT.NTWK_SRVC_AGMT_TYPE_CD as NTWK_SRVC_AGMT_TYPE_CD, AGMT.FRMLTY_TYPE_CD as FRMLTY_TYPE_CD, AGMT.CNTRCT_TERM_NUM as CNTRCT_TERM_NUM, AGMT.RATE_RPRCG_CYCL_MTH_NUM as RATE_RPRCG_CYCL_MTH_NUM, AGMT.CMPND_INT_CYCL_MTH_NUM as CMPND_INT_CYCL_MTH_NUM, AGMT.MDTERM_INT_PMT_CYCL_MTH_NUM as MDTERM_INT_PMT_CYCL_MTH_NUM, AGMT.PREV_MDTERM_INT_PMT_DT as PREV_MDTERM_INT_PMT_DT, AGMT.NXT_MDTERM_INT_PMT_DT as NXT_MDTERM_INT_PMT_DT, AGMT.PREV_INT_RATE_RVSD_DT as PREV_INT_RATE_RVSD_DT, AGMT.NXT_INT_RATE_RVSD_DT as NXT_INT_RATE_RVSD_DT, AGMT.PREV_REF_DT_INT_RATE as PREV_REF_DT_INT_RATE, AGMT.NXT_REF_DT_FOR_INT_RATE as NXT_REF_DT_FOR_INT_RATE, AGMT.MDTERM_CNCLTN_DT as MDTERM_CNCLTN_DT, AGMT.STK_FLOW_CLAS_IN_MTH_IND as STK_FLOW_CLAS_IN_MTH_IND, AGMT.STK_FLOW_CLAS_IN_TERM_IND as STK_FLOW_CLAS_IN_TERM_IND, AGMT.LGCY_DSCNT_IND as LGCY_DSCNT_IND, AGMT.AGMT_IDNTFTN_CD as AGMT_IDNTFTN_CD, AGMT.TRMTN_TYPE_CD as TRMTN_TYPE_CD, AGMT.INT_PMT_METH_CD as INT_PMT_METH_CD, AGMT.LBR_AGMT_DESC as LBR_AGMT_DESC, AGMT.GUARTD_IMPRSNS_CNT as GUARTD_IMPRSNS_CNT, AGMT.COST_PER_IMPRSN_AMT as COST_PER_IMPRSN_AMT, AGMT.GUARTD_CLKTHRU_CNT as GUARTD_CLKTHRU_CNT, AGMT.COST_PER_CLKTHRU_AMT as COST_PER_CLKTHRU_AMT, AGMT.BUSN_PRTY_ID as BUSN_PRTY_ID, AGMT.PMT_PLN_TYPE_CD as PMT_PLN_TYPE_CD, AGMT.INVC_STREM_TYPE_CD as INVC_STREM_TYPE_CD, AGMT.MODL_CRTN_DTTM as MODL_CRTN_DTTM, AGMT.CNTNUS_SRVC_DTTM as CNTNUS_SRVC_DTTM, AGMT.BILG_METH_TYPE_CD as BILG_METH_TYPE_CD, AGMT.SRC_SYS_CD as SRC_SYS_CD, AGMT.AGMT_EFF_DTTM as AGMT_EFF_DTTM, AGMT.MODL_EFF_DTTM as MODL_EFF_DTTM, AGMT.PRCS_ID as PRCS_ID, AGMT.MODL_ACTL_END_DTTM as MODL_ACTL_END_DTTM, AGMT.TIER_TYPE_CD as TIER_TYPE_CD, AGMT.EDW_STRT_DTTM as EDW_STRT_DTTM, AGMT.EDW_END_DTTM as EDW_END_DTTM, AGMT.VFYD_PLCY_IND as VFYD_PLCY_IND, AGMT.SRC_OF_BUSN_CD as SRC_OF_BUSN_CD, AGMT.OVRD_COMS_TYPE_CD as OVRD_COMS_TYPE_CD, AGMT.LGCY_PLCY_IND as LGCY_PLCY_IND, AGMT.TRANS_STRT_DTTM as TRANS_STRT_DTTM, AGMT.NK_SRC_KEY as NK_SRC_KEY, AGMT.AGMT_TYPE_CD as AGMT_TYPE_CD FROM DB_T_PROD_CORE.AGMT QUALIFY ROW_NUMBER() OVER(PARTITION BY AGMT.NK_SRC_KEY,AGMT.HOST_AGMT_NUM  ORDER BY AGMT.EDW_END_DTTM desc) = 1
) LKP ON LKP.NK_SRC_KEY = EXPTRANS.Policyperiod_publicid AND LKP.AGMT_TYPE_CD = EXPTRANS.IN_AGMT_TYPE_CD
QUALIFY RNK = 1
);


-- Component EXPTRANS1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS1 AS
(
SELECT
LKP_AGMT_PPV.AGMT_ID as AGMT_ID,
EXPTRANS.PRTY_AGMT_ROLE_CD as PRTY_AGMT_ROLE_CD,
to_date ( ''1900-01-01'' , ''yyyy-mm-dd'' ) as PRTY_AGMT_STRT_DTTM,
''UNK'' as ASSET_ROLE_CD,
LKP_1.TGT_IDNTFTN_VAL /* replaced lookup LKP_TERADATA_ETL_REF_XLAT_ASSET_CONTRACT_ROLE_SBTYPE */ as ASSET_CNTRCT_ROLE_SBTYPE_CD,
LKP_PRTY_ASSET_ID.PRTY_ASSET_ID as PRTY_ASSET_ID,
to_date ( ''1900-01-01'' , ''yyyy-mm-dd'' ) as AGMT_ASSET_STRT_DT,
to_date ( ''1900-01-01'' , ''yyyy-mm-dd'' ) as PRTY_AGMT_ASSET_STRT_DTTM,
LKP_INDIV_CNT_MGR.INDIV_PRTY_ID as PRTY_ID,
TO_DATE ( ''12/31/9999 23:59:59.999999'' , ''MM/DD/YYYY HH24:MI:SS.FF6'' ) as PRTY_AGMT_ASSET_END_DTTM,
:PRCS_ID as PRCS_ID,
CURRENT_TIMESTAMP as EDW_STRT_DTTM,
TO_DATE ( ''12/31/9999 23:59:59.999999'' , ''MM/DD/YYYY HH24:MI:SS.FF6'' ) as EDW_END_DTTM,
EXPTRANS.source_record_id,
row_number() over (partition by EXPTRANS.source_record_id order by EXPTRANS.source_record_id) as RNK1
FROM
EXPTRANS
INNER JOIN LKP_PRTY_ASSET_ID ON EXPTRANS.source_record_id = LKP_PRTY_ASSET_ID.source_record_id
INNER JOIN LKP_INDIV_CNT_MGR ON LKP_PRTY_ASSET_ID.source_record_id = LKP_INDIV_CNT_MGR.source_record_id
INNER JOIN LKP_AGMT_PPV ON LKP_INDIV_CNT_MGR.source_record_id = LKP_AGMT_PPV.source_record_id
LEFT JOIN LKP_TERADATA_ETL_REF_XLAT_ASSET_CONTRACT_ROLE_SBTYPE LKP_1 ON LKP_1.SRC_IDNTFTN_VAL = ''ASSET_CNTRCT_ROLE_SBTYPE1''
QUALIFY RNK1 = 1
);


-- Component LKP_PRTY_AGMT_ASSET, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_PRTY_AGMT_ASSET AS
(
SELECT
LKP.AGMT_ID,
LKP.PRTY_ASSET_ID,
LKP.PRTY_ID,
EXPTRANS1.source_record_id,
ROW_NUMBER() OVER(PARTITION BY EXPTRANS1.source_record_id ORDER BY LKP.AGMT_ID asc,LKP.PRTY_ASSET_ID asc,LKP.PRTY_ID asc) RNK
FROM
EXPTRANS1
LEFT JOIN (
SELECT
AGMT_ID,
PRTY_ASSET_ID,
PRTY_ID
FROM DB_T_PROD_CORE.PRTY_AGMT_ASSET
) LKP ON LKP.AGMT_ID = EXPTRANS1.AGMT_ID AND LKP.PRTY_ASSET_ID = EXPTRANS1.PRTY_ASSET_ID AND LKP.PRTY_ID = EXPTRANS1.PRTY_ID
QUALIFY RNK = 1
);


-- Component FILTRANS, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE FILTRANS AS
(
SELECT
LKP_PRTY_AGMT_ASSET.AGMT_ID as lkp_AGMT_ID,
EXPTRANS1.AGMT_ID as AGMT_ID,
EXPTRANS1.PRTY_AGMT_ROLE_CD as PRTY_AGMT_ROLE_CD,
EXPTRANS1.PRTY_AGMT_STRT_DTTM as PRTY_AGMT_STRT_DTTM,
EXPTRANS1.ASSET_ROLE_CD as ASSET_ROLE_CD,
EXPTRANS1.ASSET_CNTRCT_ROLE_SBTYPE_CD as ASSET_CNTRCT_ROLE_SBTYPE_CD,
EXPTRANS1.PRTY_ASSET_ID as PRTY_ASSET_ID,
EXPTRANS1.AGMT_ASSET_STRT_DT as AGMT_ASSET_STRT_DT,
EXPTRANS1.PRTY_AGMT_ASSET_STRT_DTTM as PRTY_AGMT_ASSET_STRT_DTTM,
EXPTRANS1.PRTY_ID as PRTY_ID,
EXPTRANS1.PRTY_AGMT_ASSET_END_DTTM as PRTY_AGMT_ASSET_END_DTTM,
EXPTRANS1.PRCS_ID as PRCS_ID,
EXPTRANS1.EDW_STRT_DTTM as EDW_STRT_DTTM,
EXPTRANS1.EDW_END_DTTM as EDW_END_DTTM,
EXPTRANS1.source_record_id
FROM
EXPTRANS1
LEFT JOIN LKP_PRTY_AGMT_ASSET ON EXPTRANS1.source_record_id = LKP_PRTY_AGMT_ASSET.source_record_id
WHERE LKP_PRTY_AGMT_ASSET.AGMT_ID IS NULL = 1 and EXPTRANS1.AGMT_ID IS NOT NULL = 1 and EXPTRANS1.PRTY_ID IS NOT NULL = 1
);


-- Component PRTY_AGMT_ASSET, Type TARGET 
INSERT INTO DB_T_PROD_CORE.PRTY_AGMT_ASSET
(
AGMT_ID,
PRTY_AGMT_ROLE_CD,
PRTY_AGMT_STRT_DTTM,
ASSET_ROLE_CD,
ASSET_CNTRCT_ROLE_SBTYPE_CD,
PRTY_ASSET_ID,
AGMT_ASSET_STRT_DTTM,
PRTY_AGMT_ASSET_STRT_DTTM,
PRTY_ID,
PRTY_AGMT_ASSET_END_DTTM,
PRCS_ID,
EDW_STRT_DTTM,
EDW_END_DTTM
)
SELECT
FILTRANS.AGMT_ID as AGMT_ID,
FILTRANS.PRTY_AGMT_ROLE_CD as PRTY_AGMT_ROLE_CD,
FILTRANS.PRTY_AGMT_STRT_DTTM as PRTY_AGMT_STRT_DTTM,
FILTRANS.ASSET_ROLE_CD as ASSET_ROLE_CD,
FILTRANS.ASSET_CNTRCT_ROLE_SBTYPE_CD as ASSET_CNTRCT_ROLE_SBTYPE_CD,
FILTRANS.PRTY_ASSET_ID as PRTY_ASSET_ID,
FILTRANS.AGMT_ASSET_STRT_DT as AGMT_ASSET_STRT_DTTM,
FILTRANS.PRTY_AGMT_ASSET_STRT_DTTM as PRTY_AGMT_ASSET_STRT_DTTM,
FILTRANS.PRTY_ID as PRTY_ID,
FILTRANS.PRTY_AGMT_ASSET_END_DTTM as PRTY_AGMT_ASSET_END_DTTM,
FILTRANS.PRCS_ID as PRCS_ID,
FILTRANS.EDW_STRT_DTTM as EDW_STRT_DTTM,
FILTRANS.EDW_END_DTTM as EDW_END_DTTM
FROM
FILTRANS;


END; ';