-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_MEMB_AGG_CREATE_PARAM("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_ECTL_PRGM_PARAM, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ECTL_PRGM_PARAM AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CAL_END_DATE,
$2 as MO_ID,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELect DISTINCT FEED_DT AS CAL_END_DATE, CASt(EXTRACT(YEAR FROM CAST(FEED_DT AS DATE))*100 + EXTRACT(MONTH  FROM CAST(FEED_DT AS DATE))  AS VARCHAR(6)) AS MO_ID
FROM DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER
) SRC
)
);


-- Component exp_CREATE_PARAM_FILE, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CREATE_PARAM_FILE AS
(
SELECT
''[Global]'' as out_CONNECTION_param1,
''$wf_MONTH_ID='' || SQ_ECTL_PRGM_PARAM.MO_ID as out_MONTH_ID_param3,
''$wf_CAL_END_DT='' || SQ_ECTL_PRGM_PARAM.CAL_END_DATE as out_CAL_END_DATE_param4,
SQ_ECTL_PRGM_PARAM.source_record_id
FROM
SQ_ECTL_PRGM_PARAM
);


-- Component nrm_COLUMNS_TO_RECORDS, Type NORMALIZER 
CREATE OR REPLACE TEMPORARY TABLE nrm_COLUMNS_TO_RECORDS AS
(
SELECT  * FROM
( /* start of inner SQL */
SELECT
exp_CREATE_PARAM_FILE.out_CONNECTION_param1 as WRITE_RECORD_in1,
exp_CREATE_PARAM_FILE.out_MONTH_ID_param3 as WRITE_RECORD_in2,
exp_CREATE_PARAM_FILE.out_CAL_END_DATE_param4 as WRITE_RECORD_in3,
exp_CREATE_PARAM_FILE.source_record_id,
null WRITE_RECORD
FROM
exp_CREATE_PARAM_FILE
/* end of inner SQL */
)
--UNPIVOT(WRITE_RECORD) FOR REC_NO IN (WRITE_RECORD_in1 AS REC1, WRITE_RECORD_in2 AS REC2, WRITE_RECORD_in3 AS REC3) UNPIVOT_TBL
);


-- Component MEMB_AGG_PARAM, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE MEMB_AGG_PARAM AS
(
SELECT
nrm_COLUMNS_TO_RECORDS.WRITE_RECORD as PARAM_WRITE
FROM
nrm_COLUMNS_TO_RECORDS
);


-- Component MEMB_AGG_PARAM, Type EXPORT_DATA Exporting data
;


END; ';