-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_POLICIES_BY_MEMBER_COUNT_INS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_POLICIES_BY_MEMBER, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_POLICIES_BY_MEMBER AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SYS_DATE,
$2 as MEMBERS_ALL,
$3 as POLICIES_ALL,
$4 as MEMBERS_INFORCE,
$5 as POLICIES_INFORCE,
$6 as TOTAL_COUNT,
$7 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT     
	CURRENT_DATE AS SYS_DATE,       
	X.MEMBERS_ALL,      
	Z.POLICIES_ALL,      
	Y.MEMBERS_INFORCE,      
	W.POLICIES_INFORCE,      
	T.TOTAL_COUNT  
FROM  
	(SELECT 1 AS theKEY,      
		COUNT(*) AS MEMBERS_ALL  
	FROM  
		(SELECT DISTINCT MEMBER_NUM  
		FROM DB_T_STAG_MEMBXREF_PROD.POLICIES_BY_MEMBER  
		WHERE POLICY_TYPE NOT IN (''5'',''ING'',''9'',''15'')  
		) X 
	)  X    
JOIN    
	(SELECT 1 AS theKEY,      
		COUNT(*) AS MEMBERS_INFORCE  
	FROM  
		(SELECT DISTINCT MEMBER_NUM  
		FROM DB_T_STAG_MEMBXREF_PROD.POLICIES_BY_MEMBER  
		WHERE POLICY_STATUS IN (''0'',''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''41'',''42'',''43'',''44'',''45'',''31'',''32'','''')  
			AND POLICY_TYPE NOT IN (''5'',''ING'',''9'',''15'')  
		) X 
	) Y ON X.theKEY = Y.theKEY    
JOIN    
	(SELECT 1 AS theKEY,      
		COUNT(*) AS POLICIES_ALL  
	FROM DB_T_STAG_MEMBXREF_PROD.POLICIES_BY_MEMBER  
	WHERE POLICY_TYPE NOT IN (''5'',''ING'',''9'',''15'')  
	) Z ON X.theKEY = Z.theKEY    
JOIN    
	(SELECT 1 AS theKEY,      
		COUNT(*) AS POLICIES_INFORCE  
	FROM DB_T_STAG_MEMBXREF_PROD.POLICIES_BY_MEMBER  
	WHERE POLICY_STATUS IN (''0'',''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''41'',''42'',''43'',''44'',''45'',''31'',''32'','''')  
		AND POLICY_TYPE NOT IN (''5'',''ING'',''9'',''15'')  
	) W ON X.theKEY = W.theKEY    
JOIN  
	(SELECT 1 AS theKEY,          
		COUNT(*) AS TOTAL_COUNT  
	FROM DB_T_STAG_MEMBXREF_PROD.POLICIES_BY_MEMBER
	) T ON W.theKEY = T.theKEY
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_POLICIES_BY_MEMBER.SYS_DATE as SYS_DATE,
SQ_POLICIES_BY_MEMBER.MEMBERS_ALL as MEMBERS_ALL,
SQ_POLICIES_BY_MEMBER.POLICIES_ALL as POLICIES_ALL,
SQ_POLICIES_BY_MEMBER.MEMBERS_INFORCE as MEMBERS_INFORCE,
SQ_POLICIES_BY_MEMBER.POLICIES_INFORCE as POLICIES_INFORCE,
SQ_POLICIES_BY_MEMBER.TOTAL_COUNT as TOTAL_COUNT,
SQ_POLICIES_BY_MEMBER.source_record_id
FROM
SQ_POLICIES_BY_MEMBER
);


-- Component POLICIES_BY_MEMBER_COUNT, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.POLICIES_BY_MEMBER_COUNT
(
SYS_DATE,
MEMBERS_ALL,
POLICIES_ALL,
MEMBERS_INFORCE,
POLICIES_INFORCE,
TOTAL_COUNT
)
SELECT
EXPTRANS.SYS_DATE as SYS_DATE,
EXPTRANS.MEMBERS_ALL as MEMBERS_ALL,
EXPTRANS.POLICIES_ALL as POLICIES_ALL,
EXPTRANS.MEMBERS_INFORCE as MEMBERS_INFORCE,
EXPTRANS.POLICIES_INFORCE as POLICIES_INFORCE,
EXPTRANS.TOTAL_COUNT as TOTAL_COUNT
FROM
EXPTRANS;


-- Component POLICIES_BY_MEMBER_COUNT, Type Post SQL 
--COLLECT STATISTICS on POL_VEH_LIST INDEX (CLIENT_REF_NBR,POL_NBR, POLICY_ID, EFFECTIVE_DT, EXPIRATION_DT, VEH_UNIT_NBR);
--COLLECT STATISTICS on POL_VEH_LIST COLUMN (TOT_PRM_AMT);
--COLLECT STATISTICS on POLICIES_BY_MEMBER INDEX (POLICY_NUM);
--COLLECT STATISTICS on POLICIES_BY_MEMBER INDEX (MEMBER_NUM);
--COLLECT STATISTICS on POLICIES_BY_MEMBER COLUMN (EXPIRATION_DATE);


END; ';