-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_CTS_CLAIMS_INFO("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 

-- Component CTS_CLAIMS_INFO2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_ML_PROD.CTS_CLAIMS_INFO;


-- PIPELINE START FOR 1

-- Component SQ_CTS_CLAIMS_INFO1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CTS_CLAIMS_INFO1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as RECORD_COUNT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
 DB_T_ML_PROD.CTS_CLAIMS_INFO
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_CTS_CLAIMS_INFO1.RECORD_COUNT as record_count,
:feed_ind as feed_ind,
to_char ( CURRENT_TIMESTAMP , ''YYYY-MM-DD'' ) as feed_dt,
SQ_CTS_CLAIMS_INFO1.source_record_id
FROM
SQ_CTS_CLAIMS_INFO1
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_CTS_CLAIMS_INFO, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CTS_CLAIMS_INFO AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CLAIMS_TRACK_NUM,
$2 as CAT_CODE,
$3 as CLAIM_TYPE,
$4 as POLICY_NUMBER,
$5 as FLT_ITEM,
$6 as PAID_FROM,
$7 as PAID_TO,
$8 as CHG_PAID_FROM,
$9 as CHG_PAID_TO,
$10 as LOSS_DATE,
$11 as LOSS_TIME,
$12 as LOSS_DESCRIPTION,
$13 as MORTGAGEE,
$14 as DEDUCTIBLE,
$15 as LOCATION_ADDRESS,
$16 as LOCATION_CITY,
$17 as LOCATION_STATE,
$18 as LOCATION_ZIP,
$19 as LOCATION_ZIP4,
$20 as PRIORITY,
$21 as PRIORITY_OR,
$22 as COMPANY,
$23 as SC_NUMBER,
$24 as AGENT_NUMBER,
$25 as ADJUSTER,
$26 as ADJUSTER_EMAIL,
$27 as ASSIGN_DATE,
$28 as PREV_ADJ,
$29 as PREV_ADJ_EMAIL,
$30 as PREV_ASSIGN_DATE,
$31 as NAME,
$32 as NAME_2,
$33 as ADDRESS,
$34 as ADDRESS_2,
$35 as CITY_STATE,
$36 as STATE,
$37 as ZIP,
$38 as COMMUNITY,
$39 as HOME_PHONE,
$40 as CELL_PHONE,
$41 as WORK_PHONE,
$42 as WORK_PHONE_EXT,
$43 as E_MAIL,
$44 as DATE_REPORTED,
$45 as REPORTED_TO,
$46 as SYSTEM_CODE,
$47 as ALPHACODE,
$48 as ALPHACODE2,
$49 as CURR_STAT,
$50 as CURR_STAT_DATE,
$51 as CURR_STAT_TIME,
$52 as PREV_STAT,
$53 as PREV_STAT_DATE,
$54 as PREV_STAT_TIME,
$55 as UNDERPAYMENT,
$56 as OUT_DATE,
$57 as TIME_REPORTED,
$58 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
CTS_CLAIMS_INFO.CLAIMS_TRACK_NUM,
CTS_CLAIMS_INFO.CAT_CODE,
CTS_CLAIMS_INFO.CLAIM_TYPE,
CTS_CLAIMS_INFO.POLICY_NUMBER,
CTS_CLAIMS_INFO.FLT_ITEM,
CTS_CLAIMS_INFO.PAID_FROM,
CTS_CLAIMS_INFO.PAID_TO,
CTS_CLAIMS_INFO.CHG_PAID_FROM,
CTS_CLAIMS_INFO.CHG_PAID_TO,
CTS_CLAIMS_INFO.LOSS_DATE,
CTS_CLAIMS_INFO.LOSS_TIME,
CTS_CLAIMS_INFO.LOSS_DESCRIPTION,
CTS_CLAIMS_INFO.MORTGAGEE,
CTS_CLAIMS_INFO.DEDUCTIBLE,
CTS_CLAIMS_INFO.LOCATION_ADDRESS,
CTS_CLAIMS_INFO.LOCATION_CITY,
CTS_CLAIMS_INFO.LOCATION_STATE,
CTS_CLAIMS_INFO.LOCATION_ZIP,
CTS_CLAIMS_INFO.LOCATION_ZIP4,
CTS_CLAIMS_INFO.PRIORITY,
CTS_CLAIMS_INFO.PRIORITY_OR,
CTS_CLAIMS_INFO.COMPANY,
CTS_CLAIMS_INFO.SC_NUMBER,
CTS_CLAIMS_INFO.AGENT_NUMBER,
CTS_CLAIMS_INFO.ADJUSTER,
CTS_CLAIMS_INFO.ADJUSTER_EMAIL,
CTS_CLAIMS_INFO.ASSIGN_DATE,
CTS_CLAIMS_INFO.PREV_ADJ,
CTS_CLAIMS_INFO.PREV_ADJ_EMAIL,
CTS_CLAIMS_INFO.PREV_ASSIGN_DATE,
CTS_CLAIMS_INFO.NAME,
CTS_CLAIMS_INFO.NAME_2,
CTS_CLAIMS_INFO.ADDRESS,
CTS_CLAIMS_INFO.ADDRESS_2,
CTS_CLAIMS_INFO.CITY_STATE,
CTS_CLAIMS_INFO.STATE,
CTS_CLAIMS_INFO.ZIP,
CTS_CLAIMS_INFO.COMMUNITY,
CTS_CLAIMS_INFO.HOME_PHONE,
CTS_CLAIMS_INFO.CELL_PHONE,
CTS_CLAIMS_INFO.WORK_PHONE,
CTS_CLAIMS_INFO.WORK_PHONE_EXT,
CTS_CLAIMS_INFO.E_MAIL,
CTS_CLAIMS_INFO.DATE_REPORTED,
CTS_CLAIMS_INFO.REPORTED_TO,
CTS_CLAIMS_INFO.SYSTEM_CODE,
CTS_CLAIMS_INFO.ALPHACODE,
CTS_CLAIMS_INFO.ALPHACODE2,
CTS_CLAIMS_INFO.CURR_STAT,
CTS_CLAIMS_INFO.CURR_STAT_DATE,
CTS_CLAIMS_INFO.CURR_STAT_TIME,
CTS_CLAIMS_INFO.PREV_STAT,
CTS_CLAIMS_INFO.PREV_STAT_DATE,
CTS_CLAIMS_INFO.PREV_STAT_TIME,
CTS_CLAIMS_INFO.UNDERPAYMENT,
CTS_CLAIMS_INFO.OUT_DATE,
CTS_CLAIMS_INFO.TIME_REPORTED
FROM DB_T_ML_PROD.CTS_CLAIMS_INFO
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_CTS_CLAIMS_INFO.CLAIMS_TRACK_NUM as CLAIMS_TRACK_NUM,
SQ_CTS_CLAIMS_INFO.CAT_CODE as CAT_CODE,
SQ_CTS_CLAIMS_INFO.CLAIM_TYPE as CLAIM_TYPE,
SQ_CTS_CLAIMS_INFO.POLICY_NUMBER as POLICY_NUMBER,
SQ_CTS_CLAIMS_INFO.FLT_ITEM as FLT_ITEM,
SQ_CTS_CLAIMS_INFO.PAID_FROM as PAID_FROM,
SQ_CTS_CLAIMS_INFO.PAID_TO as PAID_TO,
SQ_CTS_CLAIMS_INFO.CHG_PAID_FROM as CHG_PAID_FROM,
SQ_CTS_CLAIMS_INFO.CHG_PAID_TO as CHG_PAID_TO,
SQ_CTS_CLAIMS_INFO.LOSS_DATE as LOSS_DATE,
TO_CHAR ( SQ_CTS_CLAIMS_INFO.LOSS_TIME ) as o_LOSS_TIME,
SQ_CTS_CLAIMS_INFO.LOSS_DESCRIPTION as LOSS_DESCRIPTION,
SQ_CTS_CLAIMS_INFO.MORTGAGEE as MORTGAGEE,
SQ_CTS_CLAIMS_INFO.DEDUCTIBLE as DEDUCTIBLE,
SQ_CTS_CLAIMS_INFO.LOCATION_ADDRESS as LOCATION_ADDRESS,
SQ_CTS_CLAIMS_INFO.LOCATION_CITY as LOCATION_CITY,
SQ_CTS_CLAIMS_INFO.LOCATION_STATE as LOCATION_STATE,
SQ_CTS_CLAIMS_INFO.LOCATION_ZIP as LOCATION_ZIP,
SQ_CTS_CLAIMS_INFO.LOCATION_ZIP4 as LOCATION_ZIP4,
SQ_CTS_CLAIMS_INFO.PRIORITY as PRIORITY,
SQ_CTS_CLAIMS_INFO.PRIORITY_OR as PRIORITY_OR,
SQ_CTS_CLAIMS_INFO.COMPANY as COMPANY,
SQ_CTS_CLAIMS_INFO.SC_NUMBER as SC_NUMBER,
SQ_CTS_CLAIMS_INFO.AGENT_NUMBER as AGENT_NUMBER,
SQ_CTS_CLAIMS_INFO.ADJUSTER as ADJUSTER,
SQ_CTS_CLAIMS_INFO.ADJUSTER_EMAIL as ADJUSTER_EMAIL,
SQ_CTS_CLAIMS_INFO.ASSIGN_DATE as ASSIGN_DATE,
SQ_CTS_CLAIMS_INFO.PREV_ADJ as PREV_ADJ,
SQ_CTS_CLAIMS_INFO.PREV_ADJ_EMAIL as PREV_ADJ_EMAIL,
SQ_CTS_CLAIMS_INFO.PREV_ASSIGN_DATE as PREV_ASSIGN_DATE,
SQ_CTS_CLAIMS_INFO.NAME as NAME,
SQ_CTS_CLAIMS_INFO.NAME_2 as NAME_2,
SQ_CTS_CLAIMS_INFO.ADDRESS as ADDRESS,
SQ_CTS_CLAIMS_INFO.ADDRESS_2 as ADDRESS_2,
SQ_CTS_CLAIMS_INFO.CITY_STATE as CITY_STATE,
SQ_CTS_CLAIMS_INFO.STATE as STATE,
SQ_CTS_CLAIMS_INFO.ZIP as ZIP,
SQ_CTS_CLAIMS_INFO.COMMUNITY as COMMUNITY,
SQ_CTS_CLAIMS_INFO.HOME_PHONE as HOME_PHONE,
SQ_CTS_CLAIMS_INFO.CELL_PHONE as CELL_PHONE,
SQ_CTS_CLAIMS_INFO.WORK_PHONE as WORK_PHONE,
SQ_CTS_CLAIMS_INFO.WORK_PHONE_EXT as WORK_PHONE_EXT,
SQ_CTS_CLAIMS_INFO.E_MAIL as E_MAIL,
SQ_CTS_CLAIMS_INFO.DATE_REPORTED as DATE_REPORTED,
SQ_CTS_CLAIMS_INFO.REPORTED_TO as REPORTED_TO,
SQ_CTS_CLAIMS_INFO.SYSTEM_CODE as SYSTEM_CODE,
SQ_CTS_CLAIMS_INFO.ALPHACODE as ALPHACODE,
SQ_CTS_CLAIMS_INFO.ALPHACODE2 as ALPHACODE2,
SQ_CTS_CLAIMS_INFO.CURR_STAT as CURR_STAT,
SQ_CTS_CLAIMS_INFO.CURR_STAT_DATE as CURR_STAT_DATE,
TO_CHAR ( SQ_CTS_CLAIMS_INFO.CURR_STAT_TIME ) as o_CURR_STAT_TIME,
SQ_CTS_CLAIMS_INFO.PREV_STAT as PREV_STAT,
SQ_CTS_CLAIMS_INFO.PREV_STAT_DATE as PREV_STAT_DATE,
TO_CHAR ( SQ_CTS_CLAIMS_INFO.PREV_STAT_TIME ) as o_PREV_STAT_TIME,
SQ_CTS_CLAIMS_INFO.UNDERPAYMENT as UNDERPAYMENT,
SQ_CTS_CLAIMS_INFO.OUT_DATE as OUT_DATE,
SQ_CTS_CLAIMS_INFO.TIME_REPORTED as TIME_REPORTED,
SQ_CTS_CLAIMS_INFO.source_record_id
FROM
SQ_CTS_CLAIMS_INFO
);


-- Component CTS_CLAIMS_INFO2, Type TARGET 
INSERT INTO DB_T_ML_PROD.CTS_CLAIMS_INFO
(
CLAIMS_TRACK_NUM,
CAT_CODE,
CLAIM_TYPE,
POLICY_NUMBER,
FLT_ITEM,
PAID_FROM,
PAID_TO,
CHG_PAID_FROM,
CHG_PAID_TO,
LOSS_DATE,
LOSS_TIME,
LOSS_DESCRIPTION,
MORTGAGEE,
DEDUCTIBLE,
LOCATION_ADDRESS,
LOCATION_CITY,
LOCATION_STATE,
LOCATION_ZIP,
LOCATION_ZIP4,
PRIORITY,
PRIORITY_OR,
COMPANY,
SC_NUMBER,
AGENT_NUMBER,
ADJUSTER,
ADJUSTER_EMAIL,
ASSIGN_DATE,
PREV_ADJ,
PREV_ADJ_EMAIL,
PREV_ASSIGN_DATE,
NAME,
NAME_2,
ADDRESS,
ADDRESS_2,
CITY_STATE,
STATE,
ZIP,
COMMUNITY,
HOME_PHONE,
CELL_PHONE,
WORK_PHONE,
WORK_PHONE_EXT,
E_MAIL,
DATE_REPORTED,
REPORTED_TO,
SYSTEM_CODE,
ALPHACODE,
ALPHACODE2,
CURR_STAT,
CURR_STAT_DATE,
CURR_STAT_TIME,
PREV_STAT,
PREV_STAT_DATE,
PREV_STAT_TIME,
UNDERPAYMENT,
OUT_DATE,
TIME_REPORTED
)
SELECT
exp_pass_through.CLAIMS_TRACK_NUM as CLAIMS_TRACK_NUM,
exp_pass_through.CAT_CODE as CAT_CODE,
exp_pass_through.CLAIM_TYPE as CLAIM_TYPE,
exp_pass_through.POLICY_NUMBER as POLICY_NUMBER,
exp_pass_through.FLT_ITEM as FLT_ITEM,
exp_pass_through.PAID_FROM as PAID_FROM,
exp_pass_through.PAID_TO as PAID_TO,
exp_pass_through.CHG_PAID_FROM as CHG_PAID_FROM,
exp_pass_through.CHG_PAID_TO as CHG_PAID_TO,
exp_pass_through.LOSS_DATE as LOSS_DATE,
exp_pass_through.o_LOSS_TIME as LOSS_TIME,
exp_pass_through.LOSS_DESCRIPTION as LOSS_DESCRIPTION,
exp_pass_through.MORTGAGEE as MORTGAGEE,
exp_pass_through.DEDUCTIBLE as DEDUCTIBLE,
exp_pass_through.LOCATION_ADDRESS as LOCATION_ADDRESS,
exp_pass_through.LOCATION_CITY as LOCATION_CITY,
exp_pass_through.LOCATION_STATE as LOCATION_STATE,
exp_pass_through.LOCATION_ZIP as LOCATION_ZIP,
exp_pass_through.LOCATION_ZIP4 as LOCATION_ZIP4,
exp_pass_through.PRIORITY as PRIORITY,
exp_pass_through.PRIORITY_OR as PRIORITY_OR,
exp_pass_through.COMPANY as COMPANY,
exp_pass_through.SC_NUMBER as SC_NUMBER,
exp_pass_through.AGENT_NUMBER as AGENT_NUMBER,
exp_pass_through.ADJUSTER as ADJUSTER,
exp_pass_through.ADJUSTER_EMAIL as ADJUSTER_EMAIL,
exp_pass_through.ASSIGN_DATE as ASSIGN_DATE,
exp_pass_through.PREV_ADJ as PREV_ADJ,
exp_pass_through.PREV_ADJ_EMAIL as PREV_ADJ_EMAIL,
exp_pass_through.PREV_ASSIGN_DATE as PREV_ASSIGN_DATE,
exp_pass_through.NAME as NAME,
exp_pass_through.NAME_2 as NAME_2,
exp_pass_through.ADDRESS as ADDRESS,
exp_pass_through.ADDRESS_2 as ADDRESS_2,
exp_pass_through.CITY_STATE as CITY_STATE,
exp_pass_through.STATE as STATE,
exp_pass_through.ZIP as ZIP,
exp_pass_through.COMMUNITY as COMMUNITY,
exp_pass_through.HOME_PHONE as HOME_PHONE,
exp_pass_through.CELL_PHONE as CELL_PHONE,
exp_pass_through.WORK_PHONE as WORK_PHONE,
exp_pass_through.WORK_PHONE_EXT as WORK_PHONE_EXT,
exp_pass_through.E_MAIL as E_MAIL,
exp_pass_through.DATE_REPORTED as DATE_REPORTED,
exp_pass_through.REPORTED_TO as REPORTED_TO,
exp_pass_through.SYSTEM_CODE as SYSTEM_CODE,
exp_pass_through.ALPHACODE as ALPHACODE,
exp_pass_through.ALPHACODE2 as ALPHACODE2,
exp_pass_through.CURR_STAT as CURR_STAT,
exp_pass_through.CURR_STAT_DATE as CURR_STAT_DATE,
exp_pass_through.o_CURR_STAT_TIME as CURR_STAT_TIME,
exp_pass_through.PREV_STAT as PREV_STAT,
exp_pass_through.PREV_STAT_DATE as PREV_STAT_DATE,
exp_pass_through.o_PREV_STAT_TIME as PREV_STAT_TIME,
exp_pass_through.UNDERPAYMENT as UNDERPAYMENT,
exp_pass_through.OUT_DATE as OUT_DATE,
exp_pass_through.TIME_REPORTED as TIME_REPORTED
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';