-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_CTS_PROPERTY("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE FEED_IND varchar;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 

-- Component CTS_PROPERTY2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_ML_PROD.CTS_PROPERTY;


-- PIPELINE START FOR 1

-- Component SQ_CTS_PROPERTY, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CTS_PROPERTY AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CLAIMS_TRACK_NUM,
$2 as FORM,
$3 as COVERAGE_1,
$4 as COVERAGE_2,
$5 as COVERAGE_3,
$6 as COVERAGE_4,
$7 as COVERAGE_5,
$8 as COVERAGE_6,
$9 as COVERAGE_7,
$10 as COVERAGE_8,
$11 as DESCRIPTION,
$12 as DRIVING_DIRECTIONS,
$13 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
CTS_PROPERTY.CLAIMS_TRACK_NUM,
CTS_PROPERTY.FORM,
CTS_PROPERTY.COVERAGE_1,
CTS_PROPERTY.COVERAGE_2,
CTS_PROPERTY.COVERAGE_3,
CTS_PROPERTY.COVERAGE_4,
CTS_PROPERTY.COVERAGE_5,
CTS_PROPERTY.COVERAGE_6,
CTS_PROPERTY.COVERAGE_7,
CTS_PROPERTY.COVERAGE_8,
CTS_PROPERTY.DESCRIPTION,
CTS_PROPERTY.DRIVING_DIRECTIONS
FROM DB_T_ML_PROD.CTS_PROPERTY
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_CTS_PROPERTY.CLAIMS_TRACK_NUM as CLAIMS_TRACK_NUM,
SQ_CTS_PROPERTY.FORM as FORM,
SQ_CTS_PROPERTY.COVERAGE_1 as COVERAGE_1,
SQ_CTS_PROPERTY.COVERAGE_2 as COVERAGE_2,
SQ_CTS_PROPERTY.COVERAGE_3 as COVERAGE_3,
SQ_CTS_PROPERTY.COVERAGE_4 as COVERAGE_4,
SQ_CTS_PROPERTY.COVERAGE_5 as COVERAGE_5,
SQ_CTS_PROPERTY.COVERAGE_6 as COVERAGE_6,
SQ_CTS_PROPERTY.COVERAGE_7 as COVERAGE_7,
SQ_CTS_PROPERTY.COVERAGE_8 as COVERAGE_8,
SQ_CTS_PROPERTY.DESCRIPTION as DESCRIPTION,
SQ_CTS_PROPERTY.DRIVING_DIRECTIONS as DRIVING_DIRECTIONS,
SQ_CTS_PROPERTY.source_record_id
FROM
SQ_CTS_PROPERTY
);


-- Component CTS_PROPERTY2, Type TARGET 
INSERT INTO DB_T_ML_PROD.CTS_PROPERTY
(
CLAIMS_TRACK_NUM,
FORM,
COVERAGE_1,
COVERAGE_2,
COVERAGE_3,
COVERAGE_4,
COVERAGE_5,
COVERAGE_6,
COVERAGE_7,
COVERAGE_8,
DESCRIPTION,
DRIVING_DIRECTIONS
)
SELECT
exp_pass_through.CLAIMS_TRACK_NUM as CLAIMS_TRACK_NUM,
exp_pass_through.FORM as FORM,
exp_pass_through.COVERAGE_1 as COVERAGE_1,
exp_pass_through.COVERAGE_2 as COVERAGE_2,
exp_pass_through.COVERAGE_3 as COVERAGE_3,
exp_pass_through.COVERAGE_4 as COVERAGE_4,
exp_pass_through.COVERAGE_5 as COVERAGE_5,
exp_pass_through.COVERAGE_6 as COVERAGE_6,
exp_pass_through.COVERAGE_7 as COVERAGE_7,
exp_pass_through.COVERAGE_8 as COVERAGE_8,
exp_pass_through.DESCRIPTION as DESCRIPTION,
exp_pass_through.DRIVING_DIRECTIONS as DRIVING_DIRECTIONS
FROM
exp_pass_through;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_CTS_PROPERTY1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CTS_PROPERTY1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as RECORD_COUNT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
 DB_T_ML_PROD.CTS_PROPERTY
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_CTS_PROPERTY1.RECORD_COUNT as record_count,
:feed_ind as feed_ind,
to_char ( CURRENT_TIMESTAMP , ''YYYY-MM-DD'' ) as feed_dt,
SQ_CTS_PROPERTY1.source_record_id
FROM
SQ_CTS_PROPERTY1
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 2

END; ';