-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_CTS_PROPERTY_MH("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id);

-- Component CTS_PROPERTY_MH2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_ML_PROD.CTS_PROPERTY_MH;


-- PIPELINE START FOR 1

-- Component SQ_CTS_PROPERTY_MH1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CTS_PROPERTY_MH1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as RECORD_COUNT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
 DB_T_ML_PROD.CTS_PROPERTY_MH
) SRC
)
);


-- PIPELINE START FOR 2

-- Component SQ_CTS_PROPERTY_MH, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CTS_PROPERTY_MH AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CLAIMS_TRACK_NUM,
$2 as MANUFACTURER,
$3 as MODEL,
$4 as SERIAL_NUMBER,
$5 as MH_YEAR,
$6 as LENGTH,
$7 as WIDTH,
$8 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
CTS_PROPERTY_MH.CLAIMS_TRACK_NUM,
CTS_PROPERTY_MH.MANUFACTURER,
CTS_PROPERTY_MH.MODEL,
CTS_PROPERTY_MH.SERIAL_NUMBER,
CTS_PROPERTY_MH.MH_YEAR,
CTS_PROPERTY_MH.LENGTH,
CTS_PROPERTY_MH.WIDTH
FROM DB_T_ML_PROD.CTS_PROPERTY_MH
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_CTS_PROPERTY_MH1.RECORD_COUNT as record_count,
:feed_ind as feed_ind,
to_char ( CURRENT_TIMESTAMP , ''YYYY-MM-DD'' ) as feed_dt,
SQ_CTS_PROPERTY_MH1.source_record_id
FROM
SQ_CTS_PROPERTY_MH1
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_CTS_PROPERTY_MH.CLAIMS_TRACK_NUM as CLAIMS_TRACK_NUM,
SQ_CTS_PROPERTY_MH.MANUFACTURER as MANUFACTURER,
SQ_CTS_PROPERTY_MH.MODEL as MODEL,
SQ_CTS_PROPERTY_MH.SERIAL_NUMBER as SERIAL_NUMBER,
SQ_CTS_PROPERTY_MH.MH_YEAR as MH_YEAR,
SQ_CTS_PROPERTY_MH.LENGTH as LENGTH,
SQ_CTS_PROPERTY_MH.WIDTH as WIDTH,
SQ_CTS_PROPERTY_MH.source_record_id
FROM
SQ_CTS_PROPERTY_MH
);


-- Component CTS_PROPERTY_MH2, Type TARGET 
INSERT INTO DB_T_ML_PROD.CTS_PROPERTY_MH
(
CLAIMS_TRACK_NUM,
MANUFACTURER,
MODEL,
SERIAL_NUMBER,
MH_YEAR,
LENGTH,
WIDTH
)
SELECT
exp_pass_through.CLAIMS_TRACK_NUM as CLAIMS_TRACK_NUM,
exp_pass_through.MANUFACTURER as MANUFACTURER,
exp_pass_through.MODEL as MODEL,
exp_pass_through.SERIAL_NUMBER as SERIAL_NUMBER,
exp_pass_through.MH_YEAR as MH_YEAR,
exp_pass_through.LENGTH as LENGTH,
exp_pass_through.WIDTH as WIDTH
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';