-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_FARMCLAIMTOTALS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
FEED_DT date;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 
FEED_DT:=(select current_date); 

-- Component FARMCLAIMTOTALS1, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.FARMCLAIMTOTALS;


-- PIPELINE START FOR 1

-- Component SQ_FARMCLAIMTOTALS2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMCLAIMTOTALS2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
DB_T_STAG_MEMBXREF_PROD.FARMCLAIMTOTALS
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_FARMCLAIMTOTALS2.record_count as record_count,
:feed_ind as feed_ind,
:feed_dt as feed_dt,
SQ_FARMCLAIMTOTALS2.source_record_id
FROM
SQ_FARMCLAIMTOTALS2
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_FARMCLAIMTOTALS3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMCLAIMTOTALS3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_CLMT_NDX,
$3 as RFD_YR,
$4 as RFD_DWELL,
$5 as RFD_UNSCH,
$6 as RFD_ADDL,
$7 as RFD_LIAB,
$8 as RFD_MED,
$9 as RFD_OUTBLDG,
$10 as RFD_PD,
$11 as RFD_NMED,
$12 as RFD_LVSTK,
$13 as RFD_MACH,
$14 as RFD_TOT_CLMS,
$15 as RFD_TOT_AMT,
$16 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
FARMCLAIMTOTALS.SC_POLICY_NUM,
FARMCLAIMTOTALS.RFD_CLMT_NDX,
FARMCLAIMTOTALS.RFD_YR,
FARMCLAIMTOTALS.RFD_DWELL,
FARMCLAIMTOTALS.RFD_UNSCH,
FARMCLAIMTOTALS.RFD_ADDL,
FARMCLAIMTOTALS.RFD_LIAB,
FARMCLAIMTOTALS.RFD_MED,
FARMCLAIMTOTALS.RFD_OUTBLDG,
FARMCLAIMTOTALS.RFD_PD,
FARMCLAIMTOTALS.RFD_NMED,
FARMCLAIMTOTALS.RFD_LVSTK,
FARMCLAIMTOTALS.RFD_MACH,
FARMCLAIMTOTALS.RFD_TOT_CLMS,
FARMCLAIMTOTALS.RFD_TOT_AMT
FROM DB_T_STAG_MEMBXREF_PROD.FARMCLAIMTOTALS
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_FARMCLAIMTOTALS3.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMCLAIMTOTALS3.RFD_CLMT_NDX as RFD_CLMT_NDX,
SQ_FARMCLAIMTOTALS3.RFD_YR as RFD_YR,
SQ_FARMCLAIMTOTALS3.RFD_DWELL as RFD_DWELL,
SQ_FARMCLAIMTOTALS3.RFD_UNSCH as RFD_UNSCH,
SQ_FARMCLAIMTOTALS3.RFD_ADDL as RFD_ADDL,
SQ_FARMCLAIMTOTALS3.RFD_LIAB as RFD_LIAB,
SQ_FARMCLAIMTOTALS3.RFD_MED as RFD_MED,
SQ_FARMCLAIMTOTALS3.RFD_OUTBLDG as RFD_OUTBLDG,
SQ_FARMCLAIMTOTALS3.RFD_PD as RFD_PD,
SQ_FARMCLAIMTOTALS3.RFD_NMED as RFD_NMED,
SQ_FARMCLAIMTOTALS3.RFD_LVSTK as RFD_LVSTK,
SQ_FARMCLAIMTOTALS3.RFD_MACH as RFD_MACH,
SQ_FARMCLAIMTOTALS3.RFD_TOT_CLMS as RFD_TOT_CLMS,
SQ_FARMCLAIMTOTALS3.RFD_TOT_AMT as RFD_TOT_AMT,
SQ_FARMCLAIMTOTALS3.source_record_id
FROM
SQ_FARMCLAIMTOTALS3
);


-- Component FARMCLAIMTOTALS1, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.FARMCLAIMTOTALS
(
SC_POLICY_NUM,
RFD_CLMT_NDX,
RFD_YR,
RFD_DWELL,
RFD_UNSCH,
RFD_ADDL,
RFD_LIAB,
RFD_MED,
RFD_OUTBLDG,
RFD_PD,
RFD_NMED,
RFD_LVSTK,
RFD_MACH,
RFD_TOT_CLMS,
RFD_TOT_AMT
)
SELECT
exp_pass_through.SC_POLICY_NUM as SC_POLICY_NUM,
exp_pass_through.RFD_CLMT_NDX as RFD_CLMT_NDX,
exp_pass_through.RFD_YR as RFD_YR,
exp_pass_through.RFD_DWELL as RFD_DWELL,
exp_pass_through.RFD_UNSCH as RFD_UNSCH,
exp_pass_through.RFD_ADDL as RFD_ADDL,
exp_pass_through.RFD_LIAB as RFD_LIAB,
exp_pass_through.RFD_MED as RFD_MED,
exp_pass_through.RFD_OUTBLDG as RFD_OUTBLDG,
exp_pass_through.RFD_PD as RFD_PD,
exp_pass_through.RFD_NMED as RFD_NMED,
exp_pass_through.RFD_LVSTK as RFD_LVSTK,
exp_pass_through.RFD_MACH as RFD_MACH,
exp_pass_through.RFD_TOT_CLMS as RFD_TOT_CLMS,
exp_pass_through.RFD_TOT_AMT as RFD_TOT_AMT
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';