-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_FARMDWLS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
FEED_DT date;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 
FEED_DT:=(select current_date); 

-- Component FARMDWLS1, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.FARMDWLS;


-- PIPELINE START FOR 1

-- Component SQ_FARMDWLS1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMDWLS1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
DB_T_STAG_MEMBXREF_PROD.FARMDWLS
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_FARMDWLS1.record_count as record_count,
:feed_ind as feed_ind,
:feed_dt as feed_dt,
SQ_FARMDWLS1.source_record_id
FROM
SQ_FARMDWLS1
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_FARMDWLS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMDWLS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_DWL_NDX,
$3 as RFD_DWL_CLASS,
$4 as RFD_DWL_DED,
$5 as RFD_DWL_PREM,
$6 as RFD_DWL_COV,
$7 as RFD_DWL_UNSCH,
$8 as RFD_DWL_ADDL,
$9 as RFD_DWL_HS,
$10 as RFD_DWL_CNSTYR,
$11 as RFD_INFL_DWL_IND,
$12 as RFD_DWL_CNTY,
$13 as RFD_DWL_FO85,
$14 as RFD_DWL_FO1,
$15 as RFD_DWL_FO45,
$16 as RFD_PDWL_CLASS,
$17 as RFD_PDWL_DED,
$18 as RFD_PDWL_COV,
$19 as RFD_PDWL_UNSCH,
$20 as RFD_DWL_COV_DT,
$21 as RFD_DWL_BCOV_DT,
$22 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
FARMDWLS.SC_POLICY_NUM,
FARMDWLS.RFD_DWL_NDX,
FARMDWLS.RFD_DWL_CLASS,
FARMDWLS.RFD_DWL_DED,
FARMDWLS.RFD_DWL_PREM,
FARMDWLS.RFD_DWL_COV,
FARMDWLS.RFD_DWL_UNSCH,
FARMDWLS.RFD_DWL_ADDL,
FARMDWLS.RFD_DWL_HS,
FARMDWLS.RFD_DWL_CNSTYR,
FARMDWLS.RFD_INFL_DWL_IND,
FARMDWLS.RFD_DWL_CNTY,
FARMDWLS.RFD_DWL_FO85,
FARMDWLS.RFD_DWL_FO1,
FARMDWLS.RFD_DWL_FO45,
FARMDWLS.RFD_PDWL_CLASS,
FARMDWLS.RFD_PDWL_DED,
FARMDWLS.RFD_PDWL_COV,
FARMDWLS.RFD_PDWL_UNSCH,
FARMDWLS.RFD_DWL_COV_DT,
FARMDWLS.RFD_DWL_BCOV_DT
FROM DB_T_STAG_MEMBXREF_PROD.FARMDWLS
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_FARMDWLS.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMDWLS.RFD_DWL_NDX as RFD_DWL_NDX,
SQ_FARMDWLS.RFD_DWL_CLASS as RFD_DWL_CLASS,
SQ_FARMDWLS.RFD_DWL_DED as RFD_DWL_DED,
SQ_FARMDWLS.RFD_DWL_PREM as RFD_DWL_PREM,
SQ_FARMDWLS.RFD_DWL_COV as RFD_DWL_COV,
SQ_FARMDWLS.RFD_DWL_UNSCH as RFD_DWL_UNSCH,
SQ_FARMDWLS.RFD_DWL_ADDL as RFD_DWL_ADDL,
SQ_FARMDWLS.RFD_DWL_HS as RFD_DWL_HS,
SQ_FARMDWLS.RFD_DWL_CNSTYR as RFD_DWL_CNSTYR,
SQ_FARMDWLS.RFD_INFL_DWL_IND as RFD_INFL_DWL_IND,
SQ_FARMDWLS.RFD_DWL_CNTY as RFD_DWL_CNTY,
SQ_FARMDWLS.RFD_DWL_FO85 as RFD_DWL_FO85,
SQ_FARMDWLS.RFD_DWL_FO1 as RFD_DWL_FO1,
SQ_FARMDWLS.RFD_DWL_FO45 as RFD_DWL_FO45,
SQ_FARMDWLS.RFD_PDWL_CLASS as RFD_PDWL_CLASS,
SQ_FARMDWLS.RFD_PDWL_DED as RFD_PDWL_DED,
SQ_FARMDWLS.RFD_PDWL_COV as RFD_PDWL_COV,
SQ_FARMDWLS.RFD_PDWL_UNSCH as RFD_PDWL_UNSCH,
SQ_FARMDWLS.RFD_DWL_COV_DT as RFD_DWL_COV_DT,
SQ_FARMDWLS.RFD_DWL_BCOV_DT as RFD_DWL_BCOV_DT,
SQ_FARMDWLS.source_record_id
FROM
SQ_FARMDWLS
);


-- Component FARMDWLS1, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.FARMDWLS
(
SC_POLICY_NUM,
RFD_DWL_NDX,
RFD_DWL_CLASS,
RFD_DWL_DED,
RFD_DWL_PREM,
RFD_DWL_COV,
RFD_DWL_UNSCH,
RFD_DWL_ADDL,
RFD_DWL_HS,
RFD_DWL_CNSTYR,
RFD_INFL_DWL_IND,
RFD_DWL_CNTY,
RFD_DWL_FO85,
RFD_DWL_FO1,
RFD_DWL_FO45,
RFD_PDWL_CLASS,
RFD_PDWL_DED,
RFD_PDWL_COV,
RFD_PDWL_UNSCH,
RFD_DWL_COV_DT,
RFD_DWL_BCOV_DT
)
SELECT
exp_pass_through.SC_POLICY_NUM as SC_POLICY_NUM,
exp_pass_through.RFD_DWL_NDX as RFD_DWL_NDX,
exp_pass_through.RFD_DWL_CLASS as RFD_DWL_CLASS,
exp_pass_through.RFD_DWL_DED as RFD_DWL_DED,
exp_pass_through.RFD_DWL_PREM as RFD_DWL_PREM,
exp_pass_through.RFD_DWL_COV as RFD_DWL_COV,
exp_pass_through.RFD_DWL_UNSCH as RFD_DWL_UNSCH,
exp_pass_through.RFD_DWL_ADDL as RFD_DWL_ADDL,
exp_pass_through.RFD_DWL_HS as RFD_DWL_HS,
exp_pass_through.RFD_DWL_CNSTYR as RFD_DWL_CNSTYR,
exp_pass_through.RFD_INFL_DWL_IND as RFD_INFL_DWL_IND,
exp_pass_through.RFD_DWL_CNTY as RFD_DWL_CNTY,
exp_pass_through.RFD_DWL_FO85 as RFD_DWL_FO85,
exp_pass_through.RFD_DWL_FO1 as RFD_DWL_FO1,
exp_pass_through.RFD_DWL_FO45 as RFD_DWL_FO45,
exp_pass_through.RFD_PDWL_CLASS as RFD_PDWL_CLASS,
exp_pass_through.RFD_PDWL_DED as RFD_PDWL_DED,
exp_pass_through.RFD_PDWL_COV as RFD_PDWL_COV,
exp_pass_through.RFD_PDWL_UNSCH as RFD_PDWL_UNSCH,
exp_pass_through.RFD_DWL_COV_DT as RFD_DWL_COV_DT,
exp_pass_through.RFD_DWL_BCOV_DT as RFD_DWL_BCOV_DT
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';