-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_FARMHVYM("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
FEED_DT date;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id);  
FEED_DT:=(select current_date);  

-- Component FARMHVYM1, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.FARMHVYM;


-- PIPELINE START FOR 2

-- Component SQ_FARMHVYM2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMHVYM2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_HVYM_NDX,
$3 as RFD_HVYM_YR,
$4 as RFD_HVYM_DESC,
$5 as RFD_HVYM_DESC2,
$6 as RFD_HVYM_ID,
$7 as RFD_HVYM_ITM_COV,
$8 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
 SC_POLICY_NUM,
FARMHVYM.RFD_HVYM_NDX,
FARMHVYM.RFD_HVYM_YR,
FARMHVYM.RFD_HVYM_DESC,
FARMHVYM.RFD_HVYM_DESC2,
FARMHVYM.RFD_HVYM_ID,
FARMHVYM.RFD_HVYM_ITM_COV
FROM DB_T_STAG_MEMBXREF_PROD.FARMHVYM
) SRC
)
);


-- PIPELINE START FOR 1

-- Component SQ_FARMHVYM3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMHVYM3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_Count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
DB_T_STAG_MEMBXREF_PROD.FARMHVYM
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_FARMHVYM3.record_Count as record_count,
:feed_ind as feed_ind,
:feed_dt as feed_dt,
SQ_FARMHVYM3.source_record_id
FROM
SQ_FARMHVYM3
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_FARMHVYM2.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMHVYM2.RFD_HVYM_NDX as RFD_HVYM_NDX,
SQ_FARMHVYM2.RFD_HVYM_YR as RFD_HVYM_YR,
SQ_FARMHVYM2.RFD_HVYM_DESC as RFD_HVYM_DESC,
SQ_FARMHVYM2.RFD_HVYM_DESC2 as RFD_HVYM_DESC2,
SQ_FARMHVYM2.RFD_HVYM_ID as RFD_HVYM_ID,
SQ_FARMHVYM2.RFD_HVYM_ITM_COV as RFD_HVYM_ITM_COV,
SQ_FARMHVYM2.source_record_id
FROM
SQ_FARMHVYM2
);


-- Component FARMHVYM1, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.FARMHVYM
(
SC_POLICY_NUM,
RFD_HVYM_NDX,
RFD_HVYM_YR,
RFD_HVYM_DESC,
RFD_HVYM_DESC2,
RFD_HVYM_ID,
RFD_HVYM_ITM_COV
)
SELECT
exp_pass_through.SC_POLICY_NUM as SC_POLICY_NUM,
exp_pass_through.RFD_HVYM_NDX as RFD_HVYM_NDX,
exp_pass_through.RFD_HVYM_YR as RFD_HVYM_YR,
exp_pass_through.RFD_HVYM_DESC as RFD_HVYM_DESC,
exp_pass_through.RFD_HVYM_DESC2 as RFD_HVYM_DESC2,
exp_pass_through.RFD_HVYM_ID as RFD_HVYM_ID,
exp_pass_through.RFD_HVYM_ITM_COV as RFD_HVYM_ITM_COV
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';