-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_FARMMORT("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
FEED_DT date;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 
FEED_DT:=(select current_date); 

-- Component FARMMORT2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.FARMMORT;


-- PIPELINE START FOR 1

-- Component SQ_FARMMORT3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMMORT3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_Count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
DB_T_STAG_MEMBXREF_PROD.FARMMORT
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_FARMMORT3.record_Count as record_count,
:feed_ind as feed_ind,
:feed_dt as feed_dt,
SQ_FARMMORT3.source_record_id
FROM
SQ_FARMMORT3
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_FARMMORT2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMMORT2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_MORT_NDX,
$3 as RFD_MORT_NAME1,
$4 as RFD_MORT_NAME2,
$5 as RFD_MORT_ADDR1,
$6 as RFD_MORT_ADDR2,
$7 as RFD_MORT_CTY,
$8 as RFD_MORT_ST,
$9 as RFD_MORT_ZIP,
$10 as RFD_LOAN_NUM,
$11 as RFD_MORT_COLL1_TYP,
$12 as RFD_MORT_COLL1_OCC,
$13 as RFD_MORT_COLL2_TYP,
$14 as RFD_MORT_COLL2_OCC,
$15 as RFD_MORT_COLL3_TYP,
$16 as RFD_MORT_COLL3_OCC,
$17 as RFD_MORT_COLL4_TYP,
$18 as RFD_MORT_COLL4_OCC,
$19 as RFD_MORT_COLL5_TYP,
$20 as RFD_MORT_COLL5_OCC,
$21 as RFD_MORT_COLL6_TYP,
$22 as RFD_MORT_COLL6_OCC,
$23 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
FARMMORT3.SC_POLICY_NUM,
FARMMORT3.RFD_MORT_NDX,
FARMMORT3.RFD_MORT_NAME1,
FARMMORT3.RFD_MORT_NAME2,
FARMMORT3.RFD_MORT_ADDR1,
FARMMORT3.RFD_MORT_ADDR2,
FARMMORT3.RFD_MORT_CTY,
FARMMORT3.RFD_MORT_ST,
FARMMORT3.RFD_MORT_ZIP,
FARMMORT3.RFD_LOAN_NUM,
FARMMORT3.RFD_MORT_COLL1_TYP,
FARMMORT3.RFD_MORT_COLL1_OCC,
FARMMORT3.RFD_MORT_COLL2_TYP,
FARMMORT3.RFD_MORT_COLL2_OCC,
FARMMORT3.RFD_MORT_COLL3_TYP,
FARMMORT3.RFD_MORT_COLL3_OCC,
FARMMORT3.RFD_MORT_COLL4_TYP,
FARMMORT3.RFD_MORT_COLL4_OCC,
FARMMORT3.RFD_MORT_COLL5_TYP,
FARMMORT3.RFD_MORT_COLL5_OCC,
FARMMORT3.RFD_MORT_COLL6_TYP,
FARMMORT3.RFD_MORT_COLL6_OCC
FROM DB_T_STAG_MEMBXREF_PROD.FARMMORT FARMMORT3
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_FARMMORT2.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMMORT2.RFD_MORT_NDX as RFD_MORT_NDX,
SQ_FARMMORT2.RFD_MORT_NAME1 as RFD_MORT_NAME1,
SQ_FARMMORT2.RFD_MORT_NAME2 as RFD_MORT_NAME2,
SQ_FARMMORT2.RFD_MORT_ADDR1 as RFD_MORT_ADDR1,
SQ_FARMMORT2.RFD_MORT_ADDR2 as RFD_MORT_ADDR2,
SQ_FARMMORT2.RFD_MORT_CTY as RFD_MORT_CTY,
SQ_FARMMORT2.RFD_MORT_ST as RFD_MORT_ST,
SQ_FARMMORT2.RFD_MORT_ZIP as RFD_MORT_ZIP,
SQ_FARMMORT2.RFD_LOAN_NUM as RFD_LOAN_NUM,
SQ_FARMMORT2.RFD_MORT_COLL1_TYP as RFD_MORT_COLL1_TYP,
SQ_FARMMORT2.RFD_MORT_COLL1_OCC as RFD_MORT_COLL1_OCC,
SQ_FARMMORT2.RFD_MORT_COLL2_TYP as RFD_MORT_COLL2_TYP,
SQ_FARMMORT2.RFD_MORT_COLL2_OCC as RFD_MORT_COLL2_OCC,
SQ_FARMMORT2.RFD_MORT_COLL3_TYP as RFD_MORT_COLL3_TYP,
SQ_FARMMORT2.RFD_MORT_COLL3_OCC as RFD_MORT_COLL3_OCC,
SQ_FARMMORT2.RFD_MORT_COLL4_TYP as RFD_MORT_COLL4_TYP,
SQ_FARMMORT2.RFD_MORT_COLL4_OCC as RFD_MORT_COLL4_OCC,
SQ_FARMMORT2.RFD_MORT_COLL5_TYP as RFD_MORT_COLL5_TYP,
SQ_FARMMORT2.RFD_MORT_COLL5_OCC as RFD_MORT_COLL5_OCC,
SQ_FARMMORT2.RFD_MORT_COLL6_TYP as RFD_MORT_COLL6_TYP,
SQ_FARMMORT2.RFD_MORT_COLL6_OCC as RFD_MORT_COLL6_OCC,
SQ_FARMMORT2.source_record_id
FROM
SQ_FARMMORT2
);


-- Component FARMMORT2, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.FARMMORT
(
SC_POLICY_NUM,
RFD_MORT_NDX,
RFD_MORT_NAME1,
RFD_MORT_NAME2,
RFD_MORT_ADDR1,
RFD_MORT_ADDR2,
RFD_MORT_CTY,
RFD_MORT_ST,
RFD_MORT_ZIP,
RFD_LOAN_NUM,
RFD_MORT_COLL1_TYP,
RFD_MORT_COLL1_OCC,
RFD_MORT_COLL2_TYP,
RFD_MORT_COLL2_OCC,
RFD_MORT_COLL3_TYP,
RFD_MORT_COLL3_OCC,
RFD_MORT_COLL4_TYP,
RFD_MORT_COLL4_OCC,
RFD_MORT_COLL5_TYP,
RFD_MORT_COLL5_OCC,
RFD_MORT_COLL6_TYP,
RFD_MORT_COLL6_OCC
)
SELECT
exp_pass_through.SC_POLICY_NUM as SC_POLICY_NUM,
exp_pass_through.RFD_MORT_NDX as RFD_MORT_NDX,
exp_pass_through.RFD_MORT_NAME1 as RFD_MORT_NAME1,
exp_pass_through.RFD_MORT_NAME2 as RFD_MORT_NAME2,
exp_pass_through.RFD_MORT_ADDR1 as RFD_MORT_ADDR1,
exp_pass_through.RFD_MORT_ADDR2 as RFD_MORT_ADDR2,
exp_pass_through.RFD_MORT_CTY as RFD_MORT_CTY,
exp_pass_through.RFD_MORT_ST as RFD_MORT_ST,
exp_pass_through.RFD_MORT_ZIP as RFD_MORT_ZIP,
exp_pass_through.RFD_LOAN_NUM as RFD_LOAN_NUM,
exp_pass_through.RFD_MORT_COLL1_TYP as RFD_MORT_COLL1_TYP,
exp_pass_through.RFD_MORT_COLL1_OCC as RFD_MORT_COLL1_OCC,
exp_pass_through.RFD_MORT_COLL2_TYP as RFD_MORT_COLL2_TYP,
exp_pass_through.RFD_MORT_COLL2_OCC as RFD_MORT_COLL2_OCC,
exp_pass_through.RFD_MORT_COLL3_TYP as RFD_MORT_COLL3_TYP,
exp_pass_through.RFD_MORT_COLL3_OCC as RFD_MORT_COLL3_OCC,
exp_pass_through.RFD_MORT_COLL4_TYP as RFD_MORT_COLL4_TYP,
exp_pass_through.RFD_MORT_COLL4_OCC as RFD_MORT_COLL4_OCC,
exp_pass_through.RFD_MORT_COLL5_TYP as RFD_MORT_COLL5_TYP,
exp_pass_through.RFD_MORT_COLL5_OCC as RFD_MORT_COLL5_OCC,
exp_pass_through.RFD_MORT_COLL6_TYP as RFD_MORT_COLL6_TYP,
exp_pass_through.RFD_MORT_COLL6_OCC as RFD_MORT_COLL6_OCC
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';