-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_FARMPOLCLM("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
FEED_DT varchar;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 
FEED_DT:=(select current_date); 

-- Component FARMPOLCLM1, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.FARMPOLCLM;


-- PIPELINE START FOR 1

-- Component SQ_FARMPOLCLM3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMPOLCLM3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
DB_T_STAG_MEMBXREF_PROD.FARMPOLCLM
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_FARMPOLCLM3.record_count as record_count,
:feed_ind as feed_ind,
:feed_dt as feed_dt,
SQ_FARMPOLCLM3.source_record_id
FROM
SQ_FARMPOLCLM3
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_FARMPOLCLM2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMPOLCLM2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_CLM_NDX,
$3 as RFD_DOL,
$4 as RFD_ACC_DT,
$5 as RFD_DWELL_CLM,
$6 as RFD_UNSCH_CLM,
$7 as RFD_ADDL_CLM,
$8 as RFD_LIAB_CLM,
$9 as RFD_MED_CLM,
$10 as RFD_OUTBLDG_CLM,
$11 as RFD_PD_CLM,
$12 as RFD_NMED_CLM,
$13 as RFD_LVSTK_CLM,
$14 as RFD_MACH_CLM,
$15 as RFD_AMT_PYMNT,
$16 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
FARMPOLCLM3.SC_POLICY_NUM,
FARMPOLCLM3.RFD_CLM_NDX,
FARMPOLCLM3.RFD_DOL,
FARMPOLCLM3.RFD_ACC_DT,
FARMPOLCLM3.RFD_DWELL_CLM,
FARMPOLCLM3.RFD_UNSCH_CLM,
FARMPOLCLM3.RFD_ADDL_CLM,
FARMPOLCLM3.RFD_LIAB_CLM,
FARMPOLCLM3.RFD_MED_CLM,
FARMPOLCLM3.RFD_OUTBLDG_CLM,
FARMPOLCLM3.RFD_PD_CLM,
FARMPOLCLM3.RFD_NMED_CLM,
FARMPOLCLM3.RFD_LVSTK_CLM,
FARMPOLCLM3.RFD_MACH_CLM,
FARMPOLCLM3.RFD_AMT_PYMNT
FROM DB_T_STAG_MEMBXREF_PROD.FARMPOLCLM FARMPOLCLM3
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_FARMPOLCLM2.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMPOLCLM2.RFD_CLM_NDX as RFD_CLM_NDX,
SQ_FARMPOLCLM2.RFD_DOL as RFD_DOL,
SQ_FARMPOLCLM2.RFD_ACC_DT as RFD_ACC_DT,
SQ_FARMPOLCLM2.RFD_DWELL_CLM as RFD_DWELL_CLM,
SQ_FARMPOLCLM2.RFD_UNSCH_CLM as RFD_UNSCH_CLM,
SQ_FARMPOLCLM2.RFD_ADDL_CLM as RFD_ADDL_CLM,
SQ_FARMPOLCLM2.RFD_LIAB_CLM as RFD_LIAB_CLM,
SQ_FARMPOLCLM2.RFD_MED_CLM as RFD_MED_CLM,
SQ_FARMPOLCLM2.RFD_OUTBLDG_CLM as RFD_OUTBLDG_CLM,
SQ_FARMPOLCLM2.RFD_PD_CLM as RFD_PD_CLM,
SQ_FARMPOLCLM2.RFD_NMED_CLM as RFD_NMED_CLM,
SQ_FARMPOLCLM2.RFD_LVSTK_CLM as RFD_LVSTK_CLM,
SQ_FARMPOLCLM2.RFD_MACH_CLM as RFD_MACH_CLM,
SQ_FARMPOLCLM2.RFD_AMT_PYMNT as RFD_AMT_PYMNT,
SQ_FARMPOLCLM2.source_record_id
FROM
SQ_FARMPOLCLM2
);


-- Component FARMPOLCLM1, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.FARMPOLCLM
(
SC_POLICY_NUM,
RFD_CLM_NDX,
RFD_DOL,
RFD_ACC_DT,
RFD_DWELL_CLM,
RFD_UNSCH_CLM,
RFD_ADDL_CLM,
RFD_LIAB_CLM,
RFD_MED_CLM,
RFD_OUTBLDG_CLM,
RFD_PD_CLM,
RFD_NMED_CLM,
RFD_LVSTK_CLM,
RFD_MACH_CLM,
RFD_AMT_PYMNT
)
SELECT
exp_pass_through.SC_POLICY_NUM as SC_POLICY_NUM,
exp_pass_through.RFD_CLM_NDX as RFD_CLM_NDX,
exp_pass_through.RFD_DOL as RFD_DOL,
exp_pass_through.RFD_ACC_DT as RFD_ACC_DT,
exp_pass_through.RFD_DWELL_CLM as RFD_DWELL_CLM,
exp_pass_through.RFD_UNSCH_CLM as RFD_UNSCH_CLM,
exp_pass_through.RFD_ADDL_CLM as RFD_ADDL_CLM,
exp_pass_through.RFD_LIAB_CLM as RFD_LIAB_CLM,
exp_pass_through.RFD_MED_CLM as RFD_MED_CLM,
exp_pass_through.RFD_OUTBLDG_CLM as RFD_OUTBLDG_CLM,
exp_pass_through.RFD_PD_CLM as RFD_PD_CLM,
exp_pass_through.RFD_NMED_CLM as RFD_NMED_CLM,
exp_pass_through.RFD_LVSTK_CLM as RFD_LVSTK_CLM,
exp_pass_through.RFD_MACH_CLM as RFD_MACH_CLM,
exp_pass_through.RFD_AMT_PYMNT as RFD_AMT_PYMNT
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';