-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_FARMPOLOTHREND("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
FEED_DT date;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 
FEED_DT:=(select current_date); 

-- Component FARMPOLOTHREND1, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.FARMPOLOTHREND;


-- PIPELINE START FOR 1

-- Component SQ_FARMPOLOTHREND3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMPOLOTHREND3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
DB_T_STAG_MEMBXREF_PROD.FARMPOLOTHREND
) SRC
)
);


-- Component exp_rec_cnt1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt1 AS
(
SELECT
SQ_FARMPOLOTHREND3.record_count as record_count,
:feed_ind as feed_ind,
:feed_dt as feed_dt,
SQ_FARMPOLOTHREND3.source_record_id
FROM
SQ_FARMPOLOTHREND3
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt1.feed_ind as feed_ind,
exp_rec_cnt1.feed_dt as feed_dt,
exp_rec_cnt1.record_count as record_cnt
FROM
exp_rec_cnt1
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_FARMPOLOTHREND2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMPOLOTHREND2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_OTHR_END_NDX,
$3 as RFD_OTHR_END_NO,
$4 as RFD_OTHR_END_COV,
$5 as RFD_OTHR_END_PRM,
$6 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
FARMPOLOTHREND3.SC_POLICY_NUM,
FARMPOLOTHREND3.RFD_OTHR_END_NDX,
FARMPOLOTHREND3.RFD_OTHR_END_NO,
FARMPOLOTHREND3.RFD_OTHR_END_COV,
FARMPOLOTHREND3.RFD_OTHR_END_PRM
FROM DB_T_STAG_MEMBXREF_PROD.FARMPOLOTHREND FARMPOLOTHREND3
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_FARMPOLOTHREND2.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMPOLOTHREND2.RFD_OTHR_END_NDX as RFD_OTHR_END_NDX,
SQ_FARMPOLOTHREND2.RFD_OTHR_END_NO as RFD_OTHR_END_NO,
SQ_FARMPOLOTHREND2.RFD_OTHR_END_COV as RFD_OTHR_END_COV,
SQ_FARMPOLOTHREND2.RFD_OTHR_END_PRM as RFD_OTHR_END_PRM,
SQ_FARMPOLOTHREND2.source_record_id
FROM
SQ_FARMPOLOTHREND2
);


-- Component FARMPOLOTHREND1, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.FARMPOLOTHREND
(
SC_POLICY_NUM,
RFD_OTHR_END_NDX,
RFD_OTHR_END_NO,
RFD_OTHR_END_COV,
RFD_OTHR_END_PRM
)
SELECT
exp_pass_through.SC_POLICY_NUM as SC_POLICY_NUM,
exp_pass_through.RFD_OTHR_END_NDX as RFD_OTHR_END_NDX,
exp_pass_through.RFD_OTHR_END_NO as RFD_OTHR_END_NO,
exp_pass_through.RFD_OTHR_END_COV as RFD_OTHR_END_COV,
exp_pass_through.RFD_OTHR_END_PRM as RFD_OTHR_END_PRM
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';