-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_FARMPOLOUTBLD("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE FEED_IND varchar;
FEED_DT date;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 
FEED_DT:=(select current_date); 

-- Component FARMPOLOUTBLD2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.FARMPOLOUTBLD;


-- PIPELINE START FOR 1

-- Component SQ_FARMPOLOUTBLD3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMPOLOUTBLD3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
DB_T_STAG_MEMBXREF_PROD.FARMPOLOUTBLD
) SRC
)
);


-- Component exp_rec_cnt1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt1 AS
(
SELECT
SQ_FARMPOLOUTBLD3.record_count as record_count,
:feed_ind as feed_ind,
:feed_dt as feed_dt,
SQ_FARMPOLOUTBLD3.source_record_id
FROM
SQ_FARMPOLOUTBLD3
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt1.feed_ind as feed_ind,
exp_rec_cnt1.feed_dt as feed_dt,
exp_rec_cnt1.record_count as record_cnt
FROM
exp_rec_cnt1
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_FARMPOLOUTBLD, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMPOLOUTBLD AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_OUTBLD_NDX,
$3 as RFD_ECLASS,
$4 as RFD_ECOV,
$5 as RFD_PCLASS,
$6 as RFD_PECOV,
$7 as RFD_E_DT,
$8 as RFD_E_PREM,
$9 as RFD_E_DED,
$10 as RFD_PE_DED,
$11 as RFD_E_CNST_TR,
$12 as RFD_E_KBRACE,
$13 as RFD_PE_KBRACE,
$14 as RFD_E_CNST_TY,
$15 as RFD_E_DESC,
$16 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
FARMPOLOUTBLD.SC_POLICY_NUM,
FARMPOLOUTBLD.RFD_OUTBLD_NDX,
FARMPOLOUTBLD.RFD_ECLASS,
FARMPOLOUTBLD.RFD_ECOV,
FARMPOLOUTBLD.RFD_PCLASS,
FARMPOLOUTBLD.RFD_PECOV,
FARMPOLOUTBLD.RFD_E_DT,
FARMPOLOUTBLD.RFD_E_PREM,
FARMPOLOUTBLD.RFD_E_DED,
FARMPOLOUTBLD.RFD_PE_DED,
null RFD_E_CNST_TR,
FARMPOLOUTBLD.RFD_E_KBRACE,
FARMPOLOUTBLD.RFD_PE_KBRACE,
FARMPOLOUTBLD.RFD_E_CNST_TY,
FARMPOLOUTBLD.RFD_E_DESC
FROM DB_T_STAG_MEMBXREF_PROD.FARMPOLOUTBLD
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_FARMPOLOUTBLD.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMPOLOUTBLD.RFD_OUTBLD_NDX as RFD_OUTBLD_NDX,
SQ_FARMPOLOUTBLD.RFD_ECLASS as RFD_ECLASS,
SQ_FARMPOLOUTBLD.RFD_ECOV as RFD_ECOV,
SQ_FARMPOLOUTBLD.RFD_PCLASS as RFD_PCLASS,
SQ_FARMPOLOUTBLD.RFD_PECOV as RFD_PECOV,
SQ_FARMPOLOUTBLD.RFD_E_DT as RFD_E_DT,
SQ_FARMPOLOUTBLD.RFD_E_PREM as RFD_E_PREM,
SQ_FARMPOLOUTBLD.RFD_E_DED as RFD_E_DED,
SQ_FARMPOLOUTBLD.RFD_PE_DED as RFD_PE_DED,
SQ_FARMPOLOUTBLD.RFD_E_CNST_TR as RFD_E_CNST_YR,
SQ_FARMPOLOUTBLD.RFD_E_KBRACE as RFD_E_KBRACE,
SQ_FARMPOLOUTBLD.RFD_PE_KBRACE as RFD_PE_KBRACE,
SQ_FARMPOLOUTBLD.RFD_E_CNST_TY as RFD_E_CNST_TY,
SQ_FARMPOLOUTBLD.RFD_E_DESC as RFD_E_DESC,
SQ_FARMPOLOUTBLD.source_record_id
FROM
SQ_FARMPOLOUTBLD
);


-- Component FARMPOLOUTBLD2, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.FARMPOLOUTBLD
(
SC_POLICY_NUM,
RFD_OUTBLD_NDX,
RFD_ECLASS,
RFD_ECOV,
RFD_PCLASS,
RFD_PECOV,
RFD_E_DT,
RFD_E_PREM,
RFD_E_DED,
RFD_PE_DED,
RFD_E_CNST_YR,
RFD_E_KBRACE,
RFD_PE_KBRACE,
RFD_E_CNST_TY,
RFD_E_DESC
)
SELECT
exp_pass_through.SC_POLICY_NUM as SC_POLICY_NUM,
exp_pass_through.RFD_OUTBLD_NDX as RFD_OUTBLD_NDX,
exp_pass_through.RFD_ECLASS as RFD_ECLASS,
exp_pass_through.RFD_ECOV as RFD_ECOV,
exp_pass_through.RFD_PCLASS as RFD_PCLASS,
exp_pass_through.RFD_PECOV as RFD_PECOV,
exp_pass_through.RFD_E_DT as RFD_E_DT,
exp_pass_through.RFD_E_PREM as RFD_E_PREM,
exp_pass_through.RFD_E_DED as RFD_E_DED,
exp_pass_through.RFD_PE_DED as RFD_PE_DED,
exp_pass_through.RFD_E_CNST_YR as RFD_E_CNST_YR,
exp_pass_through.RFD_E_KBRACE as RFD_E_KBRACE,
exp_pass_through.RFD_PE_KBRACE as RFD_PE_KBRACE,
exp_pass_through.RFD_E_CNST_TY as RFD_E_CNST_TY,
exp_pass_through.RFD_E_DESC as RFD_E_DESC
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';