-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_ING_POL_LIST("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
FEED_DT date;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id);  
FEED_DT:=(select current_date);  

-- Component ING_POL_LIST1, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.ING_POL_LIST;


-- PIPELINE START FOR 1

-- Component SQ_ING_POL_LIST2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ING_POL_LIST2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CO_ID,
$2 as POL_ID,
$3 as INSURED_MEMBER_NUM,
$4 as PAYOR_MEMBER_NUM,
$5 as ALPHA_CODE_INSURED,
$6 as ALPHA_CODE_OWNER,
$7 as ALPHA_CODE_PAYOR,
$8 as ALPHA_CODE_JOINT,
$9 as INSURED_FIRST_NM,
$10 as INSURED_MID_NM,
$11 as INSURED_LAST_NM,
$12 as INSURED_SFX_NM,
$13 as PAYOR_FIRST_NM,
$14 as PAYOR_MID_NM,
$15 as PAYOR_LAST_NM,
$16 as PAYOR_SFX_NM,
$17 as INSURED_ADDR_LN_1,
$18 as INSURED_ADDR_LN_2,
$19 as INSURED_CITY_NM,
$20 as INSURED_STATE_CD,
$21 as INSURED_ZIP_CD,
$22 as INSURED_CLI_ID,
$23 as OWNER_CLI_ID,
$24 as PAYOR_CLI_ID,
$25 as SEC_INSURED_CLI_ID,
$26 as INSURED_SSN,
$27 as OWNER_SSN,
$28 as PAYOR_SSN,
$29 as SEC_INSURED_SSN,
$30 as AGT_ID,
$31 as POL_ISS_DT,
$32 as SERV_CENTER_NUM,
$33 as POLICY_TYPE,
$34 as POL_STATUS,
$35 as POL_CNFD_IND,
$36 as BASE_PLAN_ID,
$37 as BASE_FACE_AMT,
$38 as BILL_MODE,
$39 as CURR_CASH_VALUE,
$40 as OWNER_FIRST_NM,
$41 as OWNER_MID_NM,
$42 as OWNER_LAST_NM,
$43 as OWNER_SFX_NM,
$44 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
ING_POL_LIST.CO_ID,
ING_POL_LIST.POL_ID,
ING_POL_LIST.INSURED_MEMBER_NUM,
ING_POL_LIST.PAYOR_MEMBER_NUM,
ING_POL_LIST.ALPHA_CODE_INSURED,
ING_POL_LIST.ALPHA_CODE_OWNER,
ING_POL_LIST.ALPHA_CODE_PAYOR,
ING_POL_LIST.ALPHA_CODE_JOINT,
ING_POL_LIST.INSURED_FIRST_NM,
ING_POL_LIST.INSURED_MID_NM,
ING_POL_LIST.INSURED_LAST_NM,
ING_POL_LIST.INSURED_SFX_NM,
ING_POL_LIST.PAYOR_FIRST_NM,
ING_POL_LIST.PAYOR_MID_NM,
ING_POL_LIST.PAYOR_LAST_NM,
ING_POL_LIST.PAYOR_SFX_NM,
ING_POL_LIST.INSURED_ADDR_LN_1,
ING_POL_LIST.INSURED_ADDR_LN_2,
ING_POL_LIST.INSURED_CITY_NM,
ING_POL_LIST.INSURED_STATE_CD,
ING_POL_LIST.INSURED_ZIP_CD,
ING_POL_LIST.INSURED_CLI_ID,
ING_POL_LIST.OWNER_CLI_ID,
ING_POL_LIST.PAYOR_CLI_ID,
ING_POL_LIST.SEC_INSURED_CLI_ID,
ING_POL_LIST.INSURED_SSN,
ING_POL_LIST.OWNER_SSN,
ING_POL_LIST.PAYOR_SSN,
ING_POL_LIST.SEC_INSURED_SSN,
ING_POL_LIST.AGT_ID,
ING_POL_LIST.POL_ISS_DT,
ING_POL_LIST.SERV_CENTER_NUM,
ING_POL_LIST.POLICY_TYPE,
ING_POL_LIST.POL_STATUS,
ING_POL_LIST.POL_CNFD_IND,
ING_POL_LIST.BASE_PLAN_ID,
ING_POL_LIST.BASE_FACE_AMT,
ING_POL_LIST.BILL_MODE,
ING_POL_LIST.CURR_CASH_VALUE,
ING_POL_LIST.OWNER_FIRST_NM,
ING_POL_LIST.OWNER_MID_NM,
ING_POL_LIST.OWNER_LAST_NM,
ING_POL_LIST.OWNER_SFX_NM
FROM DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_ING_POL_LIST2.CO_ID as CO_ID,
SQ_ING_POL_LIST2.POL_ID as POL_ID,
SQ_ING_POL_LIST2.INSURED_MEMBER_NUM as INSURED_MEMBER_NUM,
SQ_ING_POL_LIST2.PAYOR_MEMBER_NUM as PAYOR_MEMBER_NUM,
SQ_ING_POL_LIST2.ALPHA_CODE_INSURED as ALPHA_CODE_INSURED,
SQ_ING_POL_LIST2.ALPHA_CODE_OWNER as ALPHA_CODE_OWNER,
SQ_ING_POL_LIST2.ALPHA_CODE_PAYOR as ALPHA_CODE_PAYOR,
SQ_ING_POL_LIST2.ALPHA_CODE_JOINT as ALPHA_CODE_JOINT,
SQ_ING_POL_LIST2.INSURED_FIRST_NM as INSURED_FIRST_NM,
SQ_ING_POL_LIST2.INSURED_MID_NM as INSURED_MID_NM,
SQ_ING_POL_LIST2.INSURED_LAST_NM as INSURED_LAST_NM,
SQ_ING_POL_LIST2.INSURED_SFX_NM as INSURED_SFX_NM,
SQ_ING_POL_LIST2.PAYOR_FIRST_NM as PAYOR_FIRST_NM,
SQ_ING_POL_LIST2.PAYOR_MID_NM as PAYOR_MID_NM,
SQ_ING_POL_LIST2.PAYOR_LAST_NM as PAYOR_LAST_NM,
SQ_ING_POL_LIST2.PAYOR_SFX_NM as PAYOR_SFX_NM,
SQ_ING_POL_LIST2.INSURED_ADDR_LN_1 as INSURED_ADDR_LN_1,
SQ_ING_POL_LIST2.INSURED_ADDR_LN_2 as INSURED_ADDR_LN_2,
SQ_ING_POL_LIST2.INSURED_CITY_NM as INSURED_CITY_NM,
SQ_ING_POL_LIST2.INSURED_STATE_CD as INSURED_STATE_CD,
SQ_ING_POL_LIST2.INSURED_ZIP_CD as INSURED_ZIP_CD,
SQ_ING_POL_LIST2.INSURED_CLI_ID as INSURED_CLI_ID,
SQ_ING_POL_LIST2.OWNER_CLI_ID as OWNER_CLI_ID,
SQ_ING_POL_LIST2.PAYOR_CLI_ID as PAYOR_CLI_ID,
SQ_ING_POL_LIST2.SEC_INSURED_CLI_ID as SEC_INSURED_CLI_ID,
SQ_ING_POL_LIST2.INSURED_SSN as INSURED_SSN,
SQ_ING_POL_LIST2.OWNER_SSN as OWNER_SSN,
SQ_ING_POL_LIST2.PAYOR_SSN as PAYOR_SSN,
SQ_ING_POL_LIST2.SEC_INSURED_SSN as SEC_INSURED_SSN,
SQ_ING_POL_LIST2.AGT_ID as AGT_ID,
SQ_ING_POL_LIST2.POL_ISS_DT as POL_ISS_DT,
SQ_ING_POL_LIST2.SERV_CENTER_NUM as SERV_CENTER_NUM,
SQ_ING_POL_LIST2.POLICY_TYPE as POLICY_TYPE,
SQ_ING_POL_LIST2.POL_STATUS as POL_STATUS,
SQ_ING_POL_LIST2.POL_CNFD_IND as POL_CNFD_IND,
SQ_ING_POL_LIST2.BASE_PLAN_ID as BASE_PLAN_ID,
SQ_ING_POL_LIST2.BASE_FACE_AMT as BASE_FACE_AMT,
SQ_ING_POL_LIST2.BILL_MODE as BILL_MODE,
SQ_ING_POL_LIST2.CURR_CASH_VALUE as CURR_CASH_VALUE,
SQ_ING_POL_LIST2.OWNER_FIRST_NM as OWNER_FIRST_NM,
SQ_ING_POL_LIST2.OWNER_MID_NM as OWNER_MID_NM,
SQ_ING_POL_LIST2.OWNER_LAST_NM as OWNER_LAST_NM,
SQ_ING_POL_LIST2.OWNER_SFX_NM as OWNER_SFX_NM,
SQ_ING_POL_LIST2.source_record_id
FROM
SQ_ING_POL_LIST2
);


-- Component ING_POL_LIST1, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.ING_POL_LIST
(
CO_ID,
POL_ID,
INSURED_MEMBER_NUM,
PAYOR_MEMBER_NUM,
ALPHA_CODE_INSURED,
ALPHA_CODE_OWNER,
ALPHA_CODE_PAYOR,
ALPHA_CODE_JOINT,
INSURED_FIRST_NM,
INSURED_MID_NM,
INSURED_LAST_NM,
INSURED_SFX_NM,
PAYOR_FIRST_NM,
PAYOR_MID_NM,
PAYOR_LAST_NM,
PAYOR_SFX_NM,
INSURED_ADDR_LN_1,
INSURED_ADDR_LN_2,
INSURED_CITY_NM,
INSURED_STATE_CD,
INSURED_ZIP_CD,
INSURED_CLI_ID,
OWNER_CLI_ID,
PAYOR_CLI_ID,
SEC_INSURED_CLI_ID,
INSURED_SSN,
OWNER_SSN,
PAYOR_SSN,
SEC_INSURED_SSN,
AGT_ID,
POL_ISS_DT,
SERV_CENTER_NUM,
POLICY_TYPE,
POL_STATUS,
POL_CNFD_IND,
BASE_PLAN_ID,
BASE_FACE_AMT,
BILL_MODE,
CURR_CASH_VALUE,
OWNER_FIRST_NM,
OWNER_MID_NM,
OWNER_LAST_NM,
OWNER_SFX_NM
)
SELECT
exp_pass_through.CO_ID as CO_ID,
exp_pass_through.POL_ID as POL_ID,
exp_pass_through.INSURED_MEMBER_NUM as INSURED_MEMBER_NUM,
exp_pass_through.PAYOR_MEMBER_NUM as PAYOR_MEMBER_NUM,
exp_pass_through.ALPHA_CODE_INSURED as ALPHA_CODE_INSURED,
exp_pass_through.ALPHA_CODE_OWNER as ALPHA_CODE_OWNER,
exp_pass_through.ALPHA_CODE_PAYOR as ALPHA_CODE_PAYOR,
exp_pass_through.ALPHA_CODE_JOINT as ALPHA_CODE_JOINT,
exp_pass_through.INSURED_FIRST_NM as INSURED_FIRST_NM,
exp_pass_through.INSURED_MID_NM as INSURED_MID_NM,
exp_pass_through.INSURED_LAST_NM as INSURED_LAST_NM,
exp_pass_through.INSURED_SFX_NM as INSURED_SFX_NM,
exp_pass_through.PAYOR_FIRST_NM as PAYOR_FIRST_NM,
exp_pass_through.PAYOR_MID_NM as PAYOR_MID_NM,
exp_pass_through.PAYOR_LAST_NM as PAYOR_LAST_NM,
exp_pass_through.PAYOR_SFX_NM as PAYOR_SFX_NM,
exp_pass_through.INSURED_ADDR_LN_1 as INSURED_ADDR_LN_1,
exp_pass_through.INSURED_ADDR_LN_2 as INSURED_ADDR_LN_2,
exp_pass_through.INSURED_CITY_NM as INSURED_CITY_NM,
exp_pass_through.INSURED_STATE_CD as INSURED_STATE_CD,
exp_pass_through.INSURED_ZIP_CD as INSURED_ZIP_CD,
exp_pass_through.INSURED_CLI_ID as INSURED_CLI_ID,
exp_pass_through.OWNER_CLI_ID as OWNER_CLI_ID,
exp_pass_through.PAYOR_CLI_ID as PAYOR_CLI_ID,
exp_pass_through.SEC_INSURED_CLI_ID as SEC_INSURED_CLI_ID,
exp_pass_through.INSURED_SSN as INSURED_SSN,
exp_pass_through.OWNER_SSN as OWNER_SSN,
exp_pass_through.PAYOR_SSN as PAYOR_SSN,
exp_pass_through.SEC_INSURED_SSN as SEC_INSURED_SSN,
exp_pass_through.AGT_ID as AGT_ID,
exp_pass_through.POL_ISS_DT as POL_ISS_DT,
exp_pass_through.SERV_CENTER_NUM as SERV_CENTER_NUM,
exp_pass_through.POLICY_TYPE as POLICY_TYPE,
exp_pass_through.POL_STATUS as POL_STATUS,
exp_pass_through.POL_CNFD_IND as POL_CNFD_IND,
exp_pass_through.BASE_PLAN_ID as BASE_PLAN_ID,
exp_pass_through.BASE_FACE_AMT as BASE_FACE_AMT,
exp_pass_through.BILL_MODE as BILL_MODE,
exp_pass_through.CURR_CASH_VALUE as CURR_CASH_VALUE,
exp_pass_through.OWNER_FIRST_NM as OWNER_FIRST_NM,
exp_pass_through.OWNER_MID_NM as OWNER_MID_NM,
exp_pass_through.OWNER_LAST_NM as OWNER_LAST_NM,
exp_pass_through.OWNER_SFX_NM as OWNER_SFX_NM
FROM
exp_pass_through;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_ING_POL_LIST3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ING_POL_LIST3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
TO_NUMBER(SQ_ING_POL_LIST3.record_count) as o_record_count,
:feed_ind as feed_ind,
:feed_dt as feed_dt,
SQ_ING_POL_LIST3.source_record_id
FROM
SQ_ING_POL_LIST3
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.o_record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 2

END; ';