-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_INJURED_PLR("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id);  

-- Component CTS_INJURED_PLR2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_ML_PROD.CTS_INJURED_PLR;


-- PIPELINE START FOR 1

-- Component SQ_CTS_INJURED_PLR1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CTS_INJURED_PLR1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as RECORD_COUNT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
 DB_T_ML_PROD.CTS_INJURED_PLR
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_CTS_INJURED_PLR1.RECORD_COUNT as record_count,
:feed_ind as feed_ind,
to_char ( CURRENT_TIMESTAMP , ''YYYY-MM-DD'' ) as feed_dt,
SQ_CTS_INJURED_PLR1.source_record_id
FROM
SQ_CTS_INJURED_PLR1
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_CTS_INJURED_PLR, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CTS_INJURED_PLR AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CLAIMS_TRACK_NUM,
$2 as INJURED_SEQ,
$3 as NAME,
$4 as ADDRESS,
$5 as CITY,
$6 as STATE,
$7 as ZIP,
$8 as GENDER,
$9 as DID_INJURED_DIE,
$10 as DOB,
$11 as INJURED_IN,
$12 as INJURED_WAS,
$13 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
CTS_INJURED_PLR.CLAIMS_TRACK_NUM,
CTS_INJURED_PLR.INJURED_SEQ,
CTS_INJURED_PLR.NAME,
CTS_INJURED_PLR.ADDRESS,
CTS_INJURED_PLR.CITY,
CTS_INJURED_PLR.STATE,
CTS_INJURED_PLR.ZIP,
CTS_INJURED_PLR.GENDER,
CTS_INJURED_PLR.DID_INJURED_DIE,
CTS_INJURED_PLR.DOB,
CTS_INJURED_PLR.INJURED_IN,
CTS_INJURED_PLR.INJURED_WAS
FROM DB_T_ML_PROD.CTS_INJURED_PLR
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_CTS_INJURED_PLR.CLAIMS_TRACK_NUM as CLAIMS_TRACK_NUM,
SQ_CTS_INJURED_PLR.INJURED_SEQ as INJURED_SEQ,
SQ_CTS_INJURED_PLR.NAME as NAME,
SQ_CTS_INJURED_PLR.ADDRESS as ADDRESS,
SQ_CTS_INJURED_PLR.CITY as CITY,
SQ_CTS_INJURED_PLR.STATE as STATE,
SQ_CTS_INJURED_PLR.ZIP as ZIP,
SQ_CTS_INJURED_PLR.GENDER as GENDER,
SQ_CTS_INJURED_PLR.DID_INJURED_DIE as DID_INJURED_DIE,
SQ_CTS_INJURED_PLR.DOB as DOB,
SQ_CTS_INJURED_PLR.INJURED_IN as INJURED_IN,
SQ_CTS_INJURED_PLR.INJURED_WAS as INJURED_WAS,
SQ_CTS_INJURED_PLR.source_record_id
FROM
SQ_CTS_INJURED_PLR
);


-- Component CTS_INJURED_PLR2, Type TARGET 
INSERT INTO DB_T_ML_PROD.CTS_INJURED_PLR
(
CLAIMS_TRACK_NUM,
INJURED_SEQ,
NAME,
ADDRESS,
CITY,
STATE,
ZIP,
GENDER,
DID_INJURED_DIE,
DOB,
INJURED_IN,
INJURED_WAS
)
SELECT
exp_pass_through.CLAIMS_TRACK_NUM as CLAIMS_TRACK_NUM,
exp_pass_through.INJURED_SEQ as INJURED_SEQ,
exp_pass_through.NAME as NAME,
exp_pass_through.ADDRESS as ADDRESS,
exp_pass_through.CITY as CITY,
exp_pass_through.STATE as STATE,
exp_pass_through.ZIP as ZIP,
exp_pass_through.GENDER as GENDER,
exp_pass_through.DID_INJURED_DIE as DID_INJURED_DIE,
exp_pass_through.DOB as DOB,
exp_pass_through.INJURED_IN as INJURED_IN,
exp_pass_through.INJURED_WAS as INJURED_WAS
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';