-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_LIFEPOLS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
FEED_DT date;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 
FEED_DT:=(select current_date); 

-- Component LIFEPOLS2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.LIFEPOLS;


-- PIPELINE START FOR 2

-- Component SQ_LIFEPOLS3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_LIFEPOLS3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_DWNLD_PRIORITY,
$2 as SC_SERVICE_CENTER,
$3 as SC_POLICY_NUM,
$4 as SC_FLT_ITEM,
$5 as SC_FILE_TYPE,
$6 as SC_REC_TRANS_CODE,
$7 as SC_TRANS_DATE,
$8 as SC_TRANS_TYPE,
$9 as LF_ALPHA_CODE,
$10 as LF_STATUS,
$11 as LF_MODE,
$12 as LF_INSURED_SSAN,
$13 as LF_MEMBERSHIP,
$14 as LF_NFO_OPTION,
$15 as LF_INSURED_NAME,
$16 as LF_ADDRESS_1,
$17 as LF_ADDRESS_2,
$18 as LF_ADDRESS_3,
$19 as LF_PAYOR_NAME,
$20 as LF_OWNER_NAME,
$21 as LF_MODAL_PREM,
$22 as LF_ISSUE_DATE,
$23 as LF_APPL_DATE,
$24 as LF_BIRTH_DATE,
$25 as LF_PAC_DRAW_DAY,
$26 as LF_DUE_USE_CD,
$27 as LF_REQUIRE_SW,
$28 as LF_PAC_BANK_CD,
$29 as LF_PAC_ACCT_NO,
$30 as LF_FORM,
$31 as LF_VOLUME,
$32 as LF_APP_PREM,
$33 as LF_OVER_SHORT,
$34 as LF_UNDERWRITER,
$35 as LF_PLAN_NAME,
$36 as LF_POLICY_FEE,
$37 as LF_FUND_BALANCE,
$38 as LF_SURR_VALUE,
$39 as LF_DEP_FUND,
$40 as LF_PD_TO_DATE,
$41 as LF_LOAN_AMOUNT,
$42 as LF_DIV_ON_DEP,
$43 as LF_PAIDUP_ADD,
$44 as LF_CASH_VAL_PUA,
$45 as LF_ANNUAL_PREM,
$46 as LF_AGENT_NO,
$47 as LF_LOAN_VALUE,
$48 as LF_PHY_ISS,
$49 as LF_CANC_REASON_CDE,
$50 as LF_ISS_AGE,
$51 as LF_2ND_INS_NAME,
$52 as LF_OWNER_ADDRESS_1,
$53 as LF_OWNER_ADDRESS_2,
$54 as LF_OWNER_ADDRESS_3,
$55 as LF_PAYOR_ADDRESS_1,
$56 as LF_PAYOR_ADDRESS_2,
$57 as LF_PAYOR_ADDRESS_3,
$58 as LF_OWNER_SSAN,
$59 as LF_LAST_ANN_DATE,
$60 as LF_FUND_BAL_LST_AN,
$61 as LF_LOAN_CALC_DATE,
$62 as LF_SURR_CHG_LST_AN,
$63 as LF_POL_ANNUAL_PREM,
$64 as LF_2ND_INS_DOB,
$65 as LF_2ND_INS_ISS_AGE,
$66 as LF_INS_ISS_AGE,
$67 as LF_INS_TOBACCO_USE,
$68 as LF_INS_SEX_CODE,
$69 as LF_2ND_INS_SEX_CDE,
$70 as LF_DEATH_BENE_OPT,
$71 as LF_2ND_INS_SSAN,
$72 as LF_RESTRICT_CODE,
$73 as LF_LOAN_INT_RATE,
$74 as LF_LOAN_INT_ACCRU,
$75 as LF_NEXT_AN_CAS_VAL,
$76 as LF_DISPLAY_SW,
$77 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
LIFEPOLS.SC_DWNLD_PRIORITY,
LIFEPOLS.SC_SERVICE_CENTER,
LIFEPOLS.SC_POLICY_NUM,
LIFEPOLS.SC_FLT_ITEM,
LIFEPOLS.SC_FILE_TYPE,
LIFEPOLS.SC_REC_TRANS_CODE,
LIFEPOLS.SC_TRANS_DATE,
LIFEPOLS.SC_TRANS_TYPE,
LIFEPOLS.LF_ALPHA_CODE,
LIFEPOLS.LF_STATUS,
LIFEPOLS.LF_MODE,
LIFEPOLS.LF_INSURED_SSAN,
LIFEPOLS.LF_MEMBERSHIP,
LIFEPOLS.LF_NFO_OPTION,
LIFEPOLS.LF_INSURED_NAME,
LIFEPOLS.LF_ADDRESS_1,
LIFEPOLS.LF_ADDRESS_2,
LIFEPOLS.LF_ADDRESS_3,
LIFEPOLS.LF_PAYOR_NAME,
LIFEPOLS.LF_OWNER_NAME,
LIFEPOLS.LF_MODAL_PREM,
LIFEPOLS.LF_ISSUE_DATE,
LIFEPOLS.LF_APPL_DATE,
LIFEPOLS.LF_BIRTH_DATE,
LIFEPOLS.LF_PAC_DRAW_DAY,
LIFEPOLS.LF_DUE_USE_CD,
LIFEPOLS.LF_REQUIRE_SW,
LIFEPOLS.LF_PAC_BANK_CD,
LIFEPOLS.LF_PAC_ACCT_NO,
LIFEPOLS.LF_FORM,
LIFEPOLS.LF_VOLUME,
LIFEPOLS.LF_APP_PREM,
LIFEPOLS.LF_OVER_SHORT,
LIFEPOLS.LF_UNDERWRITER,
LIFEPOLS.LF_PLAN_NAME,
LIFEPOLS.LF_POLICY_FEE,
LIFEPOLS.LF_FUND_BALANCE,
LIFEPOLS.LF_SURR_VALUE,
LIFEPOLS.LF_DEP_FUND,
LIFEPOLS.LF_PD_TO_DATE,
LIFEPOLS.LF_LOAN_AMOUNT,
LIFEPOLS.LF_DIV_ON_DEP,
LIFEPOLS.LF_PAIDUP_ADD,
LIFEPOLS.LF_CASH_VAL_PUA,
LIFEPOLS.LF_ANNUAL_PREM,
LIFEPOLS.LF_AGENT_NO,
LIFEPOLS.LF_LOAN_VALUE,
LIFEPOLS.LF_PHY_ISS,
LIFEPOLS.LF_CANC_REASON_CDE,
LIFEPOLS.LF_ISS_AGE,
LIFEPOLS.LF_2ND_INS_NAME,
LIFEPOLS.LF_OWNER_ADDRESS_1,
LIFEPOLS.LF_OWNER_ADDRESS_2,
LIFEPOLS.LF_OWNER_ADDRESS_3,
LIFEPOLS.LF_PAYOR_ADDRESS_1,
LIFEPOLS.LF_PAYOR_ADDRESS_2,
LIFEPOLS.LF_PAYOR_ADDRESS_3,
LIFEPOLS.LF_OWNER_SSAN,
LIFEPOLS.LF_LAST_ANN_DATE,
LIFEPOLS.LF_FUND_BAL_LST_AN,
LIFEPOLS.LF_LOAN_CALC_DATE,
LIFEPOLS.LF_SURR_CHG_LST_AN,
LIFEPOLS.LF_POL_ANNUAL_PREM,
LIFEPOLS.LF_2ND_INS_DOB,
LIFEPOLS.LF_2ND_INS_ISS_AGE,
LIFEPOLS.LF_INS_ISS_AGE,
LIFEPOLS.LF_INS_TOBACCO_USE,
LIFEPOLS.LF_INS_SEX_CODE,
LIFEPOLS.LF_2ND_INS_SEX_CDE,
LIFEPOLS.LF_DEATH_BENE_OPT,
LIFEPOLS.LF_2ND_INS_SSAN,
LIFEPOLS.LF_RESTRICT_CODE,
LIFEPOLS.LF_LOAN_INT_RATE,
LIFEPOLS.LF_LOAN_INT_ACCRU,
LIFEPOLS.LF_NEXT_AN_CAS_VAL,
LIFEPOLS.LF_DISPLAY_SW
FROM DB_T_CORE_MEMBXREF_PROD.LIFEPOLS
) SRC
)
);


-- PIPELINE START FOR 1

-- Component SQ_LIFEPOLS2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_LIFEPOLS2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_Count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
DB_T_CORE_MEMBXREF_PROD.LIFEPOLS
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_LIFEPOLS3.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
SQ_LIFEPOLS3.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
SQ_LIFEPOLS3.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_LIFEPOLS3.SC_FLT_ITEM as SC_FLT_ITEM,
SQ_LIFEPOLS3.SC_FILE_TYPE as SC_FILE_TYPE,
SQ_LIFEPOLS3.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
cast ( SQ_LIFEPOLS3.SC_TRANS_DATE as date ) as o_SC_TRANS_DATE,
SQ_LIFEPOLS3.SC_TRANS_TYPE as SC_TRANS_TYPE,
SQ_LIFEPOLS3.LF_ALPHA_CODE as LF_ALPHA_CODE,
SQ_LIFEPOLS3.LF_STATUS as LF_STATUS,
SQ_LIFEPOLS3.LF_MODE as LF_MODE,
SQ_LIFEPOLS3.LF_INSURED_SSAN as LF_INSURED_SSAN,
SQ_LIFEPOLS3.LF_MEMBERSHIP as LF_MEMBERSHIP,
SQ_LIFEPOLS3.LF_NFO_OPTION as LF_NFO_OPTION,
SQ_LIFEPOLS3.LF_INSURED_NAME as LF_INSURED_NAME,
SQ_LIFEPOLS3.LF_ADDRESS_1 as LF_ADDRESS_1,
SQ_LIFEPOLS3.LF_ADDRESS_2 as LF_ADDRESS_2,
SQ_LIFEPOLS3.LF_ADDRESS_3 as LF_ADDRESS_3,
SQ_LIFEPOLS3.LF_PAYOR_NAME as LF_PAYOR_NAME,
SQ_LIFEPOLS3.LF_OWNER_NAME as LF_OWNER_NAME,
SQ_LIFEPOLS3.LF_MODAL_PREM as LF_MODAL_PREM,
SQ_LIFEPOLS3.LF_ISSUE_DATE as LF_ISSUE_DATE,
SQ_LIFEPOLS3.LF_APPL_DATE as LF_APPL_DATE,
SQ_LIFEPOLS3.LF_BIRTH_DATE as LF_BIRTH_DATE,
SQ_LIFEPOLS3.LF_PAC_DRAW_DAY as LF_PAC_DRAW_DAY,
SQ_LIFEPOLS3.LF_DUE_USE_CD as LF_DUE_USE_CD,
SQ_LIFEPOLS3.LF_REQUIRE_SW as LF_REQUIRE_SW,
SQ_LIFEPOLS3.LF_PAC_BANK_CD as LF_PAC_BANK_CD,
SQ_LIFEPOLS3.LF_PAC_ACCT_NO as LF_PAC_ACCT_NO,
SQ_LIFEPOLS3.LF_FORM as LF_FORM,
SQ_LIFEPOLS3.LF_VOLUME as LF_VOLUME,
SQ_LIFEPOLS3.LF_APP_PREM as LF_APP_PREM,
SQ_LIFEPOLS3.LF_OVER_SHORT as LF_OVER_SHORT,
SQ_LIFEPOLS3.LF_UNDERWRITER as LF_UNDERWRITER,
SQ_LIFEPOLS3.LF_PLAN_NAME as LF_PLAN_NAME,
SQ_LIFEPOLS3.LF_POLICY_FEE as LF_POLICY_FEE,
SQ_LIFEPOLS3.LF_FUND_BALANCE as LF_FUND_BALANCE,
SQ_LIFEPOLS3.LF_SURR_VALUE as LF_SURR_VALUE,
SQ_LIFEPOLS3.LF_DEP_FUND as LF_DEP_FUND,
SQ_LIFEPOLS3.LF_PD_TO_DATE as LF_PD_TO_DATE,
SQ_LIFEPOLS3.LF_LOAN_AMOUNT as LF_LOAN_AMOUNT,
SQ_LIFEPOLS3.LF_DIV_ON_DEP as LF_DIV_ON_DEP,
SQ_LIFEPOLS3.LF_PAIDUP_ADD as LF_PAIDUP_ADD,
SQ_LIFEPOLS3.LF_CASH_VAL_PUA as LF_CASH_VAL_PUA,
SQ_LIFEPOLS3.LF_ANNUAL_PREM as LF_ANNUAL_PREM,
SQ_LIFEPOLS3.LF_AGENT_NO as LF_AGENT_NO,
SQ_LIFEPOLS3.LF_LOAN_VALUE as LF_LOAN_VALUE,
SQ_LIFEPOLS3.LF_PHY_ISS as LF_PHY_ISS,
SQ_LIFEPOLS3.LF_CANC_REASON_CDE as LF_CANC_REASON_CDE,
SQ_LIFEPOLS3.LF_ISS_AGE as LF_ISS_AGE,
SQ_LIFEPOLS3.LF_2ND_INS_NAME as LF_2ND_INS_NAME,
SQ_LIFEPOLS3.LF_OWNER_ADDRESS_1 as LF_OWNER_ADDRESS_1,
SQ_LIFEPOLS3.LF_OWNER_ADDRESS_2 as LF_OWNER_ADDRESS_2,
SQ_LIFEPOLS3.LF_OWNER_ADDRESS_3 as LF_OWNER_ADDRESS_3,
SQ_LIFEPOLS3.LF_PAYOR_ADDRESS_1 as LF_PAYOR_ADDRESS_1,
SQ_LIFEPOLS3.LF_PAYOR_ADDRESS_2 as LF_PAYOR_ADDRESS_2,
SQ_LIFEPOLS3.LF_PAYOR_ADDRESS_3 as LF_PAYOR_ADDRESS_3,
SQ_LIFEPOLS3.LF_OWNER_SSAN as LF_OWNER_SSAN,
SQ_LIFEPOLS3.LF_LAST_ANN_DATE as LF_LAST_ANN_DATE,
SQ_LIFEPOLS3.LF_FUND_BAL_LST_AN as LF_FUND_BAL_LST_AN,
SQ_LIFEPOLS3.LF_LOAN_CALC_DATE as LF_LOAN_CALC_DATE,
SQ_LIFEPOLS3.LF_SURR_CHG_LST_AN as LF_SURR_CHG_LST_AN,
SQ_LIFEPOLS3.LF_POL_ANNUAL_PREM as LF_POL_ANNUAL_PREM,
SQ_LIFEPOLS3.LF_2ND_INS_DOB as LF_2ND_INS_DOB,
SQ_LIFEPOLS3.LF_2ND_INS_ISS_AGE as LF_2ND_INS_ISS_AGE,
SQ_LIFEPOLS3.LF_INS_ISS_AGE as LF_INS_ISS_AGE,
SQ_LIFEPOLS3.LF_INS_TOBACCO_USE as LF_INS_TOBACCO_USE,
SQ_LIFEPOLS3.LF_INS_SEX_CODE as LF_INS_SEX_CODE,
SQ_LIFEPOLS3.LF_2ND_INS_SEX_CDE as LF_2ND_INS_SEX_CDE,
SQ_LIFEPOLS3.LF_DEATH_BENE_OPT as LF_DEATH_BENE_OPT,
SQ_LIFEPOLS3.LF_2ND_INS_SSAN as LF_2ND_INS_SSAN,
SQ_LIFEPOLS3.LF_RESTRICT_CODE as LF_RESTRICT_CODE,
SQ_LIFEPOLS3.LF_LOAN_INT_RATE as LF_LOAN_INT_RATE,
SQ_LIFEPOLS3.LF_LOAN_INT_ACCRU as LF_LOAN_INT_ACCRU,
SQ_LIFEPOLS3.LF_NEXT_AN_CAS_VAL as LF_NEXT_AN_CAS_VAL,
SQ_LIFEPOLS3.LF_DISPLAY_SW as LF_DISPLAY_SW,
SQ_LIFEPOLS3.source_record_id
FROM
SQ_LIFEPOLS3
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_LIFEPOLS2.record_Count as record_count,
:feed_ind as feed_ind,
:feed_dt as feed_dt,
SQ_LIFEPOLS2.source_record_id
FROM
SQ_LIFEPOLS2
);


-- Component LIFEPOLS2, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.LIFEPOLS
(
SC_DWNLD_PRIORITY,
SC_SERVICE_CENTER,
SC_POLICY_NUM,
SC_FLT_ITEM,
SC_FILE_TYPE,
SC_REC_TRANS_CODE,
SC_TRANS_DATE,
SC_TRANS_TYPE,
LF_ALPHA_CODE,
LF_STATUS,
LF_MODE,
LF_INSURED_SSAN,
LF_MEMBERSHIP,
LF_NFO_OPTION,
LF_INSURED_NAME,
LF_ADDRESS_1,
LF_ADDRESS_2,
LF_ADDRESS_3,
LF_PAYOR_NAME,
LF_OWNER_NAME,
LF_MODAL_PREM,
LF_ISSUE_DATE,
LF_APPL_DATE,
LF_BIRTH_DATE,
LF_PAC_DRAW_DAY,
LF_DUE_USE_CD,
LF_REQUIRE_SW,
LF_PAC_BANK_CD,
LF_PAC_ACCT_NO,
LF_FORM,
LF_VOLUME,
LF_APP_PREM,
LF_OVER_SHORT,
LF_UNDERWRITER,
LF_PLAN_NAME,
LF_POLICY_FEE,
LF_FUND_BALANCE,
LF_SURR_VALUE,
LF_DEP_FUND,
LF_PD_TO_DATE,
LF_LOAN_AMOUNT,
LF_DIV_ON_DEP,
LF_PAIDUP_ADD,
LF_CASH_VAL_PUA,
LF_ANNUAL_PREM,
LF_AGENT_NO,
LF_LOAN_VALUE,
LF_PHY_ISS,
LF_CANC_REASON_CDE,
LF_ISS_AGE,
LF_2ND_INS_NAME,
LF_OWNER_ADDRESS_1,
LF_OWNER_ADDRESS_2,
LF_OWNER_ADDRESS_3,
LF_PAYOR_ADDRESS_1,
LF_PAYOR_ADDRESS_2,
LF_PAYOR_ADDRESS_3,
LF_OWNER_SSAN,
LF_LAST_ANN_DATE,
LF_FUND_BAL_LST_AN,
LF_LOAN_CALC_DATE,
LF_SURR_CHG_LST_AN,
LF_POL_ANNUAL_PREM,
LF_2ND_INS_DOB,
LF_2ND_INS_ISS_AGE,
LF_INS_ISS_AGE,
LF_INS_TOBACCO_USE,
LF_INS_SEX_CODE,
LF_2ND_INS_SEX_CDE,
LF_DEATH_BENE_OPT,
LF_2ND_INS_SSAN,
LF_RESTRICT_CODE,
LF_LOAN_INT_RATE,
LF_LOAN_INT_ACCRU,
LF_NEXT_AN_CAS_VAL,
LF_DISPLAY_SW
)
SELECT
exp_pass_through.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_pass_through.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_pass_through.SC_POLICY_NUM as SC_POLICY_NUM,
exp_pass_through.SC_FLT_ITEM as SC_FLT_ITEM,
exp_pass_through.SC_FILE_TYPE as SC_FILE_TYPE,
exp_pass_through.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_pass_through.o_SC_TRANS_DATE as SC_TRANS_DATE,
exp_pass_through.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_pass_through.LF_ALPHA_CODE as LF_ALPHA_CODE,
exp_pass_through.LF_STATUS as LF_STATUS,
exp_pass_through.LF_MODE as LF_MODE,
exp_pass_through.LF_INSURED_SSAN as LF_INSURED_SSAN,
exp_pass_through.LF_MEMBERSHIP as LF_MEMBERSHIP,
exp_pass_through.LF_NFO_OPTION as LF_NFO_OPTION,
exp_pass_through.LF_INSURED_NAME as LF_INSURED_NAME,
exp_pass_through.LF_ADDRESS_1 as LF_ADDRESS_1,
exp_pass_through.LF_ADDRESS_2 as LF_ADDRESS_2,
exp_pass_through.LF_ADDRESS_3 as LF_ADDRESS_3,
exp_pass_through.LF_PAYOR_NAME as LF_PAYOR_NAME,
exp_pass_through.LF_OWNER_NAME as LF_OWNER_NAME,
exp_pass_through.LF_MODAL_PREM as LF_MODAL_PREM,
exp_pass_through.LF_ISSUE_DATE as LF_ISSUE_DATE,
exp_pass_through.LF_APPL_DATE as LF_APPL_DATE,
exp_pass_through.LF_BIRTH_DATE as LF_BIRTH_DATE,
exp_pass_through.LF_PAC_DRAW_DAY as LF_PAC_DRAW_DAY,
exp_pass_through.LF_DUE_USE_CD as LF_DUE_USE_CD,
exp_pass_through.LF_REQUIRE_SW as LF_REQUIRE_SW,
exp_pass_through.LF_PAC_BANK_CD as LF_PAC_BANK_CD,
exp_pass_through.LF_PAC_ACCT_NO as LF_PAC_ACCT_NO,
exp_pass_through.LF_FORM as LF_FORM,
exp_pass_through.LF_VOLUME as LF_VOLUME,
exp_pass_through.LF_APP_PREM as LF_APP_PREM,
exp_pass_through.LF_OVER_SHORT as LF_OVER_SHORT,
exp_pass_through.LF_UNDERWRITER as LF_UNDERWRITER,
exp_pass_through.LF_PLAN_NAME as LF_PLAN_NAME,
exp_pass_through.LF_POLICY_FEE as LF_POLICY_FEE,
exp_pass_through.LF_FUND_BALANCE as LF_FUND_BALANCE,
exp_pass_through.LF_SURR_VALUE as LF_SURR_VALUE,
exp_pass_through.LF_DEP_FUND as LF_DEP_FUND,
exp_pass_through.LF_PD_TO_DATE as LF_PD_TO_DATE,
exp_pass_through.LF_LOAN_AMOUNT as LF_LOAN_AMOUNT,
exp_pass_through.LF_DIV_ON_DEP as LF_DIV_ON_DEP,
exp_pass_through.LF_PAIDUP_ADD as LF_PAIDUP_ADD,
exp_pass_through.LF_CASH_VAL_PUA as LF_CASH_VAL_PUA,
exp_pass_through.LF_ANNUAL_PREM as LF_ANNUAL_PREM,
exp_pass_through.LF_AGENT_NO as LF_AGENT_NO,
exp_pass_through.LF_LOAN_VALUE as LF_LOAN_VALUE,
exp_pass_through.LF_PHY_ISS as LF_PHY_ISS,
exp_pass_through.LF_CANC_REASON_CDE as LF_CANC_REASON_CDE,
exp_pass_through.LF_ISS_AGE as LF_ISS_AGE,
exp_pass_through.LF_2ND_INS_NAME as LF_2ND_INS_NAME,
exp_pass_through.LF_OWNER_ADDRESS_1 as LF_OWNER_ADDRESS_1,
exp_pass_through.LF_OWNER_ADDRESS_2 as LF_OWNER_ADDRESS_2,
exp_pass_through.LF_OWNER_ADDRESS_3 as LF_OWNER_ADDRESS_3,
exp_pass_through.LF_PAYOR_ADDRESS_1 as LF_PAYOR_ADDRESS_1,
exp_pass_through.LF_PAYOR_ADDRESS_2 as LF_PAYOR_ADDRESS_2,
exp_pass_through.LF_PAYOR_ADDRESS_3 as LF_PAYOR_ADDRESS_3,
exp_pass_through.LF_OWNER_SSAN as LF_OWNER_SSAN,
exp_pass_through.LF_LAST_ANN_DATE as LF_LAST_ANN_DATE,
exp_pass_through.LF_FUND_BAL_LST_AN as LF_FUND_BAL_LST_AN,
exp_pass_through.LF_LOAN_CALC_DATE as LF_LOAN_CALC_DATE,
exp_pass_through.LF_SURR_CHG_LST_AN as LF_SURR_CHG_LST_AN,
exp_pass_through.LF_POL_ANNUAL_PREM as LF_POL_ANNUAL_PREM,
exp_pass_through.LF_2ND_INS_DOB as LF_2ND_INS_DOB,
exp_pass_through.LF_2ND_INS_ISS_AGE as LF_2ND_INS_ISS_AGE,
exp_pass_through.LF_INS_ISS_AGE as LF_INS_ISS_AGE,
exp_pass_through.LF_INS_TOBACCO_USE as LF_INS_TOBACCO_USE,
exp_pass_through.LF_INS_SEX_CODE as LF_INS_SEX_CODE,
exp_pass_through.LF_2ND_INS_SEX_CDE as LF_2ND_INS_SEX_CDE,
exp_pass_through.LF_DEATH_BENE_OPT as LF_DEATH_BENE_OPT,
exp_pass_through.LF_2ND_INS_SSAN as LF_2ND_INS_SSAN,
exp_pass_through.LF_RESTRICT_CODE as LF_RESTRICT_CODE,
exp_pass_through.LF_LOAN_INT_RATE as LF_LOAN_INT_RATE,
exp_pass_through.LF_LOAN_INT_ACCRU as LF_LOAN_INT_ACCRU,
exp_pass_through.LF_NEXT_AN_CAS_VAL as LF_NEXT_AN_CAS_VAL,
exp_pass_through.LF_DISPLAY_SW as LF_DISPLAY_SW
FROM
exp_pass_through;


-- PIPELINE END FOR 2

-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

END; ';