-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_LOANS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
FEED_DT date;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 
FEED_DT:=(select current_date); 

-- Component LOANS2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.LOANS;


-- PIPELINE START FOR 1

-- Component SQ_LOANS2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_LOANS2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_Count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
DB_T_CORE_MEMBXREF_PROD.LOANS
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_LOANS2.record_Count as record_count,
:feed_ind as feed_ind,
:feed_dt as feed_dt,
SQ_LOANS2.source_record_id
FROM
SQ_LOANS2
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_LOANS3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_LOANS3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_DWNLD_PRIORITY,
$2 as SC_SERVICE_CENTER,
$3 as SC_POLICY_NUM,
$4 as SC_FLT_ITEM,
$5 as SC_FILE_TYPE,
$6 as SC_REC_TRANS_CODE,
$7 as SC_TRANS_DATE,
$8 as SC_TRANS_TYPE,
$9 as PC_ALPHA_CODE,
$10 as PC_NAME_1,
$11 as PC_NAME_2,
$12 as PC_ADDRESS_1,
$13 as PC_ADDRESS_2,
$14 as PC_CITYST,
$15 as PC_ZIP,
$16 as PC_AGENT,
$17 as PC_MEMBER_NUMBER,
$18 as PC_COMPANY,
$19 as PC_INCEPT_DATE,
$20 as LN_STATUS,
$21 as LN_DUE_DATE,
$22 as LN_AMOUNT_DUE,
$23 as LN_NBR_PMNTS_PAID,
$24 as LN_BALANCE,
$25 as LN_PAYOFF_AMT,
$26 as LN_NBR_PMNTS_LATE,
$27 as LN_LATE_CHARGE_AMT,
$28 as LN_ORIGINAL_TERM,
$29 as LN_ORIGINL_AMT_FIN,
$30 as LN_COLLATERAL_DESC,
$31 as LN_CRDT_LIFE_IND,
$32 as LN_A_H_IND,
$33 as LN_PER_DIEM,
$34 as LN_YTD_INTEREST,
$35 as LN_PREV_YTD_INT,
$36 as LN_SSN,
$37 as LN_WORK_PHONE_NBR,
$38 as LN_HOME_PHONE_NBR,
$39 as LN_LAST_PAYMT_DATE,
$40 as LN_INT_RATE,
$41 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
LOANS.SC_DWNLD_PRIORITY,
LOANS.SC_SERVICE_CENTER,
LOANS.SC_POLICY_NUM,
LOANS.SC_FLT_ITEM,
LOANS.SC_FILE_TYPE,
LOANS.SC_REC_TRANS_CODE,
LOANS.SC_TRANS_DATE,
LOANS.SC_TRANS_TYPE,
LOANS.PC_ALPHA_CODE,
LOANS.PC_NAME_1,
LOANS.PC_NAME_2,
LOANS.PC_ADDRESS_1,
LOANS.PC_ADDRESS_2,
LOANS.PC_CITYST,
LOANS.PC_ZIP,
LOANS.PC_AGENT,
LOANS.PC_MEMBER_NUMBER,
LOANS.PC_COMPANY,
LOANS.PC_INCEPT_DATE,
LOANS.LN_STATUS,
LOANS.LN_DUE_DATE,
LOANS.LN_AMOUNT_DUE,
LOANS.LN_NBR_PMNTS_PAID,
LOANS.LN_BALANCE,
LOANS.LN_PAYOFF_AMT,
LOANS.LN_NBR_PMNTS_LATE,
LOANS.LN_LATE_CHARGE_AMT,
LOANS.LN_ORIGINAL_TERM,
LOANS.LN_ORIGINL_AMT_FIN,
LOANS.LN_COLLATERAL_DESC,
LOANS.LN_CRDT_LIFE_IND,
LOANS.LN_A_H_IND,
LOANS.LN_PER_DIEM,
LOANS.LN_YTD_INTEREST,
LOANS.LN_PREV_YTD_INT,
LOANS.LN_SSN,
LOANS.LN_WORK_PHONE_NBR,
LOANS.LN_HOME_PHONE_NBR,
LOANS.LN_LAST_PAYMT_DATE,
LOANS.LN_INT_RATE
FROM DB_T_CORE_MEMBXREF_PROD.LOANS
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_LOANS3.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
SQ_LOANS3.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
SQ_LOANS3.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_LOANS3.SC_FLT_ITEM as SC_FLT_ITEM,
SQ_LOANS3.SC_FILE_TYPE as SC_FILE_TYPE,
SQ_LOANS3.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
SQ_LOANS3.SC_TRANS_DATE as SC_TRANS_DATE,
SQ_LOANS3.SC_TRANS_TYPE as SC_TRANS_TYPE,
SQ_LOANS3.PC_ALPHA_CODE as PC_ALPHA_CODE,
SQ_LOANS3.PC_NAME_1 as PC_NAME_1,
SQ_LOANS3.PC_NAME_2 as PC_NAME_2,
SQ_LOANS3.PC_ADDRESS_1 as PC_ADDRESS_1,
SQ_LOANS3.PC_ADDRESS_2 as PC_ADDRESS_2,
SQ_LOANS3.PC_CITYST as PC_CITYST,
SQ_LOANS3.PC_ZIP as PC_ZIP,
SQ_LOANS3.PC_AGENT as PC_AGENT,
SQ_LOANS3.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
SQ_LOANS3.PC_COMPANY as PC_COMPANY,
SQ_LOANS3.PC_INCEPT_DATE as PC_INCEPT_DATE,
SQ_LOANS3.LN_STATUS as LN_STATUS,
SQ_LOANS3.LN_DUE_DATE as LN_DUE_DATE,
SQ_LOANS3.LN_AMOUNT_DUE as LN_AMOUNT_DUE,
SQ_LOANS3.LN_NBR_PMNTS_PAID as LN_NBR_PMNTS_PAID,
SQ_LOANS3.LN_BALANCE as LN_BALANCE,
SQ_LOANS3.LN_PAYOFF_AMT as LN_PAYOFF_AMT,
SQ_LOANS3.LN_NBR_PMNTS_LATE as LN_NBR_PMNTS_LATE,
SQ_LOANS3.LN_LATE_CHARGE_AMT as LN_LATE_CHARGE_AMT,
SQ_LOANS3.LN_ORIGINAL_TERM as LN_ORIGINAL_TERM,
SQ_LOANS3.LN_ORIGINL_AMT_FIN as LN_ORIGINL_AMT_FIN,
SQ_LOANS3.LN_COLLATERAL_DESC as LN_COLLATERAL_DESC,
SQ_LOANS3.LN_CRDT_LIFE_IND as LN_CRDT_LIFE_IND,
SQ_LOANS3.LN_A_H_IND as LN_A_H_IND,
SQ_LOANS3.LN_PER_DIEM as LN_PER_DIEM,
SQ_LOANS3.LN_YTD_INTEREST as LN_YTD_INTEREST,
SQ_LOANS3.LN_PREV_YTD_INT as LN_PREV_YTD_INT,
SQ_LOANS3.LN_SSN as LN_SSN,
SQ_LOANS3.LN_WORK_PHONE_NBR as LN_WORK_PHONE_NBR,
SQ_LOANS3.LN_HOME_PHONE_NBR as LN_HOME_PHONE_NBR,
SQ_LOANS3.LN_LAST_PAYMT_DATE as LN_LAST_PAYMT_DATE,
SQ_LOANS3.LN_INT_RATE as LN_INT_RATE,
SQ_LOANS3.source_record_id
FROM
SQ_LOANS3
);


-- Component LOANS2, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.LOANS
(
SC_SERVICE_CENTER,
SC_POLICY_NUM,
PC_ALPHA_CODE,
PC_NAME_1,
PC_NAME_2,
PC_ADDRESS_1,
PC_ADDRESS_2,
PC_CITYST,
PC_ZIP,
PC_AGENT,
PC_MEMBER_NUMBER,
PC_COMPANY,
SC_DWNLD_PRIORITY,
SC_FLT_ITEM,
SC_FILE_TYPE,
SC_REC_TRANS_CODE,
SC_TRANS_DATE,
SC_TRANS_TYPE,
PC_INCEPT_DATE,
LN_STATUS,
LN_DUE_DATE,
LN_AMOUNT_DUE,
LN_NBR_PMNTS_PAID,
LN_BALANCE,
LN_PAYOFF_AMT,
LN_NBR_PMNTS_LATE,
LN_LATE_CHARGE_AMT,
LN_ORIGINAL_TERM,
LN_ORIGINL_AMT_FIN,
LN_COLLATERAL_DESC,
LN_CRDT_LIFE_IND,
LN_A_H_IND,
LN_PER_DIEM,
LN_YTD_INTEREST,
LN_PREV_YTD_INT,
LN_SSN,
LN_WORK_PHONE_NBR,
LN_HOME_PHONE_NBR,
LN_LAST_PAYMT_DATE,
LN_INT_RATE
)
SELECT
exp_pass_through.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_pass_through.SC_POLICY_NUM as SC_POLICY_NUM,
exp_pass_through.PC_ALPHA_CODE as PC_ALPHA_CODE,
exp_pass_through.PC_NAME_1 as PC_NAME_1,
exp_pass_through.PC_NAME_2 as PC_NAME_2,
exp_pass_through.PC_ADDRESS_1 as PC_ADDRESS_1,
exp_pass_through.PC_ADDRESS_2 as PC_ADDRESS_2,
exp_pass_through.PC_CITYST as PC_CITYST,
exp_pass_through.PC_ZIP as PC_ZIP,
exp_pass_through.PC_AGENT as PC_AGENT,
exp_pass_through.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
exp_pass_through.PC_COMPANY as PC_COMPANY,
exp_pass_through.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_pass_through.SC_FLT_ITEM as SC_FLT_ITEM,
exp_pass_through.SC_FILE_TYPE as SC_FILE_TYPE,
exp_pass_through.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_pass_through.SC_TRANS_DATE as SC_TRANS_DATE,
exp_pass_through.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_pass_through.PC_INCEPT_DATE as PC_INCEPT_DATE,
exp_pass_through.LN_STATUS as LN_STATUS,
exp_pass_through.LN_DUE_DATE as LN_DUE_DATE,
exp_pass_through.LN_AMOUNT_DUE as LN_AMOUNT_DUE,
exp_pass_through.LN_NBR_PMNTS_PAID as LN_NBR_PMNTS_PAID,
exp_pass_through.LN_BALANCE as LN_BALANCE,
exp_pass_through.LN_PAYOFF_AMT as LN_PAYOFF_AMT,
exp_pass_through.LN_NBR_PMNTS_LATE as LN_NBR_PMNTS_LATE,
exp_pass_through.LN_LATE_CHARGE_AMT as LN_LATE_CHARGE_AMT,
exp_pass_through.LN_ORIGINAL_TERM as LN_ORIGINAL_TERM,
exp_pass_through.LN_ORIGINL_AMT_FIN as LN_ORIGINL_AMT_FIN,
exp_pass_through.LN_COLLATERAL_DESC as LN_COLLATERAL_DESC,
exp_pass_through.LN_CRDT_LIFE_IND as LN_CRDT_LIFE_IND,
exp_pass_through.LN_A_H_IND as LN_A_H_IND,
exp_pass_through.LN_PER_DIEM as LN_PER_DIEM,
exp_pass_through.LN_YTD_INTEREST as LN_YTD_INTEREST,
exp_pass_through.LN_PREV_YTD_INT as LN_PREV_YTD_INT,
exp_pass_through.LN_SSN as LN_SSN,
exp_pass_through.LN_WORK_PHONE_NBR as LN_WORK_PHONE_NBR,
exp_pass_through.LN_HOME_PHONE_NBR as LN_HOME_PHONE_NBR,
exp_pass_through.LN_LAST_PAYMT_DATE as LN_LAST_PAYMT_DATE,
exp_pass_through.LN_INT_RATE as LN_INT_RATE
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';