-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_PORTPOLS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
FEED_DT date;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id);  
FEED_DT:=(select current_date);  

-- Component PORTPOLS2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.PORTPOLS;


-- PIPELINE START FOR 1

-- Component SQ_PORTPOLS2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_PORTPOLS2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_Count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
DB_T_CORE_MEMBXREF_PROD.PORTPOLS
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_PORTPOLS2.record_Count as record_count,
:feed_ind as feed_ind,
:feed_dt as feed_dt,
SQ_PORTPOLS2.source_record_id
FROM
SQ_PORTPOLS2
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_PORTPOLS3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_PORTPOLS3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_DWNLD_PRIORITY,
$2 as SC_SERVICE_CENTER,
$3 as SC_POLICY_NUM,
$4 as SC_FLT_ITEM,
$5 as SC_FILE_TYPE,
$6 as SC_REC_TRANS_CODE,
$7 as SC_TRANS_DATE,
$8 as SC_TRANS_TYPE,
$9 as PC_ALPHA_CODE,
$10 as PC_NAME_1,
$11 as PC_NAME_2,
$12 as PC_ADDRESS_1,
$13 as PC_ADDRESS_2,
$14 as PC_CITYST,
$15 as PC_ZIP,
$16 as PC_TAX_CODE,
$17 as PC_AGENT,
$18 as PC_MEMBER_NUMBER,
$19 as PC_RATE_CODE,
$20 as PC_ENCUMBRANCE,
$21 as PC_PREM_FIN,
$22 as PC_MORT_IND,
$23 as PC_COMPANY,
$24 as PC_INCEPT_DATE,
$25 as PC_EXP_DATE,
$26 as PC_EFF_DATE,
$27 as PC_STATUS,
$28 as PORT_TOT_PREM,
$29 as PORT_REWRITE_IND,
$30 as PORT_REWRITE_DATE,
$31 as PORT_OUTST_AMT,
$32 as PORT_OUTST_TYPE,
$33 as PORT_OUTST_DATE,
$34 as PORT_OUTST_PD_DATE,
$35 as PORT_SUSPENSE_CD,
$36 as PORT_SUSPENSE_CAN,
$37 as PORT_SSN_1,
$38 as PORT_SSN_2,
$39 as PORT_UW_REV_DATE,
$40 as PORT_UW_INITIALS,
$41 as PORT_MORT_NAME_1,
$42 as PORT_MORT_NAME_2,
$43 as PORT_MORT_ADD_1,
$44 as PORT_MORT_ADD_2,
$45 as PORT_MORT_CTYST,
$46 as PORT_MORT_ZIP,
$47 as PORT_STATE,
$48 as PORT_MORT_TYPE,
$49 as PORT_LOAN_NUM,
$50 as PORT_SLOAN_NUM,
$51 as PORT_SMORT_NAME_1,
$52 as PORT_SMORT_NAME_2,
$53 as PORT_SMORT_ADD_1,
$54 as PORT_SMORT_ADD_2,
$55 as PORT_SMORT_CTYST,
$56 as PORT_SMORT_ZIP,
$57 as PORT_SMORT_TYPE,
$58 as PORT_HALF_TERM_BP,
$59 as PORT_FULL_TERM_BP,
$60 as PORT_TRANSFER_DATE,
$61 as PORT_MB_TYPE,
$62 as PORT_MB_ACCT_NUM,
$63 as PORT_SC_LIAB_PRD_I,
$64 as PORT_FIRE_COVERAGE,
$65 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
PORTPOLS.SC_DWNLD_PRIORITY,
PORTPOLS.SC_SERVICE_CENTER,
PORTPOLS.SC_POLICY_NUM,
PORTPOLS.SC_FLT_ITEM,
PORTPOLS.SC_FILE_TYPE,
PORTPOLS.SC_REC_TRANS_CODE,
PORTPOLS.SC_TRANS_DATE,
PORTPOLS.SC_TRANS_TYPE,
PORTPOLS.PC_ALPHA_CODE,
PORTPOLS.PC_NAME_1,
PORTPOLS.PC_NAME_2,
PORTPOLS.PC_ADDRESS_1,
PORTPOLS.PC_ADDRESS_2,
PORTPOLS.PC_CITYST,
PORTPOLS.PC_ZIP,
PORTPOLS.PC_TAX_CODE,
PORTPOLS.PC_AGENT,
PORTPOLS.PC_MEMBER_NUMBER,
PORTPOLS.PC_RATE_CODE,
PORTPOLS.PC_ENCUMBRANCE,
PORTPOLS.PC_PREM_FIN,
PORTPOLS.PC_MORT_IND,
PORTPOLS.PC_COMPANY,
PORTPOLS.PC_INCEPT_DATE,
PORTPOLS.PC_EXP_DATE,
PORTPOLS.PC_EFF_DATE,
PORTPOLS.PC_STATUS,
PORTPOLS.PORT_TOT_PREM,
PORTPOLS.PORT_REWRITE_IND,
PORTPOLS.PORT_REWRITE_DATE,
PORTPOLS.PORT_OUTST_AMT,
PORTPOLS.PORT_OUTST_TYPE,
PORTPOLS.PORT_OUTST_DATE,
PORTPOLS.PORT_OUTST_PD_DATE,
PORTPOLS.PORT_SUSPENSE_CD,
PORTPOLS.PORT_SUSPENSE_CAN,
PORTPOLS.PORT_SSN_1,
PORTPOLS.PORT_SSN_2,
PORTPOLS.PORT_UW_REV_DATE,
PORTPOLS.PORT_UW_INITIALS,
PORTPOLS.PORT_MORT_NAME_1,
PORTPOLS.PORT_MORT_NAME_2,
PORTPOLS.PORT_MORT_ADD_1,
PORTPOLS.PORT_MORT_ADD_2,
PORTPOLS.PORT_MORT_CTYST,
PORTPOLS.PORT_MORT_ZIP,
PORTPOLS.PORT_STATE,
PORTPOLS.PORT_MORT_TYPE,
PORTPOLS.PORT_LOAN_NUM,
PORTPOLS.PORT_SLOAN_NUM,
PORTPOLS.PORT_SMORT_NAME_1,
PORTPOLS.PORT_SMORT_NAME_2,
PORTPOLS.PORT_SMORT_ADD_1,
PORTPOLS.PORT_SMORT_ADD_2,
PORTPOLS.PORT_SMORT_CTYST,
PORTPOLS.PORT_SMORT_ZIP,
PORTPOLS.PORT_SMORT_TYPE,
PORTPOLS.PORT_HALF_TERM_BP,
PORTPOLS.PORT_FULL_TERM_BP,
PORTPOLS.PORT_TRANSFER_DATE,
PORTPOLS.PORT_MB_TYPE,
PORTPOLS.PORT_MB_ACCT_NUM,
PORTPOLS.PORT_SC_LIAB_PRD_I,
PORTPOLS.PORT_FIRE_COVERAGE
FROM DB_T_CORE_MEMBXREF_PROD.PORTPOLS
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_PORTPOLS3.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
SQ_PORTPOLS3.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
SQ_PORTPOLS3.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_PORTPOLS3.SC_FLT_ITEM as SC_FLT_ITEM,
SQ_PORTPOLS3.SC_FILE_TYPE as SC_FILE_TYPE,
SQ_PORTPOLS3.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
SQ_PORTPOLS3.SC_TRANS_DATE as SC_TRANS_DATE,
SQ_PORTPOLS3.SC_TRANS_TYPE as SC_TRANS_TYPE,
SQ_PORTPOLS3.PC_ALPHA_CODE as PC_ALPHA_CODE,
SQ_PORTPOLS3.PC_NAME_1 as PC_NAME_1,
SQ_PORTPOLS3.PC_NAME_2 as PC_NAME_2,
SQ_PORTPOLS3.PC_ADDRESS_1 as PC_ADDRESS_1,
SQ_PORTPOLS3.PC_ADDRESS_2 as PC_ADDRESS_2,
SQ_PORTPOLS3.PC_CITYST as PC_CITYST,
SQ_PORTPOLS3.PC_ZIP as PC_ZIP,
SQ_PORTPOLS3.PC_TAX_CODE as PC_TAX_CODE,
SQ_PORTPOLS3.PC_AGENT as PC_AGENT,
SQ_PORTPOLS3.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
SQ_PORTPOLS3.PC_RATE_CODE as PC_RATE_CODE,
SQ_PORTPOLS3.PC_ENCUMBRANCE as PC_ENCUMBRANCE,
SQ_PORTPOLS3.PC_PREM_FIN as PC_PREM_FIN,
SQ_PORTPOLS3.PC_MORT_IND as PC_MORT_IND,
SQ_PORTPOLS3.PC_COMPANY as PC_COMPANY,
SQ_PORTPOLS3.PC_INCEPT_DATE as PC_INCEPT_DATE,
SQ_PORTPOLS3.PC_EXP_DATE as PC_EXP_DATE,
SQ_PORTPOLS3.PC_EFF_DATE as PC_EFF_DATE,
SQ_PORTPOLS3.PC_STATUS as PC_STATUS,
SQ_PORTPOLS3.PORT_TOT_PREM as PORT_TOT_PREM,
SQ_PORTPOLS3.PORT_REWRITE_IND as PORT_REWRITE_IND,
SQ_PORTPOLS3.PORT_REWRITE_DATE as PORT_REWRITE_DATE,
SQ_PORTPOLS3.PORT_OUTST_AMT as PORT_OUTST_AMT,
SQ_PORTPOLS3.PORT_OUTST_TYPE as PORT_OUTST_TYPE,
SQ_PORTPOLS3.PORT_OUTST_DATE as PORT_OUTST_DATE,
SQ_PORTPOLS3.PORT_OUTST_PD_DATE as PORT_OUTST_PD_DATE,
SQ_PORTPOLS3.PORT_SUSPENSE_CD as PORT_SUSPENSE_CD,
SQ_PORTPOLS3.PORT_SUSPENSE_CAN as PORT_SUSPENSE_CAN,
SQ_PORTPOLS3.PORT_SSN_1 as PORT_SSN_1,
SQ_PORTPOLS3.PORT_SSN_2 as PORT_SSN_2,
SQ_PORTPOLS3.PORT_UW_REV_DATE as PORT_UW_REV_DATE,
SQ_PORTPOLS3.PORT_UW_INITIALS as PORT_UW_INITIALS,
SQ_PORTPOLS3.PORT_MORT_NAME_1 as PORT_MORT_NAME_1,
SQ_PORTPOLS3.PORT_MORT_NAME_2 as PORT_MORT_NAME_2,
SQ_PORTPOLS3.PORT_MORT_ADD_1 as PORT_MORT_ADD_1,
SQ_PORTPOLS3.PORT_MORT_ADD_2 as PORT_MORT_ADD_2,
SQ_PORTPOLS3.PORT_MORT_CTYST as PORT_MORT_CTYST,
SQ_PORTPOLS3.PORT_MORT_ZIP as PORT_MORT_ZIP,
SQ_PORTPOLS3.PORT_STATE as PORT_STATE,
SQ_PORTPOLS3.PORT_MORT_TYPE as PORT_MORT_TYPE,
SQ_PORTPOLS3.PORT_LOAN_NUM as PORT_LOAN_NUM,
SQ_PORTPOLS3.PORT_SLOAN_NUM as PORT_SLOAN_NUM,
SQ_PORTPOLS3.PORT_SMORT_NAME_1 as PORT_SMORT_NAME_1,
SQ_PORTPOLS3.PORT_SMORT_NAME_2 as PORT_SMORT_NAME_2,
SQ_PORTPOLS3.PORT_SMORT_ADD_1 as PORT_SMORT_ADD_1,
SQ_PORTPOLS3.PORT_SMORT_ADD_2 as PORT_SMORT_ADD_2,
SQ_PORTPOLS3.PORT_SMORT_CTYST as PORT_SMORT_CTYST,
SQ_PORTPOLS3.PORT_SMORT_ZIP as PORT_SMORT_ZIP,
SQ_PORTPOLS3.PORT_SMORT_TYPE as PORT_SMORT_TYPE,
SQ_PORTPOLS3.PORT_HALF_TERM_BP as PORT_HALF_TERM_BP,
SQ_PORTPOLS3.PORT_FULL_TERM_BP as PORT_FULL_TERM_BP,
SQ_PORTPOLS3.PORT_TRANSFER_DATE as PORT_TRANSFER_DATE,
SQ_PORTPOLS3.PORT_MB_TYPE as PORT_MB_TYPE,
SQ_PORTPOLS3.PORT_MB_ACCT_NUM as PORT_MB_ACCT_NUM,
SQ_PORTPOLS3.PORT_SC_LIAB_PRD_I as PORT_SC_LIAB_PRD_I,
SQ_PORTPOLS3.PORT_FIRE_COVERAGE as PORT_FIRE_COVERAGE,
SQ_PORTPOLS3.source_record_id
FROM
SQ_PORTPOLS3
);


-- Component PORTPOLS2, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.PORTPOLS
(
SC_DWNLD_PRIORITY,
SC_SERVICE_CENTER,
SC_POLICY_NUM,
SC_FLT_ITEM,
SC_FILE_TYPE,
SC_REC_TRANS_CODE,
SC_TRANS_DATE,
SC_TRANS_TYPE,
PC_ALPHA_CODE,
PC_NAME_1,
PC_NAME_2,
PC_ADDRESS_1,
PC_ADDRESS_2,
PC_CITYST,
PC_ZIP,
PC_TAX_CODE,
PC_AGENT,
PC_MEMBER_NUMBER,
PC_RATE_CODE,
PC_ENCUMBRANCE,
PC_PREM_FIN,
PC_MORT_IND,
PC_COMPANY,
PC_INCEPT_DATE,
PC_EXP_DATE,
PC_EFF_DATE,
PC_STATUS,
PORT_TOT_PREM,
PORT_REWRITE_IND,
PORT_REWRITE_DATE,
PORT_OUTST_AMT,
PORT_OUTST_TYPE,
PORT_OUTST_DATE,
PORT_OUTST_PD_DATE,
PORT_SUSPENSE_CD,
PORT_SUSPENSE_CAN,
PORT_SSN_1,
PORT_SSN_2,
PORT_UW_REV_DATE,
PORT_UW_INITIALS,
PORT_MORT_NAME_1,
PORT_MORT_NAME_2,
PORT_MORT_ADD_1,
PORT_MORT_ADD_2,
PORT_MORT_CTYST,
PORT_MORT_ZIP,
PORT_STATE,
PORT_MORT_TYPE,
PORT_LOAN_NUM,
PORT_SLOAN_NUM,
PORT_SMORT_NAME_1,
PORT_SMORT_NAME_2,
PORT_SMORT_ADD_1,
PORT_SMORT_ADD_2,
PORT_SMORT_CTYST,
PORT_SMORT_ZIP,
PORT_SMORT_TYPE,
PORT_HALF_TERM_BP,
PORT_FULL_TERM_BP,
PORT_TRANSFER_DATE,
PORT_MB_TYPE,
PORT_MB_ACCT_NUM,
PORT_SC_LIAB_PRD_I,
PORT_FIRE_COVERAGE
)
SELECT
exp_pass_through.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_pass_through.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_pass_through.SC_POLICY_NUM as SC_POLICY_NUM,
exp_pass_through.SC_FLT_ITEM as SC_FLT_ITEM,
exp_pass_through.SC_FILE_TYPE as SC_FILE_TYPE,
exp_pass_through.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_pass_through.SC_TRANS_DATE as SC_TRANS_DATE,
exp_pass_through.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_pass_through.PC_ALPHA_CODE as PC_ALPHA_CODE,
exp_pass_through.PC_NAME_1 as PC_NAME_1,
exp_pass_through.PC_NAME_2 as PC_NAME_2,
exp_pass_through.PC_ADDRESS_1 as PC_ADDRESS_1,
exp_pass_through.PC_ADDRESS_2 as PC_ADDRESS_2,
exp_pass_through.PC_CITYST as PC_CITYST,
exp_pass_through.PC_ZIP as PC_ZIP,
exp_pass_through.PC_TAX_CODE as PC_TAX_CODE,
exp_pass_through.PC_AGENT as PC_AGENT,
exp_pass_through.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
exp_pass_through.PC_RATE_CODE as PC_RATE_CODE,
exp_pass_through.PC_ENCUMBRANCE as PC_ENCUMBRANCE,
exp_pass_through.PC_PREM_FIN as PC_PREM_FIN,
exp_pass_through.PC_MORT_IND as PC_MORT_IND,
exp_pass_through.PC_COMPANY as PC_COMPANY,
exp_pass_through.PC_INCEPT_DATE as PC_INCEPT_DATE,
exp_pass_through.PC_EXP_DATE as PC_EXP_DATE,
exp_pass_through.PC_EFF_DATE as PC_EFF_DATE,
exp_pass_through.PC_STATUS as PC_STATUS,
exp_pass_through.PORT_TOT_PREM as PORT_TOT_PREM,
exp_pass_through.PORT_REWRITE_IND as PORT_REWRITE_IND,
exp_pass_through.PORT_REWRITE_DATE as PORT_REWRITE_DATE,
exp_pass_through.PORT_OUTST_AMT as PORT_OUTST_AMT,
exp_pass_through.PORT_OUTST_TYPE as PORT_OUTST_TYPE,
exp_pass_through.PORT_OUTST_DATE as PORT_OUTST_DATE,
exp_pass_through.PORT_OUTST_PD_DATE as PORT_OUTST_PD_DATE,
exp_pass_through.PORT_SUSPENSE_CD as PORT_SUSPENSE_CD,
exp_pass_through.PORT_SUSPENSE_CAN as PORT_SUSPENSE_CAN,
exp_pass_through.PORT_SSN_1 as PORT_SSN_1,
exp_pass_through.PORT_SSN_2 as PORT_SSN_2,
exp_pass_through.PORT_UW_REV_DATE as PORT_UW_REV_DATE,
exp_pass_through.PORT_UW_INITIALS as PORT_UW_INITIALS,
exp_pass_through.PORT_MORT_NAME_1 as PORT_MORT_NAME_1,
exp_pass_through.PORT_MORT_NAME_2 as PORT_MORT_NAME_2,
exp_pass_through.PORT_MORT_ADD_1 as PORT_MORT_ADD_1,
exp_pass_through.PORT_MORT_ADD_2 as PORT_MORT_ADD_2,
exp_pass_through.PORT_MORT_CTYST as PORT_MORT_CTYST,
exp_pass_through.PORT_MORT_ZIP as PORT_MORT_ZIP,
exp_pass_through.PORT_STATE as PORT_STATE,
exp_pass_through.PORT_MORT_TYPE as PORT_MORT_TYPE,
exp_pass_through.PORT_LOAN_NUM as PORT_LOAN_NUM,
exp_pass_through.PORT_SLOAN_NUM as PORT_SLOAN_NUM,
exp_pass_through.PORT_SMORT_NAME_1 as PORT_SMORT_NAME_1,
exp_pass_through.PORT_SMORT_NAME_2 as PORT_SMORT_NAME_2,
exp_pass_through.PORT_SMORT_ADD_1 as PORT_SMORT_ADD_1,
exp_pass_through.PORT_SMORT_ADD_2 as PORT_SMORT_ADD_2,
exp_pass_through.PORT_SMORT_CTYST as PORT_SMORT_CTYST,
exp_pass_through.PORT_SMORT_ZIP as PORT_SMORT_ZIP,
exp_pass_through.PORT_SMORT_TYPE as PORT_SMORT_TYPE,
exp_pass_through.PORT_HALF_TERM_BP as PORT_HALF_TERM_BP,
exp_pass_through.PORT_FULL_TERM_BP as PORT_FULL_TERM_BP,
exp_pass_through.PORT_TRANSFER_DATE as PORT_TRANSFER_DATE,
exp_pass_through.PORT_MB_TYPE as PORT_MB_TYPE,
exp_pass_through.PORT_MB_ACCT_NUM as PORT_MB_ACCT_NUM,
exp_pass_through.PORT_SC_LIAB_PRD_I as PORT_SC_LIAB_PRD_I,
exp_pass_through.PORT_FIRE_COVERAGE as PORT_FIRE_COVERAGE
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';