-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STG_MEMBXREF_TRIGGER("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE TABLENAME varchar;
BEGIN 

TABLENAME:='' '';

-- Component STG_MEMBXREF_TRIGGER, Type Pre SQL 
DELETE FROM DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER_DLY WHERE TABLENAME =''SMLNPOLS_DLY'';


-- Component sq_TRG_MEMBXREF_SRC, Type TABLE_DDL Creating an empty table
CREATE OR REPLACE TEMPORARY TABLE sq_TRG_MEMBXREF
(
FEED_IND varchar(10),
FEED_DATE varchar(10),
RECORD_CNT decimal,
source_record_id number autoincrement start 1 increment 1
);


-- Component sq_TRG_MEMBXREF_SRC, Type IMPORT_DATA Importing Data
;


-- Component exp_MEMBXREF_TRIGGER, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_MEMBXREF_TRIGGER AS
(
SELECT
:TABLENAME as TABLENAME,
sq_TRG_MEMBXREF.FEED_IND as FEED_IND,
to_date ( sq_TRG_MEMBXREF.FEED_DATE , ''YYYY-MM-DD'' ) as FEED_DT,
sq_TRG_MEMBXREF.RECORD_CNT as RECORD_CNT,
sq_TRG_MEMBXREF.source_record_id
FROM
sq_TRG_MEMBXREF
);


-- Component STG_MEMBXREF_TRIGGER, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER_DLY
(
TABLENAME,
FEED_IND,
FEED_DT,
RECORD_CNT
)
SELECT
exp_MEMBXREF_TRIGGER.TABLENAME as TABLENAME,
exp_MEMBXREF_TRIGGER.FEED_IND as FEED_IND,
exp_MEMBXREF_TRIGGER.FEED_DT as FEED_DT,
exp_MEMBXREF_TRIGGER.RECORD_CNT as RECORD_CNT
FROM
exp_MEMBXREF_TRIGGER;


END; ';