-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_VAL_TRG_DATE("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- PIPELINE START FOR 1

-- Component SQ_STG_MEMBXREF_TRIGGER, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_STG_MEMBXREF_TRIGGER AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ACTIVITY_COUNT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT COUNT(*) AS ACTIVITY_COUNT
FROM (SELECT DISTINCT FEED_DT FROM DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER A) X
) SRC
)
);


-- Component Exp_Pass_Through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_Pass_Through AS
(
SELECT
CASE WHEN SQ_STG_MEMBXREF_TRIGGER.ACTIVITY_COUNT <> 1 THEN ''F'' ELSE ''S'' END as Flag,
CASE WHEN SQ_STG_MEMBXREF_TRIGGER.ACTIVITY_COUNT <> 1 THEN 
null --RAISE_ERROR(''FEED DATE IS NULL'') 
ELSE null END as ABORT,
SQ_STG_MEMBXREF_TRIGGER.source_record_id
FROM
SQ_STG_MEMBXREF_TRIGGER
);


-- Component Exp_Pass_Through1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_Pass_Through1 AS
(
SELECT
Exp_Pass_Through.Flag as Flag,
Exp_Pass_Through.source_record_id
FROM
Exp_Pass_Through
);


-- Component DUMMY, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE DUMMY AS
(
SELECT
Exp_Pass_Through1.Flag as FLAG
FROM
Exp_Pass_Through1
);


-- Component DUMMY, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_STG_MEMBXREF_TRIGGER1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_STG_MEMBXREF_TRIGGER1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ACTIVITY_COUNT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT COUNT(*) AS ACTIVITY_COUNT
FROM
(
SELECT DISTINCT FEED_DT
FROM DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER A, (SELECT MAX(LOAD_DT) LD_DT from DB_T_STAG_MEMBXREF_PROD.STG_MEMBER) B
WHERE EXTRACT(MONTH FROM FEED_DT) = EXTRACT(MONTH FROM ADD_MONTHS(LD_DT, 1)) AND EXTRACT(DAY FROM FEED_DT) NOT BETWEEN 1 and 10
)X
) SRC
)
);


-- Component Exp_Pass_Through2, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_Pass_Through2 AS
(
SELECT
CASE WHEN SQ_STG_MEMBXREF_TRIGGER1.ACTIVITY_COUNT <> 1 THEN ''F'' ELSE ''S'' END as FLAG,
CASE WHEN SQ_STG_MEMBXREF_TRIGGER1.ACTIVITY_COUNT <> 1 THEN 
null --RAISE_ERROR(''FILES BELONG TO DIFFERENT FEED DATES'') 
ELSE null END as ABORT,
SQ_STG_MEMBXREF_TRIGGER1.source_record_id
FROM
SQ_STG_MEMBXREF_TRIGGER1
);


-- Component Exp_Pass_Through3, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_Pass_Through3 AS
(
SELECT
Exp_Pass_Through2.FLAG as FLAG,
Exp_Pass_Through2.source_record_id
FROM
Exp_Pass_Through2
);


-- Component DUMMY1, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE DUMMY1 AS
(
SELECT
Exp_Pass_Through3.FLAG as FLAG
FROM
Exp_Pass_Through3
);


-- Component DUMMY1, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 2

END; ';