-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_CLAIM_DETAILS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component CLAIM_DETAILS, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.CLAIM_DETAILS;


-- Component SQ_view_CLAIM_DETAILS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_view_CLAIM_DETAILS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMBER_NUM,
$2 as POLICY_NUM,
$3 as POLICY_TYPE,
$4 as DOL,
$5 as LINECODE_VIN,
$6 as CAUSE_CODE,
$7 as CLM_AMOUNT,
$8 as POLICY_STATUS,
$9 as POLICYSTATUS_GROUPNM,
$10 as CLAIM_NBR,
$11 as CSR_CLAIM_NBR,
$12 as CLAIM_STATUS_CD,
$13 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
view_CLAIM_DETAILS.MEMBER_NUM,
view_CLAIM_DETAILS.POLICY_NUM,
view_CLAIM_DETAILS.POLICY_TYPE,
view_CLAIM_DETAILS.DOL,
null LINECODE_VIN,
view_CLAIM_DETAILS.CAUSE_CODE,
view_CLAIM_DETAILS.CLM_AMOUNT,
view_CLAIM_DETAILS.POLICY_STATUS,
null POLICYSTATUS_GROUPNM,
view_CLAIM_DETAILS.CLAIM_NBR,
view_CLAIM_DETAILS.CSR_CLAIM_NBR,
view_CLAIM_DETAILS.CLAIM_STATUS_CD
FROM DB_T_STAG_MEMBXREF_PROD.view_CLAIM_DETAILS
) SRC
)
);


-- Component exp_claim_details, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_claim_details AS
(
SELECT
SQ_view_CLAIM_DETAILS.MEMBER_NUM as MEMBER_NUM,
SQ_view_CLAIM_DETAILS.POLICY_NUM as POLICY_NUM,
SQ_view_CLAIM_DETAILS.POLICY_TYPE as POLICY_TYPE,
SQ_view_CLAIM_DETAILS.DOL as DOL,
SQ_view_CLAIM_DETAILS.LINECODE_VIN as LINECODE_VIN,
SQ_view_CLAIM_DETAILS.CAUSE_CODE as CAUSE_CODE,
SQ_view_CLAIM_DETAILS.CLM_AMOUNT as CLM_AMOUNT,
SQ_view_CLAIM_DETAILS.POLICY_STATUS as POLICY_STATUS,
SQ_view_CLAIM_DETAILS.POLICYSTATUS_GROUPNM as POLICYSTATUS_GROUPNM,
SQ_view_CLAIM_DETAILS.CLAIM_NBR as CLAIM_NBR,
SQ_view_CLAIM_DETAILS.CSR_CLAIM_NBR as CSR_CLAIM_NBR,
SQ_view_CLAIM_DETAILS.CLAIM_STATUS_CD as CLAIM_STATUS_CD,
SQ_view_CLAIM_DETAILS.source_record_id
FROM
SQ_view_CLAIM_DETAILS
);


-- Component CLAIM_DETAILS, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.CLAIM_DETAILS
(
MEMBER_NUM,
POLICY_NUM,
POLICY_TYPE,
DOL,
LINECODE_VIN,
CAUSE_CODE,
CLM_AMOUNT,
POLICY_STATUS,
POLICYSTATUS_GROUPNM,
CLAIM_NBR,
CSR_CLAIM_NBR,
CLAIM_STATUS_CD
)
SELECT
exp_claim_details.MEMBER_NUM as MEMBER_NUM,
exp_claim_details.POLICY_NUM as POLICY_NUM,
exp_claim_details.POLICY_TYPE as POLICY_TYPE,
exp_claim_details.DOL as DOL,
exp_claim_details.LINECODE_VIN as LINECODE_VIN,
exp_claim_details.CAUSE_CODE as CAUSE_CODE,
exp_claim_details.CLM_AMOUNT as CLM_AMOUNT,
exp_claim_details.POLICY_STATUS as POLICY_STATUS,
exp_claim_details.POLICYSTATUS_GROUPNM as POLICYSTATUS_GROUPNM,
exp_claim_details.CLAIM_NBR as CLAIM_NBR,
exp_claim_details.CSR_CLAIM_NBR as CSR_CLAIM_NBR,
exp_claim_details.CLAIM_STATUS_CD as CLAIM_STATUS_CD
FROM
exp_claim_details;


END; ';