-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_CLUE_POLICY_SUMM("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component CLUE_POLICY_SUMM, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_ONSITE_PROD.CLUE_POLICY_SUMM;


-- Component SQ_UW_LOSS_HISTORY, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_UW_LOSS_HISTORY AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as PLCY_NBR,
$2 as POLICY_ID,
$3 as ULH_CLAIM_NBR,
$4 as UW_LOSS_TYPE_CD,
$5 as LOSS_TYPE_DESC,
$6 as ULH_LOSS_AMT,
$7 as ULH_LOSS_DT,
$8 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
--/* /* ----CLUE_POLICY_SUMM------*/ */
--/* -POLICY_NBRS DATA */
WITH POLICY_NBRS AS
(SELECT DISTINCT
PLCY_NBR,
POLICY_ID
FROM
(SELECT DISTINCT
POL_NBR AS PLCY_NBR,
POLICY_ID
FROM DB_T_STAG_MEMBXREF_PROD.POL_VEH_LIST        
UNION
SELECT DISTINCT
POL_NBR AS PLCY_NBR,
POLICY_ID
FROM DB_T_STAG_MEMBXREF_PROD.OUT_OF_FORCE_POL_VEH_LIST
UNION
SELECT DISTINCT
PLCY_NBR,
null AS POLICY_ID
FROM DB_T_CORE_DM_PROD.POLICY
)AS POL1),
/* -NEED_CLUE_INFO */
NEED_CLUE_INFO AS
(SELECT DISTINCT
POLICY_ID,
EFFECTIVE_DT,
EXPIRATION_DT,
ULH_CLAIM_NBR,
UNIT_NBR AS VEH_UNIT_NBR,
ULH_ENTRY_CD,
UW_OBJECT_CD,
UW_LOSS_TYPE_CD,
ULH_LOSS_AMT,
ULH_LOSS_DT,
EFFECTIVE_ACY_TS
FROM DB_T_ONSITE_PROD.UW_LOSS_HISTORY
WHERE HISTORY_VLD_NBR<=0),
/* -MERGEM */
MERGEM AS
(SELECT
A.POLICY_ID,
A.PLCY_NBR,
B.EFFECTIVE_DT,
B.EXPIRATION_DT,
B.ULH_CLAIM_NBR,
B.VEH_UNIT_NBR,
B.ULH_ENTRY_CD,
B.UW_OBJECT_CD,
B.UW_LOSS_TYPE_CD,
B.ULH_LOSS_AMT,
B.ULH_LOSS_DT,
B.EFFECTIVE_ACY_TS
FROM
POLICY_NBRS A
INNER JOIN
NEED_CLUE_INFO B
ON A.POLICY_ID=B.POLICY_ID),
/* -FILTER_MERGEM */
FILTER_MERGEM AS 
(SELECT *
FROM MERGEM 
WHERE ULH_ENTRY_CD=''RO''),
/* -FIND_EXP_DT */
FIND_EXP_DT AS 
(SELECT DISTINCT
PLCY_NBR,
UW_OBJECT_CD,
EXPIRATION_DT AS EXP_DT2,
ROW_NUMBER() OVER (PARTITION BY PLCY_NBR, UW_OBJECT_CD ORDER BY EXPIRATION_DT DESC) RNK1
FROM FILTER_MERGEM
QUALIFY RNK1=1),
/* -MERGE_EXP_DT */
MERGE_EXP_DT AS
(SELect
A.*,
B.EXP_DT2
FROM
FILTER_MERGEM A
LEFT OUTER JOIN
FIND_EXP_DT B
ON A.PLCY_NBR=B.PLCY_NBR
AND A.UW_OBJECT_CD=B.UW_OBJECT_CD
WHERE A.EXPIRATION_DT=B.EXP_DT2),
/* -FIND_EFF_DT */
FIND_EFF_DT AS (
SELECT DISTINCT
PLCY_NBR,
UW_OBJECT_CD,
EFFECTIVE_DT AS EFF_DT2,
ROW_NUMBER() OVER (PARTITION BY PLCY_NBR, UW_OBJECT_CD ORDER BY EFFECTIVE_DT DESC) RNK1
FROM MERGE_EXP_DT
QUALIFY RNK1=1),
/* -MERGE_EFF_DT */
MERGE_EFF_DT AS (
SELect
A.*,
B.EFF_DT2
FROM
FILTER_MERGEM A
LEFT OUTER JOIN
FIND_EFF_DT B
ON A.PLCY_NBR=B.PLCY_NBR
AND A.UW_OBJECT_CD=B.UW_OBJECT_CD
WHERE A.EFFECTIVE_DT=B.EFF_DT2
AND A.UW_OBJECT_CD=''BASIC'')
--/*/* --------------------MAIN_QUERY---------------------*/ */
--/* --DELETE FROM DB_T_ONSITE_PROD.CLUE_POLICY_SUMM ALL */
SELect
TRIM(PLCY_NBR) AS PLCY_NBR,
POLICY_ID,
ULH_CLAIM_NBR,
UW_LOSS_TYPE_CD,
CASE WHEN UW_LOSS_TYPE_CD=''CP'' THEN ''COMPREHENSIVE'' 
WHEN UW_LOSS_TYPE_CD=''CO'' THEN ''COLLISION''
WHEN UW_LOSS_TYPE_CD=''OT'' THEN ''OTHER''
WHEN UW_LOSS_TYPE_CD=''MP'' THEN ''MEDICAL PAYMENTS''
WHEN UW_LOSS_TYPE_CD=''PD'' THEN ''PROPERTY DAMAGE''
WHEN UW_LOSS_TYPE_CD=''RR'' THEN ''LOSS OF USE''
WHEN UW_LOSS_TYPE_CD=''GL'' THEN ''GLASS BREAKAGE''
WHEN UW_LOSS_TYPE_CD=''PI'' THEN ''PERS. INJ. PROT.''
WHEN UW_LOSS_TYPE_CD=''BI'' THEN ''BODILY INJURY''
WHEN UW_LOSS_TYPE_CD=''UM'' THEN ''UNINSURED M.''
WHEN UW_LOSS_TYPE_CD=''TL'' THEN ''ERS''
WHEN UW_LOSS_TYPE_CD=''UN'' THEN ''UNDERINSURED''
WHEN UW_LOSS_TYPE_CD=''ME'' THEN ''MEDICAL EXPENSES''
ELSE UW_LOSS_TYPE_CD END AS LOSS_TYPE_DESC,
ULH_LOSS_AMT,
ULH_LOSS_DT
FROM MERGE_EFF_DT
) SRC
)
);


-- Component EXP_CLUE_POLICY_SUMM, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXP_CLUE_POLICY_SUMM AS
(
SELECT
SQ_UW_LOSS_HISTORY.PLCY_NBR as PLCY_NBR,
SQ_UW_LOSS_HISTORY.POLICY_ID as POLICY_ID,
SQ_UW_LOSS_HISTORY.ULH_CLAIM_NBR as ULH_CLAIM_NBR,
SQ_UW_LOSS_HISTORY.UW_LOSS_TYPE_CD as UW_LOSS_TYPE_CD,
SQ_UW_LOSS_HISTORY.LOSS_TYPE_DESC as LOSS_TYPE_DESC,
SQ_UW_LOSS_HISTORY.ULH_LOSS_AMT as ULH_LOSS_AMT,
SQ_UW_LOSS_HISTORY.ULH_LOSS_DT as ULH_LOSS_DT,
SQ_UW_LOSS_HISTORY.source_record_id
FROM
SQ_UW_LOSS_HISTORY
);


-- Component CLUE_POLICY_SUMM, Type TARGET 
INSERT INTO DB_T_ONSITE_PROD.CLUE_POLICY_SUMM
(
PLCY_NBR,
POLICY_ID,
ULH_CLAIM_NBR,
UW_LOSS_TYPE_CD,
LOSS_TYPE_DESC,
ULH_LOSS_AMT,
ULH_LOSS_DT
)
SELECT
EXP_CLUE_POLICY_SUMM.PLCY_NBR as PLCY_NBR,
EXP_CLUE_POLICY_SUMM.POLICY_ID as POLICY_ID,
EXP_CLUE_POLICY_SUMM.ULH_CLAIM_NBR as ULH_CLAIM_NBR,
EXP_CLUE_POLICY_SUMM.UW_LOSS_TYPE_CD as UW_LOSS_TYPE_CD,
EXP_CLUE_POLICY_SUMM.LOSS_TYPE_DESC as LOSS_TYPE_DESC,
EXP_CLUE_POLICY_SUMM.ULH_LOSS_AMT as ULH_LOSS_AMT,
EXP_CLUE_POLICY_SUMM.ULH_LOSS_DT as ULH_LOSS_DT
FROM
EXP_CLUE_POLICY_SUMM;


END; ';