-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_FGM_SMLN_COMMERCIAL("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component FGM_SMLN_COMMERCIAL, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.FGM_SMLN_COMMERCIAL;


-- Component SQ_view_FGM_SMLN_COMMERCIAL, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_view_FGM_SMLN_COMMERCIAL AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as POLICY,
$2 as AGENT,
$3 as OTH_TYPE,
$4 as EFFECTIVE_DATE,
$5 as NEXT_RENEWAL_DATE,
$6 as YR,
$7 as MODEL,
$8 as LIABILITY_LIMITS,
$9 as TOTAL_VALUE,
$10 as COLLISION,
$11 as DWELLING,
$12 as BODILY_INJURY,
$13 as PROPERTY_DAMAGE,
$14 as MEDICAL_PAYMENTS,
$15 as UMBI,
$16 as TOTAL_PREMIUM,
$17 as MEMBER_NUMBER,
$18 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
view_FGM_SMLN_COMMERCIAL.POLICY,
view_FGM_SMLN_COMMERCIAL.AGENT,
view_FGM_SMLN_COMMERCIAL.OTH_TYPE,
view_FGM_SMLN_COMMERCIAL.EFFECTIVE_DATE,
view_FGM_SMLN_COMMERCIAL.NEXT_RENEWAL_DATE,
view_FGM_SMLN_COMMERCIAL.YR,
view_FGM_SMLN_COMMERCIAL.MODEL,
view_FGM_SMLN_COMMERCIAL.LIABILITY_LIMITS,
view_FGM_SMLN_COMMERCIAL.TOTAL_VALUE,
view_FGM_SMLN_COMMERCIAL.COLLISION,
view_FGM_SMLN_COMMERCIAL.DWELLING,
view_FGM_SMLN_COMMERCIAL.BODILY_INJURY,
view_FGM_SMLN_COMMERCIAL.PROPERTY_DAMAGE,
view_FGM_SMLN_COMMERCIAL.MEDICAL_PAYMENTS,
view_FGM_SMLN_COMMERCIAL.UMBI,
view_FGM_SMLN_COMMERCIAL.TOTAL_PREMIUM,
view_FGM_SMLN_COMMERCIAL.MEMBER_NUMBER
FROM DB_T_STAG_MEMBXREF_PROD.view_FGM_SMLN_COMMERCIAL
) SRC
)
);


-- Component exp_fgm_smln_commercial, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_fgm_smln_commercial AS
(
SELECT
SQ_view_FGM_SMLN_COMMERCIAL.POLICY as POLICY,
SQ_view_FGM_SMLN_COMMERCIAL.AGENT as AGENT,
SQ_view_FGM_SMLN_COMMERCIAL.OTH_TYPE as OTH_TYPE,
SQ_view_FGM_SMLN_COMMERCIAL.EFFECTIVE_DATE as EFFECTIVE_DATE,
SQ_view_FGM_SMLN_COMMERCIAL.NEXT_RENEWAL_DATE as NEXT_RENEWAL_DATE,
SQ_view_FGM_SMLN_COMMERCIAL.YR as YR,
SQ_view_FGM_SMLN_COMMERCIAL.MODEL as MODEL,
SQ_view_FGM_SMLN_COMMERCIAL.LIABILITY_LIMITS as LIABILITY_LIMITS,
SQ_view_FGM_SMLN_COMMERCIAL.TOTAL_VALUE as TOTAL_VALUE,
SQ_view_FGM_SMLN_COMMERCIAL.COLLISION as COLLISION,
SQ_view_FGM_SMLN_COMMERCIAL.DWELLING as DWELLING,
SQ_view_FGM_SMLN_COMMERCIAL.BODILY_INJURY as BODILY_INJURY,
SQ_view_FGM_SMLN_COMMERCIAL.PROPERTY_DAMAGE as PROPERTY_DAMAGE,
SQ_view_FGM_SMLN_COMMERCIAL.MEDICAL_PAYMENTS as MEDICAL_PAYMENTS,
SQ_view_FGM_SMLN_COMMERCIAL.UMBI as UMBI,
SQ_view_FGM_SMLN_COMMERCIAL.TOTAL_PREMIUM as TOTAL_PREMIUM,
SQ_view_FGM_SMLN_COMMERCIAL.MEMBER_NUMBER as MEMBER_NUMBER,
SQ_view_FGM_SMLN_COMMERCIAL.source_record_id
FROM
SQ_view_FGM_SMLN_COMMERCIAL
);


-- Component FGM_SMLN_COMMERCIAL, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.FGM_SMLN_COMMERCIAL
(
POLICY,
AGENT,
OTH_TYPE,
EFFECTIVE_DATE,
NEXT_RENEWAL_DATE,
YR,
MODEL,
LIABILITY_LIMITS,
TOTAL_VALUE,
COLLISION,
DWELLING,
BODILY_INJURY,
PROPERTY_DAMAGE,
MEDICAL_PAYMENTS,
UMBI,
TOTAL_PREMIUM,
MEMBER_NUMBER
)
SELECT
exp_fgm_smln_commercial.POLICY as POLICY,
exp_fgm_smln_commercial.AGENT as AGENT,
exp_fgm_smln_commercial.OTH_TYPE as OTH_TYPE,
exp_fgm_smln_commercial.EFFECTIVE_DATE as EFFECTIVE_DATE,
exp_fgm_smln_commercial.NEXT_RENEWAL_DATE as NEXT_RENEWAL_DATE,
exp_fgm_smln_commercial.YR as YR,
exp_fgm_smln_commercial.MODEL as MODEL,
exp_fgm_smln_commercial.LIABILITY_LIMITS as LIABILITY_LIMITS,
exp_fgm_smln_commercial.TOTAL_VALUE as TOTAL_VALUE,
exp_fgm_smln_commercial.COLLISION as COLLISION,
exp_fgm_smln_commercial.DWELLING as DWELLING,
exp_fgm_smln_commercial.BODILY_INJURY as BODILY_INJURY,
exp_fgm_smln_commercial.PROPERTY_DAMAGE as PROPERTY_DAMAGE,
exp_fgm_smln_commercial.MEDICAL_PAYMENTS as MEDICAL_PAYMENTS,
exp_fgm_smln_commercial.UMBI as UMBI,
exp_fgm_smln_commercial.TOTAL_PREMIUM as TOTAL_PREMIUM,
exp_fgm_smln_commercial.MEMBER_NUMBER as MEMBER_NUMBER
FROM
exp_fgm_smln_commercial;


END; ';