-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LIFE("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component LIFE, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.LIFE;


-- Component SQ_view_LIFE, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_view_LIFE AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMBER_NUMBER,
$2 as POLICY,
$3 as AGENT,
$4 as POL_TYPE,
$5 as PLAN,
$6 as INSURED,
$7 as OWNER,
$8 as PAYOR,
$9 as AMOUNT,
$10 as ISSUE_DATE,
$11 as CURRENT_CASH_VALUE,
$12 as MODE_OF_PAYMENT,
$13 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
view_LIFE.MEMBER_NUMBER,
view_LIFE.POLICY,
view_LIFE.AGENT,
view_LIFE.POL_TYPE,
view_LIFE.PLAN,
view_LIFE.INSURED,
view_LIFE.OWNER,
view_LIFE.PAYOR,
view_LIFE.AMOUNT,
view_LIFE.ISSUE_DATE,
view_LIFE.CURRENT_CASH_VALUE,
view_LIFE.MODE_OF_PAYMENT
FROM DB_T_STAG_MEMBXREF_PROD.view_LIFE
) SRC
)
);


-- Component exp_life, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_life AS
(
SELECT
SQ_view_LIFE.MEMBER_NUMBER as MEMBER_NUMBER,
SQ_view_LIFE.POLICY as POLICY,
SQ_view_LIFE.AGENT as AGENT,
SQ_view_LIFE.POL_TYPE as POL_TYPE,
SQ_view_LIFE.PLAN as PLAN,
SQ_view_LIFE.INSURED as INSURED,
SQ_view_LIFE.OWNER as OWNER,
SQ_view_LIFE.PAYOR as PAYOR,
SQ_view_LIFE.AMOUNT as AMOUNT,
SQ_view_LIFE.ISSUE_DATE as ISSUE_DATE,
SQ_view_LIFE.CURRENT_CASH_VALUE as CURRENT_CASH_VALUE,
SQ_view_LIFE.MODE_OF_PAYMENT as MODE_OF_PAYMENT,
SQ_view_LIFE.source_record_id
FROM
SQ_view_LIFE
);


-- Component LIFE, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.LIFE
(
MEMBER_NUMBER,
POLICY,
AGENT,
POL_TYPE,
PLAN,
INSURED,
OWNER,
PAYOR,
AMOUNT,
ISSUE_DATE,
CURRENT_CASH_VALUE,
MODE_OF_PAYMENT
)
SELECT
exp_life.MEMBER_NUMBER as MEMBER_NUMBER,
exp_life.POLICY as POLICY,
exp_life.AGENT as AGENT,
exp_life.POL_TYPE as POL_TYPE,
exp_life.PLAN as PLAN,
exp_life.INSURED as INSURED,
exp_life.OWNER as OWNER,
exp_life.PAYOR as PAYOR,
exp_life.AMOUNT as AMOUNT,
exp_life.ISSUE_DATE as ISSUE_DATE,
exp_life.CURRENT_CASH_VALUE as CURRENT_CASH_VALUE,
exp_life.MODE_OF_PAYMENT as MODE_OF_PAYMENT
FROM
exp_life;


END; ';