-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_MEMBER_XREF("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component MEMBER_XREF, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.MEMBER_XREF;


-- Component SQ_view_MEMBER_XREF, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_view_MEMBER_XREF AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMB_NUM,
$2 as POLICY_NUM,
$3 as NAME_1,
$4 as NAME_2,
$5 as ADDRESS_1,
$6 as ADDRESS_2,
$7 as CITY,
$8 as STATE,
$9 as ZIP,
$10 as AGT_NUM,
$11 as EXPIRATION_DATE,
$12 as HOME_PHONE,
$13 as WORK_PHONE,
$14 as CELL_PHONE,
$15 as FAX,
$16 as EMAIL,
$17 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
view_MEMBER_XREF.MEMB_NUM,
view_MEMBER_XREF.POLICY_NUM,
view_MEMBER_XREF.NAME_1,
view_MEMBER_XREF.NAME_2,
view_MEMBER_XREF.ADDRESS_1,
view_MEMBER_XREF.ADDRESS_2,
view_MEMBER_XREF.CITY,
view_MEMBER_XREF.STATE,
view_MEMBER_XREF.ZIP,
view_MEMBER_XREF.AGT_NUM,
view_MEMBER_XREF.EXPIRATION_DATE,
view_MEMBER_XREF.HOME_PHONE,
view_MEMBER_XREF.WORK_PHONE,
view_MEMBER_XREF.CELL_PHONE,
view_MEMBER_XREF.FAX,
view_MEMBER_XREF.EMAIL
FROM DB_T_STAG_MEMBXREF_PROD.view_MEMBER_XREF
) SRC
)
);


-- Component exp_member_xref, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_member_xref AS
(
SELECT
SQ_view_MEMBER_XREF.MEMB_NUM as MEMB_NUM,
SQ_view_MEMBER_XREF.POLICY_NUM as POLICY_NUM,
SQ_view_MEMBER_XREF.NAME_1 as NAME_1,
SQ_view_MEMBER_XREF.NAME_2 as NAME_2,
SQ_view_MEMBER_XREF.ADDRESS_1 as ADDRESS_1,
SQ_view_MEMBER_XREF.ADDRESS_2 as ADDRESS_2,
SQ_view_MEMBER_XREF.CITY as CITY,
SQ_view_MEMBER_XREF.STATE as STATE,
SQ_view_MEMBER_XREF.ZIP as ZIP,
SQ_view_MEMBER_XREF.AGT_NUM as AGT_NUM,
SQ_view_MEMBER_XREF.EXPIRATION_DATE as EXPIRATION_DATE,
SQ_view_MEMBER_XREF.HOME_PHONE as HOME_PHONE,
SQ_view_MEMBER_XREF.WORK_PHONE as WORK_PHONE,
SQ_view_MEMBER_XREF.CELL_PHONE as CELL_PHONE,
SQ_view_MEMBER_XREF.FAX as FAX,
SQ_view_MEMBER_XREF.EMAIL as EMAIL,
SQ_view_MEMBER_XREF.source_record_id
FROM
SQ_view_MEMBER_XREF
);


-- Component MEMBER_XREF, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.MEMBER_XREF
(
MEMB_NUM,
POLICY_NUM,
NAME_1,
NAME_2,
ADDRESS_1,
ADDRESS_2,
CITY,
STATE,
ZIP,
AGT_NUM,
EXPIRATION_DATE,
HOME_PHONE,
WORK_PHONE,
CELL_PHONE,
FAX,
EMAIL
)
SELECT
exp_member_xref.MEMB_NUM as MEMB_NUM,
exp_member_xref.POLICY_NUM as POLICY_NUM,
exp_member_xref.NAME_1 as NAME_1,
exp_member_xref.NAME_2 as NAME_2,
exp_member_xref.ADDRESS_1 as ADDRESS_1,
exp_member_xref.ADDRESS_2 as ADDRESS_2,
exp_member_xref.CITY as CITY,
exp_member_xref.STATE as STATE,
exp_member_xref.ZIP as ZIP,
exp_member_xref.AGT_NUM as AGT_NUM,
exp_member_xref.EXPIRATION_DATE as EXPIRATION_DATE,
exp_member_xref.HOME_PHONE as HOME_PHONE,
exp_member_xref.WORK_PHONE as WORK_PHONE,
exp_member_xref.CELL_PHONE as CELL_PHONE,
exp_member_xref.FAX as FAX,
exp_member_xref.EMAIL as EMAIL
FROM
exp_member_xref;


END; ';