-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_OTHER_CLIENTS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component OTHER_CLIENTS, Type Pre SQL 
delete from DB_T_STAG_MEMBXREF_PROD.OTHER_CLIENTS;


-- Component SQ_MEMBER_XREF, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_MEMBER_XREF AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MASTER_MBR,
$2 as RELATED_MBR,
$3 as MO_ID,
$4 as MEMB_NUM,
$5 as POLICY_NUM,
$6 as NAME_1,
$7 as NAME_2,
$8 as ADDRESS_1,
$9 as ADDRESS_2,
$10 as CITY,
$11 as STATE,
$12 as ZIP,
$13 as AGT_NUM,
$14 as EXPIRATION_DATE,
$15 as HOME_PHONE,
$16 as WORK_PHONE,
$17 as CELL_PHONE,
$18 as FAX,
$19 as EMAIL,
$20 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
select
	MASTER_MBR,
	RELATED_MBR,
	MO_ID,
	MEMB_NUM,
	POLICY_NUM,
	NAME_1,
	NAME_2,
	ADDRESS_1,
	ADDRESS_2,
	CITY,
	STATE,
	ZIP,
	AGT_NUM,
	EXPIRATION_DATE,
	HOME_PHONE,
	WORK_PHONE,
	CELL_PHONE,
	FAX,
	EMAIL 
from
	DB_T_STAG_MEMBXREF_PROD.Other_Members A
	inner join DB_T_STAG_MEMBXREF_PROD.MEMBER_XREF B
		on A.RELATED_MBR = B.MEMB_NUM
) SRC
)
);


-- Component Exp_Pass_Through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_Pass_Through AS
(
SELECT
SQ_MEMBER_XREF.MASTER_MBR as MASTER_MBR,
SQ_MEMBER_XREF.RELATED_MBR as RELATED_MBR,
SQ_MEMBER_XREF.MO_ID as MO_ID,
SQ_MEMBER_XREF.MEMB_NUM as MEMB_NUM,
SQ_MEMBER_XREF.POLICY_NUM as POLICY_NUM,
SQ_MEMBER_XREF.NAME_1 as NAME_1,
SQ_MEMBER_XREF.NAME_2 as NAME_2,
SQ_MEMBER_XREF.ADDRESS_1 as ADDRESS_1,
SQ_MEMBER_XREF.ADDRESS_2 as ADDRESS_2,
SQ_MEMBER_XREF.CITY as CITY,
SQ_MEMBER_XREF.STATE as STATE,
SQ_MEMBER_XREF.ZIP as ZIP,
SQ_MEMBER_XREF.AGT_NUM as AGT_NUM,
SQ_MEMBER_XREF.EXPIRATION_DATE as EXPIRATION_DATE,
SQ_MEMBER_XREF.HOME_PHONE as HOME_PHONE,
SQ_MEMBER_XREF.WORK_PHONE as WORK_PHONE,
SQ_MEMBER_XREF.CELL_PHONE as CELL_PHONE,
SQ_MEMBER_XREF.FAX as FAX,
SQ_MEMBER_XREF.EMAIL as EMAIL,
SQ_MEMBER_XREF.source_record_id
FROM
SQ_MEMBER_XREF
);


-- Component OTHER_CLIENTS, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.OTHER_CLIENTS
(
MASTER_MBR,
RELATED_MBR,
MO_ID,
MEMB_NUM,
POLICY_NUM,
NAME_1,
NAME_2,
ADDRESS_1,
ADDRESS_2,
CITY,
STATE,
ZIP,
AGT_NUM,
EXPIRATION_DATE,
HOME_PHONE,
WORK_PHONE,
CELL_PHONE,
FAX,
EMAIL
)
SELECT
Exp_Pass_Through.MASTER_MBR as MASTER_MBR,
Exp_Pass_Through.RELATED_MBR as RELATED_MBR,
Exp_Pass_Through.MO_ID as MO_ID,
Exp_Pass_Through.MEMB_NUM as MEMB_NUM,
Exp_Pass_Through.POLICY_NUM as POLICY_NUM,
Exp_Pass_Through.NAME_1 as NAME_1,
Exp_Pass_Through.NAME_2 as NAME_2,
Exp_Pass_Through.ADDRESS_1 as ADDRESS_1,
Exp_Pass_Through.ADDRESS_2 as ADDRESS_2,
Exp_Pass_Through.CITY as CITY,
Exp_Pass_Through.STATE as STATE,
Exp_Pass_Through.ZIP as ZIP,
Exp_Pass_Through.AGT_NUM as AGT_NUM,
Exp_Pass_Through.EXPIRATION_DATE as EXPIRATION_DATE,
Exp_Pass_Through.HOME_PHONE as HOME_PHONE,
Exp_Pass_Through.WORK_PHONE as WORK_PHONE,
Exp_Pass_Through.CELL_PHONE as CELL_PHONE,
Exp_Pass_Through.FAX as FAX,
Exp_Pass_Through.EMAIL as EMAIL
FROM
Exp_Pass_Through;


END; ';