-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_OTHER_MEMBERS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component OTHER_MEMBERS, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.OTHER_MEMBERS;


-- Component SQ_MEMBER_XREF, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_MEMBER_XREF AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MASTER_MBR,
$2 as RELATED_MBR,
$3 as MO_ID,
$4 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
select MASTER_MBR
,RELATED_MBR
,MO_ID
FROM
(
SELECT distinct
a.member_nbr as master_member
,b.member_nbr as related_member
,A.MO_ID
,CASE WHEN A.MEMBER_TYPE=''CST'' THEN ''C''||SUBSTR( ''0000000'' || TRIM((A.MEMBER_NBR) ),LENGTH(TRIM(A.MEMBER_NBR ))+1,7)
WHEN A.MEMBER_TYPE=''MBR'' THEN SUBSTR( ''00000000'' || (TRIM(A.MEMBER_NBR )),LENGTH(TRIM(A.MEMBER_NBR))+1,8)
ELSE ''99999999'' END AS MASTER_MBR,
CASE WHEN B.MEMBER_TYPE=''CST'' THEN ''C''||SUBSTR( ''0000000'' || TRIM((B.MEMBER_NBR) ),LENGTH(TRIM(B.MEMBER_NBR ))+1,7)
WHEN B.MEMBER_TYPE=''MBR'' THEN SUBSTR( ''00000000'' || (TRIM(B.MEMBER_NBR )),LENGTH(TRIM(B.MEMBER_NBR))+1,8)
ELSE ''99999999'' END AS RELATED_MBR
FROM
DB_T_CORE_PROD.BUXTON_REVERSE_FEED A inner join
DB_T_CORE_PROD.BUXTON_REVERSE_FEED B  
on  A.ADDR_ID = B.ADDR_ID
where a.member_nbr <> b.member_nbr
and a.LOB <> ''LIFE''
) x
where x.MO_ID = (select  Max(MO_ID)
	FROM DB_T_CORE_PROD.BUXTON_REVERSE_FEED)
) SRC
)
);


-- Component EXP_OTHER_MEMBERS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXP_OTHER_MEMBERS AS
(
SELECT
SQ_MEMBER_XREF.MASTER_MBR as MASTER_MBR,
SQ_MEMBER_XREF.RELATED_MBR as RELATED_MBR,
SQ_MEMBER_XREF.MO_ID as MO_ID,
SQ_MEMBER_XREF.source_record_id
FROM
SQ_MEMBER_XREF
);


-- Component OTHER_MEMBERS, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.OTHER_MEMBERS
(
MASTER_MBR,
RELATED_MBR,
MO_ID
)
SELECT
EXP_OTHER_MEMBERS.MASTER_MBR as MASTER_MBR,
EXP_OTHER_MEMBERS.RELATED_MBR as RELATED_MBR,
EXP_OTHER_MEMBERS.MO_ID as MO_ID
FROM
EXP_OTHER_MEMBERS;


END; ';