-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_POLICY_DETAILS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component POLICY_DETAILS, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.POLICY_DETAILS;


-- Component SQ_view_POLICY_DETAILS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_view_POLICY_DETAILS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMBER_NUM,
$2 as POLICY_NUM,
$3 as AGENT_NBR,
$4 as SERVICE_CENTER,
$5 as NAME_1,
$6 as NAME_2,
$7 as ADDRESS_1,
$8 as ADDRESS_2,
$9 as CITY,
$10 as STATE,
$11 as ZIP,
$12 as POLICY_TYPE,
$13 as FORM,
$14 as EFF_DATE,
$15 as EXP_DATE,
$16 as THE_EXP_DATE,
$17 as COVERAGE_A,
$18 as COVERAGE_B,
$19 as COVERAGE_C,
$20 as COVERAGE_D,
$21 as TOTAL_PREM,
$22 as PROTECTION_CLASS,
$23 as VALUED_CLIENT_DATE,
$24 as INCEPT_DATE,
$25 as POLICY_TENURE,
$26 as COMPANY,
$27 as COUNTY,
$28 as THE_STATE,
$29 as THE_CLASS,
$30 as LOCATION_1,
$31 as LOCATION_2,
$32 as POLICY_STATUS,
$33 as POLICY_STATUS_DESC,
$34 as UNITS,
$35 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
view_POLICY_DETAILS.MEMBER_NUM,
view_POLICY_DETAILS.POLICY_NUM,
view_POLICY_DETAILS.AGENT_NBR,
view_POLICY_DETAILS.SERVICE_CENTER,
view_POLICY_DETAILS.NAME_1,
view_POLICY_DETAILS.NAME_2,
view_POLICY_DETAILS.ADDRESS_1,
view_POLICY_DETAILS.ADDRESS_2,
view_POLICY_DETAILS.CITY,
view_POLICY_DETAILS.STATE,
view_POLICY_DETAILS.ZIP,
view_POLICY_DETAILS.POLICY_TYPE,
view_POLICY_DETAILS.FORM,
view_POLICY_DETAILS.EFF_DATE,
view_POLICY_DETAILS.EXP_DATE,
view_POLICY_DETAILS.THE_EXP_DATE,
view_POLICY_DETAILS.COVERAGE_A,
view_POLICY_DETAILS.COVERAGE_B,
view_POLICY_DETAILS.COVERAGE_C,
view_POLICY_DETAILS.COVERAGE_D,
view_POLICY_DETAILS.TOTAL_PREM,
view_POLICY_DETAILS.PROTECTION_CLASS,
view_POLICY_DETAILS.VALUED_CLIENT_DATE,
view_POLICY_DETAILS.INCEPT_DATE,
view_POLICY_DETAILS.POLICY_TENURE,
view_POLICY_DETAILS.COMPANY,
view_POLICY_DETAILS.COUNTY,
view_POLICY_DETAILS.THE_STATE,
view_POLICY_DETAILS.THE_CLASS,
view_POLICY_DETAILS.LOCATION_1,
view_POLICY_DETAILS.LOCATION_2,
view_POLICY_DETAILS.POLICY_STATUS,
view_POLICY_DETAILS.POLICY_STATUS_DESC,
view_POLICY_DETAILS.UNITS
FROM DB_T_STAG_MEMBXREF_PROD.view_POLICY_DETAILS
) SRC
)
);


-- Component exp_policy_details, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_policy_details AS
(
SELECT
SQ_view_POLICY_DETAILS.MEMBER_NUM as MEMBER_NUM,
SQ_view_POLICY_DETAILS.POLICY_NUM as POLICY_NUM,
SQ_view_POLICY_DETAILS.AGENT_NBR as AGENT_NBR,
SQ_view_POLICY_DETAILS.SERVICE_CENTER as SERVICE_CENTER,
SQ_view_POLICY_DETAILS.NAME_1 as NAME_1,
SQ_view_POLICY_DETAILS.NAME_2 as NAME_2,
SQ_view_POLICY_DETAILS.ADDRESS_1 as ADDRESS_1,
SQ_view_POLICY_DETAILS.ADDRESS_2 as ADDRESS_2,
SQ_view_POLICY_DETAILS.CITY as CITY,
SQ_view_POLICY_DETAILS.STATE as STATE,
SQ_view_POLICY_DETAILS.ZIP as ZIP,
SQ_view_POLICY_DETAILS.POLICY_TYPE as POLICY_TYPE,
SQ_view_POLICY_DETAILS.FORM as FORM,
SQ_view_POLICY_DETAILS.EFF_DATE as EFF_DATE,
SQ_view_POLICY_DETAILS.EXP_DATE as EXP_DATE,
SQ_view_POLICY_DETAILS.THE_EXP_DATE as THE_EXP_DATE,
SQ_view_POLICY_DETAILS.COVERAGE_A as COVERAGE_A,
SQ_view_POLICY_DETAILS.COVERAGE_B as COVERAGE_B,
SQ_view_POLICY_DETAILS.COVERAGE_C as COVERAGE_C,
SQ_view_POLICY_DETAILS.COVERAGE_D as COVERAGE_D,
SQ_view_POLICY_DETAILS.TOTAL_PREM as TOTAL_PREM,
SQ_view_POLICY_DETAILS.PROTECTION_CLASS as PROTECTION_CLASS,
SQ_view_POLICY_DETAILS.VALUED_CLIENT_DATE as VALUED_CLIENT_DATE,
SQ_view_POLICY_DETAILS.INCEPT_DATE as INCEPT_DATE,
SQ_view_POLICY_DETAILS.POLICY_TENURE as POLICY_TENURE,
SQ_view_POLICY_DETAILS.COMPANY as COMPANY,
SQ_view_POLICY_DETAILS.COUNTY as COUNTY,
SQ_view_POLICY_DETAILS.THE_STATE as THE_STATE,
SQ_view_POLICY_DETAILS.THE_CLASS as THE_CLASS,
SQ_view_POLICY_DETAILS.LOCATION_1 as LOCATION_1,
SQ_view_POLICY_DETAILS.LOCATION_2 as LOCATION_2,
SQ_view_POLICY_DETAILS.POLICY_STATUS as POLICY_STATUS,
SQ_view_POLICY_DETAILS.POLICY_STATUS_DESC as POLICY_STATUS_DESC,
SQ_view_POLICY_DETAILS.UNITS as UNITS,
SQ_view_POLICY_DETAILS.source_record_id
FROM
SQ_view_POLICY_DETAILS
);


-- Component POLICY_DETAILS, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.POLICY_DETAILS
(
MEMBER_NUM,
POLICY_NUM,
AGENT_NBR,
SERVICE_CENTER,
NAME_1,
NAME_2,
ADDRESS_1,
ADDRESS_2,
CITY,
STATE,
ZIP,
POLICY_TYPE,
FORM,
EFF_DATE,
EXP_DATE,
THE_EXP_DATE,
COVERAGE_A,
COVERAGE_B,
COVERAGE_C,
COVERAGE_D,
TOTAL_PREM,
PROTECTION_CLASS,
VALUED_CLIENT_DATE,
INCEPT_DATE,
POLICY_TENURE,
COMPANY,
COUNTY,
THE_STATE,
THE_CLASS,
LOCATION_1,
LOCATION_2,
POLICY_STATUS,
POLICY_STATUS_DESC,
UNITS
)
SELECT
exp_policy_details.MEMBER_NUM as MEMBER_NUM,
exp_policy_details.POLICY_NUM as POLICY_NUM,
exp_policy_details.AGENT_NBR as AGENT_NBR,
exp_policy_details.SERVICE_CENTER as SERVICE_CENTER,
exp_policy_details.NAME_1 as NAME_1,
exp_policy_details.NAME_2 as NAME_2,
exp_policy_details.ADDRESS_1 as ADDRESS_1,
exp_policy_details.ADDRESS_2 as ADDRESS_2,
exp_policy_details.CITY as CITY,
exp_policy_details.STATE as STATE,
exp_policy_details.ZIP as ZIP,
exp_policy_details.POLICY_TYPE as POLICY_TYPE,
exp_policy_details.FORM as FORM,
exp_policy_details.EFF_DATE as EFF_DATE,
exp_policy_details.EXP_DATE as EXP_DATE,
exp_policy_details.THE_EXP_DATE as THE_EXP_DATE,
exp_policy_details.COVERAGE_A as COVERAGE_A,
exp_policy_details.COVERAGE_B as COVERAGE_B,
exp_policy_details.COVERAGE_C as COVERAGE_C,
exp_policy_details.COVERAGE_D as COVERAGE_D,
exp_policy_details.TOTAL_PREM as TOTAL_PREM,
exp_policy_details.PROTECTION_CLASS as PROTECTION_CLASS,
exp_policy_details.VALUED_CLIENT_DATE as VALUED_CLIENT_DATE,
exp_policy_details.INCEPT_DATE as INCEPT_DATE,
exp_policy_details.POLICY_TENURE as POLICY_TENURE,
exp_policy_details.COMPANY as COMPANY,
exp_policy_details.COUNTY as COUNTY,
exp_policy_details.THE_STATE as THE_STATE,
exp_policy_details.THE_CLASS as THE_CLASS,
exp_policy_details.LOCATION_1 as LOCATION_1,
exp_policy_details.LOCATION_2 as LOCATION_2,
exp_policy_details.POLICY_STATUS as POLICY_STATUS,
exp_policy_details.POLICY_STATUS_DESC as POLICY_STATUS_DESC,
exp_policy_details.UNITS as UNITS
FROM
exp_policy_details;


END; ';