-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_POLICY_SCORES("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component POLICY_SCORES, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.POLICY_SCORES;


-- Component SQ_view_POLICY_SCORES, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_view_POLICY_SCORES AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SCORE_TYPE,
$2 as SCORE_DESC,
$3 as MEMBER_NUM,
$4 as POLICY_NUM,
$5 as ASOFDATE,
$6 as SCR_VALUE,
$7 as POLICY_STATUS,
$8 as POLICY_STATUS_DESC,
$9 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
view_POLICY_SCORES.SCORE_TYPE,
view_POLICY_SCORES.SCORE_DESC,
view_POLICY_SCORES.MEMBER_NUM,
view_POLICY_SCORES.POLICY_NUM,
view_POLICY_SCORES.ASOFDATE,
view_POLICY_SCORES.SCR_VALUE,
view_POLICY_SCORES.POLICY_STATUS,
view_POLICY_SCORES.POLICY_STATUS_DESC
FROM DB_T_STAG_MEMBXREF_PROD.view_POLICY_SCORES
) SRC
)
);


-- Component exp_policy_scores, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_policy_scores AS
(
SELECT
SQ_view_POLICY_SCORES.SCORE_TYPE as SCORE_TYPE,
SQ_view_POLICY_SCORES.SCORE_DESC as SCORE_DESC,
SQ_view_POLICY_SCORES.MEMBER_NUM as MEMBER_NUM,
SQ_view_POLICY_SCORES.POLICY_NUM as POLICY_NUM,
SQ_view_POLICY_SCORES.ASOFDATE as ASOFDATE,
SQ_view_POLICY_SCORES.SCR_VALUE as SCR_VALUE,
SQ_view_POLICY_SCORES.POLICY_STATUS as POLICY_STATUS,
SQ_view_POLICY_SCORES.POLICY_STATUS_DESC as POLICY_STATUS_DESC,
SQ_view_POLICY_SCORES.source_record_id
FROM
SQ_view_POLICY_SCORES
);


-- Component POLICY_SCORES, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.POLICY_SCORES
(
SCORE_TYPE,
SCORE_DESC,
MEMBER_NUM,
POLICY_NUM,
ASOFDATE,
SCR_VALUE,
POLICY_STATUS,
POLICY_STATUS_DESC
)
SELECT
exp_policy_scores.SCORE_TYPE as SCORE_TYPE,
exp_policy_scores.SCORE_DESC as SCORE_DESC,
exp_policy_scores.MEMBER_NUM as MEMBER_NUM,
exp_policy_scores.POLICY_NUM as POLICY_NUM,
exp_policy_scores.ASOFDATE as ASOFDATE,
exp_policy_scores.SCR_VALUE as SCR_VALUE,
exp_policy_scores.POLICY_STATUS as POLICY_STATUS,
exp_policy_scores.POLICY_STATUS_DESC as POLICY_STATUS_DESC
FROM
exp_policy_scores;


END; ';