-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_QRY1_MORE_THAN_3LOB("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component QRY1_MORE_THAN_3LOB, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.QRY1_MORE_THAN_3LOB;


-- Component SQ_MEMBER_XREF, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_MEMBER_XREF AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMB_NUM,
$2 as AGENT,
$3 as NAME_1,
$4 as ADDRESS_1,
$5 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 
DISTINCT  A.MEMB_NUM,
B.AGENT,
A.NAME_1,
A.ADDRESS_1
FROM DB_T_STAG_MEMBXREF_PROD.MEMBER_XREF AS A
LEFT OUTER JOIN DB_T_STAG_MEMBXREF_PROD.HOMEFARMFIRE AS B
ON A.MEMB_NUM = B.MEMBER_NUMBER
LEFT OUTER JOIN DB_T_STAG_MEMBXREF_PROD.POL_VEH_LIST AS C
ON SUBSTR(TRIM(C.CLIENT_REF_NBR),2,7) = SUBSTR(TRIM(A.MEMB_NUM),2,7) 
LEFT OUTER JOIN DB_T_STAG_MEMBXREF_PROD.SMLN_FGM_MFG_NONCOMMERCIAL AS D
ON D.MEMBER_NUMBER = A.MEMB_NUM
LEFT OUTER JOIN DB_T_STAG_MEMBXREF_PROD.FGM_SMLN_COMMERCIAL AS E
ON E.MEMBER_NUMBER = A.MEMB_NUM
LEFT OUTER JOIN DB_T_STAG_MEMBXREF_PROD.LIFE AS F
ON  F.MEMBER_NUMBER = A.MEMB_NUM
WHERE --DB_T_CORE_DM_PROD.POLICY IS NOT NULL
--AND 
C.POL_NBR IS NOT NULL
--AND DB_T_CORE_DM_PROD.POLICY IS NOT NULL
) SRC
)
);


-- Component exp_qr1_more_than_3lob, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_qr1_more_than_3lob AS
(
SELECT
SQ_MEMBER_XREF.MEMB_NUM as MEMB_NUM,
SQ_MEMBER_XREF.AGENT as AGENT,
SQ_MEMBER_XREF.NAME_1 as NAME_1,
SQ_MEMBER_XREF.ADDRESS_1 as ADDRESS_1,
SQ_MEMBER_XREF.source_record_id
FROM
SQ_MEMBER_XREF
);


-- Component QRY1_MORE_THAN_3LOB, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.QRY1_MORE_THAN_3LOB
(
MEMB_NUM,
AGENT,
NAME_1,
ADDRESS_1
)
SELECT
exp_qr1_more_than_3lob.MEMB_NUM as MEMB_NUM,
exp_qr1_more_than_3lob.AGENT as AGENT,
exp_qr1_more_than_3lob.NAME_1 as NAME_1,
exp_qr1_more_than_3lob.ADDRESS_1 as ADDRESS_1
FROM
exp_qr1_more_than_3lob;


END; ';