-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_SMLN_FGM_MFG_NONCOMMERCIAL("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SMLN_FGM_MFG_NONCOMMERCIAL, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.SMLN_FGM_MFG_NONCOMMERCIAL;


-- Component SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as POLICY,
$2 as AGENT,
$3 as POL_TYPE,
$4 as OTH_TYPE,
$5 as EFFECTIVE_DATE,
$6 as NEXT_RENEWAL_DATE,
$7 as YR,
$8 as MODEL,
$9 as LIABILITY_LIMITS,
$10 as TOTAL_VALUE,
$11 as COMPREHENSIVE,
$12 as COLLISION,
$13 as DWELLING,
$14 as BODILY_INJURY,
$15 as PROPERTY_DAMAGE,
$16 as MEDICAL_PAYMENTS,
$17 as UMBI,
$18 as TOTAL_PREMIUM,
$19 as MEMBER_NUMBER,
$20 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
v_SMLN_FGM_MFG_NONCOMMERCIAL.POLICY,
v_SMLN_FGM_MFG_NONCOMMERCIAL.AGENT,
v_SMLN_FGM_MFG_NONCOMMERCIAL.POL_TYPE,
v_SMLN_FGM_MFG_NONCOMMERCIAL.OTH_TYPE,
v_SMLN_FGM_MFG_NONCOMMERCIAL.EFFECTIVE_DATE,
v_SMLN_FGM_MFG_NONCOMMERCIAL.NEXT_RENEWAL_DATE,
v_SMLN_FGM_MFG_NONCOMMERCIAL.YR,
v_SMLN_FGM_MFG_NONCOMMERCIAL.MODEL,
v_SMLN_FGM_MFG_NONCOMMERCIAL.LIABILITY_LIMITS,
v_SMLN_FGM_MFG_NONCOMMERCIAL.TOTAL_VALUE,
v_SMLN_FGM_MFG_NONCOMMERCIAL.COMPREHENSIVE,
v_SMLN_FGM_MFG_NONCOMMERCIAL.COLLISION,
v_SMLN_FGM_MFG_NONCOMMERCIAL.DWELLING,
v_SMLN_FGM_MFG_NONCOMMERCIAL.BODILY_INJURY,
v_SMLN_FGM_MFG_NONCOMMERCIAL.PROPERTY_DAMAGE,
v_SMLN_FGM_MFG_NONCOMMERCIAL.MEDICAL_PAYMENTS,
v_SMLN_FGM_MFG_NONCOMMERCIAL.UMBI,
v_SMLN_FGM_MFG_NONCOMMERCIAL.TOTAL_PREMIUM,
v_SMLN_FGM_MFG_NONCOMMERCIAL.MEMBER_NUMBER
FROM DB_T_STAG_MEMBXREF_PROD.v_SMLN_FGM_MFG_NONCOMMERCIAL
) SRC
)
);


-- Component exp_smln_fgm_mfg_noncommercial, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_smln_fgm_mfg_noncommercial AS
(
SELECT
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.POLICY as POLICY,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.AGENT as AGENT,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.POL_TYPE as POL_TYPE,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.OTH_TYPE as OTH_TYPE,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.EFFECTIVE_DATE as EFFECTIVE_DATE,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.NEXT_RENEWAL_DATE as NEXT_RENEWAL_DATE,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.YR as YR,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.MODEL as MODEL,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.LIABILITY_LIMITS as LIABILITY_LIMITS,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.TOTAL_VALUE as TOTAL_VALUE,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.COMPREHENSIVE as COMPREHENSIVE,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.COLLISION as COLLISION,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.DWELLING as DWELLING,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.BODILY_INJURY as BODILY_INJURY,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.PROPERTY_DAMAGE as PROPERTY_DAMAGE,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.MEDICAL_PAYMENTS as MEDICAL_PAYMENTS,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.UMBI as UMBI,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.TOTAL_PREMIUM as TOTAL_PREMIUM,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.MEMBER_NUMBER as MEMBER_NUMBER,
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL.source_record_id
FROM
SQ_v_SMLN_FGM_MFG_NONCOMMERCIAL
);


-- Component SMLN_FGM_MFG_NONCOMMERCIAL, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.SMLN_FGM_MFG_NONCOMMERCIAL
(
POLICY,
AGENT,
POL_TYPE,
OTH_TYPE,
EFFECTIVE_DATE,
NEXT_RENEWAL_DATE,
YR,
MODEL,
LIABILITY_LIMITS,
TOTAL_VALUE,
COMPREHENSIVE,
COLLISION,
DWELLING,
BODILY_INJURY,
PROPERTY_DAMAGE,
MEDICAL_PAYMENTS,
UMBI,
TOTAL_PREMIUM,
MEMBER_NUMBER
)
SELECT
exp_smln_fgm_mfg_noncommercial.POLICY as POLICY,
exp_smln_fgm_mfg_noncommercial.AGENT as AGENT,
exp_smln_fgm_mfg_noncommercial.POL_TYPE as POL_TYPE,
exp_smln_fgm_mfg_noncommercial.OTH_TYPE as OTH_TYPE,
exp_smln_fgm_mfg_noncommercial.EFFECTIVE_DATE as EFFECTIVE_DATE,
exp_smln_fgm_mfg_noncommercial.NEXT_RENEWAL_DATE as NEXT_RENEWAL_DATE,
exp_smln_fgm_mfg_noncommercial.YR as YR,
exp_smln_fgm_mfg_noncommercial.MODEL as MODEL,
exp_smln_fgm_mfg_noncommercial.LIABILITY_LIMITS as LIABILITY_LIMITS,
exp_smln_fgm_mfg_noncommercial.TOTAL_VALUE as TOTAL_VALUE,
exp_smln_fgm_mfg_noncommercial.COMPREHENSIVE as COMPREHENSIVE,
exp_smln_fgm_mfg_noncommercial.COLLISION as COLLISION,
exp_smln_fgm_mfg_noncommercial.DWELLING as DWELLING,
exp_smln_fgm_mfg_noncommercial.BODILY_INJURY as BODILY_INJURY,
exp_smln_fgm_mfg_noncommercial.PROPERTY_DAMAGE as PROPERTY_DAMAGE,
exp_smln_fgm_mfg_noncommercial.MEDICAL_PAYMENTS as MEDICAL_PAYMENTS,
exp_smln_fgm_mfg_noncommercial.UMBI as UMBI,
exp_smln_fgm_mfg_noncommercial.TOTAL_PREMIUM as TOTAL_PREMIUM,
exp_smln_fgm_mfg_noncommercial.MEMBER_NUMBER as MEMBER_NUMBER
FROM
exp_smln_fgm_mfg_noncommercial;


END; ';