-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_VEH_DETAILS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component VEH_DETAILS, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.VEH_DETAILS;


-- Component SQ_view_VEH_DETAILS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_view_VEH_DETAILS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as GROUP_NAME,
$2 as MEMBER_NUM,
$3 as POLICY_NUM,
$4 as VIN,
$5 as VEH_MAKE_CD,
$6 as VEH_MODEL_DESC,
$7 as VEH_MODEL_YR,
$8 as RATED_DRV_FULL_NM,
$9 as CMP_COV_DED,
$10 as VEH_STATUS,
$11 as VEH_STATUS_DESC,
$12 as CLAIM_NBR,
$13 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
view_VEH_DETAILS.GROUP_NAME,
view_VEH_DETAILS.MEMBER_NUM,
view_VEH_DETAILS.POLICY_NUM,
view_VEH_DETAILS.VIN,
view_VEH_DETAILS.VEH_MAKE_CD,
view_VEH_DETAILS.VEH_MODEL_DESC,
view_VEH_DETAILS.VEH_MODEL_YR,
view_VEH_DETAILS.RATED_DRV_FULL_NM,
view_VEH_DETAILS.CMP_COV_DED,
view_VEH_DETAILS.VEH_STATUS,
view_VEH_DETAILS.VEH_STATUS_DESC,
view_VEH_DETAILS.CLAIM_NBR
FROM DB_T_STAG_MEMBXREF_PROD.view_VEH_DETAILS
) SRC
)
);


-- Component exp_veh_details, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_veh_details AS
(
SELECT
SQ_view_VEH_DETAILS.GROUP_NAME as GROUP_NAME,
SQ_view_VEH_DETAILS.MEMBER_NUM as MEMBER_NUM,
SQ_view_VEH_DETAILS.POLICY_NUM as POLICY_NUM,
SQ_view_VEH_DETAILS.VIN as VIN,
SQ_view_VEH_DETAILS.VEH_MAKE_CD as VEH_MAKE_CD,
SQ_view_VEH_DETAILS.VEH_MODEL_DESC as VEH_MODEL_DESC,
SQ_view_VEH_DETAILS.VEH_MODEL_YR as VEH_MODEL_YR,
SQ_view_VEH_DETAILS.RATED_DRV_FULL_NM as RATED_DRV_FULL_NM,
SQ_view_VEH_DETAILS.CMP_COV_DED as CMP_COV_DED,
SQ_view_VEH_DETAILS.VEH_STATUS as VEH_STATUS,
SQ_view_VEH_DETAILS.VEH_STATUS_DESC as VEH_STATUS_DESC,
SQ_view_VEH_DETAILS.CLAIM_NBR as CLAIM_NBR,
SQ_view_VEH_DETAILS.source_record_id
FROM
SQ_view_VEH_DETAILS
);


-- Component VEH_DETAILS, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.VEH_DETAILS
(
GROUP_NAME,
MEMBER_NUM,
POLICY_NUM,
VIN,
VEH_MAKE_CD,
VEH_MODEL_DESC,
VEH_MODEL_YR,
RATED_DRV_FULL_NM,
CMP_COV_DED,
VEH_STATUS,
VEH_STATUS_DESC,
CLAIM_NBR
)
SELECT
exp_veh_details.GROUP_NAME as GROUP_NAME,
exp_veh_details.MEMBER_NUM as MEMBER_NUM,
exp_veh_details.POLICY_NUM as POLICY_NUM,
exp_veh_details.VIN as VIN,
exp_veh_details.VEH_MAKE_CD as VEH_MAKE_CD,
exp_veh_details.VEH_MODEL_DESC as VEH_MODEL_DESC,
exp_veh_details.VEH_MODEL_YR as VEH_MODEL_YR,
exp_veh_details.RATED_DRV_FULL_NM as RATED_DRV_FULL_NM,
exp_veh_details.CMP_COV_DED as CMP_COV_DED,
exp_veh_details.VEH_STATUS as VEH_STATUS,
exp_veh_details.VEH_STATUS_DESC as VEH_STATUS_DESC,
exp_veh_details.CLAIM_NBR as CLAIM_NBR
FROM
exp_veh_details;


END; ';