-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_AGENT_RECODES_SOURCE_INS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component AGENT_RECODES_SOURCE, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.AGENT_RECODES_SOURCE;


-- Component SQ_view_Fire, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_view_Fire AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as POLICY_NUM,
$2 as MEMBER_NUM,
$3 as NAME_1,
$4 as NAME_2,
$5 as ADDRESS_1,
$6 as ADDRESS_2,
$7 as CITY,
$8 as STATE,
$9 as ZIP,
$10 as POLICY_DESCRIPTION,
$11 as AGT_NUM,
$12 as POLICY_STATUS,
$13 as SC_NUM,
$14 as POLICY_TYPE,
$15 as EXPIRATION_DATE,
$16 as TOTAL_POLS,
$17 as TOTAL_PREM,
$18 as TOTAL_LOB,
$19 as THE_STATE,
$20 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT A.POLICY_NUM,       
		A.MEMBER_NUM,       
		A.NAME_1,       
		A.NAME_2,       
		A.ADDRESS_1,       
		A.ADDRESS_2,       
		A.CITY,       
		A.STATE,       
		A.ZIP,       
		A.POLICY_DESCRIPTION,       
		A.AGT_NUM,       
		A.POLICY_STATUS,       
		A.SC_NUM,       
		A.POLICY_TYPE,       
		A.EXPIRATION_DATE,      
		B.TOTAL_POLS,      
		P.TOTAL_PREM,      
		B.TOTAL_LOB,      
		P.THE_STATE  
	FROM DB_T_STAG_MEMBXREF_PROD.POLICIES_BY_MEMBER A  
	LEFT JOIN DB_T_STAG_MEMBXREF_PROD.POLICY_TYPE_BY_CUSTOMER B ON A.MEMBER_NUM = B.MEMBER_NUM  
	LEFT JOIN  
		(SELECT POL_NBR AS POLICY_NBR,      
			RISK_STATE_CD AS THE_STATE,      
			SUM(TOT_PRM_AMT * 2) AS TOTAL_PREM  
		FROM DB_T_STAG_MEMBXREF_PROD.POL_VEH_LIST  
		GROUP BY 1,2       
		UNION    
		SELECT SC_POLICY_NUM AS POLICY_NBR,      
			HO_STATE AS THE_STATE,       
			HO_TOT_PREM AS TOTAL_PREM  
		FROM DB_T_CORE_MEMBXREF_PROD.HOMEPOLS    
		UNION    
		SELECT SC_POLICY_NUM AS POLICY_NBR,      
			RFD_STATE AS THE_STATE,       
			RFD_TOT_PREM AS TOTAL_PREM  
		FROM DB_T_CORE_MEMBXREF_PROD.FARMPOLS    
		UNION    
		SELECT SC_POLICY_NUM AS POLICY_NBR,      
			FI_STATE AS THE_STATE,       
			FI_TOT_PREM AS TOTAL_PREM  
		FROM DB_T_CORE_MEMBXREF_PROD.FIREPOLS    
		UNION    
		SELECT SC_POLICY_NUM AS POLICY_NBR,       
			MH_ALPHA_ST AS THE_STATE,       
			MH_UNP_TOTAL_PREM AS TOTAL_PREM  
		FROM DB_T_CORE_MEMBXREF_PROD.MANHOMEPOLS    
		UNION    
		SELECT SC_POLICY_NUM AS POLICY_NBR,       
			SMLN_STATE AS THE_STATE,       
			SMLN_TOT_PREM AS TOTAL_PREM  
		FROM DB_T_CORE_MEMBXREF_PROD.SMLNPOLS    
		UNION    
		SELECT SC_POLICY_NUM AS POLICY_NBR,       
			FGM_STATE AS THE_STATE,       
			FGM_TOT_PREM AS TOTAL_PREM  
		FROM DB_T_CORE_MEMBXREF_PROD.FGMPOLS    
		UNION    
		SELECT SC_POLICY_NUM AS POLICY_NBR,       
			PORT_STATE AS THE_STATE,       
			PORT_TOT_PREM AS TOTAL_PREM  
		FROM DB_T_CORE_MEMBXREF_PROD.PORTPOLS    
		UNION    
		SELECT SC_POLICY_NUM AS POLICY_NBR,       
			'''' AS THE_STATE,       
			LF_ANNUAL_PREM AS TOTAL_PREM  
		FROM DB_T_CORE_MEMBXREF_PROD.LIFEPOLS    
		UNION    
		SELECT POL_ID AS POLICY_NBR,        
			'''' AS THE_STATE,       
			0  AS TOTAL_PREM  
		FROM DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST  
		) P ON P.POLICY_NBR = A.POLICY_NUM  
		WHERE A.POLICY_TYPE NOT IN (''ING'',''5'',''9'',''13'', ''15'')      
			AND (CURRENT_DATE - EXPIRATION_DATE) < 61
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_view_Fire.POLICY_NUM as POLICY_NUM,
SQ_view_Fire.MEMBER_NUM as MEMBER_NUM,
SQ_view_Fire.NAME_1 as NAME_1,
SQ_view_Fire.NAME_2 as NAME_2,
SQ_view_Fire.ADDRESS_1 as ADDRESS_1,
SQ_view_Fire.ADDRESS_2 as ADDRESS_2,
SQ_view_Fire.CITY as CITY,
SQ_view_Fire.STATE as STATE,
SQ_view_Fire.ZIP as ZIP,
SQ_view_Fire.POLICY_DESCRIPTION as POLICY_DESCRIPTION,
SQ_view_Fire.AGT_NUM as AGT_NUM,
SQ_view_Fire.POLICY_STATUS as POLICY_STATUS,
SQ_view_Fire.SC_NUM as SC_NUM,
SQ_view_Fire.POLICY_TYPE as POLICY_TYPE,
SQ_view_Fire.EXPIRATION_DATE as EXPIRATION_DATE,
SQ_view_Fire.TOTAL_POLS as TOTAL_POLS,
SQ_view_Fire.TOTAL_PREM as TOTAL_PREM,
SQ_view_Fire.TOTAL_LOB as TOTAL_LOB,
SQ_view_Fire.THE_STATE as THE_STATE,
SQ_view_Fire.source_record_id
FROM
SQ_view_Fire
);


-- Component AGENT_RECODES_SOURCE, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.AGENT_RECODES_SOURCE
(
POLICY_NUM,
MEMBER_NUM,
NAME_1,
NAME_2,
ADDRESS_1,
ADDRESS_2,
CITY,
STATE,
ZIP,
POLICY_DESCRIPTION,
AGT_NUM,
POLICY_STATUS,
SC_NUM,
POLICY_TYPE,
EXPIRATION_DATE,
TOTAL_POLS,
TOTAL_PREM,
TOTAL_LOB,
THE_STATE
)
SELECT
EXPTRANS.POLICY_NUM as POLICY_NUM,
EXPTRANS.MEMBER_NUM as MEMBER_NUM,
EXPTRANS.NAME_1 as NAME_1,
EXPTRANS.NAME_2 as NAME_2,
EXPTRANS.ADDRESS_1 as ADDRESS_1,
EXPTRANS.ADDRESS_2 as ADDRESS_2,
EXPTRANS.CITY as CITY,
EXPTRANS.STATE as STATE,
EXPTRANS.ZIP as ZIP,
EXPTRANS.POLICY_DESCRIPTION as POLICY_DESCRIPTION,
EXPTRANS.AGT_NUM as AGT_NUM,
EXPTRANS.POLICY_STATUS as POLICY_STATUS,
EXPTRANS.SC_NUM as SC_NUM,
EXPTRANS.POLICY_TYPE as POLICY_TYPE,
EXPTRANS.EXPIRATION_DATE as EXPIRATION_DATE,
EXPTRANS.TOTAL_POLS as TOTAL_POLS,
EXPTRANS.TOTAL_PREM as TOTAL_PREM,
EXPTRANS.TOTAL_LOB as TOTAL_LOB,
EXPTRANS.THE_STATE as THE_STATE
FROM
EXPTRANS;


-- Component AGENT_RECODES_SOURCE, Type Post SQL 
--Filling blank state with first 3 characters from City
UPDATE DB_T_STAG_MEMBXREF_PROD.AGENT_RECODES_SOURCE 
SET STATE = SUBSTR(city, LENGTH(TRIM(CITY))-2) WHERE STATE = '''';

--setting city and state for city with following characters
UPDATE DB_T_STAG_MEMBXREF_PROD.AGENT_RECODES_SOURCE 
SET CITY = SUBSTR(TRIM(CITY) ,1, LENGTH(TRIM(CITY))-3);--, 
--STATE = SUBSTRING(TRIM(CITY); --FROM CHARACTER_LENGTH(TRIM(CITY)) -1 FOR 2) 
--WHERE SUBSTRING(TRIM(CITY) 
--				FROM CHARACTER_LENGTH(TRIM(CITY)) -2 FOR 3
--				) IN ('' AL'', ''ALA'', '' GA'', '' MS'', '' AK'', '' AZ'', '' AR'',  '' CA'', '' CO'', '' CT'', '' DE'', '' FL'', '' HI'', 
--					'' ID'', '' IL'', '' IN'', '' IA'', '' KS'', '' KY'', '' LA'', '' ME'', '' MD'', '' MA'', '' MI'', '' MN'', '' MO'', '' MT'', 
--					'' NE'', '' NV'', '' NH'', '' NJ'', '' NM'', '' NY'', '' NC'', '' ND'', '' OH'', '' OK'', '' OR'', '' PA'', '' RI'', '' SC'', 
--					'' SD'', '' TN'', '' TX'', '' UT'', '' VT'', '' VA'', '' WA'', '' WV'', '' WI'', '' WY'')
--;


END; ';