-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_WRK_FS_CLM_INS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '  
DECLARE start_dttm TIMESTAMP;
end_dttm TIMESTAMP;
PRCS_ID INTEGER;
fs_date date;
BEGIN 
start_dttm := CURRENT_TIMESTAMP();
end_dttm := CURRENT_TIMESTAMP();
fs_date := current_date();
PRCS_ID := 1;  

-- PIPELINE START FOR 1

-- Component SQ_FS_CLM1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FS_CLM1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CAL_QTR_NUM,
$2 as CAL_YR_NUM,
$3 as CAT_CD,
$4 as CVGE_NAME,
$5 as ST_CD,
$6 as CNTY_NAME,
$7 as CAUS_OF_LOSS_CD,
$8 as PLCY_TYPE_DESC,
$9 as UNDRWRTG_CO_CD,
$10 as PD_CLM_CVGE_CNT,
$11 as OUTST_CLM_CVGE_CNT,
$12 as PD_LOSS_NET_RCVRY_AMT,
$13 as OUTST_RSERV_AMT,
$14 as CRTD_DTTM,
$15 as UPDTD_DTTM,
$16 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH  PRTY_ASSET_COVERAGES AS

(

SELECT  AGMT.AGMT_ID, AGMT.HOST_AGMT_NUM, PRTY_ASSET.PRTY_ASSET_ID, RATE_SYMB_CD  , f.INSRNC_CVGE_TYPE_CD,

CASE 

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f2.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f4.FEAT_NAME

END TERM_NAME, 

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.FEAT_ID

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.FEAT_ID

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.FEAT_ID

END COV_FEAT_ID,

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.FEAT_NAME

END COV_NAME, 

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.NK_SRC_KEY

END COV_PATTERNCODE, 

CASE WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f2.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f4.NK_SRC_KEY

END TERM_PATTERNCODE, 

CASE 

WHEN f.FEAT_SBTYPE_CD=''OPT'' AND f.FEAT_DTL_CD_NAME  IN (''Actual'', ''Replacement'') THEN f.FEAT_DTL_CD_NAME  

WHEN f.FEAT_SBTYPE_CD=''OPT'' AND f.FEAT_DTL_CD_NAME NOT IN (''Actual'', ''Replacement'') THEN CAST(f.FEAT_DTL_VAL AS DECIMAL(18,4))      

WHEN f.FEAT_SBTYPE_CD=''TERM'' AND LENGTH(AGMT_INSRD_ASSET_FEAT.AGMT_ASSET_FEAT_TXT)>0 THEN AGMT_INSRD_ASSET_FEAT.AGMT_ASSET_FEAT_TXT

WHEN f.FEAT_SBTYPE_CD=''TERM'' AND (LENGTH(AGMT_INSRD_ASSET_FEAT.AGMT_ASSET_FEAT_TXT) =0 OR AGMT_INSRD_ASSET_FEAT.AGMT_ASSET_FEAT_TXT IS NULL) THEN AGMT_INSRD_ASSET_FEAT.AGMT_ASSET_FEAT_AMT

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN  f.FEAT_DTL_CD_NAME

END VAL  





FROM DB_T_PROD_CORE.FEAT f

JOIN DB_T_PROD_CORE.AGMT_INSRD_ASSET_FEAT ON f.FEAT_ID = AGMT_INSRD_ASSET_FEAT.FEAT_ID
AND TO_DATE (AGMT_INSRD_ASSET_FEAT.TRANS_END_DTTM) = ''9999-12-31''
JOIN DB_T_PROD_CORE.AGMT ON AGMT_INSRD_ASSET_FEAT.AGMT_ID = AGMT.AGMT_ID
AND TO_DATE (AGMT.EDW_END_DTTM) = ''9999-12-31''
JOIN DB_T_PROD_CORE.PRTY_ASSET ON AGMT_INSRD_ASSET_FEAT.PRTY_ASSET_ID = PRTY_ASSET.PRTY_ASSET_ID
AND TO_DATE (PRTY_ASSET.EDW_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr1 ON f.FEAT_ID = fr1.RLTD_FEAT_ID
AND fr1.FEAT_RLTNSHP_TYPE_CD = ''COVT''
AND TO_DATE (fr1.TRANS_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT f1 ON fr1.FEAT_ID = f1.FEAT_ID
AND TO_DATE (f1.EDW_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr2 ON f.FEAT_ID = fr2.RLTD_FEAT_ID
AND fr2.FEAT_RLTNSHP_TYPE_CD = ''TERMOPT''
AND TO_DATE (fr2.TRANS_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT f2 ON fr2.FEAT_ID = f2.FEAT_ID
AND TO_DATE (f2.EDW_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr3 ON f.FEAT_ID = fr3.RLTD_FEAT_ID
AND fr3.FEAT_RLTNSHP_TYPE_CD = ''COVOPTT''
AND TO_DATE (fr3.TRANS_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT f3 ON fr3.FEAT_ID = f3.FEAT_ID
AND TO_DATE (f3.EDW_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr4 ON f.FEAT_ID = fr4.RLTD_FEAT_ID
AND fr4.FEAT_RLTNSHP_TYPE_CD = ''TERMPKG''
AND TO_DATE (fr4.TRANS_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT f4 ON fr4.FEAT_ID = f4.FEAT_ID
AND TO_DATE (f4.EDW_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr5 ON f.FEAT_ID = fr5.RLTD_FEAT_ID
AND fr5.FEAT_RLTNSHP_TYPE_CD = ''COVPKG''
AND TO_DATE (fr5.TRANS_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT f5 ON fr5.FEAT_ID = f5.FEAT_ID
AND TO_DATE (f5.EDW_END_DTTM) = ''9999-12-31''
WHERE f.FEAT_SBTYPE_CD IN (''TERM'', ''OPT'', ''PKG'')

/* AND          AGMT.modl_crtn_dttm = (SELECT           MAX(aa.modl_crtn_dttm)  FROM                DB_T_PROD_CORE.AGMT aa WHERE                    aa.host_agmt_num=AGMT.host_agmt_num) */
AND AGMT.AGMT_CUR_STS_CD=''BOUND''

AND CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.NK_SRC_KEY

END  NOT IN (''HOLI_SCHEDULEDPROPERTYDEDUCTIBLESITEM_ALFA'', ''HOSI_SCHEDULEDPROPERTYITEM_ALFA'') 



),

AGMT_COVERAGES AS

(

SELECT  AGMT.AGMT_ID, AGMT.HOST_AGMT_NUM,

CASE 

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f2.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f4.FEAT_NAME

END TERM_NAME, 

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.FEAT_ID

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.FEAT_ID

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.FEAT_ID

END COV_FEAT_ID, 

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.FEAT_NAME

END COV_NAME, 

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.NK_SRC_KEY

END COV_PATTERNCODE, 

CASE WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f2.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f4.NK_SRC_KEY

END TERM_PATTERNCODE, 

CASE 

WHEN f.FEAT_SBTYPE_CD=''OPT'' AND f.FEAT_DTL_CD_NAME  IN (''Actual'', ''Replacement'') THEN f.FEAT_DTL_CD_NAME  

WHEN f.FEAT_SBTYPE_CD=''OPT'' AND f.FEAT_DTL_CD_NAME NOT IN (''Actual'', ''Replacement'') THEN CAST(f.FEAT_DTL_VAL AS DECIMAL(18,4)) 

WHEN f.FEAT_SBTYPE_CD=''TERM'' AND LENGTH(AGMT_FEAT_TXT)>0 THEN AGMT_FEAT.AGMT_FEAT_TXT

WHEN f.FEAT_SBTYPE_CD=''TERM'' AND (LENGTH(AGMT_FEAT_TXT) =0 OR AGMT_FEAT_TXT IS NULL) THEN AGMT_FEAT.AGMT_FEAT_AMT

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN  f.FEAT_DTL_CD_NAME

END VAL

FROM DB_T_PROD_CORE.FEAT f        

JOIN DB_T_PROD_CORE.AGMT_FEAT ON f.FEAT_ID = AGMT_FEAT.FEAT_ID
AND TO_DATE (AGMT_FEAT.TRANS_END_DTTM) = ''9999-12-31''
JOIN DB_T_PROD_CORE.AGMT ON AGMT_FEAT.AGMT_ID = AGMT.AGMT_ID
AND TO_DATE (AGMT.EDW_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr1 ON f.FEAT_ID = fr1.RLTD_FEAT_ID
AND fr1.FEAT_RLTNSHP_TYPE_CD = ''COVT''
AND TO_DATE (fr1.TRANS_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT f1 ON fr1.FEAT_ID = f1.FEAT_ID
LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr2 ON f.FEAT_ID = fr2.RLTD_FEAT_ID
AND fr2.FEAT_RLTNSHP_TYPE_CD = ''TERMOPT''
AND TO_DATE (fr2.TRANS_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT f2 ON fr2.FEAT_ID = f2.FEAT_ID
LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr3 ON f.FEAT_ID = fr3.RLTD_FEAT_ID
AND fr3.FEAT_RLTNSHP_TYPE_CD = ''COVOPTT''
AND TO_DATE (fr3.TRANS_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT f3 ON fr3.FEAT_ID = f3.FEAT_ID
LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr4 ON f.FEAT_ID = fr4.RLTD_FEAT_ID
AND fr4.FEAT_RLTNSHP_TYPE_CD = ''TERMPKG''
AND TO_DATE (fr4.TRANS_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT f4 ON fr4.FEAT_ID = f4.FEAT_ID
LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr5 ON f.FEAT_ID = fr5.RLTD_FEAT_ID
AND fr5.FEAT_RLTNSHP_TYPE_CD = ''COVPKG''
AND TO_DATE (fr5.TRANS_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.FEAT f5 ON fr5.FEAT_ID=f5.FEAT_ID

WHERE f.FEAT_SBTYPE_CD IN (''TERM'', ''OPT'', ''PKG'')

AND f.FEAT_COVERABLE_TYPE_TXT IN (''PersonalAutoLine'', ''HomeownersLine_HOE'', ''HOLineSchCovItem_alfa'')

AND CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.NK_SRC_KEY

END  NOT IN (''HOLI_SCHEDULEDPROPERTYDEDUCTIBLESITEM_ALFA'', ''HOSI_SCHEDULEDPROPERTYITEM_ALFA'')



) ,

LOCATION_ADDRESS_PROPERTY  AS

(

SELECT PRTY_ASSET_LOCTR.PRTY_ASSET_ID, PRTY_ASSET_LOCTR.LOC_ID,PRTY_ASSET_LOCTR.PRTY_ASSET_LOCTR_ROLE_CD,CNTY.GEOGRCL_AREA_NAME COUNTY, 

STREET_ADDR.ADDR_LN_1_TXT PLCY_MAIL_ADDRESS_1,                                      PRTY_ASSET_LOCTR.FIRE_DEPT_ID  ,POSTL_CD.POSTL_CD_NUM   ZIP

                                                                                FROM DB_T_PROD_CORE.PRTY_ASSET_LOCTR

                                                                            JOIN DB_T_PROD_CORE.STREET_ADDR ON STREET_ADDR.STREET_ADDR_ID = PRTY_ASSET_LOCTR.LOC_ID
AND TO_DATE (STREET_ADDR.EDW_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.CNTY ON CNTY.CNTY_ID = STREET_ADDR.CNTY_ID
AND TO_DATE (CNTY.EDW_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.POSTL_CD ON POSTL_CD.POSTL_CD_ID = STREET_ADDR.POSTL_CD_ID
AND TO_DATE (POSTL_CD.EDW_END_DTTM) = ''9999-12-31''
WHERE
  PRTY_ASSET_LOCTR.PRTY_ASSET_LOCTR_ROLE_CD = ''RSKSTADRS''
  AND PRTY_ASSET_LOCTR.TRANS_END_DTTM = TO_TIMESTAMP_NTZ (''9999-12-31 23:59:59.999999'')

) ,



LOCATION_ADDRESS_AUTO  AS

(

SELECT PRTY_ASSET_LOCTR.PRTY_ASSET_ID, PRTY_ASSET_LOCTR.LOC_ID,PRTY_ASSET_LOCTR.PRTY_ASSET_LOCTR_ROLE_CD,CNTY.GEOGRCL_AREA_NAME COUNTY, 

STREET_ADDR.ADDR_LN_1_TXT PLCY_MAIL_ADDRESS_1, POSTL_CD.POSTL_CD_NUM   ZIP

                                                                                FROM DB_T_PROD_CORE.PRTY_ASSET_LOCTR

                                                                            JOIN DB_T_PROD_CORE.STREET_ADDR ON STREET_ADDR.STREET_ADDR_ID = PRTY_ASSET_LOCTR.LOC_ID
AND TO_DATE (STREET_ADDR.EDW_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.CNTY ON CNTY.CNTY_ID = STREET_ADDR.CNTY_ID
AND TO_DATE (CNTY.EDW_END_DTTM) = ''9999-12-31''
LEFT JOIN DB_T_PROD_CORE.POSTL_CD ON POSTL_CD.POSTL_CD_ID = STREET_ADDR.POSTL_CD_ID
AND TO_DATE (POSTL_CD.EDW_END_DTTM) = ''9999-12-31''
WHERE
  PRTY_ASSET_LOCTR.PRTY_ASSET_LOCTR_ROLE_CD = ''GARSTRTADDRSS''
  AND PRTY_ASSET_LOCTR.TRANS_END_DTTM = TO_TIMESTAMP_NTZ (''9999-12-31 23:59:59.999999'')


)



SELECT



QUARTER_OF_YEAR,

YEAR_OF_CALENDAR,

/* PRTCTN_CLAS_CD, */
CAT_CD,

CVGE_NAME,

COALESCE(STATE_NM,''UNK'') AS RISK_STATE,

COALESCE(CNTY_NM,''UNK'') AS RISK_CNTY,

CAUS_OF_LOSS_CD  AS LOSS_CAUSE_CD,

COALESCE(PLCY_TYPE_DESC,''UNK'') AS POLICY_TYPE,

/* RTG_TERR_CD, */
Underwriting_Company,

SUM(PD_CLM_CVGE_CNT) AS PD_CLM_CVGE_CNT,

SUM(OUTST_CLM_CVGE_CNT) AS OUTST_CLM_CVGE_CNT,

SUM(PD_LOSS_NET_RCVRY_AMT) AS PD_LOSS_NET_RCVRY_AMT,

SUM(OUTST_RSERV_AMT) AS OUTST_RSERV_AMT,

CRT_DTTM,

CRT_DTTM AS UPD_DTTM





FROM 

(SELECT DISTINCT 

CEXP.CLM_ID,

CEXP.CLM_EXPSR_ID,

COALESCE(EVV.SRC_TRANS_ID,''N/A'') AS CAT_CD,  

CASE WHEN FT.COMN_FEAT_NAME IS NOT NULL THEN FT.COMN_FEAT_NAME 

              ELSE ''UNK''  END  AS CVGE_NAME,

CASE WHEN RISK_LOCATION.COUNTY IS NOT NULL THEN  RISK_LOCATION.COUNTY ELSE   GARAGING_LOCATION.COUNTY  END AS CNTY_NM,

RISK_STATE.RISK_STATE_NAME AS STATE_NM,

CASE WHEN CLM_PERIL.PERIL_TYPE_CD in (''UNK'',''9999'')THEN NULL ELSE  CLM_PERIL.PERIL_TYPE_CD END AS CAUS_OF_LOSS_CD,

PRD.PROD_DESC AS PLCY_TYPE_DESC,

IO.PRTY_DESC as Underwriting_Company,

CASE WHEN (CASE WHEN CLMEXPSR.PAID_LOSS_NET_RECV  IS NULL THEN 0 ELSE CLMEXPSR.PAID_LOSS_NET_RECV  END  > 0)

AND  COALESCE(CEXP.CLM_ID,'''')||COALESCE(CEXP.CLMNT_PRTY_ID,'''')||COALESCE(CEXP.CVGE_FEAT_ID,'''') IS NOT NULL

THEN  1

ELSE 0 END

AS PD_CLM_CVGE_CNT,

CASE WHEN (CASE WHEN CLMEXPSR.OUT_RESERV   IS NULL THEN 0 ELSE CLMEXPSR.OUT_RESERV END >0)

AND COALESCE(CEXP.CLM_ID,'''')||COALESCE(CEXP.CLMNT_PRTY_ID,'''')||COALESCE(CEXP.CVGE_FEAT_ID,'''') IS NOT NULL

THEN 1

ELSE 0 END

AS OUTST_CLM_CVGE_CNT, 

CASE WHEN CLMEXPSR.PAID_LOSS_NET_RECV  IS NULL THEN 0 ELSE CLMEXPSR.PAID_LOSS_NET_RECV  END AS PD_LOSS_NET_RCVRY_AMT,

CASE WHEN CLMEXPSR.OUT_RESERV   IS NULL THEN 0 ELSE CLMEXPSR.OUT_RESERV  END AS OUTST_RSERV_AMT,

CURRENT_date as CRT_DTTM,

CAL.QUARTER_OF_YEAR,

CAL.YEAR_OF_CALENDAR

FROM 

DB_T_PROD_CORE.CLM_EXPSR CEXP 

LEFT OUTER JOIN DB_T_PROD_CORE.CLM_EXPSR_TRANS CEXPTRANS ON CEXP.CLM_EXPSR_ID=CEXPTRANS.CLM_EXPSR_ID

LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_CLM AC ON CEXP.CLM_ID=AC.CLM_ID AND AC.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER JOIN DB_T_PROD_CORE.CLM_EV CE ON CEXP.CLM_ID=CE.CLM_ID AND CE.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER  JOIN DB_T_PROD_CORE.EV EVV  ON EVV.EV_ID=CE.EV_ID AND EV_ACTVY_TYPE_CD=''INT''  AND   EV_SBTYPE_CD=''CATSTRPH''   AND EVV.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER  JOIN DB_T_PROD_CORE.AGMT_PROD AP ON AC.AGMT_ID=AP.AGMT_ID AND  AP.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER  JOIN DB_T_PROD_CORE.PROD PRD  ON PRD.PROD_ID=AP.PROD_ID AND PRD.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER JOIN DB_T_PROD_CORE.CLM_PERIL ON CLM_PERIL.CLM_ID=CEXP.CLM_ID AND CLM_PERIL.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER JOIN DB_T_PROD_CORE.PRTY_AGMT PA ON AC.AGMT_ID=PA.AGMT_ID AND PA.PRTY_AGMT_ROLE_CD=  ''CMP''  AND PA.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG IO  ON IO.INTRNL_ORG_PRTY_ID=PA.PRTY_ID AND IO.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

JOIN DB_T_PROD_CORE.AGMT A ON A.AGMT_ID=AC.AGMT_ID AND LGCY_PLCY_IND <> ''Y''/*  EIM-16759:Exclude Legacy DB_T_CORE_DM_PROD.Policy and Converted DB_T_STAG_DM_PROD.Claims */
LEFT OUTER JOIN DB_T_PROD_CORE.FEAT FT ON FT.FEAT_ID=CEXP.CVGE_FEAT_ID AND FT.EDW_END_DTTM =''9999-12-31 23:59:59.999999''



Left outer join



(

                                                            

                                                            

/* MAIN QUERY CONTAINING GRANULAR DATA */
                                                                                                                                            SELECT

                                                                                                                                            PRTY_ASSET_COVERAGES.AGMT_ID,

                                                                                                                                            PRTY_ASSET_COVERAGES.PRTY_ASSET_ID

                                                                                                                                            FROM PRTY_ASSET_COVERAGES   

                                                                                                                                            UNION ALL

                                                                                                                                            SELECT

                                                                                                                                            AGMT_COVERAGES.AGMT_ID,

                                                                                                                                            NULL AS PRTY_ASSET_ID

                                                                                                                                            FROM AGMT_COVERAGES   

/* END OF MAIN QUERY  */
                                                            

                                                            )   AS  TEMP

                                                            

On Temp.agmt_id=ac.agmt_id



                    LEFT JOIN (

                                                                                                                                                                SELECT AGMT_ASSET.AGMT_ID, MAX(AGMT_ASSET.PRTY_ASSET_ID ) AS PRTY_ASSET_ID

                                                                                                                                                                FROM      DB_T_PROD_CORE.AGMT_ASSET, DB_T_PROD_CORE.PRTY_ASSET 

                                                                                                                                                                WHERE  AGMT_ASSET.PRTY_ASSET_ID=PRTY_ASSET.PRTY_ASSET_ID

                                                                                                                                                                AND PRTY_ASSET.PRTY_ASSET_SBTYPE_CD IN (''RE'', ''REALDW'')   

                                                                                                                                                                AND PRTY_ASSET.PRTY_ASSET_CLASFCN_CD=''MAIN''         

                                                                                                                                                                AND AGMT_ASSET.TRANS_END_DTTM=CAST(''12/31/9999 23:59:59.999999''  AS TIMESTAMP(6) )

                                                                                                                                                                AND CAST(PRTY_ASSET.EDW_END_DTTM AS DATE )=''9999-12-31''

                                                                                                                                                                GROUP BY AGMT_ASSET.AGMT_ID                                                  )  ASSET                      ON             ASSET.AGMT_ID=TEMP.AGMT_ID 

LEFT JOIN LOCATION_ADDRESS_PROPERTY   AS RISK_LOCATION ON                    ASSET.PRTY_ASSET_ID=RISK_LOCATION.PRTY_ASSET_ID 

LEFT JOIN LOCATION_ADDRESS_AUTO  AS GARAGING_LOCATION ON  TEMP.PRTY_ASSET_ID = GARAGING_LOCATION.PRTY_ASSET_ID







LEFT OUTER JOIN 

(

SELECT AGMT_ID,GEOGRCL_AREA_NAME AS RISK_STATE_NAME  FROM DB_T_PROD_CORE.TERR 

                    LEFT JOIN DB_T_PROD_CORE.AGMT_LOCTR  ON TERR.TERR_ID=AGMT_LOCTR.LOC_ID 

                    WHERE CAST(TERR.EDW_END_DTTM as DATE )=''9999-12-31''

                    AND AGMT_LOCTR.AGMT_LOCTR_ROLE_TYPE_CD   IN (''AGTWINST'',''BSSTUNVRFDPLCY'')

                    AND CAST(AGMT_LOCTR.TRANS_END_DTTM as DATE )=''9999-12-31''

) RISK_STATE

ON AC.AGMT_id=RISK_STATE.AGMT_ID







INNER JOIN

(

SELECT 

CE.CLM_EXPSR_ID,

CE.CLM_ID,

FT.COMN_FEAT_NAME,

SUM(

CASE     WHEN (CET.CLM_EXPSR_TRANS_SBTYPE_CD = ''PYMNT'' 

                AND       CET.EXPSR_COST_TYPE_CD IN (''PDL'',''EXPNS'') 

                AND       CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'',''EXPNS'') 

                AND       CETL.LNITM_CTGY_TYPE_CD IN (  ''LOSS'', ''SALVEXP'',''SUBROEXP'',''DED'',''DEDRFND'',''FRMRDED'') ) THEN (CETL.CLM_EXPSR_LNITM_AMT) 

ELSE      0 

END       )

-

SUM( 

CASE     WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''  

                AND       CET.RCVRY_CTGY_TYPE_CD IN (''SUBRO'' , ''SALVAGE'')

                 AND       CET.EXPSR_COST_TYPE_CD IN (''PDL'') 

                AND       CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'') 

                AND       CETL.LNITM_CTGY_TYPE_CD IN ( ''SALVEXP'',''SUBROEXP'' )) THEN (CETL.CLM_EXPSR_LNITM_AMT) 

ELSE      0 

END       ) 

 - SUM( 

CASE     WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''  

                AND       CET.RCVRY_CTGY_TYPE_CD IN (''SUBRO'' , ''SALVAGE'')

                 AND       CET.EXPSR_COST_TYPE_CD IN (''EXPNS'') 

                AND       CET.EXPSR_COST_CTGY_TYPE_CD IN (''EXPNS'') 

                AND       CETL.LNITM_CTGY_TYPE_CD IN ( ''RCVRY'' ,''SUBROEXP'',''SALVEXP'' ))  THEN (CETL.CLM_EXPSR_LNITM_AMT) 

ELSE      0 

END       )

-

(SUM ( 

CASE	    

	WHEN	( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''  

                AND       CET.RCVRY_CTGY_TYPE_CD IN (''CRLOSS'',

		''SALVAGE'',''SUBRO'') 

                AND       CET.EXPSR_COST_TYPE_CD IN (''PDL'')   

                AND       CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')  

                AND       CETL.LNITM_CTGY_TYPE_CD IN (NULL,

		''RCVRY'' )) THEN (CETL.CLM_EXPSR_LNITM_AMT) 

ELSE	     0 

END	     )) as PAID_LOSS_NET_RECV



,(SUM ( 

CASE     WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RESRV''  

 AND       CET.EXPSR_COST_TYPE_CD=''PDL'' 

                AND       CET.EXPSR_COST_CTGY_TYPE_CD =''LOSS'' 



) THEN (CETL.CLM_EXPSR_LNITM_AMT) 

ELSE      0 END ) )

-

(SUM (

CASE     WHEN (CET.CLM_EXPSR_TRANS_SBTYPE_CD = ''PYMNT'' 

                AND       CET.EXPSR_COST_TYPE_CD IN (''PDL'')  

                AND       CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')

                AND       CETL.LNITM_CTGY_TYPE_CD IN (  ''LOSS'',''DED'',''DEDRFND'',''FRMRDED'')

                AND      CET.DOES_NOT_ERODE_RSERV_IND=''F'' 

                 )

                THEN (CETL.CLM_EXPSR_LNITM_AMT) 

 ELSE      0 END ) ) AS OUT_RESERV





FROM

DB_T_PROD_CORE.CLM_EXPSR_TRANS CET

INNER JOIN DB_T_PROD_CORE.CLM_EXPSR_TRANS_LNITM CETL ON  CET.CLM_EXPSR_TRANS_ID=CETL.CLM_EXPSR_TRANS_ID AND  CETL.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

INNER JOIN DB_T_PROD_CORE.CLM_EXPSR CE ON  CE.CLM_EXPSR_ID=CET.CLM_EXPSR_ID AND CE.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

INNER JOIN DB_T_PROD_CORE.CLM_STS CST ON CST.CLM_ID=CE.CLM_ID AND CST.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

INNER JOIN DB_T_PROD_CORE.FEAT FT ON FT.FEAT_ID=CE.CVGE_FEAT_ID AND FT.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

WHERE
  CET.CLM_EXPSR_TRANS_DTTM BETWEEN (
    SELECT
      DATE_TRUNC(''QUARTER'', CALENDAR_DATE)
    FROM
      EDW_DEV_DTI.DB_SP_PROD.CALENDAR
    WHERE
      CALENDAR_DATE = :FS_DATE
  )
  AND (
    SELECT
      DATEADD(
        ''QUARTER'',
        1,
        DATE_TRUNC(''QUARTER'', CALENDAR_DATE)
      ) - INTERVAL ''1 DAY''
    FROM
      EDW_DEV_DTI.DB_SP_PROD.CALENDAR    WHERE
      CALENDAR_DATE = :FS_DATE
  )

AND 

CET.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

GROUP BY 1,2,3

) CLMEXPSR ON CLMEXPSR.CLM_EXPSR_ID=CEXP.CLM_EXPSR_ID AND CLMEXPSR.CLM_ID=CEXP.CLM_ID



LEFT JOIN (
    SELECT
      QUARTER(CALENDAR_DATE) as quarter_of_year,
      YEAR(CALENDAR_DATE) as year_of_calendar
    FROM
      EDW_DEV_DTI.DB_SP_PROD.CALENDAR
    WHERE
      CALENDAR_DATE = :FS_DATE
  ) cal

on 1=1



Where

CEXP.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

/* GROUP BY 1,2,3,4,5,6,7,8,9,10,11,14,15,16,17,18,19,20 */
) TEMP 

WHERE 

TEMP.PD_CLM_CVGE_CNT > 0 OR  

TEMP.OUTST_CLM_CVGE_CNT  > 0

GROUP BY 1,2,3,4,5,6,7,8,9,14,15
) SRC
)
);


-- Component exp_pass_to_tgt1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_to_tgt1 AS
(
SELECT
SQ_FS_CLM1.CAL_YR_NUM as CAL_YR_NUM,
SQ_FS_CLM1.CAL_QTR_NUM as CAL_QTR_NUM,
SQ_FS_CLM1.source_record_id
FROM
SQ_FS_CLM1
);


-- Component LKP_DELETE, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_DELETE AS
(
SELECT
LKP.CAL_YR_NUM,
LKP.CAL_QTR_NUM,
exp_pass_to_tgt1.CAL_YR_NUM as IN_CAL_YR_NUM,
exp_pass_to_tgt1.CAL_QTR_NUM as IN_CAL_QTR_NUM,
exp_pass_to_tgt1.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pass_to_tgt1.source_record_id ORDER BY LKP.CAL_YR_NUM asc,LKP.CAL_QTR_NUM asc) RNK
FROM
exp_pass_to_tgt1
LEFT JOIN (
SELECT
CAL_YR_NUM,
CAL_QTR_NUM
FROM DB_T_PROD_WRK.FS_CLM
) LKP ON LKP.CAL_YR_NUM = exp_pass_to_tgt1.CAL_YR_NUM AND LKP.CAL_QTR_NUM = exp_pass_to_tgt1.CAL_QTR_NUM
QUALIFY RNK = 1
);


-- Component exp_pass_to_tgt2, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_to_tgt2 AS
(
SELECT
LKP_DELETE.CAL_YR_NUM as CAL_YR_NUM,
LKP_DELETE.CAL_QTR_NUM as CAL_QTR_NUM,
NULL as ST_CD,
NULL as UNDRWRTG_CO_CD,
NULL as PRTCTN_CLAS_CD,
NULL as PLCY_TYPE_DESC,
NULL as CAT_CD,
NULL as CAUS_OF_LOSS_CD,
NULL as RTG_TERR_CD,
NULL as CNTY_NAME,
NULL as CVGE_NAME,
NULL as PD_CLM_CVGE_CNT,
NULL as OUTST_CLM_CVGE_CNT,
NULL as PD_LOSS_NET_RCVRY_AMT,
NULL as OUTST_RSERV_AMT,
NULL as CRTD_DTTM,
NULL as UPDTD_DTTM,
LKP_DELETE.IN_CAL_YR_NUM as IN_CAL_YR_NUM,
LKP_DELETE.IN_CAL_QTR_NUM as IN_CAL_QTR_NUM,
CASE WHEN LKP_DELETE.CAL_YR_NUM IS NOT NULL and LKP_DELETE.CAL_QTR_NUM IS NOT NULL THEN ''DEL'' ELSE '''' END as FLAG_DELETE,
LKP_DELETE.source_record_id
FROM
LKP_DELETE
);


-- Component delete_filter, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE delete_filter AS
(
SELECT
exp_pass_to_tgt2.CAL_YR_NUM as CAL_YR_NUM,
exp_pass_to_tgt2.CAL_QTR_NUM as CAL_QTR_NUM,
exp_pass_to_tgt2.ST_CD as ST_CD,
exp_pass_to_tgt2.UNDRWRTG_CO_CD as UNDRWRTG_CO_CD,
exp_pass_to_tgt2.PRTCTN_CLAS_CD as PRTCTN_CLAS_CD,
exp_pass_to_tgt2.PLCY_TYPE_DESC as PLCY_TYPE_DESC,
exp_pass_to_tgt2.CAT_CD as CAT_CD,
exp_pass_to_tgt2.CAUS_OF_LOSS_CD as CAUS_OF_LOSS_CD,
exp_pass_to_tgt2.RTG_TERR_CD as RTG_TERR_CD,
exp_pass_to_tgt2.CNTY_NAME as CNTY_NAME,
exp_pass_to_tgt2.CVGE_NAME as CVGE_NAME,
exp_pass_to_tgt2.PD_CLM_CVGE_CNT as PD_CLM_CVGE_CNT,
exp_pass_to_tgt2.OUTST_CLM_CVGE_CNT as OUTST_CLM_CVGE_CNT,
exp_pass_to_tgt2.PD_LOSS_NET_RCVRY_AMT as PD_LOSS_NET_RCVRY_AMT,
exp_pass_to_tgt2.OUTST_RSERV_AMT as OUTST_RSERV_AMT,
exp_pass_to_tgt2.CRTD_DTTM as CRTD_DTTM,
exp_pass_to_tgt2.UPDTD_DTTM as UPDTD_DTTM,
exp_pass_to_tgt2.IN_CAL_YR_NUM as IN_CAL_YR_NUM,
exp_pass_to_tgt2.IN_CAL_QTR_NUM as IN_CAL_QTR_NUM,
exp_pass_to_tgt2.FLAG_DELETE as FLAG_DELETE,
exp_pass_to_tgt2.source_record_id
FROM
exp_pass_to_tgt2
WHERE exp_pass_to_tgt2.FLAG_DELETE = ''DEL''
);


-- Component delete_target, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE delete_target AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
delete_filter.CAL_YR_NUM as CAL_YR_NUM,
delete_filter.CAL_QTR_NUM as CAL_QTR_NUM,
delete_filter.ST_CD as ST_CD,
delete_filter.UNDRWRTG_CO_CD as UNDRWRTG_CO_CD,
delete_filter.PRTCTN_CLAS_CD as PRTCTN_CLAS_CD,
delete_filter.PLCY_TYPE_DESC as PLCY_TYPE_DESC,
delete_filter.CAT_CD as CAT_CD,
delete_filter.CAUS_OF_LOSS_CD as CAUS_OF_LOSS_CD,
delete_filter.RTG_TERR_CD as RTG_TERR_CD,
delete_filter.CNTY_NAME as CNTY_NAME,
delete_filter.CVGE_NAME as CVGE_NAME,
delete_filter.PD_CLM_CVGE_CNT as PD_CLM_CVGE_CNT,
delete_filter.OUTST_CLM_CVGE_CNT as OUTST_CLM_CVGE_CNT,
delete_filter.PD_LOSS_NET_RCVRY_AMT as PD_LOSS_NET_RCVRY_AMT,
delete_filter.OUTST_RSERV_AMT as OUTST_RSERV_AMT,
delete_filter.CRTD_DTTM as CRTD_DTTM,
delete_filter.UPDTD_DTTM as UPDTD_DTTM,
delete_filter.IN_CAL_YR_NUM as IN_CAL_YR_NUM,
delete_filter.IN_CAL_QTR_NUM as IN_CAL_QTR_NUM,
2 as UPDATE_STRATEGY_ACTION
FROM
delete_filter
);


-- Component tgt_FS_CLM_delete, Type TARGET 

/* Perform Deletes */
DELETE FROM DB_T_PROD_WRK.FS_CLM
WHERE EXISTS (SELECT 1 FROM delete_target WHERE UPDATE_STRATEGY_ACTION = 2 AND FS_CLM.CAL_YR_NUM = delete_target.CAL_YR_NUM AND FS_CLM.CAL_QTR_NUM = delete_target.CAL_QTR_NUM)
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_FS_CLM, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FS_CLM AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CAL_QTR_NUM,
$2 as CAL_YR_NUM,
$3 as CAT_CD,
$4 as CVGE_NAME,
$5 as ST_CD,
$6 as CNTY_NAME,
$7 as CAUS_OF_LOSS_CD,
$8 as PLCY_TYPE_DESC,
$9 as UNDRWRTG_CO_CD,
$10 as PD_CLM_CVGE_CNT,
$11 as OUTST_CLM_CVGE_CNT,
$12 as PD_LOSS_NET_RCVRY_AMT,
$13 as OUTST_RSERV_AMT,
$14 as CRTD_DTTM,
$15 as UPDTD_DTTM,
$16 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH  PRTY_ASSET_COVERAGES AS

(

SELECT  AGMT.AGMT_ID, AGMT.HOST_AGMT_NUM, PRTY_ASSET.PRTY_ASSET_ID, RATE_SYMB_CD  , f.INSRNC_CVGE_TYPE_CD,

CASE 

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f2.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f4.FEAT_NAME

END TERM_NAME, 

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.FEAT_ID

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.FEAT_ID

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.FEAT_ID

END COV_FEAT_ID,

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.FEAT_NAME

END COV_NAME, 

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.NK_SRC_KEY

END COV_PATTERNCODE, 

CASE WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f2.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f4.NK_SRC_KEY

END TERM_PATTERNCODE, 

CASE 

WHEN f.FEAT_SBTYPE_CD=''OPT'' AND f.FEAT_DTL_CD_NAME  IN (''Actual'', ''Replacement'') THEN f.FEAT_DTL_CD_NAME  

WHEN f.FEAT_SBTYPE_CD=''OPT'' AND f.FEAT_DTL_CD_NAME NOT IN (''Actual'', ''Replacement'') THEN CAST(f.FEAT_DTL_VAL AS DECIMAL(18,4))      

WHEN f.FEAT_SBTYPE_CD=''TERM'' AND LENGTH(AGMT_INSRD_ASSET_FEAT.AGMT_ASSET_FEAT_TXT)>0 THEN AGMT_INSRD_ASSET_FEAT.AGMT_ASSET_FEAT_TXT

WHEN f.FEAT_SBTYPE_CD=''TERM'' AND (LENGTH(AGMT_INSRD_ASSET_FEAT.AGMT_ASSET_FEAT_TXT) =0 OR AGMT_INSRD_ASSET_FEAT.AGMT_ASSET_FEAT_TXT IS NULL) THEN AGMT_INSRD_ASSET_FEAT.AGMT_ASSET_FEAT_AMT

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN  f.FEAT_DTL_CD_NAME

END VAL  





FROM DB_T_PROD_CORE.FEAT f

JOIN DB_T_PROD_CORE.AGMT_INSRD_ASSET_FEAT ON f.FEAT_ID=AGMT_INSRD_ASSET_FEAT.FEAT_ID  AND                    CAST(AGMT_INSRD_ASSET_FEAT.TRANS_END_DTTM AS DATE )=''9999-12-31''  

JOIN DB_T_PROD_CORE.AGMT ON AGMT_INSRD_ASSET_FEAT.AGMT_ID=AGMT.AGMT_ID AND                    CAST(AGMT.EDW_END_DTTM AS DATE ) = ''9999-12-31'' 

JOIN  DB_T_PROD_CORE.PRTY_ASSET ON AGMT_INSRD_ASSET_FEAT.PRTY_ASSET_ID=PRTY_ASSET.PRTY_ASSET_ID AND                    CAST(PRTY_ASSET.EDW_END_DTTM AS DATE ) = ''9999-12-31'' 

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr1 ON f.FEAT_ID=fr1.RLTD_FEAT_ID AND   fr1.FEAT_RLTNSHP_TYPE_CD =''COVT''     AND CAST( fr1.TRANS_END_DTTM AS DATE ) = ''9999-12-31''        

LEFT JOIN DB_T_PROD_CORE.FEAT f1 ON fr1.FEAT_ID=f1.FEAT_ID   AND       CAST(f1.EDW_END_DTTM AS DATE ) = ''9999-12-31''               

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr2 ON f.FEAT_ID=fr2.RLTD_FEAT_ID AND   fr2.FEAT_RLTNSHP_TYPE_CD =''TERMOPT''     AND CAST( fr2.TRANS_END_DTTM AS DATE ) = ''9999-12-31''  

LEFT JOIN DB_T_PROD_CORE.FEAT f2 ON fr2.FEAT_ID=f2.FEAT_ID  AND        CAST(f2.EDW_END_DTTM AS DATE ) = ''9999-12-31''   

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr3 ON f.FEAT_ID=fr3.RLTD_FEAT_ID AND   fr3.FEAT_RLTNSHP_TYPE_CD =''COVOPTT''    AND CAST( fr3.TRANS_END_DTTM  AS DATE ) = ''9999-12-31'' 

LEFT JOIN DB_T_PROD_CORE.FEAT f3 ON fr3.FEAT_ID=f3.FEAT_ID  AND        CAST(f3.EDW_END_DTTM AS DATE ) = ''9999-12-31''   

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr4 ON f.FEAT_ID=fr4.RLTD_FEAT_ID AND   fr4.FEAT_RLTNSHP_TYPE_CD =''TERMPKG'' AND CAST( fr4.TRANS_END_DTTM  AS DATE ) = ''9999-12-31'' 

LEFT JOIN DB_T_PROD_CORE.FEAT f4 ON fr4.FEAT_ID=f4.FEAT_ID  AND        CAST(f4.EDW_END_DTTM AS DATE ) = ''9999-12-31''   

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr5 ON f.FEAT_ID=fr5.RLTD_FEAT_ID AND   fr5.FEAT_RLTNSHP_TYPE_CD =''COVPKG''  AND CAST( fr5.TRANS_END_DTTM  AS DATE ) = ''9999-12-31'' 

LEFT JOIN DB_T_PROD_CORE.FEAT f5 ON fr5.FEAT_ID=f5.FEAT_ID  AND        CAST(f5.EDW_END_DTTM AS DATE ) = ''9999-12-31''  

WHERE f.FEAT_SBTYPE_CD IN (''TERM'', ''OPT'', ''PKG'')

/* AND          AGMT.modl_crtn_dttm = (SELECT           MAX(aa.modl_crtn_dttm)  FROM                DB_T_PROD_CORE.AGMT aa WHERE                    aa.host_agmt_num=AGMT.host_agmt_num) */
AND AGMT.AGMT_CUR_STS_CD=''BOUND''

AND CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.NK_SRC_KEY

END  NOT IN (''HOLI_SCHEDULEDPROPERTYDEDUCTIBLESITEM_ALFA'', ''HOSI_SCHEDULEDPROPERTYITEM_ALFA'') 



),

AGMT_COVERAGES AS

(

SELECT  AGMT.AGMT_ID, AGMT.HOST_AGMT_NUM,

CASE 

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f2.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f4.FEAT_NAME

END TERM_NAME, 

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.FEAT_ID

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.FEAT_ID

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.FEAT_ID

END COV_FEAT_ID, 

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.FEAT_NAME

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.FEAT_NAME

END COV_NAME, 

CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.NK_SRC_KEY

END COV_PATTERNCODE, 

CASE WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f2.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f4.NK_SRC_KEY

END TERM_PATTERNCODE, 

CASE 

WHEN f.FEAT_SBTYPE_CD=''OPT'' AND f.FEAT_DTL_CD_NAME  IN (''Actual'', ''Replacement'') THEN f.FEAT_DTL_CD_NAME  

WHEN f.FEAT_SBTYPE_CD=''OPT'' AND f.FEAT_DTL_CD_NAME NOT IN (''Actual'', ''Replacement'') THEN CAST(f.FEAT_DTL_VAL AS DECIMAL(18,4)) 

WHEN f.FEAT_SBTYPE_CD=''TERM'' AND LENGTH(AGMT_FEAT_TXT)>0 THEN AGMT_FEAT.AGMT_FEAT_TXT

WHEN f.FEAT_SBTYPE_CD=''TERM'' AND (LENGTH(AGMT_FEAT_TXT) =0 OR AGMT_FEAT_TXT IS NULL) THEN AGMT_FEAT.AGMT_FEAT_AMT

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN  f.FEAT_DTL_CD_NAME

END VAL

FROM DB_T_PROD_CORE.FEAT f        

JOIN DB_T_PROD_CORE.AGMT_FEAT ON f.FEAT_ID=AGMT_FEAT.FEAT_ID  AND CAST(AGMT_FEAT.TRANS_END_DTTM  AS DATE ) = ''9999-12-31'' 

JOIN DB_T_PROD_CORE.AGMT ON AGMT_FEAT.AGMT_ID=AGMT.AGMT_ID AND CAST(AGMT.EDW_END_DTTM AS DATE ) = ''9999-12-31'' 

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr1 ON f.FEAT_ID=fr1.RLTD_FEAT_ID AND   fr1.FEAT_RLTNSHP_TYPE_CD =''COVT'' AND CAST(fr1.TRANS_END_DTTM AS DATE ) = ''9999-12-31'' 

LEFT JOIN DB_T_PROD_CORE.FEAT f1 ON fr1.FEAT_ID=f1.FEAT_ID

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr2 ON f.FEAT_ID=fr2.RLTD_FEAT_ID AND   fr2.FEAT_RLTNSHP_TYPE_CD =''TERMOPT''  AND CAST(fr2.TRANS_END_DTTM AS DATE ) = ''9999-12-31'' 

LEFT JOIN DB_T_PROD_CORE.FEAT f2 ON fr2.FEAT_ID=f2.FEAT_ID

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr3 ON f.FEAT_ID=fr3.RLTD_FEAT_ID AND   fr3.FEAT_RLTNSHP_TYPE_CD =''COVOPTT''  AND CAST( fr3.TRANS_END_DTTM AS DATE ) = ''9999-12-31'' 

LEFT JOIN DB_T_PROD_CORE.FEAT f3 ON fr3.FEAT_ID=f3.FEAT_ID

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr4 ON f.FEAT_ID=fr4.RLTD_FEAT_ID AND   fr4.FEAT_RLTNSHP_TYPE_CD =''TERMPKG''  AND  CAST( fr4.TRANS_END_DTTM AS DATE ) = ''9999-12-31'' 

LEFT JOIN DB_T_PROD_CORE.FEAT f4 ON fr4.FEAT_ID=f4.FEAT_ID

LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD fr5 ON f.FEAT_ID=fr5.RLTD_FEAT_ID AND   fr5.FEAT_RLTNSHP_TYPE_CD =''COVPKG''  AND CAST(  fr5.TRANS_END_DTTM AS DATE ) = ''9999-12-31'' 

LEFT JOIN DB_T_PROD_CORE.FEAT f5 ON fr5.FEAT_ID=f5.FEAT_ID

WHERE f.FEAT_SBTYPE_CD IN (''TERM'', ''OPT'', ''PKG'')

AND f.FEAT_COVERABLE_TYPE_TXT IN (''PersonalAutoLine'', ''HomeownersLine_HOE'', ''HOLineSchCovItem_alfa'')

AND CASE WHEN f.FEAT_SBTYPE_CD=''TERM'' THEN f1.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''OPT'' THEN f3.NK_SRC_KEY

WHEN f.FEAT_SBTYPE_CD=''PKG'' THEN f5.NK_SRC_KEY

END  NOT IN (''HOLI_SCHEDULEDPROPERTYDEDUCTIBLESITEM_ALFA'', ''HOSI_SCHEDULEDPROPERTYITEM_ALFA'')



) ,

LOCATION_ADDRESS_PROPERTY  AS

(

SELECT PRTY_ASSET_LOCTR.PRTY_ASSET_ID, PRTY_ASSET_LOCTR.LOC_ID,PRTY_ASSET_LOCTR.PRTY_ASSET_LOCTR_ROLE_CD,CNTY.GEOGRCL_AREA_NAME COUNTY, 

STREET_ADDR.ADDR_LN_1_TXT PLCY_MAIL_ADDRESS_1,                                      PRTY_ASSET_LOCTR.FIRE_DEPT_ID  ,POSTL_CD.POSTL_CD_NUM   ZIP

                                                                                FROM DB_T_PROD_CORE.PRTY_ASSET_LOCTR

                                                                                JOIN DB_T_PROD_CORE.STREET_ADDR ON STREET_ADDR.STREET_ADDR_ID=PRTY_ASSET_LOCTR.LOC_ID AND CAST(STREET_ADDR.EDW_END_DTTM AS DATE ) = ''9999-12-31'' 

                                                                                LEFT JOIN DB_T_PROD_CORE.CNTY ON CNTY.CNTY_ID=STREET_ADDR.CNTY_ID AND CAST(CNTY.EDW_END_DTTM AS DATE ) = ''9999-12-31'' 

                                                                                LEFT JOIN DB_T_PROD_CORE.POSTL_CD ON POSTL_CD.POSTL_CD_ID=STREET_ADDR.POSTL_CD_ID AND CAST(POSTL_CD.EDW_END_DTTM AS DATE ) = ''9999-12-31'' 

                                                                                WHERE  PRTY_ASSET_LOCTR.PRTY_ASSET_LOCTR_ROLE_CD=''RSKSTADRS''

                    AND PRTY_ASSET_LOCTR.TRANS_END_DTTM =CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP) 



) ,



LOCATION_ADDRESS_AUTO  AS

(

SELECT PRTY_ASSET_LOCTR.PRTY_ASSET_ID, PRTY_ASSET_LOCTR.LOC_ID,PRTY_ASSET_LOCTR.PRTY_ASSET_LOCTR_ROLE_CD,CNTY.GEOGRCL_AREA_NAME COUNTY, 

STREET_ADDR.ADDR_LN_1_TXT PLCY_MAIL_ADDRESS_1, POSTL_CD.POSTL_CD_NUM   ZIP

                                                                                FROM DB_T_PROD_CORE.PRTY_ASSET_LOCTR

                                                                                JOIN DB_T_PROD_CORE.STREET_ADDR ON STREET_ADDR.STREET_ADDR_ID=PRTY_ASSET_LOCTR.LOC_ID AND CAST(STREET_ADDR.EDW_END_DTTM AS DATE ) = ''9999-12-31'' 

                                                                                LEFT JOIN DB_T_PROD_CORE.CNTY ON CNTY.CNTY_ID=STREET_ADDR.CNTY_ID AND CAST(CNTY.EDW_END_DTTM AS DATE ) = ''9999-12-31'' 

                                                                                LEFT JOIN DB_T_PROD_CORE.POSTL_CD ON POSTL_CD.POSTL_CD_ID=STREET_ADDR.POSTL_CD_ID AND CAST(POSTL_CD.EDW_END_DTTM AS DATE ) = ''9999-12-31'' 

                                                                                WHERE  PRTY_ASSET_LOCTR.PRTY_ASSET_LOCTR_ROLE_CD=''GARSTRTADDRSS''

                    AND PRTY_ASSET_LOCTR.TRANS_END_DTTM =CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP)     



)



SELECT



QUARTER_OF_YEAR,

YEAR_OF_CALENDAR,

/* PRTCTN_CLAS_CD, */
CAT_CD,

CVGE_NAME,

COALESCE(STATE_NM,''UNK'') AS RISK_STATE,

COALESCE(CNTY_NM,''UNK'') AS RISK_CNTY,

CAUS_OF_LOSS_CD  AS LOSS_CAUSE_CD,

COALESCE(PLCY_TYPE_DESC,''UNK'') AS POLICY_TYPE,

/* RTG_TERR_CD, */
Underwriting_Company,

SUM(PD_CLM_CVGE_CNT) AS PD_CLM_CVGE_CNT,

SUM(OUTST_CLM_CVGE_CNT) AS OUTST_CLM_CVGE_CNT,

SUM(PD_LOSS_NET_RCVRY_AMT) AS PD_LOSS_NET_RCVRY_AMT,

SUM(OUTST_RSERV_AMT) AS OUTST_RSERV_AMT,

CRT_DTTM,

CRT_DTTM AS UPD_DTTM





FROM 

(SELECT DISTINCT 

CEXP.CLM_ID,

CEXP.CLM_EXPSR_ID,

COALESCE(EVV.SRC_TRANS_ID,''N/A'') AS CAT_CD,  

CASE WHEN FT.COMN_FEAT_NAME IS NOT NULL THEN FT.COMN_FEAT_NAME 

              ELSE ''UNK''  END  AS CVGE_NAME,

CASE WHEN RISK_LOCATION.COUNTY IS NOT NULL THEN  RISK_LOCATION.COUNTY ELSE   GARAGING_LOCATION.COUNTY  END AS CNTY_NM,

RISK_STATE.RISK_STATE_NAME AS STATE_NM,

CASE WHEN CLM_PERIL.PERIL_TYPE_CD in (''UNK'',''9999'')THEN NULL ELSE  CLM_PERIL.PERIL_TYPE_CD END AS CAUS_OF_LOSS_CD,

PRD.PROD_DESC AS PLCY_TYPE_DESC,

IO.PRTY_DESC as Underwriting_Company,

CASE WHEN (CASE WHEN CLMEXPSR.PAID_LOSS_NET_RECV  IS NULL THEN 0 ELSE CLMEXPSR.PAID_LOSS_NET_RECV  END  > 0)

AND  COALESCE(CEXP.CLM_ID,'''')||COALESCE(CEXP.CLMNT_PRTY_ID,'''')||COALESCE(CEXP.CVGE_FEAT_ID,'''') IS NOT NULL

THEN  1

ELSE 0 END

AS PD_CLM_CVGE_CNT,

CASE WHEN (CASE WHEN CLMEXPSR.OUT_RESERV   IS NULL THEN 0 ELSE CLMEXPSR.OUT_RESERV END >0)

AND COALESCE(CEXP.CLM_ID,'''')||COALESCE(CEXP.CLMNT_PRTY_ID,'''')||COALESCE(CEXP.CVGE_FEAT_ID,'''') IS NOT NULL

THEN 1

ELSE 0 END

AS OUTST_CLM_CVGE_CNT, 

CASE WHEN CLMEXPSR.PAID_LOSS_NET_RECV  IS NULL THEN 0 ELSE CLMEXPSR.PAID_LOSS_NET_RECV  END AS PD_LOSS_NET_RCVRY_AMT,

CASE WHEN CLMEXPSR.OUT_RESERV   IS NULL THEN 0 ELSE CLMEXPSR.OUT_RESERV  END AS OUTST_RSERV_AMT,

CURRENT_date as CRT_DTTM,

CAL.QUARTER_OF_YEAR,

CAL.YEAR_OF_CALENDAR

FROM 

DB_T_PROD_CORE.CLM_EXPSR CEXP 

LEFT OUTER JOIN DB_T_PROD_CORE.CLM_EXPSR_TRANS CEXPTRANS ON CEXP.CLM_EXPSR_ID=CEXPTRANS.CLM_EXPSR_ID

LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_CLM AC ON CEXP.CLM_ID=AC.CLM_ID AND AC.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER JOIN DB_T_PROD_CORE.CLM_EV CE ON CEXP.CLM_ID=CE.CLM_ID AND CE.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER  JOIN DB_T_PROD_CORE.EV EVV  ON EVV.EV_ID=CE.EV_ID AND EV_ACTVY_TYPE_CD=''INT''  AND   EV_SBTYPE_CD=''CATSTRPH''   AND EVV.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER  JOIN DB_T_PROD_CORE.AGMT_PROD AP ON AC.AGMT_ID=AP.AGMT_ID AND  AP.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER  JOIN DB_T_PROD_CORE.PROD PRD  ON PRD.PROD_ID=AP.PROD_ID AND PRD.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER JOIN DB_T_PROD_CORE.CLM_PERIL ON CLM_PERIL.CLM_ID=CEXP.CLM_ID AND CLM_PERIL.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER JOIN DB_T_PROD_CORE.PRTY_AGMT PA ON AC.AGMT_ID=PA.AGMT_ID AND PA.PRTY_AGMT_ROLE_CD=  ''CMP''  AND PA.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG IO  ON IO.INTRNL_ORG_PRTY_ID=PA.PRTY_ID AND IO.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

JOIN DB_T_PROD_CORE.AGMT A ON A.AGMT_ID=AC.AGMT_ID AND LGCY_PLCY_IND <> ''Y''/*  EIM-16759:Exclude Legacy DB_T_CORE_DM_PROD.Policy and Converted DB_T_STAG_DM_PROD.Claims */
LEFT OUTER JOIN DB_T_PROD_CORE.FEAT FT ON FT.FEAT_ID=CEXP.CVGE_FEAT_ID AND FT.EDW_END_DTTM =''9999-12-31 23:59:59.999999''



Left outer join



(

                                                            

                                                            

/* MAIN QUERY CONTAINING GRANULAR DATA */
                                                                                                                                            SELECT

                                                                                                                                            PRTY_ASSET_COVERAGES.AGMT_ID,

                                                                                                                                            PRTY_ASSET_COVERAGES.PRTY_ASSET_ID

                                                                                                                                            FROM PRTY_ASSET_COVERAGES   

                                                                                                                                            UNION ALL

                                                                                                                                            SELECT

                                                                                                                                            AGMT_COVERAGES.AGMT_ID,

                                                                                                                                            NULL AS PRTY_ASSET_ID

                                                                                                                                            FROM AGMT_COVERAGES   

/* END OF MAIN QUERY  */
                                                            

                                                            )   AS  TEMP

                                                            

On Temp.agmt_id=ac.agmt_id



                    LEFT JOIN (

                                                                                                                                                                SELECT AGMT_ASSET.AGMT_ID, MAX(AGMT_ASSET.PRTY_ASSET_ID ) AS PRTY_ASSET_ID

                                                                                                                                                                FROM      DB_T_PROD_CORE.AGMT_ASSET, DB_T_PROD_CORE.PRTY_ASSET 

                                                                                                                                                                WHERE  AGMT_ASSET.PRTY_ASSET_ID=PRTY_ASSET.PRTY_ASSET_ID

                                                                                                                                                                AND PRTY_ASSET.PRTY_ASSET_SBTYPE_CD IN (''RE'', ''REALDW'')   

                                                                                                                                                                AND PRTY_ASSET.PRTY_ASSET_CLASFCN_CD=''MAIN''         

                                                                                                                                                                AND AGMT_ASSET.TRANS_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP)

                                                                                                                                                                AND CAST(PRTY_ASSET.EDW_END_DTTM AS DATE ) = ''9999-12-31'' 

                                                                                                                                                                GROUP BY AGMT_ASSET.AGMT_ID                                                  )  ASSET                      ON             ASSET.AGMT_ID=TEMP.AGMT_ID 

LEFT JOIN LOCATION_ADDRESS_PROPERTY   AS RISK_LOCATION ON                    ASSET.PRTY_ASSET_ID=RISK_LOCATION.PRTY_ASSET_ID 

LEFT JOIN LOCATION_ADDRESS_AUTO  AS GARAGING_LOCATION ON  TEMP.PRTY_ASSET_ID = GARAGING_LOCATION.PRTY_ASSET_ID







LEFT OUTER JOIN 

(

SELECT AGMT_ID,GEOGRCL_AREA_NAME AS RISK_STATE_NAME  FROM DB_T_PROD_CORE.TERR 

                    LEFT JOIN DB_T_PROD_CORE.AGMT_LOCTR  ON TERR.TERR_ID=AGMT_LOCTR.LOC_ID 

                    WHERE CAST(TERR.EDW_END_DTTM AS DATE ) = ''9999-12-31'' 

                    AND AGMT_LOCTR.AGMT_LOCTR_ROLE_TYPE_CD   IN (''AGTWINST'',''BSSTUNVRFDPLCY'')

                    AND CAST(AGMT_LOCTR.TRANS_END_DTTM AS DATE ) = ''9999-12-31'' 

) RISK_STATE

ON AC.AGMT_id=RISK_STATE.AGMT_ID







INNER JOIN

(

SELECT 

CE.CLM_EXPSR_ID,

CE.CLM_ID,

FT.COMN_FEAT_NAME,

SUM(

CASE     WHEN (CET.CLM_EXPSR_TRANS_SBTYPE_CD = ''PYMNT'' 

                AND       CET.EXPSR_COST_TYPE_CD IN (''PDL'',''EXPNS'') 

                AND       CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'',''EXPNS'') 

                AND       CETL.LNITM_CTGY_TYPE_CD IN (  ''LOSS'', ''SALVEXP'',''SUBROEXP'',''DED'',''DEDRFND'',''FRMRDED'') ) THEN (CETL.CLM_EXPSR_LNITM_AMT) 

ELSE      0 

END       )

-

SUM( 

CASE     WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''  

                AND       CET.RCVRY_CTGY_TYPE_CD IN (''SUBRO'' , ''SALVAGE'')

                 AND       CET.EXPSR_COST_TYPE_CD IN (''PDL'') 

                AND       CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'') 

                AND       CETL.LNITM_CTGY_TYPE_CD IN ( ''SALVEXP'',''SUBROEXP'' )) THEN (CETL.CLM_EXPSR_LNITM_AMT) 

ELSE      0 

END       ) 

 - SUM( 

CASE     WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''  

                AND       CET.RCVRY_CTGY_TYPE_CD IN (''SUBRO'' , ''SALVAGE'')

                 AND       CET.EXPSR_COST_TYPE_CD IN (''EXPNS'') 

                AND       CET.EXPSR_COST_CTGY_TYPE_CD IN (''EXPNS'') 

                AND       CETL.LNITM_CTGY_TYPE_CD IN ( ''RCVRY'' ,''SUBROEXP'',''SALVEXP'' ))  THEN (CETL.CLM_EXPSR_LNITM_AMT) 

ELSE      0 

END       )

-

(SUM ( 

CASE	    

	WHEN	( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''  

                AND       CET.RCVRY_CTGY_TYPE_CD IN (''CRLOSS'',

		''SALVAGE'',''SUBRO'') 

                AND       CET.EXPSR_COST_TYPE_CD IN (''PDL'')   

                AND       CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')  

                AND       CETL.LNITM_CTGY_TYPE_CD IN (NULL,

		''RCVRY'' )) THEN (CETL.CLM_EXPSR_LNITM_AMT) 

ELSE	     0 

END	     )) as PAID_LOSS_NET_RECV



,(SUM ( 

CASE     WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RESRV''  

 AND       CET.EXPSR_COST_TYPE_CD=''PDL'' 

                AND       CET.EXPSR_COST_CTGY_TYPE_CD =''LOSS'' 



) THEN (CETL.CLM_EXPSR_LNITM_AMT) 

ELSE      0 END ) )

-

(SUM (

CASE     WHEN (CET.CLM_EXPSR_TRANS_SBTYPE_CD = ''PYMNT'' 

                AND       CET.EXPSR_COST_TYPE_CD IN (''PDL'')  

                AND       CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')

                AND       CETL.LNITM_CTGY_TYPE_CD IN (  ''LOSS'',''DED'',''DEDRFND'',''FRMRDED'')

                AND      CET.DOES_NOT_ERODE_RSERV_IND=''F'' 

                 )

                THEN (CETL.CLM_EXPSR_LNITM_AMT) 

 ELSE      0 END ) ) AS OUT_RESERV





FROM

DB_T_PROD_CORE.CLM_EXPSR_TRANS CET

INNER JOIN DB_T_PROD_CORE.CLM_EXPSR_TRANS_LNITM CETL ON  CET.CLM_EXPSR_TRANS_ID=CETL.CLM_EXPSR_TRANS_ID AND  CETL.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

INNER JOIN DB_T_PROD_CORE.CLM_EXPSR CE ON  CE.CLM_EXPSR_ID=CET.CLM_EXPSR_ID AND CE.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

INNER JOIN DB_T_PROD_CORE.CLM_STS CST ON CST.CLM_ID=CE.CLM_ID AND CST.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

INNER JOIN DB_T_PROD_CORE.FEAT FT ON FT.FEAT_ID=CE.CVGE_FEAT_ID AND FT.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

WHERE
  CET.CLM_EXPSR_TRANS_DTTM BETWEEN DATE_TRUNC(''QUARTER'', :FS_DATE)
  AND DATEADD(''QUARTER'', 1, DATE_TRUNC(''QUARTER'', :FS_DATE)) - INTERVAL ''1 DAY''
  AND CET.EDW_END_DTTM = CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP)

GROUP BY 1,2,3

) CLMEXPSR ON CLMEXPSR.CLM_EXPSR_ID=CEXP.CLM_EXPSR_ID AND CLMEXPSR.CLM_ID=CEXP.CLM_ID



LEFT JOIN (
  SELECT
    QUARTER(:FS_DATE) as quarter_of_year,
    YEAR(:FS_DATE) as year_of_calendar
) cal

on 1=1



Where

CEXP.EDW_END_DTTM=''9999-12-31 23:59:59.999999'' 

/* GROUP BY 1,2,3,4,5,6,7,8,9,10,11,14,15,16,17,18,19,20 */
) TEMP 

WHERE 

TEMP.PD_CLM_CVGE_CNT > 0 OR  

TEMP.OUTST_CLM_CVGE_CNT  > 0

GROUP BY 1,2,3,4,5,6,7,8,9,14,15
) SRC
)
);


-- Component exp_pass_to_tgt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_to_tgt AS
(
SELECT
SQ_FS_CLM.CAL_YR_NUM as CAL_YR_NUM,
SQ_FS_CLM.CAL_QTR_NUM as CAL_QTR_NUM,
SQ_FS_CLM.ST_CD as ST_CD,
SQ_FS_CLM.UNDRWRTG_CO_CD as UNDRWRTG_CO_CD,
SQ_FS_CLM.PLCY_TYPE_DESC as PLCY_TYPE_DESC,
SQ_FS_CLM.CAT_CD as CAT_CD,
SQ_FS_CLM.CAUS_OF_LOSS_CD as CAUS_OF_LOSS_CD,
SQ_FS_CLM.CNTY_NAME as CNTY_NAME,
SQ_FS_CLM.CVGE_NAME as CVGE_NAME,
SQ_FS_CLM.PD_CLM_CVGE_CNT as PD_CLM_CVGE_CNT,
SQ_FS_CLM.OUTST_CLM_CVGE_CNT as OUTST_CLM_CVGE_CNT,
SQ_FS_CLM.PD_LOSS_NET_RCVRY_AMT as PD_LOSS_NET_RCVRY_AMT,
SQ_FS_CLM.OUTST_RSERV_AMT as OUTST_RSERV_AMT,
SQ_FS_CLM.CRTD_DTTM as CRTD_DTTM,
SQ_FS_CLM.source_record_id
FROM
SQ_FS_CLM
);


-- Component tgt_FS_CLM_ins, Type TARGET 
INSERT INTO DB_T_PROD_WRK.FS_CLM
(
CAL_YR_NUM,
CAL_QTR_NUM,
ST_CD,
UNDRWRTG_CO_CD,
PLCY_TYPE_DESC,
CAT_CD,
CAUS_OF_LOSS_CD,
CNTY_NAME,
CVGE_NAME,
PD_CLM_CVGE_CNT,
OUTST_CLM_CVGE_CNT,
PD_LOSS_NET_RCVRY_AMT,
OUTST_RSERV_AMT,
LOAD_DTTM
)
SELECT
exp_pass_to_tgt.CAL_YR_NUM as CAL_YR_NUM,
exp_pass_to_tgt.CAL_QTR_NUM as CAL_QTR_NUM,
exp_pass_to_tgt.ST_CD as ST_CD,
exp_pass_to_tgt.UNDRWRTG_CO_CD as UNDRWRTG_CO_CD,
exp_pass_to_tgt.PLCY_TYPE_DESC as PLCY_TYPE_DESC,
exp_pass_to_tgt.CAT_CD as CAT_CD,
exp_pass_to_tgt.CAUS_OF_LOSS_CD as CAUS_OF_LOSS_CD,
exp_pass_to_tgt.CNTY_NAME as CNTY_NAME,
exp_pass_to_tgt.CVGE_NAME as CVGE_NAME,
exp_pass_to_tgt.PD_CLM_CVGE_CNT as PD_CLM_CVGE_CNT,
exp_pass_to_tgt.OUTST_CLM_CVGE_CNT as OUTST_CLM_CVGE_CNT,
exp_pass_to_tgt.PD_LOSS_NET_RCVRY_AMT as PD_LOSS_NET_RCVRY_AMT,
exp_pass_to_tgt.OUTST_RSERV_AMT as OUTST_RSERV_AMT,
exp_pass_to_tgt.CRTD_DTTM as LOAD_DTTM
FROM
exp_pass_to_tgt;


-- PIPELINE END FOR 2

END; ';