-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_ALFA_ARS_BILL_INFO("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 

-- Component ALFA_ARS_BILL_INFO2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_PROD.ALFA_ARS_BILL_INFO;


-- PIPELINE START FOR 1

-- Component SQ_ALFA_ARS_BILL_INFO1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ALFA_ARS_BILL_INFO1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_Count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM DB_T_STAG_PROD.alfa_ars_bill_info
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
TO_NUMBER(SQ_ALFA_ARS_BILL_INFO1.record_Count) as o_record_count,
:feed_ind as feed_ind,
to_char ( CURRENT_TIMESTAMP , ''YYYY-MM-DD'' ) as feed_dt,
SQ_ALFA_ARS_BILL_INFO1.source_record_id
FROM
SQ_ALFA_ARS_BILL_INFO1
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.o_record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_ALFA_ARS_BILL_INFO, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ALFA_ARS_BILL_INFO AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as BIL_ACCOUNT_ID,
$2 as BIL_ACCOUNT_NBR,
$3 as POLICY_NBR,
$4 as BIL_PLAN_CD,
$5 as LATE_IND_3YR,
$6 as LATE_COUNT_1YR,
$7 as LATE_COUNT_2YR,
$8 as LATE_COUNT_3YR,
$9 as LATE_COUNT_4YR,
$10 as LATE_COUNT_5YR,
$11 as TEN_DAY_LATE_COUNT,
$12 as LOB,
$13 as MEM_CUST_TYPE,
$14 as MEM_CUST_NBR,
$15 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
ALFA_ARS_BILL_INFO.BIL_ACCOUNT_ID,
ALFA_ARS_BILL_INFO.BIL_ACCOUNT_NBR,
ALFA_ARS_BILL_INFO.POLICY_NBR,
ALFA_ARS_BILL_INFO.BIL_PLAN_CD,
ALFA_ARS_BILL_INFO.LATE_IND_3YR,
ALFA_ARS_BILL_INFO.LATE_COUNT_1YR,
ALFA_ARS_BILL_INFO.LATE_COUNT_2YR,
ALFA_ARS_BILL_INFO.LATE_COUNT_3YR,
ALFA_ARS_BILL_INFO.LATE_COUNT_4YR,
ALFA_ARS_BILL_INFO.LATE_COUNT_5YR,
ALFA_ARS_BILL_INFO.TEN_DAY_LATE_COUNT,
ALFA_ARS_BILL_INFO.LOB,
ALFA_ARS_BILL_INFO.MEM_CUST_TYPE,
ALFA_ARS_BILL_INFO.MEM_CUST_NBR
FROM DB_T_STAG_PROD.ALFA_ARS_BILL_INFO
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_ALFA_ARS_BILL_INFO.BIL_ACCOUNT_ID as BIL_ACCOUNT_ID,
SQ_ALFA_ARS_BILL_INFO.BIL_ACCOUNT_NBR as BIL_ACCOUNT_NBR,
SQ_ALFA_ARS_BILL_INFO.POLICY_NBR as POLICY_NBR,
SQ_ALFA_ARS_BILL_INFO.BIL_PLAN_CD as BIL_PLAN_CD,
SQ_ALFA_ARS_BILL_INFO.LATE_IND_3YR as LATE_IND_3YR,
SQ_ALFA_ARS_BILL_INFO.LATE_COUNT_1YR as LATE_COUNT_1YR,
SQ_ALFA_ARS_BILL_INFO.LATE_COUNT_2YR as LATE_COUNT_2YR,
SQ_ALFA_ARS_BILL_INFO.LATE_COUNT_3YR as LATE_COUNT_3YR,
SQ_ALFA_ARS_BILL_INFO.LATE_COUNT_4YR as LATE_COUNT_4YR,
SQ_ALFA_ARS_BILL_INFO.LATE_COUNT_5YR as LATE_COUNT_5YR,
SQ_ALFA_ARS_BILL_INFO.TEN_DAY_LATE_COUNT as TEN_DAY_LATE_COUNT,
SQ_ALFA_ARS_BILL_INFO.LOB as LOB,
SQ_ALFA_ARS_BILL_INFO.MEM_CUST_TYPE as MEM_CUST_TYPE,
SQ_ALFA_ARS_BILL_INFO.MEM_CUST_NBR as MEM_CUST_NBR,
SQ_ALFA_ARS_BILL_INFO.source_record_id
FROM
SQ_ALFA_ARS_BILL_INFO
);


-- Component ALFA_ARS_BILL_INFO2, Type TARGET 
INSERT INTO DB_T_STAG_PROD.ALFA_ARS_BILL_INFO
(
BIL_ACCOUNT_ID,
BIL_ACCOUNT_NBR,
POLICY_NBR,
BIL_PLAN_CD,
LATE_IND_3YR,
LATE_COUNT_1YR,
LATE_COUNT_2YR,
LATE_COUNT_3YR,
LATE_COUNT_4YR,
LATE_COUNT_5YR,
TEN_DAY_LATE_COUNT,
LOB,
MEM_CUST_TYPE,
MEM_CUST_NBR
)
SELECT
exp_pass_through.BIL_ACCOUNT_ID as BIL_ACCOUNT_ID,
exp_pass_through.BIL_ACCOUNT_NBR as BIL_ACCOUNT_NBR,
exp_pass_through.POLICY_NBR as POLICY_NBR,
exp_pass_through.BIL_PLAN_CD as BIL_PLAN_CD,
exp_pass_through.LATE_IND_3YR as LATE_IND_3YR,
exp_pass_through.LATE_COUNT_1YR as LATE_COUNT_1YR,
exp_pass_through.LATE_COUNT_2YR as LATE_COUNT_2YR,
exp_pass_through.LATE_COUNT_3YR as LATE_COUNT_3YR,
exp_pass_through.LATE_COUNT_4YR as LATE_COUNT_4YR,
exp_pass_through.LATE_COUNT_5YR as LATE_COUNT_5YR,
exp_pass_through.TEN_DAY_LATE_COUNT as TEN_DAY_LATE_COUNT,
exp_pass_through.LOB as LOB,
exp_pass_through.MEM_CUST_TYPE as MEM_CUST_TYPE,
exp_pass_through.MEM_CUST_NBR as MEM_CUST_NBR
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';