-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STAG_AGENT_INFO("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
FEED_DT date;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 
FEED_DT:=(select current_date); 

-- Component AGENT_INFO2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.AGENT_INFO;


-- PIPELINE START FOR 1

-- Component SQ_AGENT_INFO3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGENT_INFO3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_ct,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) as record_count
FROM
DB_T_STAG_MEMBXREF_PROD.AGENT_INFO
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_AGENT_INFO3.record_ct as record_count,
:feed_ind as feed_ind,
:feed_dt as feed_dt,
SQ_AGENT_INFO3.source_record_id
FROM
SQ_AGENT_INFO3
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_AGENT_INFO2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGENT_INFO2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as AGENTID,
$2 as NAME,
$3 as PHONE,
$4 as IMG_PHOTO,
$5 as LASTNAME,
$6 as FIRSTNAME,
$7 as EMAIL,
$8 as CITY,
$9 as STATE,
$10 as ZIP,
$11 as ADDRESS,
$12 as CELLPHONE,
$13 as HOMEPHONE,
$14 as PAGERPHONE,
$15 as COUNTY,
$16 as ABOUT,
$17 as DIRECTIONS,
$18 as LOCATION,
$19 as REGION,
$20 as DISTRICT,
$21 as MAILING_ADDRESS,
$22 as MAILING_CITY,
$23 as MAILING_STATE,
$24 as MAILING_ZIP,
$25 as SC_NBR,
$26 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
AGENT_INFO3.AGENTID,
AGENT_INFO3.NAME,
AGENT_INFO3.PHONE,
AGENT_INFO3.IMG_PHOTO,
AGENT_INFO3.LASTNAME,
AGENT_INFO3.FIRSTNAME,
AGENT_INFO3.EMAIL,
AGENT_INFO3.CITY,
AGENT_INFO3.STATE,
AGENT_INFO3.ZIP,
AGENT_INFO3.ADDRESS,
AGENT_INFO3.CELLPHONE,
AGENT_INFO3.HOMEPHONE,
AGENT_INFO3.PAGERPHONE,
AGENT_INFO3.COUNTY,
AGENT_INFO3.ABOUT,
AGENT_INFO3.DIRECTIONS,
AGENT_INFO3.LOCATION,
AGENT_INFO3.REGION,
AGENT_INFO3.DISTRICT,
AGENT_INFO3.MAILING_ADDRESS,
AGENT_INFO3.MAILING_CITY,
AGENT_INFO3.MAILING_STATE,
AGENT_INFO3.MAILING_ZIP,
AGENT_INFO3.SC_NBR
FROM DB_T_STAG_MEMBXREF_PROD.AGENT_INFO AGENT_INFO3
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_AGENT_INFO2.AGENTID as AGENTID,
SQ_AGENT_INFO2.NAME as NAME,
SQ_AGENT_INFO2.PHONE as PHONE,
SQ_AGENT_INFO2.IMG_PHOTO as IMG_PHOTO,
SQ_AGENT_INFO2.LASTNAME as LASTNAME,
SQ_AGENT_INFO2.FIRSTNAME as FIRSTNAME,
SQ_AGENT_INFO2.EMAIL as EMAIL,
SQ_AGENT_INFO2.CITY as CITY,
SQ_AGENT_INFO2.STATE as STATE,
SQ_AGENT_INFO2.ZIP as ZIP,
SQ_AGENT_INFO2.ADDRESS as ADDRESS,
SQ_AGENT_INFO2.CELLPHONE as CELLPHONE,
SQ_AGENT_INFO2.HOMEPHONE as HOMEPHONE,
SQ_AGENT_INFO2.PAGERPHONE as PAGERPHONE,
SQ_AGENT_INFO2.COUNTY as COUNTY,
SQ_AGENT_INFO2.ABOUT as ABOUT,
SQ_AGENT_INFO2.DIRECTIONS as DIRECTIONS,
SQ_AGENT_INFO2.LOCATION as LOCATION,
SQ_AGENT_INFO2.REGION as REGION,
SQ_AGENT_INFO2.DISTRICT as DISTRICT,
SQ_AGENT_INFO2.MAILING_ADDRESS as MAILING_ADDRESS,
SQ_AGENT_INFO2.MAILING_CITY as MAILING_CITY,
SQ_AGENT_INFO2.MAILING_STATE as MAILING_STATE,
SQ_AGENT_INFO2.MAILING_ZIP as MAILING_ZIP,
SQ_AGENT_INFO2.SC_NBR as SC_NBR,
SQ_AGENT_INFO2.source_record_id
FROM
SQ_AGENT_INFO2
);


-- Component AGENT_INFO2, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.AGENT_INFO
(
AGENTID,
NAME,
PHONE,
IMG_PHOTO,
LASTNAME,
FIRSTNAME,
EMAIL,
CITY,
STATE,
ZIP,
ADDRESS,
CELLPHONE,
HOMEPHONE,
PAGERPHONE,
COUNTY,
ABOUT,
DIRECTIONS,
LOCATION,
REGION,
DISTRICT,
MAILING_ADDRESS,
MAILING_CITY,
MAILING_STATE,
MAILING_ZIP,
SC_NBR
)
SELECT
exp_pass_through.AGENTID as AGENTID,
exp_pass_through.NAME as NAME,
exp_pass_through.PHONE as PHONE,
exp_pass_through.IMG_PHOTO as IMG_PHOTO,
exp_pass_through.LASTNAME as LASTNAME,
exp_pass_through.FIRSTNAME as FIRSTNAME,
exp_pass_through.EMAIL as EMAIL,
exp_pass_through.CITY as CITY,
exp_pass_through.STATE as STATE,
exp_pass_through.ZIP as ZIP,
exp_pass_through.ADDRESS as ADDRESS,
exp_pass_through.CELLPHONE as CELLPHONE,
exp_pass_through.HOMEPHONE as HOMEPHONE,
exp_pass_through.PAGERPHONE as PAGERPHONE,
exp_pass_through.COUNTY as COUNTY,
exp_pass_through.ABOUT as ABOUT,
exp_pass_through.DIRECTIONS as DIRECTIONS,
exp_pass_through.LOCATION as LOCATION,
exp_pass_through.REGION as REGION,
exp_pass_through.DISTRICT as DISTRICT,
exp_pass_through.MAILING_ADDRESS as MAILING_ADDRESS,
exp_pass_through.MAILING_CITY as MAILING_CITY,
exp_pass_through.MAILING_STATE as MAILING_STATE,
exp_pass_through.MAILING_ZIP as MAILING_ZIP,
exp_pass_through.SC_NBR as SC_NBR
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';