-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_POLICY_TYPE_BY_CUSTOMER_INS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component POLICY_TYPE_BY_CUSTOMER, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_MEMBXREF_PROD.POLICY_TYPE_BY_CUSTOMER;


-- Component SQ_view_Fire, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_view_Fire AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMBER_NUM,
$2 as AUTO_POLS,
$3 as HOME_POLS,
$4 as FARM_POLS,
$5 as FIRE_POLS,
$6 as MFGH_POLS,
$7 as SMLN_POLS,
$8 as FGM_POLS,
$9 as SM_POLS,
$10 as PORT_POLS,
$11 as LIFE_POLS,
$12 as OTHER_POLS,
$13 as TOTAL_POLS,
$14 as TOTAL_PREM,
$15 as TOTAL_LOB,
$16 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT  
		POLS.MEMBER_NUM,   
		COALESCE(AUTO.TOTAL_POLS, 0) AS AUTO_POLS,   
		COALESCE(HOME.TOTAL_POLS, 0) AS HOME_POLS,   
		COALESCE(FARM.TOTAL_POLS, 0) AS FARM_POLS,   
		COALESCE(FIRE.TOTAL_POLS, 0) AS FIRE_POLS,   
		COALESCE(MFGH.TOTAL_POLS, 0) AS MFGH_POLS,   
		COALESCE(SMLN.TOTAL_POLS, 0) AS SMLN_POLS,   
		COALESCE(FGM.TOTAL_POLS, 0) AS FGM_POLS,   
		COALESCE(SM.TOTAL_POLS, 0) AS SM_POLS,   
		COALESCE(PORT.TOTAL_POLS, 0) AS PORT_POLS,   
		COALESCE(LIFE.TOTAL_POLS, 0) AS LIFE_POLS,   
		COALESCE(OTHER.TOTAL_POLS, 0) AS OTHER_POLS,   
		COALESCE(AUTO.TOTAL_POLS, 0) + COALESCE(HOME.TOTAL_POLS, 0) + COALESCE(FARM.TOTAL_POLS, 0) + COALESCE(FIRE.TOTAL_POLS, 0) + COALESCE(MFGH.TOTAL_POLS, 0) + COALESCE(SMLN.TOTAL_POLS, 0) + COALESCE(FGM.TOTAL_POLS, 0) + COALESCE(PORT.TOTAL_POLS, 0) + COALESCE(LIFE.TOTAL_POLS, 0) + COALESCE(OTHER.TOTAL_POLS, 0) AS TOTAL_POLS,   
		COALESCE(AUTO.TOTAL_PREM, 0) + COALESCE(HOME.TOTAL_PREM, 0) + COALESCE(FARM.TOTAL_PREM, 0) + COALESCE(FIRE.TOTAL_PREM, 0) + COALESCE(MFGH.TOTAL_PREM, 0) + COALESCE(SMLN.TOTAL_PREM, 0) + COALESCE(FGM.TOTAL_PREM, 0) + COALESCE(PORT.TOTAL_PREM, 0) + COALESCE(LIFE.TOTAL_PREM, 0) + COALESCE(OTHER.TOTAL_PREM, 0) AS TOTAL_PREM,   
		COALESCE(AUTO.LINE_OF_BUS, 0) + COALESCE(HOME.LINE_OF_BUS, 0) + COALESCE(FARM.LINE_OF_BUS, 0) + COALESCE(FIRE.LINE_OF_BUS, 0) + COALESCE(MFGH.LINE_OF_BUS, 0) + COALESCE(SMLN.LINE_OF_BUS, 0) + COALESCE(FGM.LINE_OF_BUS, 0) + COALESCE(PORT.LINE_OF_BUS, 0) + COALESCE(LIFE.LINE_OF_BUS, 0) + COALESCE(OTHER.LINE_OF_BUS, 0) AS TOTAL_LOB  
	FROM  
		(SELECT DISTINCT MEMBER_NUM     
			FROM DB_T_STAG_MEMBXREF_PROD.POLICIES_BY_MEMBER     
			WHERE POLICY_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''41'',''42'',''43'',''44'',''45'',''31'',''32'','''')  
		) POLS  
		LEFT JOIN 
			(SELECT MEMBER_NUM,       
				COUNT(POLICY_NBR) AS TOTAL_POLS,       
				SUM(TOTAL_PREM) AS TOTAL_PREM,       
				SUM(UNITS) AS UNITS,       
				1 AS LINE_OF_BUS     
			FROM     
				(
					(SELECT CLIENT_REF_NBR AS MEMBER_NUM,       
						POL_NBR AS POLICY_NBR,       
						SUM(TOT_PRM_AMT) AS TOTAL_PREM,       
						COUNT(VIN_NBR) AS UNITS,       
						1 AS LINE_OF_BUS      
					FROM DB_T_STAG_MEMBXREF_PROD.POL_VEH_LIST      
					GROUP BY 1,2     
					)           					
				) X 
				GROUP BY 1    
			) AUTO ON POLS.MEMBER_NUM = AUTO.MEMBER_NUM     
		LEFT JOIN 
			(SELECT PC_MEMBER_NUMBER AS MEMBER_NUM,        
				COUNT(SC_POLICY_NUM) AS TOTAL_POLS,       
				SUM(HO_TOT_PREM) AS TOTAL_PREM,        
				COUNT(SC_POLICY_NUM) AS UNITS,        
				1 AS LINE_OF_BUS       
			FROM DB_T_CORE_MEMBXREF_PROD.HOMEPOLS          
			WHERE PC_STATUS IN (''1'',''2'',''3'',''4'')      
			GROUP BY 1
			) HOME ON POLS.MEMBER_NUM = HOME.MEMBER_NUM     
		LEFT JOIN 
			(SELECT PC_MEMBER_NUMBER AS MEMBER_NUM,        
				COUNT(SC_POLICY_NUM) AS TOTAL_POLS,        
				SUM(RFD_TOT_PREM) AS TOTAL_PREM,        
				COUNT(SC_POLICY_NUM) AS UNITS,        
				1 AS LINE_OF_BUS       
			FROM DB_T_CORE_MEMBXREF_PROD.FARMPOLS          
			WHERE PC_STATUS IN (''1'',''2'',''3'',''4'')      
			GROUP BY 1
			) FARM ON POLS.MEMBER_NUM = FARM.MEMBER_NUM     
		LEFT JOIN 
			(SELECT PC_MEMBER_NUMBER AS MEMBER_NUM,        
				COUNT(SC_POLICY_NUM) AS TOTAL_POLS,        
				SUM(FI_TOT_PREM) AS TOTAL_PREM,        
				COUNT(SC_POLICY_NUM) AS UNITS,        
				1 AS LINE_OF_BUS       
			FROM DB_T_CORE_MEMBXREF_PROD.FIREPOLS          
			WHERE PC_STATUS IN (''1'',''2'',''3'',''4'')      
			GROUP BY 1
			) FIRE ON POLS.MEMBER_NUM = FIRE.MEMBER_NUM     
		LEFT JOIN 
			(SELECT PC_MEMBER_NUMBER AS MEMBER_NUM,        
				COUNT(SC_POLICY_NUM) AS TOTAL_POLS,        
				SUM(MH_UNP_TOTAL_PREM) AS TOTAL_PREM,        
				COUNT(SC_POLICY_NUM) AS UNITS,        
				1 AS LINE_OF_BUS       
			FROM DB_T_CORE_MEMBXREF_PROD.MANHOMEPOLS          
			WHERE PC_STATUS IN (''1'',''2'',''3'',''4'')      
			GROUP BY 1
			) MFGH ON POLS.MEMBER_NUM = MFGH.MEMBER_NUM     
		LEFT JOIN 
			(SELECT PC_MEMBER_NUMBER AS MEMBER_NUM,        
				COUNT(SC_POLICY_NUM) AS TOTAL_POLS,        
				SUM(SMLN_TOT_PREM) AS TOTAL_PREM,        
				COUNT(SC_POLICY_NUM) AS UNITS,        
				1 AS LINE_OF_BUS       
			FROM DB_T_CORE_MEMBXREF_PROD.SMLNPOLS          
			WHERE PC_STATUS IN (''1'',''2'',''3'',''4'')      
			GROUP BY 1
			) SMLN ON POLS.MEMBER_NUM = SMLN.MEMBER_NUM         
		LEFT JOIN 
			(SELECT PC_MEMBER_NUMBER AS MEMBER_NUM,        
				COUNT(SC_POLICY_NUM) AS TOTAL_POLS,        
				SUM(FGM_TOT_PREM) AS TOTAL_PREM,        
				COUNT(SC_POLICY_NUM) AS UNITS,        
				1 AS LINE_OF_BUS       
			FROM DB_T_CORE_MEMBXREF_PROD.FGMPOLS          
			WHERE PC_STATUS IN (''1'',''2'',''3'',''4'')      
			GROUP BY 1
			) FGM ON POLS.MEMBER_NUM = FGM.MEMBER_NUM         
		LEFT JOIN 
			(SELECT MEMBER_NUM,       
				TOTAL_POLS,       
				TOTAL_PREM,       
				UNITS,       
				LINE_OF_BUS       
			FROM     
				(SELECT PC_MEMBER_NUMBER AS MEMBER_NUM,        
					COUNT(SC_POLICY_NUM) AS TOTAL_POLS,        
					SUM(SMLN_TOT_PREM) AS TOTAL_PREM,        
					COUNT(SC_POLICY_NUM) AS UNITS,        
					1 AS LINE_OF_BUS     
				FROM DB_T_CORE_MEMBXREF_PROD.SMLNPOLS     
				WHERE PC_STATUS IN (''1'',''2'',''3'',''4'')               
					AND SUBSTR(SC_POLICY_NUM,1,2) = ''SM''     
				GROUP BY 1     
				) SMLN       
			UNION       
				(SELECT PC_MEMBER_NUMBER AS MEMBER_NUM,        
					COUNT(SC_POLICY_NUM) AS TOTAL_POLS,        
					SUM(FGM_TOT_PREM) AS TOTAL_PREM,        
					COUNT(SC_POLICY_NUM) AS UNITS,        
					1 AS LINE_OF_BUS     
				FROM DB_T_CORE_MEMBXREF_PROD.FGMPOLS     
				WHERE PC_STATUS IN (''1'',''2'',''3'',''4'')               
					AND SUBSTR(SC_POLICY_NUM,1,2) = ''SM''     
				GROUP BY 1     
				)      
			) SM ON POLS.MEMBER_NUM = SM.MEMBER_NUM     
		LEFT JOIN 
			(SELECT PC_MEMBER_NUMBER AS MEMBER_NUM,        
				COUNT(SC_POLICY_NUM) AS TOTAL_POLS,        
				SUM(PORT_TOT_PREM) AS TOTAL_PREM,        
				COUNT(SC_POLICY_NUM) AS UNITS,        
				1 AS LINE_OF_BUS       
			FROM DB_T_CORE_MEMBXREF_PROD.PORTPOLS          
			WHERE PC_STATUS IN (''1'',''2'',''3'',''4'')      
			GROUP BY 1
			) PORT ON POLS.MEMBER_NUM = PORT.MEMBER_NUM     
		LEFT JOIN 
			(SELECT MEMBER_NUM,        
				SUM(TOTAL_POLS) AS TOTAL_POLS,        
				SUM(TOTAL_PREM) AS TOTAL_PREM,        
				SUM(UNITS) AS UNITS,        
				1 AS LINE_OF_BUS       
			FROM       
				(SELECT LF_MEMBERSHIP AS MEMBER_NUM,        
					COUNT(SC_POLICY_NUM) AS TOTAL_POLS,        
					SUM(LF_ANNUAL_PREM) AS TOTAL_PREM,        
					COUNT(SC_POLICY_NUM) AS UNITS     
				FROM DB_T_CORE_MEMBXREF_PROD.LIFEPOLS     
				WHERE LF_STATUS IN (''22'',''41'',''42'',''43'',''44'',''45'',''31'',''32'')     
				GROUP BY 1       
				UNION       
				SELECT INSURED_MEMBER_NUM AS MEMBER_NUM,        
					COUNT(POL_ID) AS TOTAL_POLS,        
					0  AS TOTAL_PREM,        
					COUNT(POL_ID) AS UNITS     
				FROM DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST     
				WHERE POL_STATUS IN (''1'',''2'',''3'',''4'')     
				GROUP BY 1     
				) X     
			GROUP BY 1     
			) LIFE ON POLS.MEMBER_NUM = LIFE.MEMBER_NUM        
		LEFT JOIN 
			(SELECT MEMBER_NUM,        
				SUM(TOTAL_POLS) AS TOTAL_POLS,        
				SUM(TOTAL_PREM) AS TOTAL_PREM,        
				SUM(UNITS) AS UNITS,        
				1 AS LINE_OF_BUS       
			FROM     
				(SELECT PC_MEMBER_NUMBER AS MEMBER_NUM,        
					COUNT(SC_POLICY_NUM) AS TOTAL_POLS,        
					0  AS TOTAL_PREM,        
					COUNT(SC_POLICY_NUM) AS UNITS     
				FROM DB_T_CORE_MEMBXREF_PROD.LOANS     
				WHERE LN_STATUS IN (''0'')     
				GROUP BY 1       
				UNION       
				SELECT PL_MEMBER_NUM AS MEMBER_NUM,        
					COUNT(PL_POL_NUM) AS TOTAL_POLS,        
					0 AS TOTAL_PREM,        
					COUNT(PL_POL_NUM) AS UNITS     
				FROM DB_T_STAG_MEMBXREF_PROD.POLICYLIST     
				WHERE PL_TYPE = 15        
					AND PL_STATUS IN (''1'')     
				GROUP BY 1     
				) X      
			GROUP BY 1     
			) OTHER ON POLS.MEMBER_NUM = OTHER.MEMBER_NUM
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_view_Fire.MEMBER_NUM as MEMBER_NUM,
SQ_view_Fire.AUTO_POLS as AUTO_POLS,
SQ_view_Fire.HOME_POLS as HOME_POLS,
SQ_view_Fire.FARM_POLS as FARM_POLS,
SQ_view_Fire.FIRE_POLS as FIRE_POLS,
SQ_view_Fire.MFGH_POLS as MFGH_POLS,
SQ_view_Fire.SMLN_POLS as SMLN_POLS,
SQ_view_Fire.FGM_POLS as FGM_POLS,
SQ_view_Fire.SM_POLS as SM_POLS,
SQ_view_Fire.PORT_POLS as PORT_POLS,
SQ_view_Fire.LIFE_POLS as LIFE_POLS,
SQ_view_Fire.OTHER_POLS as OTHER_POLS,
SQ_view_Fire.TOTAL_POLS as TOTAL_POLS,
SQ_view_Fire.TOTAL_PREM as TOTAL_PREM,
SQ_view_Fire.TOTAL_LOB as TOTAL_LOB,
SQ_view_Fire.source_record_id
FROM
SQ_view_Fire
);


-- Component POLICY_TYPE_BY_CUSTOMER, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.POLICY_TYPE_BY_CUSTOMER
(
MEMBER_NUM,
AUTO_POLS,
HOME_POLS,
FARM_POLS,
FIRE_POLS,
MFGH_POLS,
SMLN_POLS,
FGM_POLS,
SM_POLS,
PORT_POLS,
LIFE_POLS,
OTHER_POLS,
TOTAL_POLS,
TOTAL_PREM,
TOTAL_LOB
)
SELECT
EXPTRANS.MEMBER_NUM as MEMBER_NUM,
EXPTRANS.AUTO_POLS as AUTO_POLS,
EXPTRANS.HOME_POLS as HOME_POLS,
EXPTRANS.FARM_POLS as FARM_POLS,
EXPTRANS.FIRE_POLS as FIRE_POLS,
EXPTRANS.MFGH_POLS as MFGH_POLS,
EXPTRANS.SMLN_POLS as SMLN_POLS,
EXPTRANS.FGM_POLS as FGM_POLS,
EXPTRANS.SM_POLS as SM_POLS,
EXPTRANS.PORT_POLS as PORT_POLS,
EXPTRANS.LIFE_POLS as LIFE_POLS,
EXPTRANS.OTHER_POLS as OTHER_POLS,
EXPTRANS.TOTAL_POLS as TOTAL_POLS,
EXPTRANS.TOTAL_PREM as TOTAL_PREM,
EXPTRANS.TOTAL_LOB as TOTAL_LOB
FROM
EXPTRANS;


END; ';