-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_RHPOLS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component STG_RHPOLS, Type Pre SQL 
DELETE  FROM DB_T_STAG_MEMBXREF_PROD.STG_RHPOLS where load_dt in
(select distinct a.load_dt from DB_T_STAG_MEMBXREF_PROD.STG_RHPOLS A, DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B WHERE A.LOAD_DT = B.FEED_DT AND B.TABLENAME = ''RHPOLS'');


-- Component SQ_RHPOLS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_RHPOLS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as RH_SERV_CTR,
$2 as RH_CONTRACT_NBR,
$3 as RH_ALPHA_CODE,
$4 as RH_MEM_NBR,
$5 as RH_BILL_GROUP,
$6 as RH_AMT_DUE,
$7 as RH_DUE_DATE,
$8 as RH_NBR_ADV_PMTS,
$9 as RH_O_ADV_PMT_AMT,
$10 as RH_ADV_PMT_BAL,
$11 as RH_PD_SEQ_NBR,
$12 as RH_PAID_DT,
$13 as RH_PAID_AMT,
$14 as RH_PAYMENT_SOURCE,
$15 as RH_NAME,
$16 as RH_BR_ADDR,
$17 as RH_ADDR_2,
$18 as RH_CITY,
$19 as RH_STATE,
$20 as RH_ZIP,
$21 as RH_ZIP_EXT,
$22 as RH_CANC_REQ_CODE,
$23 as RH_BCBS_GRSI,
$24 as FEED_DT,
$25 as FEED_IND,
$26 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 	
	A.RH_SERV_CTR,
	A.RH_CONTRACT_NBR,
	A.RH_ALPHA_CODE,
	A.RH_MEM_NBR,
	A.RH_BILL_GROUP,
	A.RH_AMT_DUE,
	A.RH_DUE_DATE,
	A.RH_NBR_ADV_PMTS,
	A.RH_O_ADV_PMT_AMT,
	A.RH_ADV_PMT_BAL,
	A.RH_PD_SEQ_NBR,
	A.RH_PAID_DT,
	A.RH_PAID_AMT,
	A.RH_PAYMENT_SOURCE,
	A.RH_NAME,
	A.RH_BR_ADDR,
	A.RH_ADDR_2,
	A.RH_CITY,
	A.RH_STATE,
	A.RH_ZIP,
	A.RH_ZIP_EXT,
	A.RH_CANC_REQ_CODE,
	A.RH_BCBS_GRSI,
	B.FEED_DT,
	B.FEED_IND
FROM 
	DB_T_CORE_MEMBXREF_PROD.RHPOLS A
	JOIN DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
		ON 1=1
WHERE
	TABLENAME = ''RHPOLS''
) SRC
)
);


-- Component Exp_Pass_Through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_Pass_Through AS
(
SELECT
SQ_RHPOLS.RH_SERV_CTR as RH_SERV_CTR,
SQ_RHPOLS.RH_CONTRACT_NBR as RH_CONTRACT_NBR,
SQ_RHPOLS.RH_ALPHA_CODE as RH_ALPHA_CODE,
SQ_RHPOLS.RH_MEM_NBR as RH_MEM_NBR,
SQ_RHPOLS.RH_BILL_GROUP as RH_BILL_GROUP,
SQ_RHPOLS.RH_AMT_DUE as RH_AMT_DUE,
SQ_RHPOLS.RH_DUE_DATE as RH_DUE_DATE,
SQ_RHPOLS.RH_NBR_ADV_PMTS as RH_NBR_ADV_PMTS,
SQ_RHPOLS.RH_O_ADV_PMT_AMT as RH_O_ADV_PMT_AMT,
SQ_RHPOLS.RH_ADV_PMT_BAL as RH_ADV_PMT_BAL,
SQ_RHPOLS.RH_PD_SEQ_NBR as RH_PD_SEQ_NBR,
SQ_RHPOLS.RH_PAID_DT as RH_PAID_DT,
SQ_RHPOLS.RH_PAID_AMT as RH_PAID_AMT,
SQ_RHPOLS.RH_PAYMENT_SOURCE as RH_PAYMENT_SOURCE,
SQ_RHPOLS.RH_NAME as RH_NAME,
SQ_RHPOLS.RH_BR_ADDR as RH_BR_ADDR,
SQ_RHPOLS.RH_ADDR_2 as RH_ADDR_2,
SQ_RHPOLS.RH_CITY as RH_CITY,
SQ_RHPOLS.RH_STATE as RH_STATE,
SQ_RHPOLS.RH_ZIP as RH_ZIP,
SQ_RHPOLS.RH_ZIP_EXT as RH_ZIP_EXT,
SQ_RHPOLS.RH_CANC_REQ_CODE as RH_CANC_REQ_CODE,
SQ_RHPOLS.RH_BCBS_GRSI as RH_BCBS_GRSI,
SQ_RHPOLS.FEED_DT as FEED_DT,
SQ_RHPOLS.FEED_IND as FEED_IND,
SQ_RHPOLS.source_record_id
FROM
SQ_RHPOLS
);


-- Component STG_RHPOLS, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_RHPOLS
(
RH_SERV_CTR,
RH_CONTRACT_NBR,
RH_ALPHA_CODE,
RH_MEM_NBR,
RH_BILL_GROUP,
RH_AMT_DUE,
RH_DUE_DATE,
RH_NBR_ADV_PMTS,
RH_O_ADV_PMT_AMT,
RH_ADV_PMT_BAL,
RH_PD_SEQ_NBR,
RH_PAID_DT,
RH_PAID_AMT,
RH_PAYMENT_SOURCE,
RH_NAME,
RH_BR_ADDR,
RH_ADDR_2,
RH_CITY,
RH_STATE,
RH_ZIP,
RH_ZIP_EXT,
RH_CANC_REQ_CODE,
RH_BCBS_GRSI,
LOAD_DT,
FEED_IND
)
SELECT
Exp_Pass_Through.RH_SERV_CTR as RH_SERV_CTR,
Exp_Pass_Through.RH_CONTRACT_NBR as RH_CONTRACT_NBR,
Exp_Pass_Through.RH_ALPHA_CODE as RH_ALPHA_CODE,
Exp_Pass_Through.RH_MEM_NBR as RH_MEM_NBR,
Exp_Pass_Through.RH_BILL_GROUP as RH_BILL_GROUP,
Exp_Pass_Through.RH_AMT_DUE as RH_AMT_DUE,
Exp_Pass_Through.RH_DUE_DATE as RH_DUE_DATE,
Exp_Pass_Through.RH_NBR_ADV_PMTS as RH_NBR_ADV_PMTS,
Exp_Pass_Through.RH_O_ADV_PMT_AMT as RH_O_ADV_PMT_AMT,
Exp_Pass_Through.RH_ADV_PMT_BAL as RH_ADV_PMT_BAL,
Exp_Pass_Through.RH_PD_SEQ_NBR as RH_PD_SEQ_NBR,
Exp_Pass_Through.RH_PAID_DT as RH_PAID_DT,
Exp_Pass_Through.RH_PAID_AMT as RH_PAID_AMT,
Exp_Pass_Through.RH_PAYMENT_SOURCE as RH_PAYMENT_SOURCE,
Exp_Pass_Through.RH_NAME as RH_NAME,
Exp_Pass_Through.RH_BR_ADDR as RH_BR_ADDR,
Exp_Pass_Through.RH_ADDR_2 as RH_ADDR_2,
Exp_Pass_Through.RH_CITY as RH_CITY,
Exp_Pass_Through.RH_STATE as RH_STATE,
Exp_Pass_Through.RH_ZIP as RH_ZIP,
Exp_Pass_Through.RH_ZIP_EXT as RH_ZIP_EXT,
Exp_Pass_Through.RH_CANC_REQ_CODE as RH_CANC_REQ_CODE,
Exp_Pass_Through.RH_BCBS_GRSI as RH_BCBS_GRSI,
Exp_Pass_Through.FEED_DT as LOAD_DT,
Exp_Pass_Through.FEED_IND as FEED_IND
FROM
Exp_Pass_Through;


END; ';