-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_ASICPOLS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component STG_ASICPOLS, Type Pre SQL 
DELETE  from DB_T_STAG_MEMBXREF_PROD.STG_ASICPOLS where load_dt in (
select distinct A.LOAD_DT from	DB_T_STAG_MEMBXREF_PROD.STG_ASICPOLS A,
	  DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
	A.LOAD_DT = B.FEED_DT
	AND B.TABLENAME = ''ASICPOLS'');


-- Component SQ_ASICPOLS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ASICPOLS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_SERVICE_CENTER,
$2 as SC_POLICY_NUM,
$3 as PC_ALPHA_CODE,
$4 as PC_EFF_DATE,
$5 as PC_EXP_DATE,
$6 as PC_NAME_1,
$7 as PC_NAME_2,
$8 as PC_ADDRESS_1,
$9 as PC_ADDRESS_2,
$10 as PC_CITYST,
$11 as PC_ZIP,
$12 as PC_ZIP_EXT,
$13 as PC_TAX_CODE,
$14 as PC_AGENT,
$15 as PC_MEMBER_NUMBER,
$16 as PC_ENCUMBRANCE,
$17 as PC_COMPANY,
$18 as PC_STATUS,
$19 as PC_SSNO_1,
$20 as PC_SSNO_2,
$21 as PC_STATE,
$22 as PC_ALPHA_2,
$23 as LOAD_DT,
$24 as FEED_IND,
$25 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 	
	A.*
	,B.FEED_DT,B.FEED_IND
FROM 
	DB_T_CORE_MEMBXREF_PROD.ASICPOLS A
	JOIN
	DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
	ON 1=1
WHERE
	TABLENAME = ''ASICPOLS''
) SRC
)
);


-- Component exp_Pass_Through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Pass_Through AS
(
SELECT
SQ_ASICPOLS.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
SQ_ASICPOLS.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_ASICPOLS.PC_ALPHA_CODE as PC_ALPHA_CODE,
SQ_ASICPOLS.PC_EFF_DATE as PC_EFF_DATE,
SQ_ASICPOLS.PC_EXP_DATE as PC_EXP_DATE,
SQ_ASICPOLS.PC_NAME_1 as PC_NAME_1,
SQ_ASICPOLS.PC_NAME_2 as PC_NAME_2,
SQ_ASICPOLS.PC_ADDRESS_1 as PC_ADDRESS_1,
SQ_ASICPOLS.PC_ADDRESS_2 as PC_ADDRESS_2,
SQ_ASICPOLS.PC_CITYST as PC_CITYST,
SQ_ASICPOLS.PC_ZIP as PC_ZIP,
SQ_ASICPOLS.PC_ZIP_EXT as PC_ZIP_EXT,
SQ_ASICPOLS.PC_TAX_CODE as PC_TAX_CODE,
SQ_ASICPOLS.PC_AGENT as PC_AGENT,
SQ_ASICPOLS.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
SQ_ASICPOLS.PC_ENCUMBRANCE as PC_ENCUMBRANCE,
SQ_ASICPOLS.PC_COMPANY as PC_COMPANY,
SQ_ASICPOLS.PC_STATUS as PC_STATUS,
SQ_ASICPOLS.PC_SSNO_1 as PC_SSNO_1,
SQ_ASICPOLS.PC_SSNO_2 as PC_SSNO_2,
SQ_ASICPOLS.PC_STATE as PC_STATE,
SQ_ASICPOLS.PC_ALPHA_2 as PC_ALPHA_2,
SQ_ASICPOLS.LOAD_DT as LOAD_DT,
SQ_ASICPOLS.FEED_IND as FEED_IND,
SQ_ASICPOLS.source_record_id
FROM
SQ_ASICPOLS
);


-- Component STG_ASICPOLS, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_ASICPOLS
(
SC_SERVICE_CENTER,
SC_POLICY_NUM,
PC_ALPHA_CODE,
PC_EFF_DATE,
PC_EXP_DATE,
PC_NAME_1,
PC_NAME_2,
PC_ADDRESS_1,
PC_ADDRESS_2,
PC_CITYST,
PC_ZIP,
PC_ZIP_EXT,
PC_TAX_CODE,
PC_AGENT,
PC_MEMBER_NUMBER,
PC_ENCUMBRANCE,
PC_COMPANY,
PC_STATUS,
PC_SSNO_1,
PC_SSNO_2,
PC_STATE,
PC_ALPHA_2,
LOAD_DT,
FEED_IND
)
SELECT
exp_Pass_Through.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_Pass_Through.SC_POLICY_NUM as SC_POLICY_NUM,
exp_Pass_Through.PC_ALPHA_CODE as PC_ALPHA_CODE,
exp_Pass_Through.PC_EFF_DATE as PC_EFF_DATE,
exp_Pass_Through.PC_EXP_DATE as PC_EXP_DATE,
exp_Pass_Through.PC_NAME_1 as PC_NAME_1,
exp_Pass_Through.PC_NAME_2 as PC_NAME_2,
exp_Pass_Through.PC_ADDRESS_1 as PC_ADDRESS_1,
exp_Pass_Through.PC_ADDRESS_2 as PC_ADDRESS_2,
exp_Pass_Through.PC_CITYST as PC_CITYST,
exp_Pass_Through.PC_ZIP as PC_ZIP,
exp_Pass_Through.PC_ZIP_EXT as PC_ZIP_EXT,
exp_Pass_Through.PC_TAX_CODE as PC_TAX_CODE,
exp_Pass_Through.PC_AGENT as PC_AGENT,
exp_Pass_Through.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
exp_Pass_Through.PC_ENCUMBRANCE as PC_ENCUMBRANCE,
exp_Pass_Through.PC_COMPANY as PC_COMPANY,
exp_Pass_Through.PC_STATUS as PC_STATUS,
exp_Pass_Through.PC_SSNO_1 as PC_SSNO_1,
exp_Pass_Through.PC_SSNO_2 as PC_SSNO_2,
exp_Pass_Through.PC_STATE as PC_STATE,
exp_Pass_Through.PC_ALPHA_2 as PC_ALPHA_2,
exp_Pass_Through.LOAD_DT as LOAD_DT,
exp_Pass_Through.FEED_IND as FEED_IND
FROM
exp_Pass_Through;


END; ';