-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_FARMCLAIMTOTALS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_FARMCLAIMTOTALS, Type Pre SQL 
DELETE  FROM DB_T_STAG_MEMBXREF_PROD.STG_FARMCLAIMTOTALS where load_dt in
 (select distinct a.load_dt from DB_T_STAG_MEMBXREF_PROD.STG_FARMCLAIMTOTALS A
 ,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
 A.LOAD_DT = B.FEED_DT
 AND B.TABLENAME = ''FARMCLAIMTOTALS'');


-- Component SQ_FARMCLAIMTOTALS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMCLAIMTOTALS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_CLMT_NDX,
$3 as RFD_YR,
$4 as RFD_DWELL,
$5 as RFD_UNSCH,
$6 as RFD_ADDL,
$7 as RFD_LIAB,
$8 as RFD_MED,
$9 as RFD_OUTBLDG,
$10 as RFD_PD,
$11 as RFD_NMED,
$12 as RFD_LVSTK,
$13 as RFD_MACH,
$14 as RFD_TOT_CLMS,
$15 as RFD_TOT_AMT,
$16 as FEED_DT,
$17 as FEED_IND,
$18 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELect SC_POLICY_NUM,
RFD_CLMT_NDX,
RFD_YR,
RFD_DWELL,
RFD_UNSCH,
RFD_ADDL,
RFD_LIAB,
RFD_MED,
RFD_OUTBLDG,
RFD_PD,
RFD_NMED,
RFD_LVSTK,
RFD_MACH,
RFD_TOT_CLMS,
RFD_TOT_AMT,
B.FEED_DT,B.FEED_IND
FROM 
	DB_T_STAG_MEMBXREF_PROD.FARMCLAIMTOTALS A
	JOIN
	DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
	ON 1=1
WHERE
	TABLENAME = ''FARMCLAIMTOTALS''
) SRC
)
);


-- Component Exp_trans, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_trans AS
(
SELECT
SQ_FARMCLAIMTOTALS.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMCLAIMTOTALS.RFD_CLMT_NDX as RFD_CLMT_NDX,
SQ_FARMCLAIMTOTALS.RFD_YR as RFD_YR,
SQ_FARMCLAIMTOTALS.RFD_DWELL as RFD_DWELL,
SQ_FARMCLAIMTOTALS.RFD_UNSCH as RFD_UNSCH,
SQ_FARMCLAIMTOTALS.RFD_ADDL as RFD_ADDL,
SQ_FARMCLAIMTOTALS.RFD_LIAB as RFD_LIAB,
SQ_FARMCLAIMTOTALS.RFD_MED as RFD_MED,
SQ_FARMCLAIMTOTALS.RFD_OUTBLDG as RFD_OUTBLDG,
SQ_FARMCLAIMTOTALS.RFD_PD as RFD_PD,
SQ_FARMCLAIMTOTALS.RFD_NMED as RFD_NMED,
SQ_FARMCLAIMTOTALS.RFD_LVSTK as RFD_LVSTK,
SQ_FARMCLAIMTOTALS.RFD_MACH as RFD_MACH,
SQ_FARMCLAIMTOTALS.RFD_TOT_CLMS as RFD_TOT_CLMS,
SQ_FARMCLAIMTOTALS.RFD_TOT_AMT as RFD_TOT_AMT,
TO_DATE ( SQ_FARMCLAIMTOTALS.FEED_DT  ) as Out_FEED_DT,
SQ_FARMCLAIMTOTALS.FEED_IND as FEED_IND,
SQ_FARMCLAIMTOTALS.source_record_id
FROM
SQ_FARMCLAIMTOTALS
);


-- Component STG_FARMCLAIMTOTALS, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_FARMCLAIMTOTALS
(
SC_POLICY_NUM,
RFD_CLMT_NDX,
RFD_YR,
RFD_DWELL,
RFD_UNSCH,
RFD_ADDL,
RFD_LIAB,
RFD_MED,
RFD_OUTBLDG,
RFD_PD,
RFD_NMED,
RFD_LVSTK,
RFD_MACH,
RFD_TOT_CLMS,
RFD_TOT_AMT,
LOAD_DT,
FEED_IND
)
SELECT
Exp_trans.SC_POLICY_NUM as SC_POLICY_NUM,
Exp_trans.RFD_CLMT_NDX as RFD_CLMT_NDX,
Exp_trans.RFD_YR as RFD_YR,
Exp_trans.RFD_DWELL as RFD_DWELL,
Exp_trans.RFD_UNSCH as RFD_UNSCH,
Exp_trans.RFD_ADDL as RFD_ADDL,
Exp_trans.RFD_LIAB as RFD_LIAB,
Exp_trans.RFD_MED as RFD_MED,
Exp_trans.RFD_OUTBLDG as RFD_OUTBLDG,
Exp_trans.RFD_PD as RFD_PD,
Exp_trans.RFD_NMED as RFD_NMED,
Exp_trans.RFD_LVSTK as RFD_LVSTK,
Exp_trans.RFD_MACH as RFD_MACH,
Exp_trans.RFD_TOT_CLMS as RFD_TOT_CLMS,
Exp_trans.RFD_TOT_AMT as RFD_TOT_AMT,
Exp_trans.Out_FEED_DT as LOAD_DT,
Exp_trans.FEED_IND as FEED_IND
FROM
Exp_trans;


END; ';