-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_FARMCOVERAGES("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_FARMCOVERAGES, Type Pre SQL 
DELETE  FROM DB_T_STAG_MEMBXREF_PROD.STG_FARMCOVERAGES where load_dt in
 (select distinct a.load_dt from DB_T_STAG_MEMBXREF_PROD.STG_FARMCOVERAGES A
 ,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
 A.LOAD_DT = B.FEED_DT
 AND B.TABLENAME = ''FARMCOVERAGES'');


-- Component SQ_FARMCOVERAGES, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMCOVERAGES AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_COV_NDX,
$3 as RFD_TYPE_IND,
$4 as RFD_COV,
$5 as RFD_PRM,
$6 as RFD_DED,
$7 as RFD_PCOV,
$8 as RFD_PDED,
$9 as RFD_DT,
$10 as RFD_DED_DT,
$11 as FEED_DT,
$12 as FEED_IND,
$13 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT  
 A.*
 ,B.FEED_DT,B.FEED_IND
FROM 
 DB_T_STAG_MEMBXREF_PROD.FARMCOVERAGES A
 JOIN
 DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
 ON 1=1
WHERE
 TABLENAME = ''FARMCOVERAGES''
) SRC
)
);


-- Component Exp_trans, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_trans AS
(
SELECT
SQ_FARMCOVERAGES.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMCOVERAGES.RFD_COV_NDX as RFD_COV_NDX,
SQ_FARMCOVERAGES.RFD_TYPE_IND as RFD_TYPE_IND,
SQ_FARMCOVERAGES.RFD_COV as RFD_COV,
SQ_FARMCOVERAGES.RFD_PRM as RFD_PRM,
SQ_FARMCOVERAGES.RFD_DED as RFD_DED,
SQ_FARMCOVERAGES.RFD_PCOV as RFD_PCOV,
SQ_FARMCOVERAGES.RFD_PDED as RFD_PDED,
SQ_FARMCOVERAGES.RFD_DT as RFD_DT,
SQ_FARMCOVERAGES.RFD_DED_DT as RFD_DED_DT,
SQ_FARMCOVERAGES.FEED_DT as FEED_DT,
SQ_FARMCOVERAGES.FEED_IND as FEED_IND,
SQ_FARMCOVERAGES.source_record_id
FROM
SQ_FARMCOVERAGES
);


-- Component STG_FARMCOVERAGES, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_FARMCOVERAGES
(
SC_POLICY_NUM,
RFD_COV_NDX,
RFD_TYPE_IND,
RFD_COV,
RFD_PRM,
RFD_DED,
RFD_PCOV,
RFD_PDED,
RFD_DT,
RFD_DED_DT,
LOAD_DT,
FEED_IND
)
SELECT
Exp_trans.SC_POLICY_NUM as SC_POLICY_NUM,
Exp_trans.RFD_COV_NDX as RFD_COV_NDX,
Exp_trans.RFD_TYPE_IND as RFD_TYPE_IND,
Exp_trans.RFD_COV as RFD_COV,
Exp_trans.RFD_PRM as RFD_PRM,
Exp_trans.RFD_DED as RFD_DED,
Exp_trans.RFD_PCOV as RFD_PCOV,
Exp_trans.RFD_PDED as RFD_PDED,
Exp_trans.RFD_DT as RFD_DT,
Exp_trans.RFD_DED_DT as RFD_DED_DT,
Exp_trans.FEED_DT as LOAD_DT,
Exp_trans.FEED_IND as FEED_IND
FROM
Exp_trans;


END; ';