-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_FARMDWLS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_FARMDWLS, Type Pre SQL 
DELETE FROM DB_T_STAG_MEMBXREF_PROD.STG_FARMDWLS where load_dt in
 (select distinct a.load_dt from DB_T_STAG_MEMBXREF_PROD.STG_FARMDWLS A
 ,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
 A.LOAD_DT = B.FEED_DT
 AND B.TABLENAME = ''FARMDWLS'');


-- Component SQ_FARMDWLS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMDWLS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_DWL_NDX,
$3 as RFD_DWL_CLASS,
$4 as RFD_DWL_DED,
$5 as RFD_DWL_PREM,
$6 as RFD_DWL_COV,
$7 as RFD_DWL_UNSCH,
$8 as RFD_DWL_ADDL,
$9 as RFD_DWL_HS,
$10 as RFD_DWL_CNSTYR,
$11 as RFD_INFL_DWL_IND,
$12 as RFD_DWL_CNTY,
$13 as RFD_DWL_FO85,
$14 as RFD_DWL_FO1,
$15 as RFD_DWL_FO45,
$16 as RFD_PDWL_CLASS,
$17 as RFD_PDWL_DED,
$18 as RFD_PDWL_COV,
$19 as RFD_PDWL_UNSCH,
$20 as RFD_DWL_COV_DT,
$21 as RFD_DWL_BCOV_DT,
$22 as FEED_DT,
$23 as FEED_IND,
$24 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT SC_POLICY_NUM,
RFD_DWL_NDX,
RFD_DWL_CLASS,
RFD_DWL_DED,
RFD_DWL_PREM,
RFD_DWL_COV,
RFD_DWL_UNSCH,
RFD_DWL_ADDL,
RFD_DWL_HS,
RFD_DWL_CNSTYR,
RFD_INFL_DWL_IND,
RFD_DWL_CNTY,
RFD_DWL_FO85,
RFD_DWL_FO1,
RFD_DWL_FO45,
RFD_PDWL_CLASS,
RFD_PDWL_DED,
RFD_PDWL_COV,
RFD_PDWL_UNSCH,
RFD_DWL_COV_DT,
RFD_DWL_BCOV_DT,
B.FEED_DT,B.FEED_IND
FROM 
 DB_T_STAG_MEMBXREF_PROD.FARMDWLS A
 JOIN
 DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
 ON 1=1
WHERE
 TABLENAME = ''FARMDWLS''
) SRC
)
);


-- Component Exp_Trans, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_Trans AS
(
SELECT
SQ_FARMDWLS.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMDWLS.RFD_DWL_NDX as RFD_DWL_NDX,
SQ_FARMDWLS.RFD_DWL_CLASS as RFD_DWL_CLASS,
SQ_FARMDWLS.RFD_DWL_DED as RFD_DWL_DED,
SQ_FARMDWLS.RFD_DWL_PREM as RFD_DWL_PREM,
SQ_FARMDWLS.RFD_DWL_COV as RFD_DWL_COV,
SQ_FARMDWLS.RFD_DWL_UNSCH as RFD_DWL_UNSCH,
SQ_FARMDWLS.RFD_DWL_ADDL as RFD_DWL_ADDL,
SQ_FARMDWLS.RFD_DWL_HS as RFD_DWL_HS,
SQ_FARMDWLS.RFD_DWL_CNSTYR as RFD_DWL_CNSTYR,
SQ_FARMDWLS.RFD_INFL_DWL_IND as RFD_INFL_DWL_IND,
SQ_FARMDWLS.RFD_DWL_CNTY as RFD_DWL_CNTY,
SQ_FARMDWLS.RFD_DWL_FO85 as RFD_DWL_FO85,
SQ_FARMDWLS.RFD_DWL_FO1 as RFD_DWL_FO1,
SQ_FARMDWLS.RFD_DWL_FO45 as RFD_DWL_FO45,
SQ_FARMDWLS.RFD_PDWL_CLASS as RFD_PDWL_CLASS,
SQ_FARMDWLS.RFD_PDWL_DED as RFD_PDWL_DED,
SQ_FARMDWLS.RFD_PDWL_COV as RFD_PDWL_COV,
SQ_FARMDWLS.RFD_PDWL_UNSCH as RFD_PDWL_UNSCH,
SQ_FARMDWLS.RFD_DWL_COV_DT as RFD_DWL_COV_DT,
SQ_FARMDWLS.RFD_DWL_BCOV_DT as RFD_DWL_BCOV_DT,
SQ_FARMDWLS.FEED_DT as FEED_DT,
SQ_FARMDWLS.FEED_IND as FEED_IND,
SQ_FARMDWLS.source_record_id
FROM
SQ_FARMDWLS
);


-- Component STG_FARMDWLS, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_FARMDWLS
(
SC_POLICY_NUM,
RFD_DWL_NDX,
RFD_DWL_CLASS,
RFD_DWL_DED,
RFD_DWL_PREM,
RFD_DWL_COV,
RFD_DWL_UNSCH,
RFD_DWL_ADDL,
RFD_DWL_HS,
RFD_DWL_CNSTYR,
RFD_INFL_DWL_IND,
RFD_DWL_CNTY,
RFD_DWL_FO85,
RFD_DWL_FO1,
RFD_DWL_FO45,
RFD_PDWL_CLASS,
RFD_PDWL_DED,
RFD_PDWL_COV,
RFD_PDWL_UNSCH,
RFD_DWL_COV_DT,
RFD_DWL_BCOV_DT,
LOAD_DT,
FEED_IND
)
SELECT
Exp_Trans.SC_POLICY_NUM as SC_POLICY_NUM,
Exp_Trans.RFD_DWL_NDX as RFD_DWL_NDX,
Exp_Trans.RFD_DWL_CLASS as RFD_DWL_CLASS,
Exp_Trans.RFD_DWL_DED as RFD_DWL_DED,
Exp_Trans.RFD_DWL_PREM as RFD_DWL_PREM,
Exp_Trans.RFD_DWL_COV as RFD_DWL_COV,
Exp_Trans.RFD_DWL_UNSCH as RFD_DWL_UNSCH,
Exp_Trans.RFD_DWL_ADDL as RFD_DWL_ADDL,
Exp_Trans.RFD_DWL_HS as RFD_DWL_HS,
Exp_Trans.RFD_DWL_CNSTYR as RFD_DWL_CNSTYR,
Exp_Trans.RFD_INFL_DWL_IND as RFD_INFL_DWL_IND,
Exp_Trans.RFD_DWL_CNTY as RFD_DWL_CNTY,
Exp_Trans.RFD_DWL_FO85 as RFD_DWL_FO85,
Exp_Trans.RFD_DWL_FO1 as RFD_DWL_FO1,
Exp_Trans.RFD_DWL_FO45 as RFD_DWL_FO45,
Exp_Trans.RFD_PDWL_CLASS as RFD_PDWL_CLASS,
Exp_Trans.RFD_PDWL_DED as RFD_PDWL_DED,
Exp_Trans.RFD_PDWL_COV as RFD_PDWL_COV,
Exp_Trans.RFD_PDWL_UNSCH as RFD_PDWL_UNSCH,
Exp_Trans.RFD_DWL_COV_DT as RFD_DWL_COV_DT,
Exp_Trans.RFD_DWL_BCOV_DT as RFD_DWL_BCOV_DT,
Exp_Trans.FEED_DT as LOAD_DT,
Exp_Trans.FEED_IND as FEED_IND
FROM
Exp_Trans;


END; ';