-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_FARMLOCS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_FARMLOCS, Type Pre SQL 
DELETE FROM DB_T_STAG_MEMBXREF_PROD.STG_FARMLOCS where load_dt in
( select distinct a.load_dt from	DB_T_STAG_MEMBXREF_PROD.STG_FARMLOCS A
	,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
	A.LOAD_DT = B.FEED_DT
	AND B.TABLENAME = ''FARMLOCS'');


-- Component SQ_FARMLOCS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMLOCS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_LOC_NDX,
$3 as RFD_LOC_DESC,
$4 as RFD_LOC_ZIP,
$5 as RFD_LOC_BLDG_IND,
$6 as RFD_LOC_ACRES,
$7 as FEED_DT,
$8 as FEED_IND,
$9 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT SC_POLICY_NUM,RFD_LOC_NDX,RFD_LOC_DESC,RFD_LOC_ZIP,RFD_LOC_BLDG_IND,RFD_LOC_ACRES
	,B.FEED_DT,B.FEED_IND
FROM 
	DB_T_STAG_MEMBXREF_PROD.FARMLOCS A
	JOIN
	DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
	ON 1=1
WHERE
	TABLENAME = ''FARMLOCS''
) SRC
)
);


-- Component exp_trans, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_trans AS
(
SELECT
SQ_FARMLOCS.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMLOCS.RFD_LOC_NDX as RFD_LOC_NDX,
SQ_FARMLOCS.RFD_LOC_DESC as RFD_LOC_DESC,
SQ_FARMLOCS.RFD_LOC_ZIP as RFD_LOC_ZIP,
SQ_FARMLOCS.RFD_LOC_BLDG_IND as RFD_LOC_BLDG_IND,
SQ_FARMLOCS.RFD_LOC_ACRES as RFD_LOC_ACRES,
TO_DATE ( SQ_FARMLOCS.FEED_DT ) as o_FEED_DT,
SQ_FARMLOCS.FEED_IND as FEED_IND,
SQ_FARMLOCS.source_record_id
FROM
SQ_FARMLOCS
);


-- Component STG_FARMLOCS, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_FARMLOCS
(
SC_POLICY_NUM,
RFD_LOC_NDX,
RFD_LOC_DESC,
RFD_LOC_ZIP,
RFD_LOC_BLDG_IND,
RFD_LOC_ACRES,
LOAD_DT,
FEED_IND
)
SELECT
exp_trans.SC_POLICY_NUM as SC_POLICY_NUM,
exp_trans.RFD_LOC_NDX as RFD_LOC_NDX,
exp_trans.RFD_LOC_DESC as RFD_LOC_DESC,
exp_trans.RFD_LOC_ZIP as RFD_LOC_ZIP,
exp_trans.RFD_LOC_BLDG_IND as RFD_LOC_BLDG_IND,
exp_trans.RFD_LOC_ACRES as RFD_LOC_ACRES,
exp_trans.o_FEED_DT as LOAD_DT,
exp_trans.FEED_IND as FEED_IND
FROM
exp_trans;


END; ';