-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_FARMMACH("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_STG_MEMBXREF_TRIGGER, Type Pre SQL 
DELETE  FROM DB_T_STAG_MEMBXREF_PROD.STG_FARMMACH where load_dt in (
 select distinct a.load_dt from   DB_T_STAG_MEMBXREF_PROD.STG_FARMMACH A
    ,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
    A.LOAD_DT = B.FEED_DT
    AND B.TABLENAME = ''FARMMACH'');


-- Component SQ_STG_MEMBXREF_TRIGGER, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_STG_MEMBXREF_TRIGGER AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_MACH_NDX,
$3 as RFD_MACH_YR,
$4 as RFD_MACH_DESC,
$5 as RFD_MACH_DESC2,
$6 as RFD_MACH_ID,
$7 as RFD_MACH_ITM_COV,
$8 as LOAD_DT,
$9 as FEED_IND,
$10 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT  
    A.*
    ,B.FEED_DT,B.FEED_IND
FROM 
    DB_T_STAG_MEMBXREF_PROD.FARMMACH A
    JOIN
    DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
    ON 1=1
WHERE
    TABLENAME = ''FARMMACH''
) SRC
)
);


-- Component EXP_LOAD_STG_FARMMACH, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXP_LOAD_STG_FARMMACH AS
(
SELECT
SQ_STG_MEMBXREF_TRIGGER.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_STG_MEMBXREF_TRIGGER.RFD_MACH_NDX as RFD_MACH_NDX,
SQ_STG_MEMBXREF_TRIGGER.RFD_MACH_YR as RFD_MACH_YR,
SQ_STG_MEMBXREF_TRIGGER.RFD_MACH_DESC as RFD_MACH_DESC,
SQ_STG_MEMBXREF_TRIGGER.RFD_MACH_DESC2 as RFD_MACH_DESC2,
SQ_STG_MEMBXREF_TRIGGER.RFD_MACH_ID as RFD_MACH_ID,
SQ_STG_MEMBXREF_TRIGGER.RFD_MACH_ITM_COV as RFD_MACH_ITM_COV,
SQ_STG_MEMBXREF_TRIGGER.LOAD_DT as LOAD_DT,
SQ_STG_MEMBXREF_TRIGGER.FEED_IND as FEED_IND,
SQ_STG_MEMBXREF_TRIGGER.source_record_id
FROM
SQ_STG_MEMBXREF_TRIGGER
);


-- Component STG_FARMMACH, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_FARMMACH
(
SC_POLICY_NUM,
RFD_MACH_NDX,
RFD_MACH_YR,
RFD_MACH_DESC,
RFD_MACH_DESC2,
RFD_MACH_ID,
RFD_MACH_ITM_COV,
LOAD_DT,
FEED_IND
)
SELECT
EXP_LOAD_STG_FARMMACH.SC_POLICY_NUM as SC_POLICY_NUM,
EXP_LOAD_STG_FARMMACH.RFD_MACH_NDX as RFD_MACH_NDX,
EXP_LOAD_STG_FARMMACH.RFD_MACH_YR as RFD_MACH_YR,
EXP_LOAD_STG_FARMMACH.RFD_MACH_DESC as RFD_MACH_DESC,
EXP_LOAD_STG_FARMMACH.RFD_MACH_DESC2 as RFD_MACH_DESC2,
EXP_LOAD_STG_FARMMACH.RFD_MACH_ID as RFD_MACH_ID,
EXP_LOAD_STG_FARMMACH.RFD_MACH_ITM_COV as RFD_MACH_ITM_COV,
EXP_LOAD_STG_FARMMACH.LOAD_DT as LOAD_DT,
EXP_LOAD_STG_FARMMACH.FEED_IND as FEED_IND
FROM
EXP_LOAD_STG_FARMMACH;


END; ';