-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_FARMMORT("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_STG_MEMBXREF_TRIGGER, Type Pre SQL 
DELETE FROM DB_T_STAG_MEMBXREF_PROD.STG_FARMMORT where load_dt in
  ( select distinct a.load_dt from  DB_T_STAG_MEMBXREF_PROD.STG_FARMMORT A
    ,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
    A.LOAD_DT = B.FEED_DT
    AND B.TABLENAME = ''FARMMORT'');


-- Component SQ_STG_MEMBXREF_TRIGGER, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_STG_MEMBXREF_TRIGGER AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_MORT_NDX,
$3 as RFD_MORT_NAME1,
$4 as RFD_MORT_NAME2,
$5 as RFD_MORT_ADDR1,
$6 as RFD_MORT_ADDR2,
$7 as RFD_MORT_CTY,
$8 as RFD_MORT_ST,
$9 as RFD_MORT_ZIP,
$10 as RFD_LOAN_NUM,
$11 as RFD_MORT_COLL1_TYP,
$12 as RFD_MORT_COLL1_OCC,
$13 as RFD_MORT_COLL2_TYP,
$14 as RFD_MORT_COLL2_OCC,
$15 as RFD_MORT_COLL3_TYP,
$16 as RFD_MORT_COLL3_OCC,
$17 as RFD_MORT_COLL4_TYP,
$18 as RFD_MORT_COLL4_OCC,
$19 as RFD_MORT_COLL5_TYP,
$20 as RFD_MORT_COLL5_OCC,
$21 as RFD_MORT_COLL6_TYP,
$22 as RFD_MORT_COLL6_OCC,
$23 as LOAD_DT,
$24 as FEED_IND,
$25 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT  
    A.*
    ,B.FEED_DT,B.FEED_IND
FROM 
    DB_T_STAG_MEMBXREF_PROD.FARMMORT A
    JOIN
    DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
    ON 1=1
WHERE
    TABLENAME = ''FARMMORT''
) SRC
)
);


-- Component EXP_LOAD_STG_FARMMORT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXP_LOAD_STG_FARMMORT AS
(
SELECT
SQ_STG_MEMBXREF_TRIGGER.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_NDX as RFD_MORT_NDX,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_NAME1 as RFD_MORT_NAME1,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_NAME2 as RFD_MORT_NAME2,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_ADDR1 as RFD_MORT_ADDR1,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_ADDR2 as RFD_MORT_ADDR2,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_CTY as RFD_MORT_CTY,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_ST as RFD_MORT_ST,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_ZIP as RFD_MORT_ZIP,
SQ_STG_MEMBXREF_TRIGGER.RFD_LOAN_NUM as RFD_LOAN_NUM,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_COLL1_TYP as RFD_MORT_COLL1_TYP,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_COLL1_OCC as RFD_MORT_COLL1_OCC,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_COLL2_TYP as RFD_MORT_COLL2_TYP,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_COLL2_OCC as RFD_MORT_COLL2_OCC,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_COLL3_TYP as RFD_MORT_COLL3_TYP,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_COLL3_OCC as RFD_MORT_COLL3_OCC,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_COLL4_TYP as RFD_MORT_COLL4_TYP,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_COLL4_OCC as RFD_MORT_COLL4_OCC,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_COLL5_TYP as RFD_MORT_COLL5_TYP,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_COLL5_OCC as RFD_MORT_COLL5_OCC,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_COLL6_TYP as RFD_MORT_COLL6_TYP,
SQ_STG_MEMBXREF_TRIGGER.RFD_MORT_COLL6_OCC as RFD_MORT_COLL6_OCC,
SQ_STG_MEMBXREF_TRIGGER.LOAD_DT as LOAD_DT,
SQ_STG_MEMBXREF_TRIGGER.FEED_IND as FEED_IND,
SQ_STG_MEMBXREF_TRIGGER.source_record_id
FROM
SQ_STG_MEMBXREF_TRIGGER
);


-- Component STG_FARMMORT, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_FARMMORT
(
SC_POLICY_NUM,
RFD_MORT_NDX,
RFD_MORT_NAME1,
RFD_MORT_NAME2,
RFD_MORT_ADDR1,
RFD_MORT_ADDR2,
RFD_MORT_CTY,
RFD_MORT_ST,
RFD_MORT_ZIP,
RFD_LOAN_NUM,
RFD_MORT_COLL1_TYP,
RFD_MORT_COLL1_OCC,
RFD_MORT_COLL2_TYP,
RFD_MORT_COLL2_OCC,
RFD_MORT_COLL3_TYP,
RFD_MORT_COLL3_OCC,
RFD_MORT_COLL4_TYP,
RFD_MORT_COLL4_OCC,
RFD_MORT_COLL5_TYP,
RFD_MORT_COLL5_OCC,
RFD_MORT_COLL6_TYP,
RFD_MORT_COLL6_OCC,
LOAD_DT,
FEED_IND
)
SELECT
EXP_LOAD_STG_FARMMORT.SC_POLICY_NUM as SC_POLICY_NUM,
EXP_LOAD_STG_FARMMORT.RFD_MORT_NDX as RFD_MORT_NDX,
EXP_LOAD_STG_FARMMORT.RFD_MORT_NAME1 as RFD_MORT_NAME1,
EXP_LOAD_STG_FARMMORT.RFD_MORT_NAME2 as RFD_MORT_NAME2,
EXP_LOAD_STG_FARMMORT.RFD_MORT_ADDR1 as RFD_MORT_ADDR1,
EXP_LOAD_STG_FARMMORT.RFD_MORT_ADDR2 as RFD_MORT_ADDR2,
EXP_LOAD_STG_FARMMORT.RFD_MORT_CTY as RFD_MORT_CTY,
EXP_LOAD_STG_FARMMORT.RFD_MORT_ST as RFD_MORT_ST,
EXP_LOAD_STG_FARMMORT.RFD_MORT_ZIP as RFD_MORT_ZIP,
EXP_LOAD_STG_FARMMORT.RFD_LOAN_NUM as RFD_LOAN_NUM,
EXP_LOAD_STG_FARMMORT.RFD_MORT_COLL1_TYP as RFD_MORT_COLL1_TYP,
EXP_LOAD_STG_FARMMORT.RFD_MORT_COLL1_OCC as RFD_MORT_COLL1_OCC,
EXP_LOAD_STG_FARMMORT.RFD_MORT_COLL2_TYP as RFD_MORT_COLL2_TYP,
EXP_LOAD_STG_FARMMORT.RFD_MORT_COLL2_OCC as RFD_MORT_COLL2_OCC,
EXP_LOAD_STG_FARMMORT.RFD_MORT_COLL3_TYP as RFD_MORT_COLL3_TYP,
EXP_LOAD_STG_FARMMORT.RFD_MORT_COLL3_OCC as RFD_MORT_COLL3_OCC,
EXP_LOAD_STG_FARMMORT.RFD_MORT_COLL4_TYP as RFD_MORT_COLL4_TYP,
EXP_LOAD_STG_FARMMORT.RFD_MORT_COLL4_OCC as RFD_MORT_COLL4_OCC,
EXP_LOAD_STG_FARMMORT.RFD_MORT_COLL5_TYP as RFD_MORT_COLL5_TYP,
EXP_LOAD_STG_FARMMORT.RFD_MORT_COLL5_OCC as RFD_MORT_COLL5_OCC,
EXP_LOAD_STG_FARMMORT.RFD_MORT_COLL6_TYP as RFD_MORT_COLL6_TYP,
EXP_LOAD_STG_FARMMORT.RFD_MORT_COLL6_OCC as RFD_MORT_COLL6_OCC,
EXP_LOAD_STG_FARMMORT.LOAD_DT as LOAD_DT,
EXP_LOAD_STG_FARMMORT.FEED_IND as FEED_IND
FROM
EXP_LOAD_STG_FARMMORT;


END; ';