-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BIBASE_PLCY_XREF_INS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE start_dttm TIMESTAMP;
end_dttm TIMESTAMP;
PRCS_ID INTEGER;
CAL_END_MTH_ID integer;

BEGIN 
start_dttm := CURRENT_TIMESTAMP();
end_dttm := CURRENT_TIMESTAMP();
PRCS_ID := 1; 
CAL_END_MTH_ID :=1;

-- Component SQ_AGMT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGMT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as PLCY_NBR,
$2 as LOB_TYPE,
$3 as SRC_CD,
$4 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT DISTINCT   PLCY_NBR, ''AUTO'' LOB_TYPE , ''LGCY'' SRC_CD FROM DB_T_CORE_AN_PROD.AUTO_POLICY_SUMM WHERE MO_ID=:CAL_END_MTH_ID

UNION              

SELECT DISTINCT PLCY_NBR , ''HOME'' LOB_TYPE , ''LGCY'' SRC_CD FROM DB_T_CORE_AN_PROD.HOME_POLICY_SUMM WHERE MO_ID=:CAL_END_MTH_ID

UNION

SELECT DISTINCT HOST_AGMT_NUM, CASE WHEN INSRNC_LOB_TYPE_CD=''HO'' THEN ''HOME''

WHEN INSRNC_LOB_TYPE_CD=''PA'' THEN ''AUTO'' END LOB_TYPE,''GW'' SRC_CD FROM DB_T_PROD_CORE.AGMT AG

JOIN DB_T_PROD_CORE.AGMT_PROD AP ON AG.AGMT_ID=AP.AGMT_ID

JOIN DB_T_PROD_CORE.PROD P ON P.PROD_ID=AP.PROD_ID

WHERE AG.AGMT_TYPE_CD=''PPV''

AND EXTRACT(YEAR FROM AG.MODL_EFF_DTTM)*100+EXTRACT(MONTH FROM MODL_EFF_DTTM)<=:CAL_END_MTH_ID

AND EXTRACT(YEAR FROM AG.MODL_ACTL_END_DTTM)*100+EXTRACT(MONTH FROM MODL_ACTL_END_DTTM)>=:CAL_END_MTH_ID

AND INSRNC_LOB_TYPE_CD IN (''HO'',''PA'')
) SRC
)
);


-- Component LKP_PLCY_XREF, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_PLCY_XREF AS
(
SELECT
LKP.PLCY_ID,
LKP.PLCY_NBR,
LKP.SRC_CD_lkp,
LKP.EDW_STRT_DTTM_lkp,
SQ_AGMT.PLCY_NBR as in_PLCY_NBR,
SQ_AGMT.LOB_TYPE as LOB_TYPE,
SQ_AGMT.SRC_CD as SRC_CD,
SQ_AGMT.source_record_id,
ROW_NUMBER() OVER(PARTITION BY SQ_AGMT.source_record_id ORDER BY LKP.PLCY_ID asc,LKP.PLCY_NBR asc,LKP.SRC_CD_lkp asc,LKP.EDW_STRT_DTTM_lkp asc) RNK
FROM
SQ_AGMT
LEFT JOIN (
SELECT PLCY_XREF.PLCY_ID as PLCY_ID, PLCY_XREF.SRC_TYPE as SRC_CD_lkp, PLCY_XREF.EDW_STRT_DTTM as EDW_STRT_DTTM_lkp, PLCY_XREF.PLCY_NBR as PLCY_NBR FROM DB_V_PROD_PRES.PLCY_XREF
QUALIFY ROW_NUMBER() OVER(PARTITION BY PLCY_NBR ORDER BY EDW_END_DTTM DESC)=1
) LKP ON LKP.PLCY_NBR = SQ_AGMT.PLCY_NBR
QUALIFY RNK = 1
);


-- Component exp_hold_edw, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_hold_edw AS
(
SELECT
LKP_PLCY_XREF.PLCY_ID as PLCY_ID,
LKP_PLCY_XREF.in_PLCY_NBR as in_PLCY_NBR,
LKP_PLCY_XREF.LOB_TYPE as LOB_TYPE,
LKP_PLCY_XREF.SRC_CD as SRC_CD,
:PRCS_ID as PRCS_ID,
CURRENT_TIMESTAMP as EDW_STRT_DTTM,
CASE WHEN LKP_PLCY_XREF.PLCY_NBR IS NULL THEN ''I'' ELSE ( CASE WHEN MD5 ( LKP_PLCY_XREF.SRC_CD ) <> MD5 ( LKP_PLCY_XREF.SRC_CD_lkp ) THEN ''U'' ELSE ''R'' END ) END as out_flag,
LKP_PLCY_XREF.EDW_STRT_DTTM_lkp as EDW_STRT_DTTM_lkp,
TO_DATE ( ''9999-12-31 23:59:59.999999'' , ''YYYY-MM-DD HH24:MI:SS.FF6'' ) as EDW_END_DTTM,
LKP_PLCY_XREF.source_record_id
FROM
LKP_PLCY_XREF
);


-- Component rtr_INSERT_UPDATE_UPDATE, Type ROUTER Output Group UPDATE
CREATE OR REPLACE TEMPORARY TABLE rtr_INSERT_UPDATE_UPDATE AS
(SELECT
exp_hold_edw.PLCY_ID as PLCY_ID,
exp_hold_edw.LOB_TYPE as LOB_TYPE,
exp_hold_edw.SRC_CD as SRC_CD,
exp_hold_edw.PRCS_ID as PRCS_ID,
exp_hold_edw.EDW_STRT_DTTM as EDW_STRT_DTTM,
exp_hold_edw.in_PLCY_NBR as in_PLCY_NBR,
exp_hold_edw.out_flag as out_flag,
exp_hold_edw.EDW_STRT_DTTM_lkp as EDW_STRT_DTTM_lkp,
exp_hold_edw.EDW_END_DTTM as EDW_END_DTTM,
exp_hold_edw.source_record_id
FROM
exp_hold_edw
WHERE exp_hold_edw.out_flag = ''U'');


-- Component rtr_INSERT_UPDATE_insert, Type ROUTER Output Group insert
CREATE OR REPLACE TEMPORARY TABLE rtr_INSERT_UPDATE_insert AS
(SELECT
exp_hold_edw.PLCY_ID as PLCY_ID,
exp_hold_edw.LOB_TYPE as LOB_TYPE,
exp_hold_edw.SRC_CD as SRC_CD,
exp_hold_edw.PRCS_ID as PRCS_ID,
exp_hold_edw.EDW_STRT_DTTM as EDW_STRT_DTTM,
exp_hold_edw.in_PLCY_NBR as in_PLCY_NBR,
exp_hold_edw.out_flag as out_flag,
exp_hold_edw.EDW_STRT_DTTM_lkp as EDW_STRT_DTTM_lkp,
exp_hold_edw.EDW_END_DTTM as EDW_END_DTTM,
exp_hold_edw.source_record_id
FROM
exp_hold_edw
WHERE exp_hold_edw.out_flag = ''I'');


-- Component PLCY_XREF_ins, Type TARGET 
INSERT INTO DB_V_PROD_PRES.PLCY_XREF
(
PLCY_ID,
PLCY_NBR,
LOB_TYPE,
SRC_TYPE,
PRCS_ID,
EDW_STRT_DTTM
)
SELECT
row_number() over (order by 1) as PLCY_ID,
rtr_INSERT_UPDATE_insert.in_PLCY_NBR as PLCY_NBR,
rtr_INSERT_UPDATE_insert.LOB_TYPE as LOB_TYPE,
rtr_INSERT_UPDATE_insert.SRC_CD as SRC_TYPE,
rtr_INSERT_UPDATE_insert.PRCS_ID as PRCS_ID,
rtr_INSERT_UPDATE_insert.EDW_STRT_DTTM as EDW_STRT_DTTM
FROM
rtr_INSERT_UPDATE_insert;


-- Component upd_previous_record, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_previous_record AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
rtr_INSERT_UPDATE_UPDATE.PLCY_ID as PLCY_ID3,
rtr_INSERT_UPDATE_UPDATE.SRC_CD as SRC_CD3,
rtr_INSERT_UPDATE_UPDATE.EDW_STRT_DTTM as EDW_STRT_DTTM3,
rtr_INSERT_UPDATE_UPDATE.LOB_TYPE as LOB_TYPE3,
rtr_INSERT_UPDATE_UPDATE.in_PLCY_NBR as in_PLCY_NBR3,
rtr_INSERT_UPDATE_UPDATE.EDW_END_DTTM as EDW_END_DTTM3,
rtr_INSERT_UPDATE_UPDATE.PRCS_ID as PRCS_ID3,
0 as UPDATE_STRATEGY_ACTION,
rtr_INSERT_UPDATE_UPDATE.source_record_id
FROM
rtr_INSERT_UPDATE_UPDATE
);


-- Component exp_upd, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_upd AS
(
SELECT
upd_previous_record.PLCY_ID3 as PLCY_ID3,
upd_previous_record.SRC_CD3 as SRC_CD3,
upd_previous_record.EDW_STRT_DTTM3 as EDW_STRT_DTTM3,
upd_previous_record.LOB_TYPE3 as LOB_TYPE3,
upd_previous_record.in_PLCY_NBR3 as in_PLCY_NBR3,
upd_previous_record.EDW_END_DTTM3 as EDW_END_DTTM3,
upd_previous_record.PRCS_ID3 as PRCS_ID3,
upd_previous_record.source_record_id
FROM
upd_previous_record
);


-- Component PLCY_XREF_upd, Type TARGET 
INSERT INTO DB_V_PROD_PRES.PLCY_XREF
(
PLCY_ID,
PLCY_NBR,
LOB_TYPE,
SRC_TYPE,
PRCS_ID,
EDW_STRT_DTTM,
EDW_END_DTTM
)
SELECT
exp_upd.PLCY_ID3 as PLCY_ID,
exp_upd.in_PLCY_NBR3 as PLCY_NBR,
exp_upd.LOB_TYPE3 as LOB_TYPE,
exp_upd.SRC_CD3 as SRC_TYPE,
exp_upd.PRCS_ID3 as PRCS_ID,
exp_upd.EDW_STRT_DTTM3 as EDW_STRT_DTTM,
exp_upd.EDW_END_DTTM3 as EDW_END_DTTM
FROM
exp_upd;


-- Component PLCY_XREF_upd, Type Post SQL 
UPDATE DB_V_PROD_PRES.PLCY_XREF FROM 

(SELECT PLCY_ID, SRC_TYPE,EDW_STRT_DTTM, MAX(EDW_STRT_DTTM) OVER(PARTITION BY PLCY_ID ORDER BY EDW_STRT_DTTM ASC rows between 1 following and 1 following) - INTERVAL ''1 SECOND''

as lead1 FROM DB_V_PROD_PRES.PLCY_XREF) A

SET EDW_END_dTTM =LEAD1

WHERE A.PLCY_ID=PLCY_XREF.PLCY_ID

AND A.EDW_STRT_DTTM=PLCY_XREF.EDW_STRT_DTTM

AND A.SRC_TYPE=PLCY_XREF.SRC_TYPE

AND LEAD1 IS NOT NULL;


END; ';