-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_FARMNAME("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_STG_MEMBXREF_TRIGGER, Type Pre SQL 
DELETE  FROM DB_T_STAG_MEMBXREF_PROD.STG_FARMNAME where load_dt in
 ( select distinct a.load_dt from   DB_T_STAG_MEMBXREF_PROD.STG_FARMNAME A
    ,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
    A.LOAD_DT = B.FEED_DT
    AND B.TABLENAME = ''FARMNAME'');


-- Component SQ_STG_MEMBXREF_TRIGGER, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_STG_MEMBXREF_TRIGGER AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_NAME_NDX,
$3 as RFD_NAME_IND,
$4 as RFD_NAMED_NAME,
$5 as LOAD_DT,
$6 as FEED_IND,
$7 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT  
    A.*
    ,B.FEED_DT,B.FEED_IND
FROM 
    DB_T_STAG_MEMBXREF_PROD.FARMNAME A
    JOIN
    DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
    ON 1=1
WHERE
    TABLENAME = ''FARMNAME''
) SRC
)
);


-- Component EXP_LOAD_STG_FARMNAME, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXP_LOAD_STG_FARMNAME AS
(
SELECT
SQ_STG_MEMBXREF_TRIGGER.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_STG_MEMBXREF_TRIGGER.RFD_NAME_NDX as RFD_NAME_NDX,
SQ_STG_MEMBXREF_TRIGGER.RFD_NAME_IND as RFD_NAME_IND,
SQ_STG_MEMBXREF_TRIGGER.RFD_NAMED_NAME as RFD_NAMED_NAME,
SQ_STG_MEMBXREF_TRIGGER.LOAD_DT as LOAD_DT,
SQ_STG_MEMBXREF_TRIGGER.FEED_IND as FEED_IND,
SQ_STG_MEMBXREF_TRIGGER.source_record_id
FROM
SQ_STG_MEMBXREF_TRIGGER
);


-- Component STG_FARMNAME, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_FARMNAME
(
SC_POLICY_NUM,
RFD_NAME_NDX,
RFD_NAME_IND,
RFD_NAMED_NAME,
LOAD_DT,
FEED_IND
)
SELECT
EXP_LOAD_STG_FARMNAME.SC_POLICY_NUM as SC_POLICY_NUM,
EXP_LOAD_STG_FARMNAME.RFD_NAME_NDX as RFD_NAME_NDX,
EXP_LOAD_STG_FARMNAME.RFD_NAME_IND as RFD_NAME_IND,
EXP_LOAD_STG_FARMNAME.RFD_NAMED_NAME as RFD_NAMED_NAME,
EXP_LOAD_STG_FARMNAME.LOAD_DT as LOAD_DT,
EXP_LOAD_STG_FARMNAME.FEED_IND as FEED_IND
FROM
EXP_LOAD_STG_FARMNAME;


END; ';