-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_FARMPOLEND("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_FARMPOLEND, Type Pre SQL 
DELETE  FROM DB_T_STAG_MEMBXREF_PROD.STG_FARMPOLEND where load_dt in
(  select distinct a.load_dt from	DB_T_STAG_MEMBXREF_PROD.STG_FARMPOLEND A
	,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
	A.LOAD_DT = B.FEED_DT
	AND B.TABLENAME = ''FARMPOLEND'');


-- Component SQ_FARMPOLEND, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMPOLEND AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_END_NDX,
$3 as RFD_END_NO,
$4 as RFD_END_COV,
$5 as RFD_PEND_NO,
$6 as RFD_PEND_COV,
$7 as RFD_END_PRM,
$8 as RFD_END_DT,
$9 as B_FEED_DT,
$10 as B_FEED_IND,
$11 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
sELECT	SC_POLICY_NUM, RFD_END_NDX, RFD_END_NO, RFD_END_COV, RFD_PEND_NO,
		RFD_PEND_COV, RFD_END_PRM, RFD_END_DT
	,B.FEED_DT,B.FEED_IND
FROM 
	DB_T_STAG_MEMBXREF_PROD.FARMPOLEND A
	JOIN
	DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
	ON 1=1
WHERE
	TABLENAME = ''FARMPOLEND''
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_FARMPOLEND.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMPOLEND.RFD_END_NDX as RFD_END_NDX,
SQ_FARMPOLEND.RFD_END_NO as RFD_END_NO,
SQ_FARMPOLEND.RFD_END_COV as RFD_END_COV,
SQ_FARMPOLEND.RFD_PEND_NO as RFD_PEND_NO,
SQ_FARMPOLEND.RFD_PEND_COV as RFD_PEND_COV,
SQ_FARMPOLEND.RFD_END_PRM as RFD_END_PRM,
SQ_FARMPOLEND.RFD_END_DT as RFD_END_DT,
SQ_FARMPOLEND.B_FEED_DT as B_FEED_DT,
SQ_FARMPOLEND.B_FEED_IND as B_FEED_IND,
SQ_FARMPOLEND.source_record_id
FROM
SQ_FARMPOLEND
);


-- Component STG_FARMPOLEND, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_FARMPOLEND
(
SC_POLICY_NUM,
RFD_END_NDX,
RFD_END_NO,
RFD_END_COV,
RFD_PEND_NO,
RFD_PEND_COV,
RFD_END_PRM,
RFD_END_DT,
LOAD_DT,
FEED_IND
)
SELECT
EXPTRANS.SC_POLICY_NUM as SC_POLICY_NUM,
EXPTRANS.RFD_END_NDX as RFD_END_NDX,
EXPTRANS.RFD_END_NO as RFD_END_NO,
EXPTRANS.RFD_END_COV as RFD_END_COV,
EXPTRANS.RFD_PEND_NO as RFD_PEND_NO,
EXPTRANS.RFD_PEND_COV as RFD_PEND_COV,
EXPTRANS.RFD_END_PRM as RFD_END_PRM,
EXPTRANS.RFD_END_DT as RFD_END_DT,
EXPTRANS.B_FEED_DT as LOAD_DT,
EXPTRANS.B_FEED_IND as FEED_IND
FROM
EXPTRANS;


END; ';