-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_FARMPOLOTHREND("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component STG_FARMPOLOTHREND, Type Pre SQL 
DELETE  FROM DB_T_STAG_MEMBXREF_PROD.STG_FARMPOLOTHREND where load_dt in
( select distinct a.load_dt from	DB_T_STAG_MEMBXREF_PROD.STG_FARMPOLOTHREND A
	,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
	A.LOAD_DT = B.FEED_DT
	AND B.TABLENAME = ''FARMPOLOTHREND'');


-- Component SQ_STG_MEMBXREF_TRIGGER, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_STG_MEMBXREF_TRIGGER AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_OTHR_END_NDX,
$3 as RFD_OTHR_END_NO,
$4 as RFD_OTHR_END_COV,
$5 as RFD_OTHR_END_PRM,
$6 as B_FEED_DT,
$7 as B_FEED_INT,
$8 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 	
	SC_POLICY_NUM, RFD_OTHR_END_NDX, RFD_OTHR_END_NO, RFD_OTHR_END_COV,
		RFD_OTHR_END_PRM
	,B.FEED_DT,B.FEED_IND
FROM 
	DB_T_STAG_MEMBXREF_PROD.FARMPOLOTHREND A
	JOIN
	DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
	ON 1=1
WHERE
	TABLENAME = ''FARMPOLOTHREND''
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_STG_MEMBXREF_TRIGGER.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_STG_MEMBXREF_TRIGGER.RFD_OTHR_END_NDX as RFD_OTHR_END_NDX,
SQ_STG_MEMBXREF_TRIGGER.RFD_OTHR_END_NO as RFD_OTHR_END_NO,
SQ_STG_MEMBXREF_TRIGGER.RFD_OTHR_END_COV as RFD_OTHR_END_COV,
SQ_STG_MEMBXREF_TRIGGER.RFD_OTHR_END_PRM as RFD_OTHR_END_PRM,
SQ_STG_MEMBXREF_TRIGGER.B_FEED_DT as B_FEED_DT,
SQ_STG_MEMBXREF_TRIGGER.B_FEED_INT as B_FEED_INT,
SQ_STG_MEMBXREF_TRIGGER.source_record_id
FROM
SQ_STG_MEMBXREF_TRIGGER
);


-- Component STG_FARMPOLOTHREND, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_FARMPOLOTHREND
(
SC_POLICY_NUM,
RFD_OTHR_END_NDX,
RFD_OTHR_END_NO,
RFD_OTHR_END_COV,
RFD_OTHR_END_PRM,
LOAD_DT,
FEED_IND
)
SELECT
EXPTRANS.SC_POLICY_NUM as SC_POLICY_NUM,
EXPTRANS.RFD_OTHR_END_NDX as RFD_OTHR_END_NDX,
EXPTRANS.RFD_OTHR_END_NO as RFD_OTHR_END_NO,
EXPTRANS.RFD_OTHR_END_COV as RFD_OTHR_END_COV,
EXPTRANS.RFD_OTHR_END_PRM as RFD_OTHR_END_PRM,
EXPTRANS.B_FEED_DT as LOAD_DT,
EXPTRANS.B_FEED_INT as FEED_IND
FROM
EXPTRANS;


END; ';