-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_FARMPOLOUTBLD("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component STG_FARMPOLOUTBLD, Type Pre SQL 
DELETE  FROM DB_T_STAG_MEMBXREF_PROD.STG_FARMPOLOUTBLD where load_dt in
(  select distinct a.load_dt from	DB_T_STAG_MEMBXREF_PROD.STG_FARMPOLOUTBLD A
	,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
	A.LOAD_DT = B.FEED_DT
	AND B.TABLENAME = ''FARMPOLOUTBLD'');


-- Component SQ_FARMPOLOUTBLD, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMPOLOUTBLD AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_OUTBLD_NDX,
$3 as RFD_ECLASS,
$4 as RFD_ECOV,
$5 as RFD_PCLASS,
$6 as RFD_PECOV,
$7 as RFD_E_DT,
$8 as RFD_E_PREM,
$9 as RFD_E_DED,
$10 as RFD_PE_DED,
$11 as RFD_E_CNST_YR,
$12 as RFD_E_KBRACE,
$13 as RFD_PE_KBRACE,
$14 as RFD_E_CNST_TY,
$15 as RFD_E_DESC,
$16 as B_FEED_DATE,
$17 as B_FEED_IND,
$18 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 	
	A.*
	,B.FEED_DT,B.FEED_IND
FROM 
	DB_T_STAG_MEMBXREF_PROD.FARMPOLOUTBLD A
	JOIN
	DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
	ON 1=1
WHERE
	TABLENAME = ''FARMPOLOUTBLD''
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_FARMPOLOUTBLD.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMPOLOUTBLD.RFD_OUTBLD_NDX as RFD_OUTBLD_NDX,
SQ_FARMPOLOUTBLD.RFD_ECLASS as RFD_ECLASS,
SQ_FARMPOLOUTBLD.RFD_ECOV as RFD_ECOV,
SQ_FARMPOLOUTBLD.RFD_PCLASS as RFD_PCLASS,
SQ_FARMPOLOUTBLD.RFD_PECOV as RFD_PECOV,
SQ_FARMPOLOUTBLD.RFD_E_DT as RFD_E_DT,
SQ_FARMPOLOUTBLD.RFD_E_PREM as RFD_E_PREM,
SQ_FARMPOLOUTBLD.RFD_E_DED as RFD_E_DED,
SQ_FARMPOLOUTBLD.RFD_PE_DED as RFD_PE_DED,
SQ_FARMPOLOUTBLD.RFD_E_CNST_YR as RFD_E_CNST_YR,
SQ_FARMPOLOUTBLD.RFD_E_KBRACE as RFD_E_KBRACE,
SQ_FARMPOLOUTBLD.RFD_PE_KBRACE as RFD_PE_KBRACE,
SQ_FARMPOLOUTBLD.RFD_E_CNST_TY as RFD_E_CNST_TY,
SQ_FARMPOLOUTBLD.RFD_E_DESC as RFD_E_DESC,
SQ_FARMPOLOUTBLD.B_FEED_DATE as B_FEED_DATE,
SQ_FARMPOLOUTBLD.B_FEED_IND as B_FEED_IND,
SQ_FARMPOLOUTBLD.source_record_id
FROM
SQ_FARMPOLOUTBLD
);


-- Component STG_FARMPOLOUTBLD, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_FARMPOLOUTBLD
(
SC_POLICY_NUM,
RFD_OUTBLD_NDX,
RFD_ECLASS,
RFD_ECOV,
RFD_PCLASS,
RFD_PECOV,
RFD_E_DT,
RFD_E_PREM,
RFD_E_DED,
RFD_PE_DED,
RFD_E_CNST_YR,
RFD_E_KBRACE,
RFD_PE_KBRACE,
RFD_E_CNST_TY,
RFD_E_DESC,
LOAD_DT,
FEED_IND
)
SELECT
EXPTRANS.SC_POLICY_NUM as SC_POLICY_NUM,
EXPTRANS.RFD_OUTBLD_NDX as RFD_OUTBLD_NDX,
EXPTRANS.RFD_ECLASS as RFD_ECLASS,
EXPTRANS.RFD_ECOV as RFD_ECOV,
EXPTRANS.RFD_PCLASS as RFD_PCLASS,
EXPTRANS.RFD_PECOV as RFD_PECOV,
EXPTRANS.RFD_E_DT as RFD_E_DT,
EXPTRANS.RFD_E_PREM as RFD_E_PREM,
EXPTRANS.RFD_E_DED as RFD_E_DED,
EXPTRANS.RFD_PE_DED as RFD_PE_DED,
EXPTRANS.RFD_E_CNST_YR as RFD_E_CNST_YR,
EXPTRANS.RFD_E_KBRACE as RFD_E_KBRACE,
EXPTRANS.RFD_PE_KBRACE as RFD_PE_KBRACE,
EXPTRANS.RFD_E_CNST_TY as RFD_E_CNST_TY,
EXPTRANS.RFD_E_DESC as RFD_E_DESC,
EXPTRANS.B_FEED_DATE as LOAD_DT,
EXPTRANS.B_FEED_IND as FEED_IND
FROM
EXPTRANS;


END; ';