-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_FARMPRVOUTBLD("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component STG_FARMPRVOUTBLD, Type Pre SQL 
DELETE  FROM DB_T_STAG_MEMBXREF_PROD.STG_FARMPRVOUTBLD where load_dt in
(select distinct a.load_dt from	DB_T_STAG_MEMBXREF_PROD.STG_FARMPRVOUTBLD A
	,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
	A.LOAD_DT = B.FEED_DT
	AND B.TABLENAME = ''FARMPRVOUTBLD'');


-- Component SQ_FARMPRVOUTBLD, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FARMPRVOUTBLD AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as RFD_PRV_OUT_NDX,
$3 as RFD_PCLASS,
$4 as RFD_PECOV,
$5 as RFD_E_DT,
$6 as RFD_PE_DED,
$7 as RFD_PE_KBRACE,
$8 as B_FEED_DATE,
$9 as B_FEED_IND,
$10 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 	
	A.*
	,B.FEED_DT,B.FEED_IND
FROM 
	DB_T_STAG_MEMBXREF_PROD.FARMPRVOUTBLD A
	JOIN
	DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
	ON 1=1
WHERE
	TABLENAME = ''FARMPRVOUTBLD''
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_FARMPRVOUTBLD.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_FARMPRVOUTBLD.RFD_PRV_OUT_NDX as RFD_PRV_OUT_NDX,
SQ_FARMPRVOUTBLD.RFD_PCLASS as RFD_PCLASS,
SQ_FARMPRVOUTBLD.RFD_PECOV as RFD_PECOV,
SQ_FARMPRVOUTBLD.RFD_E_DT as RFD_E_DT,
SQ_FARMPRVOUTBLD.RFD_PE_DED as RFD_PE_DED,
SQ_FARMPRVOUTBLD.RFD_PE_KBRACE as RFD_PE_KBRACE,
SQ_FARMPRVOUTBLD.B_FEED_DATE as B_FEED_DATE,
SQ_FARMPRVOUTBLD.B_FEED_IND as B_FEED_IND,
SQ_FARMPRVOUTBLD.source_record_id
FROM
SQ_FARMPRVOUTBLD
);


-- Component STG_FARMPRVOUTBLD, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_FARMPRVOUTBLD
(
SC_POLICY_NUM,
RFD_PRV_OUT_NDX,
RFD_PCLASS,
RFD_PECOV,
RFD_E_DT,
RFD_PE_DED,
RFD_PE_KBRACE,
LOAD_DT,
FEED_IND
)
SELECT
EXPTRANS.SC_POLICY_NUM as SC_POLICY_NUM,
EXPTRANS.RFD_PRV_OUT_NDX as RFD_PRV_OUT_NDX,
EXPTRANS.RFD_PCLASS as RFD_PCLASS,
EXPTRANS.RFD_PECOV as RFD_PECOV,
EXPTRANS.RFD_E_DT as RFD_E_DT,
EXPTRANS.RFD_PE_DED as RFD_PE_DED,
EXPTRANS.RFD_PE_KBRACE as RFD_PE_KBRACE,
EXPTRANS.B_FEED_DATE as LOAD_DT,
EXPTRANS.B_FEED_IND as FEED_IND
FROM
EXPTRANS;


END; ';