-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_LIFERIDERBENINFO("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_LIFERIDERBENINFO, Type Pre SQL 
DELETE  FROM DB_T_STAG_MEMBXREF_PROD.STG_LIFERIDERBENINFO where load_dt in
(select distinct a.load_dt from	DB_T_STAG_MEMBXREF_PROD.STG_LIFERIDERBENINFO A
	,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
	A.LOAD_DT = B.FEED_DT
	AND B.TABLENAME = ''LIFERIDERBENINFO'');


-- Component SQ_LIFERIDERBENINFO, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_LIFERIDERBENINFO AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as LF_RDR_NDX,
$3 as LF_RDR_PLAN,
$4 as LF_RDR_VOL,
$5 as LF_RDR_ANPRM,
$6 as FEED_DT,
$7 as FEED_IND,
$8 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 	
	A.SC_POLICY_NUM,
	A.LF_RDR_NDX,
	A.LF_RDR_PLAN,
	A.LF_RDR_VOL,
	A.LF_RDR_ANPRM,
	B.FEED_DT,B.FEED_IND
FROM 
	DB_T_STAG_MEMBXREF_PROD.LIFERIDERBENINFO A
	JOIN
	DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
	ON 1=1
WHERE
	TABLENAME = ''LIFERIDERBENINFO''
) SRC
)
);


-- Component Exp_Trans, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_Trans AS
(
SELECT
SQ_LIFERIDERBENINFO.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_LIFERIDERBENINFO.LF_RDR_NDX as LF_RDR_NDX,
SQ_LIFERIDERBENINFO.LF_RDR_PLAN as LF_RDR_PLAN,
SQ_LIFERIDERBENINFO.LF_RDR_VOL as LF_RDR_VOL,
SQ_LIFERIDERBENINFO.LF_RDR_ANPRM as LF_RDR_ANPRM,
TO_DATE ( SQ_LIFERIDERBENINFO.FEED_DT  ) as o_FEED_DT,
SQ_LIFERIDERBENINFO.FEED_IND as FEED_IND,
SQ_LIFERIDERBENINFO.source_record_id
FROM
SQ_LIFERIDERBENINFO
);


-- Component STG_LIFERIDERBENINFO, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_LIFERIDERBENINFO
(
SC_POLICY_NUM,
LF_RDR_NDX,
LF_RDR_PLAN,
LF_RDR_VOL,
LF_RDR_ANPRM,
LOAD_DT,
FEED_IND
)
SELECT
Exp_Trans.SC_POLICY_NUM as SC_POLICY_NUM,
Exp_Trans.LF_RDR_NDX as LF_RDR_NDX,
Exp_Trans.LF_RDR_PLAN as LF_RDR_PLAN,
Exp_Trans.LF_RDR_VOL as LF_RDR_VOL,
Exp_Trans.LF_RDR_ANPRM as LF_RDR_ANPRM,
Exp_Trans.o_FEED_DT as LOAD_DT,
Exp_Trans.FEED_IND as FEED_IND
FROM
Exp_Trans;


END; ';