-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_LOANS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component STG_LOANS, Type Pre SQL 
DELETE  FROM DB_T_STAG_MEMBXREF_PROD.STG_LOANS where load_dt in
( select distinct a.load_dt from DB_T_STAG_MEMBXREF_PROD.STG_LOANS A, DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B WHERE A.LOAD_DT = B.FEED_DT AND B.TABLENAME = ''LOANS'');


-- Component SQ_LOANS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_LOANS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_SERVICE_CENTER,
$2 as SC_POLICY_NUM,
$3 as PC_ALPHA_CODE,
$4 as PC_NAME_1,
$5 as PC_NAME_2,
$6 as PC_ADDRESS_1,
$7 as PC_ADDRESS_2,
$8 as PC_CITYST,
$9 as PC_ZIP,
$10 as PC_AGENT,
$11 as PC_MEMBER_NUMBER,
$12 as PC_COMPANY,
$13 as SC_DWNLD_PRIORITY,
$14 as SC_FLT_ITEM,
$15 as SC_FILE_TYPE,
$16 as SC_REC_TRANS_CODE,
$17 as SC_TRANS_DATE,
$18 as SC_TRANS_TYPE,
$19 as PC_INCEPT_DATE,
$20 as LN_STATUS,
$21 as LN_DUE_DATE,
$22 as LN_AMOUNT_DUE,
$23 as LN_NBR_PMNTS_PAID,
$24 as LN_BALANCE,
$25 as LN_PAYOFF_AMT,
$26 as LN_NBR_PMNTS_LATE,
$27 as LN_LATE_CHARGE_AMT,
$28 as LN_ORIGINAL_TERM,
$29 as LN_ORIGINL_AMT_FIN,
$30 as LN_COLLATERAL_DESC,
$31 as LN_CRDT_LIFE_IND,
$32 as LN_A_H_IND,
$33 as LN_PER_DIEM,
$34 as LN_YTD_INTEREST,
$35 as LN_PREV_YTD_INT,
$36 as LN_SSN,
$37 as LN_WORK_PHONE_NBR,
$38 as LN_HOME_PHONE_NBR,
$39 as LN_LAST_PAYMT_DATE,
$40 as LN_INT_RATE,
$41 as FEED_DT,
$42 as FEED_IND,
$43 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
	A.SC_SERVICE_CENTER,
	A.SC_POLICY_NUM,
	A.PC_ALPHA_CODE,
	A.PC_NAME_1,
	A.PC_NAME_2,
	A.PC_ADDRESS_1,
	A.PC_ADDRESS_2,
	A.PC_CITYST,
	A.PC_ZIP,
	A.PC_AGENT,
	A.PC_MEMBER_NUMBER,
	A.PC_COMPANY,
	A.SC_DWNLD_PRIORITY,
	A.SC_FLT_ITEM,
	A.SC_FILE_TYPE,
	A.SC_REC_TRANS_CODE,
	A.SC_TRANS_DATE,
	A.SC_TRANS_TYPE,
	A.PC_INCEPT_DATE,
	A.LN_STATUS,
	A.LN_DUE_DATE,
	A.LN_AMOUNT_DUE,
	A.LN_NBR_PMNTS_PAID,
	A.LN_BALANCE,
	A.LN_PAYOFF_AMT,
	A.LN_NBR_PMNTS_LATE,
	A.LN_LATE_CHARGE_AMT,
	A.LN_ORIGINAL_TERM,
	A.LN_ORIGINL_AMT_FIN,
	A.LN_COLLATERAL_DESC,
	A.LN_CRDT_LIFE_IND,
	A.LN_A_H_IND,
	A.LN_PER_DIEM,
	A.LN_YTD_INTEREST,
	A.LN_PREV_YTD_INT,
	A.LN_SSN,
	A.LN_WORK_PHONE_NBR,
	A.LN_HOME_PHONE_NBR,
	A.LN_LAST_PAYMT_DATE,
	A.LN_INT_RATE,
	B.FEED_DT,
	B.FEED_IND
FROM 
	DB_T_CORE_MEMBXREF_PROD.LOANS A
	JOIN DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
		ON 1=1
WHERE
	TABLENAME = ''LOANS''
) SRC
)
);


-- Component Exp_Pass_Through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_Pass_Through AS
(
SELECT
SQ_LOANS.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
SQ_LOANS.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_LOANS.PC_ALPHA_CODE as PC_ALPHA_CODE,
SQ_LOANS.PC_NAME_1 as PC_NAME_1,
SQ_LOANS.PC_NAME_2 as PC_NAME_2,
SQ_LOANS.PC_ADDRESS_1 as PC_ADDRESS_1,
SQ_LOANS.PC_ADDRESS_2 as PC_ADDRESS_2,
SQ_LOANS.PC_CITYST as PC_CITYST,
SQ_LOANS.PC_ZIP as PC_ZIP,
SQ_LOANS.PC_AGENT as PC_AGENT,
SQ_LOANS.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
SQ_LOANS.PC_COMPANY as PC_COMPANY,
SQ_LOANS.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
SQ_LOANS.SC_FLT_ITEM as SC_FLT_ITEM,
SQ_LOANS.SC_FILE_TYPE as SC_FILE_TYPE,
SQ_LOANS.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
SQ_LOANS.SC_TRANS_DATE as SC_TRANS_DATE,
SQ_LOANS.SC_TRANS_TYPE as SC_TRANS_TYPE,
SQ_LOANS.PC_INCEPT_DATE as PC_INCEPT_DATE,
SQ_LOANS.LN_STATUS as LN_STATUS,
SQ_LOANS.LN_DUE_DATE as LN_DUE_DATE,
SQ_LOANS.LN_AMOUNT_DUE as LN_AMOUNT_DUE,
SQ_LOANS.LN_NBR_PMNTS_PAID as LN_NBR_PMNTS_PAID,
SQ_LOANS.LN_BALANCE as LN_BALANCE,
SQ_LOANS.LN_PAYOFF_AMT as LN_PAYOFF_AMT,
SQ_LOANS.LN_NBR_PMNTS_LATE as LN_NBR_PMNTS_LATE,
SQ_LOANS.LN_LATE_CHARGE_AMT as LN_LATE_CHARGE_AMT,
SQ_LOANS.LN_ORIGINAL_TERM as LN_ORIGINAL_TERM,
SQ_LOANS.LN_ORIGINL_AMT_FIN as LN_ORIGINL_AMT_FIN,
SQ_LOANS.LN_COLLATERAL_DESC as LN_COLLATERAL_DESC,
SQ_LOANS.LN_CRDT_LIFE_IND as LN_CRDT_LIFE_IND,
SQ_LOANS.LN_A_H_IND as LN_A_H_IND,
SQ_LOANS.LN_PER_DIEM as LN_PER_DIEM,
SQ_LOANS.LN_YTD_INTEREST as LN_YTD_INTEREST,
SQ_LOANS.LN_PREV_YTD_INT as LN_PREV_YTD_INT,
SQ_LOANS.LN_SSN as LN_SSN,
SQ_LOANS.LN_WORK_PHONE_NBR as LN_WORK_PHONE_NBR,
SQ_LOANS.LN_HOME_PHONE_NBR as LN_HOME_PHONE_NBR,
SQ_LOANS.LN_LAST_PAYMT_DATE as LN_LAST_PAYMT_DATE,
SQ_LOANS.LN_INT_RATE as LN_INT_RATE,
SQ_LOANS.FEED_DT as FEED_DT,
SQ_LOANS.FEED_IND as FEED_IND,
SQ_LOANS.source_record_id
FROM
SQ_LOANS
);


-- Component STG_LOANS, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_LOANS
(
SC_SERVICE_CENTER,
SC_POLICY_NUM,
PC_ALPHA_CODE,
PC_NAME_1,
PC_NAME_2,
PC_ADDRESS_1,
PC_ADDRESS_2,
PC_CITYST,
PC_ZIP,
PC_AGENT,
PC_MEMBER_NUMBER,
PC_COMPANY,
SC_DWNLD_PRIORITY,
SC_FLT_ITEM,
SC_FILE_TYPE,
SC_REC_TRANS_CODE,
SC_TRANS_DATE,
SC_TRANS_TYPE,
PC_INCEPT_DATE,
LN_STATUS,
LN_DUE_DATE,
LN_AMOUNT_DUE,
LN_NBR_PMNTS_PAID,
LN_BALANCE,
LN_PAYOFF_AMT,
LN_NBR_PMNTS_LATE,
LN_LATE_CHARGE_AMT,
LN_ORIGINAL_TERM,
LN_ORIGINL_AMT_FIN,
LN_COLLATERAL_DESC,
LN_CRDT_LIFE_IND,
LN_A_H_IND,
LN_PER_DIEM,
LN_YTD_INTEREST,
LN_PREV_YTD_INT,
LN_SSN,
LN_WORK_PHONE_NBR,
LN_HOME_PHONE_NBR,
LN_LAST_PAYMT_DATE,
LN_INT_RATE,
LOAD_DT,
FEED_IND
)
SELECT
Exp_Pass_Through.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
Exp_Pass_Through.SC_POLICY_NUM as SC_POLICY_NUM,
Exp_Pass_Through.PC_ALPHA_CODE as PC_ALPHA_CODE,
Exp_Pass_Through.PC_NAME_1 as PC_NAME_1,
Exp_Pass_Through.PC_NAME_2 as PC_NAME_2,
Exp_Pass_Through.PC_ADDRESS_1 as PC_ADDRESS_1,
Exp_Pass_Through.PC_ADDRESS_2 as PC_ADDRESS_2,
Exp_Pass_Through.PC_CITYST as PC_CITYST,
Exp_Pass_Through.PC_ZIP as PC_ZIP,
Exp_Pass_Through.PC_AGENT as PC_AGENT,
Exp_Pass_Through.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
Exp_Pass_Through.PC_COMPANY as PC_COMPANY,
Exp_Pass_Through.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
Exp_Pass_Through.SC_FLT_ITEM as SC_FLT_ITEM,
Exp_Pass_Through.SC_FILE_TYPE as SC_FILE_TYPE,
Exp_Pass_Through.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
Exp_Pass_Through.SC_TRANS_DATE as SC_TRANS_DATE,
Exp_Pass_Through.SC_TRANS_TYPE as SC_TRANS_TYPE,
Exp_Pass_Through.PC_INCEPT_DATE as PC_INCEPT_DATE,
Exp_Pass_Through.LN_STATUS as LN_STATUS,
Exp_Pass_Through.LN_DUE_DATE as LN_DUE_DATE,
Exp_Pass_Through.LN_AMOUNT_DUE as LN_AMOUNT_DUE,
Exp_Pass_Through.LN_NBR_PMNTS_PAID as LN_NBR_PMNTS_PAID,
Exp_Pass_Through.LN_BALANCE as LN_BALANCE,
Exp_Pass_Through.LN_PAYOFF_AMT as LN_PAYOFF_AMT,
Exp_Pass_Through.LN_NBR_PMNTS_LATE as LN_NBR_PMNTS_LATE,
Exp_Pass_Through.LN_LATE_CHARGE_AMT as LN_LATE_CHARGE_AMT,
Exp_Pass_Through.LN_ORIGINAL_TERM as LN_ORIGINAL_TERM,
Exp_Pass_Through.LN_ORIGINL_AMT_FIN as LN_ORIGINL_AMT_FIN,
Exp_Pass_Through.LN_COLLATERAL_DESC as LN_COLLATERAL_DESC,
Exp_Pass_Through.LN_CRDT_LIFE_IND as LN_CRDT_LIFE_IND,
Exp_Pass_Through.LN_A_H_IND as LN_A_H_IND,
Exp_Pass_Through.LN_PER_DIEM as LN_PER_DIEM,
Exp_Pass_Through.LN_YTD_INTEREST as LN_YTD_INTEREST,
Exp_Pass_Through.LN_PREV_YTD_INT as LN_PREV_YTD_INT,
Exp_Pass_Through.LN_SSN as LN_SSN,
Exp_Pass_Through.LN_WORK_PHONE_NBR as LN_WORK_PHONE_NBR,
Exp_Pass_Through.LN_HOME_PHONE_NBR as LN_HOME_PHONE_NBR,
Exp_Pass_Through.LN_LAST_PAYMT_DATE as LN_LAST_PAYMT_DATE,
Exp_Pass_Through.LN_INT_RATE as LN_INT_RATE,
Exp_Pass_Through.FEED_DT as LOAD_DT,
Exp_Pass_Through.FEED_IND as FEED_IND
FROM
Exp_Pass_Through;


END; ';