-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_CPS_INC_RCT("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 

-- Component CPS_INC_RCT2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_ML_PROD.CPS_INC_RCT;


-- PIPELINE START FOR 1

-- Component SQ_CPS_INC_RCT1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CPS_INC_RCT1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as RECEIPT_NBR,
$2 as DEPOSIT_NBR,
$3 as SVC_NBR,
$4 as SVC_ST_NBR,
$5 as SYST_USER,
$6 as SYST_DT,
$7 as SYST_TM,
$8 as ENTRY_INIT,
$9 as TOT_RCT_AMT,
$10 as CHK_TOT,
$11 as CSH_TOT,
$12 as EPO_TOT,
$13 as VOID_COMMENTS,
$14 as ORIG_RCT_NBR,
$15 as REPLACEDBY_RCT_NBR,
$16 as PRV_RCT_NBR,
$17 as FLD_RCT_NBR,
$18 as FLD_RCT_DT,
$19 as FLD_RCT_TM,
$20 as CUR_STAT_CD,
$21 as CUR_STAT_DT,
$22 as CUR_STAT_TM,
$23 as CUR_STAT_USER,
$24 as CUR_STAT_INIT,
$25 as PRV_STAT_CD,
$26 as PRV_STAT_DT,
$27 as PRV_STAT_TM,
$28 as PRV_STAT_USER,
$29 as PRV_STAT_INIT,
$30 as CHK_APPLD_COMMENTS,
$31 as LEGAL_EMAIL,
$32 as PYMT_SRCE,
$33 as BATCH_NBR,
$34 as TRANS_NBR,
$35 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
CPS_INC_RCT1.RECEIPT_NBR,
CPS_INC_RCT1.DEPOSIT_NBR,
CPS_INC_RCT1.SVC_NBR,
CPS_INC_RCT1.SVC_ST_NBR,
CPS_INC_RCT1.SYST_USER,
CPS_INC_RCT1.SYST_DT,
CPS_INC_RCT1.SYST_TM,
CPS_INC_RCT1.ENTRY_INIT,
CPS_INC_RCT1.TOT_RCT_AMT,
CPS_INC_RCT1.CHK_TOT,
CPS_INC_RCT1.CSH_TOT,
CPS_INC_RCT1.EPO_TOT,
CPS_INC_RCT1.VOID_COMMENTS,
CPS_INC_RCT1.ORIG_RCT_NBR,
CPS_INC_RCT1.REPLACEDBY_RCT_NBR,
CPS_INC_RCT1.PRV_RCT_NBR,
CPS_INC_RCT1.FLD_RCT_NBR,
CPS_INC_RCT1.FLD_RCT_DT,
CPS_INC_RCT1.FLD_RCT_TM,
CPS_INC_RCT1.CUR_STAT_CD,
CPS_INC_RCT1.CUR_STAT_DT,
CPS_INC_RCT1.CUR_STAT_TM,
CPS_INC_RCT1.CUR_STAT_USER,
CPS_INC_RCT1.CUR_STAT_INIT,
CPS_INC_RCT1.PRV_STAT_CD,
CPS_INC_RCT1.PRV_STAT_DT,
CPS_INC_RCT1.PRV_STAT_TM,
CPS_INC_RCT1.PRV_STAT_USER,
CPS_INC_RCT1.PRV_STAT_INIT,
CPS_INC_RCT1.CHK_APPLD_COMMENTS,
CPS_INC_RCT1.LEGAL_EMAIL,
CPS_INC_RCT1.PYMT_SRCE,
CPS_INC_RCT1.BATCH_NBR,
CPS_INC_RCT1.TRANS_NBR
FROM DB_T_ML_PROD.CPS_INC_RCT CPS_INC_RCT1
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_CPS_INC_RCT1.RECEIPT_NBR as RECEIPT_NBR,
SQ_CPS_INC_RCT1.DEPOSIT_NBR as DEPOSIT_NBR,
SQ_CPS_INC_RCT1.SVC_NBR as SVC_NBR,
SQ_CPS_INC_RCT1.SVC_ST_NBR as SVC_ST_NBR,
SQ_CPS_INC_RCT1.SYST_USER as SYST_USER,
SQ_CPS_INC_RCT1.SYST_DT as SYST_DT,
SQ_CPS_INC_RCT1.SYST_TM as SYST_TM,
SQ_CPS_INC_RCT1.ENTRY_INIT as ENTRY_INIT,
SQ_CPS_INC_RCT1.TOT_RCT_AMT as TOT_RCT_AMT,
SQ_CPS_INC_RCT1.CHK_TOT as CHK_TOT,
SQ_CPS_INC_RCT1.CSH_TOT as CSH_TOT,
SQ_CPS_INC_RCT1.EPO_TOT as EPO_TOT,
SQ_CPS_INC_RCT1.VOID_COMMENTS as VOID_COMMENTS,
SQ_CPS_INC_RCT1.ORIG_RCT_NBR as ORIG_RCT_NBR,
SQ_CPS_INC_RCT1.REPLACEDBY_RCT_NBR as REPLACEDBY_RCT_NBR,
SQ_CPS_INC_RCT1.PRV_RCT_NBR as PRV_RCT_NBR,
SQ_CPS_INC_RCT1.FLD_RCT_NBR as FLD_RCT_NBR,
SQ_CPS_INC_RCT1.FLD_RCT_DT as FLD_RCT_DT,
SQ_CPS_INC_RCT1.FLD_RCT_TM as FLD_RCT_TM,
SQ_CPS_INC_RCT1.CUR_STAT_CD as CUR_STAT_CD,
SQ_CPS_INC_RCT1.CUR_STAT_DT as CUR_STAT_DT,
SQ_CPS_INC_RCT1.CUR_STAT_TM as CUR_STAT_TM,
SQ_CPS_INC_RCT1.CUR_STAT_USER as CUR_STAT_USER,
SQ_CPS_INC_RCT1.CUR_STAT_INIT as CUR_STAT_INIT,
SQ_CPS_INC_RCT1.PRV_STAT_CD as PRV_STAT_CD,
SQ_CPS_INC_RCT1.PRV_STAT_DT as PRV_STAT_DT,
SQ_CPS_INC_RCT1.PRV_STAT_TM as PRV_STAT_TM,
SQ_CPS_INC_RCT1.PRV_STAT_USER as PRV_STAT_USER,
SQ_CPS_INC_RCT1.PRV_STAT_INIT as PRV_STAT_INIT,
SQ_CPS_INC_RCT1.CHK_APPLD_COMMENTS as CHK_APPLD_COMMENTS,
SQ_CPS_INC_RCT1.LEGAL_EMAIL as LEGAL_EMAIL,
SQ_CPS_INC_RCT1.PYMT_SRCE as PYMT_SRCE,
SQ_CPS_INC_RCT1.BATCH_NBR as BATCH_NBR,
SQ_CPS_INC_RCT1.TRANS_NBR as TRANS_NBR,
SQ_CPS_INC_RCT1.source_record_id
FROM
SQ_CPS_INC_RCT1
);


-- Component CPS_INC_RCT2, Type TARGET 
INSERT INTO DB_T_ML_PROD.CPS_INC_RCT
(
RECEIPT_NBR,
DEPOSIT_NBR,
SVC_NBR,
SVC_ST_NBR,
SYST_USER,
SYST_DT,
SYST_TM,
ENTRY_INIT,
TOT_RCT_AMT,
CHK_TOT,
CSH_TOT,
EPO_TOT,
VOID_COMMENTS,
ORIG_RCT_NBR,
REPLACEDBY_RCT_NBR,
PRV_RCT_NBR,
FLD_RCT_NBR,
FLD_RCT_DT,
FLD_RCT_TM,
CUR_STAT_CD,
CUR_STAT_DT,
CUR_STAT_TM,
CUR_STAT_USER,
CUR_STAT_INIT,
PRV_STAT_CD,
PRV_STAT_DT,
PRV_STAT_TM,
PRV_STAT_USER,
PRV_STAT_INIT,
CHK_APPLD_COMMENTS,
LEGAL_EMAIL,
PYMT_SRCE,
BATCH_NBR,
TRANS_NBR
)
SELECT
exp_pass_through.RECEIPT_NBR as RECEIPT_NBR,
exp_pass_through.DEPOSIT_NBR as DEPOSIT_NBR,
exp_pass_through.SVC_NBR as SVC_NBR,
exp_pass_through.SVC_ST_NBR as SVC_ST_NBR,
exp_pass_through.SYST_USER as SYST_USER,
exp_pass_through.SYST_DT as SYST_DT,
exp_pass_through.SYST_TM as SYST_TM,
exp_pass_through.ENTRY_INIT as ENTRY_INIT,
exp_pass_through.TOT_RCT_AMT as TOT_RCT_AMT,
exp_pass_through.CHK_TOT as CHK_TOT,
exp_pass_through.CSH_TOT as CSH_TOT,
exp_pass_through.EPO_TOT as EPO_TOT,
exp_pass_through.VOID_COMMENTS as VOID_COMMENTS,
exp_pass_through.ORIG_RCT_NBR as ORIG_RCT_NBR,
exp_pass_through.REPLACEDBY_RCT_NBR as REPLACEDBY_RCT_NBR,
exp_pass_through.PRV_RCT_NBR as PRV_RCT_NBR,
exp_pass_through.FLD_RCT_NBR as FLD_RCT_NBR,
exp_pass_through.FLD_RCT_DT as FLD_RCT_DT,
exp_pass_through.FLD_RCT_TM as FLD_RCT_TM,
exp_pass_through.CUR_STAT_CD as CUR_STAT_CD,
exp_pass_through.CUR_STAT_DT as CUR_STAT_DT,
exp_pass_through.CUR_STAT_TM as CUR_STAT_TM,
exp_pass_through.CUR_STAT_USER as CUR_STAT_USER,
exp_pass_through.CUR_STAT_INIT as CUR_STAT_INIT,
exp_pass_through.PRV_STAT_CD as PRV_STAT_CD,
exp_pass_through.PRV_STAT_DT as PRV_STAT_DT,
exp_pass_through.PRV_STAT_TM as PRV_STAT_TM,
exp_pass_through.PRV_STAT_USER as PRV_STAT_USER,
exp_pass_through.PRV_STAT_INIT as PRV_STAT_INIT,
exp_pass_through.CHK_APPLD_COMMENTS as CHK_APPLD_COMMENTS,
exp_pass_through.LEGAL_EMAIL as LEGAL_EMAIL,
exp_pass_through.PYMT_SRCE as PYMT_SRCE,
exp_pass_through.BATCH_NBR as BATCH_NBR,
exp_pass_through.TRANS_NBR as TRANS_NBR
FROM
exp_pass_through;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_CPS_INC_RCT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CPS_INC_RCT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
select count(*) as record_Count
from DB_T_ML_PROD.cps_inc_rct
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_CPS_INC_RCT.record_count as record_count,
:feed_ind as feed_ind,
to_char ( CURRENT_TIMESTAMP , ''YYYY-MM-DD'' ) as feed_dt,
SQ_CPS_INC_RCT.source_record_id
FROM
SQ_CPS_INC_RCT
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 2

END; ';