-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_CPS_PMT_DEP("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 

-- Component CPS_PMT_DEP, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_ML_PROD.CPS_PMT_DEP;


-- PIPELINE START FOR 1

-- Component SQ_CPS_PMT_DEP, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CPS_PMT_DEP AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as DEPOSIT_NBR,
$2 as SVC_NBR,
$3 as SVC_ST_NBR,
$4 as SYST_USER,
$5 as SYST_DT,
$6 as SYST_TM,
$7 as ENTRY_INIT,
$8 as TOT_DEP_AMT,
$9 as SYST_CHK_TOT,
$10 as SYST_CSH_TOT,
$11 as NBR_CHKS,
$12 as ACTL_CHK_TOT,
$13 as ACTL_CSH_TOT,
$14 as CSH_ADJ_AMT,
$15 as PETTY_CSH_AMT,
$16 as OUT_BAL_COMMENTS,
$17 as VOID_COMMENTS,
$18 as CUR_STAT_CD,
$19 as CUR_STAT_DT,
$20 as CUR_STAT_TM,
$21 as CUR_STAT_USER,
$22 as CUR_STAT_INIT,
$23 as PRV_STAT_CD,
$24 as PRV_STAT_DT,
$25 as PRV_STAT_TM,
$26 as PRV_STAT_USER,
$27 as PRV_STAT_INIT,
$28 as GL_ACCT_NBR,
$29 as GL_DEPT_ID,
$30 as GL_BATCH_TX_NBR,
$31 as ACH_PROCESS_DT,
$32 as ACH_SETTLEMENT_DT,
$33 as HO_SVC_DEP_ADJ_AMT,
$34 as DISB_ACH_SETLMT_DT,
$35 as DEP_MARKED,
$36 as SYST_EPO_TOT,
$37 as ACTL_EPO_TOT,
$38 as NBR_EPO_PROC,
$39 as VISION_CSH_TOT,
$40 as NUM_REC_INV_POLS,
$41 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 
DEPOSIT_NBR,
SVC_NBR,
SVC_ST_NBR,
sYST_USER,
SYST_DT,
CAST(SYST_TM AS VARCHAR(8)) AS SYST_TM,
ENTRY_INIT,
TOT_DEP_AMT,
SYST_CHK_TOT,
SYST_CSH_TOT,
NBR_CHKS,
ACTL_CHK_TOT,
ACTL_CSH_TOT,
CSH_ADJ_AMT,
PETTY_CSH_AMT,
OUT_BAL_COMMENTS,
VOID_COMMENTS,
CUR_STAT_CD,
CUR_STAT_DT,
CAST(CUR_STAT_TM AS VARCHAR(8)) AS CUR_STAT_TM,
CUR_STAT_USER,
CUR_STAT_INIT,
PRV_STAT_CD,
PRV_STAT_DT,
CAST(PRV_STAT_TM AS VARCHAR(8)) AS PRV_STAT_TM,
PRV_STAT_USER,
PRV_STAT_INIT,
GL_ACCT_NBR,
GL_DEPT_ID,
GL_BATCH_TX_NBR,
ACH_PROCESS_DT,
ACH_SETTLEMENT_DT,
HO_SVC_DEP_ADJ_AMT,
DISB_ACH_SETLMT_DT,
DEP_MARKED,
SYST_EPO_TOT,
ACTL_EPO_TOT,
NBR_EPO_PROC,
VISION_CSH_TOT,
NUM_REC_INV_POLS
 FROM DB_T_ML_PROD.CPS_PMT_DEP
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_CPS_PMT_DEP.DEPOSIT_NBR as DEPOSIT_NBR,
SQ_CPS_PMT_DEP.SVC_NBR as SVC_NBR,
SQ_CPS_PMT_DEP.SVC_ST_NBR as SVC_ST_NBR,
SQ_CPS_PMT_DEP.SYST_USER as SYST_USER,
SQ_CPS_PMT_DEP.SYST_DT as SYST_DT,
SQ_CPS_PMT_DEP.SYST_TM as SYST_TM,
SQ_CPS_PMT_DEP.ENTRY_INIT as ENTRY_INIT,
SQ_CPS_PMT_DEP.TOT_DEP_AMT as TOT_DEP_AMT,
SQ_CPS_PMT_DEP.SYST_CHK_TOT as SYST_CHK_TOT,
SQ_CPS_PMT_DEP.SYST_CSH_TOT as SYST_CSH_TOT,
SQ_CPS_PMT_DEP.NBR_CHKS as NBR_CHKS,
SQ_CPS_PMT_DEP.ACTL_CHK_TOT as ACTL_CHK_TOT,
SQ_CPS_PMT_DEP.ACTL_CSH_TOT as ACTL_CSH_TOT,
SQ_CPS_PMT_DEP.CSH_ADJ_AMT as CSH_ADJ_AMT,
SQ_CPS_PMT_DEP.PETTY_CSH_AMT as PETTY_CSH_AMT,
SQ_CPS_PMT_DEP.OUT_BAL_COMMENTS as OUT_BAL_COMMENTS,
SQ_CPS_PMT_DEP.VOID_COMMENTS as VOID_COMMENTS,
SQ_CPS_PMT_DEP.CUR_STAT_CD as CUR_STAT_CD,
SQ_CPS_PMT_DEP.CUR_STAT_DT as CUR_STAT_DT,
SQ_CPS_PMT_DEP.CUR_STAT_TM as CUR_STAT_TM,
SQ_CPS_PMT_DEP.CUR_STAT_USER as CUR_STAT_USER,
SQ_CPS_PMT_DEP.CUR_STAT_INIT as CUR_STAT_INIT,
SQ_CPS_PMT_DEP.PRV_STAT_CD as PRV_STAT_CD,
SQ_CPS_PMT_DEP.PRV_STAT_DT as PRV_STAT_DT,
SQ_CPS_PMT_DEP.PRV_STAT_TM as PRV_STAT_TM,
SQ_CPS_PMT_DEP.PRV_STAT_USER as PRV_STAT_USER,
SQ_CPS_PMT_DEP.PRV_STAT_INIT as PRV_STAT_INIT,
SQ_CPS_PMT_DEP.GL_ACCT_NBR as GL_ACCT_NBR,
SQ_CPS_PMT_DEP.GL_DEPT_ID as GL_DEPT_ID,
SQ_CPS_PMT_DEP.GL_BATCH_TX_NBR as GL_BATCH_TX_NBR,
SQ_CPS_PMT_DEP.ACH_PROCESS_DT as ACH_PROCESS_DT,
SQ_CPS_PMT_DEP.ACH_SETTLEMENT_DT as ACH_SETTLEMENT_DT,
SQ_CPS_PMT_DEP.HO_SVC_DEP_ADJ_AMT as HO_SVC_DEP_ADJ_AMT,
SQ_CPS_PMT_DEP.DISB_ACH_SETLMT_DT as DISB_ACH_SETLMT_DT,
SQ_CPS_PMT_DEP.DEP_MARKED as DEP_MARKED,
SQ_CPS_PMT_DEP.SYST_EPO_TOT as SYST_EPO_TOT,
SQ_CPS_PMT_DEP.ACTL_EPO_TOT as ACTL_EPO_TOT,
SQ_CPS_PMT_DEP.NBR_EPO_PROC as NBR_EPO_PROC,
SQ_CPS_PMT_DEP.VISION_CSH_TOT as VISION_CSH_TOT,
SQ_CPS_PMT_DEP.NUM_REC_INV_POLS as NUM_REC_INV_POLS,
SQ_CPS_PMT_DEP.source_record_id
FROM
SQ_CPS_PMT_DEP
);


-- Component CPS_PMT_DEP, Type TARGET 
INSERT INTO DB_T_ML_PROD.CPS_PMT_DEP
(
DEPOSIT_NBR,
SVC_NBR,
SVC_ST_NBR,
SYST_USER,
SYST_DT,
SYST_TM,
ENTRY_INIT,
TOT_DEP_AMT,
SYST_CHK_TOT,
SYST_CSH_TOT,
NBR_CHKS,
ACTL_CHK_TOT,
ACTL_CSH_TOT,
CSH_ADJ_AMT,
PETTY_CSH_AMT,
OUT_BAL_COMMENTS,
VOID_COMMENTS,
CUR_STAT_CD,
CUR_STAT_DT,
CUR_STAT_TM,
CUR_STAT_USER,
CUR_STAT_INIT,
PRV_STAT_CD,
PRV_STAT_DT,
PRV_STAT_TM,
PRV_STAT_USER,
PRV_STAT_INIT,
GL_ACCT_NBR,
GL_DEPT_ID,
GL_BATCH_TX_NBR,
ACH_PROCESS_DT,
ACH_SETTLEMENT_DT,
HO_SVC_DEP_ADJ_AMT,
DISB_ACH_SETLMT_DT,
DEP_MARKED,
SYST_EPO_TOT,
ACTL_EPO_TOT,
NBR_EPO_PROC,
VISION_CSH_TOT,
NUM_REC_INV_POLS
)
SELECT
exp_pass_through.DEPOSIT_NBR as DEPOSIT_NBR,
exp_pass_through.SVC_NBR as SVC_NBR,
exp_pass_through.SVC_ST_NBR as SVC_ST_NBR,
exp_pass_through.SYST_USER as SYST_USER,
exp_pass_through.SYST_DT as SYST_DT,
exp_pass_through.SYST_TM as SYST_TM,
exp_pass_through.ENTRY_INIT as ENTRY_INIT,
exp_pass_through.TOT_DEP_AMT as TOT_DEP_AMT,
exp_pass_through.SYST_CHK_TOT as SYST_CHK_TOT,
exp_pass_through.SYST_CSH_TOT as SYST_CSH_TOT,
exp_pass_through.NBR_CHKS as NBR_CHKS,
exp_pass_through.ACTL_CHK_TOT as ACTL_CHK_TOT,
exp_pass_through.ACTL_CSH_TOT as ACTL_CSH_TOT,
exp_pass_through.CSH_ADJ_AMT as CSH_ADJ_AMT,
exp_pass_through.PETTY_CSH_AMT as PETTY_CSH_AMT,
exp_pass_through.OUT_BAL_COMMENTS as OUT_BAL_COMMENTS,
exp_pass_through.VOID_COMMENTS as VOID_COMMENTS,
exp_pass_through.CUR_STAT_CD as CUR_STAT_CD,
exp_pass_through.CUR_STAT_DT as CUR_STAT_DT,
exp_pass_through.CUR_STAT_TM as CUR_STAT_TM,
exp_pass_through.CUR_STAT_USER as CUR_STAT_USER,
exp_pass_through.CUR_STAT_INIT as CUR_STAT_INIT,
exp_pass_through.PRV_STAT_CD as PRV_STAT_CD,
exp_pass_through.PRV_STAT_DT as PRV_STAT_DT,
exp_pass_through.PRV_STAT_TM as PRV_STAT_TM,
exp_pass_through.PRV_STAT_USER as PRV_STAT_USER,
exp_pass_through.PRV_STAT_INIT as PRV_STAT_INIT,
exp_pass_through.GL_ACCT_NBR as GL_ACCT_NBR,
exp_pass_through.GL_DEPT_ID as GL_DEPT_ID,
exp_pass_through.GL_BATCH_TX_NBR as GL_BATCH_TX_NBR,
exp_pass_through.ACH_PROCESS_DT as ACH_PROCESS_DT,
exp_pass_through.ACH_SETTLEMENT_DT as ACH_SETTLEMENT_DT,
exp_pass_through.HO_SVC_DEP_ADJ_AMT as HO_SVC_DEP_ADJ_AMT,
exp_pass_through.DISB_ACH_SETLMT_DT as DISB_ACH_SETLMT_DT,
exp_pass_through.DEP_MARKED as DEP_MARKED,
exp_pass_through.SYST_EPO_TOT as SYST_EPO_TOT,
exp_pass_through.ACTL_EPO_TOT as ACTL_EPO_TOT,
exp_pass_through.NBR_EPO_PROC as NBR_EPO_PROC,
exp_pass_through.VISION_CSH_TOT as VISION_CSH_TOT,
exp_pass_through.NUM_REC_INV_POLS as NUM_REC_INV_POLS
FROM
exp_pass_through;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_CPS_PMT_DEP1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CPS_PMT_DEP1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_Count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
select count(*) as record_count
from DB_T_ML_PROD.cps_pmt_dep
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_CPS_PMT_DEP1.record_Count as record_count,
:feed_ind as feed_ind,
to_char ( CURRENT_TIMESTAMP , ''YYYY-MM-DD'' ) as feed_dt,
SQ_CPS_PMT_DEP1.source_record_id
FROM
SQ_CPS_PMT_DEP1
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 2

END; ';