-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_CPS_PMT_ITM("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 

-- Component CPS_PMT_ITM2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_ML_PROD.CPS_PMT_ITM;


-- PIPELINE START FOR 1

-- Component SQ_CPS_PMT_ITM, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CPS_PMT_ITM AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
select count(*) as record_count
from DB_T_ML_PROD.cps_pmt_rct
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
TO_NUMBER(SQ_CPS_PMT_ITM.record_count) as o_record_count,
:feed_ind as feed_ind,
to_char ( CURRENT_TIMESTAMP , ''YYYY-MM-DD'' ) as feed_dt,
SQ_CPS_PMT_ITM.source_record_id
FROM
SQ_CPS_PMT_ITM
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.o_record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_CPS_PMT_ITM1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CPS_PMT_ITM1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as RECEIPT_NBR,
$2 as ITEM_NBR,
$3 as SEQ_NBR,
$4 as AMT_PAID,
$5 as SYST,
$6 as PYMT_TYPE,
$7 as ADD_PYMT_TYPE,
$8 as MAN_RSN_CD,
$9 as DUE_DT,
$10 as MBR_CUST_NBR,
$11 as SOC_SEC_NBR,
$12 as LF_PY_CLT_NBR,
$13 as PVT_SORT_CD_1,
$14 as PVT_SORT_CD_2,
$15 as PVT_AMT_1,
$16 as PVT_AMT_2,
$17 as PVT_AMT_3,
$18 as PVT_AMT_4,
$19 as PVT_DUE_DT_ALFA,
$20 as CMPY_NBR,
$21 as ITEM_ST_NBR,
$22 as CLT_NAME,
$23 as PVT_CUR_AS_OF_DT,
$24 as SVC_NBR,
$25 as PVT_APPL_CD,
$26 as DUES_COUNTY,
$27 as ITEM_DESC,
$28 as PVT_VAL_CD,
$29 as PVT_S3_POL_SYM,
$30 as PVT_S3_POL_NBR,
$31 as PVT_LF_TURN_NBR,
$32 as PCTERM_LFMODE,
$33 as TAX_YR,
$34 as COMMENTS,
$35 as CUR_STAT_CD,
$36 as CUR_STAT_DT,
$37 as CUR_STAT_TM,
$38 as CUR_STAT_SRCE,
$39 as PRV_STAT_CD,
$40 as PRV_STAT_DT,
$41 as PRV_STAT_TM,
$42 as PRV_STAT_SRCE,
$43 as PRV_STAT_CD1,
$44 as PRV_STAT_DT1,
$45 as PRV_STAT_TM1,
$46 as PRV_STAT_SRCE1,
$47 as PRV_STAT_CD2,
$48 as PRV_STAT_DT2,
$49 as PRV_STAT_TM2,
$50 as PRV_STAT_SRCE2,
$51 as PRV_STAT_CD3,
$52 as PRV_STAT_DT3,
$53 as PRV_STAT_TM3,
$54 as PRV_STAT_SRCE3,
$55 as BATCH_STAT_CD,
$56 as BATCH_STAT_DT,
$57 as BATCH_STAT_TM,
$58 as BATCH_STAT_SRCE,
$59 as APPLIED_ITEM_NBR,
$60 as APPLIED_DT,
$61 as CHGD_ITEM_NBR,
$62 as CHGD_ITEM_DT,
$63 as CHGD_ITEM_TM,
$64 as CHGD_ITEM_SOURCE,
$65 as SRCH_ITEM_NBR,
$66 as BAL_TYPE,
$67 as DRT_EXTR_PROC_DT,
$68 as IN_APPLIED_BAL_IND,
$69 as PAID_DT,
$70 as PVT_SVC_NBR,
$71 as ITM_ORD_GROUP,
$72 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT RECEIPT_NBR,
ITEM_NBR,
SEQ_NBR,
AMT_PAID,
SYST,
PYMT_TYPE,
ADD_PYMT_TYPE,
MAN_RSN_CD,
DUE_DT,
MBR_CUST_NBR,
SOC_SEC_NBR,
LF_PY_CLT_NBR,
PVT_SORT_CD_1,
PVT_SORT_CD_2,
PVT_AMT_1,
PVT_AMT_2,
PVT_AMT_3,
PVT_AMT_4,
PVT_DUE_DT_ALFA,
CMPY_NBR,
ITEM_ST_NBR,
CLT_NAME,
PVT_CUR_AS_OF_DT,
SVC_NBR,
PVT_APPL_CD,
DUES_COUNTY,
ITEM_DESC,
PVT_VAL_CD,
PVT_S3_POL_SYM,
PVT_S3_POL_NBR,
PVT_LF_TURN_NBR,
PCTERM_LFMODE,
TAX_YR,
COMMENTS,
CUR_STAT_CD,
CUR_STAT_DT,
CAST(CUR_STAT_TM AS VARCHAR(8)) AS CUR_STAT_TM,
CUR_STAT_SRCE,
PRV_STAT_CD,
PRV_STAT_DT,
CAST(PRV_STAT_TM AS VARCHAR(8)) AS PRV_STAT_TM,
PRV_STAT_SRCE,
PRV_STAT_CD1,
PRV_STAT_DT1,
CAST(PRV_STAT_TM1 AS VARCHAR(8)) AS PRV_STAT_TM1,
PRV_STAT_SRCE1,
PRV_STAT_CD2,
PRV_STAT_DT2,
CAST(PRV_STAT_TM2 AS VARCHAR(8)) AS PRV_STAT_TM2,
PRV_STAT_SRCE2,
PRV_STAT_CD3,
PRV_STAT_DT3,
CAST(PRV_STAT_TM3 AS VARCHAR(8)) AS PRV_STAT_TM3,
PRV_STAT_SRCE3,
BATCH_STAT_CD,
BATCH_STAT_DT,
CAST(BATCH_STAT_TM AS VARCHAR(8)) AS BATCH_STAT_TM,
BATCH_STAT_SRCE,
APPLIED_ITEM_NBR,
APPLIED_DT,
CHGD_ITEM_NBR,
CHGD_ITEM_DT,
CAST(CHGD_ITEM_TM AS VARCHAR(8)) AS CHGD_ITEM_TM,
CHGD_ITEM_SOURCE,
SRCH_ITEM_NBR,
BAL_TYPE,
DRT_EXTR_PROC_DT,
IN_APPLIED_BAL_IND,
PAID_DT,
PVT_SVC_NBR,
ITM_ORD_GROUP FROM DB_T_ML_PROD.CPS_PMT_ITM
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_CPS_PMT_ITM1.RECEIPT_NBR as RECEIPT_NBR,
SQ_CPS_PMT_ITM1.ITEM_NBR as ITEM_NBR,
SQ_CPS_PMT_ITM1.SEQ_NBR as SEQ_NBR,
SQ_CPS_PMT_ITM1.AMT_PAID as AMT_PAID,
SQ_CPS_PMT_ITM1.SYST as SYST,
SQ_CPS_PMT_ITM1.PYMT_TYPE as PYMT_TYPE,
SQ_CPS_PMT_ITM1.ADD_PYMT_TYPE as ADD_PYMT_TYPE,
SQ_CPS_PMT_ITM1.MAN_RSN_CD as MAN_RSN_CD,
SQ_CPS_PMT_ITM1.DUE_DT as DUE_DT,
SQ_CPS_PMT_ITM1.MBR_CUST_NBR as MBR_CUST_NBR,
SQ_CPS_PMT_ITM1.SOC_SEC_NBR as SOC_SEC_NBR,
SQ_CPS_PMT_ITM1.LF_PY_CLT_NBR as LF_PY_CLT_NBR,
SQ_CPS_PMT_ITM1.PVT_SORT_CD_1 as PVT_SORT_CD_1,
SQ_CPS_PMT_ITM1.PVT_SORT_CD_2 as PVT_SORT_CD_2,
SQ_CPS_PMT_ITM1.PVT_AMT_1 as PVT_AMT_1,
SQ_CPS_PMT_ITM1.PVT_AMT_2 as PVT_AMT_2,
SQ_CPS_PMT_ITM1.PVT_AMT_3 as PVT_AMT_3,
SQ_CPS_PMT_ITM1.PVT_AMT_4 as PVT_AMT_4,
SQ_CPS_PMT_ITM1.PVT_DUE_DT_ALFA as PVT_DUE_DT_ALFA,
SQ_CPS_PMT_ITM1.CMPY_NBR as CMPY_NBR,
SQ_CPS_PMT_ITM1.ITEM_ST_NBR as ITEM_ST_NBR,
SQ_CPS_PMT_ITM1.CLT_NAME as CLT_NAME,
SQ_CPS_PMT_ITM1.PVT_CUR_AS_OF_DT as PVT_CUR_AS_OF_DT,
SQ_CPS_PMT_ITM1.SVC_NBR as SVC_NBR,
SQ_CPS_PMT_ITM1.PVT_APPL_CD as PVT_APPL_CD,
SQ_CPS_PMT_ITM1.DUES_COUNTY as DUES_COUNTY,
SQ_CPS_PMT_ITM1.ITEM_DESC as ITEM_DESC,
SQ_CPS_PMT_ITM1.PVT_VAL_CD as PVT_VAL_CD,
SQ_CPS_PMT_ITM1.PVT_S3_POL_SYM as PVT_S3_POL_SYM,
SQ_CPS_PMT_ITM1.PVT_S3_POL_NBR as PVT_S3_POL_NBR,
SQ_CPS_PMT_ITM1.PVT_LF_TURN_NBR as PVT_LF_TURN_NBR,
SQ_CPS_PMT_ITM1.PCTERM_LFMODE as PCTERM_LFMODE,
SQ_CPS_PMT_ITM1.TAX_YR as TAX_YR,
SQ_CPS_PMT_ITM1.COMMENTS as COMMENTS,
SQ_CPS_PMT_ITM1.CUR_STAT_CD as CUR_STAT_CD,
SQ_CPS_PMT_ITM1.CUR_STAT_DT as CUR_STAT_DT,
SQ_CPS_PMT_ITM1.CUR_STAT_TM as CUR_STAT_TM,
SQ_CPS_PMT_ITM1.CUR_STAT_SRCE as CUR_STAT_SRCE,
SQ_CPS_PMT_ITM1.PRV_STAT_CD as PRV_STAT_CD,
SQ_CPS_PMT_ITM1.PRV_STAT_DT as PRV_STAT_DT,
SQ_CPS_PMT_ITM1.PRV_STAT_TM as PRV_STAT_TM,
SQ_CPS_PMT_ITM1.PRV_STAT_SRCE as PRV_STAT_SRCE,
SQ_CPS_PMT_ITM1.PRV_STAT_CD1 as PRV_STAT_CD1,
SQ_CPS_PMT_ITM1.PRV_STAT_DT1 as PRV_STAT_DT1,
SQ_CPS_PMT_ITM1.PRV_STAT_TM1 as PRV_STAT_TM1,
SQ_CPS_PMT_ITM1.PRV_STAT_SRCE1 as PRV_STAT_SRCE1,
SQ_CPS_PMT_ITM1.PRV_STAT_CD2 as PRV_STAT_CD2,
SQ_CPS_PMT_ITM1.PRV_STAT_DT2 as PRV_STAT_DT2,
SQ_CPS_PMT_ITM1.PRV_STAT_TM2 as PRV_STAT_TM2,
SQ_CPS_PMT_ITM1.PRV_STAT_SRCE2 as PRV_STAT_SRCE2,
SQ_CPS_PMT_ITM1.PRV_STAT_CD3 as PRV_STAT_CD3,
SQ_CPS_PMT_ITM1.PRV_STAT_DT3 as PRV_STAT_DT3,
SQ_CPS_PMT_ITM1.PRV_STAT_TM3 as PRV_STAT_TM3,
SQ_CPS_PMT_ITM1.PRV_STAT_SRCE3 as PRV_STAT_SRCE3,
SQ_CPS_PMT_ITM1.BATCH_STAT_CD as BATCH_STAT_CD,
SQ_CPS_PMT_ITM1.BATCH_STAT_DT as BATCH_STAT_DT,
SQ_CPS_PMT_ITM1.BATCH_STAT_TM as BATCH_STAT_TM,
SQ_CPS_PMT_ITM1.BATCH_STAT_SRCE as BATCH_STAT_SRCE,
SQ_CPS_PMT_ITM1.APPLIED_ITEM_NBR as APPLIED_ITEM_NBR,
SQ_CPS_PMT_ITM1.APPLIED_DT as APPLIED_DT,
SQ_CPS_PMT_ITM1.CHGD_ITEM_NBR as CHGD_ITEM_NBR,
SQ_CPS_PMT_ITM1.CHGD_ITEM_DT as CHGD_ITEM_DT,
SQ_CPS_PMT_ITM1.CHGD_ITEM_TM as CHGD_ITEM_TM,
SQ_CPS_PMT_ITM1.CHGD_ITEM_SOURCE as CHGD_ITEM_SOURCE,
SQ_CPS_PMT_ITM1.SRCH_ITEM_NBR as SRCH_ITEM_NBR,
SQ_CPS_PMT_ITM1.BAL_TYPE as BAL_TYPE,
SQ_CPS_PMT_ITM1.DRT_EXTR_PROC_DT as DRT_EXTR_PROC_DT,
SQ_CPS_PMT_ITM1.IN_APPLIED_BAL_IND as IN_APPLIED_BAL_IND,
SQ_CPS_PMT_ITM1.PAID_DT as PAID_DT,
SQ_CPS_PMT_ITM1.PVT_SVC_NBR as PVT_SVC_NBR,
SQ_CPS_PMT_ITM1.ITM_ORD_GROUP as ITM_ORD_GROUP,
SQ_CPS_PMT_ITM1.source_record_id
FROM
SQ_CPS_PMT_ITM1
);


-- Component CPS_PMT_ITM2, Type TARGET 
INSERT INTO DB_T_ML_PROD.CPS_PMT_ITM
(
RECEIPT_NBR,
ITEM_NBR,
SEQ_NBR,
AMT_PAID,
SYST,
PYMT_TYPE,
ADD_PYMT_TYPE,
MAN_RSN_CD,
DUE_DT,
MBR_CUST_NBR,
SOC_SEC_NBR,
LF_PY_CLT_NBR,
PVT_SORT_CD_1,
PVT_SORT_CD_2,
PVT_AMT_1,
PVT_AMT_2,
PVT_AMT_3,
PVT_AMT_4,
PVT_DUE_DT_ALFA,
CMPY_NBR,
ITEM_ST_NBR,
CLT_NAME,
PVT_CUR_AS_OF_DT,
SVC_NBR,
PVT_APPL_CD,
DUES_COUNTY,
ITEM_DESC,
PVT_VAL_CD,
PVT_S3_POL_SYM,
PVT_S3_POL_NBR,
PVT_LF_TURN_NBR,
PCTERM_LFMODE,
TAX_YR,
COMMENTS,
CUR_STAT_CD,
CUR_STAT_DT,
CUR_STAT_TM,
CUR_STAT_SRCE,
PRV_STAT_CD,
PRV_STAT_DT,
PRV_STAT_TM,
PRV_STAT_SRCE,
PRV_STAT_CD1,
PRV_STAT_DT1,
PRV_STAT_TM1,
PRV_STAT_SRCE1,
PRV_STAT_CD2,
PRV_STAT_DT2,
PRV_STAT_TM2,
PRV_STAT_SRCE2,
PRV_STAT_CD3,
PRV_STAT_DT3,
PRV_STAT_TM3,
PRV_STAT_SRCE3,
BATCH_STAT_CD,
BATCH_STAT_DT,
BATCH_STAT_TM,
BATCH_STAT_SRCE,
APPLIED_ITEM_NBR,
APPLIED_DT,
CHGD_ITEM_NBR,
CHGD_ITEM_DT,
CHGD_ITEM_TM,
CHGD_ITEM_SOURCE,
SRCH_ITEM_NBR,
BAL_TYPE,
DRT_EXTR_PROC_DT,
IN_APPLIED_BAL_IND,
PAID_DT,
PVT_SVC_NBR,
ITM_ORD_GROUP
)
SELECT
exp_pass_through.RECEIPT_NBR as RECEIPT_NBR,
exp_pass_through.ITEM_NBR as ITEM_NBR,
exp_pass_through.SEQ_NBR as SEQ_NBR,
exp_pass_through.AMT_PAID as AMT_PAID,
exp_pass_through.SYST as SYST,
exp_pass_through.PYMT_TYPE as PYMT_TYPE,
exp_pass_through.ADD_PYMT_TYPE as ADD_PYMT_TYPE,
exp_pass_through.MAN_RSN_CD as MAN_RSN_CD,
exp_pass_through.DUE_DT as DUE_DT,
exp_pass_through.MBR_CUST_NBR as MBR_CUST_NBR,
exp_pass_through.SOC_SEC_NBR as SOC_SEC_NBR,
exp_pass_through.LF_PY_CLT_NBR as LF_PY_CLT_NBR,
exp_pass_through.PVT_SORT_CD_1 as PVT_SORT_CD_1,
exp_pass_through.PVT_SORT_CD_2 as PVT_SORT_CD_2,
exp_pass_through.PVT_AMT_1 as PVT_AMT_1,
exp_pass_through.PVT_AMT_2 as PVT_AMT_2,
exp_pass_through.PVT_AMT_3 as PVT_AMT_3,
exp_pass_through.PVT_AMT_4 as PVT_AMT_4,
exp_pass_through.PVT_DUE_DT_ALFA as PVT_DUE_DT_ALFA,
exp_pass_through.CMPY_NBR as CMPY_NBR,
exp_pass_through.ITEM_ST_NBR as ITEM_ST_NBR,
exp_pass_through.CLT_NAME as CLT_NAME,
exp_pass_through.PVT_CUR_AS_OF_DT as PVT_CUR_AS_OF_DT,
exp_pass_through.SVC_NBR as SVC_NBR,
exp_pass_through.PVT_APPL_CD as PVT_APPL_CD,
exp_pass_through.DUES_COUNTY as DUES_COUNTY,
exp_pass_through.ITEM_DESC as ITEM_DESC,
exp_pass_through.PVT_VAL_CD as PVT_VAL_CD,
exp_pass_through.PVT_S3_POL_SYM as PVT_S3_POL_SYM,
exp_pass_through.PVT_S3_POL_NBR as PVT_S3_POL_NBR,
exp_pass_through.PVT_LF_TURN_NBR as PVT_LF_TURN_NBR,
exp_pass_through.PCTERM_LFMODE as PCTERM_LFMODE,
exp_pass_through.TAX_YR as TAX_YR,
exp_pass_through.COMMENTS as COMMENTS,
exp_pass_through.CUR_STAT_CD as CUR_STAT_CD,
exp_pass_through.CUR_STAT_DT as CUR_STAT_DT,
exp_pass_through.CUR_STAT_TM as CUR_STAT_TM,
exp_pass_through.CUR_STAT_SRCE as CUR_STAT_SRCE,
exp_pass_through.PRV_STAT_CD as PRV_STAT_CD,
exp_pass_through.PRV_STAT_DT as PRV_STAT_DT,
exp_pass_through.PRV_STAT_TM as PRV_STAT_TM,
exp_pass_through.PRV_STAT_SRCE as PRV_STAT_SRCE,
exp_pass_through.PRV_STAT_CD1 as PRV_STAT_CD1,
exp_pass_through.PRV_STAT_DT1 as PRV_STAT_DT1,
exp_pass_through.PRV_STAT_TM1 as PRV_STAT_TM1,
exp_pass_through.PRV_STAT_SRCE1 as PRV_STAT_SRCE1,
exp_pass_through.PRV_STAT_CD2 as PRV_STAT_CD2,
exp_pass_through.PRV_STAT_DT2 as PRV_STAT_DT2,
exp_pass_through.PRV_STAT_TM2 as PRV_STAT_TM2,
exp_pass_through.PRV_STAT_SRCE2 as PRV_STAT_SRCE2,
exp_pass_through.PRV_STAT_CD3 as PRV_STAT_CD3,
exp_pass_through.PRV_STAT_DT3 as PRV_STAT_DT3,
exp_pass_through.PRV_STAT_TM3 as PRV_STAT_TM3,
exp_pass_through.PRV_STAT_SRCE3 as PRV_STAT_SRCE3,
exp_pass_through.BATCH_STAT_CD as BATCH_STAT_CD,
exp_pass_through.BATCH_STAT_DT as BATCH_STAT_DT,
exp_pass_through.BATCH_STAT_TM as BATCH_STAT_TM,
exp_pass_through.BATCH_STAT_SRCE as BATCH_STAT_SRCE,
exp_pass_through.APPLIED_ITEM_NBR as APPLIED_ITEM_NBR,
exp_pass_through.APPLIED_DT as APPLIED_DT,
exp_pass_through.CHGD_ITEM_NBR as CHGD_ITEM_NBR,
exp_pass_through.CHGD_ITEM_DT as CHGD_ITEM_DT,
exp_pass_through.CHGD_ITEM_TM as CHGD_ITEM_TM,
exp_pass_through.CHGD_ITEM_SOURCE as CHGD_ITEM_SOURCE,
exp_pass_through.SRCH_ITEM_NBR as SRCH_ITEM_NBR,
exp_pass_through.BAL_TYPE as BAL_TYPE,
exp_pass_through.DRT_EXTR_PROC_DT as DRT_EXTR_PROC_DT,
exp_pass_through.IN_APPLIED_BAL_IND as IN_APPLIED_BAL_IND,
exp_pass_through.PAID_DT as PAID_DT,
exp_pass_through.PVT_SVC_NBR as PVT_SVC_NBR,
exp_pass_through.ITM_ORD_GROUP as ITM_ORD_GROUP
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';