-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_CPS_PMT_RCT("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
BEGIN 

FEED_IND:=(select DAILY_FEED_IND from DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG where ECTL_BATCH_ID= :run_id); 

-- Component CPS_PMT_RCT2, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_ML_PROD.CPS_PMT_RCT;


-- PIPELINE START FOR 1

-- Component SQ_CPS_PMT_RCT1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CPS_PMT_RCT1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as record_count,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
select count(*) as record_count
from DB_T_ML_PROD.cps_pmt_rct
) SRC
)
);


-- Component exp_rec_cnt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_rec_cnt AS
(
SELECT
SQ_CPS_PMT_RCT1.record_count as record_count,
:feed_ind as feed_ind,
to_char ( CURRENT_TIMESTAMP , ''YYYY-MM-DD'' ) as feed_dt,
SQ_CPS_PMT_RCT1.source_record_id
FROM
SQ_CPS_PMT_RCT1
);


-- Component TRG_MEMBXREF, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE TRG_MEMBXREF AS
(
SELECT
exp_rec_cnt.feed_ind as feed_ind,
exp_rec_cnt.feed_dt as feed_dt,
exp_rec_cnt.record_count as record_cnt
FROM
exp_rec_cnt
);


-- Component TRG_MEMBXREF, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_CPS_PMT_RCT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_CPS_PMT_RCT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as RECEIPT_NBR,
$2 as SVC_NBR,
$3 as CUR_STAT_CD,
$4 as CUR_STAT_DT,
$5 as CUR_STAT_TM,
$6 as PRV_STAT_CD,
$7 as PRV_STAT_DT,
$8 as PRV_STAT_TM,
$9 as DEPOSIT_NBR,
$10 as SVC_ST_NBR,
$11 as SYST_USER,
$12 as SYST_DT,
$13 as SYST_TM,
$14 as ENTRY_INIT,
$15 as TOT_RCT_AMT,
$16 as CHK_TOT,
$17 as CSH_TOT,
$18 as EPO_TOT,
$19 as VOID_COMMENTS,
$20 as ORIG_RCT_NBR,
$21 as REPLACEDBY_RCT_NBR,
$22 as PRV_RCT_NBR,
$23 as FLD_RCT_NBR,
$24 as FLD_RCT_DT,
$25 as FLD_RCT_TM,
$26 as CUR_STAT_USER,
$27 as CUR_STAT_INIT,
$28 as PRV_STAT_USER,
$29 as PRV_STAT_INIT,
$30 as CHK_APPLD_COMMENTS,
$31 as LEGAL_EMAIL,
$32 as PYMT_SRCE,
$33 as BATCH_NBR,
$34 as TRANS_NBR,
$35 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 
RECEIPT_NBR,
SVC_NBR,
CUR_STAT_CD,
CUR_STAT_DT,
CAST(CUR_STAT_TM AS VARCHAR(8)) AS CUR_STAT_TM,
PRV_STAT_CD,
PRV_STAT_DT,
CAST(PRV_STAT_TM AS VARCHAR(8)) AS PRV_STAT_TM,
DEPOSIT_NBR,
SVC_ST_NBR,
SYST_USER,
SYST_DT,
CAST(SYST_TM AS VARCHAR(8)) AS SYST_TM,
ENTRY_INIT,
TOT_RCT_AMT,
CHK_TOT,
CSH_TOT,
EPO_TOT,
VOID_COMMENTS,
ORIG_RCT_NBR,
REPLACEDBY_RCT_NBR,
PRV_RCT_NBR,
FLD_RCT_NBR,
FLD_RCT_DT,
CAST(FLD_RCT_TM AS VARCHAR(8)) AS FLD_RCT_TM,
CUR_STAT_USER,
CUR_STAT_INIT,
PRV_STAT_USER,
PRV_STAT_INIT,
CHK_APPLD_COMMENTS,
LEGAL_EMAIL,
PYMT_SRCE,
BATCH_NBR,
TRANS_NBR FROM DB_T_ML_PROD.CPS_PMT_RCT
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_CPS_PMT_RCT.RECEIPT_NBR as RECEIPT_NBR,
SQ_CPS_PMT_RCT.SVC_NBR as SVC_NBR,
SQ_CPS_PMT_RCT.CUR_STAT_CD as CUR_STAT_CD,
SQ_CPS_PMT_RCT.CUR_STAT_DT as CUR_STAT_DT,
SQ_CPS_PMT_RCT.CUR_STAT_TM as CUR_STAT_TM,
SQ_CPS_PMT_RCT.PRV_STAT_CD as PRV_STAT_CD,
SQ_CPS_PMT_RCT.PRV_STAT_DT as PRV_STAT_DT,
SQ_CPS_PMT_RCT.PRV_STAT_TM as PRV_STAT_TM,
SQ_CPS_PMT_RCT.DEPOSIT_NBR as DEPOSIT_NBR,
SQ_CPS_PMT_RCT.SVC_ST_NBR as SVC_ST_NBR,
SQ_CPS_PMT_RCT.SYST_USER as SYST_USER,
SQ_CPS_PMT_RCT.SYST_DT as SYST_DT,
SQ_CPS_PMT_RCT.SYST_TM as SYST_TM,
SQ_CPS_PMT_RCT.ENTRY_INIT as ENTRY_INIT,
SQ_CPS_PMT_RCT.TOT_RCT_AMT as TOT_RCT_AMT,
SQ_CPS_PMT_RCT.CHK_TOT as CHK_TOT,
SQ_CPS_PMT_RCT.CSH_TOT as CSH_TOT,
SQ_CPS_PMT_RCT.EPO_TOT as EPO_TOT,
SQ_CPS_PMT_RCT.VOID_COMMENTS as VOID_COMMENTS,
SQ_CPS_PMT_RCT.ORIG_RCT_NBR as ORIG_RCT_NBR,
SQ_CPS_PMT_RCT.REPLACEDBY_RCT_NBR as REPLACEDBY_RCT_NBR,
SQ_CPS_PMT_RCT.PRV_RCT_NBR as PRV_RCT_NBR,
SQ_CPS_PMT_RCT.FLD_RCT_NBR as FLD_RCT_NBR,
SQ_CPS_PMT_RCT.FLD_RCT_DT as FLD_RCT_DT,
SQ_CPS_PMT_RCT.FLD_RCT_TM as FLD_RCT_TM,
SQ_CPS_PMT_RCT.CUR_STAT_USER as CUR_STAT_USER,
SQ_CPS_PMT_RCT.CUR_STAT_INIT as CUR_STAT_INIT,
SQ_CPS_PMT_RCT.PRV_STAT_USER as PRV_STAT_USER,
SQ_CPS_PMT_RCT.PRV_STAT_INIT as PRV_STAT_INIT,
SQ_CPS_PMT_RCT.CHK_APPLD_COMMENTS as CHK_APPLD_COMMENTS,
SQ_CPS_PMT_RCT.LEGAL_EMAIL as LEGAL_EMAIL,
SQ_CPS_PMT_RCT.PYMT_SRCE as PYMT_SRCE,
SQ_CPS_PMT_RCT.BATCH_NBR as BATCH_NBR,
SQ_CPS_PMT_RCT.TRANS_NBR as TRANS_NBR,
SQ_CPS_PMT_RCT.source_record_id
FROM
SQ_CPS_PMT_RCT
);


-- Component CPS_PMT_RCT2, Type TARGET 
INSERT INTO DB_T_ML_PROD.CPS_PMT_RCT
(
RECEIPT_NBR,
SVC_NBR,
CUR_STAT_CD,
CUR_STAT_DT,
CUR_STAT_TM,
PRV_STAT_CD,
PRV_STAT_DT,
PRV_STAT_TM,
DEPOSIT_NBR,
SVC_ST_NBR,
SYST_USER,
SYST_DT,
SYST_TM,
ENTRY_INIT,
TOT_RCT_AMT,
CHK_TOT,
CSH_TOT,
EPO_TOT,
VOID_COMMENTS,
ORIG_RCT_NBR,
REPLACEDBY_RCT_NBR,
PRV_RCT_NBR,
FLD_RCT_NBR,
FLD_RCT_DT,
FLD_RCT_TM,
CUR_STAT_USER,
CUR_STAT_INIT,
PRV_STAT_USER,
PRV_STAT_INIT,
CHK_APPLD_COMMENTS,
LEGAL_EMAIL,
PYMT_SRCE,
BATCH_NBR,
TRANS_NBR
)
SELECT
exp_pass_through.RECEIPT_NBR as RECEIPT_NBR,
exp_pass_through.SVC_NBR as SVC_NBR,
exp_pass_through.CUR_STAT_CD as CUR_STAT_CD,
exp_pass_through.CUR_STAT_DT as CUR_STAT_DT,
exp_pass_through.CUR_STAT_TM as CUR_STAT_TM,
exp_pass_through.PRV_STAT_CD as PRV_STAT_CD,
exp_pass_through.PRV_STAT_DT as PRV_STAT_DT,
exp_pass_through.PRV_STAT_TM as PRV_STAT_TM,
exp_pass_through.DEPOSIT_NBR as DEPOSIT_NBR,
exp_pass_through.SVC_ST_NBR as SVC_ST_NBR,
exp_pass_through.SYST_USER as SYST_USER,
exp_pass_through.SYST_DT as SYST_DT,
exp_pass_through.SYST_TM as SYST_TM,
exp_pass_through.ENTRY_INIT as ENTRY_INIT,
exp_pass_through.TOT_RCT_AMT as TOT_RCT_AMT,
exp_pass_through.CHK_TOT as CHK_TOT,
exp_pass_through.CSH_TOT as CSH_TOT,
exp_pass_through.EPO_TOT as EPO_TOT,
exp_pass_through.VOID_COMMENTS as VOID_COMMENTS,
exp_pass_through.ORIG_RCT_NBR as ORIG_RCT_NBR,
exp_pass_through.REPLACEDBY_RCT_NBR as REPLACEDBY_RCT_NBR,
exp_pass_through.PRV_RCT_NBR as PRV_RCT_NBR,
exp_pass_through.FLD_RCT_NBR as FLD_RCT_NBR,
exp_pass_through.FLD_RCT_DT as FLD_RCT_DT,
exp_pass_through.FLD_RCT_TM as FLD_RCT_TM,
exp_pass_through.CUR_STAT_USER as CUR_STAT_USER,
exp_pass_through.CUR_STAT_INIT as CUR_STAT_INIT,
exp_pass_through.PRV_STAT_USER as PRV_STAT_USER,
exp_pass_through.PRV_STAT_INIT as PRV_STAT_INIT,
exp_pass_through.CHK_APPLD_COMMENTS as CHK_APPLD_COMMENTS,
exp_pass_through.LEGAL_EMAIL as LEGAL_EMAIL,
exp_pass_through.PYMT_SRCE as PYMT_SRCE,
exp_pass_through.BATCH_NBR as BATCH_NBR,
exp_pass_through.TRANS_NBR as TRANS_NBR
FROM
exp_pass_through;


-- PIPELINE END FOR 2

END; ';