-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_STG_ING_POL_LIST("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- PIPELINE START FOR 1
-- Component STG_ING_POL_LIST_PRE_SQL, Type Pre SQL 
DELETE FROM DB_T_STAG_MEMBXREF_PROD.STG_ING_POL_LIST where load_dt in
(select distinct a.load_dt from	DB_T_STAG_MEMBXREF_PROD.STG_ING_POL_LIST A
	,DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
WHERE
	A.LOAD_DT = B.FEED_DT
	AND B.TABLENAME = ''ING_POL_LIST'');


-- Component SQ_ING_POL_LIST1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ING_POL_LIST1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CO_ID,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 	ING_POL_LIST.CO_ID FROM DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST WHERE 1=2
) SRC
)
);


-- Component exp_Pass_Through1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Pass_Through1 AS
(
SELECT
SQ_ING_POL_LIST1.CO_ID as CO_ID,
SQ_ING_POL_LIST1.source_record_id
FROM
SQ_ING_POL_LIST1
);


-- Component STG_ING_POL_LIST_PRE_SQL, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_ING_POL_LIST
(
CO_ID
)
SELECT
exp_Pass_Through1.CO_ID as CO_ID
FROM
exp_Pass_Through1;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_ING_POL_LIST, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ING_POL_LIST AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CO_ID,
$2 as POL_ID,
$3 as INSURED_MEMBER_NUM,
$4 as PAYOR_MEMBER_NUM,
$5 as ALPHA_CODE_INSURED,
$6 as ALPHA_CODE_OWNER,
$7 as ALPHA_CODE_PAYOR,
$8 as ALPHA_CODE_JOINT,
$9 as INSURED_FIRST_NM,
$10 as INSURED_MID_NM,
$11 as INSURED_LAST_NM,
$12 as INSURED_SFX_NM,
$13 as PAYOR_FIRST_NM,
$14 as PAYOR_MID_NM,
$15 as PAYOR_LAST_NM,
$16 as PAYOR_SFX_NM,
$17 as INSURED_ADDR_LN_1,
$18 as INSURED_ADDR_LN_2,
$19 as INSURED_CITY_NM,
$20 as INSURED_STATE_CD,
$21 as INSURED_ZIP_CD,
$22 as INSURED_CLI_ID,
$23 as OWNER_CLI_ID,
$24 as PAYOR_CLI_ID,
$25 as SEC_INSURED_CLI_ID,
$26 as INSURED_SSN,
$27 as OWNER_SSN,
$28 as PAYOR_SSN,
$29 as SEC_INSURED_SSN,
$30 as AGT_ID,
$31 as POL_ISS_DT,
$32 as SERV_CENTER_NUM,
$33 as POLICY_TYPE,
$34 as POL_STATUS,
$35 as POL_CNFD_IND,
$36 as BASE_PLAN_ID,
$37 as BASE_FACE_AMT,
$38 as BILL_MODE,
$39 as CURR_CASH_VALUE,
$40 as OWNER_FIRST_NM,
$41 as OWNER_MID_NM,
$42 as OWNER_LAST_NM,
$43 as OWNER_SFX_NM,
$44 as LOAD_DT,
$45 as FEED_IND,
$46 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 	
	A.*
	,B.FEED_DT,B.FEED_IND
FROM 
	DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST A
	JOIN
	DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER B
	ON 1=1
WHERE
	TABLENAME = ''ING_POL_LIST''
) SRC
)
);


-- Component exp_Pass_Through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Pass_Through AS
(
SELECT
SQ_ING_POL_LIST.CO_ID as CO_ID,
SQ_ING_POL_LIST.POL_ID as POL_ID,
SQ_ING_POL_LIST.INSURED_MEMBER_NUM as INSURED_MEMBER_NUM,
SQ_ING_POL_LIST.PAYOR_MEMBER_NUM as PAYOR_MEMBER_NUM,
SQ_ING_POL_LIST.ALPHA_CODE_INSURED as ALPHA_CODE_INSURED,
SQ_ING_POL_LIST.ALPHA_CODE_OWNER as ALPHA_CODE_OWNER,
SQ_ING_POL_LIST.ALPHA_CODE_PAYOR as ALPHA_CODE_PAYOR,
SQ_ING_POL_LIST.ALPHA_CODE_JOINT as ALPHA_CODE_JOINT,
SQ_ING_POL_LIST.INSURED_FIRST_NM as INSURED_FIRST_NM,
SQ_ING_POL_LIST.INSURED_MID_NM as INSURED_MID_NM,
SQ_ING_POL_LIST.INSURED_LAST_NM as INSURED_LAST_NM,
SQ_ING_POL_LIST.INSURED_SFX_NM as INSURED_SFX_NM,
SQ_ING_POL_LIST.PAYOR_FIRST_NM as PAYOR_FIRST_NM,
SQ_ING_POL_LIST.PAYOR_MID_NM as PAYOR_MID_NM,
SQ_ING_POL_LIST.PAYOR_LAST_NM as PAYOR_LAST_NM,
SQ_ING_POL_LIST.PAYOR_SFX_NM as PAYOR_SFX_NM,
SQ_ING_POL_LIST.INSURED_ADDR_LN_1 as INSURED_ADDR_LN_1,
SQ_ING_POL_LIST.INSURED_ADDR_LN_2 as INSURED_ADDR_LN_2,
SQ_ING_POL_LIST.INSURED_CITY_NM as INSURED_CITY_NM,
SQ_ING_POL_LIST.INSURED_STATE_CD as INSURED_STATE_CD,
SQ_ING_POL_LIST.INSURED_ZIP_CD as INSURED_ZIP_CD,
SQ_ING_POL_LIST.INSURED_CLI_ID as INSURED_CLI_ID,
SQ_ING_POL_LIST.OWNER_CLI_ID as OWNER_CLI_ID,
SQ_ING_POL_LIST.PAYOR_CLI_ID as PAYOR_CLI_ID,
SQ_ING_POL_LIST.SEC_INSURED_CLI_ID as SEC_INSURED_CLI_ID,
SQ_ING_POL_LIST.INSURED_SSN as INSURED_SSN,
SQ_ING_POL_LIST.OWNER_SSN as OWNER_SSN,
SQ_ING_POL_LIST.PAYOR_SSN as PAYOR_SSN,
SQ_ING_POL_LIST.SEC_INSURED_SSN as SEC_INSURED_SSN,
SQ_ING_POL_LIST.AGT_ID as AGT_ID,
SQ_ING_POL_LIST.POL_ISS_DT as POL_ISS_DT,
SQ_ING_POL_LIST.SERV_CENTER_NUM as SERV_CENTER_NUM,
SQ_ING_POL_LIST.POLICY_TYPE as POLICY_TYPE,
SQ_ING_POL_LIST.POL_STATUS as POL_STATUS,
SQ_ING_POL_LIST.POL_CNFD_IND as POL_CNFD_IND,
SQ_ING_POL_LIST.BASE_PLAN_ID as BASE_PLAN_ID,
SQ_ING_POL_LIST.BASE_FACE_AMT as BASE_FACE_AMT,
SQ_ING_POL_LIST.BILL_MODE as BILL_MODE,
SQ_ING_POL_LIST.CURR_CASH_VALUE as CURR_CASH_VALUE,
SQ_ING_POL_LIST.OWNER_FIRST_NM as OWNER_FIRST_NM,
SQ_ING_POL_LIST.OWNER_MID_NM as OWNER_MID_NM,
SQ_ING_POL_LIST.OWNER_LAST_NM as OWNER_LAST_NM,
SQ_ING_POL_LIST.OWNER_SFX_NM as OWNER_SFX_NM,
SQ_ING_POL_LIST.LOAD_DT as LOAD_DT,
SQ_ING_POL_LIST.FEED_IND as FEED_IND,
SQ_ING_POL_LIST.source_record_id
FROM
SQ_ING_POL_LIST
);


-- Component STG_ING_POL_LIST_TPT, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.STG_ING_POL_LIST
(
CO_ID,
POL_ID,
INSURED_MEMBER_NUM,
PAYOR_MEMBER_NUM,
ALPHA_CODE_INSURED,
ALPHA_CODE_OWNER,
ALPHA_CODE_PAYOR,
ALPHA_CODE_JOINT,
INSURED_FIRST_NM,
INSURED_MID_NM,
INSURED_LAST_NM,
INSURED_SFX_NM,
PAYOR_FIRST_NM,
PAYOR_MID_NM,
PAYOR_LAST_NM,
PAYOR_SFX_NM,
INSURED_ADDR_LN_1,
INSURED_ADDR_LN_2,
INSURED_CITY_NM,
INSURED_STATE_CD,
INSURED_ZIP_CD,
INSURED_CLI_ID,
OWNER_CLI_ID,
PAYOR_CLI_ID,
SEC_INSURED_CLI_ID,
INSURED_SSN,
OWNER_SSN,
PAYOR_SSN,
SEC_INSURED_SSN,
AGT_ID,
POL_ISS_DT,
SERV_CENTER_NUM,
POLICY_TYPE,
POL_STATUS,
POL_CNFD_IND,
BASE_PLAN_ID,
BASE_FACE_AMT,
BILL_MODE,
CURR_CASH_VALUE,
OWNER_FIRST_NM,
OWNER_MID_NM,
OWNER_LAST_NM,
OWNER_SFX_NM,
LOAD_DT,
FEED_IND
)
SELECT
exp_Pass_Through.CO_ID as CO_ID,
exp_Pass_Through.POL_ID as POL_ID,
--left(exp_Pass_Through.INSURED_MEMBER_NUM ,8) as INSURED_MEMBER_NUM,
--left(exp_Pass_Through.PAYOR_MEMBER_NUM,8) as PAYOR_MEMBER_NUM,
left(exp_Pass_Through.ALPHA_CODE_INSURED,5) as ALPHA_CODE_INSURED,
left(exp_Pass_Through.ALPHA_CODE_OWNER,5) as ALPHA_CODE_OWNER,
left(exp_Pass_Through.ALPHA_CODE_PAYOR,5) as ALPHA_CODE_PAYOR,
left(exp_Pass_Through.ALPHA_CODE_JOINT,5) as ALPHA_CODE_JOINT,
exp_Pass_Through.INSURED_FIRST_NM as INSURED_FIRST_NM,
exp_Pass_Through.INSURED_MID_NM as INSURED_MID_NM,
exp_Pass_Through.INSURED_LAST_NM as INSURED_LAST_NM,
exp_Pass_Through.INSURED_SFX_NM as INSURED_SFX_NM,
exp_Pass_Through.PAYOR_FIRST_NM as PAYOR_FIRST_NM,
exp_Pass_Through.PAYOR_MID_NM as PAYOR_MID_NM,
exp_Pass_Through.PAYOR_LAST_NM as PAYOR_LAST_NM,
exp_Pass_Through.PAYOR_SFX_NM as PAYOR_SFX_NM,
exp_Pass_Through.INSURED_ADDR_LN_1 as INSURED_ADDR_LN_1,
exp_Pass_Through.INSURED_ADDR_LN_2 as INSURED_ADDR_LN_2,
exp_Pass_Through.INSURED_CITY_NM as INSURED_CITY_NM,
exp_Pass_Through.INSURED_STATE_CD as INSURED_STATE_CD,
exp_Pass_Through.INSURED_ZIP_CD as INSURED_ZIP_CD,
exp_Pass_Through.INSURED_CLI_ID as INSURED_CLI_ID,
exp_Pass_Through.OWNER_CLI_ID as OWNER_CLI_ID,
exp_Pass_Through.PAYOR_CLI_ID as PAYOR_CLI_ID,
exp_Pass_Through.SEC_INSURED_CLI_ID as SEC_INSURED_CLI_ID,
exp_Pass_Through.INSURED_SSN as INSURED_SSN,
exp_Pass_Through.OWNER_SSN as OWNER_SSN,
exp_Pass_Through.PAYOR_SSN as PAYOR_SSN,
exp_Pass_Through.SEC_INSURED_SSN as SEC_INSURED_SSN,
exp_Pass_Through.AGT_ID as AGT_ID,
exp_Pass_Through.POL_ISS_DT as POL_ISS_DT,
exp_Pass_Through.SERV_CENTER_NUM as SERV_CENTER_NUM,
exp_Pass_Through.POLICY_TYPE as POLICY_TYPE,
exp_Pass_Through.POL_STATUS as POL_STATUS,
exp_Pass_Through.POL_CNFD_IND as POL_CNFD_IND,
exp_Pass_Through.BASE_PLAN_ID as BASE_PLAN_ID,
exp_Pass_Through.BASE_FACE_AMT as BASE_FACE_AMT,
exp_Pass_Through.BILL_MODE as BILL_MODE,
exp_Pass_Through.CURR_CASH_VALUE as CURR_CASH_VALUE,
exp_Pass_Through.OWNER_FIRST_NM as OWNER_FIRST_NM,
exp_Pass_Through.OWNER_MID_NM as OWNER_MID_NM,
exp_Pass_Through.OWNER_LAST_NM as OWNER_LAST_NM,
exp_Pass_Through.OWNER_SFX_NM as OWNER_SFX_NM,
exp_Pass_Through.LOAD_DT as LOAD_DT,
exp_Pass_Through.FEED_IND as FEED_IND,
current_date,
null
FROM
exp_Pass_Through ;


-- PIPELINE END FOR 2

END; ';