-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_ECTL_BATCH_INFO_INS2025B("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE BATCH_ACTIVE_IND varchar;
PROJ_ID varchar;
BEGIN 

--EDW_DEV 
--DB_T_CTRL_PROD
--ECTL_BATCH_INFO

BATCH_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 

-- Component sq_DUMMY_SRC, Type TABLE_DDL Creating an empty table
CREATE OR REPLACE TEMPORARY TABLE sq_DUMMY
(
DUMMY varchar(19),
source_record_id number autoincrement start 1 increment 1
);


-- Component sq_DUMMY_SRC, Type IMPORT_DATA Importing Data
;


-- Component exp_PROJ_ID_BATCH, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_PROJ_ID_BATCH AS
(
SELECT
:BATCH_ACTIVE_IND as out_ECTL_BATCH_IND,
:PROJ_ID as out_ECTL_PROJ_ID,
CURRENT_TIMESTAMP as out_ECTL_BATCH_START_TS,
sq_DUMMY.source_record_id
FROM
sq_DUMMY
);


-- Component LKP_ECTL_BATCH_INFO, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_ECTL_BATCH_INFO AS
(
SELECT
LKP.ECTL_BATCH_ID,
exp_PROJ_ID_BATCH.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_PROJ_ID_BATCH.source_record_id ORDER BY LKP.ECTL_BATCH_ID asc) RNK
FROM
exp_PROJ_ID_BATCH
LEFT JOIN (
SELECT
ECTL_BATCH_ID,
ECTL_ACTIVE_IND,
ECTL_PROJ_ID
FROM DB_T_CTRL_PROD.ECTL_BATCH_INFO
) LKP ON LKP.ECTL_ACTIVE_IND = exp_PROJ_ID_BATCH.out_ECTL_BATCH_IND AND LKP.ECTL_PROJ_ID = exp_PROJ_ID_BATCH.out_ECTL_PROJ_ID
QUALIFY RNK = 1
);


-- Component exp_ABORT_BATCH, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ABORT_BATCH AS
(
SELECT
CASE WHEN LKP_ECTL_BATCH_INFO.ECTL_BATCH_ID IS NOT NULL THEN 
null --RAISE_ERROR(''Batch already exists'') 
ELSE null END as var_ABORT_WF,
exp_PROJ_ID_BATCH.out_ECTL_PROJ_ID as ECTL_PROJ_ID,
exp_PROJ_ID_BATCH.out_ECTL_BATCH_IND as ECTL_BATCH_IND,
exp_PROJ_ID_BATCH.out_ECTL_BATCH_START_TS as ECTL_BATCH_START_TS,
exp_PROJ_ID_BATCH.source_record_id
FROM
exp_PROJ_ID_BATCH
INNER JOIN LKP_ECTL_BATCH_INFO ON exp_PROJ_ID_BATCH.source_record_id = LKP_ECTL_BATCH_INFO.source_record_id
);


-- Component ECTL_BATCH_INFO_INS, Type TARGET 
INSERT INTO DB_T_CTRL_PROD.ECTL_BATCH_INFO
(
ECTL_PROJ_ID,
ECTL_BATCH_START_TS,
ECTL_ACTIVE_IND
)
SELECT
exp_ABORT_BATCH.ECTL_PROJ_ID as ECTL_PROJ_ID,
exp_ABORT_BATCH.ECTL_BATCH_START_TS as ECTL_BATCH_START_TS,
exp_ABORT_BATCH.ECTL_BATCH_IND as ECTL_ACTIVE_IND
FROM
exp_ABORT_BATCH;


END; ';