-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_TREXIS_POLICY_DATA("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
       run_id STRING;
       PRCS_ID STRING;
	v_start_time TIMESTAMP;
BEGIN
       run_id := (SELECT run_id FROM control_run_id WHERE worklet_name = :worklet_name ORDER BY insert_ts DESC LIMIT 1);
       PRCS_ID := (SELECT param_value FROM control_params WHERE run_id = :run_id AND param_name = ''PRCS_ID'' LIMIT 1);
	v_start_time := CURRENT_TIMESTAMP();

-- Component SQ_TREXIS_POLCY_DATA, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_TREXIS_POLCY_DATA AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as PLCY_NUM,
$2 as ORIGNL_EFF_DT,
$3 as TERM_EFF_DT,
$4 as EXPN_DT,
$5 as FRST_NAME,
$6 as LAST_NAME,
$7 as DOB,
$8 as ADDR_ONE,
$9 as CITY,
$10 as ST,
$11 as ZIP,
$12 as ZIP_EXTENTION,
$13 as MUN_TAX_CD,
$14 as ST_NUM,
$15 as SRVC_CTR,
$16 as AGNT_NUM,
$17 as AGNT_SUB,
$18 as AGNT_NAME,
$19 as AGNCY_NAME,
$20 as CLNT_ID,
$21 as ENCMCE_CD,
$22 as CO,
$23 as SOC_SCURTY_ONE,
$24 as SOC_SCURTY_TWO,
$25 as WRTN_PREM,
$26 as EARND_PREM,
$27 as INFORCE_PREM,
$28 as INFORCE_IND,
$29 as MTH_ID,
$30 as PLCY_STS,
$31 as MBRSHP_NUM,
$32 as AGNT_FRST_NAME,
$33 as AGNT_LAST_NAME,
$34 as AGT_IND,
$35 as NUM_UNITS,
$36 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
select PLCY_NUM    ,

ORIGNL_EFF_DT   ,

TERM_EFF_DT ,

EXPN_DT ,

FRST_NAME   ,

LAST_NAME   ,

DOB ,

ADDR_ONE    ,

CITY    ,

ST  ,

ZIP ,

ZIP_EXTENTION   ,

MUN_TAX_CD  ,

ST_NUM  ,

SRVC_CTR    ,

AGNT_NUM    ,

AGNT_SUB    ,

AGNT_NAME   ,

AGNCY_NAME  ,

CLNT_ID ,

ENCMCE_CD   ,

CO  ,

SOC_SCURTY_ONE  ,

SOC_SCURTY_TWO  ,

/* sum(WRTN_PREM)WRTN_PREM , */
/* sum(EARND_PREM)EARND_PREM   , */
/* sum(INFORCE_PREM)INFORCE_PREM   , */
WRTN_PREM,

EARND_PREM,

INFORCE_PREM,

INFORCE_IND ,

MTH_ID  ,

PLCY_STS    ,

MBRSHP_NUM  ,

AGNT_FRST_NAME  ,

AGNT_LAST_NAME ,

AGT_IND,

NUM_UNITS  from 

DB_T_PROD_STAG.stg_trexis_polcy_data



/*group by 

PLCY_NUM    ,

ORIGNL_EFF_DT   ,

TERM_EFF_DT ,

EXPN_DT ,

FRST_NAME   ,

LAST_NAME   ,

DOB ,

ADDR_ONE    ,

DB_T_PROD_CORE.CITY    ,

ST  ,

ZIP ,

ZIP_EXTENTION   ,

MUN_TAX_CD  ,

ST_NUM  ,

SRVC_CTR    ,

AGNT_NUM    ,

AGNT_SUB    ,

AGNT_NAME   ,

AGNCY_NAME  ,

CLNT_ID ,

ENCMCE_CD   ,

CO  ,

SOC_SCURTY_ONE  ,

SOC_SCURTY_TWO  ,

MTH_ID  ,

PLCY_STS    ,

MBRSHP_NUM  ,

AGNT_FRST_NAME  ,

AGNT_LAST_NAME,INFORCE_IND

*/
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_TREXIS_POLCY_DATA.PLCY_NUM as PLCY_NUM,
to_date ( substr ( SQ_TREXIS_POLCY_DATA.ORIGNL_EFF_DT , 1 , 10 ) || '' '' || substr ( SQ_TREXIS_POLCY_DATA.ORIGNL_EFF_DT , 12 , 8 ) , ''YYYY-MM-DD HH24:MI:SS'' ) as o_ORIGNL_EFF_DT,
to_date ( substr ( SQ_TREXIS_POLCY_DATA.TERM_EFF_DT , 1 , 10 ) || '' '' || substr ( SQ_TREXIS_POLCY_DATA.TERM_EFF_DT , 12 , 8 ) , ''YYYY-MM-DD HH24:MI:SS'' ) as o_TERM_EFF_DT,
to_date ( substr ( SQ_TREXIS_POLCY_DATA.EXPN_DT , 1 , 10 ) || '' '' || substr ( SQ_TREXIS_POLCY_DATA.EXPN_DT , 12 , 8 ) , ''YYYY-MM-DD HH24:MI:SS'' ) as o_EXPN_DT,
SQ_TREXIS_POLCY_DATA.FRST_NAME as FRST_NAME,
SQ_TREXIS_POLCY_DATA.LAST_NAME as LAST_NAME,
SQ_TREXIS_POLCY_DATA.DOB as DOB,
SQ_TREXIS_POLCY_DATA.ADDR_ONE as ADDR_ONE,
SQ_TREXIS_POLCY_DATA.CITY as CITY,
SQ_TREXIS_POLCY_DATA.ST as ST,
SQ_TREXIS_POLCY_DATA.ZIP as ZIP,
SQ_TREXIS_POLCY_DATA.ZIP_EXTENTION as ZIP_EXTENTION,
SQ_TREXIS_POLCY_DATA.MUN_TAX_CD as MUN_TAX_CD,
SQ_TREXIS_POLCY_DATA.ST_NUM as ST_NUM,
SQ_TREXIS_POLCY_DATA.SRVC_CTR as SRVC_CTR,
SQ_TREXIS_POLCY_DATA.AGNT_NUM as AGNT_NUM,
SQ_TREXIS_POLCY_DATA.AGNT_SUB as AGNT_SUB,
SQ_TREXIS_POLCY_DATA.AGNT_NAME as AGNT_NAME,
SQ_TREXIS_POLCY_DATA.AGNCY_NAME as AGNCY_NAME,
SQ_TREXIS_POLCY_DATA.CLNT_ID as CLNT_ID,
SQ_TREXIS_POLCY_DATA.ENCMCE_CD as ENCMCE_CD,
SQ_TREXIS_POLCY_DATA.CO as CO,
SQ_TREXIS_POLCY_DATA.SOC_SCURTY_ONE as SOC_SCURTY_ONE,
SQ_TREXIS_POLCY_DATA.SOC_SCURTY_TWO as SOC_SCURTY_TWO,
SQ_TREXIS_POLCY_DATA.WRTN_PREM as WRTN_PREM,
SQ_TREXIS_POLCY_DATA.EARND_PREM as EARND_PREM,
SQ_TREXIS_POLCY_DATA.INFORCE_PREM as INFORCE_PREM,
SQ_TREXIS_POLCY_DATA.INFORCE_IND as INFORCE_IND,
SQ_TREXIS_POLCY_DATA.MTH_ID as MTH_ID,
SQ_TREXIS_POLCY_DATA.PLCY_STS as PLCY_STS,
SQ_TREXIS_POLCY_DATA.MBRSHP_NUM as MBRSHP_NUM,
SQ_TREXIS_POLCY_DATA.AGNT_FRST_NAME as AGNT_FRST_NAME,
SQ_TREXIS_POLCY_DATA.AGNT_LAST_NAME as AGNT_LAST_NAME,
SQ_TREXIS_POLCY_DATA.AGT_IND as AGT_IND,
:PRCS_ID as PRCS_ID,
CURRENT_TIMESTAMP as EDW_STRT_DTTM,
TO_DATE ( ''12/31/9999 23:59:59.999999'' , ''MM/DD/YYYY HH24:MI:SS.FF6'' ) as EDW_END_DTTM,
SQ_TREXIS_POLCY_DATA.NUM_UNITS as NUM_UNITS,
SQ_TREXIS_POLCY_DATA.source_record_id
FROM
SQ_TREXIS_POLCY_DATA
);


-- Component TREXIS_POLCY_DATA, Type TARGET 
INSERT INTO DB_T_PROD_COMN.TREXIS_POLCY_DATA
(
PLCY_NUM,
ORIGNL_EFF_DT,
TERM_EFF_DT,
EXPN_DT,
FRST_NAME,
LAST_NAME,
DOB,
ADDR_ONE,
CITY,
ST,
ZIP,
ZIP_EXTENTION,
MUN_TAX_CD,
ST_NUM,
SRVC_CTR,
AGNT_NUM,
AGNT_SUB,
AGNT_NAME,
AGNCY_NAME,
CLNT_ID,
ENCMCE_CD,
CO,
SOC_SCURTY_ONE,
SOC_SCURTY_TWO,
WRTN_PREM,
EARND_PREM,
INFORCE_PREM,
INFORCE_IND,
MTH_ID,
PLCY_STS,
MBRSHP_NUM,
AGNT_FRST_NAME,
AGNT_LAST_NAME,
AGT_IND,
NUM_UNITS,
PRCS_ID,
EDW_STRT_DTTM,
EDW_END_DTTM
)
SELECT
EXPTRANS.PLCY_NUM as PLCY_NUM,
EXPTRANS.o_ORIGNL_EFF_DT as ORIGNL_EFF_DT,
EXPTRANS.o_TERM_EFF_DT as TERM_EFF_DT,
EXPTRANS.o_EXPN_DT as EXPN_DT,
EXPTRANS.FRST_NAME as FRST_NAME,
EXPTRANS.LAST_NAME as LAST_NAME,
EXPTRANS.DOB as DOB,
EXPTRANS.ADDR_ONE as ADDR_ONE,
EXPTRANS.CITY as CITY,
EXPTRANS.ST as ST,
EXPTRANS.ZIP as ZIP,
EXPTRANS.ZIP_EXTENTION as ZIP_EXTENTION,
EXPTRANS.MUN_TAX_CD as MUN_TAX_CD,
EXPTRANS.ST_NUM as ST_NUM,
EXPTRANS.SRVC_CTR as SRVC_CTR,
EXPTRANS.AGNT_NUM as AGNT_NUM,
EXPTRANS.AGNT_SUB as AGNT_SUB,
EXPTRANS.AGNT_NAME as AGNT_NAME,
EXPTRANS.AGNCY_NAME as AGNCY_NAME,
EXPTRANS.CLNT_ID as CLNT_ID,
EXPTRANS.ENCMCE_CD as ENCMCE_CD,
EXPTRANS.CO as CO,
EXPTRANS.SOC_SCURTY_ONE as SOC_SCURTY_ONE,
EXPTRANS.SOC_SCURTY_TWO as SOC_SCURTY_TWO,
EXPTRANS.WRTN_PREM as WRTN_PREM,
EXPTRANS.EARND_PREM as EARND_PREM,
EXPTRANS.INFORCE_PREM as INFORCE_PREM,
EXPTRANS.INFORCE_IND as INFORCE_IND,
EXPTRANS.MTH_ID as MTH_ID,
EXPTRANS.PLCY_STS as PLCY_STS,
EXPTRANS.MBRSHP_NUM as MBRSHP_NUM,
EXPTRANS.AGNT_FRST_NAME as AGNT_FRST_NAME,
EXPTRANS.AGNT_LAST_NAME as AGNT_LAST_NAME,
EXPTRANS.AGT_IND as AGT_IND,
EXPTRANS.NUM_UNITS as NUM_UNITS,
EXPTRANS.PRCS_ID as PRCS_ID,
EXPTRANS.EDW_STRT_DTTM as EDW_STRT_DTTM,
EXPTRANS.EDW_END_DTTM as EDW_END_DTTM
FROM
EXPTRANS;


END; ';