-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_AGENT_HIER_MUL_DIST_CHECK_SCRIPT("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- PIPELINE START FOR 1

-- Component SQ_AGENT_HIER, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGENT_HIER AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as AGNT_CLIENT_ID,
$2 as AGENCY_NBR,
$3 as SALES_ST_CD,
$4 as SALES_RGN_CD,
$5 as SALES_SVC_CD,
$6 as AGNT_EFF_DT,
$7 as AGNT_EXPIRY_DT,
$8 as AGNT_STATUS_CD,
$9 as ECTL_ORIG_INS_TS,
$10 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELect AGNT_CLIENT_ID,AGENCY_NBR,SALES_ST_CD,SALES_RGN_CD,SALES_SVC_CD,CAST(AGNT_EFF_DT AS DATE),CAST(AGNT_EXPIRY_DT AS DATE),AGNT_STATUS_CD,ECTL_ORIG_INS_TS  
FROM DB_T_CORE_PROD.AGENT_HIER WHERE (SELECT CAST(ECTL_PARAM_VALUE AS DATE)FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM 
WHERE ECTL_PRGM_ID = 0 AND ECTL_PARAM_ID = 14 )  BETWEEN AGNT_EFF_DT AND AGNT_EXPIRY_DT
QUALIFY COUNT(*) OVER(PARTITION BY AGNT_CLIENT_ID,SALES_SVC_CD)>1
) SRC
)
);


-- Component Exp_AGENT_HIER, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_AGENT_HIER AS
(
SELECT
LPAD ( SQ_AGENT_HIER.AGNT_CLIENT_ID , 20 , '' '' ) as o_AGNT_CLIENT_ID,
LPAD ( SQ_AGENT_HIER.AGENCY_NBR , 5 , '' '' ) as o_AGENCY_NBR,
LPAD ( SQ_AGENT_HIER.SALES_ST_CD , 7 , '' '' ) as o_SALES_ST_CD,
LPAD ( SQ_AGENT_HIER.SALES_RGN_CD , 7 , '' '' ) as o_SALES_RGN_CD,
LPAD ( SQ_AGENT_HIER.SALES_SVC_CD , 13 , '''' ) as o_SALES_SVC_CD,
LPAD ( TO_CHAR ( SQ_AGENT_HIER.AGNT_EFF_DT , ''YYYY-MM-DD'' ) , 17 , '''' ) as o_AGNT_EFF_DT,
LPAD ( TO_CHAR ( SQ_AGENT_HIER.AGNT_EXPIRY_DT , ''YYYY-MM-DD'' ) , 17 , '''' ) as o_AGNT_EXPIRY_DT,
LPAD ( SQ_AGENT_HIER.AGNT_STATUS_CD , 7 , '''' ) as o_AGNT_STATUS_CD,
SQ_AGENT_HIER.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
SQ_AGENT_HIER.source_record_id
FROM
SQ_AGENT_HIER
);


-- Component FF_AGENT_HIER, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE FF_AGENT_HIER AS
(
SELECT
Exp_AGENT_HIER.o_AGNT_CLIENT_ID as AGNT_CLIENT_ID,
Exp_AGENT_HIER.o_AGENCY_NBR as AGENCY_NBR,
Exp_AGENT_HIER.o_SALES_ST_CD as SALES_ST_CD,
Exp_AGENT_HIER.o_SALES_RGN_CD as SALES_RGN_CD,
Exp_AGENT_HIER.o_SALES_SVC_CD as SALES_SVC_CD,
Exp_AGENT_HIER.o_AGNT_EFF_DT as AGNT_EFF_DT,
Exp_AGENT_HIER.o_AGNT_EXPIRY_DT as AGNT_EXPIRY_DT,
Exp_AGENT_HIER.o_AGNT_STATUS_CD as AGNT_STATUS_CD,
Exp_AGENT_HIER.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS
FROM
Exp_AGENT_HIER
);


-- Component FF_AGENT_HIER, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2
-- Component SQ_AGENT_HIER_CNT, Type Pre SQL 
UPDATE DB_T_CORE_PROD.AGENT_HIER TGT 
FROM    (
SELECT a.* , coalesce(MAX(AGNT_EFF_DT) OVER(PARTITION BY AGNT_CLIENT_ID ORDER
 BY case when (AGNT_STATUS_CD in (''-'',''J'')) then ''1'' else ''2'' end,
AGNT_EFF_DT ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) -1,CAST(''9999-12-31''
AS DATE)) AGNT_EXPIRY_DT_new
FROM DB_T_CORE_PROD.AGENT_HIER a
WHERE (SELECT CAST(ECTL_PARAM_VALUE AS DATE)FROM DB_T_CTRL_PROD.ECTL_PRGM_PARAM 
WHERE ECTL_PRGM_ID = 0 AND ECTL_PARAM_ID = 14 )  BETWEEN AGNT_EFF_DT AND AGNT_EXPIRY_DT
QUALIFY COUNT(*) OVER(PARTITION BY AGNT_CLIENT_ID,SALES_SVC_CD)>1
) UPD_AGG 
SET AGNT_EXPIRY_DT = AGNT_EXPIRY_DT_new
WHERE    
TGT.AGNT_CLIENT_ID = UPD_AGG.AGNT_CLIENT_ID 
AND TGT.SALES_SVC_CD = UPD_AGG.SALES_SVC_CD 
AND TGT.AGENCY_NBR = UPD_AGG.AGENCY_NBR 
AND TGT.AGNT_EFF_DT=UPD_AGG.AGNT_EFF_DT
AND TGT.ECTL_ORIG_INS_TS=UPD_AGG.ECTL_ORIG_INS_TS
AND TGT.AGNT_STATUS_CD IN (''-'',''J'');


-- Component SQ_AGENT_HIER_CNT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGENT_HIER_CNT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CNT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELect SUM(A_CNT) AS CNT FROM (
SELECT COUNT(*) AS A_CNT FROM(
SELECT AGNT_CLIENT_ID,AGENCY_NBR,SALES_ST_CD,SALES_RGN_CD,SALES_SVC_CD,AGNT_EFF_DT,AGNT_EXPIRY_DT,AGNT_STATUS_CD,ECTL_ORIG_INS_TS  
FROM DB_T_CORE_PROD.AGENT_HIER WHERE (SELECT CAST(ECTL_PARAM_VALUE AS DATE)FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM 
WHERE ECTL_PRGM_ID = 0 AND ECTL_PARAM_ID = 14 )  BETWEEN AGNT_EFF_DT AND AGNT_EXPIRY_DT
QUALIFY COUNT(*) OVER(PARTITION BY AGNT_CLIENT_ID,SALES_SVC_CD,AGNT_STATUS_CD)>1
)A

UNION 

SELECT COUNT(*) AS B_CNT FROM (
SELECT AGNT_CLIENT_ID,AGENCY_NBR,SALES_ST_CD,SALES_RGN_CD,SALES_SVC_CD,AGNT_EFF_DT,AGNT_EXPIRY_DT,AGNT_STATUS_CD,ECTL_ORIG_INS_TS  
FROM DB_T_CORE_PROD.AGENT_HIER WHERE (SELECT CAST(ECTL_PARAM_VALUE AS DATE)FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM 
WHERE ECTL_PRGM_ID = 0 AND ECTL_PARAM_ID = 14 )  BETWEEN AGNT_EFF_DT AND AGNT_EXPIRY_DT
QUALIFY COUNT(*) OVER(PARTITION BY AGENCY_NBR)>1
)B

UNION

SELECT COUNT(*) AS C_CNT FROM (
SELECT * FROM (SELECT DISTINCT SALES_ST_CD,SALES_RGN_CD, SALES_DST_CD,  SALES_SVC_CD 
FROM   DB_T_CORE_PROD.AGENT_HIER AGNT11
WHERE AGNT11.AGNT_EFF_DT <= (SELECT CAST(ECTL_PARAM_VALUE AS DATE)FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM 
WHERE ECTL_PRGM_ID = 0 AND ECTL_PARAM_ID = 14 )
QUALIFY RANK() OVER( PARTITION BY  SALES_ST_CD,SALES_SVC_CD ORDER BY AGNT_TERMINATION_DT DESC, AGNT_EFF_DT DESC) = 1
) AGNT QUALIFY COUNT(*) OVER( PARTITION BY SALES_SVC_CD) > 1
)C
)D
) SRC
)
);


-- Component Exp_Count, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_Count AS
(
SELECT
CASE WHEN SQ_AGENT_HIER_CNT.CNT <> 0 THEN 
--RAISE_ERROR(''Multiple active rows for an AGENCY_NBR/AGNT_CLIENT_ID,SALES_SVC_CD for the current month or Multiple state/region/district for a service center'') 
null ELSE ''SUCCESS:-There are no Multiple active rows for an AGENCY_NBR/AGNT_CLIENT_ID,SALES_SVC_CD for the current month or Multiple state/region/district for a service center'' END as Abort,
SQ_AGENT_HIER_CNT.source_record_id
FROM
SQ_AGENT_HIER_CNT
);


-- Component FF_AGENT_HIER_MSG, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE FF_AGENT_HIER_MSG AS
(
SELECT
Exp_Count.Abort as ParameterLine
FROM
Exp_Count
);


-- Component FF_AGENT_HIER_MSG, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 2

-- PIPELINE START FOR 3
-- Component SQ_AGENT_EFF_DT, Type Pre SQL 
UPDATE DB_T_CORE_PROD.AGENT_HIER TGT 
FROM  
( SELECT  
CAST(EPP.ECTL_PARAM_VALUE AS DATE) - EXTRACT( DAY FROM  CAST(EPP.ECTL_PARAM_VALUE AS DATE))+1 AGNT_EFF_DT_NEW,
A.AGENCY_NBR,
A.AGNT_CLIENT_ID,
A.ECTL_ORIG_INS_TS 
FROM DB_T_CORE_PROD.AGENT_HIER A 
,DB_T_Ctrl_PROD.ECTL_PRGM_PARAM EPP
WHERE EPP.ECTL_PRGM_ID = 0 
AND EPP.ECTL_PARAM_ID = 14
AND CAST(A.AGENCY_NBR AS VARCHAR(25))=CAST(A.AGNT_CLIENT_ID AS VARCHAR(25))
AND A.ECTL_TX_CD = ''NEW''
AND CAST(A.AGENCY_NBR AS VARCHAR(25)) NOT IN (''AL99999'',''GA99999'',''MS99999'')
AND AGNT_EFF_DT >AGNT_EFF_DT_NEW ) SRC 
SET 
AGNT_EFF_DT = SRC.AGNT_EFF_DT_NEW
WHERE 
TGT.AGENCY_NBR = SRC.AGENCY_NBR AND
TGT.AGNT_CLIENT_ID = SRC.AGNT_CLIENT_ID AND
TGT.ECTL_ORIG_INS_TS = SRC.ECTL_ORIG_INS_TS;


-- Component SQ_AGENT_EFF_DT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGENT_EFF_DT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CNT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELect COUNT(*) FROM (
SELECT * FROM ( SELECT  DISTINCT AGENCY_NBR, AGNT_CLIENT_ID FROM DB_T_CORE_PROD.AGENT_HIER
QUALIFY RANK() OVER(PARTITION BY AGENCY_NBR ORDER BY AGNT_EFF_DT) = 1) A 
QUALIFY COUNT(*) OVER(PARTITION BY AGENCY_NBR) >1
)B
) SRC
)
);


-- Component Exp_AGNT_EFF_DT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_AGNT_EFF_DT AS
(
SELECT
CASE WHEN SQ_AGENT_EFF_DT.CNT <> 0 THEN 
--RAISE_ERROR(''Multiple records available for Agents with the same maximum AGNT_EFF_DT. This leads to failure in Financial Profitability aggregate load'') 
null ELSE ''SUCCESS:-There are no Multiple records available for Agents with the same maximum AGNT_EFF_DT'' END as Abort,
SQ_AGENT_EFF_DT.source_record_id
FROM
SQ_AGENT_EFF_DT
);


-- Component FF_AGNT_EFF_DT_MSG, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE FF_AGNT_EFF_DT_MSG AS
(
SELECT
Exp_AGNT_EFF_DT.Abort as ParameterLine
FROM
Exp_AGNT_EFF_DT
);


-- Component FF_AGNT_EFF_DT_MSG, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 3

END; ';