-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_AUDIT_STG_SERVICE_CENTER_NAME("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE STG_NM varchar;
TGT_NM varchar;
ECTL_ACTIVE_IND varchar;
ACT_PROJ_ID varchar;
BEGIN 

STG_NM:=''DB_T_STAG_MEMBXREF_PROD.FGMPOLS''; 
TGT_NM:=''DB_T_core_MEMBXREF_PROD.FGMPOLS_DLY''; 
ECTL_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
ACT_PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 

-- PIPELINE START FOR 1

-- Component sq_TRG_FILE_SRC, Type TABLE_DDL Creating an empty table
CREATE OR REPLACE TEMPORARY TABLE sq_TRG_FILE
(
IND varchar(1),
RECORD_CNT varchar(2),
source_record_id number autoincrement start 1 increment 1
);


-- Component sq_TRG_FILE_SRC, Type IMPORT_DATA Importing Data
;


-- PIPELINE START FOR 1

-- Component sq_STG_TABLE, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_TABLE AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_BATCH_ID,
$2 as ECTL_PRGM_ID,
$3 as ECTL_TABLE_ID,
$4 as TGT_CNT,
$5 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 
 E.ECTL_BATCH_ID
,F.ECTL_PRGM_ID
,D.ECTL_TABLE_ID
,a.SRC_CNT
 
FROM
(SELECT COUNT(*) SRC_CNT FROM table(:STG_NM) ) A

JOIN
(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_TABLE_XREF WHERE ECTL_TABLE_NM  = :STG_NM) D
ON 1=1
JOIN
(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = :ACT_PROJ_ID AND ECTL_ACTIVE_IND = ''Y'') E
ON 1=1
JOIN
(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_INFO WHERE ECTL_PRGM_NM  =''$PRGM_NM'') F
ON 1=1
) SRC
)
);


-- Component exp_DUMMY_PORT_TRG, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_DUMMY_PORT_TRG AS
(
SELECT
decode ( TO_NUMBER(sq_TRG_FILE.RECORD_CNT) , 0 , 0 ) as out_RECORD_CNT,
1 as DUMMY,
sq_TRG_FILE.source_record_id
FROM
sq_TRG_FILE
);


-- Component exp_DUMMY_PORT_TGT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_DUMMY_PORT_TGT AS
(
SELECT
sq_STG_TABLE.TGT_CNT as TGT_CNT,
1 as DUMMY,
sq_STG_TABLE.ECTL_BATCH_ID as ECTL_BATCH_ID,
sq_STG_TABLE.ECTL_PRGM_ID as ECTL_PRGM_ID,
sq_STG_TABLE.ECTL_TABLE_ID as ECTL_TABLE_ID,
sq_STG_TABLE.source_record_id
FROM
sq_STG_TABLE
);


-- Component jnr_TRG_TGT, Type JOINER 
CREATE OR REPLACE TEMPORARY TABLE jnr_TRG_TGT AS
(
SELECT
exp_DUMMY_PORT_TRG.out_RECORD_CNT as RECORD_CNT,
exp_DUMMY_PORT_TRG.DUMMY as DUMMY,
exp_DUMMY_PORT_TGT.TGT_CNT as TGT_CNT,
exp_DUMMY_PORT_TGT.DUMMY as DUMMY1,
exp_DUMMY_PORT_TGT.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_DUMMY_PORT_TGT.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_DUMMY_PORT_TGT.ECTL_TABLE_ID as ECTL_TABLE_ID,
row_number() over (order by 1) AS source_record_id
FROM
exp_DUMMY_PORT_TRG
INNER JOIN exp_DUMMY_PORT_TGT ON exp_DUMMY_PORT_TGT.DUMMY = exp_DUMMY_PORT_TRG.DUMMY
);


-- Component exp_RJCT_CNT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_RJCT_CNT AS
(
SELECT
jnr_TRG_TGT.TGT_CNT as TGT_CNT,
jnr_TRG_TGT.RECORD_CNT as SRC_CNT,
jnr_TRG_TGT.RECORD_CNT - jnr_TRG_TGT.TGT_CNT as out_ECTL_RJCT_CNT,
0 as out_ECTL_DEL_CNT,
0 as out_ECTL_UPD_CNT,
CURRENT_TIMESTAMP as out_ECTL_INS_TS,
CASE WHEN ( jnr_TRG_TGT.RECORD_CNT - jnr_TRG_TGT.TGT_CNT ) <> 0 THEN :STG_NM || '' - AUDIT FAILED'' ELSE :STG_NM || '' - AUDIT PASSED'' END as out_ECTL_MSG_TEXT,
jnr_TRG_TGT.ECTL_BATCH_ID as ECTL_BATCH_ID,
jnr_TRG_TGT.ECTL_PRGM_ID as ECTL_PRGM_ID,
jnr_TRG_TGT.ECTL_TABLE_ID as ECTL_TABLE_ID,
jnr_TRG_TGT.source_record_id
FROM
jnr_TRG_TGT
);


-- Component ECTL_AUDIT_LOG_INS_STG, Type TARGET 
INSERT INTO DB_T_CTRL_FIN_PROD.ECTL_AUDIT_LOG
(
ECTL_BATCH_ID,
ECTL_PRGM_ID,
ECTL_TABLE_ID,
ECTL_SRC_ROW_CNT,
ECTL_TRGT_INS_CNT,
ECTL_TRGT_UPD_CNT,
ECTL_TRGT_DEL_CNT,
ECTL_TRGT_REJ_CNT,
ECTL_MESSAGE_TXT,
ECTL_ORIG_INS_TS
)
SELECT
exp_RJCT_CNT.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_RJCT_CNT.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_RJCT_CNT.ECTL_TABLE_ID as ECTL_TABLE_ID,
exp_RJCT_CNT.SRC_CNT as ECTL_SRC_ROW_CNT,
exp_RJCT_CNT.TGT_CNT as ECTL_TRGT_INS_CNT,
exp_RJCT_CNT.out_ECTL_UPD_CNT as ECTL_TRGT_UPD_CNT,
exp_RJCT_CNT.out_ECTL_DEL_CNT as ECTL_TRGT_DEL_CNT,
exp_RJCT_CNT.out_ECTL_RJCT_CNT as ECTL_TRGT_REJ_CNT,
exp_RJCT_CNT.out_ECTL_MSG_TEXT as ECTL_MESSAGE_TXT,
exp_RJCT_CNT.out_ECTL_INS_TS as ECTL_ORIG_INS_TS
FROM
exp_RJCT_CNT;


-- PIPELINE START FOR 2

-- Component sq_TGT_TABLE, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_TGT_TABLE AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_BATCH_ID,
$2 as ECTL_PRGM_ID,
$3 as ECTL_TABLE_ID,
$4 as SRC_CNT,
$5 as INS_CNT,
$6 as UPD_CNT,
$7 as DEL_CNT,
$8 as REJ_CNT,
$9 as MSG_TXT,
$10 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 
E.ECTL_BATCH_ID
,F.ECTL_PRGM_ID
,D.ECTL_TABLE_ID
,A.SRC_CNT
,B.INS_CNT
,0 UPD_CNT
,0 DEL_CNT
,0 REJ_CNT
,D.ECTL_TABLE_NM || '' - '' ||  ''AUDIT PASSED''  MSG_TXT FROM
(SELECT COUNT(*) SRC_CNT FROM table(:STG_NM) ) A
cross join
(SELECT COUNT(*) INS_CNT FROM table(:TGT_NM)
WHERE ECTL_BATCH_ID = (SELECT ECTL_BATCH_ID FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = :ACT_PROJ_ID AND ECTL_ACTIVE_IND = :ECTL_ACTIVE_IND) ) B
cross join
(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_TABLE_XREF WHERE ECTL_TABLE_NM  = :TGT_NM) D
cross join
(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = :ACT_PROJ_ID AND ECTL_ACTIVE_IND = :ECTL_ACTIVE_IND) E
cross join
(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_INFO WHERE ECTL_PRGM_NM  = ''$PRGM_NM_tgt'') F

) SRC
)
);


-- Component exp_Hold_data, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Hold_data AS
(
SELECT
sq_TGT_TABLE.ECTL_BATCH_ID as ECTL_BATCH_ID,
sq_TGT_TABLE.ECTL_PRGM_ID as ECTL_PRGM_ID,
sq_TGT_TABLE.ECTL_TABLE_ID as ECTL_TABLE_ID,
sq_TGT_TABLE.SRC_CNT as SRC_CNT,
sq_TGT_TABLE.INS_CNT as INS_CNT,
sq_TGT_TABLE.UPD_CNT as UPD_CNT,
sq_TGT_TABLE.DEL_CNT as DEL_CNT,
sq_TGT_TABLE.REJ_CNT as REJ_CNT,
sq_TGT_TABLE.MSG_TXT as MSG_TXT,
CURRENT_TIMESTAMP as ECTL_TIMESTAMP,
sq_TGT_TABLE.source_record_id
FROM
sq_TGT_TABLE
);


-- Component exp_hold_data2, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_hold_data2 AS
(
SELECT
exp_Hold_data.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_Hold_data.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_Hold_data.ECTL_TABLE_ID as ECTL_TABLE_ID,
exp_Hold_data.SRC_CNT as SRC_CNT,
exp_Hold_data.INS_CNT as INS_CNT,
exp_Hold_data.UPD_CNT as UPD_CNT,
exp_Hold_data.DEL_CNT as DEL_CNT,
exp_Hold_data.REJ_CNT as REJ_CNT,
exp_Hold_data.MSG_TXT as MSG_TXT,
exp_Hold_data.ECTL_TIMESTAMP as ECTL_TIMESTAMP,
exp_Hold_data.source_record_id
FROM
exp_Hold_data
);


-- Component ECTL_AUDIT_LOG_INS_TGT, Type TARGET 
INSERT INTO DB_T_CTRL_FIN_PROD.ECTL_AUDIT_LOG
(
ECTL_BATCH_ID,
ECTL_PRGM_ID,
ECTL_TABLE_ID,
ECTL_SRC_ROW_CNT,
ECTL_TRGT_INS_CNT,
ECTL_TRGT_UPD_CNT,
ECTL_TRGT_DEL_CNT,
ECTL_TRGT_REJ_CNT,
ECTL_MESSAGE_TXT,
ECTL_ORIG_INS_TS
)
SELECT
exp_hold_data2.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_hold_data2.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_hold_data2.ECTL_TABLE_ID as ECTL_TABLE_ID,
exp_hold_data2.SRC_CNT as ECTL_SRC_ROW_CNT,
exp_hold_data2.INS_CNT as ECTL_TRGT_INS_CNT,
exp_hold_data2.UPD_CNT as ECTL_TRGT_UPD_CNT,
exp_hold_data2.DEL_CNT as ECTL_TRGT_DEL_CNT,
exp_hold_data2.REJ_CNT as ECTL_TRGT_REJ_CNT,
exp_hold_data2.MSG_TXT as ECTL_MESSAGE_TXT,
exp_hold_data2.ECTL_TIMESTAMP as ECTL_ORIG_INS_TS
FROM
exp_hold_data2;


-- PIPELINE END FOR 2

END; ';