-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_ECTL_PRGM_PARAM_AGENT_HIER_TO_DATE("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE AGENT_HIER_TODATE date;
BEGIN 

AGENT_HIER_TODATE:=''1900-01-01''; 

-- Component SQ_Shortcut_to_STG_AGENT_NAME, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_STG_AGENT_NAME AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as HIER_DT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
select TO_CHAR(Last_day(add_months(:AGENT_HIER_TODATE, -1)),''yyyy-mm-dd'') As HIER_DT
) SRC
)
);


-- Component EXP_HIER_DT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXP_HIER_DT AS
(
SELECT
SQ_Shortcut_to_STG_AGENT_NAME.HIER_DT as HIER_DT,
0 as ECTL_PRGM_ID,
14 as ECTL_PARAM_ID,
SQ_Shortcut_to_STG_AGENT_NAME.source_record_id
FROM
SQ_Shortcut_to_STG_AGENT_NAME
);


-- Component UPD_AGNT_HIER_DT, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE UPD_AGNT_HIER_DT AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
EXP_HIER_DT.HIER_DT as HIER_DT,
EXP_HIER_DT.ECTL_PRGM_ID as ECTL_PRGM_ID,
EXP_HIER_DT.ECTL_PARAM_ID as ECTL_PARAM_ID,
1 as UPDATE_STRATEGY_ACTION
FROM
EXP_HIER_DT
);


-- Component ECTL_PRGM_PARAM, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM
USING UPD_AGNT_HIER_DT ON (UPDATE_STRATEGY_ACTION = 1 AND ECTL_PRGM_PARAM.ECTL_PRGM_ID = UPD_AGNT_HIER_DT.ECTL_PRGM_ID AND ECTL_PRGM_PARAM.ECTL_PARAM_ID = UPD_AGNT_HIER_DT.ECTL_PARAM_ID)
WHEN MATCHED THEN UPDATE
SET
ECTL_PARAM_VALUE = UPD_AGNT_HIER_DT.HIER_DT
;


END; ';