-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_RUN_ECTL_JOB_LOAD_STATUS_LOG("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
 FEED_DATE date;
BEGIN 

FEED_IND:='' ''; 
FEED_DATE:=''1900-01-01''; 

-- Component SQ_ECTL_JOB_LOAD_STATUS_LOG, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ECTL_JOB_LOAD_STATUS_LOG AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_BATCH_ID,
$2 as DATABASE_NM,
$3 as ECTL_PROJ_ID,
$4 as DAILY_FEED_IND,
$5 as DT_ID,
$6 as MO_ID,
$7 as BI_FOLDER_NM,
$8 as JOB_NM,
$9 as TASK_NM,
$10 as TASK_TYPE,
$11 as WF_START_TS,
$12 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT B.ECTL_BATCH_ID,CAST(''$EVIEWDB_LGCY'' AS VARCHAR(20)) AS DATABASE_NM,B.ECTL_PROJ_ID,CAST(TRIM(:FEED_IND) AS VARCHAR(1)) AS DAILY_FEED_IND,
CAST(EXTRACT(YEAR FROM (CAST(TRIM(:FEED_DATE) AS DATE)))*10000+EXTRACT(MONTH FROM (CAST(TRIM(:FEED_DATE) AS DATE)))*100+ 
EXTRACT(DAY FROM (CAST(TRIM(:FEED_DATE) AS DATE))) AS INTEGER) AS DT_ID, 
CAST(EXTRACT(YEAR FROM (CAST(TRIM(:FEED_DATE) AS DATE)))*100+EXTRACT(MONTH FROM (CAST(TRIM(:FEED_DATE) AS DATE))) AS INTEGER) AS MO_ID, 
CAST(TRIM(''$foldernm'') AS VARCHAR(50)) AS BI_FOLDER_NM, 
CAST(TRIM(''$WF_NM'') AS VARCHAR(50)) AS WF_NM, 
CAST(''ALL'' AS VARCHAR(50)) AS  TASK_NM, 
CAST(''WORKFLOW'' AS VARCHAR(50)) AS TASK_TYPE, 
CAST((TRIM(''$wf_START_TIME'')) AS TIMESTAMP(6) ) AS WF_ST_TS
FROM   DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B WHERE ECTL_PROJ_ID = CAST(TRIM(''$ACT_PROJ_ID'') AS INTEGER) AND ECTL_ACTIVE_IND = ''Y'' and 1=2
) SRC
)
);


-- Component exp_Pass_Through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Pass_Through AS
(
SELECT
SQ_ECTL_JOB_LOAD_STATUS_LOG.ECTL_BATCH_ID as ECTL_BATCH_ID,
SQ_ECTL_JOB_LOAD_STATUS_LOG.DATABASE_NM as DATABASE_NM,
SQ_ECTL_JOB_LOAD_STATUS_LOG.ECTL_PROJ_ID as ECTL_PROJ_ID,
SQ_ECTL_JOB_LOAD_STATUS_LOG.DAILY_FEED_IND as DAILY_FEED_IND,
SQ_ECTL_JOB_LOAD_STATUS_LOG.DT_ID as DT_ID,
SQ_ECTL_JOB_LOAD_STATUS_LOG.MO_ID as MO_ID,
SQ_ECTL_JOB_LOAD_STATUS_LOG.BI_FOLDER_NM as BI_FOLDER_NM,
SQ_ECTL_JOB_LOAD_STATUS_LOG.JOB_NM as JOB_NM,
SQ_ECTL_JOB_LOAD_STATUS_LOG.TASK_NM as TASK_NM,
SQ_ECTL_JOB_LOAD_STATUS_LOG.TASK_TYPE as TASK_TYPE,
SQ_ECTL_JOB_LOAD_STATUS_LOG.WF_START_TS as WF_START_TS,
SQ_ECTL_JOB_LOAD_STATUS_LOG.source_record_id
FROM
SQ_ECTL_JOB_LOAD_STATUS_LOG
);


-- Component ECTL_JOB_LOAD_STATUS_LOG1, Type TARGET 
INSERT INTO DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG
(
ECTL_BATCH_ID,
DATABASE_NM,
ECTL_PROJ_ID,
DAILY_FEED_IND,
DT_ID,
MO_ID,
BI_FOLDER_NM,
JOB_NM,
TASK_NM,
TASK_TYPE,
WF_START_TS
)
SELECT
exp_Pass_Through.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_Pass_Through.DATABASE_NM as DATABASE_NM,
exp_Pass_Through.ECTL_PROJ_ID as ECTL_PROJ_ID,
exp_Pass_Through.DAILY_FEED_IND as DAILY_FEED_IND,
exp_Pass_Through.DT_ID as DT_ID,
exp_Pass_Through.MO_ID as MO_ID,
exp_Pass_Through.BI_FOLDER_NM as BI_FOLDER_NM,
exp_Pass_Through.JOB_NM as JOB_NM,
exp_Pass_Through.TASK_NM as TASK_NM,
exp_Pass_Through.TASK_TYPE as TASK_TYPE,
exp_Pass_Through.WF_START_TS as WF_START_TS
FROM
exp_Pass_Through;


-- Component ECTL_JOB_LOAD_STATUS_LOG1, Type Post SQL 
UPDATE DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG TGT
FROM  
(
SELECT B.ECTL_BATCH_ID,CAST(''$EVIEWDB_LGCY'' AS VARCHAR(20)) AS DATABASE_NM,B.ECTL_PROJ_ID,CAST(TRIM(:FEED_IND) AS VARCHAR(1)) AS DAILY_FEED_IND,
CAST(EXTRACT(YEAR FROM (CAST(TRIM(:FEED_DATE) AS DATE)))*10000+EXTRACT(MONTH FROM (CAST(TRIM(:FEED_DATE) AS DATE)))*100+ 
EXTRACT(DAY FROM (CAST(TRIM(:FEED_DATE) AS DATE))) AS INTEGER) AS DT_ID, 
CAST(EXTRACT(YEAR FROM (CAST(TRIM(:FEED_DATE) AS DATE)))*100+EXTRACT(MONTH FROM (CAST(TRIM(:FEED_DATE) AS DATE))) AS INTEGER) AS MO_ID, 
CAST(TRIM(''$foldernm'') AS VARCHAR(50)) AS BI_FOLDER_NM, 
CAST(TRIM(''$WF_NM'') AS VARCHAR(50)) AS JOB_NM, 
CAST(''ALL'' AS VARCHAR(50)) AS  TASK_NM, 
CAST(''WORKFLOW'' AS VARCHAR(50)) AS TASK_TYPE, 
CAST((TRIM(''$wf_START_TIME'')) AS TIMESTAMP(6) ) AS WF_END_TS,''SUCCESS'' AS STATUS_MSG 
FROM   DB_T_CTRL_PROD.ECTL_BATCH_INFO B WHERE ECTL_PROJ_ID = CAST(TRIM(''$ACT_PROJ_ID'') AS INTEGER) AND ECTL_ACTIVE_IND = ''Y''
) SRC 
SET STATUS_MSG = SRC.STATUS_MSG,
WF_END_TS = SRC.WF_END_TS
WHERE 
TGT.ECTL_BATCH_ID = SRC.ECTL_BATCH_ID AND
TGT.ECTL_PROJ_ID = SRC.ECTL_PROJ_ID AND
TGT.DAILY_FEED_IND = SRC.DAILY_FEED_IND AND
TGT.DT_ID = SRC.DT_ID AND 
TGT.MO_ID = SRC.MO_ID AND 
TGT.JOB_NM = SRC.JOB_NM AND 
TGT.TASK_NM = SRC.TASK_NM AND 
TGT.TASK_TYPE = SRC.TASK_TYPE AND 
TGT.BI_FOLDER_NM = SRC.BI_FOLDER_NM AND 
TGT.STATUS_MSG IS null;


END; ';