-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_SHRD_ECTL_JOB_LOAD_STATUS_LOG_UPD("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE FEED_IND varchar;
FEED_DATE date;
BEGIN 

FEED_IND:='' ''; 
FEED_DATE:=''1900-01-01''; 

-- Component SQ_Shortcut_to_ECTL_BATCH_INFO_UPD, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_ECTL_BATCH_INFO_UPD AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_BATCH_ID,
$2 as DATABASE_NM,
$3 as ECTL_PROJ_ID,
$4 as DAILY_FEED_IND,
$5 as DT_ID,
$6 as MO_ID,
$7 as BI_FOLDER_NM,
$8 as JOB_NM,
$9 as TASK_NM,
$10 as TASK_TYPE,
$11 as WF_START_TS,
$12 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELect B.ECTL_BATCH_ID,''$EVIEWDB_LGCY'',B.ECTL_PROJ_ID,TRIM(:FEED_IND) DAILY_FEED_IND,
EXTRACT(YEAR FROM (CAST(TRIM(:FEED_DATE) AS DATE)))*10000+EXTRACT(MONTH FROM (CAST(TRIM(:FEED_DATE) AS DATE)))*100+ 
EXTRACT(DAY FROM (CAST(TRIM(:FEED_DATE) AS DATE)))AS DT_ID, 
EXTRACT(YEAR FROM (CAST(TRIM(:FEED_DATE) AS DATE)))*100+EXTRACT(MONTH FROM (CAST(TRIM(:FEED_DATE) AS DATE))) AS MO_ID, 
TRIM(''$foldernm'') AS BI_FOLDER_NM, 
TRIM(''$WF_NM'') AS WF_NM, 
''ALL'' AS  TASK_NM, 
''WORKFLOW'' AS TASK_TYPE, 
CAST((TRIM(''$wf_START_TIME'')) AS TIMESTAMP(6) ) AS WF_ST_TS  FROM 
DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B WHERE ECTL_PROJ_ID = CAST(TRIM(''$ACT_PROJ_ID'') AS INTEGER) AND ECTL_ACTIVE_IND = ''Y'' and 1=2
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD.ECTL_BATCH_ID as ECTL_BATCH_ID,
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD.DATABASE_NM as DATABASE_NM,
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD.ECTL_PROJ_ID as ECTL_PROJ_ID,
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD.DAILY_FEED_IND as DAILY_FEED_IND,
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD.DT_ID as DT_ID,
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD.MO_ID as MO_ID,
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD.BI_FOLDER_NM as BI_FOLDER_NM,
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD.JOB_NM as JOB_NM,
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD.TASK_NM as TASK_NM,
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD.TASK_TYPE as TASK_TYPE,
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD.WF_START_TS as WF_START_TS,
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD.source_record_id
FROM
SQ_Shortcut_to_ECTL_BATCH_INFO_UPD
);


-- Component ECTL_JOB_LOAD_STATUS_LOG_UPD, Type TARGET 
INSERT INTO DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG
(
ECTL_BATCH_ID,
DATABASE_NM,
ECTL_PROJ_ID,
DAILY_FEED_IND,
DT_ID,
MO_ID,
BI_FOLDER_NM,
JOB_NM,
TASK_NM,
TASK_TYPE,
WF_START_TS
)
SELECT
exp_pass_through.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_pass_through.DATABASE_NM as DATABASE_NM,
exp_pass_through.ECTL_PROJ_ID as ECTL_PROJ_ID,
exp_pass_through.DAILY_FEED_IND as DAILY_FEED_IND,
exp_pass_through.DT_ID as DT_ID,
exp_pass_through.MO_ID as MO_ID,
exp_pass_through.BI_FOLDER_NM as BI_FOLDER_NM,
exp_pass_through.JOB_NM as JOB_NM,
exp_pass_through.TASK_NM as TASK_NM,
exp_pass_through.TASK_TYPE as TASK_TYPE,
exp_pass_through.WF_START_TS as WF_START_TS
FROM
exp_pass_through;


-- Component ECTL_JOB_LOAD_STATUS_LOG_UPD, Type Post SQL 
UPDATE DB_T_CTRL_PROD.ECTL_JOB_LOAD_STATUS_LOG TGT
FROM 
(
SELECT B.ECTL_BATCH_ID ECTL_BATCH_ID,''$EVIEWDB_LGCY'' DATABASE_NM,B.ECTL_PROJ_ID ECTL_PROJ_ID, TRIM(:FEED_IND) DAILY_FEED_IND,
EXTRACT(YEAR FROM (CAST(TRIM(:FEED_DATE) AS DATE)))*10000+EXTRACT(MONTH FROM (CAST(TRIM(:FEED_DATE) AS DATE)))*100+ 
EXTRACT(DAY FROM (CAST(TRIM(:FEED_DATE) AS DATE)))AS DT_ID, 
EXTRACT(YEAR FROM (CAST(TRIM(:FEED_DATE) AS DATE)))*100+EXTRACT(MONTH FROM (CAST(TRIM(:FEED_DATE) AS DATE))) AS MO_ID, 
TRIM(''$foldernm'') AS BI_FOLDER_NM, 
TRIM(''$WF_NM'') AS JOB_NM, ''ALL'' AS  TASK_NM, 
''WORKFLOW'' AS TASK_TYPE, 
CAST((TRIM(''$wf_START_TIME'')) AS TIMESTAMP(6) ) AS WF_END_TS, 
 ''SUCCESS'' AS STATUS_MSG  FROM  
DB_T_CTRL_PROD.ECTL_BATCH_INFO B WHERE ECTL_PROJ_ID = CAST(TRIM(''$ACT_PROJ_ID'') AS INTEGER) AND ECTL_ACTIVE_IND = ''Y'' 
) SRC 
SET STATUS_MSG = SRC.STATUS_MSG,
WF_END_TS = SRC.WF_END_TS
WHERE 
TGT.ECTL_BATCH_ID = SRC.ECTL_BATCH_ID AND
TGT.DATABASE_NM = SRC.DATABASE_NM AND
TGT.ECTL_PROJ_ID = SRC.ECTL_PROJ_ID AND
TGT.DAILY_FEED_IND = SRC.DAILY_FEED_IND AND
TGT.DT_ID = SRC.DT_ID AND 
TGT.MO_ID = SRC.MO_ID AND 
TGT.JOB_NM = SRC.JOB_NM AND 
TGT.TASK_NM = SRC.TASK_NM AND 
TGT.TASK_TYPE = SRC.TASK_TYPE AND 
TGT.BI_FOLDER_NM = SRC.BI_FOLDER_NM AND 
TGT.STATUS_MSG IS null;


END; ';