-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STG_SERVICE_CENTER_NAME("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component STG_SERVICE_CENTER_NAME_INS, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_PROD.STG_SERVICE_CENTER_NAME;


-- Component amgdsq_SVCHDR_SVCHEDR, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE amgdsq_SVCHDR_SVCHEDR AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_STATE,
$2 as SC_NO,
$3 as SC_NAME,
$4 as COUNTY_NO,
$5 as COUNTY_NAME,
$6 as SC_STATUS,
$7 as SC_ZIP1,
$8 as DISTRICT,
$9 as REGION,
$10 as RENT_BS,
$11 as RENT_VEND1,
$12 as RENT_AMT1,
$13 as RENT_TIN1,
$14 as RENT_VEND2,
$15 as RENT_AMT2,
$16 as RENT_TIN2,
$17 as CR_BATCH,
$18 as CR_RECORD,
$19 as AUTO_A_UD,
$20 as FIRE_CF_UD,
$21 as AUTO_G_UD,
$22 as HO_UD,
$23 as RFD_UD,
$24 as MOBILE_HOME_UD,
$25 as SMALL_LINES_UD,
$26 as CLAIMS_DISTRICT_CODE,
$27 as DOWNLOAD_INDICATOR,
$28 as DOWNLOAD_PRIORITY,
$29 as DOWNLOAD_USER_ID,
$30 as GROUP_NUMBER,
$31 as FILE_NUMBER,
$32 as PRICE_INDEX,
$33 as CATAGORY,
$34 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
svchdr_SVCHEDR.SC_STATE,
svchdr_SVCHEDR.SC_NO,
svchdr_SVCHEDR.SC_NAME,
svchdr_SVCHEDR.COUNTY_NO,
svchdr_SVCHEDR.COUNTY_NAME,
svchdr_SVCHEDR.SC_STATUS,
svchdr_SVCHEDR.SC_ZIP1,
svchdr_SVCHEDR.DISTRICT,
svchdr_SVCHEDR.REGION,
svchdr_SVCHEDR.RENT_BS,
svchdr_SVCHEDR.RENT_VEND1,
svchdr_SVCHEDR.RENT_AMT1,
svchdr_SVCHEDR.RENT_TIN1,
svchdr_SVCHEDR.RENT_VEND2,
svchdr_SVCHEDR.RENT_AMT2,
svchdr_SVCHEDR.RENT_TIN2,
svchdr_SVCHEDR.CR_BATCH,
svchdr_SVCHEDR.CR_RECORD,
svchdr_SVCHEDR.AUTO_A_UD,
svchdr_SVCHEDR.FIRE_CF_UD,
svchdr_SVCHEDR.AUTO_G_UD,
svchdr_SVCHEDR.HO_UD,
svchdr_SVCHEDR.RFD_UD,
svchdr_SVCHEDR.MOBILE_HOME_UD,
svchdr_SVCHEDR.SMALL_LINES_UD,
svchdr_SVCHEDR.CLAIMS_DISTRICT_CODE,
svchdr_SVCHEDR.DOWNLOAD_INDICATOR,
svchdr_SVCHEDR.DOWNLOAD_PRIORITY,
svchdr_SVCHEDR.DOWNLOAD_USER_ID,
svchdr_SVCHEDR.GROUP_NUMBER,
svchdr_SVCHEDR.FILE_NUMBER,
svchdr_SVCHEDR.PRICE_INDEX,
svchdr_SVCHEDR.CATAGORY
FROM svchdr_SVCHEDR
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
amgdsq_SVCHDR_SVCHEDR.SC_STATE as SC_STATE,
TO_NUMBER(amgdsq_SVCHDR_SVCHEDR.SC_NO) as out_SC_NO,
amgdsq_SVCHDR_SVCHEDR.SC_NAME as SC_NAME,
amgdsq_SVCHDR_SVCHEDR.COUNTY_NO as COUNTY_NO,
amgdsq_SVCHDR_SVCHEDR.COUNTY_NAME as COUNTY_NAME,
amgdsq_SVCHDR_SVCHEDR.SC_STATUS as SC_STATUS,
amgdsq_SVCHDR_SVCHEDR.SC_ZIP1 as SC_ZIP1,
amgdsq_SVCHDR_SVCHEDR.DISTRICT as DISTRICT,
amgdsq_SVCHDR_SVCHEDR.REGION as REGION,
amgdsq_SVCHDR_SVCHEDR.RENT_BS as RENT_BS,
amgdsq_SVCHDR_SVCHEDR.RENT_VEND1 as RENT_VEND1,
amgdsq_SVCHDR_SVCHEDR.RENT_AMT1 as RENT_AMT1,
amgdsq_SVCHDR_SVCHEDR.RENT_TIN1 as RENT_TIN1,
amgdsq_SVCHDR_SVCHEDR.RENT_VEND2 as RENT_VEND2,
amgdsq_SVCHDR_SVCHEDR.RENT_AMT2 as RENT_AMT2,
amgdsq_SVCHDR_SVCHEDR.RENT_TIN2 as RENT_TIN2,
amgdsq_SVCHDR_SVCHEDR.CR_BATCH as CR_BATCH,
amgdsq_SVCHDR_SVCHEDR.CR_RECORD as CR_RECORD,
amgdsq_SVCHDR_SVCHEDR.AUTO_A_UD as AUTO_A_UD,
amgdsq_SVCHDR_SVCHEDR.FIRE_CF_UD as FIRE_CF_UD,
amgdsq_SVCHDR_SVCHEDR.AUTO_G_UD as AUTO_G_UD,
amgdsq_SVCHDR_SVCHEDR.HO_UD as HO_UD,
amgdsq_SVCHDR_SVCHEDR.RFD_UD as RFD_UD,
amgdsq_SVCHDR_SVCHEDR.MOBILE_HOME_UD as MOBILE_HOME_UD,
amgdsq_SVCHDR_SVCHEDR.SMALL_LINES_UD as SMALL_LINES_UD,
amgdsq_SVCHDR_SVCHEDR.CLAIMS_DISTRICT_CODE as CLAIMS_DISTRICT_CODE,
amgdsq_SVCHDR_SVCHEDR.DOWNLOAD_INDICATOR as DOWNLOAD_INDICATOR,
amgdsq_SVCHDR_SVCHEDR.DOWNLOAD_PRIORITY as DOWNLOAD_PRIORITY,
amgdsq_SVCHDR_SVCHEDR.DOWNLOAD_USER_ID as DOWNLOAD_USER_ID,
amgdsq_SVCHDR_SVCHEDR.GROUP_NUMBER as GROUP_NUMBER,
amgdsq_SVCHDR_SVCHEDR.FILE_NUMBER as FILE_NUMBER,
amgdsq_SVCHDR_SVCHEDR.PRICE_INDEX as PRICE_INDEX,
amgdsq_SVCHDR_SVCHEDR.CATAGORY as CATAGORY,
amgdsq_SVCHDR_SVCHEDR.source_record_id
FROM
amgdsq_SVCHDR_SVCHEDR
);


-- Component STG_SERVICE_CENTER_NAME_INS, Type TARGET 
INSERT INTO DB_T_STAG_PROD.STG_SERVICE_CENTER_NAME
(
SC_STATE,
SC_NO,
SC_NAME,
COUNTY_NO,
COUNTY_NAME,
SC_STATUS,
SC_ZIP_CD,
DISTRICT,
REGION,
RENT_BS,
RENT_VEND1,
RENT_AMT1,
RENT_TIN1,
RENT_VEND2,
RENT_AMT2,
RENT_TIN2,
CR_BATCH,
CR_RECORD,
AUTO_UD,
FIRE_CF_UD,
FG_UD,
HO_UD,
RFD_UD,
MOBILE_HOME_UD,
SMALL_LINES_UD,
CLAIMS_DIST_CD,
DWNLD_IND,
DWNLD_PRIORITY,
DWNLD_USERID,
GROUP_NBR,
FILE_NBR,
PRICE_INDEX,
CATAGORY
)
SELECT
EXPTRANS.SC_STATE as SC_STATE,
EXPTRANS.out_SC_NO as SC_NO,
EXPTRANS.SC_NAME as SC_NAME,
EXPTRANS.COUNTY_NO as COUNTY_NO,
EXPTRANS.COUNTY_NAME as COUNTY_NAME,
EXPTRANS.SC_STATUS as SC_STATUS,
EXPTRANS.SC_ZIP1 as SC_ZIP_CD,
EXPTRANS.DISTRICT as DISTRICT,
EXPTRANS.REGION as REGION,
EXPTRANS.RENT_BS as RENT_BS,
EXPTRANS.RENT_VEND1 as RENT_VEND1,
EXPTRANS.RENT_AMT1 as RENT_AMT1,
EXPTRANS.RENT_TIN1 as RENT_TIN1,
EXPTRANS.RENT_VEND2 as RENT_VEND2,
EXPTRANS.RENT_AMT2 as RENT_AMT2,
EXPTRANS.RENT_TIN2 as RENT_TIN2,
EXPTRANS.CR_BATCH as CR_BATCH,
EXPTRANS.CR_RECORD as CR_RECORD,
EXPTRANS.AUTO_A_UD as AUTO_UD,
EXPTRANS.FIRE_CF_UD as FIRE_CF_UD,
EXPTRANS.AUTO_G_UD as FG_UD,
EXPTRANS.HO_UD as HO_UD,
EXPTRANS.RFD_UD as RFD_UD,
EXPTRANS.MOBILE_HOME_UD as MOBILE_HOME_UD,
EXPTRANS.SMALL_LINES_UD as SMALL_LINES_UD,
EXPTRANS.CLAIMS_DISTRICT_CODE as CLAIMS_DIST_CD,
EXPTRANS.DOWNLOAD_INDICATOR as DWNLD_IND,
EXPTRANS.DOWNLOAD_PRIORITY as DWNLD_PRIORITY,
EXPTRANS.DOWNLOAD_USER_ID as DWNLD_USERID,
EXPTRANS.GROUP_NUMBER as GROUP_NBR,
EXPTRANS.FILE_NUMBER as FILE_NBR,
EXPTRANS.PRICE_INDEX as PRICE_INDEX,
EXPTRANS.CATAGORY as CATAGORY
FROM
EXPTRANS;


END; ';