-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_CHECK_EOM_ERR_RECORDS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component sq_CHECK_ERR_LOG, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_CHECK_ERR_LOG AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_ERR_ID,
$2 as ECTL_BATCH_ID,
$3 as ECTL_PROJ_ID,
$4 as ECTL_PRGM_ID,
$5 as ECTL_SRC_TABLE_ID,
$6 as ECTL_SRC_KEY_VAL,
$7 as ERR_COL_NM,
$8 as ERR_COL_VAL,
$9 as ERR_DESC,
$10 as ERR_TS,
$11 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT ECTL_ERR_LOG.ECTL_ERR_ID
, ECTL_ERR_LOG.ECTL_BATCH_ID
, ECTL_ERR_LOG.ECTL_PROJ_ID
, ECTL_ERR_LOG.ECTL_PRGM_ID
, ECTL_ERR_LOG.ECTL_SRC_TABLE_ID
, ECTL_ERR_LOG.ECTL_SRC_KEY_VAL
, ECTL_ERR_LOG.ERR_COL_NM
, ECTL_ERR_LOG.ERR_COL_VAL
, ECTL_ERR_LOG.ERR_DESC
,ERR_TS as LOG_DATE
FROM
 DB_T_CTRL_FIN_PROD.ECTL_ERR_LOG
 where log_date >
(SELECT 
actual_run_ts as first_of_month
FROM DB_T_CTRL_PROD.MIS_CLOSEOUT_CTL a
where a.actual_run_Ts = (
select max(b.actual_run_ts)
from  DB_T_CTRL_PROD.MIS_CLOSEOUT_CTL b
where actual_run_ts <> ''0001-01-01 00:00:00.000000'')) 
group by 1,2,3,4,5,6,7,8,9,10
) SRC
)
);


-- Component Error_Records_INS, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE Error_Records_INS AS
(
SELECT
sq_CHECK_ERR_LOG.ECTL_ERR_ID as ECTL_ERROR_ID,
sq_CHECK_ERR_LOG.ECTL_BATCH_ID as ECTL_BATCH_ID,
sq_CHECK_ERR_LOG.ECTL_PROJ_ID as ECTL_PROJECT_ID,
sq_CHECK_ERR_LOG.ECTL_PRGM_ID as ECTL_PROGRAM_ID,
sq_CHECK_ERR_LOG.ECTL_SRC_TABLE_ID as ECTL_SOURCE_TABLE_ID,
sq_CHECK_ERR_LOG.ECTL_SRC_KEY_VAL as ECTL_SOURCE_KEY_VALUE,
sq_CHECK_ERR_LOG.ERR_COL_NM as ERROR_COLUMN_NAME,
sq_CHECK_ERR_LOG.ERR_COL_VAL as ERROR_COLUMN_VALUE,
sq_CHECK_ERR_LOG.ERR_DESC as ERROR_DESCRIPTION,
sq_CHECK_ERR_LOG.ERR_TS as ERROR_TIMESTAMP
FROM
sq_CHECK_ERR_LOG
);


-- Component Error_Records_INS, Type EXPORT_DATA Exporting data
;


END; ';