-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_ANALYTICS_AGENT_SUMMARY_BURST_TRIGGER("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_AGG_ENTERPRISE_METRICS_MTHLY, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_ENTERPRISE_METRICS_MTHLY AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as "TITLE",
$2 as CNT,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT ''BurstKeyCount: ''||TRIM(CAST(COUNT(DISTINCT AH.AGENCY_NBR) AS VARCHAR(10)))  AS BurstKeyCount,COUNT(DISTINCT AH.AGENCY_NBR)
FROM DB_T_CORE_PROD.AGENT_HIER AH INNER JOIN DB_V_PROD.AGNT_NM_LKUP AN
ON AH.AGNT_CLIENT_ID = AN.AGNT_CLIENT_ID INNER JOIN  
(SELECT ADD_MONTHS(ECTL_ORIG_INS_TS,CASE WHEN (ECTL_PARAM_VALUE=''N'') THEN (-1) ELSE (-2)END) MAX_LOAD_TS, 
ADD_MONTHS(CAST(MAX_LOAD_TS AS DATE),1)-EXTRACT (DAY FROM MAX_LOAD_TS) CAL_END_DATE
FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_PARAM WHERE ECTL_PARAM_ID=16 AND ECTL_PARAM_DESC=''AGENT SUMMARY MTHLY LOAD STATUS'') ECTL ON 1=1
WHERE AH.AGNT_STATUS_CD  NOT IN  (''j'', ''-'') AND
ECTL.CAL_END_DATE BETWEEN AH.AGNT_EFF_DT AND AH.AGNT_EXPIRY_DT
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_AGG_ENTERPRISE_METRICS_MTHLY.TITLE as TITLE,
SQ_AGG_ENTERPRISE_METRICS_MTHLY.CNT as CNT,
CASE WHEN SQ_AGG_ENTERPRISE_METRICS_MTHLY.CNT <> 0 THEN ''S'' ELSE ''F'' END as out_flag,
CASE WHEN SQ_AGG_ENTERPRISE_METRICS_MTHLY.CNT = 0 THEN 
null --RAISE_ERROR(''No Agent records found in AGENT_HIER'') 
ELSE $3 END as Abort,
SQ_AGG_ENTERPRISE_METRICS_MTHLY.source_record_id
FROM
SQ_AGG_ENTERPRISE_METRICS_MTHLY
);


-- Component FILTRANS, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE FILTRANS AS
(
SELECT
EXPTRANS.TITLE as TITLE,
EXPTRANS.CNT as CNT,
EXPTRANS.out_flag as out_flag,
EXPTRANS.Abort as Abort,
EXPTRANS.source_record_id
FROM
EXPTRANS
WHERE EXPTRANS.out_flag = ''S''
);


-- Component EXPTRANS3, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS3 AS
(
SELECT
FILTRANS.TITLE as TITLE1,
FILTRANS.source_record_id
FROM
FILTRANS
);


-- Component Agent_summary_burst_trigger, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE Agent_summary_burst_trigger AS
(
SELECT
EXPTRANS3.TITLE1 as Title
FROM
EXPTRANS3
);


-- Component Agent_summary_burst_trigger, Type EXPORT_DATA Exporting data
;


END; ';