-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_FIN_AGG_LOSS_INFO("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE 
WF_MONTH_ID INTEGER;
ECTL_ACTIVE_IND VARCHAR;
BEGIN 
WF_MONTH_ID:=1;
ECTL_ACTIVE_IND:=''Y''; 

-- Component SQ_FIN_LOSS_TXN, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FIN_LOSS_TXN AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MO_ID,
$2 as CMPY_CD,
$3 as ST_CD,
$4 as SVC_NBR,
$5 as AGNT_NBR,
$6 as RSV_GRP,
$7 as LOB_CD,
$8 as PRODUCT_CD,
$9 as PLCY_TYPE,
$10 as PRODUCT_DESC,
$11 as PLCY_NBR,
$12 as PLCY_EFF_DT,
$13 as PLCY_EXP_DT,
$14 as ACCTNG_MO,
$15 as ACCTNG_YR,
$16 as CAT,
$17 as POOL_CD,
$18 as POOL_DESC,
$19 as MONETARY_AMT,
$20 as LEDGER,
$21 as ACCT_NBR,
$22 as GL_ACCT_DESC,
$23 as GL_ACCT_GRP,
$24 as CLM_NBR,
$25 as CLM_LOSS_DT,
$26 as DEPT_ID,
$27 as ECTL_ORIG_INS_TS,
$28 as PROD_PLAN,
$29 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT  MO_ID,FL.CMPY_CD,FL.ST_CD,SVC_NBR,AGNT_NBR,

       upper(COALESCE(CASE WHEN FL.PRODUCT_CD=''F00001''and  (cast(PLCY_TYPE as varchar(50)) like ''SF%'' OR cast(PROD_NAME as varchar(50)) like ''SF%'') AND FL.CMPY_CD IN (''AIC'',''AMF'') THEN ''Fire'' 

WHEN FL.PRODUCT_CD=''F00001''and (cast(PLCY_TYPE as varchar(50)) like ''SF%'' OR cast(PROD_NAME as varchar(50)) like ''SF%'') AND FL.CMPY_CD IN (''AAI'') THEN ''No_Triangle'' 

WHEN FL.PRODUCT_CD=''F00001''and (cast(PLCY_TYPE as varchar(50))  like ''SF%'' OR cast(PROD_NAME as varchar(50))  like ''SF%'') AND FL.CMPY_CD IN (''AMI'') THEN ''No_Triangle'' 

WHEN FL.PRODUCT_CD=''F00001''and (cast(PLCY_TYPE as varchar(50)) not like ''SF%'' OR cast(PROD_NAME as varchar(50)) not like ''SF%'') AND FL.CMPY_CD IN (''AMI'') THEN ''Fire'' WHEN FL.PRODUCT_CD=''GL0001''and (cast(PLCY_TYPE as varchar(50))  like ''PERSUMBRELLA%'' OR cast(PROD_NAME as varchar(50))  like ''PersonalUmbrella%'') AND FL.CMPY_CD IN (''AIC'',''AMI'') THEN ''Limited_Umbrella'' 

WHEN FL.PRODUCT_CD=''GL0001''and (cast(PLCY_TYPE as varchar(50)) NOT like ''PERSUMBRELLA%'' OR cast(PROD_NAME as varchar(50)) NOT  like ''PersonalUmbrella%'') AND FL.CMPY_CD IN (''AMI'') THEN ''OL'' 

WHEN FL.PRODUCT_CD=''GL0001''and (cast(PLCY_TYPE as varchar(50))  NOT like ''PERSUMBRELLA%'' OR cast(PROD_NAME as varchar(50)) NOT  like ''PersonalUmbrella%'')AND FL.CMPY_CD IN (''AIC'') THEN ''No_Triangle'' ELSE

RSV_GRP END, ''UNK'')) RSV_GRP_new,

        FL.LOB_CD,FL.PRODUCT_CD,FL.PLCY_TYPE,CASE WHEN FL.PRODUCT_CD =''F00001'' AND (cast(PLCY_TYPE as varchar(50)) like ''SF%'' OR cast(PROD_NAME as varchar(50)) like ''SF%'') THEN ''Fire''

		WHEN FL.PRODUCT_CD =''F00001'' AND  (cast(PLCY_TYPE as varchar(50)) not like ''SF%'' OR cast(PROD_NAME as varchar(50)) not like ''SF%'') THEN ''Farm Fire''

		WHEN FL.PRODUCT_CD =''GL0001'' AND  (cast(PLCY_TYPE as varchar(50))  like ''PERSUMBRELLA%'' OR cast(PROD_NAME as varchar(50))  like ''PersonalUmbrella%'') THEN ''GW Personal Umbrella''

		WHEN FL.PRODUCT_CD =''GL0001'' AND  (cast(PLCY_TYPE as varchar(50)) not  like ''PERSUMBRELLA%'' OR cast(PROD_NAME as varchar(50)) not  like ''PersonalUmbrella%'') THEN ''FARM UMBR PERS''

		else 		COV_DESC end AS PRODUCT_DESC,PLCY_NBR,PLCY_EFF_DT,

        PLCY_EXP_DT,ACCTNG_MO,ACCTNG_YR,

        CASE 

        WHEN    SUBSTR(FL.POOL_CD,1,3)=''CAT'' THEN ''CAT'' 

ELSE    ''NonCAT'' 

END CAT,

        FL.POOL_CD,POOL_DESC,sum(CAST(MONETARY_AMT AS DECIMAL (20,2)))MONETARY_AMT,

        LEDGER,FL.ACCT_NBR,ACT.ACCT_DESC,METRIC_LONG_NM ,CLM_NBR,CLM_LOSS_DT ,DEPT_ID, FL.ECTL_ORIG_INS_TS,

COALESCE(

case

    when cast(PROD_NAME as varchar(50))=''BUSINESSOWNERS'' then ''BOP''

    when cast(PROD_NAME as varchar(50)) like ''HO%'' then (case when gw.AGMT_PROD_CVGE_LVL_DESC=''HOME INNOVATION'' then ''HOINN'' else ''HO'' end)

    when cast(PROD_NAME as varchar(50)) like ''MH%'' then ''MH''

    when cast(PROD_NAME as varchar(50)) like ''SF%'' then ''SF''

    when cast(PROD_NAME as varchar(50))=''WATERCRAFT'' then ''WTC''

    when cast(PROD_NAME as varchar(50))=''PersonalUmbrella'' then ''UMB''

	    when cast(PROD_NAME as varchar(50))=''FarmUmbrella'' then ''UMB''

		

    else cast(PROD_NAME as varchar(50))

end,case

    when cast(FL.PLCY_TYPE as varchar(50))=''BUSINESSOWNERS'' then ''BOP''

    when cast(FL.PLCY_TYPE as varchar(50)) like ''HO%'' then (case when gw.AGMT_PROD_CVGE_LVL_DESC=''HOME INNOVATION'' then ''HOINN'' else ''HO'' end)

    when cast(FL.PLCY_TYPE as varchar(50)) like ''MH%'' then ''MH''

    when cast(FL.PLCY_TYPE as varchar(50)) like ''SF%'' then ''SF''

    when cast(FL.PLCY_TYPE as varchar(50))=''WATERCRAFT'' then ''WTC''

    when cast(FL.PLCY_TYPE as varchar(50))=''PERSUMBRELLA'' then ''UMB''

	    when cast(FL.PLCY_TYPE as varchar(50))=''FARMUMBRELLA'' then ''UMB''

    else cast(FL.PLCY_TYPE as varchar(50))END )as PROD_PLAN_NEW

FROM    DB_T_CORE_FIN_PROD.FIN_LOSS_TXN FL LEFT OUTER JOIN   DB_T_CORE_FIN_PROD.FIN_PRODUCT_HIER PRODT 

    ON  FL.PRODUCT_CD=PRODT.PRODUCT_CD and PRODT.PRODUCT_CD not in (''F00001'',''GL0001'') LEFT OUTER JOIN  (SELECT DISTINCT POOL_CD,POOL_DESC FROM DB_T_SHRD_FIN_PROD.FIN_POOL_CD_LKUP) POOL

    ON  FL.POOL_CD=POOL.POOL_CD LEFT OUTER JOIN DB_T_STAG_FIN_PROD.FIN_ACCT_NBR_GRP_LKUP  ACC 

    ON  FL.ACCT_NBR=ACC.ACCT_NBR LEFT OUTER JOIN  (SELECT ACCT_NBR,ACCT_DESC FROM DB_T_SHRD_FIN_PROD.FIN_ACCT_NBR_LKUP  

    QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCT_NBR ORDER BY  EFF_DT DESC)=1)ACT

    ON ACC.ACCT_NBR=ACT.ACCT_NBR    LEFT OUTER JOIN   (select  distinct  source, product_cd , CMPY_CD ,  RSV_GRP

FROM   DB_T_SHRD_FIN_PROD.RSV_GRP_LKUP 

where product_cd NOT in (''GL0001'',''F00001'')

QUALIFY ROW_NUMBER() OVER( PARTITION BY  product_cd , CMPY_CD   ORDER BY source ) = 1) RSV

    ON FL.CMPY_CD=RSV.CMPY_CD AND FL.PRODUCT_CD=RSV.PRODUCT_CD

left outer join (select distinct HOST_AGMT_NUM, PROD_NAME, AGMT_PROD_CVGE_LVL_DESC

FROM DB_T_PROD_CORE.AGMT A

JOIN DB_T_PROD_CORE.AGMT_PROD AP ON AP.AGMT_ID=A.AGMT_ID AND  AP.AGMT_PROD_ROLE_CD=''PLCYTYPE''

JOIN DB_T_PROD_CORE.PROD PROD1 ON PROD1.PROD_ID=AP.PROD_ID

WHERE AGMT_TYPE_CD=''PPV'' AND SRC_SYS_CD=''GWPC''

AND EXTRACT( YEAR FROM A.TRANS_STRT_DTTM)*100+EXTRACT(MONTH FROM A.TRANS_STRT_DTTM )<=:WF_MONTH_ID

qualify row_number() over(partition by HOST_AGMT_NUM order by a.TRANS_END_DTTM desc, A.TRANS_STRT_DTTM DESC)=1

) gw on gw.HOST_AGMT_NUM=PLCY_NBR 

WHERE   FL.MO_ID=:WF_MONTH_ID

GROUP   BY MO_ID,FL.CMPY_CD,FL.ST_CD,SVC_NBR,AGNT_NBR,

        RSV_GRP_new,

        FL.LOB_CD,FL.PRODUCT_CD,	product_desc,PLCY_NBR,PLCY_EFF_DT,

        PLCY_EXP_DT,ACCTNG_MO,ACCTNG_YR,

        CAT,

        FL.POOL_CD,POOL_DESC,FL.PLCY_TYPE,

        LEDGER,FL.ACCT_NBR,METRIC_LONG_NM,ACT.ACCT_DESC,CLM_NBR,CLM_LOSS_DT ,DEPT_ID,FL.ECTL_ORIG_INS_TS, PROD_PLAN_NEW
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_FIN_LOSS_TXN.MO_ID as MO_ID,
SQ_FIN_LOSS_TXN.CMPY_CD as CMPY_CD,
SQ_FIN_LOSS_TXN.ST_CD as ST_CD,
SQ_FIN_LOSS_TXN.SVC_NBR as SVC_NBR,
SQ_FIN_LOSS_TXN.AGNT_NBR as AGNT_NBR,
SQ_FIN_LOSS_TXN.RSV_GRP as RSV_GRP,
SQ_FIN_LOSS_TXN.LOB_CD as LOB_CD,
SQ_FIN_LOSS_TXN.PRODUCT_CD as PRODUCT_CD,
SQ_FIN_LOSS_TXN.PLCY_TYPE as PLCY_TYPE,
SQ_FIN_LOSS_TXN.PRODUCT_DESC as PRODUCT_DESC,
SQ_FIN_LOSS_TXN.PLCY_NBR as PLCY_NBR,
SQ_FIN_LOSS_TXN.PLCY_EFF_DT as PLCY_EFF_DT,
SQ_FIN_LOSS_TXN.PLCY_EXP_DT as PLCY_EXP_DT,
SQ_FIN_LOSS_TXN.ACCTNG_MO as ACCTNG_MO,
SQ_FIN_LOSS_TXN.ACCTNG_YR as ACCTNG_YR,
SQ_FIN_LOSS_TXN.CAT as CAT,
SQ_FIN_LOSS_TXN.POOL_CD as POOL_CD,
SQ_FIN_LOSS_TXN.POOL_DESC as POOL_DESC,
SQ_FIN_LOSS_TXN.MONETARY_AMT as MONETARY_AMT,
SQ_FIN_LOSS_TXN.LEDGER as LEDGER,
SQ_FIN_LOSS_TXN.ACCT_NBR as ACCT_NBR,
SQ_FIN_LOSS_TXN.GL_ACCT_DESC as GL_ACCT_DESC,
SQ_FIN_LOSS_TXN.GL_ACCT_GRP as GL_ACCT_GRP,
SQ_FIN_LOSS_TXN.CLM_NBR as CLM_NBR,
SQ_FIN_LOSS_TXN.CLM_LOSS_DT as CLM_LOSS_DT,
SQ_FIN_LOSS_TXN.DEPT_ID as DEPT_ID,
SQ_FIN_LOSS_TXN.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
SQ_FIN_LOSS_TXN.PROD_PLAN as PROD_PLAN,
SQ_FIN_LOSS_TXN.source_record_id
FROM
SQ_FIN_LOSS_TXN
);


-- Component AGG_LOSS_INFO, Type TARGET 
INSERT INTO DB_T_CORE_FIN_PROD.AGG_LOSS_INFO
(
MO_ID,
CMPY_CD,
ST_CD,
SVC_NBR,
AGNT_NBR,
RSV_GRP,
LOB_CD,
PRODUCT_CD,
PLCY_TYPE,
PRODUCT_DESC,
PLCY_NBR,
PLCY_EFF_DT,
PLCY_EXP_DT,
ACCTNG_MO,
ACCTNG_YR,
CAT,
POOL_CD,
POOL_DESC,
MONETARY_AMT,
LEDGER,
ACCT_NBR,
GL_ACCT_DESC,
GL_ACCT_GRP,
CLM_NBR,
CLM_LOSS_DT,
DEPT_ID,
PROD_PLAN,
ECTL_ORIG_INS_TS
)
SELECT
EXPTRANS.MO_ID as MO_ID,
EXPTRANS.CMPY_CD as CMPY_CD,
EXPTRANS.ST_CD as ST_CD,
EXPTRANS.SVC_NBR as SVC_NBR,
EXPTRANS.AGNT_NBR as AGNT_NBR,
EXPTRANS.RSV_GRP as RSV_GRP,
EXPTRANS.LOB_CD as LOB_CD,
EXPTRANS.PRODUCT_CD as PRODUCT_CD,
EXPTRANS.PLCY_TYPE as PLCY_TYPE,
EXPTRANS.PRODUCT_DESC as PRODUCT_DESC,
EXPTRANS.PLCY_NBR as PLCY_NBR,
EXPTRANS.PLCY_EFF_DT as PLCY_EFF_DT,
EXPTRANS.PLCY_EXP_DT as PLCY_EXP_DT,
EXPTRANS.ACCTNG_MO as ACCTNG_MO,
EXPTRANS.ACCTNG_YR as ACCTNG_YR,
EXPTRANS.CAT as CAT,
EXPTRANS.POOL_CD as POOL_CD,
EXPTRANS.POOL_DESC as POOL_DESC,
EXPTRANS.MONETARY_AMT as MONETARY_AMT,
EXPTRANS.LEDGER as LEDGER,
EXPTRANS.ACCT_NBR as ACCT_NBR,
EXPTRANS.GL_ACCT_DESC as GL_ACCT_DESC,
EXPTRANS.GL_ACCT_GRP as GL_ACCT_GRP,
EXPTRANS.CLM_NBR as CLM_NBR,
EXPTRANS.CLM_LOSS_DT as CLM_LOSS_DT,
EXPTRANS.DEPT_ID as DEPT_ID,
EXPTRANS.PROD_PLAN as PROD_PLAN,
EXPTRANS.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS
FROM
EXPTRANS;


END; ';