-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_FIN_AGG_PREMIUM_INFO("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE 
WF_MONTH_ID INTEGER;
BEGIN 
WF_MONTH_ID:=1;

-- Component SQ_FIN_PREMIUM_TXN, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FIN_PREMIUM_TXN AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MO_ID,
$2 as CMPY_CD,
$3 as ST_CD,
$4 as SVC_NBR,
$5 as AGNT_NBR,
$6 as RSV_GRP,
$7 as LOB_CD,
$8 as PRODUCT_CD,
$9 as PRODUCT_DESC,
$10 as PLCY_NBR,
$11 as PLCY_EFF_DT,
$12 as PLCY_EXP_DT,
$13 as ACCTNG_MO,
$14 as ACCTNG_YR,
$15 as CAT,
$16 as POOL_CD,
$17 as POOL_DESC,
$18 as MONETARY_AMT,
$19 as LEDGER,
$20 as ACCT_NBR,
$21 as GL_ACCT_DESC,
$22 as GL_ACCT_GRP,
$23 as PLCY_TERM,
$24 as TOT_PREM_AMT,
$25 as DEPT_ID,
$26 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT	FP.MO_ID,FP.CMPY_CD,FP.ST_CD,FP.SVC_NBR,FP.AGNT_NBR,RSV_GRP,

		FP.LOB_CD,FP.PRODUCT_CD,COV_DESC,PLCY_NBR,PLCY_EFF_DT,PLCY_EXP_DT,

		ACCTNG_MO,ACCTNG_YR,

CASE	WHEN SUBSTR(FP.POOL_CD,1,3)=''CAT'' THEN ''CAT'' 

ELSE	''NonCAT'' 

END	CAT,FP.POOL_CD,POOL_DESC,SUM(MONETARY_AMT) AS MON_AMT,

		LEDGER,FP.ACCT_NBR,ACT.ACCT_DESC,METRIC_LONG_NM ,PLCY_TERM,SUM(TOT_PREM_AMT) AS TOT_PREM,DEPT_ID

FROM	(

SELECT	MO_ID,FP.CMPY_CD,FP.ST_CD,FP.SVC_NBR,FP.AGNT_NBR,

		FP.LOB_CD,FP.PRODUCT_CD,PLCY_NBR,PLCY_EFF_DT,PLCY_EXP_DT,ACCTNG_MO,

		ACCTNG_YR,POOL_CD,SUM(MONETARY_AMT) MONETARY_AMT,LEDGER,ACCT_NBR,

		PLCY_TERM,SUM(TOT_PREM_AMT) TOT_PREM_AMT,DEPT_ID  

FROM	DB_T_CORE_FIN_PROD.FIN_PREMIUM_TXN FP 

WHERE	MO_ID=:WF_MONTH_ID

GROUP	BY MO_ID,FP.CMPY_CD,FP.ST_CD,FP.SVC_NBR,FP.AGNT_NBR,FP.LOB_CD,FP.PRODUCT_CD,PLCY_NBR,PLCY_EFF_DT,PLCY_EXP_DT,ACCTNG_MO,ACCTNG_YR,POOL_CD,LEDGER,ACCT_NBR,PLCY_TERM,DEPT_ID) FP LEFT OUTER JOIN  DB_T_CORE_FIN_PROD.FIN_PRODUCT_HIER  DEVT 

	ON	FP.PRODUCT_CD=DEVT.PRODUCT_CD LEFT OUTER JOIN  (SELECT DISTINCT POOL_CD,POOL_DESC FROM DB_T_SHRD_FIN_PROD.FIN_POOL_CD_LKUP) PL 

	ON	FP.POOL_CD=PL.POOL_CD	LEFT OUTER JOIN DB_T_STAG_FIN_PROD.FIN_ACCT_NBR_GRP_LKUP  ACCT 

		ON	FP.ACCT_NBR=ACCT.ACCT_NBR LEFT OUTER JOIN  (SELECT ACCT_NBR,ACCT_DESC FROM DB_T_SHRD_FIN_PROD.FIN_ACCT_NBR_LKUP  

	QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCT_NBR ORDER BY  EFF_DT DESC)=1)ACT

	ON ACCT.ACCT_NBR=ACT.ACCT_NBR                		

              LEFT JOIN (
  SELECT
    source,
    product_cd,
    PRC_GRP,
    CMPY_CD,
    RSV_GRP
  FROM
    DB_T_SHRD_FIN_PROD.RSV_GRP_LKUP QUALIFY ROW_NUMBER() OVER (
      PARTITION BY product_cd,
      CMPY_CD
      ORDER BY
        source
    ) = 1
) RSV ON FP.CMPY_CD ILIKE RSV.CMPY_CD
AND FP.PRODUCT_CD ILIKE RSV.PRODUCT_CD
GROUP	BY FP.MO_ID,FP.CMPY_CD,FP.ST_CD,FP.SVC_NBR,FP.AGNT_NBR,RSV_GRP,FP.LOB_CD,FP.PRODUCT_CD,COV_DESC,PLCY_NBR,PLCY_EFF_DT,PLCY_EXP_DT,ACCTNG_MO,ACCTNG_YR,CAT,FP.POOL_CD,POOL_DESC,LEDGER,FP.ACCT_NBR,METRIC_LONG_NM,ACT.ACCT_DESC,PLCY_TERM,DEPT_ID
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_FIN_PREMIUM_TXN.MO_ID as MO_ID,
SQ_FIN_PREMIUM_TXN.CMPY_CD as CMPY_CD,
SQ_FIN_PREMIUM_TXN.ST_CD as ST_CD,
SQ_FIN_PREMIUM_TXN.SVC_NBR as SVC_NBR,
SQ_FIN_PREMIUM_TXN.AGNT_NBR as AGNT_NBR,
SQ_FIN_PREMIUM_TXN.RSV_GRP as RSV_GRP,
SQ_FIN_PREMIUM_TXN.LOB_CD as LOB_CD,
SQ_FIN_PREMIUM_TXN.PRODUCT_CD as PRODUCT_CD,
SQ_FIN_PREMIUM_TXN.PRODUCT_DESC as PRODUCT_DESC,
SQ_FIN_PREMIUM_TXN.PLCY_NBR as PLCY_NBR,
SQ_FIN_PREMIUM_TXN.PLCY_EFF_DT as PLCY_EFF_DT,
SQ_FIN_PREMIUM_TXN.PLCY_EXP_DT as PLCY_EXP_DT,
SQ_FIN_PREMIUM_TXN.ACCTNG_MO as ACCTNG_MO,
SQ_FIN_PREMIUM_TXN.ACCTNG_YR as ACCTNG_YR,
SQ_FIN_PREMIUM_TXN.CAT as CAT,
SQ_FIN_PREMIUM_TXN.POOL_CD as POOL_CD,
SQ_FIN_PREMIUM_TXN.POOL_DESC as POOL_DESC,
SQ_FIN_PREMIUM_TXN.MONETARY_AMT as MONETARY_AMT,
SQ_FIN_PREMIUM_TXN.LEDGER as LEDGER,
SQ_FIN_PREMIUM_TXN.ACCT_NBR as ACCT_NBR,
SQ_FIN_PREMIUM_TXN.GL_ACCT_DESC as GL_ACCT_DESC,
SQ_FIN_PREMIUM_TXN.GL_ACCT_GRP as GL_ACCT_GRP,
SQ_FIN_PREMIUM_TXN.PLCY_TERM as PLCY_TERM,
SQ_FIN_PREMIUM_TXN.TOT_PREM_AMT as TOT_PREM_AMT,
SQ_FIN_PREMIUM_TXN.DEPT_ID as DEPT_ID,
TO_CHAR ( null ) as o_PROD_PLAN,
SQ_FIN_PREMIUM_TXN.source_record_id
FROM
SQ_FIN_PREMIUM_TXN
);


-- Component AGG_PREMIUM_INFO, Type TARGET 
INSERT INTO DB_T_CORE_FIN_PROD.AGG_PREMIUM_INFO
(
MO_ID,
CMPY_CD,
ST_CD,
SVC_NBR,
AGNT_NBR,
RSV_GRP,
LOB_CD,
PRODUCT_CD,
PRODUCT_DESC,
PLCY_NBR,
PLCY_EFF_DT,
PLCY_EXP_DT,
ACCTNG_MO,
ACCTNG_YR,
CAT,
POOL_CD,
POOL_DESC,
MONETARY_AMT,
LEDGER,
ACCT_NBR,
GL_ACCT_DESC,
GL_ACCT_GRP,
PLCY_TERM,
TOT_PREM_AMT,
DEPT_ID,
PROD_PLAN
)
SELECT
EXPTRANS.MO_ID as MO_ID,
EXPTRANS.CMPY_CD as CMPY_CD,
EXPTRANS.ST_CD as ST_CD,
EXPTRANS.SVC_NBR as SVC_NBR,
EXPTRANS.AGNT_NBR as AGNT_NBR,
EXPTRANS.RSV_GRP as RSV_GRP,
EXPTRANS.LOB_CD as LOB_CD,
EXPTRANS.PRODUCT_CD as PRODUCT_CD,
EXPTRANS.PRODUCT_DESC as PRODUCT_DESC,
EXPTRANS.PLCY_NBR as PLCY_NBR,
EXPTRANS.PLCY_EFF_DT as PLCY_EFF_DT,
EXPTRANS.PLCY_EXP_DT as PLCY_EXP_DT,
EXPTRANS.ACCTNG_MO as ACCTNG_MO,
EXPTRANS.ACCTNG_YR as ACCTNG_YR,
EXPTRANS.CAT as CAT,
EXPTRANS.POOL_CD as POOL_CD,
EXPTRANS.POOL_DESC as POOL_DESC,
EXPTRANS.MONETARY_AMT as MONETARY_AMT,
EXPTRANS.LEDGER as LEDGER,
EXPTRANS.ACCT_NBR as ACCT_NBR,
EXPTRANS.GL_ACCT_DESC as GL_ACCT_DESC,
EXPTRANS.GL_ACCT_GRP as GL_ACCT_GRP,
EXPTRANS.PLCY_TERM as PLCY_TERM,
EXPTRANS.TOT_PREM_AMT as TOT_PREM_AMT,
EXPTRANS.DEPT_ID as DEPT_ID,
EXPTRANS.o_PROD_PLAN as PROD_PLAN
FROM
EXPTRANS;


END; ';