-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LUE_FIN_PREMIUM_TXN("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_FIN_LOSS_TXN, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FIN_LOSS_TXN AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MO_ID,
$2 as CMPY_CD,
$3 as ST_CD,
$4 as SVC_NBR,
$5 as AGNT_NBR,
$6 as CMPY_TYPE_CD,
$7 as LOB_CD,
$8 as PRODUCT_CD,
$9 as COV_TYPE_CD,
$10 as PLCY_NBR,
$11 as PLCY_EFF_DT,
$12 as PLCY_EXP_DT,
$13 as PLCY_TERM,
$14 as ACCTNG_MO,
$15 as ACCTNG_YR,
$16 as POOL_CD,
$17 as REINSUR_CD,
$18 as TOT_PREM_AMT,
$19 as MONETARY_AMT,
$20 as LEDGER,
$21 as ACCT_NBR,
$22 as GL_DSTR_STATUS,
$23 as DEPT_ID,
$24 as PROJ_ID,
$25 as ALF_ACCT_ID,
$26 as ECTL_BATCH_ID,
$27 as ECTL_ORIG_INS_TS,
$28 as ECTL_MODIFY_TS,
$29 as ECTL_SRC_ID,
$30 as ECTL_SRC_INST_ID,
$31 as ECTL_PRGM_ID,
$32 as ECTL_TXN_CD,
$33 as ECTL_START_DATE,
$34 as ECTL_END_DATE,
$35 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 

MO_ID,

T1.CMPY_CD,

T1.ST_CD,SVC_NBR,AGNT_NBR,CMPY_TYPE_CD,C.LOB_ROLLUP LOB_CD,T1.PRODUCT_CD,

COV_TYPE_CD,PLCY_NBR,PLCY_EFF_DT,PLCY_EXP_DT,PLCY_TERM,ACCTNG_MO,ACCTNG_YR,POOL_CD,REINSUR_CD,TOT_PRM_AMT,

MONETARY_AMOUNT,LEDGER,ACCT_NBR,GL_DISTRIB_STATUS,DEPT_ID,PROJ_ID,ALF_ACCT_ID,T1.ECTL_BATCH_ID,T1.ECTL_ORIG_INS_TS,T1.ECTL_MODIFY_TS,T1.ECTL_SRC_ID,

T1.ECTL_SRC_INST_ID,T1.ECTL_PRGM_ID,T1.ECTL_TXN_CD,T1.ECTL_START_DATE,T1.ECTL_END_DATE

FROM 

(SELECT	

(A.FISCAL_YEAR*100+A.ACCOUNTING_PERIOD) MO_ID,

SUBSTR(TRIM(A.BUSINESS_UNIT),1,3) CMPY_CD, 

TRIM(A.CHARTFIELD1) ST_CD, 

CASE WHEN TRIM(A.ALF_SERV_CTR_NBR) BETWEEN ''0'' AND ''9999999999999999'' THEN CAST(CAST(A.ALF_SERV_CTR_NBR  AS INTEGER) AS VARCHAR(20)) ELSE TRIM(A.ALF_SERV_CTR_NBR) END SVC_NBR, 

CASE WHEN TRIM(A.ALF_AGENT_NBR) BETWEEN ''0'' AND ''9999999999999999'' THEN CAST(CAST(A.ALF_AGENT_NBR  AS INTEGER) AS VARCHAR(20)) ELSE TRIM(A.ALF_AGENT_NBR) END AGNT_NBR, 

TRIM(A.ALF_COMPANY_CD) CMPY_TYPE_CD, 

CASE WHEN (TRIM(A.PRODUCT) IS NULL OR TRIM(A.PRODUCT) = '''') THEN ''A00000'' ELSE 

(CASE WHEN TRIM(A.PRODUCT) =''NO_PRD'' THEN (CASE WHEN TRIM(A.ALF_POL_PREFIX) IN (''G'',''N'') THEN ''A00000'' ELSE 

(CASE WHEN TRIM(A.ALF_POL_PREFIX) =''B'' THEN ''C00001'' ELSE (CASE WHEN POSITION('' '' IN CAST(A.ALF_POL_PREFIX AS CHAR(6))) =2 THEN TRIM(A.ALF_POL_PREFIX)||''00000'' ELSE 

TRIM(A.ALF_POL_PREFIX)||''0000'' END) END) END) ELSE TRIM(A.PRODUCT) END) END AS PRODUCT_CD,

TRIM(A.ALF_COV_TYPE15) COV_TYPE_CD,

TRIM(A.ALF_POL_PREFIX)||CAST(TRIM(A.ALF_POL_NUMBER) AS VARCHAR(10)) PLCY_NBR,		

A.ALF_POL_EFF_DATE PLCY_EFF_DT, 

A.ALF_POL_EXP_DATE PLCY_EXP_DT,

NULL AS PLCY_TERM,

A.ACCOUNTING_PERIOD ACCTNG_MO, 

A.FISCAL_YEAR ACCTNG_YR, 

TRIM(A.CHARTFIELD2) POOL_CD, 

TRIM(A.CHARTFIELD3) REINSUR_CD, 

0 AS TOT_PRM_AMT,

SUM(A.MONETARY_AMOUNT * B.MULTIPLY_FACTOR) MONETARY_AMOUNT, 

TRIM(A.LEDGER) LEDGER, 

TRIM(A.ACCOUNT_NBR) ACCT_NBR, 

TRIM(A.GL_DISTRIB_STATUS) GL_DISTRIB_STATUS, 

TRIM(A.DEPTID) DEPT_ID, 

TRIM(A.PROJECT_ID) PROJ_ID,

NULL AS ALF_ACCT_ID,

D.ECTL_BATCH_ID ECTL_BATCH_ID,

CURRENT_TIMESTAMP ECTL_ORIG_INS_TS,

CURRENT_TIMESTAMP ECTL_MODIFY_TS ,               

E.ECTL_SRC_ID ECTL_SRC_ID,

E.ECTL_SRC_INST_ID ECTL_SRC_INST_ID,

E.ECTL_PRGM_ID ECTL_PRGM_ID,

''NEW'' ECTL_TXN_CD,

CAST(D.ECTL_BATCH_START_TS AS DATE) ECTL_START_DATE,

''9999-12-31'' ECTL_END_DATE

FROM 	

DB_T_STAG_FIN_PROD.STG_FIN_LUE A INNER JOIN DB_T_SHRD_FIN_PROD.REPOS_FIN_ACCT_NBR_LKUP B 

ON A.ACCOUNT_NBR = B.ACCT_NBR AND B.REPOS_CD = ''LUE'' INNER JOIN

(SELECT * FROM	DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 1 AND ECTL_ACTIVE_IND = ''Y'') D ON 1=1 INNER JOIN 

(SELECT	* FROM	DB_T_CTRL_FIN_PROD.ECTL_PRGM_INFO WHERE ECTL_PRGM_NM  = ''bteq_LUE_FIN_PREMIUM_TXN'') E ON 1=1 

WHERE A.GL_DISTRIB_STATUS=''D'' 

GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33) T1

LEFT OUTER JOIN DB_T_CORE_FIN_PROD.FIN_PRODUCT_HIER C ON 

T1.PRODUCT_CD = C.PRODUCT_CD
) SRC
)
);


-- Component EXP_FIN_PREMIUM_TXN, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXP_FIN_PREMIUM_TXN AS
(
SELECT
SQ_FIN_LOSS_TXN.MO_ID as MO_ID,
SQ_FIN_LOSS_TXN.CMPY_CD as CMPY_CD,
SQ_FIN_LOSS_TXN.ST_CD as ST_CD,
SQ_FIN_LOSS_TXN.SVC_NBR as SVC_NBR,
SQ_FIN_LOSS_TXN.AGNT_NBR as AGNT_NBR,
SQ_FIN_LOSS_TXN.CMPY_TYPE_CD as CMPY_TYPE_CD,
SQ_FIN_LOSS_TXN.LOB_CD as LOB_CD,
SQ_FIN_LOSS_TXN.PRODUCT_CD as PRODUCT_CD,
SQ_FIN_LOSS_TXN.COV_TYPE_CD as COV_TYPE_CD,
SQ_FIN_LOSS_TXN.PLCY_NBR as PLCY_NBR,
SQ_FIN_LOSS_TXN.PLCY_EFF_DT as PLCY_EFF_DT,
SQ_FIN_LOSS_TXN.PLCY_EXP_DT as PLCY_EXP_DT,
SQ_FIN_LOSS_TXN.PLCY_TERM as PLCY_TERM,
SQ_FIN_LOSS_TXN.ACCTNG_MO as ACCTNG_MO,
SQ_FIN_LOSS_TXN.ACCTNG_YR as ACCTNG_YR,
SQ_FIN_LOSS_TXN.POOL_CD as POOL_CD,
SQ_FIN_LOSS_TXN.REINSUR_CD as REINSUR_CD,
SQ_FIN_LOSS_TXN.TOT_PREM_AMT as TOT_PREM_AMT,
SQ_FIN_LOSS_TXN.MONETARY_AMT as MONETARY_AMT,
SQ_FIN_LOSS_TXN.LEDGER as LEDGER,
SQ_FIN_LOSS_TXN.ACCT_NBR as ACCT_NBR,
SQ_FIN_LOSS_TXN.GL_DSTR_STATUS as GL_DSTR_STATUS,
SQ_FIN_LOSS_TXN.DEPT_ID as DEPT_ID,
SQ_FIN_LOSS_TXN.PROJ_ID as PROJ_ID,
SQ_FIN_LOSS_TXN.ALF_ACCT_ID as ALF_ACCT_ID,
SQ_FIN_LOSS_TXN.ECTL_BATCH_ID as ECTL_BATCH_ID,
SQ_FIN_LOSS_TXN.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
SQ_FIN_LOSS_TXN.ECTL_MODIFY_TS as ECTL_MODIFY_TS,
SQ_FIN_LOSS_TXN.ECTL_SRC_ID as ECTL_SRC_ID,
SQ_FIN_LOSS_TXN.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
SQ_FIN_LOSS_TXN.ECTL_PRGM_ID as ECTL_PRGM_ID,
SQ_FIN_LOSS_TXN.ECTL_TXN_CD as ECTL_TXN_CD,
SQ_FIN_LOSS_TXN.ECTL_START_DATE as ECTL_START_DATE,
SQ_FIN_LOSS_TXN.ECTL_END_DATE as ECTL_END_DATE,
SQ_FIN_LOSS_TXN.source_record_id
FROM
SQ_FIN_LOSS_TXN
);


-- Component FIN_PREMIUM_TXN1, Type TARGET 
INSERT INTO DB_T_CORE_FIN_PROD.FIN_PREMIUM_TXN
(
MO_ID,
CMPY_CD,
ST_CD,
SVC_NBR,
AGNT_NBR,
CMPY_TYPE_CD,
LOB_CD,
PRODUCT_CD,
COV_TYPE_CD,
PLCY_NBR,
PLCY_EFF_DT,
PLCY_EXP_DT,
PLCY_TERM,
ACCTNG_MO,
ACCTNG_YR,
POOL_CD,
REINSUR_CD,
TOT_PREM_AMT,
MONETARY_AMT,
LEDGER,
ACCT_NBR,
GL_DSTR_STATUS,
DEPT_ID,
PROJ_ID,
ALF_ACCT_ID,
ECTL_BATCH_ID,
ECTL_ORIG_INS_TS,
ECTL_MODIFY_TS,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_PRGM_ID,
ECTL_TXN_CD,
ECTL_START_DATE,
ECTL_END_DATE
)
SELECT
EXP_FIN_PREMIUM_TXN.MO_ID as MO_ID,
EXP_FIN_PREMIUM_TXN.CMPY_CD as CMPY_CD,
EXP_FIN_PREMIUM_TXN.ST_CD as ST_CD,
EXP_FIN_PREMIUM_TXN.SVC_NBR as SVC_NBR,
EXP_FIN_PREMIUM_TXN.AGNT_NBR as AGNT_NBR,
EXP_FIN_PREMIUM_TXN.CMPY_TYPE_CD as CMPY_TYPE_CD,
EXP_FIN_PREMIUM_TXN.LOB_CD as LOB_CD,
EXP_FIN_PREMIUM_TXN.PRODUCT_CD as PRODUCT_CD,
EXP_FIN_PREMIUM_TXN.COV_TYPE_CD as COV_TYPE_CD,
EXP_FIN_PREMIUM_TXN.PLCY_NBR as PLCY_NBR,
EXP_FIN_PREMIUM_TXN.PLCY_EFF_DT as PLCY_EFF_DT,
EXP_FIN_PREMIUM_TXN.PLCY_EXP_DT as PLCY_EXP_DT,
EXP_FIN_PREMIUM_TXN.PLCY_TERM as PLCY_TERM,
EXP_FIN_PREMIUM_TXN.ACCTNG_MO as ACCTNG_MO,
EXP_FIN_PREMIUM_TXN.ACCTNG_YR as ACCTNG_YR,
EXP_FIN_PREMIUM_TXN.POOL_CD as POOL_CD,
EXP_FIN_PREMIUM_TXN.REINSUR_CD as REINSUR_CD,
EXP_FIN_PREMIUM_TXN.TOT_PREM_AMT as TOT_PREM_AMT,
EXP_FIN_PREMIUM_TXN.MONETARY_AMT as MONETARY_AMT,
EXP_FIN_PREMIUM_TXN.LEDGER as LEDGER,
EXP_FIN_PREMIUM_TXN.ACCT_NBR as ACCT_NBR,
EXP_FIN_PREMIUM_TXN.GL_DSTR_STATUS as GL_DSTR_STATUS,
EXP_FIN_PREMIUM_TXN.DEPT_ID as DEPT_ID,
EXP_FIN_PREMIUM_TXN.PROJ_ID as PROJ_ID,
EXP_FIN_PREMIUM_TXN.ALF_ACCT_ID as ALF_ACCT_ID,
EXP_FIN_PREMIUM_TXN.ECTL_BATCH_ID as ECTL_BATCH_ID,
EXP_FIN_PREMIUM_TXN.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
EXP_FIN_PREMIUM_TXN.ECTL_MODIFY_TS as ECTL_MODIFY_TS,
EXP_FIN_PREMIUM_TXN.ECTL_SRC_ID as ECTL_SRC_ID,
EXP_FIN_PREMIUM_TXN.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
EXP_FIN_PREMIUM_TXN.ECTL_PRGM_ID as ECTL_PRGM_ID,
EXP_FIN_PREMIUM_TXN.ECTL_TXN_CD as ECTL_TXN_CD,
EXP_FIN_PREMIUM_TXN.ECTL_START_DATE as ECTL_START_DATE,
EXP_FIN_PREMIUM_TXN.ECTL_END_DATE as ECTL_END_DATE
FROM
EXP_FIN_PREMIUM_TXN;


END; ';