-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STG_FIN_ACCT_NBR("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component sq_PS_ALF_GL_ACCOUNT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_PS_ALF_GL_ACCOUNT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SETID,
$2 as ACCOUNT_CD,
$3 as EFFDT,
$4 as DESCR,
$5 as ACCOUNT_TYPE,
$6 as EFF_STATUS,
$7 as DESCRSHORT,
$8 as BUDGETARY_ONLY,
$9 as BUDG_OVERRIDE_ACCT,
$10 as ACCOUNTING_OWNER,
$11 as AB_ACCOUNT_SW,
$12 as GL_ACCOUNT_SW,
$13 as PF_ACCOUNT_SW,
$14 as UNIT_OF_MEASURE,
$15 as OPEN_ITEM,
$16 as OPEN_ITEM_DESCR,
$17 as OPEN_ITEM_EDIT_REC,
$18 as OPEN_ITEM_EDIT_FLD,
$19 as OPEN_ITEM_PROMPT,
$20 as OPEN_ITEM_TOL_AMT,
$21 as CURRENCY_CD,
$22 as STATISTICS_ACCOUNT,
$23 as BALANCE_FWD_SW,
$24 as CONTROL_FLAG,
$25 as BOOK_CODE,
$26 as BAL_SHEET_IND,
$27 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 

TRIM(PS_ALF_GL_ACCOUNT.SETID), 

TRIM(PS_ALF_GL_ACCOUNT.ACCOUNT_CD), 

PS_ALF_GL_ACCOUNT.EFFDT, 

TRIM(PS_ALF_GL_ACCOUNT.DESCR), 

TRIM(PS_ALF_GL_ACCOUNT.ACCOUNT_TYPE), 

TRIM(PS_ALF_GL_ACCOUNT.EFF_STATUS), 

TRIM(PS_ALF_GL_ACCOUNT.DESCRSHORT), 

TRIM(PS_ALF_GL_ACCOUNT.BUDGETARY_ONLY), 

TRIM(PS_ALF_GL_ACCOUNT.BUDG_OVERRIDE_ACCT), 

TRIM(PS_ALF_GL_ACCOUNT.ACCOUNTING_OWNER), 

TRIM(PS_ALF_GL_ACCOUNT.AB_ACCOUNT_SW), 

TRIM(PS_ALF_GL_ACCOUNT.GL_ACCOUNT_SW), 

TRIM(PS_ALF_GL_ACCOUNT.PF_ACCOUNT_SW), 

TRIM(PS_ALF_GL_ACCOUNT.UNIT_OF_MEASURE), 

TRIM(PS_ALF_GL_ACCOUNT.OPEN_ITEM), 

TRIM(PS_ALF_GL_ACCOUNT.OPEN_ITEM_DESCR), 

TRIM(PS_ALF_GL_ACCOUNT.OPEN_ITEM_EDIT_REC), 

TRIM(PS_ALF_GL_ACCOUNT.OPEN_ITEM_EDIT_FLD), 

TRIM(PS_ALF_GL_ACCOUNT.OPEN_ITEM_PROMPT), 

PS_ALF_GL_ACCOUNT.OPEN_ITEM_TOL_AMT, 

TRIM(PS_ALF_GL_ACCOUNT.CURRENCY_CD), 

TRIM(PS_ALF_GL_ACCOUNT.STATISTICS_ACCOUNT), 

TRIM(PS_ALF_GL_ACCOUNT.BALANCE_FWD_SW), 

TRIM(PS_ALF_GL_ACCOUNT.CONTROL_FLAG), 

TRIM(PS_ALF_GL_ACCOUNT.BOOK_CODE), 

TRIM(PS_ALF_GL_ACCOUNT.BAL_SHEET_IND)

FROM

 DB_T_STAG_FIN_PROD.PS_ALF_GL_ACCOUNT
) SRC
)
);


-- Component STG_FIN_ACCT_NBR, Type TARGET 
INSERT INTO DB_T_STAG_FIN_PROD.STG_FIN_ACCT_NBR
(
SETID,
ACCOUNT_CD,
EFFDT,
DESCR,
ACCOUNT_TYPE,
EFF_STATUS,
DESCRSHORT,
BUDGETARY_ONLY,
BUDG_OVERRIDE_ACCT,
ACCOUNTING_OWNER,
AB_ACCOUNT_SW,
GL_ACCOUNT_SW,
PF_ACCOUNT_SW,
UNIT_OF_MEASURE,
OPEN_ITEM,
OPEN_ITEM_DESCR,
OPEN_ITEM_EDIT_REC,
OPEN_ITEM_EDIT_FLD,
OPEN_ITEM_PROMPT,
OPEN_ITEM_TOL_AMT,
CURRENCY_CD,
STATISTICS_ACCOUNT,
BALANCE_FWD_SW,
CONTROL_FLAG,
BOOK_CODE,
BAL_SHEET_IND
)
SELECT
sq_PS_ALF_GL_ACCOUNT.SETID as SETID,
sq_PS_ALF_GL_ACCOUNT.ACCOUNT_CD as ACCOUNT_CD,
sq_PS_ALF_GL_ACCOUNT.EFFDT as EFFDT,
sq_PS_ALF_GL_ACCOUNT.DESCR as DESCR,
sq_PS_ALF_GL_ACCOUNT.ACCOUNT_TYPE as ACCOUNT_TYPE,
sq_PS_ALF_GL_ACCOUNT.EFF_STATUS as EFF_STATUS,
sq_PS_ALF_GL_ACCOUNT.DESCRSHORT as DESCRSHORT,
sq_PS_ALF_GL_ACCOUNT.BUDGETARY_ONLY as BUDGETARY_ONLY,
sq_PS_ALF_GL_ACCOUNT.BUDG_OVERRIDE_ACCT as BUDG_OVERRIDE_ACCT,
sq_PS_ALF_GL_ACCOUNT.ACCOUNTING_OWNER as ACCOUNTING_OWNER,
sq_PS_ALF_GL_ACCOUNT.AB_ACCOUNT_SW as AB_ACCOUNT_SW,
sq_PS_ALF_GL_ACCOUNT.GL_ACCOUNT_SW as GL_ACCOUNT_SW,
sq_PS_ALF_GL_ACCOUNT.PF_ACCOUNT_SW as PF_ACCOUNT_SW,
sq_PS_ALF_GL_ACCOUNT.UNIT_OF_MEASURE as UNIT_OF_MEASURE,
sq_PS_ALF_GL_ACCOUNT.OPEN_ITEM as OPEN_ITEM,
sq_PS_ALF_GL_ACCOUNT.OPEN_ITEM_DESCR as OPEN_ITEM_DESCR,
sq_PS_ALF_GL_ACCOUNT.OPEN_ITEM_EDIT_REC as OPEN_ITEM_EDIT_REC,
sq_PS_ALF_GL_ACCOUNT.OPEN_ITEM_EDIT_FLD as OPEN_ITEM_EDIT_FLD,
sq_PS_ALF_GL_ACCOUNT.OPEN_ITEM_PROMPT as OPEN_ITEM_PROMPT,
sq_PS_ALF_GL_ACCOUNT.OPEN_ITEM_TOL_AMT as OPEN_ITEM_TOL_AMT,
sq_PS_ALF_GL_ACCOUNT.CURRENCY_CD as CURRENCY_CD,
sq_PS_ALF_GL_ACCOUNT.STATISTICS_ACCOUNT as STATISTICS_ACCOUNT,
sq_PS_ALF_GL_ACCOUNT.BALANCE_FWD_SW as BALANCE_FWD_SW,
sq_PS_ALF_GL_ACCOUNT.CONTROL_FLAG as CONTROL_FLAG,
sq_PS_ALF_GL_ACCOUNT.BOOK_CODE as BOOK_CODE,
sq_PS_ALF_GL_ACCOUNT.BAL_SHEET_IND as BAL_SHEET_IND
FROM
sq_PS_ALF_GL_ACCOUNT;


END; ';