-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_CLM_DTL_ECTL_BATCH_INFO_UPD("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
declare
BATCH_ACTIVE_IND boolean;
ACT_PROJ_ID string;

BEGIN 
BATCH_ACTIVE_IND := true;
ACT_PROJ_ID := ''TEST'';

-- Component sq_ECTL_BATCH_INFO, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_ECTL_BATCH_INFO AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_BATCH_ID,
$2 as ECTL_PROJ_ID,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT ECTL_BATCH_INFO.ECTL_BATCH_ID, ECTL_BATCH_INFO.ECTL_PROJ_ID 

FROM

 DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO

WHERE ECTL_BATCH_INFO.ECTL_ACTIVE_IND =:BATCH_ACTIVE_IND

AND ECTL_BATCH_INFO.ECTL_PROJ_ID=:ACT_PROJ_ID
) SRC
)
);


-- Component exp_UPD_TS_ACTIVE_IND, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_UPD_TS_ACTIVE_IND AS
(
SELECT
sq_ECTL_BATCH_INFO.ECTL_BATCH_ID as ECTL_BATCH_ID,
sq_ECTL_BATCH_INFO.ECTL_PROJ_ID as ECTL_PROJ_ID,
CURRENT_TIMESTAMP as out_ECTL_BATCH_END_TS,
''N'' as out_ECTL_ACTIVE_IND,
sq_ECTL_BATCH_INFO.source_record_id
FROM
sq_ECTL_BATCH_INFO
);


-- Component upd_ECTL_BATCH_INFO, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_ECTL_BATCH_INFO AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
exp_UPD_TS_ACTIVE_IND.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_UPD_TS_ACTIVE_IND.ECTL_PROJ_ID as ECTL_PROJ_ID,
exp_UPD_TS_ACTIVE_IND.out_ECTL_BATCH_END_TS as ECTL_BATCH_END_TS,
exp_UPD_TS_ACTIVE_IND.out_ECTL_ACTIVE_IND as ECTL_ACTIVE_IND,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_UPD_TS_ACTIVE_IND
);


-- Component ECTL_BATCH_INFO_UPD, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO
USING upd_ECTL_BATCH_INFO
ON (ECTL_BATCH_INFO.ECTL_BATCH_ID = upd_ECTL_BATCH_INFO.ECTL_BATCH_ID AND ECTL_BATCH_INFO.ECTL_PROJ_ID = upd_ECTL_BATCH_INFO.ECTL_PROJ_ID)
WHEN MATCHED THEN UPDATE SET
ECTL_BATCH_END_TS = upd_ECTL_BATCH_INFO.ECTL_BATCH_END_TS, ECTL_ACTIVE_IND = upd_ECTL_BATCH_INFO.ECTL_ACTIVE_IND;


END; ';