-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BAL_ANALYTICS_TABLES("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component sq_STG_BILL_PMTS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_BILL_PMTS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_BATCH_ID,
$2 as MO_ID,
$3 as CALC_SRC,
$4 as TBL_NM,
$5 as METRIC_NM,
$6 as METRIC_CNT,
$7 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
with ECTL_AUTO_DATES as(

SELECT accounting_yr*100+accounting_mo MO_ID , CAST(SUBSTR(TO_DATE,1,4)||''-''||SUBSTR(TO_DATE,6,2)||''-01'' AS DATE) as CAL_END_DATE,

ADD_MONTHS(CAL_END_DATE,1)-1 as CAL_START_DATE   from DB_T_CTRL_PROD.ECTL_MISPREM_HEADER WHERE accounting_yr*100+accounting_mo =:WF_MONTH_ID



)



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''LIFE_POLICY_SUMM'' AS TBL_NM

,''ING_POL_LIST_PLCY_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT B.MO_ID AS MO_ID,COUNT(DISTINCT POL_ID)AS PLCY_CNT

FROM  DB_T_CORE_AN_PROD.LIFE_POLICY_SUMM A, ECTL_AUTO_DATES B 

WHERE A.MO_ID = B.MO_ID AND POL_TYPE=''I'' GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''LIFE_POLICY_SUMM'' AS TBL_NM

,''LIFEPOLS_PLCY_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT B.MO_ID AS MO_ID,COUNT(DISTINCT POL_ID)AS PLCY_CNT

FROM  DB_T_CORE_AN_PROD.LIFE_POLICY_SUMM A, ECTL_AUTO_DATES B 

WHERE A.MO_ID = B.MO_ID AND POL_TYPE=''L'' GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



union



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''MEMB_CUST'' AS TBL_NM

,''PORT_MBR_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,SUM(PORT) AS PLCY_CNT

FROM DB_T_CORE_AN_PROD.MEMB_CUST A, ECTL_AUTO_DATES C 

WHERE MEMBER_TYPE=''MBR'' AND A.MO_ID=C.MO_ID GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''MEMB_CUST'' AS TBL_NM

,''PORT_CST_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,SUM(PORT) AS PLCY_CNT

FROM DB_T_CORE_AN_PROD.MEMB_CUST A, ECTL_AUTO_DATES C 

WHERE MEMBER_TYPE=''CST'' AND A.MO_ID=C.MO_ID GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''MEMB_CUST'' AS TBL_NM

,''SMLN_MBR_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,SUM(SMLN) AS PLCY_CNT

FROM DB_T_CORE_AN_PROD.MEMB_CUST A, ECTL_AUTO_DATES C 

WHERE MEMBER_TYPE=''MBR'' AND A.MO_ID=C.MO_ID GROUP BY 1 ) D

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''MEMB_CUST'' AS TBL_NM

,''FGM_CST_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,SUM(FGM) AS PLCY_CNT

FROM DB_T_CORE_AN_PROD.MEMB_CUST A, ECTL_AUTO_DATES C 

WHERE MEMBER_TYPE=''CST'' AND A.MO_ID=C.MO_ID GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''MEMB_CUST'' AS TBL_NM

,''FIRE_MBR_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,SUM(FIRE) AS PLCY_CNT

FROM DB_T_CORE_AN_PROD.MEMB_CUST A, ECTL_AUTO_DATES C 

WHERE MEMBER_TYPE=''MBR'' AND A.MO_ID=C.MO_ID GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION





SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''MEMB_CUST'' AS TBL_NM

,''FIRE_CST_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,SUM(FIRE) AS PLCY_CNT

FROM DB_T_CORE_AN_PROD.MEMB_CUST A, ECTL_AUTO_DATES C 

WHERE MEMBER_TYPE=''CST'' AND A.MO_ID=C.MO_ID GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''MEMB_CUST'' AS TBL_NM

,''FARM_MBR_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,SUM(FARM) AS PLCY_CNT

FROM DB_T_CORE_AN_PROD.MEMB_CUST A, ECTL_AUTO_DATES C 

WHERE MEMBER_TYPE=''MBR'' AND A.MO_ID=C.MO_ID GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''MEMB_CUST'' AS TBL_NM

,''ASIC_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,SUM(ASIC) AS PLCY_CNT

FROM DB_T_CORE_AN_PROD.MEMB_CUST A, ECTL_AUTO_DATES C 

WHERE A.MO_ID=C.MO_ID GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''MEMB_CUST'' AS TBL_NM

,''LIFE_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,SUM(LIFE) AS PLCY_CNT

FROM DB_T_CORE_AN_PROD.MEMB_CUST A, ECTL_AUTO_DATES C 

WHERE A.MO_ID=C.MO_ID GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''MEMB_CUST'' AS TBL_NM

,''EX_POLS_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,SUM(AUTO) AS PLCY_CNT

FROM DB_T_CORE_AN_PROD.MEMB_CUST A, ECTL_AUTO_DATES C 

WHERE A.MO_ID=C.MO_ID GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''MEMB_CUST'' AS TBL_NM

,''EXCD_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,SUM(VEH) AS PLCY_CNT

FROM DB_T_CORE_AN_PROD.MEMB_CUST A, ECTL_AUTO_DATES C 

WHERE A.MO_ID=C.MO_ID GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

C.ECTL_BATCH_ID,

MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''BILL_PMTS'' AS TBL_NM

,''DISTINCT POLICIES'' AS METRIC_NM

,B.POL_NBR

FROM

(SELECT B.MO_ID AS MO_ID,COUNT(DISTINCT POL_NBR)AS POL_NBR FROM DB_T_CORE_PROD.BILL_PMTS A, 

ECTL_AUTO_DATES  B

 WHERE CAST(BIL_ACY_TS AS DATE) BETWEEN B.CAL_END_DATE AND B.CAL_START_DATE 

and LATE_PAY_IND in (''Y'',''X'',''N'') GROUP BY 1   ) B

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') C

ON 1=1



UNION



SELECT 

C.ECTL_BATCH_ID,

MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''ACCTSTATS'' AS TBL_NM

,''DISTINCT POLICIES'' AS METRIC_NM

,B.PLCY_NBR

FROM

(SELECT B.MO_ID AS MO_ID,COUNT(DISTINCT PLCY_NBR)AS PLCY_NBR FROM DB_T_CORE_DM_PROD.ACCTSTATS A,ECTL_AUTO_DATES B

WHERE	B.MO_ID BETWEEN EXTRACT(YEAR FROM EFF_DT)*100 + EXTRACT(MONTH FROM EFF_DT) AND EXTRACT(YEAR FROM EXP_DT)*100 + EXTRACT(MONTH FROM EXP_DT) 

GROUP BY 1) B

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') C

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''ING_POL_LIST'' AS TBL_NM

,''PLCY_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,COUNT(DISTINCT POL_ID)AS PLCY_CNT

FROM DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST A, ECTL_AUTO_DATES C 

WHERE A.POL_STATUS IN (''1'',''2'',''3'',''4'') AND A.CHG_EFF_DT <=C.CAL_END_DATE AND A.CHG_EXP_DT>=C.CAL_START_DATE GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''LIFEPOLS'' AS TBL_NM

,''PLCY_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,COUNT(DISTINCT SC_POLICY_NUM)AS PLCY_CNT

FROM DB_T_CORE_MEMBXREF_PROD.LIFEPOLS A, ECTL_AUTO_DATES C 

WHERE A.LF_STATUS IN (''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'') AND A.CHG_EFF_DT <=C.CAL_END_DATE AND A.CHG_EXP_DT>=C.CAL_START_DATE GROUP BY 1 ) D



LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1

/* EIM-50197 */
/*UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''ASICPOLS'' AS TBL_NM

,''PLCY_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT C.MO_ID AS MO_ID,COUNT(DISTINCT SC_POLICY_NUM)AS PLCY_CNT

FROM DB_T_CORE_MEMBXREF_PROD.ASICPOLS A, ECTL_AUTO_DATES C 

WHERE A.PC_STATUS IN (1,2,3,4) AND C.CAL_END_DATE BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT GROUP BY 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1

*/

UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''STG_MULTILINE_POLSTAT'' AS TBL_NM

,''PORT_MBR_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT) MO_ID,COUNT(DISTINCT POL_NBR) PLCY_CNT

FROM DB_T_STAG_PROD.STG_MULTILINE_POLSTAT A,ECTL_AUTO_DATES C WHERE POL_NBR LIKE ''SC%'' AND STATUS<30

AND MEMBER_TYPE=''MBR'' AND STATE=''AL''  AND EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)=C.MO_ID GROUP by 1 ) D

LEFT OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''STG_MULTILINE_POLSTAT'' AS TBL_NM

,''PORT_CST_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT) MO_ID,COUNT(DISTINCT POL_NBR) PLCY_CNT

FROM DB_T_STAG_PROD.STG_MULTILINE_POLSTAT A,ECTL_AUTO_DATES C WHERE POL_NBR LIKE ''SC%'' AND STATUS<30

AND MEMBER_TYPE=''MBR'' AND DB_T_SHRD_PROD.STATE in (''GA'',''MS'') AND EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)=C.MO_ID GROUP by 1 ) D

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''STG_MULTILINE_POLSTAT'' AS TBL_NM

,''SMLN_MBR_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT) MO_ID,COUNT(DISTINCT POL_NBR) PLCY_CNT

FROM DB_T_STAG_PROD.STG_MULTILINE_POLSTAT A,ECTL_AUTO_DATES C WHERE (POL_NBR  LIKE ''SM%''  OR POL_NBR  LIKE ''SP%'' 

 OR POL_NBR  LIKE ''M%'' OR POL_NBR  LIKE ''CP%'' OR POL_NBR  LIKE ''GL%'' OR POL_NBR  LIKE ''WC%'' OR POL_NBR LIKE ''FC%'') AND STATUS<''30''

AND MEMBER_TYPE=''MBR'' AND STATE=''AL''  AND EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)=C.MO_ID GROUP by 1 ) D

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''STG_MULTILINE_POLSTAT'' AS TBL_NM

,''FGM_CST_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT) MO_ID,COUNT(DISTINCT POL_NBR) PLCY_CNT

FROM DB_T_STAG_PROD.STG_MULTILINE_POLSTAT A,ECTL_AUTO_DATES C WHERE (POL_NBR  LIKE ''SM%''  OR POL_NBR  LIKE ''SP%'' 

OR POL_NBR  LIKE ''M%'' OR POL_NBR  LIKE ''GL%'' OR POL_NBR  LIKE ''WC%'' OR POL_NBR LIKE ''FC%'') AND STATUS<''30''

AND MEMBER_TYPE=''CST'' AND DB_T_SHRD_PROD.STATE in (''MS'',''GA'')  AND EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)=C.MO_ID GROUP by 1) D

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''STG_MULTILINE_POLSTAT'' AS TBL_NM

,''FIRE_MBR_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT) MO_ID,COUNT(DISTINCT POL_NBR) PLCY_CNT

FROM DB_T_STAG_PROD.STG_MULTILINE_POLSTAT A,ECTL_AUTO_DATES C WHERE POL_NBR LIKE ''F0%''  AND STATUS<30

AND MEMBER_TYPE=''MBR'' AND STATE=''AL''   AND EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)=C.MO_ID GROUP by 1 ) D

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''STG_MULTILINE_POLSTAT'' AS TBL_NM

,''FIRE_CST_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT) MO_ID,COUNT(DISTINCT POL_NBR) PLCY_CNT

FROM DB_T_STAG_PROD.STG_MULTILINE_POLSTAT A,ECTL_AUTO_DATES C WHERE POL_NBR LIKE ''F0%''  AND STATUS<30

AND MEMBER_TYPE=''CST'' AND DB_T_SHRD_PROD.STATE in (''MS'',''GA'')   AND EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)=C.MO_ID GROUP by 1 ) D

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''STG_MULTILINE_POLSTAT'' AS TBL_NM

,''FARM_MBR_CNT'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT) MO_ID,COUNT(DISTINCT POL_NBR) PLCY_CNT

FROM DB_T_STAG_PROD.STG_MULTILINE_POLSTAT A,ECTL_AUTO_DATES C WHERE POL_NBR LIKE ''R%'' AND STATUS<30

AND MEMBER_TYPE=''MBR'' AND STATE=''AL''  AND EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)=C.MO_ID GROUP by 1) D

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''CLV_POL_VEH_LIST'' AS TBL_NM

,''VEHICLE DB_T_PROD_COMN.PREMIUM AMT'' AS METRIC_NM

,D.BAL_AMT

FROM

(SELECT  C.MO_ID MO_ID,SUM(TOT_PRM_AMT) BAL_AMT FROM DB_T_CORE_AN_PROD.VEHICLE_PREMIUM A,DB_T_STAG_MEMBXREF_PROD.CLV_POL_VEH_LIST B,

ECTL_AUTO_DATES C WHERE A.PLCY_NBR = B.POL_NBR AND

A.UNIT_REF_NBR = B.UNIT_RFR_NBR AND A.MO_ID=C.MO_ID GROUP by 1) D

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E 

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''VEHICLE_PREMIUM'' AS TBL_NM

,''VEHICLE DB_T_PROD_COMN.PREMIUM AMT'' AS METRIC_NM

,D.CLV_PREM_AMT 

FROM

(SELECT  A.MO_ID MO_ID,SUM(PREM_AMT) CLV_PREM_AMT FROM DB_T_CORE_AN_PROD.VEHICLE_PREMIUM A,DB_T_STAG_MEMBXREF_PROD.CLV_POL_VEH_LIST B,

ECTL_AUTO_DATES C WHERE A.PLCY_NBR = B.POL_NBR AND

A.UNIT_REF_NBR = B.UNIT_RFR_NBR AND A.MO_ID=C.MO_ID GROUP by 1) D

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,MO_ID AS MO_ID

,''ANALYTICS'' AS CALC_SRC

,''ASIC_POLICY_SUMM'' AS TBL_NM

,''DISTINCT POLICIES'' AS METRIC_NM

,D.PLCY_CNT

FROM

(SELECT A.MO_ID AS MO_ID,COUNT(DISTINCT PLCY_NBR)AS PLCY_CNT

FROM DB_T_CORE_AN_PROD.ASIC_POLICY_SUMM A,ECTL_AUTO_DATES C

WHERE A.MO_ID=C.MO_ID GROUP BY 1) D

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,B.MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''GW_TABLES'' AS TBL_NM

,''EX_POLS_CNT'' AS METRIC_NM

,D.AUTO

FROM

(SELECT

SUM(CASE WHEN INSRNC_LOB_TYPE_CD =''PA''  THEN 1 ELSE 0 END)  AUTO

 FROM 

(SELECT DISTINCT A.HOST_AGMT_NUM PLCY_NUM ,D.INSRNC_LOB_TYPE_CD,AGMT_STS_CD,

CASE WHEN A.MODL_EFF_DTTM > A.MODL_CRTN_DTTM THEN A.MODL_EFF_DTTM 

ELSE A.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM,A.AGMT_ID , A.AGMT_OPN_DTTM,A.TRANS_STRT_DTTM, A.TRANS_END_DTTM,MBRSHP_TYPE_CD,MBRSHP_NUM,

A.AGMT_PLND_EXPN_DTTM

FROM  DB_T_PROD_CORE.AGMT AS A JOIN ECTL_AUTO_DATES ON 1=1

JOIN  DB_T_PROD_CORE.AGMT TRM 

ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM 

AND    TRM.AGMT_TYPE_CD=''POLTRM''   AND CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

BETWEEN TRM.AGMT_EFF_DTTM AND TRM.AGMT_PLND_EXPN_DTTM 

JOIN DB_T_PROD_CORE.AGMT_STS  AS AS1  ON  TRM.AGMT_ID=AS1.AGMT_ID AND AS1.AGMT_STS_STRT_DTTM <= CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

AND NEW_AGMT_EFF_DTTM < CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond''

AND A.AGMT_TYPE_CD = ''PPV'' AND AGMT_STS_CD <> ''CNFRMDDT'' 

LEFT JOIN DB_T_PROD_CORE.AGMT_PROD AP ON A.AGMT_ID=AP.AGMT_ID

 LEFT JOIN DB_T_PROD_CORE.AGMT_MBRSHP  AS AM ON A.AGMT_ID=AM.AGMT_ID

LEFT JOIN DB_T_PROD_CORE.MBRSHP   AS M ON M.MBRSHP_ID=AM.MBRSHP_ID

JOIN DB_T_PROD_CORE.PROD P ON AP.PROD_ID=P.PROD_ID

JOIN DB_T_PROD_CORE.INSRNC_LOB_TYPE D ON D.INSRNC_LOB_TYPE_CD=P.INSRNC_LOB_TYPE_CD

QUALIFY ROW_NUMBER() OVER(PARTITION BY A.HOST_AGMT_NUM ORDER BY  A.MODL_CRTN_DTTM DESC,A.MODL_EFF_DTTM DESC, AS1.AGMT_STS_STRT_DTTM DESC) = 1 AND AGMT_STS_CD = ''INFORCE''

) AS A 

 ) D JOIN ECTL_AUTO_DATES  B ON 1=1

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,B.MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''GW_TABLES'' AS TBL_NM

,''FIRE_MBR_CNT'' AS METRIC_NM

,DB_T_STAG_MEMBXREF_PROD.FIRE

FROM

(SELECT

SUM(CASE WHEN INSRNC_LOB_TYPE_CD LIKE ''SF%''  THEN 1 ELSE 0 END)  FIRE

 FROM 

(SELECT DISTINCT A.HOST_AGMT_NUM PLCY_NUM ,D.INSRNC_LOB_TYPE_CD,AGMT_STS_CD,

CASE WHEN A.MODL_EFF_DTTM > A.MODL_CRTN_DTTM THEN A.MODL_EFF_DTTM 

ELSE A.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM,A.AGMT_ID , A.AGMT_OPN_DTTM,A.TRANS_STRT_DTTM, A.TRANS_END_DTTM,MBRSHP_TYPE_CD,MBRSHP_NUM,

A.AGMT_PLND_EXPN_DTTM

FROM  DB_T_PROD_CORE.AGMT AS A JOIN ECTL_AUTO_DATES ON 1=1

JOIN  DB_T_PROD_CORE.AGMT TRM 

ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM 

AND    TRM.AGMT_TYPE_CD=''POLTRM''   AND CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

BETWEEN TRM.AGMT_EFF_DTTM AND TRM.AGMT_PLND_EXPN_DTTM 

JOIN DB_T_PROD_CORE.AGMT_STS  AS AS1  ON  TRM.AGMT_ID=AS1.AGMT_ID AND AS1.AGMT_STS_STRT_DTTM <= CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

AND NEW_AGMT_EFF_DTTM < CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond''

AND A.AGMT_TYPE_CD = ''PPV'' AND AGMT_STS_CD <> ''CNFRMDDT'' 

LEFT JOIN DB_T_PROD_CORE.AGMT_PROD AP ON A.AGMT_ID=AP.AGMT_ID

 LEFT JOIN DB_T_PROD_CORE.AGMT_MBRSHP  AS AM ON A.AGMT_ID=AM.AGMT_ID

LEFT JOIN DB_T_PROD_CORE.MBRSHP   AS M ON M.MBRSHP_ID=AM.MBRSHP_ID

JOIN DB_T_PROD_CORE.PROD P ON AP.PROD_ID=P.PROD_ID

JOIN DB_T_PROD_CORE.INSRNC_LOB_TYPE D ON D.INSRNC_LOB_TYPE_CD=P.INSRNC_LOB_TYPE_CD


WHERE MBRSHP_TYPE_CD LIKE ''%MBR%''

) AS A QUALIFY ROW_NUMBER() OVER(PARTITION BY A.HOST_AGMT_NUM ORDER BY  A.MODL_CRTN_DTTM DESC,A.MODL_EFF_DTTM DESC, AS1.AGMT_STS_STRT_DTTM DESC) = 1 AND AGMT_STS_CD = ''INFORCE''
)D

 JOIN ECTL_AUTO_DATES B  ON 1=1

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,B.MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''GW_TABLES'' AS TBL_NM

,''FIRE_CST_CNT'' AS METRIC_NM

,DB_T_STAG_MEMBXREF_PROD.FIRE

FROM

(SELECT

SUM(CASE WHEN INSRNC_LOB_TYPE_CD LIKE ''SF%''  THEN 1 ELSE 0 END)  FIRE

 FROM 

(SELECT DISTINCT A.HOST_AGMT_NUM PLCY_NUM ,D.INSRNC_LOB_TYPE_CD,AGMT_STS_CD,

CASE WHEN A.MODL_EFF_DTTM > A.MODL_CRTN_DTTM THEN A.MODL_EFF_DTTM 

ELSE A.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM,A.AGMT_ID , A.AGMT_OPN_DTTM,A.TRANS_STRT_DTTM, A.TRANS_END_DTTM,MBRSHP_TYPE_CD,MBRSHP_NUM,

A.AGMT_PLND_EXPN_DTTM

FROM  DB_T_PROD_CORE.AGMT AS A JOIN ECTL_AUTO_DATES ON 1=1

JOIN  DB_T_PROD_CORE.AGMT TRM 

ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM 

AND    TRM.AGMT_TYPE_CD=''POLTRM''   AND CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

BETWEEN TRM.AGMT_EFF_DTTM AND TRM.AGMT_PLND_EXPN_DTTM 

JOIN DB_T_PROD_CORE.AGMT_STS  AS AS1  ON  TRM.AGMT_ID=AS1.AGMT_ID AND AS1.AGMT_STS_STRT_DTTM <= CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

AND NEW_AGMT_EFF_DTTM < CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond''

AND A.AGMT_TYPE_CD = ''PPV'' AND AGMT_STS_CD <> ''CNFRMDDT'' 

LEFT JOIN DB_T_PROD_CORE.AGMT_PROD AP ON A.AGMT_ID=AP.AGMT_ID

 LEFT JOIN DB_T_PROD_CORE.AGMT_MBRSHP  AS AM ON A.AGMT_ID=AM.AGMT_ID

LEFT JOIN DB_T_PROD_CORE.MBRSHP   AS M ON M.MBRSHP_ID=AM.MBRSHP_ID

JOIN DB_T_PROD_CORE.PROD P ON AP.PROD_ID=P.PROD_ID

JOIN DB_T_PROD_CORE.INSRNC_LOB_TYPE D ON D.INSRNC_LOB_TYPE_CD=P.INSRNC_LOB_TYPE_CD


WHERE MBRSHP_TYPE_CD   LIKE ''%CUST%''

) AS A QUALIFY ROW_NUMBER() OVER(PARTITION BY A.HOST_AGMT_NUM ORDER BY  A.MODL_CRTN_DTTM DESC,A.MODL_EFF_DTTM DESC, AS1.AGMT_STS_STRT_DTTM DESC) = 1 AND AGMT_STS_CD = ''INFORCE''
)D

 JOIN ECTL_AUTO_DATES B ON 1=1

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,B.MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''GW_TABLES'' AS TBL_NM

,''EXCD_CNT'' AS METRIC_NM

,D.VEH

FROM

(SELECT

COALESCE(SUM(CASE WHEN INSRNC_LOB_TYPE_CD =''PA'' then VEH_CNT else 0 end ) ,0)VEH

 FROM 

(SELECT DISTINCT A.HOST_AGMT_NUM PLCY_NUM ,D.INSRNC_LOB_TYPE_CD,AGMT_STS_CD,

CASE WHEN A.MODL_EFF_DTTM > A.MODL_CRTN_DTTM THEN A.MODL_EFF_DTTM 

ELSE A.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM,A.AGMT_ID , A.AGMT_OPN_DTTM,A.TRANS_STRT_DTTM, A.TRANS_END_DTTM,MBRSHP_TYPE_CD,MBRSHP_NUM,

A.AGMT_PLND_EXPN_DTTM

FROM  DB_T_PROD_CORE.AGMT AS A JOIN ECTL_AUTO_DATES ON 1=1

JOIN  DB_T_PROD_CORE.AGMT TRM 

ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM 

AND    TRM.AGMT_TYPE_CD=''POLTRM''   AND CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

BETWEEN TRM.AGMT_EFF_DTTM AND TRM.AGMT_PLND_EXPN_DTTM 

JOIN DB_T_PROD_CORE.AGMT_STS  AS AS1  ON  TRM.AGMT_ID=AS1.AGMT_ID AND AS1.AGMT_STS_STRT_DTTM <= CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

AND NEW_AGMT_EFF_DTTM < CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond''

AND A.AGMT_TYPE_CD = ''PPV'' AND AGMT_STS_CD <> ''CNFRMDDT'' 

LEFT JOIN DB_T_PROD_CORE.AGMT_PROD AP ON A.AGMT_ID=AP.AGMT_ID

 LEFT JOIN DB_T_PROD_CORE.AGMT_MBRSHP  AS AM ON A.AGMT_ID=AM.AGMT_ID

LEFT JOIN DB_T_PROD_CORE.MBRSHP   AS M ON M.MBRSHP_ID=AM.MBRSHP_ID

JOIN DB_T_PROD_CORE.PROD P ON AP.PROD_ID=P.PROD_ID

JOIN DB_T_PROD_CORE.INSRNC_LOB_TYPE D ON D.INSRNC_LOB_TYPE_CD=P.INSRNC_LOB_TYPE_CD

QUALIFY ROW_NUMBER() OVER(PARTITION BY A.HOST_AGMT_NUM ORDER BY  A.MODL_CRTN_DTTM DESC,A.MODL_EFF_DTTM DESC, AS1.AGMT_STS_STRT_DTTM DESC) = 1 AND AGMT_STS_CD = ''INFORCE''



) AS A 

LEFT OUTER JOIN( SELECT COUNT(DISTINCT PA.ASSET_HOST_ID_VAL) VEH_CNT,AGMT_ID  FROM DB_T_PROD_CORE.AGMT_ASSET AA  JOIN ECTL_AUTO_DATES ON 1=1

JOIN DB_T_PROD_CORE.PRTY_ASSET PA ON PA.PRTY_ASSET_ID=AA.PRTY_ASSET_ID 

WHERE PRTY_ASSET_SBTYPE_CD IN (''MV'',''MVEH'') AND CAST(AA.AGMT_ASSET_STRT_DTTM AS DATE)<=CAL_START_DATE  AND CAST(AA.AGMT_ASSET_END_DTTM AS DATE)>CAL_START_DATE

GROUP BY 2)V  ON V.AGMT_ID=A.AGMT_ID 

 ) D JOIN ECTL_AUTO_DATES B ON 1=1

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,B.MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''GW_TABLES'' AS TBL_NM

,''SMLN_MBR_CNT'' AS METRIC_NM

,D.SMLN

FROM

(SELECT

SUM(CASE WHEN ( INSRNC_LOB_TYPE_CD in (''COMPPERSL'',''PERSARTFL'',''WTC'') AND AGMT_ST=''AL'') THEN 1 ELSE 0 END)  SMLN

 FROM 

(SELECT DISTINCT A.HOST_AGMT_NUM PLCY_NUM ,D.INSRNC_LOB_TYPE_CD,AGMT_STS_CD,

CASE WHEN A.MODL_EFF_DTTM > A.MODL_CRTN_DTTM THEN A.MODL_EFF_DTTM 

ELSE A.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM,A.AGMT_ID , A.AGMT_OPN_DTTM,A.TRANS_STRT_DTTM, A.TRANS_END_DTTM,MBRSHP_TYPE_CD,MBRSHP_NUM,

A.AGMT_PLND_EXPN_DTTM

FROM  DB_T_PROD_CORE.AGMT AS A JOIN ECTL_AUTO_DATES ON 1=1

JOIN  DB_T_PROD_CORE.AGMT TRM 

ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM 

AND    TRM.AGMT_TYPE_CD=''POLTRM''   AND CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

BETWEEN TRM.AGMT_EFF_DTTM AND TRM.AGMT_PLND_EXPN_DTTM 

JOIN DB_T_PROD_CORE.AGMT_STS  AS AS1  ON  TRM.AGMT_ID=AS1.AGMT_ID AND AS1.AGMT_STS_STRT_DTTM <= CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

AND NEW_AGMT_EFF_DTTM < CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond''

AND A.AGMT_TYPE_CD = ''PPV'' AND AGMT_STS_CD <> ''CNFRMDDT'' 

LEFT JOIN DB_T_PROD_CORE.AGMT_PROD AP ON A.AGMT_ID=AP.AGMT_ID

 LEFT JOIN DB_T_PROD_CORE.AGMT_MBRSHP  AS AM ON A.AGMT_ID=AM.AGMT_ID

LEFT JOIN DB_T_PROD_CORE.MBRSHP   AS M ON M.MBRSHP_ID=AM.MBRSHP_ID

JOIN DB_T_PROD_CORE.PROD P ON AP.PROD_ID=P.PROD_ID

JOIN DB_T_PROD_CORE.INSRNC_LOB_TYPE D ON D.INSRNC_LOB_TYPE_CD=P.INSRNC_LOB_TYPE_CD


WHERE MBRSHP_TYPE_CD LIKE ''%MBR%''
QUALIFY ROW_NUMBER() OVER(PARTITION BY A.HOST_AGMT_NUM ORDER BY  A.MODL_CRTN_DTTM DESC,A.MODL_EFF_DTTM DESC, AS1.AGMT_STS_STRT_DTTM DESC) = 1 AND AGMT_STS_CD = ''INFORCE''

) AS A 

LEFT OUTER JOIN 

(SELECT DISTINCT AGMT_ID, MAX(GEOGRCL_AREA_SHRT_NAME) AGMT_ST FROM   DB_T_PROD_CORE.agmt_LOCTR AL 

JOIN DB_T_PROD_CORE.terr t ON Al.loc_id=t.terr_id WHERE AGMT_LOCTR_ROLE_TYPE_CD=''AGTWINST'' GROUP BY 1  ) AS PL

ON A.AGMT_ID = PL.AGMT_ID 

 ) D JOIN ECTL_AUTO_DATES B ON 1=1

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,B.MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''GW_TABLES'' AS TBL_NM

,''SMLN_CST_CNT'' AS METRIC_NM

,D.SMLN

FROM

(SELECT

SUM(CASE WHEN ( INSRNC_LOB_TYPE_CD in (''COMPPERSL'',''PERSARTFL'',''WTC'') AND AGMT_ST=''AL'') THEN 1 ELSE 0 END)  SMLN

 FROM 

(SELECT DISTINCT A.HOST_AGMT_NUM PLCY_NUM ,D.INSRNC_LOB_TYPE_CD,AGMT_STS_CD,

CASE WHEN A.MODL_EFF_DTTM > A.MODL_CRTN_DTTM THEN A.MODL_EFF_DTTM 

ELSE A.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM,A.AGMT_ID , A.AGMT_OPN_DTTM,A.TRANS_STRT_DTTM, A.TRANS_END_DTTM,MBRSHP_TYPE_CD,MBRSHP_NUM,

A.AGMT_PLND_EXPN_DTTM

FROM  DB_T_PROD_CORE.AGMT AS A JOIN ECTL_AUTO_DATES ON 1=1

JOIN  DB_T_PROD_CORE.AGMT TRM 

ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM 

AND    TRM.AGMT_TYPE_CD=''POLTRM''   AND CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

BETWEEN TRM.AGMT_EFF_DTTM AND TRM.AGMT_PLND_EXPN_DTTM 

JOIN DB_T_PROD_CORE.AGMT_STS  AS AS1  ON  TRM.AGMT_ID=AS1.AGMT_ID AND AS1.AGMT_STS_STRT_DTTM <= CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

AND NEW_AGMT_EFF_DTTM < CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond''

AND A.AGMT_TYPE_CD = ''PPV'' AND AGMT_STS_CD <> ''CNFRMDDT'' 

LEFT JOIN DB_T_PROD_CORE.AGMT_PROD AP ON A.AGMT_ID=AP.AGMT_ID

 LEFT JOIN DB_T_PROD_CORE.AGMT_MBRSHP  AS AM ON A.AGMT_ID=AM.AGMT_ID

LEFT JOIN DB_T_PROD_CORE.MBRSHP   AS M ON M.MBRSHP_ID=AM.MBRSHP_ID

JOIN DB_T_PROD_CORE.PROD P ON AP.PROD_ID=P.PROD_ID

JOIN DB_T_PROD_CORE.INSRNC_LOB_TYPE D ON D.INSRNC_LOB_TYPE_CD=P.INSRNC_LOB_TYPE_CD


WHERE MBRSHP_TYPE_CD   LIKE ''%CUST%''
QUALIFY ROW_NUMBER() OVER(PARTITION BY A.HOST_AGMT_NUM ORDER BY  A.MODL_CRTN_DTTM DESC,A.MODL_EFF_DTTM DESC, AS1.AGMT_STS_STRT_DTTM DESC) = 1 AND AGMT_STS_CD = ''INFORCE''

) AS A 

LEFT OUTER JOIN 

(SELECT DISTINCT AGMT_ID, MAX(GEOGRCL_AREA_SHRT_NAME) AGMT_ST FROM   DB_T_PROD_CORE.agmt_LOCTR AL 

JOIN DB_T_PROD_CORE.terr t ON Al.loc_id=t.terr_id WHERE AGMT_LOCTR_ROLE_TYPE_CD=''AGTWINST'' GROUP BY 1  ) AS PL

ON A.AGMT_ID = PL.AGMT_ID 

 ) D JOIN ECTL_AUTO_DATES B ON 1=1

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,B.MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''GW_TABLES'' AS TBL_NM

,''FGM_MBR_CNT'' AS METRIC_NM

,D.FGM

FROM

(SELECT

SUM(CASE WHEN ( INSRNC_LOB_TYPE_CD in (''COMPPERSL'',''PERSARTFL'',''WTC'') AND AGMT_ST IN (''GA'',''MS'')) THEN 1 ELSE 0 END)  FGM

 FROM 

(SELECT DISTINCT A.HOST_AGMT_NUM PLCY_NUM ,D.INSRNC_LOB_TYPE_CD,AGMT_STS_CD,

CASE WHEN A.MODL_EFF_DTTM > A.MODL_CRTN_DTTM THEN A.MODL_EFF_DTTM 

ELSE A.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM,A.AGMT_ID , A.AGMT_OPN_DTTM,A.TRANS_STRT_DTTM, A.TRANS_END_DTTM,MBRSHP_TYPE_CD,MBRSHP_NUM,

A.AGMT_PLND_EXPN_DTTM

FROM  DB_T_PROD_CORE.AGMT AS A JOIN ECTL_AUTO_DATES ON 1=1

JOIN  DB_T_PROD_CORE.AGMT TRM 

ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM 

AND    TRM.AGMT_TYPE_CD=''POLTRM''   AND CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

BETWEEN TRM.AGMT_EFF_DTTM AND TRM.AGMT_PLND_EXPN_DTTM 

JOIN DB_T_PROD_CORE.AGMT_STS  AS AS1  ON  TRM.AGMT_ID=AS1.AGMT_ID AND AS1.AGMT_STS_STRT_DTTM <= CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

AND NEW_AGMT_EFF_DTTM < CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond''

AND A.AGMT_TYPE_CD = ''PPV'' AND AGMT_STS_CD <> ''CNFRMDDT'' 

LEFT JOIN DB_T_PROD_CORE.AGMT_PROD AP ON A.AGMT_ID=AP.AGMT_ID

 LEFT JOIN DB_T_PROD_CORE.AGMT_MBRSHP  AS AM ON A.AGMT_ID=AM.AGMT_ID

LEFT JOIN DB_T_PROD_CORE.MBRSHP   AS M ON M.MBRSHP_ID=AM.MBRSHP_ID

JOIN DB_T_PROD_CORE.PROD P ON AP.PROD_ID=P.PROD_ID

JOIN DB_T_PROD_CORE.INSRNC_LOB_TYPE D ON D.INSRNC_LOB_TYPE_CD=P.INSRNC_LOB_TYPE_CD


WHERE MBRSHP_TYPE_CD  LIKE ''%MBR%''
QUALIFY ROW_NUMBER() OVER(PARTITION BY A.HOST_AGMT_NUM ORDER BY  A.MODL_CRTN_DTTM DESC,A.MODL_EFF_DTTM DESC, AS1.AGMT_STS_STRT_DTTM DESC) = 1 AND AGMT_STS_CD = ''INFORCE''

) AS A 

LEFT OUTER JOIN 

(SELECT DISTINCT AGMT_ID, MAX(GEOGRCL_AREA_SHRT_NAME) AGMT_ST FROM   DB_T_PROD_CORE.agmt_LOCTR AL 

JOIN DB_T_PROD_CORE.terr t ON Al.loc_id=t.terr_id WHERE AGMT_LOCTR_ROLE_TYPE_CD=''AGTWINST'' GROUP BY 1  ) AS PL

ON A.AGMT_ID = PL.AGMT_ID 

 ) D JOIN ECTL_AUTO_DATES B ON 1=1

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1



UNION



SELECT 

E.ECTL_BATCH_ID

,B.MO_ID AS MO_ID

,''DW'' AS CALC_SRC

,''GW_TABLES'' AS TBL_NM

,''FGM_CST_CNT'' AS METRIC_NM

,D.FGM

FROM

(SELECT

SUM(CASE WHEN ( INSRNC_LOB_TYPE_CD in (''COMPPERSL'',''PERSARTFL'',''WTC'') AND AGMT_ST IN (''GA'',''MS'')) THEN 1 ELSE 0 END)  FGM

 FROM 

(SELECT DISTINCT A.HOST_AGMT_NUM PLCY_NUM ,D.INSRNC_LOB_TYPE_CD,AGMT_STS_CD,

CASE WHEN A.MODL_EFF_DTTM > A.MODL_CRTN_DTTM THEN A.MODL_EFF_DTTM 

ELSE A.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM,A.AGMT_ID , A.AGMT_OPN_DTTM,A.TRANS_STRT_DTTM, A.TRANS_END_DTTM,MBRSHP_TYPE_CD,MBRSHP_NUM,

A.AGMT_PLND_EXPN_DTTM

FROM  DB_T_PROD_CORE.AGMT AS A JOIN ECTL_AUTO_DATES ON 1=1

JOIN  DB_T_PROD_CORE.AGMT TRM 

ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM 

AND    TRM.AGMT_TYPE_CD=''POLTRM''   AND CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

BETWEEN TRM.AGMT_EFF_DTTM AND TRM.AGMT_PLND_EXPN_DTTM 

JOIN DB_T_PROD_CORE.AGMT_STS  AS AS1  ON  TRM.AGMT_ID=AS1.AGMT_ID AND AS1.AGMT_STS_STRT_DTTM <= CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond'' 

AND NEW_AGMT_EFF_DTTM < CAST(CAST(CAL_START_DATE AS DATE)+1 AS TIMESTAMPNTZ) - INTERVAL ''1 microsecond''

AND A.AGMT_TYPE_CD = ''PPV'' AND AGMT_STS_CD <> ''CNFRMDDT'' 

LEFT JOIN DB_T_PROD_CORE.AGMT_PROD AP ON A.AGMT_ID=AP.AGMT_ID

 LEFT JOIN DB_T_PROD_CORE.AGMT_MBRSHP  AS AM ON A.AGMT_ID=AM.AGMT_ID

LEFT JOIN DB_T_PROD_CORE.MBRSHP   AS M ON M.MBRSHP_ID=AM.MBRSHP_ID

JOIN DB_T_PROD_CORE.PROD P ON AP.PROD_ID=P.PROD_ID

JOIN DB_T_PROD_CORE.INSRNC_LOB_TYPE D ON D.INSRNC_LOB_TYPE_CD=P.INSRNC_LOB_TYPE_CD


WHERE MBRSHP_TYPE_CD   LIKE ''%CUST%''
QUALIFY ROW_NUMBER() OVER(PARTITION BY A.HOST_AGMT_NUM ORDER BY  A.MODL_CRTN_DTTM DESC,A.MODL_EFF_DTTM DESC, AS1.AGMT_STS_STRT_DTTM DESC) = 1 AND AGMT_STS_CD = ''INFORCE''

) AS A 

LEFT OUTER JOIN 

(SELECT DISTINCT AGMT_ID, MAX(GEOGRCL_AREA_SHRT_NAME) AGMT_ST FROM   DB_T_PROD_CORE.agmt_LOCTR AL 

JOIN DB_T_PROD_CORE.terr t ON Al.loc_id=t.terr_id WHERE AGMT_LOCTR_ROLE_TYPE_CD=''AGTWINST'' GROUP BY 1  ) AS PL

ON A.AGMT_ID = PL.AGMT_ID 

 ) D JOIN ECTL_AUTO_DATES B ON 1=1

FULL OUTER JOIN

(SELECT * FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = 12 AND ECTL_ACTIVE_IND = ''Y'') E

ON 1=1
) SRC
)
);


-- Component expr_passthrough, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE expr_passthrough AS
(
SELECT
sq_STG_BILL_PMTS.ECTL_BATCH_ID as ECTL_BATCH_ID,
sq_STG_BILL_PMTS.MO_ID as MO_ID,
sq_STG_BILL_PMTS.CALC_SRC as CALC_SRC,
sq_STG_BILL_PMTS.TBL_NM as TBL_NM,
sq_STG_BILL_PMTS.METRIC_NM as METRIC_NM,
sq_STG_BILL_PMTS.METRIC_CNT as METRIC_CNT,
sq_STG_BILL_PMTS.source_record_id
FROM
sq_STG_BILL_PMTS
);


-- Component AGG_COUNT_BALANCE, Type TARGET 
INSERT INTO DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE
(
ECTL_BATCH_ID,
MO_ID,
CALC_SRC,
TBL_NM,
METRIC_NM,
METRIC_CNT
)
SELECT
expr_passthrough.ECTL_BATCH_ID as ECTL_BATCH_ID,
expr_passthrough.MO_ID as MO_ID,
expr_passthrough.CALC_SRC as CALC_SRC,
expr_passthrough.TBL_NM as TBL_NM,
expr_passthrough.METRIC_NM as METRIC_NM,
expr_passthrough.METRIC_CNT as METRIC_CNT
FROM
expr_passthrough;


END; ';