-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STG_MULTILINE_POLSTAT("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as POL_SYMBOL,
$2 as POL_NBR,
$3 as COMPANY,
$4 as STATE,
$5 as STATUS,
$6 as AGENT,
$7 as SERV_CNTR,
$8 as EXP_DT_CYMD,
$9 as DIST_REGION,
$10 as ADD_COV,
$11 as FIRE_CONVERT_TRANS_CODE,
$12 as SM_POL_INDICATOR,
$13 as REASON,
$14 as TOT_PREM,
$15 as FIRE_HOME_TYPE_POL,
$16 as EFF_DT_CYMD,
$17 as MEMBER_TYPE,
$18 as MEMBER_NBR,
$19 as NAMED_INS,
$20 as ADDL_NMD_INS,
$21 as ADDR1,
$22 as ADDR2,
$23 as CITY,
$24 as ADDR_STATE,
$25 as ZIP,
$26 as DIV_S3_POL_SYM,
$27 as DIV_S3_POL_NBR,
$28 as DIV_MAN_IND,
$29 as DIV_POL_LAPSE,
$30 as NR,
$31 as INF_UNIT_CTS,
$32 as FEED_DT,
$33 as POLICY_ACTIVITY,
$34 as INFORCE_IND,
$35 as LOB_GROUP,
$36 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
PRESTG_MULTILINE_POLSTAT.POL_SYMBOL,
PRESTG_MULTILINE_POLSTAT.POL_NBR,
PRESTG_MULTILINE_POLSTAT.COMPANY,
PRESTG_MULTILINE_POLSTAT.STATE,
PRESTG_MULTILINE_POLSTAT.STATUS,
PRESTG_MULTILINE_POLSTAT.AGENT,
PRESTG_MULTILINE_POLSTAT.SERV_CNTR,
PRESTG_MULTILINE_POLSTAT.EXP_DT_CYMD,
PRESTG_MULTILINE_POLSTAT.DIST_REGION,
PRESTG_MULTILINE_POLSTAT.ADD_COV,
PRESTG_MULTILINE_POLSTAT.FIRE_CONVERT_TRANS_CODE,
PRESTG_MULTILINE_POLSTAT.SM_POL_INDICATOR,
PRESTG_MULTILINE_POLSTAT.REASON,
PRESTG_MULTILINE_POLSTAT.TOT_PREM,
PRESTG_MULTILINE_POLSTAT.FIRE_HOME_TYPE_POL,
PRESTG_MULTILINE_POLSTAT.EFF_DT_CYMD,
PRESTG_MULTILINE_POLSTAT.MEMBER_TYPE,
PRESTG_MULTILINE_POLSTAT.MEMBER_NBR,
PRESTG_MULTILINE_POLSTAT.NAMED_INS,
PRESTG_MULTILINE_POLSTAT.ADDL_NMD_INS,
PRESTG_MULTILINE_POLSTAT.ADDR1,
PRESTG_MULTILINE_POLSTAT.ADDR2,
PRESTG_MULTILINE_POLSTAT.CITY,
PRESTG_MULTILINE_POLSTAT.ADDR_STATE,
PRESTG_MULTILINE_POLSTAT.ZIP,
PRESTG_MULTILINE_POLSTAT.DIV_S3_POL_SYM,
PRESTG_MULTILINE_POLSTAT.DIV_S3_POL_NBR,
PRESTG_MULTILINE_POLSTAT.DIV_MAN_IND,
PRESTG_MULTILINE_POLSTAT.DIV_POL_LAPSE,
PRESTG_MULTILINE_POLSTAT.NR,
PRESTG_MULTILINE_POLSTAT.INF_UNIT_CTS,
PRESTG_MULTILINE_POLSTAT.FEED_DT,
PRESTG_MULTILINE_POLSTAT.POLICY_ACTIVITY,
PRESTG_MULTILINE_POLSTAT.INFORCE_IND,
PRESTG_MULTILINE_POLSTAT.LOB_GROUP
FROM DB_T_STAG_PROD.PRESTG_MULTILINE_POLSTAT
) SRC
)
);


-- Component exp_CONVERSION, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CONVERSION AS
(
SELECT
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.POL_SYMBOL ) ) ) as POL_SYMBOL,
TO_CHAR ( LTRIm ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.POL_NBR ) ) ) as POL_NBR,
TO_CHAR ( LTRIm ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.COMPANY ) ) ) as COMPANY,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.STATE ) ) ) as STATE,
TO_NUMBER(LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.STATUS ) )) as STATUS,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.AGENT ) ) ) as AGENT,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.SERV_CNTR ) ) ) as SERV_CNTR,
LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.EXP_DT_CYMD ) ) as var_EXP_DT_CYMD,
TO_CHAR(
  CASE
    WHEN TO_NUMBER(SUBSTRING(var_EXP_DT_CYMD, 5, 2)) > 12
    OR TO_NUMBER(SUBSTRING(var_EXP_DT_CYMD, 5, 2)) = 0 THEN NULL
    WHEN NOT TRY_TO_DATE(var_EXP_DT_CYMD, ''yyyymmDD'') IS NULL THEN TO_NUMBER(var_EXP_DT_CYMD)
    WHEN TO_NUMBER(SUBSTRING(var_EXP_DT_CYMD, 5, 2)) IN (1, 3, 5, 7, 8, 10, 12) THEN TO_NUMBER(SUBSTRING(var_EXP_DT_CYMD, 1, 6)) * 100 + 31
    WHEN TO_NUMBER(SUBSTRING(var_EXP_DT_CYMD, 5, 2)) IN (4, 6, 9, 11) THEN TO_NUMBER(SUBSTRING(var_EXP_DT_CYMD, 1, 6)) * 100 + 30
    WHEN TO_NUMBER(SUBSTRING(var_EXP_DT_CYMD, 1, 4)) % 4 = 0
    AND TO_NUMBER(SUBSTRING(var_EXP_DT_CYMD, 5, 2)) = 2 THEN TO_NUMBER(SUBSTRING(var_EXP_DT_CYMD, 1, 6)) * 100 + 29
    ELSE TO_NUMBER(SUBSTRING(var_EXP_DT_CYMD, 1, 6)) * 100 + 28
  END
) AS var2_EXP_DT_CYMD,

TO_DATE ( var2_EXP_DT_CYMD , ''YYYYMMDD'' ) as EXP_DT_CYMD,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.DIST_REGION ) ) ) as DIST_REGION,
TO_NUMBER(LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.ADD_COV ) )) as ADD_COV,
TO_CHAR ( LTRIm ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.FIRE_CONVERT_TRANS_CODE ) ) ) as FIRE_CONVERT_TRANS_CODE,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.SM_POL_INDICATOR ) ) ) as SM_POL_INDICATOR,
TO_NUMBER(LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.REASON ) )) as REASON,
IFNULL(TRY_TO_DECIMAL(LTRIm ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.TOT_PREM ) )), 0) as TOT_PREM,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.FIRE_HOME_TYPE_POL ) ) ) as FIRE_HOME_TYPE_POL,
LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.EFF_DT_CYMD ) ) as var_EFF_DT_CYMD,
CASE
  WHEN TO_NUMBER(SUBSTRING(var_EFF_DT_CYMD, 5, 2)) > 12
  OR TO_NUMBER(SUBSTRING(var_EFF_DT_CYMD, 5, 2)) = 0 THEN NULL
  WHEN NOT TRY_TO_DATE(var_EFF_DT_CYMD, ''yyyymmDD'') IS NULL THEN TO_NUMBER(var_EFF_DT_CYMD)
  WHEN TO_NUMBER(SUBSTRING(var_EFF_DT_CYMD, 5, 2)) IN (1, 3, 5, 7, 8, 10, 12) THEN TO_NUMBER(SUBSTRING(var_EFF_DT_CYMD, 1, 6)) * 100 + 31
  WHEN TO_NUMBER(SUBSTRING(var_EFF_DT_CYMD, 5, 2)) IN (4, 6, 9, 11) THEN TO_NUMBER(SUBSTRING(var_EFF_DT_CYMD, 1, 6)) * 100 + 30
  WHEN TO_NUMBER(SUBSTRING(var_EFF_DT_CYMD, 1, 4)) % 4 = 0
  AND TO_NUMBER(SUBSTRING(var_EFF_DT_CYMD, 5, 2)) = 2 THEN TO_NUMBER(SUBSTRING(var_EFF_DT_CYMD, 1, 6)) * 100 + 29
  ELSE TO_NUMBER(SUBSTRING(var_EFF_DT_CYMD, 1, 6)) * 100 + 28
END AS var2_EFF_DT_CYMD,
TO_DATE ( var2_EFF_DT_CYMD , ''YYYYMMDD'' ) as EFF_DT_CYMD,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.MEMBER_TYPE ) ) ) as MEMBER_TYPE,
TO_CHAR ( LTRIm ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.MEMBER_NBR ) ) ) as MEMBER_NBR,
TO_CHAR ( LTRIm ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.NAMED_INS ) ) ) as NAMED_INS,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.ADDL_NMD_INS ) ) ) as ADDL_NMD_INS,
TO_CHAR ( LTRIm ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.ADDR1 ) ) ) as ADDR1,
TO_CHAR ( LTRIm ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.ADDR2 ) ) ) as ADDR2,
TO_CHAR ( LTRIm ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.CITY ) ) ) as CITY,
TO_CHAR ( LTRIm ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.ADDR_STATE ) ) ) as ADDR_STATE,
LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.ZIP ) ) as var_ZIP,
TO_CHAR ( SUBSTR ( var_ZIP , 1 , ( POSITION(''-'',var_ZIP) - 1 ) ) ) as ZIP,
TO_CHAR ( LTRIm ( RTRIm ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.DIV_S3_POL_SYM ) ) ) as DIV_S3_POL_SYM,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.DIV_S3_POL_NBR ) ) ) as DIV_S3_POL_NBR,
TO_CHAR ( LTRIm ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.DIV_MAN_IND ) ) ) as DIV_MAN_IND,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.DIV_POL_LAPSE ) ) ) as DIV_POL_LAPSE,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.NR ) ) ) as NR,
TO_NUMBER(LTRIm ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.INF_UNIT_CTS ) )) as INF_UNIT_CTS,
TO_DATE ( CASE WHEN ltrim ( rtrim ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.FEED_DT ) ) = '''' THEN null ELSE SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.FEED_DT END , ''YYYYMMDD'' ) as FEED_DT,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.POLICY_ACTIVITY ) ) ) as POLICY_ACTIVITY,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.INFORCE_IND ) ) ) as INFORCE_IND,
TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.LOB_GROUP ) ) ) as LOB_GROUP,
SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT.source_record_id
FROM
SQ_Shortcut_to_PRESTG_MULTILINE_POLSTAT
);


-- Component LKP_TARGET, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_TARGET AS
(
SELECT
LKP.POL_NBR,
LKP.STATUS,
exp_CONVERSION.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_CONVERSION.source_record_id ORDER BY LKP.POL_NBR asc,LKP.STATUS asc) RNK
FROM
exp_CONVERSION
LEFT JOIN (
SELECT STG_MULTILINE_POLSTAT.POL_NBR as POL_NBR, STG_MULTILINE_POLSTAT.STATUS as STATUS  FROM STG_MULTILINE_POLSTAT
WHERE EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)= 
(SELECT MAX(EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)) FROM STG_MULTILINE_POLSTAT) 
 GROUP by 1,2
) LKP ON LKP.POL_NBR = exp_CONVERSION.POL_NBR
QUALIFY RNK = 1
);


-- Component exp_CALC_POLICY_ACTIVITY, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CALC_POLICY_ACTIVITY AS
(
SELECT
exp_CONVERSION.POL_SYMBOL as POL_SYMBOL,
exp_CONVERSION.POL_NBR as POL_NBR,
exp_CONVERSION.COMPANY as COMPANY,
exp_CONVERSION.STATE as STATE,
exp_CONVERSION.STATUS as STATUS,
exp_CONVERSION.AGENT as AGENT,
exp_CONVERSION.SERV_CNTR as SERV_CNTR,
exp_CONVERSION.EXP_DT_CYMD as EXP_DT_CYMD,
exp_CONVERSION.DIST_REGION as DIST_REGION,
exp_CONVERSION.ADD_COV as ADD_COV,
exp_CONVERSION.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE,
exp_CONVERSION.SM_POL_INDICATOR as SM_POL_INDICATOR,
exp_CONVERSION.REASON as REASON,
exp_CONVERSION.TOT_PREM as TOT_PREM,
exp_CONVERSION.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL,
exp_CONVERSION.EFF_DT_CYMD as EFF_DT_CYMD,
exp_CONVERSION.MEMBER_TYPE as MEMBER_TYPE,
exp_CONVERSION.MEMBER_NBR as MEMBER_NBR,
exp_CONVERSION.NAMED_INS as NAMED_INS,
exp_CONVERSION.ADDL_NMD_INS as ADDL_NMD_INS,
exp_CONVERSION.ADDR1 as ADDR1,
exp_CONVERSION.ADDR2 as ADDR2,
exp_CONVERSION.CITY as CITY,
exp_CONVERSION.ADDR_STATE as ADDR_STATE,
exp_CONVERSION.ZIP as ZIP,
exp_CONVERSION.DIV_S3_POL_SYM as DIV_S3_POL_SYM,
exp_CONVERSION.DIV_S3_POL_NBR as DIV_S3_POL_NBR,
exp_CONVERSION.DIV_MAN_IND as DIV_MAN_IND,
exp_CONVERSION.DIV_POL_LAPSE as DIV_POL_LAPSE,
exp_CONVERSION.NR as NR,
exp_CONVERSION.INF_UNIT_CTS as INF_UNIT_CTS,
exp_CONVERSION.FEED_DT as FEED_DT,
CASE
  WHEN LKP_TARGET.POL_NBR IS NULL THEN CASE
    WHEN exp_CONVERSION.POLICY_ACTIVITY IS NULL
    OR TRIM(exp_CONVERSION.POLICY_ACTIVITY) = '''' THEN CASE
      WHEN exp_CONVERSION.STATUS = 0 THEN ''NEW''
      WHEN exp_CONVERSION.STATUS = 10 THEN ''INFR''
      WHEN exp_CONVERSION.STATUS IN (20, 21) THEN ''LAPS''
      WHEN exp_CONVERSION.STATUS = 30 THEN ''CANC''
      WHEN exp_CONVERSION.STATUS > 30 THEN ''LCANC''
      ELSE $3
    END
    ELSE exp_CONVERSION.POLICY_ACTIVITY
  END
  ELSE CASE
    WHEN exp_CONVERSION.STATUS = 30 THEN ''CANC''
    WHEN exp_CONVERSION.STATUS IN (21, 20) THEN ''LAPS''
    WHEN exp_CONVERSION.STATUS IN (31, 32, 33, 34, 35, 36, 37, 38, 39) THEN ''LCANC''
    WHEN exp_CONVERSION.STATUS IN (0, 10) THEN CASE
      WHEN LKP_TARGET.STATUS >= 30 THEN ''REIN''
      WHEN LKP_TARGET.STATUS < 30 THEN ''INFR''
      ELSE $3
    END
    ELSE $3
  END
END AS out_POLICY_ACTIVITY,
LTRIM ( RTRIM ( exp_CONVERSION.POLICY_ACTIVITY ) ) as OGN_POLICY_ACTIVITY,
exp_CONVERSION.INFORCE_IND as INFORCE_IND,
exp_CONVERSION.LOB_GROUP as LOB_GROUP,
exp_CONVERSION.source_record_id
FROM
exp_CONVERSION
INNER JOIN LKP_TARGET ON exp_CONVERSION.source_record_id = LKP_TARGET.source_record_id
);


-- Component LKP_TARGET1, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_TARGET1 AS
(
SELECT
LKP.STATUS_lkup,
exp_CALC_POLICY_ACTIVITY.POL_SYMBOL as POL_SYMBOL,
exp_CALC_POLICY_ACTIVITY.POL_NBR as POL_NBR,
exp_CALC_POLICY_ACTIVITY.COMPANY as COMPANY,
exp_CALC_POLICY_ACTIVITY.STATE as STATE,
exp_CALC_POLICY_ACTIVITY.STATUS as STATUS,
exp_CALC_POLICY_ACTIVITY.AGENT as AGENT,
exp_CALC_POLICY_ACTIVITY.SERV_CNTR as SERV_CNTR,
exp_CALC_POLICY_ACTIVITY.EXP_DT_CYMD as EXP_DT_CYMD,
exp_CALC_POLICY_ACTIVITY.DIST_REGION as DIST_REGION,
exp_CALC_POLICY_ACTIVITY.ADD_COV as ADD_COV,
exp_CALC_POLICY_ACTIVITY.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE,
exp_CALC_POLICY_ACTIVITY.SM_POL_INDICATOR as SM_POL_INDICATOR,
exp_CALC_POLICY_ACTIVITY.REASON as REASON,
exp_CALC_POLICY_ACTIVITY.TOT_PREM as TOT_PREM,
exp_CALC_POLICY_ACTIVITY.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL,
exp_CALC_POLICY_ACTIVITY.EFF_DT_CYMD as EFF_DT_CYMD,
exp_CALC_POLICY_ACTIVITY.MEMBER_TYPE as MEMBER_TYPE,
exp_CALC_POLICY_ACTIVITY.MEMBER_NBR as MEMBER_NBR,
exp_CALC_POLICY_ACTIVITY.NAMED_INS as NAMED_INS,
exp_CALC_POLICY_ACTIVITY.ADDL_NMD_INS as ADDL_NMD_INS,
exp_CALC_POLICY_ACTIVITY.ADDR1 as ADDR1,
exp_CALC_POLICY_ACTIVITY.ADDR2 as ADDR2,
exp_CALC_POLICY_ACTIVITY.CITY as CITY,
exp_CALC_POLICY_ACTIVITY.ADDR_STATE as ADDR_STATE,
exp_CALC_POLICY_ACTIVITY.ZIP as ZIP,
exp_CALC_POLICY_ACTIVITY.DIV_S3_POL_SYM as DIV_S3_POL_SYM,
exp_CALC_POLICY_ACTIVITY.DIV_S3_POL_NBR as DIV_S3_POL_NBR,
exp_CALC_POLICY_ACTIVITY.DIV_MAN_IND as DIV_MAN_IND,
exp_CALC_POLICY_ACTIVITY.DIV_POL_LAPSE as DIV_POL_LAPSE,
exp_CALC_POLICY_ACTIVITY.NR as NR,
exp_CALC_POLICY_ACTIVITY.INF_UNIT_CTS as INF_UNIT_CTS,
exp_CALC_POLICY_ACTIVITY.FEED_DT as FEED_DT,
exp_CALC_POLICY_ACTIVITY.INFORCE_IND as INFORCE_IND,
exp_CALC_POLICY_ACTIVITY.LOB_GROUP as LOB_GROUP,
exp_CALC_POLICY_ACTIVITY.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_CALC_POLICY_ACTIVITY.source_record_id ORDER BY LKP.POL_SYMBOL_lkup asc,LKP.POL_NBR_lkup asc,LKP.COMPANY_lkup asc,LKP.STATE_lkup asc,LKP.STATUS_lkup asc,LKP.AGENT_lkup asc,LKP.SERV_CNTR_lkup asc,LKP.DIST_REGION_lkup asc,LKP.EFF_DT_CYMD_lkup asc,LKP.EXP_DT_CYMD_lkup asc,LKP.ADD_COV_lkup asc,LKP.FIRE_CONVERT_TRANS_CODE_lkup asc,LKP.SM_POL_INDICATOR_lkup asc,LKP.REASON_lkup asc,LKP.TOT_PREM_lkup asc,LKP.FIRE_HOME_TYPE_POL_lkup asc,LKP.MEMBER_TYPE_lkup asc,LKP.MEMBER_NBR_lkup asc,LKP.NAMED_INS_lkup asc,LKP.ADDL_NMD_INS_lkup asc,LKP.ADDR1_lkup asc,LKP.ADDR2_lkup asc,LKP.CITY_lkup asc,LKP.ADDR_STATE_lkup asc,LKP.ZIP_lkup asc,LKP.DIV_S3_POL_SYM_lkup asc,LKP.DIV_S3_POL_NBR_lkup asc,LKP.DIV_MAN_IND_lkup asc,LKP.DIV_POL_LAPSE_lkup asc,LKP.NR_lkup asc,LKP.INF_UNIT_CTS_lkup asc,LKP.INFORCE_IND_lkup asc,LKP.LOB_GROUP_lkup asc,LKP.FEED_DT_lkup asc) RNK
FROM
exp_CALC_POLICY_ACTIVITY
LEFT JOIN (
SELECT STG_MULTILINE_POLSTAT.POL_SYMBOL as POL_SYMBOL_lkup, STG_MULTILINE_POLSTAT.POL_NBR as POL_NBR_lkup, 
STG_MULTILINE_POLSTAT.COMPANY as COMPANY_lkup, 
STG_MULTILINE_POLSTAT.STATE as STATE_lkup, STG_MULTILINE_POLSTAT.STATUS as STATUS_lkup, STG_MULTILINE_POLSTAT.AGENT as AGENT_lkup, 
STG_MULTILINE_POLSTAT.SERV_CNTR as SERV_CNTR_lkup, STG_MULTILINE_POLSTAT.DIST_REGION as DIST_REGION_lkup, 
STG_MULTILINE_POLSTAT.EFF_DT_CYMD as EFF_DT_CYMD_lkup, STG_MULTILINE_POLSTAT.EXP_DT_CYMD as EXP_DT_CYMD_lkup, 
STG_MULTILINE_POLSTAT.ADD_COV as ADD_COV_lkup, STG_MULTILINE_POLSTAT.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE_lkup, 
STG_MULTILINE_POLSTAT.SM_POL_INDICATOR as SM_POL_INDICATOR_lkup, STG_MULTILINE_POLSTAT.REASON as REASON_lkup, 
STG_MULTILINE_POLSTAT.TOT_PREM as TOT_PREM_lkup, STG_MULTILINE_POLSTAT.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL_lkup, 
STG_MULTILINE_POLSTAT.MEMBER_TYPE as MEMBER_TYPE_lkup, STG_MULTILINE_POLSTAT.MEMBER_NBR as MEMBER_NBR_lkup, 
STG_MULTILINE_POLSTAT.NAMED_INS as NAMED_INS_lkup, STG_MULTILINE_POLSTAT.ADDL_NMD_INS as ADDL_NMD_INS_lkup, 
STG_MULTILINE_POLSTAT.ADDR1 as ADDR1_lkup, STG_MULTILINE_POLSTAT.ADDR2 as ADDR2_lkup, STG_MULTILINE_POLSTAT.CITY as CITY_lkup, 
STG_MULTILINE_POLSTAT.ADDR_STATE as ADDR_STATE_lkup, STG_MULTILINE_POLSTAT.ZIP as ZIP_lkup, STG_MULTILINE_POLSTAT.DIV_S3_POL_SYM as DIV_S3_POL_SYM_lkup, 
STG_MULTILINE_POLSTAT.DIV_S3_POL_NBR as DIV_S3_POL_NBR_lkup, STG_MULTILINE_POLSTAT.DIV_MAN_IND as DIV_MAN_IND_lkup, 
STG_MULTILINE_POLSTAT.DIV_POL_LAPSE as DIV_POL_LAPSE_lkup, STG_MULTILINE_POLSTAT.NR as NR_lkup, STG_MULTILINE_POLSTAT.INF_UNIT_CTS as INF_UNIT_CTS_lkup, 
STG_MULTILINE_POLSTAT.INFORCE_IND as INFORCE_IND_lkup, 
STG_MULTILINE_POLSTAT.LOB_GROUP as LOB_GROUP_lkup, STG_MULTILINE_POLSTAT.FEED_DT as FEED_DT_lkup
FROM STG_MULTILINE_POLSTAT
WHERE EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)= 
(SELECT MAX(EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)) FROM STG_MULTILINE_POLSTAT)
) LKP ON LKP.POL_SYMBOL_lkup = exp_CALC_POLICY_ACTIVITY.POL_SYMBOL AND LKP.POL_NBR_lkup = exp_CALC_POLICY_ACTIVITY.POL_NBR AND LKP.COMPANY_lkup = exp_CALC_POLICY_ACTIVITY.COMPANY AND LKP.STATE_lkup = exp_CALC_POLICY_ACTIVITY.STATE AND LKP.STATUS_lkup = exp_CALC_POLICY_ACTIVITY.STATUS AND LKP.AGENT_lkup = exp_CALC_POLICY_ACTIVITY.AGENT AND LKP.SERV_CNTR_lkup = exp_CALC_POLICY_ACTIVITY.SERV_CNTR AND LKP.DIST_REGION_lkup = exp_CALC_POLICY_ACTIVITY.DIST_REGION AND LKP.EFF_DT_CYMD_lkup = exp_CALC_POLICY_ACTIVITY.EFF_DT_CYMD AND LKP.EXP_DT_CYMD_lkup = exp_CALC_POLICY_ACTIVITY.EXP_DT_CYMD AND LKP.ADD_COV_lkup = exp_CALC_POLICY_ACTIVITY.ADD_COV AND LKP.FIRE_CONVERT_TRANS_CODE_lkup = exp_CALC_POLICY_ACTIVITY.FIRE_CONVERT_TRANS_CODE AND LKP.SM_POL_INDICATOR_lkup = exp_CALC_POLICY_ACTIVITY.SM_POL_INDICATOR AND LKP.REASON_lkup = exp_CALC_POLICY_ACTIVITY.REASON AND LKP.TOT_PREM_lkup = exp_CALC_POLICY_ACTIVITY.TOT_PREM AND LKP.FIRE_HOME_TYPE_POL_lkup = exp_CALC_POLICY_ACTIVITY.FIRE_HOME_TYPE_POL AND LKP.MEMBER_TYPE_lkup = exp_CALC_POLICY_ACTIVITY.MEMBER_TYPE AND LKP.MEMBER_NBR_lkup = exp_CALC_POLICY_ACTIVITY.MEMBER_NBR AND LKP.NAMED_INS_lkup = exp_CALC_POLICY_ACTIVITY.NAMED_INS AND LKP.ADDL_NMD_INS_lkup = exp_CALC_POLICY_ACTIVITY.ADDL_NMD_INS AND LKP.ADDR1_lkup = exp_CALC_POLICY_ACTIVITY.ADDR1 AND LKP.ADDR2_lkup = exp_CALC_POLICY_ACTIVITY.ADDR2 AND LKP.CITY_lkup = exp_CALC_POLICY_ACTIVITY.CITY AND LKP.ADDR_STATE_lkup = exp_CALC_POLICY_ACTIVITY.ADDR_STATE AND LKP.ZIP_lkup = exp_CALC_POLICY_ACTIVITY.ZIP AND LKP.DIV_S3_POL_SYM_lkup = exp_CALC_POLICY_ACTIVITY.DIV_S3_POL_SYM AND LKP.DIV_S3_POL_NBR_lkup = exp_CALC_POLICY_ACTIVITY.DIV_S3_POL_NBR AND LKP.DIV_MAN_IND_lkup = exp_CALC_POLICY_ACTIVITY.DIV_MAN_IND AND LKP.DIV_POL_LAPSE_lkup = exp_CALC_POLICY_ACTIVITY.DIV_POL_LAPSE AND LKP.NR_lkup = exp_CALC_POLICY_ACTIVITY.NR AND LKP.INF_UNIT_CTS_lkup = exp_CALC_POLICY_ACTIVITY.INF_UNIT_CTS AND LKP.INFORCE_IND_lkup = exp_CALC_POLICY_ACTIVITY.INFORCE_IND AND LKP.LOB_GROUP_lkup = exp_CALC_POLICY_ACTIVITY.LOB_GROUP AND LKP.FEED_DT_lkup = exp_CALC_POLICY_ACTIVITY.FEED_DT
QUALIFY RNK = 1
);


-- Component exp_CHECK, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CHECK AS
(
SELECT
exp_CALC_POLICY_ACTIVITY.POL_SYMBOL as POL_SYMBOL,
exp_CALC_POLICY_ACTIVITY.POL_NBR as POL_NBR,
exp_CALC_POLICY_ACTIVITY.COMPANY as COMPANY,
exp_CALC_POLICY_ACTIVITY.STATE as STATE,
exp_CALC_POLICY_ACTIVITY.STATUS as STATUS,
exp_CALC_POLICY_ACTIVITY.AGENT as AGENT,
exp_CALC_POLICY_ACTIVITY.SERV_CNTR as SERV_CNTR,
exp_CALC_POLICY_ACTIVITY.EXP_DT_CYMD as EXP_DT_CYMD,
exp_CALC_POLICY_ACTIVITY.DIST_REGION as DIST_REGION,
exp_CALC_POLICY_ACTIVITY.ADD_COV as ADD_COV,
exp_CALC_POLICY_ACTIVITY.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE,
exp_CALC_POLICY_ACTIVITY.SM_POL_INDICATOR as SM_POL_INDICATOR,
exp_CALC_POLICY_ACTIVITY.REASON as REASON,
exp_CALC_POLICY_ACTIVITY.TOT_PREM as TOT_PREM,
exp_CALC_POLICY_ACTIVITY.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL,
exp_CALC_POLICY_ACTIVITY.EFF_DT_CYMD as EFF_DT_CYMD,
exp_CALC_POLICY_ACTIVITY.MEMBER_TYPE as MEMBER_TYPE,
exp_CALC_POLICY_ACTIVITY.MEMBER_NBR as MEMBER_NBR,
exp_CALC_POLICY_ACTIVITY.NAMED_INS as NAMED_INS,
exp_CALC_POLICY_ACTIVITY.ADDL_NMD_INS as ADDL_NMD_INS,
exp_CALC_POLICY_ACTIVITY.ADDR1 as ADDR1,
exp_CALC_POLICY_ACTIVITY.ADDR2 as ADDR2,
exp_CALC_POLICY_ACTIVITY.CITY as CITY,
exp_CALC_POLICY_ACTIVITY.ADDR_STATE as ADDR_STATE,
exp_CALC_POLICY_ACTIVITY.ZIP as ZIP,
exp_CALC_POLICY_ACTIVITY.DIV_S3_POL_SYM as DIV_S3_POL_SYM,
exp_CALC_POLICY_ACTIVITY.DIV_S3_POL_NBR as DIV_S3_POL_NBR,
exp_CALC_POLICY_ACTIVITY.DIV_MAN_IND as DIV_MAN_IND,
exp_CALC_POLICY_ACTIVITY.DIV_POL_LAPSE as DIV_POL_LAPSE,
exp_CALC_POLICY_ACTIVITY.NR as NR,
exp_CALC_POLICY_ACTIVITY.INF_UNIT_CTS as INF_UNIT_CTS,
exp_CALC_POLICY_ACTIVITY.FEED_DT as FEED_DT,
exp_CALC_POLICY_ACTIVITY.out_POLICY_ACTIVITY as POLICY_ACTIVITY,
exp_CALC_POLICY_ACTIVITY.INFORCE_IND as INFORCE_IND,
exp_CALC_POLICY_ACTIVITY.LOB_GROUP as LOB_GROUP,
CASE WHEN LKP_TARGET1.STATUS_lkup IS NULL THEN ''NEW'' ELSE ''REJ'' END as out_CHK,
exp_CALC_POLICY_ACTIVITY.OGN_POLICY_ACTIVITY as OGN_POLICY_ACTIVITY,
exp_CALC_POLICY_ACTIVITY.source_record_id
FROM
exp_CALC_POLICY_ACTIVITY
INNER JOIN LKP_TARGET1 ON exp_CALC_POLICY_ACTIVITY.source_record_id = LKP_TARGET1.source_record_id
);


-- Component exp_FILTER, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE exp_FILTER AS
(
SELECT
exp_CHECK.POL_SYMBOL as POL_SYMBOL,
exp_CHECK.POL_NBR as POL_NBR,
exp_CHECK.COMPANY as COMPANY,
exp_CHECK.STATE as STATE,
exp_CHECK.STATUS as STATUS,
exp_CHECK.AGENT as AGENT,
exp_CHECK.SERV_CNTR as SERV_CNTR,
exp_CHECK.EXP_DT_CYMD as EXP_DT_CYMD,
exp_CHECK.DIST_REGION as DIST_REGION,
exp_CHECK.ADD_COV as ADD_COV,
exp_CHECK.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE,
exp_CHECK.SM_POL_INDICATOR as SM_POL_INDICATOR,
exp_CHECK.REASON as REASON,
exp_CHECK.TOT_PREM as TOT_PREM,
exp_CHECK.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL,
exp_CHECK.EFF_DT_CYMD as EFF_DT_CYMD,
exp_CHECK.MEMBER_TYPE as MEMBER_TYPE,
exp_CHECK.MEMBER_NBR as MEMBER_NBR,
exp_CHECK.NAMED_INS as NAMED_INS,
exp_CHECK.ADDL_NMD_INS as ADDL_NMD_INS,
exp_CHECK.ADDR1 as ADDR1,
exp_CHECK.ADDR2 as ADDR2,
exp_CHECK.CITY as CITY,
exp_CHECK.ADDR_STATE as ADDR_STATE,
exp_CHECK.ZIP as ZIP,
exp_CHECK.DIV_S3_POL_SYM as DIV_S3_POL_SYM,
exp_CHECK.DIV_S3_POL_NBR as DIV_S3_POL_NBR,
exp_CHECK.DIV_MAN_IND as DIV_MAN_IND,
exp_CHECK.DIV_POL_LAPSE as DIV_POL_LAPSE,
exp_CHECK.NR as NR,
exp_CHECK.INF_UNIT_CTS as INF_UNIT_CTS,
exp_CHECK.FEED_DT as FEED_DT,
exp_CHECK.POLICY_ACTIVITY as POLICY_ACTIVITY,
exp_CHECK.INFORCE_IND as INFORCE_IND,
exp_CHECK.LOB_GROUP as LOB_GROUP,
exp_CHECK.out_CHK as out_CHK,
exp_CHECK.OGN_POLICY_ACTIVITY as OGN_POLICY_ACTIVITY,
exp_CHECK.source_record_id
FROM
exp_CHECK
WHERE exp_CHECK.out_CHK = ''NEW''
);


-- Component Shortcut_to_STG_MULTILINE_POLSTAT, Type TARGET 
INSERT INTO DB_T_STAG_PROD.STG_MULTILINE_POLSTAT
(
POL_SYMBOL,
POL_NBR,
COMPANY,
STATE,
STATUS,
AGENT,
SERV_CNTR,
DIST_REGION,
EFF_DT_CYMD,
EXP_DT_CYMD,
ADD_COV,
FIRE_CONVERT_TRANS_CODE,
SM_POL_INDICATOR,
REASON,
TOT_PREM,
FIRE_HOME_TYPE_POL,
MEMBER_TYPE,
MEMBER_NBR,
NAMED_INS,
ADDL_NMD_INS,
ADDR1,
ADDR2,
CITY,
ADDR_STATE,
ZIP,
DIV_S3_POL_SYM,
DIV_S3_POL_NBR,
DIV_MAN_IND,
DIV_POL_LAPSE,
NR,
INF_UNIT_CTS,
POLICY_ACTIVITY,
OGN_POLICY_ACTIVITY,
INFORCE_IND,
LOB_GROUP,
FEED_DT
)
SELECT
exp_FILTER.POL_SYMBOL as POL_SYMBOL,
exp_FILTER.POL_NBR as POL_NBR,
exp_FILTER.COMPANY as COMPANY,
exp_FILTER.STATE as STATE,
exp_FILTER.STATUS as STATUS,
exp_FILTER.AGENT as AGENT,
exp_FILTER.SERV_CNTR as SERV_CNTR,
exp_FILTER.DIST_REGION as DIST_REGION,
exp_FILTER.EFF_DT_CYMD as EFF_DT_CYMD,
exp_FILTER.EXP_DT_CYMD as EXP_DT_CYMD,
exp_FILTER.ADD_COV as ADD_COV,
exp_FILTER.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE,
exp_FILTER.SM_POL_INDICATOR as SM_POL_INDICATOR,
exp_FILTER.REASON as REASON,
exp_FILTER.TOT_PREM as TOT_PREM,
exp_FILTER.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL,
exp_FILTER.MEMBER_TYPE as MEMBER_TYPE,
exp_FILTER.MEMBER_NBR as MEMBER_NBR,
exp_FILTER.NAMED_INS as NAMED_INS,
exp_FILTER.ADDL_NMD_INS as ADDL_NMD_INS,
exp_FILTER.ADDR1 as ADDR1,
exp_FILTER.ADDR2 as ADDR2,
exp_FILTER.CITY as CITY,
exp_FILTER.ADDR_STATE as ADDR_STATE,
exp_FILTER.ZIP as ZIP,
exp_FILTER.DIV_S3_POL_SYM as DIV_S3_POL_SYM,
exp_FILTER.DIV_S3_POL_NBR as DIV_S3_POL_NBR,
exp_FILTER.DIV_MAN_IND as DIV_MAN_IND,
exp_FILTER.DIV_POL_LAPSE as DIV_POL_LAPSE,
exp_FILTER.NR as NR,
exp_FILTER.INF_UNIT_CTS as INF_UNIT_CTS,
exp_FILTER.POLICY_ACTIVITY as POLICY_ACTIVITY,
exp_FILTER.OGN_POLICY_ACTIVITY as OGN_POLICY_ACTIVITY,
exp_FILTER.INFORCE_IND as INFORCE_IND,
exp_FILTER.LOB_GROUP as LOB_GROUP,
exp_FILTER.FEED_DT as FEED_DT
FROM
exp_FILTER;


END; ';