-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LIFEPOLS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE PMMAPPINGNAME varchar;
PROJ_ID varchar;
BATCH_ACTIVE_IND varchar;
BEGIN 

PMMAPPINGNAME:=''M_LIFEPOLS'';  
BATCH_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 

-- Component LKP_STG_MEMBXREF_TRIGGER, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_STG_MEMBXREF_TRIGGER AS
(
SELECT
TABLENAME,
FEED_DT
FROM DB_T_stag_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER
);


-- PIPELINE START FOR 1

-- Component SQ_LIFEPOLS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_LIFEPOLS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as CHG_EFF_DT,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT LIFEPOLS.SC_POLICY_NUM ,LIFEPOLS.CHG_EFF_DT 
FROM
 DB_T_CORE_MEMBXREF_PROD.LIFEPOLS WHERE CHG_EXP_DT = CAST(''9999-12-31'' AS DATE ) 
) SRC
)
);


-- Component exp_ASSIGN_DUMMY_TG, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ASSIGN_DUMMY_TG AS
(
SELECT
SQ_LIFEPOLS.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_LIFEPOLS.CHG_EFF_DT as CHG_EFF_DT,
''LIFEPOLS'' as var_TABLENAME,
LKP_1.FEED_DT /* replaced lookup LKP_STG_MEMBXREF_TRIGGER */ as var_FEED_DT,
var_FEED_DT as out_FEED_DT,
SQ_LIFEPOLS.source_record_id,
row_number() over (partition by SQ_LIFEPOLS.source_record_id order by SQ_LIFEPOLS.source_record_id) as RNK
FROM
SQ_LIFEPOLS
LEFT JOIN LKP_STG_MEMBXREF_TRIGGER LKP_1 ON LKP_1.TABLENAME = var_TABLENAME
QUALIFY RNK = 1
);


-- Component LKP_STG_LIFEPOLS, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_STG_LIFEPOLS AS
(
SELECT
LKP.SC_POLICY_NUM,
exp_ASSIGN_DUMMY_TG.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_ASSIGN_DUMMY_TG.source_record_id ORDER BY LKP.SC_POLICY_NUM asc) RNK
FROM
exp_ASSIGN_DUMMY_TG
LEFT JOIN (
SELECT LTRIM(RTRIM(STG_LIFEPOLS.SC_POLICY_NUM)) as SC_POLICY_NUM FROM DB_T_stag_MEMBXREF_PROD.STG_LIFEPOLS
WHERE
 STG_LIFEPOLS. LOAD_DT=(SELECT FEED_DT FROM DB_T_stag_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER WHERE TABLENAME=''LIFEPOLS'')
) LKP ON LKP.SC_POLICY_NUM = exp_ASSIGN_DUMMY_TG.SC_POLICY_NUM
QUALIFY RNK = 1
);


-- Component fil_EXPIRED_POLS, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE fil_EXPIRED_POLS AS
(
SELECT
LKP_STG_LIFEPOLS.SC_POLICY_NUM as SC_POLICY_NUM_tgt,
exp_ASSIGN_DUMMY_TG.CHG_EFF_DT as CHG_EFF_DT,
exp_ASSIGN_DUMMY_TG.SC_POLICY_NUM as SC_POLICY_NUM_src,
exp_ASSIGN_DUMMY_TG.out_FEED_DT as LOAD_DT,
exp_ASSIGN_DUMMY_TG.source_record_id
FROM
exp_ASSIGN_DUMMY_TG
LEFT JOIN LKP_STG_LIFEPOLS ON exp_ASSIGN_DUMMY_TG.source_record_id = LKP_STG_LIFEPOLS.source_record_id
WHERE LKP_STG_LIFEPOLS.SC_POLICY_NUM IS NULL
);


-- Component exp_INPUT_ECTL_FIELDS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_INPUT_ECTL_FIELDS AS
(
SELECT
fil_EXPIRED_POLS.CHG_EFF_DT as CHG_EFF_DT,
fil_EXPIRED_POLS.SC_POLICY_NUM_src as SC_POLICY_NUM_src,
LTRIM ( RTRIM ( :PMMappingName ) ) as out_PROJ_NAME,
:PROJ_ID as out_PROJ_ID,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
:PROJ_ID as IN_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as IN_BATCH_ACTIVE_IND,
''m_STG_FIN_CLM'' IN_PRGM_NM,
null IN_TABLE_NM,
''UPD'' as ECTL_TX_CD,
TO_CHAR ( ( DATE_PART(''YYYY'', TO_TIMESTAMP(fil_EXPIRED_POLS.LOAD_DT)) * 10000 ) + ( DATE_PART(''MM'', TO_TIMESTAMP(fil_EXPIRED_POLS.LOAD_DT)) * 100 ) + 1 ) as var_FIRST_DAY_EFF_DT,
 TO_DATE ( var_FIRST_DAY_EFF_DT  )  - 1  as var_CHG_EXP_DT_NEW,
CASE WHEN fil_EXPIRED_POLS.CHG_EFF_DT >= var_CHG_EXP_DT_NEW THEN fil_EXPIRED_POLS.CHG_EFF_DT ELSE var_CHG_EXP_DT_NEW END as out_CHG_EXP_DT_NEW,
CURRENT_TIMESTAMP as out_ECTL_END_DATE,
fil_EXPIRED_POLS.source_record_id
FROM
fil_EXPIRED_POLS
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''exp_INPUT_ECTL_FIELDS'');

-- Component upd_LIFEPOLS_EXPIRED_POLS, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_LIFEPOLS_EXPIRED_POLS AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
--''1'' as ECTL_BATCH_ID,
--''1900-01-01'' as ECTL_MODIFY_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1.out_ORIG_INS_TS as ECTL_MODIFY_TS,
exp_INPUT_ECTL_FIELDS.out_ECTL_END_DATE as ECTL_END_DATE,
exp_INPUT_ECTL_FIELDS.SC_POLICY_NUM_src as SC_POLICY_NUM,
exp_INPUT_ECTL_FIELDS.CHG_EFF_DT as CHG_EFF_DT,
exp_INPUT_ECTL_FIELDS.ECTL_TX_CD as ECTL_TX_CD,
exp_INPUT_ECTL_FIELDS.out_CHG_EXP_DT_NEW as CHG_EXP_DT,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_INPUT_ECTL_FIELDS
LEFT JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1 ON exp_INPUT_ECTL_FIELDS.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1.source_record_id
);


-- Component LIFEPOLS_UPD_EXPIRED_POLS, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_core_MEMBXREF_PROD.LIFEPOLS
USING upd_LIFEPOLS_EXPIRED_POLS
ON (DB_T_core_MEMBXREF_PROD.LIFEPOLS.SC_POLICY_NUM = upd_LIFEPOLS_EXPIRED_POLS.SC_POLICY_NUM AND DB_T_core_MEMBXREF_PROD.LIFEPOLS.CHG_EFF_DT = upd_LIFEPOLS_EXPIRED_POLS.CHG_EFF_DT)
WHEN MATCHED THEN UPDATE SET
ECTL_BATCH_ID = upd_LIFEPOLS_EXPIRED_POLS.ECTL_BATCH_ID,ECTL_END_DATE =upd_LIFEPOLS_EXPIRED_POLS.ECTL_END_DATE,
ECTL_MODIFY_TS = upd_LIFEPOLS_EXPIRED_POLS.ECTL_MODIFY_TS,
ECTL_TX_CD = upd_LIFEPOLS_EXPIRED_POLS.ECTL_TX_CD,
CHG_EXP_DT = upd_LIFEPOLS_EXPIRED_POLS.CHG_EXP_DT;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component sq_STG_LIFEPOLS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_LIFEPOLS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_DWNLD_PRIORITY,
$2 as SC_SERVICE_CENTER,
$3 as SC_POLICY_NUM,
$4 as SC_FLT_ITEM,
$5 as SC_FILE_TYPE,
$6 as SC_REC_TRANS_CODE,
$7 as SC_TRANS_DATE,
$8 as SC_TRANS_TYPE,
$9 as LF_ALPHA_CODE,
$10 as LF_STATUS,
$11 as LF_MODE,
$12 as LF_INSURED_SSAN,
$13 as LF_MEMBERSHIP,
$14 as LF_NFO_OPTION,
$15 as LF_INSURED_NAME,
$16 as LF_ADDRESS_1,
$17 as LF_ADDRESS_2,
$18 as LF_ADDRESS_3,
$19 as LF_PAYOR_NAME,
$20 as LF_OWNER_NAME,
$21 as LF_MODAL_PREM,
$22 as LF_ISSUE_DATE,
$23 as LF_APPL_DATE,
$24 as LF_BIRTH_DATE,
$25 as LF_PAC_DRAW_DAY,
$26 as LF_DUE_USE_CD,
$27 as LF_REQUIRE_SW,
$28 as LF_PAC_BANK_CD,
$29 as LF_PAC_ACCT_NO,
$30 as LF_FORM,
$31 as LF_VOLUME,
$32 as LF_APP_PREM,
$33 as LF_OVER_SHORT,
$34 as LF_UNDERWRITER,
$35 as LF_PLAN_NAME,
$36 as LF_POLICY_FEE,
$37 as LF_FUND_BALANCE,
$38 as LF_SURR_VALUE,
$39 as LF_DEP_FUND,
$40 as LF_PD_TO_DATE,
$41 as LF_LOAN_AMOUNT,
$42 as LF_DIV_ON_DEP,
$43 as LF_PAIDUP_ADD,
$44 as LF_CASH_VAL_PUA,
$45 as LF_ANNUAL_PREM,
$46 as LF_AGENT_NO,
$47 as LF_LOAN_VALUE,
$48 as LF_PHY_ISS,
$49 as LF_CANC_REASON_CDE,
$50 as LF_ISS_AGE,
$51 as LF_2ND_INS_NAME,
$52 as LF_OWNER_ADDRESS_1,
$53 as LF_OWNER_ADDRESS_2,
$54 as LF_OWNER_ADDRESS_3,
$55 as LF_PAYOR_ADDRESS_1,
$56 as LF_PAYOR_ADDRESS_2,
$57 as LF_PAYOR_ADDRESS_3,
$58 as LF_OWNER_SSAN,
$59 as LF_LAST_ANN_DATE,
$60 as LF_FUND_BAL_LST_AN,
$61 as LF_LOAN_CALC_DATE,
$62 as LF_SURR_CHG_LST_AN,
$63 as LF_POL_ANNUAL_PREM,
$64 as LF_2ND_INS_DOB,
$65 as LF_2ND_INS_ISS_AGE,
$66 as LF_INS_ISS_AGE,
$67 as LF_INS_TOBACCO_USE,
$68 as LF_INS_SEX_CODE,
$69 as LF_2ND_INS_SEX_CDE,
$70 as LF_DEATH_BENE_OPT,
$71 as LF_2ND_INS_SSAN,
$72 as LF_RESTRICT_CODE,
$73 as LF_LOAN_INT_RATE,
$74 as LF_LOAN_INT_ACCRU,
$75 as LF_NEXT_AN_CAS_VAL,
$76 as LF_DISPLAY_SW,
$77 as LOAD_DT,
$78 as FEED_IND,
$79 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT STG_LIFEPOLS.SC_DWNLD_PRIORITY AS SC_DWNLD_PRIORITY,
STG_LIFEPOLS.SC_SERVICE_CENTER AS SC_SERVICE_CENTER,
TRIM(STG_LIFEPOLS.SC_POLICY_NUM) AS SC_POLICY_NUM,
TRIM(STG_LIFEPOLS.SC_FLT_ITEM) AS SC_FLT_ITEM,
STG_LIFEPOLS.SC_FILE_TYPE AS SC_FILE_TYPE,
STG_LIFEPOLS.SC_REC_TRANS_CODE AS SC_REC_TRANS_CODE,
STG_LIFEPOLS.SC_TRANS_DATE AS SC_TRANS_DATE,
STG_LIFEPOLS.SC_TRANS_TYPE AS SC_TRANS_TYPE,
TRIM(STG_LIFEPOLS.LF_ALPHA_CODE) AS LF_ALPHA_CODE,
TRIM(STG_LIFEPOLS.LF_STATUS) AS LF_STATUS,
STG_LIFEPOLS.LF_MODE AS LF_MODE,
TRIM(STG_LIFEPOLS.LF_INSURED_SSAN) AS LF_INSURED_SSAN,
TRIM(STG_LIFEPOLS.LF_MEMBERSHIP) AS LF_MEMBERSHIP,
TRIM(STG_LIFEPOLS.LF_NFO_OPTION) AS LF_NFO_OPTION,
TRIM(STG_LIFEPOLS.LF_INSURED_NAME) AS LF_INSURED_NAME,
TRIM(STG_LIFEPOLS.LF_ADDRESS_1) AS LF_ADDRESS_1,
TRIM(STG_LIFEPOLS.LF_ADDRESS_2) AS LF_ADDRESS_2,
TRIM(STG_LIFEPOLS.LF_ADDRESS_3) AS LF_ADDRESS_3,
TRIM(STG_LIFEPOLS.LF_PAYOR_NAME) AS LF_PAYOR_NAME,
TRIM(STG_LIFEPOLS.LF_OWNER_NAME) AS LF_OWNER_NAME,
STG_LIFEPOLS.LF_MODAL_PREM AS LF_MODAL_PREM,
TRIM(STG_LIFEPOLS.LF_ISSUE_DATE) AS LF_ISSUE_DATE,
TRIM(STG_LIFEPOLS.LF_APPL_DATE) AS LF_APPL_DATE,
TRIM(STG_LIFEPOLS.LF_BIRTH_DATE) AS LF_BIRTH_DATE,
TRIM(STG_LIFEPOLS.LF_PAC_DRAW_DAY) AS LF_PAC_DRAW_DAY,
TRIM(STG_LIFEPOLS.LF_DUE_USE_CD) AS LF_DUE_USE_CD,
TRIM(STG_LIFEPOLS.LF_REQUIRE_SW) AS LF_REQUIRE_SW,
TRIM(STG_LIFEPOLS.LF_PAC_BANK_CD) AS LF_PAC_BANK_CD,
TRIM(STG_LIFEPOLS.LF_PAC_ACCT_NO) AS LF_PAC_ACCT_NO,
TRIM(STG_LIFEPOLS.LF_FORM) AS LF_FORM,
STG_LIFEPOLS.LF_VOLUME AS LF_VOLUME,
STG_LIFEPOLS.LF_APP_PREM AS LF_APP_PREM,
STG_LIFEPOLS.LF_OVER_SHORT AS LF_OVER_SHORT,
TRIM(STG_LIFEPOLS.LF_UNDERWRITER) AS LF_UNDERWRITER,
TRIM(STG_LIFEPOLS.LF_PLAN_NAME) AS LF_PLAN_NAME,
STG_LIFEPOLS.LF_POLICY_FEE AS LF_POLICY_FEE,
STG_LIFEPOLS.LF_FUND_BALANCE AS LF_FUND_BALANCE,
STG_LIFEPOLS.LF_SURR_VALUE AS LF_SURR_VALUE,
STG_LIFEPOLS.LF_DEP_FUND AS LF_DEP_FUND,
TRIM(STG_LIFEPOLS.LF_PD_TO_DATE) AS LF_PD_TO_DATE,
STG_LIFEPOLS.LF_LOAN_AMOUNT AS LF_LOAN_AMOUNT,
STG_LIFEPOLS.LF_DIV_ON_DEP AS LF_DIV_ON_DEP,
STG_LIFEPOLS.LF_PAIDUP_ADD AS LF_PAIDUP_ADD,
STG_LIFEPOLS.LF_CASH_VAL_PUA AS LF_CASH_VAL_PUA,
STG_LIFEPOLS.LF_ANNUAL_PREM AS LF_ANNUAL_PREM,
STG_LIFEPOLS.LF_AGENT_NO AS LF_AGENT_NO,
STG_LIFEPOLS.LF_LOAN_VALUE AS LF_LOAN_VALUE,
TRIM(STG_LIFEPOLS.LF_PHY_ISS) AS LF_PHY_ISS,
TRIM(STG_LIFEPOLS.LF_CANC_REASON_CDE) AS LF_CANC_REASON_CDE,
TRIM(STG_LIFEPOLS.LF_ISS_AGE) AS LF_ISS_AGE,
TRIM(STG_LIFEPOLS.LF_2ND_INS_NAME) AS LF_2ND_INS_NAME,
TRIM(STG_LIFEPOLS.LF_OWNER_ADDRESS_1) AS LF_OWNER_ADDRESS_1,
TRIM(STG_LIFEPOLS.LF_OWNER_ADDRESS_2) AS LF_OWNER_ADDRESS_2,
TRIM(STG_LIFEPOLS.LF_OWNER_ADDRESS_3) AS LF_OWNER_ADDRESS_3,
TRIM(STG_LIFEPOLS.LF_PAYOR_ADDRESS_1) AS LF_PAYOR_ADDRESS_1,
TRIM(STG_LIFEPOLS.LF_PAYOR_ADDRESS_2) AS LF_PAYOR_ADDRESS_2,
TRIM(STG_LIFEPOLS.LF_PAYOR_ADDRESS_3) AS LF_PAYOR_ADDRESS_3,
TRIM(STG_LIFEPOLS.LF_OWNER_SSAN) AS LF_OWNER_SSAN,
TRIM(STG_LIFEPOLS.LF_LAST_ANN_DATE) AS LF_LAST_ANN_DATE,
STG_LIFEPOLS.LF_FUND_BAL_LST_AN AS LF_FUND_BAL_LST_AN,
TRIM(STG_LIFEPOLS.LF_LOAN_CALC_DATE) AS LF_LOAN_CALC_DATE,
STG_LIFEPOLS.LF_SURR_CHG_LST_AN AS LF_SURR_CHG_LST_AN,
STG_LIFEPOLS.LF_POL_ANNUAL_PREM AS LF_POL_ANNUAL_PREM,
TRIM(STG_LIFEPOLS.LF_2ND_INS_DOB) AS LF_2ND_INS_DOB,
TRIM(STG_LIFEPOLS.LF_2ND_INS_ISS_AGE) AS LF_2ND_INS_ISS_AGE,
TRIM(STG_LIFEPOLS.LF_INS_ISS_AGE) AS LF_INS_ISS_AGE,
TRIM(STG_LIFEPOLS.LF_INS_TOBACCO_USE) AS LF_INS_TOBACCO_USE,
TRIM(STG_LIFEPOLS.LF_INS_SEX_CODE) AS LF_INS_SEX_CODE,
TRIM(STG_LIFEPOLS.LF_2ND_INS_SEX_CDE) AS LF_2ND_INS_SEX_CDE,
TRIM(STG_LIFEPOLS.LF_DEATH_BENE_OPT) AS LF_DEATH_BENE_OPT,
TRIM(STG_LIFEPOLS.LF_2ND_INS_SSAN) AS LF_2ND_INS_SSAN,
TRIM(STG_LIFEPOLS.LF_RESTRICT_CODE) AS LF_RESTRICT_CODE,
STG_LIFEPOLS.LF_LOAN_INT_RATE AS LF_LOAN_INT_RATE,
STG_LIFEPOLS.LF_LOAN_INT_ACCRU AS LF_LOAN_INT_ACCRU,
STG_LIFEPOLS.LF_NEXT_AN_CAS_VAL AS LF_NEXT_AN_CAS_VAL,
TRIM(STG_LIFEPOLS.LF_DISPLAY_SW) AS LF_DISPLAY_SW,
STG_LIFEPOLS.LOAD_DT AS LOAD_DT,
TRIM(STG_LIFEPOLS.FEED_IND) AS FEED_IND
FROM
 DB_T_STAG_MEMBXREF_PROD.STG_LIFEPOLS
WHERE LOAD_DT=(SELECT FEED_DT FROM DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER WHERE TABLENAME=''LIFEPOLS'')
) SRC
)
);


-- Component exp_TO_DATE_ISSUE_DATE, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_TO_DATE_ISSUE_DATE AS
(
SELECT
sq_STG_LIFEPOLS.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
sq_STG_LIFEPOLS.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
sq_STG_LIFEPOLS.SC_POLICY_NUM as SC_POLICY_NUM,
sq_STG_LIFEPOLS.SC_FLT_ITEM as SC_FLT_ITEM,
sq_STG_LIFEPOLS.SC_FILE_TYPE as SC_FILE_TYPE,
sq_STG_LIFEPOLS.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
sq_STG_LIFEPOLS.SC_TRANS_DATE as SC_TRANS_DATE,
sq_STG_LIFEPOLS.SC_TRANS_TYPE as SC_TRANS_TYPE,
sq_STG_LIFEPOLS.LF_ALPHA_CODE as LF_ALPHA_CODE,
sq_STG_LIFEPOLS.LF_STATUS as LF_STATUS,
sq_STG_LIFEPOLS.LF_MODE as LF_MODE,
sq_STG_LIFEPOLS.LF_INSURED_SSAN as LF_INSURED_SSAN,
sq_STG_LIFEPOLS.LF_MEMBERSHIP as LF_MEMBERSHIP,
sq_STG_LIFEPOLS.LF_NFO_OPTION as LF_NFO_OPTION,
sq_STG_LIFEPOLS.LF_INSURED_NAME as LF_INSURED_NAME,
sq_STG_LIFEPOLS.LF_ADDRESS_1 as LF_ADDRESS_1,
sq_STG_LIFEPOLS.LF_ADDRESS_2 as LF_ADDRESS_2,
sq_STG_LIFEPOLS.LF_ADDRESS_3 as LF_ADDRESS_3,
sq_STG_LIFEPOLS.LF_PAYOR_NAME as LF_PAYOR_NAME,
sq_STG_LIFEPOLS.LF_OWNER_NAME as LF_OWNER_NAME,
sq_STG_LIFEPOLS.LF_MODAL_PREM as LF_MODAL_PREM,
CASE WHEN sq_STG_LIFEPOLS.LF_ISSUE_DATE IS NULL THEN NULL ELSE TO_DATE ( sq_STG_LIFEPOLS.LF_ISSUE_DATE , ''YYYY-MM-DD'' ) END as out_LF_ISSUE_DATE,
sq_STG_LIFEPOLS.LF_APPL_DATE as LF_APPL_DATE,
sq_STG_LIFEPOLS.LF_BIRTH_DATE as LF_BIRTH_DATE,
sq_STG_LIFEPOLS.LF_PAC_DRAW_DAY as LF_PAC_DRAW_DAY,
sq_STG_LIFEPOLS.LF_DUE_USE_CD as LF_DUE_USE_CD,
sq_STG_LIFEPOLS.LF_REQUIRE_SW as LF_REQUIRE_SW,
sq_STG_LIFEPOLS.LF_PAC_BANK_CD as LF_PAC_BANK_CD,
sq_STG_LIFEPOLS.LF_PAC_ACCT_NO as LF_PAC_ACCT_NO,
sq_STG_LIFEPOLS.LF_FORM as LF_FORM,
sq_STG_LIFEPOLS.LF_VOLUME as LF_VOLUME,
sq_STG_LIFEPOLS.LF_APP_PREM as LF_APP_PREM,
sq_STG_LIFEPOLS.LF_OVER_SHORT as LF_OVER_SHORT,
sq_STG_LIFEPOLS.LF_UNDERWRITER as LF_UNDERWRITER,
sq_STG_LIFEPOLS.LF_PLAN_NAME as LF_PLAN_NAME,
sq_STG_LIFEPOLS.LF_POLICY_FEE as LF_POLICY_FEE,
sq_STG_LIFEPOLS.LF_FUND_BALANCE as LF_FUND_BALANCE,
sq_STG_LIFEPOLS.LF_SURR_VALUE as LF_SURR_VALUE,
sq_STG_LIFEPOLS.LF_DEP_FUND as LF_DEP_FUND,
sq_STG_LIFEPOLS.LF_PD_TO_DATE as LF_PD_TO_DATE,
sq_STG_LIFEPOLS.LF_LOAN_AMOUNT as LF_LOAN_AMOUNT,
sq_STG_LIFEPOLS.LF_DIV_ON_DEP as LF_DIV_ON_DEP,
sq_STG_LIFEPOLS.LF_PAIDUP_ADD as LF_PAIDUP_ADD,
sq_STG_LIFEPOLS.LF_CASH_VAL_PUA as LF_CASH_VAL_PUA,
sq_STG_LIFEPOLS.LF_ANNUAL_PREM as LF_ANNUAL_PREM,
sq_STG_LIFEPOLS.LF_AGENT_NO as LF_AGENT_NO,
sq_STG_LIFEPOLS.LF_LOAN_VALUE as LF_LOAN_VALUE,
sq_STG_LIFEPOLS.LF_PHY_ISS as LF_PHY_ISS,
sq_STG_LIFEPOLS.LF_CANC_REASON_CDE as LF_CANC_REASON_CDE,
sq_STG_LIFEPOLS.LF_ISS_AGE as LF_ISS_AGE,
sq_STG_LIFEPOLS.LF_2ND_INS_NAME as LF_2ND_INS_NAME,
sq_STG_LIFEPOLS.LF_OWNER_ADDRESS_1 as LF_OWNER_ADDRESS_1,
sq_STG_LIFEPOLS.LF_OWNER_ADDRESS_2 as LF_OWNER_ADDRESS_2,
sq_STG_LIFEPOLS.LF_OWNER_ADDRESS_3 as LF_OWNER_ADDRESS_3,
sq_STG_LIFEPOLS.LF_PAYOR_ADDRESS_1 as LF_PAYOR_ADDRESS_1,
sq_STG_LIFEPOLS.LF_PAYOR_ADDRESS_2 as LF_PAYOR_ADDRESS_2,
sq_STG_LIFEPOLS.LF_PAYOR_ADDRESS_3 as LF_PAYOR_ADDRESS_3,
sq_STG_LIFEPOLS.LF_OWNER_SSAN as LF_OWNER_SSAN,
sq_STG_LIFEPOLS.LF_LAST_ANN_DATE as LF_LAST_ANN_DATE,
sq_STG_LIFEPOLS.LF_FUND_BAL_LST_AN as LF_FUND_BAL_LST_AN,
sq_STG_LIFEPOLS.LF_LOAN_CALC_DATE as LF_LOAN_CALC_DATE,
sq_STG_LIFEPOLS.LF_SURR_CHG_LST_AN as LF_SURR_CHG_LST_AN,
sq_STG_LIFEPOLS.LF_POL_ANNUAL_PREM as LF_POL_ANNUAL_PREM,
sq_STG_LIFEPOLS.LF_2ND_INS_DOB as LF_2ND_INS_DOB,
sq_STG_LIFEPOLS.LF_2ND_INS_ISS_AGE as LF_2ND_INS_ISS_AGE,
sq_STG_LIFEPOLS.LF_INS_ISS_AGE as LF_INS_ISS_AGE,
sq_STG_LIFEPOLS.LF_INS_TOBACCO_USE as LF_INS_TOBACCO_USE,
sq_STG_LIFEPOLS.LF_INS_SEX_CODE as LF_INS_SEX_CODE,
sq_STG_LIFEPOLS.LF_2ND_INS_SEX_CDE as LF_2ND_INS_SEX_CDE,
sq_STG_LIFEPOLS.LF_DEATH_BENE_OPT as LF_DEATH_BENE_OPT,
sq_STG_LIFEPOLS.LF_2ND_INS_SSAN as LF_2ND_INS_SSAN,
sq_STG_LIFEPOLS.LF_RESTRICT_CODE as LF_RESTRICT_CODE,
sq_STG_LIFEPOLS.LF_LOAN_INT_RATE as LF_LOAN_INT_RATE,
sq_STG_LIFEPOLS.LF_LOAN_INT_ACCRU as LF_LOAN_INT_ACCRU,
sq_STG_LIFEPOLS.LF_NEXT_AN_CAS_VAL as LF_NEXT_AN_CAS_VAL,
sq_STG_LIFEPOLS.LF_DISPLAY_SW as LF_DISPLAY_SW,
sq_STG_LIFEPOLS.LOAD_DT as LOAD_DT,
sq_STG_LIFEPOLS.FEED_IND as FEED_IND,
sq_STG_LIFEPOLS.source_record_id
FROM
sq_STG_LIFEPOLS
);


-- Component LKP_LIFEPOLS, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_LIFEPOLS AS
(
SELECT
LKP.SC_DWNLD_PRIORITY,
LKP.SC_SERVICE_CENTER,
LKP.SC_POLICY_NUM,
LKP.CHG_EFF_DT,
LKP.SC_FLT_ITEM,
LKP.SC_FILE_TYPE,
LKP.SC_REC_TRANS_CODE,
LKP.SC_TRANS_DATE,
LKP.SC_TRANS_TYPE,
LKP.LF_ALPHA_CODE,
LKP.LF_STATUS,
LKP.LF_MODE,
LKP.LF_INSURED_SSAN,
LKP.LF_MEMBERSHIP,
LKP.LF_NFO_OPTION,
LKP.LF_INSURED_NAME,
LKP.LF_ADDRESS_1,
LKP.LF_ADDRESS_2,
LKP.LF_ADDRESS_3,
LKP.LF_PAYOR_NAME,
LKP.LF_OWNER_NAME,
LKP.LF_MODAL_PREM,
LKP.LF_ISSUE_DATE,
LKP.LF_APPL_DATE,
LKP.LF_BIRTH_DATE,
LKP.LF_PAC_DRAW_DAY,
LKP.LF_DUE_USE_CD,
LKP.LF_REQUIRE_SW,
LKP.LF_PAC_BANK_CD,
LKP.LF_PAC_ACCT_NO,
LKP.LF_FORM,
LKP.LF_VOLUME,
LKP.LF_APP_PREM,
LKP.LF_OVER_SHORT,
LKP.LF_UNDERWRITER,
LKP.LF_PLAN_NAME,
LKP.LF_POLICY_FEE,
LKP.LF_FUND_BALANCE,
LKP.LF_SURR_VALUE,
LKP.LF_DEP_FUND,
LKP.LF_PD_TO_DATE,
LKP.LF_LOAN_AMOUNT,
LKP.LF_DIV_ON_DEP,
LKP.LF_PAIDUP_ADD,
LKP.LF_CASH_VAL_PUA,
LKP.LF_ANNUAL_PREM,
LKP.LF_AGENT_NO,
LKP.LF_LOAN_VALUE,
LKP.LF_PHY_ISS,
LKP.LF_CANC_REASON_CDE,
LKP.LF_ISS_AGE,
LKP.LF_2ND_INS_NAME,
LKP.LF_OWNER_ADDRESS_1,
LKP.LF_OWNER_ADDRESS_2,
LKP.LF_OWNER_ADDRESS_3,
LKP.LF_PAYOR_ADDRESS_1,
LKP.LF_PAYOR_ADDRESS_2,
LKP.LF_PAYOR_ADDRESS_3,
LKP.LF_OWNER_SSAN,
LKP.LF_LAST_ANN_DATE,
LKP.LF_FUND_BAL_LST_AN,
LKP.LF_LOAN_CALC_DATE,
LKP.LF_SURR_CHG_LST_AN,
LKP.LF_POL_ANNUAL_PREM,
LKP.LF_2ND_INS_DOB,
LKP.LF_2ND_INS_ISS_AGE,
LKP.LF_INS_ISS_AGE,
LKP.LF_INS_TOBACCO_USE,
LKP.LF_INS_SEX_CODE,
LKP.LF_2ND_INS_SEX_CDE,
LKP.LF_DEATH_BENE_OPT,
LKP.LF_2ND_INS_SSAN,
LKP.LF_RESTRICT_CODE,
LKP.LF_LOAN_INT_RATE,
LKP.LF_LOAN_INT_ACCRU,
LKP.LF_NEXT_AN_CAS_VAL,
LKP.LF_DISPLAY_SW,
LKP.FEED_IND,
exp_TO_DATE_ISSUE_DATE.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_TO_DATE_ISSUE_DATE.source_record_id ORDER BY LKP.SC_DWNLD_PRIORITY asc,LKP.SC_SERVICE_CENTER asc,LKP.SC_POLICY_NUM asc,LKP.CHG_EFF_DT asc,LKP.SC_FLT_ITEM asc,LKP.SC_FILE_TYPE asc,LKP.SC_REC_TRANS_CODE asc,LKP.SC_TRANS_DATE asc,LKP.SC_TRANS_TYPE asc,LKP.LF_ALPHA_CODE asc,LKP.LF_STATUS asc,LKP.LF_MODE asc,LKP.LF_INSURED_SSAN asc,LKP.LF_MEMBERSHIP asc,LKP.LF_NFO_OPTION asc,LKP.LF_INSURED_NAME asc,LKP.LF_ADDRESS_1 asc,LKP.LF_ADDRESS_2 asc,LKP.LF_ADDRESS_3 asc,LKP.LF_PAYOR_NAME asc,LKP.LF_OWNER_NAME asc,LKP.LF_MODAL_PREM asc,LKP.LF_ISSUE_DATE asc,LKP.LF_APPL_DATE asc,LKP.LF_BIRTH_DATE asc,LKP.LF_PAC_DRAW_DAY asc,LKP.LF_DUE_USE_CD asc,LKP.LF_REQUIRE_SW asc,LKP.LF_PAC_BANK_CD asc,LKP.LF_PAC_ACCT_NO asc,LKP.LF_FORM asc,LKP.LF_VOLUME asc,LKP.LF_APP_PREM asc,LKP.LF_OVER_SHORT asc,LKP.LF_UNDERWRITER asc,LKP.LF_PLAN_NAME asc,LKP.LF_POLICY_FEE asc,LKP.LF_FUND_BALANCE asc,LKP.LF_SURR_VALUE asc,LKP.LF_DEP_FUND asc,LKP.LF_PD_TO_DATE asc,LKP.LF_LOAN_AMOUNT asc,LKP.LF_DIV_ON_DEP asc,LKP.LF_PAIDUP_ADD asc,LKP.LF_CASH_VAL_PUA asc,LKP.LF_ANNUAL_PREM asc,LKP.LF_AGENT_NO asc,LKP.LF_LOAN_VALUE asc,LKP.LF_PHY_ISS asc,LKP.LF_CANC_REASON_CDE asc,LKP.LF_ISS_AGE asc,LKP.LF_2ND_INS_NAME asc,LKP.LF_OWNER_ADDRESS_1 asc,LKP.LF_OWNER_ADDRESS_2 asc,LKP.LF_OWNER_ADDRESS_3 asc,LKP.LF_PAYOR_ADDRESS_1 asc,LKP.LF_PAYOR_ADDRESS_2 asc,LKP.LF_PAYOR_ADDRESS_3 asc,LKP.LF_OWNER_SSAN asc,LKP.LF_LAST_ANN_DATE asc,LKP.LF_FUND_BAL_LST_AN asc,LKP.LF_LOAN_CALC_DATE asc,LKP.LF_SURR_CHG_LST_AN asc,LKP.LF_POL_ANNUAL_PREM asc,LKP.LF_2ND_INS_DOB asc,LKP.LF_2ND_INS_ISS_AGE asc,LKP.LF_INS_ISS_AGE asc,LKP.LF_INS_TOBACCO_USE asc,LKP.LF_INS_SEX_CODE asc,LKP.LF_2ND_INS_SEX_CDE asc,LKP.LF_DEATH_BENE_OPT asc,LKP.LF_2ND_INS_SSAN asc,LKP.LF_RESTRICT_CODE asc,LKP.LF_LOAN_INT_RATE asc,LKP.LF_LOAN_INT_ACCRU asc,LKP.LF_NEXT_AN_CAS_VAL asc,LKP.LF_DISPLAY_SW asc,LKP.FEED_IND asc) RNK
FROM
exp_TO_DATE_ISSUE_DATE
LEFT JOIN (
SELECT LIFEPOLS.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY, LIFEPOLS.SC_SERVICE_CENTER as SC_SERVICE_CENTER, LIFEPOLS.CHG_EFF_DT as CHG_EFF_DT, LIFEPOLS.CHG_EXP_DT as CHG_EXP_DT, LIFEPOLS.SC_FLT_ITEM as SC_FLT_ITEM, LIFEPOLS.SC_FILE_TYPE as SC_FILE_TYPE, LIFEPOLS.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE, LIFEPOLS.SC_TRANS_DATE as SC_TRANS_DATE, LIFEPOLS.SC_TRANS_TYPE as SC_TRANS_TYPE, LIFEPOLS.LF_ALPHA_CODE as LF_ALPHA_CODE, LIFEPOLS.LF_STATUS as LF_STATUS, LIFEPOLS.LF_MODE as LF_MODE, LIFEPOLS.LF_INSURED_SSAN as LF_INSURED_SSAN, LIFEPOLS.LF_MEMBERSHIP as LF_MEMBERSHIP, LIFEPOLS.LF_NFO_OPTION as LF_NFO_OPTION, LIFEPOLS.LF_INSURED_NAME as LF_INSURED_NAME, LIFEPOLS.LF_ADDRESS_1 as LF_ADDRESS_1, LIFEPOLS.LF_ADDRESS_2 as LF_ADDRESS_2, LIFEPOLS.LF_ADDRESS_3 as LF_ADDRESS_3, LIFEPOLS.LF_PAYOR_NAME as LF_PAYOR_NAME, LIFEPOLS.LF_OWNER_NAME as LF_OWNER_NAME, LIFEPOLS.LF_MODAL_PREM as LF_MODAL_PREM, LIFEPOLS.LF_ISSUE_DATE as LF_ISSUE_DATE, LIFEPOLS.LF_APPL_DATE as LF_APPL_DATE, LIFEPOLS.LF_BIRTH_DATE as LF_BIRTH_DATE, LIFEPOLS.LF_PAC_DRAW_DAY as LF_PAC_DRAW_DAY, LIFEPOLS.LF_DUE_USE_CD as LF_DUE_USE_CD, LIFEPOLS.LF_REQUIRE_SW as LF_REQUIRE_SW, LIFEPOLS.LF_PAC_BANK_CD as LF_PAC_BANK_CD, LIFEPOLS.LF_PAC_ACCT_NO as LF_PAC_ACCT_NO, LIFEPOLS.LF_FORM as LF_FORM, LIFEPOLS.LF_VOLUME as LF_VOLUME, LIFEPOLS.LF_APP_PREM as LF_APP_PREM, LIFEPOLS.LF_OVER_SHORT as LF_OVER_SHORT, LIFEPOLS.LF_UNDERWRITER as LF_UNDERWRITER, LIFEPOLS.LF_PLAN_NAME as LF_PLAN_NAME, LIFEPOLS.LF_POLICY_FEE as LF_POLICY_FEE, LIFEPOLS.LF_FUND_BALANCE as LF_FUND_BALANCE, LIFEPOLS.LF_SURR_VALUE as LF_SURR_VALUE, LIFEPOLS.LF_DEP_FUND as LF_DEP_FUND, LIFEPOLS.LF_PD_TO_DATE as LF_PD_TO_DATE, LIFEPOLS.LF_LOAN_AMOUNT as LF_LOAN_AMOUNT, LIFEPOLS.LF_DIV_ON_DEP as LF_DIV_ON_DEP, LIFEPOLS.LF_PAIDUP_ADD as LF_PAIDUP_ADD, LIFEPOLS.LF_CASH_VAL_PUA as LF_CASH_VAL_PUA, LIFEPOLS.LF_ANNUAL_PREM as LF_ANNUAL_PREM, LIFEPOLS.LF_AGENT_NO as LF_AGENT_NO, LIFEPOLS.LF_LOAN_VALUE as LF_LOAN_VALUE, LIFEPOLS.LF_PHY_ISS as LF_PHY_ISS, LIFEPOLS.LF_CANC_REASON_CDE as LF_CANC_REASON_CDE, LIFEPOLS.LF_ISS_AGE as LF_ISS_AGE, LIFEPOLS.LF_2ND_INS_NAME as LF_2ND_INS_NAME, LIFEPOLS.LF_OWNER_ADDRESS_1 as LF_OWNER_ADDRESS_1, LIFEPOLS.LF_OWNER_ADDRESS_2 as LF_OWNER_ADDRESS_2, LIFEPOLS.LF_OWNER_ADDRESS_3 as LF_OWNER_ADDRESS_3, LIFEPOLS.LF_PAYOR_ADDRESS_1 as LF_PAYOR_ADDRESS_1, LIFEPOLS.LF_PAYOR_ADDRESS_2 as LF_PAYOR_ADDRESS_2, LIFEPOLS.LF_PAYOR_ADDRESS_3 as LF_PAYOR_ADDRESS_3, LIFEPOLS.LF_OWNER_SSAN as LF_OWNER_SSAN, LIFEPOLS.LF_LAST_ANN_DATE as LF_LAST_ANN_DATE, LIFEPOLS.LF_FUND_BAL_LST_AN as LF_FUND_BAL_LST_AN, LIFEPOLS.LF_LOAN_CALC_DATE as LF_LOAN_CALC_DATE, LIFEPOLS.LF_SURR_CHG_LST_AN as LF_SURR_CHG_LST_AN, LIFEPOLS.LF_POL_ANNUAL_PREM as LF_POL_ANNUAL_PREM, LIFEPOLS.LF_2ND_INS_DOB as LF_2ND_INS_DOB, LIFEPOLS.LF_2ND_INS_ISS_AGE as LF_2ND_INS_ISS_AGE, LIFEPOLS.LF_INS_ISS_AGE as LF_INS_ISS_AGE, LIFEPOLS.LF_INS_TOBACCO_USE as LF_INS_TOBACCO_USE, LIFEPOLS.LF_INS_SEX_CODE as LF_INS_SEX_CODE, LIFEPOLS.LF_2ND_INS_SEX_CDE as LF_2ND_INS_SEX_CDE, LIFEPOLS.LF_DEATH_BENE_OPT as LF_DEATH_BENE_OPT, LIFEPOLS.LF_2ND_INS_SSAN as LF_2ND_INS_SSAN, LIFEPOLS.LF_RESTRICT_CODE as LF_RESTRICT_CODE, LIFEPOLS.LF_LOAN_INT_RATE as LF_LOAN_INT_RATE, LIFEPOLS.LF_LOAN_INT_ACCRU as LF_LOAN_INT_ACCRU, LIFEPOLS.LF_NEXT_AN_CAS_VAL as LF_NEXT_AN_CAS_VAL, LIFEPOLS.LF_DISPLAY_SW as LF_DISPLAY_SW, LIFEPOLS.FEED_IND as FEED_IND, LIFEPOLS.SC_POLICY_NUM as SC_POLICY_NUM FROM  DB_T_core_MEMBXREF_PROD.LIFEPOLS WHERE LIFEPOLS.ECTL_TX_CD=''NEW''
) LKP ON LKP.SC_POLICY_NUM = exp_TO_DATE_ISSUE_DATE.SC_POLICY_NUM
QUALIFY RNK = 1
);


-- Component exp_DERIVE_FLAG, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_DERIVE_FLAG AS
(
SELECT
exp_TO_DATE_ISSUE_DATE.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_TO_DATE_ISSUE_DATE.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_TO_DATE_ISSUE_DATE.SC_POLICY_NUM as SC_POLICY_NUM,
exp_TO_DATE_ISSUE_DATE.SC_FLT_ITEM as SC_FLT_ITEM,
exp_TO_DATE_ISSUE_DATE.SC_FILE_TYPE as SC_FILE_TYPE,
exp_TO_DATE_ISSUE_DATE.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_TO_DATE_ISSUE_DATE.SC_TRANS_DATE as SC_TRANS_DATE,
exp_TO_DATE_ISSUE_DATE.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_TO_DATE_ISSUE_DATE.LF_ALPHA_CODE as LF_ALPHA_CODE,
exp_TO_DATE_ISSUE_DATE.LF_STATUS as LF_STATUS,
exp_TO_DATE_ISSUE_DATE.LF_MODE as LF_MODE,
exp_TO_DATE_ISSUE_DATE.LF_INSURED_SSAN as LF_INSURED_SSAN,
exp_TO_DATE_ISSUE_DATE.LF_MEMBERSHIP as LF_MEMBERSHIP,
exp_TO_DATE_ISSUE_DATE.LF_NFO_OPTION as LF_NFO_OPTION,
exp_TO_DATE_ISSUE_DATE.LF_INSURED_NAME as LF_INSURED_NAME,
exp_TO_DATE_ISSUE_DATE.LF_ADDRESS_1 as LF_ADDRESS_1,
exp_TO_DATE_ISSUE_DATE.LF_ADDRESS_2 as LF_ADDRESS_2,
exp_TO_DATE_ISSUE_DATE.LF_ADDRESS_3 as LF_ADDRESS_3,
exp_TO_DATE_ISSUE_DATE.LF_PAYOR_NAME as LF_PAYOR_NAME,
exp_TO_DATE_ISSUE_DATE.LF_OWNER_NAME as LF_OWNER_NAME,
exp_TO_DATE_ISSUE_DATE.LF_MODAL_PREM as LF_MODAL_PREM,
exp_TO_DATE_ISSUE_DATE.out_LF_ISSUE_DATE as LF_ISSUE_DATE,
exp_TO_DATE_ISSUE_DATE.LF_APPL_DATE as LF_APPL_DATE,
exp_TO_DATE_ISSUE_DATE.LF_BIRTH_DATE as LF_BIRTH_DATE,
exp_TO_DATE_ISSUE_DATE.LF_PAC_DRAW_DAY as LF_PAC_DRAW_DAY,
exp_TO_DATE_ISSUE_DATE.LF_DUE_USE_CD as LF_DUE_USE_CD,
exp_TO_DATE_ISSUE_DATE.LF_REQUIRE_SW as LF_REQUIRE_SW,
exp_TO_DATE_ISSUE_DATE.LF_PAC_BANK_CD as LF_PAC_BANK_CD,
exp_TO_DATE_ISSUE_DATE.LF_PAC_ACCT_NO as LF_PAC_ACCT_NO,
exp_TO_DATE_ISSUE_DATE.LF_FORM as LF_FORM,
exp_TO_DATE_ISSUE_DATE.LF_VOLUME as LF_VOLUME,
exp_TO_DATE_ISSUE_DATE.LF_APP_PREM as LF_APP_PREM,
exp_TO_DATE_ISSUE_DATE.LF_OVER_SHORT as LF_OVER_SHORT,
exp_TO_DATE_ISSUE_DATE.LF_UNDERWRITER as LF_UNDERWRITER,
exp_TO_DATE_ISSUE_DATE.LF_PLAN_NAME as LF_PLAN_NAME,
exp_TO_DATE_ISSUE_DATE.LF_POLICY_FEE as LF_POLICY_FEE,
exp_TO_DATE_ISSUE_DATE.LF_FUND_BALANCE as LF_FUND_BALANCE,
exp_TO_DATE_ISSUE_DATE.LF_SURR_VALUE as LF_SURR_VALUE,
exp_TO_DATE_ISSUE_DATE.LF_DEP_FUND as LF_DEP_FUND,
exp_TO_DATE_ISSUE_DATE.LF_PD_TO_DATE as LF_PD_TO_DATE,
exp_TO_DATE_ISSUE_DATE.LF_LOAN_AMOUNT as LF_LOAN_AMOUNT,
exp_TO_DATE_ISSUE_DATE.LF_DIV_ON_DEP as LF_DIV_ON_DEP,
exp_TO_DATE_ISSUE_DATE.LF_PAIDUP_ADD as LF_PAIDUP_ADD,
exp_TO_DATE_ISSUE_DATE.LF_CASH_VAL_PUA as LF_CASH_VAL_PUA,
exp_TO_DATE_ISSUE_DATE.LF_ANNUAL_PREM as LF_ANNUAL_PREM,
exp_TO_DATE_ISSUE_DATE.LF_AGENT_NO as LF_AGENT_NO,
exp_TO_DATE_ISSUE_DATE.LF_LOAN_VALUE as LF_LOAN_VALUE,
exp_TO_DATE_ISSUE_DATE.LF_PHY_ISS as LF_PHY_ISS,
exp_TO_DATE_ISSUE_DATE.LF_CANC_REASON_CDE as LF_CANC_REASON_CDE,
exp_TO_DATE_ISSUE_DATE.LF_ISS_AGE as LF_ISS_AGE,
exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_NAME as LF_2ND_INS_NAME,
exp_TO_DATE_ISSUE_DATE.LF_OWNER_ADDRESS_1 as LF_OWNER_ADDRESS_1,
exp_TO_DATE_ISSUE_DATE.LF_OWNER_ADDRESS_2 as LF_OWNER_ADDRESS_2,
exp_TO_DATE_ISSUE_DATE.LF_OWNER_ADDRESS_3 as LF_OWNER_ADDRESS_3,
exp_TO_DATE_ISSUE_DATE.LF_PAYOR_ADDRESS_1 as LF_PAYOR_ADDRESS_1,
exp_TO_DATE_ISSUE_DATE.LF_PAYOR_ADDRESS_2 as LF_PAYOR_ADDRESS_2,
exp_TO_DATE_ISSUE_DATE.LF_PAYOR_ADDRESS_3 as LF_PAYOR_ADDRESS_3,
exp_TO_DATE_ISSUE_DATE.LF_OWNER_SSAN as LF_OWNER_SSAN,
exp_TO_DATE_ISSUE_DATE.LF_LAST_ANN_DATE as LF_LAST_ANN_DATE,
exp_TO_DATE_ISSUE_DATE.LF_FUND_BAL_LST_AN as LF_FUND_BAL_LST_AN,
exp_TO_DATE_ISSUE_DATE.LF_LOAN_CALC_DATE as LF_LOAN_CALC_DATE,
exp_TO_DATE_ISSUE_DATE.LF_SURR_CHG_LST_AN as LF_SURR_CHG_LST_AN,
exp_TO_DATE_ISSUE_DATE.LF_POL_ANNUAL_PREM as LF_POL_ANNUAL_PREM,
exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_DOB as LF_2ND_INS_DOB,
exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_ISS_AGE as LF_2ND_INS_ISS_AGE,
exp_TO_DATE_ISSUE_DATE.LF_INS_ISS_AGE as LF_INS_ISS_AGE,
exp_TO_DATE_ISSUE_DATE.LF_INS_TOBACCO_USE as LF_INS_TOBACCO_USE,
exp_TO_DATE_ISSUE_DATE.LF_INS_SEX_CODE as LF_INS_SEX_CODE,
exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_SEX_CDE as LF_2ND_INS_SEX_CDE,
exp_TO_DATE_ISSUE_DATE.LF_DEATH_BENE_OPT as LF_DEATH_BENE_OPT,
exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_SSAN as LF_2ND_INS_SSAN,
exp_TO_DATE_ISSUE_DATE.LF_RESTRICT_CODE as LF_RESTRICT_CODE,
exp_TO_DATE_ISSUE_DATE.LF_LOAN_INT_RATE as LF_LOAN_INT_RATE,
exp_TO_DATE_ISSUE_DATE.LF_LOAN_INT_ACCRU as LF_LOAN_INT_ACCRU,
exp_TO_DATE_ISSUE_DATE.LF_NEXT_AN_CAS_VAL as LF_NEXT_AN_CAS_VAL,
exp_TO_DATE_ISSUE_DATE.LF_DISPLAY_SW as LF_DISPLAY_SW,
exp_TO_DATE_ISSUE_DATE.LOAD_DT as LOAD_DT,
exp_TO_DATE_ISSUE_DATE.FEED_IND as FEED_IND,
LKP_LIFEPOLS.CHG_EFF_DT as CHG_EFF_DT_lkp,
CASE WHEN LKP_LIFEPOLS.SC_POLICY_NUM IS NULL THEN ''NEW'' ELSE CASE WHEN CASE WHEN LKP_LIFEPOLS.SC_DWNLD_PRIORITY IS NULL THEN 0 ELSE LKP_LIFEPOLS.SC_DWNLD_PRIORITY END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.SC_DWNLD_PRIORITY IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.SC_DWNLD_PRIORITY END OR CASE WHEN LKP_LIFEPOLS.SC_SERVICE_CENTER IS NULL THEN 0 ELSE LKP_LIFEPOLS.SC_SERVICE_CENTER END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.SC_SERVICE_CENTER IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.SC_SERVICE_CENTER END OR CASE WHEN LKP_LIFEPOLS.SC_POLICY_NUM IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.SC_POLICY_NUM END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.SC_POLICY_NUM IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.SC_POLICY_NUM END OR CASE WHEN LKP_LIFEPOLS.SC_FLT_ITEM IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.SC_FLT_ITEM END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.SC_FLT_ITEM IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.SC_FLT_ITEM END OR CASE WHEN LKP_LIFEPOLS.SC_FILE_TYPE IS NULL THEN 0 ELSE LKP_LIFEPOLS.SC_FILE_TYPE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.SC_FILE_TYPE IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.SC_FILE_TYPE END OR CASE WHEN LKP_LIFEPOLS.SC_REC_TRANS_CODE IS NULL THEN 0 ELSE LKP_LIFEPOLS.SC_REC_TRANS_CODE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.SC_REC_TRANS_CODE IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.SC_REC_TRANS_CODE END OR CASE WHEN LKP_LIFEPOLS.SC_TRANS_DATE IS NULL THEN TO_DATE ( ''12/31/9999'' , ''MM/DD/YYYY'' ) ELSE LKP_LIFEPOLS.SC_TRANS_DATE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.SC_TRANS_DATE IS NULL THEN TO_DATE ( ''12/31/9999'' , ''MM/DD/YYYY'' ) ELSE exp_TO_DATE_ISSUE_DATE.SC_TRANS_DATE END OR CASE WHEN LKP_LIFEPOLS.SC_TRANS_TYPE IS NULL THEN 0 ELSE LKP_LIFEPOLS.SC_TRANS_TYPE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.SC_TRANS_TYPE IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.SC_TRANS_TYPE END OR CASE WHEN LKP_LIFEPOLS.LF_ALPHA_CODE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_ALPHA_CODE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_ALPHA_CODE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_ALPHA_CODE END OR CASE WHEN LKP_LIFEPOLS.LF_STATUS IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_STATUS END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_STATUS IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_STATUS END OR CASE WHEN LKP_LIFEPOLS.LF_MODE IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_MODE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_MODE IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_MODE END OR CASE WHEN LKP_LIFEPOLS.LF_INSURED_SSAN IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_INSURED_SSAN END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_INSURED_SSAN IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_INSURED_SSAN END OR CASE WHEN LKP_LIFEPOLS.LF_MEMBERSHIP IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_MEMBERSHIP END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_MEMBERSHIP IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_MEMBERSHIP END OR CASE WHEN LKP_LIFEPOLS.LF_NFO_OPTION IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_NFO_OPTION END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_NFO_OPTION IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_NFO_OPTION END OR CASE WHEN LKP_LIFEPOLS.LF_INSURED_NAME IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_INSURED_NAME END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_INSURED_NAME IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_INSURED_NAME END OR CASE WHEN LKP_LIFEPOLS.LF_ADDRESS_1 IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_ADDRESS_1 END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_ADDRESS_1 IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_ADDRESS_1 END OR CASE WHEN LKP_LIFEPOLS.LF_ADDRESS_2 IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_ADDRESS_2 END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_ADDRESS_2 IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_ADDRESS_2 END OR CASE WHEN LKP_LIFEPOLS.LF_ADDRESS_3 IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_ADDRESS_3 END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_ADDRESS_3 IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_ADDRESS_3 END OR CASE WHEN LKP_LIFEPOLS.LF_PAYOR_NAME IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_PAYOR_NAME END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_PAYOR_NAME IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_PAYOR_NAME END OR CASE WHEN LKP_LIFEPOLS.LF_OWNER_NAME IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_OWNER_NAME END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_OWNER_NAME IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_OWNER_NAME END OR CASE WHEN LKP_LIFEPOLS.LF_MODAL_PREM IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_MODAL_PREM END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_MODAL_PREM IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_MODAL_PREM END OR CASE WHEN LKP_LIFEPOLS.LF_ISSUE_DATE IS NULL THEN TO_DATE ( ''12/31/9999'' , ''MM/DD/YYYY'' ) ELSE LKP_LIFEPOLS.LF_ISSUE_DATE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.out_LF_ISSUE_DATE IS NULL THEN TO_DATE ( ''12/31/9999'' , ''MM/DD/YYYY'' ) ELSE exp_TO_DATE_ISSUE_DATE.out_LF_ISSUE_DATE END OR CASE WHEN LKP_LIFEPOLS.LF_APPL_DATE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_APPL_DATE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_APPL_DATE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_APPL_DATE END OR CASE WHEN LKP_LIFEPOLS.LF_BIRTH_DATE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_BIRTH_DATE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_BIRTH_DATE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_BIRTH_DATE END OR CASE WHEN LKP_LIFEPOLS.LF_PAC_DRAW_DAY IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_PAC_DRAW_DAY END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_PAC_DRAW_DAY IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_PAC_DRAW_DAY END OR CASE WHEN LKP_LIFEPOLS.LF_DUE_USE_CD IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_DUE_USE_CD END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_DUE_USE_CD IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_DUE_USE_CD END OR CASE WHEN LKP_LIFEPOLS.LF_REQUIRE_SW IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_REQUIRE_SW END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_REQUIRE_SW IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_REQUIRE_SW END OR CASE WHEN LKP_LIFEPOLS.LF_PAC_BANK_CD IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_PAC_BANK_CD END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_PAC_BANK_CD IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_PAC_BANK_CD END OR CASE WHEN LKP_LIFEPOLS.LF_PAC_ACCT_NO IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_PAC_ACCT_NO END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_PAC_ACCT_NO IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_PAC_ACCT_NO END OR CASE WHEN LKP_LIFEPOLS.LF_FORM IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_FORM END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_FORM IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_FORM END OR CASE WHEN LKP_LIFEPOLS.LF_VOLUME IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_VOLUME END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_VOLUME IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_VOLUME END OR CASE WHEN LKP_LIFEPOLS.LF_APP_PREM IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_APP_PREM END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_APP_PREM IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_APP_PREM END OR CASE WHEN LKP_LIFEPOLS.LF_OVER_SHORT IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_OVER_SHORT END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_OVER_SHORT IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_OVER_SHORT END OR CASE WHEN LKP_LIFEPOLS.LF_UNDERWRITER IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_UNDERWRITER END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_UNDERWRITER IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_UNDERWRITER END OR CASE WHEN LKP_LIFEPOLS.LF_PLAN_NAME IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_PLAN_NAME END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_PLAN_NAME IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_PLAN_NAME END OR CASE WHEN LKP_LIFEPOLS.LF_POLICY_FEE IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_POLICY_FEE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_POLICY_FEE IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_POLICY_FEE END OR CASE WHEN LKP_LIFEPOLS.LF_FUND_BALANCE IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_FUND_BALANCE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_FUND_BALANCE IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_FUND_BALANCE END OR CASE WHEN LKP_LIFEPOLS.LF_SURR_VALUE IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_SURR_VALUE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_SURR_VALUE IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_SURR_VALUE END OR CASE WHEN LKP_LIFEPOLS.LF_DEP_FUND IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_DEP_FUND END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_DEP_FUND IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_DEP_FUND END OR CASE WHEN LKP_LIFEPOLS.LF_PD_TO_DATE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_PD_TO_DATE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_PD_TO_DATE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_PD_TO_DATE END OR CASE WHEN LKP_LIFEPOLS.LF_LOAN_AMOUNT IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_LOAN_AMOUNT END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_LOAN_AMOUNT IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_LOAN_AMOUNT END OR CASE WHEN LKP_LIFEPOLS.LF_DIV_ON_DEP IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_DIV_ON_DEP END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_DIV_ON_DEP IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_DIV_ON_DEP END OR CASE WHEN LKP_LIFEPOLS.LF_PAIDUP_ADD IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_PAIDUP_ADD END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_PAIDUP_ADD IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_PAIDUP_ADD END OR CASE WHEN LKP_LIFEPOLS.LF_CASH_VAL_PUA IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_CASH_VAL_PUA END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_CASH_VAL_PUA IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_CASH_VAL_PUA END OR CASE WHEN LKP_LIFEPOLS.LF_ANNUAL_PREM IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_ANNUAL_PREM END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_ANNUAL_PREM IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_ANNUAL_PREM END OR CASE WHEN LKP_LIFEPOLS.LF_AGENT_NO IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_AGENT_NO END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_AGENT_NO IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_AGENT_NO END OR CASE WHEN LKP_LIFEPOLS.LF_LOAN_VALUE IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_LOAN_VALUE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_LOAN_VALUE IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_LOAN_VALUE END OR CASE WHEN LKP_LIFEPOLS.LF_PHY_ISS IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_PHY_ISS END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_PHY_ISS IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_PHY_ISS END OR CASE WHEN LKP_LIFEPOLS.LF_CANC_REASON_CDE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_CANC_REASON_CDE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_CANC_REASON_CDE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_CANC_REASON_CDE END OR CASE WHEN LKP_LIFEPOLS.LF_ISS_AGE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_ISS_AGE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_ISS_AGE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_ISS_AGE END OR CASE WHEN LKP_LIFEPOLS.LF_2ND_INS_NAME IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_2ND_INS_NAME END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_NAME IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_NAME END OR CASE WHEN LKP_LIFEPOLS.LF_OWNER_ADDRESS_1 IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_OWNER_ADDRESS_1 END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_OWNER_ADDRESS_1 IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_OWNER_ADDRESS_1 END OR CASE WHEN LKP_LIFEPOLS.LF_OWNER_ADDRESS_2 IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_OWNER_ADDRESS_2 END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_OWNER_ADDRESS_2 IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_OWNER_ADDRESS_2 END OR CASE WHEN LKP_LIFEPOLS.LF_OWNER_ADDRESS_3 IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_OWNER_ADDRESS_3 END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_OWNER_ADDRESS_3 IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_OWNER_ADDRESS_3 END OR CASE WHEN LKP_LIFEPOLS.LF_PAYOR_ADDRESS_1 IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_PAYOR_ADDRESS_1 END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_PAYOR_ADDRESS_1 IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_PAYOR_ADDRESS_1 END OR CASE WHEN LKP_LIFEPOLS.LF_PAYOR_ADDRESS_2 IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_PAYOR_ADDRESS_2 END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_PAYOR_ADDRESS_2 IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_PAYOR_ADDRESS_2 END OR CASE WHEN LKP_LIFEPOLS.LF_PAYOR_ADDRESS_3 IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_PAYOR_ADDRESS_3 END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_PAYOR_ADDRESS_3 IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_PAYOR_ADDRESS_3 END OR CASE WHEN LKP_LIFEPOLS.LF_OWNER_SSAN IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_OWNER_SSAN END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_OWNER_SSAN IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_OWNER_SSAN END OR CASE WHEN LKP_LIFEPOLS.LF_LAST_ANN_DATE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_LAST_ANN_DATE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_LAST_ANN_DATE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_LAST_ANN_DATE END OR CASE WHEN LKP_LIFEPOLS.LF_FUND_BAL_LST_AN IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_FUND_BAL_LST_AN END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_FUND_BAL_LST_AN IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_FUND_BAL_LST_AN END OR CASE WHEN LKP_LIFEPOLS.LF_LOAN_CALC_DATE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_LOAN_CALC_DATE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_LOAN_CALC_DATE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_LOAN_CALC_DATE END OR CASE WHEN LKP_LIFEPOLS.LF_SURR_CHG_LST_AN IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_SURR_CHG_LST_AN END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_SURR_CHG_LST_AN IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_SURR_CHG_LST_AN END OR CASE WHEN LKP_LIFEPOLS.LF_POL_ANNUAL_PREM IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_POL_ANNUAL_PREM END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_POL_ANNUAL_PREM IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_POL_ANNUAL_PREM END OR CASE WHEN LKP_LIFEPOLS.LF_2ND_INS_DOB IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_2ND_INS_DOB END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_DOB IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_DOB END OR CASE WHEN LKP_LIFEPOLS.LF_2ND_INS_ISS_AGE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_2ND_INS_ISS_AGE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_ISS_AGE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_ISS_AGE END OR CASE WHEN LKP_LIFEPOLS.LF_INS_ISS_AGE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_INS_ISS_AGE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_INS_ISS_AGE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_INS_ISS_AGE END OR CASE WHEN LKP_LIFEPOLS.LF_INS_TOBACCO_USE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_INS_TOBACCO_USE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_INS_TOBACCO_USE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_INS_TOBACCO_USE END OR CASE WHEN LKP_LIFEPOLS.LF_INS_SEX_CODE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_INS_SEX_CODE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_INS_SEX_CODE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_INS_SEX_CODE END OR CASE WHEN LKP_LIFEPOLS.LF_2ND_INS_SEX_CDE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_2ND_INS_SEX_CDE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_SEX_CDE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_SEX_CDE END OR CASE WHEN LKP_LIFEPOLS.LF_DEATH_BENE_OPT IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_DEATH_BENE_OPT END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_DEATH_BENE_OPT IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_DEATH_BENE_OPT END OR CASE WHEN LKP_LIFEPOLS.LF_2ND_INS_SSAN IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_2ND_INS_SSAN END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_SSAN IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_2ND_INS_SSAN END OR CASE WHEN LKP_LIFEPOLS.LF_RESTRICT_CODE IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_RESTRICT_CODE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_RESTRICT_CODE IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_RESTRICT_CODE END OR CASE WHEN LKP_LIFEPOLS.LF_LOAN_INT_RATE IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_LOAN_INT_RATE END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_LOAN_INT_RATE IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_LOAN_INT_RATE END OR CASE WHEN LKP_LIFEPOLS.LF_LOAN_INT_ACCRU IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_LOAN_INT_ACCRU END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_LOAN_INT_ACCRU IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_LOAN_INT_ACCRU END OR CASE WHEN LKP_LIFEPOLS.LF_NEXT_AN_CAS_VAL IS NULL THEN 0 ELSE LKP_LIFEPOLS.LF_NEXT_AN_CAS_VAL END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_NEXT_AN_CAS_VAL IS NULL THEN 0 ELSE exp_TO_DATE_ISSUE_DATE.LF_NEXT_AN_CAS_VAL END OR CASE WHEN LKP_LIFEPOLS.LF_DISPLAY_SW IS NULL THEN ''~'' ELSE LKP_LIFEPOLS.LF_DISPLAY_SW END <> CASE WHEN exp_TO_DATE_ISSUE_DATE.LF_DISPLAY_SW IS NULL THEN ''~'' ELSE exp_TO_DATE_ISSUE_DATE.LF_DISPLAY_SW END THEN ''UPD'' ELSE ''REJ'' END END as out_FLAG,
:PMMappingName as out_PRGM_NM,
:PROJ_ID as out_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
exp_TO_DATE_ISSUE_DATE.source_record_id
FROM
exp_TO_DATE_ISSUE_DATE
INNER JOIN LKP_LIFEPOLS ON exp_TO_DATE_ISSUE_DATE.source_record_id = LKP_LIFEPOLS.source_record_id
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;


-- Component rtr_INS_UPD_INSERT, Type ROUTER Output Group INSERT
create or replace temp table RTR_INS_UPD_insert as
SELECT
exp_DERIVE_FLAG.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_DERIVE_FLAG.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_DERIVE_FLAG.SC_POLICY_NUM as SC_POLICY_NUM,
exp_DERIVE_FLAG.SC_FLT_ITEM as SC_FLT_ITEM,
exp_DERIVE_FLAG.SC_FILE_TYPE as SC_FILE_TYPE,
exp_DERIVE_FLAG.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_DERIVE_FLAG.SC_TRANS_DATE as SC_TRANS_DATE,
exp_DERIVE_FLAG.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_DERIVE_FLAG.LF_ALPHA_CODE as LF_ALPHA_CODE,
exp_DERIVE_FLAG.LF_STATUS as LF_STATUS,
exp_DERIVE_FLAG.LF_MODE as LF_MODE,
exp_DERIVE_FLAG.LF_INSURED_SSAN as LF_INSURED_SSAN,
exp_DERIVE_FLAG.LF_MEMBERSHIP as LF_MEMBERSHIP,
exp_DERIVE_FLAG.LF_NFO_OPTION as LF_NFO_OPTION,
exp_DERIVE_FLAG.LF_INSURED_NAME as LF_INSURED_NAME,
exp_DERIVE_FLAG.LF_ADDRESS_1 as LF_ADDRESS_1,
exp_DERIVE_FLAG.LF_ADDRESS_2 as LF_ADDRESS_2,
exp_DERIVE_FLAG.LF_ADDRESS_3 as LF_ADDRESS_3,
exp_DERIVE_FLAG.LF_PAYOR_NAME as LF_PAYOR_NAME,
exp_DERIVE_FLAG.LF_OWNER_NAME as LF_OWNER_NAME,
exp_DERIVE_FLAG.LF_MODAL_PREM as LF_MODAL_PREM,
exp_DERIVE_FLAG.LF_ISSUE_DATE as LF_ISSUE_DATE,
exp_DERIVE_FLAG.LF_APPL_DATE as LF_APPL_DATE,
exp_DERIVE_FLAG.LF_BIRTH_DATE as LF_BIRTH_DATE,
exp_DERIVE_FLAG.LF_PAC_DRAW_DAY as LF_PAC_DRAW_DAY,
exp_DERIVE_FLAG.LF_DUE_USE_CD as LF_DUE_USE_CD,
exp_DERIVE_FLAG.LF_REQUIRE_SW as LF_REQUIRE_SW,
exp_DERIVE_FLAG.LF_PAC_BANK_CD as LF_PAC_BANK_CD,
exp_DERIVE_FLAG.LF_PAC_ACCT_NO as LF_PAC_ACCT_NO,
exp_DERIVE_FLAG.LF_FORM as LF_FORM,
exp_DERIVE_FLAG.LF_VOLUME as LF_VOLUME,
exp_DERIVE_FLAG.LF_APP_PREM as LF_APP_PREM,
exp_DERIVE_FLAG.LF_OVER_SHORT as LF_OVER_SHORT,
exp_DERIVE_FLAG.LF_UNDERWRITER as LF_UNDERWRITER,
exp_DERIVE_FLAG.LF_PLAN_NAME as LF_PLAN_NAME,
exp_DERIVE_FLAG.LF_POLICY_FEE as LF_POLICY_FEE,
exp_DERIVE_FLAG.LF_FUND_BALANCE as LF_FUND_BALANCE,
exp_DERIVE_FLAG.LF_SURR_VALUE as LF_SURR_VALUE,
exp_DERIVE_FLAG.LF_DEP_FUND as LF_DEP_FUND,
exp_DERIVE_FLAG.LF_PD_TO_DATE as LF_PD_TO_DATE,
exp_DERIVE_FLAG.LF_LOAN_AMOUNT as LF_LOAN_AMOUNT,
exp_DERIVE_FLAG.LF_DIV_ON_DEP as LF_DIV_ON_DEP,
exp_DERIVE_FLAG.LF_PAIDUP_ADD as LF_PAIDUP_ADD,
exp_DERIVE_FLAG.LF_CASH_VAL_PUA as LF_CASH_VAL_PUA,
exp_DERIVE_FLAG.LF_ANNUAL_PREM as LF_ANNUAL_PREM,
exp_DERIVE_FLAG.LF_AGENT_NO as LF_AGENT_NO,
exp_DERIVE_FLAG.LF_LOAN_VALUE as LF_LOAN_VALUE,
exp_DERIVE_FLAG.LF_PHY_ISS as LF_PHY_ISS,
exp_DERIVE_FLAG.LF_CANC_REASON_CDE as LF_CANC_REASON_CDE,
exp_DERIVE_FLAG.LF_ISS_AGE as LF_ISS_AGE,
exp_DERIVE_FLAG.LF_2ND_INS_NAME as LF_2ND_INS_NAME,
exp_DERIVE_FLAG.LF_OWNER_ADDRESS_1 as LF_OWNER_ADDRESS_1,
exp_DERIVE_FLAG.LF_OWNER_ADDRESS_2 as LF_OWNER_ADDRESS_2,
exp_DERIVE_FLAG.LF_OWNER_ADDRESS_3 as LF_OWNER_ADDRESS_3,
exp_DERIVE_FLAG.LF_PAYOR_ADDRESS_1 as LF_PAYOR_ADDRESS_1,
exp_DERIVE_FLAG.LF_PAYOR_ADDRESS_2 as LF_PAYOR_ADDRESS_2,
exp_DERIVE_FLAG.LF_PAYOR_ADDRESS_3 as LF_PAYOR_ADDRESS_3,
exp_DERIVE_FLAG.LF_OWNER_SSAN as LF_OWNER_SSAN,
exp_DERIVE_FLAG.LF_LAST_ANN_DATE as LF_LAST_ANN_DATE,
exp_DERIVE_FLAG.LF_FUND_BAL_LST_AN as LF_FUND_BAL_LST_AN,
exp_DERIVE_FLAG.LF_LOAN_CALC_DATE as LF_LOAN_CALC_DATE,
exp_DERIVE_FLAG.LF_SURR_CHG_LST_AN as LF_SURR_CHG_LST_AN,
exp_DERIVE_FLAG.LF_POL_ANNUAL_PREM as LF_POL_ANNUAL_PREM,
exp_DERIVE_FLAG.LF_2ND_INS_DOB as LF_2ND_INS_DOB,
exp_DERIVE_FLAG.LF_2ND_INS_ISS_AGE as LF_2ND_INS_ISS_AGE,
exp_DERIVE_FLAG.LF_INS_ISS_AGE as LF_INS_ISS_AGE,
exp_DERIVE_FLAG.LF_INS_TOBACCO_USE as LF_INS_TOBACCO_USE,
exp_DERIVE_FLAG.LF_INS_SEX_CODE as LF_INS_SEX_CODE,
exp_DERIVE_FLAG.LF_2ND_INS_SEX_CDE as LF_2ND_INS_SEX_CDE,
exp_DERIVE_FLAG.LF_DEATH_BENE_OPT as LF_DEATH_BENE_OPT,
exp_DERIVE_FLAG.LF_2ND_INS_SSAN as LF_2ND_INS_SSAN,
exp_DERIVE_FLAG.LF_RESTRICT_CODE as LF_RESTRICT_CODE,
exp_DERIVE_FLAG.LF_LOAN_INT_RATE as LF_LOAN_INT_RATE,
exp_DERIVE_FLAG.LF_LOAN_INT_ACCRU as LF_LOAN_INT_ACCRU,
exp_DERIVE_FLAG.LF_NEXT_AN_CAS_VAL as LF_NEXT_AN_CAS_VAL,
exp_DERIVE_FLAG.LF_DISPLAY_SW as LF_DISPLAY_SW,
exp_DERIVE_FLAG.LOAD_DT as LOAD_DT,
exp_DERIVE_FLAG.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp,
exp_DERIVE_FLAG.out_FLAG as out_FLAG,
--''1'' as out_ECTL_PRGM_ID,
--''1'' as out_ECTL_SRC_ID,
--''1'' as out_ECTL_SRC_INST_ID,
--''1'' as out_ECTL_BATCH_ID,
--''1900-01-01'' as out_ORIG_INS_TS,
--''1900-01-01'' as out_ECTL_BATCH_START_DATE,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
exp_DERIVE_FLAG.FEED_IND as FEED_IND,
exp_DERIVE_FLAG.source_record_id
FROM
exp_DERIVE_FLAG
LEFT JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_DERIVE_FLAG.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
WHERE exp_DERIVE_FLAG.out_FLAG = ''NEW'' OR exp_DERIVE_FLAG.out_FLAG = ''UPD'';


-- Component rtr_INS_UPD_UPDATE, Type ROUTER Output Group UPDATE
create or replace temp table RTR_INS_UPD_UPDATE as
SELECT
exp_DERIVE_FLAG.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_DERIVE_FLAG.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_DERIVE_FLAG.SC_POLICY_NUM as SC_POLICY_NUM,
exp_DERIVE_FLAG.SC_FLT_ITEM as SC_FLT_ITEM,
exp_DERIVE_FLAG.SC_FILE_TYPE as SC_FILE_TYPE,
exp_DERIVE_FLAG.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_DERIVE_FLAG.SC_TRANS_DATE as SC_TRANS_DATE,
exp_DERIVE_FLAG.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_DERIVE_FLAG.LF_ALPHA_CODE as LF_ALPHA_CODE,
exp_DERIVE_FLAG.LF_STATUS as LF_STATUS,
exp_DERIVE_FLAG.LF_MODE as LF_MODE,
exp_DERIVE_FLAG.LF_INSURED_SSAN as LF_INSURED_SSAN,
exp_DERIVE_FLAG.LF_MEMBERSHIP as LF_MEMBERSHIP,
exp_DERIVE_FLAG.LF_NFO_OPTION as LF_NFO_OPTION,
exp_DERIVE_FLAG.LF_INSURED_NAME as LF_INSURED_NAME,
exp_DERIVE_FLAG.LF_ADDRESS_1 as LF_ADDRESS_1,
exp_DERIVE_FLAG.LF_ADDRESS_2 as LF_ADDRESS_2,
exp_DERIVE_FLAG.LF_ADDRESS_3 as LF_ADDRESS_3,
exp_DERIVE_FLAG.LF_PAYOR_NAME as LF_PAYOR_NAME,
exp_DERIVE_FLAG.LF_OWNER_NAME as LF_OWNER_NAME,
exp_DERIVE_FLAG.LF_MODAL_PREM as LF_MODAL_PREM,
exp_DERIVE_FLAG.LF_ISSUE_DATE as LF_ISSUE_DATE,
exp_DERIVE_FLAG.LF_APPL_DATE as LF_APPL_DATE,
exp_DERIVE_FLAG.LF_BIRTH_DATE as LF_BIRTH_DATE,
exp_DERIVE_FLAG.LF_PAC_DRAW_DAY as LF_PAC_DRAW_DAY,
exp_DERIVE_FLAG.LF_DUE_USE_CD as LF_DUE_USE_CD,
exp_DERIVE_FLAG.LF_REQUIRE_SW as LF_REQUIRE_SW,
exp_DERIVE_FLAG.LF_PAC_BANK_CD as LF_PAC_BANK_CD,
exp_DERIVE_FLAG.LF_PAC_ACCT_NO as LF_PAC_ACCT_NO,
exp_DERIVE_FLAG.LF_FORM as LF_FORM,
exp_DERIVE_FLAG.LF_VOLUME as LF_VOLUME,
exp_DERIVE_FLAG.LF_APP_PREM as LF_APP_PREM,
exp_DERIVE_FLAG.LF_OVER_SHORT as LF_OVER_SHORT,
exp_DERIVE_FLAG.LF_UNDERWRITER as LF_UNDERWRITER,
exp_DERIVE_FLAG.LF_PLAN_NAME as LF_PLAN_NAME,
exp_DERIVE_FLAG.LF_POLICY_FEE as LF_POLICY_FEE,
exp_DERIVE_FLAG.LF_FUND_BALANCE as LF_FUND_BALANCE,
exp_DERIVE_FLAG.LF_SURR_VALUE as LF_SURR_VALUE,
exp_DERIVE_FLAG.LF_DEP_FUND as LF_DEP_FUND,
exp_DERIVE_FLAG.LF_PD_TO_DATE as LF_PD_TO_DATE,
exp_DERIVE_FLAG.LF_LOAN_AMOUNT as LF_LOAN_AMOUNT,
exp_DERIVE_FLAG.LF_DIV_ON_DEP as LF_DIV_ON_DEP,
exp_DERIVE_FLAG.LF_PAIDUP_ADD as LF_PAIDUP_ADD,
exp_DERIVE_FLAG.LF_CASH_VAL_PUA as LF_CASH_VAL_PUA,
exp_DERIVE_FLAG.LF_ANNUAL_PREM as LF_ANNUAL_PREM,
exp_DERIVE_FLAG.LF_AGENT_NO as LF_AGENT_NO,
exp_DERIVE_FLAG.LF_LOAN_VALUE as LF_LOAN_VALUE,
exp_DERIVE_FLAG.LF_PHY_ISS as LF_PHY_ISS,
exp_DERIVE_FLAG.LF_CANC_REASON_CDE as LF_CANC_REASON_CDE,
exp_DERIVE_FLAG.LF_ISS_AGE as LF_ISS_AGE,
exp_DERIVE_FLAG.LF_2ND_INS_NAME as LF_2ND_INS_NAME,
exp_DERIVE_FLAG.LF_OWNER_ADDRESS_1 as LF_OWNER_ADDRESS_1,
exp_DERIVE_FLAG.LF_OWNER_ADDRESS_2 as LF_OWNER_ADDRESS_2,
exp_DERIVE_FLAG.LF_OWNER_ADDRESS_3 as LF_OWNER_ADDRESS_3,
exp_DERIVE_FLAG.LF_PAYOR_ADDRESS_1 as LF_PAYOR_ADDRESS_1,
exp_DERIVE_FLAG.LF_PAYOR_ADDRESS_2 as LF_PAYOR_ADDRESS_2,
exp_DERIVE_FLAG.LF_PAYOR_ADDRESS_3 as LF_PAYOR_ADDRESS_3,
exp_DERIVE_FLAG.LF_OWNER_SSAN as LF_OWNER_SSAN,
exp_DERIVE_FLAG.LF_LAST_ANN_DATE as LF_LAST_ANN_DATE,
exp_DERIVE_FLAG.LF_FUND_BAL_LST_AN as LF_FUND_BAL_LST_AN,
exp_DERIVE_FLAG.LF_LOAN_CALC_DATE as LF_LOAN_CALC_DATE,
exp_DERIVE_FLAG.LF_SURR_CHG_LST_AN as LF_SURR_CHG_LST_AN,
exp_DERIVE_FLAG.LF_POL_ANNUAL_PREM as LF_POL_ANNUAL_PREM,
exp_DERIVE_FLAG.LF_2ND_INS_DOB as LF_2ND_INS_DOB,
exp_DERIVE_FLAG.LF_2ND_INS_ISS_AGE as LF_2ND_INS_ISS_AGE,
exp_DERIVE_FLAG.LF_INS_ISS_AGE as LF_INS_ISS_AGE,
exp_DERIVE_FLAG.LF_INS_TOBACCO_USE as LF_INS_TOBACCO_USE,
exp_DERIVE_FLAG.LF_INS_SEX_CODE as LF_INS_SEX_CODE,
exp_DERIVE_FLAG.LF_2ND_INS_SEX_CDE as LF_2ND_INS_SEX_CDE,
exp_DERIVE_FLAG.LF_DEATH_BENE_OPT as LF_DEATH_BENE_OPT,
exp_DERIVE_FLAG.LF_2ND_INS_SSAN as LF_2ND_INS_SSAN,
exp_DERIVE_FLAG.LF_RESTRICT_CODE as LF_RESTRICT_CODE,
exp_DERIVE_FLAG.LF_LOAN_INT_RATE as LF_LOAN_INT_RATE,
exp_DERIVE_FLAG.LF_LOAN_INT_ACCRU as LF_LOAN_INT_ACCRU,
exp_DERIVE_FLAG.LF_NEXT_AN_CAS_VAL as LF_NEXT_AN_CAS_VAL,
exp_DERIVE_FLAG.LF_DISPLAY_SW as LF_DISPLAY_SW,
exp_DERIVE_FLAG.LOAD_DT as LOAD_DT,
exp_DERIVE_FLAG.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp,
exp_DERIVE_FLAG.out_FLAG as out_FLAG,
''1'' as out_ECTL_PRGM_ID,
''1'' as out_ECTL_SRC_ID,
''1'' as out_ECTL_SRC_INST_ID,
''1'' as out_ECTL_BATCH_ID,
''1900-01-01'' as out_ORIG_INS_TS,
''1900-01-01'' as out_ECTL_BATCH_START_DATE,
--mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
--mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
--mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
--mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
--mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_ORIG_INS_TS,
--mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
exp_DERIVE_FLAG.FEED_IND as FEED_IND,
exp_DERIVE_FLAG.source_record_id
FROM
exp_DERIVE_FLAG
--LEFT JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_DERIVE_FLAG.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
WHERE exp_DERIVE_FLAG.out_FLAG = ''UPD'';


-- Component exp_GET_EXP_DATE, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_GET_EXP_DATE AS
(
SELECT
rtr_INS_UPD_UPDATE.SC_POLICY_NUM as SC_POLICY_NUM,
rtr_INS_UPD_UPDATE.CHG_EFF_DT_lkp as CHG_EFF_DT,
rtr_INS_UPD_UPDATE.out_ECTL_BATCH_ID as ECTL_BATCH_ID1,
rtr_INS_UPD_UPDATE.out_ORIG_INS_TS as ORIG_INS_TS1,
CURRENT_TIMESTAMP as out_ECTL_END_DATE,
TO_CHAR ( ( DATE_PART(''YYYY'', TO_TIMESTAMP(rtr_INS_UPD_UPDATE.LOAD_DT)) * 10000 ) + ( DATE_PART(''MM'', TO_TIMESTAMP(rtr_INS_UPD_UPDATE.LOAD_DT)) * 100 ) + 1 ) as var_GET_DATE_PART,
 TO_DATE ( var_GET_DATE_PART  )  - 1  as var_CHG_EXP_DT,
CASE WHEN rtr_INS_UPD_UPDATE.CHG_EFF_DT_lkp >= TO_DATE ( var_GET_DATE_PART , ''YYYYMMDD'' ) THEN rtr_INS_UPD_UPDATE.CHG_EFF_DT_lkp ELSE var_CHG_EXP_DT END as out_CHG_EXP_DT,
''UPD'' as out_ECTL_TX_CD,
rtr_INS_UPD_UPDATE.source_record_id
FROM
rtr_INS_UPD_UPDATE
);


-- Component exp_GET_EFF_DATE, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_GET_EFF_DATE AS
(
SELECT
rtr_INS_UPD_INSERT.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY1,
rtr_INS_UPD_INSERT.SC_SERVICE_CENTER as SC_SERVICE_CENTER1,
rtr_INS_UPD_INSERT.SC_POLICY_NUM as SC_POLICY_NUM1,
rtr_INS_UPD_INSERT.SC_FLT_ITEM as SC_FLT_ITEM1,
rtr_INS_UPD_INSERT.SC_FILE_TYPE as SC_FILE_TYPE1,
rtr_INS_UPD_INSERT.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE1,
rtr_INS_UPD_INSERT.SC_TRANS_DATE as SC_TRANS_DATE1,
rtr_INS_UPD_INSERT.SC_TRANS_TYPE as SC_TRANS_TYPE1,
rtr_INS_UPD_INSERT.LF_ALPHA_CODE as LF_ALPHA_CODE1,
rtr_INS_UPD_INSERT.LF_STATUS as LF_STATUS1,
rtr_INS_UPD_INSERT.LF_MODE as LF_MODE1,
rtr_INS_UPD_INSERT.LF_INSURED_SSAN as LF_INSURED_SSAN1,
rtr_INS_UPD_INSERT.LF_MEMBERSHIP as LF_MEMBERSHIP1,
rtr_INS_UPD_INSERT.LF_NFO_OPTION as LF_NFO_OPTION1,
rtr_INS_UPD_INSERT.LF_INSURED_NAME as LF_INSURED_NAME1,
rtr_INS_UPD_INSERT.LF_ADDRESS_1 as LF_ADDRESS_11,
rtr_INS_UPD_INSERT.LF_ADDRESS_2 as LF_ADDRESS_21,
rtr_INS_UPD_INSERT.LF_ADDRESS_3 as LF_ADDRESS_31,
rtr_INS_UPD_INSERT.LF_PAYOR_NAME as LF_PAYOR_NAME1,
rtr_INS_UPD_INSERT.LF_OWNER_NAME as LF_OWNER_NAME1,
rtr_INS_UPD_INSERT.LF_MODAL_PREM as LF_MODAL_PREM1,
rtr_INS_UPD_INSERT.LF_ISSUE_DATE as LF_ISSUE_DATE1,
rtr_INS_UPD_INSERT.LF_APPL_DATE as LF_APPL_DATE1,
rtr_INS_UPD_INSERT.LF_BIRTH_DATE as LF_BIRTH_DATE1,
rtr_INS_UPD_INSERT.LF_PAC_DRAW_DAY as LF_PAC_DRAW_DAY1,
rtr_INS_UPD_INSERT.LF_DUE_USE_CD as LF_DUE_USE_CD1,
rtr_INS_UPD_INSERT.LF_REQUIRE_SW as LF_REQUIRE_SW1,
rtr_INS_UPD_INSERT.LF_PAC_BANK_CD as LF_PAC_BANK_CD1,
rtr_INS_UPD_INSERT.LF_PAC_ACCT_NO as LF_PAC_ACCT_NO1,
rtr_INS_UPD_INSERT.LF_FORM as LF_FORM1,
rtr_INS_UPD_INSERT.LF_VOLUME as LF_VOLUME1,
rtr_INS_UPD_INSERT.LF_APP_PREM as LF_APP_PREM1,
rtr_INS_UPD_INSERT.LF_OVER_SHORT as LF_OVER_SHORT1,
rtr_INS_UPD_INSERT.LF_UNDERWRITER as LF_UNDERWRITER1,
rtr_INS_UPD_INSERT.LF_PLAN_NAME as LF_PLAN_NAME1,
rtr_INS_UPD_INSERT.LF_POLICY_FEE as LF_POLICY_FEE1,
rtr_INS_UPD_INSERT.LF_FUND_BALANCE as LF_FUND_BALANCE1,
rtr_INS_UPD_INSERT.LF_SURR_VALUE as LF_SURR_VALUE1,
rtr_INS_UPD_INSERT.LF_DEP_FUND as LF_DEP_FUND1,
rtr_INS_UPD_INSERT.LF_PD_TO_DATE as LF_PD_TO_DATE1,
rtr_INS_UPD_INSERT.LF_LOAN_AMOUNT as LF_LOAN_AMOUNT1,
rtr_INS_UPD_INSERT.LF_DIV_ON_DEP as LF_DIV_ON_DEP1,
rtr_INS_UPD_INSERT.LF_PAIDUP_ADD as LF_PAIDUP_ADD1,
rtr_INS_UPD_INSERT.LF_CASH_VAL_PUA as LF_CASH_VAL_PUA1,
rtr_INS_UPD_INSERT.LF_ANNUAL_PREM as LF_ANNUAL_PREM1,
rtr_INS_UPD_INSERT.LF_AGENT_NO as LF_AGENT_NO1,
rtr_INS_UPD_INSERT.LF_LOAN_VALUE as LF_LOAN_VALUE1,
rtr_INS_UPD_INSERT.LF_PHY_ISS as LF_PHY_ISS1,
rtr_INS_UPD_INSERT.LF_CANC_REASON_CDE as LF_CANC_REASON_CDE1,
rtr_INS_UPD_INSERT.LF_ISS_AGE as LF_ISS_AGE1,
rtr_INS_UPD_INSERT.LF_2ND_INS_NAME as LF_2ND_INS_NAME1,
rtr_INS_UPD_INSERT.LF_OWNER_ADDRESS_1 as LF_OWNER_ADDRESS_11,
rtr_INS_UPD_INSERT.LF_OWNER_ADDRESS_2 as LF_OWNER_ADDRESS_21,
rtr_INS_UPD_INSERT.LF_OWNER_ADDRESS_3 as LF_OWNER_ADDRESS_31,
rtr_INS_UPD_INSERT.LF_PAYOR_ADDRESS_1 as LF_PAYOR_ADDRESS_11,
rtr_INS_UPD_INSERT.LF_PAYOR_ADDRESS_2 as LF_PAYOR_ADDRESS_21,
rtr_INS_UPD_INSERT.LF_PAYOR_ADDRESS_3 as LF_PAYOR_ADDRESS_31,
rtr_INS_UPD_INSERT.LF_OWNER_SSAN as LF_OWNER_SSAN1,
rtr_INS_UPD_INSERT.LF_LAST_ANN_DATE as LF_LAST_ANN_DATE1,
rtr_INS_UPD_INSERT.LF_FUND_BAL_LST_AN as LF_FUND_BAL_LST_AN1,
rtr_INS_UPD_INSERT.LF_LOAN_CALC_DATE as LF_LOAN_CALC_DATE1,
rtr_INS_UPD_INSERT.LF_SURR_CHG_LST_AN as LF_SURR_CHG_LST_AN1,
rtr_INS_UPD_INSERT.LF_POL_ANNUAL_PREM as LF_POL_ANNUAL_PREM1,
rtr_INS_UPD_INSERT.LF_2ND_INS_DOB as LF_2ND_INS_DOB1,
rtr_INS_UPD_INSERT.LF_2ND_INS_ISS_AGE as LF_2ND_INS_ISS_AGE1,
rtr_INS_UPD_INSERT.LF_INS_ISS_AGE as LF_INS_ISS_AGE1,
rtr_INS_UPD_INSERT.LF_INS_TOBACCO_USE as LF_INS_TOBACCO_USE1,
rtr_INS_UPD_INSERT.LF_INS_SEX_CODE as LF_INS_SEX_CODE1,
rtr_INS_UPD_INSERT.LF_2ND_INS_SEX_CDE as LF_2ND_INS_SEX_CDE1,
rtr_INS_UPD_INSERT.LF_DEATH_BENE_OPT as LF_DEATH_BENE_OPT1,
rtr_INS_UPD_INSERT.LF_2ND_INS_SSAN as LF_2ND_INS_SSAN1,
rtr_INS_UPD_INSERT.LF_RESTRICT_CODE as LF_RESTRICT_CODE1,
rtr_INS_UPD_INSERT.LF_LOAN_INT_RATE as LF_LOAN_INT_RATE1,
rtr_INS_UPD_INSERT.LF_LOAN_INT_ACCRU as LF_LOAN_INT_ACCRU1,
rtr_INS_UPD_INSERT.LF_NEXT_AN_CAS_VAL as LF_NEXT_AN_CAS_VAL1,
rtr_INS_UPD_INSERT.LF_DISPLAY_SW as LF_DISPLAY_SW1,
rtr_INS_UPD_INSERT.out_ECTL_PRGM_ID as ECTL_PRGM_ID1,
rtr_INS_UPD_INSERT.out_ECTL_SRC_ID as ECTL_SRC_ID1,
rtr_INS_UPD_INSERT.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID1,
rtr_INS_UPD_INSERT.out_ECTL_BATCH_ID as ECTL_BATCH_ID1,
rtr_INS_UPD_INSERT.out_ORIG_INS_TS as ORIG_INS_TS1,
rtr_INS_UPD_INSERT.out_ECTL_BATCH_START_DATE as ECTL_BATCH_START_DATE1,
TO_CHAR ( ( DATE_PART(''YYYY'', TO_TIMESTAMP(rtr_INS_UPD_INSERT.LOAD_DT)) * 10000 ) + ( DATE_PART(''MM'', TO_TIMESTAMP(rtr_INS_UPD_INSERT.LOAD_DT)) * 100 ) + 1 ) as var_GET_DATE_PART,
TO_DATE ( var_GET_DATE_PART , ''YYYYMMDD'' ) as var_CHG_EFF_DT,
CASE WHEN rtr_INS_UPD_INSERT.CHG_EFF_DT_lkp >= var_CHG_EFF_DT THEN  rtr_INS_UPD_INSERT.CHG_EFF_DT_lkp + 1 ELSE var_CHG_EFF_DT END as out_CHG_EFF_DT,
TO_DATE ( ''12/31/9999'' , ''MM/DD/YYYY'' ) as out_CHG_EXP_DT,
''NEW'' as out_ECTL_TX_CD,
rtr_INS_UPD_INSERT.FEED_IND as FEED_IND1,
TO_DATE ( ''12/31/9999'' , ''MM/DD/YYYY'' ) as out_ECTL_END_DATE,
rtr_INS_UPD_INSERT.source_record_id
FROM
rtr_INS_UPD_INSERT
);


-- Component LIFEPOLS_INS, Type TARGET 
INSERT INTO DB_T_CORE_MEMBXREF_PROD.LIFEPOLS
(
SC_DWNLD_PRIORITY,
SC_SERVICE_CENTER,
SC_POLICY_NUM,
CHG_EFF_DT,
CHG_EXP_DT,
SC_FLT_ITEM,
SC_FILE_TYPE,
SC_REC_TRANS_CODE,
SC_TRANS_DATE,
SC_TRANS_TYPE,
LF_ALPHA_CODE,
LF_STATUS,
LF_MODE,
LF_INSURED_SSAN,
LF_MEMBERSHIP,
LF_NFO_OPTION,
LF_INSURED_NAME,
LF_ADDRESS_1,
LF_ADDRESS_2,
LF_ADDRESS_3,
LF_PAYOR_NAME,
LF_OWNER_NAME,
LF_MODAL_PREM,
LF_ISSUE_DATE,
LF_APPL_DATE,
LF_BIRTH_DATE,
LF_PAC_DRAW_DAY,
LF_DUE_USE_CD,
LF_REQUIRE_SW,
LF_PAC_BANK_CD,
LF_PAC_ACCT_NO,
LF_FORM,
LF_VOLUME,
LF_APP_PREM,
LF_OVER_SHORT,
LF_UNDERWRITER,
LF_PLAN_NAME,
LF_POLICY_FEE,
LF_FUND_BALANCE,
LF_SURR_VALUE,
LF_DEP_FUND,
LF_PD_TO_DATE,
LF_LOAN_AMOUNT,
LF_DIV_ON_DEP,
LF_PAIDUP_ADD,
LF_CASH_VAL_PUA,
LF_ANNUAL_PREM,
LF_AGENT_NO,
LF_LOAN_VALUE,
LF_PHY_ISS,
LF_CANC_REASON_CDE,
LF_ISS_AGE,
LF_2ND_INS_NAME,
LF_OWNER_ADDRESS_1,
LF_OWNER_ADDRESS_2,
LF_OWNER_ADDRESS_3,
LF_PAYOR_ADDRESS_1,
LF_PAYOR_ADDRESS_2,
LF_PAYOR_ADDRESS_3,
LF_OWNER_SSAN,
LF_LAST_ANN_DATE,
LF_FUND_BAL_LST_AN,
LF_LOAN_CALC_DATE,
LF_SURR_CHG_LST_AN,
LF_POL_ANNUAL_PREM,
LF_2ND_INS_DOB,
LF_2ND_INS_ISS_AGE,
LF_INS_ISS_AGE,
LF_INS_TOBACCO_USE,
LF_INS_SEX_CODE,
LF_2ND_INS_SEX_CDE,
LF_DEATH_BENE_OPT,
LF_2ND_INS_SSAN,
LF_RESTRICT_CODE,
LF_LOAN_INT_RATE,
LF_LOAN_INT_ACCRU,
LF_NEXT_AN_CAS_VAL,
LF_DISPLAY_SW,
FEED_IND,
ECTL_BATCH_ID,
ECTL_ORIG_INS_TS,
ECTL_MODIFY_TS,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_PRGM_ID,
ECTL_TX_CD,
ECTL_START_DATE,
ECTL_END_DATE
)
SELECT
exp_GET_EFF_DATE.SC_DWNLD_PRIORITY1 as SC_DWNLD_PRIORITY,
exp_GET_EFF_DATE.SC_SERVICE_CENTER1 as SC_SERVICE_CENTER,
exp_GET_EFF_DATE.SC_POLICY_NUM1 as SC_POLICY_NUM,
exp_GET_EFF_DATE.out_CHG_EFF_DT as CHG_EFF_DT,
exp_GET_EFF_DATE.out_CHG_EXP_DT as CHG_EXP_DT,
exp_GET_EFF_DATE.SC_FLT_ITEM1 as SC_FLT_ITEM,
exp_GET_EFF_DATE.SC_FILE_TYPE1 as SC_FILE_TYPE,
exp_GET_EFF_DATE.SC_REC_TRANS_CODE1 as SC_REC_TRANS_CODE,
exp_GET_EFF_DATE.SC_TRANS_DATE1 as SC_TRANS_DATE,
exp_GET_EFF_DATE.SC_TRANS_TYPE1 as SC_TRANS_TYPE,
exp_GET_EFF_DATE.LF_ALPHA_CODE1 as LF_ALPHA_CODE,
exp_GET_EFF_DATE.LF_STATUS1 as LF_STATUS,
exp_GET_EFF_DATE.LF_MODE1 as LF_MODE,
exp_GET_EFF_DATE.LF_INSURED_SSAN1 as LF_INSURED_SSAN,
exp_GET_EFF_DATE.LF_MEMBERSHIP1 as LF_MEMBERSHIP,
exp_GET_EFF_DATE.LF_NFO_OPTION1 as LF_NFO_OPTION,
exp_GET_EFF_DATE.LF_INSURED_NAME1 as LF_INSURED_NAME,
exp_GET_EFF_DATE.LF_ADDRESS_11 as LF_ADDRESS_1,
exp_GET_EFF_DATE.LF_ADDRESS_21 as LF_ADDRESS_2,
exp_GET_EFF_DATE.LF_ADDRESS_31 as LF_ADDRESS_3,
exp_GET_EFF_DATE.LF_PAYOR_NAME1 as LF_PAYOR_NAME,
exp_GET_EFF_DATE.LF_OWNER_NAME1 as LF_OWNER_NAME,
exp_GET_EFF_DATE.LF_MODAL_PREM1 as LF_MODAL_PREM,
exp_GET_EFF_DATE.LF_ISSUE_DATE1 as LF_ISSUE_DATE,
exp_GET_EFF_DATE.LF_APPL_DATE1 as LF_APPL_DATE,
exp_GET_EFF_DATE.LF_BIRTH_DATE1 as LF_BIRTH_DATE,
exp_GET_EFF_DATE.LF_PAC_DRAW_DAY1 as LF_PAC_DRAW_DAY,
exp_GET_EFF_DATE.LF_DUE_USE_CD1 as LF_DUE_USE_CD,
exp_GET_EFF_DATE.LF_REQUIRE_SW1 as LF_REQUIRE_SW,
exp_GET_EFF_DATE.LF_PAC_BANK_CD1 as LF_PAC_BANK_CD,
exp_GET_EFF_DATE.LF_PAC_ACCT_NO1 as LF_PAC_ACCT_NO,
exp_GET_EFF_DATE.LF_FORM1 as LF_FORM,
exp_GET_EFF_DATE.LF_VOLUME1 as LF_VOLUME,
exp_GET_EFF_DATE.LF_APP_PREM1 as LF_APP_PREM,
exp_GET_EFF_DATE.LF_OVER_SHORT1 as LF_OVER_SHORT,
exp_GET_EFF_DATE.LF_UNDERWRITER1 as LF_UNDERWRITER,
exp_GET_EFF_DATE.LF_PLAN_NAME1 as LF_PLAN_NAME,
exp_GET_EFF_DATE.LF_POLICY_FEE1 as LF_POLICY_FEE,
exp_GET_EFF_DATE.LF_FUND_BALANCE1 as LF_FUND_BALANCE,
exp_GET_EFF_DATE.LF_SURR_VALUE1 as LF_SURR_VALUE,
exp_GET_EFF_DATE.LF_DEP_FUND1 as LF_DEP_FUND,
exp_GET_EFF_DATE.LF_PD_TO_DATE1 as LF_PD_TO_DATE,
exp_GET_EFF_DATE.LF_LOAN_AMOUNT1 as LF_LOAN_AMOUNT,
exp_GET_EFF_DATE.LF_DIV_ON_DEP1 as LF_DIV_ON_DEP,
exp_GET_EFF_DATE.LF_PAIDUP_ADD1 as LF_PAIDUP_ADD,
exp_GET_EFF_DATE.LF_CASH_VAL_PUA1 as LF_CASH_VAL_PUA,
exp_GET_EFF_DATE.LF_ANNUAL_PREM1 as LF_ANNUAL_PREM,
exp_GET_EFF_DATE.LF_AGENT_NO1 as LF_AGENT_NO,
exp_GET_EFF_DATE.LF_LOAN_VALUE1 as LF_LOAN_VALUE,
exp_GET_EFF_DATE.LF_PHY_ISS1 as LF_PHY_ISS,
exp_GET_EFF_DATE.LF_CANC_REASON_CDE1 as LF_CANC_REASON_CDE,
exp_GET_EFF_DATE.LF_ISS_AGE1 as LF_ISS_AGE,
exp_GET_EFF_DATE.LF_2ND_INS_NAME1 as LF_2ND_INS_NAME,
exp_GET_EFF_DATE.LF_OWNER_ADDRESS_11 as LF_OWNER_ADDRESS_1,
exp_GET_EFF_DATE.LF_OWNER_ADDRESS_21 as LF_OWNER_ADDRESS_2,
exp_GET_EFF_DATE.LF_OWNER_ADDRESS_31 as LF_OWNER_ADDRESS_3,
exp_GET_EFF_DATE.LF_PAYOR_ADDRESS_11 as LF_PAYOR_ADDRESS_1,
exp_GET_EFF_DATE.LF_PAYOR_ADDRESS_21 as LF_PAYOR_ADDRESS_2,
exp_GET_EFF_DATE.LF_PAYOR_ADDRESS_31 as LF_PAYOR_ADDRESS_3,
exp_GET_EFF_DATE.LF_OWNER_SSAN1 as LF_OWNER_SSAN,
exp_GET_EFF_DATE.LF_LAST_ANN_DATE1 as LF_LAST_ANN_DATE,
exp_GET_EFF_DATE.LF_FUND_BAL_LST_AN1 as LF_FUND_BAL_LST_AN,
exp_GET_EFF_DATE.LF_LOAN_CALC_DATE1 as LF_LOAN_CALC_DATE,
exp_GET_EFF_DATE.LF_SURR_CHG_LST_AN1 as LF_SURR_CHG_LST_AN,
exp_GET_EFF_DATE.LF_POL_ANNUAL_PREM1 as LF_POL_ANNUAL_PREM,
exp_GET_EFF_DATE.LF_2ND_INS_DOB1 as LF_2ND_INS_DOB,
exp_GET_EFF_DATE.LF_2ND_INS_ISS_AGE1 as LF_2ND_INS_ISS_AGE,
exp_GET_EFF_DATE.LF_INS_ISS_AGE1 as LF_INS_ISS_AGE,
exp_GET_EFF_DATE.LF_INS_TOBACCO_USE1 as LF_INS_TOBACCO_USE,
exp_GET_EFF_DATE.LF_INS_SEX_CODE1 as LF_INS_SEX_CODE,
exp_GET_EFF_DATE.LF_2ND_INS_SEX_CDE1 as LF_2ND_INS_SEX_CDE,
exp_GET_EFF_DATE.LF_DEATH_BENE_OPT1 as LF_DEATH_BENE_OPT,
exp_GET_EFF_DATE.LF_2ND_INS_SSAN1 as LF_2ND_INS_SSAN,
exp_GET_EFF_DATE.LF_RESTRICT_CODE1 as LF_RESTRICT_CODE,
exp_GET_EFF_DATE.LF_LOAN_INT_RATE1 as LF_LOAN_INT_RATE,
exp_GET_EFF_DATE.LF_LOAN_INT_ACCRU1 as LF_LOAN_INT_ACCRU,
exp_GET_EFF_DATE.LF_NEXT_AN_CAS_VAL1 as LF_NEXT_AN_CAS_VAL,
exp_GET_EFF_DATE.LF_DISPLAY_SW1 as LF_DISPLAY_SW,
exp_GET_EFF_DATE.FEED_IND1 as FEED_IND,
exp_GET_EFF_DATE.ECTL_BATCH_ID1 as ECTL_BATCH_ID,
exp_GET_EFF_DATE.ORIG_INS_TS1 as ECTL_ORIG_INS_TS,
exp_GET_EFF_DATE.ORIG_INS_TS1 as ECTL_MODIFY_TS,
exp_GET_EFF_DATE.ECTL_SRC_ID1 as ECTL_SRC_ID,
exp_GET_EFF_DATE.ECTL_SRC_INST_ID1 as ECTL_SRC_INST_ID,
exp_GET_EFF_DATE.ECTL_PRGM_ID1 as ECTL_PRGM_ID,
exp_GET_EFF_DATE.out_ECTL_TX_CD as ECTL_TX_CD,
exp_GET_EFF_DATE.ECTL_BATCH_START_DATE1 as ECTL_START_DATE,
exp_GET_EFF_DATE.out_ECTL_END_DATE as ECTL_END_DATE
FROM
exp_GET_EFF_DATE;


-- Component upd_LIFEPOLS, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_LIFEPOLS AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
exp_GET_EXP_DATE.SC_POLICY_NUM as SC_POLICY_NUM1,
exp_GET_EXP_DATE.CHG_EFF_DT as CHG_EFF_DT,
exp_GET_EXP_DATE.out_CHG_EXP_DT as CHG_EXP_DT,
exp_GET_EXP_DATE.ECTL_BATCH_ID1 as ECTL_BATCH_ID1,
exp_GET_EXP_DATE.ORIG_INS_TS1 as ORIG_INS_TS1,
exp_GET_EXP_DATE.out_ECTL_END_DATE as ECTL_END_DATE,
exp_GET_EXP_DATE.out_ECTL_TX_CD as ECTL_TX_CD,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_GET_EXP_DATE
);


-- Component LIFEPOLS_UPD, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_core_MEMBXREF_PROD.LIFEPOLS
USING upd_LIFEPOLS
ON (SC_POLICY_NUM = upd_LIFEPOLS.SC_POLICY_NUM1 AND DB_T_core_MEMBXREF_PROD.LIFEPOLS.CHG_EFF_DT = upd_LIFEPOLS.CHG_EFF_DT)
WHEN MATCHED THEN UPDATE SET
ECTL_BATCH_ID = upd_LIFEPOLS.ECTL_BATCH_ID1,ECTL_END_DATE =upd_LIFEPOLS.ECTL_END_DATE,
--ECTL_MODIFY_TS = upd_LIFEPOLS.ECTL_MODIFY_TS,
ECTL_TX_CD = upd_LIFEPOLS.ECTL_TX_CD,
CHG_EXP_DT = upd_LIFEPOLS.CHG_EXP_DT;


-- PIPELINE END FOR 2

END; ';