-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOANS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE PMMAPPINGNAME varchar;
PROJ_ID varchar;
BATCH_ACTIVE_IND varchar;
BEGIN 

PMMAPPINGNAME:=''M_LOANS'';
BATCH_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 

-- Component LKP_STG_MEMBXREF_TRIGGER, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_STG_MEMBXREF_TRIGGER AS
(
SELECT
TABLENAME,
FEED_DT
FROM DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER
);


-- PIPELINE START FOR 1

-- Component SQ_LOANS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_LOANS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as CHG_EFF_DT,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT LOANS.SC_POLICY_NUM ,LOANS.CHG_EFF_DT 
FROM
 DB_T_CORE_MEMBXREF_PROD.LOANS WHERE CHG_EXP_DT = CAST(''9999-12-31'' AS DATE ) 
) SRC
)
);


-- Component exp_ASSIGN_DUMMY_TG, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ASSIGN_DUMMY_TG AS
(
SELECT
SQ_LOANS.SC_POLICY_NUM as SC_POLICY_NUM,
SQ_LOANS.CHG_EFF_DT as CHG_EFF_DT,
''LOANS'' as var_TABLENAME,
LKP_1.FEED_DT /* replaced lookup LKP_STG_MEMBXREF_TRIGGER */ as var_FEED_DT,
var_FEED_DT as out_FEED_DT,
SQ_LOANS.source_record_id,
row_number() over (partition by SQ_LOANS.source_record_id order by SQ_LOANS.source_record_id) as RNK
FROM
SQ_LOANS
LEFT JOIN LKP_STG_MEMBXREF_TRIGGER LKP_1 ON LKP_1.TABLENAME = var_TABLENAME
QUALIFY RNK = 1
);


-- Component LKP_STG_LOANS, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_STG_LOANS AS
(
SELECT
LKP.SC_POLICY_NUM,
exp_ASSIGN_DUMMY_TG.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_ASSIGN_DUMMY_TG.source_record_id ORDER BY LKP.SC_POLICY_NUM asc) RNK
FROM
exp_ASSIGN_DUMMY_TG
LEFT JOIN (
SELECT LTRIM(RTRIM(STG_LOANS.SC_POLICY_NUM)) as SC_POLICY_NUM FROM DB_T_STAG_MEMBXREF_PROD.STG_LOANS WHERE
 STG_LOANS. LOAD_DT=(SELECT FEED_DT FROM DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER WHERE TABLENAME=''LOANS'')
) LKP ON LKP.SC_POLICY_NUM = exp_ASSIGN_DUMMY_TG.SC_POLICY_NUM
QUALIFY RNK = 1
);


-- Component fil_EXPIRED_POLS, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE fil_EXPIRED_POLS AS
(
SELECT
LKP_STG_LOANS.SC_POLICY_NUM as SC_POLICY_NUM_tgt,
exp_ASSIGN_DUMMY_TG.CHG_EFF_DT as CHG_EFF_DT,
exp_ASSIGN_DUMMY_TG.SC_POLICY_NUM as SC_POLICY_NUM_src,
exp_ASSIGN_DUMMY_TG.out_FEED_DT as LOAD_DT,
exp_ASSIGN_DUMMY_TG.source_record_id
FROM
exp_ASSIGN_DUMMY_TG
LEFT JOIN LKP_STG_LOANS ON exp_ASSIGN_DUMMY_TG.source_record_id = LKP_STG_LOANS.source_record_id
WHERE LKP_STG_LOANS.SC_POLICY_NUM IS NULL
);


-- Component exp_INPUT_ECTL_FIELDS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_INPUT_ECTL_FIELDS AS
(
SELECT
fil_EXPIRED_POLS.CHG_EFF_DT as CHG_EFF_DT,
fil_EXPIRED_POLS.SC_POLICY_NUM_src as SC_POLICY_NUM_src,
LTRIM ( RTRIM ( :PMMappingName ) ) as out_PROJ_NAME,
:PROJ_ID as out_PROJ_ID,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
:PROJ_ID as IN_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as IN_BATCH_ACTIVE_IND,
''m_STG_FIN_CLM'' IN_PRGM_NM,
null IN_TABLE_NM,
''UPD'' as ECTL_TX_CD,
TO_CHAR ( ( DATE_PART(''YYYY'', TO_TIMESTAMP(fil_EXPIRED_POLS.LOAD_DT)) * 10000 ) + ( DATE_PART(''MM'', TO_TIMESTAMP(fil_EXPIRED_POLS.LOAD_DT)) * 100 ) + 1 ) as var_FIRST_DAY_EFF_DT,
 TO_DATE ( var_FIRST_DAY_EFF_DT  ) - 1  as var_CHG_EXP_DT_NEW,
CASE WHEN fil_EXPIRED_POLS.CHG_EFF_DT >= var_CHG_EXP_DT_NEW THEN fil_EXPIRED_POLS.CHG_EFF_DT ELSE var_CHG_EXP_DT_NEW END as out_CHG_EXP_DT_NEW,
CURRENT_TIMESTAMP as out_ECTL_END_DATE,
fil_EXPIRED_POLS.source_record_id
FROM
fil_EXPIRED_POLS
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''exp_INPUT_ECTL_FIELDS'');

-- Component upd_LOANS_EXPIRED_POLS, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_LOANS_EXPIRED_POLS AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
--''1'' as ECTL_BATCH_ID,
--''1900-01-01'' as ECTL_MODIFY_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1.out_ORIG_INS_TS as ECTL_MODIFY_TS,
exp_INPUT_ECTL_FIELDS.out_ECTL_END_DATE as ECTL_END_DATE,
exp_INPUT_ECTL_FIELDS.SC_POLICY_NUM_src as SC_POLICY_NUM,
exp_INPUT_ECTL_FIELDS.CHG_EFF_DT as CHG_EFF_DT,
exp_INPUT_ECTL_FIELDS.ECTL_TX_CD as ECTL_TX_CD,
exp_INPUT_ECTL_FIELDS.out_CHG_EXP_DT_NEW as CHG_EXP_DT,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_INPUT_ECTL_FIELDS
LEFT JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1 ON exp_INPUT_ECTL_FIELDS.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1.source_record_id
);


-- Component LOANS_UPD_EXPIRED_POLS, Type TARGET 
INSERT INTO DB_T_CORE_MEMBXREF_PROD.LOANS
(
SC_POLICY_NUM,
CHG_EFF_DT,
CHG_EXP_DT,
ECTL_BATCH_ID,
ECTL_MODIFY_TS,
ECTL_TX_CD,
ECTL_END_DATE
)
SELECT
upd_LOANS_EXPIRED_POLS.SC_POLICY_NUM as SC_POLICY_NUM,
upd_LOANS_EXPIRED_POLS.CHG_EFF_DT as CHG_EFF_DT,
upd_LOANS_EXPIRED_POLS.CHG_EXP_DT as CHG_EXP_DT,
upd_LOANS_EXPIRED_POLS.ECTL_BATCH_ID as ECTL_BATCH_ID,
upd_LOANS_EXPIRED_POLS.ECTL_MODIFY_TS as ECTL_MODIFY_TS,
upd_LOANS_EXPIRED_POLS.ECTL_TX_CD as ECTL_TX_CD,
upd_LOANS_EXPIRED_POLS.ECTL_END_DATE as ECTL_END_DATE
FROM
upd_LOANS_EXPIRED_POLS
WHERE UPDATE_STRATEGY_ACTION = 0;

/* Perform Updates */
MERGE INTO DB_T_CORE_MEMBXREF_PROD.LOANS
USING upd_LOANS_EXPIRED_POLS ON (UPDATE_STRATEGY_ACTION = 1  )
WHEN MATCHED THEN UPDATE
SET
SC_POLICY_NUM = upd_LOANS_EXPIRED_POLS.SC_POLICY_NUM,
CHG_EFF_DT = upd_LOANS_EXPIRED_POLS.CHG_EFF_DT,
CHG_EXP_DT = upd_LOANS_EXPIRED_POLS.CHG_EXP_DT,
ECTL_BATCH_ID = upd_LOANS_EXPIRED_POLS.ECTL_BATCH_ID,
ECTL_MODIFY_TS = upd_LOANS_EXPIRED_POLS.ECTL_MODIFY_TS,
ECTL_TX_CD = upd_LOANS_EXPIRED_POLS.ECTL_TX_CD,
ECTL_END_DATE = upd_LOANS_EXPIRED_POLS.ECTL_END_DATE
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component sq_STG_LOANS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_LOANS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_SERVICE_CENTER,
$2 as SC_POLICY_NUM,
$3 as PC_ALPHA_CODE,
$4 as PC_NAME_1,
$5 as PC_NAME_2,
$6 as PC_ADDRESS_1,
$7 as PC_ADDRESS_2,
$8 as PC_CITYST,
$9 as PC_ZIP,
$10 as PC_AGENT,
$11 as PC_MEMBER_NUMBER,
$12 as PC_COMPANY,
$13 as SC_DWNLD_PRIORITY,
$14 as SC_FLT_ITEM,
$15 as SC_FILE_TYPE,
$16 as SC_REC_TRANS_CODE,
$17 as SC_TRANS_DATE,
$18 as SC_TRANS_TYPE,
$19 as PC_INCEPT_DATE,
$20 as LN_STATUS,
$21 as LN_DUE_DATE,
$22 as LN_AMOUNT_DUE,
$23 as LN_NBR_PMNTS_PAID,
$24 as LN_BALANCE,
$25 as LN_PAYOFF_AMT,
$26 as LN_NBR_PMNTS_LATE,
$27 as LN_LATE_CHARGE_AMT,
$28 as LN_ORIGINAL_TERM,
$29 as LN_ORIGINL_AMT_FIN,
$30 as LN_COLLATERAL_DESC,
$31 as LN_CRDT_LIFE_IND,
$32 as LN_A_H_IND,
$33 as LN_PER_DIEM,
$34 as LN_YTD_INTEREST,
$35 as LN_PREV_YTD_INT,
$36 as LN_SSN,
$37 as LN_WORK_PHONE_NBR,
$38 as LN_HOME_PHONE_NBR,
$39 as LN_LAST_PAYMT_DATE,
$40 as LN_INT_RATE,
$41 as LOAD_DT,
$42 as FEED_IND,
$43 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 
STG_LOANS.SC_SERVICE_CENTER AS SC_SERVICE_CENTER , 
LTRIM(RTRIM(STG_LOANS.SC_POLICY_NUM)) AS SC_POLICY_NUM , 
LTRIM(RTRIM(STG_LOANS.PC_ALPHA_CODE)) AS PC_ALPHA_CODE , 
LTRIM(RTRIM(STG_LOANS.PC_NAME_1)) AS PC_NAME_1 , 
LTRIM(RTRIM(STG_LOANS.PC_NAME_2)) AS PC_NAME_2 , 
LTRIM(RTRIM(STG_LOANS.PC_ADDRESS_1)) AS PC_ADDRESS_1 , 
LTRIM(RTRIM(STG_LOANS.PC_ADDRESS_2)) AS PC_ADDRESS_2 , 
LTRIM(RTRIM(STG_LOANS.PC_CITYST)) AS PC_CITYST , 
LTRIM(RTRIM(STG_LOANS.PC_ZIP)) AS PC_ZIP , 
STG_LOANS.PC_AGENT AS PC_AGENT , 
LTRIM(RTRIM(STG_LOANS.PC_MEMBER_NUMBER)) AS PC_MEMBER_NUMBER , 
LTRIM(RTRIM(STG_LOANS.PC_COMPANY)) AS PC_COMPANY , 
STG_LOANS.SC_DWNLD_PRIORITY AS SC_DWNLD_PRIORITY , 
LTRIM(RTRIM(STG_LOANS.SC_FLT_ITEM)) AS SC_FLT_ITEM , 
STG_LOANS.SC_FILE_TYPE AS SC_FILE_TYPE , 
STG_LOANS.SC_REC_TRANS_CODE AS SC_REC_TRANS_CODE , 
STG_LOANS.SC_TRANS_DATE AS SC_TRANS_DATE , 
STG_LOANS.SC_TRANS_TYPE AS SC_TRANS_TYPE , 
STG_LOANS.PC_INCEPT_DATE AS PC_INCEPT_DATE , 
LTRIM(RTRIM(STG_LOANS.LN_STATUS)) AS LN_STATUS , 
STG_LOANS.LN_DUE_DATE AS LN_DUE_DATE , 
STG_LOANS.LN_AMOUNT_DUE AS LN_AMOUNT_DUE , 
STG_LOANS.LN_NBR_PMNTS_PAID AS LN_NBR_PMNTS_PAID , 
STG_LOANS.LN_BALANCE AS LN_BALANCE , 
STG_LOANS.LN_PAYOFF_AMT AS LN_PAYOFF_AMT , 
STG_LOANS.LN_NBR_PMNTS_LATE AS LN_NBR_PMNTS_LATE , 
STG_LOANS.LN_LATE_CHARGE_AMT AS LN_LATE_CHARGE_AMT , 
STG_LOANS.LN_ORIGINAL_TERM AS LN_ORIGINAL_TERM , 
STG_LOANS.LN_ORIGINL_AMT_FIN AS LN_ORIGINL_AMT_FIN , 
LTRIM(RTRIM(STG_LOANS.LN_COLLATERAL_DESC)) AS LN_COLLATERAL_DESC , 
LTRIM(RTRIM(STG_LOANS.LN_CRDT_LIFE_IND)) AS LN_CRDT_LIFE_IND , 
LTRIM(RTRIM(STG_LOANS.LN_A_H_IND)) AS LN_A_H_IND , 
STG_LOANS.LN_PER_DIEM AS LN_PER_DIEM , 
STG_LOANS.LN_YTD_INTEREST AS LN_YTD_INTEREST , 
STG_LOANS.LN_PREV_YTD_INT AS LN_PREV_YTD_INT , 
LTRIM(RTRIM(STG_LOANS.LN_SSN)) AS LN_SSN , 
LTRIM(RTRIM(STG_LOANS.LN_WORK_PHONE_NBR)) AS LN_WORK_PHONE_NBR , 
LTRIM(RTRIM(STG_LOANS.LN_HOME_PHONE_NBR)) AS LN_HOME_PHONE_NBR , 
STG_LOANS.LN_LAST_PAYMT_DATE AS LN_LAST_PAYMT_DATE , 
STG_LOANS.LN_INT_RATE AS LN_INT_RATE , 
STG_LOANS.LOAD_DT LOAD_DT,
LTRIM(RTRIM(STG_LOANS.FEED_IND)) AS FEED_IND FROM DB_T_STAG_MEMBXREF_PROD.STG_LOANS STG_LOANS WHERE   LOAD_DT=(SELECT FEED_DT FROM DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER WHERE TABLENAME=''LOANS'')
) SRC
)
);


-- Component exp_HOLD_DATA, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_HOLD_DATA AS
(
SELECT
sq_STG_LOANS.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
sq_STG_LOANS.SC_POLICY_NUM as SC_POLICY_NUM,
sq_STG_LOANS.PC_ALPHA_CODE as PC_ALPHA_CODE,
sq_STG_LOANS.PC_NAME_1 as PC_NAME_1,
sq_STG_LOANS.PC_NAME_2 as PC_NAME_2,
sq_STG_LOANS.PC_ADDRESS_1 as PC_ADDRESS_1,
sq_STG_LOANS.PC_ADDRESS_2 as PC_ADDRESS_2,
sq_STG_LOANS.PC_CITYST as PC_CITYST,
sq_STG_LOANS.PC_ZIP as PC_ZIP,
sq_STG_LOANS.PC_AGENT as PC_AGENT,
sq_STG_LOANS.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
sq_STG_LOANS.PC_COMPANY as PC_COMPANY,
sq_STG_LOANS.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
sq_STG_LOANS.SC_FLT_ITEM as SC_FLT_ITEM,
sq_STG_LOANS.SC_FILE_TYPE as SC_FILE_TYPE,
sq_STG_LOANS.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
sq_STG_LOANS.SC_TRANS_DATE as SC_TRANS_DATE,
sq_STG_LOANS.SC_TRANS_TYPE as SC_TRANS_TYPE,
sq_STG_LOANS.PC_INCEPT_DATE as PC_INCEPT_DATE,
sq_STG_LOANS.LN_STATUS as LN_STATUS,
sq_STG_LOANS.LN_DUE_DATE as LN_DUE_DATE,
sq_STG_LOANS.LN_AMOUNT_DUE as LN_AMOUNT_DUE,
sq_STG_LOANS.LN_NBR_PMNTS_PAID as LN_NBR_PMNTS_PAID,
sq_STG_LOANS.LN_BALANCE as LN_BALANCE,
sq_STG_LOANS.LN_PAYOFF_AMT as LN_PAYOFF_AMT,
sq_STG_LOANS.LN_NBR_PMNTS_LATE as LN_NBR_PMNTS_LATE,
sq_STG_LOANS.LN_LATE_CHARGE_AMT as LN_LATE_CHARGE_AMT,
sq_STG_LOANS.LN_ORIGINAL_TERM as LN_ORIGINAL_TERM,
sq_STG_LOANS.LN_ORIGINL_AMT_FIN as LN_ORIGINL_AMT_FIN,
sq_STG_LOANS.LN_COLLATERAL_DESC as LN_COLLATERAL_DESC,
sq_STG_LOANS.LN_CRDT_LIFE_IND as LN_CRDT_LIFE_IND,
sq_STG_LOANS.LN_A_H_IND as LN_A_H_IND,
sq_STG_LOANS.LN_PER_DIEM as LN_PER_DIEM,
sq_STG_LOANS.LN_YTD_INTEREST as LN_YTD_INTEREST,
sq_STG_LOANS.LN_PREV_YTD_INT as LN_PREV_YTD_INT,
sq_STG_LOANS.LN_SSN as LN_SSN,
sq_STG_LOANS.LN_WORK_PHONE_NBR as LN_WORK_PHONE_NBR,
sq_STG_LOANS.LN_HOME_PHONE_NBR as LN_HOME_PHONE_NBR,
sq_STG_LOANS.LN_LAST_PAYMT_DATE as LN_LAST_PAYMT_DATE,
sq_STG_LOANS.LN_INT_RATE as LN_INT_RATE,
sq_STG_LOANS.LOAD_DT as LOAD_DT,
sq_STG_LOANS.FEED_IND as FEED_IND,
sq_STG_LOANS.source_record_id
FROM
sq_STG_LOANS
);


-- Component LKP_LOANS, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_LOANS AS
(
SELECT
LKP.SC_SERVICE_CENTER,
LKP.SC_POLICY_NUM,
LKP.CHG_EFF_DT,
LKP.CHG_EXP_DT,
LKP.PC_ALPHA_CODE,
LKP.PC_NAME_1,
LKP.PC_NAME_2,
LKP.PC_ADDRESS_1,
LKP.PC_ADDRESS_2,
LKP.PC_CITYST,
LKP.PC_ZIP,
LKP.PC_AGENT,
LKP.PC_MEMBER_NUMBER,
LKP.PC_COMPANY,
LKP.SC_DWNLD_PRIORITY,
LKP.SC_FLT_ITEM,
LKP.SC_FILE_TYPE,
LKP.SC_REC_TRANS_CODE,
LKP.SC_TRANS_DATE,
LKP.SC_TRANS_TYPE,
LKP.PC_INCEPT_DATE,
LKP.LN_STATUS,
LKP.LN_DUE_DATE,
LKP.LN_AMOUNT_DUE,
LKP.LN_NBR_PMNTS_PAID,
LKP.LN_BALANCE,
LKP.LN_PAYOFF_AMT,
LKP.LN_NBR_PMNTS_LATE,
LKP.LN_LATE_CHARGE_AMT,
LKP.LN_ORIGINAL_TERM,
LKP.LN_ORIGINL_AMT_FIN,
LKP.LN_COLLATERAL_DESC,
LKP.LN_CRDT_LIFE_IND,
LKP.LN_A_H_IND,
LKP.LN_PER_DIEM,
LKP.LN_YTD_INTEREST,
LKP.LN_PREV_YTD_INT,
LKP.LN_SSN,
LKP.LN_WORK_PHONE_NBR,
LKP.LN_HOME_PHONE_NBR,
LKP.LN_LAST_PAYMT_DATE,
LKP.LN_INT_RATE,
LKP.FEED_IND,
exp_HOLD_DATA.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_HOLD_DATA.source_record_id ORDER BY LKP.SC_SERVICE_CENTER asc,LKP.SC_POLICY_NUM asc,LKP.CHG_EFF_DT asc,LKP.CHG_EXP_DT asc,LKP.PC_ALPHA_CODE asc,LKP.PC_NAME_1 asc,LKP.PC_NAME_2 asc,LKP.PC_ADDRESS_1 asc,LKP.PC_ADDRESS_2 asc,LKP.PC_CITYST asc,LKP.PC_ZIP asc,LKP.PC_AGENT asc,LKP.PC_MEMBER_NUMBER asc,LKP.PC_COMPANY asc,LKP.SC_DWNLD_PRIORITY asc,LKP.SC_FLT_ITEM asc,LKP.SC_FILE_TYPE asc,LKP.SC_REC_TRANS_CODE asc,LKP.SC_TRANS_DATE asc,LKP.SC_TRANS_TYPE asc,LKP.PC_INCEPT_DATE asc,LKP.LN_STATUS asc,LKP.LN_DUE_DATE asc,LKP.LN_AMOUNT_DUE asc,LKP.LN_NBR_PMNTS_PAID asc,LKP.LN_BALANCE asc,LKP.LN_PAYOFF_AMT asc,LKP.LN_NBR_PMNTS_LATE asc,LKP.LN_LATE_CHARGE_AMT asc,LKP.LN_ORIGINAL_TERM asc,LKP.LN_ORIGINL_AMT_FIN asc,LKP.LN_COLLATERAL_DESC asc,LKP.LN_CRDT_LIFE_IND asc,LKP.LN_A_H_IND asc,LKP.LN_PER_DIEM asc,LKP.LN_YTD_INTEREST asc,LKP.LN_PREV_YTD_INT asc,LKP.LN_SSN asc,LKP.LN_WORK_PHONE_NBR asc,LKP.LN_HOME_PHONE_NBR asc,LKP.LN_LAST_PAYMT_DATE asc,LKP.LN_INT_RATE asc,LKP.FEED_IND asc) RNK
FROM
exp_HOLD_DATA
LEFT JOIN (
SELECT LOANS.SC_SERVICE_CENTER as SC_SERVICE_CENTER, 
LOANS.SC_POLICY_NUM as SC_POLICY_NUM,
LOANS.CHG_EFF_DT as CHG_EFF_DT, 
LOANS.CHG_EXP_DT as CHG_EXP_DT, 
LOANS.PC_ALPHA_CODE as PC_ALPHA_CODE, 
LOANS.PC_NAME_1 as PC_NAME_1, 
LOANS.PC_NAME_2 as PC_NAME_2, 
LOANS.PC_ADDRESS_1 as PC_ADDRESS_1, 
LOANS.PC_ADDRESS_2 as PC_ADDRESS_2, 
LOANS.PC_CITYST as PC_CITYST, 
LOANS.PC_ZIP as PC_ZIP, 
LOANS.PC_AGENT as PC_AGENT, 
LOANS.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER, 
LOANS.PC_COMPANY as PC_COMPANY, 
LOANS.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY, 
LOANS.SC_FLT_ITEM as SC_FLT_ITEM, 
LOANS.SC_FILE_TYPE as SC_FILE_TYPE, 
LOANS.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE, 
LOANS.SC_TRANS_DATE as SC_TRANS_DATE, 
LOANS.SC_TRANS_TYPE as SC_TRANS_TYPE, 
LOANS.PC_INCEPT_DATE as PC_INCEPT_DATE, 
LOANS.LN_STATUS as LN_STATUS, 
LOANS.LN_DUE_DATE as LN_DUE_DATE, 
LOANS.LN_AMOUNT_DUE as LN_AMOUNT_DUE, 
LOANS.LN_NBR_PMNTS_PAID as LN_NBR_PMNTS_PAID, 
LOANS.LN_BALANCE as LN_BALANCE, 
LOANS.LN_PAYOFF_AMT as LN_PAYOFF_AMT, 
LOANS.LN_NBR_PMNTS_LATE as LN_NBR_PMNTS_LATE, 
LOANS.LN_LATE_CHARGE_AMT as LN_LATE_CHARGE_AMT, 
LOANS.LN_ORIGINAL_TERM as LN_ORIGINAL_TERM, 
LOANS.LN_ORIGINL_AMT_FIN as LN_ORIGINL_AMT_FIN, 
LOANS.LN_COLLATERAL_DESC as LN_COLLATERAL_DESC, 
LOANS.LN_CRDT_LIFE_IND as LN_CRDT_LIFE_IND, 
LOANS.LN_A_H_IND as LN_A_H_IND, 
LOANS.LN_PER_DIEM as LN_PER_DIEM, 
LOANS.LN_YTD_INTEREST as LN_YTD_INTEREST, 
LOANS.LN_PREV_YTD_INT as LN_PREV_YTD_INT, 
LOANS.LN_SSN as LN_SSN, 
LOANS.LN_WORK_PHONE_NBR as LN_WORK_PHONE_NBR, 
LOANS.LN_HOME_PHONE_NBR as LN_HOME_PHONE_NBR, 
LOANS.LN_LAST_PAYMT_DATE as LN_LAST_PAYMT_DATE, 
LOANS.LN_INT_RATE as LN_INT_RATE, 
LOANS.FEED_IND as FEED_IND, 
LOANS.ECTL_BATCH_ID as ECTL_BATCH_ID, 
LOANS.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS, 
LOANS.ECTL_MODIFY_TS as ECTL_MODIFY_TS, 
LOANS.ECTL_SRC_ID as ECTL_SRC_ID, 
LOANS.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID, 
LOANS.ECTL_PRGM_ID as ECTL_PRGM_ID, 
LOANS.ECTL_TX_CD as ECTL_TX_CD, 
LOANS.ECTL_START_DATE as ECTL_START_DATE, 
LOANS.ECTL_END_DATE as ECTL_END_DATE 
 FROM DB_T_core_MEMBXREF_PROD.LOANS LOANS WHERE ECTL_TX_CD = ''NEW''
) LKP ON LKP.SC_POLICY_NUM = exp_HOLD_DATA.SC_POLICY_NUM
QUALIFY RNK = 1
);


-- Component exp_DERIVE_FLAG, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_DERIVE_FLAG AS
(
SELECT
LKP_LOANS.SC_POLICY_NUM as SC_POLICY_NUM_lkp,
LKP_LOANS.CHG_EFF_DT as CHG_EFF_DT_lkp,
exp_HOLD_DATA.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_HOLD_DATA.SC_POLICY_NUM as SC_POLICY_NUM,
exp_HOLD_DATA.PC_ALPHA_CODE as PC_ALPHA_CODE,
exp_HOLD_DATA.PC_NAME_1 as PC_NAME_1,
exp_HOLD_DATA.PC_NAME_2 as PC_NAME_2,
exp_HOLD_DATA.PC_ADDRESS_1 as PC_ADDRESS_1,
exp_HOLD_DATA.PC_ADDRESS_2 as PC_ADDRESS_2,
exp_HOLD_DATA.PC_CITYST as PC_CITYST,
exp_HOLD_DATA.PC_ZIP as PC_ZIP,
exp_HOLD_DATA.PC_AGENT as PC_AGENT,
exp_HOLD_DATA.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
exp_HOLD_DATA.PC_COMPANY as PC_COMPANY,
exp_HOLD_DATA.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_HOLD_DATA.SC_FLT_ITEM as SC_FLT_ITEM,
exp_HOLD_DATA.SC_FILE_TYPE as SC_FILE_TYPE,
exp_HOLD_DATA.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_HOLD_DATA.SC_TRANS_DATE as SC_TRANS_DATE,
exp_HOLD_DATA.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_HOLD_DATA.PC_INCEPT_DATE as PC_INCEPT_DATE,
exp_HOLD_DATA.LN_STATUS as LN_STATUS,
exp_HOLD_DATA.LN_DUE_DATE as LN_DUE_DATE,
exp_HOLD_DATA.LN_AMOUNT_DUE as LN_AMOUNT_DUE,
exp_HOLD_DATA.LN_NBR_PMNTS_PAID as LN_NBR_PMNTS_PAID,
exp_HOLD_DATA.LN_BALANCE as LN_BALANCE,
exp_HOLD_DATA.LN_PAYOFF_AMT as LN_PAYOFF_AMT,
exp_HOLD_DATA.LN_NBR_PMNTS_LATE as LN_NBR_PMNTS_LATE,
exp_HOLD_DATA.LN_LATE_CHARGE_AMT as LN_LATE_CHARGE_AMT,
exp_HOLD_DATA.LN_ORIGINAL_TERM as LN_ORIGINAL_TERM,
exp_HOLD_DATA.LN_ORIGINL_AMT_FIN as LN_ORIGINL_AMT_FIN,
exp_HOLD_DATA.LN_COLLATERAL_DESC as LN_COLLATERAL_DESC,
exp_HOLD_DATA.LN_CRDT_LIFE_IND as LN_CRDT_LIFE_IND,
exp_HOLD_DATA.LN_A_H_IND as LN_A_H_IND,
exp_HOLD_DATA.LN_PER_DIEM as LN_PER_DIEM,
exp_HOLD_DATA.LN_YTD_INTEREST as LN_YTD_INTEREST,
exp_HOLD_DATA.LN_PREV_YTD_INT as LN_PREV_YTD_INT,
exp_HOLD_DATA.LN_SSN as LN_SSN,
exp_HOLD_DATA.LN_WORK_PHONE_NBR as LN_WORK_PHONE_NBR,
exp_HOLD_DATA.LN_HOME_PHONE_NBR as LN_HOME_PHONE_NBR,
exp_HOLD_DATA.LN_LAST_PAYMT_DATE as LN_LAST_PAYMT_DATE,
exp_HOLD_DATA.LN_INT_RATE as LN_INT_RATE,
exp_HOLD_DATA.LOAD_DT as LOAD_DT,
exp_HOLD_DATA.FEED_IND as FEED_IND,
CASE WHEN LKP_LOANS.SC_POLICY_NUM IS NULL THEN ''NEW'' ELSE CASE WHEN CASE WHEN LKP_LOANS.SC_SERVICE_CENTER IS NULL THEN 0 ELSE LKP_LOANS.SC_SERVICE_CENTER END <> CASE WHEN exp_HOLD_DATA.SC_SERVICE_CENTER IS NULL THEN 0 ELSE exp_HOLD_DATA.SC_SERVICE_CENTER END OR CASE WHEN LKP_LOANS.PC_ALPHA_CODE IS NULL THEN ''~'' ELSE LKP_LOANS.PC_ALPHA_CODE END <> CASE WHEN exp_HOLD_DATA.PC_ALPHA_CODE IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_ALPHA_CODE END OR CASE WHEN LKP_LOANS.PC_NAME_1 IS NULL THEN ''~'' ELSE LKP_LOANS.PC_NAME_1 END <> CASE WHEN exp_HOLD_DATA.PC_NAME_1 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_NAME_1 END OR CASE WHEN LKP_LOANS.PC_NAME_2 IS NULL THEN ''~'' ELSE LKP_LOANS.PC_NAME_2 END <> CASE WHEN exp_HOLD_DATA.PC_NAME_2 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_NAME_2 END OR CASE WHEN LKP_LOANS.PC_ADDRESS_1 IS NULL THEN ''~'' ELSE LKP_LOANS.PC_ADDRESS_1 END <> CASE WHEN exp_HOLD_DATA.PC_ADDRESS_1 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_ADDRESS_1 END OR CASE WHEN LKP_LOANS.PC_ADDRESS_2 IS NULL THEN ''~'' ELSE LKP_LOANS.PC_ADDRESS_2 END <> CASE WHEN exp_HOLD_DATA.PC_ADDRESS_2 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_ADDRESS_2 END OR CASE WHEN LKP_LOANS.PC_CITYST IS NULL THEN ''~'' ELSE LKP_LOANS.PC_CITYST END <> CASE WHEN exp_HOLD_DATA.PC_CITYST IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_CITYST END OR CASE WHEN LKP_LOANS.PC_ZIP IS NULL THEN ''~'' ELSE LKP_LOANS.PC_ZIP END <> CASE WHEN exp_HOLD_DATA.PC_ZIP IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_ZIP END OR CASE WHEN LKP_LOANS.PC_AGENT IS NULL THEN 0 ELSE LKP_LOANS.PC_AGENT END <> CASE WHEN exp_HOLD_DATA.PC_AGENT IS NULL THEN 0 ELSE exp_HOLD_DATA.PC_AGENT END OR CASE WHEN LKP_LOANS.PC_MEMBER_NUMBER IS NULL THEN ''~'' ELSE LKP_LOANS.PC_MEMBER_NUMBER END <> CASE WHEN exp_HOLD_DATA.PC_MEMBER_NUMBER IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_MEMBER_NUMBER END OR CASE WHEN LKP_LOANS.PC_COMPANY IS NULL THEN ''~'' ELSE LKP_LOANS.PC_COMPANY END <> CASE WHEN exp_HOLD_DATA.PC_COMPANY IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_COMPANY END OR CASE WHEN LKP_LOANS.SC_DWNLD_PRIORITY IS NULL THEN 0 ELSE LKP_LOANS.SC_DWNLD_PRIORITY END <> CASE WHEN exp_HOLD_DATA.SC_DWNLD_PRIORITY IS NULL THEN 0 ELSE exp_HOLD_DATA.SC_DWNLD_PRIORITY END OR CASE WHEN LKP_LOANS.SC_FLT_ITEM IS NULL THEN ''~'' ELSE LKP_LOANS.SC_FLT_ITEM END <> CASE WHEN exp_HOLD_DATA.SC_FLT_ITEM IS NULL THEN ''~'' ELSE exp_HOLD_DATA.SC_FLT_ITEM END OR CASE WHEN LKP_LOANS.SC_FILE_TYPE IS NULL THEN 0 ELSE LKP_LOANS.SC_FILE_TYPE END <> CASE WHEN exp_HOLD_DATA.SC_FILE_TYPE IS NULL THEN 0 ELSE exp_HOLD_DATA.SC_FILE_TYPE END OR CASE WHEN LKP_LOANS.SC_REC_TRANS_CODE IS NULL THEN 0 ELSE LKP_LOANS.SC_REC_TRANS_CODE END <> CASE WHEN exp_HOLD_DATA.SC_REC_TRANS_CODE IS NULL THEN 0 ELSE exp_HOLD_DATA.SC_REC_TRANS_CODE END OR CASE WHEN LKP_LOANS.SC_TRANS_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_LOANS.SC_TRANS_DATE END <> CASE WHEN exp_HOLD_DATA.SC_TRANS_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.SC_TRANS_DATE END OR CASE WHEN LKP_LOANS.SC_TRANS_TYPE IS NULL THEN 0 ELSE LKP_LOANS.SC_TRANS_TYPE END <> CASE WHEN exp_HOLD_DATA.SC_TRANS_TYPE IS NULL THEN 0 ELSE exp_HOLD_DATA.SC_TRANS_TYPE END OR CASE WHEN LKP_LOANS.PC_INCEPT_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_LOANS.PC_INCEPT_DATE END <> CASE WHEN exp_HOLD_DATA.PC_INCEPT_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.PC_INCEPT_DATE END OR CASE WHEN LKP_LOANS.LN_STATUS IS NULL THEN ''~'' ELSE LKP_LOANS.LN_STATUS END <> CASE WHEN exp_HOLD_DATA.LN_STATUS IS NULL THEN ''~'' ELSE exp_HOLD_DATA.LN_STATUS END OR CASE WHEN LKP_LOANS.LN_DUE_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_LOANS.LN_DUE_DATE END <> CASE WHEN exp_HOLD_DATA.LN_DUE_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.LN_DUE_DATE END OR CASE WHEN LKP_LOANS.LN_AMOUNT_DUE IS NULL THEN 0 ELSE LKP_LOANS.LN_AMOUNT_DUE END <> CASE WHEN exp_HOLD_DATA.LN_AMOUNT_DUE IS NULL THEN 0 ELSE exp_HOLD_DATA.LN_AMOUNT_DUE END OR CASE WHEN LKP_LOANS.LN_NBR_PMNTS_PAID IS NULL THEN 0 ELSE LKP_LOANS.LN_NBR_PMNTS_PAID END <> CASE WHEN exp_HOLD_DATA.LN_NBR_PMNTS_PAID IS NULL THEN 0 ELSE exp_HOLD_DATA.LN_NBR_PMNTS_PAID END OR CASE WHEN LKP_LOANS.LN_BALANCE IS NULL THEN 0 ELSE LKP_LOANS.LN_BALANCE END <> CASE WHEN exp_HOLD_DATA.LN_BALANCE IS NULL THEN 0 ELSE exp_HOLD_DATA.LN_BALANCE END OR CASE WHEN LKP_LOANS.LN_PAYOFF_AMT IS NULL THEN 0 ELSE LKP_LOANS.LN_PAYOFF_AMT END <> CASE WHEN exp_HOLD_DATA.LN_PAYOFF_AMT IS NULL THEN 0 ELSE exp_HOLD_DATA.LN_PAYOFF_AMT END OR CASE WHEN LKP_LOANS.LN_NBR_PMNTS_LATE IS NULL THEN 0 ELSE LKP_LOANS.LN_NBR_PMNTS_LATE END <> CASE WHEN exp_HOLD_DATA.LN_NBR_PMNTS_LATE IS NULL THEN 0 ELSE exp_HOLD_DATA.LN_NBR_PMNTS_LATE END OR CASE WHEN LKP_LOANS.LN_LATE_CHARGE_AMT IS NULL THEN 0 ELSE LKP_LOANS.LN_LATE_CHARGE_AMT END <> CASE WHEN exp_HOLD_DATA.LN_LATE_CHARGE_AMT IS NULL THEN 0 ELSE exp_HOLD_DATA.LN_LATE_CHARGE_AMT END OR CASE WHEN LKP_LOANS.LN_ORIGINAL_TERM IS NULL THEN 0 ELSE LKP_LOANS.LN_ORIGINAL_TERM END <> CASE WHEN exp_HOLD_DATA.LN_ORIGINAL_TERM IS NULL THEN 0 ELSE exp_HOLD_DATA.LN_ORIGINAL_TERM END OR CASE WHEN LKP_LOANS.LN_ORIGINL_AMT_FIN IS NULL THEN 0 ELSE LKP_LOANS.LN_ORIGINL_AMT_FIN END <> CASE WHEN exp_HOLD_DATA.LN_ORIGINL_AMT_FIN IS NULL THEN 0 ELSE exp_HOLD_DATA.LN_ORIGINL_AMT_FIN END OR CASE WHEN LKP_LOANS.LN_COLLATERAL_DESC IS NULL THEN ''~'' ELSE LKP_LOANS.LN_COLLATERAL_DESC END <> CASE WHEN exp_HOLD_DATA.LN_COLLATERAL_DESC IS NULL THEN ''~'' ELSE exp_HOLD_DATA.LN_COLLATERAL_DESC END OR CASE WHEN LKP_LOANS.LN_CRDT_LIFE_IND IS NULL THEN ''~'' ELSE LKP_LOANS.LN_CRDT_LIFE_IND END <> CASE WHEN exp_HOLD_DATA.LN_CRDT_LIFE_IND IS NULL THEN ''~'' ELSE exp_HOLD_DATA.LN_CRDT_LIFE_IND END OR CASE WHEN LKP_LOANS.LN_A_H_IND IS NULL THEN ''~'' ELSE LKP_LOANS.LN_A_H_IND END <> CASE WHEN exp_HOLD_DATA.LN_A_H_IND IS NULL THEN ''~'' ELSE exp_HOLD_DATA.LN_A_H_IND END OR CASE WHEN LKP_LOANS.LN_PER_DIEM IS NULL THEN 0 ELSE LKP_LOANS.LN_PER_DIEM END <> CASE WHEN exp_HOLD_DATA.LN_PER_DIEM IS NULL THEN 0 ELSE exp_HOLD_DATA.LN_PER_DIEM END OR CASE WHEN LKP_LOANS.LN_YTD_INTEREST IS NULL THEN 0 ELSE LKP_LOANS.LN_YTD_INTEREST END <> CASE WHEN exp_HOLD_DATA.LN_YTD_INTEREST IS NULL THEN 0 ELSE exp_HOLD_DATA.LN_YTD_INTEREST END OR CASE WHEN LKP_LOANS.LN_PREV_YTD_INT IS NULL THEN 0 ELSE LKP_LOANS.LN_PREV_YTD_INT END <> CASE WHEN exp_HOLD_DATA.LN_PREV_YTD_INT IS NULL THEN 0 ELSE exp_HOLD_DATA.LN_PREV_YTD_INT END OR CASE WHEN LKP_LOANS.LN_SSN IS NULL THEN ''~'' ELSE LKP_LOANS.LN_SSN END <> CASE WHEN exp_HOLD_DATA.LN_SSN IS NULL THEN ''~'' ELSE exp_HOLD_DATA.LN_SSN END OR CASE WHEN LKP_LOANS.LN_WORK_PHONE_NBR IS NULL THEN ''~'' ELSE LKP_LOANS.LN_WORK_PHONE_NBR END <> CASE WHEN exp_HOLD_DATA.LN_WORK_PHONE_NBR IS NULL THEN ''~'' ELSE exp_HOLD_DATA.LN_WORK_PHONE_NBR END OR CASE WHEN LKP_LOANS.LN_HOME_PHONE_NBR IS NULL THEN ''~'' ELSE LKP_LOANS.LN_HOME_PHONE_NBR END <> CASE WHEN exp_HOLD_DATA.LN_HOME_PHONE_NBR IS NULL THEN ''~'' ELSE exp_HOLD_DATA.LN_HOME_PHONE_NBR END OR CASE WHEN LKP_LOANS.LN_LAST_PAYMT_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_LOANS.LN_LAST_PAYMT_DATE END <> CASE WHEN exp_HOLD_DATA.LN_LAST_PAYMT_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.LN_LAST_PAYMT_DATE END OR CASE WHEN LKP_LOANS.LN_INT_RATE IS NULL THEN 0 ELSE LKP_LOANS.LN_INT_RATE END <> CASE WHEN exp_HOLD_DATA.LN_INT_RATE IS NULL THEN 0 ELSE exp_HOLD_DATA.LN_INT_RATE END THEN ''UPD'' ELSE ''REJ'' END END as out_FLG,
:PROJ_ID as out_PROJ_ID,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
LTRIM ( RTRIM ( :PMMappingName ) ) as out_PRGM_NM,
exp_HOLD_DATA.source_record_id
FROM
exp_HOLD_DATA
INNER JOIN LKP_LOANS ON exp_HOLD_DATA.source_record_id = LKP_LOANS.source_record_id
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;


-- Component exp_LOANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_LOANS AS
(
SELECT
exp_DERIVE_FLAG.SC_POLICY_NUM_lkp as SC_POLICY_NUM_lkp,
exp_DERIVE_FLAG.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp,
exp_DERIVE_FLAG.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_DERIVE_FLAG.SC_POLICY_NUM as SC_POLICY_NUM,
exp_DERIVE_FLAG.PC_ALPHA_CODE as PC_ALPHA_CODE,
exp_DERIVE_FLAG.PC_NAME_1 as PC_NAME_1,
exp_DERIVE_FLAG.PC_NAME_2 as PC_NAME_2,
exp_DERIVE_FLAG.PC_ADDRESS_1 as PC_ADDRESS_1,
exp_DERIVE_FLAG.PC_ADDRESS_2 as PC_ADDRESS_2,
exp_DERIVE_FLAG.PC_CITYST as PC_CITYST,
exp_DERIVE_FLAG.PC_ZIP as PC_ZIP,
exp_DERIVE_FLAG.PC_AGENT as PC_AGENT,
exp_DERIVE_FLAG.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
exp_DERIVE_FLAG.PC_COMPANY as PC_COMPANY,
exp_DERIVE_FLAG.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_DERIVE_FLAG.SC_FLT_ITEM as SC_FLT_ITEM,
exp_DERIVE_FLAG.SC_FILE_TYPE as SC_FILE_TYPE,
exp_DERIVE_FLAG.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_DERIVE_FLAG.SC_TRANS_DATE as SC_TRANS_DATE,
exp_DERIVE_FLAG.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_DERIVE_FLAG.PC_INCEPT_DATE as PC_INCEPT_DATE,
exp_DERIVE_FLAG.LN_STATUS as LN_STATUS,
exp_DERIVE_FLAG.LN_DUE_DATE as LN_DUE_DATE,
exp_DERIVE_FLAG.LN_AMOUNT_DUE as LN_AMOUNT_DUE,
exp_DERIVE_FLAG.LN_NBR_PMNTS_PAID as LN_NBR_PMNTS_PAID,
exp_DERIVE_FLAG.LN_BALANCE as LN_BALANCE,
exp_DERIVE_FLAG.LN_PAYOFF_AMT as LN_PAYOFF_AMT,
exp_DERIVE_FLAG.LN_NBR_PMNTS_LATE as LN_NBR_PMNTS_LATE,
exp_DERIVE_FLAG.LN_LATE_CHARGE_AMT as LN_LATE_CHARGE_AMT,
exp_DERIVE_FLAG.LN_ORIGINAL_TERM as LN_ORIGINAL_TERM,
exp_DERIVE_FLAG.LN_ORIGINL_AMT_FIN as LN_ORIGINL_AMT_FIN,
exp_DERIVE_FLAG.LN_COLLATERAL_DESC as LN_COLLATERAL_DESC,
exp_DERIVE_FLAG.LN_CRDT_LIFE_IND as LN_CRDT_LIFE_IND,
exp_DERIVE_FLAG.LN_A_H_IND as LN_A_H_IND,
exp_DERIVE_FLAG.LN_PER_DIEM as LN_PER_DIEM,
exp_DERIVE_FLAG.LN_YTD_INTEREST as LN_YTD_INTEREST,
exp_DERIVE_FLAG.LN_PREV_YTD_INT as LN_PREV_YTD_INT,
exp_DERIVE_FLAG.LN_SSN as LN_SSN,
exp_DERIVE_FLAG.LN_WORK_PHONE_NBR as LN_WORK_PHONE_NBR,
exp_DERIVE_FLAG.LN_HOME_PHONE_NBR as LN_HOME_PHONE_NBR,
exp_DERIVE_FLAG.LN_LAST_PAYMT_DATE as LN_LAST_PAYMT_DATE,
exp_DERIVE_FLAG.LN_INT_RATE as LN_INT_RATE,
exp_DERIVE_FLAG.LOAD_DT as LOAD_DT,
exp_DERIVE_FLAG.FEED_IND as FEED_IND,
exp_DERIVE_FLAG.out_FLG as FLG,
--''1'' as ECTL_PRGM_ID,
--''1'' as ECTL_SRC_ID,
--''1'' as ECTL_SRC_INST_ID,
--''1'' as ECTL_BATCH_ID,
--''1900-01-01'' as ORIG_INS_TS,
--''1900-01-01'' as ECTL_BATCH_START_DATE,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as ECTL_BATCH_START_DATE,
exp_DERIVE_FLAG.source_record_id
FROM
exp_DERIVE_FLAG
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_DERIVE_FLAG.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
);


-- Component rtr_INS_UPD_INSERT, Type ROUTER Output Group INSERT
create or replace temp table RTR_INS_UPD_insert as
SELECT
exp_LOANS.SC_POLICY_NUM_lkp as SC_POLICY_NUM_lkp,
exp_LOANS.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp,
exp_LOANS.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_LOANS.SC_POLICY_NUM as SC_POLICY_NUM,
exp_LOANS.PC_ALPHA_CODE as PC_ALPHA_CODE,
exp_LOANS.PC_NAME_1 as PC_NAME_1,
exp_LOANS.PC_NAME_2 as PC_NAME_2,
exp_LOANS.PC_ADDRESS_1 as PC_ADDRESS_1,
exp_LOANS.PC_ADDRESS_2 as PC_ADDRESS_2,
exp_LOANS.PC_CITYST as PC_CITYST,
exp_LOANS.PC_ZIP as PC_ZIP,
exp_LOANS.PC_AGENT as PC_AGENT,
exp_LOANS.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
exp_LOANS.PC_COMPANY as PC_COMPANY,
exp_LOANS.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_LOANS.SC_FLT_ITEM as SC_FLT_ITEM,
exp_LOANS.SC_FILE_TYPE as SC_FILE_TYPE,
exp_LOANS.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_LOANS.SC_TRANS_DATE as SC_TRANS_DATE,
exp_LOANS.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_LOANS.PC_INCEPT_DATE as PC_INCEPT_DATE,
exp_LOANS.LN_STATUS as LN_STATUS,
exp_LOANS.LN_DUE_DATE as LN_DUE_DATE,
exp_LOANS.LN_AMOUNT_DUE as LN_AMOUNT_DUE,
exp_LOANS.LN_NBR_PMNTS_PAID as LN_NBR_PMNTS_PAID,
exp_LOANS.LN_BALANCE as LN_BALANCE,
exp_LOANS.LN_PAYOFF_AMT as LN_PAYOFF_AMT,
exp_LOANS.LN_NBR_PMNTS_LATE as LN_NBR_PMNTS_LATE,
exp_LOANS.LN_LATE_CHARGE_AMT as LN_LATE_CHARGE_AMT,
exp_LOANS.LN_ORIGINAL_TERM as LN_ORIGINAL_TERM,
exp_LOANS.LN_ORIGINL_AMT_FIN as LN_ORIGINL_AMT_FIN,
exp_LOANS.LN_COLLATERAL_DESC as LN_COLLATERAL_DESC,
exp_LOANS.LN_CRDT_LIFE_IND as LN_CRDT_LIFE_IND,
exp_LOANS.LN_A_H_IND as LN_A_H_IND,
exp_LOANS.LN_PER_DIEM as LN_PER_DIEM,
exp_LOANS.LN_YTD_INTEREST as LN_YTD_INTEREST,
exp_LOANS.LN_PREV_YTD_INT as LN_PREV_YTD_INT,
exp_LOANS.LN_SSN as LN_SSN,
exp_LOANS.LN_WORK_PHONE_NBR as LN_WORK_PHONE_NBR,
exp_LOANS.LN_HOME_PHONE_NBR as LN_HOME_PHONE_NBR,
exp_LOANS.LN_LAST_PAYMT_DATE as LN_LAST_PAYMT_DATE,
exp_LOANS.LN_INT_RATE as LN_INT_RATE,
exp_LOANS.LOAD_DT as LOAD_DT,
exp_LOANS.FEED_IND as FEED_IND,
exp_LOANS.FLG as FLG,
exp_LOANS.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_LOANS.ECTL_SRC_ID as ECTL_SRC_ID,
exp_LOANS.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_LOANS.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_LOANS.ORIG_INS_TS as ORIG_INS_TS,
exp_LOANS.ECTL_BATCH_START_DATE as ECTL_BATCH_START_DATE,
exp_LOANS.source_record_id
FROM
exp_LOANS
WHERE ( exp_LOANS.FLG = ''NEW'' ) OR ( exp_LOANS.FLG = ''UPD'' );


-- Component rtr_INS_UPD_UPDATE, Type ROUTER Output Group UPDATE
create or replace temp table RTR_INS_UPD_UPDATE as
SELECT
exp_LOANS.SC_POLICY_NUM_lkp as SC_POLICY_NUM_lkp,
exp_LOANS.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp,
exp_LOANS.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_LOANS.SC_POLICY_NUM as SC_POLICY_NUM,
exp_LOANS.PC_ALPHA_CODE as PC_ALPHA_CODE,
exp_LOANS.PC_NAME_1 as PC_NAME_1,
exp_LOANS.PC_NAME_2 as PC_NAME_2,
exp_LOANS.PC_ADDRESS_1 as PC_ADDRESS_1,
exp_LOANS.PC_ADDRESS_2 as PC_ADDRESS_2,
exp_LOANS.PC_CITYST as PC_CITYST,
exp_LOANS.PC_ZIP as PC_ZIP,
exp_LOANS.PC_AGENT as PC_AGENT,
exp_LOANS.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
exp_LOANS.PC_COMPANY as PC_COMPANY,
exp_LOANS.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_LOANS.SC_FLT_ITEM as SC_FLT_ITEM,
exp_LOANS.SC_FILE_TYPE as SC_FILE_TYPE,
exp_LOANS.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_LOANS.SC_TRANS_DATE as SC_TRANS_DATE,
exp_LOANS.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_LOANS.PC_INCEPT_DATE as PC_INCEPT_DATE,
exp_LOANS.LN_STATUS as LN_STATUS,
exp_LOANS.LN_DUE_DATE as LN_DUE_DATE,
exp_LOANS.LN_AMOUNT_DUE as LN_AMOUNT_DUE,
exp_LOANS.LN_NBR_PMNTS_PAID as LN_NBR_PMNTS_PAID,
exp_LOANS.LN_BALANCE as LN_BALANCE,
exp_LOANS.LN_PAYOFF_AMT as LN_PAYOFF_AMT,
exp_LOANS.LN_NBR_PMNTS_LATE as LN_NBR_PMNTS_LATE,
exp_LOANS.LN_LATE_CHARGE_AMT as LN_LATE_CHARGE_AMT,
exp_LOANS.LN_ORIGINAL_TERM as LN_ORIGINAL_TERM,
exp_LOANS.LN_ORIGINL_AMT_FIN as LN_ORIGINL_AMT_FIN,
exp_LOANS.LN_COLLATERAL_DESC as LN_COLLATERAL_DESC,
exp_LOANS.LN_CRDT_LIFE_IND as LN_CRDT_LIFE_IND,
exp_LOANS.LN_A_H_IND as LN_A_H_IND,
exp_LOANS.LN_PER_DIEM as LN_PER_DIEM,
exp_LOANS.LN_YTD_INTEREST as LN_YTD_INTEREST,
exp_LOANS.LN_PREV_YTD_INT as LN_PREV_YTD_INT,
exp_LOANS.LN_SSN as LN_SSN,
exp_LOANS.LN_WORK_PHONE_NBR as LN_WORK_PHONE_NBR,
exp_LOANS.LN_HOME_PHONE_NBR as LN_HOME_PHONE_NBR,
exp_LOANS.LN_LAST_PAYMT_DATE as LN_LAST_PAYMT_DATE,
exp_LOANS.LN_INT_RATE as LN_INT_RATE,
exp_LOANS.LOAD_DT as LOAD_DT,
exp_LOANS.FEED_IND as FEED_IND,
exp_LOANS.FLG as FLG,
exp_LOANS.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_LOANS.ECTL_SRC_ID as ECTL_SRC_ID,
exp_LOANS.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_LOANS.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_LOANS.ORIG_INS_TS as ORIG_INS_TS,
exp_LOANS.ECTL_BATCH_START_DATE as ECTL_BATCH_START_DATE,
exp_LOANS.source_record_id
FROM
exp_LOANS
WHERE exp_LOANS.FLG = ''UPD'';


-- Component exp_GET_EXP_DATE, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_GET_EXP_DATE AS
(
SELECT
rtr_INS_UPD_UPDATE.SC_POLICY_NUM_lkp as SC_POLICY_NUM_lkp3,
rtr_INS_UPD_UPDATE.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp3,
rtr_INS_UPD_UPDATE.LOAD_DT as LOAD_DT3,
rtr_INS_UPD_UPDATE.FLG as FLG3,
rtr_INS_UPD_UPDATE.ECTL_BATCH_ID as ECTL_BATCH_ID3,
rtr_INS_UPD_UPDATE.ORIG_INS_TS as ORIG_INS_TS3,
TO_CHAR ( ( DATE_PART(''YYYY'', TO_TIMESTAMP(rtr_INS_UPD_UPDATE.LOAD_DT)) * 10000 ) + ( DATE_PART(''MM'', TO_TIMESTAMP(rtr_INS_UPD_UPDATE.LOAD_DT)) * 100 ) + 1 ) as var_FIRST_DAY_EFF_DT,
 TO_DATE ( var_FIRST_DAY_EFF_DT  )  - 1  as var_CHG_EXP_DT_NEW,
CASE WHEN rtr_INS_UPD_UPDATE.CHG_EFF_DT_lkp >= TO_DATE ( var_FIRST_DAY_EFF_DT , ''YYYYMMDD'' ) THEN rtr_INS_UPD_UPDATE.CHG_EFF_DT_lkp ELSE var_CHG_EXP_DT_NEW END as out_CHG_EXP_DT_NEW,
CURRENT_TIMESTAMP as out_ECTL_END_DT,
rtr_INS_UPD_UPDATE.source_record_id
FROM
rtr_INS_UPD_UPDATE
);


-- Component upd_LOANS, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_LOANS AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
exp_GET_EXP_DATE.SC_POLICY_NUM_lkp3 as SC_POLICY_NUM_lkp3,
exp_GET_EXP_DATE.CHG_EFF_DT_lkp3 as CHG_EFF_DT_lkp3,
exp_GET_EXP_DATE.LOAD_DT3 as LOAD_DT3,
exp_GET_EXP_DATE.FLG3 as FLG3,
exp_GET_EXP_DATE.ECTL_BATCH_ID3 as ECTL_BATCH_ID3,
exp_GET_EXP_DATE.ORIG_INS_TS3 as ORIG_INS_TS3,
exp_GET_EXP_DATE.out_CHG_EXP_DT_NEW as out_CHG_EXP_DT_NEW,
exp_GET_EXP_DATE.out_ECTL_END_DT as out_ECTL_END_DT,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_GET_EXP_DATE
);


-- Component LOANS_UPD, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_core_MEMBXREF_PROD.LOANS
USING upd_LOANS
ON (SC_POLICY_NUM = upd_LOANS.SC_POLICY_NUM_lkp3 AND CHG_EFF_DT = upd_LOANS.CHG_EFF_DT_lkp3)
WHEN MATCHED THEN UPDATE SET
ECTL_BATCH_ID = upd_LOANS.ECTL_BATCH_ID3, 
--ECTL_MODIFY_TS = upd_LOANS.ECTL_MODIFY_TS,
--ECTL_TX_CD = upd_LOANS.ECTL_TX_CD,
ECTL_END_DATE = upd_LOANS.out_ECTL_END_DT, CHG_EXP_DT = upd_LOANS.out_CHG_EXP_DT_NEW;


-- Component exp_GET_EFF_DATE, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_GET_EFF_DATE AS
(
SELECT
rtr_INS_UPD_INSERT.SC_SERVICE_CENTER as SC_SERVICE_CENTER1,
rtr_INS_UPD_INSERT.SC_POLICY_NUM as SC_POLICY_NUM1,
rtr_INS_UPD_INSERT.PC_ALPHA_CODE as PC_ALPHA_CODE1,
rtr_INS_UPD_INSERT.PC_NAME_1 as PC_NAME_11,
rtr_INS_UPD_INSERT.PC_NAME_2 as PC_NAME_21,
rtr_INS_UPD_INSERT.PC_ADDRESS_1 as PC_ADDRESS_11,
rtr_INS_UPD_INSERT.PC_ADDRESS_2 as PC_ADDRESS_21,
rtr_INS_UPD_INSERT.PC_CITYST as PC_CITYST1,
rtr_INS_UPD_INSERT.PC_ZIP as PC_ZIP1,
rtr_INS_UPD_INSERT.PC_AGENT as PC_AGENT1,
rtr_INS_UPD_INSERT.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER1,
rtr_INS_UPD_INSERT.PC_COMPANY as PC_COMPANY1,
rtr_INS_UPD_INSERT.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY1,
rtr_INS_UPD_INSERT.SC_FLT_ITEM as SC_FLT_ITEM1,
rtr_INS_UPD_INSERT.SC_FILE_TYPE as SC_FILE_TYPE1,
rtr_INS_UPD_INSERT.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE1,
rtr_INS_UPD_INSERT.SC_TRANS_DATE as SC_TRANS_DATE1,
rtr_INS_UPD_INSERT.SC_TRANS_TYPE as SC_TRANS_TYPE1,
rtr_INS_UPD_INSERT.PC_INCEPT_DATE as PC_INCEPT_DATE1,
rtr_INS_UPD_INSERT.LN_STATUS as LN_STATUS1,
rtr_INS_UPD_INSERT.LN_DUE_DATE as LN_DUE_DATE1,
rtr_INS_UPD_INSERT.LN_AMOUNT_DUE as LN_AMOUNT_DUE1,
rtr_INS_UPD_INSERT.LN_NBR_PMNTS_PAID as LN_NBR_PMNTS_PAID1,
rtr_INS_UPD_INSERT.LN_BALANCE as LN_BALANCE1,
rtr_INS_UPD_INSERT.LN_PAYOFF_AMT as LN_PAYOFF_AMT1,
rtr_INS_UPD_INSERT.LN_NBR_PMNTS_LATE as LN_NBR_PMNTS_LATE1,
rtr_INS_UPD_INSERT.LN_LATE_CHARGE_AMT as LN_LATE_CHARGE_AMT1,
rtr_INS_UPD_INSERT.LN_ORIGINAL_TERM as LN_ORIGINAL_TERM1,
rtr_INS_UPD_INSERT.LN_ORIGINL_AMT_FIN as LN_ORIGINL_AMT_FIN1,
rtr_INS_UPD_INSERT.LN_COLLATERAL_DESC as LN_COLLATERAL_DESC1,
rtr_INS_UPD_INSERT.LN_CRDT_LIFE_IND as LN_CRDT_LIFE_IND1,
rtr_INS_UPD_INSERT.LN_A_H_IND as LN_A_H_IND1,
rtr_INS_UPD_INSERT.LN_PER_DIEM as LN_PER_DIEM1,
rtr_INS_UPD_INSERT.LN_YTD_INTEREST as LN_YTD_INTEREST1,
rtr_INS_UPD_INSERT.LN_PREV_YTD_INT as LN_PREV_YTD_INT1,
rtr_INS_UPD_INSERT.LN_SSN as LN_SSN1,
rtr_INS_UPD_INSERT.LN_WORK_PHONE_NBR as LN_WORK_PHONE_NBR1,
rtr_INS_UPD_INSERT.LN_HOME_PHONE_NBR as LN_HOME_PHONE_NBR1,
rtr_INS_UPD_INSERT.LN_LAST_PAYMT_DATE as LN_LAST_PAYMT_DATE1,
rtr_INS_UPD_INSERT.LN_INT_RATE as LN_INT_RATE1,
rtr_INS_UPD_INSERT.FEED_IND as FEED_IND1,
''NEW'' as out_ECTL_TX_CD,
TO_CHAR ( ( DATE_PART(''YYYY'', TO_TIMESTAMP(rtr_INS_UPD_INSERT.LOAD_DT)) * 10000 ) + ( DATE_PART(''MM'', TO_TIMESTAMP(rtr_INS_UPD_INSERT.LOAD_DT)) * 100 ) + 1 ) as var_FIRST_DAY_EFF_DT,
TO_DATE ( var_FIRST_DAY_EFF_DT , ''YYYYMMDD'' ) as var_CHG_EFF_DT,
CASE WHEN rtr_INS_UPD_INSERT.CHG_EFF_DT_lkp >= var_CHG_EFF_DT THEN  rtr_INS_UPD_INSERT.CHG_EFF_DT_lkp + 1  ELSE var_CHG_EFF_DT END as out_CHG_EFF_DT,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as out_CHG_EXP_DT_NEW,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as out_ECTL_END_DT,
rtr_INS_UPD_INSERT.ECTL_PRGM_ID as ECTL_PRGM_ID1,
rtr_INS_UPD_INSERT.ECTL_SRC_ID as ECTL_SRC_ID1,
rtr_INS_UPD_INSERT.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID1,
rtr_INS_UPD_INSERT.ECTL_BATCH_ID as ECTL_BATCH_ID1,
rtr_INS_UPD_INSERT.ORIG_INS_TS as ORIG_INS_TS1,
rtr_INS_UPD_INSERT.ECTL_BATCH_START_DATE as ECTL_BATCH_START_DATE1,
rtr_INS_UPD_INSERT.source_record_id
FROM
rtr_INS_UPD_INSERT
);


-- Component LOANS_INS, Type TARGET 
INSERT INTO DB_T_CORE_MEMBXREF_PROD.LOANS
(
SC_SERVICE_CENTER,
SC_POLICY_NUM,
CHG_EFF_DT,
CHG_EXP_DT,
PC_ALPHA_CODE,
PC_NAME_1,
PC_NAME_2,
PC_ADDRESS_1,
PC_ADDRESS_2,
PC_CITYST,
PC_ZIP,
PC_AGENT,
PC_MEMBER_NUMBER,
PC_COMPANY,
SC_DWNLD_PRIORITY,
SC_FLT_ITEM,
SC_FILE_TYPE,
SC_REC_TRANS_CODE,
SC_TRANS_DATE,
SC_TRANS_TYPE,
PC_INCEPT_DATE,
LN_STATUS,
LN_DUE_DATE,
LN_AMOUNT_DUE,
LN_NBR_PMNTS_PAID,
LN_BALANCE,
LN_PAYOFF_AMT,
LN_NBR_PMNTS_LATE,
LN_LATE_CHARGE_AMT,
LN_ORIGINAL_TERM,
LN_ORIGINL_AMT_FIN,
LN_COLLATERAL_DESC,
LN_CRDT_LIFE_IND,
LN_A_H_IND,
LN_PER_DIEM,
LN_YTD_INTEREST,
LN_PREV_YTD_INT,
LN_SSN,
LN_WORK_PHONE_NBR,
LN_HOME_PHONE_NBR,
LN_LAST_PAYMT_DATE,
LN_INT_RATE,
FEED_IND,
ECTL_BATCH_ID,
ECTL_ORIG_INS_TS,
ECTL_MODIFY_TS,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_PRGM_ID,
ECTL_TX_CD,
ECTL_START_DATE,
ECTL_END_DATE
)
SELECT
exp_GET_EFF_DATE.SC_SERVICE_CENTER1 as SC_SERVICE_CENTER,
exp_GET_EFF_DATE.SC_POLICY_NUM1 as SC_POLICY_NUM,
exp_GET_EFF_DATE.out_CHG_EFF_DT as CHG_EFF_DT,
exp_GET_EFF_DATE.out_CHG_EXP_DT_NEW as CHG_EXP_DT,
exp_GET_EFF_DATE.PC_ALPHA_CODE1 as PC_ALPHA_CODE,
exp_GET_EFF_DATE.PC_NAME_11 as PC_NAME_1,
exp_GET_EFF_DATE.PC_NAME_21 as PC_NAME_2,
exp_GET_EFF_DATE.PC_ADDRESS_11 as PC_ADDRESS_1,
exp_GET_EFF_DATE.PC_ADDRESS_21 as PC_ADDRESS_2,
exp_GET_EFF_DATE.PC_CITYST1 as PC_CITYST,
exp_GET_EFF_DATE.PC_ZIP1 as PC_ZIP,
exp_GET_EFF_DATE.PC_AGENT1 as PC_AGENT,
exp_GET_EFF_DATE.PC_MEMBER_NUMBER1 as PC_MEMBER_NUMBER,
exp_GET_EFF_DATE.PC_COMPANY1 as PC_COMPANY,
exp_GET_EFF_DATE.SC_DWNLD_PRIORITY1 as SC_DWNLD_PRIORITY,
exp_GET_EFF_DATE.SC_FLT_ITEM1 as SC_FLT_ITEM,
exp_GET_EFF_DATE.SC_FILE_TYPE1 as SC_FILE_TYPE,
exp_GET_EFF_DATE.SC_REC_TRANS_CODE1 as SC_REC_TRANS_CODE,
exp_GET_EFF_DATE.SC_TRANS_DATE1 as SC_TRANS_DATE,
exp_GET_EFF_DATE.SC_TRANS_TYPE1 as SC_TRANS_TYPE,
exp_GET_EFF_DATE.PC_INCEPT_DATE1 as PC_INCEPT_DATE,
exp_GET_EFF_DATE.LN_STATUS1 as LN_STATUS,
exp_GET_EFF_DATE.LN_DUE_DATE1 as LN_DUE_DATE,
exp_GET_EFF_DATE.LN_AMOUNT_DUE1 as LN_AMOUNT_DUE,
exp_GET_EFF_DATE.LN_NBR_PMNTS_PAID1 as LN_NBR_PMNTS_PAID,
exp_GET_EFF_DATE.LN_BALANCE1 as LN_BALANCE,
exp_GET_EFF_DATE.LN_PAYOFF_AMT1 as LN_PAYOFF_AMT,
exp_GET_EFF_DATE.LN_NBR_PMNTS_LATE1 as LN_NBR_PMNTS_LATE,
exp_GET_EFF_DATE.LN_LATE_CHARGE_AMT1 as LN_LATE_CHARGE_AMT,
exp_GET_EFF_DATE.LN_ORIGINAL_TERM1 as LN_ORIGINAL_TERM,
exp_GET_EFF_DATE.LN_ORIGINL_AMT_FIN1 as LN_ORIGINL_AMT_FIN,
exp_GET_EFF_DATE.LN_COLLATERAL_DESC1 as LN_COLLATERAL_DESC,
exp_GET_EFF_DATE.LN_CRDT_LIFE_IND1 as LN_CRDT_LIFE_IND,
exp_GET_EFF_DATE.LN_A_H_IND1 as LN_A_H_IND,
exp_GET_EFF_DATE.LN_PER_DIEM1 as LN_PER_DIEM,
exp_GET_EFF_DATE.LN_YTD_INTEREST1 as LN_YTD_INTEREST,
exp_GET_EFF_DATE.LN_PREV_YTD_INT1 as LN_PREV_YTD_INT,
exp_GET_EFF_DATE.LN_SSN1 as LN_SSN,
exp_GET_EFF_DATE.LN_WORK_PHONE_NBR1 as LN_WORK_PHONE_NBR,
exp_GET_EFF_DATE.LN_HOME_PHONE_NBR1 as LN_HOME_PHONE_NBR,
exp_GET_EFF_DATE.LN_LAST_PAYMT_DATE1 as LN_LAST_PAYMT_DATE,
exp_GET_EFF_DATE.LN_INT_RATE1 as LN_INT_RATE,
exp_GET_EFF_DATE.FEED_IND1 as FEED_IND,
exp_GET_EFF_DATE.ECTL_BATCH_ID1 as ECTL_BATCH_ID,
exp_GET_EFF_DATE.ORIG_INS_TS1 as ECTL_ORIG_INS_TS,
exp_GET_EFF_DATE.ORIG_INS_TS1 as ECTL_MODIFY_TS,
exp_GET_EFF_DATE.ECTL_SRC_ID1 as ECTL_SRC_ID,
exp_GET_EFF_DATE.ECTL_SRC_INST_ID1 as ECTL_SRC_INST_ID,
exp_GET_EFF_DATE.ECTL_PRGM_ID1 as ECTL_PRGM_ID,
exp_GET_EFF_DATE.out_ECTL_TX_CD as ECTL_TX_CD,
exp_GET_EFF_DATE.ECTL_BATCH_START_DATE1 as ECTL_START_DATE,
exp_GET_EFF_DATE.out_ECTL_END_DT as ECTL_END_DATE
FROM
exp_GET_EFF_DATE;


-- PIPELINE END FOR 2

END; ';