-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_AGENT_HIER("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 

DECLARE PMMAPPINGNAME varchar;
ACT_PROJ_ID varchar;
BATCH_ACTIVE_IND varchar;
PMSTG_CCM_CONTRACTTableName varchar;
BEGIN 

PMMAPPINGNAME:=''m_AGENT_HIER''; 
BATCH_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
ACT_PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
PMSTG_CCM_CONTRACTTableName:='' ''; 

-- Component sq_STG_CCM_CONTRACT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_CCM_CONTRACT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CCM_CONTRACT_ID,
$2 as CTT_CONTRACT_NBR,
$3 as CCM_AGENCY_ID,
$4 as CTT_CTT_CLT_ID,
$5 as CTT_CTT_TYPE_CD,
$6 as H_CODE,
$7 as STATE,
$8 as AGT_NO,
$9 as ORIG_CNTY,
$10 as SERV_CTR,
$11 as DIST,
$12 as REGION,
$13 as LAST_FIRST_NM,
$14 as PAY_AGT,
$15 as PAYROLL_NO,
$16 as INACTIVE_CD,
$17 as EMP_MO,
$18 as EMP_YR,
$19 as VAL_MO,
$20 as VAL_YR,
$21 as source_record_id
FROM (
SELECT CCM_CONTRACT_ID,
 CTT_CONTRACT_NBR,
 CCM_AGENCY_ID,
 CTT_CTT_CLT_ID,
 CTT_CTT_TYPE_CD,
 H_CODE,
 STATE,
 AGT_NO,
 ORIG_CNTY,
 SERV_CTR,
 DIST,
 REGION,
 LAST_FIRST_NM,
 PAY_AGT,
 PAYROLL_NO,
 INACTIVE_CD,
 EMP_MO,
 EMP_YR,
 VAL_MO,
 VAL_YR, row_number() over (order by 1) AS source_record_id FROM (
SELECT 
COALESCE(STG_CCM_CONTRACT.CCM_CONTRACT_ID,''0'') CCM_CONTRACT_ID, 
COALESCE(STG_CCM_CONTRACT.CTT_CONTRACT_NBR,''0'') CTT_CONTRACT_NBR, 
COALESCE(STG_CCM_CONTRACT.CCM_AGENCY_ID,''0'') CCM_AGENCY_ID,  
COALESCE(TRIM(STG_CCM_CONTRACT.CTT_CTT_CLT_ID),STG_AGENT_NAME.AGT_NO) CTT_CTT_CLT_ID, 
COALESCE(STG_CCM_CONTRACT.CTT_CTT_TYPE_CD,''0'') CTT_CTT_TYPE_CD,
STG_AGENT_NAME.H_CODE, 
STG_AGENT_NAME.STATE, 
STG_AGENT_NAME.AGT_NO, 
STG_AGENT_NAME.ORIG_CNTY,
STG_AGENT_NAME.SERV_CTR, 
STG_AGENT_NAME.DIST, 
STG_AGENT_NAME.REGION, 
STG_AGENT_NAME.LAST_FIRST_NM, 
STG_AGENT_NAME.PAY_AGT,
STG_AGENT_NAME.PAYROLL_NO,
STG_AGENT_NAME.INACTIVE_CD, 
(CASE WHEN STG_AGENT_NAME.EMP_MO< 10 THEN ''0''||CAST(STG_AGENT_NAME.EMP_MO AS CHAR) WHEN 
STG_AGENT_NAME.EMP_MO BETWEEN 10 AND 12 THEN CAST(EMP_MO AS CHAR(02)) ELSE ''00'' END)EMP_MO, 

(CASE	 
	WHEN	 EMP_YR BETWEEN 0 
	AND	 9 THEN ''0''||CAST(EMP_YR AS CHAR) 
	ELSE	 CAST(EMP_YR AS CHAR(02)) 
END) EMP_YR, 
(CASE WHEN STG_AGENT_NAME.VAL_MO< 10 THEN ''0''||CAST(STG_AGENT_NAME.VAL_MO AS CHAR) WHEN 
STG_AGENT_NAME.VAL_MO BETWEEN 10 AND 12 THEN CAST(VAL_MO AS CHAR(02)) ELSE ''00'' END) VAL_MO, 
(CASE	 
	WHEN	 VAL_YR BETWEEN 0 
	AND	 9 THEN ''0''||CAST(VAL_YR AS CHAR) 
	ELSE	 CAST(VAL_YR AS CHAR(02)) 
END) VAL_YR
FROM	 
DB_T_STAG_PROD.STG_AGENT_NAME  LEFT OUTER JOIN  DB_T_STAG_PROD.STG_CCM_CONTRACT
	ON	  TRIM(STG_AGENT_NAME.AGT_NO)  = TRIM(--LEADING ''0'' FROM 
STG_CCM_CONTRACT.CTT_CONTRACT_NBR)
WHERE STG_AGENT_NAME.AGT_NO <> ''583''
) SRC
)
);


-- Component exp_ERROR_VALIDATION, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ERROR_VALIDATION AS
(
SELECT
sq_STG_CCM_CONTRACT.CCM_CONTRACT_ID as CCM_CONTRACT_ID,
sq_STG_CCM_CONTRACT.CTT_CONTRACT_NBR as CTT_CONTRACT_NBR,
CASE WHEN sq_STG_CCM_CONTRACT.CTT_CONTRACT_NBR IS NULL THEN ''Null Value'' ELSE NULL END as out_CONT_NBR_ERROR,
''CCM_CONTRACT_NBR'' as out_CONT_NBR_ERROR_NM,
sq_STG_CCM_CONTRACT.CTT_CONTRACT_NBR as out_CCM_CONT_ERROR_VAL,
sq_STG_CCM_CONTRACT.CCM_AGENCY_ID as CCM_AGENCY_ID,
CASE WHEN sq_STG_CCM_CONTRACT.CCM_AGENCY_ID IS NULL THEN ''Null Value'' ELSE NULL END as out_CCM_AGENCY_ERROR,
''CCM_AGCY_ID'' as out_CCM_AGNY_ERR_NM,
sq_STG_CCM_CONTRACT.CCM_AGENCY_ID as out_CCM_AGNY_ERR_VAL,
sq_STG_CCM_CONTRACT.CTT_CTT_CLT_ID as CTT_CTT_CLT_ID,
CASE WHEN sq_STG_CCM_CONTRACT.CTT_CTT_CLT_ID IS NULL THEN ''Null Value'' ELSE NULL END as out_CTT_CLT_ID_ERROR,
''NULL'' as out_CTT_CLT_ID_ERROR_NM,
sq_STG_CCM_CONTRACT.CTT_CTT_CLT_ID as out_CTT_CLT_ID_ERROR_VAL,
sq_STG_CCM_CONTRACT.CTT_CTT_TYPE_CD as CTT_CTT_TYPE_CD,
sq_STG_CCM_CONTRACT.H_CODE as H_CODE,
sq_STG_CCM_CONTRACT.STATE as STATE,
sq_STG_CCM_CONTRACT.AGT_NO as AGT_NO,
sq_STG_CCM_CONTRACT.ORIG_CNTY as ORIG_CNTY,
sq_STG_CCM_CONTRACT.SERV_CTR as SERV_CTR,
sq_STG_CCM_CONTRACT.DIST as DIST,
sq_STG_CCM_CONTRACT.REGION as REGION,
sq_STG_CCM_CONTRACT.LAST_FIRST_NM as LAST_FIRST_NM,
sq_STG_CCM_CONTRACT.PAY_AGT as PAY_AGT,
sq_STG_CCM_CONTRACT.EMP_MO as EMP_MO,
sq_STG_CCM_CONTRACT.EMP_YR as EMP_YR,
sq_STG_CCM_CONTRACT.INACTIVE_CD as INACTIVE_CD,
sq_STG_CCM_CONTRACT.VAL_MO as VAL_MO,
sq_STG_CCM_CONTRACT.VAL_YR as VAL_YR,
CURRENT_TIMESTAMP as out_AGENT_EFF_DT,
CURRENT_TIMESTAMP as out_ECTL_TS,
CASE WHEN ( sq_STG_CCM_CONTRACT.EMP_MO = ''00'' and sq_STG_CCM_CONTRACT.EMP_YR <> ''00'' ) THEN ''Not valid'' ELSE CASE WHEN sq_STG_CCM_CONTRACT.EMP_MO IS NULL THEN ''Null Value'' ELSE NULL END END as out_EMP_MO_ERROR,
''NULL'' as out_EMP_NO_ERR_NM,
sq_STG_CCM_CONTRACT.EMP_MO as out_EMP_MO_ERR_VAL,
to_char ( sq_STG_CCM_CONTRACT.CCM_CONTRACT_ID ) || ''|'' || to_char ( sq_STG_CCM_CONTRACT.CTT_CONTRACT_NBR ) || ''|'' || to_char ( sq_STG_CCM_CONTRACT.CCM_AGENCY_ID ) || to_char ( sq_STG_CCM_CONTRACT.CTT_CTT_CLT_ID ) || ''|'' || to_char ( sq_STG_CCM_CONTRACT.CTT_CTT_TYPE_CD ) || ''|'' || to_char ( sq_STG_CCM_CONTRACT.EMP_MO ) || ''|'' || to_char ( sq_STG_CCM_CONTRACT.EMP_YR ) || ''|'' || to_char ( sq_STG_CCM_CONTRACT.VAL_MO ) || ''|'' || to_char ( sq_STG_CCM_CONTRACT.VAL_YR ) as out_SRC_KEY_VAL,
CASE WHEN sq_STG_CCM_CONTRACT.EMP_YR IS NULL THEN ''Not valid'' ELSE NULL END as out_EMP_YR_ERROR,
''NULL'' as out_EMP_YR_ERR_NM,
sq_STG_CCM_CONTRACT.EMP_YR as out_EMP_YR_ERR_VAL,
CASE WHEN sq_STG_CCM_CONTRACT.VAL_MO = ''00'' THEN CASE WHEN sq_STG_CCM_CONTRACT.PAYROLL_NO = 0 THEN NULL ELSE NULL END ELSE NULL END as out_VAL_MO_ERROR,
''NULL'' as out_VAL_MO_ERR_NM,
sq_STG_CCM_CONTRACT.VAL_MO as out_VAL_MO_ERR_VAL,
CASE WHEN ( sq_STG_CCM_CONTRACT.VAL_YR IS NULL ) THEN ''Not valid'' ELSE NULL END as out_VAL_YR_ERROR,
''NULL'' as out_VAL_YR_ERR_NM,
sq_STG_CCM_CONTRACT.VAL_YR as out_VAL_YR_ERR_VAL,
:PMMappingName as out_ECTL_PRGM_NM,
:ACT_PROJ_ID as out_ECTL_PROJ_ID,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
:PMSTG_CCM_CONTRACTTableName as out_SRC_TABLE_NM,
:ACT_PROJ_ID as IN_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as IN_BATCH_ACTIVE_IND,
''m_STG_FIN_CLM'' IN_PRGM_NM,
null IN_TABLE_NM,
sq_STG_CCM_CONTRACT.source_record_id
FROM
sq_STG_CCM_CONTRACT
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''exp_ERROR_VALIDATION'');

--create or replace temp table mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE as select
--''1'' as out_ECTL_PRGM_ID,
--''1''  as out_ECTL_SRC_ID,
--''1''  as out_ECTL_SRC_INST_ID,
--''1''  as out_ECTL_BATCH_ID,
--''1900-01-01'' as out_ORIG_INS_TS,
--''1900-01-01'' as out_ECTL_BATCH_START_DATE,
--''1''  as out_ECTL_TABLE_ID,
--1 as SOURCE_RECORD_ID;

-- Component rtr_INSERT_REJECT_INSERT, Type ROUTER Output Group INSERT
create or replace temp table rtr_INSERT_REJECT_INSERT as 
SELECT
exp_ERROR_VALIDATION.CCM_CONTRACT_ID as CCM_CONTRACT_ID,
exp_ERROR_VALIDATION.CTT_CONTRACT_NBR as CTT_CONTRACT_NBR,
exp_ERROR_VALIDATION.out_CONT_NBR_ERROR as out_CONT_NBR_ERROR1,
exp_ERROR_VALIDATION.out_CONT_NBR_ERROR_NM as out_CONT_NBR_ERROR_NM1,
exp_ERROR_VALIDATION.out_CCM_CONT_ERROR_VAL as out_CCM_CONT_ERROR_VAL1,
exp_ERROR_VALIDATION.CCM_AGENCY_ID as CCM_AGENCY_ID,
exp_ERROR_VALIDATION.out_CCM_AGENCY_ERROR as out_CCM_AGENCY_ERROR2,
exp_ERROR_VALIDATION.out_CCM_AGNY_ERR_NM as out_CCM_AGNY_ERR_NM2,
exp_ERROR_VALIDATION.out_CCM_AGNY_ERR_VAL as out_CCM_AGNY_ERR_VAL2,
exp_ERROR_VALIDATION.CTT_CTT_CLT_ID as CTT_CTT_CLT_ID,
exp_ERROR_VALIDATION.out_CTT_CLT_ID_ERROR as out_CTT_CLT_ID_ERROR3,
exp_ERROR_VALIDATION.out_CTT_CLT_ID_ERROR_NM as out_CTT_CLT_ID_ERROR_NM3,
exp_ERROR_VALIDATION.out_CTT_CLT_ID_ERROR_VAL as out_CTT_CLT_ID_ERROR_VAL3,
exp_ERROR_VALIDATION.CTT_CTT_TYPE_CD as CTT_CTT_TYPE_CD,
exp_ERROR_VALIDATION.out_EMP_MO_ERROR as out_EMP_MO_ERROR4,
exp_ERROR_VALIDATION.out_EMP_NO_ERR_NM as out_EMP_MO_ERR_NM4,
exp_ERROR_VALIDATION.out_EMP_MO_ERR_VAL as out_EMP_MO_ERR_VAL4,
exp_ERROR_VALIDATION.out_EMP_YR_ERROR as out_EMP_YR_ERROR5,
exp_ERROR_VALIDATION.out_EMP_YR_ERR_NM as out_EMP_YR_ERR_NM5,
exp_ERROR_VALIDATION.out_EMP_YR_ERR_VAL as out_EMP_YR_ERR_VAL5,
exp_ERROR_VALIDATION.out_VAL_MO_ERROR as out_VAL_MO_ERROR6,
exp_ERROR_VALIDATION.out_VAL_MO_ERR_NM as out_VAL_MO_ERR_NM6,
exp_ERROR_VALIDATION.out_VAL_MO_ERR_VAL as out_VAL_MO_ERR_VAL6,
exp_ERROR_VALIDATION.out_VAL_YR_ERROR as out_VAL_YR_ERROR7,
exp_ERROR_VALIDATION.out_VAL_YR_ERR_NM as out_VAL_YR_ERR_NM7,
exp_ERROR_VALIDATION.out_VAL_YR_ERR_VAL as out_VAL_YR_ERR_VAL7,
exp_ERROR_VALIDATION.out_SRC_KEY_VAL as out_SRC_KEY_VAL,
exp_ERROR_VALIDATION.H_CODE as H_CODE,
exp_ERROR_VALIDATION.STATE as STATE,
exp_ERROR_VALIDATION.AGT_NO as AGT_NO,
exp_ERROR_VALIDATION.ORIG_CNTY as ORIG_CNTY,
exp_ERROR_VALIDATION.SERV_CTR as SERV_CTR,
exp_ERROR_VALIDATION.DIST as DIST,
exp_ERROR_VALIDATION.REGION as REGION,
exp_ERROR_VALIDATION.LAST_FIRST_NM as LAST_FIRST_NM,
exp_ERROR_VALIDATION.PAY_AGT as PAY_AGT,
exp_ERROR_VALIDATION.INACTIVE_CD as INACTIVE_CD,
exp_ERROR_VALIDATION.EMP_MO as EMP_MO,
exp_ERROR_VALIDATION.EMP_YR as EMP_YR,
exp_ERROR_VALIDATION.VAL_MO as VAL_MO,
exp_ERROR_VALIDATION.VAL_YR as VAL_YR,
exp_ERROR_VALIDATION.out_AGENT_EFF_DT as out_AGENT_EFF_DT,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_TABLE_ID as out_ECTL_TABLE_ID,
exp_ERROR_VALIDATION.out_ECTL_PROJ_ID as out_ECTL_PROJ_ID,
exp_ERROR_VALIDATION.out_ECTL_TS as out_ECTL_TS,
exp_ERROR_VALIDATION.source_record_id
FROM
exp_ERROR_VALIDATION
LEFT JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_ERROR_VALIDATION.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
WHERE exp_ERROR_VALIDATION.out_CONT_NBR_ERROR IS NULL AND exp_ERROR_VALIDATION.out_CCM_AGENCY_ERROR IS NULL AND exp_ERROR_VALIDATION.out_CTT_CLT_ID_ERROR IS NULL AND ( exp_ERROR_VALIDATION.out_EMP_MO_ERROR IS NULL ) AND ( exp_ERROR_VALIDATION.out_EMP_YR_ERROR IS NULL ) AND ( exp_ERROR_VALIDATION.out_VAL_MO_ERROR IS NULL ) AND ( exp_ERROR_VALIDATION.out_VAL_YR_ERROR IS NULL );


-- Component rtr_INSERT_REJECT_REJ_ERROR_LOG, Type ROUTER Output Group REJ_ERROR_LOG
create or replace temp table RTR_INSERT_REJECT_REJ_ERROR_LOG as
SELECT
exp_ERROR_VALIDATION.CCM_CONTRACT_ID as CCM_CONTRACT_ID,
exp_ERROR_VALIDATION.CTT_CONTRACT_NBR as CTT_CONTRACT_NBR,
exp_ERROR_VALIDATION.out_CONT_NBR_ERROR as out_CONT_NBR_ERROR1,
exp_ERROR_VALIDATION.out_CONT_NBR_ERROR_NM as out_CONT_NBR_ERROR_NM1,
exp_ERROR_VALIDATION.out_CCM_CONT_ERROR_VAL as out_CCM_CONT_ERROR_VAL1,
exp_ERROR_VALIDATION.CCM_AGENCY_ID as CCM_AGENCY_ID,
exp_ERROR_VALIDATION.out_CCM_AGENCY_ERROR as out_CCM_AGENCY_ERROR2,
exp_ERROR_VALIDATION.out_CCM_AGNY_ERR_NM as out_CCM_AGNY_ERR_NM2,
exp_ERROR_VALIDATION.out_CCM_AGNY_ERR_VAL as out_CCM_AGNY_ERR_VAL2,
exp_ERROR_VALIDATION.CTT_CTT_CLT_ID as CTT_CTT_CLT_ID,
exp_ERROR_VALIDATION.out_CTT_CLT_ID_ERROR as out_CTT_CLT_ID_ERROR3,
exp_ERROR_VALIDATION.out_CTT_CLT_ID_ERROR_NM as out_CTT_CLT_ID_ERROR_NM3,
exp_ERROR_VALIDATION.out_CTT_CLT_ID_ERROR_VAL as out_CTT_CLT_ID_ERROR_VAL3,
exp_ERROR_VALIDATION.CTT_CTT_TYPE_CD as CTT_CTT_TYPE_CD,
exp_ERROR_VALIDATION.out_EMP_MO_ERROR as out_EMP_MO_ERROR4,
exp_ERROR_VALIDATION.out_EMP_NO_ERR_NM as out_EMP_MO_ERR_NM4,
exp_ERROR_VALIDATION.out_EMP_MO_ERR_VAL as out_EMP_MO_ERR_VAL4,
exp_ERROR_VALIDATION.out_EMP_YR_ERROR as out_EMP_YR_ERROR5,
exp_ERROR_VALIDATION.out_EMP_YR_ERR_NM as out_EMP_YR_ERR_NM5,
exp_ERROR_VALIDATION.out_EMP_YR_ERR_VAL as out_EMP_YR_ERR_VAL5,
exp_ERROR_VALIDATION.out_VAL_MO_ERROR as out_VAL_MO_ERROR6,
exp_ERROR_VALIDATION.out_VAL_MO_ERR_NM as out_VAL_MO_ERR_NM6,
exp_ERROR_VALIDATION.out_VAL_MO_ERR_VAL as out_VAL_MO_ERR_VAL6,
exp_ERROR_VALIDATION.out_VAL_YR_ERROR as out_VAL_YR_ERROR7,
exp_ERROR_VALIDATION.out_VAL_YR_ERR_NM as out_VAL_YR_ERR_NM7,
exp_ERROR_VALIDATION.out_VAL_YR_ERR_VAL as out_VAL_YR_ERR_VAL7,
exp_ERROR_VALIDATION.out_SRC_KEY_VAL as out_SRC_KEY_VAL,
exp_ERROR_VALIDATION.H_CODE as H_CODE,
exp_ERROR_VALIDATION.STATE as STATE,
exp_ERROR_VALIDATION.AGT_NO as AGT_NO,
exp_ERROR_VALIDATION.ORIG_CNTY as ORIG_CNTY,
exp_ERROR_VALIDATION.SERV_CTR as SERV_CTR,
exp_ERROR_VALIDATION.DIST as DIST,
exp_ERROR_VALIDATION.REGION as REGION,
exp_ERROR_VALIDATION.LAST_FIRST_NM as LAST_FIRST_NM,
exp_ERROR_VALIDATION.PAY_AGT as PAY_AGT,
exp_ERROR_VALIDATION.INACTIVE_CD as INACTIVE_CD,
exp_ERROR_VALIDATION.EMP_MO as EMP_MO,
exp_ERROR_VALIDATION.EMP_YR as EMP_YR,
exp_ERROR_VALIDATION.VAL_MO as VAL_MO,
exp_ERROR_VALIDATION.VAL_YR as VAL_YR,
exp_ERROR_VALIDATION.out_AGENT_EFF_DT as out_AGENT_EFF_DT,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_TABLE_ID as out_ECTL_TABLE_ID,
exp_ERROR_VALIDATION.out_ECTL_PROJ_ID as out_ECTL_PROJ_ID,
exp_ERROR_VALIDATION.out_ECTL_TS as out_ECTL_TS,
exp_ERROR_VALIDATION.source_record_id
FROM
exp_ERROR_VALIDATION
LEFT JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_ERROR_VALIDATION.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
WHERE exp_ERROR_VALIDATION.out_CONT_NBR_ERROR IS NOT NULL OR exp_ERROR_VALIDATION.out_CCM_AGENCY_ERROR IS NOT NULL OR exp_ERROR_VALIDATION.out_CTT_CLT_ID_ERROR IS NOT NULL OR exp_ERROR_VALIDATION.out_EMP_MO_ERROR IS NOT NULL OR exp_ERROR_VALIDATION.out_EMP_YR_ERROR IS NOT NULL OR exp_ERROR_VALIDATION.out_VAL_MO_ERROR IS NOT NULL OR exp_ERROR_VALIDATION.out_VAL_YR_ERROR IS NOT NULL;


-- Component exp_Data_validation, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Data_validation AS
(
SELECT
rtr_INSERT_REJECT_INSERT.CCM_CONTRACT_ID as CCM_CONTRACT_ID,
rtr_INSERT_REJECT_INSERT.CTT_CONTRACT_NBR as CTT_CONTRACT_NBR,
rtr_INSERT_REJECT_INSERT.CCM_AGENCY_ID as CCM_AGENCY_ID,
rtr_INSERT_REJECT_INSERT.CTT_CTT_CLT_ID as CTT_CTT_CLT_ID,
rtr_INSERT_REJECT_INSERT.CTT_CTT_TYPE_CD as CTT_CTT_TYPE_CD,
rtr_INSERT_REJECT_INSERT.H_CODE as H_CODE,
rtr_INSERT_REJECT_INSERT.STATE as STATE,
rtr_INSERT_REJECT_INSERT.AGT_NO as AGT_NO,
rtr_INSERT_REJECT_INSERT.ORIG_CNTY as ORIG_CNTY,
to_char ( rtr_INSERT_REJECT_INSERT.SERV_CTR ) as out_SERV_CTR,
rtr_INSERT_REJECT_INSERT.DIST as DIST,
rtr_INSERT_REJECT_INSERT.REGION as REGION,
rtr_INSERT_REJECT_INSERT.LAST_FIRST_NM as LAST_FIRST_NM,
rtr_INSERT_REJECT_INSERT.PAY_AGT as PAY_AGT,
rtr_INSERT_REJECT_INSERT.INACTIVE_CD as INACTIVE_CD,
rtr_INSERT_REJECT_INSERT.out_AGENT_EFF_DT as AGENT_EFF_DT,
rtr_INSERT_REJECT_INSERT.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
rtr_INSERT_REJECT_INSERT.out_ECTL_SRC_ID as ECTL_SRC_ID,
rtr_INSERT_REJECT_INSERT.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
rtr_INSERT_REJECT_INSERT.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
rtr_INSERT_REJECT_INSERT.out_ORIG_INS_TS as ORIG_INS_TS,
rtr_INSERT_REJECT_INSERT.out_ECTL_BATCH_START_DATE as ECTL_BATCH_START_DATE,
TO_CHAR ( CURRENT_TIMESTAMP , ''YY'' ) as var_CHK_YR,
CASE WHEN rtr_INSERT_REJECT_INSERT.EMP_YR = ''00'' AND rtr_INSERT_REJECT_INSERT.EMP_MO = ''00'' THEN ''9999'' ELSE CASE WHEN rtr_INSERT_REJECT_INSERT.EMP_YR = var_CHK_YR THEN ''20'' || rtr_INSERT_REJECT_INSERT.EMP_YR ELSE CASE WHEN TO_NUMBER(rtr_INSERT_REJECT_INSERT.EMP_YR) >= 46 AND TO_NUMBER(rtr_INSERT_REJECT_INSERT.EMP_YR) <= 99 THEN ''19'' || rtr_INSERT_REJECT_INSERT.EMP_YR ELSE ''20'' || rtr_INSERT_REJECT_INSERT.EMP_YR END END END as var_EMP_YR,
CASE WHEN rtr_INSERT_REJECT_INSERT.VAL_YR = ''00'' AND rtr_INSERT_REJECT_INSERT.VAL_MO = ''00'' THEN ''9999'' ELSE CASE WHEN rtr_INSERT_REJECT_INSERT.VAL_YR = var_CHK_YR THEN ''20'' || rtr_INSERT_REJECT_INSERT.VAL_YR ELSE CASE WHEN rtr_INSERT_REJECT_INSERT.VAL_YR >= ''46'' AND rtr_INSERT_REJECT_INSERT.VAL_YR <= ''99'' THEN ''19'' || rtr_INSERT_REJECT_INSERT.VAL_YR ELSE ''20'' || rtr_INSERT_REJECT_INSERT.VAL_YR END END END as var_VAL_YR,
TO_DATE ( var_EMP_YR || ''/'' || ( CASE WHEN ( rtr_INSERT_REJECT_INSERT.EMP_MO = ''00'' AND rtr_INSERT_REJECT_INSERT.EMP_YR = ''00'' ) THEN ''12'' ELSE rtr_INSERT_REJECT_INSERT.EMP_MO END ) || ''/'' || ( CASE WHEN ( rtr_INSERT_REJECT_INSERT.EMP_MO = ''00'' AND rtr_INSERT_REJECT_INSERT.EMP_YR = ''00'' ) THEN ''31'' ELSE ''01'' END ) , ''YYYY/MM/DD'' ) as var_EMP_DT,
var_EMP_DT as out_EMP_DT,
CASE WHEN rtr_INSERT_REJECT_INSERT.EMP_MO = ''00'' AND rtr_INSERT_REJECT_INSERT.EMP_YR = ''00'' THEN var_EMP_DT ELSE  (  var_EMP_DT + 1 )   - 1  END as out_EMP_DT_DD_01,
1 as DUMMY,
DATE_PART(''YYYY'', TO_TIMESTAMP(var_EMP_DT)) * 100 + DATE_PART(''MM'', TO_TIMESTAMP(var_EMP_DT)) as out_EMP_MOID,
rtr_INSERT_REJECT_INSERT.source_record_id
FROM
rtr_INSERT_REJECT_INSERT
);


-- Component LKP_AGENT_HIER, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_AGENT_HIER AS
(
SELECT
LKP.AGNT_CONTRACT_ID,
LKP.AGNT_CONTRACT_NBR,
LKP.AGENCY_ID,
LKP.AGNT_CONTRACT_TYPE_CD,
LKP.AGENCY_NBR,
LKP.PAY_AGENT_NBR,
LKP.SALES_ST_CD,
LKP.SALES_RGN_CD,
LKP.SALES_DST_CD,
LKP.AGNT_EFF_DT,
LKP.ECTL_TX_CD,
LKP.AGNT_CLIENT_ID,
LKP.AGNT_STATUS_CD,
LKP.SALES_SVC_CD,
LKP.AGNT_EMP_DT,
exp_Data_validation.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_Data_validation.source_record_id ORDER BY LKP.AGNT_CONTRACT_ID asc,LKP.AGNT_CONTRACT_NBR asc,LKP.AGENCY_ID asc,LKP.AGNT_CONTRACT_TYPE_CD asc,LKP.AGENCY_NBR asc,LKP.PAY_AGENT_NBR asc,LKP.SALES_ST_CD asc,LKP.SALES_RGN_CD asc,LKP.SALES_DST_CD asc,LKP.AGNT_EFF_DT asc,LKP.ECTL_TX_CD asc,LKP.AGNT_CLIENT_ID asc,LKP.AGNT_STATUS_CD asc,LKP.SALES_SVC_CD asc,LKP.AGNT_EMP_DT asc) RNK
FROM
exp_Data_validation
LEFT JOIN (
SELECT AGENT_HIER.AGNT_CONTRACT_ID as AGNT_CONTRACT_ID, 
AGENT_HIER.AGNT_CONTRACT_NBR as AGNT_CONTRACT_NBR, 
AGENT_HIER.AGENCY_ID as AGENCY_ID, 
AGENT_HIER.AGNT_CONTRACT_TYPE_CD as AGNT_CONTRACT_TYPE_CD, 
AGENT_HIER.AGENCY_NBR as AGENCY_NBR, 
AGENT_HIER.PAY_AGENT_NBR as PAY_AGENT_NBR, 
AGENT_HIER.SALES_ST_CD as SALES_ST_CD,
AGENT_HIER.SALES_RGN_CD as SALES_RGN_CD, 
AGENT_HIER.SALES_DST_CD as SALES_DST_CD, 
AGENT_HIER.AGNT_EFF_DT as AGNT_EFF_DT, 
AGENT_HIER.ECTL_TX_CD as ECTL_TX_CD, 
trim(AGENT_HIER.AGNT_CLIENT_ID) as AGNT_CLIENT_ID, 
AGNT_STATUS_CD as AGNT_STATUS_CD,
trim(AGENT_HIER.SALES_SVC_CD) as SALES_SVC_CD,AGENT_HIER.AGNT_EMP_DT AS AGNT_EMP_DT
 FROM DB_T_CORE_PROD.AGENT_HIER  
 WHERE  ECTL_TX_CD = ''NEW''
) LKP ON LKP.AGENCY_NBR = exp_Data_validation.AGT_NO
QUALIFY RNK = 1
);


-- Component nrm_ERROR_INFO, Type NORMALIZER 
CREATE OR REPLACE TEMPORARY TABLE nrm_ERROR_INFO AS
(
SELECT ECTL_PROJ_ID_in as ECTL_PROJ_ID, ECTL_BATCH_ID_in as ECTL_BATCH_ID, ECTL_SRC_TABLE_ID_in as ECTL_SRC_TABLE_ID, ECTL_PRGM_ID_in as ECTL_PRGM_ID, * FROM
( /* start of inner SQL */
SELECT
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_CONT_NBR_ERROR1 as ERROR_IN_in1,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_CCM_AGENCY_ERROR2 as ERROR_IN_in2,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_CTT_CLT_ID_ERROR3 as ERROR_IN_in3,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_EMP_MO_ERROR4 as ERROR_IN_in4,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_EMP_YR_ERROR5 as ERROR_IN_in5,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_VAL_MO_ERROR6 as ERROR_IN_in6,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_VAL_YR_ERROR7 as ERROR_IN_in7,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_CONT_NBR_ERROR_NM1 as ERROR_NM_in1,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_CCM_AGNY_ERR_NM2 as ERROR_NM_in2,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_CTT_CLT_ID_ERROR_NM3 as ERROR_NM_in3,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_EMP_MO_ERR_NM4 as ERROR_NM_in4,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_EMP_YR_ERR_NM5 as ERROR_NM_in5,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_VAL_MO_ERR_NM6 as ERROR_NM_in6,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_VAL_YR_ERR_NM7 as ERROR_NM_in7,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_CCM_CONT_ERROR_VAL1 as ERROR_VAL_in1,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_CCM_AGNY_ERR_VAL2 as ERROR_VAL_in2,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_CTT_CLT_ID_ERROR_VAL3 as ERROR_VAL_in3,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_EMP_MO_ERR_VAL4 as ERROR_VAL_in4,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_EMP_YR_ERR_VAL5 as ERROR_VAL_in5,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_VAL_MO_ERR_VAL6 as ERROR_VAL_in6,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_VAL_YR_ERR_VAL7 as ERROR_VAL_in7,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_SRC_KEY_VAL as ERROR_SRC_KEY_VAL_in1,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_SRC_KEY_VAL as ERROR_SRC_KEY_VAL_in2,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_SRC_KEY_VAL as ERROR_SRC_KEY_VAL_in3,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_SRC_KEY_VAL as ERROR_SRC_KEY_VAL_in4,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_SRC_KEY_VAL as ERROR_SRC_KEY_VAL_in5,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_SRC_KEY_VAL as ERROR_SRC_KEY_VAL_in6,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_SRC_KEY_VAL as ERROR_SRC_KEY_VAL_in7,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_ECTL_PROJ_ID as ECTL_PROJ_ID_in,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_ECTL_BATCH_ID as ECTL_BATCH_ID_in,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_ECTL_TABLE_ID as ECTL_SRC_TABLE_ID_in,
rtr_INSERT_REJECT_REJ_ERROR_LOG.out_ECTL_PRGM_ID as ECTL_PRGM_ID_in,
rtr_INSERT_REJECT_REJ_ERROR_LOG.source_record_id
FROM
rtr_INSERT_REJECT_REJ_ERROR_LOG
/* end of inner SQL */
)
--UNPIVOT((ERROR_IN,ERROR_NM,ERROR_SRC_KEY_VAL,ERROR_VAL)) FOR REC_NO IN ((ERROR_IN_in1,ERROR_NM_in1,ERROR_SRC_KEY_VAL_in1,ERROR_VAL_in1) AS REC1, (ERROR_IN_in2,ERROR_NM_in2,ERROR_SRC_KEY_VAL_in2,ERROR_VAL_in2) AS REC2, (ERROR_IN_in3,ERROR_NM_in3,ERROR_SRC_KEY_VAL_in3,ERROR_VAL_in3) AS REC3, (ERROR_IN_in4,ERROR_NM_in4,ERROR_SRC_KEY_VAL_in4,ERROR_VAL_in4) AS REC4, (ERROR_IN_in5,ERROR_NM_in5,ERROR_SRC_KEY_VAL_in5,ERROR_VAL_in5) AS REC5, (ERROR_IN_in6,ERROR_NM_in6,ERROR_SRC_KEY_VAL_in6,ERROR_VAL_in6) AS REC6, (ERROR_IN_in7,ERROR_NM_in7,ERROR_SRC_KEY_VAL_in7,ERROR_VAL_in7) AS REC7) UNPIVOT_TBL
);


-- Component LKP_ECTL_PRGM_PARAM_TO_DATE, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_ECTL_PRGM_PARAM_TO_DATE AS
(
SELECT
LKP.ECTL_PARAM_VALUE,
LKP.ECTL_SRC_ID,
exp_Data_validation.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_Data_validation.source_record_id ORDER BY LKP.ECTL_PARAM_VALUE asc,LKP.ECTL_SRC_ID asc) RNK
FROM
exp_Data_validation
LEFT JOIN (
SELECT ECTL_PARAM_VALUE  AS ECTL_PARAM_VALUE,
1 AS ECTL_SRC_ID 
 FROM DB_T_CTRL_PROD.ECTL_PRGM_PARAM WHERE ECTL_PRGM_ID = 0 AND ECTL_PARAM_ID = 14
) LKP ON LKP.ECTL_SRC_ID = exp_Data_validation.DUMMY
QUALIFY RNK = 1
);


-- Component fil_ERROR_LOG, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE fil_ERROR_LOG AS
(
SELECT
nrm_ERROR_INFO.ECTL_PRGM_ID as ECTL_PRGM_ID_in,
nrm_ERROR_INFO.ECTL_PROJ_ID as ECTL_PROJ_ID,
nrm_ERROR_INFO.ECTL_BATCH_ID as ECTL_BATCH_ID,
nrm_ERROR_INFO.ECTL_SRC_TABLE_ID as ECTL_SRC_TABLE_ID,
null as ERROR_IN,
--nrm_ERROR_INFO.ERROR_IN as ERROR_IN,
null as ERROR_NM,
--nrm_ERROR_INFO.ERROR_NM as ERROR_NM,
null  as ERROR_VAL,
--nrm_ERROR_INFO.ERROR_VAL as ERROR_VAL,
null as ERROR_SRC_KEY_VAL,
--nrm_ERROR_INFO.ERROR_SRC_KEY_VAL as ERROR_SRC_KEY_VAL,
nrm_ERROR_INFO.source_record_id
FROM
nrm_ERROR_INFO
--WHERE nrm_ERROR_INFO.ERROR_IN IS NOT NULL
);


-- Component exp_CHECK_NULLS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CHECK_NULLS AS
(
SELECT
LKP_AGENT_HIER.AGNT_EFF_DT as AGNT_EFF_DT_lkp,
exp_Data_validation.CCM_CONTRACT_ID as CCM_CONTRACT_ID,
exp_Data_validation.CTT_CONTRACT_NBR as CTT_CONTRACT_NBR,
exp_Data_validation.CCM_AGENCY_ID as CCM_AGENCY_ID,
exp_Data_validation.CTT_CTT_CLT_ID as CTT_CTT_CLT_ID,
exp_Data_validation.CTT_CTT_TYPE_CD as CTT_CTT_TYPE_CD,
exp_Data_validation.STATE as STATE,
exp_Data_validation.AGT_NO as AGT_NO,
exp_Data_validation.ORIG_CNTY as ORIG_CNTY,
exp_Data_validation.out_SERV_CTR as SERV_CTR,
exp_Data_validation.DIST as DIST,
exp_Data_validation.REGION as REGION,
exp_Data_validation.PAY_AGT as PAY_AGT,
exp_Data_validation.INACTIVE_CD as INACTIVE_CD,
exp_Data_validation.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_Data_validation.ECTL_SRC_ID as ECTL_SRC_ID,
exp_Data_validation.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_Data_validation.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_Data_validation.ORIG_INS_TS as ORIG_INS_TS,
exp_Data_validation.ECTL_BATCH_START_DATE as ECTL_BATCH_START_DATE,
DATE_PART(''YYYY'', TO_TIMESTAMP(LKP_AGENT_HIER.AGNT_EMP_DT)) * 100 + DATE_PART(''MM'', TO_TIMESTAMP(LKP_AGENT_HIER.AGNT_EMP_DT)) as EMP_MOID_lkp,
CASE WHEN LKP_AGENT_HIER.AGENCY_NBR IS NULL THEN ''NEW'' ELSE CASE WHEN CASE WHEN exp_Data_validation.CTT_CTT_CLT_ID IS NULL THEN ''~'' ELSE exp_Data_validation.CTT_CTT_CLT_ID END <> CASE WHEN LKP_AGENT_HIER.AGNT_CLIENT_ID IS NULL THEN ''~'' ELSE LKP_AGENT_HIER.AGNT_CLIENT_ID END OR CASE WHEN exp_Data_validation.CCM_CONTRACT_ID IS NULL THEN ''~'' ELSE exp_Data_validation.CCM_CONTRACT_ID END <> CASE WHEN LKP_AGENT_HIER.AGNT_CONTRACT_ID IS NULL THEN ''~'' ELSE LKP_AGENT_HIER.AGNT_CONTRACT_ID END OR CASE WHEN exp_Data_validation.CTT_CONTRACT_NBR IS NULL THEN ''~'' ELSE exp_Data_validation.CTT_CONTRACT_NBR END <> CASE WHEN LKP_AGENT_HIER.AGNT_CONTRACT_NBR IS NULL THEN ''~'' ELSE LKP_AGENT_HIER.AGNT_CONTRACT_NBR END OR CASE WHEN exp_Data_validation.CCM_AGENCY_ID IS NULL THEN ''~'' ELSE exp_Data_validation.CCM_AGENCY_ID END <> CASE WHEN LKP_AGENT_HIER.AGENCY_ID IS NULL THEN ''~'' ELSE LKP_AGENT_HIER.AGENCY_ID END OR CASE WHEN exp_Data_validation.CTT_CTT_TYPE_CD IS NULL THEN ''~'' ELSE exp_Data_validation.CTT_CTT_TYPE_CD END <> CASE WHEN LKP_AGENT_HIER.AGNT_CONTRACT_TYPE_CD IS NULL THEN ''~'' ELSE LKP_AGENT_HIER.AGNT_CONTRACT_TYPE_CD END OR CASE WHEN exp_Data_validation.AGT_NO IS NULL THEN ''~'' ELSE exp_Data_validation.AGT_NO END <> CASE WHEN LKP_AGENT_HIER.AGENCY_NBR IS NULL THEN ''~'' ELSE LKP_AGENT_HIER.AGENCY_NBR END OR CASE WHEN exp_Data_validation.PAY_AGT IS NULL THEN ''~'' ELSE exp_Data_validation.PAY_AGT END <> CASE WHEN LKP_AGENT_HIER.PAY_AGENT_NBR IS NULL THEN ''~'' ELSE LKP_AGENT_HIER.PAY_AGENT_NBR END OR CASE WHEN exp_Data_validation.STATE IS NULL THEN ''~'' ELSE exp_Data_validation.STATE END <> CASE WHEN LKP_AGENT_HIER.SALES_ST_CD IS NULL THEN ''~'' ELSE LKP_AGENT_HIER.SALES_ST_CD END OR CASE WHEN exp_Data_validation.REGION IS NULL THEN ''~'' ELSE exp_Data_validation.REGION END <> CASE WHEN LKP_AGENT_HIER.SALES_RGN_CD IS NULL THEN ''~'' ELSE LKP_AGENT_HIER.SALES_RGN_CD END OR CASE WHEN exp_Data_validation.INACTIVE_CD IS NULL THEN ''~'' ELSE exp_Data_validation.INACTIVE_CD END <> CASE WHEN LKP_AGENT_HIER.AGNT_STATUS_CD IS NULL THEN ''~'' ELSE LKP_AGENT_HIER.AGNT_STATUS_CD END OR CASE WHEN exp_Data_validation.DIST IS NULL THEN ''~'' ELSE exp_Data_validation.DIST END <> CASE WHEN LKP_AGENT_HIER.SALES_DST_CD IS NULL THEN ''~'' ELSE LKP_AGENT_HIER.SALES_DST_CD END OR CASE WHEN LKP_AGENT_HIER.SALES_SVC_CD IS NULL THEN ''~'' ELSE LKP_AGENT_HIER.SALES_SVC_CD END <> CASE WHEN exp_Data_validation.out_SERV_CTR IS NULL THEN ''~'' ELSE exp_Data_validation.out_SERV_CTR END THEN ''UPD'' ELSE ''REJ'' END END as var_CHK,
var_CHK as out_CHK,
-- ( TO_DATE ( LKP_ECTL_PRGM_PARAM_TO_DATE.ECTL_PARAM_VALUE , ''YYYY-MM-DD'' ) ) , ''DD'' , ( ( TO_NUMBER(DATE_PART(''DD'', TO_TIMESTAMP(( TO_DATE ( LKP_ECTL_PRGM_PARAM_TO_DATE.ECTL_PARAM_VALUE , ''YYYY-MM-DD'' ) )))) - 1 ) * ( - 1 ) )  as var_TO_DATE,
 ( TO_DATE ( LKP_ECTL_PRGM_PARAM_TO_DATE.ECTL_PARAM_VALUE , ''YYYY-MM-DD'' ) )   as var_TO_DATE,
''NEW'' as out_ECTL_TX_CD_NEW,
''UPD'' as out_ECTL_TX_CD_UPD,
CASE WHEN var_CHK = ''NEW'' and ( exp_Data_validation.INACTIVE_CD IS NULL OR TRIM(exp_Data_validation.INACTIVE_CD) = '''' ) THEN exp_Data_validation.out_EMP_DT ELSE ( CASE WHEN var_CHK = ''NEW'' and ( exp_Data_validation.INACTIVE_CD = ''J'' OR exp_Data_validation.INACTIVE_CD = ''-'' ) THEN TO_DATE ( ''2005-11-01'' , ''YYYY-MM-DD'' ) ELSE LKP_AGENT_HIER.AGNT_EMP_DT END ) END as var_AGNT_EMP_DT,
var_AGNT_EMP_DT as out_AGNT_EMP_DT,
CASE WHEN exp_Data_validation.INACTIVE_CD IS NULL OR TRIM(exp_Data_validation.INACTIVE_CD) = '''' THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_Data_validation.out_EMP_DT_DD_01 END as var_AGNT_TERMINATION_DT,
var_AGNT_TERMINATION_DT as out_AGNT_TERMINATION_DT,
CASE WHEN var_CHK = ''NEW'' THEN var_AGNT_EMP_DT ELSE var_TO_DATE END as var_AGNT_EFF_DT,
var_AGNT_EFF_DT as out_AGNT_EFF_DT,
TO_DATE ( ''12-31-9999'' , ''MM-DD-YYYY'' ) as out_END_DATE_NEW,
CURRENT_TIMESTAMP as out_END_DATE_UPD,
var_AGNT_TERMINATION_DT as out_AGNT_EXPIRY_DT_NEW,
 var_AGNT_EFF_DT  - 1  as out_AGNT_EXPIRY_DT_UPD,
exp_Data_validation.source_record_id
FROM
exp_Data_validation
INNER JOIN LKP_AGENT_HIER ON exp_Data_validation.source_record_id = LKP_AGENT_HIER.source_record_id
INNER JOIN LKP_ECTL_PRGM_PARAM_TO_DATE ON LKP_AGENT_HIER.source_record_id = LKP_ECTL_PRGM_PARAM_TO_DATE.source_record_id
);


-- Component rtr_NEW_UPD_INSERT, Type ROUTER Output Group INSERT
create or replace temp table RTR_NEW_UPD_INSERT as
SELECT
exp_CHECK_NULLS.CTT_CTT_CLT_ID as AGNT_CLIENT_ID,
exp_CHECK_NULLS.CCM_CONTRACT_ID as AGNT_CONTRACT_ID,
exp_CHECK_NULLS.CTT_CONTRACT_NBR as AGNT_CONTRACT_NBR,
exp_CHECK_NULLS.CCM_AGENCY_ID as AGENCY_ID,
exp_CHECK_NULLS.CTT_CTT_TYPE_CD as AGNT_CONTRACT_TYPE_CD,
exp_CHECK_NULLS.AGT_NO as AGENCY_NBR,
exp_CHECK_NULLS.PAY_AGT as PAY_AGENT_NBR,
exp_CHECK_NULLS.STATE as SALES_ST_CD,
exp_CHECK_NULLS.REGION as SALES_RGN_CD,
exp_CHECK_NULLS.DIST as SALES_DST_CD,
exp_CHECK_NULLS.SERV_CTR as SALES_SVC_CD,
exp_CHECK_NULLS.out_AGNT_EMP_DT as AGNT_EMP_DT,
exp_CHECK_NULLS.out_AGNT_TERMINATION_DT as AGNT_TERMINATION_DT,
exp_CHECK_NULLS.out_AGNT_EFF_DT as AGNT_EFF_DT,
exp_CHECK_NULLS.out_AGNT_EXPIRY_DT_NEW as AGNT_EXPIRY_DT_NEW,
exp_CHECK_NULLS.INACTIVE_CD as AGNT_STATUS_CD,
nvl(exp_CHECK_NULLS.ECTL_BATCH_ID,''1'') as ECTL_BATCH_ID,
nvl(exp_CHECK_NULLS.ORIG_INS_TS,''1900-01-01'') as ECTL_ORIG_INS_TS,
nvl(exp_CHECK_NULLS.ORIG_INS_TS,''1900-01-01'') as ECTL_MODIFY_TS,
nvl(exp_CHECK_NULLS.ECTL_SRC_ID,''1'') as ECTL_SRC_ID,
nvl(exp_CHECK_NULLS.ECTL_SRC_INST_ID,''1'') as ECTL_SRC_INST_ID,
nvl(exp_CHECK_NULLS.ECTL_PRGM_ID,''1'') as ECTL_PRGM_ID,
nvl(exp_CHECK_NULLS.out_CHK,''1'') as ECTL_TX_CD,
nvl(exp_CHECK_NULLS.ECTL_BATCH_START_DATE,''1900-01-01'') as ECTL_START_DATE,
nvl(exp_CHECK_NULLS.out_ECTL_TX_CD_NEW,''1'') as ECTL_TX_CD_NEW,
nvl(exp_CHECK_NULLS.out_ECTL_TX_CD_UPD,''1'') as ECTL_TX_CD_UPD,
exp_CHECK_NULLS.out_END_DATE_UPD as END_DATE_UPD,
exp_CHECK_NULLS.AGNT_EFF_DT_lkp as tgt_AGNT_EFF_DT,
exp_CHECK_NULLS.out_END_DATE_NEW as END_DATE_NEW,
exp_CHECK_NULLS.out_AGNT_EXPIRY_DT_UPD as AGNT_EXPIRY_DT_UPD,
exp_CHECK_NULLS.source_record_id
FROM
exp_CHECK_NULLS
WHERE exp_CHECK_NULLS.out_CHK = ''NEW'' OR exp_CHECK_NULLS.out_CHK = ''UPD'';


-- Component rtr_NEW_UPD_UPDATE, Type ROUTER Output Group UPDATE
create or replace temp table RTR_NEW_UPD_UPDATE as
SELECT
exp_CHECK_NULLS.CTT_CTT_CLT_ID as AGNT_CLIENT_ID,
exp_CHECK_NULLS.CCM_CONTRACT_ID as AGNT_CONTRACT_ID,
exp_CHECK_NULLS.CTT_CONTRACT_NBR as AGNT_CONTRACT_NBR,
exp_CHECK_NULLS.CCM_AGENCY_ID as AGENCY_ID,
exp_CHECK_NULLS.CTT_CTT_TYPE_CD as AGNT_CONTRACT_TYPE_CD,
exp_CHECK_NULLS.AGT_NO as AGENCY_NBR,
exp_CHECK_NULLS.PAY_AGT as PAY_AGENT_NBR,
exp_CHECK_NULLS.STATE as SALES_ST_CD,
exp_CHECK_NULLS.REGION as SALES_RGN_CD,
exp_CHECK_NULLS.DIST as SALES_DST_CD,
exp_CHECK_NULLS.SERV_CTR as SALES_SVC_CD,
exp_CHECK_NULLS.out_AGNT_EMP_DT as AGNT_EMP_DT,
exp_CHECK_NULLS.out_AGNT_TERMINATION_DT as AGNT_TERMINATION_DT,
exp_CHECK_NULLS.out_AGNT_EFF_DT as AGNT_EFF_DT,
exp_CHECK_NULLS.out_AGNT_EXPIRY_DT_NEW as AGNT_EXPIRY_DT_NEW,
exp_CHECK_NULLS.INACTIVE_CD as AGNT_STATUS_CD,
nvl(exp_CHECK_NULLS.ECTL_BATCH_ID,''1'') as ECTL_BATCH_ID,
nvl(exp_CHECK_NULLS.ORIG_INS_TS,''1900-01-01'') as ECTL_ORIG_INS_TS,
nvl(exp_CHECK_NULLS.ORIG_INS_TS,''1900-01-01'') as ECTL_MODIFY_TS,
nvl(exp_CHECK_NULLS.ECTL_SRC_ID,''1'') as ECTL_SRC_ID,
nvl(exp_CHECK_NULLS.ECTL_SRC_INST_ID,''1'') as ECTL_SRC_INST_ID,
nvl(exp_CHECK_NULLS.ECTL_PRGM_ID,''1'') as ECTL_PRGM_ID,
nvl(exp_CHECK_NULLS.out_CHK,''1'') as ECTL_TX_CD,
nvl(exp_CHECK_NULLS.ECTL_BATCH_START_DATE,''1900-01-01'') as ECTL_START_DATE,
nvl(exp_CHECK_NULLS.out_ECTL_TX_CD_NEW,''1'') as ECTL_TX_CD_NEW,
nvl(exp_CHECK_NULLS.out_ECTL_TX_CD_UPD,''1'') as ECTL_TX_CD_UPD,
exp_CHECK_NULLS.out_END_DATE_UPD as END_DATE_UPD,
exp_CHECK_NULLS.AGNT_EFF_DT_lkp as tgt_AGNT_EFF_DT,
exp_CHECK_NULLS.out_END_DATE_NEW as END_DATE_NEW,
exp_CHECK_NULLS.out_AGNT_EXPIRY_DT_UPD as AGNT_EXPIRY_DT_UPD,
exp_CHECK_NULLS.source_record_id
FROM
exp_CHECK_NULLS
WHERE exp_CHECK_NULLS.out_CHK = ''UPD'';


-- Component AGENT_HIER_INS, Type TARGET 
INSERT INTO DB_T_CORE_PROD.AGENT_HIER
(
AGNT_CLIENT_ID,
AGNT_CONTRACT_ID,
AGNT_CONTRACT_NBR,
AGENCY_ID,
AGNT_CONTRACT_TYPE_CD,
AGENCY_NBR,
PAY_AGENT_NBR,
SALES_ST_CD,
SALES_RGN_CD,
SALES_DST_CD,
SALES_SVC_CD,
AGNT_EMP_DT,
AGNT_TERMINATION_DT,
AGNT_EFF_DT,
AGNT_EXPIRY_DT,
AGNT_STATUS_CD,
ECTL_BATCH_ID,
ECTL_ORIG_INS_TS,
ECTL_MODIFY_TS,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_PRGM_ID,
ECTL_TX_CD,
ECTL_START_DATE,
ECTL_END_DATE
)
SELECT
rtr_NEW_UPD_INSERT.AGNT_CLIENT_ID as AGNT_CLIENT_ID,
rtr_NEW_UPD_INSERT.AGNT_CONTRACT_ID as AGNT_CONTRACT_ID,
rtr_NEW_UPD_INSERT.AGNT_CONTRACT_NBR as AGNT_CONTRACT_NBR,
rtr_NEW_UPD_INSERT.AGENCY_ID as AGENCY_ID,
rtr_NEW_UPD_INSERT.AGNT_CONTRACT_TYPE_CD as AGNT_CONTRACT_TYPE_CD,
rtr_NEW_UPD_INSERT.AGENCY_NBR as AGENCY_NBR,
rtr_NEW_UPD_INSERT.PAY_AGENT_NBR as PAY_AGENT_NBR,
rtr_NEW_UPD_INSERT.SALES_ST_CD as SALES_ST_CD,
rtr_NEW_UPD_INSERT.SALES_RGN_CD as SALES_RGN_CD,
rtr_NEW_UPD_INSERT.SALES_DST_CD as SALES_DST_CD,
rtr_NEW_UPD_INSERT.SALES_SVC_CD as SALES_SVC_CD,
rtr_NEW_UPD_INSERT.AGNT_EMP_DT as AGNT_EMP_DT,
rtr_NEW_UPD_INSERT.AGNT_TERMINATION_DT as AGNT_TERMINATION_DT,
rtr_NEW_UPD_INSERT.AGNT_EFF_DT as AGNT_EFF_DT,
rtr_NEW_UPD_INSERT.AGNT_EXPIRY_DT_NEW as AGNT_EXPIRY_DT,
rtr_NEW_UPD_INSERT.AGNT_STATUS_CD as AGNT_STATUS_CD,
nvl(rtr_NEW_UPD_INSERT.ECTL_BATCH_ID,''1'') as ECTL_BATCH_ID,
rtr_NEW_UPD_INSERT.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
rtr_NEW_UPD_INSERT.ECTL_MODIFY_TS as ECTL_MODIFY_TS,
rtr_NEW_UPD_INSERT.ECTL_SRC_ID as ECTL_SRC_ID,
rtr_NEW_UPD_INSERT.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
rtr_NEW_UPD_INSERT.ECTL_PRGM_ID as ECTL_PRGM_ID,
rtr_NEW_UPD_INSERT.ECTL_TX_CD_NEW as ECTL_TX_CD,
rtr_NEW_UPD_INSERT.ECTL_START_DATE as ECTL_START_DATE,
rtr_NEW_UPD_INSERT.END_DATE_NEW as ECTL_END_DATE
FROM
rtr_NEW_UPD_INSERT;


-- Component AGENT_HIER_INS, Type Post SQL 
UPDATE DB_T_CORE_PROD.AGENT_HIER SET AGNT_EXPIRY_DT = ''9999-12-31'' WHERE ECTL_TX_CD = ''NEW'';


-- Component exp_Errorlog_Info, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Errorlog_Info AS
(
SELECT
fil_ERROR_LOG.ECTL_PRGM_ID_in as ECTL_PRGM_ID_in,
fil_ERROR_LOG.ECTL_PROJ_ID as ECTL_PROJ_ID,
fil_ERROR_LOG.ECTL_BATCH_ID as ECTL_BATCH_ID,
fil_ERROR_LOG.ECTL_SRC_TABLE_ID as ECTL_SRC_TABLE_ID,
fil_ERROR_LOG.ERROR_IN as ERROR_IN,
fil_ERROR_LOG.ERROR_NM as ERROR_NM,
fil_ERROR_LOG.ERROR_VAL as ERROR_VAL,
fil_ERROR_LOG.ERROR_SRC_KEY_VAL as ERROR_SRC_KEY_VAL,
CURRENT_TIMESTAMP as out_ECTL_ORIG_INS_TS,
:PMSTG_CCM_CONTRACTTableName as out_SRC_TABLE_NM2,
fil_ERROR_LOG.source_record_id
FROM
fil_ERROR_LOG
);


-- Component upd_AGENT_HIER, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_AGENT_HIER AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
rtr_NEW_UPD_UPDATE.ECTL_BATCH_ID as ECTL_BATCH_ID,
rtr_NEW_UPD_UPDATE.ECTL_MODIFY_TS as ECTL_MOD_TS,
rtr_NEW_UPD_UPDATE.ECTL_TX_CD_UPD as ECTL_TX_CD,
rtr_NEW_UPD_UPDATE.END_DATE_UPD as END_DATE,
rtr_NEW_UPD_UPDATE.tgt_AGNT_EFF_DT as AGNT_EFF_DT,
rtr_NEW_UPD_UPDATE.AGENCY_NBR as AGENCY_NBR,
rtr_NEW_UPD_UPDATE.AGNT_EXPIRY_DT_UPD as AGNT_EXPIRY_DT_UPD1,
1 as UPDATE_STRATEGY_ACTION
FROM
rtr_NEW_UPD_UPDATE
);


-- Component LKP_ECTL_TABLE_XREF, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_ECTL_TABLE_XREF AS
(
SELECT
LKP.ECTL_TABLE_ID,
exp_Errorlog_Info.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_Errorlog_Info.source_record_id ORDER BY LKP.ECTL_TABLE_ID asc) RNK
FROM
exp_Errorlog_Info
LEFT JOIN (
SELECT ECTL_TABLE_XREF.ECTL_TABLE_ID as ECTL_TABLE_ID, TRIM(ECTL_TABLE_XREF.ECTL_TABLE_NM) as ECTL_TABLE_NM FROM DB_T_CTRL_PROD.ECTL_TABLE_XREF
) LKP ON LKP.ECTL_TABLE_NM = exp_Errorlog_Info.out_SRC_TABLE_NM2
QUALIFY RNK = 1
);


-- Component exp_ECTL_ERR_LOG, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ECTL_ERR_LOG AS
(
SELECT
exp_Errorlog_Info.ECTL_PRGM_ID_in as ECTL_PRGM_ID_in,
exp_Errorlog_Info.ECTL_PROJ_ID as ECTL_PROJ_ID,
exp_Errorlog_Info.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_Errorlog_Info.ERROR_IN as ERROR_IN,
exp_Errorlog_Info.ERROR_NM as ERROR_NM,
exp_Errorlog_Info.ERROR_VAL as ERROR_VAL,
exp_Errorlog_Info.ERROR_SRC_KEY_VAL as ERROR_SRC_KEY_VAL,
exp_Errorlog_Info.out_ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
CASE WHEN exp_Errorlog_Info.ERROR_NM IN ( LTRIM ( RTRIM ( exp_Errorlog_Info.ERROR_NM ) ) , ''CCM_AGCY_ID'' , ''CTT_CTT_CLT_ID'' , ''CCM_CONTRACT_NBR'' ) THEN exp_Errorlog_Info.ECTL_SRC_TABLE_ID ELSE LKP_ECTL_TABLE_XREF.ECTL_TABLE_ID END as out_SRC_TABLE_ID,
exp_Errorlog_Info.source_record_id
FROM
exp_Errorlog_Info
INNER JOIN LKP_ECTL_TABLE_XREF ON exp_Errorlog_Info.source_record_id = LKP_ECTL_TABLE_XREF.source_record_id
);


-- Component AGENT_HIER_UPD, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_CORE_PROD.AGENT_HIER
USING upd_AGENT_HIER ON (UPDATE_STRATEGY_ACTION = 1 AND AGENT_HIER.AGENCY_NBR = upd_AGENT_HIER.AGENCY_NBR AND AGENT_HIER.AGNT_EFF_DT = upd_AGENT_HIER.AGNT_EFF_DT)
WHEN MATCHED THEN UPDATE
SET
AGNT_EXPIRY_DT = upd_AGENT_HIER.AGNT_EXPIRY_DT_UPD1,
ECTL_BATCH_ID = nvl(upd_AGENT_HIER.ECTL_BATCH_ID,''1''),
ECTL_MODIFY_TS = upd_AGENT_HIER.ECTL_MOD_TS,
ECTL_TX_CD = upd_AGENT_HIER.ECTL_TX_CD,
ECTL_END_DATE = upd_AGENT_HIER.END_DATE
;


-- Component AGENT_HIER_UPD, Type Post SQL 
UPDATE DB_T_CORE_PROD.AGENT_HIER TGT FROM  (
SELECT AGENCY_NBR,AGNT_EFF_DT, ECTL_ORIG_INS_TS,coalesce(MAX(AGNT_EFF_DT) OVER(PARTITION BY AGENCY_NBR ORDER BY ECTL_ORIG_INS_TS ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) -1,CAST(''9999-12-31''AS DATE)) AGNT_EXPIRY_DT_NEW,
AGNT_EXPIRY_DT FROM DB_T_CORE_PROD.AGENT_HIER 
WHERE AGENCY_NBR NOT LIKE ''%-%''
) SRC
SET AGNT_EXPIRY_DT=COALESCE(AGNT_EXPIRY_DT_NEW,CAST(''9999-12-31''AS DATE)),
ECTL_TX_CD=CASE WHEN AGNT_EXPIRY_DT_NEW=''9999-12-31'' THEN ''NEW'' ELSE ''UPD'' END
WHERE TGT.AGENCY_NBR=SRC.AGENCY_NBR
AND SRC.AGNT_EFF_DT=TGT.AGNT_EFF_DT
and src.ECTL_ORIG_INS_TS=tgt.ECTL_ORIG_INS_TS;


-- Component ECTL_ERR_LOG_INS, Type TARGET 
INSERT INTO DB_T_CTRL_FIN_PROD.ECTL_ERR_LOG
(
ECTL_ERR_ID,
ECTL_BATCH_ID,
ECTL_PROJ_ID,
ECTL_PRGM_ID,
ECTL_SRC_TABLE_ID,
ECTL_SRC_KEY_VAL,
ERR_COL_NM,
ERR_COL_VAL,
ERR_DESC,
ERR_TS
)
SELECT
row_number() over (order by 1) as ECTL_ERR_ID,
exp_ECTL_ERR_LOG.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_ECTL_ERR_LOG.ECTL_PROJ_ID as ECTL_PROJ_ID,
exp_ECTL_ERR_LOG.ECTL_PRGM_ID_in as ECTL_PRGM_ID,
exp_ECTL_ERR_LOG.out_SRC_TABLE_ID as ECTL_SRC_TABLE_ID,
exp_ECTL_ERR_LOG.ERROR_SRC_KEY_VAL as ECTL_SRC_KEY_VAL,
exp_ECTL_ERR_LOG.ERROR_NM as ERR_COL_NM,
exp_ECTL_ERR_LOG.ERROR_VAL as ERR_COL_VAL,
exp_ECTL_ERR_LOG.ERROR_IN as ERR_DESC,
exp_ECTL_ERR_LOG.ECTL_ORIG_INS_TS as ERR_TS
FROM
exp_ECTL_ERR_LOG;


END; ';