-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_AGNT_NAME_LKUP("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE PMMAPPINGNAME varchar;
BATCH_ACTIVE_IND varchar;
ACT_PROJ_ID varchar;
BEGIN 

PMMAPPINGNAME:=''m_AGNT_NAME_LKUP''; 
BATCH_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
ACT_PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 


-- Component SQ_Shortcut_to_STG_CCM_CONTRACT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_STG_CCM_CONTRACT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CTT_CONTRACT_NBR,
$2 as CTT_CTT_CLT_ID,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT DISTINCT STG_CCM_CONTRACT.CTT_CONTRACT_NBR, STG_CCM_CONTRACT.CTT_CTT_CLT_ID 
FROM
 DB_T_STAG_PROD.STG_CCM_CONTRACT
) SRC
)
);


-- Component sq_STG_AGENT_NAME, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_AGENT_NAME AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as AGT_NO,
$2 as LAST_FIRST_NM,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT DISTINCT AGT_NO, LAST_FIRST_NM from 
 DB_T_STAG_PROD.STG_AGENT_NAME
) SRC
)
);


-- Component JNRTRANS, Type JOINER 
CREATE OR REPLACE TEMPORARY TABLE JNRTRANS AS
(
SELECT
SQ_Shortcut_to_STG_CCM_CONTRACT.CTT_CONTRACT_NBR as CTT_CONTRACT_NBR,
SQ_Shortcut_to_STG_CCM_CONTRACT.CTT_CTT_CLT_ID as CTT_CTT_CLT_ID,
sq_STG_AGENT_NAME.AGT_NO as AGT_NO,
sq_STG_AGENT_NAME.LAST_FIRST_NM as LAST_FIRST_NM,
row_number() over (order by 1) AS source_record_id
FROM
sq_STG_AGENT_NAME
LEFT OUTER JOIN SQ_Shortcut_to_STG_CCM_CONTRACT ON sq_STG_AGENT_NAME.AGT_NO = SQ_Shortcut_to_STG_CCM_CONTRACT.CTT_CONTRACT_NBR
);


-- Component AGGTRANS, Type AGGREGATOR 
CREATE OR REPLACE TEMPORARY TABLE AGGTRANS AS
(
SELECT
JNRTRANS.CTT_CTT_CLT_ID as CTT_CTT_CLT_ID,
MIN(JNRTRANS.LAST_FIRST_NM) as in_LAST_FIRST_NM,
max(JNRTRANS.LAST_FIRST_NM) as out_LAST_FIRST_NM,
MIN(JNRTRANS.source_record_id) as source_record_id
FROM
JNRTRANS
GROUP BY
JNRTRANS.CTT_CTT_CLT_ID
);


-- Component exp_TRIM_SRC_PARAM_FIELDS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_TRIM_SRC_PARAM_FIELDS AS
(
SELECT
AGGTRANS.CTT_CTT_CLT_ID as AGNT_CLIENT_ID,
LTRIM ( RTRIM ( AGGTRANS.out_LAST_FIRST_NM ) ) as var_AGNT_NM_DESC,
CASE WHEN ( var_AGNT_NM_DESC IS NULL OR LENGTH ( var_AGNT_NM_DESC ) = 0 ) THEN AGGTRANS.CTT_CTT_CLT_ID ELSE var_AGNT_NM_DESC END as out_AGNT_NM_DESC,
:PMMappingName as out_PRGM_NM,
:ACT_PROJ_ID as out_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
:ACT_PROJ_ID as IN_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as IN_BATCH_ACTIVE_IND,
''m_STG_FIN_CLM'' IN_PRGM_NM,
null IN_TABLE_NM,
AGGTRANS.source_record_id
FROM
AGGTRANS
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_core(''exp_TRIM_SRC_PARAM_FIELDS'');



-- Component LKP_AGNT_NAME_LKUP, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_AGNT_NAME_LKUP AS
(
SELECT
LKP.AGNT_CLIENT_ID,
LKP.SRC_AGNT_CLIENT_ID,
LKP.AGNT_NM_DESC,
exp_TRIM_SRC_PARAM_FIELDS.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_TRIM_SRC_PARAM_FIELDS.source_record_id ORDER BY LKP.AGNT_CLIENT_ID asc,LKP.SRC_AGNT_CLIENT_ID asc,LKP.AGNT_NM_DESC asc) RNK
FROM
exp_TRIM_SRC_PARAM_FIELDS
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_core mplt_LKP_ECTL_BATCH_PRGM_VALIDATION ON exp_TRIM_SRC_PARAM_FIELDS.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.source_record_id
LEFT JOIN (
SELECT LTRIM(RTRIM(AGNT_NAME_LKUP.SRC_AGNT_CLIENT_ID)) as SRC_AGNT_CLIENT_ID, LTRIM(RTRIM(AGNT_NAME_LKUP.AGNT_NM_DESC)) as AGNT_NM_DESC, LTRIM(RTRIM(AGNT_NAME_LKUP.AGNT_CLIENT_ID)) as AGNT_CLIENT_ID, AGNT_NAME_LKUP.ECTL_SRC_ID as ECTL_SRC_ID FROM DB_T_SHRD_PROD.AGNT_NAME_LKUP
) LKP ON LKP.AGNT_CLIENT_ID = exp_TRIM_SRC_PARAM_FIELDS.AGNT_CLIENT_ID AND LKP.ECTL_SRC_ID = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_SRC_ID
QUALIFY RNK = 1
);


-- Component exp_SET_VAR_CHK, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_SET_VAR_CHK AS
(
SELECT
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_SRC_ID as ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ORIG_INS_TS as ORIG_INS_TS,
exp_TRIM_SRC_PARAM_FIELDS.AGNT_CLIENT_ID as AGNT_CLIENT_ID,
exp_TRIM_SRC_PARAM_FIELDS.AGNT_CLIENT_ID as SRC_AGNT_CLIENT_ID,
exp_TRIM_SRC_PARAM_FIELDS.out_AGNT_NM_DESC as AGNT_NM_DESC,
CASE WHEN LKP_AGNT_NAME_LKUP.AGNT_CLIENT_ID IS NULL THEN ''NEW'' ELSE CASE WHEN CASE WHEN exp_TRIM_SRC_PARAM_FIELDS.AGNT_CLIENT_ID IS NULL THEN ''~'' ELSE exp_TRIM_SRC_PARAM_FIELDS.AGNT_CLIENT_ID END <> CASE WHEN LKP_AGNT_NAME_LKUP.SRC_AGNT_CLIENT_ID IS NULL THEN ''~'' ELSE LKP_AGNT_NAME_LKUP.SRC_AGNT_CLIENT_ID END OR CASE WHEN exp_TRIM_SRC_PARAM_FIELDS.out_AGNT_NM_DESC IS NULL THEN ''~'' ELSE exp_TRIM_SRC_PARAM_FIELDS.out_AGNT_NM_DESC END <> CASE WHEN LKP_AGNT_NAME_LKUP.AGNT_NM_DESC IS NULL THEN ''~'' ELSE LKP_AGNT_NAME_LKUP.AGNT_NM_DESC END THEN ''UPD'' ELSE ''REJ'' END END as out_CHK,
exp_TRIM_SRC_PARAM_FIELDS.source_record_id
FROM
exp_TRIM_SRC_PARAM_FIELDS
INNER JOIN MPLT_LKP_ECTL_BATCH_PRGM_VALIDATION_core mplt_LKP_ECTL_BATCH_PRGM_VALIDATION ON exp_TRIM_SRC_PARAM_FIELDS.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.source_record_id
INNER JOIN LKP_AGNT_NAME_LKUP ON mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.source_record_id = LKP_AGNT_NAME_LKUP.source_record_id
);


-- Component rtr_INS_UPD_REJ_AGNT_NAME_LKUP_INSERT, Type ROUTER Output Group INSERT
create or replace temp table RTR_INS_UPD_REJ_AGNT_NAME_LKUP_INSERT as
SELECT
exp_SET_VAR_CHK.AGNT_CLIENT_ID as AGNT_CLIENT_ID,
exp_SET_VAR_CHK.SRC_AGNT_CLIENT_ID as SRC_AGNT_CLIENT_ID,
exp_SET_VAR_CHK.AGNT_NM_DESC as AGNT_NM_DESC,
exp_SET_VAR_CHK.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_SET_VAR_CHK.ECTL_SRC_ID as ECTL_SRC_ID,
exp_SET_VAR_CHK.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_SET_VAR_CHK.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_SET_VAR_CHK.ORIG_INS_TS as ORIG_INS_TS,
exp_SET_VAR_CHK.out_CHK as out_CHK,
exp_SET_VAR_CHK.source_record_id
FROM
exp_SET_VAR_CHK
WHERE exp_SET_VAR_CHK.AGNT_CLIENT_ID IS NOT NULL and exp_SET_VAR_CHK.out_CHK = ''NEW'';


-- Component rtr_INS_UPD_REJ_AGNT_NAME_LKUP_UPDATE, Type ROUTER Output Group UPDATE
create or replace temp table rtr_INS_UPD_REJ_AGNT_NAME_LKUP_UPDATE as
SELECT
exp_SET_VAR_CHK.AGNT_CLIENT_ID as AGNT_CLIENT_ID,
exp_SET_VAR_CHK.SRC_AGNT_CLIENT_ID as SRC_AGNT_CLIENT_ID,
exp_SET_VAR_CHK.AGNT_NM_DESC as AGNT_NM_DESC,
exp_SET_VAR_CHK.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_SET_VAR_CHK.ECTL_SRC_ID as ECTL_SRC_ID,
exp_SET_VAR_CHK.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_SET_VAR_CHK.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_SET_VAR_CHK.ORIG_INS_TS as ORIG_INS_TS,
exp_SET_VAR_CHK.out_CHK as out_CHK,
exp_SET_VAR_CHK.source_record_id
FROM
exp_SET_VAR_CHK
WHERE exp_SET_VAR_CHK.AGNT_CLIENT_ID IS NOT NULL and exp_SET_VAR_CHK.out_CHK = ''UPD'';


-- Component AGNT_NAME_LKUP_INS, Type TARGET 
INSERT INTO DB_T_SHRD_PROD.AGNT_NAME_LKUP
(
AGNT_CLIENT_ID,
SRC_AGNT_CLIENT_ID,
AGNT_NM_DESC,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_ORIG_INS_TS,
ECTL_BATCH_ID,
ECTL_PRGM_ID
)
SELECT
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_INSERT.AGNT_CLIENT_ID as AGNT_CLIENT_ID,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_INSERT.SRC_AGNT_CLIENT_ID as SRC_AGNT_CLIENT_ID,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_INSERT.AGNT_NM_DESC as AGNT_NM_DESC,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_INSERT.ECTL_SRC_ID as ECTL_SRC_ID,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_INSERT.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_INSERT.ORIG_INS_TS as ECTL_ORIG_INS_TS,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_INSERT.ECTL_BATCH_ID as ECTL_BATCH_ID,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_INSERT.ECTL_PRGM_ID as ECTL_PRGM_ID
FROM
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_INSERT;


-- Component upd_AGNT_NAME_LKUP, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_AGNT_NAME_LKUP AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_UPDATE.AGNT_CLIENT_ID as AGNT_CLIENT_ID,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_UPDATE.SRC_AGNT_CLIENT_ID as SRC_AGNT_CLIENT_ID,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_UPDATE.AGNT_NM_DESC as AGNT_NM_DESC,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_UPDATE.ECTL_PRGM_ID as ECTL_PRGM_ID,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_UPDATE.ECTL_SRC_ID as ECTL_SRC_ID,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_UPDATE.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_UPDATE.ECTL_BATCH_ID as ECTL_BATCH_ID,
1 as UPDATE_STRATEGY_ACTION
FROM
rtr_INS_UPD_REJ_AGNT_NAME_LKUP_UPDATE
);


-- Component AGNT_NAME_LKUP_UPD, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_SHRD_PROD.AGNT_NAME_LKUP
USING upd_AGNT_NAME_LKUP ON (UPDATE_STRATEGY_ACTION = 1 AND AGNT_NAME_LKUP.AGNT_CLIENT_ID = upd_AGNT_NAME_LKUP.AGNT_CLIENT_ID AND AGNT_NAME_LKUP.ECTL_SRC_ID = upd_AGNT_NAME_LKUP.ECTL_SRC_ID)
WHEN MATCHED THEN UPDATE
SET
SRC_AGNT_CLIENT_ID = upd_AGNT_NAME_LKUP.SRC_AGNT_CLIENT_ID,
AGNT_NM_DESC = upd_AGNT_NAME_LKUP.AGNT_NM_DESC,
ECTL_SRC_INST_ID = upd_AGNT_NAME_LKUP.ECTL_SRC_INST_ID,
ECTL_BATCH_ID = upd_AGNT_NAME_LKUP.ECTL_BATCH_ID,
ECTL_PRGM_ID = upd_AGNT_NAME_LKUP.ECTL_PRGM_ID
;


END; ';