-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_CAT_CD_LOOKUP("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE PMMAPPINGNAME varchar;
BATCH_ACTIVE_IND varchar;
ACT_PROJ_ID varchar;
BEGIN 

PMMAPPINGNAME:='' ''; 
BATCH_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
ACT_PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 

-- Component Shortcut_to_CAT_CD_LOOKUP_INS, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_SHRD_PROD.CAT_CD_LOOKUP;


-- Component SQ_Shortcut_to_STG_CAT_CD, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_STG_CAT_CD AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CAT_STATE,
$2 as CAT_CATCODE,
$3 as CAT_START_DT,
$4 as CAT_END_DT,
$5 as CAT_YEAR,
$6 as CAT_3CATCODE,
$7 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
STG_CAT_CD.CAT_STATE,
STG_CAT_CD.CAT_CATCODE,
STG_CAT_CD.CAT_START_DT,
STG_CAT_CD.CAT_END_DT,
STG_CAT_CD.CAT_YEAR,
STG_CAT_CD.CAT_3CATCODE
FROM DB_T_STAG_PROD.STG_CAT_CD
) SRC
)
);


-- Component exp_TRIM_SRC_PARAM_FIELDS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_TRIM_SRC_PARAM_FIELDS AS
(
SELECT
SQ_Shortcut_to_STG_CAT_CD.CAT_START_DT as in_CAT_START_DT,
SQ_Shortcut_to_STG_CAT_CD.CAT_END_DT as in_CAT_END_DT,
SQ_Shortcut_to_STG_CAT_CD.CAT_YEAR as in_CAT_YEAR,
LTRIM ( RTRIM ( SQ_Shortcut_to_STG_CAT_CD.CAT_STATE ) ) as var_CAT_STATE,
LTRIM ( RTRIM ( SQ_Shortcut_to_STG_CAT_CD.CAT_CATCODE ) ) as var_CAT_CATCODE,
LTRIM ( RTRIM ( SQ_Shortcut_to_STG_CAT_CD.CAT_YEAR ) ) as var_CAT_YEAR,
LTRIM ( RTRIM ( SQ_Shortcut_to_STG_CAT_CD.CAT_3CATCODE ) ) as var_CAT_3CATCODE,
var_CAT_STATE as out_CAT_STATE,
var_CAT_CATCODE as out_CAT_CATCODE,
var_CAT_3CATCODE as out_CAT_3CATCODE,
:PMMappingName as out_PRGM_NM,
:ACT_PROJ_ID as out_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
:ACT_PROJ_ID as IN_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as IN_BATCH_ACTIVE_IND,
''m_STG_FIN_CLM'' IN_PRGM_NM,
null IN_TABLE_NM,
SQ_Shortcut_to_STG_CAT_CD.source_record_id
FROM
SQ_Shortcut_to_STG_CAT_CD
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_core(''exp_TRIM_SRC_PARAM_FIELDS'');



-- Component exp_SET_VAR_CHK, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_SET_VAR_CHK AS
(
SELECT
exp_TRIM_SRC_PARAM_FIELDS.out_CAT_STATE as in_CAT_STATE,
exp_TRIM_SRC_PARAM_FIELDS.out_CAT_CATCODE as in_CAT_CATCODE,
exp_TRIM_SRC_PARAM_FIELDS.in_CAT_START_DT as in_CAT_START_DT,
exp_TRIM_SRC_PARAM_FIELDS.in_CAT_END_DT as in_CAT_END_DT,
exp_TRIM_SRC_PARAM_FIELDS.in_CAT_YEAR as in_CAT_YEAR,
exp_TRIM_SRC_PARAM_FIELDS.out_CAT_3CATCODE as in_CAT_3CATCODE,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ORIG_INS_TS as out_ORIG_INS_TS,
exp_TRIM_SRC_PARAM_FIELDS.source_record_id
FROM
exp_TRIM_SRC_PARAM_FIELDS
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_core mplt_LKP_ECTL_BATCH_PRGM_VALIDATION ON exp_TRIM_SRC_PARAM_FIELDS.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.source_record_id
);


-- Component Shortcut_to_CAT_CD_LOOKUP_INS, Type TARGET 
INSERT INTO DB_T_SHRD_PROD.CAT_CD_LOOKUP
(
CAT_STATE,
CAT_CATCODE,
CAT_START_DT,
CAT_END_DT,
CAT_YEAR,
CAT_3CATCODE,
ECTL_PRGM_ID,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_BATCH_ID,
ECTL_ORIG_INS_TS
)
SELECT
exp_SET_VAR_CHK.in_CAT_STATE as CAT_STATE,
exp_SET_VAR_CHK.in_CAT_CATCODE as CAT_CATCODE,
exp_SET_VAR_CHK.in_CAT_START_DT as CAT_START_DT,
exp_SET_VAR_CHK.in_CAT_END_DT as CAT_END_DT,
exp_SET_VAR_CHK.in_CAT_YEAR as CAT_YEAR,
exp_SET_VAR_CHK.in_CAT_3CATCODE as CAT_3CATCODE,
exp_SET_VAR_CHK.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_SET_VAR_CHK.out_ECTL_SRC_ID as ECTL_SRC_ID,
exp_SET_VAR_CHK.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_SET_VAR_CHK.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_SET_VAR_CHK.out_ORIG_INS_TS as ECTL_ORIG_INS_TS
FROM
exp_SET_VAR_CHK;


END; ';