-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_SVC_NM_LKUP("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE 

PMMAPPINGNAME varchar;
BATCH_ACTIVE_IND varchar;
ACT_PROJ_ID varchar;

BEGIN 

PMMAPPINGNAME:=''m_SVC_NM_LKUP''; 
BATCH_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
ACT_PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 

-- Component sq_STG_SERVICE_CENTER_NAME, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_SERVICE_CENTER_NAME AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_NO,
$2 as SC_NAME,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT DISTINCT SC_NO, SC_NAME 
FROM
 DB_T_STAG_PROD.STG_SERVICE_CENTER_NAME
) SRC
)
);


-- Component exp_TRIM_SRC_PARAM_FIELDS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_TRIM_SRC_PARAM_FIELDS AS
(
SELECT
LTRIM ( RTRIM ( sq_STG_SERVICE_CENTER_NAME.SC_NO ) ) as var_SVC_NM_CD,
var_SVC_NM_CD as out_SVC_NM_CD,
LTRIM ( RTRIM ( sq_STG_SERVICE_CENTER_NAME.SC_NAME ) ) as var_SVC_NM_DESC,
CASE WHEN ( var_SVC_NM_DESC IS NULL OR length ( var_SVC_NM_DESC ) = 0 ) THEN var_SVC_NM_CD ELSE var_SVC_NM_DESC END as out_SVC_NM_DESC,
:PMMappingName as out_PRGM_NM,
:ACT_PROJ_ID as out_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
:ACT_PROJ_ID as IN_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as IN_BATCH_ACTIVE_IND,
''m_STG_FIN_CLM'' IN_PRGM_NM,
null IN_TABLE_NM,
sq_STG_SERVICE_CENTER_NAME.source_record_id
FROM
sq_STG_SERVICE_CENTER_NAME
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_core(''exp_TRIM_SRC_PARAM_FIELDS'');


-- Component LKP_SVC_NM_LKUP, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_SVC_NM_LKUP AS
(
SELECT
LKP.SRC_SVC_NM_CD,
LKP.SVC_NM_DESC,
LKP.SVC_NM_CD,
exp_TRIM_SRC_PARAM_FIELDS.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_TRIM_SRC_PARAM_FIELDS.source_record_id ORDER BY LKP.SRC_SVC_NM_CD asc,LKP.SVC_NM_DESC asc,LKP.SVC_NM_CD asc) RNK
FROM
exp_TRIM_SRC_PARAM_FIELDS
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_core mplt_LKP_ECTL_BATCH_PRGM_VALIDATION ON exp_TRIM_SRC_PARAM_FIELDS.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.source_record_id
LEFT JOIN (
SELECT SVC_NM_LKUP.SRC_SVC_NM_CD as SRC_SVC_NM_CD, LTRIM(RTRIM(SVC_NM_LKUP.SVC_NM_DESC)) as SVC_NM_DESC, SVC_NM_LKUP.SVC_NM_CD as SVC_NM_CD, SVC_NM_LKUP.ECTL_SRC_ID as ECTL_SRC_ID FROM DB_T_SHRD_PROD.SVC_NM_LKUP
) LKP ON LKP.SVC_NM_CD = exp_TRIM_SRC_PARAM_FIELDS.out_SVC_NM_CD AND LKP.ECTL_SRC_ID = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_SRC_ID
QUALIFY RNK = 1
);


-- Component exp_SET_VAR_CHK, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_SET_VAR_CHK AS
(
SELECT
exp_TRIM_SRC_PARAM_FIELDS.out_SVC_NM_CD as SVC_NM_CD,
exp_TRIM_SRC_PARAM_FIELDS.out_SVC_NM_CD as SRC_SVC_NM_CD,
exp_TRIM_SRC_PARAM_FIELDS.out_SVC_NM_DESC as SVC_NM_DESC,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_SRC_ID as ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.out_ORIG_INS_TS as ORIG_INS_TS,
CASE WHEN LKP_SVC_NM_LKUP.SVC_NM_CD IS NULL THEN ''NEW'' ELSE CASE WHEN CASE WHEN exp_TRIM_SRC_PARAM_FIELDS.out_SVC_NM_CD IS NULL THEN ''~'' ELSE exp_TRIM_SRC_PARAM_FIELDS.out_SVC_NM_CD END <> CASE WHEN LKP_SVC_NM_LKUP.SRC_SVC_NM_CD IS NULL THEN ''~'' ELSE LKP_SVC_NM_LKUP.SRC_SVC_NM_CD END OR CASE WHEN exp_TRIM_SRC_PARAM_FIELDS.out_SVC_NM_DESC IS NULL THEN ''~'' ELSE exp_TRIM_SRC_PARAM_FIELDS.out_SVC_NM_DESC END <> CASE WHEN LKP_SVC_NM_LKUP.SVC_NM_DESC IS NULL THEN ''~'' ELSE LKP_SVC_NM_LKUP.SVC_NM_DESC END THEN ''UPD'' ELSE ''REJ'' END END as out_CHK,
exp_TRIM_SRC_PARAM_FIELDS.source_record_id
FROM
exp_TRIM_SRC_PARAM_FIELDS
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_core mplt_LKP_ECTL_BATCH_PRGM_VALIDATION ON exp_TRIM_SRC_PARAM_FIELDS.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.source_record_id
INNER JOIN LKP_SVC_NM_LKUP ON mplt_LKP_ECTL_BATCH_PRGM_VALIDATION.source_record_id = LKP_SVC_NM_LKUP.source_record_id
);


-- Component rtr_INS_UPD_REJ_SVC_NM_LKUP_INSERT, Type ROUTER Output Group INSERT
create or replace temp table RTR_INS_UPD_REJ_SVC_NM_LKUP_INSERT as
SELECT
exp_SET_VAR_CHK.SVC_NM_CD as SVC_NM_CD,
exp_SET_VAR_CHK.SRC_SVC_NM_CD as SRC_SVC_NM_CD,
exp_SET_VAR_CHK.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_SET_VAR_CHK.ECTL_SRC_ID as ECTL_SRC_ID,
exp_SET_VAR_CHK.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_SET_VAR_CHK.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_SET_VAR_CHK.ORIG_INS_TS as ORIG_INS_TS,
exp_SET_VAR_CHK.SVC_NM_DESC as SVC_NM_DESC,
exp_SET_VAR_CHK.out_CHK as out_CHK,
exp_SET_VAR_CHK.source_record_id
FROM
exp_SET_VAR_CHK
WHERE exp_SET_VAR_CHK.out_CHK = ''NEW'';


-- Component rtr_INS_UPD_REJ_SVC_NM_LKUP_UPDATE, Type ROUTER Output Group UPDATE
create or replace temp table RTR_INS_UPD_REJ_SVC_NM_LKUP_UPDATE as
SELECT
exp_SET_VAR_CHK.SVC_NM_CD as SVC_NM_CD,
exp_SET_VAR_CHK.SRC_SVC_NM_CD as SRC_SVC_NM_CD,
exp_SET_VAR_CHK.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_SET_VAR_CHK.ECTL_SRC_ID as ECTL_SRC_ID,
exp_SET_VAR_CHK.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_SET_VAR_CHK.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_SET_VAR_CHK.ORIG_INS_TS as ORIG_INS_TS,
exp_SET_VAR_CHK.SVC_NM_DESC as SVC_NM_DESC,
exp_SET_VAR_CHK.out_CHK as out_CHK,
exp_SET_VAR_CHK.source_record_id
FROM
exp_SET_VAR_CHK
WHERE exp_SET_VAR_CHK.out_CHK = ''UPD'';


-- Component upd_SVC_NM_LKUP, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_SVC_NM_LKUP AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
rtr_INS_UPD_REJ_SVC_NM_LKUP_UPDATE.SVC_NM_CD as SVC_NM_CD,
rtr_INS_UPD_REJ_SVC_NM_LKUP_UPDATE.SRC_SVC_NM_CD as SRC_SVC_NM_CD,
rtr_INS_UPD_REJ_SVC_NM_LKUP_UPDATE.ECTL_PRGM_ID as ECTL_PRGM_ID,
rtr_INS_UPD_REJ_SVC_NM_LKUP_UPDATE.ECTL_SRC_ID as ECTL_SRC_ID,
rtr_INS_UPD_REJ_SVC_NM_LKUP_UPDATE.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
rtr_INS_UPD_REJ_SVC_NM_LKUP_UPDATE.ECTL_BATCH_ID as ECTL_BATCH_ID,
rtr_INS_UPD_REJ_SVC_NM_LKUP_UPDATE.SVC_NM_DESC as SVC_NM_DESC,
1 as UPDATE_STRATEGY_ACTION
FROM
rtr_INS_UPD_REJ_SVC_NM_LKUP_UPDATE
);


-- Component SVC_NM_LKUP_UPD, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_SHRD_PROD.SVC_NM_LKUP
USING upd_SVC_NM_LKUP
ON (DB_T_SHRD_PROD.SVC_NM_LKUP.SVC_NM_CD = upd_SVC_NM_LKUP.SVC_NM_CD)
WHEN MATCHED THEN UPDATE SET
SVC_NM_CD = upd_SVC_NM_LKUP.SVC_NM_CD, SRC_SVC_NM_CD = upd_SVC_NM_LKUP.SRC_SVC_NM_CD, SVC_NM_DESC = upd_SVC_NM_LKUP.SVC_NM_DESC, ECTL_SRC_ID = upd_SVC_NM_LKUP.ECTL_SRC_ID, ECTL_SRC_INST_ID = upd_SVC_NM_LKUP.ECTL_SRC_INST_ID, ECTL_BATCH_ID = upd_SVC_NM_LKUP.ECTL_BATCH_ID, ECTL_PRGM_ID = upd_SVC_NM_LKUP.ECTL_PRGM_ID;


-- Component SVC_NM_LKUP_INS, Type TARGET 
INSERT INTO DB_T_SHRD_PROD.SVC_NM_LKUP
(
SVC_NM_CD,
SRC_SVC_NM_CD,
SVC_NM_DESC,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_ORIG_INS_TS,
ECTL_BATCH_ID,
ECTL_PRGM_ID
)
SELECT
rtr_INS_UPD_REJ_SVC_NM_LKUP_INSERT.SVC_NM_CD as SVC_NM_CD,
rtr_INS_UPD_REJ_SVC_NM_LKUP_INSERT.SRC_SVC_NM_CD as SRC_SVC_NM_CD,
rtr_INS_UPD_REJ_SVC_NM_LKUP_INSERT.SVC_NM_DESC as SVC_NM_DESC,
rtr_INS_UPD_REJ_SVC_NM_LKUP_INSERT.ECTL_SRC_ID as ECTL_SRC_ID,
rtr_INS_UPD_REJ_SVC_NM_LKUP_INSERT.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
rtr_INS_UPD_REJ_SVC_NM_LKUP_INSERT.ORIG_INS_TS as ECTL_ORIG_INS_TS,
rtr_INS_UPD_REJ_SVC_NM_LKUP_INSERT.ECTL_BATCH_ID as ECTL_BATCH_ID,
rtr_INS_UPD_REJ_SVC_NM_LKUP_INSERT.ECTL_PRGM_ID as ECTL_PRGM_ID
FROM
rtr_INS_UPD_REJ_SVC_NM_LKUP_INSERT;


END; ';