-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STG_BENFIELD_BASE_INFO("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component LKPTRANS, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKPTRANS AS
(
SELECT  DAILY_FEED_IND AS DAILY_FEED_IND_LKP, max(CYC_END_DT) AS CYC_END_DT_LKP FROM DB_T_CTRL_PROD.ECTL_MISPREM_HEADER GROUP BY DAILY_FEED_IND_LKP /*  */
);


-- PIPELINE START FOR 1
-- Component TGT_DUMMY1, Type Pre SQL 
DELETE FROM DB_T_STAG_PROD.STG_BENFIELD_BASE_INFO;


-- Component SQ_STG_BENFIELD_BASE_INFO, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_STG_BENFIELD_BASE_INFO AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as DUMMY,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT COUNT(*) AS DUMMY FROM DB_T_STAG_PROD.STG_BENFIELD_BASE_INFO
) SRC
)
);


-- Component FILTRANS, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE FILTRANS AS
(
SELECT
SQ_STG_BENFIELD_BASE_INFO.DUMMY as DUMMY,
SQ_STG_BENFIELD_BASE_INFO.source_record_id
FROM
SQ_STG_BENFIELD_BASE_INFO
WHERE SQ_STG_BENFIELD_BASE_INFO.DUMMY >0--= ''A''
);


-- Component TGT_DUMMY1, Type TARGET 

CREATE OR REPLACE TEMPORARY TABLE TGT_DUMMY1 AS

(
SELECT
FILTRANS.DUMMY as DUMMY
FROM
FILTRANS);


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_BENFIELD_BASE_INFO_SRC, Type TABLE_DDL Creating an empty table
CREATE OR REPLACE TEMPORARY TABLE SQ_BENFIELD_BASE_INFO
(
COMP_CODE varchar(1),
POLICY_NBR varchar(15),
LOB_CODE varchar(2),
STATE_NBR varchar(2),
CNTY_NBR varchar(3),
CITY_NAME varchar(30),
ZIP_CODE varchar(5),
STREET_ADDRESS varchar(37),
PREMIUM_AMT varchar(12),
POL_LIMIT varchar(12),
DEDUCT_AMT varchar(10),
BLDG_LIMIT varchar(12),
OTHR_STR_LIMIT varchar(12),
CONTENTS_LIMIT varchar(12),
CONTENTS_GRADE varchar(1),
LOSS_OF_USE varchar(12),
INS_TO_VALUE varchar(3),
NBR_STORIES varchar(2),
YEAR_BUILT varchar(4),
OCCUPANCY_TYPE varchar(2),
CONSTR_CLASS varchar(2),
RATING_ZONE varchar(2),
source_record_id number autoincrement start 1 increment 1
);


-- Component SQ_BENFIELD_BASE_INFO_SRC, Type IMPORT_DATA Importing Data
;


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_BENFIELD_BASE_INFO.COMP_CODE as COMP_CODE,
SQ_BENFIELD_BASE_INFO.POLICY_NBR as POLICY_NBR,
SQ_BENFIELD_BASE_INFO.LOB_CODE as LOB_CODE,
SQ_BENFIELD_BASE_INFO.STATE_NBR as STATE_NBR,
SQ_BENFIELD_BASE_INFO.CNTY_NBR as CNTY_NBR,
SQ_BENFIELD_BASE_INFO.CITY_NAME as CITY_NAME,
SQ_BENFIELD_BASE_INFO.ZIP_CODE as ZIP_CODE,
SQ_BENFIELD_BASE_INFO.STREET_ADDRESS as STREET_ADDRESS,
SQ_BENFIELD_BASE_INFO.PREMIUM_AMT as PREMIUM_AMT,
SQ_BENFIELD_BASE_INFO.POL_LIMIT as POL_LIMIT,
SQ_BENFIELD_BASE_INFO.DEDUCT_AMT as DEDUCT_AMT,
SQ_BENFIELD_BASE_INFO.BLDG_LIMIT as BLDG_LIMIT,
SQ_BENFIELD_BASE_INFO.OTHR_STR_LIMIT as OTHR_STR_LIMIT,
SQ_BENFIELD_BASE_INFO.CONTENTS_LIMIT as CONTENTS_LIMIT,
SQ_BENFIELD_BASE_INFO.CONTENTS_GRADE as CONTENTS_GRADE,
SQ_BENFIELD_BASE_INFO.LOSS_OF_USE as LOSS_OF_USE,
SQ_BENFIELD_BASE_INFO.INS_TO_VALUE as INS_TO_VALUE,
SQ_BENFIELD_BASE_INFO.NBR_STORIES as NBR_STORIES,
SQ_BENFIELD_BASE_INFO.YEAR_BUILT as YEAR_BUILT,
SQ_BENFIELD_BASE_INFO.OCCUPANCY_TYPE as OCCUPANCY_TYPE,
SQ_BENFIELD_BASE_INFO.CONSTR_CLASS as CONSTR_CLASS,
SQ_BENFIELD_BASE_INFO.RATING_ZONE as RATING_ZONE,
LKP_1.CYC_END_DT_LKP /* replaced lookup LKPTRANS */ as v_FEED_DT,
TO_DATE ( v_FEED_DT , ''YYYY-MM-DD'' ) as FEED_DT,
SQ_BENFIELD_BASE_INFO.source_record_id,
row_number() over (partition by SQ_BENFIELD_BASE_INFO.source_record_id order by SQ_BENFIELD_BASE_INFO.source_record_id) as RNK
FROM
SQ_BENFIELD_BASE_INFO
LEFT JOIN LKPTRANS LKP_1 ON LKP_1.DAILY_FEED_IND_LKP = ''M''
QUALIFY RNK = 1
);


-- Component STG_BENFIELD_BASE_INFO, Type TARGET 
INSERT INTO DB_T_STAG_PROD.STG_BENFIELD_BASE_INFO
(
COMP_CODE,
POLICY_NBR,
LOB_CODE,
STATE_NBR,
CNTY_NBR,
CITY_NAME,
ZIP_CODE,
STREET_ADDRESS,
PREMIUM_AMT,
POL_LIMIT,
DEDUCT_AMT,
BLDG_LIMIT,
OTHR_STR_LIMIT,
CONTENTS_LIMIT,
CONTENTS_GRADE,
LOSS_OF_USE,
INS_TO_VALUE,
NBR_STORIES,
YEAR_BUILT,
OCCUPANCY_TYPE,
CONSTR_CLASS,
RATING_ZONE,
FEED_DT
)
SELECT
EXPTRANS.COMP_CODE as COMP_CODE,
EXPTRANS.POLICY_NBR as POLICY_NBR,
EXPTRANS.LOB_CODE as LOB_CODE,
EXPTRANS.STATE_NBR as STATE_NBR,
EXPTRANS.CNTY_NBR as CNTY_NBR,
EXPTRANS.CITY_NAME as CITY_NAME,
EXPTRANS.ZIP_CODE as ZIP_CODE,
EXPTRANS.STREET_ADDRESS as STREET_ADDRESS,
EXPTRANS.PREMIUM_AMT as PREMIUM_AMT,
EXPTRANS.POL_LIMIT as POL_LIMIT,
EXPTRANS.DEDUCT_AMT as DEDUCT_AMT,
EXPTRANS.BLDG_LIMIT as BLDG_LIMIT,
EXPTRANS.OTHR_STR_LIMIT as OTHR_STR_LIMIT,
EXPTRANS.CONTENTS_LIMIT as CONTENTS_LIMIT,
EXPTRANS.CONTENTS_GRADE as CONTENTS_GRADE,
EXPTRANS.LOSS_OF_USE as LOSS_OF_USE,
EXPTRANS.INS_TO_VALUE as INS_TO_VALUE,
EXPTRANS.NBR_STORIES as NBR_STORIES,
EXPTRANS.YEAR_BUILT as YEAR_BUILT,
EXPTRANS.OCCUPANCY_TYPE as OCCUPANCY_TYPE,
EXPTRANS.CONSTR_CLASS as CONSTR_CLASS,
EXPTRANS.RATING_ZONE as RATING_ZONE,
EXPTRANS.FEED_DT as FEED_DT
FROM
EXPTRANS;


-- PIPELINE END FOR 2

END; ';