-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_FIN_AGG_PREMIUM_INFO_QTD("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
WF_MONTH_ID  integer;
BEGIN 
WF_MONTH_ID :=1;
-- Component SQ_AGG_PREMIUM, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_PREMIUM AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MO_ID,
$2 as CMPY_CD,
$3 as ST_CD,
$4 as RSV_GRP,
$5 as LOB_CD,
$6 as PRODUCT_CD,
$7 as PRODUCT_DESC,
$8 as ACCTNG_MO,
$9 as ACCTNG_YR,
$10 as ACCTNG_QT,
$11 as CAT,
$12 as POOL_CD,
$13 as POOL_DESC,
$14 as MONETARY_AMT,
$15 as TOT_PREM_AMT,
$16 as ACCT_NBR,
$17 as GL_ACCT_DESC,
$18 as GL_ACCT_GRP,
$19 as LEDGER,
$20 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT	FP.MO_ID,FP.CMPY_CD,FP.ST_CD, RSV_GRP,FP.LOB_CD,

	FP.PRODUCT_CD,

	COV_DESC,ACCTNG_MO,ACCTNG_YR,CASE

  	 WHEN ACCTNG_MO IN (1,2,3) THEN 1 

 	 WHEN ACCTNG_MO IN (4,5,6) THEN 2 

 	 WHEN ACCTNG_MO IN (7,8,9) THEN 3 

 	 WHEN ACCTNG_MO IN (10,11,12) THEN 4 

  	END  ACCTNG_QT, 

	CASE WHEN SUBSTR(FP.POOL_CD,1,3)=''CAT'' THEN ''CAT'' 

	 ELSE	''NonCAT'' 

	END CAT,

	FP.POOL_CD,POOL_DESC,SUM(MONETARY_AMT) ,

	SUM(TOT_PREM_AMT) ,FP.ACCT_NBR,ACT.ACCT_DESC,METRIC_LONG_NM ,LEDGER 

FROM	(

	SELECT	FP.MO_ID,FP.CMPY_CD,FP.ST_CD,LOB_CD,FP.PRODUCT_CD,

		ACCTNG_MO,ACCTNG_YR,FP.POOL_CD,SUM(MONETARY_AMT) MONETARY_AMT ,

		SUM(TOT_PREM_AMT) TOT_PREM_AMT,FP.ACCT_NBR,LEDGER 

	FROM	DB_T_CORE_FIN_PROD.FIN_PREMIUM_TXN FP 

	WHERE	MO_ID=:WF_MONTH_ID

	GROUP	BY FP.MO_ID,FP.CMPY_CD,FP.ST_CD,LOB_CD,FP.PRODUCT_CD,ACCTNG_MO,ACCTNG_YR,FP.POOL_CD,FP.ACCT_NBR,LEDGER

	) FP

LEFT OUTER JOIN  DB_T_CORE_FIN_PROD.FIN_PRODUCT_HIER  DEVT 

ON FP.PRODUCT_CD=DEVT.PRODUCT_CD LEFT OUTER JOIN  (SELECT DISTINCT POOL_CD,POOL_DESC FROM DB_T_SHRD_FIN_PROD.FIN_POOL_CD_LKUP) PL

ON FP.POOL_CD=PL.POOL_CD LEFT OUTER JOIN    DB_T_STAG_FIN_PROD.FIN_ACCT_NBR_GRP_LKUP  ACCT 

ON FP.ACCT_NBR=ACCT.ACCT_NBR LEFT OUTER JOIN  (SELECT ACCT_NBR,ACCT_DESC FROM DB_T_SHRD_FIN_PROD.FIN_ACCT_NBR_LKUP  

	QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCT_NBR ORDER BY  EFF_DT DESC)=1)ACT

ON ACCT.ACCT_NBR=ACT.ACCT_NBR 	 LEFT JOIN   (select  distinct  source, product_cd , PRC_GRP, CMPY_CD ,  RSV_GRP                                                                     		

        FROM   DB_T_SHRD_FIN_PROD.RSV_GRP_LKUP		

        QUALIFY ROW_NUMBER() OVER( PARTITION BY  product_cd , CMPY_CD   ORDER BY source ) = 1)  RSV ON FP.CMPY_CD=RSV.CMPY_CD AND FP.PRODUCT_CD=RSV.PRODUCT_CD		



	

GROUP BY FP.MO_ID,FP.CMPY_CD,FP.ST_CD,RSV_GRP,FP.LOB_CD,FP.PRODUCT_CD,COV_DESC,ACCTNG_MO,ACCTNG_YR,ACCTNG_QT,CAT,FP.POOL_CD,POOL_DESC,FP.ACCT_NBR,METRIC_LONG_NM,ACT.ACCT_DESC,LEDGER
) SRC
)
);


-- Component exp_passthrough, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_passthrough AS
(
SELECT
SQ_AGG_PREMIUM.MO_ID as MO_ID,
SQ_AGG_PREMIUM.CMPY_CD as CMPY_CD,
SQ_AGG_PREMIUM.ST_CD as ST_CD,
SQ_AGG_PREMIUM.RSV_GRP as RSV_GRP,
SQ_AGG_PREMIUM.LOB_CD as LOB_CD,
SQ_AGG_PREMIUM.PRODUCT_CD as PRODUCT_CD,
SQ_AGG_PREMIUM.PRODUCT_DESC as PRODUCT_DESC,
SQ_AGG_PREMIUM.ACCTNG_MO as ACCTNG_MO,
SQ_AGG_PREMIUM.ACCTNG_YR as ACCTNG_YR,
SQ_AGG_PREMIUM.ACCTNG_QT as ACCTNG_QT,
SQ_AGG_PREMIUM.CAT as CAT,
SQ_AGG_PREMIUM.POOL_CD as POOL_CD,
SQ_AGG_PREMIUM.POOL_DESC as POOL_DESC,
SQ_AGG_PREMIUM.MONETARY_AMT as MONETARY_AMT,
SQ_AGG_PREMIUM.TOT_PREM_AMT as TOT_PREM_AMT,
SQ_AGG_PREMIUM.ACCT_NBR as ACCT_NBR,
SQ_AGG_PREMIUM.GL_ACCT_DESC as GL_ACCT_DESC,
SQ_AGG_PREMIUM.GL_ACCT_GRP as GL_ACCT_GRP,
SQ_AGG_PREMIUM.LEDGER as LEDGER,
TO_CHAR ( null ) as o_PROD_PLAN,
SQ_AGG_PREMIUM.source_record_id
FROM
SQ_AGG_PREMIUM
);


-- Component AGG_PREMIUM_INFO_QTD, Type TARGET 
INSERT INTO DB_T_CORE_FIN_PROD.AGG_PREMIUM_INFO_QTD
(
MO_ID,
CMPY_CD,
ST_CD,
RSV_GRP,
LOB_CD,
PRODUCT_CD,
PRODUCT_DESC,
ACCTNG_MO,
ACCTNG_YR,
ACCTNG_QT,
CAT,
POOL_CD,
POOL_DESC,
MONETARY_AMT,
TOT_PREM_AMT,
ACCT_NBR,
GL_ACCT_DESC,
GL_ACCT_GRP,
LEDGER,
PROD_PLAN
)
SELECT
exp_passthrough.MO_ID as MO_ID,
exp_passthrough.CMPY_CD as CMPY_CD,
exp_passthrough.ST_CD as ST_CD,
exp_passthrough.RSV_GRP as RSV_GRP,
exp_passthrough.LOB_CD as LOB_CD,
exp_passthrough.PRODUCT_CD as PRODUCT_CD,
exp_passthrough.PRODUCT_DESC as PRODUCT_DESC,
exp_passthrough.ACCTNG_MO as ACCTNG_MO,
exp_passthrough.ACCTNG_YR as ACCTNG_YR,
exp_passthrough.ACCTNG_QT as ACCTNG_QT,
exp_passthrough.CAT as CAT,
exp_passthrough.POOL_CD as POOL_CD,
exp_passthrough.POOL_DESC as POOL_DESC,
exp_passthrough.MONETARY_AMT as MONETARY_AMT,
exp_passthrough.TOT_PREM_AMT as TOT_PREM_AMT,
exp_passthrough.ACCT_NBR as ACCT_NBR,
exp_passthrough.GL_ACCT_DESC as GL_ACCT_DESC,
exp_passthrough.GL_ACCT_GRP as GL_ACCT_GRP,
exp_passthrough.LEDGER as LEDGER,
exp_passthrough.o_PROD_PLAN as PROD_PLAN
FROM
exp_passthrough;


END; ';