-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_POLICY_ALERTS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_POLICIES_BY_MEMBER, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_POLICIES_BY_MEMBER AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMBER_NUM,
$2 as POLICY_NUM,
$3 as ALERT_NUM,
$4 as ALERT_COUNT_DESC,
$5 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH rnt_table AS

(

	SELECT

		PLCY_NBR AS POLICY_NBR,

		COUNT(DISTINCT (CASE WHEN COMM_PLCY_CD IN (''A'') THEN PLCY_NBR END) ) AS PLCY_IFO_RNT_LS_EQ_10,

		COUNT(DISTINCT (CASE WHEN COMM_PLCY_CD IN (''B'') THEN PLCY_NBR END) ) AS PLCY_IFO_RNT_10_30,

		COUNT(DISTINCT (CASE WHEN COMM_PLCY_CD IN (''C'' ) THEN PLCY_NBR END) ) AS PLCY_IFO_RNT_31_60,

		COUNT(DISTINCT (CASE WHEN COMM_PLCY_CD IN (''D'' ) THEN PLCY_NBR END))  AS PLCY_IFO_RNT_61_180,

		COUNT(DISTINCT (CASE WHEN COMM_PLCY_CD IN (''E'' ) THEN PLCY_NBR END))  AS PLCY_IFO_RNT_GT_180,

		EFFECTIVE_DT AS EFF_DT

	FROM

		DB_T_CORE_PROD.PREMIUM_TRANS_DTL

	WHERE

		EFFECTIVE_DT >= ADD_MONTHS (CURRENT_DATE, -36)

	group by

		1,7

),

POL_VEH_LIB AS

(

	SELECT

		a.CLIENT_REF_NBR AS CLIENT_REF_NBR,

		a.REF_TYP_CD AS REF_TYP_CD,

		a.POL_NBR AS POL_NBR,

		a.EFFECTIVE_DT AS EFFECTIVE_DT,

		a.CMP_COV_IND AS CMP_COV_IND

	FROM

		DB_T_STAG_MEMBXREF_PROD.POL_VEH_LIST a

	WHERE

		CMP_COV_IND = ''N''

),

POL_VEH_CMP AS

(

	SELECT

		a.CLIENT_REF_NBR AS CLIENT_REF_NBR,

		a.REF_TYP_CD AS REF_TYP_CD,

		a.POL_NBR AS POL_NBR,

		a.EFFECTIVE_DT AS EFFECTIVE_DT,

		a.CMP_COV_IND AS CMP_COV_IND

	FROM

		DB_T_STAG_MEMBXREF_PROD.POL_VEH_LIST a

	WHERE

		CMP_COV_IND = ''Y''

),

CLIENT_CLAIMS AS

(

	SELECT DISTINCT

		FNOL.MEMBER_NUM AS MEMBER_NUM,

		QRY.CLM_CSR_CLAIM_NBR AS CSR_CLAIM_NUM,

		VANDALISM_CLAIMS AS VANDALISM_CLAIMS,

		PARKED_CLAIMS AS PARKED_CLAIMS,

		HIT_RUN_CLAIMS AS HIT_RUN_CLAIMS,

		PHANTOM_CLAIMS AS PHANTOM_CLAIMS,

		FIRE_CLAIMS AS FIRE_CLAIMS,

		THEFT_CLAIMS AS THEFT_CLAIMS,

		WIND_HALL_CLAIMS AS WIND_HALL_CLAIMS,

		ANIMAL_CLAIMS AS ANIMAL_CLAIMS

	FROM

		(

			SELECT

				CLT.CLIENT_ID,

				CTAB.CLM_CSR_CLAIM_NBR,

				CTAB.CLM_CAUSE_LOSS_CD,

				SUM(CASE WHEN CTAB.CLM_CAUSE_LOSS_CD=''A006'' THEN 1 ELSE 0 END) OVER (PARTITION BY CLT.CLIENT_ID) VANDALISM_CLAIMS,

				SUM(CASE WHEN CTAB.CLM_CAUSE_LOSS_CD=''A028'' THEN 1 ELSE 0 END) OVER (PARTITION BY CLT.CLIENT_ID) PARKED_CLAIMS,

				SUM(CASE WHEN CTAB.CLM_CAUSE_LOSS_CD IN (''A128'',''A129'') THEN 1 ELSE 0 END) OVER (PARTITION BY CLT.CLIENT_ID) HIT_RUN_CLAIMS,

				SUM(CASE WHEN CTAB.CLM_CAUSE_LOSS_CD=''A122'' THEN 1 ELSE 0 END) OVER (PARTITION BY CLT.CLIENT_ID) PHANTOM_CLAIMS,

				SUM(CASE WHEN CTAB.CLM_CAUSE_LOSS_CD=''A003'' THEN 1 ELSE 0 END) OVER (PARTITION BY CLT.CLIENT_ID) FIRE_CLAIMS,

				SUM(CASE WHEN CTAB.CLM_CAUSE_LOSS_CD=''A004'' THEN 1 ELSE 0 END) OVER (PARTITION BY CLT.CLIENT_ID) THEFT_CLAIMS,

				SUM(CASE WHEN CTAB.CLM_CAUSE_LOSS_CD=''A007'' THEN 1 ELSE 0 END) OVER (PARTITION BY CLT.CLIENT_ID) WIND_HALL_CLAIMS,

				SUM(CASE WHEN CTAB.CLM_CAUSE_LOSS_CD IN (''A025'',''A125'') THEN 1 ELSE 0 END) OVER (PARTITION BY CLT.CLIENT_ID) ANIMAL_CLAIMS

			FROM

				(

					SELECT DISTINCT

						CLM_CSR_CLAIM_NBR,

						CLM_CAUSE_LOSS_CD

					FROM

						DB_T_ONSITE_PROD.CLAIM_TAB

				) CTAB

				JOIN

					(

						SELECT DISTINCT

							CLIENT_ID,

							CIOR_SHW_OBJ_KEY AS CSR_CLAIM_NBR

						FROM

							DB_T_ONSITE_PROD.EX_CLT_OBJ_REL

						WHERE

							OBJ_CD=''CLM'' AND RLT_TYP_CD=''CLT'' AND CIOR_SHW_OBJ_KEY <> '' ''

					) CLT

					ON CTAB.CLM_CSR_CLAIM_NBR=CLT.CSR_CLAIM_NBR

			GROUP BY

				CLT.CLIENT_ID, CTAB.CLM_CSR_CLAIM_NBR, CTAB.CLM_CAUSE_LOSS_CD

		)QRY

		JOIN DB_T_STAG_MEMBXREF_PROD.FNOL_ADJ_REVIEW FNOL

			ON QRY.CLM_CSR_CLAIM_NBR=FNOL.CSR_CLAIM_NUM

	WHERE (VANDALISM_CLAIMS+ PARKED_CLAIMS+ HIT_RUN_CLAIMS+ PHANTOM_CLAIMS+ FIRE_CLAIMS+THEFT_CLAIMS+ WIND_HALL_CLAIMS+ANIMAL_CLAIMS)<>0

)



SELECT DISTINCT

	cast(MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

	cast('''' as varchar(25)) AS POLICY_NUM,

	cast(1 as integer) AS ALERT_NUM,

	cast('''' as varchar(35)) AS ALERT_COUNT_DESC

FROM

	DB_T_STAG_MEMBXREF_PROD.POLICY_TYPE_BY_CUSTOMER

WHERE

	AUTO_POLS = 0



UNION ALL



SELECT DISTINCT

	cast(MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

	cast(POLICY_NUM as varchar(25)) AS POLICY_NUM,

	cast(2 as integer) AS ALERT_NUM,

	cast('''' as varchar(35)) AS ALERT_COUNT_DESC 

FROM

	DB_T_STAG_MEMBXREF_PROD.POLICIES_BY_MEMBER

WHERE

	SUBSTR(POLICY_NUM,1,2) = ''GL''



UNION ALL



SELECT DISTINCT

	cast(A.MEMB as varchar(8)) AS MEMBER_NUM,  

	cast(A.PLCY_NBR as varchar(25)) AS POLICY_NUM,

	cast(3 as integer) ALERT_NUM,

	cast('''' as varchar(35)) AS ALERT_COUNT_DESC

FROM

	(

		SELECT DISTINCT

			a.PLCY_NBR,

			a.ROOF_YR_CY,

			a.exp_dt,

			(extract (year  from current_date)-1) - (ROOF_YR_CY)  as Roof_Age,

			CASE
  WHEN CUST_MEMB_TYPE = ''CST'' THEN ''C'' || SUBSTRING(
    ''0000000'' || TRIM((CUST_MEMB_NUM)),
    LENGTH(TRIM(CUST_MEMB_NUM)) + 1,
    7
  )
  WHEN CUST_MEMB_TYPE = ''MBR'' THEN SUBSTRING(
    ''00000000'' || (TRIM(CUST_MEMB_NUM)),
    LENGTH(TRIM(CUST_MEMB_NUM)) + 1,
    8
  )
  ELSE ''99999999''
END AS MEMB

		from

			DB_T_CORE_DM_PROD.ACCTSTATS a

		where

			a.exp_dt = (select max(b.exp_dt) from DB_T_CORE_DM_PROD.ACCTSTATS b where b.plcy_nbr = a.plcy_nbr and (b.plcy_nbr in (select policy_num from  DB_T_STAG_MEMBXREF_PROD.POLICY_DETAILS)))

		group by

			CUST_MEMB_NUM, PLCY_NBR, ROOF_YR_CY, exp_dt, ROOF_AGE, MEMB

	) A

where

	Roof_Age > 15



UNION ALL



SELECT DISTINCT

	cast(A.MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

 	cast(A.POLICY_NUM as varchar(25)) AS POLICY_NUM,

 	cast(4 as integer) AS ALERT_NUM,

	cast('''' as varchar(35)) AS ALERT_COUNT_DESC

FROM

	(

		SELECT

			MEMBER_NUM,

 			POLICY_NUM,

 			POLICY_TYPE,

 			count(POLICY_NUM) as POL_COUNT

		FROM

			DB_T_STAG_MEMBXREF_PROD.CLAIM_DETAILS

		WHERE

			COALESCE(POLICYSTATUS_GROUPNM,''ZYZYZYZY'') <> ''VIN CLAIMS''

		group by

			1,2,3

	) A

where

	POLICY_TYPE in (''FARM'', ''FIRE'', ''HOME'', ''MH'')



UNION ALL



SELECT DISTINCT

	cast(PC_MEMBER_NUMBER as varchar(8)) AS MEMBER_NUM,

	cast(SC_POLICY_NUM as varchar(25)) AS POLICY_NUM,

	cast(5 as integer) AS ALERT_NUM,

	cast('''' as varchar(35)) AS ALERT_COUNT_DESC

FROM

	DB_T_CORE_MEMBXREF_PROD.HOMEPOLS

where

	LEFT (HO_PRI_CLASS, 1) = ''3''
AND HO_DEDUCTIBLE IN (1, 2, 3)



UNION ALL



SELECT DISTINCT

	cast(A.PC_MEMBER_NUMBER as varchar(8)) AS MEMBER_NUM,

	cast(B.SC_POLICY_NUM as varchar(25)) AS POLICY_NUM,

	cast(6 as integer) AS ALERT_NUM,

    cast('''' as varchar(35)) AS ALERT_COUNT_DESC

FROM

	DB_T_CORE_MEMBXREF_PROD.HOMEPOLS A

	inner join DB_T_STAG_MEMBXREF_PROD.HOMEENDORSEMENTS B

		on A.SC_POLICY_NUM =  B.SC_POLICY_NUM

WHERE

	HO_END_NUM IN (52, 19)



UNION ALL



SELECT DISTINCT

	cast(A.PC_MEMBER_NUMBER as varchar(8)) AS MEMBER_NUM,

	cast(A.SC_POLICY_NUM as varchar(25)) AS POLICY_NUM,

	cast(7 as integer) AS ALERT_NUM,

    cast('''' as varchar(35)) AS ALERT_COUNT_DESC

FROM

	(

		SELECT

			PC_MEMBER_NUMBER,

			SC_POLICY_NUM,

			HO_PRI_CONST_YR,

			(extract (year  from current_date)) - HO_PRI_CONST_YR as CONYEAR

		FROM

			DB_T_CORE_MEMBXREF_PROD.HOMEPOLS

	) A

where

	CONYEAR > 50 and HO_PRI_CONST_YR <>0



UNION ALL



SELECT DISTINCT

	CASE
  WHEN ALFA_CUST_MEMB_TYPE = ''CST'' THEN ''C'' || LPAD (TRIM(ALFA_CUST_MEMB_NBR), 7, ''0'')
  WHEN ALFA_CUST_MEMB_TYPE = ''MBR'' THEN LPAD (TRIM(ALFA_CUST_MEMB_NBR), 8, ''0'')
  ELSE ''99999999''
END AS MEMBER_NUM,

 	cast(A.PLCY_NBR as varchar(25)) AS POLICY_NUM,

	cast(8 as integer) AS ALERT_NUM,

	cast('''' as varchar(35)) AS ALERT_COUNT_DESC

FROM

	DB_T_CORE_DM_PROD.POLICY A

	inner join DB_T_CORE_DM_PROD.POLICY_HOLDER B

		on A.PLCY_NBR =  B.PLCY_NBR

WHERE

	NBR_LATE_RENS > 0



UNION ALL



SELECT DISTINCT

	CASE
  WHEN ALFA_CUST_MEMB_TYPE = ''CST'' THEN ''C'' || LPAD (TRIM(ALFA_CUST_MEMB_NBR), 7, ''0'')
  WHEN ALFA_CUST_MEMB_TYPE = ''MBR'' THEN LPAD (TRIM(ALFA_CUST_MEMB_NBR), 8, ''0'')
  ELSE ''99999999''
END AS MEMBER_NUM,

 	cast(A.PLCY_NBR as varchar(25)) AS POLICY_NUM,

	cast(9 as integer) AS ALERT_NUM,

    cast('''' as varchar(35)) AS ALERT_COUNT_DESC

FROM

	DB_T_CORE_DM_PROD.POLICY A

	inner join DB_T_CORE_DM_PROD.POLICY_HOLDER B

		on A.PLCY_NBR =  B.PLCY_NBR

WHERE

	NBR_REINST > 0



UNION ALL



SELECT DISTINCT

	cast(MEMBER_NUMBER as varchar(8)) AS MEMBER_NUM,

	cast(POLICY as varchar(25)) AS POLICY_NUM,

	CASE WHEN  AMOUNT >= 100000 THEN 11 ELSE 12 END AS ALERT_NUM,

	cast('''' as varchar(35)) AS ALERT_COUNT_DESC

FROM

	DB_T_STAG_MEMBXREF_PROD.LIFE



UNION ALL



SELECT DISTINCT

	cast(MEMBER_NUMBER as varchar(8)) AS MEMBER_NUM,

	cast(POLICY as varchar(25)) AS POLICY_NUM,

	CASE WHEN DWELLING >= 200000 THEN 13 ELSE 14 END AS ALERT_NUM,

	cast('''' as varchar(35)) AS ALERT_COUNT_DESC

FROM

	DB_T_STAG_MEMBXREF_PROD.HOMEFARMMANHO



UNION ALL



SELECT DISTINCT

	x.MEMBER_NUM as MEMBER_NUM,

	x.POLICY_NUM as POLICY_NUM,

	x.ALERT_NUM as ALERT_NUM,

	cast(x.total_rnt as varchar(35)) as ALERT_COUNT_DESC

FROM

	(

		SELECT

			cast(b.member_num as varchar(8)) AS MEMBER_NUM,

			cast(a.policy_nbr as varchar(25)) AS POLICY_NUM,

			cast(15 as integer) AS ALERT_NUM,

			cast (a.PLCY_IFO_RNT_LS_EQ_10 + a.PLCY_IFO_RNT_10_30 + a.PLCY_IFO_RNT_31_60 + a.PLCY_IFO_RNT_61_180 + a.PLCY_IFO_RNT_GT_180 as integer) as total_rnt

		FROM

			rnt_table a

			inner join DB_T_STAG_MEMBXREF_PROD.POLICIES_BY_MEMBER b

				on a.policy_nbr = b.policy_num

		where

			total_rnt > 0 and b.POLICY_TYPE = ''apv''

	)x



UNION ALL



SELECT DISTINCT

	CASE
  WHEN MEM_CUST_TYPE
  /*ALFA_CUST_MEMB_TYPE*/ 
  = ''CST'' THEN ''C'' || SUBSTRING(
    ''0000000'' || ((MEM_CUST_NBR)),
    LENGTH (TRIM(MEM_CUST_NBR)) + 1,
    7
  )
  WHEN MEM_CUST_TYPE = ''MBR'' THEN SUBSTRING(
    ''00000000'' || (TRIM(MEM_CUST_NBR)),
    LENGTH (TRIM(MEM_CUST_NBR)) + 1,
    8
  )
  ELSE ''99999999''
END AS MEMBER_NUM,
	CAST(RTRIM (POLICY_NBR) AS VARCHAR(25)) AS POLICY_NUM,

	cast(16 as integer) AS ALERT_NUM,

	''  '' || trim(cast (case when late_count_3yr <> 0 then late_count_3yr when late_count_2yr <> 0 then late_count_2yr when late_count_1yr <> 0 then late_count_1yr else 0 end as integer)) || ''  (BIL ACNT # '' || trim(BIL_ACCOUNT_NBR) || '')''   as ALERT_COUNT_DESC

FROM

	DB_T_STAG_PROD.ALFA_ARS_BILL_INFO

where

	lob= ''apv'' and (case when late_count_3yr <> 0 then late_count_3yr when late_count_2yr <> 0 then late_count_2yr when late_count_1yr <> 0 then late_count_1yr else 0 end ) <> 0



UNION ALL



SELECT DISTINCT

	CASE
  WHEN MEM_CUST_TYPE = ''CST'' THEN ''C'' || SUBSTRING(
    ''0000000'' || ((MEM_CUST_NBR)),
    LENGTH(TRIM(MEM_CUST_NBR)) + 1,
    7
  )
  WHEN MEM_CUST_TYPE = ''MBR'' THEN SUBSTRING(
    ''00000000'' || (TRIM(MEM_CUST_NBR)),
    LENGTH(TRIM(MEM_CUST_NBR)) + 1,
    8
  )
  ELSE ''99999999''
END AS MEMBER_NUM,


    CAST(RTRIM (POLICY_NBR) AS VARCHAR(25)) AS POLICY_NUM,

	cast(47 as integer) AS ALERT_NUM,

	''  '' || trim(cast (case when late_count_1yr <> 0 then late_count_1yr else 0 end as integer)) || ''  (BIL ACNT # '' || trim(BIL_ACCOUNT_NBR) || '')'' as ALERT_COUNT_DESC

FROM

	DB_T_STAG_PROD.ALFA_ARS_BILL_INFO

where

	lob= ''apv'' and (case when late_count_1yr <> 0 then late_count_1yr else 0 end) <> 0



UNION ALL



SELECT DISTINCT

	CASE
  WHEN a.REF_TYP_CD = ''CST'' THEN ''C'' || SUBSTRING(
    ''0000000'' || ((a.CLIENT_REF_NBR)),
    LENGTH (TRIM(a.CLIENT_REF_NBR)) + 1,
    7
  )
  WHEN a.REF_TYP_CD = ''MBR'' THEN SUBSTRING(
    ''00000000'' || (TRIM(a.CLIENT_REF_NBR)),
    LENGTH (TRIM(a.CLIENT_REF_NBR)) + 1,
    8
  )
  ELSE ''99999999''
END AS MEMBER_NUM,

 	cast('' '' as varchar(25)) AS POLICY_NUM,

	cast(17 as integer) AS ALERT_NUM,

    cast('''' as varchar(35)) AS ALERT_COUNT_DESC

from

	POL_VEH_LIB a

where

	a.CLIENT_REF_NBR not in (select b.CLIENT_REF_NBR from POL_VEH_CMP b)



UNION ALL



SELECT DISTINCT

	cast(mem_num as varchar(8)) AS MEMBER_NUM,

	cast(plcy_num as varchar(25)) AS POLICY_NUM,

	cast(18 as integer) AS ALERT_NUM,

	concat(''          '',cast(dis_itm as varchar(35))) AS ALERT_COUNT_DESC

FROM

	(

		SELECT

			PC_MEMBER_NUMBER as mem_num,

			SC_POLICY_NUM as plcy_num,

			AG_NUM_DISHON_ITMS as dis_itm,

			max (PC_EFF_DATE) as eff_dt

		FROM

			DB_T_CORE_MEMBXREF_PROD.AUTOPOLS

		where

			ag_num_dishon_itms > 0

		group by

			1,2,3

	) a



UNION ALL



SELECT DISTINCT

	cast(FNOL.MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

	cast(FNOL.CSR_CLAIM_NUM as varchar(25)) AS POLICY_NUM,

	CASE
  WHEN DATEDIFF (
    DAY,
    PDET.INCEPT_DATE,
    TO_DATE (FNOL.DOL, ''yyyy-mm-DD'')
  ) <= 30 THEN 28
  WHEN TO_DATE (FNOL.DOL, ''yyyy-mm-DD'') <= DATEADD (MONTH, 12, PDET.INCEPT_DATE) THEN 29
  ELSE 0
END AS ALERT_NUM,

	cast(NULL as varchar(35)) AS ALERT_COUNT_DESC

FROM

	DB_T_STAG_MEMBXREF_PROD.FNOL_ADJ_REVIEW FNOL

	LEFT OUTER JOIN DB_T_STAG_MEMBXREF_PROD.POLICY_DETAILS PDET

		ON FNOL.POLICY_NUM=PDET.POLICY_NUM

WHERE

	ALERT_NUM<>0 AND FNOL.MEMBER_NUM<>''ZZZZZZZZ''



UNION ALL



SELECT DISTINCT

	cast(FNOL.MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

	cast(FNOL.CSR_CLAIM_NUM as varchar(25)) AS POLICY_NUM,

	CASE
  WHEN DATEDIFF (
    DAY,
    TO_DATE (FNOL.DOL, ''yyyy-mm-DD''),
    PDET.THE_EXP_DATE
  ) <= 30 THEN 30
  ELSE 0
END AS ALERT_NUM,

	cast(NULL as varchar(35)) AS ALERT_COUNT_DESC

FROM

	DB_T_STAG_MEMBXREF_PROD.FNOL_ADJ_REVIEW FNOL

	LEFT OUTER JOIN DB_T_STAG_MEMBXREF_PROD.POLICY_DETAILS PDET

		ON FNOL.POLICY_NUM=PDET.POLICY_NUM

WHERE

	ALERT_NUM<>0 AND FNOL.MEMBER_NUM<>''ZZZZZZZZ''



UNION ALL



SELECT DISTINCT

	cast(FNOL.MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

	cast(FNOL.CSR_CLAIM_NUM as varchar(25)) AS POLICY_NUM,

	CASE
  WHEN DATEDIFF (
    DAY,
    PDET.INCEPT_DATE,
    TO_DATE (FNOL.DOL, ''yyyy-mm-DD'')
  ) <= 7 THEN 31
  ELSE 0
END AS ALERT_NUM,

	cast(NULL as varchar(35)) AS ALERT_COUNT_DESC

FROM

	DB_T_STAG_MEMBXREF_PROD.FNOL_ADJ_REVIEW FNOL

	LEFT OUTER JOIN DB_T_STAG_MEMBXREF_PROD.POLICY_DETAILS PDET

		ON FNOL.POLICY_NUM=PDET.POLICY_NUM

WHERE

	ALERT_NUM<>0 AND FNOL.MEMBER_NUM<>''ZZZZZZZZ''



UNION ALL



SELECT

	*

FROM

	(

		SELECT DISTINCT

			cast(MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

			cast(CSR_CLAIM_NUM as varchar(25)) AS POLICY_NUM,

			CASE WHEN VANDALISM_CLAIMS=1 THEN 32 WHEN VANDALISM_CLAIMS>=2 THEN 33 ELSE 0 END ALERT_NUM,

			cast(NULL as varchar(35)) AS ALERT_COUNT_DESC

		FROM

			CLIENT_CLAIMS

		WHERE

			ALERT_NUM<>0

	)QRY QUALIFY RANK() OVER (PARTITION BY POLICY_NUM ORDER BY ALERT_NUM DESC)=1



UNION ALL



SELECT

	*

FROM

	(

		SELECT DISTINCT

			cast(MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

			cast(CSR_CLAIM_NUM as varchar(25)) AS POLICY_NUM,

			CASE WHEN PARKED_CLAIMS=1 THEN 34 WHEN PARKED_CLAIMS>=2 THEN 35 ELSE 0 END ALERT_NUM,

			cast(NULL as varchar(35)) AS ALERT_COUNT_DESC

		FROM

			CLIENT_CLAIMS

		WHERE

			ALERT_NUM<>0

	)QRY QUALIFY RANK() OVER (PARTITION BY POLICY_NUM ORDER BY ALERT_NUM DESC)=1



UNION ALL



SELECT

	*

FROM

	(

		SELECT DISTINCT

			cast(MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

			cast(CSR_CLAIM_NUM as varchar(25)) AS POLICY_NUM,

			CASE WHEN HIT_RUN_CLAIMS=1 THEN 36 WHEN HIT_RUN_CLAIMS>=2 THEN 37 ELSE 0 END ALERT_NUM,

			cast(NULL as varchar(35)) AS ALERT_COUNT_DESC

		FROM

			CLIENT_CLAIMS

		WHERE

			ALERT_NUM<>0

	)QRY QUALIFY RANK() OVER (PARTITION BY POLICY_NUM ORDER BY ALERT_NUM DESC)=1



UNION ALL



SELECT

	*

FROM

	(

		SELECT DISTINCT

			cast(MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

			cast(CSR_CLAIM_NUM as varchar(25)) AS POLICY_NUM,

			CASE WHEN PHANTOM_CLAIMS=1 THEN 38 WHEN PHANTOM_CLAIMS>=2 THEN 39 ELSE 0 END ALERT_NUM,

			cast(NULL as varchar(35)) AS ALERT_COUNT_DESC

		FROM

			CLIENT_CLAIMS

		WHERE

			ALERT_NUM<>0

	)QRY QUALIFY RANK() OVER (PARTITION BY POLICY_NUM ORDER BY ALERT_NUM DESC)=1



UNION ALL



SELECT

	*

FROM

	(

		SELECT DISTINCT

			cast(MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

			cast(CSR_CLAIM_NUM as varchar(25)) AS POLICY_NUM,

			CASE WHEN FIRE_CLAIMS>=2 THEN 40 ELSE 0 END ALERT_NUM,

			cast(NULL as varchar(35)) AS ALERT_COUNT_DESC

		FROM

			CLIENT_CLAIMS

		WHERE

			ALERT_NUM<>0

	)QRY QUALIFY RANK() OVER (PARTITION BY POLICY_NUM ORDER BY ALERT_NUM DESC)=1



UNION ALL



SELECT

	*

FROM

	(

		SELECT DISTINCT

			cast(MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

			cast(CSR_CLAIM_NUM as varchar(25)) AS POLICY_NUM,

			CASE WHEN THEFT_CLAIMS>=2 THEN 41 ELSE 0 END ALERT_NUM,

			cast(NULL as varchar(35)) AS ALERT_COUNT_DESC

		FROM

			CLIENT_CLAIMS

		WHERE

			ALERT_NUM<>0

	)QRY QUALIFY RANK() OVER (PARTITION BY POLICY_NUM ORDER BY ALERT_NUM DESC)=1



UNION ALL



SELECT

	*

FROM

	(

		SELECT DISTINCT

			cast(MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

			cast(CSR_CLAIM_NUM as varchar(25)) AS POLICY_NUM,

			CASE WHEN WIND_HALL_CLAIMS=1 THEN 42 WHEN WIND_HALL_CLAIMS>=2 THEN 43 ELSE 0 END ALERT_NUM,

			cast(NULL as varchar(35)) AS ALERT_COUNT_DESC

		FROM

			CLIENT_CLAIMS

		WHERE

			ALERT_NUM<>0

	)QRY QUALIFY RANK() OVER (PARTITION BY POLICY_NUM ORDER BY ALERT_NUM DESC)=1



UNION ALL



SELECT

	*

FROM

	(

		SELECT DISTINCT

			cast(MEMBER_NUM as varchar(8)) AS MEMBER_NUM,

			cast(CSR_CLAIM_NUM as varchar(25)) AS POLICY_NUM,

			CASE WHEN ANIMAL_CLAIMS=1 THEN 44 WHEN ANIMAL_CLAIMS=2 THEN 45 WHEN ANIMAL_CLAIMS>=3 THEN 46 ELSE 0 END ALERT_NUM,

			cast(NULL as varchar(35)) AS ALERT_COUNT_DESC

		FROM

			CLIENT_CLAIMS

		WHERE

			ALERT_NUM<>0

	)QRY QUALIFY RANK() OVER (PARTITION BY POLICY_NUM ORDER BY ALERT_NUM DESC)=1
) SRC
)
);


-- Component Exp_Pass_Through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE Exp_Pass_Through AS
(
SELECT
SQ_POLICIES_BY_MEMBER.MEMBER_NUM as MEMBER_NUM,
SQ_POLICIES_BY_MEMBER.POLICY_NUM as POLICY_NUM,
SQ_POLICIES_BY_MEMBER.ALERT_NUM as ALERT_NUM,
SQ_POLICIES_BY_MEMBER.ALERT_COUNT_DESC as ALERT_COUNT_DESC,
SQ_POLICIES_BY_MEMBER.source_record_id
FROM
SQ_POLICIES_BY_MEMBER
);


-- Component POLICY_ALERTS, Type TARGET 
INSERT INTO DB_T_STAG_MEMBXREF_PROD.POLICY_ALERTS
(
MEMBER_NUM,
POLICY_NUM_CLAIM_NUM,
ALERT_NUM,
ALERT_COUNT_DESC
)
SELECT
Exp_Pass_Through.MEMBER_NUM as MEMBER_NUM,
Exp_Pass_Through.POLICY_NUM as POLICY_NUM_CLAIM_NUM,
Exp_Pass_Through.ALERT_NUM as ALERT_NUM,
Exp_Pass_Through.ALERT_COUNT_DESC as ALERT_COUNT_DESC
FROM
Exp_Pass_Through;


END; ';