-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_PRESTG_MULTILINE_POLSTAT("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- PIPELINE START FOR 1
-- Component TGT_DUMMY1, Type Pre SQL 
DELETE FROM DB_T_STAG_PROD.PRESTG_MULTILINE_POLSTAT;


-- Component SQ_SRC_DUMMY, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_SRC_DUMMY AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as DUMMY,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT COUNT (*) AS DUMMY FROM DB_T_STAG_PROD.PRESTG_MULTILINE_POLSTAT
) SRC
)
);


-- Component FILTRANS, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE FILTRANS AS
(
SELECT
SQ_SRC_DUMMY.DUMMY as DUMMY,
SQ_SRC_DUMMY.source_record_id
FROM
SQ_SRC_DUMMY
WHERE SQ_SRC_DUMMY.DUMMY >1
/*--= ''A''*/
);


-- Component TGT_DUMMY1, Type TARGET 
--INSERT INTO TGT_DUMMY1
CREATE OR REPLACE TEMPORARY TABLE TGT_DUMMY1 AS
(
SELECT
FILTRANS.DUMMY as DUMMY
FROM
FILTRANS);


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_Shortcut_to_MULTILINE_POLSTAT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_MULTILINE_POLSTAT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as POL_SYMBOL,
$2 as POL_NBR,
$3 as COMPANY,
$4 as STATE,
$5 as STATUS,
$6 as AGENT,
$7 as SERV_CNTR,
$8 as EXP_DT_CYMD,
$9 as DIST_REGION,
$10 as ADD_COV,
$11 as FIRE_CONVERT_TRANS_CODE,
$12 as SM_POL_INDICATOR,
$13 as REASON,
$14 as TOT_PREM,
$15 as FIRE_HOME_TYPE_POL,
$16 as EFF_DT_CYMD,
$17 as MEMBER_TYPE,
$18 as MEMBER_NBR,
$19 as NAMED_INS,
$20 as ADDL_NAMED_INS,
$21 as ADDR1,
$22 as ADDR2,
$23 as CITY,
$24 as ADDR_STATE,
$25 as ZIP,
$26 as DIV_S3_POL_SYM,
$27 as DIV_S3_POL_NBR,
$28 as DIV_MAIN_IND,
$29 as DIV_POL_LAPSE,
$30 as NR,
$31 as INF_UNIT_CTS,
$32 as FEED_DT,
$33 as POLICY_ACTIVITY,
$34 as INFORCE_IND,
$35 as LOB_GROUP,
$36 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
MULTILINE_POLSTAT.PLCY_SYM_CD POL_SYMBOL,
MULTILINE_POLSTAT.PLCY_NBR POL_NBR,
MULTILINE_POLSTAT.MASTER_COMPANY_NBR  COMPANY,
MULTILINE_POLSTAT.ST_CD STATE,/*--1,;''ml.``''*/
MULTILINE_POLSTAT.STATUS,
MULTILINE_POLSTAT.AGENT,
MULTILINE_POLSTAT.PLCY_SVC_NBR SERV_CNTR,
MULTILINE_POLSTAT.EXP_DT EXP_DT_CYMD,
MULTILINE_POLSTAT.DIST_REGION,
MULTILINE_POLSTAT.ADD_COV_CD ADD_COV,
MULTILINE_POLSTAT.FIRE_CONVERT_TRANS_CD FIRE_CONVERT_TRANS_CODE,
MULTILINE_POLSTAT.SM_POL_IND SM_POL_INDICATOR,
MULTILINE_POLSTAT.REASON,
MULTILINE_POLSTAT.TOT_PREM,
MULTILINE_POLSTAT.FIRE_HOME_TYPE_POL,
MULTILINE_POLSTAT.EFF_DT EFF_DT_CYMD,
MULTILINE_POLSTAT.ALFA_CUST_MEMB_TYPE MEMBER_TYPE,
MULTILINE_POLSTAT.ALFA_CUST_MEMB_NBR MEMBER_NBR,
MULTILINE_POLSTAT.NAME_INSURED NAMED_INS,
MULTILINE_POLSTAT.ADDL_NAME_INSURED ADDL_NAMED_INS,
MULTILINE_POLSTAT.ADDR_LINE_1 ADDR1,
MULTILINE_POLSTAT.ADDR_LINE_2 ADDR2,
MULTILINE_POLSTAT.CITY,
MULTILINE_POLSTAT.ADDR_ST_CD ADDR_STATE,
MULTILINE_POLSTAT.ZIP_CD ZIP,
MULTILINE_POLSTAT.DIV_S3_POL_SYM,
MULTILINE_POLSTAT.DIV_S3_POL_NBR,
MULTILINE_POLSTAT.DIV_MAN_IND DIV_MAIN_IND,
MULTILINE_POLSTAT.DIV_POL_LAPSE,
MULTILINE_POLSTAT.NR,
MULTILINE_POLSTAT.INF_UNIT_CTS,
MULTILINE_POLSTAT.FEED_DT,
MULTILINE_POLSTAT.POLICY_ACTIVITY,
MULTILINE_POLSTAT.INFORCE_IND,
MULTILINE_POLSTAT.LOB_CD LOB_GROUP
FROM DB_T_ML_PROD.MULTILINE_POLSTAT
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_Shortcut_to_MULTILINE_POLSTAT.POL_SYMBOL as POL_SYMBOL,
SQ_Shortcut_to_MULTILINE_POLSTAT.POL_NBR as POL_NBR,
SQ_Shortcut_to_MULTILINE_POLSTAT.COMPANY as COMPANY,
SQ_Shortcut_to_MULTILINE_POLSTAT.STATE as STATE,
SQ_Shortcut_to_MULTILINE_POLSTAT.STATUS as STATUS,
SQ_Shortcut_to_MULTILINE_POLSTAT.AGENT as AGENT,
SQ_Shortcut_to_MULTILINE_POLSTAT.SERV_CNTR as SERV_CNTR,
SQ_Shortcut_to_MULTILINE_POLSTAT.EXP_DT_CYMD as EXP_DT_CYMD,
SQ_Shortcut_to_MULTILINE_POLSTAT.DIST_REGION as DIST_REGION,
SQ_Shortcut_to_MULTILINE_POLSTAT.ADD_COV as ADD_COV,
SQ_Shortcut_to_MULTILINE_POLSTAT.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE,
SQ_Shortcut_to_MULTILINE_POLSTAT.SM_POL_INDICATOR as SM_POL_INDICATOR,
SQ_Shortcut_to_MULTILINE_POLSTAT.REASON as REASON,
SQ_Shortcut_to_MULTILINE_POLSTAT.TOT_PREM as TOT_PREM,
SQ_Shortcut_to_MULTILINE_POLSTAT.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL,
SQ_Shortcut_to_MULTILINE_POLSTAT.EFF_DT_CYMD as EFF_DT_CYMD,
SQ_Shortcut_to_MULTILINE_POLSTAT.MEMBER_TYPE as MEMBER_TYPE,
SQ_Shortcut_to_MULTILINE_POLSTAT.MEMBER_NBR as MEMBER_NBR,
SQ_Shortcut_to_MULTILINE_POLSTAT.NAMED_INS as NAMED_INS,
SQ_Shortcut_to_MULTILINE_POLSTAT.ADDL_NAMED_INS as ADDL_NAMED_INS,
SQ_Shortcut_to_MULTILINE_POLSTAT.ADDR1 as ADDR1,
SQ_Shortcut_to_MULTILINE_POLSTAT.ADDR2 as ADDR2,
SQ_Shortcut_to_MULTILINE_POLSTAT.CITY as CITY,
SQ_Shortcut_to_MULTILINE_POLSTAT.ADDR_STATE as ADDR_STATE,
SQ_Shortcut_to_MULTILINE_POLSTAT.ZIP as ZIP,
SQ_Shortcut_to_MULTILINE_POLSTAT.DIV_S3_POL_SYM as DIV_S3_POL_SYM,
SQ_Shortcut_to_MULTILINE_POLSTAT.DIV_S3_POL_NBR as DIV_S3_POL_NBR,
SQ_Shortcut_to_MULTILINE_POLSTAT.DIV_MAIN_IND as DIV_MAIN_IND,
SQ_Shortcut_to_MULTILINE_POLSTAT.DIV_POL_LAPSE as DIV_POL_LAPSE,
SQ_Shortcut_to_MULTILINE_POLSTAT.NR as NR,
SQ_Shortcut_to_MULTILINE_POLSTAT.INF_UNIT_CTS as INF_UNIT_CTS,
SQ_Shortcut_to_MULTILINE_POLSTAT.FEED_DT as FEED_DT,
SQ_Shortcut_to_MULTILINE_POLSTAT.POLICY_ACTIVITY as POLICY_ACTIVITY,
SQ_Shortcut_to_MULTILINE_POLSTAT.INFORCE_IND as INFORCE_IND,
SQ_Shortcut_to_MULTILINE_POLSTAT.LOB_GROUP as LOB_GROUP,
SQ_Shortcut_to_MULTILINE_POLSTAT.source_record_id
FROM
SQ_Shortcut_to_MULTILINE_POLSTAT
);


-- Component Shortcut_to_PRESTG_MULTILINE_POLSTAT, Type TARGET 
INSERT INTO DB_T_STAG_PROD.PRESTG_MULTILINE_POLSTAT
(
POL_SYMBOL,
POL_NBR,
COMPANY,
STATE,
STATUS,
AGENT,
SERV_CNTR,
EXP_DT_CYMD,
DIST_REGION,
ADD_COV,
FIRE_CONVERT_TRANS_CODE,
SM_POL_INDICATOR,
REASON,
TOT_PREM,
FIRE_HOME_TYPE_POL,
EFF_DT_CYMD,
MEMBER_TYPE,
MEMBER_NBR,
NAMED_INS,
ADDL_NMD_INS,
ADDR1,
ADDR2,
CITY,
ADDR_STATE,
ZIP,
DIV_S3_POL_SYM,
DIV_S3_POL_NBR,
DIV_MAN_IND,
DIV_POL_LAPSE,
NR,
INF_UNIT_CTS,
FEED_DT,
POLICY_ACTIVITY,
INFORCE_IND,
LOB_GROUP
)
SELECT
EXPTRANS.POL_SYMBOL as POL_SYMBOL,
EXPTRANS.POL_NBR as POL_NBR,
EXPTRANS.COMPANY as COMPANY,
EXPTRANS.STATE as STATE,
EXPTRANS.STATUS as STATUS,
EXPTRANS.AGENT as AGENT,
EXPTRANS.SERV_CNTR as SERV_CNTR,
EXPTRANS.EXP_DT_CYMD as EXP_DT_CYMD,
EXPTRANS.DIST_REGION as DIST_REGION,
EXPTRANS.ADD_COV as ADD_COV,
EXPTRANS.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE,
EXPTRANS.SM_POL_INDICATOR as SM_POL_INDICATOR,
EXPTRANS.REASON as REASON,
EXPTRANS.TOT_PREM as TOT_PREM,
EXPTRANS.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL,
EXPTRANS.EFF_DT_CYMD as EFF_DT_CYMD,
EXPTRANS.MEMBER_TYPE as MEMBER_TYPE,
EXPTRANS.MEMBER_NBR as MEMBER_NBR,
EXPTRANS.NAMED_INS as NAMED_INS,
EXPTRANS.ADDL_NAMED_INS as ADDL_NMD_INS,
EXPTRANS.ADDR1 as ADDR1,
EXPTRANS.ADDR2 as ADDR2,
EXPTRANS.CITY as CITY,
EXPTRANS.ADDR_STATE as ADDR_STATE,
EXPTRANS.ZIP as ZIP,
EXPTRANS.DIV_S3_POL_SYM as DIV_S3_POL_SYM,
EXPTRANS.DIV_S3_POL_NBR as DIV_S3_POL_NBR,
EXPTRANS.DIV_MAIN_IND as DIV_MAN_IND,
EXPTRANS.DIV_POL_LAPSE as DIV_POL_LAPSE,
EXPTRANS.NR as NR,
EXPTRANS.INF_UNIT_CTS as INF_UNIT_CTS,
EXPTRANS.FEED_DT as FEED_DT,
EXPTRANS.POLICY_ACTIVITY as POLICY_ACTIVITY,
EXPTRANS.INFORCE_IND as INFORCE_IND,
EXPTRANS.LOB_GROUP as LOB_GROUP
FROM
EXPTRANS;


-- PIPELINE END FOR 2

END; ';