-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.MPLT_LKP_ECTL_BATCH_PRGM_VALIDATION_CORETEST("IN_IN_MPLT_LKP_BATCH_PRGM" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
    temp_sql STRING;
BEGIN

-- Component exp_HARDCODE_BATCH_ACTIVE_IND, Type EXPRESSION 
temp_sql := CONCAT(''
CREATE OR REPLACE TEMPORARY TABLE exp_HARDCODE_BATCH_ACTIVE_IND AS
(
    SELECT
    in_MPLT_LKP_BATCH_PRGM.in_PRGM_NM as PRGM_NM,
    in_MPLT_LKP_BATCH_PRGM.in_ACT_PROJ_ID as PROJ_ID,
    in_MPLT_LKP_BATCH_PRGM.in_BATCH_ACTIVE_IND as BATCH_ACTIVE_IND,
    in_MPLT_LKP_BATCH_PRGM.in_TABLE_NM as TABLE_NM,
    in_MPLT_LKP_BATCH_PRGM.source_record_id
    FROM
    '', in_in_MPLT_LKP_BATCH_PRGM, '' in_MPLT_LKP_BATCH_PRGM
);
'');
EXECUTE IMMEDIATE :temp_sql;

-- Component LKP_ECTL_PRGM_INFO, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_ECTL_PRGM_INFO AS
(
    SELECT
    LKP.ECTL_PRGM_ID,
    LKP.ECTL_SRC_ID,
    LKP.ECTL_SRC_INST_ID,
    exp_HARDCODE_BATCH_ACTIVE_IND.source_record_id,
    ROW_NUMBER() OVER(PARTITION BY exp_HARDCODE_BATCH_ACTIVE_IND.source_record_id ORDER BY LKP.ECTL_PRGM_ID asc,LKP.ECTL_SRC_ID asc,LKP.ECTL_SRC_INST_ID asc) RNK
    FROM
    exp_HARDCODE_BATCH_ACTIVE_IND
    LEFT JOIN (
    SELECT ECTL_PRGM_INFO.ECTL_PRGM_ID as ECTL_PRGM_ID, ECTL_PRGM_INFO.ECTL_PROJ_ID as ECTL_PROJ_ID,ECTL_PRGM_INFO.ECTL_SRC_ID as ECTL_SRC_ID, ECTL_PRGM_INFO.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID, ECTL_PRGM_INFO.ECTL_PRGM_NM as ECTL_PRGM_NM FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_INFO WHERE ECTL_ACTIVE_IND = ''Y''
    ) LKP ON LKP.ECTL_PRGM_NM = exp_HARDCODE_BATCH_ACTIVE_IND.PRGM_NM AND LKP.ECTL_PROJ_ID = exp_HARDCODE_BATCH_ACTIVE_IND.PROJ_ID
    QUALIFY RNK = 1
);


-- Component LKP_ECTL_BATCH_INFO, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_ECTL_BATCH_INFO AS
(
    SELECT
    LKP.ECTL_BATCH_ID,
    LKP.ECTL_BATCH_START_TS,
    exp_HARDCODE_BATCH_ACTIVE_IND.source_record_id,
    ROW_NUMBER() OVER(PARTITION BY exp_HARDCODE_BATCH_ACTIVE_IND.source_record_id ORDER BY LKP.ECTL_BATCH_ID asc,LKP.ECTL_BATCH_START_TS asc) RNK
    FROM
    exp_HARDCODE_BATCH_ACTIVE_IND
    LEFT JOIN (
    SELECT
    ECTL_BATCH_ID,
    ECTL_BATCH_START_TS,
    ECTL_PROJ_ID,
    ECTL_ACTIVE_IND
    FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO
    ) LKP ON LKP.ECTL_PROJ_ID = exp_HARDCODE_BATCH_ACTIVE_IND.PROJ_ID AND LKP.ECTL_ACTIVE_IND = exp_HARDCODE_BATCH_ACTIVE_IND.BATCH_ACTIVE_IND
    QUALIFY RNK = 1
);


-- Component LKP_ECTL_TABLE_XREF, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_ECTL_TABLE_XREF AS
(
    SELECT
    LKP.ECTL_TABLE_ID,
    exp_HARDCODE_BATCH_ACTIVE_IND.source_record_id,
    ROW_NUMBER() OVER(PARTITION BY exp_HARDCODE_BATCH_ACTIVE_IND.source_record_id ORDER BY LKP.ECTL_TABLE_ID asc) RNK
    FROM
    exp_HARDCODE_BATCH_ACTIVE_IND
    LEFT JOIN (
    SELECT
    ECTL_TABLE_ID,
    ECTL_TABLE_NM
    FROM DB_T_CTRL_FIN_PROD.ECTL_TABLE_XREF
    ) LKP ON LKP.ECTL_TABLE_NM = exp_HARDCODE_BATCH_ACTIVE_IND.TABLE_NM
    QUALIFY RNK = 1
);


-- Component exp_ASSIGN_TS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ASSIGN_TS AS
(
    SELECT
    LKP_ECTL_PRGM_INFO.ECTL_PRGM_ID as ECTL_PRGM_ID,
    LKP_ECTL_PRGM_INFO.ECTL_SRC_ID as ECTL_SRC_ID,
    LKP_ECTL_PRGM_INFO.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
    LKP_ECTL_BATCH_INFO.ECTL_BATCH_ID as ECTL_BATCH_ID,
    CURRENT_TIMESTAMP as out_ORIG_INS_TS,
    CASE WHEN LKP_ECTL_BATCH_INFO.ECTL_BATCH_ID IS NULL OR LKP_ECTL_PRGM_INFO.ECTL_PRGM_ID IS NULL THEN TO_NUMBER(''ERROR-BATCH/PROGRAM NOT ACTIVE'') ELSE NULL END as var_BATCH_VALIDATION,
--    TO_DATE ( SUBSTR ( TO_CHAR ( LKP_ECTL_BATCH_INFO.ECTL_BATCH_START_TS ) , 1 , 10 ) , ''MM/DD/YYYY'' ) as out_ECTL_BATCH_START_DATE,
         LKP_ECTL_BATCH_INFO.ECTL_BATCH_START_TS  as out_ECTL_BATCH_START_DATE,
    LKP_ECTL_TABLE_XREF.ECTL_TABLE_ID as ECTL_TABLE_ID,
    LKP_ECTL_PRGM_INFO.source_record_id
    FROM
    LKP_ECTL_PRGM_INFO
    INNER JOIN LKP_ECTL_BATCH_INFO ON LKP_ECTL_PRGM_INFO.source_record_id = LKP_ECTL_BATCH_INFO.source_record_id
    INNER JOIN LKP_ECTL_TABLE_XREF ON LKP_ECTL_BATCH_INFO.source_record_id = LKP_ECTL_TABLE_XREF.source_record_id
);


-- Component out_MPLT_LKP_BATCH_PRGM, Type OUTPUT_TRANSFORMATION 
-- Component out_MPLT_LKP_BATCH_PRGM, Type MAPPLET 
CREATE OR REPLACE TEMPORARY TABLE mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE AS
(
    SELECT
    exp_ASSIGN_TS.ECTL_PRGM_ID as out_ECTL_PRGM_ID,
    exp_ASSIGN_TS.ECTL_SRC_ID as out_ECTL_SRC_ID,
    exp_ASSIGN_TS.ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
    exp_ASSIGN_TS.ECTL_BATCH_ID as out_ECTL_BATCH_ID,
    exp_ASSIGN_TS.out_ORIG_INS_TS as out_ORIG_INS_TS,
    exp_ASSIGN_TS.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
    exp_ASSIGN_TS.ECTL_TABLE_ID as out_ECTL_TABLE_ID,
    exp_ASSIGN_TS.source_record_id
    FROM
    exp_ASSIGN_TS
);


return ''mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE'';


END; ';