-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_MANUAL_ENTRIES_GL_CORE("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE ACT_PROJ_ID varchar;
ECTL_ACTIVE_IND varchar;
BEGIN 


ECTL_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
ACT_PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 

-- Component SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as LEDGER,
$2 as BUSINESS_UNIT,
$3 as JOURNAL_ID,
$4 as JOURNAL_DATE,
$5 as JOURNAL_LINE,
$6 as ACCOUNT_NBR,
$7 as DEPT_ID,
$8 as STATE,
$9 as POOL,
$10 as REINSURANCE_CD,
$11 as PROJECT_ID,
$12 as POLICY_NBR,
$13 as SUM_AMOUNT,
$14 as SRC,
$15 as REF_NBR,
$16 as USR_NM,
$17 as BUSINESS_UNIT_GL,
$18 as AFFILIATE,
$19 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT	STG.LEDGER, STG.BUSINESS_UNIT,
		STG.JOURNAL_ID, STG.JOURNAL_DATE,
		STG.JOURNAL_LINE, STG.ACCOUNT_NBR,
		STG.DEPT_ID, STG.STATE,
		STG.POOL, STG.REINSURANCE_CD,
		STG.PROJECT_ID, STG.POLICY_NBR,
		STG.SUM_AMOUNT, STG.SRC,
		STG.REF_NBR, STG.USR_NM,
		STG.BUSINESS_UNIT_GL, STG.AFFILIATE 
FROM
 DB_T_STAG_FIN_PROD.STG_FIN_MANUAL_GL_ENTRIES STG
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.LEDGER as Ledger,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.BUSINESS_UNIT as Unit,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.JOURNAL_ID as Journal_ID,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.JOURNAL_DATE as Date,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.JOURNAL_LINE as "Line_#",
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.ACCOUNT_NBR as Account,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.DEPT_ID as Dept,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.STATE as State,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.POOL as Pool_Ind,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.REINSURANCE_CD as Reins_Cd,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.PROJECT_ID as Project,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.POLICY_NBR as Line_Descr,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.SUM_AMOUNT as Sum_Amount,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.SRC as Source,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.REF_NBR as Ref_No,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.USR_NM as User,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.BUSINESS_UNIT_GL as Unit1,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.AFFILIATE as Affiliate,
''m_MANUAL_ENTRIES_GL_CORE'' as in_PRGM_NM,
:ACT_PROJ_ID as in_ACT_PROJ_ID,
:ECTL_ACTIVE_IND as in_BATCH_ACTIVE_IND,
null IN_TABLE_NM,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL.source_record_id
FROM
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_GL
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''EXPTRANS'');

-- Component exp_target, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_target AS
(
SELECT
EXPTRANS.Ledger as Ledger,
SUBSTR ( LTRIM ( RTRIM ( EXPTRANS.Unit ) ) , 1 , 3 ) as o_Busines_Unit,
EXPTRANS.Journal_ID as Journal_ID,
EXPTRANS.Date as o_Date,
EXPTRANS."Line_#" as "Line_#",
EXPTRANS.Account as Account,
EXPTRANS.Dept as Dept,
EXPTRANS.State as State,
EXPTRANS.Pool_Ind as Pool_Ind,
EXPTRANS.Reins_Cd as Reins_Cd,
EXPTRANS.Project as Project,
UPPER ( EXPTRANS.Line_Descr ) as o_Policy_Num,
EXPTRANS.Sum_Amount as Sum_Amount,
EXPTRANS.Source as Source,
EXPTRANS.Ref_No as Ref_No,
EXPTRANS.User as User,
EXPTRANS.Unit1 as Unit1,
EXPTRANS.Affiliate as Affiliate,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_MODIFY_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
''NEW'' as out_ECTL_TXN_CD,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as out_ECTL_END_DATE,
EXPTRANS.source_record_id
FROM
EXPTRANS
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON EXPTRANS.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
);


-- Component Shortcut_to_FIN_MANUAL_GL_ENTRIES, Type TARGET 
INSERT INTO DB_T_CORE_FIN_PROD.FIN_MANUAL_GL_ENTRIES
(
LEDGER,
BUSINESS_UNIT,
JOURNAL_ID,
JOURNAL_DATE,
JOURNAL_LINE,
ACCOUNT_NBR,
DEPT_ID,
STATE,
POOL,
REINSURANCE_CD,
PROJECT_ID,
POLICY_NBR,
SUM_AMOUNT,
SRC,
REF_NBR,
USR_NM,
BUSINESS_UNIT_GL,
AFFILIATE,
ECTL_BATCH_ID,
ECTL_ORIG_INS_TS,
ECTL_MODIFY_TS,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_PRGM_ID,
ECTL_TXN_CD,
ECTL_START_DATE,
ECTL_END_DATE
)
SELECT
exp_target.Ledger as LEDGER,
exp_target.o_Busines_Unit as BUSINESS_UNIT,
exp_target.Journal_ID as JOURNAL_ID,
exp_target.o_Date as JOURNAL_DATE,
exp_target."Line_#" as JOURNAL_LINE,
exp_target.Account as ACCOUNT_NBR,
exp_target.Dept as DEPT_ID,
exp_target.State as STATE,
exp_target.Pool_Ind as POOL,
exp_target.Reins_Cd as REINSURANCE_CD,
exp_target.Project as PROJECT_ID,
exp_target.o_Policy_Num as POLICY_NBR,
exp_target.Sum_Amount as SUM_AMOUNT,
exp_target.Source as SRC,
exp_target.Ref_No as REF_NBR,
exp_target.User as USR_NM,
exp_target.Unit1 as BUSINESS_UNIT_GL,
exp_target.Affiliate as AFFILIATE,
exp_target.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_target.out_ORIG_INS_TS as ECTL_ORIG_INS_TS,
exp_target.out_MODIFY_TS as ECTL_MODIFY_TS,
exp_target.out_ECTL_SRC_ID as ECTL_SRC_ID,
exp_target.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_target.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_target.out_ECTL_TXN_CD as ECTL_TXN_CD,
exp_target.out_ECTL_BATCH_START_DATE as ECTL_START_DATE,
exp_target.out_ECTL_END_DATE as ECTL_END_DATE
FROM
exp_target;


END; ';