-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_FIN_ACCT_NBR_LKUP("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE 
PMMAPPINGNAME varchar;
ACT_PROJ_ID integer;
ECTL_ACTIVE_IND varchar;
PMSTG_FIN_ACCT_NBRTABLENAME varchar;
BEGIN 

PMMAPPINGNAME:='' ''; 
ACT_PROJ_ID:=1; 
ECTL_ACTIVE_IND:='' ''; 
PMSTG_FIN_ACCT_NBRTABLENAME:='' ''; 

-- Component sq_STG_FIN_ACCT_NBR, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_FIN_ACCT_NBR AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ACCOUNT_CD,
$2 as EFFDT,
$3 as DESCR,
$4 as EFF_STATUS,
$5 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT DISTINCT LTRIM(RTRIM(STG_FIN_ACCT_NBR.ACCOUNT_CD)),
 STG_FIN_ACCT_NBR.EFFDT, 
LTRIM(RTRIM(STG_FIN_ACCT_NBR.DESCR)), 
LTRIM(RTRIM(STG_FIN_ACCT_NBR.EFF_STATUS)) 
FROM
 DB_T_STAG_FIN_PROD.STG_FIN_ACCT_NBR
) SRC
)
);


-- Component exp_SRC_ECTL_FIELDS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_SRC_ECTL_FIELDS AS
(
SELECT
sq_STG_FIN_ACCT_NBR.ACCOUNT_CD as ACCOUNT_CD,
sq_STG_FIN_ACCT_NBR.EFFDT as EFFDT,
CASE WHEN sq_STG_FIN_ACCT_NBR.DESCR IS NULL THEN sq_STG_FIN_ACCT_NBR.ACCOUNT_CD ELSE sq_STG_FIN_ACCT_NBR.DESCR END as out_DESCRIPTION,
sq_STG_FIN_ACCT_NBR.EFF_STATUS as EFF_STATUS,
:PMMappingName as in_PRGM_NM,
:ACT_PROJ_ID as in_ACT_PROJ_ID,
:ECTL_ACTIVE_IND as in_BATCH_ACTIVE_IND,
:PMSTG_FIN_ACCT_NBRTableName as in_TABLE_NM,
sq_STG_FIN_ACCT_NBR.source_record_id
FROM
sq_STG_FIN_ACCT_NBR
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''exp_SRC_ECTL_FIELDS'');


-- Component LKP_FIN_ACCT_NBR_LKUP1, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_FIN_ACCT_NBR_LKUP1 AS
(
SELECT
LKP.ACCT_NBR,
exp_SRC_ECTL_FIELDS.ACCOUNT_CD as ACCT_NBR1,
exp_SRC_ECTL_FIELDS.EFFDT as EFFDT1,
exp_SRC_ECTL_FIELDS.out_DESCRIPTION as DESCRIPTION1,
exp_SRC_ECTL_FIELDS.EFF_STATUS as EFF_STATUS1,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as ECTL_PRGM_ID1,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as ECTL_SRC_ID1,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID1,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as ECTL_BATCH_ID1,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as ORIG_INS_TS1,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_TABLE_ID as ECTL_TABLE_ID1,
exp_SRC_ECTL_FIELDS.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_SRC_ECTL_FIELDS.source_record_id ORDER BY LKP.ACCT_NBR asc) RNK
FROM
exp_SRC_ECTL_FIELDS
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_SRC_ECTL_FIELDS.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
LEFT JOIN (
SELECT
ACCT_NBR,
EFF_DT,
EFF_STATUS,
ACCT_DESC
FROM db_t_shrd_fin_prod.FIN_ACCT_NBR_LKUP
) LKP ON LKP.ACCT_NBR = exp_SRC_ECTL_FIELDS.ACCOUNT_CD AND LKP.EFF_DT = exp_SRC_ECTL_FIELDS.EFFDT AND LKP.EFF_STATUS = exp_SRC_ECTL_FIELDS.EFF_STATUS AND LKP.ACCT_DESC = exp_SRC_ECTL_FIELDS.out_DESCRIPTION
QUALIFY RNK = 1
);


-- Component fil_REJECT, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE fil_REJECT AS
(
SELECT
LKP_FIN_ACCT_NBR_LKUP1.ACCT_NBR as ACCT_NBR,
LKP_FIN_ACCT_NBR_LKUP1.ACCT_NBR1 as ACCT_NBR1,
LKP_FIN_ACCT_NBR_LKUP1.EFFDT1 as EFFDT,
LKP_FIN_ACCT_NBR_LKUP1.DESCRIPTION1 as DESCRIPTION,
LKP_FIN_ACCT_NBR_LKUP1.EFF_STATUS1 as EFF_STATUS,
LKP_FIN_ACCT_NBR_LKUP1.ECTL_PRGM_ID1 as ECTL_PRGM_ID,
LKP_FIN_ACCT_NBR_LKUP1.ECTL_SRC_ID1 as ECTL_SRC_ID,
LKP_FIN_ACCT_NBR_LKUP1.ECTL_SRC_INST_ID1 as ECTL_SRC_INST_ID,
LKP_FIN_ACCT_NBR_LKUP1.ECTL_BATCH_ID1 as ECTL_BATCH_ID,
LKP_FIN_ACCT_NBR_LKUP1.ORIG_INS_TS1 as ORIG_INS_TS,
LKP_FIN_ACCT_NBR_LKUP1.ECTL_TABLE_ID1 as ECTL_TABLE_ID,
LKP_FIN_ACCT_NBR_LKUP1.source_record_id
FROM
LKP_FIN_ACCT_NBR_LKUP1
WHERE LKP_FIN_ACCT_NBR_LKUP1.ACCT_NBR IS NULL
);


-- Component LKP_FIN_ACCT_NBR_LKUP, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_FIN_ACCT_NBR_LKUP AS
(
SELECT
LKP.ACCT_NBR,
fil_REJECT.source_record_id,
ROW_NUMBER() OVER(PARTITION BY fil_REJECT.source_record_id ORDER BY LKP.ACCT_NBR asc) RNK
FROM
fil_REJECT
LEFT JOIN (
SELECT
ACCT_NBR,
EFF_DT,
EFF_STATUS
FROM db_t_shrd_fin_prod.FIN_ACCT_NBR_LKUP
) LKP ON LKP.ACCT_NBR = fil_REJECT.ACCT_NBR1 AND LKP.EFF_DT = fil_REJECT.EFFDT AND LKP.EFF_STATUS = fil_REJECT.EFF_STATUS
QUALIFY RNK = 1
);


-- Component exp_VAL_CHK, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_VAL_CHK AS
(
SELECT
fil_REJECT.ACCT_NBR1 as ACCT_NBR,
fil_REJECT.EFFDT as EFFDT,
TO_DATE ( ''9999-12-31'' , ''yyyy-mm-dd'' ) as out_EXP_DT,
fil_REJECT.DESCRIPTION as DESCRIPTION,
fil_REJECT.EFF_STATUS as EFF_STATUS,
fil_REJECT.ECTL_PRGM_ID as ECTL_PRGM_ID,
fil_REJECT.ECTL_SRC_ID as ECTL_SRC_ID,
fil_REJECT.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
fil_REJECT.ECTL_BATCH_ID as ECTL_BATCH_ID,
fil_REJECT.ORIG_INS_TS as ORIG_INS_TS,
fil_REJECT.ECTL_TABLE_ID as ECTL_TABLE_ID,
CASE WHEN fil_REJECT.ACCT_NBR1 IS NULL OR TRIM(fil_REJECT.ACCT_NBR1) = '''' OR LENGTH ( fil_REJECT.ACCT_NBR1 ) = 0 THEN ''ERR'' ELSE CASE WHEN LKP_FIN_ACCT_NBR_LKUP.ACCT_NBR IS NULL THEN ''NEW'' ELSE ''UPD'' END END as out_CHK,
fil_REJECT.source_record_id
FROM
fil_REJECT
INNER JOIN LKP_FIN_ACCT_NBR_LKUP ON fil_REJECT.source_record_id = LKP_FIN_ACCT_NBR_LKUP.source_record_id
);


-- Component rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG, Type ROUTER Output Group ERROR_LOG
create or replace temporary table rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG AS
SELECT
exp_VAL_CHK.ACCT_NBR as ACCT_NBR,
exp_VAL_CHK.ACCT_NBR as SRC_ACCT_NBR,
exp_VAL_CHK.EFFDT as EFFDT,
exp_VAL_CHK.EFF_STATUS as EFF_STATUS,
exp_VAL_CHK.out_EXP_DT as EXP_DT,
exp_VAL_CHK.DESCRIPTION as ACCT_DESC,
exp_VAL_CHK.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_VAL_CHK.ORIG_INS_TS as ECTL_ORIG_INS_TS,
exp_VAL_CHK.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_VAL_CHK.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_VAL_CHK.ECTL_SRC_ID as ECTL_SRC_ID,
exp_VAL_CHK.ECTL_TABLE_ID as ECTL_TABLE_ID,
exp_VAL_CHK.out_CHK as in_CHK,
exp_VAL_CHK.source_record_id
FROM
exp_VAL_CHK
WHERE exp_VAL_CHK.out_CHK = ''ERR'';


-- Component rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT, Type ROUTER Output Group INSERT
create or replace temporary table rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT AS
SELECT
exp_VAL_CHK.ACCT_NBR as ACCT_NBR,
exp_VAL_CHK.ACCT_NBR as SRC_ACCT_NBR,
exp_VAL_CHK.EFFDT as EFFDT,
exp_VAL_CHK.EFF_STATUS as EFF_STATUS,
exp_VAL_CHK.out_EXP_DT as EXP_DT,
exp_VAL_CHK.DESCRIPTION as ACCT_DESC,
exp_VAL_CHK.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_VAL_CHK.ORIG_INS_TS as ECTL_ORIG_INS_TS,
exp_VAL_CHK.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_VAL_CHK.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_VAL_CHK.ECTL_SRC_ID as ECTL_SRC_ID,
exp_VAL_CHK.ECTL_TABLE_ID as ECTL_TABLE_ID,
exp_VAL_CHK.out_CHK as in_CHK,
exp_VAL_CHK.source_record_id
FROM
exp_VAL_CHK
WHERE exp_VAL_CHK.out_CHK = ''NEW'';


-- Component rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE, Type ROUTER Output Group UPDATE
create or replace temporary table rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE AS
SELECT
exp_VAL_CHK.ACCT_NBR as ACCT_NBR,
exp_VAL_CHK.ACCT_NBR as SRC_ACCT_NBR,
exp_VAL_CHK.EFFDT as EFFDT,
exp_VAL_CHK.EFF_STATUS as EFF_STATUS,
exp_VAL_CHK.out_EXP_DT as EXP_DT,
exp_VAL_CHK.DESCRIPTION as ACCT_DESC,
exp_VAL_CHK.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_VAL_CHK.ORIG_INS_TS as ECTL_ORIG_INS_TS,
exp_VAL_CHK.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_VAL_CHK.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_VAL_CHK.ECTL_SRC_ID as ECTL_SRC_ID,
exp_VAL_CHK.ECTL_TABLE_ID as ECTL_TABLE_ID,
exp_VAL_CHK.out_CHK as in_CHK,
exp_VAL_CHK.source_record_id
FROM
exp_VAL_CHK
WHERE exp_VAL_CHK.out_CHK = ''UPD'';


-- Component exp_date, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_date AS
(
SELECT
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.ACCT_NBR as ACCT_NBR1,
to_char ( rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.EFFDT , ''yyyy-mm-dd'' ) as EFFDT11,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.EFF_STATUS as EFF_STATUS1,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.ACCT_DESC as ACCT_DESC1,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.source_record_id
FROM
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT
);


-- Component FIN_NEW_ACCT_NBRS, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE FIN_NEW_ACCT_NBRS AS
(
SELECT
exp_date.ACCT_NBR1 as ACCOUNT_NBR,
exp_date.EFFDT11 as EFF_DT,
exp_date.EFF_STATUS1 as EFF_STATUS,
exp_date.ACCT_DESC1 as ACCOUNT_DESC
FROM
exp_date
);


-- Component FIN_NEW_ACCT_NBRS, Type EXPORT_DATA Exporting data
;


-- Component upd_FIN_ACCT_NBR_LKUP, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_FIN_ACCT_NBR_LKUP AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE.ACCT_NBR as ACCT_NBR,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE.SRC_ACCT_NBR as SRC_ACCT_NBR,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE.EFFDT as EFFDT,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE.EFF_STATUS as EFF_STATUS,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE.EXP_DT as EXP_DT,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE.ACCT_DESC as ACCT_DESC,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE.ECTL_BATCH_ID as ECTL_BATCH_ID,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE.ECTL_PRGM_ID as ECTL_PRGM_ID,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE.ECTL_SRC_ID as ECTL_SRC_ID,
1 as UPDATE_STRATEGY_ACTION,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE.source_record_id
FROM
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_UPDATE
);


-- Component exp_ERR_LOG, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ERR_LOG AS
(
SELECT
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG.ECTL_BATCH_ID as ECTL_BATCH_ID,
:ACT_PROJ_ID as out_ECTL_PROJ_ID,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG.ECTL_PRGM_ID as ECTL_PRGM_ID,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG.ECTL_TABLE_ID as ECTL_TABLE_ID,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG.ACCT_NBR || '' | '' || TO_CHAR ( rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG.EFFDT ) || '' | '' || rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG.EFF_STATUS || '' | '' || rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG.ACCT_DESC as out_SRC_KEY_VAL,
''ACCT_NBR'' as out_SRC_COL_NM,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG.ACCT_NBR as out_SRC_COL_VAL,
''ACCOUNT_CD is NULL or SPACES'' as out_SRC_COL_ERR,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG.source_record_id
FROM
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_ERROR_LOG
);


-- Component FIN_ACCT_NBR_LKUP_UPD, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_SHRD_FIN_PROD.FIN_ACCT_NBR_LKUP UPD
USING upd_FIN_ACCT_NBR_LKUP
ON (upd.ACCT_NBR = upd_FIN_ACCT_NBR_LKUP.ACCT_NBR AND upd.EFF_DT = upd_FIN_ACCT_NBR_LKUP.EFFDT AND upd.EFF_STATUS = upd_FIN_ACCT_NBR_LKUP.EFF_STATUS AND upd.ACCT_DESC <> upd_FIN_ACCT_NBR_LKUP.ACCT_DESC)
WHEN MATCHED THEN UPDATE SET
upd.ACCT_NBR = upd_FIN_ACCT_NBR_LKUP.ACCT_NBR, upd.EFF_DT = upd_FIN_ACCT_NBR_LKUP.EFFDT, upd.EFF_STATUS = upd_FIN_ACCT_NBR_LKUP.EFF_STATUS, upd.ACCT_DESC = upd_FIN_ACCT_NBR_LKUP.ACCT_DESC, upd.ECTL_BATCH_ID = upd_FIN_ACCT_NBR_LKUP.ECTL_BATCH_ID;


-- Component FIN_ACCT_NBR_LKUP_INS, Type TARGET 
INSERT INTO DB_T_SHRD_FIN_PROD.FIN_ACCT_NBR_LKUP
(
ACCT_NBR,
SRC_ACCT_NBR,
EFF_DT,
EFF_STATUS,
EXP_DT,
ACCT_DESC,
ECTL_SRC_INST_ID,
ECTL_ORIG_INS_TS,
ECTL_BATCH_ID,
ECTL_PRGM_ID,
ECTL_SRC_ID
)
SELECT
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.ACCT_NBR as ACCT_NBR,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.SRC_ACCT_NBR as SRC_ACCT_NBR,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.EFFDT as EFF_DT,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.EFF_STATUS as EFF_STATUS,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.EXP_DT as EXP_DT,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.ACCT_DESC as ACCT_DESC,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.ECTL_BATCH_ID as ECTL_BATCH_ID,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.ECTL_PRGM_ID as ECTL_PRGM_ID,
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT.ECTL_SRC_ID as ECTL_SRC_ID
FROM
rtr_INS_UPD_ERR_FIN_ACCT_NBR_LKUP_INSERT;


-- Component nrm_ECTL_ERR_LOG, Type NORMALIZER 
CREATE OR REPLACE TEMPORARY TABLE nrm_ECTL_ERR_LOG AS
(
SELECT ECTL_BATCH_ID_in as ECTL_BATCH_ID, ECTL_PROJ_ID_in as ECTL_PROJ_ID, ECTL_PRGM_ID_in as ECTL_PRGM_ID, ECTL_TABLE_ID_in as ECTL_TABLE_ID, ERR_SRC_KEY_VAL_in as ERR_SRC_KEY_VAL, ERR_COL_NM_in as ERR_COL_NM, ERR_COL_VAL_in as ERR_COL_VAL, ERR_DESC_in as ERR_DESC, ERR_TS_in as ERR_TS, * FROM
( /* start of inner SQL */
SELECT
exp_ERR_LOG.ECTL_BATCH_ID as ECTL_BATCH_ID_in,
exp_ERR_LOG.out_ECTL_PROJ_ID as ECTL_PROJ_ID_in,
exp_ERR_LOG.ECTL_PRGM_ID as ECTL_PRGM_ID_in,
exp_ERR_LOG.ECTL_TABLE_ID as ECTL_TABLE_ID_in,
exp_ERR_LOG.out_SRC_KEY_VAL as ERR_SRC_KEY_VAL_in,
exp_ERR_LOG.out_SRC_COL_NM as ERR_COL_NM_in,
exp_ERR_LOG.out_SRC_COL_VAL as ERR_COL_VAL_in,
exp_ERR_LOG.out_SRC_COL_ERR as ERR_DESC_in,
exp_ERR_LOG.ECTL_ORIG_INS_TS as ERR_TS_in,
exp_ERR_LOG.source_record_id
FROM
exp_ERR_LOG
/* end of inner SQL */
)
--UNPIVOT() FOR REC_NO IN () UNPIVOT_TBL
);


-- Component ECTL_ERR_LOG, Type TARGET 
INSERT INTO DB_T_CTRL_FIN_PROD.ECTL_ERR_LOG
(
ECTL_BATCH_ID,
ECTL_PROJ_ID,
ECTL_PRGM_ID,
ECTL_SRC_TABLE_ID,
ECTL_SRC_KEY_VAL,
ERR_COL_NM,
ERR_COL_VAL,
ERR_DESC,
ERR_TS
)
SELECT
nrm_ECTL_ERR_LOG.ECTL_BATCH_ID as ECTL_BATCH_ID,
nrm_ECTL_ERR_LOG.ECTL_PROJ_ID as ECTL_PROJ_ID,
nrm_ECTL_ERR_LOG.ECTL_PRGM_ID as ECTL_PRGM_ID,
nrm_ECTL_ERR_LOG.ECTL_TABLE_ID as ECTL_SRC_TABLE_ID,
nrm_ECTL_ERR_LOG.ERR_SRC_KEY_VAL as ECTL_SRC_KEY_VAL,
nrm_ECTL_ERR_LOG.ERR_COL_NM as ERR_COL_NM,
nrm_ECTL_ERR_LOG.ERR_COL_VAL as ERR_COL_VAL,
nrm_ECTL_ERR_LOG.ERR_DESC as ERR_DESC,
nrm_ECTL_ERR_LOG.ERR_TS as ERR_TS
FROM
nrm_ECTL_ERR_LOG;


END; ';