-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BAL_STG_TO_TGT_SHRD("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE SRC_NM varchar;
TGT_NM varchar;
COL1 varchar;
COL2 varchar;
COL3 varchar;
COL4 varchar;
COL5 varchar;
COL6 varchar;
COL7 varchar;
COL8 varchar;
COL9 varchar;
ACT_PROJ_ID varchar;
ECTL_ACTIVE_IND varchar;
MAPPING_NM varchar;
BEGIN 

SRC_NM:='' '';
TGT_NM:='' '';
COL1:='' '';
COL2:='' '';
COL3:='' '';
COL4:='' '';
COL5:='' '';
COL6:='' '';
COL7:='' '';
COL8:='' '';
COL9:='' '';
MAPPING_NM:=''M_BAL_STG_TO_TGT_SHRD'';
ECTL_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
ACT_PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 

-- Component sq_SRC_CNT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_SRC_CNT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ACCOUNT_CD,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT COUNT(*) AS SRC_CNT FROM 
(SELECT DISTINCT COL1 AS COL1,COL2 AS COL2,COL3 AS COL3,COL4 AS COL4,COL5 AS COL5 
FROM
 table(:SRC_NM)
 WHERE COL6=''COL7'' AND COL8=''COL9'') A
) SRC
)
);


-- Component sq_FETCH_UPDATE_INSERT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_FETCH_UPDATE_INSERT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_SRC_INST_ID,
$2 as ECTL_PRGM_ID,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT A.INSERT_CNT AS INSERT_CNT,B.UPDATE_CNT AS UPDATE_CNT FROM 
(SELECT COUNT(*) AS INSERT_CNT FROM TGT_NM
WHERE ECTL_BATCH_ID IN (SELECT ECTL_BATCH_ID FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_ACTIVE_IND=''ECTL_ACTIVE_IND''  AND ECTL_PROJ_ID=ACT_PROJ_ID)
AND ECTL_ORIG_INS_TS > (SELECT ECTL_BATCH_START_TS FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_ACTIVE_IND=''ECTL_ACTIVE_IND''   AND ECTL_PROJ_ID=ACT_PROJ_ID)) A,
(SELECT COUNT(*) AS UPDATE_CNT FROM TGT_NM
WHERE ECTL_BATCH_ID IN (SELECT ECTL_BATCH_ID FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_ACTIVE_IND=''ECTL_ACTIVE_IND''  AND ECTL_PROJ_ID=ACT_PROJ_ID)
AND ECTL_ORIG_INS_TS < (SELECT ECTL_BATCH_START_TS FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_ACTIVE_IND=''ECTL_ACTIVE_IND''  AND ECTL_PROJ_ID=ACT_PROJ_ID)) B
WHERE 1=1
) SRC
)
);


-- Component exp_DUMMY_PORT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_DUMMY_PORT AS
(
SELECT
1 as out_DUMMY,
sq_FETCH_UPDATE_INSERT.ECTL_SRC_INST_ID as INSERT_CNT,
sq_FETCH_UPDATE_INSERT.ECTL_PRGM_ID as UPDATE_CNT,
sq_FETCH_UPDATE_INSERT.source_record_id
FROM
sq_FETCH_UPDATE_INSERT
);


-- Component exp_SRC_DUMMY, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_SRC_DUMMY AS
(
SELECT
TO_NUMBER(sq_SRC_CNT.ACCOUNT_CD) as out_SRC_COUNT,
1 as out_DUMMY,
sq_SRC_CNT.source_record_id
FROM
sq_SRC_CNT
);


-- Component jnr_DUMMY, Type JOINER 
CREATE OR REPLACE TEMPORARY TABLE jnr_DUMMY AS
(
SELECT
exp_DUMMY_PORT.out_DUMMY as out_DUMMY,
exp_DUMMY_PORT.INSERT_CNT as INSERT_CNT,
exp_DUMMY_PORT.UPDATE_CNT as UPDATE_CNT,
exp_SRC_DUMMY.out_SRC_COUNT as out_SRC_COUNT,
exp_SRC_DUMMY.out_DUMMY as out_DUMMY1,
row_number() over (order by 1) AS source_record_id
FROM
exp_DUMMY_PORT
INNER JOIN exp_SRC_DUMMY ON exp_SRC_DUMMY.out_DUMMY = exp_DUMMY_PORT.out_DUMMY
);


-- Component exp_REJCT_CNT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_REJCT_CNT AS
(
SELECT
jnr_DUMMY.INSERT_CNT as INSERT_CNT,
jnr_DUMMY.UPDATE_CNT as UPDATE_CNT,
jnr_DUMMY.out_SRC_COUNT as SRC_COUNT,
jnr_DUMMY.out_SRC_COUNT - ( jnr_DUMMY.INSERT_CNT + jnr_DUMMY.UPDATE_CNT ) as var_REJECT_CNT,
var_REJECT_CNT as out_REJECT_CNT,
CASE WHEN var_REJECT_CNT = 0 THEN TGT_NM || '' - AUDIT PASSED'' ELSE TGT_NM || '' - AUDIT FAILED'' END as out_ECTL_MSG_TEXT,
ECTL_ACTIVE_IND as out_ECTL_ACTIVE_IND,
ACT_PROJ_ID as out_ECTL_PROJ_ID,
ltrim ( rtrim ( MAPPING_NM ) ) as out_PRGM_NM,
LTRIM ( RTRIM ( TGT_NM ) ) as out_TBL_NM,
0 as out_DEL_CNT,
CURRENT_TIMESTAMP as out_ORIG_INS_TS,
jnr_DUMMY.source_record_id
FROM
jnr_DUMMY
);


-- Component mplt_LKP_CTRL_TBLS_VALIDATION, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_CTRL_TBLS_VALIDATION, mapplet instance mplt_LKP_CTRL_TBLS_VALIDATION;
call mplt_LKP_CTRL_TBLS_VALIDATION(''exp_REJCT_CNT'');

-- Component ECTL_AUDIT_LOG_INS, Type TARGET 
INSERT INTO DB_T_CTRL_FIN_PROD.ECTL_AUDIT_LOG
(
ECTL_BATCH_ID,
ECTL_PRGM_ID,
ECTL_TABLE_ID,
ECTL_SRC_ROW_CNT,
ECTL_TRGT_INS_CNT,
ECTL_TRGT_UPD_CNT,
ECTL_TRGT_DEL_CNT,
ECTL_TRGT_REJ_CNT,
ECTL_MESSAGE_TXT,
ECTL_ORIG_INS_TS
)
SELECT
mplt_LKP_CTRL_TBLS_VALIDATION.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
mplt_LKP_CTRL_TBLS_VALIDATION.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
mplt_LKP_CTRL_TBLS_VALIDATION.out_ECTL_TABLE_ID as ECTL_TABLE_ID,
exp_REJCT_CNT.SRC_COUNT as ECTL_SRC_ROW_CNT,
exp_REJCT_CNT.INSERT_CNT as ECTL_TRGT_INS_CNT,
exp_REJCT_CNT.UPDATE_CNT as ECTL_TRGT_UPD_CNT,
exp_REJCT_CNT.out_DEL_CNT as ECTL_TRGT_DEL_CNT,
exp_REJCT_CNT.out_REJECT_CNT as ECTL_TRGT_REJ_CNT,
exp_REJCT_CNT.out_ECTL_MSG_TEXT as ECTL_MESSAGE_TXT,
exp_REJCT_CNT.out_ORIG_INS_TS as ECTL_ORIG_INS_TS
FROM
exp_REJCT_CNT
INNER JOIN mplt_LKP_CTRL_TBLS_VALIDATION ON exp_REJCT_CNT.source_record_id = mplt_LKP_CTRL_TBLS_VALIDATION.source_record_id;


END; ';