-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_STG_AGENT_NAME("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component STG_AGENT_NAME_INS, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_STAG_PROD.STG_AGENT_NAME;


-- Component amgdsq_AGNTHDR_AGTHDRST, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE amgdsq_AGNTHDR_AGTHDRST AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as H_CODE,
$2 as STATEX,
$3 as AGT_NO,
$4 as ORIGINAL_CNTY,
$5 as SERVICE_CENTER,
$6 as DISTRICT,
$7 as REGION,
$8 as LAST_FIRST_NAME,
$9 as PAY_AGENT,
$10 as PAYROLL_NX,
$11 as TYPE_COMM,
$12 as AUTO_NB,
$13 as AUTO_RENEWAL,
$14 as AUTO_CO_COMP,
$15 as FIRE_NB,
$16 as FIRE_RENEWAL,
$17 as FIRE_CO_COMP,
$18 as INACTIVE_CODE,
$19 as BONUSCD,
$20 as EMP_MO,
$21 as EMP_YR,
$22 as VAL_MO,
$23 as VAL_YR,
$24 as STANDARD_CODE,
$25 as PREV_EXPER_CODE,
$26 as NBR_MTHS_LVL_1,
$27 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
agnthdr_AGTHDRST.H_CODE,
agnthdr_AGTHDRST.STATEX,
agnthdr_AGTHDRST.AGT_NO,
agnthdr_AGTHDRST.ORIGINAL_CNTY,
agnthdr_AGTHDRST.SERVICE_CENTER,
agnthdr_AGTHDRST.DISTRICT,
agnthdr_AGTHDRST.REGION,
agnthdr_AGTHDRST.LAST_FIRST_NAME,
agnthdr_AGTHDRST.PAY_AGENT,
agnthdr_AGTHDRST.PAYROLL_NX,
agnthdr_AGTHDRST.TYPE_COMM,
agnthdr_AGTHDRST.AUTO_NB,
agnthdr_AGTHDRST.AUTO_RENEWAL,
agnthdr_AGTHDRST.AUTO_CO_COMP,
agnthdr_AGTHDRST.FIRE_NB,
agnthdr_AGTHDRST.FIRE_RENEWAL,
agnthdr_AGTHDRST.FIRE_CO_COMP,
agnthdr_AGTHDRST.INACTIVE_CODE,
agnthdr_AGTHDRST.BONUSCD,
agnthdr_AGTHDRST.EMP_MO,
agnthdr_AGTHDRST.EMP_YR,
agnthdr_AGTHDRST.VAL_MO,
agnthdr_AGTHDRST.VAL_YR,
agnthdr_AGTHDRST.STANDARD_CODE,
agnthdr_AGTHDRST.PREV_EXPER_CODE,
agnthdr_AGTHDRST.NBR_MTHS_LVL_1
FROM agnthdr_AGTHDRST
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
TO_NUMBER(amgdsq_AGNTHDR_AGTHDRST.AGT_NO) as out_AGT_NO,
DECODE ( amgdsq_AGNTHDR_AGTHDRST.STATEX , ''01'' , ''AL'' , ''02'' , ''AZ'' , ''03'' , ''AR'' , ''04'' , ''CA'' , ''05'' , ''CO'' , ''06'' , ''CT'' , ''07'' , ''DE'' , ''08'' , ''DC'' , ''09'' , ''FL'' , ''10'' , ''GA'' , ''11'' , ''HI'' , ''12'' , ''ID'' , ''13'' , ''IL'' , ''15'' , ''IN'' , ''16'' , ''IA'' , ''18'' , ''KS'' , ''20'' , ''KY'' , ''22'' , ''LA'' , ''23'' , ''ME'' , ''24'' , ''MD'' , ''25'' , ''MA'' , ''26'' , ''MI'' , ''27'' , ''MN'' , ''28'' , ''MS'' , ''29'' , ''MO'' , ''31'' , ''MT'' , ''32'' , ''NE'' , ''33'' , ''NV'' , ''34'' , ''NH'' , ''35'' , ''NJ'' , ''36'' , ''NM'' , ''37'' , ''NY'' , ''38'' , ''NC'' , ''40'' , ''ND'' , ''41'' , ''OH'' , ''42'' , ''OK'' , ''43'' , ''OR'' , ''44'' , ''PA'' , ''45'' , ''RI'' , ''46'' , ''SC'' , ''47'' , ''SD'' , ''48'' , ''TN'' , ''49'' , ''TX'' , ''52'' , ''UT'' , ''53'' , ''VT'' , ''54'' , ''VA'' , ''56'' , ''WA'' , ''57'' , ''WV'' , ''58'' , ''WI'' , ''59'' , ''WY'' , ''60'' , ''AK'' , ''61'' , ''OTHER'' , ''OTHER'' ) as out_STATE,
amgdsq_AGNTHDR_AGTHDRST.source_record_id
FROM
amgdsq_AGNTHDR_AGTHDRST
);


-- Component STG_AGENT_NAME_INS, Type TARGET 
INSERT INTO DB_T_STAG_PROD.STG_AGENT_NAME
(
H_CODE,
STATE,
AGT_NO,
ORIG_CNTY,
SERV_CTR,
DIST,
REGION,
LAST_FIRST_NM,
PAY_AGT,
PAYROLL_NO,
TYPE_COMM,
AUTO_NB_COMM,
AUTO_RN_COMM,
AUTO_CO_COMP_COM,
FIRE_NB_COMM,
FIRE_RN_COMM,
FIRE_CO_COMP_COM,
INACTIVE_CD,
BONUSCD,
EMP_MO,
EMP_YR,
VAL_MO,
VAL_YR,
STD_CODE,
PREV_EXPER_CD,
NBR_MTHS_LVL_1
)
SELECT
amgdsq_AGNTHDR_AGTHDRST.H_CODE as H_CODE,
EXPTRANS.out_STATE as STATE,
EXPTRANS.out_AGT_NO as AGT_NO,
amgdsq_AGNTHDR_AGTHDRST.ORIGINAL_CNTY as ORIG_CNTY,
amgdsq_AGNTHDR_AGTHDRST.SERVICE_CENTER as SERV_CTR,
amgdsq_AGNTHDR_AGTHDRST.DISTRICT as DIST,
amgdsq_AGNTHDR_AGTHDRST.REGION as REGION,
amgdsq_AGNTHDR_AGTHDRST.LAST_FIRST_NAME as LAST_FIRST_NM,
amgdsq_AGNTHDR_AGTHDRST.PAY_AGENT as PAY_AGT,
amgdsq_AGNTHDR_AGTHDRST.PAYROLL_NX as PAYROLL_NO,
amgdsq_AGNTHDR_AGTHDRST.TYPE_COMM as TYPE_COMM,
amgdsq_AGNTHDR_AGTHDRST.AUTO_NB as AUTO_NB_COMM,
amgdsq_AGNTHDR_AGTHDRST.AUTO_RENEWAL as AUTO_RN_COMM,
amgdsq_AGNTHDR_AGTHDRST.AUTO_CO_COMP as AUTO_CO_COMP_COM,
amgdsq_AGNTHDR_AGTHDRST.FIRE_NB as FIRE_NB_COMM,
amgdsq_AGNTHDR_AGTHDRST.FIRE_RENEWAL as FIRE_RN_COMM,
amgdsq_AGNTHDR_AGTHDRST.FIRE_CO_COMP as FIRE_CO_COMP_COM,
amgdsq_AGNTHDR_AGTHDRST.INACTIVE_CODE as INACTIVE_CD,
amgdsq_AGNTHDR_AGTHDRST.BONUSCD as BONUSCD,
amgdsq_AGNTHDR_AGTHDRST.EMP_MO as EMP_MO,
amgdsq_AGNTHDR_AGTHDRST.EMP_YR as EMP_YR,
amgdsq_AGNTHDR_AGTHDRST.VAL_MO as VAL_MO,
amgdsq_AGNTHDR_AGTHDRST.VAL_YR as VAL_YR,
amgdsq_AGNTHDR_AGTHDRST.STANDARD_CODE as STD_CODE,
amgdsq_AGNTHDR_AGTHDRST.PREV_EXPER_CODE as PREV_EXPER_CD,
amgdsq_AGNTHDR_AGTHDRST.NBR_MTHS_LVL_1 as NBR_MTHS_LVL_1
FROM
amgdsq_AGNTHDR_AGTHDRST
INNER JOIN EXPTRANS ON amgdsq_AGNTHDR_AGTHDRST.source_record_id = EXPTRANS.source_record_id;


END; ';