-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_ARS_BILL_INFO("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE PMMAPPINGNAME varchar;
ACT_PROJ_ID varchar;
BATCH_ACTIVE_IND varchar;
BEGIN 

PMMAPPINGNAME:='' ''; 
BATCH_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
ACT_PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 

-- Component SQ_STG_ARS_BILL_INFO, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_STG_ARS_BILL_INFO AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as BIL_ACCOUNT_ID,
$2 as BIL_ACCOUNT_NBR,
$3 as POLICY_NBR,
$4 as FEED_DT_ID,
$5 as BIL_PLAN_CD,
$6 as LATE_IND_3YR,
$7 as LATE_COUNT_1YR,
$8 as LATE_COUNT_2YR,
$9 as LATE_COUNT_3YR,
$10 as LATE_COUNT_4YR,
$11 as LATE_COUNT_5YR,
$12 as TEN_DAY_LATE_COUNT,
$13 as LOB,
$14 as MEM_CUST_TYPE,
$15 as MEM_CUST_NBR,
$16 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
STG_ARS_BILL_INFO.BIL_ACCOUNT_ID,
STG_ARS_BILL_INFO.BIL_ACCOUNT_NBR,
STG_ARS_BILL_INFO.POLICY_NBR,
STG_ARS_BILL_INFO.FEED_DT_ID,
STG_ARS_BILL_INFO.BIL_PLAN_CD,
STG_ARS_BILL_INFO.LATE_IND_3YR,
STG_ARS_BILL_INFO.LATE_COUNT_1YR,
STG_ARS_BILL_INFO.LATE_COUNT_2YR,
STG_ARS_BILL_INFO.LATE_COUNT_3YR,
STG_ARS_BILL_INFO.LATE_COUNT_4YR,
STG_ARS_BILL_INFO.LATE_COUNT_5YR,
STG_ARS_BILL_INFO.TEN_DAY_LATE_COUNT,
STG_ARS_BILL_INFO.LOB,
STG_ARS_BILL_INFO.MEM_CUST_TYPE,
STG_ARS_BILL_INFO.MEM_CUST_NBR
FROM DB_T_STAG_PROD.STG_ARS_BILL_INFO
WHERE FEED_DT_ID=(SELECT MAX(FEED_DT_ID) FROM DB_T_STAG_PROD.STG_ARS_BILL_INFO)
) SRC
)
);


-- Component LKP_ARS_BILL_INFO, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_ARS_BILL_INFO AS
(
SELECT
LKP.BIL_ACCOUNT_ID,
LKP.BIL_ACCOUNT_NBR,
LKP.POL_NBR,
LKP.FEED_DT_ID,
LKP.CHG_EFF_DT,
LKP.BIL_PLAN_CD,
LKP.LATE_IND_3YR,
LKP.LATE_COUNT_1YR,
LKP.LATE_COUNT_2YR,
LKP.LATE_COUNT_3YR,
LKP.LATE_COUNT_4YR,
LKP.LATE_COUNT_5YR,
LKP.TEN_DAY_LATE_COUNT,
LKP.LOB,
LKP.MEMB_CUST_TYPE,
LKP.MEMB_CUST_NBR,
SQ_STG_ARS_BILL_INFO.source_record_id,
ROW_NUMBER() OVER(PARTITION BY SQ_STG_ARS_BILL_INFO.source_record_id ORDER BY LKP.BIL_ACCOUNT_ID asc,LKP.BIL_ACCOUNT_NBR asc,LKP.POL_NBR asc,LKP.FEED_DT_ID asc,LKP.CHG_EFF_DT asc,LKP.BIL_PLAN_CD asc,LKP.LATE_IND_3YR asc,LKP.LATE_COUNT_1YR asc,LKP.LATE_COUNT_2YR asc,LKP.LATE_COUNT_3YR asc,LKP.LATE_COUNT_4YR asc,LKP.LATE_COUNT_5YR asc,LKP.TEN_DAY_LATE_COUNT asc,LKP.LOB asc,LKP.MEMB_CUST_TYPE asc,LKP.MEMB_CUST_NBR asc) RNK
FROM
SQ_STG_ARS_BILL_INFO
LEFT JOIN (
SELECT ARS_BILL_INFO.BIL_ACCOUNT_ID as BIL_ACCOUNT_ID, ARS_BILL_INFO.BIL_ACCOUNT_NBR as BIL_ACCOUNT_NBR, ARS_BILL_INFO.FEED_DT_ID as FEED_DT_ID, 
ARS_BILL_INFO.CHG_EFF_DT as CHG_EFF_DT, ARS_BILL_INFO.LATE_IND_3YR as LATE_IND_3YR, ARS_BILL_INFO.LATE_COUNT_1YR as LATE_COUNT_1YR, 
ARS_BILL_INFO.LATE_COUNT_2YR as LATE_COUNT_2YR, ARS_BILL_INFO.LATE_COUNT_3YR as LATE_COUNT_3YR, ARS_BILL_INFO.LATE_COUNT_4YR as LATE_COUNT_4YR, 
ARS_BILL_INFO.LATE_COUNT_5YR as LATE_COUNT_5YR, ARS_BILL_INFO.TEN_DAY_LATE_COUNT as TEN_DAY_LATE_COUNT, ARS_BILL_INFO.LOB as LOB, 
ARS_BILL_INFO.MEMB_CUST_TYPE as MEMB_CUST_TYPE, ARS_BILL_INFO.MEMB_CUST_NBR as MEMB_CUST_NBR, ARS_BILL_INFO.POL_NBR as POL_NBR, 
ARS_BILL_INFO.BIL_PLAN_CD as BIL_PLAN_CD FROM DB_T_CORE_PROD.ARS_BILL_INFO WHERE ECTL_TX_CD=''NEW''
) LKP ON LKP.POL_NBR = SQ_STG_ARS_BILL_INFO.POLICY_NBR AND LKP.BIL_PLAN_CD = SQ_STG_ARS_BILL_INFO.BIL_PLAN_CD
QUALIFY RNK = 1
);


-- Component exp_FLG_RECORDS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_FLG_RECORDS AS
(
SELECT
CASE WHEN LKP_ARS_BILL_INFO.POL_NBR IS NULL THEN ''NEW'' ELSE CASE WHEN CASE WHEN LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.BIL_ACCOUNT_ID ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.BIL_ACCOUNT_ID ) ) END <> CASE WHEN LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.BIL_ACCOUNT_ID ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.BIL_ACCOUNT_ID ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.BIL_ACCOUNT_NBR ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.BIL_ACCOUNT_NBR ) ) END <> CASE WHEN LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.BIL_ACCOUNT_NBR ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.BIL_ACCOUNT_NBR ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.BIL_PLAN_CD ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.BIL_PLAN_CD ) ) END <> CASE WHEN LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.BIL_PLAN_CD ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.BIL_PLAN_CD ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.LATE_IND_3YR ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.LATE_IND_3YR ) ) END <> CASE WHEN LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.LATE_IND_3YR ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.LATE_IND_3YR ) ) END OR CASE WHEN LKP_ARS_BILL_INFO.LATE_COUNT_1YR IS NULL THEN 0 ELSE LKP_ARS_BILL_INFO.LATE_COUNT_1YR END <> CASE WHEN SQ_STG_ARS_BILL_INFO.LATE_COUNT_1YR IS NULL THEN 0 ELSE SQ_STG_ARS_BILL_INFO.LATE_COUNT_1YR END OR CASE WHEN LKP_ARS_BILL_INFO.LATE_COUNT_2YR IS NULL THEN 0 ELSE LKP_ARS_BILL_INFO.LATE_COUNT_2YR END <> CASE WHEN SQ_STG_ARS_BILL_INFO.LATE_COUNT_2YR IS NULL THEN 0 ELSE SQ_STG_ARS_BILL_INFO.LATE_COUNT_2YR END OR CASE WHEN LKP_ARS_BILL_INFO.LATE_COUNT_3YR IS NULL THEN 0 ELSE LKP_ARS_BILL_INFO.LATE_COUNT_3YR END <> CASE WHEN SQ_STG_ARS_BILL_INFO.LATE_COUNT_3YR IS NULL THEN 0 ELSE SQ_STG_ARS_BILL_INFO.LATE_COUNT_3YR END OR CASE WHEN LKP_ARS_BILL_INFO.LATE_COUNT_4YR IS NULL THEN 0 ELSE LKP_ARS_BILL_INFO.LATE_COUNT_4YR END <> CASE WHEN SQ_STG_ARS_BILL_INFO.LATE_COUNT_4YR IS NULL THEN 0 ELSE SQ_STG_ARS_BILL_INFO.LATE_COUNT_4YR END OR CASE WHEN LKP_ARS_BILL_INFO.LATE_COUNT_5YR IS NULL THEN 0 ELSE LKP_ARS_BILL_INFO.LATE_COUNT_5YR END <> CASE WHEN SQ_STG_ARS_BILL_INFO.LATE_COUNT_5YR IS NULL THEN 0 ELSE SQ_STG_ARS_BILL_INFO.LATE_COUNT_5YR END OR CASE WHEN LKP_ARS_BILL_INFO.TEN_DAY_LATE_COUNT IS NULL THEN 0 ELSE LKP_ARS_BILL_INFO.TEN_DAY_LATE_COUNT END <> CASE WHEN SQ_STG_ARS_BILL_INFO.TEN_DAY_LATE_COUNT IS NULL THEN 0 ELSE SQ_STG_ARS_BILL_INFO.TEN_DAY_LATE_COUNT END OR CASE WHEN LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.LOB ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.LOB ) ) END <> CASE WHEN LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.LOB ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.LOB ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.MEMB_CUST_TYPE ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.MEMB_CUST_TYPE ) ) END <> CASE WHEN LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.MEM_CUST_TYPE ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.MEM_CUST_TYPE ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.MEMB_CUST_NBR ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_ARS_BILL_INFO.MEMB_CUST_NBR ) ) END <> CASE WHEN LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.MEM_CUST_NBR ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( SQ_STG_ARS_BILL_INFO.MEM_CUST_NBR ) ) END THEN ''UPD'' ELSE ''REJ'' END END as out_CHK,
:PMMappingName as out_ECTL_PRGM_NM,
:ACT_PROJ_ID as out_ECTL_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
:ACT_PROJ_ID as IN_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as IN_BATCH_ACTIVE_IND,
''m_STG_FIN_CLM'' IN_PRGM_NM,
null IN_TABLE_NM,
SQ_STG_ARS_BILL_INFO.BIL_ACCOUNT_ID as BIL_ACCOUNT_ID,
SQ_STG_ARS_BILL_INFO.BIL_ACCOUNT_NBR as BIL_ACCOUNT_NBR,
SQ_STG_ARS_BILL_INFO.POLICY_NBR as POLICY_NBR,
SQ_STG_ARS_BILL_INFO.BIL_PLAN_CD as BIL_PLAN_CD,
SQ_STG_ARS_BILL_INFO.LATE_IND_3YR as LATE_IND_3YR,
SQ_STG_ARS_BILL_INFO.LATE_COUNT_1YR as LATE_COUNT_1YR,
SQ_STG_ARS_BILL_INFO.LATE_COUNT_2YR as LATE_COUNT_2YR,
SQ_STG_ARS_BILL_INFO.LATE_COUNT_3YR as LATE_COUNT_3YR,
SQ_STG_ARS_BILL_INFO.LATE_COUNT_4YR as LATE_COUNT_4YR,
SQ_STG_ARS_BILL_INFO.LATE_COUNT_5YR as LATE_COUNT_5YR,
SQ_STG_ARS_BILL_INFO.TEN_DAY_LATE_COUNT as TEN_DAY_LATE_COUNT,
SQ_STG_ARS_BILL_INFO.LOB as LOB,
SQ_STG_ARS_BILL_INFO.MEM_CUST_TYPE as MEM_CUST_TYPE,
SQ_STG_ARS_BILL_INFO.MEM_CUST_NBR as MEM_CUST_NBR,
SQ_STG_ARS_BILL_INFO.FEED_DT_ID as FEED_DT_ID,
LKP_ARS_BILL_INFO.CHG_EFF_DT as CHG_EFF_DT_lkup,
SQ_STG_ARS_BILL_INFO.source_record_id
FROM
SQ_STG_ARS_BILL_INFO
INNER JOIN LKP_ARS_BILL_INFO ON SQ_STG_ARS_BILL_INFO.source_record_id = LKP_ARS_BILL_INFO.source_record_id
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''exp_FLG_RECORDS'');

-- Component exp_ECTL_FIELDS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ECTL_FIELDS AS
(
SELECT
exp_FLG_RECORDS.BIL_ACCOUNT_ID as BIL_ACCOUNT_ID,
exp_FLG_RECORDS.BIL_ACCOUNT_NBR as BIL_ACCOUNT_NBR,
exp_FLG_RECORDS.POLICY_NBR as POLICY_NBR,
exp_FLG_RECORDS.BIL_PLAN_CD as BIL_PLAN_CD,
exp_FLG_RECORDS.FEED_DT_ID as FEED_DT_ID,
exp_FLG_RECORDS.LATE_IND_3YR as LATE_IND_3YR,
exp_FLG_RECORDS.LATE_COUNT_1YR as LATE_COUNT_1YR,
exp_FLG_RECORDS.LATE_COUNT_2YR as LATE_COUNT_2YR,
exp_FLG_RECORDS.LATE_COUNT_3YR as LATE_COUNT_3YR,
exp_FLG_RECORDS.LATE_COUNT_4YR as LATE_COUNT_4YR,
exp_FLG_RECORDS.LATE_COUNT_5YR as LATE_COUNT_5YR,
exp_FLG_RECORDS.TEN_DAY_LATE_COUNT as TEN_DAY_LATE_COUNT,
exp_FLG_RECORDS.LOB as LOB,
exp_FLG_RECORDS.MEM_CUST_TYPE as MEM_CUST_TYPE,
exp_FLG_RECORDS.MEM_CUST_NBR as MEM_CUST_NBR,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_TABLE_ID as out_ECTL_TABLE_ID,
NULL as out_ECTL_END_DATE,
exp_FLG_RECORDS.out_CHK as out_CHK,
exp_FLG_RECORDS.CHG_EFF_DT_lkup as CHG_EFF_DT_lkup,
exp_FLG_RECORDS.source_record_id
FROM
exp_FLG_RECORDS
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_FLG_RECORDS.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
);


-- Component rtr_GROUP_NEW_OLD_RECORDS_INSERT, Type ROUTER Output Group INSERT
create or replace temp table RTR_GROUP_NEW_OLD_RECORDS_INSERT as
SELECT
exp_ECTL_FIELDS.BIL_ACCOUNT_ID as BIL_ACCOUNT_ID,
exp_ECTL_FIELDS.BIL_ACCOUNT_NBR as BIL_ACCOUNT_NBR,
exp_ECTL_FIELDS.POLICY_NBR as POLICY_NBR,
exp_ECTL_FIELDS.BIL_PLAN_CD as BIL_PLAN_CD,
exp_ECTL_FIELDS.FEED_DT_ID as FEED_DT_ID,
exp_ECTL_FIELDS.LATE_IND_3YR as LATE_IND_3YR,
exp_ECTL_FIELDS.LATE_COUNT_1YR as LATE_COUNT_1YR,
exp_ECTL_FIELDS.LATE_COUNT_2YR as LATE_COUNT_2YR,
exp_ECTL_FIELDS.LATE_COUNT_3YR as LATE_COUNT_3YR,
exp_ECTL_FIELDS.LATE_COUNT_4YR as LATE_COUNT_4YR,
exp_ECTL_FIELDS.LATE_COUNT_5YR as LATE_COUNT_5YR,
exp_ECTL_FIELDS.TEN_DAY_LATE_COUNT as TEN_DAY_LATE_COUNT,
exp_ECTL_FIELDS.LOB as LOB,
exp_ECTL_FIELDS.MEM_CUST_TYPE as MEM_CUST_TYPE,
exp_ECTL_FIELDS.MEM_CUST_NBR as MEM_CUST_NBR,
exp_ECTL_FIELDS.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
exp_ECTL_FIELDS.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
exp_ECTL_FIELDS.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
exp_ECTL_FIELDS.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
exp_ECTL_FIELDS.out_ORIG_INS_TS as out_ORIG_INS_TS,
exp_ECTL_FIELDS.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
exp_ECTL_FIELDS.out_ECTL_TABLE_ID as out_ECTL_TABLE_ID,
exp_ECTL_FIELDS.out_ECTL_END_DATE as out_ECTL_END_DATE,
exp_ECTL_FIELDS.out_CHK as out_CHK,
exp_ECTL_FIELDS.CHG_EFF_DT_lkup as CHG_EFF_DT_lkup,
exp_ECTL_FIELDS.source_record_id
FROM
exp_ECTL_FIELDS
WHERE exp_ECTL_FIELDS.out_CHK = ''NEW'' OR exp_ECTL_FIELDS.out_CHK = ''UPD'';


-- Component rtr_GROUP_NEW_OLD_RECORDS_UPDATE, Type ROUTER Output Group UPDATE
create or replace temp table RTR_GROUP_NEW_OLD_RECORDS_UPDATE as
SELECT
exp_ECTL_FIELDS.BIL_ACCOUNT_ID as BIL_ACCOUNT_ID,
exp_ECTL_FIELDS.BIL_ACCOUNT_NBR as BIL_ACCOUNT_NBR,
exp_ECTL_FIELDS.POLICY_NBR as POLICY_NBR,
exp_ECTL_FIELDS.BIL_PLAN_CD as BIL_PLAN_CD,
exp_ECTL_FIELDS.FEED_DT_ID as FEED_DT_ID,
exp_ECTL_FIELDS.LATE_IND_3YR as LATE_IND_3YR,
exp_ECTL_FIELDS.LATE_COUNT_1YR as LATE_COUNT_1YR,
exp_ECTL_FIELDS.LATE_COUNT_2YR as LATE_COUNT_2YR,
exp_ECTL_FIELDS.LATE_COUNT_3YR as LATE_COUNT_3YR,
exp_ECTL_FIELDS.LATE_COUNT_4YR as LATE_COUNT_4YR,
exp_ECTL_FIELDS.LATE_COUNT_5YR as LATE_COUNT_5YR,
exp_ECTL_FIELDS.TEN_DAY_LATE_COUNT as TEN_DAY_LATE_COUNT,
exp_ECTL_FIELDS.LOB as LOB,
exp_ECTL_FIELDS.MEM_CUST_TYPE as MEM_CUST_TYPE,
exp_ECTL_FIELDS.MEM_CUST_NBR as MEM_CUST_NBR,
exp_ECTL_FIELDS.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
exp_ECTL_FIELDS.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
exp_ECTL_FIELDS.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
exp_ECTL_FIELDS.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
exp_ECTL_FIELDS.out_ORIG_INS_TS as out_ORIG_INS_TS,
exp_ECTL_FIELDS.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
exp_ECTL_FIELDS.out_ECTL_TABLE_ID as out_ECTL_TABLE_ID,
exp_ECTL_FIELDS.out_ECTL_END_DATE as out_ECTL_END_DATE,
exp_ECTL_FIELDS.out_CHK as out_CHK,
exp_ECTL_FIELDS.CHG_EFF_DT_lkup as CHG_EFF_DT_lkup,
exp_ECTL_FIELDS.source_record_id
FROM
exp_ECTL_FIELDS
WHERE exp_ECTL_FIELDS.out_CHK = ''UPD'';


-- Component exp_TARGET_DATA_UPD, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_TARGET_DATA_UPD AS
(
SELECT
rtr_GROUP_NEW_OLD_RECORDS_UPDATE.BIL_ACCOUNT_ID as BIL_ACCOUNT_ID,
rtr_GROUP_NEW_OLD_RECORDS_UPDATE.BIL_ACCOUNT_NBR as BIL_ACCOUNT_NBR,
rtr_GROUP_NEW_OLD_RECORDS_UPDATE.POLICY_NBR as POLICY_NBR,
rtr_GROUP_NEW_OLD_RECORDS_UPDATE.BIL_PLAN_CD as BIL_PLAN_CD,
rtr_GROUP_NEW_OLD_RECORDS_UPDATE.FEED_DT_ID as FEED_DT_ID,
rtr_GROUP_NEW_OLD_RECORDS_UPDATE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
rtr_GROUP_NEW_OLD_RECORDS_UPDATE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
rtr_GROUP_NEW_OLD_RECORDS_UPDATE.out_ORIG_INS_TS as out_ORIG_INS_TS,
rtr_GROUP_NEW_OLD_RECORDS_UPDATE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
 TO_DATE ( to_char(  rtr_GROUP_NEW_OLD_RECORDS_UPDATE.FEED_DT_ID) , ''YYYY-MM-DD'' )  - 2  as out_CHG_EXP_DATE,
''UPD'' as out_ECTL_TX_CD,
rtr_GROUP_NEW_OLD_RECORDS_UPDATE.CHG_EFF_DT_lkup as CHG_EFF_DT_lkup,
rtr_GROUP_NEW_OLD_RECORDS_UPDATE.source_record_id
FROM
rtr_GROUP_NEW_OLD_RECORDS_UPDATE
);


-- Component exp_TARGET_DATA_INS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_TARGET_DATA_INS AS
(
SELECT
rtr_GROUP_NEW_OLD_RECORDS_INSERT.BIL_ACCOUNT_ID as BIL_ACCOUNT_ID,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.BIL_ACCOUNT_NBR as BIL_ACCOUNT_NBR,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.POLICY_NBR as POLICY_NBR,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.BIL_PLAN_CD as BIL_PLAN_CD,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.FEED_DT_ID as FEED_DT_ID,
 TO_DATE ( to_char( rtr_GROUP_NEW_OLD_RECORDS_INSERT.FEED_DT_ID) , ''YYYY-MM-DD'' )  - 1  as out_CHG_EFF_DT,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as out_CHG_EXP_DT,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.LATE_IND_3YR as LATE_IND_3YR,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.LATE_COUNT_1YR as LATE_COUNT_1YR,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.LATE_COUNT_2YR as LATE_COUNT_2YR,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.LATE_COUNT_3YR as LATE_COUNT_3YR,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.LATE_COUNT_4YR as LATE_COUNT_4YR,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.LATE_COUNT_5YR as LATE_COUNT_5YR,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.TEN_DAY_LATE_COUNT as TEN_DAY_LATE_COUNT,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.LOB as LOB,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.MEM_CUST_TYPE as MEM_CUST_TYPE,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.MEM_CUST_NBR as MEM_CUST_NBR,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.out_ORIG_INS_TS as out_ORIG_INS_TS,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
''NEW'' as out_ECTL_TX_CD,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as out_ECTL_END_DATE,
rtr_GROUP_NEW_OLD_RECORDS_INSERT.source_record_id
FROM
rtr_GROUP_NEW_OLD_RECORDS_INSERT
);


-- Component upd_ARS_BILL_INFO, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_ARS_BILL_INFO AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
exp_TARGET_DATA_UPD.BIL_ACCOUNT_ID as BIL_ACCOUNT_ID,
exp_TARGET_DATA_UPD.BIL_ACCOUNT_NBR as BIL_ACCOUNT_NBR,
exp_TARGET_DATA_UPD.POLICY_NBR as POLICY_NBR,
exp_TARGET_DATA_UPD.BIL_PLAN_CD as BIL_PLAN_CD,
exp_TARGET_DATA_UPD.FEED_DT_ID as FEED_DT_ID,
exp_TARGET_DATA_UPD.out_ORIG_INS_TS as out_ORIG_INS_TS,
exp_TARGET_DATA_UPD.CHG_EFF_DT_lkup as CHG_EFF_DT_lkup,
exp_TARGET_DATA_UPD.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
exp_TARGET_DATA_UPD.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
exp_TARGET_DATA_UPD.out_ECTL_TX_CD as out_ECTL_TX_CD,
exp_TARGET_DATA_UPD.out_CHG_EXP_DATE as out_CHG_EXP_DATE,
exp_TARGET_DATA_UPD.out_ECTL_BATCH_START_DATE as out_ECTL_END_DATE,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_TARGET_DATA_UPD
);


-- Component ARS_BILL_INFO_INS, Type TARGET 
INSERT INTO DB_T_CORE_PROD.ARS_BILL_INFO
(
BIL_ACCOUNT_ID,
BIL_ACCOUNT_NBR,
POL_NBR,
FEED_DT_ID,
CHG_EFF_DT,
CHG_EXP_DT,
BIL_PLAN_CD,
LATE_IND_3YR,
LATE_COUNT_1YR,
LATE_COUNT_2YR,
LATE_COUNT_3YR,
LATE_COUNT_4YR,
LATE_COUNT_5YR,
TEN_DAY_LATE_COUNT,
LOB,
MEMB_CUST_TYPE,
MEMB_CUST_NBR,
ECTL_BATCH_ID,
ECTL_ORIG_INS_TS,
ECTL_MODIFY_TS,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_PRGM_ID,
ECTL_TX_CD,
ECTL_START_DATE,
ECTL_END_DATE
)
SELECT
exp_TARGET_DATA_INS.BIL_ACCOUNT_ID as BIL_ACCOUNT_ID,
exp_TARGET_DATA_INS.BIL_ACCOUNT_NBR as BIL_ACCOUNT_NBR,
exp_TARGET_DATA_INS.POLICY_NBR as POL_NBR,
exp_TARGET_DATA_INS.FEED_DT_ID as FEED_DT_ID,
exp_TARGET_DATA_INS.out_CHG_EFF_DT as CHG_EFF_DT,
exp_TARGET_DATA_INS.out_CHG_EXP_DT as CHG_EXP_DT,
exp_TARGET_DATA_INS.BIL_PLAN_CD as BIL_PLAN_CD,
exp_TARGET_DATA_INS.LATE_IND_3YR as LATE_IND_3YR,
exp_TARGET_DATA_INS.LATE_COUNT_1YR as LATE_COUNT_1YR,
exp_TARGET_DATA_INS.LATE_COUNT_2YR as LATE_COUNT_2YR,
exp_TARGET_DATA_INS.LATE_COUNT_3YR as LATE_COUNT_3YR,
exp_TARGET_DATA_INS.LATE_COUNT_4YR as LATE_COUNT_4YR,
exp_TARGET_DATA_INS.LATE_COUNT_5YR as LATE_COUNT_5YR,
exp_TARGET_DATA_INS.TEN_DAY_LATE_COUNT as TEN_DAY_LATE_COUNT,
exp_TARGET_DATA_INS.LOB as LOB,
exp_TARGET_DATA_INS.MEM_CUST_TYPE as MEMB_CUST_TYPE,
exp_TARGET_DATA_INS.MEM_CUST_NBR as MEMB_CUST_NBR,
exp_TARGET_DATA_INS.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_TARGET_DATA_INS.out_ORIG_INS_TS as ECTL_ORIG_INS_TS,
exp_TARGET_DATA_INS.out_ORIG_INS_TS as ECTL_MODIFY_TS,
exp_TARGET_DATA_INS.out_ECTL_SRC_ID as ECTL_SRC_ID,
exp_TARGET_DATA_INS.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_TARGET_DATA_INS.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_TARGET_DATA_INS.out_ECTL_TX_CD as ECTL_TX_CD,
exp_TARGET_DATA_INS.out_ECTL_BATCH_START_DATE as ECTL_START_DATE,
exp_TARGET_DATA_INS.out_ECTL_END_DATE as ECTL_END_DATE
FROM
exp_TARGET_DATA_INS;


-- Component ARS_BILL_INFO_UPD, Type TARGET 
INSERT INTO DB_T_CORE_PROD.ARS_BILL_INFO
(
POL_NBR,
CHG_EFF_DT,
CHG_EXP_DT,
BIL_PLAN_CD,
ECTL_BATCH_ID,
ECTL_MODIFY_TS,
ECTL_PRGM_ID,
ECTL_TX_CD,
ECTL_END_DATE
)
SELECT
upd_ARS_BILL_INFO.POLICY_NBR as POL_NBR,
upd_ARS_BILL_INFO.CHG_EFF_DT_lkup as CHG_EFF_DT,
upd_ARS_BILL_INFO.out_CHG_EXP_DATE as CHG_EXP_DT,
upd_ARS_BILL_INFO.BIL_PLAN_CD as BIL_PLAN_CD,
upd_ARS_BILL_INFO.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
upd_ARS_BILL_INFO.out_ORIG_INS_TS as ECTL_MODIFY_TS,
upd_ARS_BILL_INFO.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
upd_ARS_BILL_INFO.out_ECTL_TX_CD as ECTL_TX_CD,
upd_ARS_BILL_INFO.out_ECTL_END_DATE as ECTL_END_DATE
FROM
upd_ARS_BILL_INFO
WHERE UPDATE_STRATEGY_ACTION = 0;

/* Perform Updates */
MERGE INTO DB_T_CORE_PROD.ARS_BILL_INFO
USING upd_ARS_BILL_INFO ON (UPDATE_STRATEGY_ACTION = 1  )
WHEN MATCHED THEN UPDATE
SET
POL_NBR = upd_ARS_BILL_INFO.POLICY_NBR,
CHG_EFF_DT = upd_ARS_BILL_INFO.CHG_EFF_DT_lkup,
CHG_EXP_DT = upd_ARS_BILL_INFO.out_CHG_EXP_DATE,
BIL_PLAN_CD = upd_ARS_BILL_INFO.BIL_PLAN_CD,
ECTL_BATCH_ID = upd_ARS_BILL_INFO.out_ECTL_BATCH_ID,
ECTL_MODIFY_TS = upd_ARS_BILL_INFO.out_ORIG_INS_TS,
ECTL_PRGM_ID = upd_ARS_BILL_INFO.out_ECTL_PRGM_ID,
ECTL_TX_CD = upd_ARS_BILL_INFO.out_ECTL_TX_CD,
ECTL_END_DATE = upd_ARS_BILL_INFO.out_ECTL_END_DATE
;


END; ';