-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_CAT_EXPOS_BASE("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE BATCH_ACTIVE_IND varchar;
ACT_PROJ_ID varchar;
PMMAPPINGNAME varchar;
PMCAT_EXPOS_BASETABLENAME varchar;
BEGIN 

PMMAPPINGNAME:=''M_CAT_EXPOS_BASE''; 
PMCAT_EXPOS_BASETABLENAME:='' ''; 
BATCH_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
ACT_PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 

-- Component SQ_STG_BENFIELD_BASE_INFO, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_STG_BENFIELD_BASE_INFO AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as COMP_CODE,
$2 as POLICY_NBR,
$3 as LOB_CODE,
$4 as STATE_NBR,
$5 as CNTY_NBR,
$6 as CITY_NAME,
$7 as ZIP_CODE,
$8 as STREET_ADDRESS,
$9 as PREMIUM_AMT,
$10 as POL_LIMIT,
$11 as DEDUCT_AMT,
$12 as BLDG_LIMIT,
$13 as OTHR_STR_LIMIT,
$14 as CONTENTS_LIMIT,
$15 as CONTENTS_GRADE,
$16 as LOSS_OF_USE,
$17 as INS_TO_VALUE,
$18 as NBR_STORIES,
$19 as YEAR_BUILT,
$20 as OCCUPANCY_TYPE,
$21 as CONSTR_CLASS,
$22 as RATING_ZONE,
$23 as FEED_DT,
$24 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
STG_BENFIELD_BASE_INFO.COMP_CODE,
STG_BENFIELD_BASE_INFO.POLICY_NBR,
STG_BENFIELD_BASE_INFO.LOB_CODE,
STG_BENFIELD_BASE_INFO.STATE_NBR,
STG_BENFIELD_BASE_INFO.CNTY_NBR,
STG_BENFIELD_BASE_INFO.CITY_NAME,
STG_BENFIELD_BASE_INFO.ZIP_CODE,
STG_BENFIELD_BASE_INFO.STREET_ADDRESS,
STG_BENFIELD_BASE_INFO.PREMIUM_AMT,
STG_BENFIELD_BASE_INFO.POL_LIMIT,
STG_BENFIELD_BASE_INFO.DEDUCT_AMT,
STG_BENFIELD_BASE_INFO.BLDG_LIMIT,
STG_BENFIELD_BASE_INFO.OTHR_STR_LIMIT,
STG_BENFIELD_BASE_INFO.CONTENTS_LIMIT,
STG_BENFIELD_BASE_INFO.CONTENTS_GRADE,
STG_BENFIELD_BASE_INFO.LOSS_OF_USE,
STG_BENFIELD_BASE_INFO.INS_TO_VALUE,
STG_BENFIELD_BASE_INFO.NBR_STORIES,
STG_BENFIELD_BASE_INFO.YEAR_BUILT,
STG_BENFIELD_BASE_INFO.OCCUPANCY_TYPE,
STG_BENFIELD_BASE_INFO.CONSTR_CLASS,
STG_BENFIELD_BASE_INFO.RATING_ZONE,
STG_BENFIELD_BASE_INFO.FEED_DT
FROM DB_T_STAG_PROD.STG_BENFIELD_BASE_INFO
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
TO_CHAR ( SQ_STG_BENFIELD_BASE_INFO.COMP_CODE ) as COMP_CODE,
TO_CHAR ( SQ_STG_BENFIELD_BASE_INFO.POLICY_NBR ) as POLICY_NBR,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.LOB_CODE), 0) as LOB_CODE,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.STATE_NBR), 0) as STATE_NBR,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.CNTY_NBR), 0) as CNTY_NBR,
TO_CHAR ( SQ_STG_BENFIELD_BASE_INFO.CITY_NAME ) as CITY_NAME,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.ZIP_CODE), 0) as ZIP_CODE,
TO_CHAR ( SQ_STG_BENFIELD_BASE_INFO.STREET_ADDRESS ) as STREET_ADDRESS,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.PREMIUM_AMT), 0) as PREMIUM_AMT,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.POL_LIMIT), 0) as POL_LIMIT,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.DEDUCT_AMT), 0) as DEDUCT_AMT,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.BLDG_LIMIT), 0) as BLDG_LIMIT,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.OTHR_STR_LIMIT), 0) as OTHR_STR_LIMIT,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.CONTENTS_LIMIT), 0) as CONTENTS_LIMIT,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.CONTENTS_GRADE), 0) as CONTENTS_GRADE,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.LOSS_OF_USE), 0) as LOSS_OF_USE,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.INS_TO_VALUE), 0) as INS_TO_VALUE,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.NBR_STORIES), 0) as NBR_STORIES,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.YEAR_BUILT), 0) as YEAR_BUILT,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.OCCUPANCY_TYPE), 0) as OCCUPANCY_TYPE,
IFNULL(TRY_TO_DECIMAL(SQ_STG_BENFIELD_BASE_INFO.CONSTR_CLASS), 0) as CONSTR_CLASS,
TO_CHAR ( SQ_STG_BENFIELD_BASE_INFO.RATING_ZONE ) as RATING_ZONE,
SQ_STG_BENFIELD_BASE_INFO.FEED_DT as FEED_DT,
SQ_STG_BENFIELD_BASE_INFO.source_record_id
FROM
SQ_STG_BENFIELD_BASE_INFO
);


-- Component LKPTRANS, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKPTRANS AS
(
SELECT
LKP.COMP_CODE_lkup,
EXPTRANS.source_record_id,
ROW_NUMBER() OVER(PARTITION BY EXPTRANS.source_record_id ORDER BY LKP.COMP_CODE_lkup asc,LKP.POLICY_NBR_lkup asc,LKP.LOB_CODE_lkup asc,LKP.STATE_NBR_lkup asc,LKP.CNTY_NBR_lkup asc,LKP.CITY_NAME_lkup asc,LKP.ZIP_CODE_lkup asc,LKP.STREET_ADDRESS_lkup asc,LKP.PREMIUM_AMT_lkup asc,LKP.POL_LIMIT_lkup asc,LKP.DEDUCT_AMT_lkup asc,LKP.BLDG_LIMIT_lkup asc,LKP.OTHR_STR_LIMIT_lkup asc,LKP.CONTENTS_LIMIT_lkup asc,LKP.CONTENTS_GRADE_lkup asc,LKP.LOSS_OF_USE_lkup asc,LKP.INS_TO_VALUE_lkup asc,LKP.NBR_STORIES_lkup asc,LKP.YEAR_BUILT_lkup asc,LKP.OCCUPANCY_TYPE_lkup asc,LKP.CONSTR_CLASS_lkup asc,LKP.RATING_ZONE_lkup asc,LKP.FEED_DT_lkup asc) RNK
FROM
EXPTRANS
LEFT JOIN (
SELECT  CAT_EXPOS_BASE.COMP_CODE as COMP_CODE_lkup , CAT_EXPOS_BASE.POLICY_NBR as POLICY_NBR_lkup, 
CAT_EXPOS_BASE.LOB_CODE as LOB_CODE_lkup, CAT_EXPOS_BASE.STATE_NBR as STATE_NBR_lkup, 
CAT_EXPOS_BASE.CNTY_NBR as CNTY_NBR_lkup, CAT_EXPOS_BASE.CITY_NAME as CITY_NAME_lkup, CAT_EXPOS_BASE.ZIP_CODE as ZIP_CODE_lkup, 
CAT_EXPOS_BASE.STREET_ADDRESS as STREET_ADDRESS_lkup, CAT_EXPOS_BASE.PREMIUM_AMT as PREMIUM_AMT_lkup, 
CAT_EXPOS_BASE.POL_LIMIT as POL_LIMIT_lkup, CAT_EXPOS_BASE.DEDUCT_AMT as DEDUCT_AMT_lkup, 
CAT_EXPOS_BASE.BLDG_LIMIT as BLDG_LIMIT_lkup, CAT_EXPOS_BASE.OTHR_STR_LIMIT as OTHR_STR_LIMIT_lkup, 
CAT_EXPOS_BASE.CONTENTS_LIMIT as CONTENTS_LIMIT_lkup, CAT_EXPOS_BASE.CONTENTS_GRADE as CONTENTS_GRADE_lkup, 
CAT_EXPOS_BASE.LOSS_OF_USE as LOSS_OF_USE_lkup, CAT_EXPOS_BASE.INS_TO_VALUE as INS_TO_VALUE_lkup, 
CAT_EXPOS_BASE.NBR_STORIES as NBR_STORIES_lkup, CAT_EXPOS_BASE.YEAR_BUILT as YEAR_BUILT_lkup, 
CAT_EXPOS_BASE.OCCUPANCY_TYPE as OCCUPANCY_TYPE_lkup, CAT_EXPOS_BASE.CONSTR_CLASS as CONSTR_CLASS_lkup, 
CAT_EXPOS_BASE.RATING_ZONE as RATING_ZONE_lkup, CAT_EXPOS_BASE.FEED_DT as FEED_DT_lkup
FROM DB_T_ML_PROD.CAT_EXPOS_BASE
) LKP ON LKP.COMP_CODE_lkup = EXPTRANS.COMP_CODE AND LKP.POLICY_NBR_lkup = EXPTRANS.POLICY_NBR AND LKP.LOB_CODE_lkup = EXPTRANS.LOB_CODE AND LKP.STATE_NBR_lkup = EXPTRANS.STATE_NBR AND LKP.CNTY_NBR_lkup = EXPTRANS.CNTY_NBR AND LKP.CITY_NAME_lkup = EXPTRANS.CITY_NAME AND LKP.ZIP_CODE_lkup = EXPTRANS.ZIP_CODE AND LKP.STREET_ADDRESS_lkup = EXPTRANS.STREET_ADDRESS AND LKP.PREMIUM_AMT_lkup = EXPTRANS.PREMIUM_AMT AND LKP.POL_LIMIT_lkup = EXPTRANS.POL_LIMIT AND LKP.DEDUCT_AMT_lkup = EXPTRANS.DEDUCT_AMT AND LKP.BLDG_LIMIT_lkup = EXPTRANS.BLDG_LIMIT AND LKP.OTHR_STR_LIMIT_lkup = EXPTRANS.OTHR_STR_LIMIT AND LKP.CONTENTS_LIMIT_lkup = EXPTRANS.CONTENTS_LIMIT AND LKP.CONTENTS_GRADE_lkup = EXPTRANS.CONTENTS_GRADE AND LKP.LOSS_OF_USE_lkup = EXPTRANS.LOSS_OF_USE AND LKP.INS_TO_VALUE_lkup = EXPTRANS.INS_TO_VALUE AND LKP.NBR_STORIES_lkup = EXPTRANS.NBR_STORIES AND LKP.YEAR_BUILT_lkup = EXPTRANS.YEAR_BUILT AND LKP.OCCUPANCY_TYPE_lkup = EXPTRANS.OCCUPANCY_TYPE AND LKP.CONSTR_CLASS_lkup = EXPTRANS.CONSTR_CLASS AND LKP.RATING_ZONE_lkup = EXPTRANS.RATING_ZONE AND LKP.FEED_DT_lkup = EXPTRANS.FEED_DT
QUALIFY RNK = 1
);


-- Component EXPTRANS1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS1 AS
(
SELECT
EXPTRANS.COMP_CODE as COMP_CODE,
EXPTRANS.POLICY_NBR as POLICY_NBR,
EXPTRANS.LOB_CODE as LOB_CODE,
EXPTRANS.STATE_NBR as STATE_NBR,
EXPTRANS.CNTY_NBR as CNTY_NBR,
EXPTRANS.CITY_NAME as CITY_NAME,
EXPTRANS.ZIP_CODE as ZIP_CODE,
EXPTRANS.STREET_ADDRESS as STREET_ADDRESS,
EXPTRANS.PREMIUM_AMT as PREMIUM_AMT,
EXPTRANS.POL_LIMIT as POL_LIMIT,
EXPTRANS.DEDUCT_AMT as DEDUCT_AMT,
EXPTRANS.BLDG_LIMIT as BLDG_LIMIT,
EXPTRANS.OTHR_STR_LIMIT as OTHR_STR_LIMIT,
EXPTRANS.CONTENTS_LIMIT as CONTENTS_LIMIT,
EXPTRANS.CONTENTS_GRADE as CONTENTS_GRADE,
EXPTRANS.LOSS_OF_USE as LOSS_OF_USE,
EXPTRANS.INS_TO_VALUE as INS_TO_VALUE,
EXPTRANS.NBR_STORIES as NBR_STORIES,
EXPTRANS.YEAR_BUILT as YEAR_BUILT,
EXPTRANS.OCCUPANCY_TYPE as OCCUPANCY_TYPE,
EXPTRANS.CONSTR_CLASS as CONSTR_CLASS,
EXPTRANS.RATING_ZONE as RATING_ZONE,
EXPTRANS.FEED_DT as FEED_DT,
CASE WHEN LKPTRANS.COMP_CODE_lkup IS NULL THEN ''NEW'' ELSE ''REJ'' END as out_CHK,
EXPTRANS.source_record_id
FROM
EXPTRANS
INNER JOIN LKPTRANS ON EXPTRANS.source_record_id = LKPTRANS.source_record_id
);


-- Component FILTRANS, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE FILTRANS AS
(
SELECT
EXPTRANS1.COMP_CODE as COMP_CODE,
EXPTRANS1.POLICY_NBR as POLICY_NBR,
EXPTRANS1.LOB_CODE as LOB_CODE,
EXPTRANS1.STATE_NBR as STATE_NBR,
EXPTRANS1.CNTY_NBR as CNTY_NBR,
EXPTRANS1.CITY_NAME as CITY_NAME,
EXPTRANS1.ZIP_CODE as ZIP_CODE,
EXPTRANS1.STREET_ADDRESS as STREET_ADDRESS,
EXPTRANS1.PREMIUM_AMT as PREMIUM_AMT,
EXPTRANS1.POL_LIMIT as POL_LIMIT,
EXPTRANS1.DEDUCT_AMT as DEDUCT_AMT,
EXPTRANS1.BLDG_LIMIT as BLDG_LIMIT,
EXPTRANS1.OTHR_STR_LIMIT as OTHR_STR_LIMIT,
EXPTRANS1.CONTENTS_LIMIT as CONTENTS_LIMIT,
EXPTRANS1.CONTENTS_GRADE as CONTENTS_GRADE,
EXPTRANS1.LOSS_OF_USE as LOSS_OF_USE,
EXPTRANS1.INS_TO_VALUE as INS_TO_VALUE,
EXPTRANS1.NBR_STORIES as NBR_STORIES,
EXPTRANS1.YEAR_BUILT as YEAR_BUILT,
EXPTRANS1.OCCUPANCY_TYPE as OCCUPANCY_TYPE,
EXPTRANS1.CONSTR_CLASS as CONSTR_CLASS,
EXPTRANS1.RATING_ZONE as RATING_ZONE,
EXPTRANS1.FEED_DT as FEED_DT,
EXPTRANS1.out_CHK as out_CHK,
EXPTRANS1.source_record_id
FROM
EXPTRANS1
WHERE EXPTRANS1.out_CHK = ''NEW''
);


-- Component EXPTRANS2, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS2 AS
(
SELECT
FILTRANS.COMP_CODE as COMP_CODE,
FILTRANS.POLICY_NBR as POLICY_NBR,
FILTRANS.LOB_CODE as LOB_CODE,
FILTRANS.STATE_NBR as STATE_NBR,
FILTRANS.CNTY_NBR as CNTY_NBR,
FILTRANS.CITY_NAME as CITY_NAME,
FILTRANS.ZIP_CODE as ZIP_CODE,
FILTRANS.STREET_ADDRESS as STREET_ADDRESS,
FILTRANS.PREMIUM_AMT as PREMIUM_AMT,
FILTRANS.POL_LIMIT as POL_LIMIT,
FILTRANS.DEDUCT_AMT as DEDUCT_AMT,
FILTRANS.BLDG_LIMIT as BLDG_LIMIT,
FILTRANS.OTHR_STR_LIMIT as OTHR_STR_LIMIT,
FILTRANS.CONTENTS_LIMIT as CONTENTS_LIMIT,
FILTRANS.CONTENTS_GRADE as CONTENTS_GRADE,
FILTRANS.LOSS_OF_USE as LOSS_OF_USE,
FILTRANS.INS_TO_VALUE as INS_TO_VALUE,
FILTRANS.NBR_STORIES as NBR_STORIES,
FILTRANS.YEAR_BUILT as YEAR_BUILT,
FILTRANS.OCCUPANCY_TYPE as OCCUPANCY_TYPE,
FILTRANS.CONSTR_CLASS as CONSTR_CLASS,
FILTRANS.RATING_ZONE as RATING_ZONE,
FILTRANS.FEED_DT as FEED_DT,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
:ACT_PROJ_ID as out_ACT_PROJ_ID,
:PMMappingName as out_PRGM_NM,
:PMCAT_EXPOS_BASETableName as out_TABLE_NM,
:ACT_PROJ_ID as IN_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as IN_BATCH_ACTIVE_IND,
''m_STG_FIN_CLM'' IN_PRGM_NM,
null IN_TABLE_NM,
FILTRANS.source_record_id
FROM
FILTRANS
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''EXPTRANS2'');

-- Component EXPTRANS3, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS3 AS
(
SELECT
EXPTRANS2.COMP_CODE as COMP_CODE,
EXPTRANS2.POLICY_NBR as POLICY_NBR,
EXPTRANS2.LOB_CODE as LOB_CODE,
EXPTRANS2.STATE_NBR as STATE_NBR,
EXPTRANS2.CNTY_NBR as CNTY_NBR,
EXPTRANS2.CITY_NAME as CITY_NAME,
EXPTRANS2.ZIP_CODE as ZIP_CODE,
EXPTRANS2.STREET_ADDRESS as STREET_ADDRESS,
EXPTRANS2.PREMIUM_AMT as PREMIUM_AMT,
EXPTRANS2.POL_LIMIT as POL_LIMIT,
EXPTRANS2.DEDUCT_AMT as DEDUCT_AMT,
EXPTRANS2.BLDG_LIMIT as BLDG_LIMIT,
EXPTRANS2.OTHR_STR_LIMIT as OTHR_STR_LIMIT,
EXPTRANS2.CONTENTS_LIMIT as CONTENTS_LIMIT,
EXPTRANS2.CONTENTS_GRADE as CONTENTS_GRADE,
EXPTRANS2.LOSS_OF_USE as LOSS_OF_USE,
EXPTRANS2.INS_TO_VALUE as INS_TO_VALUE,
EXPTRANS2.NBR_STORIES as NBR_STORIES,
EXPTRANS2.YEAR_BUILT as YEAR_BUILT,
EXPTRANS2.OCCUPANCY_TYPE as OCCUPANCY_TYPE,
EXPTRANS2.CONSTR_CLASS as CONSTR_CLASS,
EXPTRANS2.RATING_ZONE as RATING_ZONE,
EXPTRANS2.FEED_DT as FEED_DT,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
''NEW'' as out_ECTL_TX_CD,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as out_ECTL_END_DATE,
EXPTRANS2.source_record_id
FROM
EXPTRANS2
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON EXPTRANS2.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
);


-- Component CAT_EXPOS_BASE, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE CAT_EXPOS_BASE AS
(
SELECT
EXPTRANS3.COMP_CODE as COMP_CODE,
EXPTRANS3.POLICY_NBR as POLICY_NBR,
EXPTRANS3.LOB_CODE as LOB_CODE,
EXPTRANS3.STATE_NBR as STATE_NBR,
EXPTRANS3.CNTY_NBR as CNTY_NBR,
EXPTRANS3.CITY_NAME as CITY_NAME,
EXPTRANS3.ZIP_CODE as ZIP_CODE,
EXPTRANS3.STREET_ADDRESS as STREET_ADDRESS,
EXPTRANS3.PREMIUM_AMT as PREMIUM_AMT,
EXPTRANS3.POL_LIMIT as POL_LIMIT,
EXPTRANS3.DEDUCT_AMT as DEDUCT_AMT,
EXPTRANS3.BLDG_LIMIT as BLDG_LIMIT,
EXPTRANS3.OTHR_STR_LIMIT as OTHR_STR_LIMIT,
EXPTRANS3.CONTENTS_LIMIT as CONTENTS_LIMIT,
EXPTRANS3.CONTENTS_GRADE as CONTENTS_GRADE,
EXPTRANS3.LOSS_OF_USE as LOSS_OF_USE,
EXPTRANS3.INS_TO_VALUE as INS_TO_VALUE,
EXPTRANS3.NBR_STORIES as NBR_STORIES,
EXPTRANS3.YEAR_BUILT as YEAR_BUILT,
EXPTRANS3.OCCUPANCY_TYPE as OCCUPANCY_TYPE,
EXPTRANS3.CONSTR_CLASS as CONSTR_CLASS,
EXPTRANS3.RATING_ZONE as RATING_ZONE,
EXPTRANS3.FEED_DT as FEED_DT,
EXPTRANS3.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
EXPTRANS3.out_ORIG_INS_TS as ECTL_ORIG_INS_TS,
EXPTRANS3.out_ECTL_SRC_ID as ECTL_SRC_ID,
EXPTRANS3.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
EXPTRANS3.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
EXPTRANS3.out_ECTL_TX_CD as ECTL_TX_CD,
EXPTRANS3.out_ECTL_BATCH_START_DATE as ECTL_START_DATE,
EXPTRANS3.out_ECTL_END_DATE as ECTL_END_DATE
FROM
EXPTRANS3
);


-- Component CAT_EXPOS_BASE, Type EXPORT_DATA Exporting data
;


END; ';