-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_LOAD_FED_DAILY_SUMMARY2025("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_Shortcut_to_STG_FED_MSTR_TRG, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_STG_FED_MSTR_TRG AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as FEED_DT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT a.CALENDAR_DATE, b.FEED_IND
FROM DB_V_PROD_SMNTC.calendar a, DB_T_STAG_PROD.stg_fed_mstr_trg b
WHERE CALENDAR_DATE > (SELECT COALESCE( MAX(CAL_DATE), CAST(''2009-05-31'' AS DATE)) FROM DB_T_CORE_PROD.FED_DAILY_SUMMARY)
AND CALENDAR_DATE <=  (SELECT FEED_DT FROM DB_T_STAG_PROD.STG_FED_MSTR_TRG)
AND b.FEED_IND = ''D''
ORDER BY 1
) SRC
)
);


-- Component exp_convert_date, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_convert_date AS
(
SELECT
lpad ( to_char ( DATE_PART(''YYYY'', TO_TIMESTAMP(SQ_Shortcut_to_STG_FED_MSTR_TRG.FEED_DT)) ) , 4 , ''0'' ) || ''-'' || lpad ( to_char ( DATE_PART(''MM'', TO_TIMESTAMP(SQ_Shortcut_to_STG_FED_MSTR_TRG.FEED_DT)) ) , 2 , ''0'' ) || ''-'' || lpad ( to_char ( DATE_PART(''DD'', TO_TIMESTAMP(SQ_Shortcut_to_STG_FED_MSTR_TRG.FEED_DT)) ) , 2 , ''0'' ) as out_DATE,
SQ_Shortcut_to_STG_FED_MSTR_TRG.source_record_id
FROM
SQ_Shortcut_to_STG_FED_MSTR_TRG
);


-- Component LOAD_FED_DAILY_SUMMARY, Type STORED_PROCEDURE 
--CREATE OR REPLACE TEMPORARY TABLE LOAD_FED_DAILY_SUMMARY AS
--(
--CREATE OR REPLACE TEMPORARY TABLE LOAD_FED_DAILY_SUMMARY AS
--(
-- WARNING: Stored Procedure node is not supported, manual conversion required. Commented call text below:
-- LOAD_FED_DAILY_SUMMARY
--)
--);


-- Component exp_Check_Status, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Check_Status AS
(
SELECT
LOAD_FED_DAILY_SUMMARY.STATUS as STATUS,
CASE WHEN LOAD_FED_DAILY_SUMMARY.STATUS = ''1'' THEN RAISE_ERROR(''Error while executing stored procedure LOAD_MEMBER_SUMMARY'') ELSE $3 END as out_Abort,
LOAD_FED_DAILY_SUMMARY.source_record_id
FROM
LOAD_FED_DAILY_SUMMARY
);


-- Component flt_status, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE flt_status AS
(
SELECT
exp_Check_Status.STATUS as STATUS,
exp_Check_Status.source_record_id
FROM
exp_Check_Status
WHERE CASE WHEN exp_Check_Status.STATUS = ''X'' THEN TRUE ELSE FALSE END
);


-- Component Shortcut_to_STG_FED_MSTR_TRG1, Type TARGET 
INSERT INTO DB_T_STAG_PROD.STG_FED_MSTR_TRG
(
REC_COUNT
)
SELECT
flt_status.STATUS as REC_COUNT
FROM
flt_status;


-- Component Shortcut_to_STG_FED_MSTR_TRG1, Type Post SQL 
INSERT INTO FED_DAILY_SUMMARY
SELECT calendar_date, NULL AS county_cd, -1 AS pac_type, 0 AS new_cnt, 0 AS rein_cnt, 0 AS ren_cnt, 0 AS canc_cnt, 0 AS billed_cnt, 0  AS del_cnt
FROM (
SELECT calendar_date FROM sys_calendar.calendar 
WHERE calendar_date > (SELECT COALESCE(MAX(cal_date), DATE ''1992-12-31'') FROM fed_daily_summary) AND calendar_date <= (SELECT  FEED_DT FROM stg_fed_mstr_trg ) 
AND calendar_date <= ''2009-05-31'') x;

INSERT INTO member_summary_top
SELECT  
M.CAL_DATE AS CAL_DATE,
EXTRACT(YEAR FROM M.CAL_DATE)*10000 + EXTRACT(MONTH FROM M.CAL_DATE)*100+EXTRACT(DAY FROM M.CAL_DATE) AS CAL_ID,
CASE WHEN EXTRACT(MONTH FROM M.CAL_DATE) BETWEEN 7 AND 12
THEN
EXTRACT(MONTH FROM M.CAL_DATE)-6
ELSE
EXTRACT(MONTH FROM M.CAL_DATE)+6
END AS MONTH_ID,
CAST((M.CAL_DATE ) AS CHAR(3)) AS MONTH_DESC,
CASE WHEN EXTRACT(MONTH FROM M.CAL_DATE) BETWEEN 7 AND 12
THEN
EXTRACT(YEAR FROM M.CAL_DATE)+1
ELSE
EXTRACT(YEAR FROM M.CAL_DATE)
END AS YEAR_ID, 
CASE WHEN EXTRACT(MONTH FROM M.CAL_DATE) BETWEEN 7 AND 12
THEN
SUBSTR(CAST (EXTRACT(YEAR FROM M.CAL_DATE) AS CHAR(4)),3,2) || '' - ''|| SUBSTR(CAST((EXTRACT(YEAR FROM M.CAL_DATE)+1) AS CHAR(4)),3,2)
ELSE
SUBSTR(CAST((EXTRACT(YEAR FROM M.CAL_DATE)-1) AS CHAR(4)),3,2) || '' - ''|| SUBSTR(CAST(EXTRACT(YEAR FROM M.CAL_DATE) AS CHAR(4)),3,2)
END AS YEAR_DESC,
M.PAC_TYPE AS PAC_TYPE,
CASE WHEN M.PAC_TYPE = ''0'' THEN ''NON PAC''
WHEN M.PAC_TYPE <> ''0'' THEN ''PAC''
END AS PAC_DESC,
CASE WHEN M.PAC_TYPE = ''0'' THEN ''NONE''
WHEN M.PAC_TYPE = ''1'' THEN ''(''
WHEN M.PAC_TYPE = ''2'' THEN ''''
WHEN M.PAC_TYPE = ''3'' THEN ''''
END AS PAC_TYPE_DESC,
SUM(M.MEMB_COUNT) AS MEMB_COUNT,
ZEROIFNULL(SUM(CASE WHEN F.COUNTY_CD IS NOT NULL THEN M.MEMB_COUNT END)) AS INFORCE_MEMB_COUNT,
ZEROIFNULL(SUM(F.NEW_CNT)) AS NEW_CNT,
ZEROIFNULL(SUM(F.REIN_CNT)) AS REIN_CNT,
ZEROIFNULL(SUM(F.REN_CNT)) AS REN_CNT,
ZEROIFNULL(SUM(F.CANC_CNT)) AS CANC_CNT,
ZEROIFNULL(SUM(CASE WHEN F.COUNTY_CD IS NOT NULL THEN M.BILLED_MEMB_COUNT END)) AS BILLED_MEMB_COUNT
FROM 
(SELECT CAL_DATE, COUNTY_CD, PAC_TYPE, SUM(CASE WHEN STATUS_CD IN (''0'',''1'',''9'') AND MEMB_TYPE IN (''A'',''C'') AND REBILLED = ''N'' THEN MEMB_COUNT END)  AS MEMB_COUNT,SUM(CASE WHEN STATUS_CD = ''1'' AND MEMB_TYPE IN (''A'',''C'') THEN MEMB_COUNT END) BILLED_MEMB_COUNT FROM 
MEMBER_SUMMARY 
WHERE cal_date > (SELECT COALESCE(MAX(cal_date), DATE ''1992-12-31'') FROM member_summary_top)
GROUP BY 
CAL_DATE, COUNTY_CD, PAC_TYPE) M LEFT OUTER JOIN 
FED_DAILY_SUMMARY F ON 
F.CAL_DATE = M.CAL_DATE
AND F.COUNTY_CD = M.COUNTY_CD
AND F.PAC_TYPE = M.PAC_TYPE
GROUP BY 1,2,3,4,5,6,7,8;

INSERT INTO MEMBER_SUMMARY_AGG
SELECT CAL_DATE, CAL_DT, COUNTY_CD, PAC_TYPE, SUM(MEMB_COUNT)
FROM MEMBER_SUMMARY
WHERE REBILLED = ''N''
AND STATUS_CD IN (0, 1, 9)
AND MEMB_TYPE IN (''A'', ''C'')
AND CAL_DATE > (SELECT COALESCE(MAX(cal_date), DATE ''1992-12-31'') FROM MEMBER_SUMMARY_AGG)
GROUP BY 1, 2, 3, 4;

UPDATE ECTL_PRGM_PARAM SET ECTL_PARAM_VALUE = CAST(STG_FED_MSTR_TRG.FEED_DT AS VARCHAR(10))  
WHERE ECTL_PRGM_ID = 0 AND ECTL_PARAM_ID = 7;

--UPDATE DB_T_STAG_R1_DEV.ECTL_PRGM_PARAM SET ECTL_PARAM_VALUE = CAST(DB_T_STAG_R1_DEV.STG_FED_MSTR_TRG.FEED_DT AS VARCHAR(10))  
--WHERE ECTL_PRGM_ID = 0 AND ECTL_PARAM_ID = 7;


END; ';