-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_MEMBER_COMMODITY("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE PMMAPPINGNAME varchar;
BEGIN 

PMMAPPINGNAME:=''M_MEMBER_COMMODITY'';

-- Component SQ_Shortcut_to_MEMBER, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_MEMBER AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMB_SKEY,
$2 as MEMBER_NBR,
$3 as COMM_CD1,
$4 as COMM_CD2,
$5 as COMM_CD3,
$6 as COMM_CD4,
$7 as COMM_CD5,
$8 as LAST_UPDATE_TS,
$9 as flag,
$10 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
select 
SQ1.LKP_MEMB_SKEY,
SQ1.MEMBER_NBR,
SQ1.COMM_CD1,
SQ1.COMM_CD2,
SQ1.COMM_CD3,
SQ1.COMM_CD4,
SQ1.COMM_CD5,
SQ1.LAST_UPDATE_TS,
SQ1.flag

from
(
select 

RANK() OVER (PARTITION BY MEMBER_NBR ORDER BY LAST_UPDATE_TS  ASC) rnk,
 
 CONCAT(COALESCE(LAG(SQ.COMM_CD1,1,null) OVER ( partition by SQ.MEMBER_NBR
 order BY SQ.LAST_UPDATE_TS),''''),
 COALESCE(LAG(SQ.COMM_CD2,1,null) OVER ( partition by SQ.MEMBER_NBR
 order BY SQ.LAST_UPDATE_TS),'''') ,
 COALESCE(LAG(SQ.COMM_CD3,1,null) OVER (partition by SQ.MEMBER_NBR
 order BY SQ.LAST_UPDATE_TS),''''),
 COALESCE(LAG(SQ.COMM_CD4,1,null) OVER (partition by SQ.MEMBER_NBR
 order BY SQ.LAST_UPDATE_TS),''''),
 COALESCE(LAG(SQ.COMM_CD5,1,null) OVER (partition by SQ.MEMBER_NBR
 order BY SQ.LAST_UPDATE_TS),'''')
 
 ) as PREV_COMM_VAL,
 
SQ.MEMBER_NBR,
SQ.COMM_CD1,
SQ.COMM_CD2,
SQ.COMM_CD3,
SQ.COMM_CD4,
SQ.COMM_CD5,
SQ.LAST_UPDATE_TS,
/*LKP_MEMB_MSTR*/

MEM_MSTR.MEMB_SKEY as LKP_MEMB_SKEY,
/*LKP_TGT_MEMBER_COMM*/
TGT_MEMBER_COMM.MEMB_SKEY as TGT_MEMB_SKEY,
TGT_MEMBER_COMM.COMM_CD1 as TGT_COMM_CD1,
TGT_MEMBER_COMM.COMM_CD2 as TGT_COMM_CD2,
TGT_MEMBER_COMM.COMM_CD3 as TGT_COMM_CD3,
TGT_MEMBER_COMM.COMM_CD4 as TGT_COMM_CD4,
TGT_MEMBER_COMM.COMM_CD5 as TGT_COMM_CD5,
TGT_MEMBER_COMM.COMM_EFF_DT as TGT_COMM_EFF_DT,
TGT_MEMBER_COMM.COMM_EXP_DT as TGT_COMM_EXP_DT,
TGT_MEMBER_COMM.ECTL_INS_BATCH_ID as TGT_ECTL_INS_BATCH_ID,
TGT_MEMBER_COMM.ECTL_UPD_BATCH_ID as TGT_ECTL_UPD_BATCH_ID,
TGT_MEMBER_COMM.ECTL_INS_PRGM_ID as TGT_ECTL_INS_PRGM_ID,
TGT_MEMBER_COMM.ECTL_UPD_PRGM_ID as TGT_ECTL_UPD_PRGM_ID,


/*SOURCE MD5*/
CAST(CONCAT(COALESCE(TRIM(CAST(SQ.COMM_CD1 as varchar(1))),''''),
COALESCE(TRIM(CAST(SQ.COMM_CD2 as varchar(1))),''''),
COALESCE(TRIM(CAST(SQ.COMM_CD3 as varchar(1))),''''),
COALESCE(TRIM(CAST(SQ.COMM_CD4 as varchar(1))),''''),
COALESCE(TRIM(CAST(SQ.COMM_CD5 as varchar(1))),'''')) as VARCHAR(50)) as SOURCEDATA,

/*TARGET_MD5*/

CAST(CONCAT(COALESCE(TRIM(CAST(TGT_COMM_CD1 as varchar(1))),''''),
COALESCE(TRIM(CAST(TGT_COMM_CD2 as varchar(1))),''''),
COALESCE(TRIM(CAST(TGT_COMM_CD3 as varchar(1))),''''),
COALESCE(TRIM(CAST(TGT_COMM_CD4 as varchar(1))),''''),
COALESCE(TRIM(CAST(TGT_COMM_CD5 as varchar(1))),'''')) as VARCHAR(50)) as TARGETDATA,

 CASE WHEN TGT_MEMB_SKEY is null and rnk=1 THEN ''I''

     when prev_comm_val <> SOURCEDATA   and rnk<>1 and SQ.LAST_UPDATE_TS> COALESCE(TGT_COMM_EFF_DT,cast(''1900-01-01 00:00:00.000000'' as timestamp)) THEN ''I''

      WHEN TRIM(TARGETDATA) <> TRIM(SOURCEDATA)  and  rnk =1 and SQ.LAST_UPDATE_TS> COALESCE(TGT_COMM_EFF_DT,cast(''1900-01-01 00:00:00.000000'' as timestamp))  THEN ''I''

      ELSE ''R'' END AS flag

from (
SELECT DISTINCT  MEMBER_NBR,COMM_CD1,COMM_CD2,COMM_CD3,COMM_CD4,COMM_CD5,LAST_UPDATE_TS  FROM DB_T_STAG_MEMBXREF_PROD.MEMBER
--where LAST_UPDATE_TS> $federation_start_dttm and LAST_UPDATE_TS <= $federation_end_dttm
)SQ

LEFT OUTER JOIN(SELECT MEMBER_MSTR.MEMB_SKEY as MEMB_SKEY,
MEMBER_MSTR.MEMB_NUM as MEMB_NUM,
MEMBER_MSTR.MEMB_EXP_DT as MEMB_EXP_DT
FROM DB_T_CORE_PROD.MEMBER_MSTR MEMBER_MSTR 
WHERE cast(MEMB_EXP_DT as date) = ''9999-12-31'' )MEM_MSTR
ON SQ.MEMBER_NBR=MEM_MSTR.MEMB_NUM
LEFT OUTER JOIN(SELECT  MEMBER_COMM.MEMB_SKEY AS MEMB_SKEY,MEMBER_COMM.COMM_CD1 AS COMM_CD1, MEMBER_COMM.COMM_CD2 AS COMM_CD2,
        MEMBER_COMM.COMM_CD3 AS COMM_CD3, MEMBER_COMM.COMM_CD4 AS COMM_CD4,
        MEMBER_COMM.COMM_CD5 AS COMM_CD5, MEMBER_COMM.COMM_EFF_DT AS COMM_EFF_DT,
        MEMBER_COMM.COMM_EXP_DT AS COMM_EXP_DT, MEMBER_COMM.ECTL_INS_BATCH_ID AS ECTL_INS_BATCH_ID,
        MEMBER_COMM.ECTL_UPD_BATCH_ID AS ECTL_UPD_BATCH_ID, MEMBER_COMM.ECTL_INS_PRGM_ID AS ECTL_INS_PRGM_ID,
        MEMBER_COMM.ECTL_UPD_PRGM_ID AS ECTL_UPD_PRGM_ID 
FROM   DB_T_CORE_PROD.MEMBER_COMM MEMBER_COMM
WHERE CAST(COMM_EXP_DT AS DATE)= ''9999-12-31'' )TGT_MEMBER_COMM
ON LKP_MEMB_SKEY=TGT_MEMBER_COMM.MEMB_SKEY )SQ1 order by 8 desc
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_Shortcut_to_MEMBER.MEMB_SKEY as MEMB_SKEY,
SQ_Shortcut_to_MEMBER.MEMBER_NBR as MEMBER_NBR,
SQ_Shortcut_to_MEMBER.COMM_CD1 as COMM_CD1,
SQ_Shortcut_to_MEMBER.COMM_CD2 as COMM_CD2,
SQ_Shortcut_to_MEMBER.COMM_CD3 as COMM_CD3,
SQ_Shortcut_to_MEMBER.COMM_CD4 as COMM_CD4,
SQ_Shortcut_to_MEMBER.COMM_CD5 as COMM_CD5,
4 as out_PROJ_ID,
''Y'' as out_BATCH_IND,
''Y'' as IN_BATCH_ACTIVE_IND,
:PMMappingName as out_PRGM_NM,
:PMMappingName as IN_PRGM_NM,
''MEMBER_COMM'' as out_TABLE_NM,
''MEMBER_COMM'' IN_SRC_TABLE_NM,
4 IN_PROJ_ID1,
4 IN_PROJ_ID,
SQ_Shortcut_to_MEMBER.LAST_UPDATE_TS as LAST_UPDATE_TS,
SQ_Shortcut_to_MEMBER.flag as flag,
SQ_Shortcut_to_MEMBER.source_record_id
FROM
SQ_Shortcut_to_MEMBER
);

--select * from MPLT_LKP_CTRL_TBLS_VALIDATION
-- Component m_lkp_Control_Tables, Type MAPPLET 
--MAPPLET NOT REGISTERED: m_lkp_Control_Tables, mapplet instance m_lkp_Control_Tables;
call MPLT_LKP_CTRL_TBLS_VALIDATION(''EXPTRANS'');

-- Component flt_remove_record_not_inerts, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE flt_remove_record_not_inerts AS
(
SELECT
EXPTRANS.MEMB_SKEY as MEMB_SKEY,
EXPTRANS.MEMBER_NBR as MEMBER_NBR,
EXPTRANS.COMM_CD1 as COMM_CD1,
EXPTRANS.COMM_CD2 as COMM_CD2,
EXPTRANS.COMM_CD3 as COMM_CD3,
EXPTRANS.COMM_CD4 as COMM_CD4,
EXPTRANS.COMM_CD5 as COMM_CD5,
EXPTRANS.LAST_UPDATE_TS as LAST_UPDATE_TS,
EXPTRANS.flag as flag,
m_lkp_Control_Tables.OUT_ECTL_BATCH_ID as mplt_BATCH_ID,
m_lkp_Control_Tables.OUT_ECTL_PRGM_ID as mplt_PRGM_ID,
m_lkp_Control_Tables.OUT_ECTL_TABLE_ID as mplt_TABLE_ID,
4 as mplt_PROJ_ID,
EXPTRANS.source_record_id
FROM
EXPTRANS
LEFT JOIN MPLT_LKP_CTRL_TBLS_VALIDATION m_lkp_Control_Tables ON EXPTRANS.source_record_id = m_lkp_Control_Tables.source_record_id
WHERE CASE WHEN EXPTRANS.flag = ''I'' AND EXPTRANS.MEMB_SKEY IS NOT NULL and EXPTRANS.LAST_UPDATE_TS IS NOT NULL THEN TRUE ELSE FALSE END
);


-- Component exp_INS_MEMBER_COMM, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_INS_MEMBER_COMM AS
(
SELECT
flt_remove_record_not_inerts.MEMB_SKEY as in_MEMB_SKEY1,
flt_remove_record_not_inerts.COMM_CD1 as in_COMM_CD11,
flt_remove_record_not_inerts.COMM_CD2 as in_COMM_CD21,
flt_remove_record_not_inerts.COMM_CD3 as in_COMM_CD31,
flt_remove_record_not_inerts.COMM_CD4 as in_COMM_CD41,
flt_remove_record_not_inerts.COMM_CD5 as in_COMM_CD51,
flt_remove_record_not_inerts.LAST_UPDATE_TS as in_COMM_EFF_DT1,
flt_remove_record_not_inerts.mplt_BATCH_ID as in_BATCH_ID1,
flt_remove_record_not_inerts.mplt_PRGM_ID as in_PRGM_ID1,
to_date ( ''99991231 23:59:59.999999'' , ''YYYYMMDD HH24:MI:SS.FF6'' ) as out_COMM_EXP_DT,
flt_remove_record_not_inerts.source_record_id
FROM
flt_remove_record_not_inerts
);


-- Component Shortcut_to_MEMBER_COMM_INS, Type TARGET 
INSERT INTO DB_T_CORE_PROD.MEMBER_COMM
(
MEMB_SKEY,
COMM_CD1,
COMM_CD2,
COMM_CD3,
COMM_CD4,
COMM_CD5,
COMM_EFF_DT,
COMM_EXP_DT,
ECTL_INS_BATCH_ID,
ECTL_INS_PRGM_ID
)
SELECT
exp_INS_MEMBER_COMM.in_MEMB_SKEY1 as MEMB_SKEY,
exp_INS_MEMBER_COMM.in_COMM_CD11 as COMM_CD1,
exp_INS_MEMBER_COMM.in_COMM_CD21 as COMM_CD2,
exp_INS_MEMBER_COMM.in_COMM_CD31 as COMM_CD3,
exp_INS_MEMBER_COMM.in_COMM_CD41 as COMM_CD4,
exp_INS_MEMBER_COMM.in_COMM_CD51 as COMM_CD5,
exp_INS_MEMBER_COMM.in_COMM_EFF_DT1 as COMM_EFF_DT,
exp_INS_MEMBER_COMM.out_COMM_EXP_DT as COMM_EXP_DT,
exp_INS_MEMBER_COMM.in_BATCH_ID1 as ECTL_INS_BATCH_ID,
exp_INS_MEMBER_COMM.in_PRGM_ID1 as ECTL_INS_PRGM_ID
FROM
exp_INS_MEMBER_COMM;


-- Component Shortcut_to_MEMBER_COMM_INS, Type Post SQL 
UPDATE  DB_T_CORE_PROD.MEMBER_COMM  FROM
(SELECT	distinct  MEMB_SKEY,COMM_EFF_DT,COMM_EXP_DT,ECTL_INS_BATCH_ID,ECTL_INS_PRGM_ID,
to_date(max(COMM_EFF_DT) over (partition by  MEMB_SKEY ORDER BY COMM_EFF_DT ASC,ECTL_INS_BATCH_ID ASC rows between 1 following and 1 following)) - 1 -- - INTERVAL ''1'' SECOND 
 as lead1
FROM DB_T_CORE_PROD.MEMBER_COMM 
 ) a
set COMM_EXP_DT=A.lead1,
ECTL_UPD_BATCH_ID = A.ECTL_INS_BATCH_ID ,
ECTL_UPD_PRGM_ID = A.ECTL_INS_PRGM_ID
where  MEMBER_COMM.MEMB_SKEY = A.MEMB_SKEY
AND MEMBER_COMM.COMM_EFF_DT = A.COMM_EFF_DT
AND CAST(MEMBER_COMM.COMM_EXP_DT AS DATE)=''9999-12-31''
AND lead1 is not null;


END; ';