-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_AUDIT_STG_TO_DW_CLAIMS2025("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE TGT_TBL_NM varchar;
SRC_TBL_NM varchar;
ACT_PROJ_ID varchar;
TABLE_NM varchar;
BATCH_ACTIVE_IND varchar;
BEGIN 

TGT_TBL_NM:=''DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO''; 
SRC_TBL_NM:=''DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO''; 
TABLE_NM:='' ''; 
BATCH_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
ACT_PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 

--select * from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO
-- Component sq_CLMF_CLAIM_CORE, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_CLMF_CLAIM_CORE AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as TGT_INS_CNT,
$2 as TGT_UPD_CNT,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 
A.TGT_INS_CNT,B.TGT_UPD_CNT FROM 
(SELECT COUNT(*) AS TGT_INS_CNT FROM table(:TGT_TBL_NM) A, DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B WHERE 
--ECTL_TX_CD=''NEW'' AND ECTL_ORIG_INS_TS >= ECTL_BATCH_START_TS  AND 
b.ECTL_ACTIVE_IND=:BATCH_ACTIVE_IND AND b.ECTL_PROJ_ID=:ACT_PROJ_ID) A,
(SELECT COUNT(*) AS TGT_UPD_CNT FROM table(:TGT_TBL_NM) A,DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B WHERE 
--ECTL_TX_CD=''UPD'' AND ECTL_MODIFY_TS >= ECTL_BATCH_START_TS  AND 
b.ECTL_ACTIVE_IND=:BATCH_ACTIVE_IND AND b.ECTL_PROJ_ID=:ACT_PROJ_ID) B
) SRC
)
);


-- Component exp_HOLD_TGT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_HOLD_TGT AS
(
SELECT
sq_CLMF_CLAIM_CORE.TGT_INS_CNT as TGT_INS_CNT,
sq_CLMF_CLAIM_CORE.TGT_UPD_CNT as TGT_UPD_CNT,
1 as DUMMY,
sq_CLMF_CLAIM_CORE.source_record_id
FROM
sq_CLMF_CLAIM_CORE
);


-- Component sq_STG_CLMF_CLM_NO_TRL_AUTO, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_CLMF_CLM_NO_TRL_AUTO AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SRC_CNT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT count(*) CNT FROM table(:SRC_TBL_NM) 
) SRC
)
);


-- Component exp_HOLD_SRC, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_HOLD_SRC AS
(
SELECT
TO_NUMBER(sq_STG_CLMF_CLM_NO_TRL_AUTO.SRC_CNT) as out_SRC_CNT,
1 as DUMMY,
sq_STG_CLMF_CLM_NO_TRL_AUTO.source_record_id
FROM
sq_STG_CLMF_CLM_NO_TRL_AUTO
);


-- Component jnr_SRC_TGT, Type JOINER 
CREATE OR REPLACE TEMPORARY TABLE jnr_SRC_TGT AS
(
SELECT
exp_HOLD_SRC.out_SRC_CNT as SRC_CNT,
exp_HOLD_SRC.DUMMY as DUMMY_SRC,
exp_HOLD_TGT.TGT_INS_CNT as TGT_INS_CNT,
exp_HOLD_TGT.TGT_UPD_CNT as TGT_UPD_CNT,
exp_HOLD_TGT.DUMMY as DUMMY_TGT,
row_number() over (order by 1) AS source_record_id
FROM
exp_HOLD_TGT
INNER JOIN exp_HOLD_SRC ON exp_HOLD_TGT.DUMMY = exp_HOLD_SRC.DUMMY
);


-- Component exp_MSG_DESC, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_MSG_DESC AS
(
SELECT
jnr_SRC_TGT.SRC_CNT as SRC_CNT,
jnr_SRC_TGT.TGT_INS_CNT as TGT_INS,
jnr_SRC_TGT.SRC_CNT - jnr_SRC_TGT.TGT_INS_CNT as TGT_REG,
jnr_SRC_TGT.TGT_UPD_CNT as TGT_UPD,
0 as TGT_DEL,
LTRIM ( RTRIM ( :TABLE_NM ) ) || '' - AUDIT INFORMATION SUCCESSFULLY LOADED'' as MSG_DESC,
CURRENT_TIMESTAMP as out_ORGN_TS,
''m_STG_FIN_CLM'' as out_PRGM_NM,
:ACT_PROJ_ID as out_ACT_PROJ_IND,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
LTRIM ( RTRIM ( :TABLE_NM ) ) as out_TABLE_NM,
:ACT_PROJ_ID as IN_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as IN_BATCH_ACTIVE_IND,
''m_STG_FIN_CLM'' IN_PRGM_NM,
null IN_TABLE_NM,
jnr_SRC_TGT.source_record_id
FROM
jnr_SRC_TGT
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''exp_MSG_DESC'');

-- Component ECTL_AUDIT_LOG_INS, Type TARGET 
INSERT INTO DB_T_CTRL_FIN_PROD.ECTL_AUDIT_LOG
(
ECTL_BATCH_ID,
ECTL_PRGM_ID,
ECTL_TABLE_ID,
ECTL_SRC_ROW_CNT,
ECTL_TRGT_INS_CNT,
ECTL_TRGT_UPD_CNT,
ECTL_TRGT_DEL_CNT,
ECTL_TRGT_REJ_CNT,
ECTL_MESSAGE_TXT,
ECTL_ORIG_INS_TS
)
SELECT
nvl(mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID,-1) as ECTL_BATCH_ID,
nvl(mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID,-1) as ECTL_PRGM_ID,
nvl(mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_TABLE_ID,-1) as ECTL_TABLE_ID,
exp_MSG_DESC.SRC_CNT as ECTL_SRC_ROW_CNT,
exp_MSG_DESC.TGT_INS as ECTL_TRGT_INS_CNT,
exp_MSG_DESC.TGT_UPD as ECTL_TRGT_UPD_CNT,
exp_MSG_DESC.TGT_DEL as ECTL_TRGT_DEL_CNT,
exp_MSG_DESC.TGT_REG as ECTL_TRGT_REJ_CNT,
exp_MSG_DESC.MSG_DESC as ECTL_MESSAGE_TXT,
exp_MSG_DESC.out_ORGN_TS as ECTL_ORIG_INS_TS
FROM
exp_MSG_DESC
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_MSG_DESC.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id;


END; ';