-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_AUDIT_STG_TO_DW_UPSERT("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE TGT_TBL_NM varchar;
SRC_TBL_NM varchar;
ACT_PROJ_ID varchar;
SEL_CLAUSE_VAL varchar;
FILTER_APP_VAL varchar;
BATCH_ACTIVE_IND varchar;
PRGM_NM varchar;
BEGIN 

TGT_TBL_NM:=''DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO''; 
SRC_TBL_NM:=''DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO''; 
SEL_CLAUSE_VAL:='' ''; 
FILTER_APP_VAL:='' ''; 
PRGM_NM:='' ''; 
BATCH_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
ACT_PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 


-- Component sq_TGT_TABLE, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_TGT_TABLE AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as TGT_INS_CNT,
$2 as TGT_UPD_CNT,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 
A.INS_CNT,B.UPD_CNT FROM 
(SELECT COUNT(*) AS INS_CNT FROM table(:TGT_TBL_NM) A, DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B 
WHERE 
--ECTL_TX_CD=''NEW'' AND ECTL_ORIG_INS_TS >= ECTL_BATCH_START_TS 
 b.ECTL_ACTIVE_IND=:BATCH_ACTIVE_IND AND b.ECTL_PROJ_ID=:ACT_PROJ_ID) A,
(SELECT COUNT(*) AS UPD_CNT FROM table(:TGT_TBL_NM) A,DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B 
WHERE 
--ECTL_TX_CD=''UPD'' AND ECTL_MODIFY_TS >= ECTL_BATCH_START_TS 
 b.ECTL_ACTIVE_IND=:BATCH_ACTIVE_IND AND b.ECTL_PROJ_ID=:ACT_PROJ_ID) B
WHERE 
1=1
) SRC
)
);


-- Component exp_DUMMY_PORT_TGT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_DUMMY_PORT_TGT AS
(
SELECT
sq_TGT_TABLE.TGT_INS_CNT as TGT_INS_CNT,
sq_TGT_TABLE.TGT_UPD_CNT as TGT_UPD_CNT,
1 as out_DUMMY,
sq_TGT_TABLE.source_record_id
FROM
sq_TGT_TABLE
);


-- Component sq_SRC_TABLE, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_SRC_TABLE AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SRC_CNT,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT COUNT(*) FROM (SELECT 
* --SEL_CLAUSE_VAL 
FROM table(:SRC_TBL_NM) --WHERE FILTER_APP_VAL
) A
) SRC
)
);


-- Component exp_DUMMY_PORT_SRC, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_DUMMY_PORT_SRC AS
(
SELECT
sq_SRC_TABLE.SRC_CNT as SRC_CNT,
1 as out_DUMMY,
sq_SRC_TABLE.source_record_id
FROM
sq_SRC_TABLE
);


-- Component jnr_JOIN_SRC_TGT, Type JOINER 
CREATE OR REPLACE TEMPORARY TABLE jnr_JOIN_SRC_TGT AS
(
SELECT
exp_DUMMY_PORT_SRC.SRC_CNT as SRC_CNT,
exp_DUMMY_PORT_TGT.TGT_INS_CNT as TGT_INS_CNT,
exp_DUMMY_PORT_TGT.TGT_UPD_CNT as TGT_UPD_CNT,
exp_DUMMY_PORT_SRC.out_DUMMY as DUMMY_SRC,
exp_DUMMY_PORT_TGT.out_DUMMY as DUMMY_TGT,
row_number() over (order by 1) AS source_record_id
FROM
exp_DUMMY_PORT_TGT
INNER JOIN exp_DUMMY_PORT_SRC ON exp_DUMMY_PORT_TGT.out_DUMMY = exp_DUMMY_PORT_SRC.out_DUMMY
);


-- Component exp_CREATE_ECTL_FIELDS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CREATE_ECTL_FIELDS AS
(
SELECT
:ACT_PROJ_ID IN_PROJ_ID1,
:ACT_PROJ_ID IN_PROJ_ID,
:ACT_PROJ_ID as IN_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as IN_BATCH_ACTIVE_IND,
''m_STG_FIN_CLM'' IN_PRGM_NM,
null IN_TABLE_NM,
:SRC_TBL_NM as out_SRC_TABLE_NM,
:SRC_TBL_NM as IN_SRC_TABLE_NM,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
:ACT_PROJ_ID as out_PROJ_ID,
:PRGM_NM as out_PRGM_NM,
jnr_JOIN_SRC_TGT.SRC_CNT as SRC_CNT,
jnr_JOIN_SRC_TGT.TGT_INS_CNT as TGT_INS_CNT,
jnr_JOIN_SRC_TGT.TGT_UPD_CNT as TGT_UPD_CNT,
0 as out_ECTL_TRGT_DEL_CNT,
jnr_JOIN_SRC_TGT.SRC_CNT - jnr_JOIN_SRC_TGT.TGT_INS_CNT as out_ECTL_TRGT_REJ_CNT,
:TGT_TBL_NM || '' -  AUDIT INFORMATION SUCCESSFULLY LOADED'' as out_ECTL_MESSAGE_TXT,
CURRENT_TIMESTAMP as out_ECTL_ORIG_INS_TS,
jnr_JOIN_SRC_TGT.source_record_id
FROM
jnr_JOIN_SRC_TGT
);


-- Component mplt_LKP_CTRL_TBLS_VALIDATION, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_CTRL_TBLS_VALIDATION, mapplet instance mplt_LKP_CTRL_TBLS_VALIDATION;
call mplt_LKP_CTRL_TBLS_VALIDATION(''exp_CREATE_ECTL_FIELDS'');

-- Component ECTL_AUDIT_LOG_INS, Type TARGET 
INSERT INTO DB_T_CTRL_FIN_PROD.ECTL_AUDIT_LOG
(
ECTL_BATCH_ID,
ECTL_PRGM_ID,
ECTL_TABLE_ID,
ECTL_SRC_ROW_CNT,
ECTL_TRGT_INS_CNT,
ECTL_TRGT_UPD_CNT,
ECTL_TRGT_DEL_CNT,
ECTL_TRGT_REJ_CNT,
ECTL_MESSAGE_TXT,
ECTL_ORIG_INS_TS
)
SELECT
nvl(mplt_LKP_CTRL_TBLS_VALIDATION.out_ECTL_BATCH_ID,-1) as ECTL_BATCH_ID,
nvl(mplt_LKP_CTRL_TBLS_VALIDATION.out_ECTL_PRGM_ID,-1) as ECTL_PRGM_ID,
nvl(mplt_LKP_CTRL_TBLS_VALIDATION.out_ECTL_TABLE_ID,-1) as ECTL_TABLE_ID,
exp_CREATE_ECTL_FIELDS.SRC_CNT as ECTL_SRC_ROW_CNT,
exp_CREATE_ECTL_FIELDS.TGT_INS_CNT as ECTL_TRGT_INS_CNT,
exp_CREATE_ECTL_FIELDS.TGT_UPD_CNT as ECTL_TRGT_UPD_CNT,
exp_CREATE_ECTL_FIELDS.out_ECTL_TRGT_DEL_CNT as ECTL_TRGT_DEL_CNT,
exp_CREATE_ECTL_FIELDS.out_ECTL_TRGT_REJ_CNT as ECTL_TRGT_REJ_CNT,
exp_CREATE_ECTL_FIELDS.out_ECTL_MESSAGE_TXT as ECTL_MESSAGE_TXT,
exp_CREATE_ECTL_FIELDS.out_ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS
FROM
exp_CREATE_ECTL_FIELDS
INNER JOIN mplt_LKP_CTRL_TBLS_VALIDATION ON exp_CREATE_ECTL_FIELDS.source_record_id = mplt_LKP_CTRL_TBLS_VALIDATION.source_record_id;


END; ';