-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_MULTILINE_POLSTAT("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE BATCH_ACTIVE_IND varchar;
ACT_PROJ_ID varchar;
PMMAPPINGNAME varchar;
PMMULTILINE_POLSTAT_INSTABLENAME varchar;
BEGIN 


PMMAPPINGNAME:=''M_MULTILINE_POLSTAT''; 
PMMULTILINE_POLSTAT_INSTABLENAME:='' ''; 
BATCH_ACTIVE_IND:=(select ectl_active_ind from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 
ACT_PROJ_ID:=(select ectl_proj_id from DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO where ECTL_BATCH_ID= :run_id); 

-- Component sq_STG_MULTILINE_POLSTAT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_MULTILINE_POLSTAT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as POL_SYMBOL,
$2 as POL_NBR,
$3 as COMPANY,
$4 as STATE,
$5 as STATUS,
$6 as AGENT,
$7 as SERV_CNTR,
$8 as DIST_REGION,
$9 as EFF_DT_CYMD,
$10 as EXP_DT_CYMD,
$11 as ADD_COV,
$12 as FIRE_CONVERT_TRANS_CODE,
$13 as SM_POL_INDICATOR,
$14 as REASON,
$15 as TOT_PREM,
$16 as FIRE_HOME_TYPE_POL,
$17 as MEMBER_TYPE,
$18 as MEMBER_NBR,
$19 as NAMED_INS,
$20 as ADDL_NMD_INS,
$21 as ADDR1,
$22 as ADDR2,
$23 as CITY,
$24 as ADDR_STATE,
$25 as ZIP,
$26 as DIV_S3_POL_SYM,
$27 as DIV_S3_POL_NBR,
$28 as DIV_MAN_IND,
$29 as DIV_POL_LAPSE,
$30 as NR,
$31 as INF_UNIT_CTS,
$32 as POLICY_ACTIVITY,
$33 as INFORCE_IND,
$34 as LOB_GROUP,
$35 as FEED_DT,
$36 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT STG_MULTILINE_POLSTAT.POL_SYMBOL, 
STG_MULTILINE_POLSTAT.POL_NBR, 
STG_MULTILINE_POLSTAT.COMPANY, 
STG_MULTILINE_POLSTAT.STATE, 
STG_MULTILINE_POLSTAT.STATUS, 
STG_MULTILINE_POLSTAT.AGENT, 
STG_MULTILINE_POLSTAT.SERV_CNTR, 
STG_MULTILINE_POLSTAT.DIST_REGION, 
STG_MULTILINE_POLSTAT.EFF_DT_CYMD, 
STG_MULTILINE_POLSTAT.EXP_DT_CYMD, 
STG_MULTILINE_POLSTAT.ADD_COV, 
STG_MULTILINE_POLSTAT.FIRE_CONVERT_TRANS_CODE, 
STG_MULTILINE_POLSTAT.SM_POL_INDICATOR, 
STG_MULTILINE_POLSTAT.REASON, 
STG_MULTILINE_POLSTAT.TOT_PREM, 
STG_MULTILINE_POLSTAT.FIRE_HOME_TYPE_POL, 
STG_MULTILINE_POLSTAT.MEMBER_TYPE, 
STG_MULTILINE_POLSTAT.MEMBER_NBR, 
STG_MULTILINE_POLSTAT.NAMED_INS, 
STG_MULTILINE_POLSTAT.ADDL_NMD_INS, 
STG_MULTILINE_POLSTAT.ADDR1, 
STG_MULTILINE_POLSTAT.ADDR2, 
STG_MULTILINE_POLSTAT.CITY, 
STG_MULTILINE_POLSTAT.ADDR_STATE, 
STG_MULTILINE_POLSTAT.ZIP, 
STG_MULTILINE_POLSTAT.DIV_S3_POL_SYM, 
STG_MULTILINE_POLSTAT.DIV_S3_POL_NBR, 
STG_MULTILINE_POLSTAT.DIV_MAN_IND, 
STG_MULTILINE_POLSTAT.DIV_POL_LAPSE, 
STG_MULTILINE_POLSTAT.NR, 
STG_MULTILINE_POLSTAT.INF_UNIT_CTS, 
STG_MULTILINE_POLSTAT.POLICY_ACTIVITY,
STG_MULTILINE_POLSTAT.INFORCE_IND,
STG_MULTILINE_POLSTAT.LOB_GROUP, 
STG_MULTILINE_POLSTAT.FEED_DT 
FROM
DB_T_STAG_PROD.STG_MULTILINE_POLSTAT
WHERE EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)=(SELECT MAX(EXTRACT(YEAR FROM FEED_DT)*100+EXTRACT(MONTH FROM FEED_DT)) FROM DB_T_STAG_PROD.STG_MULTILINE_POLSTAT)
) SRC
)
);


-- Component exp_CALC_PLCY_CHG_EFF_DT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CALC_PLCY_CHG_EFF_DT AS
(
SELECT
sq_STG_MULTILINE_POLSTAT.POL_SYMBOL as POL_SYMBOL,
sq_STG_MULTILINE_POLSTAT.POL_NBR as POL_NBR,
sq_STG_MULTILINE_POLSTAT.COMPANY as COMPANY,
sq_STG_MULTILINE_POLSTAT.STATE as STATE,
sq_STG_MULTILINE_POLSTAT.STATUS as STATUS,
sq_STG_MULTILINE_POLSTAT.AGENT as AGENT,
sq_STG_MULTILINE_POLSTAT.SERV_CNTR as SERV_CNTR,
sq_STG_MULTILINE_POLSTAT.DIST_REGION as DIST_REGION,
sq_STG_MULTILINE_POLSTAT.EFF_DT_CYMD as EFF_DT_CYMD,
sq_STG_MULTILINE_POLSTAT.EXP_DT_CYMD as EXP_DT_CYMD,
CASE WHEN sq_STG_MULTILINE_POLSTAT.EFF_DT_CYMD IS NULL THEN TO_DATE ( ''1900-01-01'' , ''YYYY-MM-DD'' ) ELSE sq_STG_MULTILINE_POLSTAT.EFF_DT_CYMD END as CHG_EFF_DT,
sq_STG_MULTILINE_POLSTAT.ADD_COV as ADD_COV,
sq_STG_MULTILINE_POLSTAT.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE,
sq_STG_MULTILINE_POLSTAT.SM_POL_INDICATOR as SM_POL_INDICATOR,
sq_STG_MULTILINE_POLSTAT.REASON as REASON,
sq_STG_MULTILINE_POLSTAT.TOT_PREM as TOT_PREM,
sq_STG_MULTILINE_POLSTAT.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL,
sq_STG_MULTILINE_POLSTAT.MEMBER_TYPE as MEMBER_TYPE,
sq_STG_MULTILINE_POLSTAT.MEMBER_NBR as MEMBER_NBR,
sq_STG_MULTILINE_POLSTAT.NAMED_INS as NAMED_INS,
sq_STG_MULTILINE_POLSTAT.ADDL_NMD_INS as ADDL_NMD_INS,
sq_STG_MULTILINE_POLSTAT.ADDR1 as ADDR1,
sq_STG_MULTILINE_POLSTAT.ADDR2 as ADDR2,
sq_STG_MULTILINE_POLSTAT.CITY as CITY,
sq_STG_MULTILINE_POLSTAT.ADDR_STATE as ADDR_STATE,
sq_STG_MULTILINE_POLSTAT.ZIP as ZIP,
sq_STG_MULTILINE_POLSTAT.DIV_S3_POL_SYM as DIV_S3_POL_SYM,
sq_STG_MULTILINE_POLSTAT.DIV_S3_POL_NBR as DIV_S3_POL_NBR,
sq_STG_MULTILINE_POLSTAT.DIV_MAN_IND as DIV_MAN_IND,
sq_STG_MULTILINE_POLSTAT.DIV_POL_LAPSE as DIV_POL_LAPSE,
sq_STG_MULTILINE_POLSTAT.NR as NR,
sq_STG_MULTILINE_POLSTAT.INF_UNIT_CTS as INF_UNIT_CTS,
sq_STG_MULTILINE_POLSTAT.POLICY_ACTIVITY as POLICY_ACTIVITY,
sq_STG_MULTILINE_POLSTAT.INFORCE_IND as INFORCE_IND,
sq_STG_MULTILINE_POLSTAT.LOB_GROUP as LOB_GROUP,
sq_STG_MULTILINE_POLSTAT.FEED_DT as FEED_DT,
sq_STG_MULTILINE_POLSTAT.source_record_id
FROM
sq_STG_MULTILINE_POLSTAT
);


-- Component LKP_TARGET, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_TARGET AS
(
SELECT
LKP.PLCY_SYM_CD_lkup,
LKP.PLCY_NBR_lkup,
LKP.MASTER_COMPANY_NBR_lkup,
LKP.ST_CD_lkup,
LKP.STATUS_lkup,
LKP.AGENT_lkup,
LKP.PLCY_SVC_NBR_lkup,
LKP.DIST_REGION_lkup,
LKP.EFF_DT_lkup,
LKP.EXP_DT_lkup,
LKP.PLCY_CHG_EFF_DT_lkup,
LKP.ADD_COV_CD_lkup,
LKP.FIRE_CONVERT_TRANS_CD_lkup,
LKP.SM_POL_IND_lkup,
LKP.REASON_lkup,
LKP.TOT_PREM_lkup,
LKP.FIRE_HOME_TYPE_POL_lkup,
LKP.ALFA_CUST_MEMB_TYPE_lkup,
LKP.ALFA_CUST_MEMB_NBR_lkup,
LKP.NAME_INSURED_lkup,
LKP.ADDL_NAME_INSURED_lkup,
LKP.ADDR_LINE_1_lkup,
LKP.ADDR_LINE_2_lkup,
LKP.CITY_lkup,
LKP.ADDR_ST_CD_lkup,
LKP.ZIP_CD_lkup,
LKP.DIV_S3_POL_SYM_lkup,
LKP.DIV_S3_POL_NBR_lkup,
LKP.DIV_MAN_IND_lkup,
LKP.DIV_POL_LAPSE_lkup,
LKP.NR_lkup,
LKP.INF_UNIT_CTS_lkup,
LKP.POLICY_ACTIVITY_lkup,
LKP.INFORCE_IND_lkup,
LKP.LOB_CD_lkup,
LKP.FEED_DT_lkup,
exp_CALC_PLCY_CHG_EFF_DT.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_CALC_PLCY_CHG_EFF_DT.source_record_id ORDER BY LKP.PLCY_SYM_CD_lkup asc,LKP.PLCY_NBR_lkup asc,LKP.MASTER_COMPANY_NBR_lkup asc,LKP.ST_CD_lkup asc,LKP.STATUS_lkup asc,LKP.AGENT_lkup asc,LKP.PLCY_SVC_NBR_lkup asc,LKP.DIST_REGION_lkup asc,LKP.EFF_DT_lkup asc,LKP.EXP_DT_lkup asc,LKP.PLCY_CHG_EFF_DT_lkup asc,LKP.ADD_COV_CD_lkup asc,LKP.FIRE_CONVERT_TRANS_CD_lkup asc,LKP.SM_POL_IND_lkup asc,LKP.REASON_lkup asc,LKP.TOT_PREM_lkup asc,LKP.FIRE_HOME_TYPE_POL_lkup asc,LKP.ALFA_CUST_MEMB_TYPE_lkup asc,LKP.ALFA_CUST_MEMB_NBR_lkup asc,LKP.NAME_INSURED_lkup asc,LKP.ADDL_NAME_INSURED_lkup asc,LKP.ADDR_LINE_1_lkup asc,LKP.ADDR_LINE_2_lkup asc,LKP.CITY_lkup asc,LKP.ADDR_ST_CD_lkup asc,LKP.ZIP_CD_lkup asc,LKP.DIV_S3_POL_SYM_lkup asc,LKP.DIV_S3_POL_NBR_lkup asc,LKP.DIV_MAN_IND_lkup asc,LKP.DIV_POL_LAPSE_lkup asc,LKP.NR_lkup asc,LKP.INF_UNIT_CTS_lkup asc,LKP.POLICY_ACTIVITY_lkup asc,LKP.INFORCE_IND_lkup asc,LKP.LOB_CD_lkup asc,LKP.FEED_DT_lkup asc) RNK
FROM
exp_CALC_PLCY_CHG_EFF_DT
LEFT JOIN (
SELECT MULTILINE_POLSTAT.PLCY_SYM_CD as PLCY_SYM_CD_lkup, 
MULTILINE_POLSTAT.PLCY_NBR as PLCY_NBR_lkup,
MULTILINE_POLSTAT.MASTER_COMPANY_NBR as MASTER_COMPANY_NBR_lkup,
MULTILINE_POLSTAT.ST_CD as ST_CD_lkup,
MULTILINE_POLSTAT.STATUS as STATUS_lkup, 
MULTILINE_POLSTAT.AGENT as AGENT_lkup,
MULTILINE_POLSTAT.PLCY_SVC_NBR as PLCY_SVC_NBR_lkup, 
MULTILINE_POLSTAT.DIST_REGION as DIST_REGION_lkup, 
MULTILINE_POLSTAT.EFF_DT as EFF_DT_lkup, 
MULTILINE_POLSTAT.EXP_DT as EXP_DT_lkup, 
MULTILINE_POLSTAT.PLCY_CHG_EFF_DT as PLCY_CHG_EFF_DT_lkup, 
MULTILINE_POLSTAT.ADD_COV_CD as ADD_COV_CD_lkup, 
MULTILINE_POLSTAT.FIRE_CONVERT_TRANS_CD as FIRE_CONVERT_TRANS_CD_lkup, 
MULTILINE_POLSTAT.SM_POL_IND as SM_POL_IND_lkup, 
MULTILINE_POLSTAT.REASON as REASON_lkup, 
MULTILINE_POLSTAT.TOT_PREM as TOT_PREM_lkup, 
MULTILINE_POLSTAT.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL_lkup, 
MULTILINE_POLSTAT.ALFA_CUST_MEMB_TYPE as ALFA_CUST_MEMB_TYPE_lkup, 
MULTILINE_POLSTAT.ALFA_CUST_MEMB_NBR as ALFA_CUST_MEMB_NBR_lkup, 
MULTILINE_POLSTAT.NAME_INSURED as NAME_INSURED_lkup, 
MULTILINE_POLSTAT.ADDL_NAME_INSURED as ADDL_NAME_INSURED_lkup, 
MULTILINE_POLSTAT.ADDR_LINE_1 as ADDR_LINE_1_lkup, 
MULTILINE_POLSTAT.ADDR_LINE_2 as ADDR_LINE_2_lkup, 
MULTILINE_POLSTAT.CITY as CITY_lkup, 
MULTILINE_POLSTAT.ADDR_ST_CD as ADDR_ST_CD_lkup, 
MULTILINE_POLSTAT.ZIP_CD as ZIP_CD_lkup, 
MULTILINE_POLSTAT.DIV_S3_POL_SYM as DIV_S3_POL_SYM_lkup, 
MULTILINE_POLSTAT.DIV_S3_POL_NBR as DIV_S3_POL_NBR_lkup, 
MULTILINE_POLSTAT.DIV_MAN_IND as DIV_MAN_IND_lkup, 
MULTILINE_POLSTAT.DIV_POL_LAPSE as DIV_POL_LAPSE_lkup, 
MULTILINE_POLSTAT.NR as NR_lkup, 
MULTILINE_POLSTAT.INF_UNIT_CTS as INF_UNIT_CTS_lkup, 
MULTILINE_POLSTAT.POLICY_ACTIVITY as POLICY_ACTIVITY_lkup, 
MULTILINE_POLSTAT.INFORCE_IND as INFORCE_IND_lkup, 
MULTILINE_POLSTAT.LOB_CD as LOB_CD_lkup,
MULTILINE_POLSTAT.FEED_DT AS FEED_DT_lkup  FROM DB_T_ML_PROD.MULTILINE_POLSTAT WHERE (POLICY_ACTIVITY_lkup IS NOT NULL OR TRIM(POLICY_ACTIVITY_lkup)='''')
QUALIFY RANK() OVER (PARTITION BY PLCY_NBR ORDER BY FEED_DT DESC,PLCY_CHG_EFF_DT DESC,PLCY_CHG_EXP_DT DESC)=1
) LKP ON LKP.PLCY_NBR_lkup = exp_CALC_PLCY_CHG_EFF_DT.POL_NBR
QUALIFY RNK = 1
);


-- Component exp_CHECK, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CHECK AS
(
SELECT
exp_CALC_PLCY_CHG_EFF_DT.POL_SYMBOL as POL_SYMBOL,
exp_CALC_PLCY_CHG_EFF_DT.POL_NBR as POL_NBR,
exp_CALC_PLCY_CHG_EFF_DT.COMPANY as COMPANY,
exp_CALC_PLCY_CHG_EFF_DT.STATE as STATE,
exp_CALC_PLCY_CHG_EFF_DT.STATUS as STATUS,
exp_CALC_PLCY_CHG_EFF_DT.AGENT as AGENT,
exp_CALC_PLCY_CHG_EFF_DT.SERV_CNTR as SERV_CNTR,
exp_CALC_PLCY_CHG_EFF_DT.DIST_REGION as DIST_REGION,
exp_CALC_PLCY_CHG_EFF_DT.EFF_DT_CYMD as EFF_DT_CYMD,
exp_CALC_PLCY_CHG_EFF_DT.EXP_DT_CYMD as EXP_DT_CYMD,
exp_CALC_PLCY_CHG_EFF_DT.CHG_EFF_DT as CHG_EFF_DT,
exp_CALC_PLCY_CHG_EFF_DT.ADD_COV as ADD_COV,
exp_CALC_PLCY_CHG_EFF_DT.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE,
exp_CALC_PLCY_CHG_EFF_DT.SM_POL_INDICATOR as SM_POL_INDICATOR,
exp_CALC_PLCY_CHG_EFF_DT.REASON as REASON,
exp_CALC_PLCY_CHG_EFF_DT.TOT_PREM as TOT_PREM,
exp_CALC_PLCY_CHG_EFF_DT.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL,
exp_CALC_PLCY_CHG_EFF_DT.MEMBER_TYPE as MEMBER_TYPE,
exp_CALC_PLCY_CHG_EFF_DT.MEMBER_NBR as MEMBER_NBR,
exp_CALC_PLCY_CHG_EFF_DT.NAMED_INS as NAMED_INS,
exp_CALC_PLCY_CHG_EFF_DT.ADDL_NMD_INS as ADDL_NMD_INS,
exp_CALC_PLCY_CHG_EFF_DT.ADDR1 as ADDR1,
exp_CALC_PLCY_CHG_EFF_DT.ADDR2 as ADDR2,
exp_CALC_PLCY_CHG_EFF_DT.CITY as CITY,
exp_CALC_PLCY_CHG_EFF_DT.ADDR_STATE as ADDR_STATE,
exp_CALC_PLCY_CHG_EFF_DT.ZIP as ZIP,
exp_CALC_PLCY_CHG_EFF_DT.DIV_S3_POL_SYM as DIV_S3_POL_SYM,
exp_CALC_PLCY_CHG_EFF_DT.DIV_S3_POL_NBR as DIV_S3_POL_NBR,
exp_CALC_PLCY_CHG_EFF_DT.DIV_MAN_IND as DIV_MAN_IND,
exp_CALC_PLCY_CHG_EFF_DT.DIV_POL_LAPSE as DIV_POL_LAPSE,
exp_CALC_PLCY_CHG_EFF_DT.NR as NR,
exp_CALC_PLCY_CHG_EFF_DT.INF_UNIT_CTS as INF_UNIT_CTS,
exp_CALC_PLCY_CHG_EFF_DT.POLICY_ACTIVITY as POLICY_ACTIVITY,
exp_CALC_PLCY_CHG_EFF_DT.INFORCE_IND as INFORCE_IND,
exp_CALC_PLCY_CHG_EFF_DT.LOB_GROUP as LOB_GROUP,
exp_CALC_PLCY_CHG_EFF_DT.FEED_DT as FEED_DT,
CASE WHEN LKP_TARGET.PLCY_NBR_lkup IS NULL THEN ''NEW'' ELSE CASE WHEN CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.PLCY_SYM_CD_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.PLCY_SYM_CD_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.POL_SYMBOL ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.POL_SYMBOL ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.MASTER_COMPANY_NBR_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.MASTER_COMPANY_NBR_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.COMPANY ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.COMPANY ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.ST_CD_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.ST_CD_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.STATE ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.STATE ) ) END OR CASE WHEN LKP_TARGET.STATUS_lkup IS NULL THEN 0 ELSE LKP_TARGET.STATUS_lkup END <> CASE WHEN exp_CALC_PLCY_CHG_EFF_DT.STATUS IS NULL THEN 0 ELSE exp_CALC_PLCY_CHG_EFF_DT.STATUS END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.AGENT_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.AGENT_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.AGENT ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.AGENT ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.PLCY_SVC_NBR_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.PLCY_SVC_NBR_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.SERV_CNTR ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.SERV_CNTR ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.DIST_REGION_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.DIST_REGION_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.DIST_REGION ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.DIST_REGION ) ) END OR CASE WHEN LKP_TARGET.EFF_DT_lkup IS NULL THEN TO_DATE ( ''99991231'' , ''YYYYMMDD'' ) ELSE LKP_TARGET.EFF_DT_lkup END <> CASE WHEN exp_CALC_PLCY_CHG_EFF_DT.EFF_DT_CYMD IS NULL THEN TO_DATE ( ''99991231'' , ''YYYYMMDD'' ) ELSE exp_CALC_PLCY_CHG_EFF_DT.EFF_DT_CYMD END OR CASE WHEN LKP_TARGET.EXP_DT_lkup IS NULL THEN TO_DATE ( ''99991231'' , ''YYYYMMDD'' ) ELSE LKP_TARGET.EXP_DT_lkup END <> CASE WHEN exp_CALC_PLCY_CHG_EFF_DT.EXP_DT_CYMD IS NULL THEN TO_DATE ( ''99991231'' , ''YYYYMMDD'' ) ELSE exp_CALC_PLCY_CHG_EFF_DT.EXP_DT_CYMD END OR CASE WHEN LKP_TARGET.ADD_COV_CD_lkup IS NULL THEN 0 ELSE LKP_TARGET.ADD_COV_CD_lkup END <> CASE WHEN exp_CALC_PLCY_CHG_EFF_DT.ADD_COV IS NULL THEN 0 ELSE exp_CALC_PLCY_CHG_EFF_DT.ADD_COV END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.FIRE_CONVERT_TRANS_CD_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.FIRE_CONVERT_TRANS_CD_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.FIRE_CONVERT_TRANS_CODE ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.FIRE_CONVERT_TRANS_CODE ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.SM_POL_IND_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.SM_POL_IND_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.SM_POL_INDICATOR ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.SM_POL_INDICATOR ) ) END OR CASE WHEN LKP_TARGET.REASON_lkup IS NULL THEN 0 ELSE LKP_TARGET.REASON_lkup END <> CASE WHEN exp_CALC_PLCY_CHG_EFF_DT.REASON IS NULL THEN 0 ELSE exp_CALC_PLCY_CHG_EFF_DT.REASON END OR CASE WHEN LKP_TARGET.TOT_PREM_lkup IS NULL THEN 0 ELSE LKP_TARGET.TOT_PREM_lkup END <> CASE WHEN exp_CALC_PLCY_CHG_EFF_DT.TOT_PREM IS NULL THEN 0 ELSE exp_CALC_PLCY_CHG_EFF_DT.TOT_PREM END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.FIRE_HOME_TYPE_POL_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.FIRE_HOME_TYPE_POL_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.FIRE_HOME_TYPE_POL ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.FIRE_HOME_TYPE_POL ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.ALFA_CUST_MEMB_TYPE_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.ALFA_CUST_MEMB_TYPE_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.MEMBER_TYPE ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.MEMBER_TYPE ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.ALFA_CUST_MEMB_NBR_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.ALFA_CUST_MEMB_NBR_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.MEMBER_NBR ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.MEMBER_NBR ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.NAME_INSURED_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.NAME_INSURED_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.NAMED_INS ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.NAMED_INS ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.ADDL_NAME_INSURED_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.ADDL_NAME_INSURED_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.ADDL_NMD_INS ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.ADDL_NMD_INS ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.ADDR_LINE_1_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.ADDR_LINE_1_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.ADDR1 ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.ADDR1 ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.ADDR_LINE_2_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.ADDR_LINE_2_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.ADDR2 ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.ADDR2 ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.CITY_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.CITY_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.CITY ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.CITY ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.ADDR_ST_CD_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.ADDR_ST_CD_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.ADDR_STATE ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.ADDR_STATE ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.ZIP_CD_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.ZIP_CD_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.ZIP ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.ZIP ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.DIV_S3_POL_SYM_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.DIV_S3_POL_SYM_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.DIV_S3_POL_SYM ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.DIV_S3_POL_SYM ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.DIV_S3_POL_NBR_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.DIV_S3_POL_NBR_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.DIV_S3_POL_NBR ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.DIV_S3_POL_NBR ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.DIV_MAN_IND_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.DIV_MAN_IND_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.DIV_MAN_IND ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.DIV_MAN_IND ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.DIV_POL_LAPSE_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.DIV_POL_LAPSE_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.DIV_POL_LAPSE ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.DIV_POL_LAPSE ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.NR_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.NR_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.NR ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.NR ) ) END OR CASE WHEN LKP_TARGET.INF_UNIT_CTS_lkup IS NULL THEN 0 ELSE LKP_TARGET.INF_UNIT_CTS_lkup END <> CASE WHEN exp_CALC_PLCY_CHG_EFF_DT.INF_UNIT_CTS IS NULL THEN 0 ELSE exp_CALC_PLCY_CHG_EFF_DT.INF_UNIT_CTS END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.INFORCE_IND_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.INFORCE_IND_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.INFORCE_IND ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.INFORCE_IND ) ) END OR CASE WHEN LTRIM ( RTRIM ( LKP_TARGET.LOB_CD_lkup ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( LKP_TARGET.LOB_CD_lkup ) ) END <> CASE WHEN LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.LOB_GROUP ) ) IS NULL THEN ''~'' ELSE LTRIM ( RTRIM ( exp_CALC_PLCY_CHG_EFF_DT.LOB_GROUP ) ) END THEN ''UPD'' ELSE ''REJ'' END END as out_CHK,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
:ACT_PROJ_ID as out_ACT_PROJ_ID,
:PMMappingName as out_PRGM_NM,
:PMMULTILINE_POLSTAT_INSTableName as out_TABLE_NM,
:ACT_PROJ_ID as IN_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as IN_BATCH_ACTIVE_IND,
''m_STG_FIN_CLM'' IN_PRGM_NM,
null IN_TABLE_NM,
LKP_TARGET.PLCY_CHG_EFF_DT_lkup as CHG_EFF_DT_lkup,
LKP_TARGET.FEED_DT_lkup as FEED_DT_lkup,
exp_CALC_PLCY_CHG_EFF_DT.source_record_id
FROM
exp_CALC_PLCY_CHG_EFF_DT
INNER JOIN LKP_TARGET ON exp_CALC_PLCY_CHG_EFF_DT.source_record_id = LKP_TARGET.source_record_id
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''exp_CHECK'');


-- Component exp_ECTL_FIELDS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ECTL_FIELDS AS
(
SELECT
exp_CHECK.POL_SYMBOL as POL_SYMBOL,
exp_CHECK.POL_NBR as POL_NBR,
exp_CHECK.COMPANY as COMPANY,
exp_CHECK.STATE as STATE,
exp_CHECK.STATUS as STATUS,
exp_CHECK.AGENT as AGENT,
exp_CHECK.SERV_CNTR as SERV_CNTR,
exp_CHECK.DIST_REGION as DIST_REGION,
exp_CHECK.EFF_DT_CYMD as EFF_DT_CYMD,
exp_CHECK.EXP_DT_CYMD as EXP_DT_CYMD,
exp_CHECK.CHG_EFF_DT as CHG_EFF_DT,
exp_CHECK.ADD_COV as ADD_COV,
exp_CHECK.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE,
exp_CHECK.SM_POL_INDICATOR as SM_POL_INDICATOR,
exp_CHECK.REASON as REASON,
exp_CHECK.TOT_PREM as TOT_PREM,
exp_CHECK.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL,
exp_CHECK.MEMBER_TYPE as MEMBER_TYPE,
exp_CHECK.MEMBER_NBR as MEMBER_NBR,
exp_CHECK.NAMED_INS as NAMED_INS,
exp_CHECK.ADDL_NMD_INS as ADDL_NMD_INS,
exp_CHECK.ADDR1 as ADDR1,
exp_CHECK.ADDR2 as ADDR2,
exp_CHECK.CITY as CITY,
exp_CHECK.ADDR_STATE as ADDR_STATE,
exp_CHECK.ZIP as ZIP,
exp_CHECK.DIV_S3_POL_SYM as DIV_S3_POL_SYM,
exp_CHECK.DIV_S3_POL_NBR as DIV_S3_POL_NBR,
exp_CHECK.DIV_MAN_IND as DIV_MAN_IND,
exp_CHECK.DIV_POL_LAPSE as DIV_POL_LAPSE,
exp_CHECK.NR as NR,
exp_CHECK.INF_UNIT_CTS as INF_UNIT_CTS,
exp_CHECK.POLICY_ACTIVITY as POLICY_ACTIVITY,
exp_CHECK.INFORCE_IND as INFORCE_IND,
exp_CHECK.LOB_GROUP as LOB_GROUP,
exp_CHECK.FEED_DT as FEED_DT,
exp_CHECK.out_CHK as out_CHK,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_TABLE_ID as out_ECTL_TABLE_ID,
exp_CHECK.CHG_EFF_DT_lkup as CHG_EFF_DT_lkup,
exp_CHECK.FEED_DT_lkup as FEED_DT_lkup,
exp_CHECK.source_record_id
FROM
exp_CHECK
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_CHECK.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
);


-- Component rtr_INS_UPD_REJ_INSERT, Type ROUTER Output Group INSERT
create or replace temp table RTR_INS_UPD_REJ_insert as
SELECT
exp_ECTL_FIELDS.POL_SYMBOL as POL_SYMBOL,
exp_ECTL_FIELDS.POL_NBR as POL_NBR,
exp_ECTL_FIELDS.COMPANY as COMPANY,
exp_ECTL_FIELDS.STATE as STATE,
exp_ECTL_FIELDS.STATUS as STATUS,
exp_ECTL_FIELDS.AGENT as AGENT,
exp_ECTL_FIELDS.SERV_CNTR as SERV_CNTR,
exp_ECTL_FIELDS.DIST_REGION as DIST_REGION,
exp_ECTL_FIELDS.EFF_DT_CYMD as EFF_DT_CYMD,
exp_ECTL_FIELDS.EXP_DT_CYMD as EXP_DT_CYMD,
exp_ECTL_FIELDS.CHG_EFF_DT as CHG_EFF_DT,
exp_ECTL_FIELDS.ADD_COV as ADD_COV,
exp_ECTL_FIELDS.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE,
exp_ECTL_FIELDS.SM_POL_INDICATOR as SM_POL_INDICATOR,
exp_ECTL_FIELDS.REASON as REASON,
exp_ECTL_FIELDS.TOT_PREM as TOT_PREM,
exp_ECTL_FIELDS.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL,
exp_ECTL_FIELDS.MEMBER_TYPE as MEMBER_TYPE,
exp_ECTL_FIELDS.MEMBER_NBR as MEMBER_NBR,
exp_ECTL_FIELDS.NAMED_INS as NAMED_INS,
exp_ECTL_FIELDS.ADDL_NMD_INS as ADDL_NMD_INS,
exp_ECTL_FIELDS.ADDR1 as ADDR1,
exp_ECTL_FIELDS.ADDR2 as ADDR2,
exp_ECTL_FIELDS.CITY as CITY,
exp_ECTL_FIELDS.ADDR_STATE as ADDR_STATE,
exp_ECTL_FIELDS.ZIP as ZIP,
exp_ECTL_FIELDS.DIV_S3_POL_SYM as DIV_S3_POL_SYM,
exp_ECTL_FIELDS.DIV_S3_POL_NBR as DIV_S3_POL_NBR,
exp_ECTL_FIELDS.DIV_MAN_IND as DIV_MAN_IND,
exp_ECTL_FIELDS.DIV_POL_LAPSE as DIV_POL_LAPSE,
exp_ECTL_FIELDS.NR as NR,
exp_ECTL_FIELDS.INF_UNIT_CTS as INF_UNIT_CTS,
exp_ECTL_FIELDS.POLICY_ACTIVITY as POLICY_ACTIVITY,
exp_ECTL_FIELDS.INFORCE_IND as INFORCE_IND,
exp_ECTL_FIELDS.LOB_GROUP as LOB_GROUP,
exp_ECTL_FIELDS.FEED_DT as FEED_DT,
exp_ECTL_FIELDS.out_CHK as out_CHK,
exp_ECTL_FIELDS.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
exp_ECTL_FIELDS.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
exp_ECTL_FIELDS.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
exp_ECTL_FIELDS.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
exp_ECTL_FIELDS.out_ORIG_INS_TS as out_ORIG_INS_TS,
exp_ECTL_FIELDS.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
exp_ECTL_FIELDS.out_ECTL_TABLE_ID as out_ECTL_TABLE_ID,
exp_ECTL_FIELDS.CHG_EFF_DT_lkup as CHG_EFF_DT_lkup,
exp_ECTL_FIELDS.FEED_DT_lkup as FEED_DT_lkup,
exp_ECTL_FIELDS.source_record_id
FROM
exp_ECTL_FIELDS
WHERE exp_ECTL_FIELDS.out_CHK = ''NEW'' OR exp_ECTL_FIELDS.out_CHK = ''UPD'';


-- Component rtr_INS_UPD_REJ_UPDATE, Type ROUTER Output Group UPDATE
create or replace temp table RTR_INS_UPD_REJ_UPDATE as
SELECT
exp_ECTL_FIELDS.POL_SYMBOL as POL_SYMBOL,
exp_ECTL_FIELDS.POL_NBR as POL_NBR,
exp_ECTL_FIELDS.COMPANY as COMPANY,
exp_ECTL_FIELDS.STATE as STATE,
exp_ECTL_FIELDS.STATUS as STATUS,
exp_ECTL_FIELDS.AGENT as AGENT,
exp_ECTL_FIELDS.SERV_CNTR as SERV_CNTR,
exp_ECTL_FIELDS.DIST_REGION as DIST_REGION,
exp_ECTL_FIELDS.EFF_DT_CYMD as EFF_DT_CYMD,
exp_ECTL_FIELDS.EXP_DT_CYMD as EXP_DT_CYMD,
exp_ECTL_FIELDS.CHG_EFF_DT as CHG_EFF_DT,
exp_ECTL_FIELDS.ADD_COV as ADD_COV,
exp_ECTL_FIELDS.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE,
exp_ECTL_FIELDS.SM_POL_INDICATOR as SM_POL_INDICATOR,
exp_ECTL_FIELDS.REASON as REASON,
exp_ECTL_FIELDS.TOT_PREM as TOT_PREM,
exp_ECTL_FIELDS.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL,
exp_ECTL_FIELDS.MEMBER_TYPE as MEMBER_TYPE,
exp_ECTL_FIELDS.MEMBER_NBR as MEMBER_NBR,
exp_ECTL_FIELDS.NAMED_INS as NAMED_INS,
exp_ECTL_FIELDS.ADDL_NMD_INS as ADDL_NMD_INS,
exp_ECTL_FIELDS.ADDR1 as ADDR1,
exp_ECTL_FIELDS.ADDR2 as ADDR2,
exp_ECTL_FIELDS.CITY as CITY,
exp_ECTL_FIELDS.ADDR_STATE as ADDR_STATE,
exp_ECTL_FIELDS.ZIP as ZIP,
exp_ECTL_FIELDS.DIV_S3_POL_SYM as DIV_S3_POL_SYM,
exp_ECTL_FIELDS.DIV_S3_POL_NBR as DIV_S3_POL_NBR,
exp_ECTL_FIELDS.DIV_MAN_IND as DIV_MAN_IND,
exp_ECTL_FIELDS.DIV_POL_LAPSE as DIV_POL_LAPSE,
exp_ECTL_FIELDS.NR as NR,
exp_ECTL_FIELDS.INF_UNIT_CTS as INF_UNIT_CTS,
exp_ECTL_FIELDS.POLICY_ACTIVITY as POLICY_ACTIVITY,
exp_ECTL_FIELDS.INFORCE_IND as INFORCE_IND,
exp_ECTL_FIELDS.LOB_GROUP as LOB_GROUP,
exp_ECTL_FIELDS.FEED_DT as FEED_DT,
exp_ECTL_FIELDS.out_CHK as out_CHK,
exp_ECTL_FIELDS.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
exp_ECTL_FIELDS.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
exp_ECTL_FIELDS.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
exp_ECTL_FIELDS.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
exp_ECTL_FIELDS.out_ORIG_INS_TS as out_ORIG_INS_TS,
exp_ECTL_FIELDS.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
exp_ECTL_FIELDS.out_ECTL_TABLE_ID as out_ECTL_TABLE_ID,
exp_ECTL_FIELDS.CHG_EFF_DT_lkup as CHG_EFF_DT_lkup,
exp_ECTL_FIELDS.FEED_DT_lkup as FEED_DT_lkup,
exp_ECTL_FIELDS.source_record_id
FROM
exp_ECTL_FIELDS
WHERE exp_ECTL_FIELDS.out_CHK = ''UPD'';


-- Component exp_CALC_PLCY_CHG_EXP_DT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CALC_PLCY_CHG_EXP_DT AS
(
SELECT
rtr_INS_UPD_REJ_UPDATE.POL_NBR as POL_NBR3,
rtr_INS_UPD_REJ_UPDATE.EFF_DT_CYMD as EFF_DT_CYMD3,
rtr_INS_UPD_REJ_UPDATE.EXP_DT_CYMD as EXP_DT_CYMD3,
 rtr_INS_UPD_REJ_UPDATE.FEED_DT  - 1  as out_CHG_EXP_DT,
rtr_INS_UPD_REJ_UPDATE.POLICY_ACTIVITY as POLICY_ACTIVITY3,
rtr_INS_UPD_REJ_UPDATE.out_CHK as out_CHK3,
rtr_INS_UPD_REJ_UPDATE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID3,
rtr_INS_UPD_REJ_UPDATE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID3,
rtr_INS_UPD_REJ_UPDATE.out_ORIG_INS_TS as out_ORIG_INS_TS3,
rtr_INS_UPD_REJ_UPDATE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE3,
rtr_INS_UPD_REJ_UPDATE.CHG_EFF_DT_lkup as CHG_EFF_DT_lkup3,
''UPD'' as out_ECTL_TX_CD,
rtr_INS_UPD_REJ_UPDATE.FEED_DT_lkup as FEED_DT_lkup3,
rtr_INS_UPD_REJ_UPDATE.source_record_id
FROM
rtr_INS_UPD_REJ_UPDATE
);


-- Component upd_TARGET, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_TARGET AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
exp_CALC_PLCY_CHG_EXP_DT.POL_NBR3 as POL_NBR3,
exp_CALC_PLCY_CHG_EXP_DT.EFF_DT_CYMD3 as EFF_DT_CYMD3,
exp_CALC_PLCY_CHG_EXP_DT.EXP_DT_CYMD3 as EXP_DT_CYMD3,
exp_CALC_PLCY_CHG_EXP_DT.CHG_EFF_DT_lkup3 as CHG_EFF_DT3,
exp_CALC_PLCY_CHG_EXP_DT.out_CHG_EXP_DT as out_CHG_EXP_DT,
exp_CALC_PLCY_CHG_EXP_DT.POLICY_ACTIVITY3 as POLICY_ACTIVITY3,
exp_CALC_PLCY_CHG_EXP_DT.out_CHK3 as out_CHK3,
exp_CALC_PLCY_CHG_EXP_DT.out_ECTL_PRGM_ID3 as out_ECTL_PRGM_ID3,
exp_CALC_PLCY_CHG_EXP_DT.out_ECTL_BATCH_ID3 as out_ECTL_BATCH_ID3,
exp_CALC_PLCY_CHG_EXP_DT.out_ORIG_INS_TS3 as out_ORIG_INS_TS3,
exp_CALC_PLCY_CHG_EXP_DT.out_ECTL_BATCH_START_DATE3 as out_ECTL_BATCH_START_DATE3,
exp_CALC_PLCY_CHG_EXP_DT.out_ECTL_TX_CD as out_ECTL_TX_CD,
exp_CALC_PLCY_CHG_EXP_DT.FEED_DT_lkup3 as FEED_DT_lkup3,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_CALC_PLCY_CHG_EXP_DT
);


-- Component exp_CALC_ECTL_END_DATE, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CALC_ECTL_END_DATE AS
(
SELECT
rtr_INS_UPD_REJ_INSERT.POL_SYMBOL as POL_SYMBOL1,
rtr_INS_UPD_REJ_INSERT.POL_NBR as POL_NBR1,
rtr_INS_UPD_REJ_INSERT.COMPANY as COMPANY1,
rtr_INS_UPD_REJ_INSERT.STATE as STATE1,
rtr_INS_UPD_REJ_INSERT.STATUS as STATUS1,
rtr_INS_UPD_REJ_INSERT.AGENT as AGENT1,
rtr_INS_UPD_REJ_INSERT.SERV_CNTR as SERV_CNTR1,
rtr_INS_UPD_REJ_INSERT.DIST_REGION as DIST_REGION1,
rtr_INS_UPD_REJ_INSERT.EFF_DT_CYMD as EFF_DT_CYMD1,
rtr_INS_UPD_REJ_INSERT.EXP_DT_CYMD as EXP_DT_CYMD1,
CASE WHEN rtr_INS_UPD_REJ_INSERT.out_CHK = ''NEW'' THEN rtr_INS_UPD_REJ_INSERT.CHG_EFF_DT ELSE rtr_INS_UPD_REJ_INSERT.FEED_DT END as out_CHG_EFF_DT,
TO_DATE ( ''99991231'' , ''YYYYMMDD'' ) as out_CHG_EXP_DT,
rtr_INS_UPD_REJ_INSERT.ADD_COV as ADD_COV1,
rtr_INS_UPD_REJ_INSERT.FIRE_CONVERT_TRANS_CODE as FIRE_CONVERT_TRANS_CODE1,
rtr_INS_UPD_REJ_INSERT.SM_POL_INDICATOR as SM_POL_INDICATOR1,
rtr_INS_UPD_REJ_INSERT.REASON as REASON1,
rtr_INS_UPD_REJ_INSERT.TOT_PREM as TOT_PREM1,
rtr_INS_UPD_REJ_INSERT.FIRE_HOME_TYPE_POL as FIRE_HOME_TYPE_POL1,
rtr_INS_UPD_REJ_INSERT.MEMBER_TYPE as MEMBER_TYPE1,
rtr_INS_UPD_REJ_INSERT.MEMBER_NBR as MEMBER_NBR1,
rtr_INS_UPD_REJ_INSERT.NAMED_INS as NAMED_INS1,
rtr_INS_UPD_REJ_INSERT.ADDL_NMD_INS as ADDL_NMD_INS1,
rtr_INS_UPD_REJ_INSERT.ADDR1 as ADDR11,
rtr_INS_UPD_REJ_INSERT.ADDR2 as ADDR21,
rtr_INS_UPD_REJ_INSERT.CITY as CITY1,
rtr_INS_UPD_REJ_INSERT.ADDR_STATE as ADDR_STATE1,
rtr_INS_UPD_REJ_INSERT.ZIP as ZIP1,
rtr_INS_UPD_REJ_INSERT.DIV_S3_POL_SYM as DIV_S3_POL_SYM1,
rtr_INS_UPD_REJ_INSERT.DIV_S3_POL_NBR as DIV_S3_POL_NBR1,
rtr_INS_UPD_REJ_INSERT.DIV_MAN_IND as DIV_MAN_IND1,
rtr_INS_UPD_REJ_INSERT.DIV_POL_LAPSE as DIV_POL_LAPSE1,
rtr_INS_UPD_REJ_INSERT.NR as NR1,
rtr_INS_UPD_REJ_INSERT.INF_UNIT_CTS as INF_UNIT_CTS1,
rtr_INS_UPD_REJ_INSERT.POLICY_ACTIVITY as POLICY_ACTIVITY1,
rtr_INS_UPD_REJ_INSERT.INFORCE_IND as INFORCE_IND1,
rtr_INS_UPD_REJ_INSERT.LOB_GROUP as LOB_GROUP1,
rtr_INS_UPD_REJ_INSERT.FEED_DT as FEED_DT1,
rtr_INS_UPD_REJ_INSERT.out_CHK as out_CHK1,
rtr_INS_UPD_REJ_INSERT.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID1,
rtr_INS_UPD_REJ_INSERT.out_ECTL_SRC_ID as out_ECTL_SRC_ID1,
rtr_INS_UPD_REJ_INSERT.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID1,
rtr_INS_UPD_REJ_INSERT.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID1,
rtr_INS_UPD_REJ_INSERT.out_ORIG_INS_TS as out_ORIG_INS_TS1,
rtr_INS_UPD_REJ_INSERT.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE1,
rtr_INS_UPD_REJ_INSERT.out_ECTL_TABLE_ID as out_ECTL_TABLE_ID1,
''NEW'' as out_ECTL_TX_CD,
TO_DATE ( ''99991231'' , ''YYYYMMDD'' ) as out_ECTL_END_DATE,
rtr_INS_UPD_REJ_INSERT.CHG_EFF_DT_lkup as CHG_EFF_DT_lkup1,
rtr_INS_UPD_REJ_INSERT.source_record_id
FROM
rtr_INS_UPD_REJ_INSERT
);


-- Component LKP_TARGET1, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_TARGET1 AS
(
SELECT
LKP.PLCY_NBR_lkup,
LKP.STATUS_OGN_EFF_DT_lkup,
LKP.POLICY_ACTIVITY_lkup,
exp_CALC_ECTL_END_DATE.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_CALC_ECTL_END_DATE.source_record_id ORDER BY LKP.PLCY_NBR_lkup asc,LKP.STATUS_OGN_EFF_DT_lkup asc,LKP.POLICY_ACTIVITY_lkup asc) RNK
FROM
exp_CALC_ECTL_END_DATE
LEFT JOIN (
SELECT MULTILINE_POLSTAT.STATUS_OGN_EFF_DT as STATUS_OGN_EFF_DT_lkup, 
MULTILINE_POLSTAT.PLCY_NBR as PLCY_NBR_lkup, 
MULTILINE_POLSTAT.POLICY_ACTIVITY as POLICY_ACTIVITY_lkup FROM DB_T_ML_PROD.MULTILINE_POLSTAT  
WHERE (POLICY_ACTIVITY_lkup IS NOT NULL OR TRIM(POLICY_ACTIVITY_lkup)='''')
QUALIFY RANK () OVER (PARTITION BY PLCY_NBR ORDER BY FEED_DT DESC) =1
) LKP ON LKP.PLCY_NBR_lkup = exp_CALC_ECTL_END_DATE.POL_NBR1
QUALIFY RNK = 1
);


-- Component exp_CALC_STATUS_OGN_EFF_DT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CALC_STATUS_OGN_EFF_DT AS
(
SELECT
exp_CALC_ECTL_END_DATE.POL_SYMBOL1 as POL_SYMBOL1,
exp_CALC_ECTL_END_DATE.POL_NBR1 as POL_NBR1,
exp_CALC_ECTL_END_DATE.COMPANY1 as COMPANY1,
exp_CALC_ECTL_END_DATE.STATE1 as STATE1,
exp_CALC_ECTL_END_DATE.STATUS1 as STATUS1,
CASE WHEN exp_CALC_ECTL_END_DATE.POLICY_ACTIVITY1 = LKP_TARGET1.POLICY_ACTIVITY_lkup THEN LKP_TARGET1.STATUS_OGN_EFF_DT_lkup ELSE exp_CALC_ECTL_END_DATE.FEED_DT1 END as out_STATUS_OGN_EFF_DT,
exp_CALC_ECTL_END_DATE.AGENT1 as AGENT1,
exp_CALC_ECTL_END_DATE.SERV_CNTR1 as SERV_CNTR1,
exp_CALC_ECTL_END_DATE.DIST_REGION1 as DIST_REGION1,
exp_CALC_ECTL_END_DATE.EFF_DT_CYMD1 as EFF_DT_CYMD1,
exp_CALC_ECTL_END_DATE.EXP_DT_CYMD1 as EXP_DT_CYMD1,
exp_CALC_ECTL_END_DATE.out_CHG_EFF_DT as out_CHG_EFF_DT,
exp_CALC_ECTL_END_DATE.out_CHG_EXP_DT as out_CHG_EXP_DT,
exp_CALC_ECTL_END_DATE.ADD_COV1 as ADD_COV1,
exp_CALC_ECTL_END_DATE.FIRE_CONVERT_TRANS_CODE1 as FIRE_CONVERT_TRANS_CODE1,
exp_CALC_ECTL_END_DATE.SM_POL_INDICATOR1 as SM_POL_INDICATOR1,
exp_CALC_ECTL_END_DATE.REASON1 as REASON1,
exp_CALC_ECTL_END_DATE.TOT_PREM1 as TOT_PREM1,
exp_CALC_ECTL_END_DATE.FIRE_HOME_TYPE_POL1 as FIRE_HOME_TYPE_POL1,
exp_CALC_ECTL_END_DATE.MEMBER_TYPE1 as MEMBER_TYPE1,
exp_CALC_ECTL_END_DATE.MEMBER_NBR1 as MEMBER_NBR1,
exp_CALC_ECTL_END_DATE.NAMED_INS1 as NAMED_INS1,
exp_CALC_ECTL_END_DATE.ADDL_NMD_INS1 as ADDL_NMD_INS1,
exp_CALC_ECTL_END_DATE.ADDR11 as ADDR11,
exp_CALC_ECTL_END_DATE.ADDR21 as ADDR21,
exp_CALC_ECTL_END_DATE.CITY1 as CITY1,
exp_CALC_ECTL_END_DATE.ADDR_STATE1 as ADDR_STATE1,
exp_CALC_ECTL_END_DATE.ZIP1 as ZIP1,
exp_CALC_ECTL_END_DATE.DIV_S3_POL_SYM1 as DIV_S3_POL_SYM1,
exp_CALC_ECTL_END_DATE.DIV_S3_POL_NBR1 as DIV_S3_POL_NBR1,
exp_CALC_ECTL_END_DATE.DIV_MAN_IND1 as DIV_MAN_IND1,
exp_CALC_ECTL_END_DATE.DIV_POL_LAPSE1 as DIV_POL_LAPSE1,
exp_CALC_ECTL_END_DATE.NR1 as NR1,
exp_CALC_ECTL_END_DATE.INF_UNIT_CTS1 as INF_UNIT_CTS1,
exp_CALC_ECTL_END_DATE.POLICY_ACTIVITY1 as in_POLICY_ACTIVITY,
exp_CALC_ECTL_END_DATE.INFORCE_IND1 as INFORCE_IND1,
exp_CALC_ECTL_END_DATE.LOB_GROUP1 as LOB_GROUP1,
exp_CALC_ECTL_END_DATE.FEED_DT1 as FEED_DT1,
exp_CALC_ECTL_END_DATE.out_ECTL_PRGM_ID1 as ECTL_PRGM_ID1,
exp_CALC_ECTL_END_DATE.out_ECTL_SRC_ID1 as ECTL_SRC_ID1,
exp_CALC_ECTL_END_DATE.out_ECTL_SRC_INST_ID1 as ECTL_SRC_INST_ID1,
exp_CALC_ECTL_END_DATE.out_ECTL_BATCH_ID1 as ECTL_BATCH_ID1,
exp_CALC_ECTL_END_DATE.out_ORIG_INS_TS1 as ORIG_INS_TS1,
exp_CALC_ECTL_END_DATE.out_ECTL_BATCH_START_DATE1 as ECTL_BATCH_START_DATE1,
exp_CALC_ECTL_END_DATE.out_ECTL_TX_CD as ECTL_TX_CD,
exp_CALC_ECTL_END_DATE.out_ECTL_END_DATE as ECTL_END_DATE,
exp_CALC_ECTL_END_DATE.source_record_id
FROM
exp_CALC_ECTL_END_DATE
INNER JOIN LKP_TARGET1 ON exp_CALC_ECTL_END_DATE.source_record_id = LKP_TARGET1.source_record_id
);


-- Component MULTILINE_POLSTAT_INS, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE MULTILINE_POLSTAT_INS AS
(
SELECT
exp_CALC_STATUS_OGN_EFF_DT.POL_SYMBOL1 as PLCY_SYM_CD,
exp_CALC_STATUS_OGN_EFF_DT.POL_NBR1 as PLCY_NBR,
exp_CALC_STATUS_OGN_EFF_DT.COMPANY1 as MASTER_COMPANY_NBR,
exp_CALC_STATUS_OGN_EFF_DT.STATE1 as ST_CD,
exp_CALC_STATUS_OGN_EFF_DT.STATUS1 as STATUS,
exp_CALC_STATUS_OGN_EFF_DT.out_STATUS_OGN_EFF_DT as STATUS_OGN_EFF_DT,
exp_CALC_STATUS_OGN_EFF_DT.AGENT1 as AGENT,
exp_CALC_STATUS_OGN_EFF_DT.SERV_CNTR1 as PLCY_SVC_NBR,
exp_CALC_STATUS_OGN_EFF_DT.DIST_REGION1 as DIST_REGION,
exp_CALC_STATUS_OGN_EFF_DT.EFF_DT_CYMD1 as EFF_DT,
exp_CALC_STATUS_OGN_EFF_DT.EXP_DT_CYMD1 as EXP_DT,
exp_CALC_STATUS_OGN_EFF_DT.out_CHG_EFF_DT as PLCY_CHG_EFF_DT,
exp_CALC_STATUS_OGN_EFF_DT.out_CHG_EXP_DT as PLCY_CHG_EXP_DT,
exp_CALC_STATUS_OGN_EFF_DT.ADD_COV1 as ADD_COV_CD,
exp_CALC_STATUS_OGN_EFF_DT.FIRE_CONVERT_TRANS_CODE1 as FIRE_CONVERT_TRANS_CD,
exp_CALC_STATUS_OGN_EFF_DT.SM_POL_INDICATOR1 as SM_POL_IND,
exp_CALC_STATUS_OGN_EFF_DT.REASON1 as REASON,
exp_CALC_STATUS_OGN_EFF_DT.TOT_PREM1 as TOT_PREM,
exp_CALC_STATUS_OGN_EFF_DT.FIRE_HOME_TYPE_POL1 as FIRE_HOME_TYPE_POL,
exp_CALC_STATUS_OGN_EFF_DT.MEMBER_TYPE1 as ALFA_CUST_MEMB_TYPE,
exp_CALC_STATUS_OGN_EFF_DT.MEMBER_NBR1 as ALFA_CUST_MEMB_NBR,
exp_CALC_STATUS_OGN_EFF_DT.NAMED_INS1 as NAME_INSURED,
exp_CALC_STATUS_OGN_EFF_DT.ADDL_NMD_INS1 as ADDL_NAME_INSURED,
exp_CALC_STATUS_OGN_EFF_DT.ADDR11 as ADDR_LINE_1,
exp_CALC_STATUS_OGN_EFF_DT.ADDR21 as ADDR_LINE_2,
exp_CALC_STATUS_OGN_EFF_DT.CITY1 as CITY,
exp_CALC_STATUS_OGN_EFF_DT.ADDR_STATE1 as ADDR_ST_CD,
exp_CALC_STATUS_OGN_EFF_DT.ZIP1 as ZIP_CD,
exp_CALC_STATUS_OGN_EFF_DT.DIV_S3_POL_SYM1 as DIV_S3_POL_SYM,
exp_CALC_STATUS_OGN_EFF_DT.DIV_S3_POL_NBR1 as DIV_S3_POL_NBR,
exp_CALC_STATUS_OGN_EFF_DT.DIV_MAN_IND1 as DIV_MAN_IND,
exp_CALC_STATUS_OGN_EFF_DT.DIV_POL_LAPSE1 as DIV_POL_LAPSE,
exp_CALC_STATUS_OGN_EFF_DT.NR1 as NR,
exp_CALC_STATUS_OGN_EFF_DT.INF_UNIT_CTS1 as INF_UNIT_CTS,
exp_CALC_STATUS_OGN_EFF_DT.in_POLICY_ACTIVITY as POLICY_ACTIVITY,
exp_CALC_STATUS_OGN_EFF_DT.INFORCE_IND1 as INFORCE_IND,
exp_CALC_STATUS_OGN_EFF_DT.LOB_GROUP1 as LOB_CD,
exp_CALC_STATUS_OGN_EFF_DT.FEED_DT1 as FEED_DT,
exp_CALC_STATUS_OGN_EFF_DT.ECTL_BATCH_ID1 as ECTL_BATCH_ID,
exp_CALC_STATUS_OGN_EFF_DT.ORIG_INS_TS1 as ECTL_ORIG_INS_TS,
exp_CALC_STATUS_OGN_EFF_DT.ORIG_INS_TS1 as ECTL_MODIFY_TS,
exp_CALC_STATUS_OGN_EFF_DT.ECTL_SRC_ID1 as ECTL_SRC_ID,
exp_CALC_STATUS_OGN_EFF_DT.ECTL_SRC_INST_ID1 as ECTL_SRC_INST_ID,
exp_CALC_STATUS_OGN_EFF_DT.ECTL_PRGM_ID1 as ECTL_PRGM_ID,
exp_CALC_STATUS_OGN_EFF_DT.ECTL_TX_CD as ECTL_TX_CD,
exp_CALC_STATUS_OGN_EFF_DT.ECTL_BATCH_START_DATE1 as ECTL_START_DATE,
exp_CALC_STATUS_OGN_EFF_DT.ECTL_END_DATE as ECTL_END_DATE
FROM
exp_CALC_STATUS_OGN_EFF_DT
);

copy into @my_internal_stage/MULTILINE_POLSTAT_INS from (select * from MULTILINE_POLSTAT_INS)
header=true
overwrite=true;

-- Component MULTILINE_POLSTAT_INS, Type EXPORT_DATA Exporting data
;


-- Component MULTILINE_POLSTAT_UPD, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_ML_PROD.MULTILINE_POLSTAT
USING upd_TARGET
ON (PLCY_NBR = upd_TARGET.POL_NBR3 AND  
PLCY_CHG_EFF_DT = upd_TARGET.CHG_EFF_DT3 AND
FEED_DT=upd_TARGET.FEED_DT_lkup3)
WHEN MATCHED THEN UPDATE SET
PLCY_CHG_EXP_DT = upd_TARGET.out_CHG_EXP_DT, 
ECTL_BATCH_ID = upd_TARGET.out_ECTL_BATCH_ID3, 
ECTL_MODIFY_TS = upd_TARGET.out_ORIG_INS_TS3, 
ECTL_PRGM_ID = upd_TARGET.out_ECTL_PRGM_ID3, 
ECTL_TX_CD = upd_TARGET.out_ECTL_TX_CD
--,ECTL_END_DATE = upd_TARGET.ECTL_END_DATE
;



END; ';