-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BIBASE_W_PLCY_INFO_DTL_FLOW_INSUPD("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
       run_id STRING;
       lastrundate_plcy STRING;
	   v_start_time TIMESTAMP;
BEGIN
       run_id := (SELECT run_id FROM control_run_id WHERE worklet_name = :worklet_name ORDER BY insert_ts DESC LIMIT 1);
       lastrundate_plcy := current_date();  -- changed to current_date for testing
       --(SELECT param_value FROM control_params WHERE run_id = :run_id AND param_name = ''lastrundate_plcy'' LIMIT 1);
	   v_start_time := CURRENT_TIMESTAMP();

-- Component SQ_AGMT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGMT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CAL_MO_ID,
$2 as CALENDAR_DATE,
$3 as LOB_CD,
$4 as CMPY_CD,
$5 as ST_CD,
$6 as RGN_CD,
$7 as DIST_CD,
$8 as SALES_CNTY_CD,
$9 as RSK_CNTY_CD,
$10 as SVC_CD,
$11 as AGENT_NBR,
$12 as PRIOR_INS_CARRIER_CD,
$13 as GENDER_CD,
$14 as MARITAL_STATUS_CD,
$15 as OCP_CD,
$16 as DRV_POINTS,
$17 as AGE,
$18 as INS_SCR_CD,
$19 as LEVEL_NBR,
$20 as DW_COV_TYPE_CD,
$21 as PP_COV_TYPE_CD,
$22 as INFO_VAL_DED,
$23 as INFO_VAL_FORM,
$24 as INFO_VAL_CNST,
$25 as INFO_VAL_CNYR,
$26 as INFO_VAL_PROT,
$27 as YRS_WITH_ALFA,
$28 as AUTO_DISC,
$29 as DSC_VAL_NWHM,
$30 as INFO_VAL_CLFR,
$31 as DSC_VAL_VCLP,
$32 as DSC_VAL_HAPC,
$33 as INFO_VAL_ALRT,
$34 as PLCY_CNT_WRIT_IFO,
$35 as PLCY_CNT_NEW_BUS,
$36 as TOTAL_VEH_IFO,
$37 as RISK_ST_CD,
$38 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT

EXTRACT(MONTH FROM TO_DATE(:lastrundate_plcy, ''YYYY-MM-DD'')) + 12 * (EXTRACT(YEAR FROM TO_DATE(:lastrundate_plcy, ''YYYY-MM-DD''))-1900) AS CAL_MO_ID

,TO_DATE(:lastrundate_plcy, ''YYYY-MM-DD'') AS CALENDAR_DATE

/* ,PRO.INSRNC_LOB_TYPE_CD AS LOB_CD */
,CASE WHEN PRO.INSRNC_LOB_TYPE_CD = ''PUP'' THEN ''UMBRELLA'' ELSE PRO.INSRNC_LOB_TYPE_CD END AS LOB_CD

,IO.INTRNL_ORG_NUM AS CMPY_CD

,orn.ORG_NAME AS SALES_ST_CD

,orn.ORG_NAME AS RGN_CD

,orn.ORG_NAME AS DIST_CD

,PL1.GEOGRCL_AREA_NAME AS SALES_CNTY_CD

,CASE

WHEN PRO.PROD_NAME IN (''PPV'',''COMMERCIAL'',''CPL'',''PAF'',''WATERCRAFT'') THEN AUTORSK.CN_NM

WHEN PRO.PROD_NAME IN (''SF3'',''HO3'',''MH3'',''HO6'',''HO8'',''HO4'',''SF2'',''SF1'',''HO2'',''MH4'',''MH9'',''MH7'',''SF4'',''HO5'',''FCL'',''Farmowners'',''MACHINERY'') THEN PRORSK.CN_NM

END AS RSK_CNTY_CD

, REGEXP_REPLACE(orn.ORG_NAME, ''^0+'', '''') AS SVC_CD

, REGEXP_REPLACE(IO1.INTRNL_ORG_NUM, ''^0+'', '''') AS AGENT_NBR

,PRINSNM.ORG_NAME_DESC AS PRIOR_INS_CARRIER_CD

,INDV.GNDR_TYPE_CD AS GENDER_CD

,IMS.MRTL_STS_CD AS MARITAL_STATUS_CD

,INO.OCPTN_TYPE_CD AS OCC_CD

,CASE WHEN PDH.PNLTY_PNTS_CNT > ''12'' THEN ''99'' ELSE PDH.PNLTY_PNTS_CNT END AS DRV_POINTS

,EXTRACT(YEAR FROM TO_DATE(:lastrundate_plcy, ''YYYY-MM-DD'')) - EXTRACT(YEAR FROM INDV.BIRTH_DT) AS AGE

,CAST(CASE

WHEN PR2.PROD_NAME = ''AUTO'' THEN

(CASE

WHEN PS.PRTY_SCR_VAL BETWEEN 0 AND 538 THEN ''001''

WHEN PS.PRTY_SCR_VAL BETWEEN 539 AND 556 THEN ''002''

WHEN PS.PRTY_SCR_VAL BETWEEN 557 AND 598 THEN ''003''

WHEN PS.PRTY_SCR_VAL BETWEEN 599 AND 638 THEN ''004''

WHEN PS.PRTY_SCR_VAL BETWEEN 639 AND 673 THEN ''005''

WHEN PS.PRTY_SCR_VAL BETWEEN 674 AND 712 THEN ''006''

WHEN PS.PRTY_SCR_VAL BETWEEN 713 AND 763 THEN ''007''

WHEN PS.PRTY_SCR_VAL BETWEEN 764 AND 806 THEN ''008''

WHEN PS.PRTY_SCR_VAL BETWEEN 807 AND 998 THEN ''009''

ELSE ''999''

END)

ELSE

(CASE

WHEN (PS.PRTY_SCR_VAL BETWEEN 0 AND 400 OR PS.PRTY_SCR_VAL IS NULL) THEN ''1''

WHEN PS.PRTY_SCR_VAL BETWEEN 401 AND 425 THEN ''2''

WHEN PS.PRTY_SCR_VAL BETWEEN 426 AND 450 THEN ''3''

WHEN PS.PRTY_SCR_VAL BETWEEN 451 AND 475 THEN ''4''

WHEN PS.PRTY_SCR_VAL BETWEEN 476 AND 500 THEN ''5''

WHEN PS.PRTY_SCR_VAL BETWEEN 501 AND 525 THEN ''6''

WHEN PS.PRTY_SCR_VAL BETWEEN 526 AND 550 THEN ''7''

WHEN PS.PRTY_SCR_VAL BETWEEN 551 AND 575 THEN ''8''

WHEN PS.PRTY_SCR_VAL BETWEEN 576 AND 600 THEN ''9''

WHEN PS.PRTY_SCR_VAL BETWEEN 601 AND 625 THEN ''10''

WHEN PS.PRTY_SCR_VAL BETWEEN 626 AND 650 THEN ''11''

WHEN PS.PRTY_SCR_VAL BETWEEN 651 AND 675 THEN ''12''

WHEN PS.PRTY_SCR_VAL BETWEEN 676 AND 700 THEN ''13''

WHEN PS.PRTY_SCR_VAL BETWEEN 701 AND 725 THEN ''14''

WHEN PS.PRTY_SCR_VAL BETWEEN 726 AND 750 THEN ''15''

WHEN PS.PRTY_SCR_VAL BETWEEN 751 AND 775 THEN ''16''

WHEN PS.PRTY_SCR_VAL BETWEEN 776 AND 800 THEN ''17''

WHEN PS.PRTY_SCR_VAL BETWEEN 801 AND 825 THEN ''18''

WHEN PS.PRTY_SCR_VAL BETWEEN 826 AND 850 THEN ''19''

WHEN PS.PRTY_SCR_VAL BETWEEN 851 AND 875 THEN ''20''

WHEN PS.PRTY_SCR_VAL BETWEEN 876 AND 900 THEN ''21''

WHEN PS.PRTY_SCR_VAL BETWEEN 901 AND 925 THEN ''22''

WHEN PS.PRTY_SCR_VAL BETWEEN 926 AND 950 THEN ''23''

WHEN PS.PRTY_SCR_VAL BETWEEN 951 AND 975 THEN ''24''

WHEN PS.PRTY_SCR_VAL BETWEEN 976 AND 1000 THEN''25''

ELSE ''26''

END)

END AS VARCHAR(10)) AS INS_SCR_CD

,CAST(PS.LVL_NUM AS INT) AS LEVEL_NBR

,CASE

WHEN (BB.COV_DW = 0 OR BB.COV_DW IS NULL) THEN 0

WHEN BB.COV_DW BETWEEN 1 AND 10000  THEN 1

WHEN BB.COV_DW BETWEEN 10001 AND 20000  THEN 2

WHEN BB.COV_DW BETWEEN 20001 AND 30000  THEN 3

WHEN BB.COV_DW BETWEEN 30001 AND 40000  THEN 4

WHEN BB.COV_DW BETWEEN 40001 AND 50000  THEN 5

WHEN BB.COV_DW BETWEEN 50001 AND 60000  THEN 6

WHEN BB.COV_DW BETWEEN 60001 AND 70000  THEN 7

WHEN BB.COV_DW BETWEEN 70001 AND 80000  THEN 8

WHEN BB.COV_DW BETWEEN 80001 AND 90000  THEN 9

WHEN BB.COV_DW BETWEEN 90001 AND 100000  THEN 10

WHEN BB.COV_DW BETWEEN 100001 AND 125000  THEN 11

WHEN BB.COV_DW BETWEEN 125001 AND 150000  THEN 12

WHEN BB.COV_DW BETWEEN 150001 AND 175000  THEN 13

WHEN BB.COV_DW BETWEEN 175001 AND 200000  THEN 14

WHEN BB.COV_DW BETWEEN 200001 AND 225000  THEN 15

WHEN BB.COV_DW BETWEEN 225001 AND 250000  THEN 16

WHEN BB.COV_DW BETWEEN 250001 AND 275000  THEN 17

WHEN BB.COV_DW BETWEEN 275001 AND 300000  THEN 18

WHEN BB.COV_DW BETWEEN 300001 AND 350000  THEN 19

WHEN BB.COV_DW BETWEEN 350001 AND 400000  THEN 20

WHEN BB.COV_DW BETWEEN 400001 AND 450000  THEN 21

WHEN BB.COV_DW BETWEEN 450001 AND 500000  THEN 22

WHEN BB.COV_DW BETWEEN 500001 AND 550000  THEN 23

WHEN BB.COV_DW BETWEEN 550001 AND 600000  THEN 24

WHEN BB.COV_DW BETWEEN 600001 AND 650000  THEN 25

WHEN BB.COV_DW BETWEEN 650001 AND 700000  THEN 26

WHEN BB.COV_DW BETWEEN 700001 AND 750000  THEN 27

WHEN BB.COV_DW BETWEEN 750001 AND 800000  THEN 28

WHEN BB.COV_DW BETWEEN 800001 AND 850000  THEN 29

WHEN BB.COV_DW BETWEEN 850001 AND 900000  THEN 30

WHEN BB.COV_DW BETWEEN 900001 AND 950000  THEN 31

WHEN BB.COV_DW BETWEEN 950001 AND 1000000  THEN 32

ELSE 33

END AS DW_COV_TYPE_CD

,CASE

WHEN (BB.COV_PP = 0 OR BB.COV_PP IS NULL) THEN 0

WHEN BB.COV_PP BETWEEN 1 AND 10000 THEN 1

WHEN BB.COV_PP BETWEEN 10001 AND 20000 THEN 2

WHEN BB.COV_PP BETWEEN 20001 AND 30000 THEN 3

WHEN BB.COV_PP BETWEEN 30001 AND 40000 THEN 4

WHEN BB.COV_PP BETWEEN 40001 AND 50000 THEN 5

WHEN BB.COV_PP BETWEEN 50001 AND 60000 THEN 6

WHEN BB.COV_PP BETWEEN 60001 AND 70000 THEN 7

WHEN BB.COV_PP BETWEEN 70001 AND 80000 THEN 8

WHEN BB.COV_PP BETWEEN 80001 AND 90000 THEN 9

WHEN BB.COV_PP BETWEEN 90001 AND 100000 THEN 10

WHEN BB.COV_PP BETWEEN 100001 AND 125000 THEN 11

WHEN BB.COV_PP BETWEEN 125001 AND 150000 THEN 12

WHEN BB.COV_PP BETWEEN 150001 AND 175000 THEN 13

WHEN BB.COV_PP BETWEEN 175001 AND 200000 THEN 14

WHEN BB.COV_PP BETWEEN 200001 AND 225000 THEN 15

WHEN BB.COV_PP BETWEEN 225001 AND 250000 THEN 16

WHEN BB.COV_PP BETWEEN 250001 AND 275000 THEN 17

WHEN BB.COV_PP BETWEEN 275001 AND 300000 THEN 18

WHEN BB.COV_PP BETWEEN 300001 AND 350000 THEN 19

WHEN BB.COV_PP BETWEEN 350001 AND 400000 THEN 20

WHEN BB.COV_PP BETWEEN 400001 AND 450000 THEN 21

WHEN BB.COV_PP BETWEEN 450001 AND 500000 THEN 22

WHEN BB.COV_PP BETWEEN 500001 AND 550000 THEN 23

WHEN BB.COV_PP BETWEEN 550001 AND 600000 THEN 24

WHEN BB.COV_PP BETWEEN 600001 AND 650000 THEN 25

WHEN BB.COV_PP BETWEEN 650001 AND 700000 THEN 26

WHEN BB.COV_PP BETWEEN 700001 AND 750000 THEN 27

WHEN BB.COV_PP BETWEEN 750001 AND 800000 THEN 28

WHEN BB.COV_PP BETWEEN 800001 AND 850000 THEN 29

WHEN BB.COV_PP BETWEEN 850001 AND 900000 THEN 30

WHEN BB.COV_PP BETWEEN 900001 AND 950000 THEN 31

WHEN BB.COV_PP BETWEEN 950001 AND 1000000 THEN 32

ELSE 33

END AS PP_COV_TYPE_CD

,BB.DED AS INFO_VAL_DED

,PRO.PROD_NAME AS INFO_VAL_FORM

,PRTCLS.INFO_VAL_CNST

,PRTCLS.INFO_VAL_CNYR

,PRTCLS.PRT_CLASS AS INFO_VAL_PROT

,(EXTRACT(YEAR FROM TO_DATE(:lastrundate_plcy, ''YYYY-MM-DD'')) - EXTRACT(YEAR FROM AG.AGMT_OPN_DTTM)) AS YRS_WITH_ALFA

,CAST(CASE WHEN BB.AUTO_DISC = 1 THEN ''Yes'' ELSE ''No'' END AS VARCHAR(3)) AS AUTO_DISC

,BB.NEW_HO_DSCNT AS DSC_VAL_NWHM

,CASE WHEN CLMF2.CFI=''Y'' THEN ''Y'' ELSE CASE WHEN CLMF1.CFI=1 THEN ''Y'' ELSE ''N'' END END AS INFO_VAL_CLFR

,BB.F1 AS DSC_VAL_VCLP

,BB.HOA_DSCNT AS DSC_VAL_HAPC

,HM_ALRT.ASSET_DTL_CD AS INFO_VAL_ALRT

,COUNT(DISTINCT INFORCE.PLCY_NUM) AS PLCY_CNT_WRIT_IFO

,COUNT(DISTINCT NEWPOL.PLCY_NUM) AS  PLCY_CNT_NEW_BUS

,CASE WHEN --PRD_RLP 
PR2.PROD_NAME IN (''PROPERTY'',''OTHER PROPERTY'') THEN 0 ELSE SUM(COALESCE(INFORCE.ASSCNT,0)) END AS TOTAL_VEH_IFO

,CASE

WHEN PRO.PROD_NAME IN (''PPV'',''COMMERCIAL'',''CPL'',''PAF'',''WATERCRAFT'') THEN AUTORSK.STATE_CD

WHEN PRO.PROD_NAME IN (''SF3'',''HO3'',''MH3'',''HO6'',''HO8'',''HO4'',''SF2'',''SF1'',''HO2'',''MH4'',''MH9'',''MH7'',''SF4'',''HO5'',''FCL'',''Farmowners'',''MACHINERY'') THEN PRORSK.STATE_CD

END AS RISK_ST_CD

,PR2.PROD_NAME AS PRD_RLP





FROM DB_T_PROD_CORE.AGMT AG

LEFT OUTER JOIN DB_T_PROD_CORE.PRTY_AGMT   PA10

ON AG.AGMT_ID = PA10.AGMT_ID

AND PA10.PRTY_AGMT_ROLE_CD = ''CMP''

AND PA10.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG IO

ON IO.INTRNL_ORG_PRTY_ID = PA10.PRTY_ID

AND cast(:lastrundate_plcy as date) BETWEEN IO.TRANS_STRT_DTTM AND IO.TRANS_END_DTTM

LEFT OUTER JOIN DB_T_PROD_CORE.PRTY_AGMT   PA12

ON AG.AGMT_ID = PA12.AGMT_ID

AND PA12.PRTY_AGMT_ROLE_CD = ''SVC''

AND PA12.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''



LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG PA

ON PA.INTRNL_ORG_PRTY_ID = PA12.PRTY_ID

AND Cast( :lastrundate_plcy  as date) BETWEEN PA.TRANS_STRT_DTTM AND PA.TRANS_END_DTTM

LEFT OUTER JOIN DB_T_PROD_CORE.ORG_NAME ORN

ON ORN.PRTY_ID = PA.INTRNL_ORG_PRTY_ID

AND ORN.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

LEFT OUTER JOIN (SELECT RLTD_PRTY_ID, MAX(PRTY_ID) PRTY_ID

FROM DB_T_PROD_CORE.PRTY_RLTD

WHERE Cast( :lastrundate_plcy  as date) BETWEEN TRANS_STRT_DTTM AND TRANS_END_DTTM

AND PRTY_RLTD_ROLE_CD = ''DISTTOSVC''

AND PRTY_STRC_TYPE_CD = ''SLSHRCHY''

GROUP BY RLTD_PRTY_ID) IND

ON IND.RLTD_PRTY_ID = PA.INTRNL_ORG_PRTY_ID



LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG PA1

ON IND.PRTY_ID = PA1.INTRNL_ORG_PRTY_ID

AND Cast( :lastrundate_plcy  as date) BETWEEN PA1.TRANS_STRT_DTTM AND PA1.TRANS_END_DTTM

LEFT OUTER JOIN DB_T_PROD_CORE.ORG_NAME ORN1

ON ORN1.PRTY_ID = PA1.INTRNL_ORG_PRTY_ID

AND ORN1.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

LEFT OUTER JOIN DB_T_PROD_CORE.PRTY_RLTD IND1

ON IND1.RLTD_PRTY_ID = PA1.INTRNL_ORG_PRTY_ID

AND IND1.PRTY_STRC_TYPE_CD = ''SLSHRCHY''

AND Cast( :lastrundate_plcy  as date) BETWEEN IND1.TRANS_STRT_DTTM AND IND1.TRANS_END_DTTM



LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG PA2

ON IND1.PRTY_ID = PA2.INTRNL_ORG_PRTY_ID

AND Cast( :lastrundate_plcy  as date) BETWEEN PA2.TRANS_STRT_DTTM AND PA2.TRANS_END_DTTM

LEFT OUTER JOIN DB_T_PROD_CORE.ORG_NAME ORN2

ON ORN2.PRTY_ID = PA2.INTRNL_ORG_PRTY_ID

AND ORN2.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

LEFT OUTER JOIN DB_T_PROD_CORE.PRTY_RLTD IND2

ON IND2.RLTD_PRTY_ID = PA2.INTRNL_ORG_PRTY_ID

AND IND2.PRTY_STRC_TYPE_CD = ''SLSHRCHY''

AND Cast( :lastrundate_plcy  as date) BETWEEN IND2.TRANS_STRT_DTTM AND IND2.TRANS_END_DTTM



LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG PA3

ON IND2.PRTY_ID = PA3.INTRNL_ORG_PRTY_ID

AND Cast( :lastrundate_plcy  as date) BETWEEN PA3.TRANS_STRT_DTTM AND PA3.TRANS_END_DTTM

LEFT OUTER JOIN DB_T_PROD_CORE.ORG_NAME ORN3

ON ORN3.PRTY_ID = PA3.INTRNL_ORG_PRTY_ID

AND ORN3.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''



LEFT OUTER JOIN (SELECT PL.PRTY_ID, GEOGRCL_AREA_NAME

FROM DB_T_PROD_CORE.PRTY_ADDR PL

JOIN DB_T_PROD_CORE.CNTY CN

ON PL.LOC_ID = CN.CNTY_ID

AND CN.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

/* AND Cast( :lastrundate_plcy  as date) BETWEEN PL.TRANS_STRT_DTTM AND PL.TRANS_END_DTTM */
AND PL.TRANS_STRT_DTTM <= Cast( :lastrundate_plcy  as date)

AND PL.TRANS_END_DTTM > Cast( :lastrundate_plcy  as date)

AND PL.PRTY_ADDR_USGE_TYPE_CD = ''BUSNCNTY'') PL1

ON PA.INTRNL_ORG_PRTY_ID = PL1.PRTY_ID



LEFT OUTER JOIN DB_T_PROD_CORE.PRTY_AGMT   PA13

ON AG.AGMT_ID = PA13.AGMT_ID

AND PA13.PRTY_AGMT_ROLE_CD = ''PRDA''

AND PA13.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG IO1

ON IO1.INTRNL_ORG_PRTY_ID = PA13.PRTY_ID

AND Cast( :lastrundate_plcy  as date) BETWEEN IO1.TRANS_STRT_DTTM AND IO1.TRANS_END_DTTM

LEFT OUTER JOIN (SELECT DISTINCT AGMT_ID,PRTY_AGMT_ROLE_CD,EDW_END_DTTM,PRTY_ID FROM DB_T_PROD_CORE.PRTY_AGMT

QUALIFY RANK() OVER (PARTITION BY AGMT_ID ORDER BY  EDW_STRT_DTTM DESC) = 1)   PA14

ON AG.AGMT_ID = PA14.AGMT_ID

AND PA14.PRTY_AGMT_ROLE_CD = ''PLCYPRININS''

AND PA14.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''



LEFT OUTER JOIN (SELECT DISTINCT PRTY_ID, PRTY_SCR_VAL, LVL_NUM

FROM DB_T_PROD_CORE.PRTY_SCR PS

JOIN DB_T_PROD_CORE.MODL_RUN MR

ON PS.MODL_ID = MR.MODL_ID

AND PS.MODL_RUN_ID = MR.MODL_RUN_ID

AND MR.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND PS.EDW_END_DTTM = ''9999-12-31 23:59:59.999999'' /* -newly added EIM_18186 */

WHERE Cast( :lastrundate_plcy  as date) BETWEEN TRANS_STRT_DTTM AND TRANS_END_DTTM

AND CAST(MR.MODL_RUN_DTTM AS DATE) <= Cast( :lastrundate_plcy  as date)

QUALIFY ROW_NUMBER() OVER (PARTITION BY PS.PRTY_ID ORDER BY PS.MODL_RUN_ID DESC, MR.MODL_RUN_DTTM DESC,TRANS_STRT_DTTM DESC) = 1

) PS

ON PS.PRTY_ID = PA14.PRTY_ID



LEFT OUTER JOIN DB_T_PROD_CORE.PRTY_AGMT   PA15

ON AG.AGMT_ID = PA15.AGMT_ID

AND PA15.PRTY_AGMT_ROLE_CD = ''PRIINSCAR''

AND PA15.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''



LEFT OUTER JOIN DB_T_PROD_CORE.ORG_NAME PRINSNM

ON PRINSNM.PRTY_ID = PA15.PRTY_ID

AND Cast( :lastrundate_plcy  as date) BETWEEN PRINSNM.TRANS_STRT_DTTM AND PRINSNM.TRANS_END_DTTM

LEFT OUTER JOIN DB_T_PROD_CORE.INDIV_MRTL_STS IMS

ON IMS.INDIV_PRTY_ID = PA14.PRTY_ID

AND IMS.TRANS_STRT_DTTM <= Cast( :lastrundate_plcy  as date)

AND IMS.TRANS_END_DTTM > Cast( :lastrundate_plcy  as date)

LEFT OUTER JOIN DB_T_PROD_CORE.INDIV INDV

ON INDV.INDIV_PRTY_ID = PA14.PRTY_ID

AND INDV.TRANS_STRT_DTTM <= Cast( :lastrundate_plcy  as date)

AND INDV.TRANS_END_DTTM > Cast( :lastrundate_plcy  as date)

LEFT OUTER JOIN DB_T_PROD_CORE.MRTL_STS_TYPE MST

ON MST.MRTL_STS_CD = IMS.MRTL_STS_CD

AND Cast( :lastrundate_plcy  as date) BETWEEN MST.EFF_DT AND MST.EXPN_DT

LEFT OUTER JOIN (SELECT *

FROM DB_T_PROD_CORE.INDIV_OCPTN

WHERE EDW_END_DTTM = ''9999-12-31 23:59:59.999999''/* -newly added EIM_18197 */
QUALIFY RANK() OVER (PARTITION BY INDIV_PRTY_ID ORDER BY INDIV_OCPTN_STRT_DTTM DESC) = 1) INO

ON INO.INDIV_PRTY_ID = PA14.PRTY_ID

AND Cast( :lastrundate_plcy  as date) BETWEEN INO.TRANS_STRT_DTTM AND INO.TRANS_END_DTTM

LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_PROD AP1

ON AP1.AGMT_ID = AG.AGMT_ID

AND AP1.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND AP1.AGMT_PROD_ROLE_CD = ''PLCYTYPE''

LEFT OUTER JOIN DB_T_PROD_CORE.PROD PRO

ON AP1.PROD_ID = PRO.PROD_ID

AND PRO.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND PRO.PROD_SBTYPE_CD = ''PLCYTYPE''

LEFT OUTER JOIN DB_T_PROD_CORE.INSRNC_LOB_TYPE ILT

ON ILT.INSRNC_LOB_TYPE_CD = PRO.INSRNC_LOB_TYPE_CD

AND PRO.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND PRO.PROD_SBTYPE_CD = ''PLCYTYPE''

LEFT OUTER JOIN DB_T_PROD_CORE.PROD_RLTD PRL1

ON PRL1.RLTD_PROD_ID = PRO.PROD_ID

AND PRL1.PROD_RLTNSHP_TYPE_CD = ''EPRDDOM''

AND Cast( :lastrundate_plcy  as date) BETWEEN PRL1.TRANS_STRT_DTTM AND PRL1.TRANS_END_DTTM

AND PRO.PROD_SBTYPE_CD = ''PLCYTYPE''

LEFT OUTER JOIN DB_T_PROD_CORE.PROD PR2

ON PRL1.PROD_ID = PR2.PROD_ID

AND PR2.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND PR2.PROD_SBTYPE_CD = ''PLCYTYPE''



LEFT OUTER JOIN (SELECT  AF.AGMT_ID

,SUM(CASE WHEN FE.INSRNC_LOB_TYPE_CD = ''PAWTC'' AND FE.COMN_FEAT_NAME IN (''COMPREHENSIVE'', ''COLLISION'') THEN 1 ELSE 0 END) AS DSCTN_CNT

,MAX(CASE WHEN FE.FEAT_SBTYPE_CD = ''MOD'' AND FE.NK_SRC_KEY IN (''PALENGTHOFSERVICEDISCOUNT_ALFA'' ,''HOLENGTHOFSERVICEDISCOUNT_ALFA'') THEN CAST(ROUND(AF.AGMT_FEAT_AMT * 100, 2) AS DECIMAL(7,2)) END) AS F1

,SUM(CASE WHEN FE.FEAT_SBTYPE_CD = ''MOD'' AND FE.NK_SRC_KEY IN (''PALENGTHOFSERVICEDISCOUNT_ALFA'' ,''HOLENGTHOFSERVICEDISCOUNT_ALFA'') THEN 1 ELSE 0 END) AS F2

,SUM(CASE WHEN FE.NK_SRC_KEY = ''PAMULTIPOLICYDISCOUNT_ALFA'' THEN 1 ELSE 0 END) AS COMBO_DISCNT

,SUM(CASE WHEN FE.NK_SRC_KEY = ''HOLIFEPOLICYDISCOUNT_ALFA'' THEN 1 ELSE 0 END) AS LIFE_DISCNT

,MAX(CASE WHEN FE.FEAT_SBTYPE_CD = ''MOD'' AND FE.NK_SRC_KEY = ''HOCONSTRUCTIONYEAR_ALFA'' AND FEAT_EFECT_TYPE_CD = ''DISC'' THEN CAST(ROUND(AF.AGMT_FEAT_AMT * 100, 2) AS DECIMAL(7,2)) END) AS NEW_HO_DSCNT

,MAX(CASE WHEN FE.NK_SRC_KEY = ''HOHOMEALERT_ALFA'' THEN TO_CHAR(AF.AGMT_FEAT_AMT * 100, ''9999999.99'') END) AS HOA_DSCNT

,MAX(CASE WHEN FE.NK_SRC_KEY = ''HODW_Dwelling_Limit_HOE'' THEN AF.AGMT_FEAT_AMT END) AS DWL

,MAX(CASE WHEN FE.NK_SRC_KEY = ''HODW_PersonalPropertyLimit_alfa'' THEN AF.AGMT_FEAT_AMT END) AS PPL

,SUM(CASE WHEN FE.NK_SRC_KEY = ''PAMULTICARDISCOUNT'' THEN 1 ELSE 0 END ) AS MULTI_CAR

,SUM(CASE WHEN FE.FEAT_SBTYPE_CD = ''MOD'' AND FE.NK_SRC_KEY = ''PAHOMEOWNERDISCOUNT_ALFA'' THEN 1 ELSE 0 END) AS HOME_DSCNT

,MAX(CASE WHEN FE.NK_SRC_KEY = ''HODW_Dwelling_Limit_HOE'' THEN AF.AGMT_FEAT_AMT END) AS COV_DW

,MAX(CASE WHEN FE.NK_SRC_KEY = ''HODW_PersonalPropertyLimit_alfa'' THEN AF.AGMT_FEAT_AMT END) AS COV_PP

,MAX(CASE WHEN FE.NK_SRC_KEY = ''HOMultiPolicyDiscount_alfa'' THEN 1 ELSE 0 END) AS AUTO_DISC

,MAX(CASE

WHEN INSRNC_CVGE_TYPE_CD = ''SD'' AND FEAT_SBTYPE_CD = ''OPT'' AND FEAT_DESC LIKE ''ALL PERILS%'' AND FEAT_DTL_CD_NAME LIKE ''%.%'' AND FEAT_DTL_CD_NAME NOT LIKE ''%K''

THEN RTRIM(TO_CHAR(FEAT_DTL_VAL, ''9999999.9999''), ''0'')

WHEN INSRNC_CVGE_TYPE_CD = ''SD'' AND FEAT_SBTYPE_CD = ''OPT'' AND FEAT_DESC LIKE ''All Perils%'' AND (FEAT_DTL_CD_NAME LIKE ''%k'' OR FEAT_DTL_CD_NAME NOT LIKE ''%.%'' AND FEAT_DTL_CD_NAME NOT LIKE ''%K'') AND FEAT_DTL_VAL > 0

THEN FEAT_DTL_CD_NAME

END) AS DED

,MAX(CASE WHEN FE.NK_SRC_KEY = ''HOAUTOPAYHISTORY_ALFA'' THEN AF.AGMT_FEAT_AMT END) AS LATE

FROM (SELECT AGMT_ID, FEAT_ID, AGMT_FEAT_AMT, FEAT_EFECT_TYPE_CD

FROM DB_T_PROD_CORE.AGMT_FEAT

WHERE EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

UNION

SELECT  AIAF.AGMT_ID

,FT.FEAT_ID

,CASE

WHEN FT.FEAT_SBTYPE_CD = ''OPT'' THEN FT.FEAT_DTL_VAL

WHEN FT.FEAT_SBTYPE_CD = ''PKG'' THEN FT.FEAT_DTL_VAL

ELSE AIAF.AGMT_ASSET_FEAT_AMT

END AS AMT

,FEAT_EFECT_TYPE_CD

FROM DB_T_PROD_CORE.AGMT_INSRD_ASSET_FEAT AIAF

INNER JOIN DB_T_PROD_CORE.FEAT FT

ON AIAF.FEAT_ID = FT.FEAT_ID

WHERE AIAF.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND FT.EDW_END_DTTM = ''9999-12-31 23:59:59.999999'') AF

LEFT OUTER JOIN DB_T_PROD_CORE.FEAT FE

ON AF.FEAT_ID = FE.FEAT_ID

AND FE.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

GROUP BY AF.AGMT_ID) BB

ON BB.AGMT_ID = AG.AGMT_ID



LEFT OUTER JOIN (SELECT HOST_AGMT_NUM, MAX(CASE WHEN AC.AGMT_ID IS NULL THEN 1 ELSE 0 END) AS CFI

FROM DB_T_PROD_CORE.AGMT AG

LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_CLM AC

ON AC.AGMT_ID = AG.AGMT_ID

AND AC.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

WHERE AGMT_TYPE_CD = ''PPV''

AND AG.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

GROUP BY HOST_AGMT_NUM) CLMF1

ON CLMF1.HOST_AGMT_NUM = AG.HOST_AGMT_NUM



LEFT OUTER JOIN (SELECT PLCY_NBR, CLM_FREE_IND CFI

FROM db_v_prod_pres.V_LGCY_PLCY_INFO

QUALIFY RANK() OVER (PARTITION BY PLCY_NBR ORDER BY MO_ID DESC) = 1) CLMF2

ON CLMF2.PLCY_NBR = AG.HOST_AGMT_NUM



LEFT OUTER JOIN (SELECT  AGMT_ID

,STATE_NM

,CN_NM

,STATE_CD

FROM DB_T_PROD_CORE.PRTY_AGMT   PA

JOIN (SELECT  PRTY_ID

,TE.GEOGRCL_AREA_NAME AS STATE_NM

,CN.GEOGRCL_AREA_NAME AS CN_NM

,TE.GEOGRCL_AREA_NAME AS STATE_CD

FROM (SELECT  PRTY_ID

,PRTY_ADDR_USGE_TYPE_CD UT

,LOC_ID

FROM DB_T_PROD_CORE.PRTY_ADDR

WHERE PRTY_ADDR_USGE_TYPE_CD = ''MAILSTADRS''

/* AND Cast( :lastrundate_plcy  as date) BETWEEN TRANS_STRT_DTTM AND TRANS_END_DTTM */
AND TRANS_STRT_DTTM <= Cast( :lastrundate_plcy  as date)

AND TRANS_END_DTTM > Cast( :lastrundate_plcy  as date)

UNION

SELECT  PRTY_ID

,LOCTR_USGE_TYPE_CD UT

,LOC_ID

FROM DB_T_PROD_CORE.PRTY_LOCTR

WHERE LOCTR_USGE_TYPE_CD = ''MAILSTADRS''

/* AND Cast( :lastrundate_plcy  as date) BETWEEN TRANS_STRT_DTTM AND TRANS_END_DTTM */
AND TRANS_STRT_DTTM <= Cast( :lastrundate_plcy  as date)

AND TRANS_END_DTTM > Cast( :lastrundate_plcy  as date)) PADD3

JOIN DB_T_PROD_CORE.STREET_ADDR SA

ON PADD3.LOC_ID = SA.STREET_ADDR_ID

AND SA.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

LEFT OUTER JOIN DB_T_PROD_CORE.TERR TE

ON SA.TERR_ID = TE.TERR_ID

AND TE.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

LEFT OUTER JOIN DB_T_PROD_CORE.CNTY CN

ON SA.CNTY_ID = CN.CNTY_ID

AND CN.EDW_END_DTTM = ''9999-12-31 23:59:59.999999'') ADDR

ON PA.PRTY_ID = ADDR.PRTY_ID

AND PA.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND PRTY_AGMT_ROLE_CD = ''PLCYPRININS''

GROUP BY AGMT_ID, STATE_NM, CN_NM, STATE_CD) AUTORSK

ON AUTORSK.AGMT_ID = AG.AGMT_ID



LEFT OUTER JOIN (SELECT  AGMT_ID

,STATE_NM

,CN_NM

,STATE_CD

FROM DB_T_PROD_CORE.AGMT_ASSET AGA

JOIN DB_T_PROD_CORE.PRTY_ASSET PA

ON AGA.PRTY_ASSET_ID = PA.PRTY_ASSET_ID

AND (PRTY_ASSET_CLASFCN_CD = ''MAIN'' OR PRTY_ASSET_CLASFCN_CD IN(''FOPOUTBLDG'',''FOPDWELL''))

AND PA.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND AGA.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

LEFT OUTER JOIN (SELECT  PAL.PRTY_ASSET_ID

,TE.GEOGRCL_AREA_NAME AS STATE_NM

,TE.GEOGRCL_AREA_SHRT_NAME AS STATE_CD

FROM DB_T_PROD_CORE.PRTY_ASSET_LOCTR PAL

JOIN DB_T_PROD_CORE.TERR TE

ON PAL.LOC_ID = TE.TERR_ID

AND TE.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND PRTY_ASSET_LOCTR_ROLE_CD = ''RSKST''

/* AND Cast( :lastrundate_plcy  as date) BETWEEN PAL.TRANS_STRT_DTTM AND PAL.TRANS_END_DTTM */
AND TRANS_STRT_DTTM <= Cast( :lastrundate_plcy  as date)

AND TRANS_END_DTTM > Cast( :lastrundate_plcy  as date)) RSKST

ON PA.PRTY_ASSET_ID = RSKST.PRTY_ASSET_ID

LEFT OUTER JOIN (SELECT  PAL.PRTY_ASSET_ID

,CN.GEOGRCL_AREA_NAME AS CN_NM

FROM DB_T_PROD_CORE.PRTY_ASSET_LOCTR PAL

JOIN DB_T_PROD_CORE.CNTY CN

ON PAL.LOC_ID = CN.CNTY_ID

AND CN.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND PRTY_ASSET_LOCTR_ROLE_CD = ''RSKCNTY''

/*  AND Cast( :lastrundate_plcy  as date) BETWEEN PAL.TRANS_STRT_DTTM AND PAL.TRANS_END_DTTM */
AND TRANS_STRT_DTTM <= Cast( :lastrundate_plcy  as date)

AND TRANS_END_DTTM > Cast( :lastrundate_plcy  as date)) RSKCNTY

ON PA.PRTY_ASSET_ID = RSKCNTY.PRTY_ASSET_ID

GROUP BY AGMT_ID, STATE_NM, CN_NM, STATE_CD) PRORSK

ON PRORSK.AGMT_ID = AG.AGMT_ID



LEFT OUTER JOIN (SELECT  AGMT_ID

,MAX(RE.CNSTRCTN_TYPE_CD) AS INFO_VAL_CNST

,MAX(PRTY_ASSET_SPEC_VAL) AS PRT_CLASS

,CAST(MIN(RE.CNSTRCTN_DT) AS VARCHAR(10)) AS INFO_VAL_CNYR

FROM DB_T_PROD_CORE.AGMT_ASSET AST

LEFT OUTER JOIN DB_T_PROD_CORE.REAL_ESTAT RE

ON AST.PRTY_ASSET_ID = RE.PRTY_ASSET_ID

AND RE.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

LEFT OUTER JOIN DB_T_PROD_CORE.PRTY_ASSET_SPEC PAC

ON AST.PRTY_ASSET_ID = PAC.PRTY_ASSET_ID

AND PAC.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND PAC.PRTY_ASSET_SPEC_TYPE_CD = ''PROT''

WHERE AST.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

GROUP BY AGMT_ID) PRTCLS

ON AG.AGMT_ID = PRTCLS.AGMT_ID



LEFT OUTER JOIN (SELECT AGMT_ID, MAX(PNLTY_PNTS_CNT) AS PNLTY_PNTS_CNT

FROM DB_T_PROD_CORE.PRTY_AGMT_ASSET PAA

JOIN DB_T_PROD_CORE.PRTY_DRVG_HIST PDH

ON PAA.PRTY_ID = PDH.INDIV_PRTY_ID

AND PDH.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

GROUP BY AGMT_ID) PDH

ON AG.AGMT_ID = PDH.AGMT_ID



/* updated code starts here */


LEFT OUTER JOIN (SELECT AGMT_ID, MAX(ADCX.ASSET_DTL_CD) AS ASSET_DTL_CD

FROM DB_T_PROD_CORE.AGMT_ASSET AAS

JOIN DB_T_PROD_CORE.ASSET_DTL_CD_XREF ADCX

ON ADCX.PRTY_ASSET_ID = AAS.PRTY_ASSET_ID

AND AAS.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND ADCX.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

JOIN DB_T_PROD_CORE.ASSET_DTL_TYPE AD

ON AD.ASSET_DTL_CD = ADCX.ASSET_DTL_CD

AND Cast( :lastrundate_plcy  as date) BETWEEN AD.EFF_DT AND AD.EXPN_DT

WHERE AD.ASSET_DTL_SCHM_TYPE_CD = ''HMALRT''

GROUP BY AGMT_ID) HM_ALRT

ON HM_ALRT.AGMT_ID = AG.AGMT_ID



LEFT OUTER JOIN  ( SELECT ag.agmt_id AS agmt_id ,

cast( :lastrundate_plcy  as date) AS dt ,

ag.host_agmt_num AS plcy_num,

count(ass1.prty_asset_id ) AS asscnt

FROM            (

SELECT ag.agmt_id,

ag.host_agmt_num,

agmt_sts_cd,

ag.term_num,

ag.modl_num

FROM   (

SELECT *

FROM DB_T_PROD_CORE.AGMT 

WHERE CAST(modl_eff_dttm AS  date) <= cast( :lastrundate_plcy  as date)

AND      CAST(modl_crtn_dttm AS date) <= cast( :lastrundate_plcy  as date)

AND  CAST(agmt_eff_dttm AS       date) <= cast( :lastrundate_plcy  as date)

AND    CAST(agmt_plnd_expn_dttm AS date) > cast( :lastrundate_plcy  as date)

AND      agmt_type_cd = ''PPV''

/* AND VFYD_PLCY_IND =''Y'' */

QUALIFY rank() OVER (PARTITION BY host_agmt_num ORDER BY modl_crtn_dttm DESC) =1

) ag

JOIN

(

SELECT *

FROM   DB_T_PROD_CORE.AGMT

WHERE  CAST(agmt_eff_dttm AS       date) <= cast( :lastrundate_plcy  as date)

AND    CAST(agmt_plnd_expn_dttm AS date) > cast( :lastrundate_plcy  as date)

AND    agmt_type_cd = ''POLTRM'' ) term

ON     term.host_agmt_num = ag.host_agmt_num

AND    term.term_num = ag.term_num

JOIN

(

SELECT   *

FROM     DB_T_PROD_CORE.agmt_sts

WHERE    cast(agmt_sts_strt_dttm as date) <= cast( :lastrundate_plcy  as date)

AND      agmt_sts_cd <> ''CNFRMDDT'' QUALIFY rank() OVER (PARTITION BY agmt_id ORDER BY agmt_sts_strt_dttm DESC) = 1 ) ast

ON     ast.agmt_id = term.agmt_id

AND    ast.agmt_sts_cd = ''INFORCE'' group by 1,2,3,4,5 ) ag

LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_ASSET ass1

ON              ag.agmt_id = ass1.agmt_id

AND CAST(CAST(:lastrundate_plcy AS DATE)+1 AS TIMESTAMP(6))-INTERVAL''0.000001 SECOND'' BETWEEN AGMT_ASSET_STRT_DTTM AND AGMT_ASSET_END_DTTM

AND             ass1.edw_end_dttm=''9999-12-31 23:59:59.999999''

GROUP BY        1,

2 ,

3

) inforce ON inforce.agmt_id =ag.agmt_id AND inforce.dt=cast( :lastrundate_plcy  as date)



LEFT OUTER JOIN (SELECT  AG1.AGMT_ID

,AG1.HOST_AGMT_NUM PLCY_NUM

,MODL_EFF_DTTM

,COUNT(ASS1.PRTY_ASSET_ID) AS ASSCNT

FROM DB_T_PROD_CORE.AGMT AG1

JOIN (SELECT  EVV1.EV_ID

,EVV1.EV_ACTVY_TYPE_CD

,EVV1.EV_SBTYPE_CD

,ES.AGMT_ID

,ES.TRANS_STRT_DTTM AS TRANS_STRT_DTTM

,ES.TRANS_END_DTTM AS TRANS_END_DTTM

FROM DB_T_PROD_CORE.EV EVV1

JOIN DB_T_PROD_CORE.EV_STS ES

ON EVV1.EV_ID = ES.EV_ID

AND ES.EV_STS_TYPE_CD = ''BOUND''

AND ES.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND EVV1.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND EVV1.EV_SBTYPE_CD = ''PLCYTRNS''

AND EV_ACTVY_TYPE_CD = ''SBMSSN'') EVV

ON AG1.AGMT_ID = EVV.AGMT_ID

AND AG1.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

AND AG1.TERM_NUM = 1

AND AGMT_TYPE_CD = ''PPV''

AND Cast( :lastrundate_plcy  as date) BETWEEN EVV.TRANS_STRT_DTTM AND EVV.TRANS_END_DTTM

LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_ASSET ASS1

ON AG1.AGMT_ID = ASS1.AGMT_ID

AND ASS1.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

WHERE

case when cast(MODL_CRTN_DTTM as date) < cast(MODL_eff_DTTM as date)

then extract(year from MODL_eff_DTTM)*100+extract(month from MODL_eff_DTTM)

else extract(year from MODL_CRTN_DTTM)*100+extract(month from MODL_CRTN_DTTM) end

=  EXTRACT(year FROM cast( :lastrundate_plcy as date)  ) *100+ EXTRACT(MONTH FROM cast( :lastrundate_plcy as date)  )

GROUP BY AG1.AGMT_ID, AG1.HOST_AGMT_NUM, MODL_EFF_DTTM

) NEWPOL

ON NEWPOL.AGMT_ID = AG.AGMT_ID

/* AND EXTRACT(MONTH FROM CALENDAR_DATE) = EXTRACT(MONTH FROM NEWPOL.MODL_EFF_DTTM) */
/* AND EXTRACT(YEAR FROM CALENDAR_DATE) = EXTRACT(YEAR FROM NEWPOL.MODL_EFF_DTTM) */


WHERE AG.AGMT_TYPE_CD = ''PPV''

AND AG.EDW_END_DTTM = ''9999-12-31 23:59:59.999999''

GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,37,38



UNION ALL



SELECT  CAL_MO_ID

,CALENDAR_DATE

,LOB_CD

,CMPY_CD

,SALES_ST_CD

,RGN_CD

,DIST_CD

,SALES_CNTY_NAME

,RISK_CNTY_NAME

,SVC_CD

,AGENT_NBR

,PRIOR_INS_CARRIER_CD

,GENDER_CD

,MARITAL_STATUS_CD

,OCC_CD

,CAST(DRV_POINTS AS VARCHAR(11))

,AGE

,INS_SCR_CD

,LEVEL_NBR

,DW_COV_TYPE_CD

,PP_COV_TYPE_CD

,INFO_VAL_DED

,INFO_VAL_FORM

,INFO_VAL_CNST

,INFO_VAL_CNYR

,INFO_VAL_PROT

,YRS_WITH_ALFA

,AUTO_DISC

,DSC_VAL_NWHM

,INFO_VAL_CLFR

,DSC_VAL_VCLP

,DSC_VAL_HAPC

,IINFO_VAL_ALRT

,PLCY_CNT_WRIT_IFO

,PLCY_CNT_NEW_BUSI

,TOTAL_VEH_IFO

,RISK_ST_CD

,''NA'' AS PRD_RLP

FROM db_v_prod_pres.V_LGCY_PLCY_INFO_DTL_CD

WHERE CAL_MO_ID = (EXTRACT(MONTH FROM TO_DATE(:lastrundate_plcy, ''YYYY-MM-DD'')) + (12*(EXTRACT(YEAR FROM TO_DATE(:lastrundate_plcy, ''YYYY-MM-DD''))-1900)))
) SRC
)
);


-- Component EXP_SQ, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXP_SQ AS
(
SELECT
SQ_AGMT.CAL_MO_ID as CAL_MO_ID,
SQ_AGMT.CALENDAR_DATE as CALENDAR_DATE,
SQ_AGMT.LOB_CD as LOB_CD,
NULL as LOB_DESC,
SQ_AGMT.CMPY_CD as CMPY_CD,
SQ_AGMT.ST_CD as ST_CD,
SQ_AGMT.RGN_CD as RGN_CD,
SQ_AGMT.DIST_CD as DIST_CD,
SQ_AGMT.SALES_CNTY_CD as SALES_CNTY_CD,
SQ_AGMT.RSK_CNTY_CD as RSK_CNTY_CD,
SQ_AGMT.SVC_CD as SVC_CD,
SQ_AGMT.AGENT_NBR as AGENT_NBR,
NULL as AGENT_DESC,
SQ_AGMT.PRIOR_INS_CARRIER_CD as PRIOR_INS_CARRIER_CD,
SQ_AGMT.GENDER_CD as GENDER_CD,
SQ_AGMT.MARITAL_STATUS_CD as MARITAL_STATUS_CD,
SQ_AGMT.OCP_CD as OCP_CD,
SQ_AGMT.DRV_POINTS as DRV_POINTS,
SQ_AGMT.AGE as AGE,
SQ_AGMT.INS_SCR_CD as INS_SCR_CD,
SQ_AGMT.LEVEL_NBR as LEVEL_NBR,
SQ_AGMT.DW_COV_TYPE_CD as DW_COV_TYPE_CD,
SQ_AGMT.PP_COV_TYPE_CD as PP_COV_TYPE_CD,
SQ_AGMT.INFO_VAL_DED as INFO_VAL_DED,
SQ_AGMT.INFO_VAL_FORM as INFO_VAL_FORM,
SQ_AGMT.INFO_VAL_CNST as INFO_VAL_CNST,
SQ_AGMT.INFO_VAL_CNYR as INFO_VAL_CNYR,
SQ_AGMT.INFO_VAL_PROT as INFO_VAL_PROT,
SQ_AGMT.YRS_WITH_ALFA as YRS_WITH_ALFA,
SQ_AGMT.AUTO_DISC as AUTO_DISC,
SQ_AGMT.DSC_VAL_NWHM as DSC_VAL_NWHM,
SQ_AGMT.INFO_VAL_CLFR as INFO_VAL_CLFR,
SQ_AGMT.DSC_VAL_VCLP as DSC_VAL_VCLP,
SQ_AGMT.DSC_VAL_HAPC as DSC_VAL_HAPC,
SQ_AGMT.INFO_VAL_ALRT as INFO_VAL_ALRT,
SQ_AGMT.PLCY_CNT_WRIT_IFO as PLCY_CNT_WRIT_IFO,
SQ_AGMT.PLCY_CNT_NEW_BUS as PLCY_CNT_NEW_BUS,
NULL as NEW_VEH_INS,
SQ_AGMT.TOTAL_VEH_IFO as TOTAL_VEH_IFO,
SQ_AGMT.RISK_ST_CD as RISK_ST_CD,
SQ_AGMT.source_record_id
FROM
SQ_AGMT
);


-- Component LKP_PLCY_INFO_DTL, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_PLCY_INFO_DTL AS
(
SELECT
EXP_SQ.CAL_MO_ID, -- LKP.CAL_MO_ID - CHANGED TO AVOID NULL VALUES
EXP_SQ.source_record_id,
ROW_NUMBER() OVER(PARTITION BY EXP_SQ.source_record_id ORDER BY LKP.CAL_MO_ID asc) RNK
FROM
EXP_SQ
LEFT JOIN (
SELECT
CAL_MO_ID
FROM db_v_prod_pres.WR_PLCY_INFO_DTL_CD
) LKP ON LKP.CAL_MO_ID = EXP_SQ.CAL_MO_ID
QUALIFY RNK = 1
);


-- Component RTR_PLCY_INFO_DTL_INSERT, Type ROUTER Output Group INSERT
create or replace temporary table RTR_PLCY_INFO_DTL_INSERT AS
SELECT
LKP_PLCY_INFO_DTL.CAL_MO_ID as CAL_MO_ID,
EXP_SQ.CAL_MO_ID as CAL_MO_ID1,
EXP_SQ.CALENDAR_DATE as CALENDAR_DATE,
EXP_SQ.LOB_CD as LOB_CD,
EXP_SQ.LOB_DESC as LOB_DESC,
EXP_SQ.CMPY_CD as CMPY_CD,
EXP_SQ.ST_CD as ST_CD,
EXP_SQ.RGN_CD as RGN_CD,
EXP_SQ.DIST_CD as DIST_CD,
EXP_SQ.SALES_CNTY_CD as SALES_CNTY_CD,
EXP_SQ.RSK_CNTY_CD as RSK_CNTY_CD,
EXP_SQ.SVC_CD as SVC_CD,
EXP_SQ.AGENT_NBR as AGENT_NBR,
EXP_SQ.AGENT_DESC as AGENT_DESC,
EXP_SQ.PRIOR_INS_CARRIER_CD as PRIOR_INS_CARRIER_CD,
EXP_SQ.GENDER_CD as GENDER_CD,
EXP_SQ.MARITAL_STATUS_CD as MARITAL_STATUS_CD,
EXP_SQ.OCP_CD as OCP_CD,
EXP_SQ.DRV_POINTS as DRV_POINTS,
EXP_SQ.AGE as AGE,
EXP_SQ.INS_SCR_CD as INS_SCR_CD,
EXP_SQ.LEVEL_NBR as LEVEL_NBR,
EXP_SQ.DW_COV_TYPE_CD as DW_COV_TYPE_CD,
EXP_SQ.PP_COV_TYPE_CD as PP_COV_TYPE_CD,
EXP_SQ.INFO_VAL_DED as INFO_VAL_DED,
EXP_SQ.INFO_VAL_FORM as INFO_VAL_FORM,
EXP_SQ.INFO_VAL_CNST as INFO_VAL_CNST,
EXP_SQ.INFO_VAL_CNYR as INFO_VAL_CNYR,
EXP_SQ.INFO_VAL_PROT as INFO_VAL_PROT,
EXP_SQ.YRS_WITH_ALFA as YRS_WITH_ALFA,
EXP_SQ.AUTO_DISC as AUTO_DISC,
EXP_SQ.DSC_VAL_NWHM as DSC_VAL_NWHM,
EXP_SQ.INFO_VAL_CLFR as INFO_VAL_CLFR,
EXP_SQ.DSC_VAL_VCLP as DSC_VAL_VCLP,
EXP_SQ.DSC_VAL_HAPC as DSC_VAL_HAPC,
EXP_SQ.INFO_VAL_ALRT as INFO_VAL_ALRT,
EXP_SQ.PLCY_CNT_WRIT_IFO as PLCY_CNT_WRIT_IFO,
EXP_SQ.PLCY_CNT_NEW_BUS as PLCY_CNT_NEW_BUS,
EXP_SQ.NEW_VEH_INS as NEW_VEH_INS,
EXP_SQ.TOTAL_VEH_IFO as TOTAL_VEH_IFO,
EXP_SQ.RISK_ST_CD as RISK_ST_CD,
EXP_SQ.source_record_id
FROM
EXP_SQ
LEFT JOIN LKP_PLCY_INFO_DTL ON EXP_SQ.source_record_id = LKP_PLCY_INFO_DTL.source_record_id
WHERE LKP_PLCY_INFO_DTL.CAL_MO_ID IS NULL;


-- Component RTR_PLCY_INFO_DTL_UPDATE, Type ROUTER Output Group UPDATE
create or replace temporary table RTR_PLCY_INFO_DTL_UPDATE AS
SELECT
LKP_PLCY_INFO_DTL.CAL_MO_ID as CAL_MO_ID,
EXP_SQ.CAL_MO_ID as CAL_MO_ID1,
EXP_SQ.CALENDAR_DATE as CALENDAR_DATE,
EXP_SQ.LOB_CD as LOB_CD,
EXP_SQ.LOB_DESC as LOB_DESC,
EXP_SQ.CMPY_CD as CMPY_CD,
EXP_SQ.ST_CD as ST_CD,
EXP_SQ.RGN_CD as RGN_CD,
EXP_SQ.DIST_CD as DIST_CD,
EXP_SQ.SALES_CNTY_CD as SALES_CNTY_CD,
EXP_SQ.RSK_CNTY_CD as RSK_CNTY_CD,
EXP_SQ.SVC_CD as SVC_CD,
EXP_SQ.AGENT_NBR as AGENT_NBR,
EXP_SQ.AGENT_DESC as AGENT_DESC,
EXP_SQ.PRIOR_INS_CARRIER_CD as PRIOR_INS_CARRIER_CD,
EXP_SQ.GENDER_CD as GENDER_CD,
EXP_SQ.MARITAL_STATUS_CD as MARITAL_STATUS_CD,
EXP_SQ.OCP_CD as OCP_CD,
EXP_SQ.DRV_POINTS as DRV_POINTS,
EXP_SQ.AGE as AGE,
EXP_SQ.INS_SCR_CD as INS_SCR_CD,
EXP_SQ.LEVEL_NBR as LEVEL_NBR,
EXP_SQ.DW_COV_TYPE_CD as DW_COV_TYPE_CD,
EXP_SQ.PP_COV_TYPE_CD as PP_COV_TYPE_CD,
EXP_SQ.INFO_VAL_DED as INFO_VAL_DED,
EXP_SQ.INFO_VAL_FORM as INFO_VAL_FORM,
EXP_SQ.INFO_VAL_CNST as INFO_VAL_CNST,
EXP_SQ.INFO_VAL_CNYR as INFO_VAL_CNYR,
EXP_SQ.INFO_VAL_PROT as INFO_VAL_PROT,
EXP_SQ.YRS_WITH_ALFA as YRS_WITH_ALFA,
EXP_SQ.AUTO_DISC as AUTO_DISC,
EXP_SQ.DSC_VAL_NWHM as DSC_VAL_NWHM,
EXP_SQ.INFO_VAL_CLFR as INFO_VAL_CLFR,
EXP_SQ.DSC_VAL_VCLP as DSC_VAL_VCLP,
EXP_SQ.DSC_VAL_HAPC as DSC_VAL_HAPC,
EXP_SQ.INFO_VAL_ALRT as INFO_VAL_ALRT,
EXP_SQ.PLCY_CNT_WRIT_IFO as PLCY_CNT_WRIT_IFO,
EXP_SQ.PLCY_CNT_NEW_BUS as PLCY_CNT_NEW_BUS,
EXP_SQ.NEW_VEH_INS as NEW_VEH_INS,
EXP_SQ.TOTAL_VEH_IFO as TOTAL_VEH_IFO,
EXP_SQ.RISK_ST_CD as RISK_ST_CD,
EXP_SQ.source_record_id
FROM
EXP_SQ
LEFT JOIN LKP_PLCY_INFO_DTL ON EXP_SQ.source_record_id = LKP_PLCY_INFO_DTL.source_record_id
WHERE LKP_PLCY_INFO_DTL.CAL_MO_ID IS NOT NULL;


-- Component UPD_PLCY_INFO_DTL_INSERT, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE UPD_PLCY_INFO_DTL_INSERT AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
RTR_PLCY_INFO_DTL_INSERT.CAL_MO_ID1 as CAL_MO_ID2,
RTR_PLCY_INFO_DTL_INSERT.CALENDAR_DATE as CALENDAR_DATE1,
RTR_PLCY_INFO_DTL_INSERT.LOB_CD as LOB_CD1,
RTR_PLCY_INFO_DTL_INSERT.LOB_DESC as LOB_DESC1,
RTR_PLCY_INFO_DTL_INSERT.CMPY_CD as CMPY_CD1,
RTR_PLCY_INFO_DTL_INSERT.ST_CD as ST_CD1,
RTR_PLCY_INFO_DTL_INSERT.RGN_CD as RGN_CD1,
RTR_PLCY_INFO_DTL_INSERT.DIST_CD as DIST_CD1,
RTR_PLCY_INFO_DTL_INSERT.SALES_CNTY_CD as SALES_CNTY_CD1,
RTR_PLCY_INFO_DTL_INSERT.RSK_CNTY_CD as RSK_CNTY_CD1,
RTR_PLCY_INFO_DTL_INSERT.SVC_CD as SVC_CD1,
RTR_PLCY_INFO_DTL_INSERT.AGENT_NBR as AGENT_NBR1,
RTR_PLCY_INFO_DTL_INSERT.AGENT_DESC as AGENT_DESC1,
RTR_PLCY_INFO_DTL_INSERT.PRIOR_INS_CARRIER_CD as PRIOR_INS_CARRIER_CD1,
RTR_PLCY_INFO_DTL_INSERT.GENDER_CD as GENDER_CD1,
RTR_PLCY_INFO_DTL_INSERT.MARITAL_STATUS_CD as MARITAL_STATUS_CD1,
RTR_PLCY_INFO_DTL_INSERT.OCP_CD as OCP_CD1,
RTR_PLCY_INFO_DTL_INSERT.DRV_POINTS as DRV_POINTS1,
RTR_PLCY_INFO_DTL_INSERT.AGE as AGE1,
RTR_PLCY_INFO_DTL_INSERT.INS_SCR_CD as INS_SCR_CD1,
RTR_PLCY_INFO_DTL_INSERT.LEVEL_NBR as LEVEL_NBR1,
RTR_PLCY_INFO_DTL_INSERT.DW_COV_TYPE_CD as DW_COV_TYPE_CD1,
RTR_PLCY_INFO_DTL_INSERT.PP_COV_TYPE_CD as PP_COV_TYPE_CD1,
RTR_PLCY_INFO_DTL_INSERT.INFO_VAL_DED as INFO_VAL_DED1,
RTR_PLCY_INFO_DTL_INSERT.INFO_VAL_FORM as INFO_VAL_FORM1,
RTR_PLCY_INFO_DTL_INSERT.INFO_VAL_CNST as INFO_VAL_CNST1,
RTR_PLCY_INFO_DTL_INSERT.INFO_VAL_CNYR as INFO_VAL_CNYR1,
RTR_PLCY_INFO_DTL_INSERT.INFO_VAL_PROT as INFO_VAL_PROT1,
RTR_PLCY_INFO_DTL_INSERT.YRS_WITH_ALFA as YRS_WITH_ALFA1,
RTR_PLCY_INFO_DTL_INSERT.AUTO_DISC as AUTO_DISC1,
RTR_PLCY_INFO_DTL_INSERT.DSC_VAL_NWHM as DSC_VAL_NWHM1,
RTR_PLCY_INFO_DTL_INSERT.INFO_VAL_CLFR as INFO_VAL_CLFR1,
RTR_PLCY_INFO_DTL_INSERT.DSC_VAL_VCLP as DSC_VAL_VCLP1,
RTR_PLCY_INFO_DTL_INSERT.DSC_VAL_HAPC as DSC_VAL_HAPC1,
RTR_PLCY_INFO_DTL_INSERT.INFO_VAL_ALRT as INFO_VAL_ALRT1,
RTR_PLCY_INFO_DTL_INSERT.PLCY_CNT_WRIT_IFO as PLCY_CNT_WRIT_IFO1,
RTR_PLCY_INFO_DTL_INSERT.PLCY_CNT_NEW_BUS as PLCY_CNT_NEW_BUS1,
RTR_PLCY_INFO_DTL_INSERT.NEW_VEH_INS as NEW_VEH_INS1,
RTR_PLCY_INFO_DTL_INSERT.TOTAL_VEH_IFO as TOTAL_VEH_IFO1,
RTR_PLCY_INFO_DTL_INSERT.RISK_ST_CD as RISK_ST_CD1,
0 as UPDATE_STRATEGY_ACTION,
RTR_PLCY_INFO_DTL_INSERT.source_record_id
FROM
RTR_PLCY_INFO_DTL_INSERT
);


-- Component UPD_PLCY_INFO_DTL_UPDATE, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE UPD_PLCY_INFO_DTL_UPDATE AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
RTR_PLCY_INFO_DTL_UPDATE.CAL_MO_ID1 as CAL_MO_ID13,
RTR_PLCY_INFO_DTL_UPDATE.CALENDAR_DATE as CALENDAR_DATE3,
RTR_PLCY_INFO_DTL_UPDATE.LOB_CD as LOB_CD3,
RTR_PLCY_INFO_DTL_UPDATE.LOB_DESC as LOB_DESC3,
RTR_PLCY_INFO_DTL_UPDATE.CMPY_CD as CMPY_CD3,
RTR_PLCY_INFO_DTL_UPDATE.ST_CD as ST_CD3,
RTR_PLCY_INFO_DTL_UPDATE.RGN_CD as RGN_CD3,
RTR_PLCY_INFO_DTL_UPDATE.DIST_CD as DIST_CD3,
RTR_PLCY_INFO_DTL_UPDATE.SALES_CNTY_CD as SALES_CNTY_CD3,
RTR_PLCY_INFO_DTL_UPDATE.RSK_CNTY_CD as RSK_CNTY_CD3,
RTR_PLCY_INFO_DTL_UPDATE.SVC_CD as SVC_CD3,
RTR_PLCY_INFO_DTL_UPDATE.AGENT_NBR as AGENT_NBR3,
RTR_PLCY_INFO_DTL_UPDATE.AGENT_DESC as AGENT_DESC3,
RTR_PLCY_INFO_DTL_UPDATE.PRIOR_INS_CARRIER_CD as PRIOR_INS_CARRIER_CD3,
RTR_PLCY_INFO_DTL_UPDATE.GENDER_CD as GENDER_CD3,
RTR_PLCY_INFO_DTL_UPDATE.MARITAL_STATUS_CD as MARITAL_STATUS_CD3,
RTR_PLCY_INFO_DTL_UPDATE.OCP_CD as OCP_CD3,
RTR_PLCY_INFO_DTL_UPDATE.DRV_POINTS as DRV_POINTS3,
RTR_PLCY_INFO_DTL_UPDATE.AGE as AGE3,
RTR_PLCY_INFO_DTL_UPDATE.INS_SCR_CD as INS_SCR_CD3,
RTR_PLCY_INFO_DTL_UPDATE.LEVEL_NBR as LEVEL_NBR3,
RTR_PLCY_INFO_DTL_UPDATE.DW_COV_TYPE_CD as DW_COV_TYPE_CD3,
RTR_PLCY_INFO_DTL_UPDATE.PP_COV_TYPE_CD as PP_COV_TYPE_CD3,
RTR_PLCY_INFO_DTL_UPDATE.INFO_VAL_DED as INFO_VAL_DED3,
RTR_PLCY_INFO_DTL_UPDATE.INFO_VAL_FORM as INFO_VAL_FORM3,
RTR_PLCY_INFO_DTL_UPDATE.INFO_VAL_CNST as INFO_VAL_CNST3,
RTR_PLCY_INFO_DTL_UPDATE.INFO_VAL_CNYR as INFO_VAL_CNYR3,
RTR_PLCY_INFO_DTL_UPDATE.INFO_VAL_PROT as INFO_VAL_PROT3,
RTR_PLCY_INFO_DTL_UPDATE.YRS_WITH_ALFA as YRS_WITH_ALFA3,
RTR_PLCY_INFO_DTL_UPDATE.AUTO_DISC as AUTO_DISC3,
RTR_PLCY_INFO_DTL_UPDATE.DSC_VAL_NWHM as DSC_VAL_NWHM3,
RTR_PLCY_INFO_DTL_UPDATE.INFO_VAL_CLFR as INFO_VAL_CLFR3,
RTR_PLCY_INFO_DTL_UPDATE.DSC_VAL_VCLP as DSC_VAL_VCLP3,
RTR_PLCY_INFO_DTL_UPDATE.DSC_VAL_HAPC as DSC_VAL_HAPC3,
RTR_PLCY_INFO_DTL_UPDATE.INFO_VAL_ALRT as INFO_VAL_ALRT3,
RTR_PLCY_INFO_DTL_UPDATE.PLCY_CNT_WRIT_IFO as PLCY_CNT_WRIT_IFO3,
RTR_PLCY_INFO_DTL_UPDATE.PLCY_CNT_NEW_BUS as PLCY_CNT_NEW_BUS3,
RTR_PLCY_INFO_DTL_UPDATE.NEW_VEH_INS as NEW_VEH_INS3,
RTR_PLCY_INFO_DTL_UPDATE.TOTAL_VEH_IFO as TOTAL_VEH_IFO3,
RTR_PLCY_INFO_DTL_UPDATE.RISK_ST_CD as RISK_ST_CD3,
1 as UPDATE_STRATEGY_ACTION,
RTR_PLCY_INFO_DTL_UPDATE.source_record_id
FROM
RTR_PLCY_INFO_DTL_UPDATE
);


-- Component WR_PLCY_INFO_DTL_CD_INS, Type TARGET 
INSERT INTO DB_V_PROD_PRES.WR_PLCY_INFO_DTL_CD
(
CAL_MO_ID,
CALENDAR_DATE,
LOB_CD,
CMPY_CD,
SALES_ST_CD,
RGN_CD,
DIST_CD,
SALES_CNTY_CD,
RSK_CNTY_CD,
SVC_CD,
AGENT_NBR,
PRIOR_INS_CARRIER_CD,
GENDER_CD,
MARITAL_STATUS_CD,
OCP_CD,
DRV_POINTS,
AGE,
INS_SCR_CD,
LEVEL_NBR,
DW_COV_TYPE_CD,
PP_COV_TYPE_CD,
INFO_VAL_DED,
INFO_VAL_FORM,
INFO_VAL_CNST,
INFO_VAL_CNYR,
INFO_VAL_PROT,
YRS_WITH_ALFA,
AUTO_DISC,
DSC_VAL_NWHM,
INFO_VAL_CLFR,
DSC_VAL_VCLP,
DSC_VAL_HAPC,
INFO_VAL_ALRT,
PLCY_CNT_WRIT_IFO,
PLCY_CNT_NEW_BUSI,
NEW_VEH_INS,
TOTAL_VEH_IFO,
RISK_ST_CD
)
SELECT
UPD_PLCY_INFO_DTL_INSERT.CAL_MO_ID2 as CAL_MO_ID,
UPD_PLCY_INFO_DTL_INSERT.CALENDAR_DATE1 as CALENDAR_DATE,
UPD_PLCY_INFO_DTL_INSERT.LOB_CD1 as LOB_CD,
UPD_PLCY_INFO_DTL_INSERT.CMPY_CD1 as CMPY_CD,
UPD_PLCY_INFO_DTL_INSERT.ST_CD1 as SALES_ST_CD,
UPD_PLCY_INFO_DTL_INSERT.RGN_CD1 as RGN_CD,
UPD_PLCY_INFO_DTL_INSERT.DIST_CD1 as DIST_CD,
left(UPD_PLCY_INFO_DTL_INSERT.SALES_CNTY_CD1,10) as SALES_CNTY_CD,
left(UPD_PLCY_INFO_DTL_INSERT.RSK_CNTY_CD1,10) as RSK_CNTY_CD,
UPD_PLCY_INFO_DTL_INSERT.SVC_CD1 as SVC_CD,
UPD_PLCY_INFO_DTL_INSERT.AGENT_NBR1 as AGENT_NBR,
UPD_PLCY_INFO_DTL_INSERT.PRIOR_INS_CARRIER_CD1 as PRIOR_INS_CARRIER_CD,
UPD_PLCY_INFO_DTL_INSERT.GENDER_CD1 as GENDER_CD,
UPD_PLCY_INFO_DTL_INSERT.MARITAL_STATUS_CD1 as MARITAL_STATUS_CD,
left(UPD_PLCY_INFO_DTL_INSERT.OCP_CD1,10) as OCP_CD,
UPD_PLCY_INFO_DTL_INSERT.DRV_POINTS1 as DRV_POINTS,
UPD_PLCY_INFO_DTL_INSERT.AGE1 as AGE,
left(UPD_PLCY_INFO_DTL_INSERT.INS_SCR_CD1,10) as INS_SCR_CD,
UPD_PLCY_INFO_DTL_INSERT.LEVEL_NBR1 as LEVEL_NBR,
UPD_PLCY_INFO_DTL_INSERT.DW_COV_TYPE_CD1 as DW_COV_TYPE_CD,
UPD_PLCY_INFO_DTL_INSERT.PP_COV_TYPE_CD1 as PP_COV_TYPE_CD,
left(UPD_PLCY_INFO_DTL_INSERT.INFO_VAL_DED1,10) as INFO_VAL_DED,
UPD_PLCY_INFO_DTL_INSERT.INFO_VAL_FORM1 as INFO_VAL_FORM,
left(UPD_PLCY_INFO_DTL_INSERT.INFO_VAL_CNST1,10) as INFO_VAL_CNST,
UPD_PLCY_INFO_DTL_INSERT.INFO_VAL_CNYR1 as INFO_VAL_CNYR,
UPD_PLCY_INFO_DTL_INSERT.INFO_VAL_PROT1 as INFO_VAL_PROT,
left(UPD_PLCY_INFO_DTL_INSERT.YRS_WITH_ALFA1,10) as YRS_WITH_ALFA,
UPD_PLCY_INFO_DTL_INSERT.AUTO_DISC1 as AUTO_DISC,
UPD_PLCY_INFO_DTL_INSERT.DSC_VAL_NWHM1 as DSC_VAL_NWHM,
left(UPD_PLCY_INFO_DTL_INSERT.INFO_VAL_CLFR1,10) as INFO_VAL_CLFR,
UPD_PLCY_INFO_DTL_INSERT.DSC_VAL_VCLP1 as DSC_VAL_VCLP,
UPD_PLCY_INFO_DTL_INSERT.DSC_VAL_HAPC1 as DSC_VAL_HAPC,
UPD_PLCY_INFO_DTL_INSERT.INFO_VAL_ALRT1 as INFO_VAL_ALRT,
UPD_PLCY_INFO_DTL_INSERT.PLCY_CNT_WRIT_IFO1 as PLCY_CNT_WRIT_IFO,
UPD_PLCY_INFO_DTL_INSERT.PLCY_CNT_NEW_BUS1 as PLCY_CNT_NEW_BUSI,
UPD_PLCY_INFO_DTL_INSERT.NEW_VEH_INS1 as NEW_VEH_INS,
UPD_PLCY_INFO_DTL_INSERT.TOTAL_VEH_IFO1 as TOTAL_VEH_IFO,
UPD_PLCY_INFO_DTL_INSERT.RISK_ST_CD1 as RISK_ST_CD
FROM
UPD_PLCY_INFO_DTL_INSERT;


-- Component WR_PLCY_INFO_DTL_CD_UPD, Type TARGET 
/* Perform Updates */
MERGE INTO DB_V_PROD_PRES.WR_PLCY_INFO_DTL_CD
USING UPD_PLCY_INFO_DTL_UPDATE ON (UPDATE_STRATEGY_ACTION = 1 AND WR_PLCY_INFO_DTL_CD.CAL_MO_ID = UPD_PLCY_INFO_DTL_UPDATE.CAL_MO_ID13 AND WR_PLCY_INFO_DTL_CD.LOB_CD = UPD_PLCY_INFO_DTL_UPDATE.LOB_CD3 AND WR_PLCY_INFO_DTL_CD.CMPY_CD = UPD_PLCY_INFO_DTL_UPDATE.CMPY_CD3 AND WR_PLCY_INFO_DTL_CD.SALES_ST_CD = UPD_PLCY_INFO_DTL_UPDATE.ST_CD3 AND WR_PLCY_INFO_DTL_CD.RGN_CD = UPD_PLCY_INFO_DTL_UPDATE.RGN_CD3 AND WR_PLCY_INFO_DTL_CD.DIST_CD = UPD_PLCY_INFO_DTL_UPDATE.DIST_CD3 AND WR_PLCY_INFO_DTL_CD.SALES_CNTY_CD = UPD_PLCY_INFO_DTL_UPDATE.SALES_CNTY_CD3 AND WR_PLCY_INFO_DTL_CD.RSK_CNTY_CD = UPD_PLCY_INFO_DTL_UPDATE.RSK_CNTY_CD3 AND WR_PLCY_INFO_DTL_CD.SVC_CD = UPD_PLCY_INFO_DTL_UPDATE.SVC_CD3 AND WR_PLCY_INFO_DTL_CD.AGENT_NBR = UPD_PLCY_INFO_DTL_UPDATE.AGENT_NBR3 AND WR_PLCY_INFO_DTL_CD.PRIOR_INS_CARRIER_CD = UPD_PLCY_INFO_DTL_UPDATE.PRIOR_INS_CARRIER_CD3 AND WR_PLCY_INFO_DTL_CD.GENDER_CD = UPD_PLCY_INFO_DTL_UPDATE.GENDER_CD3 AND WR_PLCY_INFO_DTL_CD.MARITAL_STATUS_CD = UPD_PLCY_INFO_DTL_UPDATE.MARITAL_STATUS_CD3 AND WR_PLCY_INFO_DTL_CD.OCP_CD = UPD_PLCY_INFO_DTL_UPDATE.OCP_CD3 AND WR_PLCY_INFO_DTL_CD.INS_SCR_CD = UPD_PLCY_INFO_DTL_UPDATE.INS_SCR_CD3)
WHEN MATCHED THEN UPDATE
SET
CALENDAR_DATE = UPD_PLCY_INFO_DTL_UPDATE.CALENDAR_DATE3,
DRV_POINTS = UPD_PLCY_INFO_DTL_UPDATE.DRV_POINTS3,
AGE = UPD_PLCY_INFO_DTL_UPDATE.AGE3,
LEVEL_NBR = UPD_PLCY_INFO_DTL_UPDATE.LEVEL_NBR3,
DW_COV_TYPE_CD = UPD_PLCY_INFO_DTL_UPDATE.DW_COV_TYPE_CD3,
PP_COV_TYPE_CD = UPD_PLCY_INFO_DTL_UPDATE.PP_COV_TYPE_CD3,
INFO_VAL_DED = UPD_PLCY_INFO_DTL_UPDATE.INFO_VAL_DED3,
INFO_VAL_FORM = UPD_PLCY_INFO_DTL_UPDATE.INFO_VAL_FORM3,
INFO_VAL_CNST = UPD_PLCY_INFO_DTL_UPDATE.INFO_VAL_CNST3,
INFO_VAL_CNYR = UPD_PLCY_INFO_DTL_UPDATE.INFO_VAL_CNYR3,
INFO_VAL_PROT = UPD_PLCY_INFO_DTL_UPDATE.INFO_VAL_PROT3,
YRS_WITH_ALFA = UPD_PLCY_INFO_DTL_UPDATE.YRS_WITH_ALFA3,
AUTO_DISC = UPD_PLCY_INFO_DTL_UPDATE.AUTO_DISC3,
DSC_VAL_NWHM = UPD_PLCY_INFO_DTL_UPDATE.DSC_VAL_NWHM3,
INFO_VAL_CLFR = UPD_PLCY_INFO_DTL_UPDATE.INFO_VAL_CLFR3,
DSC_VAL_VCLP = UPD_PLCY_INFO_DTL_UPDATE.DSC_VAL_VCLP3,
DSC_VAL_HAPC = UPD_PLCY_INFO_DTL_UPDATE.DSC_VAL_HAPC3,
INFO_VAL_ALRT = UPD_PLCY_INFO_DTL_UPDATE.INFO_VAL_ALRT3,
PLCY_CNT_WRIT_IFO = UPD_PLCY_INFO_DTL_UPDATE.PLCY_CNT_WRIT_IFO3,
PLCY_CNT_NEW_BUSI = UPD_PLCY_INFO_DTL_UPDATE.PLCY_CNT_NEW_BUS3,
NEW_VEH_INS = UPD_PLCY_INFO_DTL_UPDATE.NEW_VEH_INS3,
TOTAL_VEH_IFO = UPD_PLCY_INFO_DTL_UPDATE.TOTAL_VEH_IFO3,
RISK_ST_CD = UPD_PLCY_INFO_DTL_UPDATE.RISK_ST_CD3
;


END; ';