-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_AGG_ENTERPRISE_METRICS_MTHLY("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE WF_MONTH_ID integer;
BEGIN 

set WF_MONTH_ID:=204112; 

-- PIPELINE START FOR 1



-- Component SQ_AGG_ENTERPRISE_METRICS_MTHLY, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_ENTERPRISE_METRICS_MTHLY AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as GROUP_CD,
$2 as LOB_TYPE,
$3 as IND_TYPE,
$4 as MO_ID,
$5 as SALES_ST_CD,
$6 as MTD_CNT,
$7 as YTD_CNT,
$8 as BACKFILL_IND,
$9 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
/* SQ  */
/* CUST_ADDRESS DETAILS */
WITH CA1 AS (
SELECT DISTINCT MO_ID,MEMBER_TYPE,
MEMBER_NUMBER,ST_CD FROM (
SELECT MO_ID,
(CASE WHEN SUBSTR(LIFE.LF_MEMBERSHIP,1,1) =''C'' THEN ''CST'' ELSE ''MBR'' END) AS MEMBER_TYPE,
CAST (ZEROIFNULL(SUBSTR(LIFE.LF_MEMBERSHIP,2,7) )AS INTEGER) AS MEMBER_NUMBER,
AH.SALES_ST_CD ST_CD,CHG_EFF_DT,
LF_ISSUE_DATE,
LF_APPL_DATE,
SC_POLICY_NUM 
FROM DB_T_CORE_MEMBXREF_PROD.LIFEPOLS LIFE
LEFT OUTER JOIN DB_T_CORE_PROD.AGENT_HIER AH ON  CAST(SC_SERVICE_CENTER AS VARCHAR(10))=CAST(AH.SALES_SVC_CD  AS VARCHAR(10)),
(SELECT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM where MO_ID=:WF_MONTH_ID) DT 
WHERE length(TRIM(LIFE.LF_MEMBERSHIP)) = 8
AND SUBSTR(LIFE.LF_MEMBERSHIP,2,1) NOT IN (''C'',''O'') 
AND MO_DESC BETWEEN LIFE.CHG_EFF_DT AND LIFE.CHG_EXP_DT 
AND SUBSTR(LIFE.LF_MEMBERSHIP,1,1) =''C''
GROUP BY 1,2,3,4,5,6,7,8) A 
QUALIFY ROW_NUMBER() OVER(PARTITION BY MO_ID,MEMBER_NUMBER ORDER BY CHG_EFF_DT DESC,LF_ISSUE_DATE DESC,LF_APPL_DATE DESC,SC_POLICY_NUM DESC) = 1
),
CA2 AS(
SELECT DISTINCT MO_ID,MEMBER_TYPE,MEMBER_NUMBER,ST_CD FROM (
SELECT MO_ID,
(CASE WHEN SUBSTR(ING.INSURED_MEMBER_NUM,1,1) =''C'' THEN ''CST'' ELSE ''MBR'' END) AS MEMBER_TYPE,
CAST (ZEROIFNULL(SUBSTR(ING.INSURED_MEMBER_NUM,2,7) )AS INTEGER) AS MEMBER_NUMBER,
AH.SALES_ST_CD ST_CD,
CHG_EFF_DT,
POL_ISS_DT
FROM DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST ING
LEFT OUTER JOIN DB_T_CORE_PROD.AGENT_HIER AH ON  CAST(CAST(SERV_CENTER_NUM AS INTEGER) AS VARCHAR(10))=CAST(AH.SALES_SVC_CD  AS VARCHAR(10)),
(SELECT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM where mo_id  = :WF_MONTH_ID) DT 
WHERE length(TRIM(ING.INSURED_MEMBER_NUM)) = 8
AND SUBSTR(ING.INSURED_MEMBER_NUM,2,1) NOT IN (''C'',''O'') 
AND MO_DESC BETWEEN ING.CHG_EFF_DT AND ING.CHG_EXP_DT 
AND SUBSTR(ING.INSURED_MEMBER_NUM,1,1) =''C'' 
AND (MEMBER_NUMBER,MO_ID) NOT IN (SELECT MEMBER_NUMBER,MO_ID FROM  CA1 )
GROUP BY 1,2,3,4,5,6) A 
QUALIFY ROW_NUMBER() OVER(PARTITION BY MO_ID,MEMBER_NUMBER ORDER BY CHG_EFF_DT DESC,POL_ISS_DT DESC) = 1
),
/*CA3 AS(
SELECT DISTINCT MO_ID,MEMBER_TYPE,MEMBER_NUMBER,ST_CD FROM (
SELECT MO_ID,
(CASE WHEN SUBSTR(ASICPOLS.PC_MEMBER_NUMBER,1,1) =''C'' THEN ''CST'' ELSE ''MBR'' END) AS MEMBER_TYPE,
CAST (ZEROIFNULL(SUBSTR(ASICPOLS.PC_MEMBER_NUMBER,2,7) )AS INTEGER) AS MEMBER_NUMBER,
SUBSTRING(TRIM(ASICPOLS.PC_CITYST) FROM CHARACTER_LENGTH(TRIM(ASICPOLS.PC_CITYST)) -1 FOR 2) as  ST_CD,
CHG_EFF_DT
FROM DB_T_CORE_MEMBXREF_PROD.ASICPOLS DB_T_CORE_MEMBXREF_PROD.ASICPOLS, (SELECT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM where mo_id  = :WF_MONTH_ID) DT 
WHERE length(TRIM(ASICPOLS.PC_MEMBER_NUMBER)) = 8
AND SUBSTR(ASICPOLS.PC_MEMBER_NUMBER,2,1) NOT IN (''C'',''O'') 
AND MO_DESC BETWEEN ASICPOLS.CHG_EFF_DT AND ASICPOLS.CHG_EXP_DT 
AND SUBSTR(ASICPOLS.PC_MEMBER_NUMBER,1,1) =''C'' 
AND (MEMBER_NUMBER,MO_ID) NOT IN (SELECT MEMBER_NUMBER,MO_ID FROM  CA2 UNION  SELECT MEMBER_NUMBER,MO_ID FROM CA1 )
GROUP BY 1,2,3,4,5) A 
QUALIFY ROW_NUMBER() OVER(PARTITION BY MO_ID,MEMBER_NUMBER ORDER BY CHG_EFF_DT DESC) = 1
),*/
CA4 AS(
SELECT DISTINCT MO_ID,MEMBER_TYPE,MEMBER_NUMBER,ST_CD FROM (
SELECT MO_ID,
(CASE WHEN SUBSTR(MANHOMEPOLS.PC_MEMBER_NUMBER,1,1) =''C'' THEN ''CST'' ELSE ''MBR'' END) AS MEMBER_TYPE,
CAST (ZEROIFNULL(SUBSTR(MANHOMEPOLS.PC_MEMBER_NUMBER,2,7) )AS INTEGER) AS MEMBER_NUMBER,
AH.SALES_ST_CD as  ST_CD,
CHG_EFF_DT
FROM DB_T_CORE_MEMBXREF_PROD.MANHOMEPOLS MANHOMEPOLS
LEFT OUTER JOIN DB_T_CORE_PROD.AGENT_HIER AH ON  CAST(SC_SERVICE_CENTER AS VARCHAR(10))=CAST(AH.SALES_SVC_CD  AS VARCHAR(10)),
(SELECT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM where mo_id = :WF_MONTH_ID) DT 
WHERE length(TRIM(MANHOMEPOLS.PC_MEMBER_NUMBER)) = 8
AND SUBSTR(MANHOMEPOLS.PC_MEMBER_NUMBER,2,1) NOT IN (''C'',''O'') 
AND MO_DESC BETWEEN MANHOMEPOLS.CHG_EFF_DT AND MANHOMEPOLS.CHG_EXP_DT 
AND SUBSTR(MANHOMEPOLS.PC_MEMBER_NUMBER,1,1) =''C'' 
AND (MEMBER_NUMBER,MO_ID) NOT IN (/*SEL MEMBER_NUMBER,MO_ID FROM  CA3 UNION*/  SELECT MEMBER_NUMBER,MO_ID FROM CA2 UNION  SELECT MEMBER_NUMBER,MO_ID FROM CA1 )
GROUP BY 1,2,3,4,5) A 
QUALIFY ROW_NUMBER() OVER(PARTITION BY MO_ID,MEMBER_NUMBER ORDER BY CHG_EFF_DT DESC) = 1
),
CA5 AS(
SELECT DISTINCT MO_ID,MEMBER_TYPE,MEMBER_NUMBER,ST_CD FROM (
SELECT MO_ID,
(CASE WHEN SUBSTR(FIREPOLS.PC_MEMBER_NUMBER,1,1) =''C'' THEN ''CST'' ELSE ''MBR'' END) AS MEMBER_TYPE,
CAST (ZEROIFNULL(SUBSTR(FIREPOLS.PC_MEMBER_NUMBER,2,7) )AS INTEGER) AS MEMBER_NUMBER,
AH.SALES_ST_CD as  ST_CD,
CHG_EFF_DT
FROM DB_T_CORE_MEMBXREF_PROD.FIREPOLS FIREPOLS
LEFT OUTER JOIN DB_T_CORE_PROD.AGENT_HIER AH ON  CAST(SC_SERVICE_CENTER AS VARCHAR(10))=CAST(AH.SALES_SVC_CD  AS VARCHAR(10)),
(SELECT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM where mo_id  = :WF_MONTH_ID) DT 
WHERE length(TRIM(FIREPOLS.PC_MEMBER_NUMBER)) = 8
AND SUBSTR(FIREPOLS.PC_MEMBER_NUMBER,2,1) NOT IN (''C'',''O'') 
AND MO_DESC BETWEEN FIREPOLS.CHG_EFF_DT AND FIREPOLS.CHG_EXP_DT 
AND SUBSTR(FIREPOLS.PC_MEMBER_NUMBER,1,1) =''C'' 
AND (MEMBER_NUMBER,MO_ID) NOT IN (SELECT MEMBER_NUMBER,MO_ID FROM  CA4 /*UNION  SELECT MEMBER_NUMBER,MO_ID FROM CA3 */
UNION  SELECT MEMBER_NUMBER,MO_ID FROM CA2 UNION  SELECT MEMBER_NUMBER,MO_ID FROM CA1)
GROUP BY 1,2,3,4,5) A
QUALIFY ROW_NUMBER() OVER(PARTITION BY MO_ID,MEMBER_NUMBER ORDER BY CHG_EFF_DT DESC) = 1
),
/* -CUST_ADDRESS  */
CUST_ADDRESS AS(
   SELect * FROM CA1
   UNION 
   SELect * FROM CA2
   UNION 
   /*SEL*FROM CA3
   UNION ALL*/
   SELect * FROM CA4
   UNION 
   SELect * FROM CA5
   ),
   /*THIS QUERY HOLDS THE MTD BEGNINING INFORCE MEMBERS */
/*  MEMB_BEG_MTD_TEMP  */
MEMB_BEG_MTD_TEMP AS(
SELECT A.MEMB_NUM , B.MEMB_SKEY , A.MEMB_EFF_DT,C.MO_ID  
FROM DB_T_CORE_PROD.MEMBER_MSTR A, DB_T_CORE_PROD.MEMBER_TRANS B,
(SELECT MO_ID,MIN(DT_DESC)-1 BEG_DT,MAX(DT_DESC) END_DT  FROM DB_T_SHRD_PROD.DT_DIM  WHERE MO_ID = :WF_MONTH_ID GROUP by MO_ID) C
WHERE A.MEMB_SKEY = B.MEMB_SKEY
AND B.STATUS_CD IN (0,1,9)
AND B.COMM_CD1 || B.COMM_CD2 || B.COMM_CD3 <> ''XXY''
AND B.MEMB_TYPE IN (''A'', ''C'')
AND A.MEMB_EXP_DT > BEG_DT
AND BEG_DT BETWEEN B.CHG_EFF_DT AND B.CHG_EXP_DT),

/*THIS QUERY HOLDS THE ENDING INFORCE MEMBERS*/
/* MEMB_END_TEMP */
MEMB_END_TEMP AS (
SELECT A.MEMB_NUM  , B.MEMB_SKEY  , A.MEMB_EFF_DT,C.MO_ID  
FROM DB_T_CORE_PROD.MEMBER_MSTR A, DB_T_CORE_PROD.MEMBER_TRANS B,
(SELECT MO_ID,MIN(DT_DESC)-1 BEG_DT,MAX(DT_DESC) END_DT  FROM DB_T_SHRD_PROD.DT_DIM  WHERE MO_ID = :WF_MONTH_ID GROUP BY 1) C
WHERE A.MEMB_SKEY = B.MEMB_SKEY
AND B.STATUS_CD IN (0,1,9)
AND B.COMM_CD1 || B.COMM_CD2 || B.COMM_CD3 <> ''XXY''
AND B.MEMB_TYPE IN (''A'', ''C'')
AND A.MEMB_EXP_DT > END_DT
AND END_DT BETWEEN B.CHG_EFF_DT AND B.CHG_EXP_DT),

/*THIS QUERY HOLDS ALL MEMBERS THAT ARE INFORCE AT THE BEGNING AND AT THE ENDING  AND WOULD HOLD ITS STATUS (NEW, REIN, LAPSE OR STATIC)*/
/*STATUS CODES: 1-NEW BUSINESS, 2-REINSTATEMENTS, 3- LAPSES, 4-STATIC*/
/* MEMB_FLOW_TEMP */
MEMB_FLOW_TEMP AS (
SELECT DISTINCT COALESCE(BP.MEMB_NUM,EP.MEMB_NUM)MEMB_NUM ,COALESCE(BP.MEMB_SKEY,  EP.MEMB_SKEY)MEMB_SKEY, ''MTD'' PERIOD,
CASE WHEN EP.MEMB_SKEY IS NULL THEN 3
WHEN BP.MEMB_SKEY IS NULL AND EP.memb_EFF_DT  > CAST( CAST(EP.MO_ID AS VARCHAR(6))  AS DATE  )- 1  THEN 1
WHEN  BP.MEMB_SKEY IS NULL AND EP.memb_EFF_DT  <= CAST( CAST(EP.MO_ID AS VARCHAR(6))  AS DATE  )- 1  THEN 2 ELSE 4 END AS MEMB_STATUS
,COALESCE(BP.MO_ID,EP.MO_ID)MO_ID
FROM MEMB_BEG_MTD_TEMP BP FULL OUTER JOIN MEMB_END_TEMP EP
ON BP.MEMB_SKEY=EP.MEMB_SKEY
AND BP.MO_ID = EP.MO_ID),

/*THIS QUERY HOLDS ALL MEMBERS AND LOB THEY ARE IN*/
/* MEMB_BUCKET_TEMP */
MEMB_BUCKET_TEMP AS(
SELECT 
PC_MEMBER_NUMBER AS MEMB_NUM,
EXTRACT(YEAR FROM MO_DESC)*100+EXTRACT(MONTH FROM MO_DESC) MO_ID,
SUM(AUTOPOLS) AUTOPOLS,
SUM(HOMEPOLS) HOMEPOLS,
SUM(MANHOMEPOLS) MANHOMEPOLS,
SUM(FARMPOLS) FARMPOLS,
SUM(FIREPOLS) FIREPOLS,
SUM(SMLNPOLS) SMLNPOLS,
SUM(PORTPOLS) PORTPOLS,
SUM(RHPOLS) RHPOLS,
SUM(LOANS) LOANS,
SUM(ASICPOLS) ASICPOLS,
SUM(LIFEPOLS) LIFEPOLS,
SUM(FGMPOLS) FGMPOLS
FROM (
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER, MO_DESC,
1 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM (SELECT DISTINCT PC_MEMBER_NUMBER, MO_DESC  from DB_T_CORE_MEMBXREF_PROD.AUTOPOLS 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT 	
AND (CAST( (MO_DESC-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
union 
SELECT distinct EX_MEMBER_NUM,MO_DESC  from DB_T_CORE_MEMBXREF_PROD.EXCEED_POL_LIST 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT 
) bothauto
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
UNION
SELECT DISTINCT cast( PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER, MO_DESC,
0 AUTOPOLS,1 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.HOMEPOLS 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
--CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (MO_DESC-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
UNION
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER, MO_DESC, 
0 AUTOPOLS,0 HOMEPOLS,1 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.MANHOMEPOLS 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (MO_DESC-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
UNION
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER, MO_DESC,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,1 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.FARMPOLS 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (MO_DESC-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
UNION
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER, MO_DESC,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,1 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.FIREPOLS 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (MO_DESC-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
UNION
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER, MO_DESC,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,1 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS
FROM DB_T_CORE_MEMBXREF_PROD.SMLNPOLS 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (MO_DESC-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
UNION
SELECT DISTINCT cast( PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER, MO_DESC,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,1 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.PORTPOLS 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (MO_DESC-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
UNION
SELECT DISTINCT  cast(RH_MEM_NBR as integer) PC_MEMBER_NUMBER, MO_DESC, 
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,1 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS
from (SELECT DISTINCT  RH_MEM_NBR,MO_DESC  FROM DB_T_CORE_MEMBXREF_PROD.RHPOLS 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE  MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT
union
SELECT DISTINCT RH_MEM_NBR,MO_DESC FROM DB_T_CORE_MEMBXREF_PROD.RHPOLS_HIST 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE ((CAST( (MO_DESC - RH_XDATE) AS FLOAT) /366)<=2.0) ) RHPOLS where  
UPPER(SUBSTR(RH_MEM_NBR,1,1) )
--(CS)
=LOWER(SUBSTR(RH_MEM_NBR,1,1) )
UNION
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER, MO_DESC,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,1 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.LOANS 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B 
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT
/*UNION
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER, MO_DESC,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,1 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.ASICPOLS 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( ( MO_DESC-  PC_EXP_DATE) AS FLOAT) /366)<=2.0*/
UNION
SELECT DISTINCT cast( LF_MEMBERSHIP as integer) PC_MEMBER_NUMBER, MO_DESC,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,1 LIFEPOLS,0 FGMPOLS 
FROM (SELECT DISTINCT LF_MEMBERSHIP,MO_DESC from DB_T_CORE_MEMBXREF_PROD.LIFEPOLS 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B 
WHERE MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT 
union SELECT distinct INSURED_MEMBER_NUM,MO_DESC from DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT) bothlife
WHERE UPPER(SUBSTR(LF_MEMBERSHIP ,1,1) )
--(CS)
=LOWER(SUBSTR(LF_MEMBERSHIP ,1,1) )
UNION
SELECT DISTINCT cast( PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER, MO_DESC,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,1 FGMPOLS
FROM DB_T_CORE_MEMBXREF_PROD.FGMPOLS 
, (SELECT DISTINCT MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID) B
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND MO_DESC BETWEEN CHG_EFF_DT AND CHG_EXP_DT
AND (CAST( (MO_DESC-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
)UNIONED
GROUP BY PC_MEMBER_NUMBER, MO_DESC)
/* --MAIN QUERY FOR DB_T_CORE_PROD.AGG_ENTERPRISE_METRICS_MTHLY */

SELECT 1.01 GROUP_CD ,''Membership'' LOB_TYPE,CAST(''Inforce Customers'' AS VARCHAR(100)) IND_TYPE, 
MO_ID MO_ID,CAST(''AL'' AS VARCHAR(10)) SALES_ST_CD,SUM(CAST(ENDMIF_CNT AS DECIMAL(18,3)) ) CNT ,CAST(0 AS DECIMAL(18,3)) YTD_CNT,''N'' BACKFILL_IND FROM DB_T_CORE_MEMBXREF_PROD.AGG_MEMB_FLOW 
WHERE GROUP_CD = 37 AND PERIOD = ''MTD''  AND MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8

UNION
SELECT 1.01 GROUP_CD,''Membership'' LOB_TYPE,CAST(''Inforce Customers'' AS VARCHAR(100)) IND_TYPE, 
A.MO_ID MO_ID,CASE WHEN COALESCE(A.ST_CD,B.ST_CD) IN (''MS'',''GA'') THEN  COALESCE(A.ST_CD,B.ST_CD) ELSE ''OTHERS'' END SALES_ST_CD,
COUNT(*) CNT ,0 YTD_CNT,''N'' BACKFILL_IND FROM DB_T_CORE_AN_PROD.MEMB_CUST A 
LEFT OUTER JOIN  CUST_ADDRESS B
ON A.MO_ID = B.MO_ID 
AND A.MEMBER_NUMBER = B.MEMBER_NUMBER
WHERE A.MEMBER_TYPE = ''CST''  AND A.MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8

UNION
SELECT 1.02 GROUP_CD,''Membership'' LOB_TYPE,CAST(''New Customers'' AS VARCHAR(100)) IND_TYPE, 
MO_ID MO_ID,''AL'' SALES_ST_CD,SUM(NEW_CNT) CNT ,0 YTD_CNT,''N'' BACKFILL_IND FROM DB_T_CORE_MEMBXREF_PROD.AGG_MEMB_FLOW 
WHERE GROUP_CD = 37 AND PERIOD = ''MTD'' AND MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8

UNION 
SELECT 1.02 GROUP_CD,''Membership'' LOB_TYPE,CAST(''New Customers'' AS VARCHAR(100)) IND_TYPE, 
A.MO_ID MO_ID, CASE WHEN COALESCE(A.ST_CD,B.ST_CD) IN (''MS'',''GA'') THEN  COALESCE(A.ST_CD,B.ST_CD) ELSE ''OTHERS'' END SALES_ST_CD,
COUNT(*) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_AN_PROD.MEMB_CUST A LEFT OUTER JOIN  CUST_ADDRESS B
ON A.MO_ID = B.MO_ID 
AND A.MEMBER_NUMBER = B.MEMBER_NUMBER
INNER JOIN 
(SELECT MEMBER_NUMBER,MIN(MO_ID) MO_ID_MIN FROM DB_T_CORE_AN_PROD.MEMB_CUST WHERE MEMB_CUST.MEMBER_TYPE = ''CST'' GROUP BY 1) C
ON A.MEMBER_NUMBER = C.MEMBER_NUMBER AND A.MO_ID = C.MO_ID_MIN
WHERE A.MEMBER_TYPE = ''CST'' AND 
INCEPT_DATE > CAST(CAST(A.MO_ID AS VARCHAR(8)) AS DATE )-1  
AND A.MO_ID = :WF_MONTH_ID 
GROUP BY 1,2,3,4,5,7,8

UNION 
SELECT CASE 
WHEN GROUP_CD = 2 THEN 1.03
WHEN GROUP_CD = 13 THEN 1.04
WHEN GROUP_CD = 17 THEN 1.05
WHEN GROUP_CD = 19 THEN 1.06
WHEN GROUP_CD = 21 THEN 1.07
WHEN GROUP_CD = 23 THEN 1.08
WHEN GROUP_CD = 26 THEN 1.09
WHEN GROUP_CD = 32 THEN 1.10
WHEN GROUP_CD IN (3,4,5,6,7,8,9,10,11,12,14,15,18,20,22,24,27,30,33) THEN 1.11
WHEN GROUP_CD = 36 THEN 1.12
WHEN GROUP_CD = 35 THEN 1.13 ELSE NULL END GROUP_CD_NEW,
''Membership'' LOB_TYPE,
CASE 
WHEN GROUP_CD_NEW = 1.03 THEN CAST(''Auto Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD_NEW = 1.04 THEN CAST(''ASIC Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD_NEW = 1.05 THEN CAST(''Home Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD_NEW = 1.06 THEN CAST(''Farm Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD_NEW = 1.07 THEN CAST(''Man Home Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD_NEW = 1.08 THEN CAST(''Fire Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD_NEW = 1.09 THEN CAST(''Health Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD_NEW = 1.10 THEN CAST(''LIFE Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD_NEW = 1.11 THEN CAST(''Customers with Multiple DB_T_CORE_DM_PROD.Policy Lines''  AS VARCHAR(100)) 
WHEN GROUP_CD_NEW = 1.12 THEN CAST(''Customers with No DB_T_CORE_DM_PROD.Policy Lines''  AS VARCHAR(100)) 
WHEN GROUP_CD_NEW = 1.13 THEN CAST(''Customers with Other DB_T_CORE_DM_PROD.Policy Lines''  AS VARCHAR(100)) 
ELSE NULL END IND_TYPE,
MO_ID MO_ID,''AL'' SALES_ST_CD,SUM(ENDMIF_CNT) CNT ,0 YTD_CNT,''N'' BACKFILL_IND FROM DB_T_CORE_MEMBXREF_PROD.AGG_MEMB_FLOW 
WHERE PERIOD = ''MTD'' AND MO_ID = :WF_MONTH_ID
AND GROUP_CD IN (2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,23,24,26,27,30,32,33,36,35)
GROUP BY 1,2,3,4,5,7,8

UNION 
SELECT CASE 
WHEN COALESCE(AUTO,0) >0 AND COALESCE(HOME,0)+COALESCE(PORT,0)+COALESCE(MANHOME,0)+COALESCE(FIRE,0)+COALESCE(FARM,0)+COALESCE(ASIC,0)+COALESCE(SMLN,0)+COALESCE(FGM,0)+COALESCE(LIFE,0) = 0 THEN 1.03
WHEN COALESCE(ASIC,0) >0 AND COALESCE(HOME,0)+COALESCE(PORT,0)+COALESCE(MANHOME,0)+COALESCE(FIRE,0)+COALESCE(FARM,0)+COALESCE(AUTO,0)+COALESCE(SMLN,0)+COALESCE(FGM,0)+COALESCE(LIFE,0) = 0 THEN 1.04
WHEN COALESCE(HOME,0) >0 AND COALESCE(AUTO,0)+COALESCE(PORT,0)+COALESCE(MANHOME,0)+COALESCE(FIRE,0)+COALESCE(FARM,0)+COALESCE(ASIC,0)+COALESCE(SMLN,0)+COALESCE(FGM,0)+COALESCE(LIFE,0) = 0 THEN 1.05
WHEN COALESCE(FARM,0) >0 AND COALESCE(AUTO,0)+COALESCE(PORT,0)+COALESCE(MANHOME,0)+COALESCE(FIRE,0)+COALESCE(HOME,0)+COALESCE(ASIC,0)+COALESCE(SMLN,0)+COALESCE(FGM,0)+COALESCE(LIFE,0) = 0 THEN 1.06
WHEN COALESCE(MANHOME,0) >0 AND COALESCE(AUTO,0)+COALESCE(PORT,0)+COALESCE(FARM,0)+COALESCE(FIRE,0)+COALESCE(HOME,0)+COALESCE(ASIC,0)+COALESCE(SMLN,0)+COALESCE(FGM,0)+COALESCE(LIFE,0) = 0 THEN 1.07
WHEN COALESCE(FIRE,0) >0 AND COALESCE(AUTO,0)+COALESCE(PORT,0)+COALESCE(FARM,0)+COALESCE(MANHOME,0)+COALESCE(HOME,0)+COALESCE(ASIC,0)+COALESCE(SMLN,0)+COALESCE(FGM,0)+COALESCE(LIFE,0) = 0  THEN 1.08
WHEN COALESCE(LIFE,0) >0 AND COALESCE(AUTO,0)+COALESCE(HOME,0)+COALESCE(PORT,0)+COALESCE(MANHOME,0)+COALESCE(FIRE,0)+COALESCE(FARM,0)+COALESCE(ASIC,0)+COALESCE(SMLN,0)+COALESCE(FGM,0) = 0  THEN 1.10
WHEN 
((COALESCE(AUTO,0) >0 AND COALESCE(HOME,0)+COALESCE(MANHOME,0)+COALESCE(FARM,0)+COALESCE(FIRE,0)+COALESCE(SMLN,0)+COALESCE(PORT,0)+COALESCE(ASIC,0)+COALESCE(LIFE,0)+COALESCE(FGM,0) >0 )OR
(COALESCE(ASIC,0) >0 AND COALESCE(HOME,0)+COALESCE(MANHOME,0)+COALESCE(FARM,0)+COALESCE(FIRE,0)+COALESCE(SMLN,0)+COALESCE(PORT,0)+COALESCE(AUTO,0)+COALESCE(LIFE,0)+COALESCE(FGM,0)>0 ) OR
(COALESCE(HOME,0) >0 AND COALESCE(ASIC,0)+COALESCE(MANHOME,0)+COALESCE(FARM,0)+COALESCE(FIRE,0)+COALESCE(SMLN,0)+COALESCE(PORT,0)+COALESCE(AUTO,0)+COALESCE(LIFE,0)+COALESCE(FGM,0) >0 )OR
(COALESCE(FARM,0) >0 AND COALESCE(HOME,0)+COALESCE(MANHOME,0)+COALESCE(ASIC,0)+COALESCE(FIRE,0)+COALESCE(SMLN,0)+COALESCE(PORT,0)+COALESCE(AUTO,0)+COALESCE(LIFE,0)+COALESCE(FGM,0)>0 ) OR
(COALESCE(MANHOME,0) >0 AND COALESCE(HOME,0)+COALESCE(ASIC,0)+COALESCE(FARM,0)+COALESCE(FIRE,0)+COALESCE(SMLN,0)+COALESCE(PORT,0)+COALESCE(AUTO,0)+COALESCE(LIFE,0)+COALESCE(FGM,0)>0 ) OR
(COALESCE(FIRE,0) >0 AND COALESCE(HOME,0)+COALESCE(MANHOME,0)+COALESCE(FARM,0)+COALESCE(ASIC,0)+COALESCE(SMLN,0)+COALESCE(PORT,0)+COALESCE(AUTO,0)+COALESCE(LIFE,0)+COALESCE(FGM,0)>0 ) OR
(COALESCE(LIFE,0) >0 AND COALESCE(HOME,0)+COALESCE(MANHOME,0)+COALESCE(FARM,0)+COALESCE(ASIC,0)+COALESCE(SMLN,0)+COALESCE(PORT,0)+COALESCE(AUTO,0)+COALESCE(FIRE,0)+COALESCE(FGM,0)>0 ) ) THEN 1.11
WHEN 
COALESCE(AUTO,0)+COALESCE(HOME,0)+COALESCE(PORT,0)+COALESCE(MANHOME,0)+COALESCE(FIRE,0)+
COALESCE(FARM,0)+COALESCE(ASIC,0)+COALESCE(SMLN,0)+COALESCE(FGM,0)+COALESCE(LIFE,0)  = 0 THEN 1.12
ELSE 1.13  END GROUP_CD,
''Membership'' LOB_TYPE,
CASE 
WHEN GROUP_CD = 1.03 THEN CAST(''Auto Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD = 1.04 THEN CAST(''ASIC Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD = 1.05 THEN CAST(''Home Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD = 1.06 THEN CAST(''Farm Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD = 1.07 THEN CAST(''Man Home Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD = 1.08 THEN CAST(''Fire Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD = 1.10 THEN CAST(''LIFE Only Customers''  AS VARCHAR(100)) 
WHEN GROUP_CD = 1.11 THEN CAST(''Customers with Multiple DB_T_CORE_DM_PROD.Policy Lines''  AS VARCHAR(100)) 
WHEN GROUP_CD = 1.12 THEN CAST(''Customers with No DB_T_CORE_DM_PROD.Policy Lines''  AS VARCHAR(100)) 
WHEN GROUP_CD = 1.13 THEN CAST(''Customers with Other DB_T_CORE_DM_PROD.Policy Lines''  AS VARCHAR(100)) 
ELSE NULL END IND_TYPE,
A.MO_ID MO_ID,CASE WHEN COALESCE(A.ST_CD,B.ST_CD) IN (''MS'',''GA'') THEN  COALESCE(A.ST_CD,B.ST_CD) ELSE ''OTHERS'' END SALES_ST_CD,
COUNT(*) CNT ,0 YTD_CNT,''N'' BACKFILL_IND FROM DB_T_CORE_AN_PROD.MEMB_CUST A 
LEFT OUTER JOIN  CUST_ADDRESS B
ON A.MO_ID = B.MO_ID 
AND A.MEMBER_NUMBER = B.MEMBER_NUMBER
WHERE A.MEMBER_TYPE = ''CST''AND 
A.MO_ID = :WF_MONTH_ID 
GROUP BY 1,2,3,4,5,7,8

UNION 
SELECT CASE WHEN LOB_CD = ''AUTO'' THEN 2.01 
WHEN LOB_CD = ''HOME'' THEN 3.01 ELSE NULL END GROUP_CD, 
CASE WHEN LOB_CD = ''AUTO'' THEN ''Auto'' 
WHEN LOB_CD = ''HOME'' THEN ''Home'' ELSE NULL END LOB_TYPE,
CASE WHEN LOB_CD = ''AUTO'' THEN CAST(''Inforce Auto Policies''AS VARCHAR(100))
WHEN LOB_CD = ''HOME'' THEN CAST(''Inforce Home Policies''AS VARCHAR(100)) ELSE NULL END IND_TYPE,
MO_ID, ST_CD,
SUM(CASE WHEN PLCY_CHG_EXP_DT> MO_DESC AND INFORCE_IND=''Y'' THEN 1 ELSE 0 END) MTD_CNT,
0 YTD_CNT, ''N'' BACKFILL_IND  
FROM   DB_T_ML_PROD.MULTILINE_POLSTAT A JOIN                 
(SELECT DISTINCT MO_DESC,MO_ID FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID)  B
ON FEED_DT <= MO_DESC        
WHERE LOB_CD IN (''AUTO'',''HOME'') AND INFORCE_IND = ''Y'' 
GROUP BY 1,2,3,4,5,7,8

UNION 
SELECT 2.02 GROUP_CD, ''Auto'' LOB_TYPE,
CAST(''Inforce Auto Units''AS VARCHAR(100)) IND_TYPE, 
MO_ID, ST_CD
,SUM(CASE WHEN PLCY_CHG_EXP_DT> MO_DESC AND INFORCE_IND=''Y'' THEN  INF_UNIT_CTS ELSE 0 END) MTD_CNT,
0 YTD_CNT, ''N'' BACKFILL_IND  
FROM    DB_T_ML_PROD.MULTILINE_POLSTAT A JOIN                 
(SELECT DISTINCT MO_DESC,MO_ID FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID)  B
ON FEED_DT <= MO_DESC        
WHERE LOB_CD = (''AUTO'') AND INFORCE_IND = ''Y'' 
GROUP BY 1,2,3,4,5,7,8

UNION
SELECT 2.03 GROUP_CD,''Auto'' LOB_TYPE,CAST(''Earned Premium''AS VARCHAR(100)) IND_TYPE,
SALES_MO_ID MO_ID,SALES_ST_CD,SUM(TOTAL_ERN_PREM_AVG) CNT,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_PROD.AGG_LR_PI_RDD_MTHLY 
WHERE SALES_MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8

UNION
SELECT 2.04 GROUP_CD,''Auto'' LOB_TYPE,CAST(''Total Reported Loss''AS VARCHAR(100)) IND_TYPE,
SALES_MO_ID MO_ID,SALES_ST_CD,SUM(TOTAL_PAID_LOSS_AMT) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_PROD.AGG_LR_PI_RDD_MTHLY 
WHERE SALES_MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8

UNION
SELECT 2.05 GROUP_CD,''Auto'' LOB_TYPE,CAST(''Non CAT Reported Loss''AS VARCHAR(100)) IND_TYPE
,SALES_MO_ID MO_ID,SALES_ST_CD,SUM(TOTAL_PAID_LOSS_AMT) CNT  ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_PROD.AGG_LR_PI_RDD_MTHLY 
WHERE SALES_CAT_IND = 0  
AND SALES_MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8

UNION 
SELECT 2.06 GROUP_CD,''Auto'' LOB_TYPE,CAST(''Prior Year Inforce Policies''AS VARCHAR(100)) IND_TYPE
,PERSIS_YR*100+PERSIS_MTH MO_ID,ST_CD SALES_ST_CD,SUM( PREV_MTD_PLCY_CNT ) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_PROD.AGG_PERSIS_MTHLY   
WHERE  MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8

UNION 
SELECT 2.07 GROUP_CD,''Auto'' LOB_TYPE,CAST(''Persistent Policies''AS VARCHAR(100)) IND_TYPE
,PERSIS_YR*100+PERSIS_MTH MO_ID,ST_CD SALES_ST_CD,
SUM( PERSIS_PLCY_CNT ) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_PROD.AGG_PERSIS_MTHLY   
WHERE  MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8

UNION
SELECT 2.08 GROUP_CD, ''Auto'' LOB_TYPE,CAST(''New Business Policies for Retention - 3 Months'' AS VARCHAR(100))  IND_TYPE , MO_ID,SALES_ST_CD,TOT_PLCY_CNT ,0 YTD_CNT,''N'' BACKFILL_IND FROM  
(SELECT DISTINCT MO_ID,EXTRACT( YEAR FROM ADD_MONTHS(MO_DESC,-3))*100+EXTRACT( MONTH FROM ADD_MONTHS(MO_DESC,-3)) PREV_MO_ID_3 
FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) A 
LEFT OUTER JOIN 
(SELECT ipt_yr*100+ipt_mo IPT_MO_ID, SALES_ST_CD,COUNT(DISTINCT PLCY_NBR) TOT_PLCY_CNT FROM DB_T_CORE_PROD.AGG_RET_DTL GROUP BY 1,2)  B
ON B.IPT_MO_ID = A.PREV_MO_ID_3 

UNION
SELECT 2.09 GROUP_CD, ''Auto'' LOB_TYPE,CAST(''Expired Policies for Retention - 3 Months'' AS VARCHAR(100))  IND_TYPE , MO_ID,
C.SALES_ST_CD,COUNT(DISTINCT PLCY_NBR)  EXP_PLCY_CNT ,0 YTD_CNT,''N'' BACKFILL_IND FROM 
(SELECT DISTINCT MO_ID,EXTRACT( YEAR FROM ADD_MONTHS(MO_DESC,-3))*100+EXTRACT( MONTH FROM ADD_MONTHS(MO_DESC,-3)) PREV_MO_ID_3 
FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) A 
LEFT OUTER JOIN 
DB_T_CORE_PROD.AGG_RET_DTL C
ON ipt_yr*100+ipt_mo = PREV_MO_ID_3
WHERE PLCY_DEF_DT IS NOT NULL  AND EXTRACT(YEAR FROM PLCY_DEF_DT)*100+EXTRACT(MONTH FROM PLCY_DEF_DT)<=MO_ID
GROUP BY 1,2,3,4,5,7,8

UNION
SELECT 2.10 GROUP_CD, ''Auto'' LOB_TYPE,CAST(''New Business Policies for Retention - 6 Months'' AS VARCHAR(100))  IND_TYPE , MO_ID,SALES_ST_CD,TOT_PLCY_CNT ,0 YTD_CNT,''N'' BACKFILL_IND FROM  
(SELECT DISTINCT MO_ID,EXTRACT( YEAR FROM ADD_MONTHS(MO_DESC,-6))*100+EXTRACT( MONTH FROM ADD_MONTHS(MO_DESC,-6)) PREV_MO_ID_3 
FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) A 
LEFT OUTER JOIN 
(SELECT ipt_yr*100+ipt_mo IPT_MO_ID, SALES_ST_CD,COUNT(DISTINCT PLCY_NBR) TOT_PLCY_CNT FROM DB_T_CORE_PROD.AGG_RET_DTL GROUP BY 1,2)  B
ON B.IPT_MO_ID = A.PREV_MO_ID_3 




UNION
SELECT 2.11 GROUP_CD, ''Auto'' LOB_TYPE,CAST(''Expired Policies for Retention - 6 Months'' AS VARCHAR(100))  IND_TYPE , MO_ID,
C.SALES_ST_CD,COUNT(DISTINCT PLCY_NBR)  EXP_PLCY_CNT ,0 YTD_CNT,''N'' BACKFILL_IND FROM 
(SELECT DISTINCT MO_ID,EXTRACT( YEAR FROM ADD_MONTHS(MO_DESC,-6))*100+EXTRACT( MONTH FROM ADD_MONTHS(MO_DESC,-6)) PREV_MO_ID_3 
FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) A 
LEFT OUTER JOIN 
DB_T_CORE_PROD.AGG_RET_DTL C
ON ipt_yr*100+ipt_mo = PREV_MO_ID_3
WHERE PLCY_DEF_DT IS NOT NULL  AND EXTRACT(YEAR FROM PLCY_DEF_DT)*100+EXTRACT(MONTH FROM PLCY_DEF_DT)<=MO_ID
GROUP BY 1,2,3,4,5,7,8

UNION
SELECT 2.12 GROUP_CD, ''Auto'' LOB_TYPE,CAST(''New Business Policies for Retention - 1 Year'' AS VARCHAR(100))  IND_TYPE , MO_ID,SALES_ST_CD,TOT_PLCY_CNT ,0 YTD_CNT,''N'' BACKFILL_IND FROM  
(SELECT DISTINCT MO_ID,EXTRACT( YEAR FROM ADD_MONTHS(MO_DESC,-12))*100+EXTRACT( MONTH FROM ADD_MONTHS(MO_DESC,-12)) PREV_MO_ID_3 
FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) A 
LEFT OUTER JOIN 
(SELECT ipt_yr*100+ipt_mo IPT_MO_ID, SALES_ST_CD,COUNT(DISTINCT PLCY_NBR) TOT_PLCY_CNT FROM DB_T_CORE_PROD.AGG_RET_DTL GROUP BY 1,2)  B
ON B.IPT_MO_ID = A.PREV_MO_ID_3 

UNION
SELECT 2.13 GROUP_CD, ''Auto'' LOB_TYPE,CAST(''Expired Policies for Retention - 1 Year'' AS VARCHAR(100))  IND_TYPE , MO_ID,
C.SALES_ST_CD,COUNT(DISTINCT PLCY_NBR)  EXP_PLCY_CNT ,0 YTD_CNT,''N'' BACKFILL_IND FROM 
(SELECT DISTINCT MO_ID,EXTRACT( YEAR FROM ADD_MONTHS(MO_DESC,-12))*100+EXTRACT( MONTH FROM ADD_MONTHS(MO_DESC,-12)) PREV_MO_ID_3 
FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) A 
LEFT OUTER JOIN 
DB_T_CORE_PROD.AGG_RET_DTL C
ON ipt_yr*100+ipt_mo = PREV_MO_ID_3
WHERE PLCY_DEF_DT IS NOT NULL  AND EXTRACT(YEAR FROM PLCY_DEF_DT)*100+EXTRACT(MONTH FROM PLCY_DEF_DT)<=MO_ID
GROUP BY 1,2,3,4,5,7,8

UNION
SELECT 2.14 GROUP_CD,''Auto'' LOB_TYPE,CAST(''Inforce Auto Policies with ''AS VARCHAR(100))|| COV_TYPE_CD||'' ''||COALESCE(''- ''||COV_LIM_DESC, '''') IND_TYPE, 
MO_ID MO_ID,CASE WHEN RSK_ST_DESC = ''Alabama'' THEN ''AL''
WHEN RSK_ST_DESC = ''Mississippi'' THEN ''MS''
WHEN RSK_ST_DESC = ''Georgia'' THEN ''GA'' END SALES_ST_CD ,
COUNT(DISTINCT PLCY_NBR) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_PROD.AGG_PI_MTHLY 
WHERE COV_TYPE_CD IN (''BI'') AND  PLCY_CNT_WRIT_IFO = 1 
AND MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8

UNION
SELECT 2.15 GROUP_CD,''Auto'' LOB_TYPE,CAST(''Inforce Auto Policies with ''AS VARCHAR(100))|| COV_TYPE_CD||'' ''||COALESCE(''- ''||COV_LIM_DESC, '''') IND_TYPE, 
MO_ID MO_ID,CASE WHEN RSK_ST_DESC = ''Alabama'' THEN ''AL''
WHEN RSK_ST_DESC = ''Mississippi'' THEN ''MS''
WHEN RSK_ST_DESC = ''Georgia'' THEN ''GA'' END SALES_ST_CD ,
COUNT(DISTINCT PLCY_NBR) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_PROD.AGG_PI_MTHLY 
WHERE COV_TYPE_CD IN (''PD'') AND  PLCY_CNT_WRIT_IFO = 1  
AND MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8
UNION 
SELECT CASE WHEN LOB_CD = ''AUTO'' THEN 2.16 
WHEN LOB_CD = ''HOME'' THEN 3.07 ELSE NULL END GROUP_CD, 
CASE WHEN LOB_CD = ''AUTO'' THEN ''Auto'' 
WHEN LOB_CD = ''HOME'' THEN ''Home'' ELSE NULL END LOB_TYPE,
CAST(''New Business Written Counts''AS VARCHAR(100))IND_TYPE,
MO_ID, ST_CD,
SUM(CASE WHEN STATUS_OGN_EFF_DT= MO_DESC AND POLICY_ACTIVITY=''NEW'' THEN 1 ELSE 0 END) MTD_CNT,
0 YTD_CNT, ''N'' BACKFILL_IND  
FROM    DB_T_ML_PROD.MULTILINE_POLSTAT A JOIN                 
(SELECT DISTINCT MO_DESC,MO_ID FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID)  B
ON FEED_DT <= MO_DESC        
WHERE LOB_CD IN (''AUTO'',''HOME'') AND INFORCE_IND = ''Y'' 
GROUP BY 1,2,3,4,5,7,8

UNION 
SELECT 2.17 GROUP_CD,''Auto'' LOB_TYPE,CAST(''Total Quotes''AS VARCHAR(100)) IND_TYPE,
DT_ID/100 MO_ID,RISK_STATE_CD ,CAST(SUM(PLCY_CNT)AS DECIMAL(21,3)) PLCY_CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM  DB_T_CORE_PROD.AGG_AUTO_SCORECARD   A  WHERE QUOTE_IND = ''Q''  
AND QUOTE_COMPLETED = ''Y'' AND DISC NOT IN (''MTC'' , ''HOD'' , ''LFD'') 
AND MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8

UNION 
SELECT
  2.18 AS GROUP_CD,
  ''Auto'' AS LOB_TYPE,
  CAST(''Active Agents'' AS VARCHAR(100)) AS IND_TYPE,
  MO_ID,
  SALES_ST_CD,
  COUNT(DISTINCT AGENCY_NBR) AS AGNT_CNT,
  0 AS YTD_CNT,
  ''N'' AS BACKFILL_IND
FROM
  (
    SELECT
      MO_ID,
      SALES_ST_CD,
      AGENCY_NBR
    FROM
      DB_T_CORE_PROD.AGENT_HIER AS A,
      (
        SELECT
          MO_ID,
          MIN(DT_DESC) AS BEG_DT,
          MAX(DT_DESC) AS END_DT
        FROM
          DB_T_SHRD_PROD.DT_DIM
        WHERE
          MO_ID = 0
        GROUP BY
          1
      ) AS B
    WHERE
      AGNT_EFF_DT <= END_DT
      AND AGNT_EXPIRY_DT >= BEG_DT
      AND agnt_status_cd = ''''
      AND AGENCY_NBR = pay_agent_nbr
      AND sales_rgn_cd <> ''9''
      AND AGNT_CLIENT_ID <> ALL (
        SELECT
          AGNT_CLIENT_ID
        FROM
          DB_V_PROD.agnt_nm_lkup
        WHERE
          agnt_nm_Desc LIKE ''SC00%''
      )
    GROUP BY
      1,
      2,
      3
 union     SELECT
  MO_ID,
  RISK_STATE_CD,
  A.AGENCY_NBR
FROM
  DB_T_CORE_PROD.AGG_AUTO_SCORECARD AS A,
  (
    SELECT
      MO_ID,
      MIN(DT_ID) AS BEG_DT_ID,
      MAX(DT_ID) AS END_DT_ID
    FROM
      DB_T_SHRD_PROD.DT_DIM
    WHERE
      MO_ID = :WF_MONTH_ID
    GROUP BY
      1
  ) AS B,
  DB_T_CORE_PROD.AGENT_HIER AS AGNT
WHERE
  DT_ID >= BEG_DT_ID
  AND DT_ID <= END_DT_ID
  AND AGNT.AGENCY_NBR = A.AGENCY_NBR
  AND AGNT.AGENCY_NBR = PAY_AGENT_NBR
  AND QUOTE_COMPLETED = ''Y''
GROUP BY
  1,
  2,
  3
  ) as TEMP
GROUP BY
  1,
  2,
  3,
  4,
  5,
  7,
  8
UNION 
SELECT 2.19 GROUP_CD,''Auto'' LOB_TYPE,CAST(''No of Days''AS VARCHAR(100)) IND_TYPE,
A.MO_ID,RISK_STATE_CD , NO_OF_DAYS  ,0 YTD_CNT,''N'' BACKFILL_IND FROM 
(SELECT EXTRACT(YEAR FROM CALENDAR_DATE)*100+EXTRACT(MONTH FROM CALENDAR_DATE) MO_ID,COUNT(*) NO_OF_DAYS FROM 
DB_V_PROD_SMNTC.CALENDAR  WHERE DAY_OF_WEEK NOT IN (1,7) AND MO_ID  = :WF_MONTH_ID GROUP BY 1) A
INNER JOIN 
(SELECT DISTINCT  RISK_STATE_CD, DT_ID/100 MO_ID FROM DB_T_CORE_PROD.AGG_AUTO_SCORECARD WHERE MO_ID = :WF_MONTH_ID)  B
ON A.MO_ID = B.MO_ID WHERE A.MO_ID = :WF_MONTH_ID 

UNION 
SELECT 3.02 GROUP_CD,''Home'' LOB_TYPE,CAST(''Earned Premium''AS VARCHAR(100)) IND_TYPE,MO_ID,STATE_CD,
SUM(CAST(EP AS DECIMAL(21,3))) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM (
SELECT MO_ID,STATE_CD,CAT_CD_LOSS_YEAR,SUM(MTD_EP) EP,SUM(MTD_LA) LA 
FROM DB_T_CORE_DM_PROD.AGG_HO_LOSS_RATIO 
WHERE MO_ID = :WF_MONTH_ID GROUP BY 1,2,3) A 
GROUP BY  1,2,3,4,5,7,8

UNION 
SELECT 3.03 GROUP_CD,''Home'' LOB_TYPE,CAST(''Reported Loss''AS VARCHAR(100)) IND_TYPE,MO_ID,STATE_CD,
SUM(CAST(LA AS DECIMAL(21,3))) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM (
SELECT MO_ID,STATE_CD,CAT_CD_LOSS_YEAR,SUM(MTD_EP) EP,SUM(MTD_LA) LA 
FROM DB_T_CORE_DM_PROD.AGG_HO_LOSS_RATIO 
WHERE MO_ID = :WF_MONTH_ID GROUP BY 1,2,3) A 
GROUP BY  1,2,3,4,5,7,8

UNION 
SELECT 3.04 GROUP_CD,''Home'' LOB_TYPE,CAST(''Non CAT Reported Loss''AS VARCHAR(100)) IND_TYPE,MO_ID,STATE_CD,
SUM(CAST(NO_CAT_LA AS DECIMAL(21,3))) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM (
SELECT MO_ID,STATE_CD,CAT_CD_LOSS_YEAR,SUM(MTD_EP) EP,SUM(CASE WHEN SUBSTR( CAT_CD_LOSS_YEAR,1,1) = '''' THEN MTD_LA ELSE 0 END) NO_CAT_LA 
FROM DB_T_CORE_DM_PROD.AGG_HO_LOSS_RATIO 
WHERE MO_ID = :WF_MONTH_ID GROUP BY 1,2,3) A 
GROUP BY  1,2,3,4,5,7,8

UNION  
SELECT 3.05 GROUP_CD, ''Home'' LOB_TYPE, CAST(''Prior Year Inforce Policies''AS VARCHAR(100)) IND_TYPE,MO_ID,STATE_CD,
SUM(PRIOR_PLCY_CNT_IFO) CNT,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_DM_PROD.AGG_HO_PERSIST 
WHERE MO_ID = :WF_MONTH_ID 
GROUP BY 1,2,3,4,5,7,8

UNION  
SELECT 3.06 GROUP_CD, ''Home'' LOB_TYPE, CAST(''Persistent Policies''AS VARCHAR(100)) IND_TYPE,MO_ID,STATE_CD,
SUM(PERSIST_CNT_IFO) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_DM_PROD.AGG_HO_PERSIST 
WHERE MO_ID = :WF_MONTH_ID 
GROUP BY 1,2,3,4,5,7,8

UNION
SELECT 4.01 GROUP_CD,''Life'' LOB_TYPE,CAST(''Inforce DB_T_STAG_MEMBXREF_PROD.LIFE Policies'' AS VARCHAR(100)) IND_TYPE,MO_ID,
CASE WHEN STATE_CD IN (''AL'',''GA'',''MS'') THEN STATE_CD ELSE ''OTHERS'' END SALES_ST_CD,
COUNT(DISTINCT POLICY_NUM) CNT ,0 YTD_CNT,''N'' BACKFILL_IND  FROM 
(SELECT MO_ID, CAST(POL_ID AS VARCHAR(10)) POLICY_NUM,INSURED_STATE_CD STATE_CD FROM DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST  A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND POL_STATUS IN  (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') GROUP BY 1,2,3
UNION
SELECT MO_ID, CAST(SC_POLICY_NUM AS VARCHAR(10)) POLICY_NUM,
CASE WHEN  TRIM(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3) = '''' THEN NULL ELSE 
SUBSTR(
TRIM(SUBSTR(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3,1,length(TRIM(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3))-5)),
length(TRIM(SUBSTR(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3,1,length(TRIM(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3))-5)))-1,
length(TRIM(SUBSTR(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3,1,length(TRIM(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3))-5)))
) END STATE_CD 
FROM DB_T_CORE_MEMBXREF_PROD.LIFEPOLS  A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND LF_STATUS IN  (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') GROUP BY 1,2,3) TEMP
LEFT OUTER JOIN  DB_T_SHRD_PROD.STATE_LOOKUP B 
ON TEMP.STATE_CD=B.ST_CD 
GROUP BY 1,2,3,4,5,7,8

UNION 
SELECT 5.01 GROUP_CD, ''Other'' LOB_TYPE,CAST(''Total Corporate Earned Premium'' AS VARCHAR(100)) IND_TYPE,
MO_ID MO_ID,CASE WHEN SALES_ST_CD IN (''AL'',''GA'',''MS'') THEN SALES_ST_CD ELSE ''OTHERS'' END ST_CD,SUM(ERND_PREM) CNT,0 YTD_CNT,''N'' BACKFILL_IND  
FROM DB_T_CORE_FIN_PROD.AGG_FIN_SALES_PRODUCT  
WHERE MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8

UNION
SELECT 5.02 GROUP_CD, ''Other'' LOB_TYPE,CAST(''Total Corporate Reported Losses'' AS VARCHAR(100)) IND_TYPE,
MO_ID MO_ID,CASE WHEN SALES_ST_CD IN (''AL'',''GA'',''MS'') THEN SALES_ST_CD ELSE ''OTHERS'' END ST_CD,SUM(REPORTED_LOSS) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_FIN_PROD.AGG_FIN_SALES_PRODUCT  
WHERE MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8


UNION

/* --MAIN QUERY FOR DB_T_CORE_PROD.AGG_ENTERPRISE_METRICS_MTHLY */
/* DEL FROM DB_T_CORE_PROD.AGG_ENTERPRISE_METRICS_MTHLY WHERE GROUP_CD = 5.03 */
/*SELECT 5.03 GROUP_CD,''Other'' LOB_TYPE,CAST(''Unique Households'' AS VARCHAR(100)) IND_TYPE,MO_ID MO_ID,
CASE WHEN STATE IN (''AL'',''GA'',''MS'') THEN STATE ELSE ''OTHERS'' END ST_CD, COUNT(DISTINCT BUX_CMP_ID ) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_PROD.BUXTON_REVERSE_FEED
GROUP BY 1,2,3,4,5,7,8
UNION*/
SELECT 1.14, ''Membership'' LOB_TYPE,CAST(''LIFE Customers''  AS VARCHAR(100)) IND_TYPE, 
MO_ID,  ''AL'' SALES_ST_CD, 
SUM( CASE WHEN MEMB_STATUS =1 THEN 1 ELSE 0 END)+
SUM( CASE WHEN MEMB_STATUS =2 THEN 1 ELSE 0 END)+
SUM( CASE WHEN MEMB_STATUS =4 THEN 1 ELSE 0 END)  ENDMIF_CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM (
SELECT MO_ID, TEMP1.PERIOD,MEMB_NUM,MEMB_STATUS,
CASE WHEN ( LIFEPOLS>0) THEN 1 ELSE 2 END  AS GROUP_CD 
FROM 
(SELECT A.MO_ID,PERIOD, A.MEMB_NUM MEMB_NUM, A. MEMB_STATUS MEMB_STATUS,  
COALESCE(AUTOPOLS,0) AUTOPOLS ,COALESCE(HOMEPOLS,0) HOMEPOLS ,COALESCE(MANHOMEPOLS,0) MANHOMEPOLS ,
COALESCE(FARMPOLS,0) FARMPOLS ,COALESCE(FIREPOLS,0) FIREPOLS ,COALESCE(SMLNPOLS,0) SMLNPOLS,COALESCE(PORTPOLS,0) PORTPOLS ,
COALESCE(RHPOLS,0) RHPOLS ,COALESCE(LOANS,0 ) LOANS,COALESCE(ASICPOLS,0) ASICPOLS ,COALESCE(LIFEPOLS,0 ) LIFEPOLS,
COALESCE(FGMPOLS ,0) FGMPOLS 
FROM MEMB_FLOW_TEMP A
LEFT OUTER JOIN
MEMB_BUCKET_TEMP B
ON A.MEMB_NUM=B.MEMB_NUM 
AND A.MO_ID = B.MO_ID )TEMP1 WHERE GROUP_CD = 1 
)TEMP2 GROUP BY 1,2,3,4,5,7,8
UNION
SELECT 1.14 GROUP_CD,''Membership'' LOB_TYPE,CAST(''DB_T_STAG_MEMBXREF_PROD.LIFE Customers''  AS VARCHAR(100)) IND_TYPE, 
A.MO_ID MO_ID,CASE WHEN COALESCE(A.ST_CD,B.ST_CD) IN (''MS'',''GA'') THEN  COALESCE(A.ST_CD,B.ST_CD) ELSE ''OTHERS'' END SALES_ST_CD,
COUNT(*) CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM DB_T_CORE_AN_PROD.MEMB_CUST   A 
LEFT OUTER JOIN  CUST_ADDRESS B
ON A.MO_ID = B.MO_ID 
AND A.MEMBER_NUMBER = B.MEMBER_NUMBER
WHERE A.MEMBER_TYPE = ''CST''
AND LIFE >0 AND A.MO_ID = :WF_MONTH_ID
GROUP BY 1,2,3,4,5,7,8
UNION
SELECT 5.04 GROUP_CD,''Other'' LOB_TYPE,CAST(''P&C Premium''  AS VARCHAR(100)) IND_TYPE, 
MO_ID, CASE WHEN STATE IN (''AL'',''GA'',''MS'') THEN STATE ELSE ''OTHERS'' END ST_CD,
SUM(TOTAL_PREM) CNT,0 YTD_CNT,''N'' BACKFILL_IND  FROM  (
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(CAST(HO_TOT_PREM AS DECIMAL(11,2))) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.HOMEPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(MH_UNP_TOTAL_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.MANHOMEPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(SMLN_TOT_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.SMLNPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(FGM_TOT_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.FGMPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(PORT_TOT_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.PORTPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(RFD_TOT_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.FARMPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID, PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(FI_TOT_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.FIREPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,EX_MEMBER_NUM AS MEMBER_NUM,	
TRIM(EX_STATE ) AS STATE,
SUM(TOT_PRM_AMT)AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.EXCEED_POL_LIST A JOIN 		
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B  ON 
B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT
LEFT OUTER JOIN DB_T_STAG_MEMBXREF_PROD.POL_VEH_LIST
ON EX_POL_NUM=POL_NBR
AND EX_MEMBER_NUM= CLIENT_REF_NBR
WHERE 	(CASE WHEN POL_NBR IS NOT NULL THEN ''1'' ELSE ''5'' END) IN (''1'') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(0) AS  TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.ASICPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT  MO_ID,INSURED_MEMBER_NUM AS MEMBER_NUM,	
INSURED_STATE_CD AS STATE,
SUM(0) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT  AND INSURED_MEMBER_NUM <> '' '' 
AND POL_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT  MO_ID, LF_MEMBERSHIP AS MEMBER_NUM,		
CASE WHEN LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3 = '''' THEN NULL ELSE  
SUBSTR(
TRIM(SUBSTR(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3,1,length(TRIM(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3))-5)),
length(TRIM(SUBSTR(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3,1,length(TRIM(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3))-5)))-1,
length(TRIM(SUBSTR(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3,1,length(TRIM(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3))-5)))
) END STATE,
SUM(LF_ANNUAL_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.LIFEPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT AND  LF_MEMBERSHIP <> '' '' 
AND LF_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3	 ) TEMP GROUP BY 1,2,3,4,5,7,8
UNION
SELECT 5.05 GROUP_CD,''Other'' LOB_TYPE,CAST(''P&C Customers''  AS VARCHAR(100)) IND_TYPE, 
MO_ID, CASE WHEN STATE IN (''AL'',''GA'',''MS'') THEN STATE ELSE ''OTHERS'' END ST_CD,
CAST(COUNT(DISTINCT MEMBER_NUM) AS DECIMAL(21,3)) CNT,0 YTD_CNT,''N'' BACKFILL_IND  FROM  (
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(CAST(HO_TOT_PREM AS DECIMAL(11,2))) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.HOMEPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(MH_UNP_TOTAL_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.MANHOMEPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(SMLN_TOT_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.SMLNPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(FGM_TOT_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.FGMPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(PORT_TOT_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.PORTPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(RFD_TOT_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.FARMPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID, PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(FI_TOT_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.FIREPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,EX_MEMBER_NUM AS MEMBER_NUM,	
TRIM(EX_STATE ) AS STATE,
SUM(TOT_PRM_AMT)AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.EXCEED_POL_LIST A JOIN 		
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B  ON 
B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT
LEFT OUTER JOIN DB_T_STAG_MEMBXREF_PROD.POL_VEH_LIST
ON EX_POL_NUM=POL_NBR
AND EX_MEMBER_NUM= CLIENT_REF_NBR
WHERE 	(CASE WHEN POL_NBR IS NOT NULL THEN ''1'' ELSE ''5'' END) IN (''1'') 
GROUP BY 1,2,3
UNION
SELECT MO_ID,PC_MEMBER_NUMBER AS MEMBER_NUM,	
CASE WHEN LENGTH(TRIM(PC_CITYST)) > 2 THEN SUBSTR(TRIM(PC_CITYST),LENGTH(TRIM(PC_CITYST))-1,2) END AS STATE,
SUM(0) AS  TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.ASICPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT 
AND PC_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT  MO_ID,INSURED_MEMBER_NUM AS MEMBER_NUM,	
INSURED_STATE_CD AS STATE,
SUM(0) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT  AND INSURED_MEMBER_NUM <> '' '' 
AND POL_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3
UNION
SELECT  MO_ID, LF_MEMBERSHIP AS MEMBER_NUM,		
CASE WHEN LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3 = '''' THEN NULL ELSE  
SUBSTR(
TRIM(SUBSTR(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3,1,length(TRIM(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3))-5)),
length(TRIM(SUBSTR(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3,1,length(TRIM(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3))-5)))-1,
length(TRIM(SUBSTR(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3,1,length(TRIM(LF_ADDRESS_1||LF_ADDRESS_2||LF_ADDRESS_3))-5)))
) END STATE,
SUM(LF_ANNUAL_PREM) AS TOTAL_PREM FROM DB_T_CORE_MEMBXREF_PROD.LIFEPOLS A ,
(SELECT DISTINCT MO_ID,MO_DESC FROM DB_T_SHRD_PROD.DT_DIM WHERE MO_ID = :WF_MONTH_ID ) B
WHERE B.MO_DESC BETWEEN A.CHG_EFF_DT AND A.CHG_EXP_DT AND  LF_MEMBERSHIP <> '' '' 
AND LF_STATUS IN (''1'',''2'',''3'',''4'',''01'',''02'',''03'',''04'',''22'',''31'',''32'',''41'',''42'',''43'',''44'',''45'','' '') 
GROUP BY 1,2,3	 ) TEMP GROUP BY 1,2,3,4,5,7,8

) SRC
)
);

-- Component AGG_ENTERPRISE_METRICS_MTHLY, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE AGG_ENTERPRISE_METRICS_MTHLY AS
(
SELECT
SQ_AGG_ENTERPRISE_METRICS_MTHLY.GROUP_CD as GROUP_CD,
SQ_AGG_ENTERPRISE_METRICS_MTHLY.LOB_TYPE as LOB_TYPE,
SQ_AGG_ENTERPRISE_METRICS_MTHLY.IND_TYPE as IND_TYPE,
SQ_AGG_ENTERPRISE_METRICS_MTHLY.MO_ID as MO_ID,
SQ_AGG_ENTERPRISE_METRICS_MTHLY.SALES_ST_CD as SALES_ST_CD,
SQ_AGG_ENTERPRISE_METRICS_MTHLY.MTD_CNT as MTD_CNT,
SQ_AGG_ENTERPRISE_METRICS_MTHLY.YTD_CNT as YTD_CNT,
SQ_AGG_ENTERPRISE_METRICS_MTHLY.BACKFILL_IND as BACKFILL_IND,
SQ_AGG_ENTERPRISE_METRICS_MTHLY.source_record_id
FROM
SQ_AGG_ENTERPRISE_METRICS_MTHLY
);


-- Component AGG_ENTERPRISE_METRICS_MTHLY_MAIN, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE AGG_ENTERPRISE_METRICS_MTHLY_MAIN AS
(
SELECT
*
FROM
AGG_ENTERPRISE_METRICS_MTHLY
);


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_AGG_ENTERPRISE_METRICS_MTHLY1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_ENTERPRISE_METRICS_MTHLY1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as GROUP_CD,
$2 as LOB_TYPE,
$3 as IND_TYPE,
$4 as MO_ID,
$5 as SALES_ST_CD,
$6 as MTD_CNT,
$7 as YTD_CNT,
$8 as BACKFILL_IND,
$9 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 1.06 GROUP_CD,''Membership'' LOB_TYPE,CAST(''Farm Only Customers''  AS VARCHAR(100)) IND_TYPE, 
A.MO_ID MO_ID,A.ST_CD SALES_ST_CD,
0 CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM (SELECT DISTINCT MO_ID,ST_CD FROM DB_T_SHRD_PROD.DT_DIM,DB_T_SHRD_PROD.STATE_LOOKUP 
WHERE MO_ID BETWEEN :WF_MONTH_ID AND :WF_MONTH_ID  AND  ST_CD IN (''GA'',''MS'') ) A 
LEFT OUTER JOIN 
(SELECT * FROM DB_T_CORE_PROD.AGG_ENTERPRISE_METRICS_MTHLY  WHERE GROUP_CD = 1.06 AND IND_TYPE = ''Farm Only Customers'' 
AND MO_ID = :WF_MONTH_ID) B 
ON A.MO_ID = B.MO_ID AND A.ST_CD = B.SALES_ST_CD 
WHERE B.IND_TYPE IS NULL
) SRC
)
);


-- Component AGG_ENTERPRISE_METRICS_MTHLY3, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE AGG_ENTERPRISE_METRICS_MTHLY3 AS
(
SELECT
SQ_AGG_ENTERPRISE_METRICS_MTHLY1.GROUP_CD as GROUP_CD,
SQ_AGG_ENTERPRISE_METRICS_MTHLY1.LOB_TYPE as LOB_TYPE,
SQ_AGG_ENTERPRISE_METRICS_MTHLY1.IND_TYPE as IND_TYPE,
SQ_AGG_ENTERPRISE_METRICS_MTHLY1.MO_ID as MO_ID,
SQ_AGG_ENTERPRISE_METRICS_MTHLY1.SALES_ST_CD as SALES_ST_CD,
SQ_AGG_ENTERPRISE_METRICS_MTHLY1.MTD_CNT as MTD_CNT,
SQ_AGG_ENTERPRISE_METRICS_MTHLY1.YTD_CNT as YTD_CNT,
SQ_AGG_ENTERPRISE_METRICS_MTHLY1.BACKFILL_IND as BACKFILL_IND,
SQ_AGG_ENTERPRISE_METRICS_MTHLY1.source_record_id
FROM
SQ_AGG_ENTERPRISE_METRICS_MTHLY1
);


-- Component AGG_ENTERPRISE_METRICS_MTHLY_ins1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE AGG_ENTERPRISE_METRICS_MTHLY_ins1 AS
(
SELECT
*
FROM
AGG_ENTERPRISE_METRICS_MTHLY3
);


-- PIPELINE END FOR 2

-- PIPELINE START FOR 3

-- Component SQ_AGG_ENTERPRISE_METRICS_MTHLY2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_ENTERPRISE_METRICS_MTHLY2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as GROUP_CD,
$2 as LOB_TYPE,
$3 as IND_TYPE,
$4 as MO_ID,
$5 as SALES_ST_CD,
$6 as MTD_CNT,
$7 as YTD_CNT,
$8 as BACKFILL_IND,
$9 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 1.09 GROUP_CD,''Membership'' LOB_TYPE,CAST(''Health Only Customers''  AS VARCHAR(100)) IND_TYPE, 
A.MO_ID MO_ID,A.ST_CD SALES_ST_CD,
0 CNT ,0 YTD_CNT,''N'' BACKFILL_IND 
FROM (SELECT DISTINCT MO_ID,ST_CD FROM DB_T_SHRD_PROD.DT_DIM,DB_T_SHRD_PROD.STATE_LOOKUP 
WHERE MO_ID BETWEEN :WF_MONTH_ID AND :WF_MONTH_ID  AND  ST_CD IN (''GA'',''MS'') ) A 
LEFT OUTER JOIN 
(SELECT * FROM DB_T_CORE_PROD.AGG_ENTERPRISE_METRICS_MTHLY  WHERE GROUP_CD = 1.06 AND IND_TYPE = ''Health Only Customers'' 
AND MO_ID = :WF_MONTH_ID) B 
ON A.MO_ID = B.MO_ID AND A.ST_CD = B.SALES_ST_CD 
WHERE B.IND_TYPE IS NULL
) SRC
)
);


-- Component AGG_ENTERPRISE_METRICS_MTHLY4, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE AGG_ENTERPRISE_METRICS_MTHLY4 AS
(
SELECT
SQ_AGG_ENTERPRISE_METRICS_MTHLY2.GROUP_CD as GROUP_CD,
SQ_AGG_ENTERPRISE_METRICS_MTHLY2.LOB_TYPE as LOB_TYPE,
SQ_AGG_ENTERPRISE_METRICS_MTHLY2.IND_TYPE as IND_TYPE,
SQ_AGG_ENTERPRISE_METRICS_MTHLY2.MO_ID as MO_ID,
SQ_AGG_ENTERPRISE_METRICS_MTHLY2.SALES_ST_CD as SALES_ST_CD,
SQ_AGG_ENTERPRISE_METRICS_MTHLY2.MTD_CNT as MTD_CNT,
SQ_AGG_ENTERPRISE_METRICS_MTHLY2.YTD_CNT as YTD_CNT,
SQ_AGG_ENTERPRISE_METRICS_MTHLY2.BACKFILL_IND as BACKFILL_IND,
SQ_AGG_ENTERPRISE_METRICS_MTHLY2.source_record_id
FROM
SQ_AGG_ENTERPRISE_METRICS_MTHLY2
);


-- Component AGG_ENTERPRISE_METRICS_MTHLY_INS2, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE AGG_ENTERPRISE_METRICS_MTHLY_INS2 AS
(
SELECT
*
FROM
AGG_ENTERPRISE_METRICS_MTHLY4
);


-- PIPELINE END FOR 3

-- PIPELINE START FOR 4

-- Component SQ_AGG_ENTERPRISE_METRICS_MTHLY3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_ENTERPRISE_METRICS_MTHLY3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as GROUP_CD,
$2 as LOB_TYPE,
$3 as IND_TYPE,
$4 as MO_ID,
$5 as SALES_ST_CD,
$6 as MTD_CNT,
$7 as YTD_CNT,
$8 as BACKFILL_IND,
$9 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT GROUP_CD,LOB_TYPE,IND_TYPE,:WF_MONTH_ID,SALES_ST_CD,
0 AS MTD_CNT,0 AS YTD_CNT,''Y'' AS BACKFILL_IND
FROM DB_T_CORE_PROD.AGG_ENTERPRISE_METRICS_MTHLY A INNER JOIN   (SELECT DISTINCT  MO_ID,QTR_ID,YR_ID FROM DB_T_SHRD_PROD.DT_DIM) B
ON B.MO_ID = :WF_MONTH_ID  WHERE (A.MO_ID =  :WF_MONTH_ID OR A.MO_ID = (-1+(:WF_MONTH_ID))) 
QUALIFY SUM(1) OVER (PARTITION BY GROUP_CD,LOB_TYPE,IND_TYPE,SALES_ST_CD 
ORDER BY A.MO_ID DESC ROWS 1 PRECEDING )  = 1 AND A.MO_ID = (:WF_MONTH_ID-1)
) SRC
)
);


-- Component AGG_ENTERPRISE_METRICS_MTHLY5, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE AGG_ENTERPRISE_METRICS_MTHLY5 AS
(
SELECT
SQ_AGG_ENTERPRISE_METRICS_MTHLY3.GROUP_CD as GROUP_CD,
SQ_AGG_ENTERPRISE_METRICS_MTHLY3.LOB_TYPE as LOB_TYPE,
SQ_AGG_ENTERPRISE_METRICS_MTHLY3.IND_TYPE as IND_TYPE,
SQ_AGG_ENTERPRISE_METRICS_MTHLY3.MO_ID as MO_ID,
SQ_AGG_ENTERPRISE_METRICS_MTHLY3.SALES_ST_CD as SALES_ST_CD,
SQ_AGG_ENTERPRISE_METRICS_MTHLY3.MTD_CNT as MTD_CNT,
SQ_AGG_ENTERPRISE_METRICS_MTHLY3.YTD_CNT as YTD_CNT,
SQ_AGG_ENTERPRISE_METRICS_MTHLY3.BACKFILL_IND as BACKFILL_IND,
SQ_AGG_ENTERPRISE_METRICS_MTHLY3.source_record_id
FROM
SQ_AGG_ENTERPRISE_METRICS_MTHLY3
);


-- Component AGG_ENTERPRISE_METRICS_MTHLY_INS3, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE AGG_ENTERPRISE_METRICS_MTHLY_INS3 AS
(
SELECT
*
FROM
AGG_ENTERPRISE_METRICS_MTHLY5
);


-- PIPELINE END FOR 4
-- Component AGG_ENTERPRISE_METRICS_MTHLY_INS3, Type Post SQL 

MERGE INTO DB_T_CORE_PROD.AGG_ENTERPRISE_METRICS_MTHLY AS A USING (
  SELECT
    CURR.GROUP_CD,
    CURR.LOB_TYPE,
    CURR.IND_TYPE,
    CURR.MO_ID,
    CURR.SALES_ST_CD,
    CURR.MTD_CNT,
    CASE
      WHEN CURR.GROUP_CD IN (
        1.02,
        2.03,
        2.04,
        2.05,
        2.16,
        2.17,
        2.19,
        3.02,
        3.03,
        3.04,
        3.07,
        5.01,
        5.02,
        5.04
      ) THEN COALESCE(PREV.YTD_CNT, 0)
      ELSE 0
    END + CURR.MTD_CNT AS YTD_CNT_NEW
  FROM
    DB_T_CORE_PROD.AGG_ENTERPRISE_METRICS_MTHLY AS CURR
    LEFT OUTER JOIN DB_T_CORE_PROD.AGG_ENTERPRISE_METRICS_MTHLY AS PREV ON CURR.GROUP_CD = PREV.GROUP_CD
    AND CURR.LOB_TYPE = PREV.LOB_TYPE
    AND CURR.IND_TYPE = PREV.IND_TYPE
    AND CURR.SALES_ST_CD = PREV.SALES_ST_CD
    AND CURR.MO_ID / 100 = PREV.MO_ID / 100
    AND CURR.MO_ID = PREV.MO_ID + 1
  WHERE
    CURR.MO_ID = :WF_MONTH_ID
) AS UPD_AGG ON A.GROUP_CD = UPD_AGG.GROUP_CD
AND A.LOB_TYPE = UPD_AGG.LOB_TYPE
AND A.IND_TYPE = UPD_AGG.IND_TYPE
AND A.MO_ID = UPD_AGG.MO_ID
AND A.SALES_ST_CD = UPD_AGG.SALES_ST_CD
AND A.MO_ID = :WF_MONTH_ID
WHEN MATCHED THEN
UPDATE
SET
  YTD_CNT = UPD_AGG.YTD_CNT_NEW;

UPDATE DB_T_CTRL_PROD.ECTL_PRGM_PARAM SET ECTL_PARAM_VALUE = ''N'' , ECTL_ORIG_INS_TS = CURRENT_TIMESTAMP 
WHERE ECTL_PARAM_DESC = ''ENTERPRISE METRICS MTHLY LOAD STATUS'' 
AND ECTL_PARAM_ID = 15;


END; ';