-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_AON_BENFIELD_FEED_FILE("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
  p_MOID varchar;
  p_prcs_id_fltr varchar;
  PMWorkflowName varchar;
  PMSessionName varchar;
BEGIN
   
    set p_MOID:=''1'';
    set p_prcs_id_fltr:=''abc'';
    set PMWorkflowName:=''sample'';
    set PMSessionName:=''s_m_aon_benfield_feed_file'';

-- Component SQ_AON_BENFIELD_PRPTY_FEED, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AON_BENFIELD_PRPTY_FEED AS
(
SELECT /* adding column aliases to ensure properdownstream column references */
$1 as MO_ID,
$2 as PLCY_NBR,
$3 as PLCY_TYPE,
$4 as PLCY_STATUS,
$5 as PLCY_INCPT_DT,
$6 as EXPIRED_DT,
$7 as AGENT_NBR,
$8 as COMPANY_CODE,
$9 as SALE_SERVICE_CENTER,
$10 as PROP_TERR,
$11 as PLCY_LIMIT,
$12 as BUILDING_LIMIT,
$13 as OTHER_STRUCT_LIMIT,
$14 as LOSS_USE_LIMIT,
$15 as CONTENTS_LIMIT,
$16 as PLCY_DED,
$17 as INSRNC_VALUE,
$18 as CNSTRNC_CLASS,
$19 as CONTENTS_GRADE,
$20 as LOB,
$21 as OCCPNCY_TYPE,
$22 as EQ_ENDOR_DED,
$23 as EXWND_ENDRSMT_DESC,
$24 as HURRICANE_ENDOR_DED,
$25 as WIND_HAIL_ENDOR_DED,
$26 as NBR_STORIES,
$27 as FOUNDATION_TYPE,
$28 as BCEG_INFO,
$29 as SQ_FOOTAGE,
$30 as ROOF_YEAR,
$31 as YR_BUILT,
$32 as COMP_DED,
$33 as COMP_DESC,
$34 as PA_SYM_CD,
$35 as MAXIMUM,
$36 as MEAN,
$37 as MINIMUM,
$38 as VIN,
$39 as VEH_MODEL_YR,
$40 as VEH_TYPE_DESC,
$41 as APP_SYM,
$42 as ANNUAL_PREMIUM,
$43 as APPEND_PREM,
$44 as PROP_ADDR_LOC,
$45 as ADDR_1,
$46 as CITY,
$47 as STATE,
$48 as RSK_ST_CD,
$49 as CNTY_CD,
$50 as ZIPCODE,
$51 as IBHS_LEVEL,
$52 as BOP_CAUSE_OF_LOSS_CVGE,
$53 as FEED_TYPE,
$54 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
/* Property Query */
SELECT DISTINCT 

MO_ID,

PLCY_NUM,

PLCY_TYPE,

PLCY_STS,

PLCY_INCPTN_DT,

PLCY_EXPRD_DT,

AGNT_CD,

CO_CD,

SL_SRVC_CTR,

PRPTY_TERR,

PLCY_LMT,

BLDG_LMT,

OTHR_STRC_LMT,

LOSS_USE_LMT,

CNTNTS_LMT,

PLCY_DEDCTB,

INSRNC_VAL,

CNSTRCTN_CLAS,

CNTNTS_GRADE,

LOB,

OCCPY_TYPE,

EAQK_ENDRSMT_DEDCTB,

EXWND_ENDRSMT_DESC,

HURCN_ENDRSMT_DEDCTB,

WIND_HAIL_ENDRSMT_DEDCTB,

NBR_OF_STORIES,

FNDTN_TYPE, 
/*  Put back in column as part of EIM- 33807 */
CAST(NULL AS VARCHAR(50)) BCEG_INFO, 
/*  Put back in column as part of EIM- 33807 */
SQ_FOOTAGE,

ROOF_YEAR,

YR_BUILT,

CAST(NULL  AS DECIMAL(18,4)) CMP_DED,

CAST(NULL AS VARCHAR(3)) CMP_COV_IND,

CAST(NULL AS INTEGER) PA_SYM_CD,

CAST(NULL  AS DECIMAL(18,4)) MAXI,

CAST(NULL  AS DECIMAL(18,4)) MEAN,

CAST(NULL  AS DECIMAL(18,4)) MINI,

CAST(NULL AS VARCHAR(50)) UNIT_REF_NBR,

CAST(NULL AS VARCHAR(50)) VEH_MODEL_YR,

CAST(NULL AS VARCHAR(50)) VEH_TYPE_DESC,

CAST(NULL AS VARCHAR(50)) APP_SYM,

CASE WHEN ANNUAL_PREM IS NULL THEN 0 ELSE ANNUAL_PREM END AS ANNUAL_PREM,

CAST(NULL  AS DECIMAL(18,4)) APPEND_PREM,

PRPTY_ADDR_LOC,

ADDR_1,

CITY,

STATE,

CAST(NULL AS VARCHAR(100)) RSK_ST_CD,

CNTY_CD,

ZIPCD,

CAST(IBHS_LEVEL AS VARCHAR(100)) IBHS_LEVEL, 

CAST(NULL AS VARCHAR(50)) BOP_CAUSE_OF_LOSS_CVGE,

CAST(''PROPERTY'' AS VARCHAR(25)) LOB_PROPERTY

FROM DB_T_PROD_WRK.AON_BENFIELD_PRPTY_FEED

where MO_ID=:p_MOID

--:p_prcs_id_fltr



UNION ALL



/*  Auto Query */
SELECT 

MO_ID,

PLCY_NUM,

PLCY_TYPE,

CAST(NULL AS VARCHAR(50)) PLCY_STATUS,

NULL PLCY_INCPT_DT,

NULL EXPIRED_DT,

CAST(NULL as VARCHAR(12)) AGENT_NBR,

CO_CD COMPANY_CODE,

CAST(NULL AS VARCHAR(50)) SALE_SERVICE_CENTER,

CAST(NULL AS VARCHAR(100)) PROP_TERR,

CAST(NULL  AS DECIMAL(18,4)) PLCY_LIMIT,

CAST(NULL  AS DECIMAL(18,4)) BUILDING_LIMIT,

CAST(NULL  AS DECIMAL(18,4)) OTHER_STRUCT_LIMIT,

CAST(NULL  AS DECIMAL(18,4)) LOSS_USE_LIMIT,

CAST(NULL  AS DECIMAL(18,4)) CONTENTS_LIMIT,

CAST(NULL  AS DECIMAL(18,4)) PLCY_DED,

''100%'' INSRNC_VALUE,

CAST(NULL AS VARCHAR(250)) CNSTRNC_CLASS,

CAST(NULL AS INTEGER) CONTENTS_GRADE,

LOB,

CAST(NULL AS VARCHAR(50)) OCCPNCY_TYPE,

CAST(NULL AS VARCHAR(10)) EQ_ENDOR_DED,

CAST(NULL AS VARCHAR(15))EXWND_ENDRSMT_DESC,

CAST(NULL AS VARCHAR(10)) HURRICANE_ENDOR_DED,

CAST(NULL AS VARCHAR(10)) WIND_HAIL_ENDOR_DED,

CAST(NULL AS VARCHAR(20)) NBR_STORIES,
/* EIM-50235 */
CAST(NULL AS VARCHAR(100)) FOUNDATION_TYPE, 
/*  Put back in this column as part of EIM- 33807 */
CAST(NULL AS VARCHAR(50)) BCEG_INFO, 
/*  Put back in as part of EIM- 33807 */
CAST(NULL AS DECIMAL(18,4)) SQ_FOOTAGE,

CAST(NULL AS VARCHAR(100)) ROOF_YEAR,

CAST(NULL AS VARCHAR(100)) YR_BUILT,

CMPRN_DEDCTB,

CMPRN_CVGE_IND,

PA_SYM_CD,

MAXM_VAL,

MEAN_VAL,

MIN_VAL,

UNIT_REF_CD,

VEH_MODL_YR,

VEH_TYPE_DESC,

APP_SYM,

CASE WHEN ANNUAL_PREM IS NULL THEN 0 ELSE ANNUAL_PREM END AS ANNUAL_PREM,

APPEND_PREM,

CAST(NULL AS VARCHAR(1000)) PROP_ADDR_LOC,

ADDR_1,

CITY,

STATE,

RSK_ST_CD,

CAST(NULL AS VARCHAR(100)) CNTY_CD,

ZIPCD,

CAST(NULL AS VARCHAR(100)) IBHS_LEVEL,  

CAST(NULL AS VARCHAR(50)) BOP_CAUSE_OF_LOSS_CVGE,

CAST(''AUTO'' AS VARCHAR(25)) LOB_AUTO

FROM DB_T_PROD_WRK.AON_BENFIELD_AUTO_FEED

where MO_ID=:p_MOID 

--:p_prcs_id_fltr



UNION ALL



/* BOP/Church Query */
SELECT DISTINCT 

MO_ID,

PLCY_NUM,

PLCY_TYPE,

PLCY_STS,

PLCY_INCPTN_DT,

PLCY_EXPRD_DT,

AGNT_CD,

CO_CD,

SL_SRVC_CTR,

PRPTY_TERR,

PLCY_LMT,

BLDG_LMT,

CAST(NULL  AS DECIMAL(18,4)) OTHER_STRUCT_LIMIT,

CAST(NULL  AS DECIMAL(18,4)) LOSS_USE_LIMIT,

CNTNTS_LMT,

PLCY_DEDCTB,

INSRNC_VAL,

CNSTRCTN_CLAS,

CNTNTS_GRADE,

LOB,

OCCPY_TYPE,

CAST(NULL AS VARCHAR(10)) EQ_ENDOR_DED,

EXWND_ENDRSMT_DESC,

CAST(NULL AS VARCHAR(10)) HURRICANE_ENDOR_DED,

WIND_HAIL_ENDRSMT_DEDCTB,

NBR_OF_STORIES,

FNDTN_TYPE,  /*  Put back in this column as part of EIM- 33807 */
BCEG_INFO,  /*  Put back in this column as part of EIM- 33807 */
SQ_FOOTAGE,

ROOF_YEAR,

YR_BUILT,

CAST(NULL  AS DECIMAL(18,4)) CMP_DED,

CAST(NULL AS VARCHAR(3)) CMP_COV_IND,

CAST(NULL AS INTEGER) PA_SYM_CD,

CAST(NULL  AS DECIMAL(18,4)) MAXI,

CAST(NULL  AS DECIMAL(18,4)) MEAN,

CAST(NULL  AS DECIMAL(18,4)) MINI,

CAST(NULL AS VARCHAR(50)) UNIT_REF_NBR,

CAST(NULL AS VARCHAR(50)) VEH_MODEL_YR,

CAST(NULL AS VARCHAR(50)) VEH_TYPE_DESC,

CAST(NULL AS VARCHAR(50)) APP_SYM,

CASE WHEN ANNUAL_PREM IS NULL THEN 0 ELSE ANNUAL_PREM END AS ANNUAL_PREM,

CAST(NULL  AS DECIMAL(18,4)) APPEND_PREM,

CAST(NULL AS VARCHAR(1000)) PROP_ADDR_LOC,

ADDR_1,

CITY,

STATE,

CAST(NULL AS VARCHAR(100)) RSK_ST_CD,

CNTY_CD,

ZIPCD,

CAST(IBHS_LEVEL AS VARCHAR(100)) IBHS_LEVEL,  

BOP_CAUSE_OF_LOSS_CVGE,

CAST(''BUSINESSOWNERS'' AS VARCHAR(25)) LOB_BOP

FROM DB_T_PROD_WRK.AON_BENFIELD_BOP_CHURCH_FEED

where MO_ID=:p_MOID 

--:p_prcs_id_fltr



UNION ALL



/* FARM Query */
SELECT DISTINCT 

MO_ID,

PLCY_NUM,

PLCY_TYPE,

''INFORCE'' PLCY_STS,

PLCY_INCPTN_DT,

PLCY_EXPRD_DT,

AGNT_CD,

CO_CD,

SL_SRVC_CTR,

PRPTY_TERR,

PLCY_LMT,

BLDG_LMT,

OTH_STRCTR_LMT as OTHER_STRUCT_LIMIT,

LOSS_LMT as LOSS_USE_LIMIT,

CNTNTS_LMT,

PLCY_DEDCTB,

INSRNC_VAL,

CNSTRCTN_CLAS,

CAST(NULL AS INTEGER) CNTNTS_GRADE,

LOB,

OCCPY_TYPE,

EQ_END as EQ_ENDOR_DED,

CAST(NULL AS VARCHAR(10)) EXWND_ENDRSMT_DESC,

CAST(NULL AS VARCHAR(10)) HURRICANE_ENDOR_DED,

CAST(NULL AS VARCHAR(10)) WIND_HAIL_ENDRSMT_DEDCTB,

NBR_OF_STORIES,

FNDTN_TYPE,  /*  Put back in this column as part of EIM- 33807 */
CAST(NULL AS VARCHAR(10)) BCEG_INFO,  /*  Put back in this column as part of EIM- 33807 */
SQ_FOOTAGE,

ROOF_YEAR,

YR_BUILT,

CAST(NULL  AS DECIMAL(18,4)) CMP_DED,

CAST(NULL AS VARCHAR(3)) CMP_COV_IND,

CAST(NULL AS INTEGER) PA_SYM_CD,

CAST(NULL  AS DECIMAL(18,4)) MAXI,

CAST(NULL  AS DECIMAL(18,4)) MEAN,

CAST(NULL  AS DECIMAL(18,4)) MINI,

CAST(NULL AS VARCHAR(50)) UNIT_REF_NBR,

CAST(NULL AS VARCHAR(50)) VEH_MODEL_YR,

CAST(NULL AS VARCHAR(50)) VEH_TYPE_DESC,

CAST(NULL AS VARCHAR(50)) APP_SYM,

CASE WHEN ANNUAL_PREM IS NULL THEN 0 ELSE ANNUAL_PREM END AS ANNUAL_PREM,

CAST(NULL  AS DECIMAL(18,4)) APPEND_PREM,

CAST(NULL AS VARCHAR(1000)) PROP_ADDR_LOC,

ADDR_1,

CITY,

STATE,

CAST(NULL AS VARCHAR(100)) RSK_ST_CD,

CNTY_CD,

ZIPCD,

CAST(NULL AS VARCHAR(10)) IBHS_LEVEL,   

CAST(NULL AS VARCHAR(50)) BOP_CAUSE_OF_LOSS_CVGE,

CAST(''Farmowners'' AS VARCHAR(25)) LOB_BOP

FROM DB_T_PROD_WRK.AON_BENFIELD_FARM_FEED

where MO_ID=:p_MOID 

--:p_prcs_id_fltr
) SRC
)
);


-- Component exp_HOLD_BENFIELD_PRPTY, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_HOLD_BENFIELD_PRPTY AS
(
SELECT
SQ_AON_BENFIELD_PRPTY_FEED.MO_ID as MO_ID,
SQ_AON_BENFIELD_PRPTY_FEED.PLCY_NBR as PLCY_NBR,
SQ_AON_BENFIELD_PRPTY_FEED.PLCY_TYPE as PLCY_TYPE,
SQ_AON_BENFIELD_PRPTY_FEED.PLCY_INCPT_DT as PLCY_INCPT_DT,
SQ_AON_BENFIELD_PRPTY_FEED.EXPIRED_DT as EXPIRED_DT,
SQ_AON_BENFIELD_PRPTY_FEED.AGENT_NBR as AGENT_NBR,
SQ_AON_BENFIELD_PRPTY_FEED.COMPANY_CODE as COMPANY_CODE,
SQ_AON_BENFIELD_PRPTY_FEED.SALE_SERVICE_CENTER as SALE_SERVICE_CENTER,
SQ_AON_BENFIELD_PRPTY_FEED.PROP_TERR as PROP_TERR,
SQ_AON_BENFIELD_PRPTY_FEED.PLCY_LIMIT as PLCY_LIMIT,
SQ_AON_BENFIELD_PRPTY_FEED.BUILDING_LIMIT as BUILDING_LIMIT,
SQ_AON_BENFIELD_PRPTY_FEED.OTHER_STRUCT_LIMIT as OTHER_STRUCT_LIMIT,
SQ_AON_BENFIELD_PRPTY_FEED.LOSS_USE_LIMIT as LOSS_USE_LIMIT,
SQ_AON_BENFIELD_PRPTY_FEED.CONTENTS_LIMIT as CONTENTS_LIMIT,
SQ_AON_BENFIELD_PRPTY_FEED.PLCY_DED as PLCY_DED,
SQ_AON_BENFIELD_PRPTY_FEED.INSRNC_VALUE as INSRNC_VALUE,
SQ_AON_BENFIELD_PRPTY_FEED.CNSTRNC_CLASS as CNSTRNC_CLASS,
SQ_AON_BENFIELD_PRPTY_FEED.CONTENTS_GRADE as CONTENTS_GRADE,
SQ_AON_BENFIELD_PRPTY_FEED.LOB as LOB,
SQ_AON_BENFIELD_PRPTY_FEED.OCCPNCY_TYPE as OCCPNCY_TYPE,
SQ_AON_BENFIELD_PRPTY_FEED.EQ_ENDOR_DED as EQ_ENDOR_DED,
SQ_AON_BENFIELD_PRPTY_FEED.EXWND_ENDRSMT_DESC as EXWND_ENDOR_DESC,
SQ_AON_BENFIELD_PRPTY_FEED.WIND_HAIL_ENDOR_DED as WIND_HAIL_ENDOR_DED,
SQ_AON_BENFIELD_PRPTY_FEED.HURRICANE_ENDOR_DED as HURRICANE_ENDOR_DED,
SQ_AON_BENFIELD_PRPTY_FEED.NBR_STORIES as NBR_STORIES,
SQ_AON_BENFIELD_PRPTY_FEED.FOUNDATION_TYPE as FOUNDATION_TYPE,
SQ_AON_BENFIELD_PRPTY_FEED.SQ_FOOTAGE as SQ_FOOTAGE,
SQ_AON_BENFIELD_PRPTY_FEED.ROOF_YEAR as ROOF_YEAR,
SQ_AON_BENFIELD_PRPTY_FEED.YR_BUILT as YR_BUILT,
SQ_AON_BENFIELD_PRPTY_FEED.COMP_DED as COMP_COV_DED,
SQ_AON_BENFIELD_PRPTY_FEED.COMP_DESC as CMP_COV_DESC,
SQ_AON_BENFIELD_PRPTY_FEED.PA_SYM_CD as PA_SYM_CD,
SQ_AON_BENFIELD_PRPTY_FEED.MAXIMUM as MAXIMUM,
SQ_AON_BENFIELD_PRPTY_FEED.MEAN as MEAN,
SQ_AON_BENFIELD_PRPTY_FEED.MINIMUM as MINIMUM,
SQ_AON_BENFIELD_PRPTY_FEED.VEH_MODEL_YR as VEH_MODEL_YR,
SQ_AON_BENFIELD_PRPTY_FEED.VEH_TYPE_DESC as VEH_TYPE_DESC,
SQ_AON_BENFIELD_PRPTY_FEED.ANNUAL_PREMIUM as ANNUAL_PREMIUM,
SQ_AON_BENFIELD_PRPTY_FEED.ADDR_1 as ADDR_1,
SQ_AON_BENFIELD_PRPTY_FEED.CITY as CITY,
SQ_AON_BENFIELD_PRPTY_FEED.STATE as STATE,
SQ_AON_BENFIELD_PRPTY_FEED.CNTY_CD as CNTY_CD,
SQ_AON_BENFIELD_PRPTY_FEED.ZIPCODE as ZIPCODE,
SQ_AON_BENFIELD_PRPTY_FEED.FEED_TYPE as FEED_TYPE,
CASE WHEN SQ_AON_BENFIELD_PRPTY_FEED.EQ_ENDOR_DED IS NULL or ltrim ( rtrim ( SQ_AON_BENFIELD_PRPTY_FEED.EQ_ENDOR_DED ) ) = '''' THEN ''No'' ELSE ''Yes'' END as EQ_ENDOR_IND,
SQ_AON_BENFIELD_PRPTY_FEED.IBHS_LEVEL as IBHS_LEVEL,
SQ_AON_BENFIELD_PRPTY_FEED.BCEG_INFO as BCEG_INFO,
SQ_AON_BENFIELD_PRPTY_FEED.BOP_CAUSE_OF_LOSS_CVGE as BOP_CAUSE_OF_LOSS_CVGE,
SQ_AON_BENFIELD_PRPTY_FEED.source_record_id
FROM
SQ_AON_BENFIELD_PRPTY_FEED
);


-- Component Aon_Benfield_Feed, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE Aon_Benfield_Feed AS
(
SELECT
exp_HOLD_BENFIELD_PRPTY.MO_ID as MonthId,
exp_HOLD_BENFIELD_PRPTY.COMPANY_CODE as CompanyCode,
exp_HOLD_BENFIELD_PRPTY.PLCY_NBR as PolicyNumber,
exp_HOLD_BENFIELD_PRPTY.ANNUAL_PREMIUM as AnnualPremium,
exp_HOLD_BENFIELD_PRPTY.LOB as LineofBusiness,
exp_HOLD_BENFIELD_PRPTY.PLCY_TYPE as PolicyType,
exp_HOLD_BENFIELD_PRPTY.PLCY_LIMIT as PolicyLimit,
exp_HOLD_BENFIELD_PRPTY.PLCY_INCPT_DT as PolicyInceptionDate,
exp_HOLD_BENFIELD_PRPTY.EXPIRED_DT as ExpiredDate,
exp_HOLD_BENFIELD_PRPTY.PLCY_DED as PolicyDeductible,
exp_HOLD_BENFIELD_PRPTY.EQ_ENDOR_DED as EQEndorsementDed,
exp_HOLD_BENFIELD_PRPTY.WIND_HAIL_ENDOR_DED as Wind_Windstorm_HailEndorsement,
exp_HOLD_BENFIELD_PRPTY.COMP_COV_DED as ComprehensiveCoverageDeductible,
exp_HOLD_BENFIELD_PRPTY.HURRICANE_ENDOR_DED as HurricaneEndorsementDed,
exp_HOLD_BENFIELD_PRPTY.PROP_TERR as PropertyTerritory,
exp_HOLD_BENFIELD_PRPTY.BUILDING_LIMIT as BuildingLimit,
exp_HOLD_BENFIELD_PRPTY.OTHER_STRUCT_LIMIT as OtherStructureLimit,
exp_HOLD_BENFIELD_PRPTY.CONTENTS_LIMIT as ContentsLimit,
exp_HOLD_BENFIELD_PRPTY.LOSS_USE_LIMIT as LossofUseLimit,
exp_HOLD_BENFIELD_PRPTY.INSRNC_VALUE as InsurancetoValue,
exp_HOLD_BENFIELD_PRPTY.STATE as State,
exp_HOLD_BENFIELD_PRPTY.ZIPCODE as Zipcode,
exp_HOLD_BENFIELD_PRPTY.CNSTRNC_CLASS as ConstructionClass,
exp_HOLD_BENFIELD_PRPTY.ADDR_1 as StreetAddress,
exp_HOLD_BENFIELD_PRPTY.CITY as City,
exp_HOLD_BENFIELD_PRPTY.CNTY_CD as CountyCode,
exp_HOLD_BENFIELD_PRPTY.NBR_STORIES as NumberofStories,
exp_HOLD_BENFIELD_PRPTY.YR_BUILT as YearBuilt,
exp_HOLD_BENFIELD_PRPTY.OCCPNCY_TYPE as OccupancyType,
exp_HOLD_BENFIELD_PRPTY.SQ_FOOTAGE as SquareFootage,
exp_HOLD_BENFIELD_PRPTY.PA_SYM_CD as PersonalAutoSymbolCode,
exp_HOLD_BENFIELD_PRPTY.MAXIMUM as Maximum,
exp_HOLD_BENFIELD_PRPTY.MEAN as Mean,
exp_HOLD_BENFIELD_PRPTY.MINIMUM as Minimum,
exp_HOLD_BENFIELD_PRPTY.VEH_MODEL_YR as VehicleModelYear,
exp_HOLD_BENFIELD_PRPTY.VEH_TYPE_DESC as VehicleTypeDesc,
exp_HOLD_BENFIELD_PRPTY.EXWND_ENDOR_DESC as ExwindEndorsementDesc,
exp_HOLD_BENFIELD_PRPTY.EQ_ENDOR_IND as EarthquakeEndorsed,
exp_HOLD_BENFIELD_PRPTY.CMP_COV_DESC as ComprehensiveCoverageIndicator,
exp_HOLD_BENFIELD_PRPTY.AGENT_NBR as AgentNumber,
exp_HOLD_BENFIELD_PRPTY.SALE_SERVICE_CENTER as SaleServiceCenter,
exp_HOLD_BENFIELD_PRPTY.ROOF_YEAR as RoofYear,
exp_HOLD_BENFIELD_PRPTY.FOUNDATION_TYPE as FoundationType,
exp_HOLD_BENFIELD_PRPTY.CONTENTS_GRADE as ContentsGrade,
exp_HOLD_BENFIELD_PRPTY.IBHS_LEVEL as IBHS_LEVEL,
exp_HOLD_BENFIELD_PRPTY.BCEG_INFO as BCEGInformation,
exp_HOLD_BENFIELD_PRPTY.BOP_CAUSE_OF_LOSS_CVGE as BOPCauseofLossCoverage,
exp_HOLD_BENFIELD_PRPTY.FEED_TYPE as RecordType
FROM
exp_HOLD_BENFIELD_PRPTY
);


-- Component Aon_Benfield_Feed, Type EXPORT_DATA Exporting data

COPY INTO @my_internal_stage/my_export_folder/Aon_Benfield_Feed_
FROM (SELECT * FROM Aon_Benfield_Feed)
HEADER = TRUE
OVERWRITE = TRUE;

END; ';