-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_XLAT_AUTO_1_GET_ALL_SOURCE_DATA("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component XLAT_AUTMTN_ALL_SRC_REF, Type TRUNCATE_TABLE 
TRUNCATE TABLE DB_T_PROD_STAG.XLAT_AUTMTN_ALL_SRC_REF;


-- Component SQ_TERADATA_ETL_REF_XLAT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_TERADATA_ETL_REF_XLAT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SRC_TBL_NM,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT Substr(SRC_IDNTFTN_NM,1,Position(''.'' IN SRC_IDNTFTN_NM)-1) AS SRC_TBL_NM
FROM    DB_T_PROD_CORE.TERADATA_ETL_REF_XLAT 
WHERE SRC_IDNTFTN_SYS=''GW''
AND Lower(SRC_IDNTFTN_NM)  LIKE ''%typecode%''
/* and SRC_IDNTFTN_NM like''%pctl_grouptype.typecode%'' */
AND EXPN_DT =''9999-12-31'' 
AND SRC_TBL_NM IN(SELECT Src_tbl_Nm_stg FROM DB_T_PROD_STAG.XLAT_AUTMTN_SRC_TBL_LIST WHERE Avlbl_ind_stg=''Y'')
GROUP BY 1
) SRC
)
);


-- Component EXPTRANS1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS1 AS
(
SELECT
SQ_TERADATA_ETL_REF_XLAT.SRC_TBL_NM as SRC_TBL_NM,
SQ_TERADATA_ETL_REF_XLAT.source_record_id
FROM
SQ_TERADATA_ETL_REF_XLAT
);


// ******** No handler defined for type SQL_TRANSFORM, node SQL_PCTL *******


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQL_PCTL.TBL_NM as TBL_NM,
SQL_PCTL.L_en_US as L_en_US,
SQL_PCTL.PRIORITY as PRIORITY,
SQL_PCTL.TYPECODE as TYPECODE,
SQL_PCTL.S_en_US as S_en_US,
SQL_PCTL.RETIRED as RETIRED,
SQL_PCTL.NAME as NAME,
SQL_PCTL.ID as ID,
SQL_PCTL.DESCRIPTION as DESCRIPTION,
SQL_PCTL.source_record_id
FROM
SQL_PCTL
);


-- Component XLAT_AUTMTN_ALL_SRC_REF, Type TARGET 
INSERT INTO DB_T_PROD_STAG.XLAT_AUTMTN_ALL_SRC_REF
(
SRC_TBL_NM,
L_en_US,
PRIORITY,
TYPECODE,
S_en_US,
RETIRED,
NAME,
ID,
DESCRIPTION
)
SELECT
EXPTRANS.TBL_NM as SRC_TBL_NM,
EXPTRANS.L_en_US as L_en_US,
EXPTRANS.PRIORITY as PRIORITY,
EXPTRANS.TYPECODE as TYPECODE,
EXPTRANS.S_en_US as S_en_US,
EXPTRANS.RETIRED as RETIRED,
EXPTRANS.NAME as NAME,
EXPTRANS.ID as ID,
EXPTRANS.DESCRIPTION as DESCRIPTION
FROM
EXPTRANS;


END; ';