-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_XLAT_AUTO_6_GENERATE_MAIL("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- PIPELINE START FOR 1

-- Component SQ_XLAT_AUTOMATION_2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_XLAT_AUTOMATION_2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SRC_TBL_NM,
$2 as L_en_US,
$3 as PRIORITY,
$4 as TYPECODE,
$5 as S_en_US,
$6 as RETIRED,
$7 as NAME,
$8 as ID,
$9 as DESCRIPTION,
$10 as TGT_IDNTFTN_NM,
$11 as ROW_IND,
$12 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
XLAT_AUTMTN_CMPRSN.SRC_TBL_NM,
XLAT_AUTMTN_CMPRSN.L_en_US,
XLAT_AUTMTN_CMPRSN.PRIORITY,
XLAT_AUTMTN_CMPRSN.TYPECODE,
XLAT_AUTMTN_CMPRSN.S_en_US,
XLAT_AUTMTN_CMPRSN.RETIRED,
XLAT_AUTMTN_CMPRSN.NAME,
XLAT_AUTMTN_CMPRSN.ID,
XLAT_AUTMTN_CMPRSN.DESCRIPTION,
XLAT_AUTMTN_CMPRSN.TGT_IDNTFTN_NM,
XLAT_AUTMTN_CMPRSN.ROW_IND
FROM DB_T_PROD_STAG.XLAT_AUTMTN_CMPRSN
) SRC
)
);


-- Component RTRTRANS_New_Records, Type ROUTER Output Group New_Records
create or replace temp table RTRTRANS_NEW_RECORDS as
SELECT
SQ_XLAT_AUTOMATION_2.SRC_TBL_NM as SRC_TBL_NM,
SQ_XLAT_AUTOMATION_2.L_en_US as L_en_US,
SQ_XLAT_AUTOMATION_2.PRIORITY as PRIORITY,
SQ_XLAT_AUTOMATION_2.TYPECODE as TYPECODE,
SQ_XLAT_AUTOMATION_2.S_en_US as S_en_US,
SQ_XLAT_AUTOMATION_2.RETIRED as RETIRED,
SQ_XLAT_AUTOMATION_2.NAME as NAME,
SQ_XLAT_AUTOMATION_2.ID as ID,
SQ_XLAT_AUTOMATION_2.DESCRIPTION as DESCRIPTION,
SQ_XLAT_AUTOMATION_2.TGT_IDNTFTN_NM as TGT_IDNTFTN_NM,
SQ_XLAT_AUTOMATION_2.ROW_IND as ROW_IND,
SQ_XLAT_AUTOMATION_2.source_record_id
FROM
SQ_XLAT_AUTOMATION_2
WHERE SQ_XLAT_AUTOMATION_2.ROW_IND = ''N'';


-- Component RTRTRANS_Retired, Type ROUTER Output Group Retired
create or replace temp table RTRTRANS_RETIRED as
SELECT
SQ_XLAT_AUTOMATION_2.SRC_TBL_NM as SRC_TBL_NM,
SQ_XLAT_AUTOMATION_2.L_en_US as L_en_US,
SQ_XLAT_AUTOMATION_2.PRIORITY as PRIORITY,
SQ_XLAT_AUTOMATION_2.TYPECODE as TYPECODE,
SQ_XLAT_AUTOMATION_2.S_en_US as S_en_US,
SQ_XLAT_AUTOMATION_2.RETIRED as RETIRED,
SQ_XLAT_AUTOMATION_2.NAME as NAME,
SQ_XLAT_AUTOMATION_2.ID as ID,
SQ_XLAT_AUTOMATION_2.DESCRIPTION as DESCRIPTION,
SQ_XLAT_AUTOMATION_2.TGT_IDNTFTN_NM as TGT_IDNTFTN_NM,
SQ_XLAT_AUTOMATION_2.ROW_IND as ROW_IND,
SQ_XLAT_AUTOMATION_2.source_record_id
FROM
SQ_XLAT_AUTOMATION_2
WHERE SQ_XLAT_AUTOMATION_2.ROW_IND = ''RE'';


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
RTRTRANS_New_Records.SRC_TBL_NM as SRC_TBL_NM1,
RTRTRANS_New_Records.TYPECODE as TYPECODE1,
RTRTRANS_New_Records.NAME as NAME1,
RTRTRANS_New_Records.DESCRIPTION as DESCRIPTION1,
RTRTRANS_New_Records.TGT_IDNTFTN_NM as TGT_IDNTFTN_NM1,
RTRTRANS_New_Records.source_record_id
FROM
RTRTRANS_New_Records
);


-- Component EXPTRANS1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS1 AS
(
SELECT
RTRTRANS_Retired.SRC_TBL_NM as SRC_TBL_NM3,
RTRTRANS_Retired.TYPECODE as TYPECODE3,
RTRTRANS_Retired.RETIRED as RETIRED3,
RTRTRANS_Retired.NAME as NAME3,
RTRTRANS_Retired.DESCRIPTION as DESCRIPTION3,
RTRTRANS_Retired.TGT_IDNTFTN_NM as TGT_IDNTFTN_NM3,
RTRTRANS_Retired.source_record_id
FROM
RTRTRANS_Retired
);


-- Component SRTTRANS, Type SORTER 
CREATE OR REPLACE TEMPORARY TABLE SRTTRANS AS
(
SELECT
EXPTRANS.SRC_TBL_NM1 as SRC_TBL_NM1,
EXPTRANS.TYPECODE1 as TYPECODE1,
EXPTRANS.NAME1 as NAME1,
EXPTRANS.DESCRIPTION1 as DESCRIPTION1,
EXPTRANS.TGT_IDNTFTN_NM1 as TGT_IDNTFTN_NM1,
EXPTRANS.source_record_id
FROM
EXPTRANS
ORDER BY SRC_TBL_NM1 , TYPECODE1 , NAME1 , DESCRIPTION1 , TGT_IDNTFTN_NM1 
);


-- Component SRTTRANS1, Type SORTER 
CREATE OR REPLACE TEMPORARY TABLE SRTTRANS1 AS
(
SELECT
EXPTRANS1.SRC_TBL_NM3 as SRC_TBL_NM3,
EXPTRANS1.TYPECODE3 as TYPECODE3,
EXPTRANS1.RETIRED3 as RETIRED3,
EXPTRANS1.NAME3 as NAME3,
EXPTRANS1.DESCRIPTION3 as DESCRIPTION3,
EXPTRANS1.TGT_IDNTFTN_NM3 as TGT_IDNTFTN_NM3,
EXPTRANS1.source_record_id
FROM
EXPTRANS1
ORDER BY SRC_TBL_NM3 , TYPECODE3 , RETIRED3 , NAME3 , DESCRIPTION3 , TGT_IDNTFTN_NM3 
);


-- Component XLAT_RETIRED_RECORDS, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE XLAT_RETIRED_RECORDS AS
(
SELECT
SRTTRANS1.SRC_TBL_NM3 as SRC_TBL_NM,
SRTTRANS1.TYPECODE3 as TYPECODE,
SRTTRANS1.RETIRED3 as RETIRED,
SRTTRANS1.NAME3 as NAME,
SRTTRANS1.DESCRIPTION3 as DESCRIPTION,
SRTTRANS1.TGT_IDNTFTN_NM3 as TGT_IDNTFTN_NM
FROM
SRTTRANS1
);

copy into @my_internal_stage/XLAT_RETIRED_RECORDS from (select * from XLAT_RETIRED_RECORDS)
header=true
overwrite=true;

-- Component XLAT_RETIRED_RECORDS, Type EXPORT_DATA Exporting data
;


-- Component XLAT_NEW_RECORDS, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE XLAT_NEW_RECORDS AS
(
SELECT
SRTTRANS.SRC_TBL_NM1 as SRC_TBL_NM,
SRTTRANS.TYPECODE1 as TYPECODE,
SRTTRANS.NAME1 as NAME,
SRTTRANS.DESCRIPTION1 as DESCRIPTION,
SRTTRANS.TGT_IDNTFTN_NM1 as POTENTIAL_TGT_IDNTFTN_NM
FROM
SRTTRANS
);


copy into @my_internal_stage/XLAT_NEW_RECORDS from (select * from XLAT_NEW_RECORDS)
header=true
overwrite=true;

-- Component XLAT_NEW_RECORDS, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_XLAT_AUTOMATION_UPD_DATA, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_XLAT_AUTOMATION_UPD_DATA AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as REF_TBL_NM,
$2 as SRC_TBL_NM,
$3 as NM_FRM_SRC,
$4 as DESC_VAL_IN_TGT,
$5 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
XLAT_AUTMTN_UPD_TGT_REF.REF_TBL_NM,
XLAT_AUTMTN_UPD_TGT_REF.SRC_TBL_NM,
XLAT_AUTMTN_UPD_TGT_REF.NM_FRM_SRC,
XLAT_AUTMTN_UPD_TGT_REF.DESC_VAL_IN_TGT
FROM DB_T_PROD_STAG.XLAT_AUTMTN_UPD_TGT_REF
WHERE XLAT_AUTMTN_UPD_TGT_REF.ROW_IND <>''E''
) SRC
)
);


-- Component SRTTRANS2, Type SORTER 
CREATE OR REPLACE TEMPORARY TABLE SRTTRANS2 AS
(
SELECT
SQ_XLAT_AUTOMATION_UPD_DATA.REF_TBL_NM as REF_TBL_NM,
SQ_XLAT_AUTOMATION_UPD_DATA.SRC_TBL_NM as SRC_TBL_NM,
SQ_XLAT_AUTOMATION_UPD_DATA.NM_FRM_SRC as NM_FRM_SRC,
SQ_XLAT_AUTOMATION_UPD_DATA.DESC_VAL_IN_TGT as DESC_VAL_IN_TGT,
SQ_XLAT_AUTOMATION_UPD_DATA.source_record_id
FROM
SQ_XLAT_AUTOMATION_UPD_DATA
ORDER BY REF_TBL_NM , SRC_TBL_NM , NM_FRM_SRC , DESC_VAL_IN_TGT 
);


-- Component XLAT__UPD_DATA, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE XLAT__UPD_DATA AS
(
SELECT
SRTTRANS2.REF_TBL_NM as REF_TBL_NM,
SRTTRANS2.SRC_TBL_NM as SRC_TBL_NM,
SRTTRANS2.NM_FRM_SRC as NM_FRM_SRC,
SRTTRANS2.DESC_VAL_IN_TGT as DESC_VAL_IN_TGT
FROM
SRTTRANS2
);

copy into @my_internal_stage/XLAT__UPD_DATA from (select * from XLAT__UPD_DATA)
header=true
overwrite=true;

-- Component XLAT__UPD_DATA, Type EXPORT_DATA Exporting data
;


-- PIPELINE END FOR 2

END; ';