-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_POST_BALANCING_VALIDATE_DW_AGG_ANALYTICS("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE 
WF_MONTH_ID varchar;
BEGIN 

WF_MONTH_ID:=''1''; 

-- PIPELINE START FOR 1

-- Component SQ_AGG_COUNT_BALANCE, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_COUNT_BALANCE AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MO_ID,
$2 as METRIC_NM,
$3 as ANL_TABLE_NAME,
$4 as DW_TABLE_NAME,
$5 as ANL_CNT,
$6 as DW_CNT,
$7 as PERCENT_DEVIATION,
$8 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH ECTL_MISPREM_HEADER_TEMP AS (SELECT 
((EXTRACT (YEAR FROM CAST(TO_DATE AS DATE))  *100) + (EXTRACT(MONTH FROM CASt(TO_DATE AS DATE)) ))  MO_ID, 
B.ECTL_BATCH_ID,
CASE WHEN  ( CAST(FROM_DATE AS DATE) <> (CAST(FROM_DATE AS DATE) - EXTRACT
(DAY FROM (CAST(FROM_DATE AS DATE))) + 1))
THEN CAST(FROM_DATE AS DATE)+1 ELSE CAST(FROM_DATE AS DATE) END FROM_DT ,CAST(TO_DATE AS DATE) TO_DT,  
CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE)) + 1  CAL_ST_DT,
ADD_MONTHS((CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE))+1),1)-1   CAL_END_DT 
FROM (SELect * FROM DB_T_CTRL_PROD.ECTL_MISPREM_HEADER WHERE ACCOUNTING_YR*100+ACCOUNTING_MO=:wf_MONTH_ID ) A 
INNER JOIN  DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B 
ON B.ECTL_ACTIVE_IND = ''Y'' AND B.ECTL_PROJ_ID = 12

)

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(25)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''DISTINCT POLICIES''
AND TBL_NM=''AUTO_BILLING'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''DISTINCT POLICIES''
AND TBL_NM=''BILL_PMTS'') DW  
ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(25)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''DISTINCT POLICIES''
AND TBL_NM=''HOME_POLICY_DETAILS'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''DISTINCT POLICIES''
AND TBL_NM=''ACCTSTATS'') DW  
ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(25)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''ING_POL_LIST_PLCY_CNT''
AND TBL_NM=''LIFE_POLICY_SUMM'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''PLCY_CNT''
AND TBL_NM=''ING_POL_LIST'') DW  
ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(25)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''LIFEPOLS_PLCY_CNT''
AND TBL_NM=''LIFE_POLICY_SUMM'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''PLCY_CNT''
AND TBL_NM=''LIFEPOLS'') DW  
ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(25)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''FARM_MBR_CNT''
AND TBL_NM=''MEMB_CUST'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''FARM_MBR_CNT''
AND TBL_NM=''STG_MULTILINE_POLSTAT'') DW  
ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(25)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''LIFE_CNT''
AND TBL_NM=''MEMB_CUST'') ANL 
INNER JOIN 
(SELECT ECTL_BATCH_ID,MO_ID,CALC_SRC,METRIC_NM,''LIFE_POLS,ING_POL_LIST'' AS TBL_NM,SUM(METRIC_CNT) METRIC_CNT
FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM=''PLCY_CNT''
AND TBL_NM in (''LIFEPOLS'',''ING_POL_LIST'')) A GROUP By 1,2,3,4) DW  
ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(25)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''VEHICLE DB_T_PROD_COMN.PREMIUM AMT''
AND TBL_NM=''VEHICLE_PREMIUM'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''VEHICLE DB_T_PROD_COMN.PREMIUM AMT''
AND TBL_NM=''CLV_POL_VEH_LIST'') DW  
ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(25)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''ASIC_CNT''
AND TBL_NM=''MEMB_CUST'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''PLCY_CNT''
AND TBL_NM=''ASICPOLS'') DW  
ON 1=1
/* EIM-50197 */
/*UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(25)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''DISTINCT POLICIES''
AND TBL_NM=''ASIC_POLICY_SUMM'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''PLCY_CNT''
AND TBL_NM=''ASICPOLS'') DW  
ON 1=1
*/
UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(25)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''DISTINCT POLICIES''
AND TBL_NM=''AUTO_QUOTE_SUMM'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''DISTINCT POLICIES''
AND TBL_NM=''AUTO_QUOTE_DLY'') DW  
ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(25)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''DISTINCT VEHICLES''
AND TBL_NM=''AUTO_QUOTE_DETAILS'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''DISTINCT VEHICLES''
AND TBL_NM=''AUTO_QUOTE_DLY'') DW  
ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(25)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''DISTINCT POLICIES''
AND TBL_NM=''HOME_QUOTE_SUMM'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''DISTINCT POLICIES''
AND TBL_NM=''HO_QUOTE_SAVE'') DW  
ON 1=1
) SRC
)
);


-- Component exp_src_tgt_passthrough, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_src_tgt_passthrough AS
(
SELECT
''MO_ID     METRIC_NAME              ANL_TABLE_NAME           DW_TABLE_NAME            ANL_CNT   DW_CNT    PERCENT_DEVIATION'' as v_header,
'''' as v_underline,
RPAD ( SQ_AGG_COUNT_BALANCE.MO_ID , 10 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE.METRIC_NM , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE.ANL_TABLE_NAME , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE.DW_TABLE_NAME , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE.ANL_CNT , 10 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE.DW_CNT , 10 , '' '' ) || SQ_AGG_COUNT_BALANCE.PERCENT_DEVIATION as v_actual_records,
CHR ( 13 ) || v_header || CHR ( 13 ) || v_underline || CHR ( 13 ) || v_actual_records || CHR ( 13 ) as o_output,
SQ_AGG_COUNT_BALANCE.source_record_id
FROM
SQ_AGG_COUNT_BALANCE
);


-- Component REPORT_DW_AGG_ANALYTICS_1, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE REPORT_DW_AGG_ANALYTICS_1 AS
(
SELECT
exp_src_tgt_passthrough.o_output as OUTPUT
FROM
exp_src_tgt_passthrough
);


-- Component REPORT_DW_AGG_ANALYTICS_1, Type EXPORT_DATA Exporting data
COPY INTO @my_internal_stage/my_export_folder/REPORT_DW_AGG_ANALYTICS_1_
FROM (SELECT * FROM REPORT_DW_AGG_ANALYTICS_1)
HEADER = TRUE
OVERWRITE = TRUE;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_AGG_COUNT_BALANCE2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_COUNT_BALANCE2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MO_ID,
$2 as METRIC_NM,
$3 as ANL_TABLE_NAME,
$4 as DW_TABLE_NAME,
$5 as ANL_CNT,
$6 as DW_CNT,
$7 as PERCENT_DEVIATION,
$8 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH ECTL_MISPREM_HEADER_TEMP AS (SELECT 
((EXTRACT (YEAR FROM CAST(TO_DATE AS DATE))  *100) + (EXTRACT(MONTH FROM CASt(TO_DATE AS DATE)) ))  MO_ID, 
B.ECTL_BATCH_ID,
CASE WHEN  ( CAST(FROM_DATE AS DATE) <> (CAST(FROM_DATE AS DATE) - EXTRACT
(DAY FROM (CAST(FROM_DATE AS DATE))) + 1))
THEN CAST(FROM_DATE AS DATE)+1 ELSE CAST(FROM_DATE AS DATE) END FROM_DT ,CAST(TO_DATE AS DATE) TO_DT,  
CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE)) + 1  CAL_ST_DT,
ADD_MONTHS((CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE))+1),1)-1   CAL_END_DT 
FROM (SELect * FROM DB_T_CTRL_PROD.ECTL_MISPREM_HEADER WHERE ACCOUNTING_YR*100+ACCOUNTING_MO=:wf_MONTH_ID ) A 
INNER JOIN  DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B 
ON B.ECTL_ACTIVE_IND = ''Y'' AND B.ECTL_PROJ_ID = 12

)

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(AGG.TBL_NM AS CHAR(25)) AGG_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT AGG_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''TOTAL_VEH_INFORCE''
AND TBL_NM=''AUTO_POLICY_DETAILS'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''AGG'' AND METRIC_NM = ''TOTAL_VEH_INS''
AND TBL_NM=''AGG_RDD_MTHLY'') AGG  
ON 1=1
) SRC
)
);


-- Component exp_src_tgt_passthrough2, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_src_tgt_passthrough2 AS
(
SELECT
''MO_ID     METRIC_NAME              ANL_TABLE_NAME           DW_TABLE_NAME            ANL_CNT   AGG_CNT   PERCENT_DEVIATION'' as v_header,
'''' as v_underline,
RPAD ( SQ_AGG_COUNT_BALANCE2.MO_ID , 10 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE2.METRIC_NM , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE2.ANL_TABLE_NAME , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE2.DW_TABLE_NAME , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE2.ANL_CNT , 10 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE2.DW_CNT , 10 , '' '' ) || SQ_AGG_COUNT_BALANCE2.PERCENT_DEVIATION as v_actual_records,
CHR ( 13 ) || v_header || CHR ( 13 ) || v_underline || CHR ( 13 ) || v_actual_records || CHR ( 13 ) as o_output,
SQ_AGG_COUNT_BALANCE2.source_record_id
FROM
SQ_AGG_COUNT_BALANCE2
);


-- Component REPORT_DW_AGG_ANALYTICS_2, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE REPORT_DW_AGG_ANALYTICS_2 AS
(
SELECT
exp_src_tgt_passthrough2.o_output as OUTPUT
FROM
exp_src_tgt_passthrough2
);


-- Component REPORT_DW_AGG_ANALYTICS_2, Type EXPORT_DATA Exporting data

COPY INTO @my_internal_stage/my_export_folder/REPORT_DW_AGG_ANALYTICS_2_
FROM (SELECT * FROM REPORT_DW_AGG_ANALYTICS_2)
HEADER = TRUE
OVERWRITE = TRUE;

-- PIPELINE END FOR 2

-- PIPELINE START FOR 3

-- Component SQ_AGG_COUNT_BALANCE3, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_COUNT_BALANCE3 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MO_ID,
$2 as METRIC_NM,
$3 as ANL_TABLE_NAME,
$4 as DW_TABLE_NAME,
$5 as ANL_CNT,
$6 as DW_CNT,
$7 as PERCENT_DEVIATION,
$8 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH ECTL_MISPREM_HEADER_TEMP AS (SELECT 
((EXTRACT (YEAR FROM CAST(TO_DATE AS DATE))  *100) + (EXTRACT(MONTH FROM CASt(TO_DATE AS DATE)) ))  MO_ID, 
B.ECTL_BATCH_ID,
CASE WHEN  ( CAST(FROM_DATE AS DATE) <> (CAST(FROM_DATE AS DATE) - EXTRACT
(DAY FROM (CAST(FROM_DATE AS DATE))) + 1))
THEN CAST(FROM_DATE AS DATE)+1 ELSE CAST(FROM_DATE AS DATE) END FROM_DT ,CAST(TO_DATE AS DATE) TO_DT,  
CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE)) + 1  CAL_ST_DT,
ADD_MONTHS((CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE))+1),1)-1   CAL_END_DT 
FROM (SELect * FROM DB_T_CTRL_PROD.ECTL_MISPREM_HEADER WHERE ACCOUNTING_YR*100+ACCOUNTING_MO=:wf_MONTH_ID ) A 
INNER JOIN  DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B 
ON B.ECTL_ACTIVE_IND = ''Y'' AND B.ECTL_PROJ_ID = 12

)

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM ||''-''||GW.TBL_NM AS CHAR(50)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT -DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''FIRE_CST_CNT''
AND TBL_NM=''MEMB_CUST'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''FIRE_CST_CNT''
AND TBL_NM=''STG_MULTILINE_POLSTAT'') DW  
ON 1=1  INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''FIRE_CST_CNT''
AND TBL_NM=''GW_TABLES'') GW ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM ||''-''||GW.TBL_NM AS CHAR(50)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''FIRE_MBR_CNT''
AND TBL_NM=''MEMB_CUST'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''FIRE_MBR_CNT''
AND TBL_NM=''STG_MULTILINE_POLSTAT'') DW  
ON 1=1   INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''FIRE_MBR_CNT''
AND TBL_NM=''GW_TABLES'') GW ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(50)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''PORT_MBR_CNT''
AND TBL_NM=''MEMB_CUST'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''PORT_MBR_CNT''
AND TBL_NM=''STG_MULTILINE_POLSTAT'') DW  
ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM AS CHAR(50)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''PORT_CST_CNT''
AND TBL_NM=''MEMB_CUST'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''PORT_CST_CNT''
AND TBL_NM=''STG_MULTILINE_POLSTAT'') DW  
ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM ||''-''||GW.TBL_NM AS CHAR(50)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''SMLN_MBR_CNT''
AND TBL_NM=''MEMB_CUST'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''SMLN_MBR_CNT''
AND TBL_NM=''STG_MULTILINE_POLSTAT'') DW  
ON 1=1 INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''SMLN_MBR_CNT''
AND TBL_NM=''GW_TABLES'') GW ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(DW.TBL_NM ||''-''||GW.TBL_NM AS CHAR(50)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT DW_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''FGM_CST_CNT''
AND TBL_NM=''MEMB_CUST'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''FGM_CST_CNT''
AND TBL_NM=''STG_MULTILINE_POLSTAT'') DW  
ON 1=1  INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''FGM_CST_CNT''
AND TBL_NM=''GW_TABLES'') GW ON 1=1
) SRC
)
);


-- Component exp_src_tgt_passthrough3, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_src_tgt_passthrough3 AS
(
SELECT
''MO_ID     METRIC_NAME              ANL_TABLE_NAME           DW_TABLE_NAME                                     ANL_CNT   DW_CNT    PERCENT_DEVIATION'' as v_header,
'''' as v_underline,
RPAD ( SQ_AGG_COUNT_BALANCE3.MO_ID , 10 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE3.METRIC_NM , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE3.ANL_TABLE_NAME , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE3.DW_TABLE_NAME , 50 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE3.ANL_CNT , 10 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE3.DW_CNT , 10 , '' '' ) || SQ_AGG_COUNT_BALANCE3.PERCENT_DEVIATION as v_actual_records,
CHR ( 13 ) || v_header || CHR ( 13 ) || v_underline || CHR ( 13 ) || v_actual_records || CHR ( 13 ) as o_output,
SQ_AGG_COUNT_BALANCE3.source_record_id
FROM
SQ_AGG_COUNT_BALANCE3
);


-- Component REPORT_DW_AGG_ANALYTICS_3, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE REPORT_DW_AGG_ANALYTICS_3 AS
(
SELECT
exp_src_tgt_passthrough3.o_output as OUTPUT
FROM
exp_src_tgt_passthrough3
);


-- Component REPORT_DW_AGG_ANALYTICS_3, Type EXPORT_DATA Exporting data
COPY INTO @my_internal_stage/my_export_folder/REPORT_DW_AGG_ANALYTICS_3_
FROM (SELECT * FROM REPORT_DW_AGG_ANALYTICS_3)
HEADER = TRUE
OVERWRITE = TRUE;


-- PIPELINE END FOR 3

-- PIPELINE START FOR 4

-- Component SQ_AGG_COUNT_BALANCE4, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_COUNT_BALANCE4 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MO_ID,
$2 as METRIC_NM,
$3 as ANL_TABLE_NAME,
$4 as DW_TABLE_NAME,
$5 as ANL_CNT,
$6 as DW_CNT,
$7 as PERCENT_DEVIATION,
$8 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH ECTL_MISPREM_HEADER_TEMP AS (SELECT 
((EXTRACT (YEAR FROM CAST(TO_DATE AS DATE))  *100) + (EXTRACT(MONTH FROM CASt(TO_DATE AS DATE)) ))  MO_ID, 
B.ECTL_BATCH_ID,
CASE WHEN  ( CAST(FROM_DATE AS DATE) <> (CAST(FROM_DATE AS DATE) - EXTRACT
(DAY FROM (CAST(FROM_DATE AS DATE))) + 1))
THEN CAST(FROM_DATE AS DATE)+1 ELSE CAST(FROM_DATE AS DATE) END FROM_DT ,CAST(TO_DATE AS DATE) TO_DT,  
CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE)) + 1  CAL_ST_DT,
ADD_MONTHS((CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE))+1),1)-1   CAL_END_DT 
FROM (SELect * FROM DB_T_CTRL_PROD.ECTL_MISPREM_HEADER WHERE ACCOUNTING_YR*100+ACCOUNTING_MO=:wf_MONTH_ID ) A 
INNER JOIN  DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B 
ON B.ECTL_ACTIVE_IND = ''Y'' AND B.ECTL_PROJ_ID = 12

)

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(AGG.TBL_NM ||''-''||GW.TBL_NM AS CHAR(50)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT AGG_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''EX_POLS_CNT''
AND TBL_NM=''MEMB_CUST'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''AGG'' AND METRIC_NM = ''PLCY_CNT_WRIT_IFO''
AND TBL_NM=''AGG_SALES_MTHLY'') AGG  
ON 1=1  INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''EX_POLS_CNT''
AND TBL_NM=''GW_TABLES'') GW ON 1=1

UNION

SELECT ANL.MO_ID, CAST(ANL.METRIC_NM AS CHAR(25)) METRIC_NAME , CAST(ANL.TBL_NM AS CHAR(25)) ANL_TABLE_NAME,CAST(AGG.TBL_NM ||''-''||GW.TBL_NM AS CHAR(50)) DW_TABLE_NAME,
DB_T_STAG_PROD.METRIC_CNT ANL_CNT,DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT AGG_CNT, 
( CAST((DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CASE WHEN DB_T_STAG_PROD.METRIC_CNT=0 THEN 1 ELSE CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3))  END) AS PERCENT_DEVIATION  FROM 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''ANALYTICS'' AND METRIC_NM = ''EXCD_CNT''
AND TBL_NM=''MEMB_CUST'') ANL 
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''AGG'' AND METRIC_NM = ''TOTAL_VEH_INS''
AND TBL_NM=''AGG_RDD_MTHLY'') AGG   ON 1=1
INNER JOIN 
(SELECT * FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE WHERE MO_ID = (SELECT MO_ID FROM ECTL_MISPREM_HEADER_TEMP) AND  CALC_SRC = ''DW'' AND METRIC_NM = ''EXCD_CNT''
AND TBL_NM=''GW_TABLES'') GW ON 1=1
) SRC
)
);


-- Component exp_src_tgt_passthrough4, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_src_tgt_passthrough4 AS
(
SELECT
''MO_ID     METRIC_NAME              ANL_TABLE_NAME           DW_TABLE_NAME                                     ANL_CNT   AGG_CNT   PERCENT_DEVIATION'' as v_header,
'''' as v_underline,
RPAD ( SQ_AGG_COUNT_BALANCE4.MO_ID , 10 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE4.METRIC_NM , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE4.ANL_TABLE_NAME , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE4.DW_TABLE_NAME , 50 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE4.ANL_CNT , 10 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE4.DW_CNT , 10 , '' '' ) || SQ_AGG_COUNT_BALANCE4.PERCENT_DEVIATION as v_actual_records,
CHR ( 13 ) || v_header || CHR ( 13 ) || v_underline || CHR ( 13 ) || v_actual_records || CHR ( 13 ) as o_output,
SQ_AGG_COUNT_BALANCE4.source_record_id
FROM
SQ_AGG_COUNT_BALANCE4
);


-- Component REPORT_DW_AGG_ANALYTICS_4, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE REPORT_DW_AGG_ANALYTICS_4 AS
(
SELECT
exp_src_tgt_passthrough4.o_output as OUTPUT
FROM
exp_src_tgt_passthrough4
);


-- Component REPORT_DW_AGG_ANALYTICS_4, Type EXPORT_DATA Exporting data
COPY INTO @my_internal_stage/my_export_folder/REPORT_DW_AGG_ANALYTICS_4_
FROM (SELECT * FROM REPORT_DW_AGG_ANALYTICS_4)
HEADER = TRUE
OVERWRITE = TRUE;


-- PIPELINE END FOR 4

-- PIPELINE START FOR 5

-- Component SQ_AGG_COUNT_BALANCE1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_COUNT_BALANCE1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_BATCH_ID,
$2 as MO_ID,
$3 as TBL_NM,
$4 as METRIC_NM,
$5 as METRIC_CNT,
$6 as TBL_NM1,
$7 as METRIC_NM1,
$8 as METRIC_CNT1,
$9 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH ECTL_MISPREM_HEADER_TEMP AS (SELECT 
((EXTRACT (YEAR FROM CAST(TO_DATE AS DATE))  *100) + (EXTRACT(MONTH FROM CASt(TO_DATE AS DATE)) ))  MO_ID, 
B.ECTL_BATCH_ID,
CASE WHEN  ( CAST(FROM_DATE AS DATE) <> (CAST(FROM_DATE AS DATE) - EXTRACT
(DAY FROM (CAST(FROM_DATE AS DATE))) + 1))
THEN CAST(FROM_DATE AS DATE)+1 ELSE CAST(FROM_DATE AS DATE) END FROM_DT ,CAST(TO_DATE AS DATE) TO_DT,  
CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE)) + 1  CAL_ST_DT,
ADD_MONTHS((CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE))+1),1)-1   CAL_END_DT 
FROM (SELect * FROM DB_T_CTRL_PROD.ECTL_MISPREM_HEADER WHERE ACCOUNTING_YR*100+ACCOUNTING_MO=:wf_MONTH_ID ) A 
INNER JOIN  DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B 
ON B.ECTL_ACTIVE_IND = ''Y'' AND B.ECTL_PROJ_ID = 12

)

SELECT A.ECTL_BATCH_ID,A.MO_ID,A.TBL_NM,A.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''PLCY_CNT'' AND B.METRIC_NM = ''ING_POL_LIST_PLCY_CNT''  
AND A.CALC_SRC = ''DW'' AND A.TBL_NM = ''ING_POL_LIST'' 
AND B.CALC_SRC = ''ANALYTICS'' AND B.TBL_NM = ''LIFE_POLICY_SUMM''   
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID 
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,A.TBL_NM,A.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''PLCY_CNT'' AND B.METRIC_NM = ''LIFEPOLS_PLCY_CNT''  
AND A.CALC_SRC = ''DW'' AND A.TBL_NM = ''LIFEPOLS'' 
AND B.CALC_SRC = ''ANALYTICS'' AND B.TBL_NM = ''LIFE_POLICY_SUMM''   
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID 
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,A.TBL_NM,A.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''PORT_MBR_CNT'' AND B.METRIC_NM = ''PORT_MBR_CNT''  
AND A.CALC_SRC = ''DW'' AND A.TBL_NM = ''STG_MULTILINE_POLSTAT'' 
AND B.CALC_SRC = ''ANALYTICS'' AND B.TBL_NM = ''MEMB_CUST''   
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID  
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,A.TBL_NM,A.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''PORT_CST_CNT'' AND B.METRIC_NM = ''PORT_CST_CNT''  
AND A.CALC_SRC = ''DW'' AND A.TBL_NM = ''STG_MULTILINE_POLSTAT'' 
AND B.CALC_SRC = ''ANALYTICS'' AND B.TBL_NM = ''MEMB_CUST''   
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID 
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,A.TBL_NM,A.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''FARM_MBR_CNT'' AND B.METRIC_NM = ''FARM_MBR_CNT''  
AND A.CALC_SRC = ''DW'' AND A.TBL_NM = ''STG_MULTILINE_POLSTAT'' 
AND B.CALC_SRC = ''ANALYTICS'' AND B.TBL_NM = ''MEMB_CUST''   
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID 
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,A.TBL_NM,A.METRIC_NM,SUM(DB_T_STAG_PROD.METRIC_CNT) METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''VEHICLE DB_T_PROD_COMN.PREMIUM AMT'' AND B.METRIC_NM = ''VEHICLE DB_T_PROD_COMN.PREMIUM AMT''  
AND A.CALC_SRC = ''ANALYTICS'' AND A.TBL_NM = ''VEHICLE_PREMIUM''   
AND B.CALC_SRC = ''DW'' AND B.TBL_NM = ''CLV_POL_VEH_LIST''
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID  
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
GROUP BY 1,2,3,4,6,7,8
HAVING ( ( (CAST( (SUm(DB_T_STAG_PROD.METRIC_CNT)-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(SUM(DB_T_STAG_PROD.METRIC_CNT) AS DECIMAL(20,3)))>3 )
OR  ( (CAST( (SUM(DB_T_STAG_PROD.METRIC_CNT)-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST (SUM(DB_T_STAG_PROD.METRIC_CNT) AS DECIMAL(20,3)))< (-3) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,A.TBL_NM,A.METRIC_NM,SUM(DB_T_STAG_PROD.METRIC_CNT) METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''ASIC_CNT'' AND B.METRIC_NM = ''PLCY_CNT''  
AND A.CALC_SRC = ''ANALYTICS'' AND A.TBL_NM = ''MEMB_CUST''   
AND B.CALC_SRC = ''DW'' AND B.TBL_NM = ''ASICPOLS''
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID  
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
GROUP BY 1,2,3,4,6,7,8
HAVING ( ( (CAST( (SUm(DB_T_STAG_PROD.METRIC_CNT)-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(SUM(DB_T_STAG_PROD.METRIC_CNT) AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (SUM(DB_T_STAG_PROD.METRIC_CNT)-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST (SUM(DB_T_STAG_PROD.METRIC_CNT) AS DECIMAL(20,3)))< (-2) ) )
/* EIM-50197 */
/*UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,A.TBL_NM,A.METRIC_NM,SUM(DB_T_STAG_PROD.METRIC_CNT) DB_T_STAG_PROD.METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''DISTINCT POLICIES'' AND B.METRIC_NM = ''PLCY_CNT''  
AND A.CALC_SRC = ''ANALYTICS'' AND A.TBL_NM = ''ASIC_POLICY_SUMM''   
AND B.CALC_SRC = ''DW'' AND B.TBL_NM = ''ASICPOLS''
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID  
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
GROUP BY 1,2,3,4,6,7,8
HAVING ( ( (CAST( (SUm(DB_T_STAG_PROD.METRIC_CNT)-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(SUM(DB_T_STAG_PROD.METRIC_CNT) AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (SUM(DB_T_STAG_PROD.METRIC_CNT)-DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST (SUM(DB_T_STAG_PROD.METRIC_CNT) AS DECIMAL(20,3)))< (-2) ) )*/
) SRC
)
);


-- Component exp_src_tgt_passthrough1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_src_tgt_passthrough1 AS
(
SELECT
''ECTL_BATCH_ID MO_ID     TBL_NM                   METRIC_NM                METRIC_CNT TBL_NM                   METRIC_NM                METRIC_CNT'' as v_header,
'''' as v_underline,
RPAD ( SQ_AGG_COUNT_BALANCE1.ECTL_BATCH_ID , 14 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE1.MO_ID , 10 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE1.TBL_NM , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE1.METRIC_NM , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE1.METRIC_CNT , 11 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE1.TBL_NM1 , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE1.METRIC_NM1 , 25 , '' '' ) || SQ_AGG_COUNT_BALANCE1.METRIC_CNT1 as v_actual_records,
CHR ( 13 ) || v_header || CHR ( 13 ) || v_underline || CHR ( 13 ) || v_actual_records || CHR ( 13 ) as o_output,
SQ_AGG_COUNT_BALANCE1.source_record_id
FROM
SQ_AGG_COUNT_BALANCE1
);


-- Component REPORT_DW_AGG_ANALYTICS_5, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE REPORT_DW_AGG_ANALYTICS_5 AS
(
SELECT
exp_src_tgt_passthrough1.o_output as OUTPUT
FROM
exp_src_tgt_passthrough1
);


-- Component REPORT_DW_AGG_ANALYTICS_5, Type EXPORT_DATA Exporting data
COPY INTO @my_internal_stage/my_export_folder/REPORT_DW_AGG_ANALYTICS_5_
FROM (SELECT * FROM REPORT_DW_AGG_ANALYTICS_5)
HEADER = TRUE
OVERWRITE = TRUE;


-- PIPELINE END FOR 5

-- PIPELINE START FOR 6

-- Component SQ_AGG_COUNT_BALANCE11, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_COUNT_BALANCE11 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_BATCH_ID,
$2 as MO_ID,
$3 as TBL_NM,
$4 as METRIC_NM,
$5 as METRIC_CNT,
$6 as TBL_NM1,
$7 as METRIC_NM1,
$8 as METRIC_CNT1,
$9 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH ECTL_MISPREM_HEADER_TEMP AS (SELECT 
((EXTRACT (YEAR FROM CAST(TO_DATE AS DATE))  *100) + (EXTRACT(MONTH FROM CASt(TO_DATE AS DATE)) ))  MO_ID, 
B.ECTL_BATCH_ID,
CASE WHEN  ( CAST(FROM_DATE AS DATE) <> (CAST(FROM_DATE AS DATE) - EXTRACT
(DAY FROM (CAST(FROM_DATE AS DATE))) + 1))
THEN CAST(FROM_DATE AS DATE)+1 ELSE CAST(FROM_DATE AS DATE) END FROM_DT ,CAST(TO_DATE AS DATE) TO_DT,  
CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE)) + 1  CAL_ST_DT,
ADD_MONTHS((CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE))+1),1)-1   CAL_END_DT 
FROM (SELect * FROM DB_T_CTRL_PROD.ECTL_MISPREM_HEADER WHERE ACCOUNTING_YR*100+ACCOUNTING_MO=:wf_MONTH_ID ) A 
INNER JOIN  DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B 
ON B.ECTL_ACTIVE_IND = ''Y'' AND B.ECTL_PROJ_ID = 12

)

SELECT A.ECTL_BATCH_ID,A.MO_ID,CAST(A.TBL_NM ||''-''||C.TBL_NM AS CHAR(50)) METRIC_NM,(DB_T_STAG_PROD.METRIC_CNT +DB_T_STAG_PROD.METRIC_CNT) METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''HOME_CST_CNT'' AND B.METRIC_NM = ''HOME_CST_CNT''  
AND A.CALC_SRC = ''DW'' AND A.TBL_NM = ''STG_MULTILINE_POLSTAT'' 
AND B.CALC_SRC = ''ANALYTICS'' AND B.TBL_NM = ''MEMB_CUST'' 
INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE C  
ON C.METRIC_NM = ''HOME_CST_CNT'' 
AND C.CALC_SRC = ''DW''  AND C.TBL_NM = ''GW_TABLES''     
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID   AND A.MO_ID = C.MO_ID AND A.ECTL_BATCH_ID  = C.ECTL_BATCH_ID 
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,CAST(A.TBL_NM ||''-''||C.TBL_NM AS CHAR(50)) DW_TABLE_NAME,B.METRIC_NM,(DB_T_STAG_PROD.METRIC_CNT +DB_T_STAG_PROD.METRIC_CNT) METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''MANHOME_MBR_CNT'' AND B.METRIC_NM = ''MANHOME_MBR_CNT''  
AND A.CALC_SRC = ''DW'' AND A.TBL_NM = ''STG_MULTILINE_POLSTAT'' 
AND B.CALC_SRC = ''ANALYTICS'' AND B.TBL_NM = ''MEMB_CUST''   
INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE C  
ON C.METRIC_NM = ''MANHOME_MBR_CNT'' 
AND C.CALC_SRC = ''DW''  AND C.TBL_NM = ''GW_TABLES''     
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID  AND A.MO_ID = C.MO_ID AND A.ECTL_BATCH_ID  = C.ECTL_BATCH_ID 
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,CAST(A.TBL_NM ||''-''||C.TBL_NM AS CHAR(50)) DW_TABLE_NAME,B.METRIC_NM,(DB_T_STAG_PROD.METRIC_CNT +DB_T_STAG_PROD.METRIC_CNT) METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''MANHOME_CST_CNT'' AND B.METRIC_NM = ''MANHOME_CST_CNT''  
AND A.CALC_SRC = ''DW'' AND A.TBL_NM = ''STG_MULTILINE_POLSTAT'' 
AND B.CALC_SRC = ''ANALYTICS'' AND B.TBL_NM = ''MEMB_CUST''   
INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE C  
ON C.METRIC_NM = ''MANHOME_CST_CNT'' 
AND C.CALC_SRC = ''DW''  AND C.TBL_NM = ''GW_TABLES''     
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID  AND A.MO_ID = C.MO_ID AND A.ECTL_BATCH_ID  = C.ECTL_BATCH_ID 
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,CAST(A.TBL_NM ||''-''||C.TBL_NM AS CHAR(50)) DW_TABLE_NAME,B.METRIC_NM,(DB_T_STAG_PROD.METRIC_CNT +DB_T_STAG_PROD.METRIC_CNT) METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''FIRE_MBR_CNT'' AND B.METRIC_NM = ''FIRE_MBR_CNT''  
AND A.CALC_SRC = ''DW'' AND A.TBL_NM = ''STG_MULTILINE_POLSTAT'' 
AND B.CALC_SRC = ''ANALYTICS'' AND B.TBL_NM = ''MEMB_CUST''   
INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE C  
ON C.METRIC_NM = ''FIRE_MBR_CNT'' 
AND C.CALC_SRC = ''DW''  AND C.TBL_NM = ''GW_TABLES''     
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID  AND A.MO_ID = C.MO_ID AND A.ECTL_BATCH_ID  = C.ECTL_BATCH_ID 
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,CAST(A.TBL_NM ||''-''||C.TBL_NM AS CHAR(50)) DW_TABLE_NAME,B.METRIC_NM,(DB_T_STAG_PROD.METRIC_CNT +DB_T_STAG_PROD.METRIC_CNT) METRIC_CNT,B.TBL_NM,B.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''FIRE_CST_CNT'' AND B.METRIC_NM = ''FIRE_CST_CNT''  
AND A.CALC_SRC = ''DW'' AND A.TBL_NM = ''STG_MULTILINE_POLSTAT'' 
AND B.CALC_SRC = ''ANALYTICS'' AND B.TBL_NM = ''MEMB_CUST''   
INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE C  
ON C.METRIC_NM = ''FIRE_cst_CNT'' 
AND C.CALC_SRC = ''DW''  AND C.TBL_NM = ''GW_TABLES''     
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID  AND A.MO_ID = C.MO_ID AND A.ECTL_BATCH_ID  = C.ECTL_BATCH_ID 
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (DB_T_STAG_PROD.METRIC_CNT-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,CAST(B.TBL_NM ||''-''||C.TBL_NM AS CHAR(50)) DW_TABLE_NAME,B.METRIC_NM,(DB_T_STAG_PROD.METRIC_CNT +DB_T_STAG_PROD.METRIC_CNT) METRIC_CNT,A.TBL_NM,A.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''EX_POLS_CNT'' AND B.METRIC_NM = ''PLCY_CNT_WRIT_IFO''  
AND A.CALC_SRC = ''ANALYTICS'' AND A.TBL_NM = ''MEMB_CUST''
AND B.CALC_SRC = ''AGG'' AND B.TBL_NM = ''AGG_SALES_MTHLY''   
AND A.MO_ID = B.MO_ID /* AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID  */
INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE C  
ON C.METRIC_NM = ''EX_POLS_CNT'' 
AND C.CALC_SRC = ''DW''  AND C.TBL_NM = ''GW_TABLES''     
AND A.MO_ID = B.MO_ID /* AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID  */
AND A.MO_ID = C.MO_ID /* AND A.ECTL_BATCH_ID  = C.ECTL_BATCH_ID  */
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,CAST(B.TBL_NM ||''-''||C.TBL_NM AS CHAR(50)) DW_TABLE_NAME,B.METRIC_NM,(DB_T_STAG_PROD.METRIC_CNT +DB_T_STAG_PROD.METRIC_CNT) METRIC_CNT,A.TBL_NM,A.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''EXCD_CNT'' AND B.METRIC_NM = ''TOTAL_VEH_INS''  
AND A.CALC_SRC = ''ANALYTICS'' AND A.TBL_NM = ''MEMB_CUST''
AND B.CALC_SRC = ''AGG'' AND B.TBL_NM = ''AGG_RDD_MTHLY''  
INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE C  
ON C.METRIC_NM = ''EXCD_CNT'' 
AND C.CALC_SRC = ''DW''  AND C.TBL_NM = ''GW_TABLES''     
AND A.MO_ID = B.MO_ID/*  AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID   */
AND A.MO_ID = C.MO_ID /* AND A.ECTL_BATCH_ID  = C.ECTL_BATCH_ID  */
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )
) SRC
)
);


-- Component exp_src_tgt_passthrough11, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_src_tgt_passthrough11 AS
(
SELECT
''ECTL_BATCH_ID MO_ID     DW_TABLE_NAME                                     METRIC_NM                METRIC_CNT TBL_NM                   METRIC_NM                METRIC_CNT'' as v_header,
'''' as v_underline,
RPAD ( SQ_AGG_COUNT_BALANCE11.ECTL_BATCH_ID , 14 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE11.MO_ID , 10 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE11.TBL_NM , 50 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE11.METRIC_NM , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE11.METRIC_CNT , 11 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE11.TBL_NM1 , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE11.METRIC_NM1 , 25 , '' '' ) || SQ_AGG_COUNT_BALANCE11.METRIC_CNT1 as v_actual_records,
CHR ( 13 ) || v_header || CHR ( 13 ) || v_underline || CHR ( 13 ) || v_actual_records || CHR ( 13 ) as o_output,
SQ_AGG_COUNT_BALANCE11.source_record_id
FROM
SQ_AGG_COUNT_BALANCE11
);


-- Component REPORT_DW_AGG_ANALYTICS_6, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE REPORT_DW_AGG_ANALYTICS_6 AS
(
SELECT
exp_src_tgt_passthrough11.o_output as OUTPUT
FROM
exp_src_tgt_passthrough11
);


-- Component REPORT_DW_AGG_ANALYTICS_6, Type EXPORT_DATA Exporting data
COPY INTO @my_internal_stage/my_export_folder/REPORT_DW_AGG_ANALYTICS_6_
FROM (SELECT * FROM REPORT_DW_AGG_ANALYTICS_6)
HEADER = TRUE
OVERWRITE = TRUE;


-- PIPELINE END FOR 6

-- PIPELINE START FOR 7

-- Component SQ_AGG_COUNT_BALANCE12, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_COUNT_BALANCE12 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_BATCH_ID,
$2 as MO_ID,
$3 as TBL_NM,
$4 as METRIC_NM,
$5 as METRIC_CNT,
$6 as TBL_NM1,
$7 as METRIC_NM1,
$8 as METRIC_CNT1,
$9 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH ECTL_MISPREM_HEADER_TEMP AS (SELECT 
((EXTRACT (YEAR FROM CAST(TO_DATE AS DATE))  *100) + (EXTRACT(MONTH FROM CASt(TO_DATE AS DATE)) ))  MO_ID, 
B.ECTL_BATCH_ID,
CASE WHEN  ( CAST(FROM_DATE AS DATE) <> (CAST(FROM_DATE AS DATE) - EXTRACT
(DAY FROM (CAST(FROM_DATE AS DATE))) + 1))
THEN CAST(FROM_DATE AS DATE)+1 ELSE CAST(FROM_DATE AS DATE) END FROM_DT ,CAST(TO_DATE AS DATE) TO_DT,  
CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE)) + 1  CAL_ST_DT,
ADD_MONTHS((CAST(TO_DATE AS DATE) - EXTRACT(DAY FROM CAST(TO_DATE AS DATE))+1),1)-1   CAL_END_DT 
FROM (SELect * FROM DB_T_CTRL_PROD.ECTL_MISPREM_HEADER WHERE ACCOUNTING_YR*100+ACCOUNTING_MO=:wf_MONTH_ID ) A 
INNER JOIN  DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO B 
ON B.ECTL_ACTIVE_IND = ''Y'' AND B.ECTL_PROJ_ID = 12

)

SELECT A.ECTL_BATCH_ID,A.MO_ID,A.TBL_NM,A.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT  ,CAST(B.TBL_NM ||''-''||C.TBL_NM AS CHAR(50)) DW_TABLE_NAME,B.METRIC_NM,(DB_T_STAG_PROD.METRIC_CNT +DB_T_STAG_PROD.METRIC_CNT) METRIC_CNT
FROM
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A  JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''SMLN_MBR_CNT'' AND B.METRIC_NM = ''SMLN_MBR_CNT''  
AND A.CALC_SRC = ''ANALYTICS'' AND A.TBL_NM = ''MEMB_CUST''
AND B.CALC_SRC = ''DW'' AND B.TBL_NM = ''STG_MULTILINE_POLSTAT''  
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID
JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE C  
ON C.METRIC_NM = ''SMLN_MBR_CNT'' 
AND C.CALC_SRC = ''DW''  AND C.TBL_NM = ''GW_TABLES''     
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID  
AND A.MO_ID = C.MO_ID AND A.ECTL_BATCH_ID  = C.ECTL_BATCH_ID 
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )

UNION

SELECT A.ECTL_BATCH_ID,A.MO_ID,A.TBL_NM,A.METRIC_NM,DB_T_STAG_PROD.METRIC_CNT ,CAST(B.TBL_NM ||''-''||C.TBL_NM AS CHAR(50)) DW_TABLE_NAME,B.METRIC_NM,(DB_T_STAG_PROD.METRIC_CNT +DB_T_STAG_PROD.METRIC_CNT) METRIC_CNT
FROM 
DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE A INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE B  
ON A.METRIC_NM = ''FGM_CST_CNT'' AND B.METRIC_NM = ''FGM_CST_CNT''  
AND A.CALC_SRC = ''ANALYTICS'' AND A.TBL_NM = ''MEMB_CUST''
AND B.CALC_SRC = ''DW'' AND B.TBL_NM = ''STG_MULTILINE_POLSTAT''  
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID
INNER JOIN DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE C  
ON C.METRIC_NM = ''FGM_CST_CNT'' 
AND C.CALC_SRC = ''DW''  AND C.TBL_NM = ''GW_TABLES''     
AND A.MO_ID = B.MO_ID AND A.ECTL_BATCH_ID  = B.ECTL_BATCH_ID  AND A.MO_ID = C.MO_ID AND A.ECTL_BATCH_ID  = C.ECTL_BATCH_ID 
WHERE (A.MO_ID,A.ECTL_BATCH_ID) IN (SELECT MO_ID,ECTL_BATCH_ID FROM ECTL_MISPREM_HEADER_TEMP) 
AND ( ( (CAST( (-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))>2 )
OR  ( (CAST( (-DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT+DB_T_STAG_PROD.METRIC_CNT)*100 AS DECIMAL(20,3))/CAST(DB_T_STAG_PROD.METRIC_CNT AS DECIMAL(20,3)))< (-2) ) )
) SRC
)
);


-- Component exp_src_tgt_passthrough12, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_src_tgt_passthrough12 AS
(
SELECT
''ECTL_BATCH_ID MO_ID     TBL_NM                   METRIC_NM                METRIC_CNT DW_TABLE_NAME                                     METRIC_NM                METRIC_CNT'' as v_header,
'''' as v_underline,
RPAD ( SQ_AGG_COUNT_BALANCE12.ECTL_BATCH_ID , 14 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE12.MO_ID , 10 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE12.TBL_NM , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE12.METRIC_NM , 25 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE12.METRIC_CNT , 11 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE12.TBL_NM1 , 50 , '' '' ) || RPAD ( SQ_AGG_COUNT_BALANCE12.METRIC_NM1 , 25 , '' '' ) || SQ_AGG_COUNT_BALANCE12.METRIC_CNT1 as v_actual_records,
CHR ( 13 ) || v_header || CHR ( 13 ) || v_underline || CHR ( 13 ) || v_actual_records || CHR ( 13 ) as o_output,
SQ_AGG_COUNT_BALANCE12.source_record_id
FROM
SQ_AGG_COUNT_BALANCE12
);


-- Component REPORT_DW_AGG_ANALYTICS_7, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE REPORT_DW_AGG_ANALYTICS_7 AS
(
SELECT
exp_src_tgt_passthrough12.o_output as OUTPUT
FROM
exp_src_tgt_passthrough12
);


-- Component REPORT_DW_AGG_ANALYTICS_7, Type EXPORT_DATA Exporting data
COPY INTO @my_internal_stage/my_export_folder/REPORT_DW_AGG_ANALYTICS_7_
FROM (SELECT * FROM REPORT_DW_AGG_ANALYTICS_7)
HEADER = TRUE
OVERWRITE = TRUE;


-- PIPELINE END FOR 7

END; ';