-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_CLMF_CLM_LOSS_RESERVE_CORE_AUTO("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE 
PMMAPPINGNAME varchar;
ACT_PROJ_ID varchar;
BATCH_ACTIVE_IND varchar;
TABLE_NM varchar;

BEGIN 


-- Component LKP_ECTL_PRGM_PARAM, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ECTL_PRGM_PARAM AS
(
SELECT
ECTL_PARAM_VALUE,
ECTL_PARAM_DESC
FROM db_t_ctrl_prod.ECTL_PRGM_PARAM
);


-- Component sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ROW_NUMBER,
$2 as CLAIM_SKEY,
$3 as MRI,
$4 as LR_LINE_L,
$5 as LR_END_L,
$6 as LR_COV_L,
$7 as LR_INO_NOC_L,
$8 as LR_TX_L,
$9 as LR_ACCTNO_L,
$10 as LR_REL_L,
$11 as LR_DPX_L,
$12 as LR_DNO_L,
$13 as LR_DAMT_L,
$14 as LR_IODT_L,
$15 as LR_IODT_L_DATE,
$16 as LR_PCDT_L,
$17 as LR_PCDT_L_DATE,
$18 as LR_VOID_L,
$19 as LR_CLASS_L,
$20 as LR_TEN_L,
$21 as LR_INS_L,
$22 as LR_TIN_L,
$23 as COML_EXPOBASE_L,
$24 as COML_EXPO_L,
$25 as LR_COTPLN_L,
$26 as LR_LIMIT_L,
$27 as LR_DEDUCT_L,
$28 as LR_CNSTR_YR_L,
$29 as LR_CF_POL_NBR_L,
$30 as LR_GB_PAYEE_L,
$31 as LR_GB_INVOICE_PFX_L,
$32 as LR_GB_INVOICE_NBR_L,
$33 as CAT_POOL_CCYY_L,
$34 as CAT_POOL_LEVEL_L,
$35 as CAT_POOL_ACT_DATE_L,
$36 as CAT_POOL_ACT_DATE,
$37 as CAT_POOL_RUN_TYPE_L,
$38 as LOSS_RES_ADJ_L,
$39 as ACT_CD_L,
$40 as DRAFT_CD_L,
$41 as DETN_L,
$42 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
/*
Used for: 	This the source query for Loss reserve core mapping
Purpose: 	For unique combination of Q.CLAIM_SKEY,Q.LINE_CD,Q.TX_CD,Q.DRFT_NBR_PFX,Q.DRFT_NBR,Q.OPENED_DT,Q.DRFT_AMT  mutliple records are allowed in this table
			Also the source sends the whole set of record everyday. This query eliminate the unchanged records.

Logic:		The Minus ALL query will eliminate all the records that exists in Core table from the staging table. 
			The query over the minus query is used to assign a sequence number to the records. The INFORMATION_SCHEMA.columns used in partition by clause is same as in lookup override query. 
			This sequence number is used to select the record from lookup to update. If there is no match in lookup record get inserted. 
*/
select
	ROW_NUMBER() over (partition by Q.CLAIM_SKEY,Q.LR_LINE_L,Q.LR_TX_L,Q.LR_DPX_L,Q.LR_DNO_L,Q.LR_IODT_L,Q.LR_DAMT_L order by LR_IODT_L)
    ,Q.CLAIM_SKEY
	,Q.MRI
	,Q.LR_LINE_L
	,Q.LR_END_L
	,Q.LR_COV_L
	,Q.LR_INO_NOC_L
	,Q.LR_TX_L
	,Q.LR_ACCTNO_L
	,Q.LR_REL_L
	,Q.LR_DPX_L
	,Q.LR_DNO_L
	,Q.LR_DAMT_L
	,Q.LR_IODT_L
	,Q.LR_IODT_L_DATE
	,Q.LR_PCDT_L
	,Q.LR_PCDT_L_DATE
	,Q.LR_VOID_L
	,Q.LR_CLASS_L
	,Q.LR_TEN_L
	,Q.LR_INS_L
	,Q.LR_TIN_L
	,Q.COML_EXPOBASE_L
	,Q.COML_EXPO_L
	,Q.LR_COTPLN_L
	,Q.LR_LIMIT_L
	,Q.LR_DEDUCT_L
	,Q.LR_CNSTR_YR_L
	,Q.LR_CF_POL_NBR_L
	,Q.LR_GB_PAYEE_L
	,Q.LR_GB_INVOICE_PFX_L
	,Q.LR_GB_INVOICE_NBR_L
	,Q.CAT_POOL_CCYY_L
	,Q.CAT_POOL_LEVEL_L
	,Q.CAT_POOL_ACT_DATE_L
	,Q.CAT_POOL_ACT_DATE
	,Q.CAT_POOL_RUN_TYPE_L
	,Q.LOSS_RES_ADJ_L
	,Q.ACT_CD_L
	,Q.DRAFT_CD_L
	,Q.DETN_L
	from 
	(
SELECT	
	 CLM_C.CLAIM_SKEY
	 ,TRIM(LR_S.MRI) MRI
	,LR_S.LR_LINE_L
	,TRIM(LR_S.LR_END_L) LR_END_L
	,LR_S.LR_COV_L
	,LR_S.LR_INO_NOC_L
	,TRIM(LR_S.LR_TX_L) LR_TX_L
	,LR_S.LR_ACCTNO_L
	,TRIM(LR_S.LR_REL_L) LR_REL_L
	,TRIM(LR_S.LR_DPX_L) LR_DPX_L
	,LR_S.LR_DNO_L
	,LR_S.LR_DAMT_L
	,LR_S.LR_IODT_L
	,LR_S.LR_IODT_L_DATE
	,LR_S.LR_PCDT_L
	,LR_S.LR_PCDT_L_DATE
	,TRIM(LR_S.LR_VOID_L) LR_VOID_L
	,TRIM(LR_S.LR_CLASS_L) LR_CLASS_L
	,TRIM(LR_S.LR_TEN_L) LR_TEN_L
	,LR_S.LR_INS_L
	,LR_S.LR_TIN_L
	,TRIM(LR_S.COML_EXPOBASE_L) COML_EXPOBASE_L
	,TRIM(LR_S.COML_EXPO_L) COML_EXPO_L
	,LR_S.LR_COTPLN_L
	,LR_S.LR_LIMIT_L
	,LR_S.LR_DEDUCT_L
	,LR_S.LR_CNSTR_YR_L
	,LR_S.LR_CF_POL_NBR_L
	,LR_S.LR_GB_PAYEE_L
	,TRIM(LR_S.LR_GB_INVOICE_PFX_L) LR_GB_INVOICE_PFX_L
	,LR_S.LR_GB_INVOICE_NBR_L
	,LR_S.CAT_POOL_CCYY_L
	,LR_S.CAT_POOL_LEVEL_L
	,LR_S.CAT_POOL_ACT_DATE_L
	,LR_S.CAT_POOL_ACT_DATE
	,TRIM(LR_S.CAT_POOL_RUN_TYPE_L) CAT_POOL_RUN_TYPE_L
	,TRIM(LR_S.LOSS_RES_ADJ_L) LOSS_RES_ADJ_L
	,TRIM(LR_S.ACT_CD_L) ACT_CD_L
	,TRIM(LR_S.DRAFT_CD_L) DRAFT_CD_L
	,LR_S.DETN_L
FROM	DB_T_STAG_PROD.STG_CLMF_CLM_LOSS_RESERVE_AUTO  LR_S 
left outer join( SELECT DISTINCT  CLAIM_SKEY, PLCY_ST,PLCY_PREFIX, PLCY_NBR,LOSS_DT,SEQ_NBR FROM DB_T_CORE_PROD.CLMF_CLAIM_CORE) CLM_C /*  Join is used to derive CLAIM_SKEY */
	on	CLM_C.PLCY_ST = LR_S.POL_STATE 
	AND	CLM_C.PLCY_PREFIX = LR_S.PFX 
	AND	CLM_C.PLCY_NBR = LR_S.PNO 
	AND	CLM_C.LOSS_DT = LR_S.DATE_O_LOSS 
	AND	CLM_C.SEQ_NBR = LR_S.SEQNO
Minus /*ALL*/
SELECT 
	LR_C.CLAIM_SKEY
	,LR_C.REC_TYPE
	,LR_C.LINE_CD
	,LR_C.END_NBR
	,COVERAGE
	,LR_C.NBR_PAID
	,LR_C.TX_CD
	,LR_C.ACCT_NBR
	,LR_C.RELEASE_CD
	,LR_C.DRFT_NBR_PFX
	,LR_C.DRFT_NBR
	,LR_C.DRFT_AMT
	,LR_C.OPENED_DT
	,LR_C.OPENED_DATE
	,LR_C.CLOSED_DT
	,LR_C.CLOSED_DATE
	,LR_C.VOID_IND
	,LR_C.CLASSIFICATION
	,LR_C.TENANT_CD
	,LR_C.INS_AMT
	,LR_C.TAX_ID
	,LR_C.COML_EXPO_BASE
	,LR_C.COML_EXPO
	,LR_C.COT_PLN
	,LR_C.LR_LIMIT
	,LR_C.DEDUCT_CD
	,LR_C.CNSTR_YR
	,LR_C.CF_PLCY_NBR
	,LR_C.GB_PAYEE
	,LR_C.GB_INVOICE_PFX
	,LR_C.GB_INVOICE_NBR
	,LR_C.CAT_POOL_CCYY
	,LR_C.CAT_POOL_LEVEL
	,LR_C.CAT_POOL_ACT_DT
	,LR_C.CAT_POOL_ACT_DATE
	,LR_C.CAT_POOL_RUN_TYPE
	,LR_C.LOSS_RES_ADJ
	,LR_C.ACT_CD
	,LR_C.DRAFT_CD
	,LR_C.DETAIL_NBR
FROM DB_T_CORE_PROD.CLMF_CLM_LOSS_RESERVE_CORE LR_C JOIN
DB_T_CORE_PROD.CLMF_CLAIM_CORE NO_C ON NO_C.CLAIM_SKEY=LR_C.CLAIM_SKEY AND
(
(CMPY_CD in (40,50,70) and PLCY_PREFIX =70) 
or
(CMPY_CD =10 and PLCY_PREFIX =10) 
)
)Q
) SRC
)
);


-- Component exp_HOLD_SRC, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_HOLD_SRC AS
(
SELECT
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.ROW_NUMBER as ROW_NUMBER,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.CLAIM_SKEY as CLAIM_SKEY,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.MRI as MRI,
LKP_1.ECTL_PARAM_VALUE /* replaced lookup LKP_ECTL_PRGM_PARAM */ as var_CHG_EFF_DT,
TO_DATE ( var_CHG_EFF_DT , ''YYYY-MM-DD'' ) as out_CHG_EFF_DT,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as out_CHG_EXP_DT,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_LINE_L as LR_LINE_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_END_L as LR_END_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_COV_L as LR_COV_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_INO_NOC_L as LR_INO_NOC_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_TX_L as LR_TX_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_ACCTNO_L as LR_ACCTNO_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_REL_L as LR_REL_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_DPX_L as LR_DPX_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_DNO_L as LR_DNO_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_DAMT_L as LR_DAMT_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_IODT_L as LR_IODT_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_IODT_L_DATE as LR_IODT_L_DATE,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_PCDT_L as LR_PCDT_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_PCDT_L_DATE as LR_PCDT_L_DATE,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_VOID_L as LR_VOID_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_CLASS_L as LR_CLASS_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_TEN_L as LR_TEN_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_INS_L as LR_INS_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_TIN_L as LR_TIN_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.COML_EXPOBASE_L as COML_EXPOBASE_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.COML_EXPO_L as COML_EXPO_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_COTPLN_L as LR_COTPLN_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_LIMIT_L as LR_LIMIT_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_DEDUCT_L as LR_DEDUCT_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_CNSTR_YR_L as LR_CNSTR_YR_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_CF_POL_NBR_L as LR_CF_POL_NBR_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_GB_PAYEE_L as LR_GB_PAYEE_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_GB_INVOICE_PFX_L as LR_GB_INVOICE_PFX_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LR_GB_INVOICE_NBR_L as LR_GB_INVOICE_NBR_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.CAT_POOL_CCYY_L as CAT_POOL_CCYY_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.CAT_POOL_LEVEL_L as CAT_POOL_LEVEL_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.CAT_POOL_ACT_DATE_L as CAT_POOL_ACT_DATE_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.CAT_POOL_ACT_DATE as CAT_POOL_ACT_DATE,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.CAT_POOL_RUN_TYPE_L as CAT_POOL_RUN_TYPE_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.LOSS_RES_ADJ_L as LOSS_RES_ADJ_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.ACT_CD_L as ACT_CD_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.DRAFT_CD_L as DRAFT_CD_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.DETN_L as DETN_L,
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.source_record_id,
row_number() over (partition by sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.source_record_id order by sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO.source_record_id) as RNK
FROM
sq_STG_CLMF_CLM_LOSS_RESERVE_AUTO
LEFT JOIN LKP_ECTL_PRGM_PARAM LKP_1 ON LKP_1.ECTL_PARAM_DESC = ''CLAIM MASTER FEED DATE''
QUALIFY RNK = 1
);


-- Component LKP_CLMF_CLM_LOSS_RESERVE_CORE, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_CLMF_CLM_LOSS_RESERVE_CORE AS
(
SELECT
LKP.CLAIM_SKEY_lkp,
LKP.LOSS_RESERVE_SKEY,
LKP.CHG_EFF_DT_lkp,
exp_HOLD_SRC.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_HOLD_SRC.source_record_id ORDER BY LKP.CLAIM_SKEY_lkp asc,LKP.LOSS_RESERVE_SKEY asc,LKP.CHG_EFF_DT_lkp asc) RNK
FROM
exp_HOLD_SRC
LEFT JOIN (
SELECT LR_C.LOSS_RESERVE_SKEY as LOSS_RESERVE_SKEY
	,LR_C.CHG_EFF_DT as CHG_EFF_DT_lkp
	,LR_C.CLAIM_SKEY as CLAIM_SKEY_lkp
	,LR_C.LINE_CD AS LINE_CD
	,LR_C.TX_CD AS TX_CD
	,LR_C.DRFT_NBR_PFX AS DRFT_NBR_PFX
	,LR_C.DRFT_NBR AS  DRFT_NBR
	,LR_C.DRFT_AMT AS DRFT_AMT
	,LR_C.OPENED_DT AS OPENED_DT
	,ROW_NUMBER() OVER (
		PARTITION BY LR_C.CLAIM_SKEY
		,LR_C.LINE_CD
		,LR_C.TX_CD
		,LR_C.DRFT_NBR_PFX
		,LR_C.DRFT_NBR
		,LR_C.OPENED_DT
		,LR_C.DRFT_AMT ORDER BY LR_C.LOSS_RESERVE_SKEY
		) AS ROW_ID
	
FROM (
	SELECT row_number() OVER (
			PARTITION BY LR_C.CLAIM_SKEY
			,LINE_CD
			,END_NBR
			,COVERAGE
			,NBR_PAID
			,TX_CD
			,ACCT_NBR
			,RELEASE_CD
			,DRFT_NBR_PFX
			,DRFT_NBR
			,DRFT_AMT
			,OPENED_DT
			,OPENED_DATE
			,CLOSED_DT
			,CLOSED_DATE
			,VOID_IND
			,CLASSIFICATION
			,TENANT_CD
			,INS_AMT
			,TAX_ID
			,COML_EXPO_BASE
			,COML_EXPO
			,LR_C.COT_PLN
			,LR_LIMIT
			,DEDUCT_CD
			,CNSTR_YR
			,CF_PLCY_NBR
			,GB_PAYEE
			,GB_INVOICE_PFX
			,GB_INVOICE_NBR
			,CAT_POOL_CCYY
			,CAT_POOL_LEVEL
			,CAT_POOL_ACT_DT
			,CAT_POOL_ACT_DATE
			,CAT_POOL_RUN_TYPE
			,LOSS_RES_ADJ
			,ACT_CD
			,DRAFT_CD
			,DETAIL_NBR ORDER BY LOSS_RESERVE_SKEY DESC
			) ID
/* 	,LR_LINE_L */
		,LR_C.CHG_EFF_DT
		,LR_C.CLAIM_SKEY
		,LOSS_RESERVE_SKEY
		,LINE_CD
		,LR_C.REC_TYPE
		,END_NBR
		,COVERAGE
		,NBR_PAID
		,TX_CD
		,ACCT_NBR
		,RELEASE_CD
		,DRFT_NBR_PFX
		,DRFT_NBR
		,DRFT_AMT
		,OPENED_DT
		,OPENED_DATE
		,CLOSED_DT
		,CLOSED_DATE
		,VOID_IND
		,CLASSIFICATION
		,TENANT_CD
		,INS_AMT
		,TAX_ID
		,COML_EXPO_BASE
		,COML_EXPO
		,LR_C.COT_PLN
		,LR_LIMIT
		,DEDUCT_CD
		,CNSTR_YR
		,CF_PLCY_NBR
		,GB_PAYEE
		,GB_INVOICE_PFX
		,GB_INVOICE_NBR
		,CAT_POOL_CCYY
		,CAT_POOL_LEVEL
		,CAT_POOL_ACT_DT
		,CAT_POOL_ACT_DATE
		,CAT_POOL_RUN_TYPE
		,LOSS_RES_ADJ
		,ACT_CD
		,DRAFT_CD
		,DETAIL_NBR
	FROM db_t_core_prod.CLMF_CLM_LOSS_RESERVE_CORE LR_C JOIN
db_t_core_prod.CLMF_CLAIM_CORE NO_C ON NO_C.CLAIM_SKEY=LR_C.CLAIM_SKEY AND
(
(CMPY_CD in (40,50,70) and PLCY_PREFIX =70) 
or
(CMPY_CD =10 and PLCY_PREFIX =10) 
)/*  Join is used to get columns LOSS_RESERVE_SKEY and CHG_EFF_DT */
	WHERE LR_C.CHG_EXP_DT = ''9999/12/31''
	) LR_C
LEFT OUTER JOIN (
	SELECT ROW_NUMBER() OVER (
			PARTITION BY POL_STATE
			,PFX
			,PNO
			,DATE_O_LOSS
			,SEQNO
			,LR_LINE_L
			,LR_END_L
			,LR_COV_L
			,LR_INO_NOC_L
			,LR_TX_L
			,LR_ACCTNO_L
			,LR_REL_L
			,LR_DPX_L
			,LR_DNO_L
			,LR_DAMT_L
			,LR_IODT_L
			,LR_IODT_L_DATE
			,LR_PCDT_L
			,LR_PCDT_L_DATE
			,LR_VOID_L
			,LR_CLASS_L
			,LR_TEN_L
			,LR_INS_L
			,LR_TIN_L
			,COML_EXPOBASE_L
			,COML_EXPO_L
			,LR_COTPLN_L
			,LR_LIMIT_L
			,LR_DEDUCT_L
			,LR_CNSTR_YR_L
			,LR_CF_POL_NBR_L
			,LR_GB_PAYEE_L
			,LR_GB_INVOICE_PFX_L
			,LR_GB_INVOICE_NBR_L
			,CAT_POOL_CCYY_L
			,CAT_POOL_LEVEL_L
			,CAT_POOL_ACT_DATE_L
			,CAT_POOL_ACT_DATE
			,CAT_POOL_RUN_TYPE_L
			,LOSS_RES_ADJ_L
			,ACT_CD_L
			,DRAFT_CD_L
			,DETN_L ORDER BY LR_IODT_L
			) ID
		,POL_STATE
		,PFX
		,PNO
		,DATE_O_LOSS
		,SEQNO
		,MRI
		,LR_LINE_L
		,LR_END_L
		,LR_COV_L
		,LR_INO_NOC_L
		,LR_TX_L
		,LR_ACCTNO_L
		,LR_REL_L
		,LR_DPX_L
		,LR_DNO_L
		,LR_DAMT_L
		,LR_IODT_L
		,LR_IODT_L_DATE
		,LR_PCDT_L
		,LR_PCDT_L_DATE
		,LR_VOID_L
		,LR_CLASS_L
		,LR_TEN_L
		,LR_INS_L
		,LR_TIN_L
		,COML_EXPOBASE_L
		,COML_EXPO_L
		,LR_COTPLN_L
		,LR_LIMIT_L
		,LR_DEDUCT_L
		,LR_CNSTR_YR_L
		,LR_CF_POL_NBR_L
		,LR_GB_PAYEE_L
		,LR_GB_INVOICE_PFX_L
		,LR_GB_INVOICE_NBR_L
		,CAT_POOL_CCYY_L
		,CAT_POOL_LEVEL_L
		,CAT_POOL_ACT_DATE_L
		,CAT_POOL_ACT_DATE
		,CAT_POOL_RUN_TYPE_L
		,LOSS_RES_ADJ_L
		,ACT_CD_L
		,DRAFT_CD_L
		,DETN_L
	FROM db_t_stag_prod.STG_CLMF_CLM_LOSS_RESERVE_AUTO
	) LR_S ON COALESCE(LR_C.LINE_CD, 0) = COALESCE(LR_S.LR_LINE_L, 0)
	AND COALESCE(LR_C.REC_TYPE, '''') = TRIM(COALESCE(LR_S.MRI, ''''))
	AND COALESCE(LR_C.END_NBR, '''') = TRIM(COALESCE(LR_S.LR_END_L, ''''))
	AND COALESCE(LR_C.COVERAGE, 0) = COALESCE(LR_S.LR_COV_L, 0)
	AND COALESCE(LR_C.NBR_PAID, 0) = COALESCE(LR_S.LR_INO_NOC_L, 0)
	AND COALESCE(LR_C.TX_CD, '''') = TRIM(COALESCE(LR_S.LR_TX_L, ''''))
	AND COALESCE(LR_C.ACCT_NBR, 0) = COALESCE(LR_S.LR_ACCTNO_L, 0)
	AND COALESCE(LR_C.RELEASE_CD, '''') = TRIM(COALESCE(LR_S.LR_REL_L, ''''))
	AND COALESCE(LR_C.DRFT_NBR_PFX, '''') = TRIM(COALESCE(LR_S.LR_DPX_L, ''''))
	AND COALESCE(LR_C.DRFT_NBR, 0) = COALESCE(LR_S.LR_DNO_L, 0)
	AND COALESCE(LR_C.DRFT_AMT, 0) = COALESCE(LR_S.LR_DAMT_L, 0)
	AND COALESCE(LR_C.OPENED_DT, 0) = COALESCE(LR_S.LR_IODT_L, 0)
	AND COALESCE(LR_C.OPENED_DATE, CAST(''9999-12-31'' AS DATE)) = COALESCE(LR_S.LR_IODT_L_DATE, CAST(''9999-12-31'' AS DATE))
	AND COALESCE(LR_C.CLOSED_DT, 0) = COALESCE(LR_S.LR_PCDT_L, 0)
	AND COALESCE(LR_C.CLOSED_DATE, CAST(''9999-12-31'' AS DATE)) = COALESCE(LR_S.LR_PCDT_L_DATE, CAST(''9999-12-31'' AS DATE))
	AND COALESCE(LR_C.VOID_IND, '''') = TRIM(COALESCE(LR_S.LR_VOID_L, ''''))
	AND COALESCE(LR_C.CLASSIFICATION, '''') = TRIM(COALESCE(LR_S.LR_CLASS_L, ''''))
	AND COALESCE(LR_C.TENANT_CD, '''') = TRIM(COALESCE(LR_S.LR_TEN_L, ''''))
	AND COALESCE(LR_C.INS_AMT, 0) = COALESCE(LR_S.LR_INS_L, 0)
	AND COALESCE(LR_C.TAX_ID, 0) = COALESCE(LR_S.LR_TIN_L, 0)
	AND COALESCE(LR_C.COML_EXPO_BASE, '''') = TRIM(COALESCE(LR_S.COML_EXPOBASE_L, ''''))
	AND COALESCE(LR_C.COML_EXPO, '''') = TRIM(COALESCE(LR_S.COML_EXPO_L, ''''))
	AND COALESCE(LR_C.COT_PLN, 0) = COALESCE(LR_S.LR_COTPLN_L, 0)
	AND COALESCE(LR_C.LR_LIMIT, 0) = COALESCE(LR_S.LR_LIMIT_L, 0)
	AND COALESCE(LR_C.DEDUCT_CD, 0) = COALESCE(LR_S.LR_DEDUCT_L, 0)
	AND COALESCE(LR_C.CNSTR_YR, 0) = COALESCE(LR_S.LR_CNSTR_YR_L, 0)
	AND COALESCE(LR_C.CF_PLCY_NBR, 0) = COALESCE(LR_S.LR_CF_POL_NBR_L, 0)
	AND COALESCE(LR_C.GB_PAYEE, 0) = COALESCE(LR_S.LR_GB_PAYEE_L, 0)
	AND COALESCE(LR_C.GB_INVOICE_PFX, '''') = TRIM(COALESCE(LR_S.LR_GB_INVOICE_PFX_L, ''''))
	AND COALESCE(LR_C.GB_INVOICE_NBR, 0) = COALESCE(LR_S.LR_GB_INVOICE_NBR_L, 0)
	AND COALESCE(LR_C.CAT_POOL_CCYY, 0) = COALESCE(LR_S.CAT_POOL_CCYY_L, 0)
	AND COALESCE(LR_C.CAT_POOL_LEVEL, 0) = COALESCE(LR_S.CAT_POOL_LEVEL_L, 0)
	AND COALESCE(LR_C.CAT_POOL_ACT_DT, 0) = COALESCE(LR_S.CAT_POOL_ACT_DATE_L, 0)
	AND COALESCE(LR_C.CAT_POOL_ACT_DATE, CAST(''9999-12-31'' AS DATE)) = COALESCE(LR_S.CAT_POOL_ACT_DATE, CAST(''9999-12-31'' AS DATE))
	AND COALESCE(LR_C.CAT_POOL_RUN_TYPE, '''') = TRIM(COALESCE(LR_S.CAT_POOL_RUN_TYPE_L, ''''))
	AND COALESCE(LR_C.LOSS_RES_ADJ, '''') = TRIM(COALESCE(LR_S.LOSS_RES_ADJ_L, ''''))
	AND COALESCE(LR_C.ACT_CD, '''') = TRIM(COALESCE(LR_S.ACT_CD_L, ''''))
	AND COALESCE(LR_C.DRAFT_CD, '''') = TRIM(COALESCE(LR_S.DRAFT_CD_L, ''''))
	AND COALESCE(LR_C.DETAIL_NBR, 0) = COALESCE(LR_S.DETN_L, 0)
	AND LR_C.ID = LR_S.ID
WHERE LR_S.POL_STATE IS NULL
	AND LR_S.PFX IS NULL
	AND LR_S.PNO IS NULL
	AND LR_S.DATE_O_LOSS IS NULL
	AND LR_S.SEQNO IS NULL
----------------------------------------------------------------------------------------------------------/*  */
/* Used for:	This the look up override query to be used in claims core load mapping */
/* Purpose:	This look up will help to find out if record exists in the core table before deciding whether to update or insert the source record */
/* 			For unique combination of Q.CLAIM_SKEY,Q.LINE_CD,Q.TX_CD,Q.DRFT_NBR_PFX,Q.DRFT_NBR,Q.OPENED_DT,Q.DRFT_AMT  mutliple records are allowed in this  table */
/* 			In a bunch of record of same unique key values if two record changes, two of them should be updated in core as well and rest should be left untouched */
/* 			 */
/* Logic:		The active records from the Loss reserve core is selected in the first part of join in subquery */
/* 			Filter on CMPY_CD and PLCY_PREFIX combination is used to filter the records for each Line of Business */
/* 			The outer join and filter eliminate the records that match exactly with staging and selects only the records that has some change in source */
/* 			In the selected record more than one will have same combination of Q.CLAIM_SKEY,Q.LINE_CD,Q.TX_CD,Q.DRFT_NBR_PFX,Q.DRFT_NBR,Q.OPENED_DT,Q.DRFT_AMT */
/* 			If the same key combination is used in look up condition only one record will be selected always and will be updated multiple times in same load/run if there are more than one record has changes to be updated for the combination */
/* 			The row_number function assigns a sequence number to the selected records. This source records also will be numbered similarly. These will be used in selecting each of the changed record from core table and updating them.  */
/* 			A similar sequence number is used in the outer join in the subquery for the same purpose. */
---------------------------------------------------------------------------------------------------------/*  */
) LKP ON LKP.CLAIM_SKEY_lkp = exp_HOLD_SRC.CLAIM_SKEY AND LKP.LINE_CD = exp_HOLD_SRC.LR_LINE_L AND LKP.TX_CD = exp_HOLD_SRC.LR_TX_L AND LKP.DRFT_NBR_PFX = exp_HOLD_SRC.LR_DPX_L AND LKP.DRFT_NBR = exp_HOLD_SRC.LR_DNO_L AND LKP.DRFT_AMT = exp_HOLD_SRC.LR_DAMT_L AND LKP.OPENED_DT = exp_HOLD_SRC.LR_IODT_L AND LKP.ROW_ID = exp_HOLD_SRC.ROW_NUMBER
QUALIFY RNK = 1
);


-- Component exp_CHECK, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CHECK AS
(
SELECT
LKP_CLMF_CLM_LOSS_RESERVE_CORE.LOSS_RESERVE_SKEY as LOSS_RESERVE_SKEY,
exp_HOLD_SRC.MRI as MRI,
exp_HOLD_SRC.LR_LINE_L as LR_LINE_L,
exp_HOLD_SRC.LR_END_L as LR_END_L,
exp_HOLD_SRC.LR_COV_L as LR_COV_L,
exp_HOLD_SRC.LR_INO_NOC_L as LR_INO_NOC_L,
exp_HOLD_SRC.LR_TX_L as LR_TX_L,
exp_HOLD_SRC.LR_ACCTNO_L as LR_ACCTNO_L,
exp_HOLD_SRC.LR_REL_L as LR_REL_L,
exp_HOLD_SRC.LR_DPX_L as LR_DPX_L,
exp_HOLD_SRC.LR_DNO_L as LR_DNO_L,
exp_HOLD_SRC.LR_DAMT_L as LR_DAMT_L,
exp_HOLD_SRC.LR_IODT_L as LR_IODT_L,
exp_HOLD_SRC.LR_IODT_L_DATE as LR_IODT_L_DATE,
exp_HOLD_SRC.LR_PCDT_L as LR_PCDT_L,
exp_HOLD_SRC.LR_PCDT_L_DATE as LR_PCDT_L_DATE,
exp_HOLD_SRC.LR_VOID_L as LR_VOID_L,
exp_HOLD_SRC.LR_CLASS_L as LR_CLASS_L,
exp_HOLD_SRC.LR_TEN_L as LR_TEN_L,
exp_HOLD_SRC.LR_INS_L as LR_INS_L,
exp_HOLD_SRC.LR_TIN_L as LR_TIN_L,
exp_HOLD_SRC.COML_EXPOBASE_L as COML_EXPOBASE_L,
exp_HOLD_SRC.COML_EXPO_L as COML_EXPO_L,
exp_HOLD_SRC.LR_COTPLN_L as LR_COTPLN_L,
exp_HOLD_SRC.LR_LIMIT_L as LR_LIMIT_L,
exp_HOLD_SRC.LR_DEDUCT_L as LR_DEDUCT_L,
exp_HOLD_SRC.LR_CNSTR_YR_L as LR_CNSTR_YR_L,
exp_HOLD_SRC.LR_CF_POL_NBR_L as LR_CF_POL_NBR_L,
exp_HOLD_SRC.LR_GB_PAYEE_L as LR_GB_PAYEE_L,
exp_HOLD_SRC.LR_GB_INVOICE_PFX_L as LR_GB_INVOICE_PFX_L,
exp_HOLD_SRC.LR_GB_INVOICE_NBR_L as LR_GB_INVOICE_NBR_L,
exp_HOLD_SRC.CAT_POOL_CCYY_L as CAT_POOL_CCYY_L,
exp_HOLD_SRC.CAT_POOL_LEVEL_L as CAT_POOL_LEVEL_L,
exp_HOLD_SRC.CAT_POOL_ACT_DATE_L as CAT_POOL_ACT_DATE_L,
exp_HOLD_SRC.CAT_POOL_ACT_DATE as CAT_POOL_ACT_DATE1,
exp_HOLD_SRC.CAT_POOL_RUN_TYPE_L as CAT_POOL_RUN_TYPE_L,
exp_HOLD_SRC.LOSS_RES_ADJ_L as LOSS_RES_ADJ_L,
exp_HOLD_SRC.ACT_CD_L as ACT_CD_L,
exp_HOLD_SRC.DRAFT_CD_L as DRAFT_CD_L,
exp_HOLD_SRC.DETN_L as DETN_L,
LTRIM ( RTRIM ( :PMMappingName ) ) as in_PRGM_NM,
:ACT_PROJ_ID as in_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as in_BATCH_ACTIVE_IND,
:TABLE_NM as in_TABLE_NM,
exp_HOLD_SRC.out_CHG_EFF_DT as out_CHG_EFF_DT,
exp_HOLD_SRC.out_CHG_EXP_DT as out_CHG_EXP_DT,
LKP_CLMF_CLM_LOSS_RESERVE_CORE.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp,
exp_HOLD_SRC.CLAIM_SKEY as CLAIM_SKEY,
exp_HOLD_SRC.source_record_id
FROM
exp_HOLD_SRC
INNER JOIN LKP_CLMF_CLM_LOSS_RESERVE_CORE ON exp_HOLD_SRC.source_record_id = LKP_CLMF_CLM_LOSS_RESERVE_CORE.source_record_id
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''exp_CHECK'');


-- Component rtr_INS_UPD_INS, Type ROUTER Output Group INS
create or replace temporary table rtr_INS_UPD_INS as
SELECT
exp_CHECK.MRI as MRI,
exp_CHECK.LR_LINE_L as LR_LINE_L,
exp_CHECK.LR_END_L as LR_END_L,
exp_CHECK.LR_COV_L as LR_COV_L,
exp_CHECK.LR_INO_NOC_L as LR_INO_NOC_L,
exp_CHECK.LR_TX_L as LR_TX_L,
exp_CHECK.LR_ACCTNO_L as LR_ACCTNO_L,
exp_CHECK.LR_REL_L as LR_REL_L,
exp_CHECK.LR_DPX_L as LR_DPX_L,
exp_CHECK.LR_DNO_L as LR_DNO_L,
exp_CHECK.LR_DAMT_L as LR_DAMT_L,
exp_CHECK.LR_IODT_L as LR_IODT_L,
exp_CHECK.LR_IODT_L_DATE as LR_IODT_L_DATE,
exp_CHECK.LR_PCDT_L as LR_PCDT_L,
exp_CHECK.LR_PCDT_L_DATE as LR_PCDT_L_DATE,
exp_CHECK.LR_VOID_L as LR_VOID_L,
exp_CHECK.LR_CLASS_L as LR_CLASS_L,
exp_CHECK.LR_TEN_L as LR_TEN_L,
exp_CHECK.LR_INS_L as LR_INS_L,
exp_CHECK.LR_TIN_L as LR_TIN_L,
exp_CHECK.COML_EXPOBASE_L as COML_EXPOBASE_L,
exp_CHECK.COML_EXPO_L as COML_EXPO_L,
exp_CHECK.LR_COTPLN_L as LR_COTPLN_L,
exp_CHECK.LR_LIMIT_L as LR_LIMIT_L,
exp_CHECK.LR_DEDUCT_L as LR_DEDUCT_L,
exp_CHECK.LR_CNSTR_YR_L as LR_CNSTR_YR_L,
exp_CHECK.LR_CF_POL_NBR_L as LR_CF_POL_NBR_L,
exp_CHECK.LR_GB_PAYEE_L as LR_GB_PAYEE_L,
exp_CHECK.LR_GB_INVOICE_PFX_L as LR_GB_INVOICE_PFX_L,
exp_CHECK.LR_GB_INVOICE_NBR_L as LR_GB_INVOICE_NBR_L,
exp_CHECK.CAT_POOL_CCYY_L as CAT_POOL_CCYY_L,
exp_CHECK.CAT_POOL_LEVEL_L as CAT_POOL_LEVEL_L,
exp_CHECK.CAT_POOL_ACT_DATE_L as CAT_POOL_ACT_DATE_L,
exp_CHECK.CAT_POOL_ACT_DATE1 as CAT_POOL_ACT_DATE1,
exp_CHECK.CAT_POOL_RUN_TYPE_L as CAT_POOL_RUN_TYPE_L,
exp_CHECK.LOSS_RES_ADJ_L as LOSS_RES_ADJ_L,
exp_CHECK.ACT_CD_L as ACT_CD_L,
exp_CHECK.DRAFT_CD_L as DRAFT_CD_L,
exp_CHECK.DETN_L as DETN_L,
exp_CHECK.out_CHG_EFF_DT as out_CHG_EFF_DT,
exp_CHECK.out_CHG_EXP_DT as out_CHG_EXP_DT,
exp_CHECK.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
exp_CHECK.LOSS_RESERVE_SKEY as LOSS_RESERVE_SKEY,
exp_CHECK.CLAIM_SKEY as CLAIM_SKEY4,
exp_CHECK.source_record_id
FROM
exp_CHECK
LEFT JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_CHECK.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
WHERE exp_CHECK.LOSS_RESERVE_SKEY IS NULL;


-- Component rtr_INS_UPD_UPD, Type ROUTER Output Group UPD
create or replace temporary table rtr_INS_UPD_UPD as
SELECT
exp_CHECK.MRI as MRI,
exp_CHECK.LR_LINE_L as LR_LINE_L,
exp_CHECK.LR_END_L as LR_END_L,
exp_CHECK.LR_COV_L as LR_COV_L,
exp_CHECK.LR_INO_NOC_L as LR_INO_NOC_L,
exp_CHECK.LR_TX_L as LR_TX_L,
exp_CHECK.LR_ACCTNO_L as LR_ACCTNO_L,
exp_CHECK.LR_REL_L as LR_REL_L,
exp_CHECK.LR_DPX_L as LR_DPX_L,
exp_CHECK.LR_DNO_L as LR_DNO_L,
exp_CHECK.LR_DAMT_L as LR_DAMT_L,
exp_CHECK.LR_IODT_L as LR_IODT_L,
exp_CHECK.LR_IODT_L_DATE as LR_IODT_L_DATE,
exp_CHECK.LR_PCDT_L as LR_PCDT_L,
exp_CHECK.LR_PCDT_L_DATE as LR_PCDT_L_DATE,
exp_CHECK.LR_VOID_L as LR_VOID_L,
exp_CHECK.LR_CLASS_L as LR_CLASS_L,
exp_CHECK.LR_TEN_L as LR_TEN_L,
exp_CHECK.LR_INS_L as LR_INS_L,
exp_CHECK.LR_TIN_L as LR_TIN_L,
exp_CHECK.COML_EXPOBASE_L as COML_EXPOBASE_L,
exp_CHECK.COML_EXPO_L as COML_EXPO_L,
exp_CHECK.LR_COTPLN_L as LR_COTPLN_L,
exp_CHECK.LR_LIMIT_L as LR_LIMIT_L,
exp_CHECK.LR_DEDUCT_L as LR_DEDUCT_L,
exp_CHECK.LR_CNSTR_YR_L as LR_CNSTR_YR_L,
exp_CHECK.LR_CF_POL_NBR_L as LR_CF_POL_NBR_L,
exp_CHECK.LR_GB_PAYEE_L as LR_GB_PAYEE_L,
exp_CHECK.LR_GB_INVOICE_PFX_L as LR_GB_INVOICE_PFX_L,
exp_CHECK.LR_GB_INVOICE_NBR_L as LR_GB_INVOICE_NBR_L,
exp_CHECK.CAT_POOL_CCYY_L as CAT_POOL_CCYY_L,
exp_CHECK.CAT_POOL_LEVEL_L as CAT_POOL_LEVEL_L,
exp_CHECK.CAT_POOL_ACT_DATE_L as CAT_POOL_ACT_DATE_L,
exp_CHECK.CAT_POOL_ACT_DATE1 as CAT_POOL_ACT_DATE1,
exp_CHECK.CAT_POOL_RUN_TYPE_L as CAT_POOL_RUN_TYPE_L,
exp_CHECK.LOSS_RES_ADJ_L as LOSS_RES_ADJ_L,
exp_CHECK.ACT_CD_L as ACT_CD_L,
exp_CHECK.DRAFT_CD_L as DRAFT_CD_L,
exp_CHECK.DETN_L as DETN_L,
exp_CHECK.out_CHG_EFF_DT as out_CHG_EFF_DT,
exp_CHECK.out_CHG_EXP_DT as out_CHG_EXP_DT,
exp_CHECK.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
exp_CHECK.LOSS_RESERVE_SKEY as LOSS_RESERVE_SKEY,
exp_CHECK.CLAIM_SKEY as CLAIM_SKEY4,
exp_CHECK.source_record_id
FROM
exp_CHECK
LEFT JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_CHECK.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
WHERE exp_CHECK.LOSS_RESERVE_SKEY IS NOT NULL;


-- Component exp_UPD, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_UPD AS
(
SELECT
rtr_INS_UPD_UPD.CLAIM_SKEY4 as CLAIM_SKEY_lkp3,
rtr_INS_UPD_UPD.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID3,
rtr_INS_UPD_UPD.out_ORIG_INS_TS as out_ORIG_INS_TS3,
rtr_INS_UPD_UPD.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE3,
''UPD'' as out_CHECK3,
dateadd (day, -1, rtr_INS_UPD_UPD.out_CHG_EFF_DT  ) as out_CHG_EXP_DT,
CURRENT_TIMESTAMP as out_ECTL_END_DATE,
rtr_INS_UPD_UPD.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp3,
rtr_INS_UPD_UPD.LOSS_RESERVE_SKEY as LOSS_RESERVE_SKEY3,
rtr_INS_UPD_UPD.source_record_id
FROM
rtr_INS_UPD_UPD
);


-- Component exp_INS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_INS AS
(
SELECT
rtr_INS_UPD_INS.CLAIM_SKEY4 as CLAIM_SKEY1,
rtr_INS_UPD_INS.out_CHG_EFF_DT as CHG_EFF_DT,
rtr_INS_UPD_INS.out_CHG_EXP_DT as CHG_EXP_DT,
rtr_INS_UPD_INS.MRI as MRI1,
rtr_INS_UPD_INS.LR_LINE_L as LR_LINE_L1,
rtr_INS_UPD_INS.LR_END_L as LR_END_L1,
rtr_INS_UPD_INS.LR_COV_L as LR_COV_L1,
rtr_INS_UPD_INS.LR_INO_NOC_L as LR_INO_NOC_L1,
rtr_INS_UPD_INS.LR_TX_L as LR_TX_L1,
rtr_INS_UPD_INS.LR_ACCTNO_L as LR_ACCTNO_L1,
rtr_INS_UPD_INS.LR_REL_L as LR_REL_L1,
rtr_INS_UPD_INS.LR_DPX_L as LR_DPX_L1,
rtr_INS_UPD_INS.LR_DNO_L as LR_DNO_L1,
rtr_INS_UPD_INS.LR_DAMT_L as LR_DAMT_L1,
rtr_INS_UPD_INS.LR_IODT_L as LR_IODT_L1,
rtr_INS_UPD_INS.LR_IODT_L_DATE as LR_IODT_L_DATE1,
rtr_INS_UPD_INS.LR_PCDT_L as LR_PCDT_L1,
rtr_INS_UPD_INS.LR_PCDT_L_DATE as LR_PCDT_L_DATE1,
rtr_INS_UPD_INS.LR_VOID_L as LR_VOID_L1,
rtr_INS_UPD_INS.LR_CLASS_L as LR_CLASS_L1,
rtr_INS_UPD_INS.LR_TEN_L as LR_TEN_L1,
rtr_INS_UPD_INS.LR_INS_L as LR_INS_L1,
rtr_INS_UPD_INS.LR_TIN_L as LR_TIN_L1,
rtr_INS_UPD_INS.COML_EXPOBASE_L as COML_EXPOBASE_L1,
rtr_INS_UPD_INS.COML_EXPO_L as COML_EXPO_L1,
rtr_INS_UPD_INS.LR_COTPLN_L as LR_COTPLN_L1,
rtr_INS_UPD_INS.LR_LIMIT_L as LR_LIMIT_L1,
rtr_INS_UPD_INS.LR_DEDUCT_L as LR_DEDUCT_L1,
rtr_INS_UPD_INS.LR_CNSTR_YR_L as LR_CNSTR_YR_L1,
rtr_INS_UPD_INS.LR_CF_POL_NBR_L as LR_CF_POL_NBR_L1,
rtr_INS_UPD_INS.LR_GB_PAYEE_L as LR_GB_PAYEE_L1,
rtr_INS_UPD_INS.LR_GB_INVOICE_PFX_L as LR_GB_INVOICE_PFX_L1,
rtr_INS_UPD_INS.LR_GB_INVOICE_NBR_L as LR_GB_INVOICE_NBR_L1,
rtr_INS_UPD_INS.CAT_POOL_CCYY_L as CAT_POOL_CCYY_L1,
rtr_INS_UPD_INS.CAT_POOL_LEVEL_L as CAT_POOL_LEVEL_L1,
rtr_INS_UPD_INS.CAT_POOL_ACT_DATE_L as CAT_POOL_ACT_DATE_L1,
rtr_INS_UPD_INS.CAT_POOL_ACT_DATE1 as CAT_POOL_ACT_DATE11,
rtr_INS_UPD_INS.CAT_POOL_RUN_TYPE_L as CAT_POOL_RUN_TYPE_L1,
rtr_INS_UPD_INS.LOSS_RES_ADJ_L as LOSS_RES_ADJ_L1,
rtr_INS_UPD_INS.ACT_CD_L as ACT_CD_L1,
rtr_INS_UPD_INS.DRAFT_CD_L as DRAFT_CD_L1,
rtr_INS_UPD_INS.DETN_L as DETN_L1,
rtr_INS_UPD_INS.out_ECTL_PRGM_ID as ECTL_PRGM_ID1,
rtr_INS_UPD_INS.out_ECTL_SRC_ID as ECTL_SRC_ID1,
rtr_INS_UPD_INS.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID1,
rtr_INS_UPD_INS.out_ECTL_BATCH_ID as ECTL_BATCH_ID1,
rtr_INS_UPD_INS.out_ORIG_INS_TS as ORIG_INS_TS1,
rtr_INS_UPD_INS.out_ECTL_BATCH_START_DATE as ECTL_BATCH_START_DATE1,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as ECTL_END_DATE,
''NEW'' as out_CHECK,
rtr_INS_UPD_INS.source_record_id
FROM
rtr_INS_UPD_INS
);


-- Component exp_UPD_INS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_UPD_INS AS
(
SELECT
rtr_INS_UPD_UPD.CLAIM_SKEY4 as CLAIM_SKEY_lkp3,
rtr_INS_UPD_UPD.MRI as MRI3,
rtr_INS_UPD_UPD.LR_LINE_L as LR_LINE_L3,
rtr_INS_UPD_UPD.LR_END_L as LR_END_L3,
rtr_INS_UPD_UPD.LR_COV_L as LR_COV_L3,
rtr_INS_UPD_UPD.LR_INO_NOC_L as LR_INO_NOC_L3,
rtr_INS_UPD_UPD.LR_TX_L as LR_TX_L3,
rtr_INS_UPD_UPD.LR_ACCTNO_L as LR_ACCTNO_L3,
rtr_INS_UPD_UPD.LR_REL_L as LR_REL_L3,
rtr_INS_UPD_UPD.LR_DPX_L as LR_DPX_L3,
rtr_INS_UPD_UPD.LR_DNO_L as LR_DNO_L3,
rtr_INS_UPD_UPD.LR_DAMT_L as LR_DAMT_L3,
rtr_INS_UPD_UPD.LR_IODT_L as LR_IODT_L3,
rtr_INS_UPD_UPD.LR_IODT_L_DATE as LR_IODT_L_DATE3,
rtr_INS_UPD_UPD.LR_PCDT_L as LR_PCDT_L3,
rtr_INS_UPD_UPD.LR_PCDT_L_DATE as LR_PCDT_L_DATE3,
rtr_INS_UPD_UPD.LR_VOID_L as LR_VOID_L3,
rtr_INS_UPD_UPD.LR_CLASS_L as LR_CLASS_L3,
rtr_INS_UPD_UPD.LR_TEN_L as LR_TEN_L3,
rtr_INS_UPD_UPD.LR_INS_L as LR_INS_L3,
rtr_INS_UPD_UPD.LR_TIN_L as LR_TIN_L3,
rtr_INS_UPD_UPD.COML_EXPOBASE_L as COML_EXPOBASE_L3,
rtr_INS_UPD_UPD.COML_EXPO_L as COML_EXPO_L3,
rtr_INS_UPD_UPD.LR_COTPLN_L as LR_COTPLN_L3,
rtr_INS_UPD_UPD.LR_LIMIT_L as LR_LIMIT_L3,
rtr_INS_UPD_UPD.LR_DEDUCT_L as LR_DEDUCT_L3,
rtr_INS_UPD_UPD.LR_CNSTR_YR_L as LR_CNSTR_YR_L3,
rtr_INS_UPD_UPD.LR_CF_POL_NBR_L as LR_CF_POL_NBR_L3,
rtr_INS_UPD_UPD.LR_GB_PAYEE_L as LR_GB_PAYEE_L3,
rtr_INS_UPD_UPD.LR_GB_INVOICE_PFX_L as LR_GB_INVOICE_PFX_L3,
rtr_INS_UPD_UPD.LR_GB_INVOICE_NBR_L as LR_GB_INVOICE_NBR_L3,
rtr_INS_UPD_UPD.CAT_POOL_CCYY_L as CAT_POOL_CCYY_L3,
rtr_INS_UPD_UPD.CAT_POOL_LEVEL_L as CAT_POOL_LEVEL_L3,
rtr_INS_UPD_UPD.CAT_POOL_ACT_DATE_L as CAT_POOL_ACT_DATE_L3,
rtr_INS_UPD_UPD.CAT_POOL_ACT_DATE1 as CAT_POOL_ACT_DATE13,
rtr_INS_UPD_UPD.CAT_POOL_RUN_TYPE_L as CAT_POOL_RUN_TYPE_L3,
rtr_INS_UPD_UPD.LOSS_RES_ADJ_L as LOSS_RES_ADJ_L3,
rtr_INS_UPD_UPD.ACT_CD_L as ACT_CD_L3,
rtr_INS_UPD_UPD.DRAFT_CD_L as DRAFT_CD_L3,
rtr_INS_UPD_UPD.DETN_L as DETN_L3,
rtr_INS_UPD_UPD.out_CHG_EFF_DT as out_CHG_EFF_DT3,
rtr_INS_UPD_UPD.out_CHG_EXP_DT as out_CHG_EXP_DT31,
rtr_INS_UPD_UPD.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID31,
rtr_INS_UPD_UPD.out_ECTL_SRC_ID as out_ECTL_SRC_ID31,
rtr_INS_UPD_UPD.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID31,
rtr_INS_UPD_UPD.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID31,
rtr_INS_UPD_UPD.out_ORIG_INS_TS as out_ORIG_INS_TS31,
rtr_INS_UPD_UPD.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE31,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as out_ECTL_END_DATE,
''NEW'' as out_TX_CD,
rtr_INS_UPD_UPD.LOSS_RESERVE_SKEY as LOSS_RESERVE_SKEY3,
rtr_INS_UPD_UPD.source_record_id
FROM
rtr_INS_UPD_UPD
);


-- Component CLMF_CLM_LOSS_RESERVE_COR_INS, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE CLMF_CLM_LOSS_RESERVE_COR_INS AS
(
SELECT
seq_SKEY_GEN.NEXTVAL as LOSS_RESERVE_SKEY,
exp_INS.CLAIM_SKEY1 as CLAIM_SKEY,
exp_INS.CHG_EFF_DT as CHG_EFF_DT,
exp_INS.CHG_EXP_DT as CHG_EXP_DT,
exp_INS.MRI1 as REC_TYPE,
exp_INS.LR_LINE_L1 as LINE_CD,
exp_INS.LR_END_L1 as END_NBR,
exp_INS.LR_COV_L1 as COVERAGE,
exp_INS.LR_INO_NOC_L1 as NBR_PAID,
exp_INS.LR_TX_L1 as TX_CD,
exp_INS.LR_ACCTNO_L1 as ACCT_NBR,
exp_INS.LR_REL_L1 as RELEASE_CD,
exp_INS.LR_DPX_L1 as DRFT_NBR_PFX,
exp_INS.LR_DNO_L1 as DRFT_NBR,
exp_INS.LR_DAMT_L1 as DRFT_AMT,
exp_INS.LR_IODT_L1 as OPENED_DT,
exp_INS.LR_IODT_L_DATE1 as OPENED_DATE,
exp_INS.LR_PCDT_L1 as CLOSED_DT,
exp_INS.LR_PCDT_L_DATE1 as CLOSED_DATE,
exp_INS.LR_VOID_L1 as VOID_IND,
exp_INS.LR_CLASS_L1 as CLASSIFICATION,
exp_INS.LR_TEN_L1 as TENANT_CD,
exp_INS.LR_INS_L1 as INS_AMT,
exp_INS.LR_TIN_L1 as TAX_ID,
exp_INS.COML_EXPOBASE_L1 as COML_EXPO_BASE,
exp_INS.COML_EXPO_L1 as COML_EXPO,
exp_INS.LR_COTPLN_L1 as COT_PLN,
exp_INS.LR_LIMIT_L1 as LR_LIMIT,
exp_INS.LR_DEDUCT_L1 as DEDUCT_CD,
exp_INS.LR_CNSTR_YR_L1 as CNSTR_YR,
exp_INS.LR_CF_POL_NBR_L1 as CF_PLCY_NBR,
exp_INS.LR_GB_PAYEE_L1 as GB_PAYEE,
exp_INS.LR_GB_INVOICE_PFX_L1 as GB_INVOICE_PFX,
exp_INS.LR_GB_INVOICE_NBR_L1 as GB_INVOICE_NBR,
exp_INS.CAT_POOL_CCYY_L1 as CAT_POOL_CCYY,
exp_INS.CAT_POOL_LEVEL_L1 as CAT_POOL_LEVEL,
exp_INS.CAT_POOL_ACT_DATE_L1 as CAT_POOL_ACT_DT,
exp_INS.CAT_POOL_ACT_DATE11 as CAT_POOL_ACT_DATE,
exp_INS.CAT_POOL_RUN_TYPE_L1 as CAT_POOL_RUN_TYPE,
exp_INS.LOSS_RES_ADJ_L1 as LOSS_RES_ADJ,
exp_INS.ACT_CD_L1 as ACT_CD,
exp_INS.DRAFT_CD_L1 as DRAFT_CD,
exp_INS.DETN_L1 as DETAIL_NBR,
exp_INS.ECTL_BATCH_ID1 as ECTL_BATCH_ID,
exp_INS.ORIG_INS_TS1 as ECTL_ORIG_INS_TS,
exp_INS.ORIG_INS_TS1 as ECTL_MODIFY_TS,
exp_INS.ECTL_SRC_ID1 as ECTL_SRC_ID,
exp_INS.ECTL_SRC_INST_ID1 as ECTL_SRC_INST_ID,
exp_INS.ECTL_PRGM_ID1 as ECTL_PRGM_ID,
exp_INS.out_CHECK as ECTL_TX_CD,
exp_INS.ECTL_BATCH_START_DATE1 as ECTL_START_DATE,
exp_INS.ECTL_END_DATE as ECTL_END_DATE
FROM
exp_INS
);

copy into @public.edw_stage/CLMF_CLM_LOSS_RESERVE_COR_INS from (select * from CLMF_CLM_LOSS_RESERVE_COR_INS)
header=true
overwrite=true;

-- Component CLMF_CLM_LOSS_RESERVE_COR_INS, Type EXPORT_DATA Exporting data
;


-- Component upd_TARGET, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_TARGET AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
exp_UPD.CLAIM_SKEY_lkp3 as CLAIM_SKEY_lkp3,
exp_UPD.out_CHECK3 as out_CHECK3,
exp_UPD.out_ECTL_BATCH_ID3 as out_ECTL_BATCH_ID3,
exp_UPD.out_ORIG_INS_TS3 as out_ORIG_INS_TS3,
exp_UPD.out_CHG_EXP_DT as out_CHG_EXP_DT,
exp_UPD.out_ECTL_END_DATE as out_ECTL_END_DATE,
exp_UPD.CHG_EFF_DT_lkp3 as CHG_EFF_DT_lkp3,
exp_UPD.LOSS_RESERVE_SKEY3 as LOSS_RESERVE_SKEY3,
exp_UPD.out_ECTL_BATCH_START_DATE3 as out_ECTL_BATCH_START_DATE3,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_UPD
);


-- Component CLMF_CLM_LOSS_RESERVE_CORE_UPD_INS, Type TARGET 
INSERT INTO DB_T_CORE_PROD.CLMF_CLM_LOSS_RESERVE_CORE
(
LOSS_RESERVE_SKEY,
CLAIM_SKEY,
CHG_EFF_DT,
CHG_EXP_DT,
REC_TYPE,
LINE_CD,
END_NBR,
COVERAGE,
NBR_PAID,
TX_CD,
ACCT_NBR,
RELEASE_CD,
DRFT_NBR_PFX,
DRFT_NBR,
DRFT_AMT,
OPENED_DT,
OPENED_DATE,
CLOSED_DT,
CLOSED_DATE,
VOID_IND,
CLASSIFICATION,
TENANT_CD,
INS_AMT,
TAX_ID,
COML_EXPO_BASE,
COML_EXPO,
COT_PLN,
LR_LIMIT,
DEDUCT_CD,
CNSTR_YR,
CF_PLCY_NBR,
GB_PAYEE,
GB_INVOICE_PFX,
GB_INVOICE_NBR,
CAT_POOL_CCYY,
CAT_POOL_LEVEL,
CAT_POOL_ACT_DT,
CAT_POOL_ACT_DATE,
CAT_POOL_RUN_TYPE,
LOSS_RES_ADJ,
ACT_CD,
DRAFT_CD,
DETAIL_NBR,
ECTL_BATCH_ID,
ECTL_ORIG_INS_TS,
ECTL_MODIFY_TS,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_PRGM_ID,
ECTL_TX_CD,
ECTL_START_DATE,
ECTL_END_DATE
)
SELECT
exp_UPD_INS.LOSS_RESERVE_SKEY3 as LOSS_RESERVE_SKEY,
exp_UPD_INS.CLAIM_SKEY_lkp3 as CLAIM_SKEY,
exp_UPD_INS.out_CHG_EFF_DT3 as CHG_EFF_DT,
exp_UPD_INS.out_CHG_EXP_DT31 as CHG_EXP_DT,
exp_UPD_INS.MRI3 as REC_TYPE,
exp_UPD_INS.LR_LINE_L3 as LINE_CD,
exp_UPD_INS.LR_END_L3 as END_NBR,
exp_UPD_INS.LR_COV_L3 as COVERAGE,
exp_UPD_INS.LR_INO_NOC_L3 as NBR_PAID,
exp_UPD_INS.LR_TX_L3 as TX_CD,
exp_UPD_INS.LR_ACCTNO_L3 as ACCT_NBR,
exp_UPD_INS.LR_REL_L3 as RELEASE_CD,
exp_UPD_INS.LR_DPX_L3 as DRFT_NBR_PFX,
exp_UPD_INS.LR_DNO_L3 as DRFT_NBR,
exp_UPD_INS.LR_DAMT_L3 as DRFT_AMT,
exp_UPD_INS.LR_IODT_L3 as OPENED_DT,
exp_UPD_INS.LR_IODT_L_DATE3 as OPENED_DATE,
exp_UPD_INS.LR_PCDT_L3 as CLOSED_DT,
exp_UPD_INS.LR_PCDT_L_DATE3 as CLOSED_DATE,
exp_UPD_INS.LR_VOID_L3 as VOID_IND,
exp_UPD_INS.LR_CLASS_L3 as CLASSIFICATION,
exp_UPD_INS.LR_TEN_L3 as TENANT_CD,
exp_UPD_INS.LR_INS_L3 as INS_AMT,
exp_UPD_INS.LR_TIN_L3 as TAX_ID,
exp_UPD_INS.COML_EXPOBASE_L3 as COML_EXPO_BASE,
exp_UPD_INS.COML_EXPO_L3 as COML_EXPO,
exp_UPD_INS.LR_COTPLN_L3 as COT_PLN,
exp_UPD_INS.LR_LIMIT_L3 as LR_LIMIT,
exp_UPD_INS.LR_DEDUCT_L3 as DEDUCT_CD,
exp_UPD_INS.LR_CNSTR_YR_L3 as CNSTR_YR,
exp_UPD_INS.LR_CF_POL_NBR_L3 as CF_PLCY_NBR,
exp_UPD_INS.LR_GB_PAYEE_L3 as GB_PAYEE,
exp_UPD_INS.LR_GB_INVOICE_PFX_L3 as GB_INVOICE_PFX,
exp_UPD_INS.LR_GB_INVOICE_NBR_L3 as GB_INVOICE_NBR,
exp_UPD_INS.CAT_POOL_CCYY_L3 as CAT_POOL_CCYY,
exp_UPD_INS.CAT_POOL_LEVEL_L3 as CAT_POOL_LEVEL,
exp_UPD_INS.CAT_POOL_ACT_DATE_L3 as CAT_POOL_ACT_DT,
exp_UPD_INS.CAT_POOL_ACT_DATE13 as CAT_POOL_ACT_DATE,
exp_UPD_INS.CAT_POOL_RUN_TYPE_L3 as CAT_POOL_RUN_TYPE,
exp_UPD_INS.LOSS_RES_ADJ_L3 as LOSS_RES_ADJ,
exp_UPD_INS.ACT_CD_L3 as ACT_CD,
exp_UPD_INS.DRAFT_CD_L3 as DRAFT_CD,
exp_UPD_INS.DETN_L3 as DETAIL_NBR,
exp_UPD_INS.out_ECTL_BATCH_ID31 as ECTL_BATCH_ID,
exp_UPD_INS.out_ORIG_INS_TS31 as ECTL_ORIG_INS_TS,
exp_UPD_INS.out_ORIG_INS_TS31 as ECTL_MODIFY_TS,
exp_UPD_INS.out_ECTL_SRC_ID31 as ECTL_SRC_ID,
exp_UPD_INS.out_ECTL_SRC_INST_ID31 as ECTL_SRC_INST_ID,
exp_UPD_INS.out_ECTL_PRGM_ID31 as ECTL_PRGM_ID,
exp_UPD_INS.out_TX_CD as ECTL_TX_CD,
exp_UPD_INS.out_ECTL_BATCH_START_DATE31 as ECTL_START_DATE,
exp_UPD_INS.out_ECTL_END_DATE as ECTL_END_DATE
FROM
exp_UPD_INS;


-- Component CLMF_CLM_LOSS_RESERVE_CORE_upd, Type TARGET 
/* Perform Updates */
MERGE INTO db_t_core_prod.CLMF_CLM_LOSS_RESERVE_CORE upd
USING upd_TARGET
ON (LOSS_RESERVE_SKEY = upd_TARGET.LOSS_RESERVE_SKEY3 and CLAIM_SKEY = upd_TARGET.CLAIM_SKEY_lkp3 and CHG_EFF_DT = upd_TARGET.CHG_EFF_DT_lkp3 and CLAIM_SKEY = upd_TARGET.CLAIM_SKEY_lkp3)
WHEN MATCHED THEN UPDATE SET
CHG_EXP_DT = upd_TARGET.out_CHG_EXP_DT, ECTL_BATCH_ID = upd_TARGET.out_ECTL_BATCH_ID3, ECTL_MODIFY_TS = upd_TARGET.out_ORIG_INS_TS3, 
--ECTL_TX_CD = upd_TARGET.ECTL_TX_CD, 
ECTL_START_DATE = upd_TARGET.out_ECTL_BATCH_START_DATE3, ECTL_END_DATE = upd_TARGET.out_ECTL_END_DATE;




END; ';