-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_CLMF_ECTL_PRGM_PARAM("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component sq_TRG_CLAIM_MASTER_SRC, Type TABLE_DDL Creating an empty table
CREATE OR REPLACE TEMPORARY TABLE sq_TRG_CLAIM_MASTER
(
FILE_NAME varchar(13),
FREQUENCY varchar(6),
DATE varchar(13),
MRI_L_CNT varchar(12),
MRI_BLANK_CNT varchar(16),
MRI_C_CNT varchar(12),
MRI_D_CNT varchar(12),
MRI_A_CNT varchar(12),
MRI_V_CNT varchar(12),
MRI_TOTAL varchar(20),
FIELD11 varchar(12),
source_record_id number autoincrement start 1 increment 1
);


-- Component sq_TRG_CLAIM_MASTER_SRC, Type IMPORT_DATA Importing Data
;


-- Component exp_DATE_CONVERSION, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_DATE_CONVERSION AS
(
SELECT
TO_CHAR ( TO_DATE ( regexp_replace(sq_TRG_CLAIM_MASTER.DATE,''DATE '','''',1,0,''i'') , ''MM/DD/YY'' ) , ''YYYY-MM-DD'' ) as out_DATE_VALUE,
sq_TRG_CLAIM_MASTER.source_record_id
FROM
sq_TRG_CLAIM_MASTER
);


-- Component upd_ECTL_PARAM_VALUE, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_ECTL_PARAM_VALUE AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
exp_DATE_CONVERSION.out_DATE_VALUE as ECTL_PARAM_VALUE,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_DATE_CONVERSION
);


-- Component ECTL_PRGM_PARAM_UPD, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_CTRL_PROD.ECTL_PRGM_PARAM
USING upd_ECTL_PARAM_VALUE
ON (ECTL_PARAM_DESC =''CLAIM MASTER FEED DATE'')
WHEN MATCHED THEN UPDATE SET
ECTL_PARAM_VALUE = upd_ECTL_PARAM_VALUE.ECTL_PARAM_VALUE;


END; ';