-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_MANUAL_ENTRIES_LOSSES_CORE("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE 
PMMAPPINGNAME varchar;
ACT_PROJ_ID INTEGER;
ECTL_ACTIVE_IND varchar;
TABLE_NM varchar;
BEGIN 



-- Component SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as BUSINESS_UNIT,
$2 as ACCOUNT1,
$3 as REINSURANCE_CODE,
$4 as MONTH_ID,
$5 as MONETARY_AMOUNT,
$6 as SOURCE1,
$7 as YEAR1,
$8 as DEPT_ID,
$9 as PRODUCT,
$10 as STATE,
$11 as POOL,
$12 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT
STG_FIN_MANUAL_ENTRIES_LOSS_TXN.BUSINESS_UNIT,
STG_FIN_MANUAL_ENTRIES_LOSS_TXN.ACCOUNT1,
STG_FIN_MANUAL_ENTRIES_LOSS_TXN.REINSURANCE_CODE,
STG_FIN_MANUAL_ENTRIES_LOSS_TXN.MONTH_ID,
STG_FIN_MANUAL_ENTRIES_LOSS_TXN.MONETARY_AMOUNT,
STG_FIN_MANUAL_ENTRIES_LOSS_TXN.SOURCE1,
STG_FIN_MANUAL_ENTRIES_LOSS_TXN.YEAR1,
STG_FIN_MANUAL_ENTRIES_LOSS_TXN.DEPT_ID,
STG_FIN_MANUAL_ENTRIES_LOSS_TXN.PRODUCT,
STG_FIN_MANUAL_ENTRIES_LOSS_TXN.STATE,
STG_FIN_MANUAL_ENTRIES_LOSS_TXN.POOL
FROM DB_T_STAG_FIN_PROD.STG_FIN_MANUAL_ENTRIES_LOSS_TXN
) SRC
)
);


-- Component exp_MOVE_DATA, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_MOVE_DATA AS
(
SELECT
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN.BUSINESS_UNIT as BUSINESS_UNIT,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN.ACCOUNT1 as ACCOUNT1,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN.REINSURANCE_CODE as REINSURANCE_CODE,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN.MONTH_ID as MONTH_ID,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN.MONETARY_AMOUNT as MONITARY_AMOUNT,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN.SOURCE1 as SOURCE1,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN.YEAR1 as YEAR1,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN.DEPT_ID as DEPT_ID,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN.PRODUCT as PRODUCT,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN.STATE as STATE,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN.POOL as POOL,
:PMMappingName as in_PRGM_NM,
:ACT_PROJ_ID as in_ACT_PROJ_ID,
:ECTL_ACTIVE_IND as in_BATCH_ACTIVE_IND,
:TABLE_NM as in_TABLE_NM,
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN.source_record_id
FROM
SQ_Shortcut_to_STG_FIN_MANUAL_ENTRIES_LOSS_TXN
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;
call MPLT_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''exp_MOVE_DATA'');

-- Component exp_MOVE_DATA_2, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_MOVE_DATA_2 AS
(
SELECT
exp_MOVE_DATA.BUSINESS_UNIT as BUSINESS_UNIT,
exp_MOVE_DATA.ACCOUNT1 as ACCOUNT1,
exp_MOVE_DATA.REINSURANCE_CODE as REINSURANCE_CODE,
exp_MOVE_DATA.MONTH_ID as MONTH_ID,
exp_MOVE_DATA.MONITARY_AMOUNT as MONITARY_AMOUNT,
exp_MOVE_DATA.SOURCE1 as SOURCE1,
exp_MOVE_DATA.YEAR1 as YEAR1,
exp_MOVE_DATA.DEPT_ID as DEPT_ID,
exp_MOVE_DATA.PRODUCT as PRODUCT,
exp_MOVE_DATA.STATE as STATE,
exp_MOVE_DATA.POOL as POOL,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as out_ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as out_ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as out_ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as out_ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as out_MODIFY_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as out_ECTL_BATCH_START_DATE,
''NEW'' as out_ECTL_TXN_CD,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as out_ECTL_END_DATE,
exp_MOVE_DATA.source_record_id
FROM
exp_MOVE_DATA
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_MOVE_DATA.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
);


-- Component Shortcut_to_FIN_MANUAL_ENTRIES_LOSS_TXN1, Type TARGET 
INSERT INTO DB_T_CORE_FIN_PROD.FIN_MANUAL_ENTRIES_LOSS_TXN
(
BUSINESS_UNIT,
ACCOUNT1,
REINSURANCE_CODE,
MONTH_ID,
MONETARY_AMOUNT,
SOURCE1,
YEAR1,
DEPT_ID,
PRODUCT,
STATE,
POOL,
ECTL_BATCH_ID,
ECTL_ORIG_INS_TS,
ECTL_MODIFY_TS,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_PRGM_ID,
ECTL_TXN_CD,
ECTL_START_DATE,
ECTL_END_DATE
)
SELECT
exp_MOVE_DATA_2.BUSINESS_UNIT as BUSINESS_UNIT,
exp_MOVE_DATA_2.ACCOUNT1 as ACCOUNT1,
exp_MOVE_DATA_2.REINSURANCE_CODE as REINSURANCE_CODE,
exp_MOVE_DATA_2.MONTH_ID as MONTH_ID,
exp_MOVE_DATA_2.MONITARY_AMOUNT as MONETARY_AMOUNT,
exp_MOVE_DATA_2.SOURCE1 as SOURCE1,
exp_MOVE_DATA_2.YEAR1 as YEAR1,
exp_MOVE_DATA_2.DEPT_ID as DEPT_ID,
exp_MOVE_DATA_2.PRODUCT as PRODUCT,
exp_MOVE_DATA_2.STATE as STATE,
exp_MOVE_DATA_2.POOL as POOL,
exp_MOVE_DATA_2.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_MOVE_DATA_2.out_ORIG_INS_TS as ECTL_ORIG_INS_TS,
exp_MOVE_DATA_2.out_MODIFY_TS as ECTL_MODIFY_TS,
nvl(exp_MOVE_DATA_2.out_ECTL_SRC_ID,-1) as ECTL_SRC_ID,
nvl(exp_MOVE_DATA_2.out_ECTL_SRC_INST_ID,-1) as ECTL_SRC_INST_ID,
nvl(exp_MOVE_DATA_2.out_ECTL_PRGM_ID,-1) as ECTL_PRGM_ID,
exp_MOVE_DATA_2.out_ECTL_TXN_CD as ECTL_TXN_CD,
exp_MOVE_DATA_2.out_ECTL_BATCH_START_DATE as ECTL_START_DATE,
exp_MOVE_DATA_2.out_ECTL_END_DATE as ECTL_END_DATE
FROM
exp_MOVE_DATA_2;


END; ';