-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.S_M_AUDT_PRM_DTL_UNEARNED("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

CALL M_AUDT_PRM_DTL('':RUN_ID'', ''SELECT FIN_PREMIUM_TXN.MO_ID, FIN_PREMIUM_TXN.CMPY_CD, FIN_PREMIUM_TXN.ST_CD, FIN_PREMIUM_TXN.SVC_NBR, FIN_PREMIUM_TXN.AGNT_NBR, FIN_PREMIUM_TXN.LOB_CD, FIN_PREMIUM_TXN.PRODUCT_CD, FIN_PREMIUM_TXN.COV_TYPE_CD, FIN_PREMIUM_TXN.PLCY_NBR, FIN_PREMIUM_TXN.PLCY_EFF_DT, FIN_PREMIUM_TXN.PLCY_EXP_DT, FIN_PREMIUM_TXN.PLCY_TERM, FIN_PREMIUM_TXN.ACCTNG_MO, FIN_PREMIUM_TXN.ACCTNG_YR, FIN_PREMIUM_TXN.POOL_CD, FIN_PREMIUM_TXN.REINSUR_CD, FIN_PREMIUM_TXN.LEDGER, FIN_PREMIUM_TXN.ACCT_NBR, FIN_PREMIUM_TXN.GL_DSTR_STATUS, FIN_PREMIUM_TXN.MONETARY_AMT FROM DB_T_CORE_FIN_PROD.FIN_PREMIUM_TXN  WHERE MO_ID = :wf_MONTH_ID AND ACCT_NBR IN (:LEG_UEP_ACCTS)  UNION ALL  SELECT GL_EXTR_YR || GL_EXTR_MO, UNDERWRITING_CMPY_CD, RISK_STATE_CD, SERVICE_CENTER, AGENT_NBR, LOB_ROLLUP, PRODUCT, COV_CD, POLICY_NBR, POLICY_EFF_DT, POLICY_EXP_DT, POLICY_TERM, GL_EXTR_MO, GL_EXTR_YR, PS_POOL_CD, REINSURANCE_CD, LEDGER, GL_ACCOUNT_NBR, GL_DISTRIB_STATUS, TRNS_UNEARN_PREM_AMT FROM DB_T_PROD_COMN.GW_PREM_TRANS_GL_HIST, DB_T_CORE_FIN_PROD.FIN_PRODUCT_HIER'');


END; ';