-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_AUDT_PRM_DTL("RUN_ID" VARCHAR, "SESSION_QUERY" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' BEGIN 

-- Component SQ_Shortcut_to_FIN_PREMIUM_TXN, Type SOURCE
EXECUTE IMMEDIATE ''
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_FIN_PREMIUM_TXN AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MO_ID,
$2 as CMPY_CD,
$3 as ST_CD,
$4 as SVC_NBR,
$5 as AGNT_NBR,
$6 as LOB_CD,
$7 as PRODUCT_CD,
$8 as COV_TYPE_CD,
$9 as PLCY_NBR,
$10 as PLCY_EFF_DT,
$11 as PLCY_EXP_DT,
$12 as PLCY_TERM,
$13 as ACCTNG_MO,
$14 as ACCTNG_YR,
$15 as POOL_CD,
$16 as REINSUR_CD,
$17 as LEDGER,
$18 as ACCT_NBR,
$19 as GL_DSTR_STATUS,
$20 as MONETARY_AMT,
$21 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (

'' || :SESSION_QUERY || ''

) SRC
)
)'';


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_Shortcut_to_FIN_PREMIUM_TXN.MO_ID as MO_ID,
SQ_Shortcut_to_FIN_PREMIUM_TXN.CMPY_CD as CMPY_CD,
SQ_Shortcut_to_FIN_PREMIUM_TXN.ST_CD as ST_CD,
SQ_Shortcut_to_FIN_PREMIUM_TXN.SVC_NBR as SVC_NBR,
SQ_Shortcut_to_FIN_PREMIUM_TXN.AGNT_NBR as AGNT_NBR,
SQ_Shortcut_to_FIN_PREMIUM_TXN.LOB_CD as LOB_CD,
SQ_Shortcut_to_FIN_PREMIUM_TXN.PRODUCT_CD as PRODUCT_CD,
SQ_Shortcut_to_FIN_PREMIUM_TXN.COV_TYPE_CD as COV_TYPE_CD,
SQ_Shortcut_to_FIN_PREMIUM_TXN.PLCY_NBR as PLCY_NBR,
SQ_Shortcut_to_FIN_PREMIUM_TXN.PLCY_EFF_DT as PLCY_EFF_DT,
SQ_Shortcut_to_FIN_PREMIUM_TXN.PLCY_EXP_DT as PLCY_EXP_DT,
SQ_Shortcut_to_FIN_PREMIUM_TXN.PLCY_TERM as PLCY_TERM,
SQ_Shortcut_to_FIN_PREMIUM_TXN.ACCTNG_MO as ACCTNG_MO,
SQ_Shortcut_to_FIN_PREMIUM_TXN.ACCTNG_YR as ACCTNG_YR,
SQ_Shortcut_to_FIN_PREMIUM_TXN.POOL_CD as POOL_CD,
SQ_Shortcut_to_FIN_PREMIUM_TXN.REINSUR_CD as REINSUR_CD,
SQ_Shortcut_to_FIN_PREMIUM_TXN.LEDGER as LEDGER,
SQ_Shortcut_to_FIN_PREMIUM_TXN.ACCT_NBR as ACCT_NBR,
SQ_Shortcut_to_FIN_PREMIUM_TXN.GL_DSTR_STATUS as GL_DSTR_STATUS,
SQ_Shortcut_to_FIN_PREMIUM_TXN.MONETARY_AMT as MONETARY_AMT,
SQ_Shortcut_to_FIN_PREMIUM_TXN.source_record_id
FROM
SQ_Shortcut_to_FIN_PREMIUM_TXN
);


-- Component AUDT_PRM_DTL, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE AUDT_PRM_DTL AS
(
SELECT
EXPTRANS.MO_ID as MO_ID,
EXPTRANS.CMPY_CD as CMPY_CD,
EXPTRANS.ST_CD as ST_CD,
EXPTRANS.SVC_NBR as SVC_NBR,
EXPTRANS.AGNT_NBR as AGNT_NBR,
EXPTRANS.LOB_CD as LOB_CD,
EXPTRANS.PRODUCT_CD as PRODUCT_CD,
EXPTRANS.COV_TYPE_CD as COV_TYPE_CD,
EXPTRANS.PLCY_NBR as PLCY_NBR,
EXPTRANS.PLCY_EFF_DT as PLCY_EFF_DT,
EXPTRANS.PLCY_EXP_DT as PLCY_EXP_DT,
EXPTRANS.PLCY_TERM as PLCY_TERM,
EXPTRANS.ACCTNG_MO as ACCTNG_MO,
EXPTRANS.ACCTNG_YR as ACCTNG_YR,
EXPTRANS.POOL_CD as POOL_CD,
EXPTRANS.REINSUR_CD as REINSUR_CD,
EXPTRANS.LEDGER as LEDGER,
EXPTRANS.ACCT_NBR as ACCT_NBR,
EXPTRANS.GL_DSTR_STATUS as GL_DSTR_STATUS,
EXPTRANS.MONETARY_AMT as MONETARY_AMT
FROM
EXPTRANS
);

COPY INTO @public.edw_stage/my_export_folder/AUDT_PRM_SUMM_
FROM (SELECT * FROM AUDT_PRM_DTL)
HEADER = TRUE
OVERWRITE = TRUE;
-- Component AUDT_PRM_DTL, Type EXPORT_DATA Exporting data
;


END; ';