-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_AGG_MEMB_FLOW("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE wf_CAL_END_DT date;
BEGIN 

wf_CAL_END_DT:=''1900-01-01''; 

-- PIPELINE START FOR 1
-- Component AGG_MEMB_FLOW, Type Pre SQL 
DELETE FROM DB_T_CORE_MEMBXREF_PROD.AGG_MEMB_FLOW WHERE MO_ID = year( :wf_CAL_END_DT)*100 + month( :wf_CAL_END_DT);


-- Component SQ_AGG_MEMB_FLOW, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_MEMB_FLOW AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MO_ID,
$2 as PERIOD,
$3 as GROUP_CD,
$4 as BEGMIF_CNT,
$5 as ENDMIF_CNT,
$6 as PCT_MIF,
$7 as NEW_CNT,
$8 as LAPSE_CNT,
$9 as NET_GL_CNT,
$10 as NEW_RATE,
$11 as LAPSE_RATE,
$12 as NET_GL_RATE,
$13 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH MEMB_BEG_YTD_TEMP AS(
SELECT DISTINCT A.MEMB_NUM , B.MEMB_SKEY , cast(A.MEMB_EFF_DT  as date) MEMB_EFF_DT
FROM (SELECT MEMB_NUM,MEMB_SKEY, (MEMB_EFF_DT) MEMB_EFF_DT,(MEMB_EXP_DT) MEMB_EXP_DT FROM DB_T_CORE_PROD.MEMBER_MSTR GROUP BY 1 ,2,3,4) A, (SELECT * from DB_T_CORE_PROD.MEMBER_TRANS B qualify row_number() over(partition by memb_skey,cast(chg_eff_Dt as date) order by chg_eff_dt desc)=1) B
WHERE A.MEMB_SKEY = B.MEMB_SKEY
AND cast(A.MEMB_EXP_DT as date)> cast (add_months(:wf_CAL_END_DT ,-month (:wf_CAL_END_DT)+1) - day (:wf_CAL_END_DT) as date)

AND CAST(B.CHG_EFF_DT AS DATE) <= cast (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+1)- day (:wf_CAL_END_DT) as date)
 AND CAST(B.CHG_EXP_DT AS DATE) >= case when (cast (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+1)- day(:wf_CAL_END_DT) as date)<=''2021-07-31'')
 then cast (add_months(:wf_CAL_END_DT ,-month (:wf_CAL_END_DT )+1)- day(:wf_CAL_END_DT) as date) else cast (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+1)- day(:wf_CAL_END_DT) as date)+1 end
AND B.STATUS_CD IN (0,1,9)
AND B.MEMB_TYPE IN (''A'', ''C'')),
MEMB_BEG_FTD_TEMP AS(
SELECT DISTINCT A.MEMB_NUM , B.MEMB_SKEY , CAST( A.MEMB_EFF_DT AS DATE) MEMB_EFF_DT
FROM (SELECT MEMB_NUM,MEMB_SKEY, (MEMB_EFF_DT) MEMB_EFF_DT,(MEMB_EXP_DT) MEMB_EXP_DT FROM DB_T_CORE_PROD.MEMBER_MSTR GROUP BY 1 ,2,3,4) A, (SELECT * from DB_T_CORE_PROD.MEMBER_TRANS B qualify row_number() over(partition by memb_skey,cast(chg_eff_Dt as date) order by chg_eff_dt desc)=1) B
WHERE A.MEMB_SKEY = B.MEMB_SKEY
AND CAST(A.MEMB_EXP_DT AS DATE)> cast (case when (month(:wf_CAL_END_DT )>6) then (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+6))
else (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )-6)) end as date)

AND CAST(B.CHG_EFF_DT AS DATE)<= cast (case when (month(:wf_CAL_END_DT )>6) 
then (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+6))
else  (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )-6)) end as date) 
AND CAST(B.CHG_EXP_DT AS DATE) >=case when (cast (case when (month(:wf_CAL_END_DT )>6) 
then (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+6))
else  (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )-6)) end as date) <=''2021-07-31'') then 
cast (case when (month(:wf_CAL_END_DT )>6) 
then (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+6))
else  (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )-6)) end as date) else 
cast (case when (month(:wf_CAL_END_DT )>6) 
then (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+6))
else  (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )-6)) end as date) +1 end
AND B.STATUS_CD IN (0,1,9)
AND B.MEMB_TYPE IN (''A'', ''C'')
AND year(:wf_CAL_END_DT)*100+month(:wf_CAL_END_DT)  > 201106),
MEMB_BEG_MTD_TEMP AS(
SELECT DISTINCT A.MEMB_NUM , B.MEMB_SKEY , CAST(A.MEMB_EFF_DT AS DATE) MEMB_EFF_DT
FROM (SELECT MEMB_NUM,MEMB_SKEY, (MEMB_EFF_DT) MEMB_EFF_DT,(MEMB_EXP_DT) MEMB_EXP_DT FROM DB_T_CORE_PROD.MEMBER_MSTR GROUP BY 1 ,2,3,4) A, (SELECT * from DB_T_CORE_PROD.MEMBER_TRANS B qualify row_number() over(partition by memb_skey,cast(chg_eff_Dt as date) order by chg_eff_dt desc)=1) B
WHERE A.MEMB_SKEY = B.MEMB_SKEY
AND CAST(A.MEMB_EXP_DT AS DATE)> CAST( :wf_CAL_END_DT AS DATE)- day(:wf_CAL_END_DT) 

AND CAST(B.CHG_EFF_DT AS DATE) <=CAST( :wf_CAL_END_DT AS DATE)- day(:wf_CAL_END_DT)  AND CAST(B.CHG_EXP_DT AS DATE) >= case when (CAST( :wf_CAL_END_DT AS DATE)- day(:wf_CAL_END_DT) <=''2021-07-31'')
then CAST( :wf_CAL_END_DT AS DATE)- day(:wf_CAL_END_DT)  else CAST( :wf_CAL_END_DT AS DATE)- day(:wf_CAL_END_DT) +1 end 
AND B.STATUS_CD IN (0,1,9)
/* AND B.COMM_CD1 || B.COMM_CD2 || B.COMM_CD3 <> ''XXY'' */
AND B.MEMB_TYPE IN (''A'', ''C'')),
MEMB_END_TEMP AS(
SELECT DISTINCT A.MEMB_NUM  , B.MEMB_SKEY  ,CAST( A.MEMB_EFF_DT AS DATE) MEMB_EFF_DT
FROM (SELECT MEMB_NUM,MEMB_SKEY, (MEMB_EFF_DT) MEMB_EFF_DT,(MEMB_EXP_DT) MEMB_EXP_DT FROM DB_T_CORE_PROD.MEMBER_MSTR GROUP BY 1 ,2,3,4) A, (SELECT * from DB_T_CORE_PROD.MEMBER_TRANS B qualify row_number() over(partition by memb_skey,cast(chg_eff_Dt as date) order by chg_eff_dt desc)=1) B
WHERE A.MEMB_SKEY = B.MEMB_SKEY
AND CAST(A.MEMB_EXP_DT AS DATE) > :wf_CAL_END_DT
/*AND :wf_CAL_END_DT BETWEEN CAST(B.CHG_EFF_DT AS DATE) AND CAST(B.CHG_EXP_DT AS DATE)*/
AND CAST(B.CHG_EFF_DT AS DATE) <= CAST(:wf_CAL_END_DT AS DATE) AND CAST(B.CHG_EXP_DT AS DATE) >= 
case when (CAST(:wf_CAL_END_DT AS DATE)<=''2021-07-31'') then CAST(:wf_CAL_END_DT AS DATE) else CAST(:wf_CAL_END_DT AS DATE)+1 end
AND B.STATUS_CD IN (0,1,9)
/* AND B.COMM_CD1 || B.COMM_CD2 || B.COMM_CD3 <> ''XXY'' */
AND B.MEMB_TYPE IN (''A'', ''C'')),
MEMB_REIN_GT_365 AS(
SELECT MEMB_NUM, MEMB_SKEY,NEW_CHG_EFF_DT MEMB_REIN_DT FROM (
SELECT A.MEMB_SKEY,A.MEMB_NUM,
CAST(A.MEMB_EFF_DT AS DATE) MEMB_EFF_DT,CAST(A.MEMB_EXP_DT AS DATE) MEMB_EXP_DT,
CASE WHEN CAST(A.MEMB_EXP_DT AS DATE)<CAST(B.CHG_EFF_DT AS DATE) THEN CAST(A.MEMB_EXP_DT AS DATE) ELSE CAST(B.CHG_EFF_DT AS DATE) END AS NEW_CHG_EFF_DT,
CASE WHEN CAST( A.MEMB_EXP_DT AS DATE)<CAST(B.CHG_EXP_DT AS DATE) THEN CAST(A.MEMB_EXP_DT AS DATE) ELSE CAST(B.CHG_EXP_DT AS DATE) END AS NEW_CHG_EXP_DT,
COALESCE(MAX(NEW_CHG_EXP_DT) OVER(PARTITION BY A.MEMB_SKEY ORDER BY NEW_CHG_EFF_DT ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING),CAST(MEMB_EFF_DT AS DATE)) AS PREV_CHG_EXP_DT,
NEW_CHG_EFF_DT-PREV_CHG_EXP_DT AS DAYS 
FROM (SELECT MEMB_NUM,MEMB_SKEY, (MEMB_EFF_DT) MEMB_EFF_DT,(MEMB_EXP_DT) MEMB_EXP_DT FROM DB_T_CORE_PROD.MEMBER_MSTR GROUP BY 1 ,2,3,4) A, (SELECT * from DB_T_CORE_PROD.MEMBER_TRANS B qualify row_number() over(partition by memb_skey,cast(chg_eff_Dt as date) order by chg_eff_dt desc)=1) B 
WHERE A.MEMB_SKEY = B.MEMB_SKEY
AND B.STATUS_CD IN (0,1,9)
/* AND B.COMM_CD1 || B.COMM_CD2 || B.COMM_CD3 <> ''XXY'' */
AND B.MEMB_TYPE IN (''A'', ''C'') 
GROUP BY 1,2,3,4,5,6
QUALIFY DAYS>365) T  
WHERE NEW_CHG_EFF_DT > 
cast (case when (month(:wf_CAL_END_DT )>6) then cast (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+1)- day(:wf_CAL_END_DT) as date)
else (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )-6)) end as date)
AND NEW_CHG_EFF_DT<=:wf_CAL_END_DT  
GROUP BY 1,2,3),
MEMB_FLOW_TEMP AS(
SELECT T.MEMBER_NUMBER AS MEMB_NUM, T.MEMBER_SKEY AS MEMB_SKEY, T.PERIOD, 
CASE WHEN T.MEMB_STATUS = 2 AND  R.MEMB_NUM IS NOT NULL THEN 1 ELSE T.MEMB_STATUS END AS MEMB_STATUS FROM 
(SELECT COALESCE(BP.MEMB_NUM,EP.MEMB_NUM) MEMBER_NUMBER,COALESCE(BP.MEMB_SKEY,  EP.MEMB_SKEY) MEMBER_SKEY, ''YTD'' PERIOD,
CASE WHEN EP.MEMB_SKEY IS NULL THEN 3
WHEN BP.MEMB_SKEY IS NULL AND EP.memb_EFF_DT  > cast (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+1)- day(:wf_CAL_END_DT) as date) THEN 1
WHEN  BP.MEMB_SKEY IS NULL AND EP.memb_EFF_DT  <= cast (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+1)- day(:wf_CAL_END_DT) as date) THEN 2 ELSE 4 END AS MEMB_STATUS
 FROM MEMB_BEG_YTD_TEMP BP FULL OUTER JOIN MEMB_END_TEMP EP
ON BP.MEMB_SKEY=EP.MEMB_SKEY) T 
LEFT OUTER JOIN 
(SELECT DISTINCT MEMB_NUM,MEMB_SKEY  FROM MEMB_REIN_GT_365 WHERE 
MEMB_REIN_DT > cast (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+1)- day(:wf_CAL_END_DT) as date)+1  
AND MEMB_REIN_DT <= :wf_CAL_END_DT) R ON T.MEMBER_SKEY = R.MEMB_SKEY
UNION
SELECT T.MEMBER_NUMBER AS MEMB_NUM, T.MEMBER_SKEY AS MEMB_SKEY, T.PERIOD, 
CASE WHEN T.MEMB_STATUS = 2 AND  R.MEMB_NUM IS NOT NULL THEN 1 ELSE T.MEMB_STATUS END AS MEMB_STATUS FROM 
(SELECT COALESCE(BP.MEMB_NUM,EP.MEMB_NUM) MEMBER_NUMBER,COALESCE(BP.MEMB_SKEY,  EP.MEMB_SKEY) MEMBER_SKEY, ''FTD'' PERIOD,
CASE WHEN EP.MEMB_SKEY IS NULL THEN 3
WHEN BP.MEMB_SKEY IS NULL AND EP.memb_EFF_DT  > cast (case when (month(:wf_CAL_END_DT )>6) then (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+6))
else (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )-6)) end as date) THEN 1
WHEN  BP.MEMB_SKEY IS NULL AND EP.memb_EFF_DT  <= cast (case when (month(:wf_CAL_END_DT )>6) then (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+6))
else (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )-6)) end as date) THEN 2 ELSE 4 END AS MEMB_STATUS
 FROM MEMB_BEG_FTD_TEMP BP FULL OUTER JOIN MEMB_END_TEMP EP
ON BP.MEMB_SKEY=EP.MEMB_SKEY 
where  year(:wf_CAL_END_DT)*100+month(:wf_CAL_END_DT)  > 201106
) T 
LEFT OUTER JOIN 
(SELECT DISTINCT MEMB_NUM,MEMB_SKEY  FROM MEMB_REIN_GT_365 WHERE 
MEMB_REIN_DT > cast (case when (month(:wf_CAL_END_DT )>6) then (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )+6))
else (add_months(:wf_CAL_END_DT ,-month(:wf_CAL_END_DT )-6)) end as date) 
AND MEMB_REIN_DT <= :wf_CAL_END_DT) R ON T.MEMBER_SKEY = R.MEMB_SKEY
UNION
SELECT T.MEMBER_NUMBER AS MEMB_NUM, T.MEMBER_SKEY AS MEMB_SKEY, T.PERIOD, 
CASE WHEN T.MEMB_STATUS = 2 AND  R.MEMB_NUM IS NOT NULL THEN 1 ELSE T.MEMB_STATUS END AS MEMB_STATUS FROM 
(SELECT COALESCE(BP.MEMB_NUM,EP.MEMB_NUM) MEMBER_NUMBER,COALESCE(BP.MEMB_SKEY,  EP.MEMB_SKEY) MEMBER_SKEY, ''MTD'' PERIOD,
CASE WHEN EP.MEMB_SKEY IS NULL THEN 3
WHEN BP.MEMB_SKEY IS NULL AND EP.memb_EFF_DT  > CAST( :wf_CAL_END_DT AS DATE)- day(:wf_CAL_END_DT)  THEN 1
WHEN  BP.MEMB_SKEY IS NULL AND EP.memb_EFF_DT  <= CAST( :wf_CAL_END_DT AS DATE)- day(:wf_CAL_END_DT)  THEN 2 ELSE 4 END AS MEMB_STATUS
 FROM MEMB_BEG_MTD_TEMP BP FULL OUTER JOIN MEMB_END_TEMP EP
ON BP.MEMB_SKEY=EP.MEMB_SKEY) T 
LEFT OUTER JOIN 
(SELECT DISTINCT MEMB_NUM,MEMB_SKEY  FROM MEMB_REIN_GT_365 WHERE 
MEMB_REIN_DT > CAST( :wf_CAL_END_DT AS DATE)- day(:wf_CAL_END_DT)   
AND MEMB_REIN_DT <= :wf_CAL_END_DT) R ON T.MEMBER_SKEY = R.MEMB_SKEY),
MEMB_BUCKET_TEMP AS(
SELECT 
PC_MEMBER_NUMBER AS MEMB_NUM,
SUM(AUTOPOLS) AUTOPOLS,
SUM(HOMEPOLS) HOMEPOLS,
SUM(MANHOMEPOLS) MANHOMEPOLS,
SUM(FARMPOLS) FARMPOLS,
SUM(FIREPOLS) FIREPOLS,
SUM(SMLNPOLS) SMLNPOLS,
SUM(PORTPOLS) PORTPOLS,
SUM(RHPOLS) RHPOLS,
SUM(LOANS) LOANS,
SUM(ASICPOLS) ASICPOLS,
SUM(LIFEPOLS) LIFEPOLS,
SUM(FGMPOLS) FGMPOLS
FROM (
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER,
1 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM (SELECT DISTINCT PC_MEMBER_NUMBER  from DB_T_CORE_MEMBXREF_PROD.AUTOPOLS WHERE :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT 	AND (CAST( (cast(:wf_CAL_END_DT as date)-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
union 
SELECT distinct EX_MEMBER_NUM  from DB_T_CORE_MEMBXREF_PROD.EXCEED_POL_LIST WHERE :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT 
) bothauto
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
UNION
SELECT DISTINCT cast( PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER,
0 AUTOPOLS,1 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.HOMEPOLS
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (cast(:wf_CAL_END_DT as date)-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
UNION
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER ,
0 AUTOPOLS,0 HOMEPOLS,1 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.MANHOMEPOLS
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (cast(:wf_CAL_END_DT as date)-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
UNION
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,1 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.FARMPOLS
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (cast(:wf_CAL_END_DT as date)-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
UNION
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,1 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.FIREPOLS
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (cast(:wf_CAL_END_DT as date)-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
UNION
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,1 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS
FROM DB_T_CORE_MEMBXREF_PROD.SMLNPOLS
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (cast(:wf_CAL_END_DT as date)-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
UNION
SELECT DISTINCT cast( PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,1 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.PORTPOLS
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (cast(:wf_CAL_END_DT as date)-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
UNION
SELECT DISTINCT  cast(RH_MEM_NBR as integer) PC_MEMBER_NUMBER ,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,1 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS
from (SELECT DISTINCT  RH_MEM_NBR  FROM DB_T_CORE_MEMBXREF_PROD.RHPOLS
WHERE  :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT
union
SELECT DISTINCT RH_MEM_NBR FROM DB_T_CORE_MEMBXREF_PROD.RHPOLS_HIST
WHERE ((CAST( (cast(:wf_CAL_END_DT as date) - RH_XDATE) AS FLOAT) /366)<=2.0) ) RHPOLS where  
UPPER(SUBSTR(RH_MEM_NBR,1,1) )--(CS)
=LOWER(SUBSTR(RH_MEM_NBR,1,1) )

UNION
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,1 LOANS,0 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.LOANS
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT

/*UNION
SELECT DISTINCT cast(PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,1 ASICPOLS,0 LIFEPOLS,0 FGMPOLS 
FROM DB_T_CORE_MEMBXREF_PROD.ASICPOLS
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT
	AND (CAST( (cast(:wf_CAL_END_DT as date)-  PC_EXP_DATE) AS FLOAT) /366)<=2.0*/
UNION
SELECT DISTINCT cast( LF_MEMBERSHIP as integer) PC_MEMBER_NUMBER,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,1 LIFEPOLS,0 FGMPOLS 
FROM (SELECT DISTINCT LF_MEMBERSHIP from DB_T_CORE_MEMBXREF_PROD.LIFEPOLS WHERE :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT 
union SELECT distinct INSURED_MEMBER_NUM from DB_T_CORE_MEMBXREF_PROD.ING_POL_LIST WHERE :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT) bothlife
WHERE UPPER(SUBSTR(LF_MEMBERSHIP ,1,1) )--(CS)
=LOWER(SUBSTR(LF_MEMBERSHIP ,1,1) )
UNION
SELECT DISTINCT cast( PC_MEMBER_NUMBER as integer) PC_MEMBER_NUMBER,
0 AUTOPOLS,0 HOMEPOLS,0 MANHOMEPOLS,0 FARMPOLS,0 FIREPOLS,0 SMLNPOLS,0 PORTPOLS,0 RHPOLS,0 LOANS,0 ASICPOLS,0 LIFEPOLS,1 FGMPOLS
FROM DB_T_CORE_MEMBXREF_PROD.FGMPOLS
WHERE UPPER(SUBSTR(PC_MEMBER_NUMBER,1,1) )--(CS)
=LOWER(SUBSTR(PC_MEMBER_NUMBER,1,1) )
AND :wf_CAL_END_DT BETWEEN CHG_EFF_DT AND CHG_EXP_DT
AND (CAST( (cast(:wf_CAL_END_DT as date)-  PC_EXP_DATE) AS FLOAT) /366)<=2.0
)UNIONED
GROUP BY PC_MEMBER_NUMBER),
AGG_MEMB_FLOW_TEMP AS(
SELECT MO_ID, PERIOD, group_cd, BEGMIF_CNT ,ENDMIF_CNT ,CAST(PCT_MIF AS DECIMAL(5,2)) AS PCT_MIF ,New_Cnt ,Lapse_Cnt ,Net_GL_Cnt ,CAST(New_Rate AS DECIMAL(5,2)) AS New_Rate ,CAST(Lapse_Rate AS DECIMAL(5,2)) AS Lapse_Rate,CAST(Net_GL_Rate AS DECIMAL(5,2)) AS Net_GL_Rate, OVERALL_ENDMIF_CNT, AVGMIF_CNT FROM (SELECT MO_ID,  PERIOD,GROUP_CD, SUM( CASE WHEN MEMB_STATUS =1 THEN 1 ELSE 0 END) NEW_CNT,
SUM( CASE WHEN MEMB_STATUS =2 THEN 1 ELSE 0 END) REIN_CNT,
SUM( CASE WHEN MEMB_STATUS =3 THEN 1 ELSE 0 END) ACTLAPSE_CNT,
SUM( CASE WHEN MEMB_STATUS =4 THEN 1 ELSE 0 END) STATIC_CNT,
STATIC_CNT+ACTLAPSE_CNT BEGMIF_CNT,
STATIC_CNT+NEW_CNT+REIN_CNT ENDMIF_CNT,
(BEGMIF_CNT+ENDMIF_CNT)/2 AVGMIF_CNT,
ACTLAPSE_CNT-REIN_CNT LAPSE_CNT ,
OVERALL_BEGMIF_CNT,
OVERALL_ENDMIF_CNT,
(ENDMIF_CNT/cast(OVERALL_ENDMIF_CNT as decimal(12,5)))*100 PCT_MIF,
(NEW_CNT-LAPSE_CNT) NET_GL_CNT,
(NEW_CNT/cast(AVGMIF_CNT as decimal(12,5)))*100 NEW_RATE,
(LAPSE_CNT/cast(AVGMIF_CNT as decimal(12,5)))*100 LAPSE_RATE,
(NET_GL_CNT/cast(AVGMIF_CNT as decimal(12,5)))*100 NET_GL_RATE 
FROM (
SELECT year(:wf_CAL_END_DT)*100+month(:wf_CAL_END_DT) MO_ID, Q1.PERIOD,
MEMB_NUM,MEMB_STATUS,
CASE WHEN (AUTOPOLS=1 AND HOMEPOLS=0 AND MANHOMEPOLS=0 AND FARMPOLS=0 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=0 AND FGMPOLS=0 ) THEN  2
WHEN ( AUTOPOLS=1 AND HOMEPOLS=1 AND MANHOMEPOLS=0 AND FARMPOLS=0 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=0 AND FGMPOLS=0 ) THEN 3
WHEN ( AUTOPOLS=1 AND HOMEPOLS=1 AND MANHOMEPOLS=0 AND FARMPOLS=0 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=1 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=0 AND FGMPOLS=0 ) THEN 4
WHEN ( AUTOPOLS=1 AND HOMEPOLS=1 AND MANHOMEPOLS=0 AND FARMPOLS=0 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=1 AND FGMPOLS=0 ) THEN 5
WHEN (AUTOPOLS=1 AND HOMEPOLS=1  AND  (FARMPOLS =1 OR  MANHOMEPOLS=1  OR FIREPOLS=1 
OR SMLNPOLS=1 OR PORTPOLS=1 OR RHPOLS=1 OR LOANS=1 OR ASICPOLS=1 OR LIFEPOLS=1 OR FGMPOLS=1) ) THEN 6
WHEN ( AUTOPOLS=1 AND HOMEPOLS=0 AND MANHOMEPOLS=0 AND FARMPOLS=1 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=0 AND FGMPOLS=0 ) THEN 7
WHEN ( FARMPOLS=1 AND AUTOPOLS=1 AND ( HOMEPOLS = 1 OR MANHOMEPOLS=1 OR FIREPOLS=1 
OR SMLNPOLS=1 OR PORTPOLS=1 OR RHPOLS=1 OR LOANS=1 OR ASICPOLS=1 OR LIFEPOLS=1 OR FGMPOLS=1) ) THEN 8
WHEN ( AUTOPOLS=1 AND HOMEPOLS=0 AND MANHOMEPOLS=1 AND FARMPOLS=0 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=0 AND FGMPOLS=0 ) THEN 9
WHEN ( AUTOPOLS=1 AND MANHOMEPOLS=1 AND ( HOMEPOLS = 1 OR FARMPOLS=1 OR FIREPOLS=1 
OR SMLNPOLS=1 OR PORTPOLS=1 OR RHPOLS=1 OR LOANS=1 OR ASICPOLS=1 OR LIFEPOLS=1 OR FGMPOLS=1) ) THEN 10
WHEN ( AUTOPOLS=1 AND HOMEPOLS=0 AND MANHOMEPOLS=0 AND FARMPOLS=0 AND FIREPOLS=1 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=0 AND FGMPOLS=0 ) THEN 11
WHEN ( AUTOPOLS=1 AND FIREPOLS=1 AND ( HOMEPOLS = 1 OR FARMPOLS=1 OR MANHOMEPOLS=1 
OR SMLNPOLS=1 OR PORTPOLS=1 OR RHPOLS=1 OR LOANS=1 OR ASICPOLS=1 OR LIFEPOLS=1 OR FGMPOLS=1) ) THEN 12
WHEN ( AUTOPOLS=0 AND HOMEPOLS=0 AND MANHOMEPOLS=0 AND FARMPOLS=0 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=1 AND LIFEPOLS=0 AND FGMPOLS=0 ) THEN 13
WHEN ( ASICPOLS=1 AND (AUTOPOLS=1 OR HOMEPOLS=1 OR MANHOMEPOLS=1 OR FARMPOLS=1 OR FIREPOLS=1 
OR SMLNPOLS=1 OR PORTPOLS=1 OR RHPOLS=1 OR LOANS=1 OR LIFEPOLS=1 OR FGMPOLS=1 )) THEN 14
WHEN (AUTOPOLS=1 AND (HOMEPOLS=1 OR MANHOMEPOLS=1 OR FARMPOLS=1 OR FIREPOLS=1 
OR SMLNPOLS=1 OR PORTPOLS=1 OR RHPOLS=1 OR LOANS=1 OR ASICPOLS=1 OR LIFEPOLS=1 OR FGMPOLS=1) ) THEN 15
WHEN ( AUTOPOLS=0 AND HOMEPOLS=1 AND MANHOMEPOLS=0 AND FARMPOLS=0 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=0 AND FGMPOLS=0 ) THEN 17
WHEN ( HOMEPOLS=1  AND (AUTOPOLS=1 OR MANHOMEPOLS=1 OR FARMPOLS=1 OR FIREPOLS=1 
OR SMLNPOLS=1 OR PORTPOLS=1 OR RHPOLS=1 OR LOANS=1 OR ASICPOLS=1 OR LIFEPOLS=1 OR FGMPOLS=1) ) THEN 18
WHEN ( AUTOPOLS=0 AND HOMEPOLS=0 AND MANHOMEPOLS=0 AND FARMPOLS=1 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=0 AND FGMPOLS=0 ) THEN 19
WHEN ( FARMPOLS=1 AND  (AUTOPOLS=1 OR HOMEPOLS =1 OR MANHOMEPOLS=1 OR FIREPOLS=1 
OR SMLNPOLS=1 OR PORTPOLS=1 OR RHPOLS=1 OR LOANS=1 OR ASICPOLS=1 OR LIFEPOLS=1 OR FGMPOLS=1) ) THEN 20
WHEN ( AUTOPOLS=0 AND HOMEPOLS=0 AND MANHOMEPOLS=1 AND FARMPOLS=0 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=0 AND FGMPOLS=0) THEN 21
WHEN (   MANHOMEPOLS=1  AND (AUTOPOLS=1 OR HOMEPOLS =1 OR  FARMPOLS=1 OR FIREPOLS=1 
OR SMLNPOLS=1 OR PORTPOLS=1 OR RHPOLS=1 OR LOANS=1 OR ASICPOLS=1 OR LIFEPOLS=1 OR FGMPOLS=1)) THEN 22
WHEN ( AUTOPOLS=0 AND HOMEPOLS=0 AND MANHOMEPOLS=0 AND FARMPOLS=0 AND FIREPOLS=1 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=0 AND FGMPOLS=0 ) THEN 23
WHEN (  FIREPOLS=1 AND (AUTOPOLS=1 OR HOMEPOLS=1 OR  MANHOMEPOLS=1 OR FARMPOLS =1 OR 
SMLNPOLS=1 OR PORTPOLS=1 OR RHPOLS=1 OR LOANS=1 OR ASICPOLS=1 OR LIFEPOLS=1 OR FGMPOLS=1)) THEN 24
WHEN ( AUTOPOLS=0 AND HOMEPOLS=0 AND MANHOMEPOLS=0 AND FARMPOLS=0 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=1 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=0 AND FGMPOLS=0 ) THEN 26
WHEN (  RHPOLS=1 AND (AUTOPOLS=1 OR HOMEPOLS=1 OR  MANHOMEPOLS=1 OR FARMPOLS =1 OR 
FIREPOLS =1 OR  SMLNPOLS=1 OR PORTPOLS=1 OR LOANS=1 OR ASICPOLS=1 OR LIFEPOLS=1 OR FGMPOLS=1)) THEN 27
WHEN ( AUTOPOLS=0 AND HOMEPOLS=0 AND MANHOMEPOLS=0 AND FARMPOLS=0 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=1 AND FGMPOLS=0 ) THEN 32
WHEN (  LIFEPOLS=1 AND (AUTOPOLS=1 OR HOMEPOLS=1 OR  MANHOMEPOLS=1 OR FARMPOLS =1 OR 
FIREPOLS =1 OR SMLNPOLS=1 OR PORTPOLS=1  OR LOANS=1 OR RHPOLS = 1 OR  ASICPOLS=1 OR FGMPOLS=1) ) THEN 33
WHEN ( AUTOPOLS=0 AND HOMEPOLS=0 AND MANHOMEPOLS=0 AND FARMPOLS=0 AND FIREPOLS=0 
AND SMLNPOLS=0 AND PORTPOLS=0 AND RHPOLS=0 AND LOANS=0 AND ASICPOLS=0 AND LIFEPOLS=0 AND FGMPOLS=0 ) THEN 36
ELSE 35 END AS GROUP_CD,OVERALL_BEGMIF_CNT,OVERALL_ENDMIF_CNT
FROM ( SELECT PERIOD, A.MEMB_NUM MEMB_NUM, A. MEMB_STATUS MEMB_STATUS,  
COALESCE(AUTOPOLS,0) AUTOPOLS ,COALESCE(HOMEPOLS,0) HOMEPOLS ,COALESCE(MANHOMEPOLS,0) MANHOMEPOLS ,
COALESCE(FARMPOLS,0) FARMPOLS ,COALESCE(FIREPOLS,0) FIREPOLS ,COALESCE(SMLNPOLS,0) SMLNPOLS,COALESCE(PORTPOLS,0) PORTPOLS ,
COALESCE(RHPOLS,0) RHPOLS ,COALESCE(LOANS,0 ) LOANS,COALESCE(ASICPOLS,0) ASICPOLS ,COALESCE(LIFEPOLS,0 ) LIFEPOLS,
COALESCE(FGMPOLS ,0) FGMPOLS 
FROM MEMB_FLOW_TEMP A
LEFT OUTER JOIN
 MEMB_BUCKET_TEMP B
ON A.MEMB_NUM=B.MEMB_NUM )q1
 JOIN
( SELECT PERIOD,   SUM(CASE WHEN (MEMB_STATUS=4) THEN 1 ELSE 0  END)+ SUM(CASE WHEN (MEMB_STATUS=3) THEN 1 ELSE 0 END) 
OVERALL_BEGMIF_CNT,
SUM(CASE WHEN (MEMB_STATUS=4) THEN 1 ELSE 0 END)+ SUM(CASE WHEN (MEMB_STATUS=1) THEN 1 ELSE 0 END)+ SUM(CASE 
WHEN (MEMB_STATUS=2) THEN 1 else 0 END) OVERALL_ENDMIF_CNT FROM 
 MEMB_FLOW_TEMP A
LEFT OUTER JOIN
 MEMB_BUCKET_TEMP B
ON A.MEMB_NUM=B.MEMB_NUM GROUP BY 1)Q
ON Q.PERIOD =Q1.PERIOD
)QUERY1 GROUP BY 1,2,3,12,13)qUERY1)

SELECT MO_ID, PERIOD ,group_cd, BEGMIF_CNT ,ENDMIF_CNT ,CAST(PCT_MIF AS DECIMAL(5,2)) AS PCT_MIF ,New_Cnt ,Lapse_Cnt ,Net_GL_Cnt ,CAST(New_Rate AS DECIMAL(5,2)) AS New_Rate ,CAST(Lapse_Rate AS DECIMAL(5,2)) AS Lapse_Rate ,CAST(Net_GL_Rate AS DECIMAL(5,2)) AS Net_GL_Rate FROM (
SELECT MO_ID,qrya.PERIOD,  group_cd, BEGMIF_CNT ,ENDMIF_CNT , (ENDMIF_CNT/cast(OVERALL_ENDMIF_CNT as decimal(12,5)))*100 PCT_MIF ,New_Cnt ,Lapse_Cnt ,Net_GL_Cnt ,(NEW_CNT/cast(AVGMIF_CNT as decimal(12,5)) )*100 NEW_RATE ,(LAPSE_CNT/cast(AVGMIF_CNT as decimal(12,5)))*100 LAPSE_RATE, (NET_GL_CNT/cast(AVGMIF_CNT as decimal(12,5)))*100 NET_GL_RATE FROM (
SELECT MO_ID,PERIOD,GROUP_CD,SUM(BEGMIF_CNT) BEGMIF_CNT , SUM(ENDMIF_CNT) ENDMIF_CNT , SUM(New_Cnt) New_Cnt, SUM(Lapse_CnT) Lapse_Cnt, SUM(Net_GL_Cnt) Net_GL_Cnt,SUM(AVGMIF_CNT) AVGMIF_CNT from (
SELECT MO_ID,PERIOD, case when ( group_cd in (2,3,4,5,6,7,8,9,10,11,12,13,14,15)) then 1
when ( group_cd in (17,18,19,20,21,22,23,24)) then 16
when ( group_cd in (26,27)) then 25
when ( group_cd in (32,33)) then 31
when ( group_cd in(35,36)) then 34 end Group_cd,
 BEGMIF_CNT ,  ENDMIF_CNT , New_Cnt,  Lapse_Cnt, Net_GL_Cnt, AVGMIF_CNT
FROM AGG_MEMB_FLOW_TEMP)qry 
GROUP BY MO_ID,PERIOD,group_cd) qryA join  (SELECT DISTINCT PERIOD, OVERALL_ENDMIF_CNT FROM AGG_MEMB_FLOW_TEMP) QRYB on QRYA.PERIOD = QRYB.PERIOD) QRY1

UNION

SELECT MO_ID,PERIOD, group_cd,BEGMIF_CNT ,ENDMIF_CNT ,CAST(PCT_MIF AS DECIMAL(5,2)) AS PCT_MIF ,New_Cnt ,Lapse_Cnt ,Net_GL_Cnt ,CAST(New_Rate AS DECIMAL(5,2)) AS New_Rate ,CAST(Lapse_Rate AS DECIMAL(5,2)) AS Lapse_Rate ,CAST(Net_GL_Rate AS DECIMAL(5,2)) AS Net_GL_Rate FROM (
SELECT MO_ID,qrya.PERIOD, 37 group_cd, BEGMIF_CNT ,ENDMIF_CNT , (ENDMIF_CNT/cast(OVERALL_ENDMIF_CNT as decimal(12,5)))*100 PCT_MIF ,New_Cnt ,Lapse_Cnt ,Net_GL_Cnt ,(NEW_CNT/cast(AVGMIF_CNT as decimal(12,5)) )*100 NEW_RATE ,(LAPSE_CNT/cast(AVGMIF_CNT as decimal(12,5)))*100 LAPSE_RATE, (NET_GL_CNT/cast(AVGMIF_CNT as decimal(12,5)))*100 NET_GL_RATE FROM(
SELECT MO_ID,PERIOD,
SUM(BEGMIF_CNT) BEGMIF_CNT , SUM(ENDMIF_CNT) ENDMIF_CNT , SUM(New_Cnt) New_Cnt, SUM(Lapse_CnT) Lapse_Cnt, SUM(Net_GL_Cnt) Net_GL_Cnt,SUM(AVGMIF_CNT) AVGMIF_CNT
FROM AGG_MEMB_FLOW_TEMP
GROUP BY MO_ID,PERIOD) qryA join  (SELECT DISTINCT PERIOD, OVERALL_ENDMIF_CNT FROM AGG_MEMB_FLOW_TEMP) QRYB on QRYA.PERIOD = QRYB.PERIOD) QRY27

UNION

SELECT MO_ID, PERIOD, group_cd, BEGMIF_CNT ,ENDMIF_CNT ,CAST(PCT_MIF AS DECIMAL(5,2)) AS PCT_MIF ,New_Cnt ,Lapse_Cnt ,Net_GL_Cnt ,CAST(New_Rate AS DECIMAL(5,2)) AS New_Rate ,CAST(Lapse_Rate AS DECIMAL(5,2)) AS Lapse_Rate ,CAST(Net_GL_Rate AS DECIMAL(5,2)) AS Net_GL_Rate 
FROM AGG_MEMB_FLOW_TEMP
) SRC
)
);


-- Component exp_Pass_Through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Pass_Through AS
(
SELECT
SQ_AGG_MEMB_FLOW.MO_ID as MO_ID,
SQ_AGG_MEMB_FLOW.PERIOD as PERIOD,
SQ_AGG_MEMB_FLOW.GROUP_CD as GROUP_CD,
SQ_AGG_MEMB_FLOW.BEGMIF_CNT as BEGMIF_CNT,
SQ_AGG_MEMB_FLOW.ENDMIF_CNT as ENDMIF_CNT,
SQ_AGG_MEMB_FLOW.PCT_MIF as PCT_MIF,
SQ_AGG_MEMB_FLOW.NEW_CNT as NEW_CNT,
SQ_AGG_MEMB_FLOW.LAPSE_CNT as LAPSE_CNT,
SQ_AGG_MEMB_FLOW.NET_GL_CNT as NET_GL_CNT,
SQ_AGG_MEMB_FLOW.NEW_RATE as NEW_RATE,
SQ_AGG_MEMB_FLOW.LAPSE_RATE as LAPSE_RATE,
SQ_AGG_MEMB_FLOW.NET_GL_RATE as NET_GL_RATE,
SQ_AGG_MEMB_FLOW.source_record_id
FROM
SQ_AGG_MEMB_FLOW
);


-- Component AGG_MEMB_FLOW, Type TARGET 
INSERT INTO DB_T_CORE_MEMBXREF_PROD.AGG_MEMB_FLOW
(
MO_ID,
PERIOD,
GROUP_CD,
BEGMIF_CNT,
ENDMIF_CNT,
PCT_MIF,
NEW_CNT,
LAPSE_CNT,
NET_GL_CNT,
NEW_RATE,
LAPSE_RATE,
NET_GL_RATE
)
SELECT
exp_Pass_Through.MO_ID as MO_ID,
exp_Pass_Through.PERIOD as PERIOD,
exp_Pass_Through.GROUP_CD as GROUP_CD,
exp_Pass_Through.BEGMIF_CNT as BEGMIF_CNT,
exp_Pass_Through.ENDMIF_CNT as ENDMIF_CNT,
exp_Pass_Through.PCT_MIF as PCT_MIF,
exp_Pass_Through.NEW_CNT as NEW_CNT,
exp_Pass_Through.LAPSE_CNT as LAPSE_CNT,
exp_Pass_Through.NET_GL_CNT as NET_GL_CNT,
exp_Pass_Through.NEW_RATE as NEW_RATE,
exp_Pass_Through.LAPSE_RATE as LAPSE_RATE,
exp_Pass_Through.NET_GL_RATE as NET_GL_RATE
FROM
exp_Pass_Through;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2
-- Component AGG_COUNT_BALANCE, Type Pre SQL 
DELETE FROM DB_T_CORE_PROD.AGG_COUNT_BALANCE WHERE TBL_NM =''V_MEMBER_SUMMARY_TOP'' AND	MO_ID =  YEAR(:wf_CAL_END_DT) *100 + 
MONTH(:wf_CAL_END_DT) AND METRIC_NM = ''MEMBER_INFORCE_COUNT'' AND CALC_SRC = ''AGG'';

DELETE FROM DB_T_CORE_PROD.AGG_COUNT_BALANCE WHERE TBL_NM =''AGG_MEMB_FLOW'' AND MO_ID =  YEAR(:wf_CAL_END_DT) *100 + 
MONTH(:wf_CAL_END_DT) AND METRIC_NM = ''MEMBER_INFORCE_COUNT''  AND CALC_SRC = ''AGG'';


-- Component SQ_AGG_MEMB_FLOW1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_MEMB_FLOW1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_BATCH_ID,
$2 as MO_ID,
$3 as CALC_SRC,
$4 as TBL_NM,
$5 as METRIC_NM,
$6 as METRIC_CNT,
$7 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH TEMP_FED_DATE AS(
SELECT 
MONTH( FEED_DT) MO_ID,
cast(:wf_CAL_END_DT as date ) AS MEMBXREF_LD_DT 
FROM DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER STAG, DB_V_PROD_SMNTC.CALENDAR A 
WHERE STAG.FEED_DT=A.CALENDAR_DATE GROUP BY 1,2)

SELECT	  ( YEAR( CAL_DATE) *100 + MONTH( CAL_DATE)) *100 +  DAY( CAL_DATE),  YEAR( CAL_DATE) *100 + MONTH( CAL_DATE) MO_ID , ''AGG'',''V_MEMBER_SUMMARY_TOP'',''MEMBER_INFORCE_COUNT'' ,SUM(INFORCE_MEMB_COUNT) METRIC_CNT  
FROM 	DB_V_MEMBXREF_PROD.V_MEMBER_SUMMARY_TOP A,TEMP_FED_DATE B WHERE A.CAL_DATE = B.MEMBXREF_LD_DT  GROUP BY 1,2,3,4,5

 UNION

SELECT   ( YEAR( :wf_CAL_END_DT) *100 + MONTH( :wf_CAL_END_DT)) *100 +  DAY( :wf_CAL_END_DT),  YEAR(:wf_CAL_END_DT) *100 + MONTH(:wf_CAL_END_DT) MO_ID ,
''AGG'',''AGG_MEMB_FLOW'',''MEMBER_INFORCE_COUNT'', ENDMIF_CNT   FROM DB_T_CORE_MEMBXREF_PROD.AGG_MEMB_FLOW 
WHERE GROUP_CD=37 AND MO_ID =  YEAR(:wf_CAL_END_DT) *100 + MONTH(:wf_CAL_END_DT) AND PERIOD =''MTD''
) SRC
)
);


-- Component exp_Pass_Through1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Pass_Through1 AS
(
SELECT
SQ_AGG_MEMB_FLOW1.ECTL_BATCH_ID as ECTL_BATCH_ID,
SQ_AGG_MEMB_FLOW1.MO_ID as MO_ID,
SQ_AGG_MEMB_FLOW1.CALC_SRC as CALC_SRC,
SQ_AGG_MEMB_FLOW1.TBL_NM as TBL_NM,
SQ_AGG_MEMB_FLOW1.METRIC_NM as METRIC_NM,
SQ_AGG_MEMB_FLOW1.METRIC_CNT as METRIC_CNT,
SQ_AGG_MEMB_FLOW1.source_record_id
FROM
SQ_AGG_MEMB_FLOW1
);


-- Component AGG_COUNT_BALANCE, Type TARGET 
INSERT INTO DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE
(
ECTL_BATCH_ID,
MO_ID,
CALC_SRC,
TBL_NM,
METRIC_NM,
METRIC_CNT
)
SELECT
exp_Pass_Through1.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_Pass_Through1.MO_ID as MO_ID,
exp_Pass_Through1.CALC_SRC as CALC_SRC,
exp_Pass_Through1.TBL_NM as TBL_NM,
exp_Pass_Through1.METRIC_NM as METRIC_NM,
exp_Pass_Through1.METRIC_CNT as METRIC_CNT
FROM
exp_Pass_Through1;


-- PIPELINE END FOR 2

-- PIPELINE START FOR 3

-- Component SQ_AGG_MEMB_FLOW2, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_AGG_MEMB_FLOW2 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CNT1,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT COUNT(a.CNT1), COUNT(b.CNT2)
FROM
(SELECT METRIC_CNT as CNT1  FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE  WHERE TBL_NM =''V_MEMBER_SUMMARY_TOP'' AND	MO_ID =  YEAR(:wf_CAL_END_DT) *100 + 
MONTH(:wf_CAL_END_DT) AND METRIC_NM = ''MEMBER_INFORCE_COUNT'' AND CALC_SRC = ''AGG'') a,

(SELECT METRIC_CNT as CNT2 FROM DB_T_CORE_FIN_PROD.AGG_COUNT_BALANCE  WHERE TBL_NM =''AGG_MEMB_FLOW'' AND MO_ID =  YEAR(:wf_CAL_END_DT) *100 + 
MONTH(:wf_CAL_END_DT) AND METRIC_NM = ''MEMBER_INFORCE_COUNT''  AND CALC_SRC = ''AGG'') b
WHERE a.CNT1 - b.CNT2 = 0
) SRC
)
);


-- Component exp_Pass_Through2, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Pass_Through2 AS
(
SELECT
CASE WHEN SQ_AGG_MEMB_FLOW2.CNT1 <> 0 THEN ''S'' ELSE ''F'' END as FLAG,
CASE WHEN SQ_AGG_MEMB_FLOW2.CNT1 = 0 THEN 
null --RAISE_ERROR(''MEMBERS INFORCE COUNT IS NOT MATCHING BETWEEN MEMBER FLOW AND FEDERATION'') 
ELSE 
null END as ABORT,
SQ_AGG_MEMB_FLOW2.source_record_id
FROM
SQ_AGG_MEMB_FLOW2
);


-- Component exp_Pass_Through3, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Pass_Through3 AS
(
SELECT
exp_Pass_Through2.FLAG as FLAG,
exp_Pass_Through2.source_record_id
FROM
exp_Pass_Through2
);


-- Component DUMMY, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE DUMMY AS
(
SELECT
exp_Pass_Through3.FLAG as FLAG
FROM
exp_Pass_Through3
);


-- Component DUMMY, Type EXPORT_DATA Exporting data
COPY INTO @public.edw_stage/my_export_folder/DUMMY_
FROM (SELECT * FROM DUMMY)
HEADER = TRUE
OVERWRITE = TRUE;


-- PIPELINE END FOR 3

END; ';