-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_PORTPOLS_DLY("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE PMMAPPINGNAME varchar;
PROJ_ID varchar;
BATCH_ACTIVE_IND varchar;
BEGIN 


-- Component LKP_STG_MEMBXEF_TRIGGER_DLY, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_STG_MEMBXEF_TRIGGER_DLY AS
(
SELECT
FEED_DT,
TABLENAME
FROM DB_T_STAG_MEMBXREF_PROD.STG_MEMBXREF_TRIGGER_DLY
);


-- PIPELINE START FOR 1

-- Component sq_STG_PORTPOLS_DLY, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_STG_PORTPOLS_DLY AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_DWNLD_PRIORITY,
$2 as SC_SERVICE_CENTER,
$3 as SC_POLICY_NUM,
$4 as SC_FLT_ITEM,
$5 as SC_FILE_TYPE,
$6 as SC_REC_TRANS_CODE,
$7 as SC_TRANS_DATE,
$8 as SC_TRANS_TYPE,
$9 as PC_ALPHA_CODE,
$10 as PC_NAME_1,
$11 as PC_NAME_2,
$12 as PC_ADDRESS_1,
$13 as PC_ADDRESS_2,
$14 as PC_CITYST,
$15 as PC_ZIP,
$16 as PC_TAX_CODE,
$17 as PC_AGENT,
$18 as PC_MEMBER_NUMBER,
$19 as PC_RATE_CODE,
$20 as PC_ENCUMBRANCE,
$21 as PC_PREM_FIN,
$22 as PC_MORT_IND,
$23 as PC_COMPANY,
$24 as PC_INCEPT_DATE,
$25 as PC_EXP_DATE,
$26 as PC_EFF_DATE,
$27 as PC_STATUS,
$28 as PORT_TOT_PREM,
$29 as PORT_REWRITE_IND,
$30 as PORT_REWRITE_DATE,
$31 as PORT_OUTST_AMT,
$32 as PORT_OUTST_TYPE,
$33 as PORT_OUTST_DATE,
$34 as PORT_OUTST_PD_DATE,
$35 as PORT_SUSPENSE_CD,
$36 as PORT_SUSPENSE_CAN,
$37 as PORT_SSN_1,
$38 as PORT_SSN_2,
$39 as PORT_UW_REV_DATE,
$40 as PORT_UW_INITIALS,
$41 as PORT_MORT_NAME_1,
$42 as PORT_MORT_NAME_2,
$43 as PORT_MORT_ADD_1,
$44 as PORT_MORT_ADD_2,
$45 as PORT_MORT_CTYST,
$46 as PORT_MORT_ZIP,
$47 as PORT_STATE,
$48 as PORT_MORT_TYPE,
$49 as PORT_LOAN_NUM,
$50 as PORT_SLOAN_NUM,
$51 as PORT_SMORT_NAME_1,
$52 as PORT_SMORT_NAME_2,
$53 as PORT_SMORT_ADD_1,
$54 as PORT_SMORT_ADD_2,
$55 as PORT_SMORT_CTYST,
$56 as PORT_SMORT_ZIP,
$57 as PORT_SMORT_TYPE,
$58 as PORT_HALF_TERM_BP,
$59 as PORT_FULL_TERM_BP,
$60 as PORT_TRANSFER_DATE,
$61 as PORT_MB_TYPE,
$62 as PORT_MB_ACCT_NUM,
$63 as PORT_SC_LIAB_PRD_I,
$64 as PORT_FIRE_COVERAGE,
$65 as LOAD_DT,
$66 as FEED_IND,
$67 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT STG_PORTPOLS_DLY.SC_DWNLD_PRIORITY, STG_PORTPOLS_DLY.SC_SERVICE_CENTER, 
LTRIM(RTRIM(STG_PORTPOLS_DLY.SC_POLICY_NUM)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.SC_FLT_ITEM)), STG_PORTPOLS_DLY.SC_FILE_TYPE, STG_PORTPOLS_DLY.SC_REC_TRANS_CODE, STG_PORTPOLS_DLY.SC_TRANS_DATE, STG_PORTPOLS_DLY.SC_TRANS_TYPE, 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_ALPHA_CODE)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_NAME_1)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_NAME_2)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_ADDRESS_1)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_ADDRESS_2)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_CITYST)),
 STG_PORTPOLS_DLY.PC_ZIP, 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_TAX_CODE)), STG_PORTPOLS_DLY.PC_AGENT, 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_MEMBER_NUMBER)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_RATE_CODE)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_ENCUMBRANCE)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_PREM_FIN)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_MORT_IND)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_COMPANY)), STG_PORTPOLS_DLY.PC_INCEPT_DATE, STG_PORTPOLS_DLY.PC_EXP_DATE, STG_PORTPOLS_DLY.PC_EFF_DATE, 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PC_STATUS)), STG_PORTPOLS_DLY.PORT_TOT_PREM, 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_REWRITE_IND)), STG_PORTPOLS_DLY.PORT_REWRITE_DATE, STG_PORTPOLS_DLY.PORT_OUTST_AMT, 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_OUTST_TYPE)), STG_PORTPOLS_DLY.PORT_OUTST_DATE, STG_PORTPOLS_DLY.PORT_OUTST_PD_DATE, 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_SUSPENSE_CD)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_SUSPENSE_CAN)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_SSN_1)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_SSN_2)), STG_PORTPOLS_DLY.PORT_UW_REV_DATE, 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_UW_INITIALS)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_MORT_NAME_1)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_MORT_NAME_2)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_MORT_ADD_1)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_MORT_ADD_2)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_MORT_CTYST)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_MORT_ZIP)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_STATE)), STG_PORTPOLS_DLY.PORT_MORT_TYPE, 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_LOAN_NUM)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_SLOAN_NUM)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_SMORT_NAME_1)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_SMORT_NAME_2)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_SMORT_ADD_1)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_SMORT_ADD_2)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_SMORT_CTYST)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_SMORT_ZIP)), STG_PORTPOLS_DLY.PORT_SMORT_TYPE, STG_PORTPOLS_DLY.PORT_HALF_TERM_BP, STG_PORTPOLS_DLY.PORT_FULL_TERM_BP, STG_PORTPOLS_DLY.PORT_TRANSFER_DATE, 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_MB_TYPE)), 
LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_MB_ACCT_NUM)), LTRIM(RTRIM(STG_PORTPOLS_DLY.PORT_SC_LIAB_PRD_I)), STG_PORTPOLS_DLY.PORT_FIRE_COVERAGE, STG_PORTPOLS_DLY.LOAD_DT, 
LTRIM(RTRIM(STG_PORTPOLS_DLY.FEED_IND ))
FROM DB_T_STAG_MEMBXREF_PROD.STG_PORTPOLS_DLY STG_PORTPOLS_DLY 
) SRC
)
);


-- Component exp_HOLD_DATA, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_HOLD_DATA AS
(
SELECT
sq_STG_PORTPOLS_DLY.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
sq_STG_PORTPOLS_DLY.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
sq_STG_PORTPOLS_DLY.SC_POLICY_NUM as SC_POLICY_NUM,
sq_STG_PORTPOLS_DLY.SC_FLT_ITEM as SC_FLT_ITEM,
sq_STG_PORTPOLS_DLY.SC_FILE_TYPE as SC_FILE_TYPE,
sq_STG_PORTPOLS_DLY.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
sq_STG_PORTPOLS_DLY.SC_TRANS_DATE as SC_TRANS_DATE,
sq_STG_PORTPOLS_DLY.SC_TRANS_TYPE as SC_TRANS_TYPE,
sq_STG_PORTPOLS_DLY.PC_ALPHA_CODE as PC_ALPHA_CODE,
sq_STG_PORTPOLS_DLY.PC_NAME_1 as PC_NAME_1,
sq_STG_PORTPOLS_DLY.PC_NAME_2 as PC_NAME_2,
sq_STG_PORTPOLS_DLY.PC_ADDRESS_1 as PC_ADDRESS_1,
sq_STG_PORTPOLS_DLY.PC_ADDRESS_2 as PC_ADDRESS_2,
sq_STG_PORTPOLS_DLY.PC_CITYST as PC_CITYST,
sq_STG_PORTPOLS_DLY.PC_ZIP as PC_ZIP,
sq_STG_PORTPOLS_DLY.PC_TAX_CODE as PC_TAX_CODE,
sq_STG_PORTPOLS_DLY.PC_AGENT as PC_AGENT,
sq_STG_PORTPOLS_DLY.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
sq_STG_PORTPOLS_DLY.PC_RATE_CODE as PC_RATE_CODE,
sq_STG_PORTPOLS_DLY.PC_ENCUMBRANCE as PC_ENCUMBRANCE,
sq_STG_PORTPOLS_DLY.PC_PREM_FIN as PC_PREM_FIN,
sq_STG_PORTPOLS_DLY.PC_MORT_IND as PC_MORT_IND,
sq_STG_PORTPOLS_DLY.PC_COMPANY as PC_COMPANY,
sq_STG_PORTPOLS_DLY.PC_INCEPT_DATE as PC_INCEPT_DATE,
sq_STG_PORTPOLS_DLY.PC_EXP_DATE as PC_EXP_DATE,
sq_STG_PORTPOLS_DLY.PC_EFF_DATE as PC_EFF_DATE,
sq_STG_PORTPOLS_DLY.PC_STATUS as PC_STATUS,
sq_STG_PORTPOLS_DLY.PORT_TOT_PREM as PORT_TOT_PREM,
sq_STG_PORTPOLS_DLY.PORT_REWRITE_IND as PORT_REWRITE_IND,
sq_STG_PORTPOLS_DLY.PORT_REWRITE_DATE as PORT_REWRITE_DATE,
sq_STG_PORTPOLS_DLY.PORT_OUTST_AMT as PORT_OUTST_AMT,
sq_STG_PORTPOLS_DLY.PORT_OUTST_TYPE as PORT_OUTST_TYPE,
sq_STG_PORTPOLS_DLY.PORT_OUTST_DATE as PORT_OUTST_DATE,
sq_STG_PORTPOLS_DLY.PORT_OUTST_PD_DATE as PORT_OUTST_PD_DATE,
sq_STG_PORTPOLS_DLY.PORT_SUSPENSE_CD as PORT_SUSPENSE_CD,
sq_STG_PORTPOLS_DLY.PORT_SUSPENSE_CAN as PORT_SUSPENSE_CAN,
sq_STG_PORTPOLS_DLY.PORT_SSN_1 as PORT_SSN_1,
sq_STG_PORTPOLS_DLY.PORT_SSN_2 as PORT_SSN_2,
sq_STG_PORTPOLS_DLY.PORT_UW_REV_DATE as PORT_UW_REV_DATE,
sq_STG_PORTPOLS_DLY.PORT_UW_INITIALS as PORT_UW_INITIALS,
sq_STG_PORTPOLS_DLY.PORT_MORT_NAME_1 as PORT_MORT_NAME_1,
sq_STG_PORTPOLS_DLY.PORT_MORT_NAME_2 as PORT_MORT_NAME_2,
sq_STG_PORTPOLS_DLY.PORT_MORT_ADD_1 as PORT_MORT_ADD_1,
sq_STG_PORTPOLS_DLY.PORT_MORT_ADD_2 as PORT_MORT_ADD_2,
sq_STG_PORTPOLS_DLY.PORT_MORT_CTYST as PORT_MORT_CTYST,
sq_STG_PORTPOLS_DLY.PORT_MORT_ZIP as PORT_MORT_ZIP,
sq_STG_PORTPOLS_DLY.PORT_STATE as PORT_STATE,
sq_STG_PORTPOLS_DLY.PORT_MORT_TYPE as PORT_MORT_TYPE,
sq_STG_PORTPOLS_DLY.PORT_LOAN_NUM as PORT_LOAN_NUM,
sq_STG_PORTPOLS_DLY.PORT_SLOAN_NUM as PORT_SLOAN_NUM,
sq_STG_PORTPOLS_DLY.PORT_SMORT_NAME_1 as PORT_SMORT_NAME_1,
sq_STG_PORTPOLS_DLY.PORT_SMORT_NAME_2 as PORT_SMORT_NAME_2,
sq_STG_PORTPOLS_DLY.PORT_SMORT_ADD_1 as PORT_SMORT_ADD_1,
sq_STG_PORTPOLS_DLY.PORT_SMORT_ADD_2 as PORT_SMORT_ADD_2,
sq_STG_PORTPOLS_DLY.PORT_SMORT_CTYST as PORT_SMORT_CTYST,
sq_STG_PORTPOLS_DLY.PORT_SMORT_ZIP as PORT_SMORT_ZIP,
sq_STG_PORTPOLS_DLY.PORT_SMORT_TYPE as PORT_SMORT_TYPE,
sq_STG_PORTPOLS_DLY.PORT_HALF_TERM_BP as PORT_HALF_TERM_BP,
sq_STG_PORTPOLS_DLY.PORT_FULL_TERM_BP as PORT_FULL_TERM_BP,
sq_STG_PORTPOLS_DLY.PORT_TRANSFER_DATE as PORT_TRANSFER_DATE,
sq_STG_PORTPOLS_DLY.PORT_MB_TYPE as PORT_MB_TYPE,
sq_STG_PORTPOLS_DLY.PORT_MB_ACCT_NUM as PORT_MB_ACCT_NUM,
sq_STG_PORTPOLS_DLY.PORT_SC_LIAB_PRD_I as PORT_SC_LIAB_PRD_I,
sq_STG_PORTPOLS_DLY.PORT_FIRE_COVERAGE as PORT_FIRE_COVERAGE,
sq_STG_PORTPOLS_DLY.LOAD_DT as LOAD_DT,
sq_STG_PORTPOLS_DLY.FEED_IND as FEED_IND,
sq_STG_PORTPOLS_DLY.source_record_id
FROM
sq_STG_PORTPOLS_DLY
);


-- Component LKP_PORTPOLS_DLY, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_PORTPOLS_DLY AS
(
SELECT
LKP.SC_DWNLD_PRIORITY,
LKP.SC_SERVICE_CENTER,
LKP.SC_POLICY_NUM,
LKP.CHG_EFF_DT,
LKP.CHG_EXP_DT,
LKP.SC_FLT_ITEM,
LKP.SC_FILE_TYPE,
LKP.SC_REC_TRANS_CODE,
LKP.SC_TRANS_DATE,
LKP.SC_TRANS_TYPE,
LKP.PC_ALPHA_CODE,
LKP.PC_NAME_1,
LKP.PC_NAME_2,
LKP.PC_ADDRESS_1,
LKP.PC_ADDRESS_2,
LKP.PC_CITYST,
LKP.PC_ZIP,
LKP.PC_TAX_CODE,
LKP.PC_AGENT,
LKP.PC_MEMBER_NUMBER,
LKP.PC_RATE_CODE,
LKP.PC_ENCUMBRANCE,
LKP.PC_PREM_FIN,
LKP.PC_MORT_IND,
LKP.PC_COMPANY,
LKP.PC_INCEPT_DATE,
LKP.PC_EXP_DATE,
LKP.PC_EFF_DATE,
LKP.PC_STATUS,
LKP.PORT_TOT_PREM,
LKP.PORT_REWRITE_IND,
LKP.PORT_REWRITE_DATE,
LKP.PORT_OUTST_AMT,
LKP.PORT_OUTST_TYPE,
LKP.PORT_OUTST_DATE,
LKP.PORT_OUTST_PD_DATE,
LKP.PORT_SUSPENSE_CD,
LKP.PORT_SUSPENSE_CAN,
LKP.PORT_SSN_1,
LKP.PORT_SSN_2,
LKP.PORT_UW_REV_DATE,
LKP.PORT_UW_INITIALS,
LKP.PORT_MORT_NAME_1,
LKP.PORT_MORT_NAME_2,
LKP.PORT_MORT_ADD_1,
LKP.PORT_MORT_ADD_2,
LKP.PORT_MORT_CTYST,
LKP.PORT_MORT_ZIP,
LKP.PORT_STATE,
LKP.PORT_MORT_TYPE,
LKP.PORT_LOAN_NUM,
LKP.PORT_SLOAN_NUM,
LKP.PORT_SMORT_NAME_1,
LKP.PORT_SMORT_NAME_2,
LKP.PORT_SMORT_ADD_1,
LKP.PORT_SMORT_ADD_2,
LKP.PORT_SMORT_CTYST,
LKP.PORT_SMORT_ZIP,
LKP.PORT_SMORT_TYPE,
LKP.PORT_HALF_TERM_BP,
LKP.PORT_FULL_TERM_BP,
LKP.PORT_TRANSFER_DATE,
LKP.PORT_MB_TYPE,
LKP.PORT_MB_ACCT_NUM,
LKP.PORT_SC_LIAB_PRD_I,
LKP.PORT_FIRE_COVERAGE,
LKP.FEED_IND,
exp_HOLD_DATA.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_HOLD_DATA.source_record_id ORDER BY LKP.SC_DWNLD_PRIORITY asc,LKP.SC_SERVICE_CENTER asc,LKP.SC_POLICY_NUM asc,LKP.CHG_EFF_DT asc,LKP.CHG_EXP_DT asc,LKP.SC_FLT_ITEM asc,LKP.SC_FILE_TYPE asc,LKP.SC_REC_TRANS_CODE asc,LKP.SC_TRANS_DATE asc,LKP.SC_TRANS_TYPE asc,LKP.PC_ALPHA_CODE asc,LKP.PC_NAME_1 asc,LKP.PC_NAME_2 asc,LKP.PC_ADDRESS_1 asc,LKP.PC_ADDRESS_2 asc,LKP.PC_CITYST asc,LKP.PC_ZIP asc,LKP.PC_TAX_CODE asc,LKP.PC_AGENT asc,LKP.PC_MEMBER_NUMBER asc,LKP.PC_RATE_CODE asc,LKP.PC_ENCUMBRANCE asc,LKP.PC_PREM_FIN asc,LKP.PC_MORT_IND asc,LKP.PC_COMPANY asc,LKP.PC_INCEPT_DATE asc,LKP.PC_EXP_DATE asc,LKP.PC_EFF_DATE asc,LKP.PC_STATUS asc,LKP.PORT_TOT_PREM asc,LKP.PORT_REWRITE_IND asc,LKP.PORT_REWRITE_DATE asc,LKP.PORT_OUTST_AMT asc,LKP.PORT_OUTST_TYPE asc,LKP.PORT_OUTST_DATE asc,LKP.PORT_OUTST_PD_DATE asc,LKP.PORT_SUSPENSE_CD asc,LKP.PORT_SUSPENSE_CAN asc,LKP.PORT_SSN_1 asc,LKP.PORT_SSN_2 asc,LKP.PORT_UW_REV_DATE asc,LKP.PORT_UW_INITIALS asc,LKP.PORT_MORT_NAME_1 asc,LKP.PORT_MORT_NAME_2 asc,LKP.PORT_MORT_ADD_1 asc,LKP.PORT_MORT_ADD_2 asc,LKP.PORT_MORT_CTYST asc,LKP.PORT_MORT_ZIP asc,LKP.PORT_STATE asc,LKP.PORT_MORT_TYPE asc,LKP.PORT_LOAN_NUM asc,LKP.PORT_SLOAN_NUM asc,LKP.PORT_SMORT_NAME_1 asc,LKP.PORT_SMORT_NAME_2 asc,LKP.PORT_SMORT_ADD_1 asc,LKP.PORT_SMORT_ADD_2 asc,LKP.PORT_SMORT_CTYST asc,LKP.PORT_SMORT_ZIP asc,LKP.PORT_SMORT_TYPE asc,LKP.PORT_HALF_TERM_BP asc,LKP.PORT_FULL_TERM_BP asc,LKP.PORT_TRANSFER_DATE asc,LKP.PORT_MB_TYPE asc,LKP.PORT_MB_ACCT_NUM asc,LKP.PORT_SC_LIAB_PRD_I asc,LKP.PORT_FIRE_COVERAGE asc,LKP.FEED_IND asc,LKP.ECTL_BATCH_ID asc,LKP.ECTL_ORIG_INS_TS asc,LKP.ECTL_MODIFY_TS asc,LKP.ECTL_SRC_ID asc,LKP.ECTL_SRC_INST_ID asc,LKP.ECTL_PRGM_ID asc,LKP.ECTL_TX_CD asc,LKP.ECTL_START_DATE asc,LKP.ECTL_END_DATE asc) RNK
FROM
exp_HOLD_DATA
LEFT JOIN (
SELECT PORTPOLS_DLY.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY, PORTPOLS_DLY.SC_SERVICE_CENTER as SC_SERVICE_CENTER, PORTPOLS_DLY.CHG_EFF_DT as CHG_EFF_DT, PORTPOLS_DLY.CHG_EXP_DT as CHG_EXP_DT, PORTPOLS_DLY.SC_FLT_ITEM as SC_FLT_ITEM, PORTPOLS_DLY.SC_FILE_TYPE as SC_FILE_TYPE, PORTPOLS_DLY.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE, PORTPOLS_DLY.SC_TRANS_DATE as SC_TRANS_DATE, PORTPOLS_DLY.SC_TRANS_TYPE as SC_TRANS_TYPE, PORTPOLS_DLY.PC_ALPHA_CODE as PC_ALPHA_CODE, PORTPOLS_DLY.PC_NAME_1 as PC_NAME_1, PORTPOLS_DLY.PC_NAME_2 as PC_NAME_2, PORTPOLS_DLY.PC_ADDRESS_1 as PC_ADDRESS_1, PORTPOLS_DLY.PC_ADDRESS_2 as PC_ADDRESS_2, PORTPOLS_DLY.PC_CITYST as PC_CITYST, PORTPOLS_DLY.PC_ZIP as PC_ZIP, PORTPOLS_DLY.PC_TAX_CODE as PC_TAX_CODE, PORTPOLS_DLY.PC_AGENT as PC_AGENT, PORTPOLS_DLY.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER, PORTPOLS_DLY.PC_RATE_CODE as PC_RATE_CODE, PORTPOLS_DLY.PC_ENCUMBRANCE as PC_ENCUMBRANCE, PORTPOLS_DLY.PC_PREM_FIN as PC_PREM_FIN, PORTPOLS_DLY.PC_MORT_IND as PC_MORT_IND, PORTPOLS_DLY.PC_COMPANY as PC_COMPANY, PORTPOLS_DLY.PC_INCEPT_DATE as PC_INCEPT_DATE, PORTPOLS_DLY.PC_EXP_DATE as PC_EXP_DATE, PORTPOLS_DLY.PC_EFF_DATE as PC_EFF_DATE, PORTPOLS_DLY.PC_STATUS as PC_STATUS, PORTPOLS_DLY.PORT_TOT_PREM as PORT_TOT_PREM, PORTPOLS_DLY.PORT_REWRITE_IND as PORT_REWRITE_IND, PORTPOLS_DLY.PORT_REWRITE_DATE as PORT_REWRITE_DATE, PORTPOLS_DLY.PORT_OUTST_AMT as PORT_OUTST_AMT, PORTPOLS_DLY.PORT_OUTST_TYPE as PORT_OUTST_TYPE, PORTPOLS_DLY.PORT_OUTST_DATE as PORT_OUTST_DATE, PORTPOLS_DLY.PORT_OUTST_PD_DATE as PORT_OUTST_PD_DATE, PORTPOLS_DLY.PORT_SUSPENSE_CD as PORT_SUSPENSE_CD, PORTPOLS_DLY.PORT_SUSPENSE_CAN as PORT_SUSPENSE_CAN, PORTPOLS_DLY.PORT_SSN_1 as PORT_SSN_1, PORTPOLS_DLY.PORT_SSN_2 as PORT_SSN_2, PORTPOLS_DLY.PORT_UW_REV_DATE as PORT_UW_REV_DATE, PORTPOLS_DLY.PORT_UW_INITIALS as PORT_UW_INITIALS, PORTPOLS_DLY.PORT_MORT_NAME_1 as PORT_MORT_NAME_1, PORTPOLS_DLY.PORT_MORT_NAME_2 as PORT_MORT_NAME_2, PORTPOLS_DLY.PORT_MORT_ADD_1 as PORT_MORT_ADD_1, PORTPOLS_DLY.PORT_MORT_ADD_2 as PORT_MORT_ADD_2, PORTPOLS_DLY.PORT_MORT_CTYST as PORT_MORT_CTYST, PORTPOLS_DLY.PORT_MORT_ZIP as PORT_MORT_ZIP, PORTPOLS_DLY.PORT_STATE as PORT_STATE, PORTPOLS_DLY.PORT_MORT_TYPE as PORT_MORT_TYPE, PORTPOLS_DLY.PORT_LOAN_NUM as PORT_LOAN_NUM, PORTPOLS_DLY.PORT_SLOAN_NUM as PORT_SLOAN_NUM, PORTPOLS_DLY.PORT_SMORT_NAME_1 as PORT_SMORT_NAME_1, PORTPOLS_DLY.PORT_SMORT_NAME_2 as PORT_SMORT_NAME_2, PORTPOLS_DLY.PORT_SMORT_ADD_1 as PORT_SMORT_ADD_1, PORTPOLS_DLY.PORT_SMORT_ADD_2 as PORT_SMORT_ADD_2, PORTPOLS_DLY.PORT_SMORT_CTYST as PORT_SMORT_CTYST, PORTPOLS_DLY.PORT_SMORT_ZIP as PORT_SMORT_ZIP, PORTPOLS_DLY.PORT_SMORT_TYPE as PORT_SMORT_TYPE, PORTPOLS_DLY.PORT_HALF_TERM_BP as PORT_HALF_TERM_BP, PORTPOLS_DLY.PORT_FULL_TERM_BP as PORT_FULL_TERM_BP, PORTPOLS_DLY.PORT_TRANSFER_DATE as PORT_TRANSFER_DATE, PORTPOLS_DLY.PORT_MB_TYPE as PORT_MB_TYPE, PORTPOLS_DLY.PORT_MB_ACCT_NUM as PORT_MB_ACCT_NUM, PORTPOLS_DLY.PORT_SC_LIAB_PRD_I as PORT_SC_LIAB_PRD_I, PORTPOLS_DLY.PORT_FIRE_COVERAGE as PORT_FIRE_COVERAGE, PORTPOLS_DLY.FEED_IND as FEED_IND, PORTPOLS_DLY.ECTL_BATCH_ID as ECTL_BATCH_ID, PORTPOLS_DLY.ECTL_ORIG_INS_TS as ECTL_ORIG_INS_TS, PORTPOLS_DLY.ECTL_MODIFY_TS as ECTL_MODIFY_TS, PORTPOLS_DLY.ECTL_SRC_ID as ECTL_SRC_ID, PORTPOLS_DLY.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID, PORTPOLS_DLY.ECTL_PRGM_ID as ECTL_PRGM_ID, PORTPOLS_DLY.ECTL_TX_CD as ECTL_TX_CD, PORTPOLS_DLY.ECTL_START_DATE as ECTL_START_DATE, PORTPOLS_DLY.ECTL_END_DATE as ECTL_END_DATE, PORTPOLS_DLY.SC_POLICY_NUM as SC_POLICY_NUM FROM DB_T_core_MEMBXREF_PROD.PORTPOLS_DLY WHERE PORTPOLS_DLY.ECTL_TX_CD = ''NEW''
) LKP ON LKP.SC_POLICY_NUM = exp_HOLD_DATA.SC_POLICY_NUM
QUALIFY RNK = 1
);


-- Component exp_DERIVE_FLAG, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_DERIVE_FLAG AS
(
SELECT
LKP_PORTPOLS_DLY.SC_POLICY_NUM as SC_POLICY_NUM_lkp,
LKP_PORTPOLS_DLY.CHG_EFF_DT as CHG_EFF_DT_lkp,
exp_HOLD_DATA.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_HOLD_DATA.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_HOLD_DATA.SC_POLICY_NUM as SC_POLICY_NUM,
exp_HOLD_DATA.SC_FLT_ITEM as SC_FLT_ITEM,
exp_HOLD_DATA.SC_FILE_TYPE as SC_FILE_TYPE,
exp_HOLD_DATA.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_HOLD_DATA.SC_TRANS_DATE as SC_TRANS_DATE,
exp_HOLD_DATA.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_HOLD_DATA.PC_ALPHA_CODE as PC_ALPHA_CODE,
exp_HOLD_DATA.PC_NAME_1 as PC_NAME_1,
exp_HOLD_DATA.PC_NAME_2 as PC_NAME_2,
exp_HOLD_DATA.PC_ADDRESS_1 as PC_ADDRESS_1,
exp_HOLD_DATA.PC_ADDRESS_2 as PC_ADDRESS_2,
exp_HOLD_DATA.PC_CITYST as PC_CITYST,
exp_HOLD_DATA.PC_ZIP as PC_ZIP,
exp_HOLD_DATA.PC_TAX_CODE as PC_TAX_CODE,
exp_HOLD_DATA.PC_AGENT as PC_AGENT,
exp_HOLD_DATA.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
exp_HOLD_DATA.PC_RATE_CODE as PC_RATE_CODE,
exp_HOLD_DATA.PC_ENCUMBRANCE as PC_ENCUMBRANCE,
exp_HOLD_DATA.PC_PREM_FIN as PC_PREM_FIN,
exp_HOLD_DATA.PC_MORT_IND as PC_MORT_IND,
exp_HOLD_DATA.PC_COMPANY as PC_COMPANY,
exp_HOLD_DATA.PC_INCEPT_DATE as PC_INCEPT_DATE,
exp_HOLD_DATA.PC_EXP_DATE as PC_EXP_DATE,
exp_HOLD_DATA.PC_EFF_DATE as PC_EFF_DATE,
exp_HOLD_DATA.PC_STATUS as PC_STATUS,
exp_HOLD_DATA.PORT_TOT_PREM as PORT_TOT_PREM,
exp_HOLD_DATA.PORT_REWRITE_IND as PORT_REWRITE_IND,
exp_HOLD_DATA.PORT_REWRITE_DATE as PORT_REWRITE_DATE,
exp_HOLD_DATA.PORT_OUTST_AMT as PORT_OUTST_AMT,
exp_HOLD_DATA.PORT_OUTST_TYPE as PORT_OUTST_TYPE,
exp_HOLD_DATA.PORT_OUTST_DATE as PORT_OUTST_DATE,
exp_HOLD_DATA.PORT_OUTST_PD_DATE as PORT_OUTST_PD_DATE,
exp_HOLD_DATA.PORT_SUSPENSE_CD as PORT_SUSPENSE_CD,
exp_HOLD_DATA.PORT_SUSPENSE_CAN as PORT_SUSPENSE_CAN,
exp_HOLD_DATA.PORT_SSN_1 as PORT_SSN_1,
exp_HOLD_DATA.PORT_SSN_2 as PORT_SSN_2,
exp_HOLD_DATA.PORT_UW_REV_DATE as PORT_UW_REV_DATE,
exp_HOLD_DATA.PORT_UW_INITIALS as PORT_UW_INITIALS,
exp_HOLD_DATA.PORT_MORT_NAME_1 as PORT_MORT_NAME_1,
exp_HOLD_DATA.PORT_MORT_NAME_2 as PORT_MORT_NAME_2,
exp_HOLD_DATA.PORT_MORT_ADD_1 as PORT_MORT_ADD_1,
exp_HOLD_DATA.PORT_MORT_ADD_2 as PORT_MORT_ADD_2,
exp_HOLD_DATA.PORT_MORT_CTYST as PORT_MORT_CTYST,
exp_HOLD_DATA.PORT_MORT_ZIP as PORT_MORT_ZIP,
exp_HOLD_DATA.PORT_STATE as PORT_STATE,
exp_HOLD_DATA.PORT_MORT_TYPE as PORT_MORT_TYPE,
exp_HOLD_DATA.PORT_LOAN_NUM as PORT_LOAN_NUM,
exp_HOLD_DATA.PORT_SLOAN_NUM as PORT_SLOAN_NUM,
exp_HOLD_DATA.PORT_SMORT_NAME_1 as PORT_SMORT_NAME_1,
exp_HOLD_DATA.PORT_SMORT_NAME_2 as PORT_SMORT_NAME_2,
exp_HOLD_DATA.PORT_SMORT_ADD_1 as PORT_SMORT_ADD_1,
exp_HOLD_DATA.PORT_SMORT_ADD_2 as PORT_SMORT_ADD_2,
exp_HOLD_DATA.PORT_SMORT_CTYST as PORT_SMORT_CTYST,
exp_HOLD_DATA.PORT_SMORT_ZIP as PORT_SMORT_ZIP,
exp_HOLD_DATA.PORT_SMORT_TYPE as PORT_SMORT_TYPE,
exp_HOLD_DATA.PORT_HALF_TERM_BP as PORT_HALF_TERM_BP,
exp_HOLD_DATA.PORT_FULL_TERM_BP as PORT_FULL_TERM_BP,
exp_HOLD_DATA.PORT_TRANSFER_DATE as PORT_TRANSFER_DATE,
exp_HOLD_DATA.PORT_MB_TYPE as PORT_MB_TYPE,
exp_HOLD_DATA.PORT_MB_ACCT_NUM as PORT_MB_ACCT_NUM,
exp_HOLD_DATA.PORT_SC_LIAB_PRD_I as PORT_SC_LIAB_PRD_I,
exp_HOLD_DATA.PORT_FIRE_COVERAGE as PORT_FIRE_COVERAGE,
exp_HOLD_DATA.LOAD_DT as LOAD_DT,
exp_HOLD_DATA.FEED_IND as FEED_IND,
CASE WHEN LKP_PORTPOLS_DLY.SC_POLICY_NUM IS NULL THEN ''NEW'' ELSE CASE WHEN CASE WHEN LKP_PORTPOLS_DLY.SC_DWNLD_PRIORITY IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.SC_DWNLD_PRIORITY END <> CASE WHEN exp_HOLD_DATA.SC_DWNLD_PRIORITY IS NULL THEN 0 ELSE exp_HOLD_DATA.SC_DWNLD_PRIORITY END OR CASE WHEN LKP_PORTPOLS_DLY.SC_SERVICE_CENTER IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.SC_SERVICE_CENTER END <> CASE WHEN exp_HOLD_DATA.SC_SERVICE_CENTER IS NULL THEN 0 ELSE exp_HOLD_DATA.SC_SERVICE_CENTER END OR CASE WHEN LKP_PORTPOLS_DLY.SC_FLT_ITEM IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.SC_FLT_ITEM END <> CASE WHEN exp_HOLD_DATA.SC_FLT_ITEM IS NULL THEN ''~'' ELSE exp_HOLD_DATA.SC_FLT_ITEM END OR CASE WHEN LKP_PORTPOLS_DLY.SC_FILE_TYPE IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.SC_FILE_TYPE END <> CASE WHEN exp_HOLD_DATA.SC_FILE_TYPE IS NULL THEN 0 ELSE exp_HOLD_DATA.SC_FILE_TYPE END OR CASE WHEN LKP_PORTPOLS_DLY.SC_REC_TRANS_CODE IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.SC_REC_TRANS_CODE END <> CASE WHEN exp_HOLD_DATA.SC_REC_TRANS_CODE IS NULL THEN 0 ELSE exp_HOLD_DATA.SC_REC_TRANS_CODE END OR CASE WHEN LKP_PORTPOLS_DLY.SC_TRANS_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_PORTPOLS_DLY.SC_TRANS_DATE END <> CASE WHEN exp_HOLD_DATA.SC_TRANS_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.SC_TRANS_DATE END OR CASE WHEN LKP_PORTPOLS_DLY.SC_TRANS_TYPE IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.SC_TRANS_TYPE END <> CASE WHEN exp_HOLD_DATA.SC_TRANS_TYPE IS NULL THEN 0 ELSE exp_HOLD_DATA.SC_TRANS_TYPE END OR CASE WHEN LKP_PORTPOLS_DLY.PC_ALPHA_CODE IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_ALPHA_CODE END <> CASE WHEN exp_HOLD_DATA.PC_ALPHA_CODE IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_ALPHA_CODE END OR CASE WHEN LKP_PORTPOLS_DLY.PC_NAME_1 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_NAME_1 END <> CASE WHEN exp_HOLD_DATA.PC_NAME_1 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_NAME_1 END OR CASE WHEN LKP_PORTPOLS_DLY.PC_NAME_2 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_NAME_2 END <> CASE WHEN exp_HOLD_DATA.PC_NAME_2 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_NAME_2 END OR CASE WHEN LKP_PORTPOLS_DLY.PC_ADDRESS_1 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_ADDRESS_1 END <> CASE WHEN exp_HOLD_DATA.PC_ADDRESS_1 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_ADDRESS_1 END OR CASE WHEN LKP_PORTPOLS_DLY.PC_ADDRESS_2 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_ADDRESS_2 END <> CASE WHEN exp_HOLD_DATA.PC_ADDRESS_2 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_ADDRESS_2 END OR CASE WHEN LKP_PORTPOLS_DLY.PC_CITYST IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_CITYST END <> CASE WHEN exp_HOLD_DATA.PC_CITYST IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_CITYST END OR CASE WHEN LKP_PORTPOLS_DLY.PC_ZIP IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_ZIP END <> CASE WHEN exp_HOLD_DATA.PC_ZIP IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_ZIP END OR CASE WHEN LKP_PORTPOLS_DLY.PC_TAX_CODE IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_TAX_CODE END <> CASE WHEN exp_HOLD_DATA.PC_TAX_CODE IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_TAX_CODE END OR CASE WHEN LKP_PORTPOLS_DLY.PC_AGENT IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.PC_AGENT END <> CASE WHEN exp_HOLD_DATA.PC_AGENT IS NULL THEN 0 ELSE exp_HOLD_DATA.PC_AGENT END OR CASE WHEN LKP_PORTPOLS_DLY.PC_MEMBER_NUMBER IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_MEMBER_NUMBER END <> CASE WHEN exp_HOLD_DATA.PC_MEMBER_NUMBER IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_MEMBER_NUMBER END OR CASE WHEN LKP_PORTPOLS_DLY.PC_RATE_CODE IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_RATE_CODE END <> CASE WHEN exp_HOLD_DATA.PC_RATE_CODE IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_RATE_CODE END OR CASE WHEN LKP_PORTPOLS_DLY.PC_ENCUMBRANCE IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_ENCUMBRANCE END <> CASE WHEN exp_HOLD_DATA.PC_ENCUMBRANCE IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_ENCUMBRANCE END OR CASE WHEN LKP_PORTPOLS_DLY.PC_PREM_FIN IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_PREM_FIN END <> CASE WHEN exp_HOLD_DATA.PC_PREM_FIN IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_PREM_FIN END OR CASE WHEN LKP_PORTPOLS_DLY.PC_MORT_IND IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_MORT_IND END <> CASE WHEN exp_HOLD_DATA.PC_MORT_IND IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_MORT_IND END OR CASE WHEN LKP_PORTPOLS_DLY.PC_COMPANY IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_COMPANY END <> CASE WHEN exp_HOLD_DATA.PC_COMPANY IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_COMPANY END OR CASE WHEN LKP_PORTPOLS_DLY.PC_INCEPT_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_PORTPOLS_DLY.PC_INCEPT_DATE END <> CASE WHEN exp_HOLD_DATA.PC_INCEPT_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.PC_INCEPT_DATE END OR CASE WHEN LKP_PORTPOLS_DLY.PC_EXP_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_PORTPOLS_DLY.PC_EXP_DATE END <> CASE WHEN exp_HOLD_DATA.PC_EXP_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.PC_EXP_DATE END OR CASE WHEN LKP_PORTPOLS_DLY.PC_EFF_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_PORTPOLS_DLY.PC_EFF_DATE END <> CASE WHEN exp_HOLD_DATA.PC_EFF_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.PC_EFF_DATE END OR CASE WHEN LKP_PORTPOLS_DLY.PC_STATUS IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PC_STATUS END <> CASE WHEN exp_HOLD_DATA.PC_STATUS IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PC_STATUS END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_REWRITE_IND IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_REWRITE_IND END <> CASE WHEN exp_HOLD_DATA.PORT_REWRITE_IND IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_REWRITE_IND END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_REWRITE_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_PORTPOLS_DLY.PORT_REWRITE_DATE END <> CASE WHEN exp_HOLD_DATA.PORT_REWRITE_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.PORT_REWRITE_DATE END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_OUTST_TYPE IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_OUTST_TYPE END <> CASE WHEN exp_HOLD_DATA.PORT_OUTST_TYPE IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_OUTST_TYPE END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_OUTST_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_PORTPOLS_DLY.PORT_OUTST_DATE END <> CASE WHEN exp_HOLD_DATA.PORT_OUTST_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.PORT_OUTST_DATE END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_OUTST_PD_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_PORTPOLS_DLY.PORT_OUTST_PD_DATE END <> CASE WHEN exp_HOLD_DATA.PORT_OUTST_PD_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.PORT_OUTST_PD_DATE END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SUSPENSE_CD IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_SUSPENSE_CD END <> CASE WHEN exp_HOLD_DATA.PORT_SUSPENSE_CD IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_SUSPENSE_CD END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SUSPENSE_CAN IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_SUSPENSE_CAN END <> CASE WHEN exp_HOLD_DATA.PORT_SUSPENSE_CAN IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_SUSPENSE_CAN END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SSN_1 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_SSN_1 END <> CASE WHEN exp_HOLD_DATA.PORT_SSN_1 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_SSN_1 END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SSN_2 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_SSN_2 END <> CASE WHEN exp_HOLD_DATA.PORT_SSN_2 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_SSN_2 END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_UW_REV_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_PORTPOLS_DLY.PORT_UW_REV_DATE END <> CASE WHEN exp_HOLD_DATA.PORT_UW_REV_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.PORT_UW_REV_DATE END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_UW_INITIALS IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_UW_INITIALS END <> CASE WHEN exp_HOLD_DATA.PORT_UW_INITIALS IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_UW_INITIALS END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_MORT_NAME_1 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_MORT_NAME_1 END <> CASE WHEN exp_HOLD_DATA.PORT_MORT_NAME_1 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_MORT_NAME_1 END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_MORT_NAME_2 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_MORT_NAME_2 END <> CASE WHEN exp_HOLD_DATA.PORT_MORT_NAME_2 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_MORT_NAME_2 END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_MORT_ADD_1 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_MORT_ADD_1 END <> CASE WHEN exp_HOLD_DATA.PORT_MORT_ADD_1 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_MORT_ADD_1 END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_MORT_ADD_2 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_MORT_ADD_2 END <> CASE WHEN exp_HOLD_DATA.PORT_MORT_ADD_2 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_MORT_ADD_2 END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_MORT_CTYST IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_MORT_CTYST END <> CASE WHEN exp_HOLD_DATA.PORT_MORT_CTYST IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_MORT_CTYST END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_MORT_ZIP IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_MORT_ZIP END <> CASE WHEN exp_HOLD_DATA.PORT_MORT_ZIP IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_MORT_ZIP END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_STATE IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_STATE END <> CASE WHEN exp_HOLD_DATA.PORT_STATE IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_STATE END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_MORT_TYPE IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.PORT_MORT_TYPE END <> CASE WHEN exp_HOLD_DATA.PORT_MORT_TYPE IS NULL THEN 0 ELSE exp_HOLD_DATA.PORT_MORT_TYPE END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_LOAN_NUM IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_LOAN_NUM END <> CASE WHEN exp_HOLD_DATA.PORT_LOAN_NUM IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_LOAN_NUM END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SLOAN_NUM IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_SLOAN_NUM END <> CASE WHEN exp_HOLD_DATA.PORT_SLOAN_NUM IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_SLOAN_NUM END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SMORT_NAME_1 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_SMORT_NAME_1 END <> CASE WHEN exp_HOLD_DATA.PORT_SMORT_NAME_1 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_SMORT_NAME_1 END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SMORT_NAME_2 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_SMORT_NAME_2 END <> CASE WHEN exp_HOLD_DATA.PORT_SMORT_NAME_2 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_SMORT_NAME_2 END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SMORT_ADD_1 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_SMORT_ADD_1 END <> CASE WHEN exp_HOLD_DATA.PORT_SMORT_ADD_1 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_SMORT_ADD_1 END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SMORT_ADD_2 IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_SMORT_ADD_2 END <> CASE WHEN exp_HOLD_DATA.PORT_SMORT_ADD_2 IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_SMORT_ADD_2 END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SMORT_CTYST IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_SMORT_CTYST END <> CASE WHEN exp_HOLD_DATA.PORT_SMORT_CTYST IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_SMORT_CTYST END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SMORT_ZIP IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_SMORT_ZIP END <> CASE WHEN exp_HOLD_DATA.PORT_SMORT_ZIP IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_SMORT_ZIP END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SMORT_TYPE IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.PORT_SMORT_TYPE END <> CASE WHEN exp_HOLD_DATA.PORT_SMORT_TYPE IS NULL THEN 0 ELSE exp_HOLD_DATA.PORT_SMORT_TYPE END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_TRANSFER_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE LKP_PORTPOLS_DLY.PORT_TRANSFER_DATE END <> CASE WHEN exp_HOLD_DATA.PORT_TRANSFER_DATE IS NULL THEN TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) ELSE exp_HOLD_DATA.PORT_TRANSFER_DATE END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_MB_TYPE IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_MB_TYPE END <> CASE WHEN exp_HOLD_DATA.PORT_MB_TYPE IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_MB_TYPE END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_MB_ACCT_NUM IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_MB_ACCT_NUM END <> CASE WHEN exp_HOLD_DATA.PORT_MB_ACCT_NUM IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_MB_ACCT_NUM END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_SC_LIAB_PRD_I IS NULL THEN ''~'' ELSE LKP_PORTPOLS_DLY.PORT_SC_LIAB_PRD_I END <> CASE WHEN exp_HOLD_DATA.PORT_SC_LIAB_PRD_I IS NULL THEN ''~'' ELSE exp_HOLD_DATA.PORT_SC_LIAB_PRD_I END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_TOT_PREM IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.PORT_TOT_PREM END <> CASE WHEN exp_HOLD_DATA.PORT_TOT_PREM IS NULL THEN 0 ELSE exp_HOLD_DATA.PORT_TOT_PREM END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_OUTST_AMT IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.PORT_OUTST_AMT END <> CASE WHEN exp_HOLD_DATA.PORT_OUTST_AMT IS NULL THEN 0 ELSE exp_HOLD_DATA.PORT_OUTST_AMT END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_HALF_TERM_BP IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.PORT_HALF_TERM_BP END <> CASE WHEN exp_HOLD_DATA.PORT_HALF_TERM_BP IS NULL THEN 0 ELSE exp_HOLD_DATA.PORT_HALF_TERM_BP END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_FULL_TERM_BP IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.PORT_FULL_TERM_BP END <> CASE WHEN exp_HOLD_DATA.PORT_FULL_TERM_BP IS NULL THEN 0 ELSE exp_HOLD_DATA.PORT_FULL_TERM_BP END OR CASE WHEN LKP_PORTPOLS_DLY.PORT_FIRE_COVERAGE IS NULL THEN 0 ELSE LKP_PORTPOLS_DLY.PORT_FIRE_COVERAGE END <> CASE WHEN exp_HOLD_DATA.PORT_FIRE_COVERAGE IS NULL THEN 0 ELSE exp_HOLD_DATA.PORT_FIRE_COVERAGE END THEN ''UPD'' ELSE ''REJ'' END END as out_FLG,
LTRIM ( RTRIM ( :PMMappingName ) ) as out_PRGM_NM,
:PROJ_ID as out_PROJ_ID,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
:PROJ_ID as IN_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as IN_BATCH_ACTIVE_IND,
''m_STG_FIN_CLM'' IN_PRGM_NM,
null IN_TABLE_NM,
exp_HOLD_DATA.source_record_id
FROM
exp_HOLD_DATA
INNER JOIN LKP_PORTPOLS_DLY ON exp_HOLD_DATA.source_record_id = LKP_PORTPOLS_DLY.source_record_id
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;
call mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''exp_DERIVE_FLAG'');


-- Component exp_PORTPOLS_DLY, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_PORTPOLS_DLY AS
(
SELECT
exp_DERIVE_FLAG.SC_POLICY_NUM_lkp as SC_POLICY_NUM_lkp,
exp_DERIVE_FLAG.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp,
exp_DERIVE_FLAG.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_DERIVE_FLAG.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_DERIVE_FLAG.SC_POLICY_NUM as SC_POLICY_NUM,
exp_DERIVE_FLAG.SC_FLT_ITEM as SC_FLT_ITEM,
exp_DERIVE_FLAG.SC_FILE_TYPE as SC_FILE_TYPE,
exp_DERIVE_FLAG.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_DERIVE_FLAG.SC_TRANS_DATE as SC_TRANS_DATE,
exp_DERIVE_FLAG.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_DERIVE_FLAG.PC_ALPHA_CODE as PC_ALPHA_CODE,
exp_DERIVE_FLAG.PC_NAME_1 as PC_NAME_1,
exp_DERIVE_FLAG.PC_NAME_2 as PC_NAME_2,
exp_DERIVE_FLAG.PC_ADDRESS_1 as PC_ADDRESS_1,
exp_DERIVE_FLAG.PC_ADDRESS_2 as PC_ADDRESS_2,
exp_DERIVE_FLAG.PC_CITYST as PC_CITYST,
exp_DERIVE_FLAG.PC_ZIP as PC_ZIP,
exp_DERIVE_FLAG.PC_TAX_CODE as PC_TAX_CODE,
exp_DERIVE_FLAG.PC_AGENT as PC_AGENT,
exp_DERIVE_FLAG.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
exp_DERIVE_FLAG.PC_RATE_CODE as PC_RATE_CODE,
exp_DERIVE_FLAG.PC_ENCUMBRANCE as PC_ENCUMBRANCE,
exp_DERIVE_FLAG.PC_PREM_FIN as PC_PREM_FIN,
exp_DERIVE_FLAG.PC_MORT_IND as PC_MORT_IND,
exp_DERIVE_FLAG.PC_COMPANY as PC_COMPANY,
exp_DERIVE_FLAG.PC_INCEPT_DATE as PC_INCEPT_DATE,
exp_DERIVE_FLAG.PC_EXP_DATE as PC_EXP_DATE,
exp_DERIVE_FLAG.PC_EFF_DATE as PC_EFF_DATE,
exp_DERIVE_FLAG.PC_STATUS as PC_STATUS,
exp_DERIVE_FLAG.PORT_TOT_PREM as PORT_TOT_PREM,
exp_DERIVE_FLAG.PORT_REWRITE_IND as PORT_REWRITE_IND,
exp_DERIVE_FLAG.PORT_REWRITE_DATE as PORT_REWRITE_DATE,
exp_DERIVE_FLAG.PORT_OUTST_AMT as PORT_OUTST_AMT,
exp_DERIVE_FLAG.PORT_OUTST_TYPE as PORT_OUTST_TYPE,
exp_DERIVE_FLAG.PORT_OUTST_DATE as PORT_OUTST_DATE,
exp_DERIVE_FLAG.PORT_OUTST_PD_DATE as PORT_OUTST_PD_DATE,
exp_DERIVE_FLAG.PORT_SUSPENSE_CD as PORT_SUSPENSE_CD,
exp_DERIVE_FLAG.PORT_SUSPENSE_CAN as PORT_SUSPENSE_CAN,
exp_DERIVE_FLAG.PORT_SSN_1 as PORT_SSN_1,
exp_DERIVE_FLAG.PORT_SSN_2 as PORT_SSN_2,
exp_DERIVE_FLAG.PORT_UW_REV_DATE as PORT_UW_REV_DATE,
exp_DERIVE_FLAG.PORT_UW_INITIALS as PORT_UW_INITIALS,
exp_DERIVE_FLAG.PORT_MORT_NAME_1 as PORT_MORT_NAME_1,
exp_DERIVE_FLAG.PORT_MORT_NAME_2 as PORT_MORT_NAME_2,
exp_DERIVE_FLAG.PORT_MORT_ADD_1 as PORT_MORT_ADD_1,
exp_DERIVE_FLAG.PORT_MORT_ADD_2 as PORT_MORT_ADD_2,
exp_DERIVE_FLAG.PORT_MORT_CTYST as PORT_MORT_CTYST,
exp_DERIVE_FLAG.PORT_MORT_ZIP as PORT_MORT_ZIP,
exp_DERIVE_FLAG.PORT_STATE as PORT_STATE,
exp_DERIVE_FLAG.PORT_MORT_TYPE as PORT_MORT_TYPE,
exp_DERIVE_FLAG.PORT_LOAN_NUM as PORT_LOAN_NUM,
exp_DERIVE_FLAG.PORT_SLOAN_NUM as PORT_SLOAN_NUM,
exp_DERIVE_FLAG.PORT_SMORT_NAME_1 as PORT_SMORT_NAME_1,
exp_DERIVE_FLAG.PORT_SMORT_NAME_2 as PORT_SMORT_NAME_2,
exp_DERIVE_FLAG.PORT_SMORT_ADD_1 as PORT_SMORT_ADD_1,
exp_DERIVE_FLAG.PORT_SMORT_ADD_2 as PORT_SMORT_ADD_2,
exp_DERIVE_FLAG.PORT_SMORT_CTYST as PORT_SMORT_CTYST,
exp_DERIVE_FLAG.PORT_SMORT_ZIP as PORT_SMORT_ZIP,
exp_DERIVE_FLAG.PORT_SMORT_TYPE as PORT_SMORT_TYPE,
exp_DERIVE_FLAG.PORT_HALF_TERM_BP as PORT_HALF_TERM_BP,
exp_DERIVE_FLAG.PORT_FULL_TERM_BP as PORT_FULL_TERM_BP,
exp_DERIVE_FLAG.PORT_TRANSFER_DATE as PORT_TRANSFER_DATE,
exp_DERIVE_FLAG.PORT_MB_TYPE as PORT_MB_TYPE,
exp_DERIVE_FLAG.PORT_MB_ACCT_NUM as PORT_MB_ACCT_NUM,
exp_DERIVE_FLAG.PORT_SC_LIAB_PRD_I as PORT_SC_LIAB_PRD_I,
exp_DERIVE_FLAG.PORT_FIRE_COVERAGE as PORT_FIRE_COVERAGE,
exp_DERIVE_FLAG.LOAD_DT as LOAD_DT,
exp_DERIVE_FLAG.FEED_IND as FEED_IND,
exp_DERIVE_FLAG.out_FLG as FLG,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_ID as ECTL_SRC_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ORIG_INS_TS as ORIG_INS_TS,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_START_DATE as ECTL_BATCH_START_DATE,
exp_DERIVE_FLAG.source_record_id
FROM
exp_DERIVE_FLAG
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_DERIVE_FLAG.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id
);


-- Component rtr_INS_UPD_INSERT, Type ROUTER Output Group INSERT
create or replace temp table RTR_INS_UPD_INSERT as
SELECT
exp_PORTPOLS_DLY.SC_POLICY_NUM_lkp as SC_POLICY_NUM_lkp,
exp_PORTPOLS_DLY.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp,
exp_PORTPOLS_DLY.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_PORTPOLS_DLY.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_PORTPOLS_DLY.SC_POLICY_NUM as SC_POLICY_NUM,
exp_PORTPOLS_DLY.SC_FLT_ITEM as SC_FLT_ITEM,
exp_PORTPOLS_DLY.SC_FILE_TYPE as SC_FILE_TYPE,
exp_PORTPOLS_DLY.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_PORTPOLS_DLY.SC_TRANS_DATE as SC_TRANS_DATE,
exp_PORTPOLS_DLY.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_PORTPOLS_DLY.PC_ALPHA_CODE as PC_ALPHA_CODE,
exp_PORTPOLS_DLY.PC_NAME_1 as PC_NAME_1,
exp_PORTPOLS_DLY.PC_NAME_2 as PC_NAME_2,
exp_PORTPOLS_DLY.PC_ADDRESS_1 as PC_ADDRESS_1,
exp_PORTPOLS_DLY.PC_ADDRESS_2 as PC_ADDRESS_2,
exp_PORTPOLS_DLY.PC_CITYST as PC_CITYST,
exp_PORTPOLS_DLY.PC_ZIP as PC_ZIP,
exp_PORTPOLS_DLY.PC_TAX_CODE as PC_TAX_CODE,
exp_PORTPOLS_DLY.PC_AGENT as PC_AGENT,
exp_PORTPOLS_DLY.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
exp_PORTPOLS_DLY.PC_RATE_CODE as PC_RATE_CODE,
exp_PORTPOLS_DLY.PC_ENCUMBRANCE as PC_ENCUMBRANCE,
exp_PORTPOLS_DLY.PC_PREM_FIN as PC_PREM_FIN,
exp_PORTPOLS_DLY.PC_MORT_IND as PC_MORT_IND,
exp_PORTPOLS_DLY.PC_COMPANY as PC_COMPANY,
exp_PORTPOLS_DLY.PC_INCEPT_DATE as PC_INCEPT_DATE,
exp_PORTPOLS_DLY.PC_EXP_DATE as PC_EXP_DATE,
exp_PORTPOLS_DLY.PC_EFF_DATE as PC_EFF_DATE,
exp_PORTPOLS_DLY.PC_STATUS as PC_STATUS,
exp_PORTPOLS_DLY.PORT_TOT_PREM as PORT_TOT_PREM,
exp_PORTPOLS_DLY.PORT_REWRITE_IND as PORT_REWRITE_IND,
exp_PORTPOLS_DLY.PORT_REWRITE_DATE as PORT_REWRITE_DATE,
exp_PORTPOLS_DLY.PORT_OUTST_AMT as PORT_OUTST_AMT,
exp_PORTPOLS_DLY.PORT_OUTST_TYPE as PORT_OUTST_TYPE,
exp_PORTPOLS_DLY.PORT_OUTST_DATE as PORT_OUTST_DATE,
exp_PORTPOLS_DLY.PORT_OUTST_PD_DATE as PORT_OUTST_PD_DATE,
exp_PORTPOLS_DLY.PORT_SUSPENSE_CD as PORT_SUSPENSE_CD,
exp_PORTPOLS_DLY.PORT_SUSPENSE_CAN as PORT_SUSPENSE_CAN,
exp_PORTPOLS_DLY.PORT_SSN_1 as PORT_SSN_1,
exp_PORTPOLS_DLY.PORT_SSN_2 as PORT_SSN_2,
exp_PORTPOLS_DLY.PORT_UW_REV_DATE as PORT_UW_REV_DATE,
exp_PORTPOLS_DLY.PORT_UW_INITIALS as PORT_UW_INITIALS,
exp_PORTPOLS_DLY.PORT_MORT_NAME_1 as PORT_MORT_NAME_1,
exp_PORTPOLS_DLY.PORT_MORT_NAME_2 as PORT_MORT_NAME_2,
exp_PORTPOLS_DLY.PORT_MORT_ADD_1 as PORT_MORT_ADD_1,
exp_PORTPOLS_DLY.PORT_MORT_ADD_2 as PORT_MORT_ADD_2,
exp_PORTPOLS_DLY.PORT_MORT_CTYST as PORT_MORT_CTYST,
exp_PORTPOLS_DLY.PORT_MORT_ZIP as PORT_MORT_ZIP,
exp_PORTPOLS_DLY.PORT_STATE as PORT_STATE,
exp_PORTPOLS_DLY.PORT_MORT_TYPE as PORT_MORT_TYPE,
exp_PORTPOLS_DLY.PORT_LOAN_NUM as PORT_LOAN_NUM,
exp_PORTPOLS_DLY.PORT_SLOAN_NUM as PORT_SLOAN_NUM,
exp_PORTPOLS_DLY.PORT_SMORT_NAME_1 as PORT_SMORT_NAME_1,
exp_PORTPOLS_DLY.PORT_SMORT_NAME_2 as PORT_SMORT_NAME_2,
exp_PORTPOLS_DLY.PORT_SMORT_ADD_1 as PORT_SMORT_ADD_1,
exp_PORTPOLS_DLY.PORT_SMORT_ADD_2 as PORT_SMORT_ADD_2,
exp_PORTPOLS_DLY.PORT_SMORT_CTYST as PORT_SMORT_CTYST,
exp_PORTPOLS_DLY.PORT_SMORT_ZIP as PORT_SMORT_ZIP,
exp_PORTPOLS_DLY.PORT_SMORT_TYPE as PORT_SMORT_TYPE,
exp_PORTPOLS_DLY.PORT_HALF_TERM_BP as PORT_HALF_TERM_BP,
exp_PORTPOLS_DLY.PORT_FULL_TERM_BP as PORT_FULL_TERM_BP,
exp_PORTPOLS_DLY.PORT_TRANSFER_DATE as PORT_TRANSFER_DATE,
exp_PORTPOLS_DLY.PORT_MB_TYPE as PORT_MB_TYPE,
exp_PORTPOLS_DLY.PORT_MB_ACCT_NUM as PORT_MB_ACCT_NUM,
exp_PORTPOLS_DLY.PORT_SC_LIAB_PRD_I as PORT_SC_LIAB_PRD_I,
exp_PORTPOLS_DLY.PORT_FIRE_COVERAGE as PORT_FIRE_COVERAGE,
exp_PORTPOLS_DLY.LOAD_DT as LOAD_DT,
exp_PORTPOLS_DLY.FEED_IND as FEED_IND,
exp_PORTPOLS_DLY.FLG as FLG,
exp_PORTPOLS_DLY.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_PORTPOLS_DLY.ECTL_SRC_ID as ECTL_SRC_ID,
exp_PORTPOLS_DLY.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_PORTPOLS_DLY.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_PORTPOLS_DLY.ORIG_INS_TS as ORIG_INS_TS,
exp_PORTPOLS_DLY.ECTL_BATCH_START_DATE as ECTL_BATCH_START_DATE,
exp_PORTPOLS_DLY.source_record_id
FROM
exp_PORTPOLS_DLY
WHERE ( exp_PORTPOLS_DLY.FLG = ''NEW'' ) OR ( exp_PORTPOLS_DLY.FLG = ''UPD'' );


-- Component rtr_INS_UPD_UPDATE, Type ROUTER Output Group UPDATE
create or replace temp table RTR_INS_UPD_update as
SELECT
exp_PORTPOLS_DLY.SC_POLICY_NUM_lkp as SC_POLICY_NUM_lkp,
exp_PORTPOLS_DLY.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp,
exp_PORTPOLS_DLY.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY,
exp_PORTPOLS_DLY.SC_SERVICE_CENTER as SC_SERVICE_CENTER,
exp_PORTPOLS_DLY.SC_POLICY_NUM as SC_POLICY_NUM,
exp_PORTPOLS_DLY.SC_FLT_ITEM as SC_FLT_ITEM,
exp_PORTPOLS_DLY.SC_FILE_TYPE as SC_FILE_TYPE,
exp_PORTPOLS_DLY.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE,
exp_PORTPOLS_DLY.SC_TRANS_DATE as SC_TRANS_DATE,
exp_PORTPOLS_DLY.SC_TRANS_TYPE as SC_TRANS_TYPE,
exp_PORTPOLS_DLY.PC_ALPHA_CODE as PC_ALPHA_CODE,
exp_PORTPOLS_DLY.PC_NAME_1 as PC_NAME_1,
exp_PORTPOLS_DLY.PC_NAME_2 as PC_NAME_2,
exp_PORTPOLS_DLY.PC_ADDRESS_1 as PC_ADDRESS_1,
exp_PORTPOLS_DLY.PC_ADDRESS_2 as PC_ADDRESS_2,
exp_PORTPOLS_DLY.PC_CITYST as PC_CITYST,
exp_PORTPOLS_DLY.PC_ZIP as PC_ZIP,
exp_PORTPOLS_DLY.PC_TAX_CODE as PC_TAX_CODE,
exp_PORTPOLS_DLY.PC_AGENT as PC_AGENT,
exp_PORTPOLS_DLY.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER,
exp_PORTPOLS_DLY.PC_RATE_CODE as PC_RATE_CODE,
exp_PORTPOLS_DLY.PC_ENCUMBRANCE as PC_ENCUMBRANCE,
exp_PORTPOLS_DLY.PC_PREM_FIN as PC_PREM_FIN,
exp_PORTPOLS_DLY.PC_MORT_IND as PC_MORT_IND,
exp_PORTPOLS_DLY.PC_COMPANY as PC_COMPANY,
exp_PORTPOLS_DLY.PC_INCEPT_DATE as PC_INCEPT_DATE,
exp_PORTPOLS_DLY.PC_EXP_DATE as PC_EXP_DATE,
exp_PORTPOLS_DLY.PC_EFF_DATE as PC_EFF_DATE,
exp_PORTPOLS_DLY.PC_STATUS as PC_STATUS,
exp_PORTPOLS_DLY.PORT_TOT_PREM as PORT_TOT_PREM,
exp_PORTPOLS_DLY.PORT_REWRITE_IND as PORT_REWRITE_IND,
exp_PORTPOLS_DLY.PORT_REWRITE_DATE as PORT_REWRITE_DATE,
exp_PORTPOLS_DLY.PORT_OUTST_AMT as PORT_OUTST_AMT,
exp_PORTPOLS_DLY.PORT_OUTST_TYPE as PORT_OUTST_TYPE,
exp_PORTPOLS_DLY.PORT_OUTST_DATE as PORT_OUTST_DATE,
exp_PORTPOLS_DLY.PORT_OUTST_PD_DATE as PORT_OUTST_PD_DATE,
exp_PORTPOLS_DLY.PORT_SUSPENSE_CD as PORT_SUSPENSE_CD,
exp_PORTPOLS_DLY.PORT_SUSPENSE_CAN as PORT_SUSPENSE_CAN,
exp_PORTPOLS_DLY.PORT_SSN_1 as PORT_SSN_1,
exp_PORTPOLS_DLY.PORT_SSN_2 as PORT_SSN_2,
exp_PORTPOLS_DLY.PORT_UW_REV_DATE as PORT_UW_REV_DATE,
exp_PORTPOLS_DLY.PORT_UW_INITIALS as PORT_UW_INITIALS,
exp_PORTPOLS_DLY.PORT_MORT_NAME_1 as PORT_MORT_NAME_1,
exp_PORTPOLS_DLY.PORT_MORT_NAME_2 as PORT_MORT_NAME_2,
exp_PORTPOLS_DLY.PORT_MORT_ADD_1 as PORT_MORT_ADD_1,
exp_PORTPOLS_DLY.PORT_MORT_ADD_2 as PORT_MORT_ADD_2,
exp_PORTPOLS_DLY.PORT_MORT_CTYST as PORT_MORT_CTYST,
exp_PORTPOLS_DLY.PORT_MORT_ZIP as PORT_MORT_ZIP,
exp_PORTPOLS_DLY.PORT_STATE as PORT_STATE,
exp_PORTPOLS_DLY.PORT_MORT_TYPE as PORT_MORT_TYPE,
exp_PORTPOLS_DLY.PORT_LOAN_NUM as PORT_LOAN_NUM,
exp_PORTPOLS_DLY.PORT_SLOAN_NUM as PORT_SLOAN_NUM,
exp_PORTPOLS_DLY.PORT_SMORT_NAME_1 as PORT_SMORT_NAME_1,
exp_PORTPOLS_DLY.PORT_SMORT_NAME_2 as PORT_SMORT_NAME_2,
exp_PORTPOLS_DLY.PORT_SMORT_ADD_1 as PORT_SMORT_ADD_1,
exp_PORTPOLS_DLY.PORT_SMORT_ADD_2 as PORT_SMORT_ADD_2,
exp_PORTPOLS_DLY.PORT_SMORT_CTYST as PORT_SMORT_CTYST,
exp_PORTPOLS_DLY.PORT_SMORT_ZIP as PORT_SMORT_ZIP,
exp_PORTPOLS_DLY.PORT_SMORT_TYPE as PORT_SMORT_TYPE,
exp_PORTPOLS_DLY.PORT_HALF_TERM_BP as PORT_HALF_TERM_BP,
exp_PORTPOLS_DLY.PORT_FULL_TERM_BP as PORT_FULL_TERM_BP,
exp_PORTPOLS_DLY.PORT_TRANSFER_DATE as PORT_TRANSFER_DATE,
exp_PORTPOLS_DLY.PORT_MB_TYPE as PORT_MB_TYPE,
exp_PORTPOLS_DLY.PORT_MB_ACCT_NUM as PORT_MB_ACCT_NUM,
exp_PORTPOLS_DLY.PORT_SC_LIAB_PRD_I as PORT_SC_LIAB_PRD_I,
exp_PORTPOLS_DLY.PORT_FIRE_COVERAGE as PORT_FIRE_COVERAGE,
exp_PORTPOLS_DLY.LOAD_DT as LOAD_DT,
exp_PORTPOLS_DLY.FEED_IND as FEED_IND,
exp_PORTPOLS_DLY.FLG as FLG,
exp_PORTPOLS_DLY.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_PORTPOLS_DLY.ECTL_SRC_ID as ECTL_SRC_ID,
exp_PORTPOLS_DLY.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID,
exp_PORTPOLS_DLY.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_PORTPOLS_DLY.ORIG_INS_TS as ORIG_INS_TS,
exp_PORTPOLS_DLY.ECTL_BATCH_START_DATE as ECTL_BATCH_START_DATE,
exp_PORTPOLS_DLY.source_record_id
FROM
exp_PORTPOLS_DLY
WHERE exp_PORTPOLS_DLY.FLG = ''UPD'';


-- Component exp_GET_EXP_DATE, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_GET_EXP_DATE AS
(
SELECT
rtr_INS_UPD_UPDATE.SC_POLICY_NUM_lkp as SC_POLICY_NUM_lkp3,
rtr_INS_UPD_UPDATE.CHG_EFF_DT_lkp as CHG_EFF_DT_lkp3,
rtr_INS_UPD_UPDATE.LOAD_DT as LOAD_DT3,
rtr_INS_UPD_UPDATE.FLG as FLG3,
rtr_INS_UPD_UPDATE.ECTL_BATCH_ID as ECTL_BATCH_ID3,
rtr_INS_UPD_UPDATE.ORIG_INS_TS as ORIG_INS_TS3,
 rtr_INS_UPD_UPDATE.LOAD_DT  - 1  as var_CHG_EXP_DT_NEW,
CASE WHEN rtr_INS_UPD_UPDATE.CHG_EFF_DT_lkp >= rtr_INS_UPD_UPDATE.LOAD_DT THEN rtr_INS_UPD_UPDATE.CHG_EFF_DT_lkp ELSE var_CHG_EXP_DT_NEW END as out_CHG_EXP_DT_NEW,
CURRENT_TIMESTAMP as out_ECTL_END_DT,
rtr_INS_UPD_UPDATE.source_record_id
FROM
rtr_INS_UPD_UPDATE
);


-- Component upd_PORTPOLS_DLY, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_PORTPOLS_DLY AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
exp_GET_EXP_DATE.SC_POLICY_NUM_lkp3 as SC_POLICY_NUM_lkp3,
exp_GET_EXP_DATE.CHG_EFF_DT_lkp3 as CHG_EFF_DT_lkp3,
exp_GET_EXP_DATE.LOAD_DT3 as LOAD_DT3,
exp_GET_EXP_DATE.FLG3 as FLG3,
exp_GET_EXP_DATE.ECTL_BATCH_ID3 as ECTL_BATCH_ID3,
exp_GET_EXP_DATE.ORIG_INS_TS3 as ORIG_INS_TS3,
exp_GET_EXP_DATE.out_CHG_EXP_DT_NEW as out_CHG_EXP_DT_NEW,
exp_GET_EXP_DATE.out_ECTL_END_DT as out_ECTL_END_DT,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_GET_EXP_DATE
);


-- Component PORTPOLS_DLY_UPD_INS, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_core_MEMBXREF_PROD.PORTPOLS_DLY
USING upd_PORTPOLS_DLY
ON (SC_POLICY_NUM = upd_PORTPOLS_DLY.SC_POLICY_NUM_lkp3 AND CHG_EFF_DT = upd_PORTPOLS_DLY.CHG_EFF_DT_lkp3)
WHEN MATCHED THEN UPDATE SET
ECTL_BATCH_ID = upd_PORTPOLS_DLY.ECTL_BATCH_ID3, ECTL_MODIFY_TS = upd_PORTPOLS_DLY.ORIG_INS_TS3, --ECTL_TX_CD = upd_PORTPOLS_DLY.ECTL_TX_CD, 
ECTL_END_DATE = upd_PORTPOLS_DLY.out_ECTL_END_DT, CHG_EXP_DT = upd_PORTPOLS_DLY.out_CHG_EXP_DT_NEW;



-- Component exp_GET_EFF_DATE, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_GET_EFF_DATE AS
(
SELECT
rtr_INS_UPD_INSERT.SC_DWNLD_PRIORITY as SC_DWNLD_PRIORITY1,
rtr_INS_UPD_INSERT.SC_SERVICE_CENTER as SC_SERVICE_CENTER1,
rtr_INS_UPD_INSERT.SC_POLICY_NUM as SC_POLICY_NUM1,
rtr_INS_UPD_INSERT.SC_FLT_ITEM as SC_FLT_ITEM1,
rtr_INS_UPD_INSERT.SC_FILE_TYPE as SC_FILE_TYPE1,
rtr_INS_UPD_INSERT.SC_REC_TRANS_CODE as SC_REC_TRANS_CODE1,
rtr_INS_UPD_INSERT.SC_TRANS_DATE as SC_TRANS_DATE1,
rtr_INS_UPD_INSERT.SC_TRANS_TYPE as SC_TRANS_TYPE1,
rtr_INS_UPD_INSERT.PC_ALPHA_CODE as PC_ALPHA_CODE1,
rtr_INS_UPD_INSERT.PC_NAME_1 as PC_NAME_11,
rtr_INS_UPD_INSERT.PC_NAME_2 as PC_NAME_21,
rtr_INS_UPD_INSERT.PC_ADDRESS_1 as PC_ADDRESS_11,
rtr_INS_UPD_INSERT.PC_ADDRESS_2 as PC_ADDRESS_21,
rtr_INS_UPD_INSERT.PC_CITYST as PC_CITYST1,
rtr_INS_UPD_INSERT.PC_ZIP as PC_ZIP1,
rtr_INS_UPD_INSERT.PC_TAX_CODE as PC_TAX_CODE1,
rtr_INS_UPD_INSERT.PC_AGENT as PC_AGENT1,
rtr_INS_UPD_INSERT.PC_MEMBER_NUMBER as PC_MEMBER_NUMBER1,
rtr_INS_UPD_INSERT.PC_RATE_CODE as PC_RATE_CODE1,
rtr_INS_UPD_INSERT.PC_ENCUMBRANCE as PC_ENCUMBRANCE1,
rtr_INS_UPD_INSERT.PC_PREM_FIN as PC_PREM_FIN1,
rtr_INS_UPD_INSERT.PC_MORT_IND as PC_MORT_IND1,
rtr_INS_UPD_INSERT.PC_COMPANY as PC_COMPANY1,
rtr_INS_UPD_INSERT.PC_INCEPT_DATE as PC_INCEPT_DATE1,
rtr_INS_UPD_INSERT.PC_EXP_DATE as PC_EXP_DATE1,
rtr_INS_UPD_INSERT.PC_EFF_DATE as PC_EFF_DATE1,
rtr_INS_UPD_INSERT.PC_STATUS as PC_STATUS1,
rtr_INS_UPD_INSERT.PORT_TOT_PREM as PORT_TOT_PREM1,
rtr_INS_UPD_INSERT.PORT_REWRITE_IND as PORT_REWRITE_IND1,
rtr_INS_UPD_INSERT.PORT_REWRITE_DATE as PORT_REWRITE_DATE1,
rtr_INS_UPD_INSERT.PORT_OUTST_AMT as PORT_OUTST_AMT1,
rtr_INS_UPD_INSERT.PORT_OUTST_TYPE as PORT_OUTST_TYPE1,
rtr_INS_UPD_INSERT.PORT_OUTST_DATE as PORT_OUTST_DATE1,
rtr_INS_UPD_INSERT.PORT_OUTST_PD_DATE as PORT_OUTST_PD_DATE1,
rtr_INS_UPD_INSERT.PORT_SUSPENSE_CD as PORT_SUSPENSE_CD1,
rtr_INS_UPD_INSERT.PORT_SUSPENSE_CAN as PORT_SUSPENSE_CAN1,
rtr_INS_UPD_INSERT.PORT_SSN_1 as PORT_SSN_11,
rtr_INS_UPD_INSERT.PORT_SSN_2 as PORT_SSN_21,
rtr_INS_UPD_INSERT.PORT_UW_REV_DATE as PORT_UW_REV_DATE1,
rtr_INS_UPD_INSERT.PORT_UW_INITIALS as PORT_UW_INITIALS1,
rtr_INS_UPD_INSERT.PORT_MORT_NAME_1 as PORT_MORT_NAME_11,
rtr_INS_UPD_INSERT.PORT_MORT_NAME_2 as PORT_MORT_NAME_21,
rtr_INS_UPD_INSERT.PORT_MORT_ADD_1 as PORT_MORT_ADD_11,
rtr_INS_UPD_INSERT.PORT_MORT_ADD_2 as PORT_MORT_ADD_21,
rtr_INS_UPD_INSERT.PORT_MORT_CTYST as PORT_MORT_CTYST1,
rtr_INS_UPD_INSERT.PORT_MORT_ZIP as PORT_MORT_ZIP1,
rtr_INS_UPD_INSERT.PORT_STATE as PORT_STATE1,
rtr_INS_UPD_INSERT.PORT_MORT_TYPE as PORT_MORT_TYPE1,
rtr_INS_UPD_INSERT.PORT_LOAN_NUM as PORT_LOAN_NUM1,
rtr_INS_UPD_INSERT.PORT_SLOAN_NUM as PORT_SLOAN_NUM1,
rtr_INS_UPD_INSERT.PORT_SMORT_NAME_1 as PORT_SMORT_NAME_11,
rtr_INS_UPD_INSERT.PORT_SMORT_NAME_2 as PORT_SMORT_NAME_21,
rtr_INS_UPD_INSERT.PORT_SMORT_ADD_1 as PORT_SMORT_ADD_11,
rtr_INS_UPD_INSERT.PORT_SMORT_ADD_2 as PORT_SMORT_ADD_21,
rtr_INS_UPD_INSERT.PORT_SMORT_CTYST as PORT_SMORT_CTYST1,
rtr_INS_UPD_INSERT.PORT_SMORT_ZIP as PORT_SMORT_ZIP1,
rtr_INS_UPD_INSERT.PORT_SMORT_TYPE as PORT_SMORT_TYPE1,
rtr_INS_UPD_INSERT.PORT_HALF_TERM_BP as PORT_HALF_TERM_BP1,
rtr_INS_UPD_INSERT.PORT_FULL_TERM_BP as PORT_FULL_TERM_BP1,
rtr_INS_UPD_INSERT.PORT_TRANSFER_DATE as PORT_TRANSFER_DATE1,
rtr_INS_UPD_INSERT.PORT_MB_TYPE as PORT_MB_TYPE1,
rtr_INS_UPD_INSERT.PORT_MB_ACCT_NUM as PORT_MB_ACCT_NUM1,
rtr_INS_UPD_INSERT.PORT_SC_LIAB_PRD_I as PORT_SC_LIAB_PRD_I1,
rtr_INS_UPD_INSERT.PORT_FIRE_COVERAGE as PORT_FIRE_COVERAGE1,
rtr_INS_UPD_INSERT.FEED_IND as FEED_IND1,
rtr_INS_UPD_INSERT.ECTL_PRGM_ID as ECTL_PRGM_ID1,
rtr_INS_UPD_INSERT.ECTL_SRC_ID as ECTL_SRC_ID1,
rtr_INS_UPD_INSERT.ECTL_SRC_INST_ID as ECTL_SRC_INST_ID1,
rtr_INS_UPD_INSERT.ECTL_BATCH_ID as ECTL_BATCH_ID1,
rtr_INS_UPD_INSERT.ORIG_INS_TS as ORIG_INS_TS1,
rtr_INS_UPD_INSERT.ECTL_BATCH_START_DATE as ECTL_BATCH_START_DATE1,
''NEW'' as out_ECTL_TX_CD,
CASE WHEN rtr_INS_UPD_INSERT.CHG_EFF_DT_lkp >= rtr_INS_UPD_INSERT.LOAD_DT THEN  rtr_INS_UPD_INSERT.CHG_EFF_DT_lkp + 1  ELSE rtr_INS_UPD_INSERT.LOAD_DT END as out_CHG_EFF_DT,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as out_CHG_EXP_DT_NEW,
TO_DATE ( ''9999-12-31'' , ''YYYY-MM-DD'' ) as out_ECTL_END_DT,
rtr_INS_UPD_INSERT.source_record_id
FROM
rtr_INS_UPD_INSERT
);


-- Component PORTPOLS_DLY_INS, Type TARGET 
INSERT INTO DB_T_CORE_MEMBXREF_PROD.PORTPOLS_DLY
(
SC_DWNLD_PRIORITY,
SC_SERVICE_CENTER,
SC_POLICY_NUM,
CHG_EFF_DT,
CHG_EXP_DT,
SC_FLT_ITEM,
SC_FILE_TYPE,
SC_REC_TRANS_CODE,
SC_TRANS_DATE,
SC_TRANS_TYPE,
PC_ALPHA_CODE,
PC_NAME_1,
PC_NAME_2,
PC_ADDRESS_1,
PC_ADDRESS_2,
PC_CITYST,
PC_ZIP,
PC_TAX_CODE,
PC_AGENT,
PC_MEMBER_NUMBER,
PC_RATE_CODE,
PC_ENCUMBRANCE,
PC_PREM_FIN,
PC_MORT_IND,
PC_COMPANY,
PC_INCEPT_DATE,
PC_EXP_DATE,
PC_EFF_DATE,
PC_STATUS,
PORT_TOT_PREM,
PORT_REWRITE_IND,
PORT_REWRITE_DATE,
PORT_OUTST_AMT,
PORT_OUTST_TYPE,
PORT_OUTST_DATE,
PORT_OUTST_PD_DATE,
PORT_SUSPENSE_CD,
PORT_SUSPENSE_CAN,
PORT_SSN_1,
PORT_SSN_2,
PORT_UW_REV_DATE,
PORT_UW_INITIALS,
PORT_MORT_NAME_1,
PORT_MORT_NAME_2,
PORT_MORT_ADD_1,
PORT_MORT_ADD_2,
PORT_MORT_CTYST,
PORT_MORT_ZIP,
PORT_STATE,
PORT_MORT_TYPE,
PORT_LOAN_NUM,
PORT_SLOAN_NUM,
PORT_SMORT_NAME_1,
PORT_SMORT_NAME_2,
PORT_SMORT_ADD_1,
PORT_SMORT_ADD_2,
PORT_SMORT_CTYST,
PORT_SMORT_ZIP,
PORT_SMORT_TYPE,
PORT_HALF_TERM_BP,
PORT_FULL_TERM_BP,
PORT_TRANSFER_DATE,
PORT_MB_TYPE,
PORT_MB_ACCT_NUM,
PORT_SC_LIAB_PRD_I,
PORT_FIRE_COVERAGE,
FEED_IND,
ECTL_BATCH_ID,
ECTL_ORIG_INS_TS,
ECTL_MODIFY_TS,
ECTL_SRC_ID,
ECTL_SRC_INST_ID,
ECTL_PRGM_ID,
ECTL_TX_CD,
ECTL_START_DATE,
ECTL_END_DATE
)
SELECT DISTINCT * FROM ( SELECT 
exp_GET_EFF_DATE.SC_DWNLD_PRIORITY1 as SC_DWNLD_PRIORITY,
exp_GET_EFF_DATE.SC_SERVICE_CENTER1 as SC_SERVICE_CENTER,
exp_GET_EFF_DATE.SC_POLICY_NUM1 as SC_POLICY_NUM,
exp_GET_EFF_DATE.out_CHG_EFF_DT as CHG_EFF_DT,
exp_GET_EFF_DATE.out_CHG_EXP_DT_NEW as CHG_EXP_DT,
exp_GET_EFF_DATE.SC_FLT_ITEM1 as SC_FLT_ITEM,
exp_GET_EFF_DATE.SC_FILE_TYPE1 as SC_FILE_TYPE,
exp_GET_EFF_DATE.SC_REC_TRANS_CODE1 as SC_REC_TRANS_CODE,
exp_GET_EFF_DATE.SC_TRANS_DATE1 as SC_TRANS_DATE,
exp_GET_EFF_DATE.SC_TRANS_TYPE1 as SC_TRANS_TYPE,
exp_GET_EFF_DATE.PC_ALPHA_CODE1 as PC_ALPHA_CODE,
exp_GET_EFF_DATE.PC_NAME_11 as PC_NAME_1,
exp_GET_EFF_DATE.PC_NAME_21 as PC_NAME_2,
exp_GET_EFF_DATE.PC_ADDRESS_11 as PC_ADDRESS_1,
exp_GET_EFF_DATE.PC_ADDRESS_21 as PC_ADDRESS_2,
exp_GET_EFF_DATE.PC_CITYST1 as PC_CITYST,
exp_GET_EFF_DATE.PC_ZIP1 as PC_ZIP,
exp_GET_EFF_DATE.PC_TAX_CODE1 as PC_TAX_CODE,
exp_GET_EFF_DATE.PC_AGENT1 as PC_AGENT,
exp_GET_EFF_DATE.PC_MEMBER_NUMBER1 as PC_MEMBER_NUMBER,
exp_GET_EFF_DATE.PC_RATE_CODE1 as PC_RATE_CODE,
exp_GET_EFF_DATE.PC_ENCUMBRANCE1 as PC_ENCUMBRANCE,
exp_GET_EFF_DATE.PC_PREM_FIN1 as PC_PREM_FIN,
exp_GET_EFF_DATE.PC_MORT_IND1 as PC_MORT_IND,
exp_GET_EFF_DATE.PC_COMPANY1 as PC_COMPANY,
exp_GET_EFF_DATE.PC_INCEPT_DATE1 as PC_INCEPT_DATE,
exp_GET_EFF_DATE.PC_EXP_DATE1 as PC_EXP_DATE,
exp_GET_EFF_DATE.PC_EFF_DATE1 as PC_EFF_DATE,
exp_GET_EFF_DATE.PC_STATUS1 as PC_STATUS,
exp_GET_EFF_DATE.PORT_TOT_PREM1 as PORT_TOT_PREM,
exp_GET_EFF_DATE.PORT_REWRITE_IND1 as PORT_REWRITE_IND,
exp_GET_EFF_DATE.PORT_REWRITE_DATE1 as PORT_REWRITE_DATE,
exp_GET_EFF_DATE.PORT_OUTST_AMT1 as PORT_OUTST_AMT,
exp_GET_EFF_DATE.PORT_OUTST_TYPE1 as PORT_OUTST_TYPE,
exp_GET_EFF_DATE.PORT_OUTST_DATE1 as PORT_OUTST_DATE,
exp_GET_EFF_DATE.PORT_OUTST_PD_DATE1 as PORT_OUTST_PD_DATE,
exp_GET_EFF_DATE.PORT_SUSPENSE_CD1 as PORT_SUSPENSE_CD,
exp_GET_EFF_DATE.PORT_SUSPENSE_CAN1 as PORT_SUSPENSE_CAN,
exp_GET_EFF_DATE.PORT_SSN_11 as PORT_SSN_1,
exp_GET_EFF_DATE.PORT_SSN_21 as PORT_SSN_2,
exp_GET_EFF_DATE.PORT_UW_REV_DATE1 as PORT_UW_REV_DATE,
exp_GET_EFF_DATE.PORT_UW_INITIALS1 as PORT_UW_INITIALS,
exp_GET_EFF_DATE.PORT_MORT_NAME_11 as PORT_MORT_NAME_1,
exp_GET_EFF_DATE.PORT_MORT_NAME_21 as PORT_MORT_NAME_2,
exp_GET_EFF_DATE.PORT_MORT_ADD_11 as PORT_MORT_ADD_1,
exp_GET_EFF_DATE.PORT_MORT_ADD_21 as PORT_MORT_ADD_2,
exp_GET_EFF_DATE.PORT_MORT_CTYST1 as PORT_MORT_CTYST,
exp_GET_EFF_DATE.PORT_MORT_ZIP1 as PORT_MORT_ZIP,
exp_GET_EFF_DATE.PORT_STATE1 as PORT_STATE,
exp_GET_EFF_DATE.PORT_MORT_TYPE1 as PORT_MORT_TYPE,
exp_GET_EFF_DATE.PORT_LOAN_NUM1 as PORT_LOAN_NUM,
exp_GET_EFF_DATE.PORT_SLOAN_NUM1 as PORT_SLOAN_NUM,
exp_GET_EFF_DATE.PORT_SMORT_NAME_11 as PORT_SMORT_NAME_1,
exp_GET_EFF_DATE.PORT_SMORT_NAME_21 as PORT_SMORT_NAME_2,
exp_GET_EFF_DATE.PORT_SMORT_ADD_11 as PORT_SMORT_ADD_1,
exp_GET_EFF_DATE.PORT_SMORT_ADD_21 as PORT_SMORT_ADD_2,
exp_GET_EFF_DATE.PORT_SMORT_CTYST1 as PORT_SMORT_CTYST,
exp_GET_EFF_DATE.PORT_SMORT_ZIP1 as PORT_SMORT_ZIP,
exp_GET_EFF_DATE.PORT_SMORT_TYPE1 as PORT_SMORT_TYPE,
exp_GET_EFF_DATE.PORT_HALF_TERM_BP1 as PORT_HALF_TERM_BP,
exp_GET_EFF_DATE.PORT_FULL_TERM_BP1 as PORT_FULL_TERM_BP,
exp_GET_EFF_DATE.PORT_TRANSFER_DATE1 as PORT_TRANSFER_DATE,
exp_GET_EFF_DATE.PORT_MB_TYPE1 as PORT_MB_TYPE,
exp_GET_EFF_DATE.PORT_MB_ACCT_NUM1 as PORT_MB_ACCT_NUM,
exp_GET_EFF_DATE.PORT_SC_LIAB_PRD_I1 as PORT_SC_LIAB_PRD_I,
exp_GET_EFF_DATE.PORT_FIRE_COVERAGE1 as PORT_FIRE_COVERAGE,
exp_GET_EFF_DATE.FEED_IND1 as FEED_IND,
exp_GET_EFF_DATE.ECTL_BATCH_ID1 as ECTL_BATCH_ID,
exp_GET_EFF_DATE.ORIG_INS_TS1 as ECTL_ORIG_INS_TS,
exp_GET_EFF_DATE.ORIG_INS_TS1 as ECTL_MODIFY_TS,
exp_GET_EFF_DATE.ECTL_SRC_ID1 as ECTL_SRC_ID,
exp_GET_EFF_DATE.ECTL_SRC_INST_ID1 as ECTL_SRC_INST_ID,
exp_GET_EFF_DATE.ECTL_PRGM_ID1 as ECTL_PRGM_ID,
exp_GET_EFF_DATE.out_ECTL_TX_CD as ECTL_TX_CD,
exp_GET_EFF_DATE.ECTL_BATCH_START_DATE1 as ECTL_START_DATE,
exp_GET_EFF_DATE.out_ECTL_END_DT as ECTL_END_DATE
FROM
exp_GET_EFF_DATE );


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component sq_PORTPOLS_DLY, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_PORTPOLS_DLY AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as SC_POLICY_NUM,
$2 as CHG_EFF_DT,
$3 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT PORTPOLS_DLY.SC_POLICY_NUM ,PORTPOLS_DLY.CHG_EFF_DT 
FROM
 DB_T_CORE_MEMBXREF_PROD.PORTPOLS_DLY WHERE CHG_EXP_DT = CAST(''9999-12-31'' AS DATE )
) SRC
)
);


-- Component exp_ASSIGN_DUMMY_TG, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ASSIGN_DUMMY_TG AS
(
SELECT
sq_PORTPOLS_DLY.SC_POLICY_NUM as SC_POLICY_NUM,
sq_PORTPOLS_DLY.CHG_EFF_DT as CHG_EFF_DT,
''PORTPOLS_DLY'' as var_TABLENAME,
LKP_1.FEED_DT /* replaced lookup LKP_STG_MEMBXEF_TRIGGER_DLY */ as var_LOAD_DT,
 TO_DATE ( var_LOAD_DT  )  - 1  as out_LOAD_DT,
sq_PORTPOLS_DLY.source_record_id,
row_number() over (partition by sq_PORTPOLS_DLY.source_record_id order by sq_PORTPOLS_DLY.source_record_id) as RNK
FROM
sq_PORTPOLS_DLY
LEFT JOIN LKP_STG_MEMBXEF_TRIGGER_DLY LKP_1 ON LKP_1.TABLENAME = var_TABLENAME
QUALIFY RNK = 1
);


-- Component LKP_STG_PORTPOLS_DLY, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_STG_PORTPOLS_DLY AS
(
SELECT
LKP.SC_POLICY_NUM,
exp_ASSIGN_DUMMY_TG.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_ASSIGN_DUMMY_TG.source_record_id ORDER BY LKP.SC_POLICY_NUM asc) RNK
FROM
exp_ASSIGN_DUMMY_TG
LEFT JOIN (
SELECT LTRIM(RTRIM(STG_PORTPOLS_DLY.SC_POLICY_NUM)) as SC_POLICY_NUM FROM DB_T_STAG_MEMBXREF_PROD.STG_PORTPOLS_DLY
) LKP ON LKP.SC_POLICY_NUM = exp_ASSIGN_DUMMY_TG.SC_POLICY_NUM
QUALIFY RNK = 1
);


-- Component fil_EXPIRED_POLS, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE fil_EXPIRED_POLS AS
(
SELECT
LKP_STG_PORTPOLS_DLY.SC_POLICY_NUM as SC_POLICY_NUM_tgt,
exp_ASSIGN_DUMMY_TG.CHG_EFF_DT as CHG_EFF_DT,
exp_ASSIGN_DUMMY_TG.SC_POLICY_NUM as SC_POLICY_NUM_src,
exp_ASSIGN_DUMMY_TG.out_LOAD_DT as LOAD_DT,
exp_ASSIGN_DUMMY_TG.source_record_id
FROM
exp_ASSIGN_DUMMY_TG
LEFT JOIN LKP_STG_PORTPOLS_DLY ON exp_ASSIGN_DUMMY_TG.source_record_id = LKP_STG_PORTPOLS_DLY.source_record_id
WHERE LKP_STG_PORTPOLS_DLY.SC_POLICY_NUM IS NULL
);


-- Component exp_INPUT_ECTL_FIELDS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_INPUT_ECTL_FIELDS AS
(
SELECT
fil_EXPIRED_POLS.CHG_EFF_DT as CHG_EFF_DT,
fil_EXPIRED_POLS.SC_POLICY_NUM_src as SC_POLICY_NUM_src,
LTRIM ( RTRIM ( :PMMappingName ) ) as out_PROJ_NAME,
:PROJ_ID as out_PROJ_ID,
:BATCH_ACTIVE_IND as out_BATCH_ACTIVE_IND,
''UPD'' as ECTL_TX_CD,
 fil_EXPIRED_POLS.LOAD_DT  - 1  as var_CHG_EXP_DT_NEW,
CASE WHEN fil_EXPIRED_POLS.CHG_EFF_DT >= var_CHG_EXP_DT_NEW THEN fil_EXPIRED_POLS.CHG_EFF_DT ELSE var_CHG_EXP_DT_NEW END as out_CHG_EXP_DT_NEW,
CURRENT_TIMESTAMP as out_ECTL_END_DATE,
fil_EXPIRED_POLS.source_record_id
FROM
fil_EXPIRED_POLS
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1;


-- Component upd_PORTPOLS_DLY_EXPIRED_POLS, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_PORTPOLS_DLY_EXPIRED_POLS AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1.out_ORIG_INS_TS as ECTL_MODIFY_TS,
exp_INPUT_ECTL_FIELDS.out_ECTL_END_DATE as ECTL_END_DATE,
exp_INPUT_ECTL_FIELDS.SC_POLICY_NUM_src as SC_POLICY_NUM,
exp_INPUT_ECTL_FIELDS.CHG_EFF_DT as CHG_EFF_DT,
exp_INPUT_ECTL_FIELDS.ECTL_TX_CD as ECTL_TX_CD,
exp_INPUT_ECTL_FIELDS.out_CHG_EXP_DT_NEW as CHG_EXP_DT,
1 as UPDATE_STRATEGY_ACTION
FROM
exp_INPUT_ECTL_FIELDS
LEFT JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1 ON exp_INPUT_ECTL_FIELDS.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE1.source_record_id
);


-- Component PORTPOLS_DLY_UPD_EXPIRED, Type TARGET 
/* Perform Updates */
MERGE INTO DB_T_core_MEMBXREF_PROD.PORTPOLS_DLY
USING upd_PORTPOLS_DLY_EXPIRED_POLS
ON (DB_T_core_MEMBXREF_PROD.PORTPOLS_DLY.SC_POLICY_NUM = upd_PORTPOLS_DLY_EXPIRED_POLS.SC_POLICY_NUM AND DB_T_core_MEMBXREF_PROD.PORTPOLS_DLY.CHG_EFF_DT = upd_PORTPOLS_DLY_EXPIRED_POLS.CHG_EFF_DT)
WHEN MATCHED THEN UPDATE SET
ECTL_BATCH_ID = 
nvl(upd_PORTPOLS_DLY_EXPIRED_POLS.ECTL_BATCH_ID,''1''), ECTL_MODIFY_TS = 
nvl(upd_PORTPOLS_DLY_EXPIRED_POLS.ECTL_MODIFY_TS,''1900-01-01''), ECTL_TX_CD = upd_PORTPOLS_DLY_EXPIRED_POLS.ECTL_TX_CD, ECTL_END_DATE = 
nvl(upd_PORTPOLS_DLY_EXPIRED_POLS.ECTL_END_DATE,''1900-01-01''), CHG_EXP_DT = 
nvl(upd_PORTPOLS_DLY_EXPIRED_POLS.CHG_EXP_DT,''1900-01-01'');


-- PIPELINE END FOR 2

END; ';