-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_MEMBER_MASTER("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
BEGIN 


-- Component SQ_Shortcut_to_MEMBER, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_Shortcut_to_MEMBER AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMBER_NBR,
$2 as AGENT,
$3 as SERVICE_CENTER,
$4 as USER_ID,
$5 as LAST_UPDATE_TS,
$6 as FONTEVA_STATUS,
$7 as TREX_BUS_WRT_AGT,
$8 as AGT_CSR_EMAIL,
$9 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT MEMBER.MEMBER_NBR,MEMBER.AGENT,
MEMBER.SERVICE_CENTER,
MEMBER.USER_ID,
MEMBER.LAST_UPDATE_TS,
MEMBER.FONTEVA_STATUS,
MEMBER.TREX_BUS_WRT_AGT,
MEMBER.AGT_CSR_EMAIL
 FROM DB_T_STAG_MEMBXREF_PROD.MEMBER left join DB_T_STAG_MEMBXREF_PROD.MEMBER m2
WHERE 1=2
) SRC
)
);


-- Component SQ_Shortcut_to_MEMBER, Type Post SQL 
UPDATE DB_T_STAG_MEMBXREF_PROD.MEMBER SET DATE_CANCELLED=CAST(LAST_UPDATE_TS AS DATE) WHERE STATUS =''3'' AND CAST( LAST_UPDATE_TS AS DATE)>=''2021-08-21'';


-- Component exp_EFF_DT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_EFF_DT AS
(
SELECT
SQ_Shortcut_to_MEMBER.LAST_UPDATE_TS as FEED_DT,
SQ_Shortcut_to_MEMBER.source_record_id
FROM
SQ_Shortcut_to_MEMBER
);


-- Component LKP_MEMBER_MSTR, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_MEMBER_MSTR AS
(
SELECT
LKP.MEMB_SKEY,
LKP.MEMB_NUM,
LKP.MEMB_EFF_DT,
LKP.MEMB_ORIG_SALES_AGENT_NBR,
LKP.MEMB_ORIG_SALES_AGENT_SC_NBR,
LKP.MEMB_ORIG_SALES_USER_ID,
LKP.MEMB_ORIG_SALES_USER_EMAIL,
LKP.MEMB_TREX_BUS_WRT_AGT,
SQ_Shortcut_to_MEMBER.source_record_id,
ROW_NUMBER() OVER(PARTITION BY SQ_Shortcut_to_MEMBER.source_record_id ORDER BY LKP.MEMB_SKEY asc,LKP.MEMB_NUM asc,LKP.MEMB_EFF_DT asc,LKP.MEMB_EXP_DT asc,LKP.MEMB_EMAIL asc,LKP.MEMB_PHONE asc,LKP.MEMB_ORIG_SALES_AGENT_NBR asc,LKP.MEMB_ORIG_SALES_AGENT_SC_NBR asc,LKP.MEMB_ORIG_SALES_USER_ID asc,LKP.MEMB_ORIG_SALES_USER_EMAIL asc,LKP.MEMB_TREX_BUS_WRT_AGT asc,LKP.MEMB_SEQ asc,LKP.MEMB_DATE_REQUESTED asc,LKP.MEMB_TIME_REQUESTED asc,LKP.ECTL_INS_BATCH_ID asc,LKP.ECTL_UPD_BATCH_ID asc,LKP.ECTL_INS_PRGM_ID asc,LKP.ECTL_UPD_PRGM_ID asc) RNK
FROM
SQ_Shortcut_to_MEMBER
LEFT JOIN (
SELECT	MEMBER_MSTR.MEMB_SKEY as MEMB_SKEY, MEMBER_MSTR.MEMB_EFF_DT as MEMB_EFF_DT,
		MEMBER_MSTR.MEMB_EXP_DT as MEMB_EXP_DT, MEMBER_MSTR.MEMB_EMAIL as MEMB_EMAIL,
		MEMBER_MSTR.MEMB_PHONE as MEMB_PHONE,MEMBER_MSTR.MEMB_ORIG_SALES_AGENT_NBR as MEMB_ORIG_SALES_AGENT_NBR,
		MEMBER_MSTR.MEMB_ORIG_SALES_AGENT_SC_NBR as MEMB_ORIG_SALES_AGENT_SC_NBR,
		MEMBER_MSTR.MEMB_ORIG_SALES_USER_ID as MEMB_ORIG_SALES_USER_ID,MEMBER_MSTR.MEMB_ORIG_SALES_USER_EMAIL as MEMB_ORIG_SALES_USER_EMAIL, 
		MEMB_TREX_BUS_WRT_AGT as MEMB_TREX_BUS_WRT_AGT,
		MEMBER_MSTR.MEMB_SEQ as MEMB_SEQ, MEMBER_MSTR.MEMB_DATE_REQUESTED as MEMB_DATE_REQUESTED,
		MEMBER_MSTR.MEMB_TIME_REQUESTED as MEMB_TIME_REQUESTED, MEMBER_MSTR.ECTL_INS_BATCH_ID as ECTL_INS_BATCH_ID,
		MEMBER_MSTR.ECTL_UPD_BATCH_ID as ECTL_UPD_BATCH_ID, MEMBER_MSTR.ECTL_INS_PRGM_ID as ECTL_INS_PRGM_ID,
		MEMBER_MSTR.ECTL_UPD_PRGM_ID as ECTL_UPD_PRGM_ID, MEMBER_MSTR.MEMB_NUM as MEMB_NUM 
FROM	DB_T_CORE_PROD.MEMBER_MSTR 
WHERE	cast(MEMB_EXP_DT as date) = ''9999-12-31''
) LKP ON LKP.MEMB_NUM = SQ_Shortcut_to_MEMBER.MEMBER_NBR
QUALIFY RNK = 1
);


-- Component LKP_AD_USERS, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_AD_USERS AS
(
SELECT
LKP.USER_NAME,
SQ_Shortcut_to_MEMBER.AGT_CSR_EMAIL as in_AGT_CSR_EMAIL,
SQ_Shortcut_to_MEMBER.source_record_id,
ROW_NUMBER() OVER(PARTITION BY SQ_Shortcut_to_MEMBER.source_record_id ORDER BY LKP.USER_NAME asc,LKP.EMAIL asc) RNK
FROM
SQ_Shortcut_to_MEMBER
LEFT JOIN (
SELECT AD_USERS.USER_NAME as USER_NAME, TRIM(AD_USERS.EMAIL) as EMAIL FROM DB_T_STAG_MEMBXREF_PROD.AD_USERS
WHERE LENGTH(TRIM(EMAIL)) >0
) LKP ON LKP.EMAIL = SQ_Shortcut_to_MEMBER.AGT_CSR_EMAIL
QUALIFY RNK = 1
);


-- Component exp_Batch_Prgm, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Batch_Prgm AS
(
SELECT
SQ_Shortcut_to_MEMBER.MEMBER_NBR as MEMBER_NBR,
4 as PROJECT_ID,
''Y'' as BATCH_ACTIVE_IND,
''M_MEMBER_MASTER'' as PROGRAM_NM,
''MEMBER_MASTER'' as TABLE_NAME,
SQ_Shortcut_to_MEMBER.source_record_id
FROM
SQ_Shortcut_to_MEMBER
);


-- Component m_lkp_Control_Tables, Type MAPPLET 
--MAPPLET NOT REGISTERED: m_lkp_Control_Tables, mapplet instance m_lkp_Control_Tables;
call m_lkp_Control_Tables(''exp_Batch_Prgm'');

-- Component EXPTRANS_Member, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS_Member AS
(
SELECT
LKP_MEMBER_MSTR.MEMB_SKEY as LKP_MEMB_SKEY,
SQ_Shortcut_to_MEMBER.MEMBER_NBR as MEMBER_NBR,
SEQ_MEMBER_KEY.NEXTVAL as SRC_MEMB_SKEY,
exp_EFF_DT.FEED_DT as EFF_DT,
m_lkp_Control_Tables.mplt_BATCH_ID as mplt_BATCH_ID,
m_lkp_Control_Tables.mplt_PRGM_ID as mplt_PRGM_ID,
SQ_Shortcut_to_MEMBER.AGENT as AGENT,
SQ_Shortcut_to_MEMBER.SERVICE_CENTER as SERVICE_CENTER,
SQ_Shortcut_to_MEMBER.TREX_BUS_WRT_AGT as TREX_BUS_WRT_AGT,
LKP_AD_USERS.in_AGT_CSR_EMAIL as AGT_CSR_EMAIL,
CASE WHEN SQ_Shortcut_to_MEMBER.TREX_BUS_WRT_AGT IN ( UPPER ( LTRIM ( RTRIM ( SQ_Shortcut_to_MEMBER.TREX_BUS_WRT_AGT ) ) ) , ''ALFA'' , ''TREXIS'' ) THEN LKP_AD_USERS.USER_NAME ELSE SQ_Shortcut_to_MEMBER.USER_ID END as v_USER_ID,
v_USER_ID as o_USER_ID,
SQ_Shortcut_to_MEMBER.FONTEVA_STATUS as FONTEVA_STATUS,
LKP_MEMBER_MSTR.MEMB_NUM as LKP_MEMB_NUM,
LKP_MEMBER_MSTR.MEMB_EFF_DT as LKP_MEMB_EFF_DT,
MD5 ( CASE WHEN v_USER_ID IS NULL THEN ''~'' ELSE v_USER_ID END || CASE WHEN TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_MEMBER.SERVICE_CENTER ) ) ) IS NULL THEN ''~'' ELSE TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_MEMBER.SERVICE_CENTER ) ) ) END || CASE WHEN TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_MEMBER.AGENT ) ) ) IS NULL THEN ''~'' ELSE TO_CHAR ( LTRIM ( RTRIM ( SQ_Shortcut_to_MEMBER.AGENT ) ) ) END || CASE WHEN SQ_Shortcut_to_MEMBER.TREX_BUS_WRT_AGT IS NULL THEN ''~'' ELSE SQ_Shortcut_to_MEMBER.TREX_BUS_WRT_AGT END || CASE WHEN LTRIM ( RTRIM ( LKP_AD_USERS.in_AGT_CSR_EMAIL ) ) IS NULL THEN ''~'' ELSE LKP_AD_USERS.in_AGT_CSR_EMAIL END ) as v_src_md5,
MD5 ( CASE WHEN LKP_MEMBER_MSTR.MEMB_ORIG_SALES_USER_ID IS NULL THEN ''~'' ELSE LKP_MEMBER_MSTR.MEMB_ORIG_SALES_USER_ID END || CASE WHEN TO_CHAR ( LTRIM ( RTRIM ( LKP_MEMBER_MSTR.MEMB_ORIG_SALES_AGENT_SC_NBR ) ) ) IS NULL THEN ''~'' ELSE TO_CHAR ( LTRIM ( RTRIM ( LKP_MEMBER_MSTR.MEMB_ORIG_SALES_AGENT_SC_NBR ) ) ) END || CASE WHEN TO_CHAR ( LTRIM ( RTRIM ( LKP_MEMBER_MSTR.MEMB_ORIG_SALES_AGENT_NBR ) ) ) IS NULL THEN ''~'' ELSE TO_CHAR ( LTRIM ( RTRIM ( LKP_MEMBER_MSTR.MEMB_ORIG_SALES_AGENT_NBR ) ) ) END || CASE WHEN LKP_MEMBER_MSTR.MEMB_TREX_BUS_WRT_AGT IS NULL THEN ''~'' ELSE LKP_MEMBER_MSTR.MEMB_TREX_BUS_WRT_AGT END || CASE WHEN LTRIM ( RTRIM ( LKP_MEMBER_MSTR.MEMB_ORIG_SALES_USER_EMAIL ) ) IS NULL THEN ''~'' ELSE LKP_MEMBER_MSTR.MEMB_ORIG_SALES_USER_EMAIL END ) as v_lkp_md5,
CASE WHEN LKP_MEMBER_MSTR.MEMB_NUM IS NULL THEN ''I'' ELSE CASE WHEN v_lkp_md5 = v_src_md5 THEN ''R'' ELSE ''U'' END END as out_flag,
SQ_Shortcut_to_MEMBER.source_record_id
FROM
SQ_Shortcut_to_MEMBER
INNER JOIN exp_EFF_DT ON SQ_Shortcut_to_MEMBER.source_record_id = exp_EFF_DT.source_record_id
INNER JOIN LKP_MEMBER_MSTR ON exp_EFF_DT.source_record_id = LKP_MEMBER_MSTR.source_record_id
INNER JOIN LKP_AD_USERS ON LKP_MEMBER_MSTR.source_record_id = LKP_AD_USERS.source_record_id
INNER JOIN m_lkp_Control_Tables ON LKP_AD_USERS.source_record_id = m_lkp_Control_Tables.source_record_id
);


-- Component Router_member_mstr_INSERT, Type ROUTER Output Group INSERT
CREATE OR REPLACE TEMP TABLE ROUTER_MEMBER_MSTR_INSERT AS (
SELECT
EXPTRANS_Member.LKP_MEMB_SKEY as LKP_MEMB_SKEY,
EXPTRANS_Member.SRC_MEMB_SKEY as SRC_MEMB_SKEY,
EXPTRANS_Member.MEMBER_NBR as MEMBER_NBR,
EXPTRANS_Member.EFF_DT as EFF_DT,
EXPTRANS_Member.mplt_BATCH_ID as mplt_BATCH_ID,
EXPTRANS_Member.mplt_PRGM_ID as mplt_PRGM_ID,
EXPTRANS_Member.AGENT as AGENT,
EXPTRANS_Member.SERVICE_CENTER as SERVICE_CENTER,
EXPTRANS_Member.o_USER_ID as USER_ID,
EXPTRANS_Member.FONTEVA_STATUS as FONTEVA_STATUS,
EXPTRANS_Member.LKP_MEMB_EFF_DT as LKP_MEMB_EFF_DT,
EXPTRANS_Member.LKP_MEMB_NUM as LKP_MEMB_NUM,
EXPTRANS_Member.out_flag as out_flag,
EXPTRANS_Member.TREX_BUS_WRT_AGT as TREX_BUS_WRT_AGT,
EXPTRANS_Member.AGT_CSR_EMAIL as AGT_CSR_EMAIL,
EXPTRANS_Member.source_record_id
FROM
EXPTRANS_Member
WHERE EXPTRANS_Member.LKP_MEMB_NUM IS NULL and EXPTRANS_Member.out_flag = ''I''
);


-- Component Router_member_mstr_UPDATE, Type ROUTER Output Group UPDATE
CREATE OR REPLACE TEMP TABLE ROUTER_MEMBER_MSTR_UPDATE AS (
SELECT
EXPTRANS_Member.LKP_MEMB_SKEY as LKP_MEMB_SKEY,
EXPTRANS_Member.SRC_MEMB_SKEY as SRC_MEMB_SKEY,
EXPTRANS_Member.MEMBER_NBR as MEMBER_NBR,
EXPTRANS_Member.EFF_DT as EFF_DT,
EXPTRANS_Member.mplt_BATCH_ID as mplt_BATCH_ID,
EXPTRANS_Member.mplt_PRGM_ID as mplt_PRGM_ID,
EXPTRANS_Member.AGENT as AGENT,
EXPTRANS_Member.SERVICE_CENTER as SERVICE_CENTER,
EXPTRANS_Member.o_USER_ID as USER_ID,
EXPTRANS_Member.FONTEVA_STATUS as FONTEVA_STATUS,
EXPTRANS_Member.LKP_MEMB_EFF_DT as LKP_MEMB_EFF_DT,
EXPTRANS_Member.LKP_MEMB_NUM as LKP_MEMB_NUM,
EXPTRANS_Member.out_flag as out_flag,
EXPTRANS_Member.TREX_BUS_WRT_AGT as TREX_BUS_WRT_AGT,
EXPTRANS_Member.AGT_CSR_EMAIL as AGT_CSR_EMAIL,
EXPTRANS_Member.source_record_id
FROM
EXPTRANS_Member
WHERE EXPTRANS_Member.LKP_MEMB_NUM IS NOT NULL and EXPTRANS_Member.out_flag = ''U''
);


-- Component UPDTRANS, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE UPDTRANS AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
Router_member_mstr_UPDATE.LKP_MEMB_SKEY as LKP_MEMB_SKEY1,
Router_member_mstr_UPDATE.MEMBER_NBR as MEMBER_NBR1,
Router_member_mstr_UPDATE.EFF_DT as EFF_DT1,
Router_member_mstr_UPDATE.mplt_BATCH_ID as mplt_BATCH_ID1,
Router_member_mstr_UPDATE.mplt_PRGM_ID as mplt_PRGM_ID1,
Router_member_mstr_UPDATE.LKP_MEMB_EFF_DT as LKP_MEMB_EFF_DT3,
Router_member_mstr_UPDATE.AGENT as AGENT3,
Router_member_mstr_UPDATE.SERVICE_CENTER as SERVICE_CENTER3,
Router_member_mstr_UPDATE.USER_ID as USER_ID3,
Router_member_mstr_UPDATE.TREX_BUS_WRT_AGT as TREX_BUS_WRT_AGT3,
Router_member_mstr_UPDATE.AGT_CSR_EMAIL as AGMT_CSR_EMAIL,
Router_member_mstr_UPDATE.source_record_id,
1 as UPDATE_STRATEGY_ACTION
FROM
Router_member_mstr_UPDATE
);


-- Component exp_New_Member, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_New_Member AS
(
SELECT
Router_member_mstr_INSERT.MEMBER_NBR as MEMBER_NBR,
Router_member_mstr_INSERT.EFF_DT as EFF_DT,
to_date ( ''12/31/9999 23:59:59.999999'' , ''MM/DD/YYYY HH24:MI:SS.FF6'' ) as EXP_DT,
Router_member_mstr_INSERT.mplt_BATCH_ID as INS_BATCH_ID,
Router_member_mstr_INSERT.mplt_PRGM_ID as INS_PRGM_ID,
Router_member_mstr_INSERT.AGENT as AGENT_NBR1,
Router_member_mstr_INSERT.SERVICE_CENTER as SC_NUMBER1,
Router_member_mstr_INSERT.USER_ID as USER_ID1,
Router_member_mstr_INSERT.SRC_MEMB_SKEY as SRC_MEMB_SKEY1,
Router_member_mstr_INSERT.TREX_BUS_WRT_AGT as TREX_BUS_WRT_AGT1,
Router_member_mstr_INSERT.AGT_CSR_EMAIL as AGT_CSR_EMAIL1,
Router_member_mstr_INSERT.source_record_id
FROM
Router_member_mstr_INSERT
);


-- Component EXPTRANS_Expire, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS_Expire AS
(
SELECT
UPDTRANS.LKP_MEMB_SKEY1 as LKP_MEMB_SKEY1,
UPDTRANS.MEMBER_NBR1 as MEMBER_NBR1,
UPDTRANS.mplt_BATCH_ID1 as mplt_BATCH_ID1,
UPDTRANS.mplt_PRGM_ID1 as mplt_PRGM_ID1,
UPDTRANS.LKP_MEMB_EFF_DT3 as LKP_MEMB_EFF_DT3,
UPDTRANS.AGENT3 as AGENT3,
UPDTRANS.SERVICE_CENTER3 as SERVICE_CENTER3,
UPDTRANS.USER_ID3 as USER_ID3,
UPDTRANS.TREX_BUS_WRT_AGT3 as TREX_BUS_WRT_AGT3,
UPDTRANS.AGMT_CSR_EMAIL as AGMT_CSR_EMAIL,
UPDTRANS.source_record_id
FROM
UPDTRANS
);


-- Component MEMBER_MSTR_INS, Type TARGET 
INSERT INTO DB_T_CORE_PROD.MEMBER_MSTR
(
MEMB_SKEY,
MEMB_NUM,
MEMB_EFF_DT,
MEMB_EXP_DT,
MEMB_ORIG_SALES_AGENT_NBR,
MEMB_ORIG_SALES_AGENT_SC_NBR,
MEMB_ORIG_SALES_USER_ID,
MEMB_ORIG_SALES_USER_EMAIL,
MEMB_TREX_BUS_WRT_AGT,
ECTL_INS_BATCH_ID,
ECTL_INS_PRGM_ID
)
SELECT
exp_New_Member.SRC_MEMB_SKEY1 as MEMB_SKEY,
exp_New_Member.MEMBER_NBR as MEMB_NUM,
exp_New_Member.EFF_DT as MEMB_EFF_DT,
exp_New_Member.EXP_DT as MEMB_EXP_DT,
exp_New_Member.AGENT_NBR1 as MEMB_ORIG_SALES_AGENT_NBR,
exp_New_Member.SC_NUMBER1 as MEMB_ORIG_SALES_AGENT_SC_NBR,
exp_New_Member.USER_ID1 as MEMB_ORIG_SALES_USER_ID,
exp_New_Member.AGT_CSR_EMAIL1 as MEMB_ORIG_SALES_USER_EMAIL,
exp_New_Member.TREX_BUS_WRT_AGT1 as MEMB_TREX_BUS_WRT_AGT,
exp_New_Member.INS_BATCH_ID as ECTL_INS_BATCH_ID,
exp_New_Member.INS_PRGM_ID as ECTL_INS_PRGM_ID
FROM
exp_New_Member;


-- Component MEMBER_MSTR_UPD, Type TARGET 
MERGE INTO DB_T_CORE_PROD.MEMBER_MSTR
USING EXPTRANS_Expire ON (MEMBER_MSTR.MEMB_SKEY = EXPTRANS_Expire.LKP_MEMB_SKEY1 AND MEMBER_MSTR.MEMB_EFF_DT = EXPTRANS_Expire.LKP_MEMB_EFF_DT3)
WHEN MATCHED THEN UPDATE
SET
MEMB_SKEY = EXPTRANS_Expire.LKP_MEMB_SKEY1,
MEMB_NUM = EXPTRANS_Expire.MEMBER_NBR1,
MEMB_EFF_DT = EXPTRANS_Expire.LKP_MEMB_EFF_DT3,
MEMB_ORIG_SALES_AGENT_NBR = EXPTRANS_Expire.AGENT3,
MEMB_ORIG_SALES_AGENT_SC_NBR = EXPTRANS_Expire.SERVICE_CENTER3,
MEMB_ORIG_SALES_USER_ID = EXPTRANS_Expire.USER_ID3,
MEMB_ORIG_SALES_USER_EMAIL = EXPTRANS_Expire.AGMT_CSR_EMAIL,
MEMB_TREX_BUS_WRT_AGT = EXPTRANS_Expire.TREX_BUS_WRT_AGT3,
ECTL_UPD_BATCH_ID = EXPTRANS_Expire.mplt_BATCH_ID1,
ECTL_UPD_PRGM_ID = EXPTRANS_Expire.mplt_PRGM_ID1;


END; ';