-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_MEMBER_TRANSACTION("RUN_ID" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE PMMAPPINGNAME varchar;
BEGIN 

PMMAPPINGNAME:='' ''; 

-- Component STG_FED_MSTR_DELTA, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE STG_FED_MSTR_DELTA AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MEMBER_NBR,
$2 as FED_TYPE,
$3 as COMMODITY,
$4 as COUNTY,
$5 as STATUS,
$6 as AMOUNT_PAID,
$7 as PAID_TO_DATE,
$8 as COPAY_DATE,
$9 as FED_SOURCE,
$10 as OUT_OF_STATE,
$11 as COUNTY_CHG_IND,
$12 as TX_CD,
$13 as DATE_BILLED,
$14 as DATE_PAID,
$15 as DATE_CANCELLED,
$16 as FEED_DT,
$17 as FEED_IND,
$18 as GW_BILL_REF,
$19 as GW_DUE_DATE,
$20 as COMB_BILL_IND,
$21 as ALLOW_COMBINED_BILLING,
$22 as FOUR_DAY_LTR_IND,
$23 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 
STG_FED_MSTR_DELTA.MEMBER_NBR, 
STG_FED_MSTR_DELTA.FED_TYPE, 
coalesce(STG_FED_MSTR_DELTA.COMMODITY,'' '') AS COMMODITY, 
STG_FED_MSTR_DELTA.COUNTY, 
STG_FED_MSTR_DELTA.STATUS, 
STG_FED_MSTR_DELTA.AMOUNT_PAID, 
STG_FED_MSTR_DELTA.PAID_TO_DATE, 
STG_FED_MSTR_DELTA.COPAY_DATE, 
coalesce(STG_FED_MSTR_DELTA.FED_SOURCE,'' '') AS FED_SOURCE, 
coalesce(STG_FED_MSTR_DELTA.OUT_OF_STATE,'' '') AS OUT_OF_STATE,
coalesce(STG_FED_MSTR_DELTA.COUNTY_CHG_IND, '' '') AS COUNTY_CHG_IND, 
STG_FED_MSTR_DELTA.TX_CD,
STG_FED_MSTR_DELTA.DATE_BILLED,
STG_FED_MSTR_DELTA.DATE_PAID,
STG_FED_MSTR_DELTA.DATE_CANCELLED,
STG_FED_MSTR_TRG.FEED_DT,
STG_FED_MSTR_TRG.FEED_IND,
STG_FED_MSTR_DELTA.GW_BILL_REF,
STG_FED_MSTR_DELTA.GW_DUE_DATE,
STG_FED_MSTR_DELTA.COMB_BILL_IND,
STG_FED_MSTR_DELTA.ALLOW_COMBINED_BILLING,
STG_FED_MSTR_DELTA.FOUR_DAY_LTR_IND
FROM
 DB_T_STAG_PROD.STG_FED_MSTR_DELTA, DB_T_STAG_PROD.STG_FED_MSTR_TRG
WHERE TX_CD <> ''DEL''
) SRC
)
);


-- Component LKP_MEMBER_MSTR, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_MEMBER_MSTR AS
(
SELECT
LKP.MEMB_SKEY,
LKP.MEMB_EFF_DT,
STG_FED_MSTR_DELTA.source_record_id,
ROW_NUMBER() OVER(PARTITION BY STG_FED_MSTR_DELTA.source_record_id ORDER BY LKP.MEMB_SKEY asc,LKP.MEMB_NUM asc,LKP.MEMB_EFF_DT asc,LKP.MEMB_EXP_DT asc,LKP.MEMB_EMAIL asc,LKP.MEMB_PHONE asc,LKP.ECTL_INS_BATCH_ID asc,LKP.ECTL_UPD_BATCH_ID asc,LKP.ECTL_INS_PRGM_ID asc,LKP.ECTL_UPD_PRGM_ID asc) RNK
FROM
STG_FED_MSTR_DELTA
LEFT JOIN (
SELECT MEMBER_MSTR.MEMB_SKEY as MEMB_SKEY, 
MEMBER_MSTR.MEMB_NUM as MEMB_NUM, 
MEMBER_MSTR.MEMB_EFF_DT as MEMB_EFF_DT, 
MEMBER_MSTR.MEMB_EXP_DT as MEMB_EXP_DT, 
MEMBER_MSTR.MEMB_EMAIL as MEMB_EMAIL, 
MEMBER_MSTR.MEMB_PHONE as MEMB_PHONE, 
MEMBER_MSTR.ECTL_INS_BATCH_ID as ECTL_INS_BATCH_ID, MEMBER_MSTR.ECTL_UPD_BATCH_ID as ECTL_UPD_BATCH_ID, MEMBER_MSTR.ECTL_INS_PRGM_ID as ECTL_INS_PRGM_ID,
MEMBER_MSTR.ECTL_UPD_PRGM_ID as ECTL_UPD_PRGM_ID
FROM DB_T_CORE_PROD.MEMBER_MSTR
WHERE MEMB_EXP_DT = ''9999-12-31''
) LKP ON LKP.MEMB_NUM = STG_FED_MSTR_DELTA.MEMBER_NBR
QUALIFY RNK = 1
);


-- Component exp_Source, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Source AS
(
SELECT
LKP_MEMBER_MSTR.MEMB_SKEY as MEMB_SKEY,
STG_FED_MSTR_DELTA.FED_TYPE as FED_TYPE,
STG_FED_MSTR_DELTA.COMMODITY as COMMODITY,
STG_FED_MSTR_DELTA.COUNTY as COUNTY,
STG_FED_MSTR_DELTA.STATUS as STATUS,
STG_FED_MSTR_DELTA.AMOUNT_PAID as AMOUNT_PAID,
try_to_date ( STG_FED_MSTR_DELTA.PAID_TO_DATE , ''YYYYMMDD'' ) as out_PAID_TO_DATE,
try_to_date ( STG_FED_MSTR_DELTA.COPAY_DATE , ''YYYYMMDD'' ) as out_COPAY_DATE,
STG_FED_MSTR_DELTA.FED_SOURCE as FED_SOURCE,
STG_FED_MSTR_DELTA.OUT_OF_STATE as OUT_OF_STATE,
STG_FED_MSTR_DELTA.COUNTY_CHG_IND as COUNTY_CHG_IND,
STG_FED_MSTR_DELTA.TX_CD as TX_CD,
STG_FED_MSTR_DELTA.FEED_IND as FEED_IND,
CASE WHEN STG_FED_MSTR_DELTA.TX_CD = ''NEW'' THEN LKP_MEMBER_MSTR.MEMB_EFF_DT ELSE CASE WHEN STG_FED_MSTR_DELTA.TX_CD = ''UPD'' and STG_FED_MSTR_DELTA.FEED_IND = ''X'' THEN to_date ( ''0101'' || to_char ( DATE_PART(''YYYY'', TO_TIMESTAMP(STG_FED_MSTR_DELTA.FEED_DT)) ) , ''MMDDYYYY'' ) ELSE CASE WHEN STG_FED_MSTR_DELTA.TX_CD = ''UPD'' and STG_FED_MSTR_DELTA.FEED_IND = ''M'' THEN to_date ( lpad ( to_char ( DATE_PART(''MM'', TO_TIMESTAMP(STG_FED_MSTR_DELTA.FEED_DT)) ) , 2 , ''0'' ) || ''01'' || to_char ( DATE_PART(''YYYY'', TO_TIMESTAMP(STG_FED_MSTR_DELTA.FEED_DT)) ) , ''MMDDYYYY'' ) ELSE STG_FED_MSTR_DELTA.FEED_DT END END END as out_CHG_EFF_DT,
4 as PROJECT_ID,
''Y'' as BATCH_ACTIVE_IND,
:PMMappingName as PROGRAM_NM,
''MEMBER_TRANS'' as TABLE_NAME,
substr ( STG_FED_MSTR_DELTA.DATE_BILLED , 1 , 4 ) as out_DB_YYYY,
substr ( STG_FED_MSTR_DELTA.DATE_BILLED , 5 , 2 ) as out_DB_MM,
substr ( STG_FED_MSTR_DELTA.DATE_BILLED , 7 , 2 ) as out_DB_DD,
substr ( STG_FED_MSTR_DELTA.DATE_PAID , 1 , 4 ) as out_DP_YYYY,
substr ( STG_FED_MSTR_DELTA.DATE_PAID , 5 , 2 ) as out_DP_MM,
substr ( STG_FED_MSTR_DELTA.DATE_PAID , 7 , 2 ) as out_DP_DD,
substr ( STG_FED_MSTR_DELTA.DATE_CANCELLED , 1 , 4 ) as out_DC_YYYY,
substr ( STG_FED_MSTR_DELTA.DATE_CANCELLED , 5 , 2 ) as out_DC_MM,
substr ( STG_FED_MSTR_DELTA.DATE_CANCELLED , 7 , 2 ) as out_DC_DD,
STG_FED_MSTR_DELTA.GW_BILL_REF as GW_BILL_REF,
try_to_date ( STG_FED_MSTR_DELTA.GW_DUE_DATE , ''YYYYMMDD'' ) as out_GW_DUE_DATE,
STG_FED_MSTR_DELTA.COMB_BILL_IND as COMB_BILL_IND,
STG_FED_MSTR_DELTA.ALLOW_COMBINED_BILLING as ALLOW_COMBINED_BILLING,
STG_FED_MSTR_DELTA.FOUR_DAY_LTR_IND as FOUR_DAY_LTR_IND,
STG_FED_MSTR_DELTA.source_record_id
FROM
STG_FED_MSTR_DELTA
INNER JOIN LKP_MEMBER_MSTR ON STG_FED_MSTR_DELTA.source_record_id = LKP_MEMBER_MSTR.source_record_id
);


-- Component m_validate_date_DC, Type MAPPLET 
--MAPPLET NOT REGISTERED: m_validate_date, mapplet instance m_validate_date_DC;
create or replace table exp_Source_DC as SELECT out_DC_YYYY as YYYY, out_DC_MM as MM, out_DC_DD as DD, source_record_id FROM exp_Source;
CALL m_validate_date(''exp_Source_DC'');
create or replace temp table m_validate_date_DC as select * from m_validate_date;


-- Component LKP_MEMBER_TRANS, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_MEMBER_TRANS AS
(
SELECT
LKP.MEMB_SKEY,
LKP.CHG_EFF_DT,
LKP.MEMB_TYPE,
LKP.COMMODITY,
LKP.COMM_CD1,
LKP.COMM_CD2,
LKP.COMM_CD3,
LKP.COUNTY_CD,
LKP.STATUS_CD,
LKP.AMT_PAID,
LKP.PAID_TO_DT,
LKP.COUNTY_PAID_DT,
LKP.FED_SRC,
LKP.OUT_OF_STATE,
LKP.COUNTY_CHG_IND,
LKP.PREV_STATUS_CD,
LKP.DATE_BILLED,
LKP.DATE_PAID,
LKP.DATE_CANCELLED,
LKP.GW_BILL_REF,
LKP.GW_DUE_DATE,
LKP.COMB_BILL_IND,
LKP.ALLOW_COMBINED_BILLING,
LKP.FOUR_DAY_LTR_IND,
exp_Source.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_Source.source_record_id ORDER BY LKP.MEMB_SKEY asc,LKP.CHG_EFF_DT asc,LKP.MEMB_TYPE asc,LKP.COMMODITY asc,LKP.COMM_CD1 asc,LKP.COMM_CD2 asc,LKP.COMM_CD3 asc,LKP.COUNTY_CD asc,LKP.STATUS_CD asc,LKP.AMT_PAID asc,LKP.PAID_TO_DT asc,LKP.COUNTY_PAID_DT asc,LKP.FED_SRC asc,LKP.OUT_OF_STATE asc,LKP.COUNTY_CHG_IND asc,LKP.PREV_STATUS_CD asc,LKP.DATE_BILLED asc,LKP.DATE_PAID asc,LKP.DATE_CANCELLED asc,LKP.GW_BILL_REF asc,LKP.GW_DUE_DATE asc,LKP.COMB_BILL_IND asc,LKP.ALLOW_COMBINED_BILLING asc,LKP.FOUR_DAY_LTR_IND asc) RNK
FROM
exp_Source
LEFT JOIN (
SELECT 
MEMBER_TRANS.MEMB_SKEY as MEMB_SKEY,
MEMBER_TRANS.CHG_EFF_DT as CHG_EFF_DT, 
MEMBER_TRANS.MEMB_TYPE as MEMB_TYPE, 
Trim(Trim(MEMBER_TRANS.COMM_CD1) ||  
Trim(MEMBER_TRANS.COMM_CD2) || 
Trim(MEMBER_TRANS.COMM_CD3)) AS COMMODITY, 
MEMBER_TRANS.COMM_CD1 as COMM_CD1, 
MEMBER_TRANS.COMM_CD2 as COMM_CD2, 
MEMBER_TRANS.COMM_CD3 as COMM_CD3, 
MEMBER_TRANS.COUNTY_CD as COUNTY_CD, 
MEMBER_TRANS.STATUS_CD as STATUS_CD, 
MEMBER_TRANS.AMT_PAID as AMT_PAID, 
MEMBER_TRANS.PAID_TO_DT as PAID_TO_DT, 
MEMBER_TRANS.COUNTY_PAID_DT as COUNTY_PAID_DT, 
coalesce(MEMBER_TRANS.FED_SRC , '' '') AS FED_SRC, 
coalesce(MEMBER_TRANS.OUT_OF_STATE , '' '') AS OUT_OF_STATE, 
coalesce(MEMBER_TRANS.COUNTY_CHG_IND , '' '') AS COUNTY_CHG_IND,
MEMBER_TRANS.PREV_STATUS_CD as PREV_STATUS_CD,
MEMBER_TRANS.DATE_BILLED as DATE_BILLED,
MEMBER_TRANS.DATE_PAID as DATE_PAID,
MEMBER_TRANS.DATE_CANCELLED as DATE_CANCELLED,
MEMBER_TRANS.GW_BILL_REF as GW_BILL_REF,
MEMBER_TRANS.GW_DUE_DATE as GW_DUE_DATE,
MEMBER_TRANS.COMB_BILL_IND as COMB_BILL_IND,
MEMBER_TRANS.ALLOW_COMBINED_BILLING as ALLOW_COMBINED_BILLING,
MEMBER_TRANS.FOUR_DAY_LTR_IND as FOUR_DAY_LTR_IND
FROM DB_T_CORE_PROD.MEMBER_TRANS
WHERE CHG_EXP_DT = ''9999-12-31''
) LKP ON LKP.MEMB_SKEY = exp_Source.MEMB_SKEY
QUALIFY RNK = 1
);


-- Component m_validate_date_DP, Type MAPPLET 
--MAPPLET NOT REGISTERED: m_validate_date, mapplet instance m_validate_date_DP;
create or replace table exp_Source_DP as SELECT out_DP_YYYY as YYYY, out_DP_MM as MM, out_DP_DD as DD, source_record_id FROM exp_Source;
call m_validate_date(''exp_Source_DP'');
create or replace temp table m_validate_date_DP as select * from m_validate_date;

-- Component m_lkp_Control_Tables, Type MAPPLET 
--MAPPLET NOT REGISTERED: m_lkp_Control_Tables, mapplet instance m_lkp_Control_Tables;
call m_lkp_Control_Tables(''exp_Source'');

-- Component m_validate_date_DB, Type MAPPLET 
--MAPPLET NOT REGISTERED: m_validate_date, mapplet instance m_validate_date_DB;
create or replace table exp_Source_DB as SELECT out_DB_YYYY as YYYY, out_DB_MM as MM, out_DB_DD as DD, source_record_id FROM exp_Source;
call m_validate_date(''exp_Source_DB'');
create or replace temp table m_validate_date_DB as select * from m_validate_date;

-- Component rtr_Member_Trans_NEW, Type ROUTER Output Group NEW
create or replace temp table rtr_Member_Trans_NEW as
SELECT
LKP_MEMBER_TRANS.MEMB_SKEY as MEMB_SKEY_MTLKP,
LKP_MEMBER_TRANS.CHG_EFF_DT as CHG_EFF_DT_MTLKP,
LKP_MEMBER_TRANS.MEMB_TYPE as MEMB_TYPE_MTLKP,
LKP_MEMBER_TRANS.COMMODITY as COMMODITY_MTLKP,
LKP_MEMBER_TRANS.COMM_CD1 as COMM_CD1_MTLKP,
LKP_MEMBER_TRANS.COMM_CD2 as COMM_CD2_MTLKP,
LKP_MEMBER_TRANS.COMM_CD3 as COMM_CD3_MTLKP,
LKP_MEMBER_TRANS.COUNTY_CD as COUNTY_CD_MTLKP,
LKP_MEMBER_TRANS.STATUS_CD as STATUS_CD_MTLKP,
LKP_MEMBER_TRANS.AMT_PAID as AMT_PAID_MTLKP,
LKP_MEMBER_TRANS.PAID_TO_DT as PAID_TO_DT_MTLKP,
LKP_MEMBER_TRANS.COUNTY_PAID_DT as COUNTY_PAID_DT_MTLKP,
LKP_MEMBER_TRANS.FED_SRC as FED_SRC_MTLKP,
LKP_MEMBER_TRANS.OUT_OF_STATE as OUT_OF_STATE_MTLKP,
LKP_MEMBER_TRANS.COUNTY_CHG_IND as COUNTY_CHG_IND_MTLKP,
LKP_MEMBER_TRANS.PREV_STATUS_CD as PREV_STATUS_CD_MTLKP,
LKP_MEMBER_TRANS.GW_BILL_REF as GW_BILL_REF_MTLKP,
LKP_MEMBER_TRANS.GW_DUE_DATE as GW_DUE_DATE_MTLKP,
LKP_MEMBER_TRANS.COMB_BILL_IND as COMB_BILL_IND_MTLKP,
LKP_MEMBER_TRANS.ALLOW_COMBINED_BILLING as ALLOW_COMBINED_BILLING_MTLKP,
LKP_MEMBER_TRANS.FOUR_DAY_LTR_IND as FOUR_DAY_LTR_IND_MTLKP,
exp_Source.MEMB_SKEY as MEMB_SKEY_SRC,
exp_Source.FED_TYPE as FED_TYPE_SRC,
exp_Source.COMMODITY as COMMODITY_SRC,
exp_Source.COUNTY as COUNTY_SRC,
exp_Source.STATUS as STATUS_SRC,
exp_Source.AMOUNT_PAID as AMOUNT_PAID_SRC,
exp_Source.out_PAID_TO_DATE as PAID_TO_DATE_SRC,
exp_Source.out_COPAY_DATE as COPAY_DATE_SRC,
exp_Source.FED_SOURCE as FED_SOURCE_SRC,
exp_Source.OUT_OF_STATE as OUT_OF_STATE_SRC,
exp_Source.COUNTY_CHG_IND as COUNTY_CHG_IND_SRC,
exp_Source.TX_CD as TX_CD,
exp_Source.out_CHG_EFF_DT as CHG_EFF_DT,
exp_Source.FEED_IND as FEED_IND,
m_validate_date_DB.out_DATE_DT as DATE_BILLED_DELTA,
m_validate_date_DP.out_DATE_DT as DATE_PAID_DELTA,
m_validate_date_DC.out_DATE_DT as DATE_CANCELLED_DELTA,
LKP_MEMBER_TRANS.DATE_BILLED as DATE_BILLED_MTLKP,
LKP_MEMBER_TRANS.DATE_PAID as DATE_PAID_MT_LKP,
LKP_MEMBER_TRANS.DATE_CANCELLED as DATE_CANCELLED_LKP,
m_lkp_Control_Tables.mplt_BATCH_ID as mplt_BATCH_ID,
m_lkp_Control_Tables.mplt_PRGM_ID as mplt_PRGM_ID,
m_lkp_Control_Tables.mplt_TABLE_ID as mplt_TABLE_ID,
m_lkp_Control_Tables.mplt_PROJ_ID as mplt_PROJ_ID,
exp_Source.GW_BILL_REF as GW_BILL_REF_SRC,
exp_Source.out_GW_DUE_DATE as GW_DUE_DATE_SRC,
exp_Source.COMB_BILL_IND as COMB_BILL_IND_SRC,
exp_Source.ALLOW_COMBINED_BILLING as ALLOW_COMBINED_BILLING_SRC,
exp_Source.FOUR_DAY_LTR_IND as FOUR_DAY_LTR_IND_SRC,
exp_Source.source_record_id
FROM
exp_Source
LEFT JOIN m_validate_date_DC ON exp_Source.source_record_id = m_validate_date_DC.source_record_id
LEFT JOIN LKP_MEMBER_TRANS ON m_validate_date_DC.source_record_id = LKP_MEMBER_TRANS.source_record_id
LEFT JOIN m_validate_date_DP ON LKP_MEMBER_TRANS.source_record_id = m_validate_date_DP.source_record_id
LEFT JOIN m_lkp_Control_Tables ON m_validate_date_DP.source_record_id = m_lkp_Control_Tables.source_record_id
LEFT JOIN m_validate_date_DB ON m_lkp_Control_Tables.source_record_id = m_validate_date_DB.source_record_id
WHERE CASE WHEN LKP_MEMBER_TRANS.MEMB_SKEY IS NULL or ( exp_Source.TX_CD = ''UPD'' and ( LKP_MEMBER_TRANS.MEMB_TYPE != exp_Source.FED_TYPE or ltrim ( rTrim ( LKP_MEMBER_TRANS.COMMODITY ) ) != ltrim ( rTrim ( exp_Source.COMMODITY ) ) or LKP_MEMBER_TRANS.COUNTY_CD != exp_Source.COUNTY or LKP_MEMBER_TRANS.STATUS_CD != exp_Source.STATUS or LKP_MEMBER_TRANS.AMT_PAID != exp_Source.AMOUNT_PAID or LKP_MEMBER_TRANS.PAID_TO_DT != exp_Source.out_PAID_TO_DATE or LKP_MEMBER_TRANS.COUNTY_PAID_DT != exp_Source.out_COPAY_DATE or LKP_MEMBER_TRANS.FED_SRC != exp_Source.FED_SOURCE or LKP_MEMBER_TRANS.OUT_OF_STATE != exp_Source.OUT_OF_STATE or LKP_MEMBER_TRANS.COUNTY_CHG_IND != exp_Source.COUNTY_CHG_IND or ( CASE WHEN LKP_MEMBER_TRANS.GW_BILL_REF IS NULL THEN ''~'' ELSE LKP_MEMBER_TRANS.GW_BILL_REF END ) <> ( CASE WHEN exp_Source.GW_BILL_REF IS NULL THEN ''~'' ELSE exp_Source.GW_BILL_REF END ) or ( CASE WHEN LKP_MEMBER_TRANS.GW_DUE_DATE IS NULL THEN to_date ( ''1900-01-01'' , ''YYYY-MM-DD'' ) ELSE LKP_MEMBER_TRANS.GW_DUE_DATE END ) <> ( CASE WHEN exp_Source.out_GW_DUE_DATE IS NULL THEN to_date ( ''1900-01-01'' , ''YYYY-MM-DD'' ) ELSE exp_Source.out_GW_DUE_DATE END ) or ( CASE WHEN LKP_MEMBER_TRANS.COMB_BILL_IND IS NULL THEN ''~'' ELSE LKP_MEMBER_TRANS.COMB_BILL_IND END ) <> ( CASE WHEN exp_Source.COMB_BILL_IND IS NULL THEN ''~'' ELSE exp_Source.COMB_BILL_IND END ) or ( CASE WHEN LKP_MEMBER_TRANS.ALLOW_COMBINED_BILLING IS NULL THEN ''~'' ELSE LKP_MEMBER_TRANS.ALLOW_COMBINED_BILLING END ) <> ( CASE WHEN exp_Source.ALLOW_COMBINED_BILLING IS NULL THEN ''~'' ELSE exp_Source.ALLOW_COMBINED_BILLING END ) or ( CASE WHEN LKP_MEMBER_TRANS.FOUR_DAY_LTR_IND IS NULL THEN ''~'' ELSE LKP_MEMBER_TRANS.FOUR_DAY_LTR_IND END ) <> ( CASE WHEN exp_Source.FOUR_DAY_LTR_IND IS NULL THEN ''~'' ELSE exp_Source.FOUR_DAY_LTR_IND END ) ) ) THEN TRUE ELSE FALSE END 
-- CASE WHEN ( exp_Source.TX_CD = ''NEW'' or exp_Source.TX_CD = ''UPD'' ) and ( LKP_MEMBER_TRANS.MEMB_TYPE != exp_Source.FED_TYPE or LKP_MEMBER_TRANS.COMMODITY != exp_Source.COMMODITY or LKP_MEMBER_TRANS.COUNTY_CD != exp_Source.COUNTY or LKP_MEMBER_TRANS.STATUS_CD != exp_Source.STATUS or LKP_MEMBER_TRANS.AMT_PAID != exp_Source.AMOUNT_PAID or LKP_MEMBER_TRANS.PAID_TO_DT != exp_Source.out_PAID_TO_DATE or LKP_MEMBER_TRANS.COUNTY_PAID_DT != exp_Source.out_COPAY_DATE or LKP_MEMBER_TRANS.FED_SRC != exp_Source.FED_SOURCE or LKP_MEMBER_TRANS.OUT_OF_STATE != exp_Source.OUT_OF_STATE or LKP_MEMBER_TRANS.COUNTY_CHG_IND != exp_Source.COUNTY_CHG_IND ) THEN TRUE ELSE FALSE END 
-- CASE WHEN exp_Source.TX_CD = ''NEW'' or ( exp_Source.TX_CD = ''UPD'' and ( LKP_MEMBER_TRANS.MEMB_TYPE != exp_Source.FED_TYPE or LKP_MEMBER_TRANS.COMMODITY != exp_Source.COMMODITY or LKP_MEMBER_TRANS.COUNTY_CD != exp_Source.COUNTY or LKP_MEMBER_TRANS.STATUS_CD != exp_Source.STATUS or LKP_MEMBER_TRANS.AMT_PAID != exp_Source.AMOUNT_PAID or LKP_MEMBER_TRANS.PAID_TO_DT != exp_Source.out_PAID_TO_DATE or LKP_MEMBER_TRANS.COUNTY_PAID_DT != exp_Source.out_COPAY_DATE or LKP_MEMBER_TRANS.FED_SRC != exp_Source.FED_SOURCE or LKP_MEMBER_TRANS.OUT_OF_STATE != exp_Source.OUT_OF_STATE or LKP_MEMBER_TRANS.COUNTY_CHG_IND != exp_Source.COUNTY_CHG_IND ) ) THEN TRUE ELSE FALSE END
;


-- Component rtr_Member_Trans_UPD, Type ROUTER Output Group UPD
create or replace temp table rtr_Member_Trans_UPD as
SELECT
LKP_MEMBER_TRANS.MEMB_SKEY as MEMB_SKEY_MTLKP,
LKP_MEMBER_TRANS.CHG_EFF_DT as CHG_EFF_DT_MTLKP,
LKP_MEMBER_TRANS.MEMB_TYPE as MEMB_TYPE_MTLKP,
LKP_MEMBER_TRANS.COMMODITY as COMMODITY_MTLKP,
LKP_MEMBER_TRANS.COMM_CD1 as COMM_CD1_MTLKP,
LKP_MEMBER_TRANS.COMM_CD2 as COMM_CD2_MTLKP,
LKP_MEMBER_TRANS.COMM_CD3 as COMM_CD3_MTLKP,
LKP_MEMBER_TRANS.COUNTY_CD as COUNTY_CD_MTLKP,
LKP_MEMBER_TRANS.STATUS_CD as STATUS_CD_MTLKP,
LKP_MEMBER_TRANS.AMT_PAID as AMT_PAID_MTLKP,
LKP_MEMBER_TRANS.PAID_TO_DT as PAID_TO_DT_MTLKP,
LKP_MEMBER_TRANS.COUNTY_PAID_DT as COUNTY_PAID_DT_MTLKP,
LKP_MEMBER_TRANS.FED_SRC as FED_SRC_MTLKP,
LKP_MEMBER_TRANS.OUT_OF_STATE as OUT_OF_STATE_MTLKP,
LKP_MEMBER_TRANS.COUNTY_CHG_IND as COUNTY_CHG_IND_MTLKP,
LKP_MEMBER_TRANS.PREV_STATUS_CD as PREV_STATUS_CD_MTLKP,
LKP_MEMBER_TRANS.GW_BILL_REF as GW_BILL_REF_MTLKP,
LKP_MEMBER_TRANS.GW_DUE_DATE as GW_DUE_DATE_MTLKP,
LKP_MEMBER_TRANS.COMB_BILL_IND as COMB_BILL_IND_MTLKP,
LKP_MEMBER_TRANS.ALLOW_COMBINED_BILLING as ALLOW_COMBINED_BILLING_MTLKP,
LKP_MEMBER_TRANS.FOUR_DAY_LTR_IND as FOUR_DAY_LTR_IND_MTLKP,
exp_Source.MEMB_SKEY as MEMB_SKEY_SRC,
exp_Source.FED_TYPE as FED_TYPE_SRC,
exp_Source.COMMODITY as COMMODITY_SRC,
exp_Source.COUNTY as COUNTY_SRC,
exp_Source.STATUS as STATUS_SRC,
exp_Source.AMOUNT_PAID as AMOUNT_PAID_SRC,
exp_Source.out_PAID_TO_DATE as PAID_TO_DATE_SRC,
exp_Source.out_COPAY_DATE as COPAY_DATE_SRC,
exp_Source.FED_SOURCE as FED_SOURCE_SRC,
exp_Source.OUT_OF_STATE as OUT_OF_STATE_SRC,
exp_Source.COUNTY_CHG_IND as COUNTY_CHG_IND_SRC,
exp_Source.TX_CD as TX_CD,
exp_Source.out_CHG_EFF_DT as CHG_EFF_DT,
exp_Source.FEED_IND as FEED_IND,
m_validate_date_DB.out_DATE_DT as DATE_BILLED_DELTA,
m_validate_date_DP.out_DATE_DT as DATE_PAID_DELTA,
m_validate_date_DC.out_DATE_DT as DATE_CANCELLED_DELTA,
LKP_MEMBER_TRANS.DATE_BILLED as DATE_BILLED_MTLKP,
LKP_MEMBER_TRANS.DATE_PAID as DATE_PAID_MT_LKP,
LKP_MEMBER_TRANS.DATE_CANCELLED as DATE_CANCELLED_LKP,
m_lkp_Control_Tables.mplt_BATCH_ID as mplt_BATCH_ID,
m_lkp_Control_Tables.mplt_PRGM_ID as mplt_PRGM_ID,
m_lkp_Control_Tables.mplt_TABLE_ID as mplt_TABLE_ID,
m_lkp_Control_Tables.mplt_PROJ_ID as mplt_PROJ_ID,
exp_Source.GW_BILL_REF as GW_BILL_REF_SRC,
exp_Source.out_GW_DUE_DATE as GW_DUE_DATE_SRC,
exp_Source.COMB_BILL_IND as COMB_BILL_IND_SRC,
exp_Source.ALLOW_COMBINED_BILLING as ALLOW_COMBINED_BILLING_SRC,
exp_Source.FOUR_DAY_LTR_IND as FOUR_DAY_LTR_IND_SRC,
exp_Source.source_record_id
FROM
exp_Source
LEFT JOIN m_validate_date_DC ON exp_Source.source_record_id = m_validate_date_DC.source_record_id
LEFT JOIN LKP_MEMBER_TRANS ON m_validate_date_DC.source_record_id = LKP_MEMBER_TRANS.source_record_id
LEFT JOIN m_validate_date_DP ON LKP_MEMBER_TRANS.source_record_id = m_validate_date_DP.source_record_id
LEFT JOIN m_lkp_Control_Tables ON m_validate_date_DP.source_record_id = m_lkp_Control_Tables.source_record_id
LEFT JOIN m_validate_date_DB ON m_lkp_Control_Tables.source_record_id = m_validate_date_DB.source_record_id
WHERE CASE WHEN exp_Source.TX_CD = ''UPD'' and ( LKP_MEMBER_TRANS.MEMB_TYPE != exp_Source.FED_TYPE or ltrim ( rtrim ( LKP_MEMBER_TRANS.COMMODITY ) ) != ltrim ( rtrim ( exp_Source.COMMODITY ) ) or LKP_MEMBER_TRANS.COUNTY_CD != exp_Source.COUNTY or LKP_MEMBER_TRANS.STATUS_CD != exp_Source.STATUS or LKP_MEMBER_TRANS.AMT_PAID != exp_Source.AMOUNT_PAID or LKP_MEMBER_TRANS.PAID_TO_DT != exp_Source.out_PAID_TO_DATE or LKP_MEMBER_TRANS.COUNTY_PAID_DT != exp_Source.out_COPAY_DATE or LKP_MEMBER_TRANS.FED_SRC != exp_Source.FED_SOURCE or LKP_MEMBER_TRANS.OUT_OF_STATE != exp_Source.OUT_OF_STATE or LKP_MEMBER_TRANS.COUNTY_CHG_IND != exp_Source.COUNTY_CHG_IND or ( CASE WHEN LKP_MEMBER_TRANS.GW_BILL_REF IS NULL THEN ''~'' ELSE LKP_MEMBER_TRANS.GW_BILL_REF END ) <> ( CASE WHEN exp_Source.GW_BILL_REF IS NULL THEN ''~'' ELSE exp_Source.GW_BILL_REF END ) or ( CASE WHEN LKP_MEMBER_TRANS.GW_DUE_DATE IS NULL THEN to_date ( ''1900-01-01'' , ''YYYY-MM-DD'' ) ELSE LKP_MEMBER_TRANS.GW_DUE_DATE END ) <> ( CASE WHEN exp_Source.out_GW_DUE_DATE IS NULL THEN to_date ( ''1900-01-01'' , ''YYYY-MM-DD'' ) ELSE exp_Source.out_GW_DUE_DATE END ) or ( CASE WHEN LKP_MEMBER_TRANS.COMB_BILL_IND IS NULL THEN ''~'' ELSE LKP_MEMBER_TRANS.COMB_BILL_IND END ) <> ( CASE WHEN exp_Source.COMB_BILL_IND IS NULL THEN ''~'' ELSE exp_Source.COMB_BILL_IND END ) or ( CASE WHEN LKP_MEMBER_TRANS.ALLOW_COMBINED_BILLING IS NULL THEN ''~'' ELSE LKP_MEMBER_TRANS.ALLOW_COMBINED_BILLING END ) <> ( CASE WHEN exp_Source.ALLOW_COMBINED_BILLING IS NULL THEN ''~'' ELSE exp_Source.ALLOW_COMBINED_BILLING END ) or ( CASE WHEN LKP_MEMBER_TRANS.FOUR_DAY_LTR_IND IS NULL THEN ''~'' ELSE LKP_MEMBER_TRANS.FOUR_DAY_LTR_IND END ) <> ( CASE WHEN exp_Source.FOUR_DAY_LTR_IND IS NULL THEN ''~'' ELSE exp_Source.FOUR_DAY_LTR_IND END ) ) THEN TRUE ELSE FALSE END;


-- Component upd_Expire_Trans, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_Expire_Trans AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
rtr_Member_Trans_UPD.MEMB_SKEY_MTLKP as MEMB_SKEY,
rtr_Member_Trans_UPD.CHG_EFF_DT_MTLKP as CHG_EFF_DT,
rtr_Member_Trans_UPD.CHG_EFF_DT as CHG_EXP_DT,
rtr_Member_Trans_UPD.mplt_BATCH_ID as UPD_BATCH_ID,
rtr_Member_Trans_UPD.mplt_PRGM_ID as UPD_PRGM_ID,
rtr_Member_Trans_UPD.source_record_id as source_record_id,
1 as UPDATE_STRATEGY_ACTION
FROM
rtr_Member_Trans_UPD
);


-- Component exp_Expire_Member_Trans, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Expire_Member_Trans AS
(
SELECT
upd_Expire_Trans.MEMB_SKEY as MEMB_SKEY,
upd_Expire_Trans.CHG_EFF_DT as CHG_EFF_DT,
DATEADD (''d'', -1, upd_Expire_Trans.CHG_EXP_DT) as out_CHG_EXP_DT,
upd_Expire_Trans.UPD_BATCH_ID as UPD_BATCH_ID,
upd_Expire_Trans.UPD_PRGM_ID as UPD_PRGM_ID,
upd_Expire_Trans.source_record_id
FROM
upd_Expire_Trans
);


-- Component exp_INS_Member_Trans, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_INS_Member_Trans AS
(
SELECT
rtr_Member_Trans_NEW.MEMB_SKEY_SRC as MEMB_SKEY,
rtr_Member_Trans_NEW.CHG_EFF_DT as CHG_EFF_DT,
to_date ( ''99991231'' , ''YYYYMMDD'' ) as out_CHG_EXP_DT,
rtr_Member_Trans_NEW.FED_TYPE_SRC as FED_TYPE,
ltrim ( rtrim ( substr ( rtr_Member_Trans_NEW.COMMODITY_SRC , 1 , 1 ) ) ) as COMM_CD1,
ltrim ( rtrim ( substr ( rtr_Member_Trans_NEW.COMMODITY_SRC , 2 , 1 ) ) ) as COMM_CD2,
ltrim ( rtrim ( substr ( rtr_Member_Trans_NEW.COMMODITY_SRC , 3 , 1 ) ) ) as COMM_CD3,
rtr_Member_Trans_NEW.COUNTY_SRC as COUNTY,
rtr_Member_Trans_NEW.STATUS_SRC as STATUS,
CASE WHEN rtr_Member_Trans_NEW.TX_CD = ''UPD'' and rtr_Member_Trans_NEW.STATUS_CD_MTLKP != rtr_Member_Trans_NEW.STATUS_SRC THEN rtr_Member_Trans_NEW.STATUS_CD_MTLKP ELSE rtr_Member_Trans_NEW.PREV_STATUS_CD_MTLKP END as out_PREV_STATUS,
rtr_Member_Trans_NEW.AMOUNT_PAID_SRC as AMOUNT_PAID,
rtr_Member_Trans_NEW.PAID_TO_DATE_SRC as PAID_TO_DATE,
rtr_Member_Trans_NEW.COPAY_DATE_SRC as COPAY_DATE,
CASE WHEN ltrim ( rtrim ( rtr_Member_Trans_NEW.FED_SOURCE_SRC ) ) IS NULL THEN null ELSE ltrim ( rtrim ( rtr_Member_Trans_NEW.FED_SOURCE_SRC ) ) END as out_FED_SOURCE,
CASE WHEN ltrim ( rtrim ( rtr_Member_Trans_NEW.OUT_OF_STATE_SRC ) ) IS NULL THEN null ELSE ltrim ( rtrim ( rtr_Member_Trans_NEW.OUT_OF_STATE_SRC ) ) END as out_OUT_OF_STATE,
CASE WHEN ltrim ( rtrim ( rtr_Member_Trans_NEW.COUNTY_CHG_IND_SRC ) ) IS NULL THEN null ELSE ltrim ( rtrim ( rtr_Member_Trans_NEW.COUNTY_CHG_IND_SRC ) ) END as out_COUNTY_CHG_IND,
rtr_Member_Trans_NEW.mplt_BATCH_ID as INS_BATCH_ID,
rtr_Member_Trans_NEW.mplt_PRGM_ID as INS_PRGM_ID,
CASE WHEN rtr_Member_Trans_NEW.FEED_IND != ''D'' THEN CASE WHEN ( rtr_Member_Trans_NEW.DATE_BILLED_MTLKP IS NULL or rtr_Member_Trans_NEW.DATE_BILLED_DELTA > rtr_Member_Trans_NEW.DATE_BILLED_MTLKP ) THEN rtr_Member_Trans_NEW.DATE_BILLED_DELTA ELSE rtr_Member_Trans_NEW.DATE_BILLED_MTLKP END ELSE CASE WHEN rtr_Member_Trans_NEW.FEED_IND = ''D'' and rtr_Member_Trans_NEW.STATUS_CD_MTLKP = 0 and rtr_Member_Trans_NEW.STATUS_SRC = 1 THEN rtr_Member_Trans_NEW.DATE_BILLED_DELTA ELSE rtr_Member_Trans_NEW.DATE_BILLED_MTLKP END END as out_DATE_BILLED,
CASE WHEN rtr_Member_Trans_NEW.FEED_IND != ''D'' THEN CASE WHEN ( rtr_Member_Trans_NEW.DATE_CANCELLED_LKP IS NULL or rtr_Member_Trans_NEW.DATE_CANCELLED_DELTA > rtr_Member_Trans_NEW.DATE_CANCELLED_LKP ) THEN rtr_Member_Trans_NEW.DATE_CANCELLED_DELTA ELSE rtr_Member_Trans_NEW.DATE_CANCELLED_LKP END ELSE CASE WHEN rtr_Member_Trans_NEW.FEED_IND = ''D'' and rtr_Member_Trans_NEW.STATUS_CD_MTLKP != 3 and rtr_Member_Trans_NEW.STATUS_SRC = 3 THEN rtr_Member_Trans_NEW.DATE_CANCELLED_DELTA ELSE rtr_Member_Trans_NEW.DATE_CANCELLED_LKP END END as out_DATE_CANCELLED,
CASE WHEN rtr_Member_Trans_NEW.FEED_IND != ''D'' THEN CASE WHEN ( rtr_Member_Trans_NEW.DATE_PAID_MT_LKP IS NULL or rtr_Member_Trans_NEW.DATE_PAID_DELTA > rtr_Member_Trans_NEW.DATE_PAID_MT_LKP ) THEN rtr_Member_Trans_NEW.DATE_PAID_DELTA ELSE rtr_Member_Trans_NEW.DATE_PAID_MT_LKP END ELSE CASE WHEN rtr_Member_Trans_NEW.FEED_IND = ''D'' and ( rtr_Member_Trans_NEW.STATUS_SRC = 9 or rtr_Member_Trans_NEW.STATUS_SRC = 0 ) and ltrim ( rtrim ( rtr_Member_Trans_NEW.COMMODITY_SRC ) ) != ''XXY'' and rtr_Member_Trans_NEW.PAID_TO_DATE_SRC > rtr_Member_Trans_NEW.PAID_TO_DT_MTLKP THEN rtr_Member_Trans_NEW.DATE_PAID_DELTA ELSE rtr_Member_Trans_NEW.DATE_PAID_MT_LKP END END as out_DATE_PAID,
rtr_Member_Trans_NEW.GW_BILL_REF_SRC as GW_BILL_REF_SRC1,
rtr_Member_Trans_NEW.GW_DUE_DATE_SRC as GW_DUE_DATE_SRC1,
rtr_Member_Trans_NEW.COMB_BILL_IND_SRC as COMB_BILL_IND_SRC1,
rtr_Member_Trans_NEW.ALLOW_COMBINED_BILLING_SRC as ALLOW_COMBINED_BILLING_SRC1,
rtr_Member_Trans_NEW.FOUR_DAY_LTR_IND_SRC as FOUR_DAY_LTR_IND_SRC1,
rtr_Member_Trans_NEW.source_record_id
FROM
rtr_Member_Trans_NEW
WHERE MEMB_SKEY IS NOT NULL
);


-- Component MEMBER_TRANS_UPD, Type TARGET 
MERGE INTO DB_T_CORE_PROD.MEMBER_TRANS
USING exp_Expire_Member_Trans ON (MEMBER_TRANS.MEMB_SKEY = exp_Expire_Member_Trans.MEMB_SKEY AND MEMBER_TRANS.CHG_EFF_DT = exp_Expire_Member_Trans.CHG_EFF_DT)
WHEN MATCHED THEN UPDATE
SET
MEMB_SKEY = exp_Expire_Member_Trans.MEMB_SKEY,
CHG_EFF_DT = exp_Expire_Member_Trans.CHG_EFF_DT,
CHG_EXP_DT = exp_Expire_Member_Trans.out_CHG_EXP_DT,
ECTL_UPD_BATCH_ID = exp_Expire_Member_Trans.UPD_BATCH_ID,
ECTL_UPD_PRGM_ID = exp_Expire_Member_Trans.UPD_PRGM_ID;


-- Component MEMBER_TRANS_INS, Type TARGET 
INSERT INTO DB_T_CORE_PROD.MEMBER_TRANS
(
MEMB_SKEY,
CHG_EFF_DT,
CHG_EXP_DT,
MEMB_TYPE,
COMM_CD1,
COMM_CD2,
COMM_CD3,
COUNTY_CD,
STATUS_CD,
AMT_PAID,
PAID_TO_DT,
COUNTY_PAID_DT,
FED_SRC,
OUT_OF_STATE,
COUNTY_CHG_IND,
PREV_STATUS_CD,
DATE_BILLED,
DATE_PAID,
DATE_CANCELLED,
ECTL_INS_BATCH_ID,
ECTL_INS_PRGM_ID,
GW_BILL_REF,
GW_DUE_DATE,
COMB_BILL_IND,
ALLOW_COMBINED_BILLING,
FOUR_DAY_LTR_IND
)
SELECT
exp_INS_Member_Trans.MEMB_SKEY as MEMB_SKEY,
exp_INS_Member_Trans.CHG_EFF_DT as CHG_EFF_DT,
exp_INS_Member_Trans.out_CHG_EXP_DT as CHG_EXP_DT,
exp_INS_Member_Trans.FED_TYPE as MEMB_TYPE,
exp_INS_Member_Trans.COMM_CD1 as COMM_CD1,
exp_INS_Member_Trans.COMM_CD2 as COMM_CD2,
exp_INS_Member_Trans.COMM_CD3 as COMM_CD3,
exp_INS_Member_Trans.COUNTY as COUNTY_CD,
exp_INS_Member_Trans.STATUS as STATUS_CD,
exp_INS_Member_Trans.AMOUNT_PAID as AMT_PAID,
exp_INS_Member_Trans.PAID_TO_DATE as PAID_TO_DT,
exp_INS_Member_Trans.COPAY_DATE as COUNTY_PAID_DT,
exp_INS_Member_Trans.out_FED_SOURCE as FED_SRC,
exp_INS_Member_Trans.out_OUT_OF_STATE as OUT_OF_STATE,
exp_INS_Member_Trans.out_COUNTY_CHG_IND as COUNTY_CHG_IND,
exp_INS_Member_Trans.out_PREV_STATUS as PREV_STATUS_CD,
exp_INS_Member_Trans.out_DATE_BILLED as DATE_BILLED,
exp_INS_Member_Trans.out_DATE_PAID as DATE_PAID,
exp_INS_Member_Trans.out_DATE_CANCELLED as DATE_CANCELLED,
exp_INS_Member_Trans.INS_BATCH_ID as ECTL_INS_BATCH_ID,
exp_INS_Member_Trans.INS_PRGM_ID as ECTL_INS_PRGM_ID,
exp_INS_Member_Trans.GW_BILL_REF_SRC1 as GW_BILL_REF,
exp_INS_Member_Trans.GW_DUE_DATE_SRC1 as GW_DUE_DATE,
exp_INS_Member_Trans.COMB_BILL_IND_SRC1 as COMB_BILL_IND,
exp_INS_Member_Trans.ALLOW_COMBINED_BILLING_SRC1 as ALLOW_COMBINED_BILLING,
exp_INS_Member_Trans.FOUR_DAY_LTR_IND_SRC1 as FOUR_DAY_LTR_IND
FROM
exp_INS_Member_Trans;


END; ';