-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BIBASE_F_AGNT_PERFC_SUMRY("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE
  CAL_END_MTH_ID STRING;
  cal_end_dt STRING;
  run_id STRING;
  workflow_name STRING;
  session_name STRING;
BEGIN
  run_id := public.func_get_scoped_param(:run_id, ''run_id'', :workflow_name, :worklet_name, :session_name);
  workflow_name := public.func_get_scoped_param(:run_id, ''workflow_name'', :workflow_name, :worklet_name, :session_name);
  session_name := public.func_get_scoped_param(:run_id, ''session_name'', :workflow_name, :worklet_name, :session_name);
 
  CAL_END_MTH_ID := public.func_get_scoped_param(:run_id, ''CAL_END_MTH_ID'', :workflow_name, :worklet_name, :session_name);
  cal_end_dt := public.func_get_scoped_param(:run_id, ''cal_end_dt'', :workflow_name, :worklet_name, :session_name);

-- Component F_AGNT_PERFC_SUMRY, Type Pre SQL 
DELETE FROM db_v_prod_pres.F_AGNT_PERFC_SUMRY WHERE MO_ID=:CAL_END_MTH_ID;


-- Component sq_AGMT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_AGMT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as PRODUCER_ID,
$2 as MO_ID,
$3 as PROD_TYPE_CD,
$4 as NEW_BUSN_CNT,
$5 as QUOTES_CNT,
$6 as PYR_INFORCE_PLCY_CNT,
$7 as PRSISTNT_PLCY_CNT,
$8 as INFORCE_PLCY_CNT,
$9 as LOSS_1_YR_AMT,
$10 as EARND_PREM_1_YR_AMT,
$11 as RPTD_LOSS,
$12 as EARND_PREM,
$13 as LOSS_YTD_AMT,
$14 as EARND_PREM_YTD_AMT,
$15 as INCTV_PREM_AMT,
$16 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT  

cast(case when (to_varchar(COALESCE(A.AGNT_NBR,B.AGENT_NBR,C.AGNT_NBR,D.AGNT_NBR,0)) =''unk'') then 0 else   COALESCE(A.AGNT_NBR,B.AGENT_NBR,C.AGNT_NBR,D.AGNT_NBR,0) end as integer) AGNT_NBR,

COALESCE(A.MO_ID,B.MO_ID,C.MO_ID,D.MO_ID)MO_ID,

COALESCE(A.LOB_CD,B.LOB_CD,C.LOB_CD, D.LOB_CD) LOB_CD,

SUM(COALESCE(NEW_BUSN_CNT,0)) NEW_BUSN_CNT,

SUM(COALESCE(QUOTES_CNT,0))QUOTES_CNT ,

SUM(COALESCE(PYR_INFORCE_PLCY_CNT,0)) PYR_INFORCE_PLCY_CNT,

SUM(COALESCE(PRSISTNT_PLCY_CNT,0)) PRSISTNT_PLCY_CNT,

SUM(COALESCE(INFORCE_PLCY_CNT,0)) INFORCE_PLCY_CNT,

SUM(COALESCE(TOTAL_PAID_LOSS_AMT_NO_CAT_1YR_AMT,0)) TOTAL_PAID_LOSS_AMT_NO_CAT_1YR_AMT,

SUM(COALESCE(TOTAL_ERN_PREM_1YR_AMT,0))TOTAL_ERN_PREM_1YR_AMT,

SUM(COALESCE(RPTD_LOSS,0)) RPTD_LOSS,

SUM(COALESCE(EARND_PREM,0)) EARND_PREM,

SUM(COALESCE(TOTAL_PAID_LOSS_AMT_NO_CAT_YTD_AMT,0)) TOTAL_PAID_LOSS_AMT_NO_CAT_YTD_AMT,

SUM(COALESCE(TOTAL_ERN_PREM_YTD_AMT,0)) TOTAL_ERN_PREM_YTD_AMT,

SUM(COALESCE(BOOK_SIZE_PREMIUM,0))COMMISION

FROM 

/*CURRENT YR QUOTE,NEW BUSI, PREVIOUS INFORCE COUNT*/

(select :CAL_END_MTH_ID MO_ID, LOB_CD,AGNT_NBR, SUM(NEW_QUOT_CNT) QUOTES_CNT, SUM(NEW_BND_CNT) NEW_BUSN_CNT, SUM(PYR_INFRC_PLCY_CNT)PYR_INFORCE_PLCY_CNT,

SUM(PRSISTNT_PLCY_CNT)  PRSISTNT_PLCY_CNT

 from DB_V_PROD_PRES.WR_AGNT_SUMRY

WHERE LOB_CD IN (''PA'',''HO'')  AND CAL_DT=:cal_end_dt GROUP BY 1,2,3  )A

/*CURRENT INFORCE*/

FULL OUTER JOIN

(SELECT :CAL_END_MTH_ID MO_ID,LOB_CD, AGENT_NBR, SUM(PLCY_CNT_END_IFO) INFORCE_PLCY_CNT FROM DB_V_PROD_ACT.WR_MULTILINE_METRICS_SUMRY WHERE CALENDAR_DATE=:cal_end_dt

AND LOB_CD IN (''PA'',''HO'') GROUP BY 1,2,3)B

ON A.MO_ID=B.MO_ID AND

A.AGNT_NBR=B.AGENT_NBR AND

A.LOB_CD=B.LOB_CD

/*LOSS RATIO*/

FULL OUTER JOIN

(SELECT :CAL_END_MTH_ID mo_id  , LOB_CD,AGNT_NBR,

SUM(CASE WHEN (cal_dt BETWEEN  ADD_MONTHS(:cal_end_dt ,-11) aND  cast(:cal_end_dt as date))

THEN ERND_PREM ELSE 0 END)TOTAL_ERN_PREM_1YR_AMT,

SUM(CASE WHEN (cal_dt BETWEEN ADD_MONTHS(:cal_end_dt ,-11) aND  cast(:cal_end_dt as date))

THEN RPTD_LOSS_NONCAT ELSE 0 END)TOTAL_PAID_LOSS_AMT_NO_CAT_1YR_AMT,

SUM(CASE WHEN CAL_DT=:cal_end_dt AND B.MO_ID=:CAL_END_MTH_ID  THEN ERND_PREM ELSE 0 END) AS EARND_PREM, /* EIM-35454 */
SUM(CASE WHEN CAL_DT=:cal_end_dt AND B.MO_ID=:CAL_END_MTH_ID  THEN RPTD_LOSS_NONCAT ELSE 0 END) AS RPTD_LOSS,/* EIM-35454 */
SUM(CASE WHEN (cal_dt  BETWEEN add_months(cast(:cal_end_dt as date), -extract(MONTH , cast(:cal_end_dt as date))+1) AND  cast(:cal_end_dt as date))

THEN ERND_PREM ELSE 0 END)TOTAL_ERN_PREM_YTD_AMT,

SUM(CASE WHEN (cal_dt BETWEEN add_months(cast(:cal_end_dt as date), -extract(MONTH , cast(:cal_end_dt as date))+1) AND  cast(:cal_end_dt as date))

THEN RPTD_LOSS_NONCAT ELSE 0 END)TOTAL_PAID_LOSS_AMT_NO_CAT_YTD_AMT

 FROM DB_T_PROD_STAG.F_FIN_PREM_LOSS_MTHLY A JOIN 

DB_T_PROD_STAG.D_FIN_PREM_LOSS_MTHLY B ON A.DIM_SKEY=B.DIM_SKEY

WHERE LOB_CD IN (''PA'',''HO'') AND cal_dt BETWEEN    ADD_MONTHS(cast(:cal_end_dt as date),-35) AND  cast(:cal_end_dt as date)

 and a.SRC_TYPE_CD in (''PS'', ''GW'', ''ADB'',		''MAN-OTH'', ''BULK-OTH'') 	and	b.ST_CD in (''AL'', ''GA'', ''MS'') 

GROUP BY 1,2,3)C ON

B.MO_iD=C.MO_ID AND

B.AGENT_NBR=C.AGNT_NBR AND

B.LOB_CD=C.LOB_CD

/*book size*/

FULL OUTER JOIN

(SELECT MO_ID, LOB_TYPE LOB_CD,AGENT AGNT_NBR, SUM(BOOK_SIZE_PREMIUM) BOOK_SIZE_PREMIUM FROM (

SELECT :CAL_END_MTH_ID MO_ID, CAST(''PA'' AS VARCHAR(20)) LOB_TYPE,AGENT_NBR AGENT, SUM(BOOK_SIZE_AUTO) BOOK_SIZE_PREMIUM 
from DB_V_PROD_PRES.wr_book_size where calendar_date =:cal_end_dt 
GROUP BY 1,2,3

UNION

SELECT :CAL_END_MTH_ID MO_ID,''HO''  LOB_TYPE, CAST(  PC_AGENT AS VARCHAR(10)) AGENT, SUM(HO_TOT_PREM) BOOK_SIZE_PREMIUM --DB_T_CORE_MEMBXREF_PROD.BOOK_SIZE  
FROM DB_T_CORE_MEMBXREF_PROD.HOMEPOLS A 

WHERE  CAST(:cal_end_dt AS DATE) BETWEEN CHG_EFF_DT AND CHG_EXP_DT AND PC_STATUS NOT IN (''5'',''6'')

GROUP BY MO_ID, LOB_TYPE,  AGENT

UNION

SELECT

:CAL_END_MTH_ID AS CAL_MO_ID,INSRNC_LOB_TYPE_CD,
ltrim( INTRNL_ORG_NUM, ''0'') AS AGENT_NBR

,SUM (COALESCE(INFORCE.PLCY_AMT,0) ) AS BOOK_SIZE_HO

FROM (

SELECT  INTRNL_ORG_NUM, INSRNC_LOB_TYPE_CD,AG.AGMT_ID,AGMT_TYPE_CD,AG.SRC_SYS_CD

FROM DB_T_PROD_CORE.AGMT AG

/* FOR AGENT	 */
	LEFT OUTER JOIN  DB_T_PROD_CORE.PRTY_AGMT PA13 ON AG.AGMT_ID = PA13.AGMT_ID AND PA13.PRTY_AGMT_ROLE_CD =''PRDA'' 

		LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG IO1 ON IO1.INTRNL_ORG_PRTY_ID =PA13.PRTY_ID 

	AND :cal_end_dt::date BETWEEN  IO1.TRANS_STRT_DTTM AND  IO1.TRANS_END_DTTM	

/* -FOR PRODUCT	 */
	LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_PROD AP1 ON AP1.AGMT_ID = AG.AGMT_ID

	LEFT OUTER JOIN DB_T_PROD_CORE.PROD PRO ON AP1.PROD_ID = PRO.PROD_ID

	QUALIFY ROW_NUMBER() OVER(PARTITION BY AG.AGMT_ID ORDER BY PA13.TRANS_END_DTTM DESC, AP1.EDW_END_DTTM DESC)=1)AG

/* FOR INFORCE AMOUNT */
LEFT OUTER  JOIN	(

	SELECT AG.AGMT_ID AS AGMT_ID ,:cal_end_dt::date AS DT ,AG.HOST_AGMT_NUM AS PLCY_NUM,PLCY_AMT,INSRNC_MTRC_TYPE_CD

	FROM

	(

	SELECT AG.AGMT_ID,AG.HOST_AGMT_NUM,AGMT_STS_CD,TERM_NUM,MODL_NUM,MODL_EFF_DTTM

	FROM 

	(SELECT * FROM DB_T_PROD_CORE.AGMT 
	WHERE CAST(MODL_EFF_DTTM AS DATE) <= :cal_end_dt::date
	QUALIFY RANK() OVER (PARTITION BY HOST_AGMT_NUM ORDER BY TERM_NUM DESC, MODL_NUM DESC) =1


	) AG

	JOIN (

	SELECT * FROM DB_T_PROD_CORE.AGMT_STS QUALIFY RANK() OVER (PARTITION BY AGMT_ID ORDER BY EDW_STRT_DTTM DESC) = 1 

	  ) AST ON AST.AGMT_ID = AG.AGMT_ID   AND AST.AGMT_STS_CD=''INFORCE''  

	  AND AGMT_TYPE_CD=''PPV''

	) AG 

	JOIN DB_T_PROD_CORE.PLCY_MTRC PM ON PM.AGMT_ID = AG.AGMT_ID  AND INSRNC_MTRC_TYPE_CD IN (''PREM'')

	GROUP BY 1,2    ,3,4,5

	) INFORCE             ON INFORCE.AGMT_ID =AG.AGMT_ID AND EXTRACT(MONTH , :cal_end_dt::date)  =  EXTRACT(MONTH , INFORCE.DT	)

	AND EXTRACT(YEAR , :cal_end_dt::date)  =  EXTRACT(YEAR , INFORCE.DT) 

WHERE AG.AGMT_TYPE_CD=''PPV''  AND AG.SRC_SYS_CD=''GWPC''

AND INSRNC_LOB_TYPE_CD IN (''HO'')

GROUP BY 1,2,3

) A GROUP BY 1,2,3)D ON

C.MO_iD=D.MO_ID AND

C.AGNT_NBR=D.AGNT_NBR AND

C.LOB_CD=D.LOB_CD

GROUP BY 1,2,3

HAVING sum(NEW_BUSN_CNT)<>0 OR sum( QUOTES_CNT)<>0 OR sum(PYR_INFORCE_PLCY_CNT)<>0 OR SUM(PRSISTNT_PLCY_CNT) <>0 OR sum( INFORCE_PLCY_CNT)<> 0 OR sum(TOTAL_PAID_LOSS_AMT_NO_CAT_1YR_AMT)<>0 OR 

sum(TOTAL_ERN_PREM_1YR_AMT)<> 0 OR sum(RPTD_LOSS) <> 0 OR sum(EARND_PREM)<> 0 OR  sum(TOTAL_PAID_LOSS_AMT_NO_CAT_YTD_AMT)<> 0 OR 

sum(TOTAL_ERN_PREM_YTD_AMT)<> 0 OR sum(BOOK_SIZE_PREMIUM)<>0
) SRC
)
);


-- Component exp_Passthrough, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Passthrough AS
(
SELECT
sq_AGMT.PRODUCER_ID as PRODUCER_ID,
sq_AGMT.MO_ID as MO_ID,
sq_AGMT.PROD_TYPE_CD as PROD_TYPE_CD,
sq_AGMT.NEW_BUSN_CNT as NEW_BUSN_CNT,
sq_AGMT.QUOTES_CNT as QUOTES_CNT,
sq_AGMT.PYR_INFORCE_PLCY_CNT as PYR_INFORCE_PLCY_CNT,
sq_AGMT.INFORCE_PLCY_CNT as INFORCE_PLCY_CNT,
sq_AGMT.LOSS_1_YR_AMT as LOSS_1_YR_AMT,
sq_AGMT.EARND_PREM_1_YR_AMT as EARND_PREM_1_YR_AMT,
sq_AGMT.RPTD_LOSS as RPTD_LOSS,
sq_AGMT.EARND_PREM as EARND_PREM,
sq_AGMT.LOSS_YTD_AMT as LOSS_YTD_AMT,
sq_AGMT.EARND_PREM_YTD_AMT as EARND_PREM_YTD_AMT,
sq_AGMT.INCTV_PREM_AMT as INCTV_PREM_AMT,
sq_AGMT.PRSISTNT_PLCY_CNT as PRSISTNT_PLCY_CNT,
sq_AGMT.source_record_id
FROM
sq_AGMT
);


-- Component F_AGNT_PERFC_SUMRY, Type TARGET 
INSERT INTO DB_V_PROD_PRES.F_AGNT_PERFC_SUMRY
(
PRODUCER_ID,
MO_ID,
PROD_TYPE_CD,
NEW_BUSN_CNT,
QUOTES_CNT,
PYR_INFORCE_PLCY_CNT,
PRSISTNT_PLCY_CNT,
INFORCE_PLCY_CNT,
LOSS_1_YR_AMT,
EARND_PREM_1_YR_AMT,
RPTD_LOSS,
EARND_PREM,
LOSS_YTD_AMT,
EARND_PREM_YTD_AMT,
INCTV_PREM_AMT
)
SELECT
exp_Passthrough.PRODUCER_ID as PRODUCER_ID,
exp_Passthrough.MO_ID as MO_ID,
exp_Passthrough.PROD_TYPE_CD as PROD_TYPE_CD,
exp_Passthrough.NEW_BUSN_CNT as NEW_BUSN_CNT,
exp_Passthrough.QUOTES_CNT as QUOTES_CNT,
exp_Passthrough.PYR_INFORCE_PLCY_CNT as PYR_INFORCE_PLCY_CNT,
exp_Passthrough.PRSISTNT_PLCY_CNT as PRSISTNT_PLCY_CNT,
exp_Passthrough.INFORCE_PLCY_CNT as INFORCE_PLCY_CNT,
exp_Passthrough.LOSS_1_YR_AMT as LOSS_1_YR_AMT,
exp_Passthrough.EARND_PREM_1_YR_AMT as EARND_PREM_1_YR_AMT,
exp_Passthrough.RPTD_LOSS as RPTD_LOSS,
exp_Passthrough.EARND_PREM as EARND_PREM,
exp_Passthrough.LOSS_YTD_AMT as LOSS_YTD_AMT,
exp_Passthrough.EARND_PREM_YTD_AMT as EARND_PREM_YTD_AMT,
exp_Passthrough.INCTV_PREM_AMT as INCTV_PREM_AMT
FROM
exp_Passthrough;


END; ';