-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BIBASE_F_AUTO_PLCY("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE
  CAL_END_DT STRING;
  CAL_END_MTH_ID STRING;
  run_id STRING;
  workflow_name STRING;
  session_name STRING;
BEGIN
  run_id := public.func_get_scoped_param(:run_id, ''run_id'', :workflow_name, :worklet_name, :session_name);
  workflow_name := public.func_get_scoped_param(:run_id, ''workflow_name'', :workflow_name, :worklet_name, :session_name);
  session_name := public.func_get_scoped_param(:run_id, ''session_name'', :workflow_name, :worklet_name, :session_name);

  CAL_END_DT := public.func_get_scoped_param(:run_id, ''cal_end_dt'', :workflow_name, :worklet_name, :session_name);
  CAL_END_MTH_ID := public.func_get_scoped_param(:run_id, ''cal_end_mth_id'', :workflow_name, :worklet_name, :session_name);
 

-- Component sq_AGMT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_AGMT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as PLCY_NUM,
$2 as MO_ID,
$3 as PRODUCER_ID,
$4 as BUSN_TYPE_CD,
$5 as INSRNC_SCR_AMT,
$6 as INSRNC_SCR_PLCY_CNT,
$7 as NMND_INSRD_AGE_AMT,
$8 as YRS_WTH_ALFA_AMT,
$9 as COMBO_CNT,
$10 as MULTICAR_CNT,
$11 as LIABTY_ONLY_CNT,
$12 as MIN_LMTS_CNT,
$13 as PREFD_CO_CNT,
$14 as DRVR_PNTS_CNT,
$15 as NO_PRIOR_INSRNC_CNT,
$16 as ASIC_PRIOR_INSRNC_CNT,
$17 as COMP_DEDCTB_0_CNT,
$18 as COMP_DEDCTB_500_LESS_CNT,
$19 as COMP_DEDCTB_500_CNT,
$20 as COMP_DEDCTB_1000_CNT,
$21 as COMP_DEDCTB_OTH_CNT,
$22 as TOT_COMP_DEDCTB_UNIT_CNT,
$23 as COLL_DEDCTB_0_CNT,
$24 as COLL_DEDCTB_500_LESS_CNT,
$25 as COLL_DEDCTB_500_CNT,
$26 as COLL_DEDCTB_1000_CNT,
$27 as COLL_DEDCTB_OTH_CNT,
$28 as TOT_COLL_DEDCTB_UNIT_CNT,
$29 as PLEASURE_USE_CNT,
$30 as COMMUTER_USE_CNT,
$31 as BUSN_USE_CNT,
$32 as FARM_USE_CNT,
$33 as COMRCL_USE_CNT,
$34 as SHRT_ANNUAL_MILEG_CNT,
$35 as TOT_VEH_USE_CNT,
$36 as AGE_26_49_CNT,
$37 as AGE_25_29_CNT,
$38 as AGE_75_PLUS_CNT,
$39 as YOUTHFUL_CNT,
$40 as TOT_RTD_DRVR_CNT,
$41 as TOT_VEH_CNT,
$42 as SRC_SYS_CD,
$43 as MED_PAY_CNT,
$44 as LOSS_OF_USE_CNT,
$45 as PROD_NAME,
$46 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT

AG.plcy_nbr AS PLCY_NUM

,:CAL_END_MTH_ID AS MO_ID

,COALESCE(AGNT_NUM ,0)AS PRODUCER_ID

 ,CASE WHEN (PREV.HOST_AGMT_NUM  IS  NULL AND AG.PLCY_NBR NOT LIKE ''16%'' AND   AG.PLCY_NBR NOT LIKE ''14%'' AND   AG.PLCY_NBR NOT LIKE ''12%'' AND   AG.PLCY_NBR NOT LIKE ''18%''

 AND  AG.PLCY_NBR NOT LIKE ''A%'' AND  AG.PLCY_NBR NOT LIKE ''G%'' ) THEN ''NEW'' ELSE ''EXISTING'' END BUSN_TYPE_CD

,COALESCE(case when (SCR.SCR BETWEEN 1 AND 997 ) then CAST( SCR.SCR AS INTEGER) else 0 end,0) AS SCR

,case when (SCR.SCR BETWEEN 1 AND 997 ) then 1 else 0 end    AS ins_scr_plcy_cnt

,CASE WHEN BIRTH_DT IS NOT NULL THEN (CAST((extract( year,  CAST(:CAL_END_DT AS DATE))-extract(year,  cast(BIRTH_DT as date))) AS INTEGER) ) ELSE 0 END AS NMND_INSRD_AGE_AMT

,CASE WHEN ( CAST(ag.CNTNUS_SRVC_DTTM AS DATE)<>''9999-12-31'' AND CAST(ag.CNTNUS_SRVC_DTTM AS DATE)<> ''1900-01-01'' and CAST(ag.CNTNUS_SRVC_DTTM AS DATE)is not null) THEN 

(CAST((extract( year,  CAST(:CAL_END_DT AS DATE))-extract(year,  cast(ag.CNTNUS_SRVC_DTTM as date))) AS INTEGER) ) 

WHEN ( CAST(ag.AGMT_OPN_DTTM AS DATE)<>''9999-12-31'' AND CAST(ag.AGMT_OPN_DTTM AS DATE)<> ''1900-01-01'' and CAST(ag.AGMT_OPN_DTTM AS DATE)is not null) THEN 

coalesce(CAST((extract( year,  CAST(:CAL_END_DT AS DATE))-extract(year,  CAST(ag.AGMT_OPN_DTTM AS DATE))) AS INTEGER),0) 

ELSE 0 END  AS years_with_alfa

,CASE WHEN ((CD_DISC_IND) =''Y'' ) THEN 1 ELSE 0 END AS COMBO_CNT

, CASE WHEN ((MTC_DISC_IND) =''Y'' ) THEN 1 ELSE 0 END AS MULTICAR_CNT

,CASE WHEN ( (CMP_IND) =''N'' AND (COLL_IND) =''N'') THEN 1 ELSE 0 END AS LIABTY_ONLY_CNT

,CASE WHEN ((MIN_BI_LIMIT)=''Y'') THEN 1 ELSE 0 END AS MIN_LMTS_CNT

,CASE WHEN ((CO_CD) IN (''AIC'',''AMI'')) THEN 1 ELSE 0 END  AS PERFERD_COMPANY_CNT

,CASE WHEN ((PNLTY_PNTS_CNT) >0 ) THEN 1 ELSE 0 END AS DRV_POINTS_CNT

, CASE WHEN ((PREV_INS) =1 ) THEN 0 ELSE 1 END NO_PREV_INS_CNT

,CASE WHEN ((GEOGRCL_AREA_SHRT_NAME) =''AL'' AND((ASIC_INS) like ''%ASIC%'' OR (ASIC_INS) like ''%ALFA SPECIALITY%'') )THEN 1 ELSE 0 END ASIC_PREV_INS_CNT

, COALESCE(CMP_0_DED_CNT,0) CMP_0_DED_CNT

,COALESCE(CMP_500_less_DED_CNT,0) CMP_500_less_DED_CNT

,COALESCE( CMP_500_DED_CNT,0) CMP_500_DED_CNT

,COALESCE( CMP_1000_DED_CNT,0)  CMP_1000_DED_CNT

,COALESCE(  CMP_1000_great_DED_CNT,0)   CMP_1000_great_DED_CNT

,COALESCE( TOT_COMP_DEDCTB_UNIT_CNT,0)  TOT_COMP_DEDCTB_UNIT_CNT

,COALESCE(COL_0_DED_CNT,0) COL_0_DED_CNT

,COALESCE( COL_500_less_DED_CNT,0)  COL_500_less_DED_CNT

,COALESCE(COL_500_DED_CNT,0) COL_500_DED_CNT

,COALESCE(COL_1000_DED_CNT,0) COL_1000_DED_CNT

,COALESCE(COL_1000_great_DED_CNT,0) COL_1000_great_DED_CNT

,COALESCE(TOT_COL_DEDCTB_UNIT_CNT,0) TOT_COL_DEDCTB_UNIT_CNT

,COALESCE( PLEASURE_USE_CNT,0)  PLEASURE_USE_CNT

,COALESCE( COMMUTER_USE_CNT,0)  COMMUTER_USE_CNT

,COALESCE( BUSINESS_USE_CNT,0)  BUSINESS_USE_CNT

,COALESCE( FARM_USE_CNT,0)  FARM_USE_CNT

,COALESCE( COMRCL_USE_CNT,0)  COMRCL_USE_CNT

,COALESCE(SHRT_ANNUAL_MILEG_CNT,0) SHRT_ANNUAL_MILEG_CNT

,COALESCE( TOT_VEH_USE_CNT,0)  TOT_VEH_USE_CNT

,COALESCE( AGE_25_29_CNT,0)  AGE_25_29_CNT

,COALESCE( AGE_26_49_CNT,0)  AGE_26_49_CNT

,COALESCE( AGE_75_PLUS_CNT,0)  AGE_75_PLUS_CNT

,COALESCE(YOUTHFUL_CNT,0) YOUTHFUL_CNT

,COALESCE( TOTAL_RTD_DRV_CNT,0)  TOTAL_RTD_DRV_CNT

,COALESCE( TOTAL_VEH_CNT,0)  TOTAL_VEH_CNT

,''GW'' AS SRC_SYS_CD

,COALESCE(MED_PAY_CNT,0) MED_PAY_CNT

,COALESCE(LOSS_OF_USE_CNT,0) LOSS_OF_USE_CNT,

PROD_NAME

 FROM 

(

SELECT A.AGMT_ID,  ast.AGMT_STS_CD,

A.HOST_AGMT_NUM PLCY_NBR,P.PROD_NAME,a.CNTNUS_SRVC_DTTM,a.AGMT_OPN_DTTM,

CASE WHEN a.MODL_EFF_DTTM > a.MODL_CRTN_DTTM THEN a.MODL_EFF_DTTM 

ELSE a.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM FROM  DB_T_PROD_CORE.AGMT AS A 

JOIN  DB_T_PROD_CORE.AGMT TRM 

ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM 

and    TRM.AGMT_TYPE_CD=''POLTRM''   AND CAST(CAST(:CAL_END_DT AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' 

BETWEEN trm.AGMT_EFF_DTTM AND trm.AGMT_PLND_EXPN_DTTM 

AND A.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

JOIN DB_T_PROD_CORE.AGMT_STS  AS AS1  ON  TRM.AGMT_ID=AS1.AGMT_ID 

AND AS1.AGMT_STS_STRT_DTTM <= CAST(CAST(:CAL_END_DT AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' 

and NEW_AGMT_EFF_DTTM < CAST(CAST(:CAL_END_DT  AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND''

AND A.AGMT_TYPE_CD = ''PPV'' AND AS1.AGMT_STS_CD <> ''CNFRMDDT'' 

JOIN DB_T_PROD_CORE.AGMT_PROD  AS AP ON A.AGMT_ID=AP.AGMT_ID  AND AP.AGMT_PROD_ROLE_CD=''PLCYTYPE''

AND  :CAL_END_DT::date  BETWEEN CAST(AP.AGMT_PROD_STRT_DTTM AS DATE) AND CAST(AP.AGMT_PROD_END_DTTM AS DATE)

JOIN DB_T_PROD_CORE.PROD  P ON AP.PROD_ID=P.PROD_ID 

AND :CAL_END_DT::date BETWEEN CAST(P.PROD_STRT_DTTM AS DATE) AND CAST(P.PROD_END_DTTM AS DATE)

AND P.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_STS_TYPE AST ON AS1.AGMT_STS_CD = AST.AGMT_STS_CD 

LEFT OUTER JOIN DB_T_PROD_CORE.AGMT_MBRSHP  AS AM ON  A.AGMT_ID=AM.AGMT_ID

 AND :CAL_END_DT::date BETWEEN CAST(AM.AGMT_MBRSHP_STRT_DTTM AS DATE) AND CAST(AM.AGMT_MBRSHP_END_DTTM AS DATE)

LEFT OUTER JOIN DB_T_PROD_CORE.MBRSHP   AS M ON M.MBRSHP_ID=AM.MBRSHP_ID AND CAST(M.EDW_END_DTTM AS DATE) =CAST( ''9999-12-31''  AS DATE)

WHERE 	  P.PROD_NAME IN (''PPV'',''PPV2'',''COMMERCIAL'')

QUALIFY ROW_NUMBER() OVER(PARTITION BY A.HOST_AGMT_NUM ORDER BY A.MODL_CRTN_DTTM DESC, A.MODL_EFF_DTTM DESC,  AS1.AGMT_STS_STRT_DTTM DESC, AS1.EDW_END_DTTM DESC) = 1



and ast.AGMT_STS_CD =''inforce''

) AG

left outer join 

(

SELECT AGMT_ID, MAX(case when (cast(birth_dt as date)<> ''1900-01-01'') then BIRTH_DT  end ) BIRTH_DT , MAX(PNLTY_PNTS_CNT) PNLTY_PNTS_CNT, MAX(ASIC_INS) ASIC_INS, MAX(CO_CD) CO_CD, MAX(AGNT_NUM) AGNT_NUM FROM (

SELECT PA.AGMT_ID,

CASE WHEN  PA.PRTY_AGMT_ROLE_CD = ''PLCYPRININS'' THEN  BIRTH_DT END AS BIRTH_DT, 

CASE WHEN  PA.PRTY_AGMT_ROLE_CD = ''PLCYDRVR'' THEN PNLTY_PNTS_CNT END AS PNLTY_PNTS_CNT, 

CASE WHEN  PA.PRTY_AGMT_ROLE_CD = ''PRIINSCAR'' THEN  orgn.ORG_NAME END AS ASIC_INS, 

CASE WHEN  PA.PRTY_AGMT_ROLE_CD = ''CMP'' THEN  ltrim(IO.INTRNL_ORG_NUM,''0'') END AS CO_CD ,

CASE WHEN  PA.PRTY_AGMT_ROLE_CD = ''PRDA'' THEN  ltrim(IO.INTRNL_ORG_NUM,''0'') END AS AGNT_NUM

FROM  DB_T_PROD_CORE.PRTY_AGMT AS PA  

 LEFT OUTER JOIN DB_T_PROD_CORE.INDIV AS INM ON PA.PRTY_ID = INM.INDIV_PRTY_ID  

  LEFT OUTER JOIN DB_T_PROD_CORE.INTRNL_ORG AS IO ON PA.PRTY_ID = IO.INTRNL_ORG_PRTY_ID

 LEFT OUTER JOIN DB_T_PROD_CORE.ORG_NAME AS ORGN ON PA.PRTY_ID = ORGN.PRTY_ID

 LEFT OUTER JOIN  DB_T_PROD_CORE.PRTY_DRVG_HIST    PDH ON PA.PRTY_ID = PDH.INDIV_PRTY_ID              

WHERE  PA.PRTY_AGMT_ROLE_CD IN (''PLCYPRININS'', ''CMP'',''PRIINSCAR'',''PLCYDRVR'', ''PRDA'') 

 QUALIFY ROW_NUMBER() OVER(PARTITION BY PA.AGMT_ID,PA.PRTY_ID,PA.PRTY_AGMT_ROLE_CD ORDER BY PA.PRTY_AGMT_STRT_DTTM DESC, PA.TRANS_STRT_DTTM  DESC)=1)T1

 GROUP BY 1

  )SVC_AGNT  ON AG.AGMT_ID=SVC_AGNT.AGMT_ID

    left outer join 

(SELECT T1.AGMT_ID, COUNT(DISTINCT PRTY_ID) TOTAL_RTD_DRV_CNT

,SUM(CASE WHEN (CAST((extract( year,  CAST(:CAL_END_DT AS DATE))-extract(year,  cast(BIRTH_DT as date))) AS INTEGER) BETWEEN  25 AND 29) THEN 1 ELSE 0 END) AGE_25_29_CNT

,SUM(CASE WHEN (CAST((extract( year,  CAST(:CAL_END_DT AS DATE))-extract(year,  cast(BIRTH_DT as date))) AS INTEGER) BETWEEN  26 AND 49) THEN 1 ELSE 0 END) AGE_26_49_CNT

,SUM(CASE WHEN (CAST((extract( year,  CAST(:CAL_END_DT AS DATE))-extract(year,  cast(BIRTH_DT as date))) AS INTEGER) > 75) THEN 1 ELSE 0 END) AGE_75_PLUS_CNT

,SUM(CASE WHEN (CAST((extract( year,  CAST(:CAL_END_DT AS DATE))-extract(year,  cast(BIRTH_DT as date))) AS INTEGER) <25) THEN 1 ELSE 0 END) YOUTHFUL_CNT

from (SELECT PA.AGMT_ID,PA.PRTY_ID,

CASE WHEN  PA.PRTY_AGMT_ROLE_CD = ''RTDDRVR'' THEN  BIRTH_DT END AS BIRTH_DT

FROM  DB_T_PROD_CORE.PRTY_AGMT_ASSET AS PA  

 JOIN DB_T_PROD_CORE.INDIV AS INM ON PA.PRTY_ID = INM.INDIV_PRTY_ID  

WHERE  PA.PRTY_AGMT_ROLE_CD IN (''RTDDRVR'')

AND CAST(INM.TRANS_STRT_DTTM AS DATE)<=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

AND CAST(INM.TRANS_END_DTTM AS DATE)>=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

 QUALIFY ROW_NUMBER() OVER(PARTITION BY PA.AGMT_ID,PA.PRTY_ID ORDER BY  PA.EDW_STRT_DTTM  DESC)=1)T1

   GROUP BY 1

  )AGE  ON AG.AGMT_ID=AGE.AGMT_ID

LEFT OUTER JOIN

(

SELECT AGMT_ID,

MAX(CASE WHEN (INSRNC_CVGE_TYPE_CD = ''BI'' AND FEAT_SBTYPE_CD = ''PKG'' AND FEAT_DTL_CD_NAME=''25K_50k'') THEN ''Y'' ELSE ''N'' END) MIN_BI_LIMIT,

MAX(CASE WHEN ((INSRNC_CVGE_TYPE_CD )= ''COMP''  ) THEN ''Y'' ELSE''N'' END  ) AS CMP_IND,

MAX(CASE WHEN ((INSRNC_CVGE_TYPE_CD )= ''COLL''  ) THEN ''Y'' ELSE''N'' END  ) AS COLL_IND

,sum(CASE WHEN ((CASE WHEN INSRNC_CVGE_TYPE_CD = ''COMP'' AND FEAT_SBTYPE_CD = ''OPT'' THEN CAST(FEAT_DTL_VAL AS INTEGER)  END )=0) THEN 1 ELSE 0 END) CMP_0_DED_CNT

,sum(CASE WHEN ((CASE WHEN INSRNC_CVGE_TYPE_CD = ''COMP'' AND FEAT_SBTYPE_CD = ''OPT'' THEN CAST(FEAT_DTL_VAL AS INTEGER)  END )<500) THEN 1 ELSE 0 END) CMP_500_less_DED_CNT

,sum(CASE WHEN ((CASE WHEN INSRNC_CVGE_TYPE_CD = ''COMP'' AND FEAT_SBTYPE_CD = ''OPT'' THEN CAST(FEAT_DTL_VAL AS INTEGER)  END )=500) THEN 1 ELSE 0 END) CMP_500_DED_CNT

,sum(CASE WHEN ((CASE WHEN INSRNC_CVGE_TYPE_CD = ''COMP'' AND FEAT_SBTYPE_CD = ''OPT'' THEN CAST(FEAT_DTL_VAL AS INTEGER)  END )=1000) THEN 1 ELSE 0 END) CMP_1000_DED_CNT

,sum(CASE WHEN ((CASE WHEN INSRNC_CVGE_TYPE_CD = ''COMP'' AND FEAT_SBTYPE_CD = ''OPT'' THEN CAST(FEAT_DTL_VAL AS INTEGER)  END )>1000) THEN 1 ELSE 0 END)  CMP_1000_great_DED_CNT

,sum(CASE WHEN (INSRNC_CVGE_TYPE_CD = ''COMP''  ) THEN 1 ELSE 0 END) TOT_COMP_DEDCTB_UNIT_CNT

,sum(CASE WHEN ((CASE WHEN INSRNC_CVGE_TYPE_CD = ''COLL'' AND FEAT_SBTYPE_CD = ''OPT'' THEN CAST(FEAT_DTL_VAL AS INTEGER) END )=0) THEN 1 ELSE 0 END) COL_0_DED_CNT

,sum(CASE WHEN ((CASE WHEN INSRNC_CVGE_TYPE_CD = ''COLL'' AND FEAT_SBTYPE_CD = ''OPT'' THEN CAST(FEAT_DTL_VAL AS INTEGER) END )<500) THEN 1 ELSE 0 END) COL_500_less_DED_CNT

,sum(CASE WHEN ((CASE WHEN INSRNC_CVGE_TYPE_CD = ''COLL'' AND FEAT_SBTYPE_CD = ''OPT'' THEN CAST(FEAT_DTL_VAL AS INTEGER) END )=500) THEN 1 ELSE 0 END )COL_500_DED_CNT

,sum(CASE WHEN ((CASE WHEN INSRNC_CVGE_TYPE_CD = ''COLL'' AND FEAT_SBTYPE_CD = ''OPT'' THEN CAST(FEAT_DTL_VAL AS INTEGER) END )=1000) THEN 1 ELSE 0 END )COL_1000_DED_CNT

,sum(CASE WHEN ((CASE WHEN INSRNC_CVGE_TYPE_CD = ''COLL'' AND FEAT_SBTYPE_CD = ''OPT'' THEN CAST(FEAT_DTL_VAL AS INTEGER) END )>1000) THEN 1 ELSE 0 END )COL_1000_great_DED_CNT

,SUM (CASE WHEN (INSRNC_CVGE_TYPE_CD = ''COLL''  )  THEN 1 ELSE 0 END )TOT_COL_DEDCTB_UNIT_CNT

,MAX (CASE WHEN (INSRNC_CVGE_TYPE_CD = ''MED''  )  THEN 1 ELSE 0 END )MED_PAY_CNT

,MAX (CASE WHEN (INSRNC_CVGE_TYPE_CD = ''LOU''  )  THEN 1 ELSE 0 END )LOSS_OF_USE_CNT

FROM 

(SELECT A.AGMT_ID,PRTY_ASSET_ID,FEAT_ID FROM DB_T_PROD_CORE.AGMT_INSRD_ASSET_FEAT A

JOIN DB_T_PROD_CORE.AGMT_PROD  AS AP ON A.AGMT_ID=AP.AGMT_ID 

JOIN DB_T_PROD_CORE.PROD  P ON AP.PROD_ID=P.PROD_ID 

WHERE  PROD_NAME IN ( ''PPV'',''PPV2'',''COMMERCIAL'')

AND CAST(A.AGMT_ASSET_FEAT_STRT_DTTM AS DATE)<=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

AND CAST(A.TRANS_END_DTTM AS DATE)>=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

QUALIFY ROW_NUMBER() OVER(PARTITION BY A.AGMT_ID,A.PRTY_ASSET_ID,A.FEAT_ID ORDER BY A.AGMT_ASSET_FEAT_STRT_DTTM DESC, A.TRANS_STRT_DTTM DESC ) = 1) T1

JOIN DB_T_PROD_CORE.FEAT AS F ON T1.FEAT_ID = F.FEAT_ID  WHERE F.INSRNC_CVGE_TYPE_CD IN (''BI'',''COMP'',''COLL'',''MED'',''LOU'')  

GROUP BY 1) COV ON AG.AGMT_ID=COV.AGMT_ID

LEFT OUTER JOIN

(

SELECT AGMT_ID,

MAX(CASE WHEN( NK_SRC_KEY = ''PAMultiPolicyDiscount_alfa'') THEN ''Y'' ELSE ''N'' END)  AS CD_DISC_IND,

MAX(CASE WHEN (NK_SRC_KEY IN(''PAMultiCarDiscount'',''PAKeepMultiCar_alfa'')) THEN ''Y'' ELSE ''N'' END)  AS MTC_DISC_IND

FROM 

(SELECT A.AGMT_ID,FEAT_ID FROM DB_T_PROD_CORE.AGMT_FEAT  A

JOIN DB_T_PROD_CORE.AGMT_PROD  AS AP ON A.AGMT_ID=AP.AGMT_ID 

JOIN DB_T_PROD_CORE.PROD  P ON AP.PROD_ID=P.PROD_ID 

WHERE  PROD_NAME IN ( ''PPV'',''PPV2'',''COMMERCIAL'') AND A.FEAT_ELGBL_IND = ''T''

AND CAST(A.AGMT_FEAT_STRT_DTTM AS DATE)<=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

AND CAST(A.TRANS_END_DTTM AS DATE)>=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

QUALIFY ROW_NUMBER() OVER(PARTITION BY A.AGMT_ID,A.FEAT_ID ORDER BY A.AGMT_FEAT_STRT_DTTM DESC, A.TRANS_STRT_DTTM DESC ) = 1) T1

JOIN DB_T_PROD_CORE.FEAT AS F ON T1.FEAT_ID = F.FEAT_ID  

WHERE F.INSRNC_LOB_TYPE_CD = ''PAWTC'' 

AND F.FEAT_SBTYPE_CD = ''MOD'' AND F.NK_SRC_KEY IN (''PAMultiPolicyDiscount_alfa'',''PAMultiCarDiscount'',''PAKeepMultiCar_alfa'')

GROUP BY 1) DIS ON AG.AGMT_ID=DIS.AGMT_ID

LEFT OUTER JOIN  (SELECT AGMT_ID, COUNT(DISTINCT AA.PRTY_ASSET_ID) TOTAL_VEH_CNT,

SUM(CASE WHEN  ASSET_DTL_CD =''PLEASURE'' THEN 1 ELSE 0 END) PLEASURE_USE_CNT,

SUM(CASE WHEN  ASSET_DTL_CD =''COMMUTR'' THEN 1 ELSE 0 END) COMMUTER_USE_CNT,

SUM(CASE WHEN  ASSET_DTL_CD =''BUSN'' THEN 1 ELSE 0 END) BUSINESS_USE_CNT,

SUM(CASE WHEN  ASSET_DTL_CD =''FARMING'' THEN 1 ELSE 0 END) FARM_USE_CNT,

SUM(CASE WHEN  ASSET_DTL_CD  IN (''COMMAC'',''COMMDS'') THEN 1 ELSE 0 END) COMRCL_USE_CNT,

SUM(CASE WHEN (ANNUAL_DSTC_MEAS<=7500 ) THEN 1 ELSE 0 END) AS SHRT_ANNUAL_MILEG_CNT

,PLEASURE_USE_CNT+COMMUTER_USE_CNT+BUSINESS_USE_CNT+FARM_USE_CNT+ COMRCL_USE_CNT AS TOT_VEH_USE_CNT

 FROM (

SELECT DISTINCT AA.AGMT_ID, AA.PRTY_ASSET_ID,ASSET_DTL_CD,ANNUAL_DSTC_MEAS FROM DB_T_PROD_CORE.AGMT_ASSET AA

LEFT OUTER JOIN DB_T_PROD_CORE.ASSET_DTL_CD_XREF ADCX

ON AA.PRTY_ASSET_ID=ADCX.PRTY_ASSET_ID

AND CAST(ADCX.ASSET_DTL_XREF_STRT_DTTM AS DATE)<=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

AND CAST(ADCX.ASSET_DTL_XREF_END_DTTM AS DATE)>=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

AND  ASSET_DTL_CD IN (''PLEASURE'',''COMMUTR'',''BUSN'',''FARMING'',''COMMAC'',''COMMDS'')

LEFT OUTER JOIN DB_T_PROD_CORE.MOTR_VEH_DTL MVD

ON AA.PRTY_ASSET_ID=MVD.PRTY_ASSET_ID

AND CAST(MVD.EDW_STRT_DTTM AS DATE)<=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

AND CAST(MVD.EDW_END_DTTM AS DATE)>=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

WHERE  CAST(AA.AGMT_ASSET_STRT_DTTM AS DATE)<=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

AND CAST(AA.TRANS_END_DTTM AS DATE)>=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

QUALIFY 	ROW_NUMBER() OVER(PARTITION BY AA.AGMT_ID,AA.PRTY_ASSET_ID ORDER BY AA.AGMT_ASSET_STRT_DTTM DESC, AA.TRANS_STRT_DTTM DESC ) = 1) AA

GROUP BY 1

) VEH ON VEH.AGMT_ID=AG.AGMT_ID

LEFT OUTER JOIN (select  HOST_APLCTN_NUM, AGMT_ID,PRIOR_INSRNC_IND PREV_INS  from DB_T_PROD_CORE.insrnc_quotn A JOIN DB_T_PROD_CORE.APLCTN B ON A.APLCTN_ID=B.APLCTN_ID

JOIN DB_T_PROD_CORE.QUOTN_AGMT QA ON A.QUOTN_ID=QA.QUOTN_ID 

WHERE CAST(A.QUOTN_UPDT_DTTM AS DATE)<=to_date(:CAL_END_DT , ''YYYY-MM-DD'')  

QUALIFY ROW_NUMBER() OVER(PARTITION BY AGMT_ID ORDER BY QUOTN_UPDT_DTTM DESC)=1)INSCR_SCR

ON INSCR_SCR.AGMT_ID=AG.AGMT_iD

LEFT OUTER JOIN (

SELECT PA.AGMT_ID,MAX(SCR1.SCR) SCR FROM 

(SELECT PS1.PRTY_ID,CAST(PS1.PRTY_SCR_VAL AS INTEGER) AS SCR

FROM DB_T_PROD_CORE.PRTY_SCR PS1

JOIN  DB_T_PROD_CORE.MODL_RUN MR1

ON PS1.MODL_RUN_ID= MR1.MODL_RUN_ID

WHERE PS1.MODL_ID =1 AND CAST(MR1.MODL_RUN_DTTM AS DATE)<=:CAL_END_DT::date

QUALIFY ROW_NUMBER() OVER(PARTITION BY PS1.PRTY_ID ORDER BY  MR1.MODL_RUN_DTTM DESC)=1 )SCR1

JOIN DB_T_PROD_CORE.PRTY_AGMT  PA

ON PA.PRTY_AGMT_ROLE_CD IN ( ''PLCYPRININS'' ,''PLCYADDNMINS'') AND SCR1.PRTY_ID=PA.PRTY_ID 

WHERE CAST( PA.PRTY_AGMT_STRT_DTTM AS DATE)<= :CAL_END_DT::date  

AND CAST( PA.TRANS_END_DTTM AS DATE)>= :CAL_END_DT::date

GROUP BY 1) SCR ON SCR.AGMT_ID=AG.AGMT_ID

LEFT OUTER JOIN   (SELECT HOST_AGMT_NUM FROM DB_T_PROD_CORE.AGMT PREV WHERE

 PREV.AGMT_TYPE_CD=''PPV'' AND CAST(PREV.MODL_EFF_DTTM AS DATE)<=ADD_MONTHS(CAST(:CAL_END_DT AS DATE),-1)

AND SRC_SYS_CD=''GWPC''

  GROUP BY 1) PREV 

 ON PREV.HOST_AGMT_NUM =AG.PLCY_NBR

 LEFT OUTER JOIN (SELECT AGMT_ID, T.GEOGRCL_AREA_SHRT_NAME FROM DB_T_PROD_CORE.AGMT_LOCTR AL  JOIN DB_T_PROD_CORE.TERR T ON AL.LOC_ID=T.TERR_ID AND  AGMT_LOCTR_ROLE_TYPE_CD=''AGTWINST'' 

WHERE CAST(AGMT_LOCTR_STRT_DTTM AS DATE)<=:CAL_END_DT::date )ST

ON ST.AGMT_ID=AG.AGMT_ID

 WHERE  AGMT_STS_CD IN (''INFORCE'',''RNEWLLAPSD'',''CNFRMD'')
) SRC
)
);


-- Component LKP_PLCY_XREF, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_PLCY_XREF AS
(
SELECT
LKP.PLCY_ID,
sq_AGMT.source_record_id,
ROW_NUMBER() OVER(PARTITION BY sq_AGMT.source_record_id ORDER BY LKP.PLCY_ID asc) RNK
FROM
sq_AGMT
LEFT JOIN (
SELECT PLCY_ID as PLCY_ID, PLCY_NBR as PLCY_NBR FROM  db_v_prod_pres.PLCY_XREF
WHERE SRC_TYPE=''GW''
QUALIFY ROW_NUMBER() OVER (PARTITION BY PLCY_NBR ORDER BY EDW_END_DTTM DESC)=1
) LKP ON 
sq_AGMT.PLCY_NUM = LKP.PLCY_NBR
QUALIFY RNK = 1
);


-- Component exp_Passthrough, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Passthrough AS
(
SELECT
LKP_PLCY_XREF.PLCY_ID as PLCY_ID,
sq_AGMT.PRODUCER_ID as PRODUCER_ID,
sq_AGMT.MO_ID as MO_ID,
sq_AGMT.BUSN_TYPE_CD as BUSN_TYPE_CD,
sq_AGMT.INSRNC_SCR_AMT as INSRNC_SCR_AMT,
sq_AGMT.INSRNC_SCR_PLCY_CNT as INSRNC_SCR_PLCY_CNT,
sq_AGMT.NMND_INSRD_AGE_AMT as NMND_INSRD_AGE_AMT,
sq_AGMT.YRS_WTH_ALFA_AMT as YRS_WTH_ALFA_AMT,
sq_AGMT.COMBO_CNT as COMBO_CNT,
sq_AGMT.MULTICAR_CNT as MULTICAR_CNT,
sq_AGMT.LIABTY_ONLY_CNT as LIABTY_ONLY_CNT,
sq_AGMT.MIN_LMTS_CNT as MIN_LMTS_CNT,
sq_AGMT.PREFD_CO_CNT as PREFD_CO_CNT,
sq_AGMT.DRVR_PNTS_CNT as DRVR_PNTS_CNT,
sq_AGMT.NO_PRIOR_INSRNC_CNT as NO_PRIOR_INSRNC_CNT,
sq_AGMT.ASIC_PRIOR_INSRNC_CNT as ASIC_PRIOR_INSRNC_CNT,
sq_AGMT.COMP_DEDCTB_0_CNT as COMP_DEDCTB_0_CNT,
sq_AGMT.COMP_DEDCTB_500_LESS_CNT as COMP_DEDCTB_500_LESS_CNT,
sq_AGMT.COMP_DEDCTB_500_CNT as COMP_DEDCTB_500_CNT,
sq_AGMT.COMP_DEDCTB_1000_CNT as COMP_DEDCTB_1000_CNT,
sq_AGMT.COMP_DEDCTB_OTH_CNT as COMP_DEDCTB_OTH_CNT,
sq_AGMT.TOT_COMP_DEDCTB_UNIT_CNT as TOT_COMP_DEDCTB_UNIT_CNT,
sq_AGMT.COLL_DEDCTB_0_CNT as COLL_DEDCTB_0_CNT,
sq_AGMT.COLL_DEDCTB_500_LESS_CNT as COLL_DEDCTB_500_LESS_CNT,
sq_AGMT.COLL_DEDCTB_500_CNT as COLL_DEDCTB_500_CNT,
sq_AGMT.COLL_DEDCTB_1000_CNT as COLL_DEDCTB_1000_CNT,
sq_AGMT.COLL_DEDCTB_OTH_CNT as COLL_DEDCTB_OTH_CNT,
sq_AGMT.TOT_COLL_DEDCTB_UNIT_CNT as TOT_COLL_DEDCTB_UNIT_CNT,
sq_AGMT.PLEASURE_USE_CNT as PLEASURE_USE_CNT,
sq_AGMT.COMMUTER_USE_CNT as COMMUTER_USE_CNT,
sq_AGMT.BUSN_USE_CNT as BUSN_USE_CNT,
sq_AGMT.FARM_USE_CNT as FARM_USE_CNT,
sq_AGMT.COMRCL_USE_CNT as COMRCL_USE_CNT,
sq_AGMT.SHRT_ANNUAL_MILEG_CNT as SHRT_ANNUAL_MILEG_CNT,
sq_AGMT.TOT_VEH_USE_CNT as TOT_VEH_USE_CNT,
sq_AGMT.AGE_26_49_CNT as AGE_26_49_CNT,
sq_AGMT.AGE_25_29_CNT as AGE_25_29_CNT,
sq_AGMT.AGE_75_PLUS_CNT as AGE_75_PLUS_CNT,
sq_AGMT.YOUTHFUL_CNT as YOUTHFUL_CNT,
sq_AGMT.TOT_RTD_DRVR_CNT as TOT_RTD_DRVR_CNT,
sq_AGMT.TOT_VEH_CNT as TOT_VEH_CNT,
sq_AGMT.SRC_SYS_CD as SRC_SYS_CD,
sq_AGMT.MED_PAY_CNT as MED_PAY_CNT,
sq_AGMT.LOSS_OF_USE_CNT as LOSS_OF_USE_CNT,
sq_AGMT.PROD_NAME as PROD_NAME,
sq_AGMT.source_record_id
FROM
sq_AGMT
INNER JOIN LKP_PLCY_XREF ON sq_AGMT.source_record_id = LKP_PLCY_XREF.source_record_id
);


-- Component fil_invalid_policynumber, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE fil_invalid_policynumber AS
(
SELECT
exp_Passthrough.PLCY_ID as PLCY_ID,
exp_Passthrough.PRODUCER_ID as PRODUCER_ID,
exp_Passthrough.MO_ID as MO_ID,
exp_Passthrough.BUSN_TYPE_CD as BUSN_TYPE_CD,
exp_Passthrough.INSRNC_SCR_AMT as INSRNC_SCR_AMT,
exp_Passthrough.INSRNC_SCR_PLCY_CNT as INSRNC_SCR_PLCY_CNT,
exp_Passthrough.NMND_INSRD_AGE_AMT as NMND_INSRD_AGE_AMT,
exp_Passthrough.YRS_WTH_ALFA_AMT as YRS_WTH_ALFA_AMT,
exp_Passthrough.COMBO_CNT as COMBO_CNT,
exp_Passthrough.MULTICAR_CNT as MULTICAR_CNT,
exp_Passthrough.LIABTY_ONLY_CNT as LIABTY_ONLY_CNT,
exp_Passthrough.MIN_LMTS_CNT as MIN_LMTS_CNT,
exp_Passthrough.PREFD_CO_CNT as PREFD_CO_CNT,
exp_Passthrough.DRVR_PNTS_CNT as DRVR_PNTS_CNT,
exp_Passthrough.NO_PRIOR_INSRNC_CNT as NO_PRIOR_INSRNC_CNT,
exp_Passthrough.ASIC_PRIOR_INSRNC_CNT as ASIC_PRIOR_INSRNC_CNT,
exp_Passthrough.COMP_DEDCTB_0_CNT as COMP_DEDCTB_0_CNT,
exp_Passthrough.COMP_DEDCTB_500_LESS_CNT as COMP_DEDCTB_500_LESS_CNT,
exp_Passthrough.COMP_DEDCTB_500_CNT as COMP_DEDCTB_500_CNT,
exp_Passthrough.COMP_DEDCTB_1000_CNT as COMP_DEDCTB_1000_CNT,
exp_Passthrough.COMP_DEDCTB_OTH_CNT as COMP_DEDCTB_OTH_CNT,
exp_Passthrough.TOT_COMP_DEDCTB_UNIT_CNT as TOT_COMP_DEDCTB_UNIT_CNT,
exp_Passthrough.COLL_DEDCTB_0_CNT as COLL_DEDCTB_0_CNT,
exp_Passthrough.COLL_DEDCTB_500_LESS_CNT as COLL_DEDCTB_500_LESS_CNT,
exp_Passthrough.COLL_DEDCTB_500_CNT as COLL_DEDCTB_500_CNT,
exp_Passthrough.COLL_DEDCTB_1000_CNT as COLL_DEDCTB_1000_CNT,
exp_Passthrough.COLL_DEDCTB_OTH_CNT as COLL_DEDCTB_OTH_CNT,
exp_Passthrough.TOT_COLL_DEDCTB_UNIT_CNT as TOT_COLL_DEDCTB_UNIT_CNT,
exp_Passthrough.PLEASURE_USE_CNT as PLEASURE_USE_CNT,
exp_Passthrough.COMMUTER_USE_CNT as COMMUTER_USE_CNT,
exp_Passthrough.BUSN_USE_CNT as BUSN_USE_CNT,
exp_Passthrough.FARM_USE_CNT as FARM_USE_CNT,
exp_Passthrough.COMRCL_USE_CNT as COMRCL_USE_CNT,
exp_Passthrough.SHRT_ANNUAL_MILEG_CNT as SHRT_ANNUAL_MILEG_CNT,
exp_Passthrough.TOT_VEH_USE_CNT as TOT_VEH_USE_CNT,
exp_Passthrough.AGE_26_49_CNT as AGE_26_49_CNT,
exp_Passthrough.AGE_25_29_CNT as AGE_25_29_CNT,
exp_Passthrough.AGE_75_PLUS_CNT as AGE_75_PLUS_CNT,
exp_Passthrough.YOUTHFUL_CNT as YOUTHFUL_CNT,
exp_Passthrough.TOT_RTD_DRVR_CNT as TOT_RTD_DRVR_CNT,
exp_Passthrough.TOT_VEH_CNT as TOT_VEH_CNT,
exp_Passthrough.SRC_SYS_CD as SRC_SYS_CD,
exp_Passthrough.MED_PAY_CNT as MED_PAY_CNT,
exp_Passthrough.LOSS_OF_USE_CNT as LOSS_OF_USE_CNT,
exp_Passthrough.PROD_NAME as PROD_NAME,
exp_Passthrough.source_record_id
FROM
exp_Passthrough
WHERE exp_Passthrough.PLCY_ID IS NOT NULL
);


-- Component F_AUTO_PLCY, Type TARGET 
INSERT INTO DB_V_PROD_PRES.F_AUTO_PLCY
(
PLCY_ID,
MO_ID,
PRODUCER_ID,
BUSN_TYPE_CD,
INSRNC_SCR_AMT,
INSRNC_SCR_PLCY_CNT,
NMND_INSRD_AGE_AMT,
YRS_WTH_ALFA_AMT,
COMBO_CNT,
MULTICAR_CNT,
LIABTY_ONLY_CNT,
MIN_LMTS_CNT,
PREFD_CO_CNT,
DRVR_PNTS_CNT,
NO_PRIOR_INSRNC_CNT,
ASIC_PRIOR_INSRNC_CNT,
COMP_DEDCTB_0_CNT,
COMP_DEDCTB_500_LESS_CNT,
COMP_DEDCTB_500_CNT,
COMP_DEDCTB_1000_CNT,
COMP_DEDCTB_OTH_CNT,
TOT_COMP_DEDCTB_UNIT_CNT,
COLL_DEDCTB_0_CNT,
COLL_DEDCTB_500_LESS_CNT,
COLL_DEDCTB_500_CNT,
COLL_DEDCTB_1000_CNT,
COLL_DEDCTB_OTH_CNT,
TOT_COLL_DEDCTB_UNIT_CNT,
PLEASURE_USE_CNT,
COMMUTER_USE_CNT,
BUSN_USE_CNT,
FARM_USE_CNT,
COMRCL_USE_CNT,
SHRT_ANNUAL_MILEG_CNT,
TOT_VEH_USE_CNT,
AGE_26_49_CNT,
AGE_25_29_CNT,
AGE_75_PLUS_CNT,
YOUTHFUL_CNT,
TOT_RTD_DRVR_CNT,
TOT_VEH_CNT,
SRC_SYS_CD,
MED_PAY_CNT,
LOSS_OF_USE_CNT,
PROD_NAME
)
SELECT
fil_invalid_policynumber.PLCY_ID as PLCY_ID,
fil_invalid_policynumber.MO_ID as MO_ID,
fil_invalid_policynumber.PRODUCER_ID as PRODUCER_ID,
fil_invalid_policynumber.BUSN_TYPE_CD as BUSN_TYPE_CD,
fil_invalid_policynumber.INSRNC_SCR_AMT as INSRNC_SCR_AMT,
fil_invalid_policynumber.INSRNC_SCR_PLCY_CNT as INSRNC_SCR_PLCY_CNT,
fil_invalid_policynumber.NMND_INSRD_AGE_AMT as NMND_INSRD_AGE_AMT,
fil_invalid_policynumber.YRS_WTH_ALFA_AMT as YRS_WTH_ALFA_AMT,
fil_invalid_policynumber.COMBO_CNT as COMBO_CNT,
fil_invalid_policynumber.MULTICAR_CNT as MULTICAR_CNT,
fil_invalid_policynumber.LIABTY_ONLY_CNT as LIABTY_ONLY_CNT,
fil_invalid_policynumber.MIN_LMTS_CNT as MIN_LMTS_CNT,
fil_invalid_policynumber.PREFD_CO_CNT as PREFD_CO_CNT,
fil_invalid_policynumber.DRVR_PNTS_CNT as DRVR_PNTS_CNT,
fil_invalid_policynumber.NO_PRIOR_INSRNC_CNT as NO_PRIOR_INSRNC_CNT,
fil_invalid_policynumber.ASIC_PRIOR_INSRNC_CNT as ASIC_PRIOR_INSRNC_CNT,
fil_invalid_policynumber.COMP_DEDCTB_0_CNT as COMP_DEDCTB_0_CNT,
fil_invalid_policynumber.COMP_DEDCTB_500_LESS_CNT as COMP_DEDCTB_500_LESS_CNT,
fil_invalid_policynumber.COMP_DEDCTB_500_CNT as COMP_DEDCTB_500_CNT,
fil_invalid_policynumber.COMP_DEDCTB_1000_CNT as COMP_DEDCTB_1000_CNT,
fil_invalid_policynumber.COMP_DEDCTB_OTH_CNT as COMP_DEDCTB_OTH_CNT,
fil_invalid_policynumber.TOT_COMP_DEDCTB_UNIT_CNT as TOT_COMP_DEDCTB_UNIT_CNT,
fil_invalid_policynumber.COLL_DEDCTB_0_CNT as COLL_DEDCTB_0_CNT,
fil_invalid_policynumber.COLL_DEDCTB_500_LESS_CNT as COLL_DEDCTB_500_LESS_CNT,
fil_invalid_policynumber.COLL_DEDCTB_500_CNT as COLL_DEDCTB_500_CNT,
fil_invalid_policynumber.COLL_DEDCTB_1000_CNT as COLL_DEDCTB_1000_CNT,
fil_invalid_policynumber.COLL_DEDCTB_OTH_CNT as COLL_DEDCTB_OTH_CNT,
fil_invalid_policynumber.TOT_COLL_DEDCTB_UNIT_CNT as TOT_COLL_DEDCTB_UNIT_CNT,
fil_invalid_policynumber.PLEASURE_USE_CNT as PLEASURE_USE_CNT,
fil_invalid_policynumber.COMMUTER_USE_CNT as COMMUTER_USE_CNT,
fil_invalid_policynumber.BUSN_USE_CNT as BUSN_USE_CNT,
fil_invalid_policynumber.FARM_USE_CNT as FARM_USE_CNT,
fil_invalid_policynumber.COMRCL_USE_CNT as COMRCL_USE_CNT,
fil_invalid_policynumber.SHRT_ANNUAL_MILEG_CNT as SHRT_ANNUAL_MILEG_CNT,
fil_invalid_policynumber.TOT_VEH_USE_CNT as TOT_VEH_USE_CNT,
fil_invalid_policynumber.AGE_25_29_CNT as AGE_26_49_CNT,
fil_invalid_policynumber.AGE_26_49_CNT as AGE_25_29_CNT,
fil_invalid_policynumber.AGE_75_PLUS_CNT as AGE_75_PLUS_CNT,
fil_invalid_policynumber.YOUTHFUL_CNT as YOUTHFUL_CNT,
fil_invalid_policynumber.TOT_RTD_DRVR_CNT as TOT_RTD_DRVR_CNT,
fil_invalid_policynumber.TOT_VEH_CNT as TOT_VEH_CNT,
fil_invalid_policynumber.SRC_SYS_CD as SRC_SYS_CD,
fil_invalid_policynumber.MED_PAY_CNT as MED_PAY_CNT,
fil_invalid_policynumber.LOSS_OF_USE_CNT as LOSS_OF_USE_CNT,
fil_invalid_policynumber.PROD_NAME as PROD_NAME
FROM
fil_invalid_policynumber;


END; ';