-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_RECON_EDW_SEMANTIC_MTRC_INS("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE
  PRCS_ID STRING;
  run_id STRING;
  workflow_name STRING;
  session_name STRING;
BEGIN
  run_id := public.func_get_scoped_param(:run_id, ''run_id'', :workflow_name, :worklet_name, :session_name);
  workflow_name := public.func_get_scoped_param(:run_id, ''workflow_name'', :workflow_name, :worklet_name, :session_name);
  session_name := public.func_get_scoped_param(:run_id, ''session_name'', :workflow_name, :worklet_name, :session_name);

  PRCS_ID := public.func_get_scoped_param(:run_id, ''prcs_id'', :workflow_name, :worklet_name, :session_name);
 

-- Component SQ_RECON_SMNTC_MTRC_INT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_RECON_SMNTC_MTRC_INT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MTRC,
$2 as FRQCY,
$3 as VALUE_TYPE,
$4 as RECON_MTRC_LAYER,
$5 as SOURCE_LAYER,
$6 as TARGET_LAYER,
$7 as SOURCE_VAL,
$8 as TARGET_VAL,
$9 as CMPRSN_DT,
$10 as THRSH_VAL,
$11 as THRSH_PCT,
$12 as THRSH_VAL_CALC_MTHD,
$13 as MTRC_ORIGN,
$14 as MTRC_DESC,
$15 as LOAD_DTTM,
$16 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT	RECON_SMNTC_MTRC_INT.MTRC, RECON_SMNTC_MTRC_INT.FRQCY,

		RECON_SMNTC_MTRC_INT.VALUE_TYPE, RECON_SMNTC_MTRC_INT.RECON_MTRC_LAYER,

		RECON_SMNTC_MTRC_INT.SOURCE_LAYER, RECON_SMNTC_MTRC_INT.TARGET_LAYER,

		RECON_SMNTC_MTRC_INT.SOURCE_VAL, RECON_SMNTC_MTRC_INT.TARGET_VAL,

		RECON_SMNTC_MTRC_INT.CMPRSN_DT, RECON_SMNTC_MTRC_INT.THRSH_VAL,

		RECON_SMNTC_MTRC_INT.THRSH_PCT, RECON_SMNTC_MTRC_INT.THRSH_VAL_CALC_MTHD,

		RECON_SMNTC_MTRC_INT.MTRC_ORIGN, RECON_SMNTC_MTRC_INT.MTRC_DESC,

		RECON_SMNTC_MTRC_INT.LOAD_DTTM 

FROM	

 db_t_prod_core.RECON_SMNTC_MTRC_INT

 WHERE RECON_SMNTC_MTRC_INT.RECON_MTRC_LAYER =''EDW | SMNTC''

 AND RECON_SMNTC_MTRC_INT.FRQCY =''DLY''
) SRC
)
);


-- Component exp_pass_through_data, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through_data AS
(
SELECT
SQ_RECON_SMNTC_MTRC_INT.MTRC as MTRC,
SQ_RECON_SMNTC_MTRC_INT.FRQCY as FRQCY,
SQ_RECON_SMNTC_MTRC_INT.VALUE_TYPE as VALUE_TYPE,
SQ_RECON_SMNTC_MTRC_INT.RECON_MTRC_LAYER as RECON_MTRC_LAYER,
SQ_RECON_SMNTC_MTRC_INT.SOURCE_LAYER as SOURCE_LAYER,
SQ_RECON_SMNTC_MTRC_INT.TARGET_LAYER as TARGET_LAYER,
SQ_RECON_SMNTC_MTRC_INT.SOURCE_VAL as SOURCE_VAL,
SQ_RECON_SMNTC_MTRC_INT.TARGET_VAL as TARGET_VAL,
SQ_RECON_SMNTC_MTRC_INT.THRSH_VAL as THRSH_VAL,
SQ_RECON_SMNTC_MTRC_INT.THRSH_PCT as THRSH_PCT,
SQ_RECON_SMNTC_MTRC_INT.THRSH_VAL_CALC_MTHD as THRSH_VAL_CALC_MTHD,
SQ_RECON_SMNTC_MTRC_INT.MTRC_ORIGN as MTRC_ORIGN,
SQ_RECON_SMNTC_MTRC_INT.MTRC_DESC as MTRC_DESC,
SQ_RECON_SMNTC_MTRC_INT.source_record_id
FROM
SQ_RECON_SMNTC_MTRC_INT
);


-- Component LKP_RECON_MTRC, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_RECON_MTRC AS
(
SELECT
LKP.MTRC,
LKP.FRQCY,
LKP.VALUE_TYPE,
LKP.RECON_MTRC_LAYER,
LKP.DIFF_MTRC_VAL,
LKP.THRSH_VAL,
LKP.THRSH_VAL_CALC_MTHD,
LKP.MTRC_ORIGN,
LKP.MTRC_DESC,
exp_pass_through_data.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pass_through_data.source_record_id ORDER BY LKP.MTRC asc,LKP.FRQCY asc,LKP.VALUE_TYPE asc,LKP.RECON_MTRC_LAYER asc,LKP.SOURCE_MTRC_VAL asc,LKP.TARGET_MTRC_VAL asc,LKP.DIFF_MTRC_VAL asc,LKP.THRSH_VAL asc,LKP.THRSH_VAL_CALC_MTHD asc,LKP.DIFF_MTRC_VAL_OVR_THRSH asc,LKP.PRIOR_DIFF_MTRC_VAL asc,LKP.PCT_CHG_DIFF_MTRC_VAL asc,LKP.CMPRSN_DT asc,LKP.MTRC_ORIGN asc,LKP.MTRC_DESC asc,LKP.LOAD_DTTM asc,LKP.PRCS_ID asc) RNK
FROM
exp_pass_through_data
LEFT JOIN (
SELECT DISTINCT	A.FRQCY as FRQCY, A.SOURCE_MTRC_VAL as SOURCE_MTRC_VAL,
		A.TARGET_MTRC_VAL as TARGET_MTRC_VAL, A.DIFF_MTRC_VAL as DIFF_MTRC_VAL,
		A.THRSH_VAL as THRSH_VAL, A.THRSH_VAL_CALC_MTHD as THRSH_VAL_CALC_MTHD,
		A.DIFF_MTRC_VAL_OVR_THRSH as DIFF_MTRC_VAL_OVR_THRSH,
		A.PRIOR_DIFF_MTRC_VAL as PRIOR_DIFF_MTRC_VAL, A.PCT_CHG_DIFF_MTRC_VAL as PCT_CHG_DIFF_MTRC_VAL,
		A.CMPRSN_DT as CMPRSN_DT, A.MTRC_ORIGN as MTRC_ORIGN,
		A.MTRC_DESC as MTRC_DESC, A.LOAD_DTTM as LOAD_DTTM,
		A.PRCS_ID as PRCS_ID, A.MTRC as MTRC, A.VALUE_TYPE as VALUE_TYPE,
		A.RECON_MTRC_LAYER as RECON_MTRC_LAYER 		
FROM	( 
SELECT	DISTINCT A.* , ROW_NUMBER() OVER(PARTITION BY A.MTRC,A.RECON_MTRC_LAYER,A.FRQCY,A.VALUE_TYPE
ORDER	BY	LOAD_DTTM DESC, CMPRSN_DT DESC  )RNK 
		 FROM  db_t_prod_core.RECON_MTRC A   )A WHERE A.RNK=1
) LKP ON LKP.MTRC = exp_pass_through_data.MTRC AND LKP.VALUE_TYPE = exp_pass_through_data.VALUE_TYPE AND LKP.RECON_MTRC_LAYER = exp_pass_through_data.RECON_MTRC_LAYER
QUALIFY RNK = 1
);


-- Component EXP_RECON_MTRC_CALC, Type EXPRESSION 
/*CREATE OR REPLACE TEMPORARY TABLE EXP_RECON_MTRC_CALC AS
(
SELECT
exp_pass_through_data.MTRC as MTRC,
exp_pass_through_data.FRQCY as FRQCY,
exp_pass_through_data.VALUE_TYPE as VALUE_TYPE,
exp_pass_through_data.RECON_MTRC_LAYER as RCON_MTRC_LYER,
exp_pass_through_data.SOURCE_LAYER as SOURCE_LAYER,
exp_pass_through_data.TARGET_LAYER as TARGET_LAYER,
CASE WHEN TO_CHAR ( IFNULL(TRY_TO_DECIMAL(exp_pass_through_data.SOURCE_VAL), 0) ) IS NULL THEN ''0.00'' ELSE TO_CHAR ( IFNULL(TRY_TO_DECIMAL(exp_pass_through_data.SOURCE_VAL), 0) ) END as V_SOURCE_SQL_VALUE,
TO_CHAR ( IFNULL(TRY_TO_DECIMAL(TO_CHAR ( V_SOURCE_SQL_VALUE )), 0) ) as O_SOURCE_SQL_VALUE,
CASE WHEN TO_CHAR ( IFNULL(TRY_TO_DECIMAL(exp_pass_through_data.TARGET_VAL), 0) ) IS NULL THEN ''0.00'' ELSE TO_CHAR ( IFNULL(TRY_TO_DECIMAL(exp_pass_through_data.TARGET_VAL), 0) ) END as V_TARGET_SQL_VALUE,
TO_CHAR ( IFNULL(TRY_TO_DECIMAL(TO_CHAR ( V_TARGET_SQL_VALUE )), 0) ) as O_TARGET_SQL_VALUE,
TO_CHAR ( IFNULL(TRY_TO_DECIMAL(V_SOURCE_SQL_VALUE), 0) - IFNULL(TRY_TO_DECIMAL(V_TARGET_SQL_VALUE), 0) ) as DIFF_SQL_VAL_VAR,
TO_CHAR ( IFNULL(TRY_TO_DECIMAL(TO_CHAR ( DIFF_SQL_VAL_VAR )), 0) ) as DIFF_MTRC_VAL,
exp_pass_through_data.THRSH_VAL as THRSH_VAL,
exp_pass_through_data.THRSH_PCT as THRSH_PCT,
exp_pass_through_data.THRSH_VAL_CALC_MTHD as THRSH_VAL_CALC_MTHD,
TO_CHAR ( ABS ( IFNULL(TRY_TO_DECIMAL(DIFF_SQL_VAL_VAR), 0) ) - ABS ( IFNULL(TRY_TO_DECIMAL(exp_pass_through_data.THRSH_VAL), 0) ) ) as DIFF_MTRC_VAL_OVER_THRSH_VAR,
TO_CHAR ( IFNULL(TRY_TO_DECIMAL(DIFF_MTRC_VAL_OVER_THRSH_VAR), 0) ) as DIFF_MTRC_VAL_OVER_THRSH,
TO_CHAR ( IFNULL(TRY_TO_DECIMAL(TO_CHAR ( LKP_RECON_MTRC.DIFF_MTRC_VAL )), 0) ) as PRIOR_DIFF_MTRC_VAL,
CASE WHEN ( IFNULL(TRY_TO_DECIMAL(DIFF_SQL_VAL_VAR), 0) - IFNULL(TRY_TO_DECIMAL(LKP_RECON_MTRC.DIFF_MTRC_VAL), 0) ) <> 0 THEN CASE WHEN IFNULL(TRY_TO_DECIMAL(LKP_RECON_MTRC.DIFF_MTRC_VAL), 0) <> 0 THEN TO_CHAR ( ( ( IFNULL(TRY_TO_DECIMAL(DIFF_SQL_VAL_VAR), 0) - IFNULL(TRY_TO_DECIMAL(LKP_RECON_MTRC.DIFF_MTRC_VAL), 0) ) / IFNULL(TRY_TO_DECIMAL(LKP_RECON_MTRC.DIFF_MTRC_VAL), 0) ) * 100 ) ELSE ''100.000'' END ELSE ''0.000'' END as PCT_CHG_DIFF_MTRC_VAL_VAR,
CASE WHEN PCT_CHG_DIFF_MTRC_VAL_VAR IS NULL THEN ''0.000'' ELSE PCT_CHG_DIFF_MTRC_VAL_VAR END as PCT_CHG_DIFF_MTRC_VAL,
TO_CHAR ( IFNULL(TRY_TO_DECIMAL(PCT_CHG_DIFF_MTRC_VAL), 0) ) || ''%'' as O_PCT_CHG_DIFF_MTRC_VAL,
CURRENT_TIMESTAMP as CMPRSN_DATE,
exp_pass_through_data.MTRC_ORIGN as MTRC_ORIGN,
exp_pass_through_data.MTRC_DESC as MTRC_DESC,
CURRENT_TIMESTAMP as LAOD_DTTM,
:PRCS_ID as PRCS_ID,
exp_pass_through_data.source_record_id
FROM
exp_pass_through_data
INNER JOIN LKP_RECON_MTRC ON exp_pass_through_data.source_record_id = LKP_RECON_MTRC.source_record_id
);
*/

CREATE OR REPLACE TEMPORARY TABLE EXP_RECON_MTRC_CALC AS
SELECT
  e.MTRC,
  e.FRQCY,
  e.VALUE_TYPE,
  e.RECON_MTRC_LAYER    AS RCON_MTRC_LYER,
  e.SOURCE_LAYER,
  e.TARGET_LAYER,

  -- Source value
  COALESCE(
    TO_CHAR(TRY_TO_DECIMAL(e.SOURCE_VAL::VARCHAR), ''9999999990.00''),
    ''0.00''
  ) AS V_SOURCE_SQL_VALUE,
  -- Output copy
  TO_CHAR(
    TRY_TO_DECIMAL(V_SOURCE_SQL_VALUE::VARCHAR),
    ''9999999990.00''
  ) AS O_SOURCE_SQL_VALUE,

  -- Target value
  COALESCE(
    TO_CHAR(TRY_TO_DECIMAL(e.TARGET_VAL::VARCHAR), ''9999999990.00''),
    ''0.00''
  ) AS V_TARGET_SQL_VALUE,
  -- Output copy
  TO_CHAR(
    TRY_TO_DECIMAL(V_TARGET_SQL_VALUE::VARCHAR),
    ''9999999990.00''
  ) AS O_TARGET_SQL_VALUE,

  -- Difference
  TO_CHAR(
    TRY_TO_DECIMAL(V_SOURCE_SQL_VALUE::VARCHAR)
    - TRY_TO_DECIMAL(V_TARGET_SQL_VALUE::VARCHAR),
    ''9999999990.00''
  ) AS DIFF_SQL_VAL_VAR,

  TO_CHAR(
    TRY_TO_DECIMAL(DIFF_SQL_VAL_VAR::VARCHAR),
    ''9999999990.00''
  ) AS DIFF_MTRC_VAL,

  e.THRSH_VAL,
  e.THRSH_PCT,
  e.THRSH_VAL_CALC_MTHD,

  -- Difference over threshold
  TO_CHAR(
    ABS(TRY_TO_DECIMAL(DIFF_SQL_VAL_VAR::VARCHAR))
    - ABS(TRY_TO_DECIMAL(e.THRSH_VAL::VARCHAR)),
    ''9999999990.00''
  ) AS DIFF_MTRC_VAL_OVER_THRSH_VAR,

  TO_CHAR(
    TRY_TO_DECIMAL(DIFF_MTRC_VAL_OVER_THRSH_VAR::VARCHAR),
    ''9999999990.00''
  ) AS DIFF_MTRC_VAL_OVER_THRSH,

  -- Prior difference
  TO_CHAR(
    TRY_TO_DECIMAL(l.DIFF_MTRC_VAL::VARCHAR),
    ''9999999990.00''
  ) AS PRIOR_DIFF_MTRC_VAL,

  -- Percent change
  TO_CHAR(
    CASE
      WHEN TRY_TO_DECIMAL(DIFF_SQL_VAL_VAR::VARCHAR)
           - TRY_TO_DECIMAL(l.DIFF_MTRC_VAL::VARCHAR) <> 0
      THEN
        CASE
          WHEN TRY_TO_DECIMAL(l.DIFF_MTRC_VAL::VARCHAR) <> 0
          THEN (
            (TRY_TO_DECIMAL(DIFF_SQL_VAL_VAR::VARCHAR)
             - TRY_TO_DECIMAL(l.DIFF_MTRC_VAL::VARCHAR))
            / TRY_TO_DECIMAL(l.DIFF_MTRC_VAL::VARCHAR)
          ) * 100
          ELSE 100
        END
      ELSE 0
    END,
    ''990.000''
  ) AS PCT_CHG_DIFF_MTRC_VAL_VAR,

  COALESCE(
    TO_CHAR(TRY_TO_DECIMAL(PCT_CHG_DIFF_MTRC_VAL_VAR::VARCHAR), ''990.000''),
    ''0.000''
  ) AS PCT_CHG_DIFF_MTRC_VAL,

  -- Append percent sign
  TO_CHAR(
    TRY_TO_DECIMAL(PCT_CHG_DIFF_MTRC_VAL::VARCHAR),
    ''990.000''
  ) || ''%'' AS O_PCT_CHG_DIFF_MTRC_VAL,

  CURRENT_TIMESTAMP() AS CMPRSN_DATE,
  e.MTRC_ORIGN,
  e.MTRC_DESC,
  CURRENT_TIMESTAMP() AS LAOD_DTTM,
  :PRCS_ID       AS PRCS_ID,
  e.source_record_id
FROM exp_pass_through_data e
JOIN LKP_RECON_MTRC l
  ON e.source_record_id = l.source_record_id;


-- Component RECON_MTRC_EDW_SYMNTC, Type TARGET 
INSERT INTO db_t_prod_core.RECON_MTRC
(
MTRC,
FRQCY,
VALUE_TYPE,
RECON_MTRC_LAYER,
SOURCE_MTRC_VAL,
TARGET_MTRC_VAL,
DIFF_MTRC_VAL,
THRSH_VAL,
THRSH_VAL_CALC_MTHD,
DIFF_MTRC_VAL_OVR_THRSH,
PRIOR_DIFF_MTRC_VAL,
PCT_CHG_DIFF_MTRC_VAL,
CMPRSN_DT,
MTRC_ORIGN,
MTRC_DESC,
LOAD_DTTM,
PRCS_ID
)
SELECT
EXP_RECON_MTRC_CALC.MTRC as MTRC,
EXP_RECON_MTRC_CALC.FRQCY as FRQCY,
EXP_RECON_MTRC_CALC.VALUE_TYPE as VALUE_TYPE,
EXP_RECON_MTRC_CALC.RCON_MTRC_LYER as RECON_MTRC_LAYER,
EXP_RECON_MTRC_CALC.O_SOURCE_SQL_VALUE as SOURCE_MTRC_VAL,
EXP_RECON_MTRC_CALC.O_TARGET_SQL_VALUE as TARGET_MTRC_VAL,
EXP_RECON_MTRC_CALC.DIFF_MTRC_VAL as DIFF_MTRC_VAL,
EXP_RECON_MTRC_CALC.THRSH_VAL as THRSH_VAL,
EXP_RECON_MTRC_CALC.THRSH_VAL_CALC_MTHD as THRSH_VAL_CALC_MTHD,
EXP_RECON_MTRC_CALC.DIFF_MTRC_VAL_OVER_THRSH as DIFF_MTRC_VAL_OVR_THRSH,
EXP_RECON_MTRC_CALC.PRIOR_DIFF_MTRC_VAL as PRIOR_DIFF_MTRC_VAL,
EXP_RECON_MTRC_CALC.O_PCT_CHG_DIFF_MTRC_VAL as PCT_CHG_DIFF_MTRC_VAL,
EXP_RECON_MTRC_CALC.CMPRSN_DATE as CMPRSN_DT,
EXP_RECON_MTRC_CALC.MTRC_ORIGN as MTRC_ORIGN,
EXP_RECON_MTRC_CALC.MTRC_DESC as MTRC_DESC,
EXP_RECON_MTRC_CALC.LAOD_DTTM as LOAD_DTTM,
EXP_RECON_MTRC_CALC.PRCS_ID as PRCS_ID
FROM
EXP_RECON_MTRC_CALC;


END; ';