-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_ACCTBLY_DTL_INS("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE
  run_id STRING;
  workflow_name STRING;
  session_name STRING;
BEGIN
  run_id := public.func_get_scoped_param(:run_id, ''run_id'', :workflow_name, :worklet_name, :session_name);
  workflow_name := public.func_get_scoped_param(:run_id, ''workflow_name'', :workflow_name, :worklet_name, :session_name);
  session_name := public.func_get_scoped_param(:run_id, ''session_name'', :workflow_name, :worklet_name, :session_name);
 

-- Component LKP_ACCTBLY_TYPE_CD_A, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_CD_A AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG,
ACCTBLY_TYPE_REF,
EFF_DT,
EXPN_DT
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component LKP_ACCTBLY_TYPE_CD_B, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_CD_B AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG,
ACCTBLY_TYPE_REF,
EFF_DT,
EXPN_DT
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component LKP_ACCTBLY_TYPE_CD_C, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_CD_C AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG,
ACCTBLY_TYPE_REF,
EFF_DT,
EXPN_DT
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component LKP_ACCTBLY_TYPE_CD_D, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_CD_D AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG,
ACCTBLY_TYPE_REF,
EFF_DT,
EXPN_DT
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component LKP_ACCTBLY_TYPE_CD_E, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_CD_E AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG,
ACCTBLY_TYPE_REF,
EFF_DT,
EXPN_DT
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component LKP_ACCTBLY_TYPE_CD_F, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_CD_F AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG,
ACCTBLY_TYPE_REF,
EFF_DT,
EXPN_DT
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component LKP_ACCTBLY_TYPE_CD_G, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_CD_G AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG,
--ACCTBLY_TYPE_CD_G,
ACCTBLY_TYPE_REF,
EFF_DT,
EXPN_DT
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component SQ_ACCTBLY_PTS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ACCTBLY_PTS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as AGENT_NBR,
$2 as DATE_WRITTEN,
$3 as DATE_USED,
$4 as STATE_NBR,
$5 as DISTRICT,
$6 as REGION,
$7 as SERVICE_CENTER,
$8 as POINT_1_AMT,
$9 as POINT_1_IND,
$10 as POINT_2_AMT,
$11 as POINT_2_IND,
$12 as POINT_3_AMT,
$13 as POINT_3_IND,
$14 as POINT_4_AMT,
$15 as POINT_4_IND,
$16 as POINT_5_AMT,
$17 as POINT_5_IND,
$18 as POINT_6_AMT,
$19 as POINT_6_IND,
$20 as POINT_7_AMT,
$21 as POINT_7_IND,
$22 as TOTAL_POINTS,
$23 as UPDATE_DATE,
$24 as UPDATE_TIME,
$25 as UPDATE_SOURCE,
$26 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT	AGENT_NBR, DATE_WRITTEN, 

DATE_USED, 

STATE_NBR, 

DISTRICT,

REGION, 

SERVICE_CENTER, 

POINT_1_AMT, 

POINT_1_IND, 

POINT_2_AMT,

POINT_2_IND, 

POINT_3_AMT, 

POINT_3_IND, 

POINT_4_AMT, 

POINT_4_IND,

POINT_5_AMT, 

POINT_5_IND, 

POINT_6_AMT, 

POINT_6_IND, 

POINT_7_AMT,

POINT_7_IND,

TOTAL_POINTS, 

UPDATE_DATE, 

UPDATE_TIME, 

UPDATE_SOURCE,

PRCS_ID

FROM	db_t_prod_stag.ACCTBLY_PTS

/*WHERE DATE_WRITTEN >= ''$CAL_START_DT''

AND DATE_WRITTEN <= ''$CAL_END_DT''*/
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_ACCTBLY_PTS.AGENT_NBR as AGENT_NBR,
SQ_ACCTBLY_PTS.DATE_WRITTEN as DATE_WRITTEN,
SQ_ACCTBLY_PTS.DATE_USED as DATE_USED,
DECODE ( SQ_ACCTBLY_PTS.STATE_NBR , 1 , ''AL'' , 10 , ''GA'' , 28 , ''MS'' ) as out_STATE_CD,
SQ_ACCTBLY_PTS.DISTRICT as DISTRICT,
SQ_ACCTBLY_PTS.REGION as REGION,
SQ_ACCTBLY_PTS.SERVICE_CENTER as SERVICE_CENTER,
LKP_1.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_CD_A */ as ACCTBLY_TYPE_CD_A,
SQ_ACCTBLY_PTS.POINT_1_AMT as POINT_1_AMT,
SQ_ACCTBLY_PTS.POINT_1_IND as POINT_1_IND,
LKP_2.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_CD_B */ as ACCTBLY_TYPE_CD_B,
SQ_ACCTBLY_PTS.POINT_2_AMT as POINT_2_AMT,
SQ_ACCTBLY_PTS.POINT_2_IND as POINT_2_IND,
LKP_3.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_CD_C */ as ACCTBLY_TYPE_CD_C,
SQ_ACCTBLY_PTS.POINT_3_AMT as POINT_3_AMT,
SQ_ACCTBLY_PTS.POINT_3_IND as POINT_3_IND,
LKP_4.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_CD_D */ as ACCTBLY_TYPE_CD_D,
SQ_ACCTBLY_PTS.POINT_4_AMT as POINT_4_AMT,
SQ_ACCTBLY_PTS.POINT_4_IND as POINT_4_IND,
LKP_5.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_CD_E */ as ACCTBLY_TYPE_CD_E,
SQ_ACCTBLY_PTS.POINT_5_AMT as POINT_5_AMT,
SQ_ACCTBLY_PTS.POINT_5_IND as POINT_5_IND,
LKP_6.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_CD_F */ as ACCTBLY_TYPE_CD_F,
SQ_ACCTBLY_PTS.POINT_6_AMT as POINT_6_AMT,
SQ_ACCTBLY_PTS.POINT_6_IND as POINT_6_IND,
LKP_7.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_CD_G */ as ACCTBLY_TYPE_CD_G,
SQ_ACCTBLY_PTS.POINT_7_AMT as POINT_7_AMT,
SQ_ACCTBLY_PTS.POINT_7_IND as POINT_7_IND,
SQ_ACCTBLY_PTS.TOTAL_POINTS as TOTAL_POINTS,
SQ_ACCTBLY_PTS.source_record_id,
row_number() over (partition by SQ_ACCTBLY_PTS.source_record_id order by SQ_ACCTBLY_PTS.source_record_id) as RNK
FROM
SQ_ACCTBLY_PTS
LEFT JOIN LKP_ACCTBLY_TYPE_CD_A LKP_1 ON LKP_1.ACCTBLY_TYPE_REF = ''ACCTBLY_TYPE_CD_A'' AND LKP_1.EFF_DT <= SQ_ACCTBLY_PTS.DATE_WRITTEN AND LKP_1.EXPN_DT >= SQ_ACCTBLY_PTS.DATE_WRITTEN
LEFT JOIN LKP_ACCTBLY_TYPE_CD_B LKP_2 ON LKP_2.ACCTBLY_TYPE_REF = ''ACCTBLY_TYPE_CD_B'' AND LKP_2.EFF_DT <= SQ_ACCTBLY_PTS.DATE_WRITTEN AND LKP_2.EXPN_DT >= SQ_ACCTBLY_PTS.DATE_WRITTEN
LEFT JOIN LKP_ACCTBLY_TYPE_CD_C LKP_3 ON LKP_3.ACCTBLY_TYPE_REF = ''ACCTBLY_TYPE_CD_C'' AND LKP_3.EFF_DT <= SQ_ACCTBLY_PTS.DATE_WRITTEN AND LKP_3.EXPN_DT >= SQ_ACCTBLY_PTS.DATE_WRITTEN
LEFT JOIN LKP_ACCTBLY_TYPE_CD_D LKP_4 ON LKP_4.ACCTBLY_TYPE_REF = CASE WHEN SQ_ACCTBLY_PTS.STATE_NBR = 1 THEN ''ACCTBLY_TYPE_CD_D_AL'' ELSE ''ACCTBLY_TYPE_CD_D_GAMS'' END AND LKP_4.EFF_DT <= SQ_ACCTBLY_PTS.DATE_WRITTEN AND LKP_4.EXPN_DT >= SQ_ACCTBLY_PTS.DATE_WRITTEN
LEFT JOIN LKP_ACCTBLY_TYPE_CD_E LKP_5 ON LKP_5.ACCTBLY_TYPE_REF = ''ACCTBLY_TYPE_CD_E'' AND LKP_5.EFF_DT <= SQ_ACCTBLY_PTS.DATE_WRITTEN AND LKP_5.EXPN_DT >= SQ_ACCTBLY_PTS.DATE_WRITTEN
LEFT JOIN LKP_ACCTBLY_TYPE_CD_F LKP_6 ON LKP_6.ACCTBLY_TYPE_REF = ''ACCTBLY_TYPE_CD_F'' AND LKP_6.EFF_DT <= SQ_ACCTBLY_PTS.DATE_WRITTEN AND LKP_6.EXPN_DT >= SQ_ACCTBLY_PTS.DATE_WRITTEN
LEFT JOIN LKP_ACCTBLY_TYPE_CD_G LKP_7 ON LKP_7.ACCTBLY_TYPE_REF = ''ACCTBLY_TYPE_CD_G'' AND LKP_7.EFF_DT <= SQ_ACCTBLY_PTS.DATE_WRITTEN AND LKP_7.EXPN_DT >= SQ_ACCTBLY_PTS.DATE_WRITTEN
QUALIFY RNK = 1
);


-- Component ACCTBLY_DTL, Type TARGET 
INSERT INTO db_t_prod_comn.ACCTBLY_DTL
(
AGENT_NBR,
STATE_CD,
SERVICE_CENTER,
ACCOUNTING_DT,
DSTRCT,
RGN,
ACCTBLY_TYPE_CD_A,
ACCTBLY_VAL_A,
ACCTBLY_PTS_A,
ACCTBLY_TYPE_CD_B,
ACCTBLY_VAL_B,
ACCTBLY_PTS_B,
ACCTBLY_TYPE_CD_C,
ACCTBLY_VAL_C,
ACCTBLY_PTS_C,
ACCTBLY_TYPE_CD_D,
ACCTBLY_VAL_D,
ACCTBLY_PTS_D,
ACCTBLY_TYPE_CD_E,
ACCTBLY_VAL_E,
ACCTBLY_PTS_E,
ACCTBLY_TYPE_CD_F,
ACCTBLY_VAL_F,
ACCTBLY_PTS_F,
ACCTBLY_TYPE_CD_G,
ACCTBLY_VAL_G,
ACCTBLY_PTS_G,
ACCTBLY_PTS_TOT,
REPORTING_DT
)
SELECT
EXPTRANS.AGENT_NBR as AGENT_NBR,
EXPTRANS.out_STATE_CD as STATE_CD,
EXPTRANS.SERVICE_CENTER as SERVICE_CENTER,
EXPTRANS.DATE_WRITTEN as ACCOUNTING_DT,
EXPTRANS.DISTRICT as DSTRCT,
EXPTRANS.REGION as RGN,
EXPTRANS.ACCTBLY_TYPE_CD_A as ACCTBLY_TYPE_CD_A,
EXPTRANS.POINT_1_AMT as ACCTBLY_VAL_A,
EXPTRANS.POINT_1_IND as ACCTBLY_PTS_A,
EXPTRANS.ACCTBLY_TYPE_CD_B as ACCTBLY_TYPE_CD_B,
EXPTRANS.POINT_2_AMT as ACCTBLY_VAL_B,
EXPTRANS.POINT_2_IND as ACCTBLY_PTS_B,
EXPTRANS.ACCTBLY_TYPE_CD_C as ACCTBLY_TYPE_CD_C,
EXPTRANS.POINT_3_AMT as ACCTBLY_VAL_C,
EXPTRANS.POINT_3_IND as ACCTBLY_PTS_C,
EXPTRANS.ACCTBLY_TYPE_CD_D as ACCTBLY_TYPE_CD_D,
EXPTRANS.POINT_4_AMT as ACCTBLY_VAL_D,
EXPTRANS.POINT_4_IND as ACCTBLY_PTS_D,
EXPTRANS.ACCTBLY_TYPE_CD_E as ACCTBLY_TYPE_CD_E,
EXPTRANS.POINT_5_AMT as ACCTBLY_VAL_E,
EXPTRANS.POINT_5_IND as ACCTBLY_PTS_E,
EXPTRANS.ACCTBLY_TYPE_CD_F as ACCTBLY_TYPE_CD_F,
EXPTRANS.POINT_6_AMT as ACCTBLY_VAL_F,
EXPTRANS.POINT_6_IND as ACCTBLY_PTS_F,
EXPTRANS.ACCTBLY_TYPE_CD_G as ACCTBLY_TYPE_CD_G,
EXPTRANS.POINT_7_AMT as ACCTBLY_VAL_G,
EXPTRANS.POINT_7_IND as ACCTBLY_PTS_G,
EXPTRANS.TOTAL_POINTS as ACCTBLY_PTS_TOT,
EXPTRANS.DATE_USED as REPORTING_DT
FROM
EXPTRANS;


END; ';