-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BIBASE_D_HOME_PLCY("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE
  CAL_END_DT STRING;
  CAL_END_MTH_ID STRING;
  run_id STRING;
  workflow_name STRING;
  session_name STRING;
BEGIN
  run_id := public.func_get_scoped_param(:run_id, ''run_id'', :workflow_name, :worklet_name, :session_name);
  workflow_name := public.func_get_scoped_param(:run_id, ''workflow_name'', :workflow_name, :worklet_name, :session_name);
  session_name := public.func_get_scoped_param(:run_id, ''session_name'', :workflow_name, :worklet_name, :session_name);

  CAL_END_DT := public.func_get_scoped_param(:run_id, ''cal_end_dt'', :workflow_name, :worklet_name, :session_name);
  CAL_END_MTH_ID := public.func_get_scoped_param(:run_id, ''cal_end_mth_id'', :workflow_name, :worklet_name, :session_name);
 

-- Component sq_AGMT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_AGMT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as MO_ID,
$2 as PRODUCER_ID,
$3 as BUSN_TYPE_CD,
$4 as PLCY_NUM,
$5 as FRST_NAME,
$6 as LAST_NAME,
$7 as AGNT_NUM,
$8 as SRVC_CTR_NUM,
$9 as HO4_IND,
$10 as SRC_SYS_CD,
$11 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT

:CAL_END_MTH_ID AS MO_ID,

CAST(AGNT_NUM AS INTEGER) AS PRODUCER_ID,

 CASE WHEN (PREV.HOST_AGMT_NUM  IS  NULL AND  AG.PLCY_NBR NOT  LIKE ''H%'') THEN ''NEW'' ELSE ''EXISTING'' END BUSN_TYPE_CD

,PLCY_NBR

,GVN_NAME AS FRST_NAME

,FMLY_NAME AS LAST_NAME

,AGNT_NUM AS AGNT_NUM

,SC_NUM AS SRVC_CTR_NUM

, MAX(CASE WHEN (PROD_NAME LIKE ''%HO4%'') THEN ''Y'' ELSE ''N'' END) HO4_IND

,''GW'' AS SRC_SYS_CD

 FROM 

(

SELECT A.AGMT_ID,  ast.AGMT_STS_CD,

A.HOST_AGMT_NUM PLCY_NBR,P.PROD_NAME,a.CNTNUS_SRVC_DTTM,

CASE WHEN a.MODL_EFF_DTTM > a.MODL_CRTN_DTTM THEN a.MODL_EFF_DTTM 

ELSE a.MODL_CRTN_DTTM END AS NEW_AGMT_EFF_DTTM 
FROM  db_t_prod_core.AGMT AS A 

JOIN  db_t_prod_core.AGMT TRM 

ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM 

and    TRM.AGMT_TYPE_CD=''POLTRM''   AND CAST(CAST(:CAL_END_DT AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' 

BETWEEN trm.AGMT_EFF_DTTM AND trm.AGMT_PLND_EXPN_DTTM 

AND A.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

JOIN db_t_prod_core.AGMT_STS  AS AS1  ON  TRM.AGMT_ID=AS1.AGMT_ID 

AND AS1.AGMT_STS_STRT_DTTM <= CAST(CAST(:CAL_END_DT AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND'' 

and NEW_AGMT_EFF_DTTM < CAST(CAST(:CAL_END_DT  AS DATE)+1 AS TIMESTAMP(6)) - INTERVAL ''0.000001 SECOND''

AND A.AGMT_TYPE_CD = ''PPV'' AND AS1.AGMT_STS_CD <> ''CNFRMDDT'' 

JOIN db_t_prod_core.AGMT_PROD  AS AP ON A.AGMT_ID=AP.AGMT_ID  AND AP.AGMT_PROD_ROLE_CD=''PLCYTYPE''

AND  :CAL_END_DT  BETWEEN CAST(AP.AGMT_PROD_STRT_DTTM AS DATE) AND CAST(AP.AGMT_PROD_END_DTTM AS DATE)

JOIN db_t_prod_core.PROD  P ON AP.PROD_ID=P.PROD_ID 

AND :CAL_END_DT BETWEEN CAST(P.PROD_STRT_DTTM AS DATE) AND CAST(P.PROD_END_DTTM AS DATE)

AND P.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

LEFT OUTER JOIN db_t_prod_core.AGMT_STS_TYPE AST ON AS1.AGMT_STS_CD = AST.AGMT_STS_CD 

LEFT OUTER JOIN db_t_prod_core.AGMT_MBRSHP  AS AM ON  A.AGMT_ID=AM.AGMT_ID

 AND :CAL_END_DT BETWEEN CAST(AM.AGMT_MBRSHP_STRT_DTTM AS DATE) AND CAST(AM.AGMT_MBRSHP_END_DTTM AS DATE)

LEFT OUTER JOIN db_t_prod_core.MBRSHP   AS M ON M.MBRSHP_ID=AM.MBRSHP_ID AND CAST(M.EDW_END_DTTM AS DATE) =CAST( ''9999-12-31''  AS DATE)

WHERE 	  P.PROD_NAME like ''HO%''

QUALIFY ROW_NUMBER() OVER(PARTITION BY A.HOST_AGMT_NUM ORDER BY A.MODL_CRTN_DTTM DESC, A.MODL_EFF_DTTM DESC,  AS1.AGMT_STS_STRT_DTTM DESC, AS1.EDW_END_DTTM DESC) = 1



and ast.AGMT_STS_CD =''inforce''

) AG

left outer join 

(SELECT AGMT_ID,

MAX(GVN_NAME) AS GVN_NAME,

MAX(FMLY_NAME) AS FMLY_NAME,

MAX(AGNT_NUM) AS AGNT_NUM, 

MAX(SC_NUM) AS SC_NUM 

FROM (

SELECT PA.AGMT_ID,

CASE WHEN  PA.PRTY_AGMT_ROLE_CD = ''PLCYPRININS'' THEN  UPPER(COALESCE(TRIM(INM.GVN_NAME), ORG_NAME)) END AS GVN_NAME,

CASE WHEN  PA.PRTY_AGMT_ROLE_CD = ''PLCYPRININS'' THEN UPPER(TRIM(INM.FMLY_NAME)) END AS FMLY_NAME,

CASE WHEN  PA.PRTY_AGMT_ROLE_CD = ''PRDA'' THEN  ltrim(IO.INTRNL_ORG_NUM,''0'') END AS AGNT_NUM, 

CASE WHEN  PA.PRTY_AGMT_ROLE_CD = ''SVC'' THEN  ltrim(IO.INTRNL_ORG_NUM,''0'') END AS SC_NUM

FROM  db_t_prod_core.PRTY_AGMT AS PA  

LEFT OUTER JOIN db_t_prod_core.INDIV_NAME AS INM ON PA.PRTY_ID = INM.INDIV_PRTY_ID AND  PA.PRTY_AGMT_ROLE_CD IN (''PLCYPRININS'') 

LEFT OUTER JOIN db_t_prod_core.ORG_NAME AS ORN ON PA.PRTY_ID = ORN.PRTY_ID 

LEFT OUTER JOIN db_t_prod_core.INTRNL_ORG AS IO ON PA.PRTY_ID = IO.INTRNL_ORG_PRTY_ID AND 

PA.PRTY_AGMT_ROLE_CD = CASE WHEN IO.INTRNL_ORG_SBTYPE_CD = ''SRVCCTR'' THEN ''SVC'' ELSE IO.INTRNL_ORG_SBTYPE_CD END  

WHERE 

 PA.PRTY_AGMT_ROLE_CD IN (''PLCYPRININS'',''PRDA'',''SVC'')

QUALIFY ROW_NUMBER() OVER(PARTITION BY PA.AGMT_ID,PA.PRTY_ID,PA.PRTY_AGMT_ROLE_CD ORDER BY PA.PRTY_AGMT_STRT_DTTM DESC, PA.TRANS_STRT_DTTM  DESC)=1

) T1 

GROUP BY 1 )SVC_AGNT  ON AG.AGMT_ID=SVC_AGNT.AGMT_ID

LEFT OUTER JOIN   db_t_prod_core.AGMT PREV ON

PREV.HOST_AGMT_NUM =AG.PLCY_NBR AND PREV.AGMT_TYPE_CD=''PPV'' 

AND CAST(PREV.MODL_EFF_DTTM AS DATE)<=ADD_MONTHS(CAST(:CAL_END_DT AS DATE),-1)

AND SRC_SYS_CD=''GWPC''

WHERE  AGMT_STS_CD IN (''INFORCE'',''RNEWLLAPSD'',''CNFRMD'')

GROUP BY 1,2,3,4,5,6,7,8
) SRC
)
);


-- Component LKP_PLCY_XREF, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_PLCY_XREF AS
(
SELECT
LKP.PLCY_ID,
sq_AGMT.PLCY_NUM as PLCY_NUM,
sq_AGMT.source_record_id,
ROW_NUMBER() OVER(PARTITION BY sq_AGMT.source_record_id ORDER BY LKP.PLCY_ID asc) RNK
FROM
sq_AGMT
LEFT JOIN (
SELECT PLCY_ID as PLCY_ID, PLCY_NBR as PLCY_NBR 
FROM db_v_prod_pres.PLCY_XREF
WHERE SRC_TYPE=''GW''
QUALIFY ROW_NUMBER() OVER (PARTITION BY PLCY_NBR ORDER BY EDW_END_DTTM DESC)=1
) LKP ON -- msiing join condition
sq_AGMT.PLCY_NUM = LKP.PLCY_NBR
QUALIFY RNK = 1
);


-- Component exp_Passthrough, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Passthrough AS
(
SELECT
LKP_PLCY_XREF.PLCY_ID as PLCY_ID,
sq_AGMT.MO_ID as MO_ID,
sq_AGMT.PRODUCER_ID as PRODUCER_ID,
sq_AGMT.BUSN_TYPE_CD as BUSN_TYPE_CD,
LKP_PLCY_XREF.PLCY_NUM as PLCY_NUM,
sq_AGMT.FRST_NAME as FRST_NAME,
sq_AGMT.LAST_NAME as LAST_NAME,
sq_AGMT.AGNT_NUM as AGNT_NUM,
sq_AGMT.SRVC_CTR_NUM as SRVC_CTR_NUM,
sq_AGMT.HO4_IND as HO4_IND,
sq_AGMT.SRC_SYS_CD as SRC_SYS_CD,
sq_AGMT.source_record_id
FROM
sq_AGMT
INNER JOIN LKP_PLCY_XREF ON sq_AGMT.source_record_id = LKP_PLCY_XREF.source_record_id
);


-- Component fil_invalid_policy, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE fil_invalid_policy AS
(
SELECT
exp_Passthrough.PLCY_ID as PLCY_ID,
exp_Passthrough.MO_ID as MO_ID,
exp_Passthrough.PRODUCER_ID as PRODUCER_ID,
exp_Passthrough.BUSN_TYPE_CD as BUSN_TYPE_CD,
exp_Passthrough.PLCY_NUM as PLCY_NUM,
exp_Passthrough.FRST_NAME as FRST_NAME,
exp_Passthrough.LAST_NAME as LAST_NAME,
exp_Passthrough.AGNT_NUM as AGNT_NUM,
exp_Passthrough.SRVC_CTR_NUM as SRVC_CTR_NUM,
exp_Passthrough.HO4_IND as HO4_IND,
exp_Passthrough.SRC_SYS_CD as SRC_SYS_CD,
exp_Passthrough.source_record_id
FROM
exp_Passthrough
WHERE exp_Passthrough.PLCY_ID IS NOT NULL
);


-- Component D_HOME_PLCY, Type TARGET 
INSERT INTO db_v_prod_pres.D_HOME_PLCY
(
PLCY_ID,
MO_ID,
PRODUCER_ID,
BUSN_TYPE_CD,
PLCY_NUM,
FRST_NAME,
LAST_NAME,
AGNT_NUM,
SRVC_CTR_NUM,
HO4_IND,
SRC_SYS_CD
)
SELECT
fil_invalid_policy.PLCY_ID as PLCY_ID,
fil_invalid_policy.MO_ID as MO_ID,
fil_invalid_policy.PRODUCER_ID as PRODUCER_ID,
fil_invalid_policy.BUSN_TYPE_CD as BUSN_TYPE_CD,
fil_invalid_policy.PLCY_NUM as PLCY_NUM,
fil_invalid_policy.FRST_NAME as FRST_NAME,
fil_invalid_policy.LAST_NAME as LAST_NAME,
fil_invalid_policy.AGNT_NUM as AGNT_NUM,
fil_invalid_policy.SRVC_CTR_NUM as SRVC_CTR_NUM,
fil_invalid_policy.HO4_IND as HO4_IND,
fil_invalid_policy.SRC_SYS_CD as SRC_SYS_CD
FROM
fil_invalid_policy;


END; ';