-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BAL_SRC_TO_PRESTG_STG("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
	run_id STRING;
	workflow_name STRING;
	session_name STRING;
	TGT_NM STRING;
    PRGM_NM STRING;
    ACT_PROJ_ID STRING;
    BATCH_ACTIVE_IND STRING;
    temp_sql STRING;
	v_start_time TIMESTAMP;
BEGIN
	run_id := (SELECT run_id FROM control_run_id WHERE worklet_name = :worklet_name ORDER BY insert_ts DESC LIMIT 1);
	workflow_name := (SELECT workflow_name FROM control_run_id WHERE worklet_name = :worklet_name ORDER BY insert_ts DESC LIMIT 1);
	session_name := ''s_m_BAL_SRC_TO_PRESTG_STG'';
	TGT_NM := public.func_get_scoped_param(:run_id, ''TGT_NM'', :workflow_name, :worklet_name, :session_name);
	PRGM_NM := public.func_get_scoped_param(:run_id, ''PRGM_NM'', :workflow_name, :worklet_name, :session_name);
	ACT_PROJ_ID := public.func_get_scoped_param(:run_id, ''ACT_PROJ_ID'', :workflow_name, :worklet_name, :session_name);
	BATCH_ACTIVE_IND := public.func_get_scoped_param(:run_id, ''BATCH_ACTIVE_IND'', :workflow_name, :worklet_name, :session_name);
	v_start_time := CURRENT_TIMESTAMP();

-- Component sq_TGT_FILE, Type SOURCE 

temp_sql := ''
CREATE OR REPLACE TEMPORARY TABLE sq_TGT_FILE AS
SELECT COUNT(*) AS RECORD_CNT,
       ''''1'''' AS DUMMY,
       ROW_NUMBER() OVER (ORDER BY 1) AS source_record_id
FROM '' || :TGT_NM;

EXECUTE IMMEDIATE :temp_sql;


-- Component exp_INTEGER_CONVERSION, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_INTEGER_CONVERSION AS
(
SELECT
TO_NUMBER(LTRIM ( RTRIM ( sq_TGT_FILE.RECORD_CNT ) )) as out_RECORD_CNT,
TO_NUMBER(LTRIM ( RTRIM ( sq_TGT_FILE.DUMMY ) )) as out_DUMMY,
sq_TGT_FILE.source_record_id
FROM
sq_TGT_FILE
);


-- Component SQ_TRG_FILE_SRC, Type TABLE_DDL Creating an empty table
CREATE OR REPLACE TEMPORARY TABLE SQ_TRG_FILE
(
FEED_IND varchar(1),
FEED_DATE varchar(29),
RECORD_CNT integer,
source_record_id number autoincrement start 1 increment 1
);


-- Component SQ_TRG_FILE_SRC, Type IMPORT_DATA Importing Data
;


-- Component exp_FEED_CNT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_FEED_CNT AS
(
SELECT
SQ_TRG_FILE.RECORD_CNT as RECORD_CNT,
1 as DUMMY,
SQ_TRG_FILE.source_record_id
FROM
SQ_TRG_FILE
);


-- Component jnr_SRC_TGT, Type JOINER 
CREATE OR REPLACE TEMPORARY TABLE jnr_SRC_TGT AS
(
SELECT
exp_FEED_CNT.RECORD_CNT as RECORD_CNT_FEED,
exp_FEED_CNT.DUMMY as DUMMY_FEED,
exp_INTEGER_CONVERSION.out_RECORD_CNT as RECORD_CNT_TRGT,
exp_INTEGER_CONVERSION.out_DUMMY as DUMMY_TRGT,
row_number() over (order by 1) AS source_record_id
FROM
exp_INTEGER_CONVERSION
INNER JOIN exp_FEED_CNT ON exp_INTEGER_CONVERSION.out_DUMMY = exp_FEED_CNT.DUMMY
);


-- Component exp_MSG_DESCRIPTION, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_MSG_DESCRIPTION AS
(
SELECT
jnr_SRC_TGT.RECORD_CNT_FEED as RECORD_CNT_FEED,
jnr_SRC_TGT.RECORD_CNT_TRGT as RECORD_CNT_TRGT,
0 as out_TARGET_UPD,
0 as out_TARGET_DEL,
jnr_SRC_TGT.RECORD_CNT_FEED - jnr_SRC_TGT.RECORD_CNT_TRGT as var_TARGET_REJ,
var_TARGET_REJ as out_TARGET_REJ,
CASE WHEN ( var_TARGET_REJ = 0 ) THEN ''SOURCE COUNT AND TARGET COUNT ARE EQUALLY BALANCED'' ELSE ''SOURCE COUNT AND TARGET COUNT ARE NOT EQUALLY BALANCED'' END as out_MSG_DESCRIPTION,
CURRENT_TIMESTAMP as in_ORIG_TS,
:PRGM_NM as in_PROGRAM_NAME,
:ACT_PROJ_ID as in_ACT_PROJ_ID,
:BATCH_ACTIVE_IND as in_BATCH_ACTIVE_IND,
:TGT_NM as in_TABLE_NM,
jnr_SRC_TGT.source_record_id
FROM
jnr_SRC_TGT
);


-- Component mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, Type MAPPLET 
--MAPPLET NOT REGISTERED: mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE, mapplet instance mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE;
CALL mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE(''exp_MSG_DESCRIPTION'');


-- Component ECTL_AUDIT_LOG_1, Type TARGET 
INSERT INTO DB_T_CTRL_FIN_PROD.ECTL_AUDIT_LOG
(
ECTL_BATCH_ID,
ECTL_PRGM_ID,
ECTL_TABLE_ID,
ECTL_SRC_ROW_CNT,
ECTL_TRGT_INS_CNT,
ECTL_TRGT_UPD_CNT,
ECTL_TRGT_DEL_CNT,
ECTL_TRGT_REJ_CNT,
ECTL_MESSAGE_TXT,
ECTL_ORIG_INS_TS
)
SELECT
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_BATCH_ID as ECTL_BATCH_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_PRGM_ID as ECTL_PRGM_ID,
mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.out_ECTL_TABLE_ID as ECTL_TABLE_ID,
exp_MSG_DESCRIPTION.RECORD_CNT_FEED as ECTL_SRC_ROW_CNT,
exp_MSG_DESCRIPTION.RECORD_CNT_TRGT as ECTL_TRGT_INS_CNT,
exp_MSG_DESCRIPTION.out_TARGET_UPD as ECTL_TRGT_UPD_CNT,
exp_MSG_DESCRIPTION.out_TARGET_DEL as ECTL_TRGT_DEL_CNT,
exp_MSG_DESCRIPTION.out_TARGET_REJ as ECTL_TRGT_REJ_CNT,
exp_MSG_DESCRIPTION.out_MSG_DESCRIPTION as ECTL_MESSAGE_TXT,
exp_MSG_DESCRIPTION.out_ORIG_TS as ECTL_ORIG_INS_TS
FROM
exp_MSG_DESCRIPTION
INNER JOIN mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE ON exp_MSG_DESCRIPTION.source_record_id = mplt_LKP_ECTL_BATCH_PRGM_VALIDATION_CORE.source_record_id;


-- PIPELINE START FOR 2

-- Component sq_ECTL_AUDIT_LOG, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_ECTL_AUDIT_LOG AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ECTL_BATCH_ID,
$2 as ECTL_PRGM_ID,
$3 as ECTL_TABLE_ID,
$4 as ECTL_TRGT_REJ_CNT,
$5 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT ECTL_BATCH_ID,ECTL_PRGM_ID,ECTL_TABLE_ID  , ECTL_TRGT_REJ_CNT FROM DB_T_CTRL_FIN_PROD.ECTL_AUDIT_LOG WHERE ECTL_BATCH_ID =(SELECT ECTL_BATCH_ID FROM DB_T_CTRL_FIN_PROD.ECTL_BATCH_INFO WHERE ECTL_PROJ_ID = :ACT_PROJ_ID AND ECTL_ACTIVE_IND ='':BATCH_ACTIVE_IND'') AND ECTL_PRGM_ID = (SELECT ECTL_PRGM_ID FROM DB_T_CTRL_FIN_PROD.ECTL_PRGM_INFO WHERE ECTL_PRGM_NM ='':PRGM_NM'') AND ECTL_TABLE_ID =(SELECT ECTL_TABLE_ID FROM DB_T_CTRL_FIN_PROD.ECTL_TABLE_XREF WHERE ECTL_TABLE_NM ='':TGT_NM'')
) SRC
)
);


-- Component exp_CHECK, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_CHECK AS
(
SELECT
''SUCCESS'' as out_SUCCESS,
CASE WHEN ( sq_ECTL_AUDIT_LOG.ECTL_TRGT_REJ_CNT <> 0 ) THEN RAISE_ERROR(''AUDIT BALANCING FAILED FOR '' || :TGT_NM) ELSE NULL END as var_CHECK,
sq_ECTL_AUDIT_LOG.ECTL_PRGM_ID as ECTL_PRGM_ID,
sq_ECTL_AUDIT_LOG.ECTL_TABLE_ID as ECTL_TABLE_ID,
sq_ECTL_AUDIT_LOG.ECTL_BATCH_ID as ECTL_BATCH_ID,
sq_ECTL_AUDIT_LOG.source_record_id
FROM
sq_ECTL_AUDIT_LOG
);


-- Component fil_SUCCESS, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE fil_SUCCESS AS
(
SELECT
exp_CHECK.out_SUCCESS as out_SUCCESS,
exp_CHECK.ECTL_PRGM_ID as ECTL_PRGM_ID,
exp_CHECK.ECTL_TABLE_ID as ECTL_TABLE_ID,
exp_CHECK.ECTL_BATCH_ID as ECTL_BATCH_ID,
exp_CHECK.source_record_id
FROM
exp_CHECK
WHERE exp_CHECK.out_SUCCESS <> ''SUCCESS''
);


-- Component ECTL_AUDIT_LOG1, Type TARGET 
INSERT INTO DB_T_CTRL_FIN_PROD.ECTL_AUDIT_LOG
(
ECTL_BATCH_ID,
ECTL_PRGM_ID,
ECTL_TABLE_ID,
ECTL_MESSAGE_TXT
)
SELECT
fil_SUCCESS.ECTL_BATCH_ID as ECTL_BATCH_ID,
fil_SUCCESS.ECTL_PRGM_ID as ECTL_PRGM_ID,
fil_SUCCESS.ECTL_TABLE_ID as ECTL_TABLE_ID,
fil_SUCCESS.out_SUCCESS as ECTL_MESSAGE_TXT
FROM
fil_SUCCESS;


-- PIPELINE END FOR 2

END; ';