-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_ACCTBLY_TGT_INS("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE
  run_id STRING;
  workflow_name STRING;
  session_name STRING;
BEGIN
  run_id := public.func_get_scoped_param(:run_id, ''run_id'', :workflow_name, :worklet_name, :session_name);
  workflow_name := public.func_get_scoped_param(:run_id, ''workflow_name'', :workflow_name, :worklet_name, :session_name);
  session_name := public.func_get_scoped_param(:run_id, ''session_name'', :workflow_name, :worklet_name, :session_name);
 

-- Component LKP_ACCTBLY_TYPE_A, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_A AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component LKP_ACCTBLY_TYPE_B, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_B AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component LKP_ACCTBLY_TYPE_C, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_C AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component LKP_ACCTBLY_TYPE_D, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_D AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component LKP_ACCTBLY_TYPE_E, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_E AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component LKP_ACCTBLY_TYPE_F, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_F AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component LKP_ACCTBLY_TYPE_G, Type Prerequisite Lookup Object 
CREATE OR REPLACE TEMPORARY TABLE LKP_ACCTBLY_TYPE_G AS
(
SELECT
ACCTBLY_TYPE_CD,
ACCTBLY_TYPE_COMM_HDG
FROM db_t_prod_comn.ACCTBLY_TYPE_LKUP
);


-- Component SQ_ACCTBLY_TGT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_ACCTBLY_TGT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as DISTRICT,
$2 as REGION,
$3 as STATE_NBR,
$4 as AGENT_NBR,
$5 as EFFECTIVE_DATE,
$6 as EXPIRE_DATE,
$7 as POINT_1_HEADING,
$8 as POINT_1_TARGET,
$9 as POINT_2_HEADING,
$10 as POINT_2_TARGET,
$11 as POINT_3_HEADING,
$12 as POINT_3_TARGET,
$13 as POINT_4_HEADING,
$14 as POINT_4_TARGET,
$15 as POINT_5_HEADING,
$16 as POINT_5_TARGET,
$17 as POINT_6_HEADING,
$18 as POINT_6_TARGET,
$19 as POINT_7_HEADING,
$20 as POINT_7_TARGET,
$21 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT	DISTRICT, REGION, STATE_NBR, AGENT_NBR, EFFECTIVE_DATE, EXPIRE_DATE,

		POINT_1_HEADING, POINT_1_TARGET, POINT_2_HEADING, POINT_2_TARGET,

		POINT_3_HEADING, POINT_3_TARGET, POINT_4_HEADING, POINT_4_TARGET,

		POINT_5_HEADING, POINT_5_TARGET, POINT_6_HEADING, POINT_6_TARGET,

		POINT_7_HEADING, POINT_7_TARGET, (SELECT CAST (LAST_DAY(ADD_MONTHS(CURRENT_DATE, -1)) AS DATE)) AS ACCOUNTING_DT

		FROM	db_t_prod_stag.ACCTBLY_TGT
) SRC
)
);


-- Component EXPTRANS, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXPTRANS AS
(
SELECT
SQ_ACCTBLY_TGT.DISTRICT as DISTRICT,
SQ_ACCTBLY_TGT.REGION as REGION,
DECODE ( SQ_ACCTBLY_TGT.STATE_NBR , 1 , ''AL'' , 10 , ''GA'' , 28 , ''MS'' ) as out_STATE_CD,
SQ_ACCTBLY_TGT.AGENT_NBR as AGENT_NBR,
SQ_ACCTBLY_TGT.EFFECTIVE_DATE as EFFECTIVE_DATE,
SQ_ACCTBLY_TGT.EXPIRE_DATE as EXPIRE_DATE,
LKP_1.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_A */ as POINT_1_HEADING1,
SQ_ACCTBLY_TGT.POINT_1_TARGET as POINT_1_TARGET,
LKP_2.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_B */ as POINT_2_HEADING1,
SQ_ACCTBLY_TGT.POINT_2_TARGET as POINT_2_TARGET,
LKP_3.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_C */ as POINT_3_HEADING1,
SQ_ACCTBLY_TGT.POINT_3_TARGET as POINT_3_TARGET,
LKP_4.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_D */ as POINT_4_HEADING1,
SQ_ACCTBLY_TGT.POINT_4_TARGET as POINT_4_TARGET,
LKP_5.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_E */ as POINT_5_HEADING1,
SQ_ACCTBLY_TGT.POINT_5_TARGET as POINT_5_TARGET,
LKP_6.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_F */ as POINT_6_HEADING1,
SQ_ACCTBLY_TGT.POINT_6_TARGET as POINT_6_TARGET,
LKP_7.ACCTBLY_TYPE_CD /* replaced lookup LKP_ACCTBLY_TYPE_G */ as POINT_7_HEADING1,
SQ_ACCTBLY_TGT.POINT_7_TARGET as POINT_7_TARGET,
SQ_ACCTBLY_TGT.source_record_id,
row_number() over (partition by SQ_ACCTBLY_TGT.source_record_id order by SQ_ACCTBLY_TGT.source_record_id) as RNK
FROM
SQ_ACCTBLY_TGT
LEFT JOIN LKP_ACCTBLY_TYPE_A LKP_1 ON LKP_1.ACCTBLY_TYPE_COMM_HDG = SQ_ACCTBLY_TGT.POINT_1_HEADING
LEFT JOIN LKP_ACCTBLY_TYPE_B LKP_2 ON LKP_2.ACCTBLY_TYPE_COMM_HDG = SQ_ACCTBLY_TGT.POINT_2_HEADING
LEFT JOIN LKP_ACCTBLY_TYPE_C LKP_3 ON LKP_3.ACCTBLY_TYPE_COMM_HDG = SQ_ACCTBLY_TGT.POINT_3_HEADING
LEFT JOIN LKP_ACCTBLY_TYPE_D LKP_4 ON LKP_4.ACCTBLY_TYPE_COMM_HDG = SQ_ACCTBLY_TGT.POINT_4_HEADING
LEFT JOIN LKP_ACCTBLY_TYPE_E LKP_5 ON LKP_5.ACCTBLY_TYPE_COMM_HDG = SQ_ACCTBLY_TGT.POINT_5_HEADING
LEFT JOIN LKP_ACCTBLY_TYPE_F LKP_6 ON LKP_6.ACCTBLY_TYPE_COMM_HDG = SQ_ACCTBLY_TGT.POINT_6_HEADING
LEFT JOIN LKP_ACCTBLY_TYPE_G LKP_7 ON LKP_7.ACCTBLY_TYPE_COMM_HDG = SQ_ACCTBLY_TGT.POINT_7_HEADING
QUALIFY RNK = 1
);


-- Component ACCTBLY_TGT_1, Type TARGET 
INSERT INTO db_t_prod_comn.ACCTBLY_TGT
(
AGENT_NBR,
DSTRCT,
RGN,
STATE_CD,
ACCTBLY_TYPE_CD_A,
ACCTBLY_TGT_A,
ACCTBLY_TYPE_CD_B,
ACCTBLY_TGT_B,
ACCTBLY_TYPE_CD_C,
ACCTBLY_TGT_C,
ACCTBLY_TYPE_CD_D,
ACCTBLY_TGT_D,
ACCTBLY_TYPE_CD_E,
ACCTBLY_TGT_E,
ACCTBLY_TYPE_CD_F,
ACCTBLY_TGT_F,
ACCTBLY_TYPE_CD_G,
ACCTBLY_TGT_G,
EFFECTIVE_DT,
EXPIRATION_DT
)
SELECT
EXPTRANS.AGENT_NBR as AGENT_NBR,
EXPTRANS.DISTRICT as DSTRCT,
EXPTRANS.REGION as RGN,
EXPTRANS.out_STATE_CD as STATE_CD,
EXPTRANS.POINT_1_HEADING1 as ACCTBLY_TYPE_CD_A,
EXPTRANS.POINT_1_TARGET as ACCTBLY_TGT_A,
EXPTRANS.POINT_2_HEADING1 as ACCTBLY_TYPE_CD_B,
EXPTRANS.POINT_2_TARGET as ACCTBLY_TGT_B,
EXPTRANS.POINT_3_HEADING1 as ACCTBLY_TYPE_CD_C,
EXPTRANS.POINT_3_TARGET as ACCTBLY_TGT_C,
EXPTRANS.POINT_4_HEADING1 as ACCTBLY_TYPE_CD_D,
EXPTRANS.POINT_4_TARGET as ACCTBLY_TGT_D,
EXPTRANS.POINT_5_HEADING1 as ACCTBLY_TYPE_CD_E,
EXPTRANS.POINT_5_TARGET as ACCTBLY_TGT_E,
EXPTRANS.POINT_6_HEADING1 as ACCTBLY_TYPE_CD_F,
EXPTRANS.POINT_6_TARGET as ACCTBLY_TGT_F,
EXPTRANS.POINT_7_HEADING1 as ACCTBLY_TYPE_CD_G,
EXPTRANS.POINT_7_TARGET as ACCTBLY_TGT_G,
EXPTRANS.EFFECTIVE_DATE as EFFECTIVE_DT,
EXPTRANS.EXPIRE_DATE as EXPIRATION_DT
FROM
EXPTRANS;


END; ';