-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_WRK_FS_PLCY_INS("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS 'declare
run_id varchar;
	start_dttm timestamp;
	end_dttm timestamp;
    prcs_id int;
    FS_DATE date;
 
BEGIN 
run_id :=   (SELECT run_id   FROM control_run_id where worklet_name=:worklet_name order by insert_ts desc limit 1);   
END_DTTM:=   (SELECT left(param_value,19) FROM control_params where run_id = :run_id and upper(param_name)=''END_DTTM'');
START_DTTM:=     (SELECT left(param_value,19) FROM control_params where run_id = :run_id and upper(param_name)=''START_DTTM'');
PRCS_ID:=     (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''PRCS_ID'');
FS_DATE:=     (SELECT left(param_value,19) FROM control_params where FS_DATE = :FS_DATE and upper(param_name)=''FS_DATE'');



-- PIPELINE START FOR 1

-- Component SQ_FS_PLCY, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FS_PLCY AS

WITH  PRTY_ASSET_COVERAGES AS
(
  SELECT
    A.AGMT_ID,
    A.HOST_AGMT_NUM,
    PA.PRTY_ASSET_ID,
    AIAF.RATE_SYMB_CD,
    F.INSRNC_CVGE_TYPE_CD,
    CASE
      WHEN F.FEAT_SBTYPE_CD = ''OPT'' THEN F2.FEAT_NAME
      WHEN F.FEAT_SBTYPE_CD = ''TERM'' THEN F.FEAT_NAME
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F4.FEAT_NAME
    END AS TERM_NAME,
    CASE
      WHEN F.FEAT_SBTYPE_CD = ''TERM'' THEN F1.FEAT_ID
      WHEN F.FEAT_SBTYPE_CD = ''OPT'' THEN F3.FEAT_ID
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F5.FEAT_ID
    END AS COV_FEAT_ID,
    CASE
      WHEN F.FEAT_SBTYPE_CD = ''TERM'' THEN F1.FEAT_NAME
      WHEN F.FEAT_SBTYPE_CD = ''OPT'' THEN F3.FEAT_NAME
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F5.FEAT_NAME
    END AS COV_NAME,
    CASE
      WHEN F.FEAT_SBTYPE_CD = ''TERM'' THEN F1.NK_SRC_KEY
      WHEN F.FEAT_SBTYPE_CD = ''OPT'' THEN F3.NK_SRC_KEY
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F5.NK_SRC_KEY
    END AS COV_PATTERNCODE,
    CASE
      WHEN F.FEAT_SBTYPE_CD = ''OPT'' THEN F2.NK_SRC_KEY
      WHEN F.FEAT_SBTYPE_CD = ''TERM'' THEN F.NK_SRC_KEY
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F4.NK_SRC_KEY
    END AS TERM_PATTERNCODE,
    CASE
      WHEN F.FEAT_SBTYPE_CD = ''OPT''
      AND F.FEAT_DTL_CD_NAME IN (''ACTUAL'', ''REPLACEMENT'') THEN F.FEAT_DTL_CD_NAME
      WHEN F.FEAT_SBTYPE_CD = ''OPT''
      AND NOT F.FEAT_DTL_CD_NAME IN (''ACTUAL'', ''REPLACEMENT'') THEN CAST(F.FEAT_DTL_VAL AS DECIMAL(18, 4))
      WHEN F.FEAT_SBTYPE_CD = ''TERM''
      AND LENGTH (AIAF.AGMT_ASSET_FEAT_TXT) > 0 THEN AIAF.AGMT_ASSET_FEAT_TXT
      WHEN F.FEAT_SBTYPE_CD = ''TERM''
      AND (
        LENGTH (AIAF.AGMT_ASSET_FEAT_TXT) = 0
        OR AIAF.AGMT_ASSET_FEAT_TXT IS NULL
      ) THEN AIAF.AGMT_ASSET_FEAT_AMT
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F.FEAT_DTL_CD_NAME
    END AS VAL
  FROM
    DB_T_PROD_CORE.FEAT AS F
    JOIN DB_T_PROD_CORE.AGMT_INSRD_ASSET_FEAT AS AIAF ON F.FEAT_ID = AIAF.FEAT_ID
    AND CAST(AIAF.TRANS_END_DTTM AS DATE) = ''9999-12-31''
    JOIN DB_T_PROD_CORE.AGMT AS A ON AIAF.AGMT_ID = A.AGMT_ID
    AND CAST(A.EDW_END_DTTM AS DATE) = ''9999-12-31''
    JOIN DB_T_PROD_CORE.PRTY_ASSET AS PA ON AIAF.PRTY_ASSET_ID = PA.PRTY_ASSET_ID
    AND CAST(PA.EDW_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD AS FR1 ON F.FEAT_ID = FR1.RLTD_FEAT_ID
    AND FR1.FEAT_RLTNSHP_TYPE_CD = ''COVT''
    AND CAST(FR1.TRANS_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT AS F1 ON FR1.FEAT_ID = F1.FEAT_ID
    AND CAST(F1.EDW_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD AS FR2 ON F.FEAT_ID = FR2.RLTD_FEAT_ID
    AND FR2.FEAT_RLTNSHP_TYPE_CD = ''TERMOPT''
    AND CAST(FR2.TRANS_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT AS F2 ON FR2.FEAT_ID = F2.FEAT_ID
    AND CAST(F2.EDW_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD AS FR3 ON F.FEAT_ID = FR3.RLTD_FEAT_ID
    AND FR3.FEAT_RLTNSHP_TYPE_CD = ''COVOPTT''
    AND CAST(FR3.TRANS_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT AS F3 ON FR3.FEAT_ID = F3.FEAT_ID
    AND CAST(F3.EDW_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD AS FR4 ON F.FEAT_ID = FR4.RLTD_FEAT_ID
    AND FR4.FEAT_RLTNSHP_TYPE_CD = ''TERMPKG''
    AND CAST(FR4.TRANS_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT AS F4 ON FR4.FEAT_ID = F4.FEAT_ID
    AND CAST(F4.EDW_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD AS FR5 ON F.FEAT_ID = FR5.RLTD_FEAT_ID
    AND FR5.FEAT_RLTNSHP_TYPE_CD = ''COVPKG''
    AND CAST(FR5.TRANS_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT AS F5 ON FR5.FEAT_ID = F5.FEAT_ID
    AND CAST(F5.EDW_END_DTTM AS DATE) = ''9999-12-31''
  WHERE
    F.FEAT_SBTYPE_CD IN (''TERM'', ''OPT'', ''PKG'')
    AND A.MODL_CRTN_DTTM = (
      SELECT
        MAX(AA.MODL_CRTN_DTTM)
      FROM
        DB_T_PROD_CORE.AGMT AS AA
      WHERE
        AA.HOST_AGMT_NUM = A.HOST_AGMT_NUM
    )
    AND A.AGMT_CUR_STS_CD = ''BOUND''
    AND NOT CASE
      WHEN F.FEAT_SBTYPE_CD = ''TERM'' THEN F1.NK_SRC_KEY
      WHEN F.FEAT_SBTYPE_CD = ''OPT'' THEN F3.NK_SRC_KEY
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F5.NK_SRC_KEY
    END IN (
      ''HOLI_SCHEDULEDPROPERTYDEDUCTIBLESITEM_ALFA'',
      ''HOSI_SCHEDULEDPROPERTYITEM_ALFA''
    )
), 



LOCATION_ADDRESS_PROPERTY  AS
(
  SELECT
    PAL.PRTY_ASSET_ID,
    PAL.LOC_ID,
    PAL.PRTY_ASSET_LOCTR_ROLE_CD,
    C.GEOGRCL_AREA_NAME AS COUNTY,
    SA.ADDR_LN_1_TXT AS PLCY_MAIL_ADDRESS_1,
    PAL.FIRE_DEPT_ID,
    PC.POSTL_CD_NUM AS ZIP
  FROM
    DB_T_PROD_CORE.PRTY_ASSET_LOCTR AS PAL
    JOIN DB_T_PROD_CORE.STREET_ADDR AS SA ON SA.STREET_ADDR_ID = PAL.LOC_ID
    AND CAST(SA.EDW_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.CNTY AS C ON C.CNTY_ID = SA.CNTY_ID
    AND CAST(C.EDW_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.POSTL_CD AS PC ON PC.POSTL_CD_ID = SA.POSTL_CD_ID
    AND CAST(PC.EDW_END_DTTM AS DATE) = ''9999-12-31''
  WHERE
    PAL.PRTY_ASSET_LOCTR_ROLE_CD = ''RSKSTADRS''
    AND PAL.TRANS_END_DTTM = CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP)
)  ,
LOCATION_ADDRESS_AUTO  AS
(
  SELECT
    PAL.PRTY_ASSET_ID,
    PAL.LOC_ID,
    PAL.PRTY_ASSET_LOCTR_ROLE_CD,
    C.GEOGRCL_AREA_NAME AS COUNTY,
    SA.ADDR_LN_1_TXT AS PLCY_MAIL_ADDRESS_1,
    PC.POSTL_CD_NUM AS ZIP
  FROM
    DB_T_PROD_CORE.PRTY_ASSET_LOCTR AS PAL
    JOIN DB_T_PROD_CORE.STREET_ADDR AS SA ON SA.STREET_ADDR_ID = PAL.LOC_ID
    AND CAST(SA.EDW_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.CNTY AS C ON C.CNTY_ID = SA.CNTY_ID
    AND CAST(C.EDW_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.POSTL_CD AS PC ON PC.POSTL_CD_ID = SA.POSTL_CD_ID
    AND CAST(PC.EDW_END_DTTM AS DATE) = ''9999-12-31''
  WHERE
    PAL.PRTY_ASSET_LOCTR_ROLE_CD = ''GARSTRTADDRSS''
    AND PAL.TRANS_END_DTTM = CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP)
) ,





AGMT_COVERAGES AS
 (
  SELECT
    A.AGMT_ID,
    A.HOST_AGMT_NUM,
    CASE
      WHEN F.FEAT_SBTYPE_CD = ''OPT'' THEN F2.FEAT_NAME
      WHEN F.FEAT_SBTYPE_CD = ''TERM'' THEN F.FEAT_NAME
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F4.FEAT_NAME
    END AS TERM_NAME,
    CASE
      WHEN F.FEAT_SBTYPE_CD = ''TERM'' THEN F1.FEAT_ID
      WHEN F.FEAT_SBTYPE_CD = ''OPT'' THEN F3.FEAT_ID
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F5.FEAT_ID
    END AS COV_FEAT_ID,
    CASE
      WHEN F.FEAT_SBTYPE_CD = ''TERM'' THEN F1.FEAT_NAME
      WHEN F.FEAT_SBTYPE_CD = ''OPT'' THEN F3.FEAT_NAME
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F5.FEAT_NAME
    END AS COV_NAME,
    CASE
      WHEN F.FEAT_SBTYPE_CD = ''TERM'' THEN F1.NK_SRC_KEY
      WHEN F.FEAT_SBTYPE_CD = ''OPT'' THEN F3.NK_SRC_KEY
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F5.NK_SRC_KEY
    END AS COV_PATTERNCODE,
    CASE
      WHEN F.FEAT_SBTYPE_CD = ''OPT'' THEN F2.NK_SRC_KEY
      WHEN F.FEAT_SBTYPE_CD = ''TERM'' THEN F.NK_SRC_KEY
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F4.NK_SRC_KEY
    END AS TERM_PATTERNCODE,
    CASE
      WHEN F.FEAT_SBTYPE_CD = ''OPT''
      AND F.FEAT_DTL_CD_NAME IN (''ACTUAL'', ''REPLACEMENT'') THEN F.FEAT_DTL_CD_NAME
      WHEN F.FEAT_SBTYPE_CD = ''OPT''
      AND NOT F.FEAT_DTL_CD_NAME IN (''ACTUAL'', ''REPLACEMENT'') THEN CAST(F.FEAT_DTL_VAL AS DECIMAL(18, 4))
      WHEN F.FEAT_SBTYPE_CD = ''TERM''
      AND LENGTH (AF.AGMT_FEAT_TXT) > 0 THEN AF.AGMT_FEAT_TXT
      WHEN F.FEAT_SBTYPE_CD = ''TERM''
      AND (
        LENGTH (AF.AGMT_FEAT_TXT) = 0
        OR AF.AGMT_FEAT_TXT IS NULL
      ) THEN AF.AGMT_FEAT_AMT
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F.FEAT_DTL_CD_NAME
    END AS VAL
  FROM
    DB_T_PROD_CORE.FEAT AS F
    JOIN DB_T_PROD_CORE.AGMT_FEAT AS AF ON F.FEAT_ID = AF.FEAT_ID
    AND CAST(AF.TRANS_END_DTTM AS DATE) = ''9999-12-31''
    JOIN DB_T_PROD_CORE.AGMT AS A ON AF.AGMT_ID = A.AGMT_ID
    AND CAST(A.EDW_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD AS FR1 ON F.FEAT_ID = FR1.RLTD_FEAT_ID
    AND FR1.FEAT_RLTNSHP_TYPE_CD = ''COVT''
    AND CAST(FR1.TRANS_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT AS F1 ON FR1.FEAT_ID = F1.FEAT_ID
    LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD AS FR2 ON F.FEAT_ID = FR2.RLTD_FEAT_ID
    AND FR2.FEAT_RLTNSHP_TYPE_CD = ''TERMOPT''
    AND CAST(FR2.TRANS_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT AS F2 ON FR2.FEAT_ID = F2.FEAT_ID
    LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD AS FR3 ON F.FEAT_ID = FR3.RLTD_FEAT_ID
    AND FR3.FEAT_RLTNSHP_TYPE_CD = ''COVOPTT''
    AND CAST(FR3.TRANS_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT AS F3 ON FR3.FEAT_ID = F3.FEAT_ID
    LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD AS FR4 ON F.FEAT_ID = FR4.RLTD_FEAT_ID
    AND FR4.FEAT_RLTNSHP_TYPE_CD = ''TERMPKG''
    AND CAST(FR4.TRANS_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT AS F4 ON FR4.FEAT_ID = F4.FEAT_ID
    LEFT JOIN DB_T_PROD_CORE.FEAT_RLTD AS FR5 ON F.FEAT_ID = FR5.RLTD_FEAT_ID
    AND FR5.FEAT_RLTNSHP_TYPE_CD = ''COVPKG''
    AND CAST(FR5.TRANS_END_DTTM AS DATE) = ''9999-12-31''
    LEFT JOIN DB_T_PROD_CORE.FEAT AS F5 ON FR5.FEAT_ID = F5.FEAT_ID
  WHERE
    F.FEAT_SBTYPE_CD IN (''TERM'', ''OPT'', ''PKG'')
    AND F.FEAT_COVERABLE_TYPE_TXT IN (
      ''PERSONALAUTOLINE'',
      ''HOMEOWNERSLINE_HOE'',
      ''HOLINESCHCOVITEM_ALFA''
    )
    AND NOT CASE
      WHEN F.FEAT_SBTYPE_CD = ''TERM'' THEN F1.NK_SRC_KEY
      WHEN F.FEAT_SBTYPE_CD = ''OPT'' THEN F3.NK_SRC_KEY
      WHEN F.FEAT_SBTYPE_CD = ''PKG'' THEN F5.NK_SRC_KEY
    END IN (
      ''HOLI_SCHEDULEDPROPERTYDEDUCTIBLESITEM_ALFA'',
      ''HOSI_SCHEDULEDPROPERTYITEM_ALFA''
    )
), 

 UNDERWRITING AS (
  SELECT
    MAX(O.PRTY_DESC) AS PRTY_DESC,
    PA.AGMT_ID
  FROM
    DB_T_PROD_CORE.INTRNL_ORG O
    JOIN DB_T_PROD_CORE.PRTY_AGMT PA ON O.INTRNL_ORG_PRTY_ID = PA.PRTY_ID
  WHERE
    PA.PRTY_AGMT_ROLE_CD = ''CMP''
    AND DATE(PA.TRANS_END_DTTM) = ''9999-12-31''
    AND DATE(O.EDW_END_DTTM) = ''9999-12-31''
  GROUP BY
    PA.AGMT_ID
),
INFORCE_DAYS AS (SELECT
  AAA.AGMT_ID,
  AAA.HOST_AGMT_NUM,
  DATEDIFF(
    DAY,
    AAA.INFORCE_START_DATE,
    AAA.INFORCE_END_DATE
  ) AS DAYS_BETWEEN
FROM
  (
    SELECT
      DISTINCT AG.AGMT_ID,
      AG.HOST_AGMT_NUM,
      AST.AGMT_STS_CD,
      cal.QUARTERBEGIN,
      AST.AGMT_STS_STRT_DTTM,
      AG.MODL_ACTL_END_DTTM,
      DATEADD(DAY, -1, DATEADD(QUARTER, 1, cal.QUARTERBEGIN)) AS QUARTEREND,
      CASE
        WHEN cal.QUARTERBEGIN > AST.AGMT_STS_STRT_DTTM THEN cal.QUARTERBEGIN
        ELSE AST.AGMT_STS_STRT_DTTM
      END AS INFORCE_START_DATE,
      CASE
        WHEN DATEADD(DAY, -1, DATEADD(QUARTER, 1, cal.QUARTERBEGIN)) < AG.MODL_ACTL_END_DTTM THEN DATEADD(DAY, -1, DATEADD(QUARTER, 1, cal.QUARTERBEGIN))
        ELSE AG.MODL_ACTL_END_DTTM
      END AS INFORCE_END_DATE
    FROM
      (
        SELECT
          *
        FROM
          DB_T_PROD_CORE.AGMT
        WHERE
          TO_DATE(MODL_EFF_DTTM) <= :FS_DATE
          AND TO_DATE(MODL_CRTN_DTTM) <= :FS_DATE
          AND AGMT_TYPE_CD = ''PPV'' QUALIFY RANK() OVER (
            PARTITION BY HOST_AGMT_NUM,
            TERM_NUM
            ORDER BY
              MODL_NUM DESC
          ) = 1
      ) AS AG
      JOIN (
        SELECT
          *
        FROM
          DB_T_PROD_CORE.AGMT
        WHERE
          TO_DATE(AGMT_EFF_DTTM) <= :FS_DATE
          AND TO_DATE(AGMT_PLND_EXPN_DTTM) > :FS_DATE
          AND AGMT_TYPE_CD = ''POLTRM''
      ) AS TERM ON TERM.HOST_AGMT_NUM = AG.HOST_AGMT_NUM
      AND TERM.TERM_NUM = AG.TERM_NUM
      JOIN (
        SELECT
          *
        FROM
          DB_T_PROD_CORE.AGMT_STS
        WHERE
          AGMT_STS_STRT_DTTM <= :FS_DATE
          AND AGMT_STS_CD <> ''CNFRMDDT'' QUALIFY RANK() OVER (
            PARTITION BY AGMT_ID
            ORDER BY
              AGMT_STS_STRT_DTTM DESC
          ) = 1
      ) AS AST ON AST.AGMT_ID = TERM.AGMT_ID
      AND AST.AGMT_STS_CD = ''INFORCE'',
      (
        SELECT
          QUARTER(:FS_DATE) AS QUARTER_OF_YEAR,
          YEAR(:FS_DATE) AS YEAR_OF_CALENDAR,
          DATE_TRUNC(''QUARTER'', :FS_DATE) AS QUARTERBEGIN,
          :FS_DATE AS CALENDAR_DATE
      ) AS cal
    WHERE
      AG.AGMT_CUR_STS_CD = ''BOUND''
      AND AST.AGMT_STS_STRT_DTTM <= DATEADD(DAY, -1, DATEADD(QUARTER, 1, cal.QUARTERBEGIN))
  ) AS AAA
GROUP BY
  AAA.HOST_AGMT_NUM,
  AAA.AGMT_ID,
  AAA.INFORCE_START_DATE,
  AAA.INFORCE_END_DATE)

/* THE OUTERMOST GROUP BY SECTION WILL SUM UP ACROSS POLICIES */
SELECT 

YEAR_OF_CALENDAR, 

QUARTER_OF_YEAR, 

PLCY_RISK_STATE, 

UNDERWRITING_COMPANY, 

PLCY_TYPE_DESC,

CVGE_NAME, 

RISK_GARAGING_COUNTY, 

SUM(EARND_UNIT_CVGE_YR_AMT)  AS EARND_UNIT_CVGE_YR_AMT, 

SUM(INSRNC_YR_AMT) AS INSRNC_YR_AMT,

SUM (EARND_PREM_AMT)  AS EARND_PREM_AMT,

CURRENT_TIMESTAMP AS CRDT_DTTM,

CURRENT_TIMESTAMP AS UPDT_DTTM

FROM

( /*  THIS SECTION WILL SUM UP ACROSS COVERAGES BUT NOT ACROSS POLICIES */
 SELECT 
 
      YEAR(:FS_DATE) AS YEAR_OF_CALENDAR,
    QUARTER(:FS_DATE) AS QUARTER_OF_YEAR
 , (

 SELECT  PRTY_DESC

 FROM  UNDERWRITING
 WHERE  AGMT_ID=TEMP.AGMT_ID) AS UNDERWRITING_COMPANY

 ,P.PROD_DESC AS PLCY_TYPE_DESC

 ,CVGE_NAME

 , HOST_AGMT_NUM

 ,  ( CAST(EARND_UNIT_CVGE_DAYS AS DECIMAL (10,4))/365 )  AS EARND_UNIT_CVGE_YR_AMT

 , (SELECT UPPER(GEOGRCL_AREA_NAME) FROM  DB_T_PROD_CORE.TERR T

  WHERE CAST(T.EDW_END_DTTM AS DATE) =''9999-12-31''

  AND TERR_ID=WRITTEN_STATE.LOC_ID ) AS  PLCY_RISK_STATE

 , CASE WHEN COUNTY IS NOT NULL THEN  COUNTY ELSE GARAGING_LOCATION.COUNTY  END AS RISK_GARAGING_COUNTY

 , MAX ( CVGE_LIMIT * CAST(EARND_UNIT_CVGE_DAYS AS DECIMAL (10,6))/36500000 ) AS INSRNC_YR_AMT

 , MAX (EARND_PREM_AMT)  AS EARND_PREM_AMT

 FROM 

 (

 
/* MAIN QUERY CONTAINING GRANULAR DATA */
SELECT
  PAC.AGMT_ID,
  ID.HOST_AGMT_NUM,
  PAC.PRTY_ASSET_ID,
  CASE
    WHEN PAC.TERM_PATTERNCODE LIKE ''%DED%''
    AND PAC.TERM_PATTERNCODE <> ''PAREDUCEDORADDEDON_ALFA'' THEN PAC.VAL
    ELSE 0
  END AS DED_AMT,
  PAC.COV_NAME AS CVGE_NAME,
  ID.DAYS_BETWEEN AS EARND_UNIT_CVGE_DAYS,
  CASE
    WHEN PAC.TERM_PATTERNCODE LIKE ''%LIMIT%''
    AND SUBSTRING(PAC.TERM_PATTERNCODE, 1, 2) = ''HO'' THEN CAST(PAC.VAL AS DECIMAL(10, 2))
    ELSE 0
  END AS CVGE_LIMIT,
  PLCY_ASSET_CVGE_AMT AS EARND_PREM_AMT,
  PAC.VAL,
  PAC.TERM_PATTERNCODE
FROM
  (
    SELECT
      *
    FROM
      PRTY_ASSET_COVERAGES AS PAC
    WHERE
      (
        PAC.TERM_PATTERNCODE LIKE ''%LIMIT%''
        OR PAC.TERM_PATTERNCODE LIKE ''%DED%''
      )
      AND NOT PAC.TERM_NAME LIKE ''PERCENT%''
  ) AS PAC
  JOIN DB_T_PROD_CORE.AGMT AS A ON PAC.AGMT_ID = A.AGMT_ID
  JOIN INFORCE_DAYS AS ID ON ID.HOST_AGMT_NUM = PAC.HOST_AGMT_NUM
  LEFT JOIN (
    SELECT
      AGMT_ID,
      FEAT_ID,
      PRTY_ASSET_ID,
      PLCY_ASSET_CVGE_AMT
    FROM
      DB_T_PROD_CORE.PLCY_ASSET_CVGE_MTRC
    WHERE
      INSRNC_MTRC_TYPE_CD = ''ERNDPREM''
  ) AS PACM ON A.AGMT_ID = PACM.AGMT_ID
  AND PAC.COV_FEAT_ID = PACM.FEAT_ID
  AND PAC.PRTY_ASSET_ID = PACM.PRTY_ASSET_ID
/* AND PACM.INSRNC_MTRC_TYPE_CD=''ERNDPREM'' */
 

 UNION ALL
SELECT
  AC.AGMT_ID,
  ID.HOST_AGMT_NUM,
  NULL AS PRTY_ASSET_ID,
  CASE
    WHEN AC.TERM_PATTERNCODE LIKE ''%DED%'' THEN AC.VAL
    ELSE 0
  END AS DED_AMT,
  AC.COV_NAME AS CVGE_NAME,
  ID.DAYS_BETWEEN AS EARND_UNIT_CVGE_DAYS,
  0 AS CVGE_LIMIT,
  PCM.PLCY_CVGE_AMT AS EARND_PREM_AMT,
  AC.VAL,
  AC.TERM_PATTERNCODE
  --,

FROM
  (
    SELECT
      *
    FROM
      AGMT_COVERAGES
    WHERE
      (
        TERM_PATTERNCODE LIKE ''%LIMIT%''
        OR TERM_PATTERNCODE LIKE ''%DED%''
      )
      AND NOT TERM_NAME LIKE ''PERCENT%''
  ) AS AC
  JOIN DB_T_PROD_CORE.AGMT AS A ON AC.AGMT_ID = A.AGMT_ID
  JOIN INFORCE_DAYS AS ID ON ID.HOST_AGMT_NUM = AC.HOST_AGMT_NUM
  LEFT JOIN (
    SELECT
      AGMT_ID,
      FEAT_ID,
      PLCY_CVGE_AMT
    FROM
      DB_T_PROD_CORE.PLCY_CVGE_MTRC
    WHERE
      INSRNC_MTRC_TYPE_CD = ''ERNDPREM''
  ) AS PCM ON A.AGMT_ID = PCM.AGMT_ID
  AND AC.COV_FEAT_ID = PCM.FEAT_ID
  JOIN DB_T_PROD_CORE.AGMT_PROD AS AP ON AC.AGMT_ID = AP.AGMT_ID
  AND CAST(AP.EDW_END_DTTM AS DATE) = ''9999-12-31''
  LEFT JOIN DB_T_PROD_CORE.AGMT_LOCTR AS WRITTEN_STATE ON AC.AGMT_ID = WRITTEN_STATE.AGMT_ID
  AND WRITTEN_STATE.AGMT_LOCTR_ROLE_TYPE_CD = ''AGTWINST''
  AND CAST(WRITTEN_STATE.TRANS_END_DTTM AS DATE) = ''9999-12-31''
  JOIN DB_T_PROD_CORE.PROD AS P ON AP.PROD_ID = P.PROD_ID
  AND CAST(P.EDW_END_DTTM AS DATE) = ''9999-12-31''
  LEFT JOIN (
    SELECT
      AA.AGMT_ID,
      MAX(AA.PRTY_ASSET_ID) AS PRTY_ASSET_ID
    FROM
      DB_T_PROD_CORE.AGMT_ASSET AS AA
      JOIN DB_T_PROD_CORE.PRTY_ASSET AS PA ON AA.PRTY_ASSET_ID = PA.PRTY_ASSET_ID
    WHERE
      PA.PRTY_ASSET_SBTYPE_CD IN (''RE'', ''REALDW'')
      AND PA.PRTY_ASSET_CLASFCN_CD = ''MAIN''
      AND AA.TRANS_END_DTTM = CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP)
      AND CAST(PA.EDW_END_DTTM AS DATE) = ''9999-12-31''
    GROUP BY
      AA.AGMT_ID
  ) AS ASSET ON AC.AGMT_ID = ASSET.AGMT_ID
  LEFT JOIN LOCATION_ADDRESS_PROPERTY AS RISK_LOCATION ON ASSET.PRTY_ASSET_ID = RISK_LOCATION.PRTY_ASSET_ID
  LEFT JOIN LOCATION_ADDRESS_AUTO AS GARAGING_LOCATION ON NULL = GARAGING_LOCATION.PRTY_ASSET_ID
  CROSS JOIN (
    SELECT
      QUARTER(:FS_DATE) AS QUARTER_OF_YEAR,
      YEAR(:FS_DATE) AS YEAR_OF_CALENDAR,
      DATE_TRUNC(''QUARTER'', :FS_DATE) AS QUARTERBEGIN
  ) AS cal

  GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9
 ) 
 left JOIN  DB_T_PROD_CORE.AGMT_PROD AP ON  AGMT_ID=AP.AGMT_ID AND CAST(AP.EDW_END_DTTM AS DATE) =''9999-12-31''
 left JOIN  DB_T_PROD_CORE.PROD  P  ON  AP.PROD_ID=P.PROD_ID AND CAST(P.EDW_END_DTTM AS DATE) =''9999-12-31''

)  SUM_ACROSS_COVERAGES



GROUP BY YEAR_OF_CALENDAR, 

QUARTER_OF_YEAR, 

UNDERWRITING_COMPANY, 

PLCY_RISK_STATE, 

RISK_GARAGING_COUNTY, 

PLCY_TYPE_DESC,

CVGE_NAME

ORDER BY 1,2,3,4,5,6,7;




-- Component exp_pass_to_tgt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_to_tgt AS
(
SELECT
ltrim ( rtrim ( SQ_FS_PLCY.CAL_YR_NUM ) ) as CAL_YR_NUM_trim,
ltrim ( rtrim ( SQ_FS_PLCY.CAL_QTR_NUM ) ) as CAL_QTR_NUM_trim,
SQ_FS_PLCY.source_record_id
FROM
SQ_FS_PLCY
);


-- Component DELETE_LOOKUP, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE DELETE_LOOKUP AS
(
SELECT
LKP.CAL_YR_NUM,
LKP.CAL_QTR_NUM,
exp_pass_to_tgt.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pass_to_tgt.source_record_id ORDER BY LKP.CAL_YR_NUM asc,LKP.CAL_QTR_NUM asc) RNK
FROM
exp_pass_to_tgt
LEFT JOIN (
SELECT
CAL_YR_NUM,
CAL_QTR_NUM
FROM FS_PLCY
) LKP ON LKP.CAL_YR_NUM = exp_pass_to_tgt.CAL_YR_NUM_trim AND LKP.CAL_QTR_NUM = exp_pass_to_tgt.CAL_QTR_NUM_trim
QUALIFY RNK = 1
);


-- Component exp_pass_to_tgt2, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_to_tgt2 AS
(
SELECT
DELETE_LOOKUP.CAL_YR_NUM as CAL_YR_NUM,
DELETE_LOOKUP.CAL_QTR_NUM as CAL_QTR_NUM,
NULL as ST_CD,
NULL as UNDRWRTG_CO_CD,
NULL as PLCY_TYPE_DESC,
NULL as PRTCTN_CLAS_CD,
NULL as DEDCTB_AMT,
NULL as CVGE_NAME,
NULL as CNTY_NAME,
NULL as RTG_TERR_CD,
NULL as COLLISION_VEH_SYMB_CD,
NULL as CMPRN_VEH_SYMB_CD,
NULL as DRVR_CLAS_CD,
NULL as MODL_YR_NUM,
NULL as MULTICAR_DSCNT_IND,
NULL as DRVR_TRNG_IND,
NULL as HONOR_STDNT_DSCNT_IND,
NULL as EARND_UNIT_CVGE_YR_AMT,
NULL as INSRNC_YR_AMT,
NULL as EARND_PREM_AMT,
NULL as CRTD_DTTM,
NULL as UPDTD_DTTM,
CASE WHEN DELETE_LOOKUP.CAL_YR_NUM IS NOT NULL and DELETE_LOOKUP.CAL_QTR_NUM IS NOT NULL THEN ''DEL'' ELSE '''' END as FLAG_DELETE,
DELETE_LOOKUP.source_record_id
FROM
DELETE_LOOKUP
);


-- Component delete_filter, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE delete_filter AS
(
SELECT
exp_pass_to_tgt2.CAL_YR_NUM as CAL_YR_NUM,
exp_pass_to_tgt2.CAL_QTR_NUM as CAL_QTR_NUM,
exp_pass_to_tgt2.ST_CD as ST_CD,
exp_pass_to_tgt2.UNDRWRTG_CO_CD as UNDRWRTG_CO_CD,
exp_pass_to_tgt2.PLCY_TYPE_DESC as PLCY_TYPE_DESC,
exp_pass_to_tgt2.PRTCTN_CLAS_CD as PRTCTN_CLAS_CD,
exp_pass_to_tgt2.DEDCTB_AMT as DEDCTB_AMT,
exp_pass_to_tgt2.CVGE_NAME as CVGE_NAME,
exp_pass_to_tgt2.CNTY_NAME as CNTY_NAME,
exp_pass_to_tgt2.RTG_TERR_CD as RTG_TERR_CD,
exp_pass_to_tgt2.COLLISION_VEH_SYMB_CD as COLLISION_VEH_SYMB_CD,
exp_pass_to_tgt2.CMPRN_VEH_SYMB_CD as CMPRN_VEH_SYMB_CD,
exp_pass_to_tgt2.DRVR_CLAS_CD as DRVR_CLAS_CD,
exp_pass_to_tgt2.MODL_YR_NUM as MODL_YR_NUM,
exp_pass_to_tgt2.MULTICAR_DSCNT_IND as MULTICAR_DSCNT_IND,
exp_pass_to_tgt2.DRVR_TRNG_IND as DRVR_TRNG_IND,
exp_pass_to_tgt2.HONOR_STDNT_DSCNT_IND as HONOR_STDNT_DSCNT_IND,
exp_pass_to_tgt2.EARND_UNIT_CVGE_YR_AMT as EARND_UNIT_CVGE_YR_AMT,
exp_pass_to_tgt2.INSRNC_YR_AMT as INSRNC_YR_AMT,
exp_pass_to_tgt2.EARND_PREM_AMT as EARND_PREM_AMT,
exp_pass_to_tgt2.CRTD_DTTM as CRTD_DTTM,
exp_pass_to_tgt2.UPDTD_DTTM as UPDTD_DTTM,
exp_pass_to_tgt2.FLAG_DELETE as FLAG_DELETE,
exp_pass_to_tgt2.source_record_id
FROM
exp_pass_to_tgt2
WHERE exp_pass_to_tgt2.FLAG_DELETE = ''DEL''
);


-- Component delete_target, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE delete_target AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
delete_filter.CAL_YR_NUM as CAL_YR_NUM,
delete_filter.CAL_QTR_NUM as CAL_QTR_NUM,
delete_filter.ST_CD as ST_CD,
delete_filter.UNDRWRTG_CO_CD as UNDRWRTG_CO_CD,
delete_filter.PLCY_TYPE_DESC as PLCY_TYPE_DESC,
delete_filter.PRTCTN_CLAS_CD as PRTCTN_CLAS_CD,
delete_filter.DEDCTB_AMT as DEDCTB_AMT,
delete_filter.CVGE_NAME as CVGE_NAME,
delete_filter.CNTY_NAME as CNTY_NAME,
delete_filter.RTG_TERR_CD as RTG_TERR_CD,
delete_filter.COLLISION_VEH_SYMB_CD as COLLISION_VEH_SYMB_CD,
delete_filter.CMPRN_VEH_SYMB_CD as CMPRN_VEH_SYMB_CD,
delete_filter.DRVR_CLAS_CD as DRVR_CLAS_CD,
delete_filter.MODL_YR_NUM as MODL_YR_NUM,
delete_filter.MULTICAR_DSCNT_IND as MULTICAR_DSCNT_IND,
delete_filter.DRVR_TRNG_IND as DRVR_TRNG_IND,
delete_filter.HONOR_STDNT_DSCNT_IND as HONOR_STDNT_DSCNT_IND,
delete_filter.EARND_UNIT_CVGE_YR_AMT as EARND_UNIT_CVGE_YR_AMT,
delete_filter.INSRNC_YR_AMT as INSRNC_YR_AMT,
delete_filter.EARND_PREM_AMT as EARND_PREM_AMT,
delete_filter.CRTD_DTTM as CRTD_DTTM,
delete_filter.UPDTD_DTTM as UPDTD_DTTM,
dd_delete as UPDATE_STRATEGY_ACTION
FROM
delete_filter
);


-- Component tgt_FS_PLCY_DELETE, Type TARGET 

/* Perform Deletes */
DELETE FROM DB_T_PROD_WRK.FS_PLCY
WHERE EXISTS (SELECT 1 FROM delete_target WHERE UPDATE_STRATEGY_ACTION = 2 AND FS_PLCY.CAL_YR_NUM = delete_target.CAL_YR_NUM AND FS_PLCY.CAL_QTR_NUM = delete_target.CAL_QTR_NUM)
;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_FS_PLCY1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_FS_PLCY1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as CAL_YR_NUM,
$2 as CAL_QTR_NUM,
$3 as ST_CD,
$4 as UNDRWRTG_CO_CD,
$5 as PLCY_TYPE_DESC,
$6 as CVGE_NAME,
$7 as CNTY_NAME,
$8 as EARND_UNIT_CVGE_YR_AMT,
$9 as INSRNC_YR_AMT,
$10 as EARND_PREM_AMT,
$11 as CRTD_DTTM,
$12 as UPDTD_DTTM,
$13 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
WITH  PRTY_ASSET_COVERAGES AS

(

SELECT  A.AGMT_ID, A.HOST_AGMT_NUM, PA.PRTY_ASSET_ID, RATE_SYMB_CD  , F.INSRNC_CVGE_TYPE_CD,

CASE 

WHEN F.FEAT_SBTYPE_CD=''OPT'' THEN F2.FEAT_NAME

WHEN F.FEAT_SBTYPE_CD=''TERM'' THEN F.FEAT_NAME

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN F4.FEAT_NAME

END TERM_NAME, 

CASE WHEN F.FEAT_SBTYPE_CD=''TERM'' THEN F1.FEAT_ID

WHEN F.FEAT_SBTYPE_CD=''OPT'' THEN F3.FEAT_ID

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN F5.FEAT_ID

END COV_FEAT_ID,

CASE WHEN F.FEAT_SBTYPE_CD=''TERM'' THEN F1.FEAT_NAME

WHEN F.FEAT_SBTYPE_CD=''OPT'' THEN F3.FEAT_NAME

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN F5.FEAT_NAME

END COV_NAME, 

CASE WHEN F.FEAT_SBTYPE_CD=''TERM'' THEN F1.NK_SRC_KEY

WHEN F.FEAT_SBTYPE_CD=''OPT'' THEN F3.NK_SRC_KEY

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN F5.NK_SRC_KEY

END COV_PATTERNCODE, 

CASE WHEN F.FEAT_SBTYPE_CD=''OPT'' THEN F2.NK_SRC_KEY

WHEN F.FEAT_SBTYPE_CD=''TERM'' THEN F.NK_SRC_KEY

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN F4.NK_SRC_KEY

END TERM_PATTERNCODE, 

CASE 

WHEN F.FEAT_SBTYPE_CD=''OPT'' AND F.FEAT_DTL_CD_NAME  IN (''ACTUAL'', ''REPLACEMENT'') THEN F.FEAT_DTL_CD_NAME  

WHEN F.FEAT_SBTYPE_CD=''OPT'' AND F.FEAT_DTL_CD_NAME NOT IN (''ACTUAL'', ''REPLACEMENT'') THEN CAST(F.FEAT_DTL_VAL AS DECIMAL(18,4))  

WHEN F.FEAT_SBTYPE_CD=''TERM'' AND LENGTH(AIAF.AGMT_ASSET_FEAT_TXT)>0 THEN AIAF.AGMT_ASSET_FEAT_TXT

WHEN F.FEAT_SBTYPE_CD=''TERM'' AND (LENGTH(AIAF.AGMT_ASSET_FEAT_TXT) =0 OR AIAF.AGMT_ASSET_FEAT_TXT IS NULL) THEN AIAF.AGMT_ASSET_FEAT_AMT

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN  F.FEAT_DTL_CD_NAME

END VAL  





FROM  DB_T_PROD_CORE.FEAT F

JOIN  DB_T_PROD_CORE.AGMT_INSRD_ASSET_FEAT AIAF ON F.FEAT_ID=AIAF.FEAT_ID  AND  CAST(AIAF.TRANS_END_DTTM AS DATE) =''9999-12-31''  

JOIN  DB_T_PROD_CORE.AGMT A ON AIAF.AGMT_ID=A.AGMT_ID AND  CAST(A.EDW_END_DTTM AS DATE) =''9999-12-31''

JOIN DB_T_PROD_CORE.PRTY_ASSET PA ON AIAF.PRTY_ASSET_ID=PA.PRTY_ASSET_ID AND  CAST(PA.EDW_END_DTTM AS DATE) =''9999-12-31''

LEFT JOIN  DB_T_PROD_CORE.FEAT_RLTD FR1 ON F.FEAT_ID=FR1.RLTD_FEAT_ID AND FR1.FEAT_RLTNSHP_TYPE_CD =''COVT'' AND CAST( FR1.TRANS_END_DTTM  AS DATE) =''9999-12-31'' 

LEFT JOIN  DB_T_PROD_CORE.FEAT F1 ON FR1.FEAT_ID=F1.FEAT_ID AND  CAST(F1.EDW_END_DTTM AS DATE) =''9999-12-31'' 

LEFT JOIN  DB_T_PROD_CORE.FEAT_RLTD FR2 ON F.FEAT_ID=FR2.RLTD_FEAT_ID AND FR2.FEAT_RLTNSHP_TYPE_CD =''TERMOPT'' AND CAST( FR2.TRANS_END_DTTM AS DATE) =''9999-12-31''  

LEFT JOIN  DB_T_PROD_CORE.FEAT F2 ON FR2.FEAT_ID=F2.FEAT_ID  AND CAST(F2.EDW_END_DTTM AS DATE) =''9999-12-31''  

LEFT JOIN  DB_T_PROD_CORE.FEAT_RLTD FR3 ON F.FEAT_ID=FR3.RLTD_FEAT_ID AND FR3.FEAT_RLTNSHP_TYPE_CD =''COVOPTT''  AND CAST( FR3.TRANS_END_DTTM AS DATE) =''9999-12-31''

LEFT JOIN  DB_T_PROD_CORE.FEAT F3 ON FR3.FEAT_ID=F3.FEAT_ID  AND CAST(F3.EDW_END_DTTM AS DATE) =''9999-12-31''  

LEFT JOIN  DB_T_PROD_CORE.FEAT_RLTD FR4 ON F.FEAT_ID=FR4.RLTD_FEAT_ID AND FR4.FEAT_RLTNSHP_TYPE_CD =''TERMPKG'' AND CAST( FR4.TRANS_END_DTTM  AS DATE) =''9999-12-31''

LEFT JOIN  DB_T_PROD_CORE.FEAT F4 ON FR4.FEAT_ID=F4.FEAT_ID  AND CAST(F4.EDW_END_DTTM AS DATE) =''9999-12-31''  

LEFT JOIN  DB_T_PROD_CORE.FEAT_RLTD FR5 ON F.FEAT_ID=FR5.RLTD_FEAT_ID AND FR5.FEAT_RLTNSHP_TYPE_CD =''COVPKG''  AND CAST( FR5.TRANS_END_DTTM  AS DATE) =''9999-12-31''

LEFT JOIN  DB_T_PROD_CORE.FEAT F5 ON FR5.FEAT_ID=F5.FEAT_ID  AND CAST(F5.EDW_END_DTTM AS DATE) =''9999-12-31''  

WHERE F.FEAT_SBTYPE_CD IN (''TERM'', ''OPT'', ''PKG'')

AND  A.MODL_CRTN_DTTM = (SELECT MAX(AA.MODL_CRTN_DTTM)  FROM DB_T_PROD_CORE.AGMT AA WHERE  AA.HOST_AGMT_NUM=A.HOST_AGMT_NUM)

AND A.AGMT_CUR_STS_CD=''BOUND''

AND CASE WHEN F.FEAT_SBTYPE_CD=''TERM'' THEN F1.NK_SRC_KEY

WHEN F.FEAT_SBTYPE_CD=''OPT'' THEN F3.NK_SRC_KEY

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN F5.NK_SRC_KEY

END  NOT IN (''HOLI_SCHEDULEDPROPERTYDEDUCTIBLESITEM_ALFA'', ''HOSI_SCHEDULEDPROPERTYITEM_ALFA'') 



), 



LOCATION_ADDRESS_PROPERTY  AS

(

SELECT  PAL.PRTY_ASSET_ID, PAL.LOC_ID,PAL.PRTY_ASSET_LOCTR_ROLE_CD,C.GEOGRCL_AREA_NAME COUNTY, 

SA.ADDR_LN_1_TXT PLCY_MAIL_ADDRESS_1, PAL.FIRE_DEPT_ID  ,PC.POSTL_CD_NUM ZIP

 FROM  DB_T_PROD_CORE.PRTY_ASSET_LOCTR PAL

 JOIN  DB_T_PROD_CORE.STREET_ADDR SA ON SA.STREET_ADDR_ID=PAL.LOC_ID AND CAST(SA.EDW_END_DTTM AS DATE) =''9999-12-31''

 LEFT JOIN  DB_T_PROD_CORE.CNTY C ON C.CNTY_ID=SA.CNTY_ID AND CAST(C.EDW_END_DTTM AS DATE) =''9999-12-31''

 LEFT JOIN  DB_T_PROD_CORE.POSTL_CD PC ON PC.POSTL_CD_ID=SA.POSTL_CD_ID AND CAST(PC.EDW_END_DTTM AS DATE) =''9999-12-31''

 WHERE  PAL.PRTY_ASSET_LOCTR_ROLE_CD=''RSKSTADRS''

  AND PAL.TRANS_END_DTTM =CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP)



)  ,



LOCATION_ADDRESS_AUTO  AS

(

SELECT  PAL.PRTY_ASSET_ID, PAL.LOC_ID,PAL.PRTY_ASSET_LOCTR_ROLE_CD,C.GEOGRCL_AREA_NAME COUNTY, 

SA.ADDR_LN_1_TXT PLCY_MAIL_ADDRESS_1, PC.POSTL_CD_NUM ZIP

 FROM  DB_T_PROD_CORE.PRTY_ASSET_LOCTR PAL 

 JOIN  DB_T_PROD_CORE.STREET_ADDR SA ON SA.STREET_ADDR_ID=PAL.LOC_ID AND CAST(SA.EDW_END_DTTM AS DATE) =''9999-12-31''

 LEFT JOIN  DB_T_PROD_CORE.CNTY C ON C.CNTY_ID=SA.CNTY_ID AND CAST(C.EDW_END_DTTM AS DATE) =''9999-12-31''

 LEFT JOIN  DB_T_PROD_CORE.POSTL_CD PC ON PC.POSTL_CD_ID=SA.POSTL_CD_ID AND CAST(PC.EDW_END_DTTM AS DATE) =''9999-12-31''

 WHERE  PAL.PRTY_ASSET_LOCTR_ROLE_CD=''GARSTRTADDRSS''

  AND PAL.TRANS_END_DTTM =CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP)



)  ,





AGMT_COVERAGES AS

(

SELECT  A.AGMT_ID, A.HOST_AGMT_NUM,

CASE 

WHEN F.FEAT_SBTYPE_CD=''OPT'' THEN F2.FEAT_NAME

WHEN F.FEAT_SBTYPE_CD=''TERM'' THEN F.FEAT_NAME

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN F4.FEAT_NAME

END TERM_NAME, 

CASE WHEN F.FEAT_SBTYPE_CD=''TERM'' THEN F1.FEAT_ID

WHEN F.FEAT_SBTYPE_CD=''OPT'' THEN F3.FEAT_ID

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN F5.FEAT_ID

END COV_FEAT_ID, 

CASE WHEN F.FEAT_SBTYPE_CD=''TERM'' THEN F1.FEAT_NAME

WHEN F.FEAT_SBTYPE_CD=''OPT'' THEN F3.FEAT_NAME

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN F5.FEAT_NAME

END COV_NAME, 

CASE WHEN F.FEAT_SBTYPE_CD=''TERM'' THEN F1.NK_SRC_KEY

WHEN F.FEAT_SBTYPE_CD=''OPT'' THEN F3.NK_SRC_KEY

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN F5.NK_SRC_KEY

END COV_PATTERNCODE, 

CASE WHEN F.FEAT_SBTYPE_CD=''OPT'' THEN F2.NK_SRC_KEY

WHEN F.FEAT_SBTYPE_CD=''TERM'' THEN F.NK_SRC_KEY

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN F4.NK_SRC_KEY

END TERM_PATTERNCODE, 

CASE 

WHEN F.FEAT_SBTYPE_CD=''OPT'' AND F.FEAT_DTL_CD_NAME  IN (''ACTUAL'', ''REPLACEMENT'') THEN F.FEAT_DTL_CD_NAME  

WHEN F.FEAT_SBTYPE_CD=''OPT'' AND F.FEAT_DTL_CD_NAME NOT IN (''ACTUAL'', ''REPLACEMENT'') THEN CAST(F.FEAT_DTL_VAL AS DECIMAL(18,4)) 

WHEN F.FEAT_SBTYPE_CD=''TERM'' AND LENGTH(AGMT_FEAT_TXT)>0 THEN AF.AGMT_FEAT_TXT

WHEN F.FEAT_SBTYPE_CD=''TERM'' AND (LENGTH(AGMT_FEAT_TXT) =0 OR AGMT_FEAT_TXT IS NULL) THEN AF.AGMT_FEAT_AMT

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN  F.FEAT_DTL_CD_NAME

END VAL

FROM  DB_T_PROD_CORE.FEAT F 

JOIN  DB_T_PROD_CORE.AGMT_FEAT AF ON F.FEAT_ID=AF.FEAT_ID  AND CAST(AF.TRANS_END_DTTM  AS DATE) =''9999-12-31''

JOIN  DB_T_PROD_CORE.AGMT A ON AF.AGMT_ID=A.AGMT_ID AND CAST(A.EDW_END_DTTM AS DATE) =''9999-12-31''

LEFT JOIN  DB_T_PROD_CORE.FEAT_RLTD FR1 ON F.FEAT_ID=FR1.RLTD_FEAT_ID AND FR1.FEAT_RLTNSHP_TYPE_CD =''COVT'' AND CAST(FR1.TRANS_END_DTTM AS DATE) =''9999-12-31''

LEFT JOIN  DB_T_PROD_CORE.FEAT F1 ON FR1.FEAT_ID=F1.FEAT_ID

LEFT JOIN  DB_T_PROD_CORE.FEAT_RLTD FR2 ON F.FEAT_ID=FR2.RLTD_FEAT_ID AND FR2.FEAT_RLTNSHP_TYPE_CD =''TERMOPT''  AND CAST(FR2.TRANS_END_DTTM AS DATE) =''9999-12-31''

LEFT JOIN  DB_T_PROD_CORE.FEAT F2 ON FR2.FEAT_ID=F2.FEAT_ID

LEFT JOIN  DB_T_PROD_CORE.FEAT_RLTD FR3 ON F.FEAT_ID=FR3.RLTD_FEAT_ID AND FR3.FEAT_RLTNSHP_TYPE_CD =''COVOPTT''  AND CAST( FR3.TRANS_END_DTTM AS DATE) =''9999-12-31''

LEFT JOIN  DB_T_PROD_CORE.FEAT F3 ON FR3.FEAT_ID=F3.FEAT_ID

LEFT JOIN  DB_T_PROD_CORE.FEAT_RLTD FR4 ON F.FEAT_ID=FR4.RLTD_FEAT_ID AND FR4.FEAT_RLTNSHP_TYPE_CD =''TERMPKG''  AND  CAST( FR4.TRANS_END_DTTM AS DATE) =''9999-12-31''

LEFT JOIN  DB_T_PROD_CORE.FEAT F4 ON FR4.FEAT_ID=F4.FEAT_ID

LEFT JOIN  DB_T_PROD_CORE.FEAT_RLTD FR5 ON F.FEAT_ID=FR5.RLTD_FEAT_ID AND FR5.FEAT_RLTNSHP_TYPE_CD =''COVPKG''  AND CAST(  FR5.TRANS_END_DTTM AS DATE) =''9999-12-31''

LEFT JOIN  DB_T_PROD_CORE.FEAT F5 ON FR5.FEAT_ID=F5.FEAT_ID

WHERE F.FEAT_SBTYPE_CD IN (''TERM'', ''OPT'', ''PKG'')

AND F.FEAT_COVERABLE_TYPE_TXT IN (''PERSONALAUTOLINE'', ''HOMEOWNERSLINE_HOE'', ''HOLINESCHCOVITEM_ALFA'')

AND CASE WHEN F.FEAT_SBTYPE_CD=''TERM'' THEN F1.NK_SRC_KEY

WHEN F.FEAT_SBTYPE_CD=''OPT'' THEN F3.NK_SRC_KEY

WHEN F.FEAT_SBTYPE_CD=''PKG'' THEN F5.NK_SRC_KEY

END  NOT IN (''HOLI_SCHEDULEDPROPERTYDEDUCTIBLESITEM_ALFA'', ''HOSI_SCHEDULEDPROPERTYITEM_ALFA'')



) , 



UNDERWRITING AS

(

SELECT  MAX(O.PRTY_DESC) PRTY_DESC , PA.AGMT_ID

FROM DB_T_PROD_CORE.INTRNL_ORG  O,  DB_T_PROD_CORE.PRTY_AGMT PA

WHERE O.INTRNL_ORG_PRTY_ID=PA.PRTY_ID

  AND  PA.PRTY_AGMT_ROLE_CD=  ''CMP''

  AND  CAST( PA.TRANS_END_DTTM AS DATE) =''9999-12-31''

  AND  CAST(O.EDW_END_DTTM AS DATE) =''9999-12-31''

  GROUP BY PA.AGMT_ID

) ,



INFORCE_DAYS AS

(

SELECT AAA.AGMT_ID, AAA.HOST_AGMT_NUM,

DATEDIFF (DAY, INFORCE_START_DATE, INFORCE_END_DATE) AS DAYS_BETWEEN





FROM 

(

SELECT  DISTINCT AG.AGMT_ID, AG.HOST_AGMT_NUM, AST.AGMT_STS_CD, QUARTERBEGIN, AST.AGMT_STS_STRT_DTTM, AG.MODL_ACTL_END_DTTM, QUARTEREND,

CASE WHEN QUARTERBEGIN > AST.AGMT_STS_STRT_DTTM THEN QUARTERBEGIN ELSE AST.AGMT_STS_STRT_DTTM  END INFORCE_START_DATE,

CASE WHEN QUARTEREND < AG.MODL_ACTL_END_DTTM THEN QUARTEREND ELSE AG.MODL_ACTL_END_DTTM  END INFORCE_END_DATE

FROM 



(SELECT * FROM  DB_T_PROD_CORE.AGMT 
WHERE CAST(MODL_EFF_DTTM AS DATE) <=  (:FS_DATE) 

AND  CAST(MODL_CRTN_DTTM AS DATE) <=  (:FS_DATE)

AND AGMT_TYPE_CD = ''PPV'' 

QUALIFY RANK() OVER (PARTITION BY HOST_AGMT_NUM, TERM_NUM ORDER BY  MODL_NUM DESC) =1
) AG



JOIN 

(SELECT * FROM  DB_T_PROD_CORE.AGMT 

WHERE CAST(AGMT_EFF_DTTM AS DATE) <=  (:FS_DATE)

AND  CAST(AGMT_PLND_EXPN_DTTM AS DATE) >  (:FS_DATE)

AND AGMT_TYPE_CD = ''POLTRM'' 

) TERM ON TERM.HOST_AGMT_NUM = AG.HOST_AGMT_NUM AND TERM.TERM_NUM = AG.TERM_NUM



JOIN (

SELECT * FROM  DB_T_PROD_CORE.AGMT_STS 

WHERE AGMT_STS_STRT_DTTM (DATE) <=  (:FS_DATE)

AND AGMT_STS_CD <> ''CNFRMDDT''

QUALIFY RANK() OVER (PARTITION BY AGMT_ID ORDER BY AGMT_STS_STRT_DTTM DESC) = 1 

  ) AST ON AST.AGMT_ID = TERM.AGMT_ID AND AST.AGMT_STS_CD = ''INFORCE''

  

 JOIN (
  SELECT
    QUARTER(:FS_DATE) as QUARTER_OF_YEAR,
    YEAR(:FS_DATE) as YEAR_OF_CALENDAR,
    DATE_TRUNC(''QUARTER'', :FS_DATE) as QUARTERBEGIN,
    :FS_DATE as CALENDAR_DATE
)

WHERE  AG.AGMT_CUR_STS_CD=''BOUND''



AND AST.AGMT_STS_STRT_DTTM <=QUARTEREND

) AAA

GROUP BY AAA.HOST_AGMT_NUM, AAA.AGMT_ID

)







/* THE OUTERMOST GROUP BY SECTION WILL SUM UP ACROSS POLICIES */
SELECT 

YEAR_OF_CALENDAR, 

QUARTER_OF_YEAR, 

PLCY_RISK_STATE, 

UNDERWRITING_COMPANY, 

PLCY_TYPE_DESC,

CVGE_NAME, 

RISK_GARAGING_COUNTY, 

SUM(EARND_UNIT_CVGE_YR_AMT)  AS EARND_UNIT_CVGE_YR_AMT, 

SUM(INSRNC_YR_AMT) AS INSRNC_YR_AMT,

SUM (EARND_PREM_AMT)  AS EARND_PREM_AMT,

CURRENT_TIMESTAMP AS CRDT_DTTM,

CURRENT_TIMESTAMP AS UPDT_DTTM

FROM

( /*  THIS SECTION WILL SUM UP ACROSS COVERAGES BUT NOT ACROSS POLICIES */
 SELECT YEAR_OF_CALENDAR

 ,QUARTER_OF_YEAR

 , (

 SELECT  PRTY_DESC

 FROM  UNDERWRITING

 WHERE  AGMT_ID=TEMP.AGMT_ID) AS UNDERWRITING_COMPANY

 ,P.PROD_DESC AS PLCY_TYPE_DESC

 ,CVGE_NAME

 , HOST_AGMT_NUM

 ,  ( CAST(EARND_UNIT_CVGE_DAYS AS DECIMAL (10,4))/365 )  AS EARND_UNIT_CVGE_YR_AMT

 , (SELECT UPPER(GEOGRCL_AREA_NAME) FROM  DB_T_PROD_CORE.TERR T

  WHERE CAST(T.EDW_END_DTTM AS DATE) =''9999-12-31''

  AND TERR_ID=WRITTEN_STATE.LOC_ID ) AS  PLCY_RISK_STATE

 , CASE WHEN COUNTY IS NOT NULL THEN  COUNTY ELSE GARAGING_LOCATION.COUNTY  END AS RISK_GARAGING_COUNTY

 , MAX ( CVGE_LIMIT * CAST(EARND_UNIT_CVGE_DAYS AS DECIMAL (10,6))/36500000 ) AS INSRNC_YR_AMT

 , MAX (EARND_PREM_AMT)  AS EARND_PREM_AMT

 FROM 

 (

 

 

/* MAIN QUERY CONTAINING GRANULAR DATA */
 SELECT

 PAC.AGMT_ID,

 ID.HOST_AGMT_NUM,

 PAC.PRTY_ASSET_ID,

  CASE WHEN PAC.TERM_PATTERNCODE LIKE ''%DED%'' AND PAC.TERM_PATTERNCODE <> ''PAREDUCEDORADDEDON_ALFA'' THEN PAC.VAL ELSE 0 END  AS DED_AMT,

 PAC.COV_NAME  AS CVGE_NAME,

 

  ID.DAYS_BETWEEN  AS EARND_UNIT_CVGE_DAYS, 

 CASE WHEN PAC.TERM_PATTERNCODE LIKE ''%LIMIT%''  AND SUBSTR(PAC.TERM_PATTERNCODE, 1, 2) =''HO''  THEN CAST(PAC.VAL AS DECIMAL(10,2))  ELSE 0 END  AS CVGE_LIMIT,  

PLCY_ASSET_CVGE_AMT AS EARND_PREM_AMT,  /*  NEED TO UPDATE THIS LOGIC   */
 PAC.VAL ,

 PAC.TERM_PATTERNCODE

 

 FROM (SELECT * FROM PRTY_ASSET_COVERAGES PAC WHERE ( (PAC.TERM_PATTERNCODE LIKE ''%LIMIT%'' )  OR  (PAC.TERM_PATTERNCODE LIKE ''%DED%'')  )

  AND PAC.TERM_NAME NOT LIKE ''PERCENT%'')PAC

  

  JOIN  DB_T_PROD_CORE.AGMT A ON PAC.AGMT_ID=A.AGMT_ID  

 JOIN INFORCE_DAYS ID  ON ID.HOST_AGMT_NUM=PAC.HOST_AGMT_NUM

 LEFT  JOIN (SELECT AGMT_ID, FEAT_ID, PRTY_ASSET_ID,PLCY_ASSET_CVGE_AMT FROM  DB_T_PROD_CORE.PLCY_ASSET_CVGE_MTRC  WHERE INSRNC_MTRC_TYPE_CD=''ERNDPREM'') PACM

 ON A.AGMT_ID= PACM.AGMT_ID AND PAC.COV_FEAT_ID= PACM.FEAT_ID 

AND PAC.PRTY_ASSET_ID= PACM.PRTY_ASSET_ID /* AND PACM.INSRNC_MTRC_TYPE_CD=''ERNDPREM'' */
 

 UNION ALL

 

 SELECT

 AC.AGMT_ID,

 ID.HOST_AGMT_NUM,

 NULL AS PRTY_ASSET_ID,

 CASE WHEN AC.TERM_PATTERNCODE LIKE ''%DED%''  THEN AC.VAL ELSE 0 END  AS DED_AMT,

 AC.COV_NAME  AS CVGE_NAME, 

 ID.DAYS_BETWEEN  AS EARND_UNIT_CVGE_DAYS,  

 0 AS CVGE_LIMIT,  

  PLCY_CVGE_AMT AS EARND_PREM_AMT,  

 AC.VAL ,

 AC.TERM_PATTERNCODE

 

 FROM (SELECT * FROM AGMT_COVERAGES AC WHERE  ( (AC.TERM_PATTERNCODE LIKE ''%LIMIT%'' )  OR  (AC.TERM_PATTERNCODE LIKE ''%DED%'')  )  AND AC.TERM_NAME NOT LIKE ''PERCENT%'') AC

  JOIN  DB_T_PROD_CORE.AGMT A ON AC.AGMT_ID=A.AGMT_ID 

 JOIN INFORCE_DAYS ID ON ID.HOST_AGMT_NUM=AC.HOST_AGMT_NUM

 LEFT  JOIN (SELECT AGMT_ID, FEAT_ID , PLCY_CVGE_AMT FROM  DB_T_PROD_CORE.PLCY_CVGE_MTRC  WHERE INSRNC_MTRC_TYPE_CD=''ERNDPREM'') PCM ON A.AGMT_ID= PCM.AGMT_ID AND AC.COV_FEAT_ID= PCM.FEAT_ID 

 

/* END OF MAIN QUERY  */
 

 ) AS  TEMP

 

 JOIN  DB_T_PROD_CORE.AGMT_PROD AP ON  TEMP.AGMT_ID=AP.AGMT_ID AND CAST(AP.EDW_END_DTTM AS DATE) =''9999-12-31''

 LEFT JOIN  DB_T_PROD_CORE.AGMT_LOCTR  AS WRITTEN_STATE ON WRITTEN_STATE.AGMT_ID=TEMP.AGMT_ID AND WRITTEN_STATE.AGMT_LOCTR_ROLE_TYPE_CD=''AGTWINST''  AND CAST(WRITTEN_STATE.TRANS_END_DTTM AS DATE) =''9999-12-31''

 JOIN  DB_T_PROD_CORE.PROD  P  ON  AP.PROD_ID=P.PROD_ID AND CAST(P.EDW_END_DTTM AS DATE) =''9999-12-31''

 LEFT JOIN (

  SELECT  AA.AGMT_ID, MAX(AA.PRTY_ASSET_ID ) AS PRTY_ASSET_ID

  FROM DB_T_PROD_CORE.AGMT_ASSET AA,  DB_T_PROD_CORE.PRTY_ASSET PA

  WHERE AA.PRTY_ASSET_ID=PA.PRTY_ASSET_ID

  AND PA.PRTY_ASSET_SBTYPE_CD IN (''RE'', ''REALDW'') 

  AND PA.PRTY_ASSET_CLASFCN_CD=''MAIN''  

  AND AA.TRANS_END_DTTM=CAST(''9999-12-31 23:59:59.999999'' AS TIMESTAMP)

  AND CAST(PA.EDW_END_DTTM AS DATE) =''9999-12-31''

  GROUP BY AA.AGMT_ID )  ASSET ON  ASSET.AGMT_ID=TEMP.AGMT_ID 

 LEFT JOIN LOCATION_ADDRESS_PROPERTY AS RISK_LOCATION ON  ASSET.PRTY_ASSET_ID=RISK_LOCATION.PRTY_ASSET_ID 

 LEFT JOIN LOCATION_ADDRESS_AUTO  AS GARAGING_LOCATION ON  TEMP.PRTY_ASSET_ID = GARAGING_LOCATION.PRTY_ASSET_ID

LEFT JOIN (
  SELECT
    QUARTER(:FS_DATE) as QUARTER_OF_YEAR,
    YEAR(:FS_DATE) as YEAR_OF_CALENDAR,
    DATE_TRUNC(''QUARTER'', :FS_DATE) as QUARTERBEGIN
) CAL ON 1=1 

  

  GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9



)  SUM_ACROSS_COVERAGES



GROUP BY YEAR_OF_CALENDAR, 

QUARTER_OF_YEAR, 

UNDERWRITING_COMPANY, 

PLCY_RISK_STATE, 

RISK_GARAGING_COUNTY, 

PLCY_TYPE_DESC,

CVGE_NAME

ORDER BY 1,2,3,4,5,6,7
) SRC
)
);


-- Component exp_pass_to_tgt1, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_to_tgt1 AS
(
SELECT
ltrim ( rtrim ( SQ_FS_PLCY1.CAL_YR_NUM ) ) as CAL_YR_NUM_TRIM,
ltrim ( rtrim ( SQ_FS_PLCY1.CAL_QTR_NUM ) ) as CAL_QTR_NUM_TRIM,
SQ_FS_PLCY1.ST_CD as ST_CD,
SQ_FS_PLCY1.UNDRWRTG_CO_CD as UNDRWRTG_CO_CD,
SQ_FS_PLCY1.PLCY_TYPE_DESC as PLCY_TYPE_DESC,
SQ_FS_PLCY1.CVGE_NAME as CVGE_NAME,
SQ_FS_PLCY1.CNTY_NAME as CNTY_NAME,
SQ_FS_PLCY1.EARND_UNIT_CVGE_YR_AMT as EARND_UNIT_CVGE_YR_AMT,
SQ_FS_PLCY1.INSRNC_YR_AMT as INSRNC_YR_AMT,
SQ_FS_PLCY1.EARND_PREM_AMT as EARND_PREM_AMT,
SQ_FS_PLCY1.CRTD_DTTM as CRTD_DTTM,
SQ_FS_PLCY1.source_record_id
FROM
SQ_FS_PLCY1
);


-- Component tgt_FS_PLCY_ins1, Type TARGET 
INSERT INTO DB_T_PROD_WRK.FS_PLCY
(
CAL_YR_NUM,
CAL_QTR_NUM,
ST_CD,
UNDRWRTG_CO_CD,
PLCY_TYPE_DESC,
CVGE_NAME,
CNTY_NAME,
EARND_UNIT_CVGE_YR_AMT,
INSRNC_YR_AMT,
EARND_PREM_AMT,
LOAD_DTTM
)
SELECT
exp_pass_to_tgt1.CAL_YR_NUM_TRIM as CAL_YR_NUM,
exp_pass_to_tgt1.CAL_QTR_NUM_TRIM as CAL_QTR_NUM,
exp_pass_to_tgt1.ST_CD as ST_CD,
exp_pass_to_tgt1.UNDRWRTG_CO_CD as UNDRWRTG_CO_CD,
exp_pass_to_tgt1.PLCY_TYPE_DESC as PLCY_TYPE_DESC,
exp_pass_to_tgt1.CVGE_NAME as CVGE_NAME,
exp_pass_to_tgt1.CNTY_NAME as CNTY_NAME,
exp_pass_to_tgt1.EARND_UNIT_CVGE_YR_AMT as EARND_UNIT_CVGE_YR_AMT,
exp_pass_to_tgt1.INSRNC_YR_AMT as INSRNC_YR_AMT,
exp_pass_to_tgt1.EARND_PREM_AMT as EARND_PREM_AMT,
exp_pass_to_tgt1.CRTD_DTTM as LOAD_DTTM
FROM
exp_pass_to_tgt1;


-- PIPELINE END FOR 2

END; ';