-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_PREFILL_SUMRY_INSUPD("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
 DECLARE 
run_id varchar;
	start_dttm timestamp;
	end_dttm timestamp;
    prcs_id int;


BEGIN 
run_id :=   (SELECT run_id   FROM control_run_id where upper(worklet_name) = upper(:worklet_name) order by insert_ts desc limit 1);   
END_DTTM:=   (SELECT left(param_value,19) FROM control_params where run_id = :run_id and upper(param_name)=''END_DTTM'' order by insert_ts desc limit 1);
START_DTTM:=     (SELECT left(param_value,19) FROM control_params where run_id = :run_id and upper(param_name)=''START_DTTM'' order by insert_ts desc limit 1);
PRCS_ID:=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''PRCS_ID'' order by insert_ts desc limit 1);
-- PIPELINE START FOR 1

-- Component SQ_pc_effectivedatedfields, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_pc_effectivedatedfields AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as BranchID,
$2 as PrimaryNamedInsured,
$3 as UpdateTime,
$4 as PrefillAddData_alfa,
$5 as PrefillIDCheck_alfa,
$6 as nk_publc_id,
$7 as rnk,
$8 as nk_src_key,
$9 as jobnumber,
$10 as branchnumber,
$11 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT	BranchID,

 PrimaryNamedInsured,

 updatetime,

prefilladddata_alfa,

prefillidcheck_alfa,  

cast (nk_publc_id as varchar(64)) as nk_publc_id,

	 Rank()  OVER(

PARTITION BY BranchID, PrimaryNamedInsured,

		nk_publc_id 

ORDER BY updatetime )  as rnk,

cast(nk_src_key as varchar(64)) as nk_src_key,

 cast(jobnumber as varchar(60)) as jobnumber,

cast(branchnumber as varchar(60)) as branchnumber

 from	(

 SELECT distinct

 effdt.PrimaryNamedInsured_stg as PrimaryNamedInsured,  

 effdt.updatetime_stg as updatetime,

 effdt.BranchID_stg as BranchID,

effdt.prefilladddata_alfa_stg as prefilladddata_alfa,   

effdt.prefillidcheck_alfa_stg as prefillidcheck_alfa,

cast(cnt.addressbookuid_stg as varchar(64)) AS nk_publc_id,

cast(pp.publicid_stg as varchar(64))as nk_src_key,

pcj.JobNumber_stg as jobnumber,

pp.branchnumber_stg as  branchnumber

from   DB_T_PROD_STAG.pc_effectivedatedfields as effdt

left outer join   DB_T_PROD_STAG.pc_policyperiod pp on pp.id_stg=effdt.BranchID_stg

left outer join   DB_T_PROD_STAG.pc_policycontactrole pcr on pp.id_stg=pcr.BranchId_stg and pcr.FixedID_stg=effdt.PrimaryNamedInsured_stg

left outer join   DB_T_PROD_STAG.pc_contact cnt on cnt.id_stg=pcr.ContactDenorm_stg

left outer join    DB_T_PROD_STAG.pctl_contact ON pctl_contact.id_stg = cnt.subtype_stg

LEFT OUTER JOIN   DB_T_PROD_STAG.pc_job pcj ON pcj.id_stg = pp.JobID_stg

 LEFT OUTER  JOIN   DB_T_PROD_STAG.pctl_job pctlj ON pctlj.id_stg=pcj.Subtype_stg

LEFT JOIN   DB_T_PROD_STAG.pctl_policyperiodstatus pps ON pps.id_stg = pp.Status_stg

WHERE effdt.ExpirationDate_stg is null and pctlj.TYPECODE_stg  IN (''Cancellation'',''PolicyChange'',''Reinstatement'', ''Renewal'',''Rewrite'',''Submission'')

 AND pps.Typecode_stg<>''Temporary'' and effdt.UpdateTime_stg > (:start_dttm) and effdt.UpdateTime_stg <= (:end_dttm)

 )src

  QUALIFY	ROW_NUMBER() OVER(

PARTITION BY  nk_src_key,

jobnumber,

branchnumber,

prefilladddata_alfa,

prefillidcheck_alfa, nk_publc_id  

ORDER BY updatetime DESC) = 1
) SRC
)
);


-- Component exp_pc_effectivedatedfields, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pc_effectivedatedfields AS
(
SELECT
SQ_pc_effectivedatedfields.UpdateTime as UpdateTime,
SQ_pc_effectivedatedfields.PrefillAddData_alfa as PrefillAddData_alfa,
SQ_pc_effectivedatedfields.PrefillIDCheck_alfa as PrefillIDCheck_alfa,
SQ_pc_effectivedatedfields.nk_publc_id as nk_publc_id,
SQ_pc_effectivedatedfields.rnk as rnk,
SQ_pc_effectivedatedfields.nk_src_key as nk_src_key,
SQ_pc_effectivedatedfields.jobnumber as jobnumber,
SQ_pc_effectivedatedfields.branchnumber as branchnumber,
''PPV'' as IN_AGMT_TYPE_CD,
''CO'' as in_BUSN_CTGY_CD_CO,
''COV'' as in_BUSN_CTGY_CD_COV,
SQ_pc_effectivedatedfields.source_record_id
FROM
SQ_pc_effectivedatedfields
);


-- Component LKP_PREFILL_IDCHK, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_PREFILL_IDCHK AS
(
SELECT
LKP.PREFILL_IDCHK_ID,
exp_pc_effectivedatedfields.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pc_effectivedatedfields.source_record_id ORDER BY LKP.PREFILL_IDCHK_ID asc,LKP.HRI5_DESC asc,LKP.HRI3_DESC asc,LKP.HRI1_DESC asc,LKP.HRI5_SCR_VAL asc,LKP.HRI3_SCR_VAL asc,LKP.HRI1_SCR_VAL asc,LKP.NK_SRC_KEY asc,LKP.HRI6_DESC asc,LKP.CVI_DESC asc,LKP.HRI4_DESC asc,LKP.HRI2_DESC asc,LKP.PREFILL_IDCHK_TYPE_CD asc,LKP.HRI6_SCR_VAL asc,LKP.CVI_SCR_VAL asc,LKP.HRI4_SCR_VAL asc,LKP.HRI2_SCR_VAL asc,LKP.PRCS_ID asc,LKP.EDW_STRT_DTTM asc,LKP.EDW_END_DTTM asc,LKP.TRANS_STRT_DTTM asc,LKP.TRANS_END_DTTM asc) RNK
FROM
exp_pc_effectivedatedfields
LEFT JOIN (
SELECT PREFILL_IDCHK.HRI5_DESC as HRI5_DESC, PREFILL_IDCHK.HRI3_DESC as HRI3_DESC, PREFILL_IDCHK.HRI1_DESC as HRI1_DESC, PREFILL_IDCHK.HRI5_SCR_VAL as HRI5_SCR_VAL, PREFILL_IDCHK.HRI3_SCR_VAL as HRI3_SCR_VAL, PREFILL_IDCHK.HRI1_SCR_VAL as HRI1_SCR_VAL, PREFILL_IDCHK.NK_SRC_KEY as NK_SRC_KEY, PREFILL_IDCHK.HRI6_DESC as HRI6_DESC, PREFILL_IDCHK.CVI_DESC as CVI_DESC, PREFILL_IDCHK.HRI4_DESC as HRI4_DESC, PREFILL_IDCHK.HRI2_DESC as HRI2_DESC, PREFILL_IDCHK.PREFILL_IDCHK_TYPE_CD as PREFILL_IDCHK_TYPE_CD, PREFILL_IDCHK.HRI6_SCR_VAL as HRI6_SCR_VAL, PREFILL_IDCHK.CVI_SCR_VAL as CVI_SCR_VAL, PREFILL_IDCHK.HRI4_SCR_VAL as HRI4_SCR_VAL, PREFILL_IDCHK.HRI2_SCR_VAL as HRI2_SCR_VAL, PREFILL_IDCHK.PRCS_ID as PRCS_ID, PREFILL_IDCHK.EDW_STRT_DTTM as EDW_STRT_DTTM, PREFILL_IDCHK.EDW_END_DTTM as EDW_END_DTTM, PREFILL_IDCHK.TRANS_STRT_DTTM as TRANS_STRT_DTTM, PREFILL_IDCHK.TRANS_END_DTTM as TRANS_END_DTTM, 
PREFILL_IDCHK.PREFILL_IDCHK_ID as PREFILL_IDCHK_ID FROM DB_T_PROD_CORE.PREFILL_IDCHK
QUALIFY	ROW_NUMBER() OVER(PARTITION BY  PREFILL_IDCHK.PREFILL_IDCHK_ID 
ORDER	BY PREFILL_IDCHK.EDW_END_DTTM DESC) = 1
) LKP ON LKP.PREFILL_IDCHK_ID = exp_pc_effectivedatedfields.PrefillIDCheck_alfa
QUALIFY RNK = 1
);


-- Component LKP_BUSN_CO, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_BUSN_CO AS
(
SELECT
LKP.BUSN_PRTY_ID,
exp_pc_effectivedatedfields.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pc_effectivedatedfields.source_record_id ORDER BY LKP.BUSN_PRTY_ID desc,LKP.BUSN_CTGY_CD desc,LKP.NK_BUSN_CD desc,LKP.SRC_SYS_CD desc,LKP.TAX_BRAKT_CD desc,LKP.ORG_TYPE_CD desc,LKP.GICS_SBIDSTRY_CD desc,LKP.LIFCYCL_CD desc,LKP.PRTY_TYPE_CD desc,LKP.BUSN_END_DTTM desc,LKP.BUSN_STRT_DTTM desc,LKP.INC_IND desc,LKP.EDW_STRT_DTTM desc,LKP.EDW_END_DTTM desc) RNK
FROM
exp_pc_effectivedatedfields
LEFT JOIN (
SELECT BUSN.BUSN_PRTY_ID as BUSN_PRTY_ID, BUSN.SRC_SYS_CD as SRC_SYS_CD, BUSN.TAX_BRAKT_CD as TAX_BRAKT_CD, BUSN.ORG_TYPE_CD as ORG_TYPE_CD, BUSN.GICS_SBIDSTRY_CD as GICS_SBIDSTRY_CD, BUSN.LIFCYCL_CD as LIFCYCL_CD, BUSN.PRTY_TYPE_CD as PRTY_TYPE_CD, BUSN.BUSN_END_DTTM as BUSN_END_DTTM, BUSN.BUSN_STRT_DTTM as BUSN_STRT_DTTM, BUSN.INC_IND as INC_IND, BUSN.EDW_STRT_DTTM as EDW_STRT_DTTM, BUSN.EDW_END_DTTM as EDW_END_DTTM, BUSN.BUSN_CTGY_CD as BUSN_CTGY_CD, BUSN.NK_BUSN_CD as NK_BUSN_CD 
FROM DB_T_PROD_CORE.BUSN 
QUALIFY ROW_NUMBER () OVER (PARTITION BY NK_BUSN_CD,BUSN_CTGY_CD ORDER BY EDW_END_DTTM DESC )=1
) LKP ON LKP.BUSN_CTGY_CD = exp_pc_effectivedatedfields.in_BUSN_CTGY_CD_CO AND LKP.NK_BUSN_CD = exp_pc_effectivedatedfields.nk_publc_id
QUALIFY RNK = 1
);


-- Component LKP_INSRNC_QUOTN, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_INSRNC_QUOTN AS
(
SELECT
LKP.QUOTN_ID,
exp_pc_effectivedatedfields.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pc_effectivedatedfields.source_record_id ORDER BY LKP.QUOTN_ID asc) RNK
FROM
exp_pc_effectivedatedfields
LEFT JOIN (
SELECT INSRNC_QUOTN.QUOTN_ID AS QUOTN_ID, INSRNC_QUOTN.NK_JOB_NBR AS NK_JOB_NBR, INSRNC_QUOTN.VERS_NBR AS VERS_NBR FROM DB_T_PROD_CORE.INSRNC_QUOTN
QUALIFY ROW_NUMBER() OVER(PARTITION BY  INSRNC_QUOTN.NK_JOB_NBR, INSRNC_QUOTN.VERS_NBR,  INSRNC_QUOTN.SRC_SYS_CD  ORDER BY INSRNC_QUOTN.EDW_END_DTTM DESC) = 1
) LKP ON LKP.NK_JOB_NBR = exp_pc_effectivedatedfields.jobnumber AND LKP.VERS_NBR = exp_pc_effectivedatedfields.branchnumber
QUALIFY RNK = 1
);


-- Component LKP_INDIV_CNT_MGR, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_INDIV_CNT_MGR AS
(
SELECT
LKP.INDIV_PRTY_ID,
exp_pc_effectivedatedfields.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pc_effectivedatedfields.source_record_id ORDER BY LKP.INDIV_PRTY_ID desc,LKP.NK_LINK_ID desc) RNK
FROM
exp_pc_effectivedatedfields
LEFT JOIN (
SELECT 
	INDIV.INDIV_PRTY_ID as INDIV_PRTY_ID, 
	INDIV.NK_LINK_ID as NK_LINK_ID 
FROM 
	DB_T_PROD_CORE.INDIV
WHERE
	INDIV.NK_PUBLC_ID IS NULL
) LKP ON LKP.NK_LINK_ID = exp_pc_effectivedatedfields.nk_publc_id
QUALIFY RNK = 1
);


-- Component LKP_AGMT_PPV, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_AGMT_PPV AS
(
SELECT
LKP.AGMT_ID,
exp_pc_effectivedatedfields.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pc_effectivedatedfields.source_record_id ORDER BY LKP.AGMT_ID asc,LKP.HOST_AGMT_NUM asc,LKP.AGMT_NAME asc,LKP.AGMT_OPN_DTTM asc,LKP.AGMT_CLS_DTTM asc,LKP.AGMT_PLND_EXPN_DTTM asc,LKP.AGMT_SIGND_DTTM asc,LKP.AGMT_TYPE_CD asc,LKP.AGMT_LEGLY_BINDG_IND asc,LKP.AGMT_SRC_CD asc,LKP.AGMT_CUR_STS_CD asc,LKP.AGMT_CUR_STS_RSN_CD asc,LKP.AGMT_OBTND_CD asc,LKP.AGMT_SBTYPE_CD asc,LKP.AGMT_PRCSG_DTTM asc,LKP.ALT_AGMT_NAME asc,LKP.ASSET_LIABTY_CD asc,LKP.BAL_SHET_CD asc,LKP.STMT_CYCL_CD asc,LKP.STMT_ML_TYPE_CD asc,LKP.PRPOSL_ID asc,LKP.AGMT_OBJTV_TYPE_CD asc,LKP.FINCL_AGMT_SBTYPE_CD asc,LKP.MKT_RISK_TYPE_CD asc,LKP.ORIGNL_MATURTY_DT asc,LKP.RISK_EXPSR_MTGNT_SBTYPE_CD asc,LKP.BNK_TRD_BK_CD asc,LKP.PRCG_METH_SBTYPE_CD asc,LKP.FINCL_AGMT_TYPE_CD asc,LKP.DY_CNT_BSS_CD asc,LKP.FRST_PREM_DUE_DT asc,LKP.INSRNC_AGMT_SBTYPE_CD asc,LKP.INSRNC_AGMT_TYPE_CD asc,LKP.NTWK_SRVC_AGMT_TYPE_CD asc,LKP.FRMLTY_TYPE_CD asc,LKP.CNTRCT_TERM_NUM asc,LKP.RATE_RPRCG_CYCL_MTH_NUM asc,LKP.CMPND_INT_CYCL_MTH_NUM asc,LKP.MDTERM_INT_PMT_CYCL_MTH_NUM asc,LKP.PREV_MDTERM_INT_PMT_DT asc,LKP.NXT_MDTERM_INT_PMT_DT asc,LKP.PREV_INT_RATE_RVSD_DT asc,LKP.NXT_INT_RATE_RVSD_DT asc,LKP.PREV_REF_DT_INT_RATE asc,LKP.NXT_REF_DT_FOR_INT_RATE asc,LKP.MDTERM_CNCLTN_DT asc,LKP.STK_FLOW_CLAS_IN_MTH_IND asc,LKP.STK_FLOW_CLAS_IN_TERM_IND asc,LKP.LGCY_DSCNT_IND asc,LKP.AGMT_IDNTFTN_CD asc,LKP.TRMTN_TYPE_CD asc,LKP.INT_PMT_METH_CD asc,LKP.LBR_AGMT_DESC asc,LKP.GUARTD_IMPRSNS_CNT asc,LKP.COST_PER_IMPRSN_AMT asc,LKP.GUARTD_CLKTHRU_CNT asc,LKP.COST_PER_CLKTHRU_AMT asc,LKP.BUSN_PRTY_ID asc,LKP.PMT_PLN_TYPE_CD asc,LKP.INVC_STREM_TYPE_CD asc,LKP.MODL_CRTN_DTTM asc,LKP.CNTNUS_SRVC_DTTM asc,LKP.BILG_METH_TYPE_CD asc,LKP.SRC_SYS_CD asc,LKP.AGMT_EFF_DTTM asc,LKP.MODL_EFF_DTTM asc,LKP.PRCS_ID asc,LKP.MODL_ACTL_END_DTTM asc,LKP.TIER_TYPE_CD asc,LKP.EDW_STRT_DTTM asc,LKP.EDW_END_DTTM asc,LKP.VFYD_PLCY_IND asc,LKP.SRC_OF_BUSN_CD asc,LKP.NK_SRC_KEY asc,LKP.OVRD_COMS_TYPE_CD asc,LKP.LGCY_PLCY_IND asc,LKP.TRANS_STRT_DTTM asc) RNK
FROM
exp_pc_effectivedatedfields
LEFT JOIN (
SELECT AGMT.AGMT_ID as AGMT_ID, AGMT.HOST_AGMT_NUM as HOST_AGMT_NUM, AGMT.AGMT_NAME as AGMT_NAME, AGMT.AGMT_OPN_DTTM as AGMT_OPN_DTTM, AGMT.AGMT_CLS_DTTM as AGMT_CLS_DTTM, AGMT.AGMT_PLND_EXPN_DTTM as AGMT_PLND_EXPN_DTTM, AGMT.AGMT_SIGND_DTTM as AGMT_SIGND_DTTM, AGMT.AGMT_LEGLY_BINDG_IND as AGMT_LEGLY_BINDG_IND, AGMT.AGMT_SRC_CD as AGMT_SRC_CD, AGMT.AGMT_CUR_STS_CD as AGMT_CUR_STS_CD, AGMT.AGMT_CUR_STS_RSN_CD as AGMT_CUR_STS_RSN_CD, AGMT.AGMT_OBTND_CD as AGMT_OBTND_CD, AGMT.AGMT_SBTYPE_CD as AGMT_SBTYPE_CD, AGMT.AGMT_PRCSG_DTTM as AGMT_PRCSG_DTTM, AGMT.ALT_AGMT_NAME as ALT_AGMT_NAME, AGMT.ASSET_LIABTY_CD as ASSET_LIABTY_CD, AGMT.BAL_SHET_CD as BAL_SHET_CD, AGMT.STMT_CYCL_CD as STMT_CYCL_CD, AGMT.STMT_ML_TYPE_CD as STMT_ML_TYPE_CD, AGMT.PRPOSL_ID as PRPOSL_ID, AGMT.AGMT_OBJTV_TYPE_CD as AGMT_OBJTV_TYPE_CD, AGMT.FINCL_AGMT_SBTYPE_CD as FINCL_AGMT_SBTYPE_CD, AGMT.MKT_RISK_TYPE_CD as MKT_RISK_TYPE_CD, AGMT.ORIGNL_MATURTY_DT as ORIGNL_MATURTY_DT, AGMT.RISK_EXPSR_MTGNT_SBTYPE_CD as RISK_EXPSR_MTGNT_SBTYPE_CD, AGMT.BNK_TRD_BK_CD as BNK_TRD_BK_CD, AGMT.PRCG_METH_SBTYPE_CD as PRCG_METH_SBTYPE_CD, AGMT.FINCL_AGMT_TYPE_CD as FINCL_AGMT_TYPE_CD, AGMT.DY_CNT_BSS_CD as DY_CNT_BSS_CD, AGMT.FRST_PREM_DUE_DT as FRST_PREM_DUE_DT, AGMT.INSRNC_AGMT_SBTYPE_CD as INSRNC_AGMT_SBTYPE_CD, AGMT.INSRNC_AGMT_TYPE_CD as INSRNC_AGMT_TYPE_CD, AGMT.NTWK_SRVC_AGMT_TYPE_CD as NTWK_SRVC_AGMT_TYPE_CD, AGMT.FRMLTY_TYPE_CD as FRMLTY_TYPE_CD, AGMT.CNTRCT_TERM_NUM as CNTRCT_TERM_NUM, AGMT.RATE_RPRCG_CYCL_MTH_NUM as RATE_RPRCG_CYCL_MTH_NUM, AGMT.CMPND_INT_CYCL_MTH_NUM as CMPND_INT_CYCL_MTH_NUM, AGMT.MDTERM_INT_PMT_CYCL_MTH_NUM as MDTERM_INT_PMT_CYCL_MTH_NUM, AGMT.PREV_MDTERM_INT_PMT_DT as PREV_MDTERM_INT_PMT_DT, AGMT.NXT_MDTERM_INT_PMT_DT as NXT_MDTERM_INT_PMT_DT, AGMT.PREV_INT_RATE_RVSD_DT as PREV_INT_RATE_RVSD_DT, AGMT.NXT_INT_RATE_RVSD_DT as NXT_INT_RATE_RVSD_DT, AGMT.PREV_REF_DT_INT_RATE as PREV_REF_DT_INT_RATE, AGMT.NXT_REF_DT_FOR_INT_RATE as NXT_REF_DT_FOR_INT_RATE, AGMT.MDTERM_CNCLTN_DT as MDTERM_CNCLTN_DT, AGMT.STK_FLOW_CLAS_IN_MTH_IND as STK_FLOW_CLAS_IN_MTH_IND, AGMT.STK_FLOW_CLAS_IN_TERM_IND as STK_FLOW_CLAS_IN_TERM_IND, AGMT.LGCY_DSCNT_IND as LGCY_DSCNT_IND, AGMT.AGMT_IDNTFTN_CD as AGMT_IDNTFTN_CD, AGMT.TRMTN_TYPE_CD as TRMTN_TYPE_CD, AGMT.INT_PMT_METH_CD as INT_PMT_METH_CD, AGMT.LBR_AGMT_DESC as LBR_AGMT_DESC, AGMT.GUARTD_IMPRSNS_CNT as GUARTD_IMPRSNS_CNT, AGMT.COST_PER_IMPRSN_AMT as COST_PER_IMPRSN_AMT, AGMT.GUARTD_CLKTHRU_CNT as GUARTD_CLKTHRU_CNT, AGMT.COST_PER_CLKTHRU_AMT as COST_PER_CLKTHRU_AMT, AGMT.BUSN_PRTY_ID as BUSN_PRTY_ID, AGMT.PMT_PLN_TYPE_CD as PMT_PLN_TYPE_CD, AGMT.INVC_STREM_TYPE_CD as INVC_STREM_TYPE_CD, AGMT.MODL_CRTN_DTTM as MODL_CRTN_DTTM, AGMT.CNTNUS_SRVC_DTTM as CNTNUS_SRVC_DTTM, AGMT.BILG_METH_TYPE_CD as BILG_METH_TYPE_CD, AGMT.SRC_SYS_CD as SRC_SYS_CD, AGMT.AGMT_EFF_DTTM as AGMT_EFF_DTTM, AGMT.MODL_EFF_DTTM as MODL_EFF_DTTM, AGMT.PRCS_ID as PRCS_ID, AGMT.MODL_ACTL_END_DTTM as MODL_ACTL_END_DTTM, AGMT.TIER_TYPE_CD as TIER_TYPE_CD, AGMT.EDW_STRT_DTTM as EDW_STRT_DTTM, AGMT.EDW_END_DTTM as EDW_END_DTTM, AGMT.VFYD_PLCY_IND as VFYD_PLCY_IND, AGMT.SRC_OF_BUSN_CD as SRC_OF_BUSN_CD, AGMT.OVRD_COMS_TYPE_CD as OVRD_COMS_TYPE_CD, AGMT.LGCY_PLCY_IND as LGCY_PLCY_IND, AGMT.TRANS_STRT_DTTM as TRANS_STRT_DTTM, AGMT.NK_SRC_KEY as NK_SRC_KEY, AGMT.AGMT_TYPE_CD as AGMT_TYPE_CD FROM DB_T_PROD_CORE.AGMT QUALIFY ROW_NUMBER() OVER(PARTITION BY AGMT.NK_SRC_KEY,AGMT.HOST_AGMT_NUM  ORDER BY AGMT.EDW_END_DTTM desc) = 1
) LKP ON LKP.NK_SRC_KEY = exp_pc_effectivedatedfields.nk_src_key AND LKP.AGMT_TYPE_CD = exp_pc_effectivedatedfields.IN_AGMT_TYPE_CD
QUALIFY RNK = 1
);


-- Component LKP_BUSN_COV, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_BUSN_COV AS
(
SELECT
LKP.BUSN_PRTY_ID,
exp_pc_effectivedatedfields.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pc_effectivedatedfields.source_record_id ORDER BY LKP.BUSN_PRTY_ID desc,LKP.BUSN_CTGY_CD desc,LKP.NK_BUSN_CD desc,LKP.SRC_SYS_CD desc,LKP.TAX_BRAKT_CD desc,LKP.ORG_TYPE_CD desc,LKP.GICS_SBIDSTRY_CD desc,LKP.LIFCYCL_CD desc,LKP.PRTY_TYPE_CD desc,LKP.BUSN_END_DTTM desc,LKP.BUSN_STRT_DTTM desc,LKP.INC_IND desc,LKP.EDW_STRT_DTTM desc,LKP.EDW_END_DTTM desc) RNK
FROM
exp_pc_effectivedatedfields
LEFT JOIN (
SELECT BUSN.BUSN_PRTY_ID as BUSN_PRTY_ID, BUSN.SRC_SYS_CD as SRC_SYS_CD, BUSN.TAX_BRAKT_CD as TAX_BRAKT_CD, BUSN.ORG_TYPE_CD as ORG_TYPE_CD, BUSN.GICS_SBIDSTRY_CD as GICS_SBIDSTRY_CD, BUSN.LIFCYCL_CD as LIFCYCL_CD, BUSN.PRTY_TYPE_CD as PRTY_TYPE_CD, BUSN.BUSN_END_DTTM as BUSN_END_DTTM, BUSN.BUSN_STRT_DTTM as BUSN_STRT_DTTM, BUSN.INC_IND as INC_IND, BUSN.EDW_STRT_DTTM as EDW_STRT_DTTM, BUSN.EDW_END_DTTM as EDW_END_DTTM, BUSN.BUSN_CTGY_CD as BUSN_CTGY_CD, BUSN.NK_BUSN_CD as NK_BUSN_CD 
FROM DB_T_PROD_CORE.BUSN 
QUALIFY ROW_NUMBER () OVER (PARTITION BY NK_BUSN_CD,BUSN_CTGY_CD ORDER BY EDW_END_DTTM DESC )=1
) LKP ON LKP.BUSN_CTGY_CD = exp_pc_effectivedatedfields.in_BUSN_CTGY_CD_COV AND LKP.NK_BUSN_CD = exp_pc_effectivedatedfields.nk_publc_id
QUALIFY RNK = 1
);


-- Component LKP_PREFILL_ADDLDATA, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_PREFILL_ADDLDATA AS
(
SELECT
LKP.PREFILL_ADDLDATA_ID,
exp_pc_effectivedatedfields.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pc_effectivedatedfields.source_record_id ORDER BY LKP.PREFILL_ADDLDATA_ID asc,LKP.CARIER_NAME asc,LKP.NK_SRC_KEY asc,LKP.CVGE_LAPS_IND asc,LKP.LAST_CNCLTN_DTTM asc,LKP.RISK_TYPE_CD asc,LKP.PRIOR_PLCY_INCPTN_DTTM asc,LKP.PREFILL_ST_NAME asc,LKP.OCCRNC_CD asc,LKP.LAST_CNCLTN_RSN_CD asc,LKP.PRIOR_PLCY_IND asc,LKP.EXSTG_CUST_RLTNSHP_IND asc,LKP.RLTNSHP_CD asc,LKP.STS_CD asc,LKP.PREFILL_ADDLDATA_TYPE_CD asc,LKP.PRIOR_NUM_POLS_CNT asc,LKP.PARNT_PLCY_NUM asc,LKP.PLCY_LAPS_IND asc,LKP.PRCS_ID asc,LKP.EDW_STRT_DTTM asc,LKP.EDW_END_DTTM asc,LKP.TRANS_STRT_DTTM asc,LKP.TRANS_END_DTTM asc) RNK
FROM
exp_pc_effectivedatedfields
LEFT JOIN (
SELECT PREFILL_ADDLDATA.CARIER_NAME as CARIER_NAME, PREFILL_ADDLDATA.NK_SRC_KEY as NK_SRC_KEY, PREFILL_ADDLDATA.CVGE_LAPS_IND as CVGE_LAPS_IND, PREFILL_ADDLDATA.LAST_CNCLTN_DTTM as LAST_CNCLTN_DTTM, PREFILL_ADDLDATA.RISK_TYPE_CD as RISK_TYPE_CD, PREFILL_ADDLDATA.PRIOR_PLCY_INCPTN_DTTM as PRIOR_PLCY_INCPTN_DTTM, PREFILL_ADDLDATA.PREFILL_ST_NAME as PREFILL_ST_NAME, PREFILL_ADDLDATA.OCCRNC_CD as OCCRNC_CD, PREFILL_ADDLDATA.LAST_CNCLTN_RSN_CD as LAST_CNCLTN_RSN_CD, PREFILL_ADDLDATA.PRIOR_PLCY_IND as PRIOR_PLCY_IND, PREFILL_ADDLDATA.EXSTG_CUST_RLTNSHP_IND as EXSTG_CUST_RLTNSHP_IND, PREFILL_ADDLDATA.RLTNSHP_CD as RLTNSHP_CD, PREFILL_ADDLDATA.STS_CD as STS_CD, PREFILL_ADDLDATA.PREFILL_ADDLDATA_TYPE_CD as PREFILL_ADDLDATA_TYPE_CD, PREFILL_ADDLDATA.PRIOR_NUM_POLS_CNT as PRIOR_NUM_POLS_CNT, PREFILL_ADDLDATA.PARNT_PLCY_NUM as PARNT_PLCY_NUM, PREFILL_ADDLDATA.PLCY_LAPS_IND as PLCY_LAPS_IND, PREFILL_ADDLDATA.PRCS_ID as PRCS_ID, PREFILL_ADDLDATA.EDW_STRT_DTTM as EDW_STRT_DTTM, PREFILL_ADDLDATA.EDW_END_DTTM as EDW_END_DTTM, PREFILL_ADDLDATA.TRANS_STRT_DTTM as TRANS_STRT_DTTM, PREFILL_ADDLDATA.TRANS_END_DTTM as TRANS_END_DTTM, PREFILL_ADDLDATA.PREFILL_ADDLDATA_ID as PREFILL_ADDLDATA_ID FROM DB_T_PROD_CORE.PREFILL_ADDLDATA
QUALIFY	ROW_NUMBER() OVER(PARTITION BY  PREFILL_ADDLDATA.PREFILL_ADDLDATA_ID 
ORDER	BY PREFILL_ADDLDATA.EDW_END_DTTM DESC) = 1
) LKP ON LKP.PREFILL_ADDLDATA_ID = exp_pc_effectivedatedfields.PrefillAddData_alfa
QUALIFY RNK = 1
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
LKP_AGMT_PPV.AGMT_ID as AGMT_ID,
LKP_INSRNC_QUOTN.QUOTN_ID as QUOTN_ID,
LKP_PREFILL_ADDLDATA.PREFILL_ADDLDATA_ID as PrefillAddData_alfa,
LKP_PREFILL_IDCHK.PREFILL_IDCHK_ID as PrefillIDCheck_alfa,
exp_pc_effectivedatedfields.UpdateTime as UpdateTime,
exp_pc_effectivedatedfields.rnk as rnk,
CASE WHEN LKP_INDIV_CNT_MGR.INDIV_PRTY_ID IS NOT NULL THEN LKP_INDIV_CNT_MGR.INDIV_PRTY_ID ELSE CASE WHEN LKP_BUSN_CO.BUSN_PRTY_ID IS NOT NULL THEN LKP_BUSN_CO.BUSN_PRTY_ID ELSE CASE WHEN LKP_BUSN_COV.BUSN_PRTY_ID IS NOT NULL THEN LKP_BUSN_COV.BUSN_PRTY_ID ELSE null END END END as INDIV_PRTY_ID,
exp_pc_effectivedatedfields.source_record_id
FROM
exp_pc_effectivedatedfields
INNER JOIN LKP_PREFILL_IDCHK ON exp_pc_effectivedatedfields.source_record_id = LKP_PREFILL_IDCHK.source_record_id
INNER JOIN LKP_BUSN_CO ON LKP_PREFILL_IDCHK.source_record_id = LKP_BUSN_CO.source_record_id
INNER JOIN LKP_INSRNC_QUOTN ON LKP_BUSN_CO.source_record_id = LKP_INSRNC_QUOTN.source_record_id
INNER JOIN LKP_INDIV_CNT_MGR ON LKP_INSRNC_QUOTN.source_record_id = LKP_INDIV_CNT_MGR.source_record_id
INNER JOIN LKP_AGMT_PPV ON LKP_INDIV_CNT_MGR.source_record_id = LKP_AGMT_PPV.source_record_id
INNER JOIN LKP_BUSN_COV ON LKP_AGMT_PPV.source_record_id = LKP_BUSN_COV.source_record_id
INNER JOIN LKP_PREFILL_ADDLDATA ON LKP_BUSN_COV.source_record_id = LKP_PREFILL_ADDLDATA.source_record_id
);


-- Component LKP_PREFILL_SUMRY, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_PREFILL_SUMRY AS
(
SELECT
LKP.PREFILL_SUMRY_ID,
LKP.QUOTN_ID,
LKP.INDIV_PRTY_ID,
LKP.AGMT_ID,
LKP.EDW_STRT_DTTM,
LKP.EDW_END_DTTM,
exp_pass_through.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pass_through.source_record_id ORDER BY LKP.PREFILL_SUMRY_ID asc,LKP.QUOTN_ID asc,LKP.INDIV_PRTY_ID asc,LKP.PREFILL_ADDLDATA_ID asc,LKP.PREFILL_IDCHK_ID asc,LKP.AGMT_ID asc,LKP.PRCS_ID asc,LKP.EDW_STRT_DTTM asc,LKP.EDW_END_DTTM asc,LKP.TRANS_STRT_DTTM asc,LKP.TRANS_END_DTTM asc) RNK
FROM
exp_pass_through
LEFT JOIN (
SELECT	PREFILL_SUMRY.PREFILL_SUMRY_ID as PREFILL_SUMRY_ID, PREFILL_SUMRY.AGMT_ID as AGMT_ID,
		PREFILL_SUMRY.PRCS_ID as PRCS_ID, PREFILL_SUMRY.EDW_STRT_DTTM as EDW_STRT_DTTM,
		PREFILL_SUMRY.EDW_END_DTTM as EDW_END_DTTM, PREFILL_SUMRY.TRANS_STRT_DTTM as TRANS_STRT_DTTM,
		PREFILL_SUMRY.TRANS_END_DTTM as TRANS_END_DTTM, PREFILL_SUMRY.QUOTN_ID as QUOTN_ID,
		PREFILL_SUMRY.INDIV_PRTY_ID as INDIV_PRTY_ID, PREFILL_SUMRY.PREFILL_ADDLDATA_ID as PREFILL_ADDLDATA_ID,
		PREFILL_SUMRY.PREFILL_IDCHK_ID as PREFILL_IDCHK_ID 
FROM	DB_T_PROD_CORE.PREFILL_SUMRY
QUALIFY	ROW_NUMBER() OVER(PARTITION BY  PREFILL_SUMRY.QUOTN_ID,
		PREFILL_SUMRY.INDIV_PRTY_ID,PREFILL_SUMRY.PREFILL_ADDLDATA_ID, PREFILL_SUMRY.PREFILL_IDCHK_ID
ORDER	BY PREFILL_SUMRY.EDW_END_DTTM DESC) = 1
) LKP ON LKP.QUOTN_ID = exp_pass_through.QUOTN_ID AND LKP.INDIV_PRTY_ID = exp_pass_through.INDIV_PRTY_ID AND LKP.PREFILL_ADDLDATA_ID = exp_pass_through.PrefillAddData_alfa AND LKP.PREFILL_IDCHK_ID = exp_pass_through.PrefillIDCheck_alfa
QUALIFY RNK = 1
);


-- Component exp_ins_upd, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_ins_upd AS
(
SELECT
LKP_PREFILL_SUMRY.PREFILL_SUMRY_ID as lkp_PREFILL_SUMRY_ID,
LKP_PREFILL_SUMRY.EDW_STRT_DTTM as lkp_EDW_STRT_DTTM,
LKP_PREFILL_SUMRY.EDW_END_DTTM as lkp_EDW_END_DTTM,
MD5 ( TO_CHAR ( LKP_PREFILL_SUMRY.AGMT_ID ) ) as lkp_checksum,
exp_pass_through.AGMT_ID as AGMT_ID,
exp_pass_through.QUOTN_ID as QUOTN_ID,
exp_pass_through.INDIV_PRTY_ID as INDIV_PRTY_ID,
exp_pass_through.PrefillAddData_alfa as PrefillAddData_alfa,
exp_pass_through.PrefillIDCheck_alfa as PrefillIDCheck_alfa,
exp_pass_through.UpdateTime as UpdateTime,
exp_pass_through.rnk as rnk,
MD5 ( TO_CHAR ( exp_pass_through.AGMT_ID ) ) as in_checksum,
CASE WHEN lkp_checksum IS NULL THEN ''I'' ELSE ( CASE WHEN lkp_checksum <> in_checksum THEN ''U'' ELSE ''R'' END ) END as ins_upd_flag,
:PRCS_ID as PRCS_ID,
CURRENT_TIMESTAMP as EDW_STRT_DTTM,
TO_timestamp ( ''12/31/9999 23:59:59.999999'' , ''MM/DD/YYYY HH24:MI:SS.FF6'' ) as EDW_END_DTTM,
exp_pass_through.source_record_id
FROM
exp_pass_through
INNER JOIN LKP_PREFILL_SUMRY ON exp_pass_through.source_record_id = LKP_PREFILL_SUMRY.source_record_id
);


-- Component rtr_prefill_sumry_INSERT, Type ROUTER Output Group INSERT
CREATE OR REPLACE TEMPORARY TABLE rtr_prefill_sumry_INSERT AS
(SELECT
exp_ins_upd.AGMT_ID as AGMT_ID,
exp_ins_upd.QUOTN_ID as QUOTN_ID,
exp_ins_upd.INDIV_PRTY_ID as INDIV_PRTY_ID,
exp_ins_upd.PrefillAddData_alfa as PrefillAddData_alfa,
exp_ins_upd.PrefillIDCheck_alfa as PrefillIDCheck_alfa,
exp_ins_upd.ins_upd_flag as ins_upd_flag,
exp_ins_upd.PRCS_ID as PRCS_ID,
exp_ins_upd.lkp_EDW_STRT_DTTM as lkp_EDW_STRT_DTTM,
exp_ins_upd.lkp_EDW_END_DTTM as lkp_EDW_END_DTTM,
exp_ins_upd.UpdateTime as UpdateTime,
exp_ins_upd.rnk as rnk,
exp_ins_upd.EDW_STRT_DTTM as EDW_STRT_DTTM,
exp_ins_upd.EDW_END_DTTM as EDW_END_DTTM,
exp_ins_upd.lkp_PREFILL_SUMRY_ID as lkp_PREFILL_SUMRY_ID,
exp_ins_upd.source_record_id
FROM
exp_ins_upd
WHERE ( exp_ins_upd.ins_upd_flag = ''I'' OR exp_ins_upd.ins_upd_flag = ''U'' ) and exp_ins_upd.QUOTN_ID IS NOT NULL and exp_ins_upd.INDIV_PRTY_ID IS NOT NULL and exp_ins_upd.PrefillAddData_alfa IS NOT NULL and exp_ins_upd.PrefillIDCheck_alfa IS NOT NULL);


-- Component upd_PREFILL_SUMRY_ins, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE upd_PREFILL_SUMRY_ins AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
rtr_prefill_sumry_INSERT.AGMT_ID as AGMT_ID1,
rtr_prefill_sumry_INSERT.QUOTN_ID as QUOTN_ID1,
rtr_prefill_sumry_INSERT.INDIV_PRTY_ID as INDIV_PRTY_ID1,
rtr_prefill_sumry_INSERT.PrefillAddData_alfa as PrefillAddData_alfa1,
rtr_prefill_sumry_INSERT.PrefillIDCheck_alfa as PrefillIDCheck_alfa1,
rtr_prefill_sumry_INSERT.PRCS_ID as PRCS_ID1,
rtr_prefill_sumry_INSERT.EDW_STRT_DTTM as EDW_STRT_DTTM1,
rtr_prefill_sumry_INSERT.EDW_END_DTTM as EDW_END_DTTM1,
rtr_prefill_sumry_INSERT.UpdateTime as UPDATETIME1,
rtr_prefill_sumry_INSERT.rnk as rnk1,
rtr_prefill_sumry_INSERT.lkp_PREFILL_SUMRY_ID as lkp_PREFILL_SUMRY_ID1,
0 as UPDATE_STRATEGY_ACTION,
rtr_prefill_sumry_INSERT.source_record_id
FROM
rtr_prefill_sumry_INSERT
);


-- Component exp_pass_to_tgt, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_to_tgt AS
(
SELECT
upd_PREFILL_SUMRY_ins.AGMT_ID1 as AGMT_ID1,
upd_PREFILL_SUMRY_ins.QUOTN_ID1 as QUOTN_ID1,
upd_PREFILL_SUMRY_ins.INDIV_PRTY_ID1 as INDIV_PRTY_ID1,
upd_PREFILL_SUMRY_ins.PrefillAddData_alfa1 as PrefillAddData_alfa1,
upd_PREFILL_SUMRY_ins.PrefillIDCheck_alfa1 as PrefillIDCheck_alfa1,
upd_PREFILL_SUMRY_ins.PRCS_ID1 as PRCS_ID1,
DATEADD(
  SECOND,
  (2 * (upd_PREFILL_SUMRY_ins.rnk1 - 1)),
  CURRENT_TIMESTAMP()
) as var_EDW_STRT_DTTM1,
var_EDW_STRT_DTTM1 as EDW_STRT_DTTM11,
upd_PREFILL_SUMRY_ins.EDW_END_DTTM1 as o_EDW_END_DTTM,
upd_PREFILL_SUMRY_ins.UPDATETIME1 as UPDATETIME1,
to_date ( ''9999-12-31 23:59:59.999999'' , ''YYYY-MM-DD HH24:MI:SS.FF6'' ) as out_TRANS_END_DTTM,
CASE WHEN upd_PREFILL_SUMRY_ins.lkp_PREFILL_SUMRY_ID1 IS NULL THEN row_number() over (order by 1) ELSE upd_PREFILL_SUMRY_ins.lkp_PREFILL_SUMRY_ID1 END as o_PREFILL_SUMRY_ID,
upd_PREFILL_SUMRY_ins.source_record_id
FROM
upd_PREFILL_SUMRY_ins
);


-- Component PREFILL_SUMRY_INS, Type TARGET 
INSERT INTO DB_T_PROD_CORE.PREFILL_SUMRY
(
PREFILL_SUMRY_ID,
QUOTN_ID,
INDIV_PRTY_ID,
PREFILL_ADDLDATA_ID,
PREFILL_IDCHK_ID,
AGMT_ID,
PRCS_ID,
EDW_STRT_DTTM,
EDW_END_DTTM,
TRANS_STRT_DTTM,
TRANS_END_DTTM
)
SELECT
exp_pass_to_tgt.o_PREFILL_SUMRY_ID as PREFILL_SUMRY_ID,
exp_pass_to_tgt.QUOTN_ID1 as QUOTN_ID,
exp_pass_to_tgt.INDIV_PRTY_ID1 as INDIV_PRTY_ID,
exp_pass_to_tgt.PrefillAddData_alfa1 as PREFILL_ADDLDATA_ID,
exp_pass_to_tgt.PrefillIDCheck_alfa1 as PREFILL_IDCHK_ID,
exp_pass_to_tgt.AGMT_ID1 as AGMT_ID,
exp_pass_to_tgt.PRCS_ID1 as PRCS_ID,
exp_pass_to_tgt.EDW_STRT_DTTM11 as EDW_STRT_DTTM,
exp_pass_to_tgt.o_EDW_END_DTTM as EDW_END_DTTM,
exp_pass_to_tgt.UPDATETIME1 as TRANS_STRT_DTTM,
exp_pass_to_tgt.out_TRANS_END_DTTM as TRANS_END_DTTM
FROM
exp_pass_to_tgt;


-- PIPELINE END FOR 1

-- PIPELINE START FOR 2

-- Component SQ_pc_effectivedatedfields1, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_pc_effectivedatedfields1 AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as BranchID,
$2 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT  effdt.BranchID_stg as BranchID from   DB_T_PROD_STAG.pc_effectivedatedfields effdt where  1=2
) SRC
)
);


-- Component exp_pass_to_tgt11, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_to_tgt11 AS
(
SELECT
SQ_pc_effectivedatedfields1.BranchID as AGMT_ID3,
SQ_pc_effectivedatedfields1.source_record_id
FROM
SQ_pc_effectivedatedfields1
);


-- Component PREFILL_SUMRY_UPD, Type TARGET 
INSERT INTO DB_T_PROD_CORE.PREFILL_SUMRY
(
QUOTN_ID
)
SELECT
exp_pass_to_tgt11.AGMT_ID3 as QUOTN_ID
FROM
exp_pass_to_tgt11;


-- PIPELINE END FOR 2
-- Component PREFILL_SUMRY_UPD, Type Post SQL 
UPDATE  DB_T_PROD_CORE.PREFILL_SUMRY  FROM  

(

SELECT	DISTINCT PREFILL_SUMRY_ID,QUOTN_ID,INDIV_PRTY_ID,PREFILL_ADDLDATA_ID,PREFILL_IDCHK_ID,EDW_STRT_DTTM,TRANS_STRT_DTTM,

MAX(EDW_STRT_DTTM) OVER (PARTITION BY QUOTN_ID,INDIV_PRTY_ID,PREFILL_ADDLDATA_ID,PREFILL_IDCHK_ID ORDER BY EDW_STRT_DTTM ASC ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) - INTERVAL ''1 SECOND'' 

 AS LEAD1, 

MAX(TRANS_STRT_DTTM) OVER (PARTITION BY QUOTN_ID,INDIV_PRTY_ID,PREFILL_ADDLDATA_ID,PREFILL_IDCHK_ID ORDER BY EDW_STRT_DTTM ASC ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) - INTERVAL ''1 SECOND'' 

 AS LEAD

FROM DB_T_PROD_CORE.PREFILL_SUMRY 

)  A

SET TRANS_END_DTTM=  A.LEAD, 

EDW_END_DTTM=A.LEAD1

WHERE  PREFILL_SUMRY.EDW_STRT_DTTM = A.EDW_STRT_DTTM

AND PREFILL_SUMRY.TRANS_STRT_DTTM = A.TRANS_STRT_DTTM

AND PREFILL_SUMRY.PREFILL_SUMRY_ID=A.PREFILL_SUMRY_ID

AND PREFILL_SUMRY.QUOTN_ID=A.QUOTN_ID

AND PREFILL_SUMRY.INDIV_PRTY_ID=A.INDIV_PRTY_ID

AND PREFILL_SUMRY.PREFILL_ADDLDATA_ID=A.PREFILL_ADDLDATA_ID

AND PREFILL_SUMRY.PREFILL_IDCHK_ID=A.PREFILL_IDCHK_ID

AND CAST(PREFILL_SUMRY.EDW_END_DTTM AS DATE)=''9999-12-31''

AND CAST(PREFILL_SUMRY.TRANS_END_DTTM AS DATE)=''9999-12-31'' 

AND LEAD1 IS NOT NULL AND LEAD IS NOT NULL;


END; 
';