-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_GW_CLOSEOUT_CTL_DLY("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
 declare

run_id varchar;
	start_dttm timestamp;
	end_dttm timestamp;
    prcs_id int;

BEGIN 
run_id :=   (SELECT run_id   FROM control_run_id where upper(worklet_name) = upper(:worklet_name) order by insert_ts desc limit 1);   
END_DTTM:=   (SELECT left(param_value,19) FROM control_params where run_id = :run_id and upper(param_name)=''END_DTTM'' order by insert_ts desc limit 1);
START_DTTM:=     (SELECT left(param_value,19) FROM control_params where run_id = :run_id and upper(param_name)=''START_DTTM'' order by insert_ts desc limit 1);
PRCS_ID:=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''PRCS_ID'' order by insert_ts desc limit 1);

-- Component SQ_GW_CLOSEOUT_CTL_DLY, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_GW_CLOSEOUT_CTL_DLY AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as ACCOUNTING_YR,
$2 as ACCOUNTING_MO,
$3 as CLOSEOUT_TYPE,
$4 as CLOSEOUT_SEQ_NBR,
$5 as BEGINNING_TS,
$6 as ENDING_TS,
$7 as EOM_DT,
$8 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT GW_CLOSEOUT_CTL_DLY.ACCOUNTING_YR, GW_CLOSEOUT_CTL_DLY.ACCOUNTING_MO, GW_CLOSEOUT_CTL_DLY.CLOSEOUT_TYPE, GW_CLOSEOUT_CTL_DLY.CLOSEOUT_SEQ_NBR, GW_CLOSEOUT_CTL_DLY.BEGINNING_TS, GW_CLOSEOUT_CTL_DLY.ENDING_TS, GW_CLOSEOUT_CTL_DLY.EOM_DT

FROM

 db_t_prod_stag.GW_CLOSEOUT_CTL_DLY
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_GW_CLOSEOUT_CTL_DLY.ACCOUNTING_YR as ACCOUNTING_YR,
SQ_GW_CLOSEOUT_CTL_DLY.ACCOUNTING_MO as ACCOUNTING_MO,
SQ_GW_CLOSEOUT_CTL_DLY.CLOSEOUT_TYPE as CLOSEOUT_TYPE,
SQ_GW_CLOSEOUT_CTL_DLY.CLOSEOUT_SEQ_NBR as CLOSEOUT_SEQ_NBR,
SQ_GW_CLOSEOUT_CTL_DLY.BEGINNING_TS as BEGINNING_TS,
SQ_GW_CLOSEOUT_CTL_DLY.ENDING_TS as ENDING_TS,
SQ_GW_CLOSEOUT_CTL_DLY.EOM_DT as EOM_DT,
:PRCS_ID as PRCS_ID,
SQ_GW_CLOSEOUT_CTL_DLY.source_record_id
FROM
SQ_GW_CLOSEOUT_CTL_DLY
);


-- Component LKP_GW_CLOSEOUT_CTL_DLY_CDC, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_GW_CLOSEOUT_CTL_DLY_CDC AS
(
SELECT
LKP.ACCOUNTING_YR,
LKP.ACCOUNTING_MO,
LKP.CLOSEOUT_TYPE,
LKP.CLOSEOUT_SEQ_NBR,
LKP.BEGINNING_TS,
LKP.ENDING_TS,
LKP.EOM_DT,
LKP.PRCS_ID,
exp_pass_through.ACCOUNTING_YR as in_ACCOUNTING_YR,
exp_pass_through.ACCOUNTING_MO as in_ACCOUNTING_MO,
exp_pass_through.CLOSEOUT_TYPE as in_CLOSEOUT_TYPE,
exp_pass_through.CLOSEOUT_SEQ_NBR as in_CLOSEOUT_SEQ_NBR,
exp_pass_through.BEGINNING_TS as in_BEGINNING_TS,
exp_pass_through.ENDING_TS as in_ENDING_TS,
exp_pass_through.EOM_DT as in_EOM_DT,
exp_pass_through.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pass_through.source_record_id ORDER BY LKP.ACCOUNTING_YR asc,LKP.ACCOUNTING_MO asc,LKP.CLOSEOUT_TYPE asc,LKP.CLOSEOUT_SEQ_NBR asc,LKP.BEGINNING_TS asc,LKP.ENDING_TS asc,LKP.EOM_DT asc,LKP.PRCS_ID asc) RNK
FROM
exp_pass_through
LEFT JOIN (
SELECT
ACCOUNTING_YR,
ACCOUNTING_MO,
CLOSEOUT_TYPE,
CLOSEOUT_SEQ_NBR,
BEGINNING_TS,
ENDING_TS,
EOM_DT,
PRCS_ID
FROM db_t_prod_stag.GW_CLOSEOUT_CTL_DLY
) LKP ON LKP.ACCOUNTING_YR = exp_pass_through.ACCOUNTING_YR AND LKP.ACCOUNTING_MO = exp_pass_through.ACCOUNTING_MO AND LKP.CLOSEOUT_TYPE = exp_pass_through.CLOSEOUT_TYPE AND LKP.CLOSEOUT_SEQ_NBR = exp_pass_through.CLOSEOUT_SEQ_NBR AND LKP.BEGINNING_TS = exp_pass_through.BEGINNING_TS AND LKP.ENDING_TS = exp_pass_through.ENDING_TS AND LKP.EOM_DT = exp_pass_through.EOM_DT
QUALIFY ROW_NUMBER() OVER(PARTITION BY exp_pass_through.source_record_id ORDER BY LKP.ACCOUNTING_YR asc,LKP.ACCOUNTING_MO asc,LKP.CLOSEOUT_TYPE asc,LKP.CLOSEOUT_SEQ_NBR asc,LKP.BEGINNING_TS asc,LKP.ENDING_TS asc,LKP.EOM_DT asc,LKP.PRCS_ID asc)  = 1
);


-- Component EXP_CDC_CHECK, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE EXP_CDC_CHECK AS
(
SELECT
LKP_GW_CLOSEOUT_CTL_DLY_CDC.ACCOUNTING_YR as lkp_ACCOUNTING_YR,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.ACCOUNTING_MO as lkp_ACCOUNTING_MO,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.CLOSEOUT_TYPE as lkp_CLOSEOUT_TYPE,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.CLOSEOUT_SEQ_NBR as lkp_CLOSEOUT_SEQ_NBR,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.BEGINNING_TS as lkp_BEGINNING_TS,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.ENDING_TS as lkp_ENDING_TS,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.EOM_DT as lkp_EOM_DT,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_ACCOUNTING_YR as in_ACCOUNTING_YR,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_ACCOUNTING_MO as in_ACCOUNTING_MO,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_CLOSEOUT_TYPE as in_CLOSEOUT_TYPE,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_CLOSEOUT_SEQ_NBR as in_CLOSEOUT_SEQ_NBR,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_BEGINNING_TS as in_BEGINNING_TS,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_ENDING_TS as in_ENDING_TS,
LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_EOM_DT as in_EOM_DT,
exp_pass_through.PRCS_ID as in_PRCS_ID,
MD5 ( ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_ACCOUNTING_YR ) ) || ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_ACCOUNTING_MO ) ) || ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_CLOSEOUT_TYPE ) ) || ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_CLOSEOUT_SEQ_NBR ) ) || ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_BEGINNING_TS ) ) || ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_ENDING_TS ) ) || ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.in_EOM_DT ) ) ) as v_Src_MD5,
MD5 ( ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.ACCOUNTING_YR ) ) || ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.ACCOUNTING_MO ) ) || ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.CLOSEOUT_TYPE ) ) || ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.CLOSEOUT_SEQ_NBR ) ) || ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.BEGINNING_TS ) ) || ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.ENDING_TS ) ) || ltrim ( rtrim ( LKP_GW_CLOSEOUT_CTL_DLY_CDC.EOM_DT ) ) ) as v_Tgt_MD5,
CASE WHEN v_Tgt_MD5 IS NULL THEN ''I'' ELSE CASE WHEN v_Src_MD5 = v_Tgt_MD5 THEN ''R'' ELSE ''U'' END END as out_Src_Tgt,
exp_pass_through.source_record_id
FROM
exp_pass_through
INNER JOIN LKP_GW_CLOSEOUT_CTL_DLY_CDC ON exp_pass_through.source_record_id = LKP_GW_CLOSEOUT_CTL_DLY_CDC.source_record_id
);


-- Component RTR_INS_INSERT, Type ROUTER Output Group INSERT
create or replace temporary table RTR_INS_INSERT as
SELECT
EXP_CDC_CHECK.lkp_ACCOUNTING_YR as lkp_ACCOUNTING_YR,
EXP_CDC_CHECK.lkp_ACCOUNTING_MO as lkp_ACCOUNTING_MO,
EXP_CDC_CHECK.lkp_CLOSEOUT_TYPE as lkp_CLOSEOUT_TYPE,
EXP_CDC_CHECK.lkp_CLOSEOUT_SEQ_NBR as lkp_CLOSEOUT_SEQ_NBR,
EXP_CDC_CHECK.lkp_BEGINNING_TS as lkp_BEGINING_TS,
EXP_CDC_CHECK.lkp_ENDING_TS as lkp_ENDING_TS,
EXP_CDC_CHECK.lkp_EOM_DT as lkp_EOM_DT,
EXP_CDC_CHECK.in_ACCOUNTING_YR as in_ACCOUNTING_YR,
EXP_CDC_CHECK.in_ACCOUNTING_MO as in_ACCOUNTING_MO,
EXP_CDC_CHECK.in_CLOSEOUT_TYPE as in_CLOSEOUT_TYPE,
EXP_CDC_CHECK.in_CLOSEOUT_SEQ_NBR as in_CLOSEOUT_SEQ_NBR,
EXP_CDC_CHECK.in_BEGINNING_TS as in_BEGINNING_TS,
EXP_CDC_CHECK.in_ENDING_TS as in_ENDING_TS,
EXP_CDC_CHECK.in_EOM_DT as in_EOM_DT,
EXP_CDC_CHECK.in_PRCS_ID as in_PRCS_ID,
EXP_CDC_CHECK.out_Src_Tgt as out_Src_Tgt,
EXP_CDC_CHECK.source_record_id
FROM
EXP_CDC_CHECK
WHERE EXP_CDC_CHECK.out_Src_Tgt = ''I'' AND EXP_CDC_CHECK.in_ACCOUNTING_YR IS NOT NULL AND EXP_CDC_CHECK.in_ACCOUNTING_MO IS NOT NULL AND EXP_CDC_CHECK.in_CLOSEOUT_TYPE IS NOT NULL;


-- Component UPD_Ins, Type UPDATE 
CREATE OR REPLACE TEMPORARY TABLE UPD_Ins AS
(
/* UPDATE_STRATEGY_ACTION = 0 FOR INSERT / UPDATE_STRATEGY_ACTION = 1 FOR UPDATE / UPDATE_STRATEGY_ACTION = 2 FOR DELETE / UPDATE_STRATEGY_ACTION = 3 FOR REJECT */
SELECT
RTR_INS_INSERT.in_ACCOUNTING_YR as in_ACCOUNTING_YR1,
RTR_INS_INSERT.in_ACCOUNTING_MO as in_ACCOUNTING_MO1,
RTR_INS_INSERT.in_CLOSEOUT_TYPE as in_CLOSEOUT_TYPE1,
RTR_INS_INSERT.in_CLOSEOUT_SEQ_NBR as in_CLOSEOUT_SEQ_NBR1,
RTR_INS_INSERT.in_BEGINNING_TS as in_BEGINNING_TS1,
RTR_INS_INSERT.in_ENDING_TS as in_ENDING_TS1,
RTR_INS_INSERT.in_EOM_DT as in_EOM_DT1,
RTR_INS_INSERT.in_PRCS_ID as in_PRCS_ID1,
0 as UPDATE_STRATEGY_ACTION
FROM
RTR_INS_INSERT
);


-- Component GW_CLOSEOUT_CTL_DLY_1, Type TARGET 
INSERT INTO db_t_prod_comn.GW_CLOSEOUT_CTL_DLY
(
ACCOUNTING_YR,
ACCOUNTING_MO,
CLOSEOUT_TYPE,
CLOSEOUT_SEQ_NBR,
BEGINNING_TS,
ENDING_TS,
EOM_DT,
PRCS_ID
)
SELECT
UPD_Ins.in_ACCOUNTING_YR1 as ACCOUNTING_YR,
UPD_Ins.in_ACCOUNTING_MO1 as ACCOUNTING_MO,
UPD_Ins.in_CLOSEOUT_TYPE1 as CLOSEOUT_TYPE,
UPD_Ins.in_CLOSEOUT_SEQ_NBR1 as CLOSEOUT_SEQ_NBR,
UPD_Ins.in_BEGINNING_TS1 as BEGINNING_TS,
UPD_Ins.in_ENDING_TS1 as ENDING_TS,
UPD_Ins.in_EOM_DT1 as EOM_DT,
UPD_Ins.in_PRCS_ID1 as PRCS_ID
FROM
UPD_Ins;


END;
';