-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_GW_PREM_TRANS_GL_INFO("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
 DECLARE
  PRCS_ID int;
  run_id STRING;

BEGIN
run_id :=   (SELECT run_id   FROM control_run_id where upper(worklet_name) = upper(:worklet_name) order by insert_ts desc limit 1);   
PRCS_ID:=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''PRCS_ID'' order by insert_ts desc limit 1);


-- Component SQ_GW_PREMIUM_TRANS, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE SQ_GW_PREMIUM_TRANS AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as BATCH_SEQ_NBR,
$2 as TRANS_SEQ_NBR,
$3 as ACCOUNTING_MO,
$4 as ACCOUNTING_YR,
$5 as ACCOUNTING_DT,
$6 as POLICY_NBR,
$7 as RISK_STATE_CD,
$8 as POLICY_TERM_NBR,
$9 as POLICY_MODEL_NBR,
$10 as TRANS_TYPE_CD,
$11 as TRANS_PUBLIC_ID,
$12 as COV_TYPE_CD,
$13 as TRANS_EFF_DT,
$14 as TRANS_EXP_DT,
$15 as PREMIUM_TRANS_AMT,
$16 as BUS_ACT_TRNS_OBJ,
$17 as BUS_ACT_TRNS_ACT,
$18 as UNIT_REFERENCE_NBR,
$19 as UNIT_TYPE_CD,
$20 as UNIT_TYPE_NM,
$21 as TRNS_EARN_PREM_AMT,
$22 as TRNS_UNEARN_PREM_AMT,
$23 as GL_EXTR_MO,
$24 as GL_EXTR_YR,
$25 as GL_PREM_TYPE,
$26 as PS_ACCOUNTING_MO,
$27 as PS_ACCOUNTING_YR,
$28 as LEDGER,
$29 as JOURNAL_ID,
$30 as JOURNAL_LINE,
$31 as JOURNAL_DATE,
$32 as GL_ACCOUNT_NBR,
$33 as DEPTID,
$34 as PRODUCT,
$35 as PS_COMPANY_CD,
$36 as PS_STATE,
$37 as PS_POOL_CD,
$38 as GL_RECORD_TAG,
$39 as MASTER_CMPY_NBR,
$40 as BRANCH_NBR,
$41 as STATE_CD,
$42 as COV_CD,
$43 as INSURANCE_LINE_CD,
$44 as TRANS_SOURCE_CD,
$45 as REINSURANCE_CD,
$46 as GL_DISTRIB_STATUS,
$47 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT	GW_PREMIUM_TRANS.BATCH_SEQ_NBR, GW_PREMIUM_TRANS.TRANS_SEQ_NBR,

		GW_PREMIUM_TRANS.ACCOUNTING_MO, GW_PREMIUM_TRANS.ACCOUNTING_YR,

		GW_PREMIUM_TRANS.ACCOUNTING_DT, GW_PREMIUM_TRANS.POLICY_NBR,

		GW_PREMIUM_TRANS.RISK_STATE_CD, GW_PREMIUM_TRANS.POLICY_TERM_NBR,

		GW_PREMIUM_TRANS.POLICY_MODEL_NBR, GW_PREMIUM_TRANS.TRANS_TYPE_CD,

		GW_PREMIUM_TRANS.TRANS_PUBLIC_ID, GW_PREMIUM_TRANS.COV_TYPE_CD,

		GW_PREMIUM_TRANS.TRANS_EFF_DT, GW_PREMIUM_TRANS.TRANS_EXP_DT,

		GW_PREMIUM_TRANS.PREMIUM_TRANS_AMT, GW_PREMIUM_TRANS.BUS_ACT_TRNS_OBJ,

		GW_PREMIUM_TRANS.BUS_ACT_TRNS_ACT,

		GW_PREMIUM_TRANS.UNIT_REFERENCE_NBR, 

		GW_PREMIUM_TRANS.UNIT_TYPE_CD, GW_PREMIUM_TRANS.UNIT_TYPE_NM,

		GW_PREMIUM_TRANS.TRNS_EARN_PREM_AMT,

		GW_PREMIUM_TRANS.TRNS_UNEARN_PREM_AMT, GW_PREMIUM_TRANS.GL_EXTR_MO,

		GW_PREMIUM_TRANS.GL_EXTR_YR, GW_PREMIUM_TRANS.GL_PREM_TYPE,    GW_PREMIUM_TRANS.PS_ACCOUNTING_MO,

		GW_PREMIUM_TRANS.PS_ACCOUNTING_YR, GW_PREMIUM_TRANS.LEDGER, GW_PREMIUM_TRANS.JOURNAL_ID,

		GW_PREMIUM_TRANS.JOURNAL_LINE, GW_PREMIUM_TRANS.JOURNAL_DATE,

		GW_PREMIUM_TRANS.GL_ACCOUNT_NBR, GW_PREMIUM_TRANS.DEPTID, GW_PREMIUM_TRANS.PRODUCT,

		GW_PREMIUM_TRANS.PS_COMPANY_CD, GW_PREMIUM_TRANS.PS_STATE, GW_PREMIUM_TRANS.PS_POOL_CD,

		GW_PREMIUM_TRANS.GL_RECORD_TAG, GW_PREMIUM_TRANS.MASTER_CMPY_NBR,

		GW_PREMIUM_TRANS.BRANCH_NBR, GW_PREMIUM_TRANS.STATE_CD, GW_PREMIUM_TRANS.COV_CD,

		GW_PREMIUM_TRANS.INSURANCE_LINE_CD, GW_PREMIUM_TRANS.TRANS_SOURCE_CD,

		GW_PREMIUM_TRANS.REINSURANCE_CD ,GW_PREMIUM_TRANS.GL_DISTRIB_STATUS

FROM	

 db_t_prod_stag.GW_PREMIUM_TRANS

where	trim(BATCH_TYPE)=''GL ROW''
) SRC
)
);


-- Component exp_pass_through, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_pass_through AS
(
SELECT
SQ_GW_PREMIUM_TRANS.BATCH_SEQ_NBR as BATCH_SEQ_NBR,
SQ_GW_PREMIUM_TRANS.TRANS_SEQ_NBR as TRANS_SEQ_NBR,
SQ_GW_PREMIUM_TRANS.GL_EXTR_MO as GL_EXTR_MO,
SQ_GW_PREMIUM_TRANS.GL_EXTR_YR as GL_EXTR_YR,
SQ_GW_PREMIUM_TRANS.ACCOUNTING_DT as ACCOUNTING_DT,
SQ_GW_PREMIUM_TRANS.BUS_ACT_TRNS_ACT as BUS_ACT_TRNS_ACT,
SQ_GW_PREMIUM_TRANS.GL_PREM_TYPE as GL_PREM_TYPE,
SQ_GW_PREMIUM_TRANS.PS_ACCOUNTING_MO as PS_ACCOUNTING_MO,
SQ_GW_PREMIUM_TRANS.PS_ACCOUNTING_YR as PS_ACCOUNTING_YR,
SQ_GW_PREMIUM_TRANS.PS_COMPANY_CD as PS_COMPANY_CD,
SQ_GW_PREMIUM_TRANS.PS_STATE as PS_STATE,
SQ_GW_PREMIUM_TRANS.PS_POOL_CD as PS_POOL_CD,
SQ_GW_PREMIUM_TRANS.LEDGER as LEDGER,
SQ_GW_PREMIUM_TRANS.JOURNAL_ID as JOURNAL_ID,
SQ_GW_PREMIUM_TRANS.JOURNAL_LINE as JOURNAL_LINE,
SQ_GW_PREMIUM_TRANS.JOURNAL_DATE as JOURNAL_DATE,
SQ_GW_PREMIUM_TRANS.GL_ACCOUNT_NBR as GL_ACCOUNT_NBR,
SQ_GW_PREMIUM_TRANS.DEPTID as DEPTID,
SQ_GW_PREMIUM_TRANS.PRODUCT as PRODUCT,
SQ_GW_PREMIUM_TRANS.GL_RECORD_TAG as GL_RECORD_TAG,
SQ_GW_PREMIUM_TRANS.MASTER_CMPY_NBR as MASTER_CMPY_NBR,
SQ_GW_PREMIUM_TRANS.BRANCH_NBR as BRANCH_NBR,
SQ_GW_PREMIUM_TRANS.STATE_CD as STATE_CD,
SQ_GW_PREMIUM_TRANS.COV_CD as COV_CD,
SQ_GW_PREMIUM_TRANS.INSURANCE_LINE_CD as INSURANCE_LINE_CD,
SQ_GW_PREMIUM_TRANS.PREMIUM_TRANS_AMT as PREMIUM_TRANS_AMT,
SQ_GW_PREMIUM_TRANS.TRNS_EARN_PREM_AMT as TRNS_EARN_PREM_AMT,
SQ_GW_PREMIUM_TRANS.TRNS_UNEARN_PREM_AMT as TRNS_UNEARN_PREM_AMT,
SQ_GW_PREMIUM_TRANS.TRANS_SOURCE_CD as TRANS_SOURCE_CD,
SQ_GW_PREMIUM_TRANS.TRANS_PUBLIC_ID as TRANS_PUBLIC_ID,
SQ_GW_PREMIUM_TRANS.TRANS_EFF_DT as TRANS_EFF_DT,
SQ_GW_PREMIUM_TRANS.TRANS_EXP_DT as TRANS_EXP_DT,
SQ_GW_PREMIUM_TRANS.TRANS_TYPE_CD as TRANS_TYPE_CD,
SQ_GW_PREMIUM_TRANS.COV_TYPE_CD as COV_TYPE_CD,
SQ_GW_PREMIUM_TRANS.REINSURANCE_CD as REINSURANCE_CD,
SQ_GW_PREMIUM_TRANS.GL_DISTRIB_STATUS as GL_DISTRIB_STATUS,
SQ_GW_PREMIUM_TRANS.POLICY_NBR as POLICY_NBR,
SQ_GW_PREMIUM_TRANS.POLICY_TERM_NBR as POLICY_TERM_NBR,
SQ_GW_PREMIUM_TRANS.POLICY_MODEL_NBR as POLICY_MODEL_NBR,
SQ_GW_PREMIUM_TRANS.ACCOUNTING_MO as ACCOUNTING_MO,
SQ_GW_PREMIUM_TRANS.ACCOUNTING_YR as ACCOUNTING_YR,
SQ_GW_PREMIUM_TRANS.BUS_ACT_TRNS_OBJ as BUS_ACT_TRNS_OBJ,
SQ_GW_PREMIUM_TRANS.RISK_STATE_CD as RISK_STATE_CD,
SQ_GW_PREMIUM_TRANS.UNIT_REFERENCE_NBR as UNIT_REFERENCE_NBR,
SQ_GW_PREMIUM_TRANS.UNIT_TYPE_CD as UNIT_TYPE_CD,
SQ_GW_PREMIUM_TRANS.UNIT_TYPE_NM as UNIT_TYPE_NM,
SQ_GW_PREMIUM_TRANS.source_record_id
FROM
SQ_GW_PREMIUM_TRANS
);


-- Component LKP_GL_PREM_TRANS_PLCY_INFO, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_GL_PREM_TRANS_PLCY_INFO AS
(
SELECT
LKP.PLCY_INFO_ID,
exp_pass_through.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp_pass_through.source_record_id ORDER BY LKP.PLCY_INFO_ID asc,LKP.PLCY_NUM asc,LKP.PLCY_TERM_NUM asc,LKP.PLCY_MODL_NUM asc,LKP.PLCY_EFF_DT asc,LKP.PLCY_EXPN_DT asc,LKP.SRVC_CTR asc,LKP.PRCS_ID asc,LKP.SRC_SYS_CD asc,LKP.EDW_STRT_DTTM asc,LKP.EDW_END_DTTM asc) RNK
FROM
exp_pass_through
LEFT JOIN (
SELECT
PLCY_INFO_ID,
PLCY_NUM,
PLCY_TERM_NUM,
PLCY_MODL_NUM,
PLCY_EFF_DT,
PLCY_EXPN_DT,
SRVC_CTR,
PRCS_ID,
SRC_SYS_CD,
EDW_STRT_DTTM,
EDW_END_DTTM
FROM db_t_prod_comn.GW_PREM_TRANS_PLCY_INFO
) LKP ON LKP.PLCY_NUM = exp_pass_through.POLICY_NBR AND LKP.PLCY_TERM_NUM = exp_pass_through.POLICY_TERM_NBR AND LKP.PLCY_MODL_NUM = exp_pass_through.POLICY_MODEL_NBR
QUALIFY ROW_NUMBER() OVER(PARTITION BY exp_pass_through.source_record_id ORDER BY LKP.PLCY_INFO_ID asc,LKP.PLCY_NUM asc,LKP.PLCY_TERM_NUM asc,LKP.PLCY_MODL_NUM asc,LKP.PLCY_EFF_DT asc,LKP.PLCY_EXPN_DT asc,LKP.SRVC_CTR asc,LKP.PRCS_ID asc,LKP.SRC_SYS_CD asc,LKP.EDW_STRT_DTTM asc,LKP.EDW_END_DTTM asc) = 1
);


-- Component exp, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp AS
(
SELECT
LKP_GL_PREM_TRANS_PLCY_INFO.PLCY_INFO_ID as PLCY_INFO_ID,
exp_pass_through.BATCH_SEQ_NBR as BATCH_SEQ_NBR,
exp_pass_through.TRANS_SEQ_NBR as TRANS_SEQ_NBR,
exp_pass_through.GL_EXTR_MO as GL_EXTR_MO,
exp_pass_through.GL_EXTR_YR as GL_EXTR_YR,
exp_pass_through.ACCOUNTING_DT as ACCOUNTING_DT,
exp_pass_through.BUS_ACT_TRNS_ACT as BUS_ACT_TRNS_ACT,
exp_pass_through.GL_PREM_TYPE as GL_PREM_TYPE,
exp_pass_through.PS_ACCOUNTING_MO as PS_ACCOUNTING_MO,
exp_pass_through.PS_ACCOUNTING_YR as PS_ACCOUNTING_YR,
exp_pass_through.PS_COMPANY_CD as PS_COMPANY_CD,
exp_pass_through.PS_STATE as PS_STATE,
exp_pass_through.PS_POOL_CD as PS_POOL_CD,
exp_pass_through.LEDGER as LEDGER,
exp_pass_through.JOURNAL_ID as JOURNAL_ID,
exp_pass_through.JOURNAL_LINE as JOURNAL_LINE,
exp_pass_through.JOURNAL_DATE as JOURNAL_DATE,
exp_pass_through.GL_ACCOUNT_NBR as GL_ACCOUNT_NBR,
exp_pass_through.DEPTID as DEPTID,
exp_pass_through.PRODUCT as PRODUCT,
exp_pass_through.GL_RECORD_TAG as GL_RECORD_TAG,
exp_pass_through.MASTER_CMPY_NBR as MASTER_CMPY_NBR,
exp_pass_through.BRANCH_NBR as BRANCH_NBR,
exp_pass_through.STATE_CD as STATE_CD,
exp_pass_through.COV_CD as COV_CD,
exp_pass_through.INSURANCE_LINE_CD as INSURANCE_LINE_CD,
exp_pass_through.PREMIUM_TRANS_AMT as PREMIUM_TRANS_AMT,
exp_pass_through.TRNS_EARN_PREM_AMT as TRNS_EARN_PREM_AMT,
exp_pass_through.TRNS_UNEARN_PREM_AMT as TRNS_UNEARN_PREM_AMT,
exp_pass_through.TRANS_SOURCE_CD as TRANS_SOURCE_CD,
exp_pass_through.TRANS_PUBLIC_ID as TRANS_PUBLIC_ID,
exp_pass_through.TRANS_EFF_DT as TRANS_EFF_DT,
exp_pass_through.TRANS_EXP_DT as TRANS_EXP_DT,
exp_pass_through.TRANS_TYPE_CD as TRANS_TYPE_CD,
exp_pass_through.COV_TYPE_CD as COV_TYPE_CD,
exp_pass_through.REINSURANCE_CD as REINSURANCE_CD,
exp_pass_through.GL_DISTRIB_STATUS as GL_DISTRIB_STATUS,
exp_pass_through.ACCOUNTING_MO as ACCOUNTING_MO,
exp_pass_through.ACCOUNTING_YR as ACCOUNTING_YR,
exp_pass_through.BUS_ACT_TRNS_OBJ as BUS_ACT_TRNS_OBJ,
exp_pass_through.RISK_STATE_CD as RISK_STATE_CD,
exp_pass_through.UNIT_REFERENCE_NBR as UNIT_REFERENCE_NBR,
exp_pass_through.UNIT_TYPE_CD as UNIT_TYPE_CD,
exp_pass_through.UNIT_TYPE_NM as UNIT_TYPE_NM,
:PRCS_ID as PRCS_ID,
''DB2'' as SRC_SYS_CD,
CURRENT_TIMESTAMP as Start_ts,
to_timestamp_ntz ( ''12/31/9999 23:59:59.999999'' , ''MM/DD/YYYY HH24:MI:SS.FF6'' ) as end_ts,
exp_pass_through.source_record_id
FROM
exp_pass_through
INNER JOIN LKP_GL_PREM_TRANS_PLCY_INFO ON exp_pass_through.source_record_id = LKP_GL_PREM_TRANS_PLCY_INFO.source_record_id
);


-- Component LKP_TGT, Type LOOKUP 
CREATE OR REPLACE TEMPORARY TABLE LKP_TGT AS
(
SELECT
LKP.PLCY_INFO_ID,
LKP.GL_EXTC_YR,
LKP.GL_EXTC_MTH,
exp.source_record_id,
ROW_NUMBER() OVER(PARTITION BY exp.source_record_id ORDER BY LKP.PLCY_INFO_ID asc,LKP.GL_EXTC_YR asc,LKP.GL_EXTC_MTH asc) RNK
FROM
exp
LEFT JOIN (
SELECT
PLCY_INFO_ID,
GL_EXTC_YR,
GL_EXTC_MTH
FROM db_t_prod_comn.GW_PREM_TRANS_GL_INFO
) LKP ON LKP.PLCY_INFO_ID = exp.PLCY_INFO_ID AND LKP.GL_EXTC_MTH = exp.GL_EXTR_MO AND LKP.GL_EXTC_YR = exp.GL_EXTR_YR
QUALIFY ROW_NUMBER() OVER(PARTITION BY exp.source_record_id ORDER BY LKP.PLCY_INFO_ID asc,LKP.GL_EXTC_YR asc,LKP.GL_EXTC_MTH asc)  = 1
);


-- Component exp_check_flag, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_check_flag AS
(
SELECT
exp.PLCY_INFO_ID as PLCY_INFO_ID,
exp.BATCH_SEQ_NBR as BATCH_SEQ_NBR,
exp.TRANS_SEQ_NBR as TRANS_SEQ_NBR,
exp.GL_EXTR_MO as GL_EXTR_MO,
exp.GL_EXTR_YR as GL_EXTR_YR,
exp.ACCOUNTING_DT as ACCOUNTING_DT,
exp.BUS_ACT_TRNS_ACT as BUS_ACT_TRNS_ACT,
exp.GL_PREM_TYPE as GL_PREM_TYPE,
exp.PS_ACCOUNTING_MO as PS_ACCOUNTING_MO,
exp.PS_ACCOUNTING_YR as PS_ACCOUNTING_YR,
exp.PS_COMPANY_CD as PS_COMPANY_CD,
exp.PS_STATE as PS_STATE,
exp.PS_POOL_CD as PS_POOL_CD,
exp.LEDGER as LEDGER,
exp.JOURNAL_ID as JOURNAL_ID,
exp.JOURNAL_LINE as JOURNAL_LINE,
exp.JOURNAL_DATE as JOURNAL_DATE,
exp.GL_ACCOUNT_NBR as GL_ACCOUNT_NBR,
exp.DEPTID as DEPTID,
exp.PRODUCT as PRODUCT,
exp.GL_RECORD_TAG as GL_RECORD_TAG,
exp.MASTER_CMPY_NBR as MASTER_CMPY_NBR,
exp.BRANCH_NBR as BRANCH_NBR,
exp.STATE_CD as STATE_CD,
exp.COV_CD as COV_CD,
exp.INSURANCE_LINE_CD as INSURANCE_LINE_CD,
exp.PREMIUM_TRANS_AMT as PREMIUM_TRANS_AMT,
exp.TRNS_EARN_PREM_AMT as TRNS_EARN_PREM_AMT,
exp.TRNS_UNEARN_PREM_AMT as TRNS_UNEARN_PREM_AMT,
exp.TRANS_SOURCE_CD as TRANS_SOURCE_CD,
exp.TRANS_PUBLIC_ID as TRANS_PUBLIC_ID,
exp.TRANS_EFF_DT as TRANS_EFF_DT,
exp.TRANS_EXP_DT as TRANS_EXP_DT,
exp.TRANS_TYPE_CD as TRANS_TYPE_CD,
exp.COV_TYPE_CD as COV_TYPE_CD,
exp.REINSURANCE_CD as REINSURANCE_CD,
exp.GL_DISTRIB_STATUS as GL_DISTRIB_STATUS,
exp.ACCOUNTING_MO as ACCOUNTING_MO,
exp.ACCOUNTING_YR as ACCOUNTING_YR,
exp.BUS_ACT_TRNS_OBJ as BUS_ACT_TRNS_OBJ,
exp.RISK_STATE_CD as RISK_STATE_CD,
exp.UNIT_REFERENCE_NBR as UNIT_REFERENCE_NBR,
exp.UNIT_TYPE_CD as UNIT_TYPE_CD,
exp.UNIT_TYPE_NM as UNIT_TYPE_NM,
exp.PRCS_ID as PRCS_ID,
exp.SRC_SYS_CD as SRC_SYS_CD,
exp.Start_ts as Start_ts,
exp.end_ts as end_ts,
CASE WHEN LKP_TGT.PLCY_INFO_ID IS NULL AND LKP_TGT.GL_EXTC_YR IS NULL AND LKP_TGT.GL_EXTC_MTH IS NULL THEN 1 ELSE 0 END as v_flag,
v_flag as o_flag,
exp.source_record_id
FROM
exp
INNER JOIN LKP_TGT ON exp.source_record_id = LKP_TGT.source_record_id
);


-- Component fil_pass_ins_flag, Type FILTER 
CREATE OR REPLACE TEMPORARY TABLE fil_pass_ins_flag AS
(
SELECT
exp_check_flag.PLCY_INFO_ID as PLCY_INFO_ID,
exp_check_flag.BATCH_SEQ_NBR as BATCH_SEQ_NBR,
exp_check_flag.TRANS_SEQ_NBR as TRANS_SEQ_NBR,
exp_check_flag.GL_EXTR_MO as GL_EXTR_MO,
exp_check_flag.GL_EXTR_YR as GL_EXTR_YR,
exp_check_flag.ACCOUNTING_DT as ACCOUNTING_DT,
exp_check_flag.BUS_ACT_TRNS_ACT as BUS_ACT_TRNS_ACT,
exp_check_flag.GL_PREM_TYPE as GL_PREM_TYPE,
exp_check_flag.PS_ACCOUNTING_MO as PS_ACCOUNTING_MO,
exp_check_flag.PS_ACCOUNTING_YR as PS_ACCOUNTING_YR,
exp_check_flag.PS_COMPANY_CD as PS_COMPANY_CD,
exp_check_flag.PS_STATE as PS_STATE,
exp_check_flag.PS_POOL_CD as PS_POOL_CD,
exp_check_flag.LEDGER as LEDGER,
exp_check_flag.JOURNAL_ID as JOURNAL_ID,
exp_check_flag.JOURNAL_LINE as JOURNAL_LINE,
exp_check_flag.JOURNAL_DATE as JOURNAL_DATE,
exp_check_flag.GL_ACCOUNT_NBR as GL_ACCOUNT_NBR,
exp_check_flag.DEPTID as DEPTID,
exp_check_flag.PRODUCT as PRODUCT,
exp_check_flag.GL_RECORD_TAG as GL_RECORD_TAG,
exp_check_flag.MASTER_CMPY_NBR as MASTER_CMPY_NBR,
exp_check_flag.BRANCH_NBR as BRANCH_NBR,
exp_check_flag.STATE_CD as STATE_CD,
exp_check_flag.COV_CD as COV_CD,
exp_check_flag.INSURANCE_LINE_CD as INSURANCE_LINE_CD,
exp_check_flag.PREMIUM_TRANS_AMT as PREMIUM_TRANS_AMT,
exp_check_flag.TRNS_EARN_PREM_AMT as TRNS_EARN_PREM_AMT,
exp_check_flag.TRNS_UNEARN_PREM_AMT as TRNS_UNEARN_PREM_AMT,
exp_check_flag.TRANS_SOURCE_CD as TRANS_SOURCE_CD,
exp_check_flag.TRANS_PUBLIC_ID as TRANS_PUBLIC_ID,
exp_check_flag.TRANS_EFF_DT as TRANS_EFF_DT,
exp_check_flag.TRANS_EXP_DT as TRANS_EXP_DT,
exp_check_flag.TRANS_TYPE_CD as TRANS_TYPE_CD,
exp_check_flag.COV_TYPE_CD as COV_TYPE_CD,
exp_check_flag.REINSURANCE_CD as REINSURANCE_CD,
exp_check_flag.GL_DISTRIB_STATUS as GL_DISTRIB_STATUS,
exp_check_flag.ACCOUNTING_MO as ACCOUNTING_MO,
exp_check_flag.ACCOUNTING_YR as ACCOUNTING_YR,
exp_check_flag.BUS_ACT_TRNS_OBJ as BUS_ACT_TRNS_OBJ,
exp_check_flag.RISK_STATE_CD as RISK_STATE_CD,
exp_check_flag.UNIT_REFERENCE_NBR as UNIT_REFERENCE_NBR,
exp_check_flag.UNIT_TYPE_CD as UNIT_TYPE_CD,
exp_check_flag.UNIT_TYPE_NM as UNIT_TYPE_NM,
exp_check_flag.PRCS_ID as PRCS_ID,
exp_check_flag.SRC_SYS_CD as SRC_SYS_CD,
exp_check_flag.Start_ts as Start_ts,
exp_check_flag.end_ts as end_ts,
exp_check_flag.o_flag as o_flag,
exp_check_flag.source_record_id
FROM
exp_check_flag
WHERE exp_check_flag.o_flag = 1
);


-- Component GW_PREM_TRANS_GL_INFO, Type TARGET 
INSERT INTO db_t_prod_comn.GW_PREM_TRANS_GL_INFO
(
PLCY_INFO_ID,
BATCH_SEQ_NUM,
TRANS_SEQ_NUM,
GL_EXTC_YR,
GL_EXTC_MTH,
ACCTG_YR,
ACCTG_MTH,
ACCTG_DT,
BUS_ACT_TRNS_OBJ,
BUS_ACT_TRNS_ACT,
RISK_STATE_CD,
GL_PREM_TYPE,
PS_ACCNTG_MTH,
PS_ACCNTG_YR,
PS_CO_CD,
PS_ST,
PS_POOL_CD,
LEDGR,
JRNL_ID,
JRNL_LN,
JRNL_DT,
PROD,
GL_RCORD_TAG,
MSTR_CO_NUM,
BRNCH_NUM,
ST_CD,
CVGE_CD,
INSRNC_LN_CD,
UNIT_REF_NUM,
UNIT_TYPE_CD,
UNIT_TYPE_NAME,
TRANS_PREM_AMT,
TRANS_EARND_PREM,
TRANS_UNEARND_PREM,
TRANS_SRC_CD,
TRANS_PUBLC_ID,
TRANS_EFF_DT,
TRANS_EXPN_DT,
TRANS_TYPE_CD,
CVGE_TYPE_CD,
RINSRNC_CD,
GL_DSTRBD_STS,
PRCS_ID,
GL_ACCOUNT_NBR,
DEPTID,
SRC_SYS_CD,
EDW_STRT_DTTM,
EDW_END_DTTM
)
SELECT
fil_pass_ins_flag.PLCY_INFO_ID as PLCY_INFO_ID,
fil_pass_ins_flag.BATCH_SEQ_NBR as BATCH_SEQ_NUM,
fil_pass_ins_flag.TRANS_SEQ_NBR as TRANS_SEQ_NUM,
fil_pass_ins_flag.GL_EXTR_YR as GL_EXTC_YR,
fil_pass_ins_flag.GL_EXTR_MO as GL_EXTC_MTH,
fil_pass_ins_flag.ACCOUNTING_YR as ACCTG_YR,
fil_pass_ins_flag.ACCOUNTING_MO as ACCTG_MTH,
fil_pass_ins_flag.ACCOUNTING_DT as ACCTG_DT,
fil_pass_ins_flag.BUS_ACT_TRNS_OBJ as BUS_ACT_TRNS_OBJ,
fil_pass_ins_flag.BUS_ACT_TRNS_ACT as BUS_ACT_TRNS_ACT,
fil_pass_ins_flag.RISK_STATE_CD as RISK_STATE_CD,
fil_pass_ins_flag.GL_PREM_TYPE as GL_PREM_TYPE,
fil_pass_ins_flag.PS_ACCOUNTING_MO as PS_ACCNTG_MTH,
fil_pass_ins_flag.PS_ACCOUNTING_YR as PS_ACCNTG_YR,
fil_pass_ins_flag.PS_COMPANY_CD as PS_CO_CD,
fil_pass_ins_flag.PS_STATE as PS_ST,
fil_pass_ins_flag.PS_POOL_CD as PS_POOL_CD,
fil_pass_ins_flag.LEDGER as LEDGR,
fil_pass_ins_flag.JOURNAL_ID as JRNL_ID,
fil_pass_ins_flag.JOURNAL_LINE as JRNL_LN,
fil_pass_ins_flag.JOURNAL_DATE as JRNL_DT,
fil_pass_ins_flag.PRODUCT as PROD,
fil_pass_ins_flag.GL_RECORD_TAG as GL_RCORD_TAG,
fil_pass_ins_flag.MASTER_CMPY_NBR as MSTR_CO_NUM,
fil_pass_ins_flag.BRANCH_NBR as BRNCH_NUM,
fil_pass_ins_flag.STATE_CD as ST_CD,
fil_pass_ins_flag.COV_CD as CVGE_CD,
fil_pass_ins_flag.INSURANCE_LINE_CD as INSRNC_LN_CD,
fil_pass_ins_flag.UNIT_REFERENCE_NBR as UNIT_REF_NUM,
fil_pass_ins_flag.UNIT_TYPE_CD as UNIT_TYPE_CD,
fil_pass_ins_flag.UNIT_TYPE_NM as UNIT_TYPE_NAME,
fil_pass_ins_flag.PREMIUM_TRANS_AMT as TRANS_PREM_AMT,
fil_pass_ins_flag.TRNS_EARN_PREM_AMT as TRANS_EARND_PREM,
fil_pass_ins_flag.TRNS_UNEARN_PREM_AMT as TRANS_UNEARND_PREM,
fil_pass_ins_flag.TRANS_SOURCE_CD as TRANS_SRC_CD,
fil_pass_ins_flag.TRANS_PUBLIC_ID as TRANS_PUBLC_ID,
fil_pass_ins_flag.TRANS_EFF_DT as TRANS_EFF_DT,
fil_pass_ins_flag.TRANS_EXP_DT as TRANS_EXPN_DT,
fil_pass_ins_flag.TRANS_TYPE_CD as TRANS_TYPE_CD,
fil_pass_ins_flag.COV_TYPE_CD as CVGE_TYPE_CD,
fil_pass_ins_flag.REINSURANCE_CD as RINSRNC_CD,
fil_pass_ins_flag.GL_DISTRIB_STATUS as GL_DSTRBD_STS,
fil_pass_ins_flag.PRCS_ID as PRCS_ID,
fil_pass_ins_flag.GL_ACCOUNT_NBR as GL_ACCOUNT_NBR,
fil_pass_ins_flag.DEPTID as DEPTID,
fil_pass_ins_flag.SRC_SYS_CD as SRC_SYS_CD,
fil_pass_ins_flag.Start_ts as EDW_STRT_DTTM,
fil_pass_ins_flag.end_ts as EDW_END_DTTM
FROM
fil_pass_ins_flag;


END; 
';