-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BIBASE_D_PRODUCER_HIERY("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE
  
run_id varchar;
	start_dttm timestamp;
	end_dttm timestamp;
    prcs_id int;


BEGIN 
 run_id :=   (SELECT run_id   FROM control_run_id where worklet_name=:worklet_name order by insert_ts desc limit 1);   
 END_DTTM:=   (SELECT left(param_value,19) FROM control_params where run_id = :run_id and upper(param_name)=''END_DTTM'' limit 1);
 START_DTTM:=     (SELECT left(param_value,19) FROM control_params where run_id = :run_id and upper(param_name)=''START_DTTM'' limit 1);
 PRCS_ID:=     (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''PRCS_ID'' limit 1); 

-- Component sq_WR_AGNT_HIERY, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_WR_AGNT_HIERY AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as PRODUCER_ID,
$2 as AGNT_NUM,
$3 as AGNT_NAME,
$4 as AGNT_FRST_NAME,
$5 as AGNT_LAST_NAME,
$6 as SRVC_CTR_NAME,
$7 as SRVC_CTR_NUM,
$8 as SRVC_CTR_CNTY_NAME,
$9 as DSTRCT_NAME,
$10 as DSTRCT_CD1,
$11 as RGN_NAME,
$12 as RGN_CD1,
$13 as ST_NAME,
$14 as ST_CD1,
$15 as DSTRCT_MGR_NAME1,
$16 as DSTRCT_MGR_FRST_NAME,
$17 as DSTRCT_MGR_LAST_NAME,
$18 as AGNT_HIRE_DT,
$19 as AGNT_TRMTN_DT,
$20 as AGNT_EFF_DT,
$21 as AGNT_EXPN_DT,
$22 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 

CASE WHEN (AGNT_NBR =''UNK'' ) THEN 0 ELSE CAST(A.AGNT_NBR AS INTEGER) END AS PRODUCER_ID

,CASE WHEN (AGNT_NBR =''UNK'' ) THEN 0 ELSE CAST(A.AGNT_NBR AS INTEGER) END AS AGNT_NUM

,CASE WHEN (AGNT_NBR =''UNK'' ) THEN ''0 - UNKNOWN'' ELSE B.COL1 END AS AGNT_NAME

,CASE WHEN (AGNT_NBR =''UNK'' ) THEN ''UNKNOWN'' 

WHEN SUBSTRING(B.COL1 ,POSITION('','' IN B.COL1))   NOT LIKE '',%'' THEN TRIM(G.FIRST_NAME) ELSE  TRIM(B.FIRST_NAME) END AS AGNT_FRST_NAME

,CASE WHEN (AGNT_NBR =''UNK'' ) THEN ''UNKNOWN'' 

WHEN SUBSTRING(B.COL1 ,POSITION('','' IN B.COL1))   NOT LIKE '',%'' THEN TRIM(G.LAST_NAME) ELSE  TRIM(B.LAST_NAME) END AS AGNT_LAST_NAME

,C.LKUP_CD_DESC AS SRVC_CTR_NAME

,A.SRVC_CTR_CD AS SRVC_CTR_NUM

,A.CNTY_NM AS SRVC_CTR_CNTY_NAME

,E.LKUP_CD_DESC AS DSTRCT_NAME

,A.DSTRCT_CD AS DSTRCT_CD

,D.LKUP_CD_DESC AS RGN_NAME

,A.RGN_CD AS RGN_CD

,F.LKUP_CD_DESC AS ST_NAME

,A.ST_CD AS ST_CD

,A.DSTRCT_MGR_NAME AS DSTRCT_MGR_NAME

,A.LSTNM2 AS DSTRCT_MGR_FRST_NAME

,A.LSTNM1 AS DSTRCT_MGR_LAST_NAME

,A.EMPLMT_DT AS AGNT_HIRE_DT

,A.TRMTN_DT AS AGNT_TRMTN_DT

,A.EFF_DT AS AGNT_EFF_DT

,A.EXPRY_DT AS AGNT_EXPN_DT

FROM 

(SELECT AGNT_NBR,SRVC_CTR_CD,RGN_CD,ST_CD,DSTRCT_MGR_NAME,EMPLMT_DT,TRMTN_DT,EFF_DT,EXPRY_DT,DSTRCT_CD,CNTY_NM,

SUBSTRING(DSTRCT_MGR_NAME ,POSITION('','' IN DSTRCT_MGR_NAME)+1)AS REST_NAME 

,SUBSTRING(REST_NAME ,POSITION( ''- '' IN REST_NAME)+1)AS FIRST_NAME

,SUBSTRING(FIRST_NAME ,POSITION('' '' IN FIRST_NAME)+1) AS LSTNM

,SUBSTRING(LSTNM ,POSITION('' '' IN LSTNM)+1) AS LSTNM1

,SUBSTRING(LSTNM ,1, POSITION('' '' IN LSTNM)+1) AS LSTNM2  

FROM db_v_prod_pres.WR_AGNT_HIERY A ) A



LEFT OUTER JOIN (SELECT LKUP_CD_DESC AS COL1 ,LKUP_VAL_CD,LKUP_NAME,

SUBSTRING(COL1 ,POSITION('','' IN COL1)+1)AS REST_NAME 

,SUBSTRING(REST_NAME ,POSITION(''- '' IN REST_NAME)+1)AS FIRST_NAME

,SUBSTRING(COL1 ,POSITION(''-'' IN COL1)+1)AS R1 

,SUBSTRING(R1,1,POSITION('','' IN R1)+1)AS R2

,SUBSTRING(R2 ,1, POSITION('','' IN R2))AS LAST_NAME

FROM db_v_prod_pres.CMPSIT_LKUP WHERE LKUP_NAME=''AGENT_LKP'' )     B

ON A.AGNT_NBR=B.LKUP_VAL_CD



LEFT OUTER JOIN (

SELECT  LKUP_CD_DESC AS COL1 ,LKUP_VAL_CD,LKUP_NAME,

SUBSTRING(COL1 ,POSITION(''-'' IN COL1)+1)AS R1  

,TRIM(R1) AS A

,SUBSTRING(A ,POSITION('' '' IN A)+1) AS LAST_NAME

,SUBSTRING(A ,1,POSITION('' '' IN A)) AS FIRST_NAME 
FROM  db_v_prod_pres.CMPSIT_LKUP 
 WHERE LKUP_NAME=''AGENT_LKP'' ) G

 ON A.AGNT_NBR=G.LKUP_VAL_CD





LEFT OUTER JOIN (SELECT LKUP_CD_DESC,LKUP_VAL_CD 
FROM db_v_prod_pres.CMPSIT_LKUP  WHERE LKUP_NAME=''SVC_NM_LKUP'' GROUP BY 1,2)     C

ON A.SRVC_CTR_CD=C.LKUP_VAL_CD





LEFT OUTER JOIN (SELECT LKUP_CD_DESC,LKUP_VAL_CD 
FROM db_v_prod_pres.CMPSIT_LKUP  WHERE LKUP_NAME=''RGN_CD_LKUP'' GROUP BY 1,2)   D

ON A.RGN_CD=D.LKUP_VAL_CD





LEFT OUTER JOIN (SELECT LKUP_CD_DESC,LKUP_VAL_CD 
FROM db_v_prod_pres.CMPSIT_LKUP  WHERE LKUP_NAME=''DIST_CD_LKUP'' GROUP BY 1,2)    E

ON A.DSTRCT_CD=E.LKUP_VAL_CD





LEFT OUTER JOIN (SELECT LKUP_CD_DESC,LKUP_VAL_CD 
FROM db_v_prod_pres.CMPSIT_LKUP  WHERE LKUP_NAME=''STATE_LKUP'' GROUP BY 1,2)   F

ON  A.ST_CD=F.LKUP_VAL_CD
) SRC
)
);


-- Component exp_Passthrough, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_Passthrough AS
(
SELECT
sq_WR_AGNT_HIERY.PRODUCER_ID as PRODUCER_ID,
sq_WR_AGNT_HIERY.AGNT_NUM as AGNT_NUM,
sq_WR_AGNT_HIERY.AGNT_NAME as AGNT_NAME,
sq_WR_AGNT_HIERY.AGNT_FRST_NAME as AGNT_FRST_NAME,
sq_WR_AGNT_HIERY.AGNT_LAST_NAME as AGNT_LAST_NAME,
sq_WR_AGNT_HIERY.SRVC_CTR_NAME as SRVC_CTR_NAME,
sq_WR_AGNT_HIERY.SRVC_CTR_NUM as SRVC_CTR_NUM,
sq_WR_AGNT_HIERY.SRVC_CTR_CNTY_NAME as SRVC_CTR_CNTY_NAME,
sq_WR_AGNT_HIERY.DSTRCT_NAME as DSTRCT_NAME,
sq_WR_AGNT_HIERY.DSTRCT_CD1 as DSTRCT_CD,
sq_WR_AGNT_HIERY.RGN_NAME as RGN_NAME,
sq_WR_AGNT_HIERY.RGN_CD1 as RGN_CD,
sq_WR_AGNT_HIERY.ST_NAME as ST_NAME,
sq_WR_AGNT_HIERY.ST_CD1 as ST_CD,
sq_WR_AGNT_HIERY.DSTRCT_MGR_NAME1 as DSTRCT_MGR_NAME,
sq_WR_AGNT_HIERY.DSTRCT_MGR_FRST_NAME as DSTRCT_MGR_FRST_NAME,
sq_WR_AGNT_HIERY.DSTRCT_MGR_LAST_NAME as DSTRCT_MGR_LAST_NAME,
sq_WR_AGNT_HIERY.AGNT_HIRE_DT as AGNT_HIRE_DT,
sq_WR_AGNT_HIERY.AGNT_TRMTN_DT as AGNT_TRMTN_DT,
sq_WR_AGNT_HIERY.AGNT_EFF_DT as AGNT_EFF_DT,
sq_WR_AGNT_HIERY.AGNT_EXPN_DT as AGNT_EXPN_DT,
sq_WR_AGNT_HIERY.source_record_id
FROM
sq_WR_AGNT_HIERY
);


-- Component D_PRODUCER_HIERY, Type TARGET 
INSERT INTO db_v_prod_pres.D_PRODUCER_HIERY
(
PRODUCER_ID,
AGNT_NUM,
AGNT_NAME,
AGNT_FRST_NAME,
AGNT_LAST_NAME,
SRVC_CTR_NAME,
SRVC_CTR_NUM,
SRVC_CTR_CNTY_NAME,
DSTRCT_NAME,
DSTRCT_CD,
RGN_NAME,
RGN_CD,
ST_NAME,
ST_CD,
DSTRCT_MGR_NAME,
DSTRCT_MGR_FRST_NAME,
DSTRCT_MGR_LAST_NAME,
AGNT_HIRE_DT,
AGNT_TRMTN_DT,
AGNT_EFF_DT,
AGNT_EXPN_DT
)
SELECT
exp_Passthrough.PRODUCER_ID as PRODUCER_ID,
exp_Passthrough.AGNT_NUM as AGNT_NUM,
exp_Passthrough.AGNT_NAME as AGNT_NAME,
exp_Passthrough.AGNT_FRST_NAME as AGNT_FRST_NAME,
exp_Passthrough.AGNT_LAST_NAME as AGNT_LAST_NAME,
exp_Passthrough.SRVC_CTR_NAME as SRVC_CTR_NAME,
exp_Passthrough.SRVC_CTR_NUM as SRVC_CTR_NUM,
exp_Passthrough.SRVC_CTR_CNTY_NAME as SRVC_CTR_CNTY_NAME,
exp_Passthrough.DSTRCT_NAME as DSTRCT_NAME,
exp_Passthrough.DSTRCT_CD as DSTRCT_CD,
exp_Passthrough.RGN_NAME as RGN_NAME,
exp_Passthrough.RGN_CD as RGN_CD,
exp_Passthrough.ST_NAME as ST_NAME,
exp_Passthrough.ST_CD as ST_CD,
exp_Passthrough.DSTRCT_MGR_NAME as DSTRCT_MGR_NAME,
exp_Passthrough.DSTRCT_MGR_FRST_NAME as DSTRCT_MGR_FRST_NAME,
exp_Passthrough.DSTRCT_MGR_LAST_NAME as DSTRCT_MGR_LAST_NAME,
exp_Passthrough.AGNT_HIRE_DT as AGNT_HIRE_DT,
exp_Passthrough.AGNT_TRMTN_DT as AGNT_TRMTN_DT,
exp_Passthrough.AGNT_EFF_DT as AGNT_EFF_DT,
exp_Passthrough.AGNT_EXPN_DT as AGNT_EXPN_DT
FROM
exp_Passthrough;


END; ';