-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_MS_CLARITY_EXTRACT_FILE("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' 
DECLARE

run_id STRING;
prcs_id int;
YR_STRT_DT string;
YR_END_DT string;
CO_CD1 string;
CO_CD2 string;
PULL_YR1 int;
PULL_YR2 int;
PULL_YR3 int;
BEGIN

run_id :=   (SELECT run_id   FROM control_run_id where upper(worklet_name) = upper(:worklet_name) order by insert_ts desc limit 1);   
PRCS_ID:=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''PRCS_ID'' order by insert_ts desc limit 1);
YR_STRT_DT :=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''YR_STRT_DT'' order by insert_ts desc limit 1);
YR_END_DT :=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''YR_END_DT'' order by insert_ts desc limit 1);
CO_CD1 :=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''CO_CD1'' order by insert_ts desc limit 1);
CO_CD2 :=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''CO_CD2'' order by insert_ts desc limit 1);
PULL_YR1 :=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''PULL_YR1'' order by insert_ts desc limit 1);
PULL_YR2 :=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''PULL_YR2'' order by insert_ts desc limit 1);
PULL_YR3 :=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''PULL_YR3'' order by insert_ts desc limit 1);


-- Component sq_MS_CLRTY_XTRCT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_MS_CLRTY_XTRCT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as NAIC_CD,
$2 as CO_NAME,
$3 as PULL_YR,
$4 as ZIPCD,
$5 as DPW_TOT,
$6 as DPW_WIND_ONLY,
$7 as DPW_EXCLG_WIND,
$8 as DPW_INCLG_WIND,
$9 as DEP_TOT,
$10 as DEP_WIND_ONLY,
$11 as DEP_EXCLG_WIND,
$12 as DEP_INCLG_WIND,
$13 as WIND_EXCL_FCTR,
$14 as DLI_TOT,
$15 as DLI_WIND_ONLY,
$16 as DLI_EXCLG_WIND,
$17 as DLI_INCLG_WIND,
$18 as DLI_HURCN,
$19 as DLI_WIND_CTSTRPH,
$20 as DLI_OTH_WIND,
$21 as DLI_WIND_SBTOT,
$22 as DLI_OTH_CTSTRPH,
$23 as DLI_ALL_OTH,
$24 as ALAE_TOT,
$25 as ALAE_WIND_ONLY,
$26 as ALAE_EXCLG_WIND,
$27 as ALAE_INCLG_WIND,
$28 as ALAE_HURCN,
$29 as ALAE_WIND_CTSTRPH,
$30 as ALAE_OTH_WIND,
$31 as ALAE_WIND_SBTOT,
$32 as ALAE_OTH_CTSTRPH,
$33 as ALAE_ALL_OTH,
$34 as EHY_TOT,
$35 as EHY_WIND_ONLY,
$36 as EHY_EXCLG_WIND,
$37 as EHY_ALL_OTH,
$38 as DWL_CVGE_A_TOT,
$39 as DWL_CVGE_A_WO,
$40 as DWL_CVGE_A_EXCLG_WIND,
$41 as DWL_CVGE_A_INCLG_WIND,
$42 as DWL_CVGE_C_TOT,
$43 as DWL_CVGE_C_WO,
$44 as DWL_CVGE_C_EXCLG_WIND,
$45 as DWL_CVGE_C_INCLG_WIND,
$46 as COMTS,
$47 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT NAIC_CD,CO_NAME,PULL_YR,

ZIPCD,

SUM(DPW_TOT) AS DPW_TOT,

MAX(DPW_WIND_ONLY) AS DPW_WIND_ONLY,

SUM(DPW_EXCLG_WIND) AS DPW_EXCLG_WIND,

SUM(DPW_INCLG_WIND) AS DPW_INCLG_WIND,

SUM(DEP_TOT) AS DEP_TOT,

MAX(DEP_WIND_ONLY) AS DEP_WIND_ONLY,

SUM(DEP_EXCLG_WIND) AS DEP_EXCLG_WIND,

SUM(DEP_INCLG_WIND) AS DEP_INCLG_WIND,

(WIND_EXCL_FCTR) AS WIND_EXCL_FCTR,

SUM(DLI_TOT) AS DLI_TOT,

MAX( DLI_WIND_ONLY) AS DLI_WIND_ONLY,

SUM(DLI_EXCLG_WIND) AS DLI_EXCLG_WIND,

SUM(DLI_INCLG_WIND) AS DLI_INCLG_WIND,

SUM(DLI_HURCN) AS DLI_HURCN,

SUM(DLI_WIND_CTSTRPH) AS DLI_WIND_CTSTRPH,

SUM(DLI_OTH_WIND) AS DLI_OTH_WIND,

SUM(DLI_WIND_SBTOT) AS DLI_WIND_SBTOT,

 MAX(DLI_OTH_CTSTRPH) AS DLI_OTH_CTSTRPH,

SUM(DLI_ALL_OTH) AS DLI_ALL_OTH,

SUM(ALAE_TOT) AS ALAE_TOT,

MAX(ALAE_WIND_ONLY) AS ALAE_WIND_ONLY,

SUM(ALAE_EXCLG_WIND) AS ALAE_EXCLG_WIND,

SUM(ALAE_INCLG_WIND) AS ALAE_INCLG_WIND,

SUM(ALAE_HURCN) AS ALAE_HURCN,

SUM(ALAE_WIND_CTSTRPH) AS ALAE_WIND_CTSTRPH,

SUM(ALAE_OTH_WIND) AS ALAE_OTH_WIND,

SUM(ALAE_WIND_SBTOT) AS ALAE_WIND_SBTOT,

 MAX(ALAE_OTH_CTSTRPH) AS ALAE_OTH_CTSTRPH,

SUM(ALAE_ALL_OTH) AS ALAE_ALL_OTH,

SUM(EHY_TOT) AS EHY_TOT,

MAX(EHY_WIND_ONLY) AS EHY_WIND_ONLY,

SUM(EHY_EXCLG_WIND) AS EHY_EXCLG_WIND,

SUM(EHY_ALL_OTH) AS EHY_ALL_OTH,

SUM(DWL_CVGE_A_TOT) AS DWL_CVGE_A_TOT,

MAX(DWL_CVGE_A_WO) AS DWL_CVGE_A_WO,

SUM(DWL_CVGE_A_EXCLG_WIND) AS DWL_CVGE_A_EXCLG_WIND,

SUM(DWL_CVGE_A_INCLG_WIND) AS DWL_CVGE_A_INCLG_WIND,

SUM(DWL_CVGE_C_TOT) AS DWL_CVGE_C_TOT,

MAX(DWL_CVGE_C_WO) AS DWL_CVGE_C_WO,

SUM(DWL_CVGE_C_EXCLG_WIND) AS DWL_CVGE_C_EXCLG_WIND,

SUM(DWL_CVGE_C_INCLG_WIND) AS DWL_CVGE_C_INCLG_WIND,

(COMTS) AS COMTS

FROM DB_T_PROD_WRK.MS_CLRTY_XTRCT WHERE  ROW_TYPE_CD=''MRGD'' AND VLDN_ERR_MSG='''' 

and PULL_YR between extract(year from to_date( :YR_STRT_DT , ''mm/dd/yyyy''))

and extract(year from to_date( :YR_END_DT ,''mm/dd/yyyy'')) 

GROUP BY NAIC_CD,CO_NAME,PULL_YR,ZIPCD ,COMTS,WIND_EXCL_FCTR ORDER BY NAIC_CD,CO_NAME,PULL_YR,ZIPCD
) SRC
)
);


-- Component exp_DEFAULT, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_DEFAULT AS
(
SELECT
sq_MS_CLRTY_XTRCT.NAIC_CD as NAIC_CD,
sq_MS_CLRTY_XTRCT.CO_NAME as CO_NAME,
sq_MS_CLRTY_XTRCT.PULL_YR as PULL_YR,
sq_MS_CLRTY_XTRCT.ZIPCD as ZIPCD,
sq_MS_CLRTY_XTRCT.DPW_TOT as o_DPW_TOT,
sq_MS_CLRTY_XTRCT.DPW_WIND_ONLY as DPW_WIND_ONLY,
sq_MS_CLRTY_XTRCT.DPW_EXCLG_WIND as o_DPW_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.DPW_INCLG_WIND as o_DPW_INCLG_WIND,
sq_MS_CLRTY_XTRCT.DEP_TOT as o_DEP_TOT,
sq_MS_CLRTY_XTRCT.DEP_WIND_ONLY as DEP_WIND_ONLY,
sq_MS_CLRTY_XTRCT.DEP_EXCLG_WIND as o_DEP_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.DEP_INCLG_WIND as o_DEP_INCLG_WIND,
sq_MS_CLRTY_XTRCT.WIND_EXCL_FCTR as WIND_EXCL_FCTR,
sq_MS_CLRTY_XTRCT.DLI_TOT as o_DLI_TOT,
sq_MS_CLRTY_XTRCT.DLI_WIND_ONLY as DLI_WIND_ONLY,
sq_MS_CLRTY_XTRCT.DLI_EXCLG_WIND as o_DLI_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.DLI_INCLG_WIND as o_DLI_INCLG_WIND,
sq_MS_CLRTY_XTRCT.DLI_HURCN as o_DLI_HURCN,
sq_MS_CLRTY_XTRCT.DLI_WIND_CTSTRPH as o_DLI_WIND_CTSTRPH,
sq_MS_CLRTY_XTRCT.DLI_OTH_WIND as o_DLI_OTH_WIND,
sq_MS_CLRTY_XTRCT.DLI_WIND_SBTOT as o_DLI_WIND_SBTOT,
sq_MS_CLRTY_XTRCT.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
sq_MS_CLRTY_XTRCT.DLI_ALL_OTH as o_DLI_ALL_OTH,
sq_MS_CLRTY_XTRCT.ALAE_TOT as o_ALAE_TOT,
sq_MS_CLRTY_XTRCT.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
sq_MS_CLRTY_XTRCT.ALAE_EXCLG_WIND as o_ALAE_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.ALAE_INCLG_WIND as o_ALAE_INCLG_WIND,
sq_MS_CLRTY_XTRCT.ALAE_HURCN as o_ALAE_HURCN,
sq_MS_CLRTY_XTRCT.ALAE_WIND_CTSTRPH as o_ALAE_WIND_CTSTRPH,
sq_MS_CLRTY_XTRCT.ALAE_OTH_WIND as o_ALAE_OTH_WIND,
sq_MS_CLRTY_XTRCT.ALAE_WIND_SBTOT as o_ALAE_WIND_SBTOT,
sq_MS_CLRTY_XTRCT.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
sq_MS_CLRTY_XTRCT.ALAE_ALL_OTH as o_ALAE_ALL_OTH,
sq_MS_CLRTY_XTRCT.EHY_TOT as o_EHY_TOT,
sq_MS_CLRTY_XTRCT.EHY_WIND_ONLY as EHY_WIND_ONLY,
sq_MS_CLRTY_XTRCT.EHY_EXCLG_WIND as o_EHY_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.EHY_ALL_OTH as o_EHY_ALL_OTH,
sq_MS_CLRTY_XTRCT.DWL_CVGE_A_TOT as o_DWL_CVGE_A_TOT,
sq_MS_CLRTY_XTRCT.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
sq_MS_CLRTY_XTRCT.DWL_CVGE_A_EXCLG_WIND as o_DWL_CVGE_A_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.DWL_CVGE_A_INCLG_WIND as o_DWL_CVGE_A_INCLG_WIND,
sq_MS_CLRTY_XTRCT.DWL_CVGE_C_TOT as o_DWL_CVGE_C_TOT,
sq_MS_CLRTY_XTRCT.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
sq_MS_CLRTY_XTRCT.DWL_CVGE_C_EXCLG_WIND as o_DWL_CVGE_C_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.DWL_CVGE_C_INCLG_WIND as o_DWL_CVGE_C_INCLG_WIND,
sq_MS_CLRTY_XTRCT.COMTS as COMTS,
CASE WHEN sq_MS_CLRTY_XTRCT.CO_NAME = ''ALFA GEN INS CORP'' THEN ''AGI'' ELSE NULL END as CO_CD1,
CASE WHEN sq_MS_CLRTY_XTRCT.CO_NAME = ''ALFA INS CORP'' THEN ''AIC'' ELSE NULL END as CO_CD2,
sq_MS_CLRTY_XTRCT.source_record_id
FROM
sq_MS_CLRTY_XTRCT
);


-- Component rtr_CO_NAME_PULL_YR_CO_CD1_YR1, Type ROUTER Output Group CO_CD1_YR1
create or replace temporary table rtr_CO_NAME_PULL_YR_CO_CD1_YR1 as
SELECT
exp_DEFAULT.NAIC_CD as NAIC_CD,
exp_DEFAULT.CO_NAME as CO_NAME,
exp_DEFAULT.PULL_YR as PULL_YR,
exp_DEFAULT.ZIPCD as ZIPCD,
exp_DEFAULT.o_DPW_TOT as o_DPW_TOT,
exp_DEFAULT.DPW_WIND_ONLY as DPW_WIND_ONLY,
exp_DEFAULT.o_DPW_EXCLG_WIND as o_DPW_EXCLG_WIND,
exp_DEFAULT.o_DPW_INCLG_WIND as o_DPW_INCLG_WIND,
exp_DEFAULT.o_DEP_TOT as o_DEP_TOT,
exp_DEFAULT.DEP_WIND_ONLY as DEP_WIND_ONLY,
exp_DEFAULT.o_DEP_EXCLG_WIND as o_DEP_EXCLG_WIND,
exp_DEFAULT.o_DEP_INCLG_WIND as o_DEP_INCLG_WIND,
exp_DEFAULT.WIND_EXCL_FCTR as WIND_EXCL_FCTR,
exp_DEFAULT.o_DLI_TOT as o_DLI_TOT,
exp_DEFAULT.DLI_WIND_ONLY as DLI_WIND_ONLY,
exp_DEFAULT.o_DLI_EXCLG_WIND as o_DLI_EXCLG_WIND,
exp_DEFAULT.o_DLI_INCLG_WIND as o_DLI_INCLG_WIND,
exp_DEFAULT.o_DLI_HURCN as o_DLI_HURCN,
exp_DEFAULT.o_DLI_WIND_CTSTRPH as o_DLI_WIND_CTSTRPH,
exp_DEFAULT.o_DLI_OTH_WIND as o_DLI_OTH_WIND,
exp_DEFAULT.o_DLI_WIND_SBTOT as o_DLI_WIND_SBTOT,
exp_DEFAULT.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
exp_DEFAULT.o_DLI_ALL_OTH as o_DLI_ALL_OTH,
exp_DEFAULT.o_ALAE_TOT as o_ALAE_TOT,
exp_DEFAULT.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
exp_DEFAULT.o_ALAE_EXCLG_WIND as o_ALAE_EXCLG_WIND,
exp_DEFAULT.o_ALAE_INCLG_WIND as o_ALAE_INCLG_WIND,
exp_DEFAULT.o_ALAE_HURCN as o_ALAE_HURCN,
exp_DEFAULT.o_ALAE_WIND_CTSTRPH as o_ALAE_WIND_CTSTRPH,
exp_DEFAULT.o_ALAE_OTH_WIND as o_ALAE_OTH_WIND,
exp_DEFAULT.o_ALAE_WIND_SBTOT as o_ALAE_WIND_SBTOT,
exp_DEFAULT.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
exp_DEFAULT.o_ALAE_ALL_OTH as o_ALAE_ALL_OTH,
exp_DEFAULT.o_EHY_TOT as o_EHY_TOT,
exp_DEFAULT.EHY_WIND_ONLY as EHY_WIND_ONLY,
exp_DEFAULT.o_EHY_EXCLG_WIND as o_EHY_EXCLG_WIND,
exp_DEFAULT.o_EHY_ALL_OTH as o_EHY_ALL_OTH,
exp_DEFAULT.o_DWL_CVGE_A_TOT as o_DWL_CVGE_A_TOT,
exp_DEFAULT.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
exp_DEFAULT.o_DWL_CVGE_A_EXCLG_WIND as o_DWL_CVGE_A_EXCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_A_INCLG_WIND as o_DWL_CVGE_A_INCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_C_TOT as o_DWL_CVGE_C_TOT,
exp_DEFAULT.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
exp_DEFAULT.o_DWL_CVGE_C_EXCLG_WIND as o_DWL_CVGE_C_EXCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_C_INCLG_WIND as o_DWL_CVGE_C_INCLG_WIND,
exp_DEFAULT.COMTS as COMTS,
exp_DEFAULT.CO_CD1 as CO_CD1,
exp_DEFAULT.CO_CD2 as CO_CD2,
exp_DEFAULT.source_record_id
FROM
exp_DEFAULT
WHERE exp_DEFAULT.CO_CD1 = :CO_CD1 AND exp_DEFAULT.PULL_YR = :PULL_YR1;


-- Component rtr_CO_NAME_PULL_YR_CO_CD1_YR2, Type ROUTER Output Group CO_CD1_YR2
create or replace temporary table rtr_CO_NAME_PULL_YR_CO_CD1_YR2 as
SELECT
exp_DEFAULT.NAIC_CD as NAIC_CD,
exp_DEFAULT.CO_NAME as CO_NAME,
exp_DEFAULT.PULL_YR as PULL_YR,
exp_DEFAULT.ZIPCD as ZIPCD,
exp_DEFAULT.o_DPW_TOT as o_DPW_TOT,
exp_DEFAULT.DPW_WIND_ONLY as DPW_WIND_ONLY,
exp_DEFAULT.o_DPW_EXCLG_WIND as o_DPW_EXCLG_WIND,
exp_DEFAULT.o_DPW_INCLG_WIND as o_DPW_INCLG_WIND,
exp_DEFAULT.o_DEP_TOT as o_DEP_TOT,
exp_DEFAULT.DEP_WIND_ONLY as DEP_WIND_ONLY,
exp_DEFAULT.o_DEP_EXCLG_WIND as o_DEP_EXCLG_WIND,
exp_DEFAULT.o_DEP_INCLG_WIND as o_DEP_INCLG_WIND,
exp_DEFAULT.WIND_EXCL_FCTR as WIND_EXCL_FCTR,
exp_DEFAULT.o_DLI_TOT as o_DLI_TOT,
exp_DEFAULT.DLI_WIND_ONLY as DLI_WIND_ONLY,
exp_DEFAULT.o_DLI_EXCLG_WIND as o_DLI_EXCLG_WIND,
exp_DEFAULT.o_DLI_INCLG_WIND as o_DLI_INCLG_WIND,
exp_DEFAULT.o_DLI_HURCN as o_DLI_HURCN,
exp_DEFAULT.o_DLI_WIND_CTSTRPH as o_DLI_WIND_CTSTRPH,
exp_DEFAULT.o_DLI_OTH_WIND as o_DLI_OTH_WIND,
exp_DEFAULT.o_DLI_WIND_SBTOT as o_DLI_WIND_SBTOT,
exp_DEFAULT.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
exp_DEFAULT.o_DLI_ALL_OTH as o_DLI_ALL_OTH,
exp_DEFAULT.o_ALAE_TOT as o_ALAE_TOT,
exp_DEFAULT.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
exp_DEFAULT.o_ALAE_EXCLG_WIND as o_ALAE_EXCLG_WIND,
exp_DEFAULT.o_ALAE_INCLG_WIND as o_ALAE_INCLG_WIND,
exp_DEFAULT.o_ALAE_HURCN as o_ALAE_HURCN,
exp_DEFAULT.o_ALAE_WIND_CTSTRPH as o_ALAE_WIND_CTSTRPH,
exp_DEFAULT.o_ALAE_OTH_WIND as o_ALAE_OTH_WIND,
exp_DEFAULT.o_ALAE_WIND_SBTOT as o_ALAE_WIND_SBTOT,
exp_DEFAULT.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
exp_DEFAULT.o_ALAE_ALL_OTH as o_ALAE_ALL_OTH,
exp_DEFAULT.o_EHY_TOT as o_EHY_TOT,
exp_DEFAULT.EHY_WIND_ONLY as EHY_WIND_ONLY,
exp_DEFAULT.o_EHY_EXCLG_WIND as o_EHY_EXCLG_WIND,
exp_DEFAULT.o_EHY_ALL_OTH as o_EHY_ALL_OTH,
exp_DEFAULT.o_DWL_CVGE_A_TOT as o_DWL_CVGE_A_TOT,
exp_DEFAULT.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
exp_DEFAULT.o_DWL_CVGE_A_EXCLG_WIND as o_DWL_CVGE_A_EXCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_A_INCLG_WIND as o_DWL_CVGE_A_INCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_C_TOT as o_DWL_CVGE_C_TOT,
exp_DEFAULT.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
exp_DEFAULT.o_DWL_CVGE_C_EXCLG_WIND as o_DWL_CVGE_C_EXCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_C_INCLG_WIND as o_DWL_CVGE_C_INCLG_WIND,
exp_DEFAULT.COMTS as COMTS,
exp_DEFAULT.CO_CD1 as CO_CD1,
exp_DEFAULT.CO_CD2 as CO_CD2,
exp_DEFAULT.source_record_id
FROM
exp_DEFAULT
WHERE exp_DEFAULT.CO_CD1 = :CO_CD1 AND exp_DEFAULT.PULL_YR = :PULL_YR2;


-- Component rtr_CO_NAME_PULL_YR_CO_CD1_YR3, Type ROUTER Output Group CO_CD1_YR3
create or replace temporary table rtr_CO_NAME_PULL_YR_CO_CD1_YR3 as
SELECT
exp_DEFAULT.NAIC_CD as NAIC_CD,
exp_DEFAULT.CO_NAME as CO_NAME,
exp_DEFAULT.PULL_YR as PULL_YR,
exp_DEFAULT.ZIPCD as ZIPCD,
exp_DEFAULT.o_DPW_TOT as o_DPW_TOT,
exp_DEFAULT.DPW_WIND_ONLY as DPW_WIND_ONLY,
exp_DEFAULT.o_DPW_EXCLG_WIND as o_DPW_EXCLG_WIND,
exp_DEFAULT.o_DPW_INCLG_WIND as o_DPW_INCLG_WIND,
exp_DEFAULT.o_DEP_TOT as o_DEP_TOT,
exp_DEFAULT.DEP_WIND_ONLY as DEP_WIND_ONLY,
exp_DEFAULT.o_DEP_EXCLG_WIND as o_DEP_EXCLG_WIND,
exp_DEFAULT.o_DEP_INCLG_WIND as o_DEP_INCLG_WIND,
exp_DEFAULT.WIND_EXCL_FCTR as WIND_EXCL_FCTR,
exp_DEFAULT.o_DLI_TOT as o_DLI_TOT,
exp_DEFAULT.DLI_WIND_ONLY as DLI_WIND_ONLY,
exp_DEFAULT.o_DLI_EXCLG_WIND as o_DLI_EXCLG_WIND,
exp_DEFAULT.o_DLI_INCLG_WIND as o_DLI_INCLG_WIND,
exp_DEFAULT.o_DLI_HURCN as o_DLI_HURCN,
exp_DEFAULT.o_DLI_WIND_CTSTRPH as o_DLI_WIND_CTSTRPH,
exp_DEFAULT.o_DLI_OTH_WIND as o_DLI_OTH_WIND,
exp_DEFAULT.o_DLI_WIND_SBTOT as o_DLI_WIND_SBTOT,
exp_DEFAULT.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
exp_DEFAULT.o_DLI_ALL_OTH as o_DLI_ALL_OTH,
exp_DEFAULT.o_ALAE_TOT as o_ALAE_TOT,
exp_DEFAULT.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
exp_DEFAULT.o_ALAE_EXCLG_WIND as o_ALAE_EXCLG_WIND,
exp_DEFAULT.o_ALAE_INCLG_WIND as o_ALAE_INCLG_WIND,
exp_DEFAULT.o_ALAE_HURCN as o_ALAE_HURCN,
exp_DEFAULT.o_ALAE_WIND_CTSTRPH as o_ALAE_WIND_CTSTRPH,
exp_DEFAULT.o_ALAE_OTH_WIND as o_ALAE_OTH_WIND,
exp_DEFAULT.o_ALAE_WIND_SBTOT as o_ALAE_WIND_SBTOT,
exp_DEFAULT.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
exp_DEFAULT.o_ALAE_ALL_OTH as o_ALAE_ALL_OTH,
exp_DEFAULT.o_EHY_TOT as o_EHY_TOT,
exp_DEFAULT.EHY_WIND_ONLY as EHY_WIND_ONLY,
exp_DEFAULT.o_EHY_EXCLG_WIND as o_EHY_EXCLG_WIND,
exp_DEFAULT.o_EHY_ALL_OTH as o_EHY_ALL_OTH,
exp_DEFAULT.o_DWL_CVGE_A_TOT as o_DWL_CVGE_A_TOT,
exp_DEFAULT.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
exp_DEFAULT.o_DWL_CVGE_A_EXCLG_WIND as o_DWL_CVGE_A_EXCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_A_INCLG_WIND as o_DWL_CVGE_A_INCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_C_TOT as o_DWL_CVGE_C_TOT,
exp_DEFAULT.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
exp_DEFAULT.o_DWL_CVGE_C_EXCLG_WIND as o_DWL_CVGE_C_EXCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_C_INCLG_WIND as o_DWL_CVGE_C_INCLG_WIND,
exp_DEFAULT.COMTS as COMTS,
exp_DEFAULT.CO_CD1 as CO_CD1,
exp_DEFAULT.CO_CD2 as CO_CD2,
exp_DEFAULT.source_record_id
FROM
exp_DEFAULT
WHERE exp_DEFAULT.CO_CD1 = :CO_CD1 AND exp_DEFAULT.PULL_YR = :PULL_YR3;


-- Component rtr_CO_NAME_PULL_YR_CO_CD2_YR1, Type ROUTER Output Group CO_CD2_YR1
create or replace temporary table rtr_CO_NAME_PULL_YR_CO_CD2_YR1 as
SELECT
exp_DEFAULT.NAIC_CD as NAIC_CD,
exp_DEFAULT.CO_NAME as CO_NAME,
exp_DEFAULT.PULL_YR as PULL_YR,
exp_DEFAULT.ZIPCD as ZIPCD,
exp_DEFAULT.o_DPW_TOT as o_DPW_TOT,
exp_DEFAULT.DPW_WIND_ONLY as DPW_WIND_ONLY,
exp_DEFAULT.o_DPW_EXCLG_WIND as o_DPW_EXCLG_WIND,
exp_DEFAULT.o_DPW_INCLG_WIND as o_DPW_INCLG_WIND,
exp_DEFAULT.o_DEP_TOT as o_DEP_TOT,
exp_DEFAULT.DEP_WIND_ONLY as DEP_WIND_ONLY,
exp_DEFAULT.o_DEP_EXCLG_WIND as o_DEP_EXCLG_WIND,
exp_DEFAULT.o_DEP_INCLG_WIND as o_DEP_INCLG_WIND,
exp_DEFAULT.WIND_EXCL_FCTR as WIND_EXCL_FCTR,
exp_DEFAULT.o_DLI_TOT as o_DLI_TOT,
exp_DEFAULT.DLI_WIND_ONLY as DLI_WIND_ONLY,
exp_DEFAULT.o_DLI_EXCLG_WIND as o_DLI_EXCLG_WIND,
exp_DEFAULT.o_DLI_INCLG_WIND as o_DLI_INCLG_WIND,
exp_DEFAULT.o_DLI_HURCN as o_DLI_HURCN,
exp_DEFAULT.o_DLI_WIND_CTSTRPH as o_DLI_WIND_CTSTRPH,
exp_DEFAULT.o_DLI_OTH_WIND as o_DLI_OTH_WIND,
exp_DEFAULT.o_DLI_WIND_SBTOT as o_DLI_WIND_SBTOT,
exp_DEFAULT.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
exp_DEFAULT.o_DLI_ALL_OTH as o_DLI_ALL_OTH,
exp_DEFAULT.o_ALAE_TOT as o_ALAE_TOT,
exp_DEFAULT.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
exp_DEFAULT.o_ALAE_EXCLG_WIND as o_ALAE_EXCLG_WIND,
exp_DEFAULT.o_ALAE_INCLG_WIND as o_ALAE_INCLG_WIND,
exp_DEFAULT.o_ALAE_HURCN as o_ALAE_HURCN,
exp_DEFAULT.o_ALAE_WIND_CTSTRPH as o_ALAE_WIND_CTSTRPH,
exp_DEFAULT.o_ALAE_OTH_WIND as o_ALAE_OTH_WIND,
exp_DEFAULT.o_ALAE_WIND_SBTOT as o_ALAE_WIND_SBTOT,
exp_DEFAULT.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
exp_DEFAULT.o_ALAE_ALL_OTH as o_ALAE_ALL_OTH,
exp_DEFAULT.o_EHY_TOT as o_EHY_TOT,
exp_DEFAULT.EHY_WIND_ONLY as EHY_WIND_ONLY,
exp_DEFAULT.o_EHY_EXCLG_WIND as o_EHY_EXCLG_WIND,
exp_DEFAULT.o_EHY_ALL_OTH as o_EHY_ALL_OTH,
exp_DEFAULT.o_DWL_CVGE_A_TOT as o_DWL_CVGE_A_TOT,
exp_DEFAULT.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
exp_DEFAULT.o_DWL_CVGE_A_EXCLG_WIND as o_DWL_CVGE_A_EXCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_A_INCLG_WIND as o_DWL_CVGE_A_INCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_C_TOT as o_DWL_CVGE_C_TOT,
exp_DEFAULT.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
exp_DEFAULT.o_DWL_CVGE_C_EXCLG_WIND as o_DWL_CVGE_C_EXCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_C_INCLG_WIND as o_DWL_CVGE_C_INCLG_WIND,
exp_DEFAULT.COMTS as COMTS,
exp_DEFAULT.CO_CD1 as CO_CD1,
exp_DEFAULT.CO_CD2 as CO_CD2,
exp_DEFAULT.source_record_id
FROM
exp_DEFAULT
WHERE exp_DEFAULT.CO_CD2 = :CO_CD2 AND exp_DEFAULT.PULL_YR = :PULL_YR1;


-- Component rtr_CO_NAME_PULL_YR_CO_CD2_YR2, Type ROUTER Output Group CO_CD2_YR2
create or replace temporary table rtr_CO_NAME_PULL_YR_CO_CD2_YR2 as
SELECT
exp_DEFAULT.NAIC_CD as NAIC_CD,
exp_DEFAULT.CO_NAME as CO_NAME,
exp_DEFAULT.PULL_YR as PULL_YR,
exp_DEFAULT.ZIPCD as ZIPCD,
exp_DEFAULT.o_DPW_TOT as o_DPW_TOT,
exp_DEFAULT.DPW_WIND_ONLY as DPW_WIND_ONLY,
exp_DEFAULT.o_DPW_EXCLG_WIND as o_DPW_EXCLG_WIND,
exp_DEFAULT.o_DPW_INCLG_WIND as o_DPW_INCLG_WIND,
exp_DEFAULT.o_DEP_TOT as o_DEP_TOT,
exp_DEFAULT.DEP_WIND_ONLY as DEP_WIND_ONLY,
exp_DEFAULT.o_DEP_EXCLG_WIND as o_DEP_EXCLG_WIND,
exp_DEFAULT.o_DEP_INCLG_WIND as o_DEP_INCLG_WIND,
exp_DEFAULT.WIND_EXCL_FCTR as WIND_EXCL_FCTR,
exp_DEFAULT.o_DLI_TOT as o_DLI_TOT,
exp_DEFAULT.DLI_WIND_ONLY as DLI_WIND_ONLY,
exp_DEFAULT.o_DLI_EXCLG_WIND as o_DLI_EXCLG_WIND,
exp_DEFAULT.o_DLI_INCLG_WIND as o_DLI_INCLG_WIND,
exp_DEFAULT.o_DLI_HURCN as o_DLI_HURCN,
exp_DEFAULT.o_DLI_WIND_CTSTRPH as o_DLI_WIND_CTSTRPH,
exp_DEFAULT.o_DLI_OTH_WIND as o_DLI_OTH_WIND,
exp_DEFAULT.o_DLI_WIND_SBTOT as o_DLI_WIND_SBTOT,
exp_DEFAULT.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
exp_DEFAULT.o_DLI_ALL_OTH as o_DLI_ALL_OTH,
exp_DEFAULT.o_ALAE_TOT as o_ALAE_TOT,
exp_DEFAULT.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
exp_DEFAULT.o_ALAE_EXCLG_WIND as o_ALAE_EXCLG_WIND,
exp_DEFAULT.o_ALAE_INCLG_WIND as o_ALAE_INCLG_WIND,
exp_DEFAULT.o_ALAE_HURCN as o_ALAE_HURCN,
exp_DEFAULT.o_ALAE_WIND_CTSTRPH as o_ALAE_WIND_CTSTRPH,
exp_DEFAULT.o_ALAE_OTH_WIND as o_ALAE_OTH_WIND,
exp_DEFAULT.o_ALAE_WIND_SBTOT as o_ALAE_WIND_SBTOT,
exp_DEFAULT.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
exp_DEFAULT.o_ALAE_ALL_OTH as o_ALAE_ALL_OTH,
exp_DEFAULT.o_EHY_TOT as o_EHY_TOT,
exp_DEFAULT.EHY_WIND_ONLY as EHY_WIND_ONLY,
exp_DEFAULT.o_EHY_EXCLG_WIND as o_EHY_EXCLG_WIND,
exp_DEFAULT.o_EHY_ALL_OTH as o_EHY_ALL_OTH,
exp_DEFAULT.o_DWL_CVGE_A_TOT as o_DWL_CVGE_A_TOT,
exp_DEFAULT.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
exp_DEFAULT.o_DWL_CVGE_A_EXCLG_WIND as o_DWL_CVGE_A_EXCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_A_INCLG_WIND as o_DWL_CVGE_A_INCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_C_TOT as o_DWL_CVGE_C_TOT,
exp_DEFAULT.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
exp_DEFAULT.o_DWL_CVGE_C_EXCLG_WIND as o_DWL_CVGE_C_EXCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_C_INCLG_WIND as o_DWL_CVGE_C_INCLG_WIND,
exp_DEFAULT.COMTS as COMTS,
exp_DEFAULT.CO_CD1 as CO_CD1,
exp_DEFAULT.CO_CD2 as CO_CD2,
exp_DEFAULT.source_record_id
FROM
exp_DEFAULT
WHERE exp_DEFAULT.CO_CD2 = :CO_CD2 AND exp_DEFAULT.PULL_YR = :PULL_YR2;


-- Component rtr_CO_NAME_PULL_YR_CO_CD2_YR3, Type ROUTER Output Group CO_CD2_YR3
create or replace temporary table rtr_CO_NAME_PULL_YR_CO_CD2_YR3 as
SELECT
exp_DEFAULT.NAIC_CD as NAIC_CD,
exp_DEFAULT.CO_NAME as CO_NAME,
exp_DEFAULT.PULL_YR as PULL_YR,
exp_DEFAULT.ZIPCD as ZIPCD,
exp_DEFAULT.o_DPW_TOT as o_DPW_TOT,
exp_DEFAULT.DPW_WIND_ONLY as DPW_WIND_ONLY,
exp_DEFAULT.o_DPW_EXCLG_WIND as o_DPW_EXCLG_WIND,
exp_DEFAULT.o_DPW_INCLG_WIND as o_DPW_INCLG_WIND,
exp_DEFAULT.o_DEP_TOT as o_DEP_TOT,
exp_DEFAULT.DEP_WIND_ONLY as DEP_WIND_ONLY,
exp_DEFAULT.o_DEP_EXCLG_WIND as o_DEP_EXCLG_WIND,
exp_DEFAULT.o_DEP_INCLG_WIND as o_DEP_INCLG_WIND,
exp_DEFAULT.WIND_EXCL_FCTR as WIND_EXCL_FCTR,
exp_DEFAULT.o_DLI_TOT as o_DLI_TOT,
exp_DEFAULT.DLI_WIND_ONLY as DLI_WIND_ONLY,
exp_DEFAULT.o_DLI_EXCLG_WIND as o_DLI_EXCLG_WIND,
exp_DEFAULT.o_DLI_INCLG_WIND as o_DLI_INCLG_WIND,
exp_DEFAULT.o_DLI_HURCN as o_DLI_HURCN,
exp_DEFAULT.o_DLI_WIND_CTSTRPH as o_DLI_WIND_CTSTRPH,
exp_DEFAULT.o_DLI_OTH_WIND as o_DLI_OTH_WIND,
exp_DEFAULT.o_DLI_WIND_SBTOT as o_DLI_WIND_SBTOT,
exp_DEFAULT.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
exp_DEFAULT.o_DLI_ALL_OTH as o_DLI_ALL_OTH,
exp_DEFAULT.o_ALAE_TOT as o_ALAE_TOT,
exp_DEFAULT.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
exp_DEFAULT.o_ALAE_EXCLG_WIND as o_ALAE_EXCLG_WIND,
exp_DEFAULT.o_ALAE_INCLG_WIND as o_ALAE_INCLG_WIND,
exp_DEFAULT.o_ALAE_HURCN as o_ALAE_HURCN,
exp_DEFAULT.o_ALAE_WIND_CTSTRPH as o_ALAE_WIND_CTSTRPH,
exp_DEFAULT.o_ALAE_OTH_WIND as o_ALAE_OTH_WIND,
exp_DEFAULT.o_ALAE_WIND_SBTOT as o_ALAE_WIND_SBTOT,
exp_DEFAULT.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
exp_DEFAULT.o_ALAE_ALL_OTH as o_ALAE_ALL_OTH,
exp_DEFAULT.o_EHY_TOT as o_EHY_TOT,
exp_DEFAULT.EHY_WIND_ONLY as EHY_WIND_ONLY,
exp_DEFAULT.o_EHY_EXCLG_WIND as o_EHY_EXCLG_WIND,
exp_DEFAULT.o_EHY_ALL_OTH as o_EHY_ALL_OTH,
exp_DEFAULT.o_DWL_CVGE_A_TOT as o_DWL_CVGE_A_TOT,
exp_DEFAULT.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
exp_DEFAULT.o_DWL_CVGE_A_EXCLG_WIND as o_DWL_CVGE_A_EXCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_A_INCLG_WIND as o_DWL_CVGE_A_INCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_C_TOT as o_DWL_CVGE_C_TOT,
exp_DEFAULT.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
exp_DEFAULT.o_DWL_CVGE_C_EXCLG_WIND as o_DWL_CVGE_C_EXCLG_WIND,
exp_DEFAULT.o_DWL_CVGE_C_INCLG_WIND as o_DWL_CVGE_C_INCLG_WIND,
exp_DEFAULT.COMTS as COMTS,
exp_DEFAULT.CO_CD1 as CO_CD1,
exp_DEFAULT.CO_CD2 as CO_CD2,
exp_DEFAULT.source_record_id
FROM
exp_DEFAULT
WHERE exp_DEFAULT.CO_CD2 = :CO_CD2 AND exp_DEFAULT.PULL_YR = :PULL_YR3;


-- Component FF_extract_file_co_cd1_yr1, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE FF_extract_file_co_cd1_yr1 AS
(
SELECT
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.NAIC_CD as NAIC_CD,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.CO_NAME as CO_NAME,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.PULL_YR as PULL_YR,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.ZIPCD as ZIPCD,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DPW_TOT as DPW_TOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.DPW_WIND_ONLY as DPW_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DPW_EXCLG_WIND as DPW_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DPW_INCLG_WIND as DPW_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DEP_TOT as DEP_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.DEP_WIND_ONLY as DEP_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DEP_EXCLG_WIND as DEP_EXCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DEP_INCLG_WIND as DEP_INCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.WIND_EXCL_FCTR as WIND_EXCL_FACTOR,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DLI_TOT as DLI_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.DLI_WIND_ONLY as DLI_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DLI_EXCLG_WIND as DLI_EXCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DLI_INCLG_WIND as DLI_INCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DLI_HURCN as DLI_HURCN,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DLI_WIND_CTSTRPH as DLI_WIND_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DLI_OTH_WIND as DLI_OTH_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DLI_WIND_SBTOT as DLI_WIND_SBTOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DLI_ALL_OTH as DLI_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_ALAE_TOT as ALAE_TOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_ALAE_EXCLG_WIND as ALAE_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_ALAE_INCLG_WIND as ALAE_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_ALAE_HURCN as ALAE_HURCN,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_ALAE_WIND_CTSTRPH as ALAE_WIND_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_ALAE_OTH_WIND as ALAE_OTH_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_ALAE_WIND_SBTOT as ALAE_WIND_SBTOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_ALAE_ALL_OTH as ALAE_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_EHY_TOT as EHY_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.EHY_WIND_ONLY as EHY_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_EHY_EXCLG_WIND as EHY_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_EHY_ALL_OTH as EHY_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DWL_CVGE_A_TOT as DWL_CVGE_A_TOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DWL_CVGE_A_EXCLG_WIND as DWL_CVGE_A_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DWL_CVGE_A_INCLG_WIND as DWL_CVGE_A_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DWL_CVGE_C_TOT as DWL_CVGE_C_TOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DWL_CVGE_C_EXCLG_WIND as DWL_CVGE_C_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.o_DWL_CVGE_C_INCLG_WIND as DWL_CVGE_C_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR1.COMTS as COMTS
FROM
rtr_CO_NAME_PULL_YR_CO_CD1_YR1
);


-- Component FF_extract_file_co_cd1_yr1, Type EXPORT_DATA Exporting data
copy into @edw_stage/Parameter/edw_base/ff_extract_file_co_cd1_yr1.txt
from 
(select *
from ff_extract_file_co_cd1_yr1)
file_format = ''CSV_FORMAT''
OVERWRITE = TRUE;



-- Component FF_extract_file_co_cd2_yr1, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE FF_extract_file_co_cd2_yr1 AS
(
SELECT
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.NAIC_CD as NAIC_CD,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.CO_NAME as CO_NAME,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.PULL_YR as PULL_YR,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.ZIPCD as ZIPCD,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DPW_TOT as DPW_TOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.DPW_WIND_ONLY as DPW_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DPW_EXCLG_WIND as DPW_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DPW_INCLG_WIND as DPW_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DEP_TOT as DEP_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.DEP_WIND_ONLY as DEP_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DEP_EXCLG_WIND as DEP_EXCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DEP_INCLG_WIND as DEP_INCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.WIND_EXCL_FCTR as WIND_EXCL_FACTOR,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DLI_TOT as DLI_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.DLI_WIND_ONLY as DLI_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DLI_EXCLG_WIND as DLI_EXCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DLI_INCLG_WIND as DLI_INCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DLI_HURCN as DLI_HURCN,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DLI_WIND_CTSTRPH as DLI_WIND_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DLI_OTH_WIND as DLI_OTH_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DLI_WIND_SBTOT as DLI_WIND_SBTOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DLI_ALL_OTH as DLI_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_ALAE_TOT as ALAE_TOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_ALAE_EXCLG_WIND as ALAE_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_ALAE_INCLG_WIND as ALAE_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_ALAE_HURCN as ALAE_HURCN,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_ALAE_WIND_CTSTRPH as ALAE_WIND_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_ALAE_OTH_WIND as ALAE_OTH_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_ALAE_WIND_SBTOT as ALAE_WIND_SBTOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_ALAE_ALL_OTH as ALAE_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_EHY_TOT as EHY_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.EHY_WIND_ONLY as EHY_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_EHY_EXCLG_WIND as EHY_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_EHY_ALL_OTH as EHY_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DWL_CVGE_A_TOT as DWL_CVGE_A_TOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DWL_CVGE_A_EXCLG_WIND as DWL_CVGE_A_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DWL_CVGE_A_INCLG_WIND as DWL_CVGE_A_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DWL_CVGE_C_TOT as DWL_CVGE_C_TOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DWL_CVGE_C_EXCLG_WIND as DWL_CVGE_C_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.o_DWL_CVGE_C_INCLG_WIND as DWL_CVGE_C_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR1.COMTS as COMTS
FROM
rtr_CO_NAME_PULL_YR_CO_CD2_YR1
);


-- Component FF_extract_file_co_cd2_yr1, Type EXPORT_DATA Exporting data
copy into @edw_stage/Parameter/edw_base/ff_extract_file_co_cd2_yr1.txt
from 
(select *
from ff_extract_file_co_cd2_yr1)
file_format = ''CSV_FORMAT''
OVERWRITE = TRUE;


-- Component FF_extract_file_co_cd1_yr3, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE FF_extract_file_co_cd1_yr3 AS
(
SELECT
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.NAIC_CD as NAIC_CD,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.CO_NAME as CO_NAME,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.PULL_YR as PULL_YR,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.ZIPCD as ZIPCD,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DPW_TOT as DPW_TOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.DPW_WIND_ONLY as DPW_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DPW_EXCLG_WIND as DPW_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DPW_INCLG_WIND as DPW_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DEP_TOT as DEP_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.DEP_WIND_ONLY as DEP_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DEP_EXCLG_WIND as DEP_EXCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DEP_INCLG_WIND as DEP_INCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.WIND_EXCL_FCTR as WIND_EXCL_FACTOR,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DLI_TOT as DLI_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.DLI_WIND_ONLY as DLI_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DLI_EXCLG_WIND as DLI_EXCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DLI_INCLG_WIND as DLI_INCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DLI_HURCN as DLI_HURCN,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DLI_WIND_CTSTRPH as DLI_WIND_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DLI_OTH_WIND as DLI_OTH_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DLI_WIND_SBTOT as DLI_WIND_SBTOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DLI_ALL_OTH as DLI_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_ALAE_TOT as ALAE_TOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_ALAE_EXCLG_WIND as ALAE_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_ALAE_INCLG_WIND as ALAE_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_ALAE_HURCN as ALAE_HURCN,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_ALAE_WIND_CTSTRPH as ALAE_WIND_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_ALAE_OTH_WIND as ALAE_OTH_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_ALAE_WIND_SBTOT as ALAE_WIND_SBTOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_ALAE_ALL_OTH as ALAE_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_EHY_TOT as EHY_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.EHY_WIND_ONLY as EHY_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_EHY_EXCLG_WIND as EHY_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_EHY_ALL_OTH as EHY_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DWL_CVGE_A_TOT as DWL_CVGE_A_TOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DWL_CVGE_A_EXCLG_WIND as DWL_CVGE_A_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DWL_CVGE_A_INCLG_WIND as DWL_CVGE_A_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DWL_CVGE_C_TOT as DWL_CVGE_C_TOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DWL_CVGE_C_EXCLG_WIND as DWL_CVGE_C_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.o_DWL_CVGE_C_INCLG_WIND as DWL_CVGE_C_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR3.COMTS as COMTS
FROM
rtr_CO_NAME_PULL_YR_CO_CD1_YR3
);


-- Component FF_extract_file_co_cd1_yr3, Type EXPORT_DATA Exporting data
copy into @edw_stage/Parameter/edw_base/ff_extract_file_co_cd1_yr3.txt
from 
(select *
from ff_extract_file_co_cd1_yr3)
file_format = ''CSV_FORMAT''
OVERWRITE = TRUE;


-- Component FF_extract_file_co_cd1_yr2, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE FF_extract_file_co_cd1_yr2 AS
(
SELECT
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.NAIC_CD as NAIC_CD,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.CO_NAME as CO_NAME,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.PULL_YR as PULL_YR,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.ZIPCD as ZIPCD,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DPW_TOT as DPW_TOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.DPW_WIND_ONLY as DPW_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DPW_EXCLG_WIND as DPW_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DPW_INCLG_WIND as DPW_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DEP_TOT as DEP_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.DEP_WIND_ONLY as DEP_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DEP_EXCLG_WIND as DEP_EXCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DEP_INCLG_WIND as DEP_INCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.WIND_EXCL_FCTR as WIND_EXCL_FACTOR,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DLI_TOT as DLI_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.DLI_WIND_ONLY as DLI_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DLI_EXCLG_WIND as DLI_EXCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DLI_INCLG_WIND as DLI_INCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DLI_HURCN as DLI_HURCN,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DLI_WIND_CTSTRPH as DLI_WIND_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DLI_OTH_WIND as DLI_OTH_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DLI_WIND_SBTOT as DLI_WIND_SBTOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DLI_ALL_OTH as DLI_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_ALAE_TOT as ALAE_TOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_ALAE_EXCLG_WIND as ALAE_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_ALAE_INCLG_WIND as ALAE_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_ALAE_HURCN as ALAE_HURCN,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_ALAE_WIND_CTSTRPH as ALAE_WIND_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_ALAE_OTH_WIND as ALAE_OTH_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_ALAE_WIND_SBTOT as ALAE_WIND_SBTOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_ALAE_ALL_OTH as ALAE_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_EHY_TOT as EHY_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.EHY_WIND_ONLY as EHY_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_EHY_EXCLG_WIND as EHY_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_EHY_ALL_OTH as EHY_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DWL_CVGE_A_TOT as DWL_CVGE_A_TOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DWL_CVGE_A_EXCLG_WIND as DWL_CVGE_A_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DWL_CVGE_A_INCLG_WIND as DWL_CVGE_A_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DWL_CVGE_C_TOT as DWL_CVGE_C_TOT,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DWL_CVGE_C_EXCLG_WIND as DWL_CVGE_C_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.o_DWL_CVGE_C_INCLG_WIND as DWL_CVGE_C_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD1_YR2.COMTS as COMTS
FROM
rtr_CO_NAME_PULL_YR_CO_CD1_YR2
);


-- Component FF_extract_file_co_cd1_yr2, Type EXPORT_DATA Exporting data
copy into @edw_stage/Parameter/edw_base/ff_extract_file_co_cd1_yr2.txt
from 
(select *
from ff_extract_file_co_cd1_yr2)
file_format = ''CSV_FORMAT''
OVERWRITE = TRUE;


-- Component FF_extract_file_co_cd2_yr3, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE FF_extract_file_co_cd2_yr3 AS
(
SELECT
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.NAIC_CD as NAIC_CD,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.CO_NAME as CO_NAME,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.PULL_YR as PULL_YR,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.ZIPCD as ZIPCD,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DPW_TOT as DPW_TOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.DPW_WIND_ONLY as DPW_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DPW_EXCLG_WIND as DPW_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DPW_INCLG_WIND as DPW_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DEP_TOT as DEP_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.DEP_WIND_ONLY as DEP_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DEP_EXCLG_WIND as DEP_EXCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DEP_INCLG_WIND as DEP_INCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.WIND_EXCL_FCTR as WIND_EXCL_FACTOR,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DLI_TOT as DLI_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.DLI_WIND_ONLY as DLI_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DLI_EXCLG_WIND as DLI_EXCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DLI_INCLG_WIND as DLI_INCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DLI_HURCN as DLI_HURCN,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DLI_WIND_CTSTRPH as DLI_WIND_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DLI_OTH_WIND as DLI_OTH_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DLI_WIND_SBTOT as DLI_WIND_SBTOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DLI_ALL_OTH as DLI_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_ALAE_TOT as ALAE_TOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_ALAE_EXCLG_WIND as ALAE_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_ALAE_INCLG_WIND as ALAE_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_ALAE_HURCN as ALAE_HURCN,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_ALAE_WIND_CTSTRPH as ALAE_WIND_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_ALAE_OTH_WIND as ALAE_OTH_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_ALAE_WIND_SBTOT as ALAE_WIND_SBTOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_ALAE_ALL_OTH as ALAE_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_EHY_TOT as EHY_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.EHY_WIND_ONLY as EHY_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_EHY_EXCLG_WIND as EHY_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_EHY_ALL_OTH as EHY_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DWL_CVGE_A_TOT as DWL_CVGE_A_TOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DWL_CVGE_A_EXCLG_WIND as DWL_CVGE_A_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DWL_CVGE_A_INCLG_WIND as DWL_CVGE_A_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DWL_CVGE_C_TOT as DWL_CVGE_C_TOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DWL_CVGE_C_EXCLG_WIND as DWL_CVGE_C_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.o_DWL_CVGE_C_INCLG_WIND as DWL_CVGE_C_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR3.COMTS as COMTS
FROM
rtr_CO_NAME_PULL_YR_CO_CD2_YR3
);


-- Component FF_extract_file_co_cd2_yr3, Type EXPORT_DATA Exporting data
copy into @edw_stage/Parameter/edw_base/ff_extract_file_co_cd2_yr3.txt
from 
(select *
from ff_extract_file_co_cd2_yr3)
file_format = ''CSV_FORMAT''
OVERWRITE = TRUE;


-- Component FF_extract_file_co_cd2_yr2, Type TARGET_EXPORT_PREPARE Stage data before exporting
CREATE OR REPLACE TEMPORARY TABLE FF_extract_file_co_cd2_yr2 AS
(
SELECT
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.NAIC_CD as NAIC_CD,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.CO_NAME as CO_NAME,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.PULL_YR as PULL_YR,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.ZIPCD as ZIPCD,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DPW_TOT as DPW_TOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.DPW_WIND_ONLY as DPW_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DPW_EXCLG_WIND as DPW_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DPW_INCLG_WIND as DPW_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DEP_TOT as DEP_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.DEP_WIND_ONLY as DEP_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DEP_EXCLG_WIND as DEP_EXCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DEP_INCLG_WIND as DEP_INCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.WIND_EXCL_FCTR as WIND_EXCL_FACTOR,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DLI_TOT as DLI_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.DLI_WIND_ONLY as DLI_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DLI_EXCLG_WIND as DLI_EXCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DLI_INCLG_WIND as DLI_INCL_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DLI_HURCN as DLI_HURCN,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DLI_WIND_CTSTRPH as DLI_WIND_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DLI_OTH_WIND as DLI_OTH_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DLI_WIND_SBTOT as DLI_WIND_SBTOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DLI_ALL_OTH as DLI_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_ALAE_TOT as ALAE_TOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_ALAE_EXCLG_WIND as ALAE_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_ALAE_INCLG_WIND as ALAE_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_ALAE_HURCN as ALAE_HURCN,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_ALAE_WIND_CTSTRPH as ALAE_WIND_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_ALAE_OTH_WIND as ALAE_OTH_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_ALAE_WIND_SBTOT as ALAE_WIND_SBTOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_ALAE_ALL_OTH as ALAE_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_EHY_TOT as EHY_TOTAL,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.EHY_WIND_ONLY as EHY_WIND_ONLY,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_EHY_EXCLG_WIND as EHY_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_EHY_ALL_OTH as EHY_ALL_OTH,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DWL_CVGE_A_TOT as DWL_CVGE_A_TOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.DWL_CVGE_A_WO as DWL_CVGE_A_WO,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DWL_CVGE_A_EXCLG_WIND as DWL_CVGE_A_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DWL_CVGE_A_INCLG_WIND as DWL_CVGE_A_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DWL_CVGE_C_TOT as DWL_CVGE_C_TOT,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.DWL_CVGE_C_WO as DWL_CVGE_C_WO,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DWL_CVGE_C_EXCLG_WIND as DWL_CVGE_C_EXCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.o_DWL_CVGE_C_INCLG_WIND as DWL_CVGE_C_INCLG_WIND,
rtr_CO_NAME_PULL_YR_CO_CD2_YR2.COMTS as COMTS
FROM
rtr_CO_NAME_PULL_YR_CO_CD2_YR2
);


-- Component FF_extract_file_co_cd2_yr2, Type EXPORT_DATA Exporting data
copy into @edw_stage/Parameter/edw_base/ff_extract_file_co_cd2_yr2.txt
from 
(select *
from ff_extract_file_co_cd2_yr2)
file_format = ''CSV_FORMAT''
OVERWRITE = TRUE;


END; ';