-- Object Type: PROCEDURES
CREATE OR REPLACE PROCEDURE ALFA_EDW_DEV.PUBLIC.M_BASE_MS_CLARITY_EXTRACT_GW("WORKLET_NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS ' DECLARE
  PRCS_ID STRING;
  YR_END_DT STRING;
  YR_STRT_DT STRING;
  run_id STRING;

BEGIN
run_id :=   (SELECT run_id   FROM control_run_id where upper(worklet_name) = upper(:worklet_name) order by insert_ts desc limit 1);   
PRCS_ID:=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''PRCS_ID'' order by insert_ts desc limit 1);
YR_STRT_DT :=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''YR_STRT_DT'' order by insert_ts desc limit 1);
YR_END_DT :=   (SELECT param_value FROM control_params where run_id = :run_id and upper(param_name)=''YR_END_DT'' order by insert_ts desc limit 1);


-- Component MS_CLRTY_XTRCT_GW, Type Pre SQL 
DELETE from  db_t_prod_wrk.MS_CLRTY_XTRCT  WHERE PULL_YR between extract(year from to_date( :YR_STRT_DT , ''mm/dd/yyyy''))
and extract(year from to_date ( :YR_END_DT , ''mm/dd/yyyy'')) AND ROW_TYPE_CD=''GW'';


-- Component sq_MS_CLRTY_XTRCT, Type SOURCE 
CREATE OR REPLACE TEMPORARY TABLE sq_MS_CLRTY_XTRCT AS
(
SELECT /* adding column aliases to ensure proper downstream column references */
$1 as NAIC_CD,
$2 as CO_NAME,
$3 as PULL_YR,
$4 as ZIPCD,
$5 as DPW_TOT,
$6 as DPW_WIND_ONLY,
$7 as DPW_EXCLG_WIND,
$8 as DPW_INCLG_WIND,
$9 as DEP_TOT,
$10 as DEP_WIND_ONLY,
$11 as DEP_EXCLG_WIND,
$12 as DEP_INCLG_WIND,
$13 as WIND_EXCL_FCTR,
$14 as DLI_TOT,
$15 as DLI_WIND_ONLY,
$16 as DLI_EXCLG_WIND,
$17 as DLI_INCLG_WIND,
$18 as DLI_HURCN,
$19 as DLI_WIND_CTSTRPH,
$20 as DLI_OTH_WIND,
$21 as DLI_WIND_SBTOT,
$22 as DLI_OTH_CTSTRPH,
$23 as DLI_ALL_OTH,
$24 as ALAE_TOT,
$25 as ALAE_WIND_ONLY,
$26 as ALAE_EXCLG_WIND,
$27 as ALAE_INCLG_WIND,
$28 as ALAE_HURCN,
$29 as ALAE_WIND_CTSTRPH,
$30 as ALAE_OTH_WIND,
$31 as ALAE_WIND_SBTOT,
$32 as ALAE_OTH_CTSTRPH,
$33 as ALAE_ALL_OTH,
$34 as EHY_TOT,
$35 as EHY_WIND_ONLY,
$36 as EHY_EXCLG_WIND,
$37 as EHY_ALL_OTH,
$38 as DWL_CVGE_A_TOT,
$39 as DWL_CVGE_A_WO,
$40 as DWL_CVGE_A_EXCLG_WIND,
$41 as DWL_CVGE_A_INCLG_WIND,
$42 as DWL_CVGE_C_TOT,
$43 as DWL_CVGE_C_WO,
$44 as DWL_CVGE_C_EXCLG_WIND,
$45 as DWL_CVGE_C_INCLG_WIND,
$46 as COMTS,
$47 as source_record_id
FROM (
SELECT SRC.*, row_number() over (order by 1) AS source_record_id FROM (
SELECT 

NAIC_CODE,/* 1 */
CMPY_NAME,/* 2 */
PULL_YEAR PULL_YEAR,/* 3 */
/* HOST_AGMT_NUM, */
COALESCE(CAST(TRIM(ZIPCODE) AS VARCHAR(10)) ,''NA'')ZIPCODE,/* 4 */
SUM(COALESCE(CAST(DPW_TOTAL AS DECIMAL(12,2)),0)) DPW_TOTAL,/* 5 */
MAX(DPW_WIND_ONLY) DPW_WIND_ONLY,/* 6 */
SUM(COALESCE(CAST(DPW_EXCL_WIND AS DECIMAL(12,2)),0)) DPW_EXCL_WIND,/* 7 */
SUM(COALESCE(CAST(DPW_INCL_WIND AS DECIMAL(12,2)),0)) DPW_INCL_WIND,

SUM(COALESCE(CAST(DEP_TOTAL AS DECIMAL(12,2)),0)) DEP_TOTAL,

MAX(DEP_WIND_ONLY) DEP_WIND_ONLY,

SUM(COALESCE(CAST(DEP_EXCL_WIND AS DECIMAL(12,2)),0)) DEP_EXCL_WIND,

SUM(COALESCE(CAST(DEP_INCL_WIND AS DECIMAL(12,2)),0)) DEP_INCL_WIND,

(WIND_EXCL_FACTOR) WIND_EXCL_FACTOR,

SUM(COALESCE(CAST(DLI_TOTAL AS DECIMAL(12,2)),0)) DLI_TOTAL,

MAX(DLI_WIND_ONLY) DLI_WIND_ONLY,

SUM(COALESCE(CAST(DLI_EXCL_WIND AS DECIMAL(12,2)),0)) DLI_EXCL_WIND,

SUM(COALESCE(CAST(DLI_INCL_WIND AS DECIMAL(12,2)),0)) DLI_INCL_WIND,

SUM(COALESCE(CAST(DLI_HURR AS DECIMAL(12,2)),0)) DLI_HURR,/* 18 */
SUM(COALESCE(CAST(DLI_NON_NAMED AS DECIMAL(12,2)),0)) DLI_NON_NAMED,

SUM(COALESCE(CAST(DLI_OTHER_WIND AS DECIMAL(12,2)),0) ) DLI_OTHER_WIND,

SUM(COALESCE(CAST(DLI_SUBTOTAL AS DECIMAL(12,2)),0)) DLI_SUBTOTAL,

SUM(COALESCE(CAST(DLI_OTHER_NON_NAMED AS DECIMAL(12,2)),0)) DLI_OTHER_NON_NAMED,

SUM(COALESCE(CAST(DLI_ALL_OTHER_PERIL AS DECIMAL(12,2)),0)) DLI_ALL_OTHER_PERIL,

SUM(COALESCE(CAST(ALAE_TOTAL AS DECIMAL(12,2)),0)) ALAE_TOTAL,

MAX(ALAE_WIND_ONLY) ALAE_WIND_ONLY,

SUM(COALESCE(CAST(ALAE_EXCL_WIND AS DECIMAL(12,2)),0)) ALAE_EXCL_WIND,

SUM(COALESCE(CAST(ALAE_INCL_WIND AS DECIMAL(12,2)),0)) ALAE_INCL_WIND,

SUM(COALESCE(CAST(ALAE_HURR AS DECIMAL(12,2)),0)) ALAE_HURR,

SUM(COALESCE(CAST(ALAE_NON_NAMED AS DECIMAL(12,2)),0)) ALAE_NON_NAMED,

SUM(COALESCE(CAST(ALAE_OTHER_WIND AS DECIMAL(12,2)),0)) ALAE_OTHER_WIND,

SUM(COALESCE(CAST(ALAE_SUBTOTAL AS DECIMAL(12,2)),0)) ALAE_SUBTOTAL,

SUM(COALESCE(CAST(ALAE_OTHER_NON_NAMED AS DECIMAL(12,2)),0)) ALAE_OTHER_NON_NAMED,

SUM(COALESCE(CAST(ALAE_ALL_OTHER_PERIL AS DECIMAL(12,2)),0)) ALAE_ALL_OTHER_PERIL,

 SUM(COALESCE(cast(EHY_TOTAL as decimal(12,2)) ,0)) EHY_TOTAL,

MAX(EHY_WIND_ONLY) EHY_WIND_ONLY, /* 34 */
SUM(COALESCE(cast(EHY_EXCL_WIND as decimal(12,2)) ,0)) EHY_EXCL_WIND,

SUM(COALESCE(cast(EHY_INCL_WIND as decimal(12,2)) ,0)) EHY_INCL_WIND,

SUM(COALESCE(CAST(DWL_COVA_TOT AS DECIMAL(12,2)),0)) DWL_COVA_TOT,

MAX(DWL_COVA_WO) DWL_COVA_WO,

SUM(COALESCE(CAST(DWL_COVA_EXCL_WIND AS DECIMAL(12,2)),0)) DWL_COVA_EXCL_WIND,

SUM(COALESCE(CAST(DWL_COVA_INCL_WIND AS DECIMAL(12,2)),0)) DWL_COVA_INCL_WIND,

SUM(COALESCE(CAST(DWL_COVC_TOT AS DECIMAL(12,2)),0)) DWL_COVC_TOT,

MAX(DWL_COVC_WO)DWL_COVC_WO,

SUM(COALESCE(CAST(DWL_COVC_EXCL_WIND AS DECIMAL(12,2)),0)) DWL_COVC_EXCL_WIND,

SUM(COALESCE(CAST(DWL_COVC_INCL_WIND AS DECIMAL(12,2)),0))DWL_COVC_INCL_WIND,

(COMMENTS) COMMENTS

FROM (

SELECT HOST_AGMT_NUM,/* 1 */
CASE WHEN COMPANY.COMPANY=''AIC'' THEN ''22330'' WHEN COMPANY.COMPANY=''AGI'' THEN ''41661'' END AS NAIC_CODE,

CASE WHEN COMPANY.COMPANY=''AIC'' THEN ''ALFA INS CORP'' WHEN COMPANY.COMPANY=''AGI'' THEN ''ALFA GEN INS CORP'' END AS CMPY_NAME,

(POLICY.AGMT_MONTH/100) AS PULL_YEAR,

/*PULL ZIP_CODE FROM MS CLARITY ZIP CODE TABLE. IF MISSING GET FROM GW TABLE*/

COALESCE(MS_CLARITY_ZIP.ZIPCODE, 0) ZIPCODE, /* 5 */
 sum(COALESCE(DWP_EPM.WRITTEN_AMT,0)) AS DPW_TOTAL,

''NAV'' AS DPW_WIND_ONLY,/* 7 */
SUM(CASE WHEN WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT=1 THEN COALESCE( DWP_EPM.WRITTEN_AMT,0) ELSE 0 END) AS DPW_EXCL_WIND,

SUM(CASE WHEN COALESCE(WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT,0)<>1 THEN COALESCE( DWP_EPM.WRITTEN_AMT,0) ELSE 0 END )AS DPW_INCL_WIND,

SUM(COALESCE(DWP_EPM.EARNED_AMT,0)) AS DEP_TOTAL,

''NAV'' AS DEP_WIND_ONLY,/* 11 */
SUM(CASE WHEN WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT=1 THEN DWP_EPM.EARNED_AMT ELSE 0 END) AS DEP_EXCL_WIND,

SUM(CASE WHEN COALESCE(WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT,0)<>1 THEN DWP_EPM.EARNED_AMT ELSE 0 END) AS DEP_INCL_WIND,

(CASE  WHEN MS_CLARITY_ZIP.ZIPCODE IS  NULL THEN ''NA''

WHEN WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT=1 AND ZIP_COUNTY.COUNTY IN (''GEORGE'',''HANCOCK'',''HARRISON'',''JACKSON'',''PEARL RIVER'',''STONE'')  

THEN ''OTH'' ELSE ''NA'' END) AS WIND_EXCL_FACTOR,

SUM(COALESCE(DLI.DLI_TOTAL,0) ) AS DLI_TOTAL,

''NAV'' AS DLI_WIND_ONLY,/* 16 */
SUM(CASE WHEN WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT=1 THEN DLI.DLI_TOTAL ELSE 0 END) AS DLI_EXCL_WIND,

SUM(CASE WHEN COALESCE(WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT,0)<>1 THEN DLI.DLI_TOTAL ELSE 0 END) AS DLI_INCL_WIND,

SUM(DLI.DLI_HURR) DLI_HURR,

SUM(DLI.DLI_NON_NAMED)DLI_NON_NAMED,

SUM(DLI.DLI_OTHER_WIND)DLI_OTHER_WIND,

SUM(DLI.DLI_SUBTOTAL)DLI_SUBTOTAL,

SUM(DLI.DLI_OTHER_NON_NAMED) DLI_OTHER_NON_NAMED,

SUM(DLI.DLI_ALL_OTHER_PERIL) DLI_ALL_OTHER_PERIL,

SUM(COALESCE(ALAE.ALAE_TOTAL,0) )AS ALAE_TOTAL,

''NAV'' AS ALAE_WIND_ONLY,

SUM(CASE WHEN WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT=1 THEN ALAE.ALAE_TOTAL ELSE 0 END ) AS ALAE_EXCL_WIND,

SUM(CASE WHEN COALESCE(WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT,0)<>1 THEN ALAE.ALAE_TOTAL ELSE 0 END )AS ALAE_INCL_WIND,

SUM(ALAE.ALAE_HURR)ALAE_HURR,

SUM(ALAE.ALAE_NON_NAMED)ALAE_NON_NAMED,

SUM(ALAE.ALAE_OTHER_WIND)ALAE_OTHER_WIND,

SUM(ALAE.ALAE_SUBTOTAL)ALAE_SUBTOTAL,

SUM(ALAE.ALAE_OTHER_NON_NAMED)ALAE_OTHER_NON_NAMED,

SUM(ALAE.ALAE_ALL_OTHER_PERIL)ALAE_ALL_OTHER_PERIL,

SUM(CAST(NO_OF_UNITS.NO_OF_UNITS AS DECIMAL(20, 16))) AS EHY_TOTAL,

''NAV'' AS EHY_WIND_ONLY,

SUM(CASE WHEN WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT=1 THEN NO_OF_UNITS.NO_OF_UNITS ELSE 0 END) AS EHY_EXCL_WIND,

SUM(CASE WHEN COALESCE(WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT,0)<>1 THEN NO_OF_UNITS.NO_OF_UNITS ELSE 0 END) AS EHY_INCL_WIND,

CASE WHEN (SUM(DWP_EPM.WRITTEN_AMT)<>0 OR SUM(DWP_EPM.EARNED_AMT)<>0) THEN (MAX(COALESCE(DW_LIMIT.AMT,0) )) ELSE 0 END  AS DWL_COVA_TOT,

''NAV'' AS DWL_COVA_WO,

CASE WHEN (SUM(DWP_EPM.WRITTEN_AMT)<>0 OR SUM(DWP_EPM.EARNED_AMT)<>0) THEN 

(CASE WHEN MAX(WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT)=1 THEN MAX(DW_LIMIT.AMT) ELSE 0 END) 

ELSE 0 END AS DWL_COVA_EXCL_WIND,

CASE WHEN (SUM(DWP_EPM.WRITTEN_AMT)<>0 OR SUM(DWP_EPM.EARNED_AMT)<>0) THEN 

(CASE WHEN (COALESCE(MAX(WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT),0)<>1) THEN MAX(DW_LIMIT.AMT) ELSE 0 END) ELSE 0 END  AS DWL_COVA_INCL_WIND,

CASE WHEN (SUM(DWP_EPM.WRITTEN_AMT)<>0 OR SUM(DWP_EPM.EARNED_AMT)<>0) then MAX(COALESCE(CNT_LIMIT.AMT,0) ) else 0 end AS DWL_COVC_TOT,

''NAV'' AS DWL_COVC_WO,

CASE WHEN (SUM(DWP_EPM.WRITTEN_AMT)<>0 OR SUM(DWP_EPM.EARNED_AMT)<>0) THEN 

(CASE WHEN MAX(WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT)=1 THEN MAX( CNT_LIMIT.AMT) ELSE 0 END) ELSE 0 END AS DWL_COVC_EXCL_WIND,

CASE WHEN (SUM(DWP_EPM.WRITTEN_AMT)<>0 OR SUM(DWP_EPM.EARNED_AMT)<>0) THEN 

(CASE WHEN COALESCE(MAX(WIND_HAIL_EXCLUSION.AGMT_FEAT_AMT),0)<>1 THEN MAX(CNT_LIMIT.AMT) ELSE 0 END) ELSE 0 END  AS DWL_COVC_INCL_WIND,

CASE WHEN MS_CLARITY_ZIP.ZIPCODE IS NULL THEN ''FLD A4:LOCATION ZIP CODE NOT AVAILABLE'' 

WHEN WIND_EXCL_FACTOR=''OTH'' THEN ''FLD D13:WIND EXCL FACTOR FOR FIRE POLICIES 0.60, FOR   HOME: 0.58, FOR MH POLICIES: 0.70.'' 

ELSE ''NA'' END  COMMENTS

 FROM 

  /* POLICY LEVEL INFORMATION FROM AGMT TABLE. AS AGM_ID WAS MISSING FOR FEW MONTHS JOINED WITH CALENDAR TABLE AND POPULATED  ALL MONTHS FOR AGMT_ID*/

 (SELECT DISTINCT AGMT_ID,   EXTRACT(YEAR FROM CALENDAR_DATE)*100+EXTRACT(MONTH FROM CALENDAR_DATE) AGMT_MONTH,HOST_AGMT_NUM 
  FROM 
  (SELECT A.HOST_AGMT_NUM,A.AGMT_ID,A.TERM_NUM,A.MODL_NUM,

  CAST(MODL_EFF_DTTM AS DATE) PLCY_MODL_EFF_DT, CAST(MODL_ACTL_END_DTTM AS DATE) PLCY_MODL_EXP_DT, A.TRANS_STRT_DTTM

 ,A.AGMT_EFF_DTTM , A.AGMT_PLND_EXPN_DTTM 
 FROM --EVIEWDB_EDW.AGMT 
 db_t_prod_core.AGMT A

 WHERE A.AGMT_TYPE_CD=''PPV'' AND A.SRC_SYS_CD=''GWPC'' AND CAST(A.EDW_END_DTTM AS DATE)=''9999-12-31'') A
  

 -- WHERE AGMT_TYPE_CD=''PPV'' AND SRC_SYS_CD=''GWPC'' AND CAST(EDW_END_DTTM AS DATE)=''9999-12-31'')  A

 JOIN --SYS_CALENDAR.CALENDAR 
 public.SYS_CALENDAR 
 ON CALENDAR_DATE BETWEEN to_date(:YR_STRT_DT , ''MM/DD/YYYY'')   AND to_date(:YR_END_DT ,''MM/DD/YYYY'')  )POLICY

 /*LOB. APPLIED LOB FILTER IN THIS SUB QUERY */

 JOIN (

SELECT DISTINCT AGMT_ID,PRD.PROD_NAME POL_DESC,PRD.INSRNC_LOB_TYPE_CD 
FROM  
--EVIEWDB_EDW.AGMT_PROD APRD
    db_t_prod_core.AGMT_PROD APRD

JOIN  --EVIEWDB_EDW.PROD PRD 
    db_t_prod_core.PROD PRD
ON APRD.PROD_ID = PRD.PROD_ID

AND PRD.INSRNC_LOB_TYPE_CD IN (''HO'',''MH'',''SF'')

) LOB ON LOB.AGMT_ID =POLICY.AGMT_ID

/* ZIP CODE. APPLIED STATE FILTER IN THIS SUB QUERY*/

 JOIN (SELECT PAL.AGMT_ID

,MIN(PAL.PRTY_ASSET_ID) PRTY_ASSET_ID /* IF THERE IS TWO PRTY_ASSET_ID, PICKING THE FIRST PRTY_ASSET_ID''S COUNTY INFORMATION*/

,MAX(CASE WHEN PAL.PRTY_ASSET_LOCTR_ROLE_CD=''RSKPC'' THEN  

CAST((CASE WHEN (POSITION(''-'' IN PC.POSTL_CD_NUM )>1) THEN  /*GW  TABLE  HAS ''-''  IN ZIP_CODE VALUE. REMOVING THE CHARACTERS FROM ''-''*AND PICKING THE FIRST PART OF ZIP CODE*/

SUBSTR(PC.POSTL_CD_NUM,0,(POSITION(''-'' IN PC.POSTL_CD_NUM ))) ELSE  PC.POSTL_CD_NUM END ) AS VARCHAR(50)) ELSE NULL END) AS POSTL_CD_NUM

,MAX(CASE WHEN PAL.PRTY_ASSET_LOCTR_ROLE_CD=''RSKST'' THEN TR.GEOGRCL_AREA_NAME ELSE NULL END) AS STATE

,MAX(CASE WHEN PAL.PRTY_ASSET_LOCTR_ROLE_CD IN (''RSKCNTY'') THEN CN.GEOGRCL_AREA_NAME ELSE NULL END) AS COUNTY

FROM (

SELECT AA.AGMT_ID

,PAL.PRTY_ASSET_ID

,LOC_ID

,PAL.PRTY_ASSET_LOCTR_ROLE_CD 
FROM  --EVIEWDB_EDW.AGMT_ASSET 
db_t_prod_core.AGMT_ASSET AA

INNER JOIN  --EVIEWDB_EDW.PRTY_ASSET_LOCTR PAL 
db_t_prod_core.PRTY_ASSET_LOCTR PAL 
ON AA.PRTY_ASSET_ID = PAL.PRTY_ASSET_ID

WHERE PRTY_ASSET_LOCTR_ROLE_CD IN (''RSKPC'',''RSKCNTY'',''RSKST'')

QUALIFY ROW_NUMBER() OVER (PARTITION BY AA.AGMT_ID,PAL.PRTY_ASSET_ID,PAL.PRTY_ASSET_LOCTR_ROLE_CD ORDER BY AA.EDW_END_DTTM DESC,PAL.EDW_END_DTTM DESC) = 1

) PAL

LEFT JOIN  --EVIEWDB_EDW.POSTL_CD PC 
db_t_prod_core.POSTL_CD PC
ON PAL.LOC_ID = PC.POSTL_CD_ID AND CAST(PC.EDW_END_DTTM AS DATE) = ''9999-12-31''

LEFT JOIN --EVIEWDB_EDW.TERR TR 
db_t_prod_core.TERR TR
ON PAL.LOC_ID=TR.TERR_ID AND CAST(TR.EDW_END_DTTM AS DATE) = ''9999-12-31''

LEFT JOIN  --EVIEWDB_EDW.CNTY CN 
db_t_prod_core.CNTY CN
ON PAL.LOC_ID = CN.CNTY_ID AND CAST(CN.EDW_END_DTTM AS DATE) = ''9999-12-31''

GROUP BY PAL.AGMT_ID HAVING STATE =''MISSISSIPPI''

) ZIP_COUNTY ON  POLICY.AGMT_ID = ZIP_COUNTY.AGMT_ID

/*UW COMPANY CODE AND NAIC CODE*/

JOIN (

SELECT PA.AGMT_ID,INTRNL_ORG_NUM COMPANY,PRTY_AGMT_ROLE_CD

FROM  --EVIEWDB_EDW.PRTY_AGMT PA
db_t_prod_core.PRTY_AGMT PA
JOIN  --EVIEWDB_EDW.INTRNL_ORG IO 
db_t_prod_core.INTRNL_ORG IO ON PA.PRTY_ID = IO.INTRNL_ORG_PRTY_ID AND CAST(IO.EDW_END_DTTM AS DATE) = ''9999-12-31''

WHERE PA.PRTY_AGMT_ROLE_CD = ''CMP'' AND INTRNL_ORG_SBTYPE_CD = ''CO'' AND INTRNL_ORG_NUM IN (''AGI'',''AIC'') AND CAST(PA.EDW_END_DTTM AS DATE) = ''9999-12-31''

) COMPANY ON  POLICY.AGMT_ID = COMPANY.AGMT_ID

 /*DIRECT WRITTEN PREMIUM_EARNED PREMIUM*/

LEFT JOIN (SELECT DISTINCT EXTRACT(YEAR FROM PLCY_MTRC_STRT_DTTM)*100+EXTRACT(MONTH FROM PLCY_MTRC_STRT_DTTM) MTRC_MONTH,AGMT_ID,

SUM(WRITTEN_AMT) WRITTEN_AMT,SUM(EARNED_AMT)EARNED_AMT  FROM (

SELECT AGMT_ID, PLCY_MTRC_STRT_DTTM,SUM(WRITEN_AMT) WRITTEN_AMT,SUM(EARNED_AMT) EARNED_AMT FROM (

SELECT COALESCE( CURR_WRIT.AGMT_ID,CURR_UNEAR.AGMT_ID, PREV.AGMT_ID) AGMT_ID,

COALESCE( CAST(CURR_WRIT.PLCY_MTRC_STRT_DTTM AS DATE) ,  CAST(CURR_UNEAR.PLCY_MTRC_STRT_DTTM AS DATE) , ADD_MONTHS(CAST(PREV.PLCY_MTRC_STRT_DTTM AS DATE),1))  PLCY_MTRC_STRT_DTTM, 

COALESCE(CASE WHEN (CURR_WRIT.INSRNC_MTRC_TYPE_CD =''GLTRANPREM'') THEN (CURR_WRIT.PLCY_AMT) ELSE 0 END,0) WRITEN_AMT,

COALESCE(CASE WHEN (CURR_WRIT.INSRNC_MTRC_TYPE_CD =''GLTRANPREM'') THEN (CURR_WRIT.PLCY_AMT) ELSE 0 END,0) -COALESCE(CASE WHEN (CURR_UNEAR.INSRNC_MTRC_TYPE_CD =''GLUNERNPREM'') THEN (CURR_UNEAR.PLCY_AMT) ELSE 0 END,0)

+COALESCE(CASE WHEN (PREV.INSRNC_MTRC_TYPE_CD =''GLUNERNPREM'') THEN (PREV.PLCY_AMT) ELSE 0 END,0) EARNED_AMT

FROM (SELECT DISTINCT AGMT_ID, PLCY_MTRC_STRT_DTTM, PLCY_AMT , INSRNC_MTRC_TYPE_CD  
FROM  --EVIEWDB_EDW.PLCY_MTRC 
db_t_prod_core.PLCY_MTRC
WHERE INSRNC_MTRC_TYPE_CD IN (''GLTRANPREM'')) CURR_WRIT

FULL JOIN

(SELECT DISTINCT AGMT_ID, PLCY_MTRC_STRT_DTTM, PLCY_AMT , INSRNC_MTRC_TYPE_CD  
FROM  --EVIEWDB_EDW.PLCY_MTRC 
db_t_prod_core.PLCY_MTRC
WHERE INSRNC_MTRC_TYPE_CD IN (''GLUNERNPREM'')) CURR_UNEAR 

ON CURR_WRIT.AGMT_ID=CURR_UNEAR.AGMT_ID AND CURR_WRIT.PLCY_MTRC_STRT_DTTM=CURR_UNEAR.PLCY_MTRC_STRT_DTTM

FULL JOIN 

(SELECT  DISTINCT AGMT_ID, PLCY_MTRC_STRT_DTTM, PLCY_AMT , INSRNC_MTRC_TYPE_CD  
FROM  --EVIEWDB_EDW.PLCY_MTRC 
db_t_prod_core.PLCY_MTRC
WHERE   INSRNC_MTRC_TYPE_CD IN (''GLUNERNPREM'')) PREV

ON CURR_WRIT.AGMT_ID=PREV.AGMT_ID

AND CAST(PREV.PLCY_MTRC_STRT_DTTM AS DATE)=ADD_MONTHS(CAST(CURR_WRIT.PLCY_MTRC_STRT_DTTM AS DATE),-1)   )A GROUP BY 1,2)B GROUP BY 1,2

)DWP_EPM ON DWP_EPM.AGMT_ID=POLICY.AGMT_ID AND MTRC_MONTH =POLICY.AGMT_MONTH

/* WIND HAIL INCLUSION & EXCLUSION*/

LEFT JOIN (

SELECT DISTINCT AGMT_ID ,AGMT_FEAT_AMT

FROM  --EVIEWDB_EDW.AGMT_FEAT AF 
db_t_prod_core.AGMT_FEAT AF
INNER JOIN  --EVIEWDB_EDW.FEAT F ON AF.FEAT_ID = F.FEAT_ID
db_t_prod_core.FEAT F ON AF.FEAT_ID = F.FEAT_ID

WHERE F.FEAT_NAME = ''IS WIND, WINDSTORM AND HAIL EXCLUDED?'' AND F.FEAT_COVERABLE_TYPE_TXT = ''DWELLING_HOE''

AND FEAT_SBTYPE_CD = ''TERM'' AND CAST(AF.EDW_END_DTTM AS DATE) = ''9999-12-31''

) WIND_HAIL_EXCLUSION ON  POLICY.AGMT_ID = WIND_HAIL_EXCLUSION.AGMT_ID

/*DLI_TOTAL*/

/* THIS CALUCLATION IS PROVIDED BY CLIENT . REFER FROM TICKET EIM-15160*/

LEFT  OUTER JOIN (SELECT AGMT_ID,MONTH_ID, SUM(DLI_AMT) DLI_TOTAL,

 SUM(CASE WHEN( ISO_IND =''Y'' AND NAMED_STROM =''Y''  ) THEN DLI_AMT ELSE 0 END ) DLI_HURR,

 SUM(CASE WHEN( ISO_IND =''Y'' AND NAMED_STROM =''N'' AND WIND =''NON- NAMED WIND CATASTROPHE'' ) THEN DLI_AMT ELSE 0 END ) DLI_NON_NAMED,

 SUM(CASE WHEN( ISO_IND =''N'' AND NAMED_STROM =''N''  AND WIND =''OTHER WIND'') THEN DLI_AMT ELSE 0 END ) DLI_OTHER_WIND,

 DLI_HURR+DLI_NON_NAMED+DLI_OTHER_WIND DLI_SUBTOTAL,

 SUM(CASE WHEN( ISO_IND =''Y'' AND NAMED_STROM =''N''  AND WIND  NOT   IN (''NON- NAMED WIND CATASTROPHE'',''OTHER WIND'')) THEN DLI_AMT ELSE 0 END ) DLI_OTHER_NON_NAMED,

 SUM(CASE WHEN( ISO_IND IS NULL ) THEN DLI_AMT ELSE 0 END ) DLI_ALL_OTHER_PERIL

 FROM (

SELECT

CLM_EXPSR_ID,EXTRACT(YEAR FROM CLM_EXPSR_TRANS_STRT_DTTM)*100+EXTRACT(MONTH FROM CLM_EXPSR_TRANS_STRT_DTTM) MONTH_ID,

/*CLM_DA_0541*//*EIM-46303*/

SUM (CASE WHEN (CET.CLM_EXPSR_TRANS_SBTYPE_CD = ''PYMNT'' AND CET.EXPSR_COST_TYPE_CD IN (''PDL'') AND  CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')  

AND CET.DOES_NOT_ERODE_RSERV_IND=''F''  AND  CETL.LNITM_CTGY_TYPE_CD IN (  ''LOSS'',''DED'',''DEDRFND'',''FRMRDED'',''DMNSHDVAL'') ) THEN (CETL.CLM_EXPSR_LNITM_AMT)  ELSE 0 END  )  AS LOSS_PMT_ERODING_AMT,

(SUM (CASE WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD=''RESRV'' ) AND  CET.EXPSR_COST_TYPE_CD=''PDL''  AND  CET.EXPSR_COST_CTGY_TYPE_CD =''LOSS''   

THEN (CETL.CLM_EXPSR_LNITM_AMT) ELSE 0 END  ) )- (LOSS_PMT_ERODING_AMT) AS RSERV_AMT ,

/*CLM_DA_0547*/

(SUM(CASE WHEN (CET.CLM_EXPSR_TRANS_SBTYPE_CD =''PYMNT'' AND  CET.EXPSR_COST_TYPE_CD =''EXPNS''   AND  CET.EXPSR_COST_CTGY_TYPE_CD=''EXPNS'' 

AND  CETL.LNITM_CTGY_TYPE_CD=''SUBROEXP'' )  THEN (CETL.CLM_EXPSR_LNITM_AMT) ELSE 0 END  ))-

(SUM ( CASE WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''   AND  CET.RCVRY_CTGY_TYPE_CD IN (''SUBRO'')  AND  CET.EXPSR_COST_TYPE_CD IN (''PDL'')   

AND  CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')   AND  CETL.LNITM_CTGY_TYPE_CD IN (''RCVRY'',''SUBROEXP'') ) THEN (CETL.CLM_EXPSR_LNITM_AMT) ELSE 0 END  ))-

(SUM ( CASE WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''   AND  CET.RCVRY_CTGY_TYPE_CD IN (''SUBRO'')  AND  CET.EXPSR_COST_TYPE_CD IN (''EXPNS'')   

AND  CET.EXPSR_COST_CTGY_TYPE_CD IN (''EXPNS'')   AND  CETL.LNITM_CTGY_TYPE_CD IN (''RCVRY'',''SUBROEXP'') ) THEN (CETL.CLM_EXPSR_LNITM_AMT) ELSE 0 END  ))-

SUM( CASE WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''   AND  CET.RCVRY_CTGY_TYPE_CD=''CREXP''  AND  CET.EXPSR_COST_TYPE_CD IN (''EXPNS'')   

AND  CET.EXPSR_COST_CTGY_TYPE_CD IN (''EXPNS'')   AND  CETL.LNITM_CTGY_TYPE_CD IN (''SUBROEXP'' )) THEN (CETL.CLM_EXPSR_LNITM_AMT) ELSE 0 END  ) -

(SUM ( CASE WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''   AND  CET.RCVRY_CTGY_TYPE_CD IN (''SUBRO'')  AND  CET.EXPSR_COST_TYPE_CD IN (''PDL'')   

AND  CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')    AND  CETL.LNITM_CTGY_TYPE_CD IN (''RCVRY'' ) )  THEN (CETL.CLM_EXPSR_LNITM_AMT) ELSE 0 END  ))AS NET_SUBRGTN,

/*CLM_DA_0569*/

SUM( CASE WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''   AND  CET.RCVRY_CTGY_TYPE_CD IN (''CRLOSS'')  AND  CET.EXPSR_COST_TYPE_CD IN (''PDL'')   

AND  CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')    ) THEN (CETL.CLM_EXPSR_LNITM_AMT) ELSE 0 END  ) AS RCVRY_BY_OTH_METH_AMT,

/*CLM_DZ_0570*/

((SUM ( CASE WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''PYMNT''      AND  CET.EXPSR_COST_TYPE_CD=''EXPNS''     AND  CET.EXPSR_COST_CTGY_TYPE_CD =''EXPNS'' 

AND  CETL.LNITM_CTGY_TYPE_CD IN ( ''SALVEXP'' ) )THEN (CETL.CLM_EXPSR_LNITM_AMT) ELSE 0 END  ))-

(SUM ( CASE WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''  AND  CET.RCVRY_CTGY_TYPE_CD IN (''SALVAGE'')   AND  CET.EXPSR_COST_TYPE_CD IN (''EXPNS''   ) 

AND  CET.EXPSR_COST_CTGY_TYPE_CD IN  (''EXPNS'' ) AND  CETL.LNITM_CTGY_TYPE_CD IN ( ''RCVRY'',''SALVEXP'')) THEN (CETL.CLM_EXPSR_LNITM_AMT) ELSE 0 END  )) -

(SUM (CASE  WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''    AND  CET.RCVRY_CTGY_TYPE_CD=''CREXP'' AND  CET.EXPSR_COST_TYPE_CD  =''EXPNS''

AND  CET.EXPSR_COST_CTGY_TYPE_CD IN (''EXPNS'')  AND  CETL.LNITM_CTGY_TYPE_CD IN ( ''SALVEXP'' ) )THEN (CETL.CLM_EXPSR_LNITM_AMT) ELSE 0 END   ))-

(SUM ( CASE WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''   AND  CET.RCVRY_CTGY_TYPE_CD IN (''SALVAGE'')  AND  CET.EXPSR_COST_TYPE_CD IN (''PDL'')   

 AND  CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')   AND  CETL.LNITM_CTGY_TYPE_CD IN (''RCVRY'') ) THEN (CETL.CLM_EXPSR_LNITM_AMT) ELSE 0 END  ) ))AS NET_SALV,

 /*CLM_DA_0555*//*EIM-46303*/

SUM (CASE WHEN (CET.CLM_EXPSR_TRANS_SBTYPE_CD = ''PYMNT'' AND CET.EXPSR_COST_TYPE_CD IN (''PDL'') AND  CET.EXPSR_COST_CTGY_TYPE_CD IN (''LOSS'')  

AND  CETL.LNITM_CTGY_TYPE_CD IN (  ''LOSS'',''DED'',''DEDRFND'',''FRMRDED'',''DMNSHDVAL'') ) THEN (CETL.CLM_EXPSR_LNITM_AMT)  ELSE 0 END  )  AS LOSS_PMT,

(RSERV_AMT)+(NET_SUBRGTN)+(RCVRY_BY_OTH_METH_AMT)+(NET_SALV) +LOSS_PMT DLI_AMT

 FROM --EVIEWDB_EDW.CLM_EXPSR_TRANS  CET
 
 db_t_prod_core.CLM_EXPSR_TRANS  CET

LEFT OUTER JOIN  --EVIEWDB_EDW.CLM_EXPSR_TRANS_LNITM CETL 
db_t_prod_core.CLM_EXPSR_TRANS_LNITM CETL
ON CETL.CLM_EXPSR_TRANS_ID =  CET.CLM_EXPSR_TRANS_ID

AND CET.EDW_END_DTTM =''9999-12-31 23:59:59.999999'' AND CETL.EDW_END_DTTM =''9999-12-31 23:59:59.999999'' GROUP BY 1,2)CET 

LEFT OUTER   JOIN  --EVIEWDB_EDW.CLM_EXPSR CE 
db_t_prod_core.CLM_EXPSR CE
ON CE.CLM_EXPSR_ID=CET.CLM_EXPSR_ID AND CE.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

LEFT JOIN --EVIEWDB_EDW.CLM_EV C_E 
db_t_prod_core.CLM_EV C_E
ON CE.CLM_ID=C_E.CLM_ID AND C_E.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

LEFT JOIN --EVIEWDB_EDW.INCDT INC 
db_t_prod_core.INCDT INC
ON C_E.EV_ID=INC.INCDT_EV_ID AND INC.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

LEFT JOIN --DB_WRK.PERIL_TYPE PT 
db_t_prod_wrk.PERIL_TYPE PT
ON CTSTRPH_NAME=CAT_CD

LEFT OUTER JOIN  --EVIEWDB_EDW.AGMT_CLM AF 
db_t_prod_core.AGMT_CLM AF
ON AF.CLM_ID=CE.CLM_ID AND AF.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

 GROUP BY 1,2

)DLI ON POLICY.AGMT_ID=DLI.AGMT_ID AND DLI.MONTH_ID=AGMT_MONTH

/*ALAE TOTAL*/

/* THIS CALUCLATION IS PROVIDED BY CLIENT . REFER FROM TICKET EIM-15160*/

LEFT JOIN ( 

SELECT AGMT_ID,MONTH_ID,SUM(PMT_EXP_LEGL_CVGE_AMT) ALAE_TOTAL,

SUM(CASE WHEN(( ISO_IND =''Y'' AND NAMED_STROM =''Y'' )) THEN PMT_EXP_LEGL_CVGE_AMT ELSE 0 END ) ALAE_HURR,

SUM(CASE WHEN( ISO_IND =''Y'' AND NAMED_STROM =''N'' AND WIND =''NON- NAMED WIND CATASTROPHE'' ) THEN PMT_EXP_LEGL_CVGE_AMT ELSE 0 END ) ALAE_NON_NAMED,

SUM(CASE WHEN( ISO_IND =''N'' AND NAMED_STROM =''N''  AND WIND =''OTHER WIND'') THEN PMT_EXP_LEGL_CVGE_AMT ELSE 0 END ) ALAE_OTHER_WIND,

ALAE_HURR+ALAE_NON_NAMED+ALAE_OTHER_WIND ALAE_SUBTOTAL,

SUM(CASE WHEN( ISO_IND =''Y'' AND NAMED_STROM =''N''  AND WIND  NOT   IN (''NON- NAMED WIND CATASTROPHE'',''OTHER WIND'')) THEN PMT_EXP_LEGL_CVGE_AMT ELSE 0 END ) ALAE_OTHER_NON_NAMED,

SUM(CASE WHEN( ISO_IND IS NULL ) THEN PMT_EXP_LEGL_CVGE_AMT ELSE 0 END ) ALAE_ALL_OTHER_PERIL

FROM (

SELECT CLM_EXPSR_ID,  EXTRACT(YEAR FROM CLM_EXPSR_TRANS_STRT_DTTM)*100+EXTRACT(MONTH FROM CLM_EXPSR_TRANS_STRT_DTTM) MONTH_ID,

SUM(CASE WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''PYMNT''  

AND  CET.EXPSR_COST_TYPE_CD=''EXPNS''    

AND  CET.EXPSR_COST_CTGY_TYPE_CD =''EXPNS''  

AND  CETL.LNITM_CTGY_TYPE_CD = ''LEGDEF'' ) THEN (CETL.CLM_EXPSR_LNITM_AMT ) 

ELSE 0 END)-

SUM ( CASE WHEN ( CET.CLM_EXPSR_TRANS_SBTYPE_CD =''RCVRY''  

AND  CET.RCVRY_CTGY_TYPE_CD IN (''SUBRO'',''CREXP'',''SALVAGE'') 

AND  CET.EXPSR_COST_TYPE_CD=''EXPNS''    

AND  CET.EXPSR_COST_CTGY_TYPE_CD =''EXPNS''  

AND  CETL.LNITM_CTGY_TYPE_CD = ''LEGDEF'' ) THEN (CETL.CLM_EXPSR_LNITM_AMT ) 

ELSE 0 END  ) AS PMT_EXP_LEGL_CVGE_AMT

FROM 

--EVIEWDB_EDW.CLM_EXPSR_TRANS  CET
db_t_prod_core.CLM_EXPSR_TRANS  CET

LEFT OUTER JOIN  --EVIEWDB_EDW.CLM_EXPSR_TRANS_LNITM CETL 
db_t_prod_core.CLM_EXPSR_TRANS_LNITM CETL
ON CETL.CLM_EXPSR_TRANS_ID =  CET.CLM_EXPSR_TRANS_ID

AND CET.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

AND CETL.EDW_END_DTTM =''9999-12-31 23:59:59.999999'' GROUP BY 1,2)CET 

LEFT OUTER   JOIN  --EVIEWDB_EDW.CLM_EXPSR CE 
db_t_prod_core.CLM_EXPSR CE
ON CE.CLM_EXPSR_ID=CET.CLM_EXPSR_ID AND CE.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

LEFT JOIN --EVIEWDB_EDW.CLM_EV C_E 
db_t_prod_core.CLM_EV C_E
ON CE.CLM_ID=C_E.CLM_ID AND C_E.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

LEFT JOIN --EVIEWDB_EDW.INCDT INC 
db_t_prod_core.INCDT INC
ON C_E.EV_ID=INC.INCDT_EV_ID AND INC.EDW_END_DTTM =''9999-12-31 23:59:59.999999''

LEFT JOIN --DB_WRK.PERIL_TYPE PT 
db_t_prod_wrk.PERIL_TYPE PT
ON CTSTRPH_NAME=CAT_CD

LEFT OUTER JOIN  --EVIEWDB_EDW.AGMT_CLM AF 
db_t_prod_core.AGMT_CLM AF
ON AF.CLM_ID=CE.CLM_ID

AND AF.EDW_END_DTTM =''9999-12-31 23:59:59.999999'' GROUP BY 1,2 

)ALAE ON  POLICY.AGMT_ID=ALAE.AGMT_ID AND ALAE.MONTH_ID=AGMT_MONTH

/*NO OF UNITS CALCULATION*/

LEFT JOIN  

 (SELECT EXTRACT(YEAR FROM AGMT_STS_STRT_DT)*100+EXTRACT(MONTH FROM AGMT_STS_STRT_DT ) MO_ID,AGMT_ID, SUM(NO_OF_UNITS) NO_OF_UNITS FROM (

/*FIRST YEAR OF  THREEE MS DAT A- NO OF UNITS CALCULATION*/

SELECT A.HOST_AGMT_NUM,

A.AGMT_ID,

A.TERM_NUM,

A.MODL_NUM,

A.MODL_EFF_DTTM,

AST.AGMT_STS_CD,

AST.AGMT_STS_STRT_DTTM,

A.MODL_ACTL_END_DTTM,

CASE WHEN ( MODL_EFF_DTTM >

 COALESCE(MAX(MODL_ACTL_END_DTTM) OVER ( PARTITION BY HOST_AGMT_NUM ORDER BY A.TERM_NUM,A.MODL_NUM,MODL_EFF_DTTM ROWS BETWEEN 1 PRECEDING  AND 1 PRECEDING ), 

MODL_EFF_DTTM) ) THEN MODL_EFF_DTTM  ELSE 

COALESCE(MAX(MODL_ACTL_END_DTTM) OVER (  PARTITION BY HOST_AGMT_NUM ORDER BY A.TERM_NUM,A.MODL_NUM,MODL_EFF_DTTM ROWS BETWEEN 1 PRECEDING  AND 1 PRECEDING  ),

MODL_EFF_DTTM)  END AS MODL_EFF_DTTM_NEW,

MAX(AGMT_STS_CD) OVER (  PARTITION BY A.HOST_AGMT_NUM ORDER BY A.TERM_NUM,A.MODL_NUM,AST.AGMT_STS_STRT_DTTM ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING  ) AS NEXT_STATUS,

MAX(AGMT_STS_STRT_DTTM) OVER (  PARTITION BY A.HOST_AGMT_NUM ORDER BY A.TERM_NUM,A.MODL_NUM,AST.AGMT_STS_STRT_DTTM ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING  ) AS NEXT_STS_CHANGE_DTTM,

CASE WHEN A.MODL_ACTL_END_DTTM IS NOT NULL THEN A.MODL_ACTL_END_DTTM  ELSE NEXT_STS_CHANGE_DTTM  END AS NEXT_STS_CHANGE_DTE,

CASE WHEN MODL_EFF_DTTM_NEW < to_date(:YR_STRT_DT , ''MM/DD/YYYY'') THEN  to_date(:YR_STRT_DT , ''MM/DD/YYYY'') 

WHEN MODL_EFF_DTTM_NEW > ADD_MONTHS(to_date(:YR_END_DT , ''MM/DD/YYYY''),-24) THEN ADD_MONTHS(to_date(:YR_END_DT , ''MM/DD/YYYY''),-24)  ELSE MODL_EFF_DTTM_NEW  END AGMT_STS_STRT_DT,

CASE WHEN NEXT_STS_CHANGE_DTE > ADD_MONTHS(to_date(:YR_END_DT , ''MM/DD/YYYY''),-24) THEN ADD_MONTHS(to_date(:YR_END_DT , ''MM/DD/YYYY''),-24)+ INTERVAL ''1 DAY''  ELSE NEXT_STS_CHANGE_DTE 

 END NEXT_STS_CHANGE_DT ,

CAST(CAST( NEXT_STS_CHANGE_DT AS DATE) -CAST( AGMT_STS_STRT_DT AS DATE) AS DECIMAL(18,4))/365.25 AS NO_OF_UNITS

FROM(

SELECT  AGMT_ID, AGMT_STS_STRT_DTTM,AGMT_STS_CD 
FROM --EVIEWDB_EDW.AGMT_STS 
db_t_prod_core.AGMT_STS
WHERE AGMT_STS_CD <> ''CNFRMDDT'')AST

INNER JOIN (SELECT DISTINCT A.HOST_AGMT_NUM, TRM.AGMT_ID AGMT_ID_POL, A.AGMT_ID AGMT_ID,A.MODL_EFF_DTTM, A.MODL_ACTL_END_DTTM,A.TERM_NUM,A.MODL_NUM,A.EDW_END_DTTM,A.AGMT_TYPE_CD 

FROM --EVIEWDB_EDW.AGMT 
db_t_prod_core.AGMT AS A 
JOIN --EVIEWDB_EDW.AGMT 
db_t_prod_core.AGMT TRM ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM AND TRM.AGMT_TYPE_CD=''POLTRM'' 

AND A.AGMT_TYPE_CD = ''PPV''

AND A.SRC_SYS_CD=''GWPC'') A ON A.AGMT_ID_POL = AST.AGMT_ID 

AND TERM_NUM IS NOT NULL  AND MODL_NUM IS NOT NULL  

AND MODL_EFF_DTTM <= ADD_MONTHS(to_date(:YR_END_DT ,''MM/DD/YYYY''),-24)  

AND A.MODL_EFF_DTTM < A.MODL_ACTL_END_DTTM  AND A.MODL_ACTL_END_DTTM >=  to_date(:YR_STRT_DT , ''MM/DD/YYYY'') 

AND A.EDW_END_DTTM = ''9999-12-31 23:59:59.999999'' 

AND AGMT_STS_CD=''INFORCE''

QUALIFY MODL_EFF_DTTM_NEW < A.MODL_ACTL_END_DTTM

AND MODL_EFF_DTTM_NEW <= ADD_MONTHS(to_date(:YR_END_DT ,''MM/DD/YYYY''),-24)  

UNION

/*SECOND YEAR OF  THREEE MS DAT A- NO OF UNITS CALCULATION*/

SELECT A.HOST_AGMT_NUM,

A.AGMT_ID,

A.TERM_NUM,

A.MODL_NUM,

A.MODL_EFF_DTTM,

AST.AGMT_STS_CD,

AST.AGMT_STS_STRT_DTTM,

A.MODL_ACTL_END_DTTM,

CASE WHEN ( MODL_EFF_DTTM >

 COALESCE(MAX(MODL_ACTL_END_DTTM) OVER ( PARTITION BY HOST_AGMT_NUM ORDER BY A.TERM_NUM,A.MODL_NUM,MODL_EFF_DTTM ROWS BETWEEN 1 PRECEDING  AND 1 PRECEDING ), 

MODL_EFF_DTTM) ) THEN MODL_EFF_DTTM  ELSE 

COALESCE(MAX(MODL_ACTL_END_DTTM) OVER (  PARTITION BY HOST_AGMT_NUM ORDER BY A.TERM_NUM,A.MODL_NUM,MODL_EFF_DTTM ROWS BETWEEN 1 PRECEDING  AND 1 PRECEDING  ),

MODL_EFF_DTTM)  END AS MODL_EFF_DTTM_NEW,

MAX(AGMT_STS_CD) OVER (  PARTITION BY A.HOST_AGMT_NUM ORDER BY A.TERM_NUM,A.MODL_NUM,AST.AGMT_STS_STRT_DTTM ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING  ) AS NEXT_STATUS,

MAX(AGMT_STS_STRT_DTTM) OVER (  PARTITION BY A.HOST_AGMT_NUM ORDER BY A.TERM_NUM,A.MODL_NUM,AST.AGMT_STS_STRT_DTTM ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING  ) AS NEXT_STS_CHANGE_DTTM,

CASE WHEN A.MODL_ACTL_END_DTTM IS NOT NULL THEN A.MODL_ACTL_END_DTTM  ELSE NEXT_STS_CHANGE_DTTM  END AS NEXT_STS_CHANGE_DTE,

CASE WHEN MODL_EFF_DTTM_NEW < ADD_MONTHS( to_date(:YR_STRT_DT , ''MM/DD/YYYY''),12) THEN  ADD_MONTHS( to_date(:YR_STRT_DT , ''MM/DD/YYYY''),12) 

WHEN MODL_EFF_DTTM_NEW > ADD_MONTHS(to_date(:YR_END_DT , ''MM/DD/YYYY''),-12) THEN ADD_MONTHS(to_date(:YR_END_DT , ''MM/DD/YYYY''),-12)  ELSE MODL_EFF_DTTM_NEW  END AGMT_STS_STRT_DT,

CASE WHEN NEXT_STS_CHANGE_DTE > ADD_MONTHS(to_date(:YR_END_DT , ''MM/DD/YYYY''),-12) THEN ADD_MONTHS(to_date(:YR_END_DT , ''MM/DD/YYYY''),-12)+ INTERVAL ''1 DAY'' ELSE NEXT_STS_CHANGE_DTE 

 END NEXT_STS_CHANGE_DT ,

CAST(CAST( NEXT_STS_CHANGE_DT AS DATE) -CAST( AGMT_STS_STRT_DT AS DATE) AS DECIMAL(18,4))/365.25 AS NO_OF_UNITS

FROM(

SELECT  AGMT_ID, AGMT_STS_STRT_DTTM,AGMT_STS_CD 
FROM --EVIEWDB_EDW.AGMT_STS 
db_t_prod_core.AGMT_STS
WHERE AGMT_STS_CD <> ''CNFRMDDT'')AST

INNER JOIN (SELECT DISTINCT A.HOST_AGMT_NUM, TRM.AGMT_ID AGMT_ID_POL, A.AGMT_ID AGMT_ID,A.MODL_EFF_DTTM, A.MODL_ACTL_END_DTTM,A.TERM_NUM,A.MODL_NUM,A.EDW_END_DTTM,A.AGMT_TYPE_CD 

FROM --EVIEWDB_EDW.AGMT 
db_t_prod_core.AGMT AS A 
JOIN --EVIEWDB_EDW.AGMT 
db_t_prod_core.AGMT TRM ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM AND TRM.AGMT_TYPE_CD=''POLTRM'' 

AND A.AGMT_TYPE_CD = ''PPV''

AND A.SRC_SYS_CD=''GWPC'') A ON A.AGMT_ID_POL = AST.AGMT_ID 

AND TERM_NUM IS NOT NULL  AND MODL_NUM IS NOT NULL  

AND MODL_EFF_DTTM <= ADD_MONTHS(to_date(:YR_END_DT ,''MM/DD/YYYY''),-12)  

AND A.MODL_EFF_DTTM < A.MODL_ACTL_END_DTTM  AND A.MODL_ACTL_END_DTTM >=  ADD_MONTHS(to_date(:YR_STRT_DT ,''MM/DD/YYYY''),12) 

AND A.EDW_END_DTTM = ''9999-12-31 23:59:59.999999'' 

AND AGMT_STS_CD=''INFORCE''

QUALIFY MODL_EFF_DTTM_NEW < A.MODL_ACTL_END_DTTM

AND MODL_EFF_DTTM_NEW <= ADD_MONTHS(to_date(:YR_END_DT ,''MM/DD/YYYY''),-12)  

UNION 

/*THIRD YEAR OF  THREEE MS DAT A- NO OF UNITS CALCULATION*/

SELECT A.HOST_AGMT_NUM,

A.AGMT_ID,

A.TERM_NUM,

A.MODL_NUM,

A.MODL_EFF_DTTM,

AST.AGMT_STS_CD,

AST.AGMT_STS_STRT_DTTM,

A.MODL_ACTL_END_DTTM,

CASE WHEN ( MODL_EFF_DTTM >

 COALESCE(MAX(MODL_ACTL_END_DTTM) OVER ( PARTITION BY HOST_AGMT_NUM ORDER BY A.TERM_NUM,A.MODL_NUM,MODL_EFF_DTTM ROWS BETWEEN 1 PRECEDING  AND 1 PRECEDING ), 

MODL_EFF_DTTM) ) THEN MODL_EFF_DTTM  ELSE 

COALESCE(MAX(MODL_ACTL_END_DTTM) OVER (  PARTITION BY HOST_AGMT_NUM ORDER BY A.TERM_NUM,A.MODL_NUM,MODL_EFF_DTTM ROWS BETWEEN 1 PRECEDING  AND 1 PRECEDING  ),

MODL_EFF_DTTM)  END AS MODL_EFF_DTTM_NEW,

MAX(AGMT_STS_CD) OVER (  PARTITION BY A.HOST_AGMT_NUM ORDER BY A.TERM_NUM,A.MODL_NUM,AST.AGMT_STS_STRT_DTTM ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING  ) AS NEXT_STATUS,

MAX(AGMT_STS_STRT_DTTM) OVER (  PARTITION BY A.HOST_AGMT_NUM ORDER BY A.TERM_NUM,A.MODL_NUM,AST.AGMT_STS_STRT_DTTM ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING  ) AS NEXT_STS_CHANGE_DTTM,

CASE WHEN A.MODL_ACTL_END_DTTM IS NOT NULL THEN A.MODL_ACTL_END_DTTM  ELSE NEXT_STS_CHANGE_DTTM  END AS NEXT_STS_CHANGE_DTE,

CASE WHEN MODL_EFF_DTTM_NEW < ADD_MONTHS( to_date(:YR_STRT_DT ,''MM/DD/YYYY''),24) THEN  ADD_MONTHS( to_date(:YR_STRT_DT ,''MM/DD/YYYY''),24) 

WHEN MODL_EFF_DTTM_NEW > to_date(:YR_END_DT ,''MM/DD/YYYY'') THEN to_date(:YR_END_DT ,''MM/DD/YYYY'')  ELSE MODL_EFF_DTTM_NEW  END AGMT_STS_STRT_DT,

CASE WHEN NEXT_STS_CHANGE_DTE > to_date(:YR_END_DT ,''MM/DD/YYYY'') THEN to_date(:YR_END_DT ,''MM/DD/YYYY'')+ INTERVAL ''1 DAY''  ELSE NEXT_STS_CHANGE_DTE 

 END NEXT_STS_CHANGE_DT ,

CAST(CAST( NEXT_STS_CHANGE_DT AS DATE) -CAST( AGMT_STS_STRT_DT AS DATE) AS DECIMAL(18,4))/365.25 AS NO_OF_UNITS

FROM(

SELECT  AGMT_ID, AGMT_STS_STRT_DTTM,AGMT_STS_CD 
FROM --EVIEWDB_EDW.AGMT_STS 
db_t_prod_core.AGMT_STS
WHERE AGMT_STS_CD <> ''CNFRMDDT'')AST

INNER JOIN (SELECT DISTINCT A.HOST_AGMT_NUM, TRM.AGMT_ID AGMT_ID_POL, A.AGMT_ID AGMT_ID,A.MODL_EFF_DTTM, A.MODL_ACTL_END_DTTM,A.TERM_NUM,A.MODL_NUM,A.EDW_END_DTTM,A.AGMT_TYPE_CD 

FROM --EVIEWDB_EDW.AGMT 
db_t_prod_core.AGMT AS A 
JOIN --EVIEWDB_EDW.AGMT 
db_t_prod_core.AGMT TRM ON TRM.HOST_AGMT_NUM=A.HOST_AGMT_NUM AND TRM.TERM_NUM=A.TERM_NUM AND TRM.AGMT_TYPE_CD=''POLTRM'' 

AND A.AGMT_TYPE_CD = ''PPV''

AND A.SRC_SYS_CD=''GWPC'') A ON A.AGMT_ID_POL = AST.AGMT_ID 

AND TERM_NUM IS NOT NULL  AND MODL_NUM IS NOT NULL  

AND MODL_EFF_DTTM <= to_date(:YR_END_DT ,''MM/DD/YYYY'')  

AND A.MODL_EFF_DTTM < A.MODL_ACTL_END_DTTM  AND A.MODL_ACTL_END_DTTM >=  ADD_MONTHS( to_date(:YR_STRT_DT ,''MM/DD/YYYY''),24) 

AND A.EDW_END_DTTM = ''9999-12-31 23:59:59.999999'' 

AND AGMT_STS_CD=''INFORCE''

QUALIFY MODL_EFF_DTTM_NEW < A.MODL_ACTL_END_DTTM

AND MODL_EFF_DTTM_NEW <= to_date(:YR_END_DT ,''MM/DD/YYYY'')  

)NO_OF_UNITS GROUP BY 1,2

) NO_OF_UNITS ON  POLICY.AGMT_ID=NO_OF_UNITS.AGMT_ID  AND AGMT_MONTH =NO_OF_UNITS.MO_ID

/*DWELLING LIMIT*/

LEFT JOIN (

SELECT AGMT_ID,EXTRACT(YEAR FROM AGMT_FEAT_STRT_DTTM)*100+EXTRACT(MONTH FROM AGMT_FEAT_STRT_DTTM) MO_ID ,SUM(AGMT_FEAT_AMT)  AS AMT

FROM  --EVIEWDB_EDW.AGMT_FEAT AF
db_t_prod_core.AGMT_FEAT AF

INNER JOIN  --EVIEWDB_EDW.FEAT F 
db_t_prod_core.FEAT F
ON AF.FEAT_ID = F.FEAT_ID

WHERE INSRNC_CVGE_TYPE_CD IN (''DW'',''DWELL'')

AND FEAT_NAME = ''LIMIT''

AND CAST(AF.EDW_END_DTTM AS DATE) = ''9999-12-31''

GROUP BY AGMT_ID, MO_ID

) DW_LIMIT ON  DWP_EPM.AGMT_ID = DW_LIMIT.AGMT_ID AND MTRC_MONTH=DW_LIMIT.MO_ID

/*CONTENTS LIMIT*/

LEFT JOIN (

SELECT AGMT_ID,EXTRACT(YEAR FROM AGMT_FEAT_STRT_DTTM)*100+EXTRACT(MONTH FROM AGMT_FEAT_STRT_DTTM) MO_ID ,SUM(AGMT_FEAT_AMT)  AS AMT

FROM  --EVIEWDB_EDW.AGMT_FEAT AF
db_t_prod_core.AGMT_FEAT AF

INNER JOIN  --EVIEWDB_EDW.FEAT F ON AF.FEAT_ID = F.FEAT_ID
db_t_prod_core.FEAT F ON AF.FEAT_ID = F.FEAT_ID

WHERE INSRNC_CVGE_TYPE_CD IN (''PP'')

AND FEAT_NAME = ''LIMIT''

AND CAST(AF.EDW_END_DTTM AS DATE) = ''9999-12-31''

GROUP BY AGMT_ID, MO_ID

) CNT_LIMIT ON  DWP_EPM.AGMT_ID = CNT_LIMIT.AGMT_ID AND MTRC_MONTH=CNT_LIMIT.MO_ID

/*MS ZIP CODE PROVIDED BY CLIENT*/

LEFT JOIN --DB_WRK.MS_CLARITY_ACT_ZIPCODES  
 db_t_prod_wrk.MS_CLARITY_ACT_ZIPCODES  MS_CLARITY_ZIP ON COALESCE(ZIP_COUNTY.POSTL_CD_NUM,0) =CAST(TRIM(MS_CLARITY_ZIP.ZIPCODE) AS VARCHAR(8))

GROUP BY 1,2,3,4,5,7,11,14,16,26,36,40,44,47) AS MS_CLARITY_GW_FIRST_YEAR 
  GROUP BY 1,2,3,4,13,46
HAVING SUM(DPW_TOTAL)<>0 
  OR SUM(DEP_TOTAL)<>0 OR SUM(DLI_TOTAL)<>0 
  OR SUM(ALAE_TOTAL)<>0 OR SUM(EHY_TOTAL)<> 0 
  or sum(DWL_COVA_TOT)<>0 or sum(DWL_COVC_TOT)<>0 
) SRC
)
);


-- Component exp_default, Type EXPRESSION 
CREATE OR REPLACE TEMPORARY TABLE exp_default AS
(
SELECT
:PRCS_ID as PRCS_ID,
LTRIM ( RTRIM ( sq_MS_CLRTY_XTRCT.NAIC_CD ) ) as o_NAIC_CD,
LTRIM ( RTRIM ( sq_MS_CLRTY_XTRCT.CO_NAME ) ) as o_CO_NAME,
LTRIM ( RTRIM ( sq_MS_CLRTY_XTRCT.PULL_YR ) ) as o_PULL_YR,
LTRIM ( RTRIM ( sq_MS_CLRTY_XTRCT.ZIPCD ) ) as o_ZIPCD,
sq_MS_CLRTY_XTRCT.DPW_TOT as DPW_TOT,
LTRIM ( RTRIM ( sq_MS_CLRTY_XTRCT.DPW_WIND_ONLY ) ) as o_DPW_WIND_ONLY,
sq_MS_CLRTY_XTRCT.DPW_EXCLG_WIND as DPW_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.DPW_INCLG_WIND as DPW_INCLG_WIND,
sq_MS_CLRTY_XTRCT.DEP_TOT as DEP_TOT,
LTRIM ( RTRIM ( sq_MS_CLRTY_XTRCT.DEP_WIND_ONLY ) ) as o_DEP_WIND_ONLY,
sq_MS_CLRTY_XTRCT.DEP_EXCLG_WIND as DEP_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.DEP_INCLG_WIND as DEP_INCLG_WIND,
LTRIM ( RTRIM ( sq_MS_CLRTY_XTRCT.WIND_EXCL_FCTR ) ) as o_WIND_EXCL_FCTR,
sq_MS_CLRTY_XTRCT.DLI_TOT as DLI_TOT,
LTRIM ( RTRIM ( sq_MS_CLRTY_XTRCT.DLI_WIND_ONLY ) ) as o_DLI_WIND_ONLY,
sq_MS_CLRTY_XTRCT.DLI_EXCLG_WIND as DLI_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.DLI_INCLG_WIND as DLI_INCLG_WIND,
sq_MS_CLRTY_XTRCT.DLI_HURCN as DLI_HURCN,
sq_MS_CLRTY_XTRCT.DLI_WIND_CTSTRPH as DLI_WIND_CTSTRPH,
sq_MS_CLRTY_XTRCT.DLI_OTH_WIND as DLI_OTH_WIND,
sq_MS_CLRTY_XTRCT.DLI_WIND_SBTOT as DLI_WIND_SBTOT,
sq_MS_CLRTY_XTRCT.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
sq_MS_CLRTY_XTRCT.DLI_ALL_OTH as DLI_ALL_OTH,
sq_MS_CLRTY_XTRCT.ALAE_TOT as ALAE_TOT,
sq_MS_CLRTY_XTRCT.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
sq_MS_CLRTY_XTRCT.ALAE_EXCLG_WIND as ALAE_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.ALAE_INCLG_WIND as ALAE_INCLG_WIND,
sq_MS_CLRTY_XTRCT.ALAE_HURCN as ALAE_HURCN,
sq_MS_CLRTY_XTRCT.ALAE_WIND_CTSTRPH as ALAE_WIND_CTSTRPH,
sq_MS_CLRTY_XTRCT.ALAE_OTH_WIND as ALAE_OTH_WIND,
sq_MS_CLRTY_XTRCT.ALAE_WIND_SBTOT as ALAE_WIND_SBTOT,
sq_MS_CLRTY_XTRCT.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
sq_MS_CLRTY_XTRCT.ALAE_ALL_OTH as ALAE_ALL_OTH,
sq_MS_CLRTY_XTRCT.EHY_TOT as EHY_TOT,
LTRIM ( RTRIM ( sq_MS_CLRTY_XTRCT.EHY_WIND_ONLY ) ) as o_EHY_WIND_ONLY,
sq_MS_CLRTY_XTRCT.EHY_EXCLG_WIND as EHY_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.EHY_ALL_OTH as EHY_ALL_OTH,
sq_MS_CLRTY_XTRCT.DWL_CVGE_A_TOT as DWL_CVGE_A_TOT,
LTRIM ( RTRIM ( sq_MS_CLRTY_XTRCT.DWL_CVGE_A_WO ) ) as o_DWL_CVGE_A_WO,
sq_MS_CLRTY_XTRCT.DWL_CVGE_A_EXCLG_WIND as DWL_CVGE_A_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.DWL_CVGE_A_INCLG_WIND as DWL_CVGE_A_INCLG_WIND,
sq_MS_CLRTY_XTRCT.DWL_CVGE_C_TOT as DWL_CVGE_C_TOT,
LTRIM ( RTRIM ( sq_MS_CLRTY_XTRCT.DWL_CVGE_C_WO ) ) as o_DWL_CVGE_C_WO,
sq_MS_CLRTY_XTRCT.DWL_CVGE_C_EXCLG_WIND as DWL_CVGE_C_EXCLG_WIND,
sq_MS_CLRTY_XTRCT.DWL_CVGE_C_INCLG_WIND as DWL_CVGE_C_INCLG_WIND,
LTRIM ( RTRIM ( sq_MS_CLRTY_XTRCT.COMTS ) ) as o_COMTS,
''GW'' as ROW_TYPE_CD,
''NA'' as VLDN_ERR_MSG,
CURRENT_TIMESTAMP as EDW_STRT_DTTM,
to_timestamp_ntz ( ''9999-12-31 23:59:59.999999'' , ''YYYY-MM-DD HH24:MI:SS.FF6'' ) as EDW_END_DTTM,
sq_MS_CLRTY_XTRCT.source_record_id
FROM
sq_MS_CLRTY_XTRCT
);


-- Component MS_CLRTY_XTRCT_GW, Type TARGET 
INSERT INTO db_t_prod_wrk.MS_CLRTY_XTRCT
(
PRCS_ID,
NAIC_CD,
CO_NAME,
PULL_YR,
ZIPCD,
DPW_TOT,
DPW_WIND_ONLY,
DPW_EXCLG_WIND,
DPW_INCLG_WIND,
DEP_TOT,
DEP_WIND_ONLY,
DEP_EXCLG_WIND,
DEP_INCLG_WIND,
WIND_EXCL_FCTR,
DLI_TOT,
DLI_WIND_ONLY,
DLI_EXCLG_WIND,
DLI_INCLG_WIND,
DLI_HURCN,
DLI_WIND_CTSTRPH,
DLI_OTH_WIND,
DLI_WIND_SBTOT,
DLI_OTH_CTSTRPH,
DLI_ALL_OTH,
ALAE_TOT,
ALAE_WIND_ONLY,
ALAE_EXCLG_WIND,
ALAE_INCLG_WIND,
ALAE_HURCN,
ALAE_WIND_CTSTRPH,
ALAE_OTH_WIND,
ALAE_WIND_SBTOT,
ALAE_OTH_CTSTRPH,
ALAE_ALL_OTH,
EHY_TOT,
EHY_WIND_ONLY,
EHY_EXCLG_WIND,
EHY_ALL_OTH,
DWL_CVGE_A_TOT,
DWL_CVGE_A_WO,
DWL_CVGE_A_EXCLG_WIND,
DWL_CVGE_A_INCLG_WIND,
DWL_CVGE_C_TOT,
DWL_CVGE_C_WO,
DWL_CVGE_C_EXCLG_WIND,
DWL_CVGE_C_INCLG_WIND,
COMTS,
ROW_TYPE_CD,
VLDN_ERR_MSG,
EDW_STRT_DTTM,
EDW_END_DTTM
)
SELECT
exp_default.PRCS_ID as PRCS_ID,
exp_default.o_NAIC_CD as NAIC_CD,
exp_default.o_CO_NAME as CO_NAME,
exp_default.o_PULL_YR as PULL_YR,
exp_default.o_ZIPCD as ZIPCD,
exp_default.DPW_TOT as DPW_TOT,
exp_default.o_DPW_WIND_ONLY as DPW_WIND_ONLY,
exp_default.DPW_EXCLG_WIND as DPW_EXCLG_WIND,
exp_default.DPW_INCLG_WIND as DPW_INCLG_WIND,
exp_default.DEP_TOT as DEP_TOT,
exp_default.o_DEP_WIND_ONLY as DEP_WIND_ONLY,
exp_default.DEP_EXCLG_WIND as DEP_EXCLG_WIND,
exp_default.DEP_INCLG_WIND as DEP_INCLG_WIND,
exp_default.o_WIND_EXCL_FCTR as WIND_EXCL_FCTR,
exp_default.DLI_TOT as DLI_TOT,
exp_default.o_DLI_WIND_ONLY as DLI_WIND_ONLY,
exp_default.DLI_EXCLG_WIND as DLI_EXCLG_WIND,
exp_default.DLI_INCLG_WIND as DLI_INCLG_WIND,
exp_default.DLI_HURCN as DLI_HURCN,
exp_default.DLI_WIND_CTSTRPH as DLI_WIND_CTSTRPH,
exp_default.DLI_OTH_WIND as DLI_OTH_WIND,
exp_default.DLI_WIND_SBTOT as DLI_WIND_SBTOT,
exp_default.DLI_OTH_CTSTRPH as DLI_OTH_CTSTRPH,
exp_default.DLI_ALL_OTH as DLI_ALL_OTH,
exp_default.ALAE_TOT as ALAE_TOT,
exp_default.ALAE_WIND_ONLY as ALAE_WIND_ONLY,
exp_default.ALAE_EXCLG_WIND as ALAE_EXCLG_WIND,
exp_default.ALAE_INCLG_WIND as ALAE_INCLG_WIND,
exp_default.ALAE_HURCN as ALAE_HURCN,
exp_default.ALAE_WIND_CTSTRPH as ALAE_WIND_CTSTRPH,
exp_default.ALAE_OTH_WIND as ALAE_OTH_WIND,
exp_default.ALAE_WIND_SBTOT as ALAE_WIND_SBTOT,
exp_default.ALAE_OTH_CTSTRPH as ALAE_OTH_CTSTRPH,
exp_default.ALAE_ALL_OTH as ALAE_ALL_OTH,
exp_default.EHY_TOT as EHY_TOT,
exp_default.o_EHY_WIND_ONLY as EHY_WIND_ONLY,
exp_default.EHY_EXCLG_WIND as EHY_EXCLG_WIND,
exp_default.EHY_ALL_OTH as EHY_ALL_OTH,
exp_default.DWL_CVGE_A_TOT as DWL_CVGE_A_TOT,
exp_default.o_DWL_CVGE_A_WO as DWL_CVGE_A_WO,
exp_default.DWL_CVGE_A_EXCLG_WIND as DWL_CVGE_A_EXCLG_WIND,
exp_default.DWL_CVGE_A_INCLG_WIND as DWL_CVGE_A_INCLG_WIND,
exp_default.DWL_CVGE_C_TOT as DWL_CVGE_C_TOT,
exp_default.o_DWL_CVGE_C_WO as DWL_CVGE_C_WO,
exp_default.DWL_CVGE_C_EXCLG_WIND as DWL_CVGE_C_EXCLG_WIND,
exp_default.DWL_CVGE_C_INCLG_WIND as DWL_CVGE_C_INCLG_WIND,
exp_default.o_COMTS as COMTS,
exp_default.ROW_TYPE_CD as ROW_TYPE_CD,
exp_default.VLDN_ERR_MSG as VLDN_ERR_MSG,
exp_default.EDW_STRT_DTTM as EDW_STRT_DTTM,
exp_default.EDW_END_DTTM as EDW_END_DTTM
FROM
exp_default;


END; ';