-- Object Type: FUNCTIONS
CREATE OR REPLACE FUNCTION ALFA_EDW_DEV.PUBLIC.TIMESTAMP_DIFFERENCE_UDF("MINUEND" TIMESTAMP_NTZ(9), "SUBTRAHEND" TIMESTAMP_NTZ(9), "INPUT_PART" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
IMMUTABLE
COMMENT='{ \"origin\": \"sf_sc\", \"name\": \"snowconvert\", \"version\": {  \"major\": 1,  \"minor\": 7,  \"patch\": \"1.0\" }, \"attributes\": {  \"component\": \"udf\",  \"convertedOn\": \"06/04/2025\",  \"domain\": \"alfains\" }}'
AS '
   DECODE(INPUT_PART,
           ''YEAR'',             TO_VARCHAR(DATEDIFF(YEAR, SUBTRAHEND, MINUEND)),
           ''MONTH'',            TO_VARCHAR(DATEDIFF(MONTH, SUBTRAHEND, MINUEND)),
           ''YEAR TO MONTH'',    CASE WHEN SUBTRAHEND>MINUEND AND TRUNC(DATEDIFF(MONTH, SUBTRAHEND, MINUEND)/12) >= 0 THEN ''-'' ELSE '''' END || TO_VARCHAR(TRUNC(DATEDIFF(MONTH, SUBTRAHEND, MINUEND)/12)) ||''-''|| REPLACE(TO_VARCHAR(DATEDIFF(MONTH, SUBTRAHEND, MINUEND)%12,''FM00''),''-'',''''),
           ''DAY'',              TO_VARCHAR(TRUNC(DATEDIFF(SECONDS, SUBTRAHEND, MINUEND)/(86400))),
           ''DAY TO HOUR'',      CASE WHEN SUBTRAHEND>MINUEND THEN ''-'' ELSE '''' END || REPLACE(TO_VARCHAR(TRUNC(DATEDIFF(SECONDS, SUBTRAHEND, MINUEND)/(86400))) || '' '' || TO_CHAR(TIMEDIFF(''HOUR'', LEAST(MINUEND::TIME,SUBTRAHEND::TIME), GREATEST(MINUEND::TIME, SUBTRAHEND::TIME)),''FM00''),''-'',''''),
           ''DAY TO MINUTE'',    CASE WHEN SUBTRAHEND>MINUEND THEN ''-'' ELSE '''' END || REPLACE(TO_VARCHAR(TRUNC(DATEDIFF(SECONDS, SUBTRAHEND, MINUEND)/(86400))) || '' '' || TO_CHAR(TRUNC(MOD((DATEDIFF(''SECOND'', SUBTRAHEND, MINUEND)),86400)/3600),''FM00'') || '':'' || TO_CHAR(TRUNC(MOD((DATEDIFF(''SECOND'', SUBTRAHEND, MINUEND)),3600)/60),''FM00''),''-'',''''),
           ''DAY TO SECOND'',    CASE WHEN SUBTRAHEND>MINUEND THEN ''-'' ELSE '''' END || REPLACE(TO_VARCHAR(TRUNC(DATEDIFF(SECONDS, SUBTRAHEND, MINUEND)/(86400))) || '' '' || TO_CHAR(TRUNC(MOD((DATEDIFF(''SECOND'', SUBTRAHEND, MINUEND)),86400)/3600),''FM00'') || '':'' || TO_CHAR(TRUNC(MOD((DATEDIFF(''SECOND'', SUBTRAHEND, MINUEND)),3600)/60),''FM00'') || '':''|| TO_CHAR((DATEDIFF(''MILLISECOND'', SUBTRAHEND, MINUEND)/1000)%60,''FM00.000000''),''-'',''''),
           ''HOUR'',             TO_VARCHAR(DATEDIFF(HOUR, SUBTRAHEND, MINUEND)),
           ''HOUR TO MINUTE'',   TO_CHAR(TRUNC((DATEDIFF(''SECOND'', SUBTRAHEND, MINUEND))/3600),''FM99999999999999999999999999999999'') || '':'' ||  REPLACE(TO_CHAR(TRUNC(MOD((DATEDIFF(''SECOND'', SUBTRAHEND, MINUEND)),3600)/60),''FM00''),''-'','''') ,
           ''HOUR TO SECOND'',   TO_CHAR(TRUNC((DATEDIFF(''SECOND'', SUBTRAHEND, MINUEND))/3600),''FM99999999999999999999999999999999'') || '':'' ||  REPLACE(TO_CHAR(TRUNC(MOD((DATEDIFF(''SECOND'', SUBTRAHEND, MINUEND)),3600)/60),''FM00''),''-'','''') || '':'' || REPLACE(TO_CHAR((DATEDIFF(''MILLISECOND'', SUBTRAHEND, MINUEND)/1000)%60,''FM00.000000''),''-'',''''),
           ''MINUTE'',           TO_VARCHAR(DATEDIFF(MINUTE, SUBTRAHEND, MINUEND)),
           ''MINUTE TO SECOND'', TO_CHAR(TRUNC((DATEDIFF(''SECOND'', SUBTRAHEND, MINUEND))/60),''FM99999999999999999999999999999999'') || '':'' || REPLACE(TO_CHAR((DATEDIFF(''MILLISECOND'', SUBTRAHEND, MINUEND)/1000)%60,''FM00.000000''),''-'',''''),
           ''SECOND'',           TO_CHAR((DATEDIFF(''MILLISECOND'', SUBTRAHEND, MINUEND)/1000)%60,''FM99999999999999999999999999999999.000000'')
            )
';