-- Object Type: FUNCTIONS
CREATE OR REPLACE FUNCTION ALFA_EDW_DEV.PUBLIC.TIME_DIFFERENCE_UDF("MINUEND" TIME(9), "SUBTRAHEND" TIME(9), "INPUT_PART" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
IMMUTABLE
COMMENT='{ \"origin\": \"sf_sc\", \"name\": \"snowconvert\", \"version\": {  \"major\": 1,  \"minor\": 7,  \"patch\": \"1.0\" }, \"attributes\": {  \"component\": \"udf\",  \"convertedOn\": \"06/04/2025\",  \"domain\": \"alfains\" }}'
AS '
DECODE(INPUT_PART,
        ''HOUR'',   CASE WHEN HOUR(MINUEND) <= HOUR(SUBTRAHEND) 
                    THEN TO_VARCHAR( HOUR(SUBTRAHEND) - HOUR(MINUEND)           , ''FM9900'')
                    ELSE TO_VARCHAR( 24-ABS(HOUR(MINUEND) - HOUR(SUBTRAHEND))   , ''FM9900'') END,
        ''MINUTE'', CASE WHEN HOUR(MINUEND) < HOUR(SUBTRAHEND) 
                    THEN TO_VARCHAR( CASE  WHEN  MINUTE(MINUEND)>MINUTE(SUBTRAHEND)  THEN  (HOUR(SUBTRAHEND) - HOUR(MINUEND)) - 1             ELSE  HOUR(SUBTRAHEND) - HOUR(MINUEND)            END, ''FM9900'')
                    ELSE TO_VARCHAR( CASE  WHEN  MINUTE(MINUEND)>MINUTE(SUBTRAHEND)  THEN  (24-ABS(HOUR(MINUEND) - HOUR(SUBTRAHEND))) - 1     ELSE  24-ABS(HOUR(MINUEND) - HOUR(SUBTRAHEND))    END, ''FM9900'')
                    END  || '':'' ||
                  CASE WHEN MINUTE(MINUEND) <= MINUTE(SUBTRAHEND)
                    THEN TO_VARCHAR( MINUTE(SUBTRAHEND) - MINUTE(MINUEND)          , ''FM9900'')
                    ELSE TO_VARCHAR( 60 - ABS(MINUTE(MINUEND) - MINUTE(SUBTRAHEND)), ''FM9900'') END,
        ''SECOND'', CASE WHEN HOUR(MINUEND) <= HOUR(SUBTRAHEND)
                    THEN TO_VARCHAR( CASE WHEN MINUTE(MINUEND) > MINUTE(SUBTRAHEND)  THEN  (HOUR(SUBTRAHEND) - HOUR(MINUEND)) - 1             ELSE  HOUR(SUBTRAHEND) - HOUR(MINUEND)            END, ''FM9900'')
                    ELSE TO_VARCHAR( CASE WHEN MINUTE(MINUEND) > MINUTE(SUBTRAHEND)  THEN  (24-ABS(HOUR(MINUEND) - HOUR(SUBTRAHEND))) - 1     ELSE  24-ABS(HOUR(MINUEND) - HOUR(SUBTRAHEND))    END, ''FM9900'')
                    END || '':'' ||
                  CASE WHEN MINUTE(MINUEND) <= MINUTE(SUBTRAHEND) 
                    THEN TO_VARCHAR( CASE WHEN SECOND(MINUEND) > SECOND(SUBTRAHEND)  THEN  (MINUTE(SUBTRAHEND) - MINUTE(MINUEND)) - 1         ELSE  MINUTE(SUBTRAHEND) - MINUTE(MINUEND)        END, ''FM9900'')
                    ELSE TO_VARCHAR( CASE WHEN SECOND(MINUEND) > SECOND(SUBTRAHEND)  THEN  (60 - (MINUTE(MINUEND) - MINUTE(SUBTRAHEND))) - 1  ELSE  60 - (MINUTE(MINUEND) - MINUTE(SUBTRAHEND)) END, ''FM9900'')
                    END || '':'' ||
                  CASE WHEN SECOND(MINUEND) <= SECOND(SUBTRAHEND)
                    THEN TO_VARCHAR( SECOND(SUBTRAHEND) - SECOND(MINUEND),         ''FM9900'')
                    ELSE TO_VARCHAR( 60 - (SECOND(MINUEND) - SECOND(SUBTRAHEND)),  ''FM9900'')
                    END
      )
';