-- Object Type: TASKS
create or replace task ALFA_EDW_DEV.PUBLIC.WF_STG_TO_DW_CLAIMS_DLY__S_M_CLMF_CLM_SURVEY_LETTER_CORE_AUTO
	warehouse=COMPUTE_WH
	after ALFA_EDW_DEV.PUBLIC.WF_STG_TO_DW_CLAIMS_DLY__S_M_CLMF_CLAIM_CORE_WC
	as CALL public.m_CLMF_CLM_SURVEY_LETTER_CORE_AUTO('wf_STG_TO_DW_CLAIMS_DLY');