-- Object Type: TASKS
-- Level: L3, ExecOrder: 68

create or replace task ALFA_EDW_DEV.PUBLIC.WF_STG_TO_DW_CLAIMS_DLY__S_M_CLMF_CLAIM_CORE_HO
	warehouse=COMPUTE_WH
	after ALFA_EDW_DEV.PUBLIC.WF_STG_TO_DW_CLAIMS_DLY__S_M_CLMF_CLAIM_CORE_AUTO
	as CALL public.m_CLMF_CLAIM_CORE_HO('wf_STG_TO_DW_CLAIMS_DLY');