-- Object Type: TASKS
-- Level: L4, ExecOrder: 69

create or replace task ALFA_EDW_DEV.PUBLIC.WF_STG_TO_DW_CLAIMS_DLY__S_M_CLMF_CLAIM_CORE_WC
	warehouse=COMPUTE_WH
	after ALFA_EDW_DEV.PUBLIC.WF_STG_TO_DW_CLAIMS_DLY__S_M_CLMF_CLAIM_CORE_HO
	as CALL public.m_CLMF_CLAIM_CORE_WC('wf_STG_TO_DW_CLAIMS_DLY');