-- Object Type: TASKS
-- Level: L6, ExecOrder: 233

create or replace task ALFA_EDW_DEV.PUBLIC.WKLT_BASE_PRIORLOSS_CLMPMT_INSUPD__CONTROL_CLEANUP
	warehouse=COMPUTE_WH
	after ALFA_EDW_DEV.PUBLIC.WKLT_BASE_PRIORLOSS_CLMPMT_INSUPD__S_M_JOB_FAILURE, ALFA_EDW_DEV.PUBLIC.WKLT_BASE_PRIORLOSS_CLMPMT_INSUPD__S_M_JOB_SUCCESS
	as CALL sp_control_cleanup('wklt_base_priorloss_clmpmt_insupd', TRUE);