-- Object Type: TASKS
-- Level: L8, ExecOrder: 73

create or replace task ALFA_EDW_DEV.PUBLIC.WF_STG_TO_DW_CLAIMS_DLY__S_M_CLMF_CLM_LOSS_RESERVE_AUTO
	warehouse=COMPUTE_WH
	after ALFA_EDW_DEV.PUBLIC.WF_STG_TO_DW_CLAIMS_DLY__S_M_CLMF_CLM_SURVEY_LETTER_CORE_WC
	as SELECT 1;