-- Object Type: TASKS
-- Level: L9, ExecOrder: 74

create or replace task ALFA_EDW_DEV.PUBLIC.WF_STG_TO_DW_CLAIMS_DLY__S_M_CLMF_CLM_LOSS_RESERVE_WC
	warehouse=COMPUTE_WH
	after ALFA_EDW_DEV.PUBLIC.WF_STG_TO_DW_CLAIMS_DLY__S_M_CLMF_CLM_LOSS_RESERVE_AUTO
	as CALL public.m_CLMF_CLM_LOSS_RESERVE_WC('wf_STG_TO_DW_CLAIMS_DLY');