-- Object Type: TASKS
-- Level: L10, ExecOrder: 75

create or replace task ALFA_EDW_DEV.PUBLIC.WF_STG_TO_DW_CLAIMS_DLY__S_M_CLMF_CLM_LOSS_RESERVE_HO
	warehouse=COMPUTE_WH
	after ALFA_EDW_DEV.PUBLIC.WF_STG_TO_DW_CLAIMS_DLY__S_M_CLMF_CLM_LOSS_RESERVE_WC
	as CALL public.m_CLMF_CLM_LOSS_RESERVE_HO('wf_STG_TO_DW_CLAIMS_DLY');